### ISSUE TITLE
CircularNotchedRectangle() is not working in BottomAppBar() !

### ISSUE THREAD

**Issue by PrabeshPP** [flutter/flutter#94009]
The CircularNotchedRectangle() is only seen when opening an app for the first time. However, after doing back and forth the notch will no longer
![sc21](https://user-images.githubusercontent.com/83439329/142822582-cdcab9ca-b97e-4fd4-a5bc-15570029276b.jpg)
![sc211](https://user-images.githubusercontent.com/83439329/142822598-50a40ac8-179c-4cd2-800f-1b4a6a83e84e.jpg)
 get displayed on the cart page.

**Comment by danagbemava-nc** [comment]
Hi @PrabeshPP, thanks for filing the issue. 

Please provide the output of `flutter doctor -v` and also, please post the code sample here instead of posting a screenshot. 

Thank you

**Comment by PrabeshPP** [comment]
Hi @danagbemava-nc !
Here is the output for flutter doctor -v:

`[√] Flutter (Channel dev, 2.6.0-11.0.pre, on Microsoft Windows [Version 10.0.22000.318], locale en-US)
    • Flutter version 2.6.0-11.0.pre at C:\Users\prabe\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4b330ddbed (10 weeks ago), 2021-09-16 17:29:58 -0700
    • Engine revision 5b81c6d615
    • Dart version 2.15.0 (build 2.15.0-116.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\prabe\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.62.3)
    • VS Code at C:\Users\prabe\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.28.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.45
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 95.0.1020.53

• No issues found!`

**Comment by danagbemava-nc** [comment]
Hi @PrabeshPP, I can reproduce this on `dev` and `stable`  but I cannot reproduce on `beta` and `master`. 
As such I believe the issue is fixed. 
Kindly check either the `beta`/`master` branch to see if you can still reproduce this.

```
flutter channel beta/master
flutter upgrade --force
```

<details>
<summary>sample used</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
        scrollbarTheme: ScrollbarThemeData(
          thickness: MaterialStateProperty.all<double>(3),
          thumbColor: MaterialStateProperty.all(Colors.blue),
          trackColor: MaterialStateProperty.all(Colors.pink),
        ),
      ),
      home: const HomeScreen(),
    );
  }
}

class HomeScreen extends StatelessWidget {
  const HomeScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Home'),
      ),
      body: Center(
        child: TextButton(
          onPressed: () {
            Navigator.push(
              context,
              MaterialPageRoute(builder: (context) => CartPage()),
            );
          },
          child: Text('Click Me'),
        ),
      ),
    );
  }
}

class CartPage extends StatelessWidget {
  const CartPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Cart'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: const <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          Navigator.pop(context);
        },
        child: const Icon(Icons.arrow_back),
      ),
      floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,
      bottomNavigationBar: BottomAppBar(
        color: Colors.blue,
        notchMargin: 5,
        shape: const CircularNotchedRectangle(),
        child: SizedBox(
          height: 42,
        ),
      ),
    );
  }
}

```
</details>
