### ISSUE TITLE
Unable to detect Landscape for iOS 15

### ISSUE THREAD

**Issue by lukeirvin** [flutter/flutter#94004]
I've been having trouble getting orientation information on my iOS 15 iPhone. I've run various example projects and some seem to work but when trying to test out code I don't see any changes.

Just testing `MediaQuery.of(context).orientation` ALWAYS returns `Orientation.portraitUp` even when I turn my device to Landscape Left or Right. 

I've also tested with `NativeDeviceOrientationReader` & `VisibilityDetector` but both have the same results.

I can only get different orientations if I manually set them via a button action, etc.

My goal is to use a button action & to dynamically update it when rotation my device.

This works as expected on Android, just not on iPhone.

Any suggestions?

**Comment by danagbemava-nc** [comment]
Hi @lukeirvin, thanks for filing the issue.

Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Thank you

**Comment by lukeirvin** [comment]
Here is my `flutter doctor -v`:

[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale en-US)
    • Flutter version 2.5.3 at /Users/lukeirvin/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (5 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/lukeirvin/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.55

• No issues found!

**Comment by danagbemava-nc** [comment]
Please provide a complete minimal reproducible code sample as well. 

Thank you
