### ISSUE TITLE
Material DatePicker does not return the expected date...

### ISSUE THREAD

**Issue by cmeuser** [flutter/flutter#94001]
The material DatePicker loses or does not cary forward the selected day when changing the year.  Additionally, the dialog permits the user to select okay when the UI is in an inconsistent state returning an unexpected date.

## Steps to Reproduce
Launch the datepicker by calling showDatePicker with an initial date of Nov 21, 2021.
User selects the year drop down, and selects 2022.  (Note that the UI does not cary forward or loses the selected day when changing the year)
Select okay. The date returned is Nov 21, 2021.

This is unexpected and confusing, changing the year should not require the user to reselect the 21st again.  Then allowing the user to select okay and return Nov 21, 2021 is unexpected.  I'm not sure if this is a bug or by design but I would recommend if the user changes the year either cary forward the day or disable the "okay" button requiring the user to select a day.  
 

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Datepicker Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Datepicker Demo'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  DateTime? selectedDate;

  @override
  Widget build(BuildContext context) {
    
    final dateString = selectedDate == null ? '' : DateFormat('yyyy-MM-dd').format(selectedDate!);

    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'Selected Date: $dateString',
            ),
            TextButton(
              onPressed: () async {
                var date = await showDatePicker(
                  context: context,
                  initialDate: DateTime.now(),
                  firstDate: DateTime.now().subtract(const Duration(days: 365)),
                  lastDate: DateTime.now().add(const Duration(days: 365)),
                );
                setState(() {
                  selectedDate = date;
                });
              },
              child: const Text('Select Date'),
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @cmeuser, this issue is being tracked in https://github.com/flutter/flutter/issues/81547. 

Kindly follow up there for more information. 

Closing as duplicate. 

If you disagree, kindly leave a comment below and I will reopen. 

Thank you
