### ISSUE TITLE
Problem with hot reload in real device specifically Vivo phones

### ISSUE THREAD

**Issue by samsapi01** [flutter/flutter#94006]
I am developing in flutter since a year,I user vs code and no issues with hot reload on real device other than Vivo.
I have seen multiple issues with the same title on stackoverflow and github and then sumhow it worked for them but for vivo phones the hot reload doesn't work. I have checked flutter doctor, flutter clean, Real device hard reset, Laptop os installation nothing works. I have checked installing on mac as well, same issue !!!

**Comment by danagbemava-nc** [comment]
Hi @samsapi01, what do you see in your console when you try to hot-reload?

**Comment by samsapi01** [comment]
Hi, @danagbemava-nc I see below text in the console and it doen't progress further.

/FlutterActivityAndFragmentDelegate(13845): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
I/flutter (13845): Observatory listening on ************************************


after waiting for long time I see
Error waiting for a debug connection: The log reader stopped unexpectedly
Error launching application on vivo 1920.

**Comment by danagbemava-nc** [comment]
Hi @samsapi01, yes a lot of Vivo users have been reporting the same thing. 
That issue is known and is being tracked https://github.com/flutter/flutter/issues/82520.

Kindly follow up there for more information. 

Closing as duplicate from here. 

Thank you
