### ISSUE TITLE
[webview_flutter] android crash

### ISSUE THREAD

**Issue by yoferzhang** [flutter/flutter#94014]
```
    java.lang.NullPointerException: Attempt to read from field 'android.view.WindowManager$LayoutParams android.view.ViewRootImpl.mWindowAttributes' on a null object reference
        at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1818)
        at android.view.inputmethod.InputMethodManager.checkFocus(InputMethodManager.java:2074)
        at android.view.inputmethod.InputMethodManager.isActive(InputMethodManager.java:1322)
        at io.flutter.plugins.webviewflutter.InputAwareWebView$1.run(InputAwareWebView.java:188)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8668)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
```

**Comment by danagbemava-nc** [comment]
Hi @yoferzhang, 

Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Also, specify which version of `webview_flutter` and concrete steps to reproduce. 

Thank you

**Comment by nalnir** [comment]
I had a similar issue with `webview_flutter: ^2.3.1`. The page would show on on initial load but than when I would Hot Restart and get to WebView component it would crash with the same error.

I was using WebView in Stateless Widget without this piece of code:
```
@override
  void initState() {
    super.initState();
    if (Platform.isAndroid) WebView.platform = SurfaceAndroidWebView();
  }
``` 

This solved it for me. Can you check if you have this implemented and if not can you please try it and let us know if it works?

Full code:
```
class WebViewComponent extends StatefulWidget {
  final String url;
  WebViewComponent({
    Key? key,
    required this.url,
  });

  @override
  _WebViewComponentState createState() => _WebViewComponentState();
}

class _WebViewComponentState extends State<WebViewComponent> {
  @override
  Widget build(BuildContext context) {
    final Completer<WebViewController> webViewController = Completer<WebViewController>();

    @override
    void initState() {
      super.initState();
      if (Platform.isAndroid) WebView.platform = SurfaceAndroidWebView();
    }

    return WebView(
      initialUrl: widget.url,
      javascriptMode: JavascriptMode.unrestricted,
      onWebViewCreated: (WebViewController controller) {
        webViewController.complete(controller);
      },
      onProgress: (int progress) {
         print('Page loading');
      },
      onPageStarted: (String url) {
        print('Page started loading: $url');
      },
      onPageFinished: (String url) {
        print('Page finished loading: $url');
      },
      gestureRecognizers: Set()..add(Factory<VerticalDragGestureRecognizer>(() => VerticalDragGestureRecognizer())),
      gestureNavigationEnabled: true,
    );
  }
}
```

**Comment by nalnir** [comment]
> I had a similar issue with `webview_flutter: ^2.3.1`. The page would show on on initial load but than when I would Hot Restart and get to WebView component it would crash with the same error.
> 
> I was using WebView in Stateless Widget without this piece of code:
> 
> ```
> @override
>   void initState() {
>     super.initState();
>     if (Platform.isAndroid) WebView.platform = SurfaceAndroidWebView();
>   }
> ```
> 
> So instead I transformed it into StateFull Widget and added the missing code. This solved it for me. Can you check if you have this implemented and if not can you please try it and let us know if it works?
> 
> Full code:
> 
> ```
> class WebViewComponent extends StatefulWidget {
>   final String url;
>   WebViewComponent({
>     Key? key,
>     required this.url,
>   });
> 
>   @override
>   _WebViewComponentState createState() => _WebViewComponentState();
> }
> 
> class _WebViewComponentState extends State<WebViewComponent> {
>   @override
>   Widget build(BuildContext context) {
>     final Completer<WebViewController> webViewController = Completer<WebViewController>();
> 
>     @override
>     void initState() {
>       super.initState();
>       if (Platform.isAndroid) WebView.platform = SurfaceAndroidWebView();
>     }
> 
>     return WebView(
>       initialUrl: widget.url,
>       javascriptMode: JavascriptMode.unrestricted,
>       onWebViewCreated: (WebViewController controller) {
>         webViewController.complete(controller);
>       },
>       onProgress: (int progress) {
>          print('Page loading');
>       },
>       onPageStarted: (String url) {
>         print('Page started loading: $url');
>       },
>       onPageFinished: (String url) {
>         print('Page finished loading: $url');
>       },
>       gestureRecognizers: Set()..add(Factory<VerticalDragGestureRecognizer>(() => VerticalDragGestureRecognizer())),
>       gestureNavigationEnabled: true,
>     );
>   }
> }
> ```

Unfortunately, the error keeps popping up for me still even after the change. It's quite inconsistent in when it happens but it's still happening. So please disregard my suggestion above is it may not be helpful in this instance.
