### ISSUE TITLE
[iOS]  When UiKitView views inside ListView, I can't scroll ListView with Gesture

### ISSUE THREAD

**Issue by maruipp** [flutter/flutter#94017]
I use UiKitView to embed UIImageView in Flutter ListView , After that the ListView can't be scrolled use gesture.
here is my reproducable demo: git@gitlab.com:AaronMa/gesture_conflict.git

**Comment by maruipp** [comment]
$ flutter doctor --verbose
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.0.1 21A559 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 2.2.3 at /Users/maruipeng/development/flutter
    • Framework revision f4abaa0735 (5 个月前), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/maruipeng/Library/Android/sdk
    • Platform android-31, build-tools 30.0.2
    • ANDROID_HOME = /Users/maruipeng/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

**Comment by mamuseferha** [comment]
Hi @maruipp looks like you're using an older version of flutter, can you please upgrade to the latest stable version? 

If the issue persists, please provide your updated `flutter doctor -v`, your `flutter run --verbose` and a minimal reproducible code sample. I am unable to open the reproducible demo you provided.

Also, please confirm if issue is similar to this https://github.com/flutter/flutter/issues/57702
Thank you

**Comment by maruipp** [comment]
> $ flutter doctor --verbose
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.5.3 at /Users/maruipeng/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (6 周前), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/maruipeng/Library/Android/sdk
    • Platform android-31, build-tools 30.0.2
    • ANDROID_HOME = /Users/maruipeng/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • mm (mobile)     • 00008101-001D49EE3E04001E • ios            • iOS 14.4 18D52
    • macOS (desktop) • macos                     • darwin-x64     • macOS 12.0.1 21A559 darwin-x64
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 96.0.4664.55

• No issues found!

**Comment by maruipp** [comment]
[flutter run --verbose](https://github.com/flutter/flutter/files/7587748/runlog.log)

**Comment by maruipp** [comment]
Hi, mamuseferha,thanks for your response.

I have readed the #57702, unfortunately they are not similar.
I upgrade to the latest stable version, and the issue is still there.
You said my demo can't be open, do you mean that it can't be run ? Maybe it is because my drag and drop plugin is only available for iPad.
I use hitTestBehavior property in UiKitView class, which has a definition: PlatformViewHitTestBehavior.translucent,it is documented that:  Translucent targets both receive events within their bounds and permit targets visually behind them to also receive events. I think it not work as expected.  It seem like when i pan the picture area, my ListView can't be scroll, I think the reason is ListView didn't get gesture.

**Comment by mamuseferha** [comment]
@maruipp, can you provide a demo that does not include an external plugin so I can isolate the issue to the flutter framework? `dragable_image_view` is an external plugin.

**Comment by quetool** [comment]
@mamuseferha I think it's related with this one https://github.com/flutter/flutter/issues/45510

**Comment by maruipp** [comment]
my fault. It works perfect now after change gestureRecognizers parameter.
grateful for your response @mamuseferha
