### ISSUE TITLE
Error: XMLHttpRequest error. C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 908:28  

### ISSUE THREAD

**Issue by ritunjaykumar** [flutter/flutter#94010]
**while, i am run the flutter web application in google chrome with following code..**
```
final String _baseUrl = "http://172.16.10.170:8080";
Future<dynamic> sigInAdmin() async {
    final Uri adminSignInUrl = Uri.parse('$_baseUrl/test');
    final response = await get(adminSignInUrl);
    print('status code: ${response.statusCode}');
    print('body: ${response.body}');
    return response;
  }
```

- given url is working fine in browser.

> 
> so i am getting following error: 
> Error: XMLHttpRequest error.
>     C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 908:28                get current
> packages/http/src/browser_client.dart 69:22                                                                                    <fn>
> C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1687:54                                              runUnary
> C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 160:18                                        handleValue
> C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 767:44                                        handleValueCallback
> C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 796:13                                        _propagateToListeners
> C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 593:7                                         [_complete]
> C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/stream_pipe.dart 61:11                                         _cancelAndValue
> C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/stream.dart 1232:7                                             <fn>
> C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 334:14  _checkAndCall
> C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 339:39  dcall
> C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/html/dart2js/html_dart2js.dart 37332:58                              <fn>
> 
> 
>     at Object.createErrorWithStack (http://localhost:56964/dart_sdk.js:5074:12)
>     at Object._rethrow (http://localhost:56964/dart_sdk.js:38925:16)
>     at async._AsyncCallbackEntry.new.callback (http://localhost:56964/dart_sdk.js:38921:13)
>     at Object._microtaskLoop (http://localhost:56964/dart_sdk.js:38778:13)
>     at _startMicrotaskLoop (http://localhost:56964/dart_sdk.js:38784:13)
>     at http://localhost:56964/dart_sdk.js:34519:9

**Comment by PrabeshPP** [comment]
is that URL right?

**Comment by ritunjaykumar** [comment]
> is that URL right?

yes

**Comment by danagbemava-nc** [comment]
HI @ritunjaykumar, thanks for filing the issue. 

Please provide a complete minimal reproducible code sample as well as the output of `flutter doctor -v`.

Thank you

**Comment by ritunjaykumar** [comment]
### flutter doctor -v

Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19042.1348], locale en-IN)
    • Flutter version 2.5.3 at C:\Users\ritunjay\flutter_windows_2.5.3-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (7 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\ritunjay\AppData\Local\Android\Sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = C:\Users\ritunjay\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.61.2)
    • VS Code at C:\Users\ritunjay\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 96.0.4664.45
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 96.0.1054.34

• No issues found!



### browser console output
Access to XMLHttpRequest at 'http://172.16.10.170:8080/admin/signin' from origin 'http://localhost:57083' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**for back-end  i am using spring boot**

**Comment by danagbemava-nc** [comment]
Hi @ritunjaykumar, you appear to be hitting a `CORS` error which is an error thrown by the browser itself. 
There isn't much flutter can do about that.

This issue has been reported on the chrome issue tracker and it has been labelled as a `wont fix`. 
https://bugs.chromium.org/p/chromium/issues/detail?id=67743
https://stackoverflow.com/questions/10883211/why-does-my-http-localhost-cors-origin-not-work

Kindly configure your server to allow `CORS`. 

Closing as this is beyond the scope of flutter. 

Thank you
