### ISSUE TITLE
[webview_benchmarks] Update new Frame Names

### ISSUE THREAD

**Issue by amanv8060** [flutter/flutter#94027]
In chromium release (89) : https://github.com/chromium/chromium/commit/1e884fcf6e908f42de2300f71e817025f24f1d64

WebFrameWidgetBase and WebFrameWidgetImpl were merged into WebFrameWidgetImpl 

This requires webview_benchmarks to update the event name.

Other features affected by this issue: https://github.com/flutter/gallery/issues/463

**Comment by ditman** [comment]
This should be fixed as of `web_benchmarks: ^0.0.7`.

Thank you very much for your contribution and help @amanv8060!
