### ISSUE TITLE
ClassNotFoundException when running app using flutter run

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#9403]
## Steps to Reproduce

I frequently get a `ClassNotFoundException` at runtime when running a plugin project using `flutter run`. The problem goes away after I `flutter build clean` then `flutter run` again.

## Logs

```
04-14 14:34:08.431 24576 24576 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "io.flutter.firebase_analytics_example.MainActivity" on path: DexPathList[[zip file "/data/app/io.flutter.firebase_analytics_example-1/base.apk"],nativeLibraryDirectories=[/data/app/io.flutter.firebase_analytics_example-1/lib/arm, /data/app/io.flutter.firebase_analytics_example-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
04-14 14:34:08.431 24576 24576 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
04-14 14:34:08.431 24576 24576 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
04-14 14:34:08.431 24576 24576 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
04-14 14:34:08.431 24576 24576 E AndroidRuntime: 	at android.app.Instrumentation.newActivity(Instrumentation.java:1067)
04-14 14:34:08.431 24576 24576 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2317)
04-14 14:34:08.431 24576 24576 E AndroidRuntime: 	... 9 more
04-14 14:34:08.431 24576 24576 E AndroidRuntime: 	Suppressed: java.lang.ClassNotFoundException: io.flutter.firebase_analytics_example.MainActivity
04-14 14:34:08.431 24576 24576 E AndroidRuntime: 		at java.lang.Class.classForName(Native Method)
04-14 14:34:08.431 24576 24576 E AndroidRuntime: 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
04-14 14:34:08.431 24576 24576 E AndroidRuntime: 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
04-14 14:34:08.431 24576 24576 E AndroidRuntime: 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
04-14 14:34:08.431 24576 24576 E AndroidRuntime: 		... 12 more
04-14 14:34:08.431 24576 24576 E AndroidRuntime: 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

## Flutter doctor

```
[✓] Flutter (on Mac OS X 10.12.3 16D32, channel master)
    • Flutter at /Users/yjbanov/code/flutter/flutter
    • Framework revision a5593b1678 (4 days ago), 2017-04-10 14:20:47 -0700
    • Engine revision 5d9a642257
    • Tools Dart version 1.23.0-dev.11.6

[✓] Host Executable Compatibility
    • Downloaded executables execute on host

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/yjbanov/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • ANDROID_HOME = /Users/yjbanov/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.1, Build version 8E1000a
    • ios-deploy 1.9.0
    • CocoaPods version 1.2.0

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[-] IntelliJ IDEA Community Edition (version 2016.3.4)
    • Dart plugin version 163.13137
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/managing-plugins.html

[✓] Connected devices
    • Nexus 5 • 06c8a457006b2f2d • android-arm • Android 6.0.1 (API 23)
```

/cc @jakobr-google @szakarias

**Comment by yjbanov** [comment]
It looks like the location of `MainActivity.java` was indeed busted. I'm not sure why the app sometimes works though. The fix is https://github.com/flutter/firebase_analytics/pull/5

**Comment by yjbanov** [comment]
@NewITCorp yeah, that repo got merged into https://github.com/flutter/plugins/tree/master/packages/firebase_analytics

**Comment by cwichoski** [comment]
Hi @yjbanov , I got same message using firebase in a project, but always occurs the crash, and I cant go ahead with flutter firebase current version, can you remember what you changed in that fix for me to have a change to investigate what happens in my case?

**Comment by cwichoski** [comment]
I found the issue after inspecting .dex files, the ClassNotFoundException occured in my case, because class MainActivity at android folder, was in a different package than the one I specified in AndroidManifest.xml, now everything works, then I correct the android MainActivity class with correct package and worked.

**Comment by tiago-meurer** [comment]
> 
> 
> I found the issue after inspecting `.dex` files, the `ClassNotFoundException` occurred in my case, because `class MainActivity` at `android` folder, was in a different package than the one I specified in `AndroidManifest.xml`, now everything works, then I correct the android `MainActivity` class with correct package and worked.

Worked with me! Thanks, Sir.

**Comment by Mapk26** [comment]
> > I found the issue after inspecting `.dex` files, the `ClassNotFoundException` occurred in my case, because `class MainActivity` at `android` folder, was in a different package than the one I specified in `AndroidManifest.xml`, now everything works, then I correct the android `MainActivity` class with correct package and worked.
> 
> Worked with me! Thanks, Sir.

Could you explain what you changed and where? 
Thanks

**Comment by melvinm99** [comment]
Same error for me: : I get this error when trying to login with both Facebook and Google. Email login instead is working (I'm using Firebase)

**Comment by melvinm99** [comment]
I could solve it only creating a new flutter project and copying libs and assets

**Comment by cheekbyname** [comment]
> Could you explain what you changed and where?
> Thanks

In my case it was MainActivity.kt under android/app/src/main/kotlin which was still on package com.example.myprojectname

**Comment by bsutton** [comment]
I had three problems.
1) as per @cheekbyname my default language was kotlin and I was looking for a java file.
2) the package declaration in MainActivity.kt don't match the package path the file lived in.
3) the AndroidManifest.xml 'package=' statement had a package name that didn't match the location of the the MainActivity.kt.

**Comment by Beyga** [comment]
In my case the issue was that MainActivity.java was in folder android/app/src/java. I have created the package folder android/app/src/java/{package_name} and put the MainActivity.java file inside this package. That solved the problem.

**Comment by ianmistr** [comment]
> I had three problems.
> 
> 1. as per @cheekbyname my default language was kotlin and I was looking for a java file.
> 2. the package declaration in MainActivity.kt don't match the package path the file lived in.
> 3. the AndroidManifest.xml 'package=' statement had a package name that didn't match the location of the the MainActivity.kt.

How did you solve it?

**Comment by usavas** [comment]
@ianmistr You need to rename each folder in the path to the MainActivity.kt file accordingly, then run flutter clean && flutter run. In my case it only worked after a clean build.
