### ISSUE TITLE
Generating synthetic localizations package failed with 1 error:  Exception: The 'template-arb-file', LocalFile: 'E:\FlutterDevelopment\pro\holiday\lib/l10n\app_en.arb', is not readable. Please ensure that the user has read permissions.

### ISSUE THREAD

**Issue by rddewan** [flutter/flutter#94044]
## Steps to Reproduce

```console
E:\FlutterDevelopment\pro\holiday>flutter run
Generating synthetic localizations package failed with 1 error:

Exception: The 'template-arb-file', LocalFile: 'E:\FlutterDevelopment\pro\holiday\lib/l10n\app_en.arb', is not readable.
Please ensure that the user has read permissions.
```
l10n.yaml

```
arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
```
Unable to run the app and generate localizations file . I have follow the sample doc  https://docs.flutter.dev/development/accessibility-and-localization/internationalization

**Comment by maheshmnj** [comment]
Hi @rddewan,  Thanks for filing the issue. Please share your `flutter doctor -v` and the complete error logs. The issue seems to be related to permissions please also try changing the location of your project.

Thanks

**Comment by rddewan** [comment]
@maheshmnj  Below is the log file. I have full permission on the file path it's located E:\FlutterDevelopment\pro\holiday
E:\FlutterDevelopment\pro\holiday>flutter doctor -v
╔════════════════════════════════════════════════════════════════════════════╗
║ A new version of Flutter is available!                                     ║
║                                                                            ║
║ To update to the latest version, run "flutter upgrade".                    ║
╚════════════════════════════════════════════════════════════════════════════╝


[√] Flutter (Channel stable, 2.5.2, on Microsoft Windows [Version 10.0.19042.1348], locale en-US)
    • Flutter version 2.5.2 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (8 weeks ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at E:\AppData\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android-studio-2020.3.1.9
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[!] Android Studio (version 4.2)
    • Android Studio at C:\Program Files\Android\Android Studio 4.2 Beta5
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[√] IntelliJ IDEA Ultimate Edition (version 2020.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2020.1.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.62.3)
    • VS Code at C:\Users\Richard\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.28.0

[√] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 11 (API 30) (emulator)
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 96.0.4664.45
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 96.0.1054.29

! Doctor found issues in 2 categories.

E:\FlutterDevelopment\pro\holiday>

**Comment by maheshmnj** [comment]
Hi @rddewan, I verified on `stable 2.5.3` and I could not reproduce the issue the app does run and generate localization files. Can you please try running this [sample app](https://github.com/flutter/flutter/files/7623452/hello_world.zip)and see if it generated the files. If you still face the same issue with this app please try upgrading to `stable 2.5.3` by running 
`flutter upgrade`.


<details>
<summary>flutter doctor -v</summary>

```
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19042.1348], locale en-US)
    • Flutter version 2.5.3 at C:\flutter_sdk\stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (6 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\mahesh\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java      
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)    
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)  
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)        

[√] VS Code (version 1.61.2)
    • VS Code at C:\Users\mahesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.28.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.1348]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 96.0.4664.45
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 95.0.1020.44

• No issues found!
```
</details>
