### ISSUE TITLE
Devicelab staging ios bots are failing on certs issue in dismiss dialogs

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#94068]
Related to https://github.com/flutter/flutter/issues/93605

https://ci.chromium.org/p/flutter/g/devicelab_staging/console shows all purple

**Comment by godofredoc** [comment]
The cert failing are a consequence of invalid certificates. These bot should be quarantined but salt has not run on them to get the latest device doctor.

**Comment by godofredoc** [comment]
This is affecting mac-4 and mac-10

**Comment by godofredoc** [comment]
ok those machines were disconnected from salt, add them back.

**Comment by godofredoc** [comment]
Salt states are now fixed. It also required an update of salt minion to 3002.7
