### ISSUE TITLE
[Proposal] flutter/engine GN build files for fuchsia integration tests should be simplified

### ISSUE THREAD

**Issue by richkadel** [flutter/flutter#94065]
Recommendation: Consider implementing a flutter_app()-equivalent template that would hide the complexities and redundancies, and provide a central place for work around existing build limitations, such as the target name collisions.

BUILD.gn files for Dart-based Fuchsia packages, in the flutter/engine repo, are a bit brittle, and more complicated than the single flutter_app() target in the original BUILD.gn files from fuchsia.git. (Note that the flutter_app() template is deprecated, and flutter_component() is recommended; but something similar to flutter_app() may still be worthwhile, to simplify build file generation.)

See parent-view2/BUILD.gn for example.

The BUILD.gn file constructs the final test package in stages: the dart_library(), wrapped in a flutter_component(), wrapped in a fuchsia_package(). These three template definitions generate their own intermediate targets, and due to the way the templates are implemented, it’s easy to end up with a name collision when two templates try to generate two targets with the same name, in the same scope (this BUILD.gn file’s scope).

I think this is a limitation of the current implementation of fuchsia_component() in the Fuchsia GN SDK.
See the TODO comment in parent-view2 (linked above), and child-view2 and at least one other Dart-based fuchsia build target in flutter/engine with the same structure (//flutter/shell/platform/fuchsia/dart-pkg/zircon/test/BUILD.gn).

**Comment by arbreng** [comment]
We are tracking this in monorail.  closing this.
