### ISSUE TITLE
image_picker plugin freezes when uploading a huge bitmap file

### ISSUE THREAD

**Issue by ctrance** [flutter/flutter#94073]
Our app is getting stuck on uploading a huge 39.6 MB bitmap file (dimensions 3040 x 4560) when using the image_picker plugin.

**Comment by danagbemava-nc** [comment]
Hi @ctrance, thanks for filing the issue. 

Please provide a complete minimal reproducible code sample, a sample image you're experiencing the issue with, the version of `image_picker` you're using and the output of `flutter doctor -v`. 

Thank you
