### ISSUE TITLE
Add curated sample code to each Widget class in the dartdocs

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#9407]
Some have it, but many don't.

**Comment by Hixie** [comment]
Also to constructors, like `new EdgeInsets.all()`.

**Comment by abarth** [comment]
We might want to shard out this work.  It's going to be a lot of typing if @Hixie tries to do it all himself.  :)

Suggestion: create a bug tree with groups of widgets and we can assign / work through the bugs.  Maybe do half a dozen first to establish a good pattern for the rest of us to follow.

**Comment by Hixie** [comment]
Yeah that's more or less what i was planning on doing.

**Comment by Hixie** [comment]
Some that I should definitely do: Column, ListView

**Comment by Hixie** [comment]
I've started the trend of doing this for many classes (some of these only once https://github.com/flutter/flutter/pull/10331 lands):

https://docs.flutter.io/flutter/animation/Tween-class.html
https://docs.flutter.io/flutter/material/Card-class.html
https://docs.flutter.io/flutter/material/CheckboxListTile-class.html
https://docs.flutter.io/flutter/widgets/ScrollView-class.html
https://docs.flutter.io/flutter/painting/EdgeInsets-class.html
https://docs.flutter.io/flutter/widgets/Column-class.html
https://docs.flutter.io/flutter/material/IconButton-class.html
...and various others (in total I count 44 cases of "/// ## Sample code" in our code now).

I'm going to close this bug when that PR lands on the basis that the concept is proven, but we should file new bugs on specific classes that require samples, and we should generally continue to add them over time.
