### ISSUE TITLE
Upgrade Mac builders to macOS Big Sur 11.3 or higher

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#94078]
The version of macOS on the builders is too low to upgrade Xcode 13:

https://logs.chromium.org/logs/flutter/led/magder_google.com/dd113c1bbe3d7446736c820c5adcb5ca521bff202009107cdaea5f24df2ecf82/+/u/install_xcode/stdout
```
xcodebuild: error: unable execute utility "/opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/usr/bin/xcodebuild" because it requires a newer version of macOS.
```

https://developer.apple.com/documentation/xcode-release-notes/xcode-13-release-notes
> Xcode 13 requires a Mac running macOS 11.3 or later.

Blocking https://github.com/flutter/flutter/issues/91633 and https://github.com/flutter/flutter/issues/85555

**Comment by jmagman** [comment]
@godofredoc what version are they running now?  If it's not already somewhere I'm missing, printing `sw_vers` as part of a recipe step would be helpful.

**Comment by godofredoc** [comment]
Catalina Mac-10.15.7-19H15. They show up in the os dimension in the pool: https://chromium-swarm.appspot.com/botlist?c=id&c=task&c=os&c=status&d=asc&f=pool%3Aluci.flutter.prod&f=os%3AMac&k=os&s=id

**Comment by jmagman** [comment]
flutter/flutter staging bots have been upgraded.  @godofredoc opened a bug to upgrade the engine staging bots https://bugs.chromium.org/p/chromium/issues/detail?id=1274888

**Comment by jmagman** [comment]
Engine staging bots have been upgraded.

**Comment by jmagman** [comment]
Now that https://flutter-review.googlesource.com/c/recipes/+/24944 has merged, I think we're ready to try upgrading the engine builders!  Requires `xcode` and `sdk_version` to be `13a233`, and the cache `runtime_versions` be `[ "ios-13-0" ]`.

`Mac iOS Engine`
https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/magder_google.com/34b0add45b8fe97daadbfb8f634b2426c6fdea1e39c03af96488ca5ff59eb6f2/+/build.proto?server=chromium-swarm.appspot.com

`Mac Unopt` https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/magder_google.com/15ce71ff15e962e13bb340538339f307495e846c6eba7ec007621015430e011f/+/build.proto

`Mac Web Engine` 
https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/magder_google.com/9a0597c302a0ba1bf2edb738c803dbdcad105f47a13c5eec62f43f3a5e92cf16/+/build.proto?server=chromium-swarm.appspot.com

**Comment by godofredoc** [comment]
This will be Mac OS 12.2

**Comment by jmagman** [comment]
Currently blocked by https://github.com/flutter/flutter/issues/98278, need to upgrade Chrome to be reliable on newer version of macOS.

**Comment by jmagman** [comment]
Framework tests are now running on macOS 12, now to the engine builders.  I believe that is blocked on allowing Xcode to be upgraded with different iOS simulator runtimes https://github.com/flutter/flutter/issues/91689

**Comment by jmagman** [comment]
As of https://github.com/flutter/engine/pull/31915 most of the engine builders are now running on macOS 12.  However the Mac Web Engine tests are still running on 10.15 due to https://github.com/flutter/flutter/issues/99885.
We also need to leave some capacity for release builds.

**Comment by godofredoc** [comment]
@jmagman I believe this is complete, can we close it?
