### ISSUE TITLE
Flutter web: Debugger does not stop at breakpoints in async code

### ISSUE THREAD

**Issue by Wissperwind** [flutter/flutter#94095]
Hi,

Version:  Channel master, 2.6.0-12.0.pre.790, on Microsoft Windows

I try to find an error in my code. Some NullPointerException.

```
VoidCallback onSendPressed = () async {

      print("send pressed");

      //---Create http package multipart request object
      var request = http.MultipartRequest(
        "POST",
        Uri.parse("http://127.0.0.1:8000/backend/upload"),
      );

      print(TokenStorage.myToken!);

      Map<String, String> headers = {
        //'content-type': 'application/json',
        //'accept': 'application/json',
        'Authorization': TokenStorage.myToken!
      };
      request.headers.addAll(headers);

      //-----add other fields if needed
      request.fields["id"] = "abc";

      List<PlatformFile>? files = fileUploadView.result?.files;
      for (PlatformFile file in files!) {
        //-----add selected file with request
        request.files.add(http.MultipartFile(
            "Your parameter name on server side", file.readStream!,
            file.size,
            filename: file.name));
      }

      //-------Send request
      var resp = await request.send();

      //------Read response
      String result = await resp.stream.bytesToString();

      //-------Your response
      print(result);

    };
```

I set breakpoints at the first two prints. But the debbugger simply runs through them. The prints were executed. The debugger stopps at some random point in exception handling. But that does not help since flutter unfortunetly does not say in an exception where in my dart code the error occoured.

**Comment by Wissperwind** [comment]
by the way file.readStream is null. Thats the problem of the code. But not the problem of this issue.

**Comment by Wissperwind** [comment]
It is not in general the problem, that the debugger does not stop in async code.
It just not stopps on breakpoints where "in the future will be a nullpointer exception".
Sounds strange, but that exactly is the case.

**Comment by maheshmnj** [comment]
Hi @Wissperwind, I tried running the basic counter app in vscode on the web and I was able to add breakpoints and the app paused at the breakpoints. Could you please share a minimal and complete reproducible code along with the steps to reproduce the issue. Also, which IDE are you using?

**Comment by Wissperwind** [comment]
I used Android Studio. Today it is not reproducible on my machine. Maybe a god thing...
Sorry, there was defenetly this error and I was not able to find the error by using the debugger.
