### ISSUE TITLE
[add_to_app][iOS] FlutterViewController never calls `dealloc` after upgrading to `flutter 2.5.3`

### ISSUE THREAD

**Issue by yuoao86** [flutter/flutter#94099]
<details>
<summary>flutter doctor -v</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on Mac OS X 10.15.5 19F101 darwin-x64,
    locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.
[!] Xcode - develop for iOS and macOS
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] Connected device (3 available)
```
</details>

**Comment by danagbemava-nc** [comment]
Hi @yuoao86, thanks for filing the issue. 

Please provide a complete minimal reproducible code sample and what your expectations vs actual results are.

Also, provide clear steps to reproduce. 

Thank you

**Comment by yuoao86** [comment]
ZGFLutterViewController.h
`#import <Flutter/Flutter.h>
NS_ASSUME_NONNULL_BEGIN

@interface ZGFlutterViewController : FlutterViewController

@end

NS_ASSUME_NONNULL_END`

ZGFlutterViewController.m
`
@interface ZGFlutterViewController ()
@property(strong) WifiCameraPlugin *wifiCameraPlugin;
@end

@implementation ZGFlutterViewController

- (instancetype)initWithProject:(FlutterDartProject *)project initialRoute:(NSString *)initialRoute nibName:(NSString *)nibName bundle:(NSBundle *)nibBundle{
    self = [super initWithProject:project  initialRoute:initialRoute nibName:nibName bundle:nibBundle];
    if (self) {
        [self registerPlugin];
    }
    return self;
}
-(void)registerPlugin{
}

@end
`
ZGFlutterViewController *vc = [[ZGFlutterViewController alloc] initWithProject:nil initialRoute:@"myRoute" nibName:nil bundle:nil];
self.navigationController?.pushViewController(vc, animated: true)

My project is the add_to_app project,IOS platform when invoke SystemNavigator.pop(animated: true) in dart to return native, dealloc never be call.
before upgrade to flutter 2.5.3 is no this problem.

**Comment by yuoao86** [comment]
> Hi @yuoao86, thanks for filing the issue.
> 
> Please provide a complete minimal reproducible code sample and what your expectations vs actual results are.
> 
> Also, provide clear steps to reproduce and what platform this issue is on.
> 
> Thank you



> Hi @yuoao86, thanks for filing the issue.
> 
> Please provide a complete minimal reproducible code sample and what your expectations vs actual results are.
> 
> Also, provide clear steps to reproduce and what platform this issue is on.
> 
> Thank you

ZGFLutterViewController.h
#import <Flutter/Flutter.h>
NS_ASSUME_NONNULL_BEGIN

@interface ZGFlutterViewController : FlutterViewController

@EnD

NS_ASSUME_NONNULL_END


ZGFlutterViewController.m

@interface ZGFlutterViewController ()
@Property(strong) WifiCameraPlugin *wifiCameraPlugin;
@EnD

@implementation ZGFlutterViewController

(instancetype)initWithProject:(FlutterDartProject *)project initialRoute:(NSString *)initialRoute nibName:(NSString *)nibName bundle:(NSBundle *)nibBundle{
self = [super initWithProject:project initialRoute:initialRoute nibName:nibName bundle:nibBundle];
if (self) {
[self registerPlugin];
}
return self;
}
-(void)registerPlugin{
}
@EnD


ZGFlutterViewController *vc = [[ZGFlutterViewController alloc] initWithProject:nil initialRoute:@"myRoute" nibName:nil bundle:nil];
self.navigationController?.pushViewController(vc, animated: true)

My project is the add_to_app project,IOS platform when invoke SystemNavigator.pop(animated: true) in dart to return native, dealloc never be call.
before upgrade to flutter 2.5.3 is no this problem.

**Comment by danagbemava-nc** [comment]
Hi @yuoao86, unfortunately, your sample doesn't give me much to work with as I'm not particularly familiar with native iOS. 

If possible, kindly provide a minimal reproducible code sample in a repo that I can clone and run to verify the behavior you're 
experiencing. 

Thank you

**Comment by yuoao86** [comment]
> Hi @yuoao86, unfortunately, your sample doesn't give me much to work with as I'm not particularly familiar with native iOS.
> 
> If possible, kindly provide a minimal reproducible code sample in a repo that I can clone and run to verify the behavior you're experiencing.
> 
> Thank you

Thank you  @danagbemava-nc ,I've solved the problem.

FlutterEngine *flutterEngine = [[FlutterEngine alloc] init];
[flutterEngine runWithEntrypoint:nil initialRoute:initialRoute];
self = [super initWithEngine:flutterEngine nibName:nibName bundle:nibBundle];

to replace

self = [super initWithProject:project initialRoute:initialRoute nibName:nibName bundle:nibBundle];

FlutterViewController run well,the dealloc method can be call.

**Comment by danagbemava-nc** [comment]
Given your last comment, I feel it is safe to close the issue. 

Closing as solved. 

Thank you
