### ISSUE TITLE
flutter engine compile

### ISSUE THREAD

**Issue by rickren0** [flutter/flutter#94093]
1. How can i compile libflutter_engine.so for arm64 android.
2. I compiled libflutter_engine.so for arm64 linux. When i use it in arm64 android ,some errors occurred.

**Comment by maheshmnj** [comment]
Hi @rickren0 Please ask discussion and "How to" questions on one of the communities at https://flutter.dev/community, Closing as this issue doesn't describe a bug nor a feature request.

Thanks

**Comment by rickren0** [comment]
I compile the flutter engine like this:
./flutter/tools/gn --embedder-for-target --target-os android --runtime-mode release --android-cpu arm64 --arm-float-abi hard

ninja -C out/android_release_arm64

but some error occurred :
ninja: Entering directory `out/android_release_arm64'
[1/4] SOLINK ./libflutter_engine.so
FAILED: libflutter_engine.so libflutter_engine.so.TOC lib.stripped/libflutter_engine.so 
../../buildtools/linux-x64/clang/bin/clang++ -shared -Wl,--fatal-warnings -fPIC -Wl,-z,noexecstack -Wl,-z,now -Wl,-z,relro -Wl,-z,defs --gcc-toolchain=../../third_party/android_tools/ndk/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64 -Wl,--no-undefined -Wl,--exclude-libs,ALL -fuse-ld=lld -Wl,--icf=all --target=aarch64-linux-android -nostdlib++ -nostdlib -L/home/rick/workspace/flutter/engine/src/third_party/android_tools/ndk/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/22  -Wl,-O2 -Wl,--gc-sections -Wl,--as-needed -flto -L../../third_party/android_tools/ndk/sources/cxx-stl/llvm-libc++/libs/arm64-v8a  -o ./libflutter_engine.so -Wl,--build-id=sha1 -Wl,-soname=libflutter_engine.so @./libflutter_engine.so.rsp && { ../../third_party/android_tools/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-readelf -d ./libflutter_engine.so | grep SONAME ; ../../third_party/android_tools/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-nm -gD -f posix ./libflutter_engine.so | cut -f1-2 -d' '; } > ./libflutter_engine.so.tmp && if ! cmp -s ./libflutter_engine.so.tmp ./libflutter_engine.so.TOC; then mv ./libflutter_engine.so.tmp ./libflutter_engine.so.TOC; fi && ../../third_party/android_tools/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-strip --strip-unneeded -o lib.stripped/libflutter_engine.so.tmp libflutter_engine.so && if ! cmp -s lib.stripped/libflutter_engine.so.tmp lib.stripped/libflutter_engine.so; then mv lib.stripped/libflutter_engine.so.tmp lib.stripped/libflutter_engine.so; fi
ld.lld: error: undefined symbol: _binary_icudtl_dat_start
>>> referenced by memory:3003 (../../third_party/libcxx/include/memory:3003)
>>>               lto.tmp:(GetICUStaticMapping())
>>> referenced by memory:3003 (../../third_party/libcxx/include/memory:3003)
>>>               lto.tmp:(GetICUStaticMapping())

ld.lld: error: undefined symbol: _binary_icudtl_dat_end
>>> referenced by memory:3003 (../../third_party/libcxx/include/memory:3003)
>>>               lto.tmp:(GetICUStaticMapping())
>>> referenced by memory:3003 (../../third_party/libcxx/include/memory:3003)
>>>               lto.tmp:(GetICUStaticMapping())
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

What should I do to solve the problem?
