### ISSUE TITLE
best way to initialize MethodChannel in  FlutterPlugin?

### ISSUE THREAD

**Issue by hello-soon** [flutter/flutter#94105]
FlutterPlugin has onAttachedToEngine, onAttachedToActivity

Which is the best way to initialize the MethodChannel? 
------------------------
{
      this. channel = new MethodChannel()
     this. channel.setMethodCallHandler()
}

put it in onAttachedToEngine?
or
put it in onAttachedToActivity?

**Comment by stuartmorgan** [comment]
Please use one of the resources at https://flutter.dev/community#community-grid for general questions and discussion.

Closing as this is neither a feature request nor a bug report.
