### ISSUE TITLE
[Web]: Dark mode map style in `google_maps_flutter_web`

### ISSUE THREAD

**Issue by bambinoua** [flutter/flutter#94103]
We have a problem to set map style in dark mode. The setting of map style is executed in
```dart
GoogleMap(
  onMapCreated: (GoogleMapController controller) {
    final mapStyle = Theme.of(context).brightness == Brighness.dark ? darkModeStyleJson : lightModeStyleJson;
    controller.setMapStyle(mapStyle);
    mapController.complete(controller);
  }
)
```
When `GoogleMap` widget is rendered in dark mode than first it shown as light and then become dark. So it flickers. Is it possible to add property `mapStyle` for `GoogleMap` widget as it done for `mapType` parameter?

**Comment by mamuseferha** [comment]
Hi @bambinoua 
I see there's an open issue addressing the case you described https://github.com/flutter/flutter/issues/61317.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
