### ISSUE TITLE
Shader warm up takes too much start up time

### ISSUE THREAD

**Issue by youssefali424** [flutter/flutter#94106]
## Details

1.  issue happens on a fresh install of the app and the first start of the app, subsequent starts are faster,
    the issue is so obvious on iPad specifically , it got rejected from apple due to start up time as well,
    so is this normal warm up shader time ? this is a profile run but it happens with release as well.

3.  
**Target Platform: iOS 
**Target OS version/browser: 15.0
**Devices: iPad 15.0.1, iPhone 6 12.0, 

## Logs
![shader_warmup_time](https://user-images.githubusercontent.com/38167511/143025604-3c32cf9f-003e-4e33-b237-98fdf8f7bb9c.jpeg)

```flutter (Channel stable, 2.5.3, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 2.5.3 at /Users/yosefaly/Desktop/flutter_sdks/flutter1.22.6
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (6 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/yosefaly/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run path/to/sdkmanager --install "cmdline-tools;latest"
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run flutter doctor --android-licenses to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.11.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      :hammer: https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      :hammer: https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Users/yosefaly/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (1 available)
    • iPhone (mobile) • 995dff8bee53cf1e8beffdd58ce2f2e6c192e341 • ios • iOS 12.0 16A366

! Doctor found issues in 2 categories.
```

</details>

**Comment by maheshmnj** [comment]
Hi @youssefali424, Can you please share any reproducible code sample for us to have a look?
 (preferably a complete project with minimal code).
 
 Thanks

**Comment by youssefali424** [comment]
I really couldn't put my hand on something specific I know how hard it is to debug it as well, but would a project with a multiple packages and the key io.flutter.embedded_views_preview = true added to info.plist would affect the shader warm up and the flutter pipeline ? cuz the pipeline actually took much time, specially on iPad, 
I don't want to make assumptions and at the sam time I made sure that once the main method was called the didn't need more than like 4 to 5 sec load that is for first load, so when the app takes like 15 to 20 secs sometimes and each time I debugged it through profile flutter initialization, pipeline and shader warm up took around 10 ~ 14 sec 
until I am sure what is causing the issue I can't share any reproducible code, the only one I am guaranteed to happen on was a project that had flutter 1.22 and was upgraded , it's commercial code that I can't share now.
all the demos I tried to create to share with you doesn't always show the same issue, all I got that tends to happen when we use multiple packages in the app even if they aren't used in dart code (like flutterfire, google ads... etc)

**Comment by maheshmnj** [comment]
Thanks for the info @youssefali424,
Can you please share the timeline trace by running your app with `--trace-skia` you can follow the complete steps mentioned here https://github.com/flutter/flutter/issues/74833#issue-795394794

Additionally, You might want to take a look at this https://docs.flutter.dev/perf/rendering/shader

**Comment by youssefali424** [comment]
yeah I looked into this issue, the app did have janks before while it was on 1.22 and it had more bugs and issues, after fixing most of the issues i had to upgrade to a newer version of flutter, and everything is actually better, except the first start of the app after directly being installed, after much tracing I came to find that the pipeline took too much time, and shader warm up as well, 

it happens only on ios, especially on iPads (on iPhone 12 this isn't so apparent), on Android it's super-fast, and has no shader warm-up.

 i couldn't replicate the same numbers on a new project but I saw the issue the more i add libraries to the created project the more it takes to do shader warm-up on the first open, and once you add some code to the project like waiting for firebase init, it becomes so obvious.
 
and I was sure all the profiling time for shader warm-up or pipelines happened before even calling main method, so somehow it is irrelevant to the code itself rather to the project size and packages used.

**Comment by maheshmnj** [comment]
thanks for the info @youssefali424, In order for this issue to be actionable we would need at least the sample code or the timeline trace of the app that has issue.

> Can you please share the timeline trace by running your app with --trace-skia you can follow the complete steps mentioned here #74833 (comment)
