### ISSUE TITLE
[web] iOS 15 does not load/rendering issues

### ISSUE THREAD

**Issue by vixez** [flutter/flutter#94111]
## Steps to Reproduce

A lot of our users have issues opening our Flutter app on Safari. This might be related to this [issue](https://github.com/flutter/flutter/issues/93404).

On iPad the web version does not run at all, or has severe rendering issues.
In the JavaScript console there are no errors.

Our build command:
`flutter build web --dart-define=SENTRY_RELEASE=$SENTRY_RELEASE -t lib/$FLAVOR_ENTRYPOINT --release --source-maps --web-renderer canvaskit`

On Chrome (desktop) this issue does not seem to happen.
![Screenshot 2021-11-23 at 15 58 01](https://user-images.githubusercontent.com/3032294/143058405-dc77401b-f3a7-4e73-988d-1e6de9d0bc98.png)

**Comment by danagbemava-nc** [comment]
Hi @vixez, thanks for filing the issue. 

Please provide the output of `flutter doctor -v` and a complete minimal reproducible code sample. 

Thank you

**Comment by vixez** [comment]
```
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.5.2 20G95 darwin-x64, locale en-GB)
    • Flutter version 2.5.3 at /Users/glennruysschaert/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (6 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/glennruysschaert/Library/Android/sdk
    • Platform android-31, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • GM1913 (mobile) • 2b00d10b • android-arm64  • Android 11 (API 30)
    • macOS (desktop) • macos    • darwin-x64     • macOS 11.5.2 20G95 darwin-x64
    • Chrome (web)    • chrome   • web-javascript • Google Chrome 96.0.4664.55

• No issues found!
```

I cannot provide an example as this is company owned code.

**Comment by danagbemava-nc** [comment]
Hi @vixez, can you check if this issue is similar to yours?

If it is, can you check if any of the workarounds in there work for you?

https://github.com/flutter/flutter/issues/89655

**Comment by vixez** [comment]
Hello @danagbemava-nc 

I tried the solution but it did not work.
However I did find something else.

If I remove `--web-renderer canvaskit` from the build command, it does work on my iPad (with some lag).
So it seems that rendereris the source of the issue.

**Comment by danagbemava-nc** [comment]
> If I remove `--web-renderer canvaskit` from the build command, it does work on my iPad (with some lag).

Several people reported issues with canvaskit applications on `iOS 15` before the beta became stable. If you don't specify a renderer it defaults to `auto` which I believe should use the `html` renderer on mobile devices and tablets. 

Can you check on the `master` channel to see if you still experience this issue?

**Comment by vixez** [comment]
Hello @danagbemava-nc ,
When I switch to the master channel and build with
`flutter build web -t lib/main-customer_production_store.dart  --release --source-maps --web-renderer canvaskit`

I can confirm it works on my iPad (iPad Air 4tth Gen, iOS 15.1) on Safari.

**Comment by danagbemava-nc** [comment]
Then the issue has been fixed. 

A fix should rollout to stable in the future. I would also recommend you check out the beta channel to see if the issue is fixed over there as well, as that channel is more stable than master. 

Given https://github.com/flutter/flutter/issues/94111#issuecomment-984448921, I feel it is safe to close as fixed. 

If you still experience this issue, kindly leave a comment below with the output of `flutter doctor -v`, thank you
