### ISSUE TITLE
NotificationListener has very minimal docs

### ISSUE THREAD

**Issue by eseidel** [flutter/flutter#9412]
I think I want to use NotificationListener to listen for the onChanged of my dependent TextField and then rebuild my search results, but the docs don't really help me figure that out currently:
https://docs.flutter.io/flutter/widgets/NotificationListener-class.html

This is also just me trying to fix https://github.com/flutter/flutter/issues/9395 myself. :)

**Comment by eseidel** [comment]
Hmmm, I think NotificationListener isn't really what I'm looking for, but I suspect this bug is still valid that it needs more docs. :)

**Comment by abarth** [comment]
Yeah, it doesn't do that.  This bug would be helped if Notification listed its subclasses, which is an open dartdoc bug.

**Comment by rxlabz** [comment]
Thanks for mentioning it, I had totally missed this option! A tutorial about components communication could be very helpful in Flutter.io ( parent to child, child to parent, between siblings ) with change/valueNotifier, notification.

**Comment by abarth** [comment]
I'm not sure what you'd like added to the NotificationListener docs.  Please reopen if you have a specific request.
