### ISSUE TITLE
Dead links in devicelab docs

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#94132]
A lot of the links in https://github.com/flutter/flutter/tree/master/dev/devicelab#adding-tests-to-continuous-integration and the following sections are going to a 404 error page and needs updating.

**Comment by CaseyHillers** [comment]
I have https://github.com/flutter/flutter/pull/93684 out to fix this (indirectly). It's blocked on the infra code freeze this week, and should be ready to land next week.
