### ISSUE TITLE
[Web] Android textfield selection shows two handles and sometimes subsequently changes selection by one character

### ISSUE THREAD

**Issue by zambetpentru** [flutter/flutter#94130]
Hi,

I noticed that on Android Web that there are often two Selection handles (?) when trying to Select text. I also note on occasion that there is a text offset (i.e. it selects a few characters away from where I am pressing, but I don't have a clear repo yet for that one - but one case is tapping around I can see it then move one character to the left).

I am able to replicate this on a Galaxy S20 with the latest (and older) versions of Chrome and Opera using the following link: https://gallery.flutter.dev/#/demo/text-field and in my own project on Flutter-2.4-candidate-2 and Flutter-2.8-candidate.6.

Image1             |  Image2 |   Image3     |  Image4.   
:-------------------------:|:-------------------------:|:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/81489824/143136831-3cccbd21-5ed1-485d-b99e-f805f1b56e63.png) | ![image](https://user-images.githubusercontent.com/81489824/143136845-124af61b-aa67-4816-a866-c2095ce09830.png) | ![image](https://user-images.githubusercontent.com/81489824/143136856-ff36e46f-1ad5-47ce-9be8-146cd6452138.png) | ![image](https://user-images.githubusercontent.com/81489824/143136872-d54c2180-c93f-47e9-89ab-7d352d8cf847.png)

**Comment by maheshmnj** [comment]
Hi, @zambetpentru, Thanks for filing the issue. I am able to reproduce the issue looking at the cursor handle's thumb it looks like there are two handles overlapping each other. This is reproducible on both the stable and the master channel on Android. It's worth noting that this is only reproducible on the web and not in a flutter app.



Flutter gallery             |  Deployed flutter app
:-------------------------:|:-------------------------:
![flutter_01](https://user-images.githubusercontent.com/31410839/143398295-0cf17839-6b0a-43ab-b98e-bd98611be0ad.png) | ![flutter_01](https://user-images.githubusercontent.com/31410839/143398402-db334b04-f17b-4a24-a3dc-197abccec86f.png)

deployed app: https://textfield.netlify.app/ 



<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.5.3 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (6 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.0.1 21A559 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 96.0.4664.55

• No issues found!
```

```
[✓] Flutter (Channel master, 2.6.0-12.0.pre.789, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.6.0-12.0.pre.789 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6ae721de3d (3 days ago), 2021-11-21 15:22:37 -0500
    • Engine revision ad00d12833
    • Dart version 2.16.0 (build 2.16.0-35.0.dev)
    • DevTools version 2.8.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.0.1 21A559 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 96.0.4664.55

• No issues found!
```
</details>

**Comment by mdebbar** [comment]
Similar to https://github.com/flutter/flutter/issues/70841

**Comment by TimWhiting** [comment]
I've looked into css styles, and it doesn't seem to be possible to remove the native handle. It seems more apparent with fonts with different spacing. The flutter handle seems to be spaced correctly, whereas the native handle sometimes is in the middle of a character. Could it be that the font that flutter is using to paint is not the same as the one on the native input / textarea, or the font properties are not set right?

**Comment by squaregen** [comment]
Any news or any workaround?

**Comment by wl1395182472** [comment]
so there is no evolve about this?

**Comment by wl1395182472** [comment]
what is the temporary treatment about this?

**Comment by htoor3** [comment]
Is this still occurring? I tried reproducing this with a Pixel 5 (simulator) and Pixel 6 (real device) and I'm unable to see the overlapping handles. I tried on both gallery.flutter.dev and textfield.netlify.app

**Comment by zambetpentru** [comment]
Hi,  I can't seem to reproduce it now :-)

**Comment by htoor3** [comment]
@zambetpentru thank you for checking! If you come across this issue again, feel free to reopen this
