### ISSUE TITLE
[Proposal] Add Default position of ListView/ScrollView and other Scrollable widgets

### ISSUE THREAD

**Issue by eli1stark** [flutter/flutter#94143]
## Use case
1. You have a huge array of items that for example are lazily built with ListView.builder and you need to start your ListView at the bottom. In order to do that you need to use `scrollController.jumpTo(scrollController.position.maxScrollExtent);` which takes time to perform (depends on the expansiveness of widgets) but it's visible to an eye that ListView is scrolling, the goal is to make it just start from the bottom. The second workaround to this problem is you can provide `ScrollController(initialScrollOffset: position)` before building ListView which requires you to calculate how much all widgets take place in the ListView by yourself and then provide it to the constructor. There are 2 problems in the second workaround: 1) It's not always known how much space widgets will occupy 2) Even if we successfully calculate this and provide the needed position to the ListView it will build all widgets in order to get to the bottom, this hurts performance if you have expensive widgets in ListView.
2. The are lots of use cases in real life: like chats, calendars, and other stuff that is based on chronological ordering.

## Proposal
Proposal is to add a new optional argument to ListView that will be called `defaultPosition`.

This will be an enum:
```dart
enum DefaultScrollPosition{start, bottom}
```

Full example:
```dart
ListView(
  defaultPosition: DefaultScrollPosition.bottom,
  children: []
);
```
The example above is expected to build only the visible part of ListView at the bottom. The same way it works right now when it starts at the start. And when I scroll from the bottom to the top it will gradually build new widgets as they appear on the screen the same way it works now but in reverse.

* This feature is expected to support all types of scrollable widgets, like ListView, ListView.builder, CustomScrollView, and so on.

**Comment by eli1stark** [comment]
There is a good workaround to this problem by adding a reverse parameter to ListView and setting it to true and reversing your array of widgets. This workaround solves the problem if you will always default to bottom or start but in cases where you can have a dynamic starting position (I mean it can be either start or end) then the problem still persists.

```dart
ListView(
  reverse: true,
  children: [
    for (final element in arrayOfWidgets.reveresed.toList()) 
      element
  ]
);
```

**Comment by goderbauer** [comment]
> This workaround solves the problem if you will always default to bottom or start but in cases where you can have a dynamic starting position (I mean it can be either start or end) then the problem still persists.

Can you elaborate on what you mean by this? You can dynamically switch `reverse` from true to false and vice versa at runtime if needed.

**Comment by eli1stark** [comment]
Yes, but I mean that you also need to reverse your data every time when you need to switch the starting position, and makes you think more about manipulating the data than the position of your ListView. And it looks like hacks below.
```dart
ListView(
  reverse: isStart,
  children: [
    for (final i in isStart ? array : array.reversed) SomeWidget(i: i),
  ],
),
```
And generally, you can have 4 cases, depending on your specific situation
 ```dart
/// 1 -> 100
final array = List.generate(100, (i) => i + 1);

// if you need to start from 1 and the start position
return ListView(
  children: [for (final i in array) MyText(i: i)],
);
// if you need to start from 1 and the bottom position
return ListView(
  reverse: true,
  children: [for (final i in array) MyText(i: i)],
);
// if you need to start from 100 and the start position
return ListView(
  children: [for (final i in array.reversed) MyText(i: i)],
);
// if you need to start from 100 and the bottom position
return ListView(
  reverse: true,
  children: [for (final i in array.reversed) MyText(i: i)],
);
```
Why not make the `reverse` parameter be about the data your ListView holds, and the `defaultPosition` about your starting position when ListView builds? What do you think?

**Comment by robert-bitguild** [comment]
Hey, Check at [FlutterListView](https://pub.dev/packages/flutter_list_view). It resolve your issue
```dart
FlutterListView(
    delegate: FlutterListViewDelegate(
        (BuildContext context, int index) => Container(
              color: Colors.white,
              child:
                  ListTile(title: Text('List Item ${data[index]}')),
            ),
        childCount: data.length,
        initIndex: 50,
        initOffset: 0,
        initOffsetBasedOnBottom: false))
```
I guess you are writing chat app. The package also give your full chat feature support

**Comment by AnthonyAniobi** [comment]
I think building a very large list using the defualt `ListView` class is not memory efficient.
you should use the `ListView.builder` instead. This is because it builds only the widget whose index are in view.
Also. rearranging a list is also not very efficient both in time and space complexity, `ListView.builder` also helps you here because you get the items by their index, and this is a constant time operation.

The solution to this your problem using the listview builder would 
```dart
int item_length; // length of your very long list
List very_long_list; // your long list of items

ListView.builder(
    reverse: true,
    itemCount: item_length,
    itemBuilder: (context, index)=>Text(
        '${very_long_list[item_length-index]}'
    ))
)
```

**Comment by Piinks** [comment]
This is already possible using ScrollController.initialScrollOffset, and/r combinations of reverse and AxisDirection.

> ```
> ListView(
>  reverse: true,
>  children: [
>    for (final element in arrayOfWidgets.reveresed.toList()) 
>      element
>  ]
>);
>```

I don't think this is necessary either, you can just access the children on demand in reverse using ListView.builder as pointed out in the comment above this.

There already exists a lot of different ways to described scrolling directions (ScrollDirection, AxisDirection, GrowthDirection - we actually just landed a lot of docs and samples on this!), and since this is already supported, I do not think there is anything else to resolve here so I am closing this issue.

Thanks for contributing!
