### ISSUE TITLE
Flutter Fire web hosting documentation improvement request

### ISSUE THREAD

**Issue by nyck33** [flutter/flutter#94141]
https://firebase.flutter.dev/docs/installation/web/ is very sparse.
There are many many steps missing like what happens between `firebase init` and `firebase deploy` so users have to read blogs which are poorly written with typos at crucial points like designating `build/web` as the public folder being given as `build web` or one blog that says, "point to folder index.html`.  
This is disappointing to say the least to get stuck at this last point after I have Firebase auth working locally on mobile and web and to know that Flutter team seems to be relying on outsiders to write blogs to fill in the gaps.  `https://coupon-firebase.web.app` is my 
assigned url and my output through the init process below:
```
What do you want to use as your public directory? build/web
? Configure as a single-page app (rewrite all urls to /index.html)? Yes
? Set up automatic builds and deploys with GitHub? No
? File build/web/index.html already exists. Overwrite? No
i  Skipping write of build/web/index.html

i  Writing configuration info to firebase.json...
i  Writing project information to .firebaserc...

✔  Firebase initialization complete!
nobu@nobu-IdeaPad-3-15IIL05:/media/nobu/NTFSUbuWin/1_TAP/_Github/coupon_app_versions/coupon_app$ firebase deploy

=== Deploying to 'coupon-firebase'...

i  deploying hosting
i  hosting[coupon-firebase]: beginning deploy...
i  hosting[coupon-firebase]: found 60 files in build/web
✔  hosting[coupon-firebase]: file upload complete
i  hosting[coupon-firebase]: finalizing version...
✔  hosting[coupon-firebase]: version finalized
i  hosting[coupon-firebase]: releasing new version...
✔  hosting[coupon-firebase]: release complete

✔  Deploy complete!

Project Console: https://console.firebase.google.com/project/coupon-firebase/overview
Hosting URL: https://coupon-firebase.web.
```
I just checked and it works now for some unknown reason except above I tried saying "No" to automatic builds and deploys with GIthub.  I'm not sure why saying yes would derail the entire process but please flesh out the documentation to include such potential problems.   If you include something as a feature, please document it perhaps leaning towards overboard rather than not enough.

**Comment by danagbemava-nc** [comment]
Hi @nyck33, issues with `flutterfire` and its documentation should be filed in its dedicated repo.
I can't transfer the issue there as it's in a different org so you'll have to file this issue there. 

Select the `Documentation Feedback` template and please provide your feedback. The team will be glad to hear from you.

https://github.com/FirebaseExtended/flutterfire/issues/new/choose

Closing as this isn't an issue with `flutter` .

Thank you

**Comment by nyck33** [comment]
@danagbemava-nc Yes, please move it, thanks for your time.
