### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by janbentz** [flutter/flutter#94154]
@Michael: There's a bug here when creating a new team. Looks like instead of owner being passed in, NULL is being passed in.

[pillar-messaging-client] lib/ui/views/team/team_creation_viewmodel.dart (Lines 61-71)

```

await _apiService.createTeamMember(owner);
    response.on(
      success: () {
        _eventBusService.eventBus.fire(TeamCreationEvent(owner));
        _actionSuccessful = true;
        result = true;
      },
      orElse: () {
        print(response.message);
        result = false;
      },
```

[Open in IDE](https://api.codestream.com/c/XtLBaymEW0iWLy7D/DG_aG4FuRNa6si_tYft1dw?marker=619e2826292450730902e8e9&ide=default&src=GitHub) · [Open on GitHub](https://github.com/chinola-vine/pillar-messaging-client/blob/6008f7f1a4b14cc3575277beba397ad3e732b1f0/lib/ui/views/team/team_creation_viewmodel.dart#L61-L71)

<sup>Created from VS Code using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=issue&utm_campaign=github)</sup>

**Comment by Azandowski** [comment]
I think you should recheck owner if it is null, try to paste breakpoint

**Comment by maheshmnj** [comment]
Hi @janbentz, As per my understanding you are using a third-party plugin [event_bus](https://pub.dev/packages/event_bus)  Any issues related to that plugin must be filed with the maintainer. Closing as this isn't an issue with flutter, If you disagree feel free to write in the comments and I will reopen it.

Thank You.

**Comment by janbentz** [comment]
Hi I marked it as a bug so my brother and I would resolve it. Didn’t know
that by marking a bug in code stream that it would be sent to anyone
outside of our team
