### ISSUE TITLE
FileSystemException: readSync failed, path = ‘/Users/abcc/StudioProjects/projectname/build/app/outputs/flutter-apk/app-debug.apk’ (OS Error: Invalid argument, errno = 22)

### ISSUE THREAD

**Issue by MuhammamdArslanKhan** [flutter/flutter#94157]
I have an application which generate around 2GB apk, now I am having run time error 
`FileSystemException: readSync failed, path = ‘/Users/abcc/StudioProjects/projectname/build/app/outputs/flutter-apk/app-debug.apk’ (OS Error: Invalid argument, errno = 22)`

Most of the data in application is videos , it has 2.18 GB size of assets folder. I think its size issue. I cannot put data on cloud, it is necessary to put data locally, so what are the limitation , how much I can put data into assets folder , I think my assets will increate to 3GB in future.
```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.3 20E232 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
[✓] VS Code (version 1.61.2)
[✓] Connected device (2 available)

• No issues found!
```
Note: let me know how to tell reproduce because it will only be reproduced if you have that much data in your assets.

**Comment by mamuseferha** [comment]
Hi @MuhammamdArslanKhan can you please run `flutter clean` and then upgrade to the latest stable channel `flutter upgrade` to see if the issue persists?

If the issue persists, please provide your updated `flutter doctor -v`.
