### ISSUE TITLE
[Windows] Can not Instantiate FlutterViewController from plugin project.

### ISSUE THREAD

**Issue by boyan01** [flutter/flutter#94169]
## Steps to Reproduce

1.  create a plugin project `flutter create -t plugin --platform=windows plugin_test`
2.  modify `windows/plugin_test_plugin.cpp` file.
```
void PluginTestPluginRegisterWithRegistrar(
    FlutterDesktopPluginRegistrarRef registrar) {
  PluginTestPlugin::RegisterWithRegistrar(
      flutter::PluginRegistrarManager::GetInstance()
          ->GetRegistrar<flutter::PluginRegistrarWindows>(registrar));

  // insert this code to PluginTestPluginRegisterWithRegistrar method end.
  flutter::DartProject project(L"data");
  auto flutter_controller = std::make_unique<flutter::FlutterViewController>(10, 10, project);
}

```

3. `cd example && flutter run -d windows`

**Expected results:** 

Compile and run.

**Actual results:** 

Build failed with a link error.

```log
Launching lib\main.dart on Windows in debug mode...
plugin_test_plugin.obj : error LNK2019: unresolved external symbol "public: __cdecl flutter::FlutterViewController::FlutterViewController(int,int,class flutter::DartProject const &)" (??0FlutterViewController@flutter@@QEAA@HHAEBVDartProject@1@@Z) referenced in function "class std::unique_ptr<class flutter::FlutterViewController,struct std::default_delete<class flutter::FlutterViewController> > __cdecl std::make_unique<class flutter::FlutterViewController,int,int,class flutter::DartProject &,0>(int &&,int &&,class flutter::DartProject &)" (??$make_unique@VFlutterViewController@flutter@@HHAEAVDartProject@2@$0A@@std@@YA?AV?$unique_ptr@VFlutterViewController@flutter@@U?$default_delete@VFlutterViewController@flutter@@@std@@@0@$$QEAH0AEAVDartProject@flutter@@@Z) [plugin_test\example\build\windows\plugins\plugin_test\plugin_test_plugin.vcxproj]
plugin_test\example\build\windows\plugins\plugin_test\Debug\plugin_test_plugin.dll : fatal error LNK1120: 1 unresolved externals [plugin_test\example\build\windows\plugins\plugin_test\plugin_test_plugin.vcxproj]
Building Windows application...
Exception: Build process failed.
```

```log
Flutter 2.6.0-12.0.pre.828 • channel master • https://github.com/flutter/flutter.git
Framework • revision a2a888ec13 (37 minutes ago) • 2021-11-24 07:53:03 -0800
Engine • revision 539239e256
Tools • Dart 2.16.0 (build 2.16.0-42.0.dev) • DevTools 2.8.0
```

</details>

I am trying create flutter view from plugin on Windows.  And there are also some other functions that can not be called from plugin project.

`FlutterViewController::HandleTopLevelWindowProc()`

`FlutterViewController::engine()`

<details>
  <summary>Logs</summary>

```

```

```
```

```
```

</details>

**Comment by stuartmorgan** [comment]
This is the intended behavior; the plugin template's build file [only links the portions of the client-side wrapper that is relevant for plugin development](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/plugin/windows.tmpl/CMakeLists.txt.tmpl#L18), which [does not include FlutterViewController](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/app_shared/windows.tmpl/flutter/CMakeLists.txt#L36-L78).

As with all plugin development, if you want things in your plugin that aren't part of the template (which is quite common), you need to add them.

**Comment by boyan01** [comment]
oops, I missed this. Thanks , I got it.
