### ISSUE TITLE
Mac_ios platform_interaction_test_ios is failing

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#94162]
The tree is red due to `Mac_ios platform_interaction_test_ios` failure. The failure started after https://github.com/flutter/flutter/pull/94084 landed. Retrying multiple times didn't help.

It looks like it's causing some VM Service commands to timeout?
```
VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:58604/ebzRxB5ZBv8=/
VMServiceFlutterDriver: Isolate found with number: 1114977420153723
VMServiceFlutterDriver: Isolate is paused at start.
VMServiceFlutterDriver: Attempting to resume isolate
VMServiceFlutterDriver: >>> {command: get_health}
fopen failed for data file: errno = 2 (No such file or directory)
Errors found! Invalidating cache...
VMServiceFlutterDriver: <<< {isError: false, response: {status: ok}, type: _extensionType, method: ext.flutter.driver}
VMServiceFlutterDriver: Connected to Flutter application.
00:01  [32m+0 [0m: channel suite step through [0m
VMServiceFlutterDriver: >>> {command: get_text, finderType: ByValueKey, keyValueString: status, keyValueType: String}
fopen failed for data file: errno = 2 (No such file or directory)
Errors found! Invalidating cache...
VMServiceFlutterDriver: <<< {isError: false, response: {text: ok}, type: _extensionType, method: ext.flutter.driver}
VMServiceFlutterDriver: >>> {command: tap, finderType: ByValueKey, keyValueString: step, keyValueType: String}
VMServiceFlutterDriver: <<< {isError: false, response: {}, type: _extensionType, method: ext.flutter.driver}
VMServiceFlutterDriver: >>> {command: get_text, finderType: ByValueKey, keyValueString: status, keyValueType: String}
VMServiceFlutterDriver: get_text message is taking a long time to complete...
```

* https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20platform_interaction_test_ios/2885/overview
* https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20platform_interaction_test_ios/2886/overview
* https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20platform_interaction_test_ios/2887/overview
* https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20platform_interaction_test_ios/2888/overview

cc @jmagman

**Comment by mdebbar** [comment]
Doing one last retry. If it doesn't work, I'll revert the PR to see if that helps.

**Comment by mdebbar** [comment]
The revert is ready at https://github.com/flutter/flutter/pull/94164.

**Comment by mdebbar** [comment]
The retries failed again. Reverted the PR.

**Comment by mdebbar** [comment]
Tree is green again after reverting the PR. So this confirms that the PR was the cause for the failure.

**Comment by cyanglaz** [comment]
cc @jmagman

**Comment by jmagman** [comment]
@mdebbar thanks for reverting!

**Comment by jmagman** [comment]
Closing, I'll make sure this test passes when it re-merges.
