### ISSUE TITLE
[Web] iPad 11" Pro 2021 pencil causes screen to go white upon interaction with Textfield on PWA / Saved to homescreen web app

### ISSUE THREAD

**Issue by zambetpentru** [flutter/flutter#94184]
Hi,

An unusual one, where the Apple pencil tap causes the screen to go white while interacting with a Textfield in a PWA / saved to homescreen Flutter Web application on iPad 11 Pro 2021 in both iPadOS 14 and 15. Not high on my list of concerns but I wanted to raise it for awareness. 

Update: So far in group testing older iPad Pros and iPad Mini 6th Gen do not seem to have this issue.

I have been able to replicate it by: 
1) Open the link https://gallery.flutter.dev/#/demo/text-field 
2) Save to home screen
3) Open the Home screen / PWA app

<img src="https://user-images.githubusercontent.com/81489824/143308766-68917efb-4cb8-47e6-a26a-7d1bb69b9ce8.png" width ="300">

4) Go to the Textfield and tap with the Apple Pencil and the screen goes white

<img src="https://user-images.githubusercontent.com/81489824/143308772-4c5fbeb6-e499-4faa-ae84-e3b859a381f7.png" width ="300">

5) If the virtual keyboard is shown then the widgets will be drawn too.

<img src="https://user-images.githubusercontent.com/81489824/143308780-9ddad858-8605-494b-84ad-97cbf191cb00.png" width ="300">

**Comment by maheshmnj** [comment]
Hi @zambetpentru, Thanks for reporting the issue. Can you please verify if this happens with a newly created flutter app too on the latest `stable 2.5.3`?  And also share the`flutter doctor -v`.

Thanks

**Comment by zambetpentru** [comment]
Hi,

Sorry for the delay in replying, I believe the answer is yes but I will come back to you with confirmation when I have a chance to make a PWA sample app.

**Comment by zambetpentru** [comment]
To confirm, yes it is happening on 2.8 but I haven't had a chance to make a simple repo for it.

**Comment by maheshmnj** [comment]
Thanks for the info will keep this open for further investigation.

**Comment by maheshmnj** [comment]
@zambetpentru My colleague @TahaTesser verified this on ipadOS 15.3

And the issue was not reproducible with the deployed flutter gallery.


https://user-images.githubusercontent.com/31410839/146155055-126ea285-2add-425f-a582-3184e36c0206.mov

**Comment by zambetpentru** [comment]
Interesting! I updated to iPadOS 15.2 (15.3 is not available to me yet it seems) and I can repeat the issue:

Issue:
https://user-images.githubusercontent.com/81489824/146191160-77da3160-f676-4375-9540-42448b01ec8f.mp4

If the keyboard is visible the pencil works:
https://user-images.githubusercontent.com/81489824/146191185-9a61cb5b-b65c-4879-b505-4d8e8f04b126.mp4

**Comment by TahaTesser** [comment]
@zambetpentru 
By mistake, I said `15.3`, my iPad was actually running `15.2`, and the issue is not reproduced. 

iPad 8, 60hz, 2020 model

![Image from iOS](https://user-images.githubusercontent.com/48603081/146206976-4cda877f-ec1a-46c7-9f49-044350262f6c.png)

**Comment by zambetpentru** [comment]
Hi, 

That is strange. I asked a friend who has an older iPad Pro to try and he couldn't replicate the issue either. 

I also note that without using the pen when you hit the scan text button in the input field that the widget disappears, does this happen for you too @TahaTesser ? I don't know if it's intentional or not. 

![photo_2021-12-16_02-25-03](https://user-images.githubusercontent.com/81489824/146368580-7ff37e93-eb99-42ac-8f2f-9d2f1991afa6.jpg)

![photo_2021-12-16_02-25-13](https://user-images.githubusercontent.com/81489824/146368638-58e3fd75-09ac-412a-8f4e-49d0b58056fe.jpg)

To my knowledge I haven't configured anything weird on my iPad Pro, I just had a look and there's not so many settings and they look like the defaults. I have one other friend who has an older iPad in the same region so I'll ask him for another data point.

**Comment by TahaTesser** [comment]
@zambetpentru 
"when I hit the scan text button"

I don't see such button when focusing on a text field even in native iOS apps

**Comment by zambetpentru** [comment]
My friend has it on his older iPad Pro too and on his iPhone:

![photo_2021-12-16_15-39-57](https://user-images.githubusercontent.com/81489824/146409729-fefd122b-7e2f-4593-a034-777e8b5a34fd.jpg)

and the widget doesn't go blank while scanning the test on either his iPad or his iPhone.

**Comment by zambetpentru** [comment]
His iPad Pro 

![photo_2021-12-16_16-26-28](https://user-images.githubusercontent.com/81489824/146410034-4b4fc28e-d150-4a98-b310-900559b214dc.jpg)

**Comment by TahaTesser** [comment]
@zambetpentru 
Got it, still no issue tho
![Image from iOS (1)](https://user-images.githubusercontent.com/48603081/146410396-a84ef75b-2d06-43ff-af6b-33d4fdbafe4e.png)

**Comment by zambetpentru** [comment]
My other friend has a: 

![image](https://user-images.githubusercontent.com/81489824/146420119-60c1bc2c-cca9-4e72-8aa3-c436ca8da5c1.png)

and no issues there either (it would also be the same regional settings). I propose we leave this ticket open for a while and see if someone else comes along with a 2021 iPad Pro with the same issue.

**Comment by justinmc** [comment]
@zambetpentru Looks like we couldn't reproduce this years ago, has this bug ever come up again for you? It looks like no one else has piped up about this bug, maybe we should close it.

**Comment by zambetpentru** [comment]
Greetings! I'm just starting to travel and I don't have my stylus. I will confirm in a few weeks,  last I checked I could still repeat. Now that I am aware of other Flutter apps I will cross check against those as well and let you know what I find.

**Comment by zambetpentru** [comment]
It appears to work perfectly now including scribble support :-)
