### ISSUE TITLE
Problem executing command "pub get" in the flutter

### ISSUE THREAD

**Issue by EnChoopani** [flutter/flutter#94183]
Hello Guys,

I proceeded according to the instructions and installed the flutter completely, then I checked the health of the flutter and everything was absolutely right.

Then I opened the source and I waited for it to be indexed, then I click the "pub get" command and got an error. This image is the same error.

![Problem Image](https://user-images.githubusercontent.com/94993341/143308177-a5d5ac57-a90a-435d-8f28-1102c1f58820.png)

**Comment by EnChoopani** [comment]
@jonasfj Can you help me?

**Comment by mamuseferha** [comment]
Hi @EnChoopani 
Can you please run (making sure you run from your terminal and not from an IDE)
```console
cd <your app folder>
flutter doctor -v
flutter pub upgrade --verbose
``` 
and provide the output.
Thank you

**Comment by EnChoopani** [comment]
@mamuseferha Hello my friend, I run flutter doctor -v in command promt.
![Flutter Doctor](https://user-images.githubusercontent.com/94993341/143418112-4bca21b7-4248-4fe3-a5f9-fe9360d4b87a.png)

**Comment by EnChoopani** [comment]
@mamuseferha Execute the **flutter pub upgrade --verbose** command in the Android Studio terminal? When is the project open?

**Comment by EnChoopani** [comment]
@mamuseferha I ran **flutter pub upgrade --verbose** in the Android Studio terminal.

https://user-images.githubusercontent.com/94993341/143424149-0c468333-d432-4e72-bb07-b83c3a126a52.mp4

**Comment by aravind-b-dev** [comment]
flutter doctor -v

**Comment by mamuseferha** [comment]
Hi @EnChoopani can you provide the output in a file (.txt file) and not an image/video? Also, please run the command in CMD(command prompt) and not android studio, you don't have to open the project for this to work.
