### ISSUE TITLE
Selection controls in GBoard for Android fail to work

### ISSUE THREAD

**Issue by ds84182** [flutter/flutter#9419]
I'm running the latest version of Flutter and the latest GBoard beta. Selection controls can be found by pressing the Google icon on the top-left and pressing the <I> icon that shows up. Select all and general selection traversal fails to function. Native Android applications work fine with this.

**Comment by eseidelGoogle** [comment]
We may not have a full implementation of the android input protocols?  Here is our current code:
https://github.com/flutter/engine/tree/master/shell/platform/android/io/flutter/plugin/editing

**Comment by eseidelGoogle** [comment]
FYI @jason-simmons

**Comment by ds84182** [comment]
An update on the current behavior of Flutter w/ GBoard selection controls:

* Left and right navigation works.

* Up and down navigation doesn't work.

* Selection mode doesn't work.

* Cut/Copy/Paste doesn't work.

* Home `<|` and End `|>` doesn't work.

* Select All doesn't work.

Most of these (other than home and end) work fine with a physical keyboard.

**Comment by eseidelGoogle** [comment]
I think @justinmc is our input-expert these days.

**Comment by justinmc** [comment]
Yeah I'm seeing the same results.  Only the left/right arrows and backspace work.  This is the keyboard we're talking about for reference:

![Screenshot_1568654238](https://user-images.githubusercontent.com/389558/64979893-8e2f2500-d86d-11e9-9b2b-e4d9eec4c9d9.png)

**Comment by justinmc** [comment]
The PR referenced above should make this a bit easier.  See https://github.com/flutter/flutter/pull/42879#issuecomment-543319194.

**Comment by justinmc** [comment]
Here is likely where we need to add support for new keycodes: https://github.com/flutter/engine/blob/a5243c024c5241a297b2afed6473a187112388b7/shell/platform/android/io/flutter/plugin/editing/InputConnectionAdaptor.java#L156

**Comment by justinmc** [comment]
There is another issue about certain keys on a third party Chinese keyboard not working.  Likely similar to this. https://github.com/flutter/flutter/issues/37371

**Comment by edman** [comment]
Latest update on text editing support after the recent change:

* Selection mode works.

* Cut/Copy/Paste works.

* Select All works.

* Up/down navigation partly works.

  We don't know the view width at the moment we treat key events, so there's a problem when lines are long and soft wrap.

* Home <| and End |> does not work.

  This should be a simple `setSelection` call, but for some reason our `InputConnectionAdaptor` is not being sent these events. Not sure why.

**Comment by markusaksli-nc** [comment]
@edman What's the status on this? Everything seems to be working on the latest master `1.22.0-10.0.pre.403`.

**Comment by justinmc** [comment]
I agree, this seems to work now and can be closed.  I'm not sure who/what fixed this, but that's great.  The two problems mentioned above, up/down with soft wrapping lines and end/home, both seem to work fine for me now.
