### ISSUE TITLE
[Android] FlutterEngine is Running

### ISSUE THREAD

**Issue by VinniciusJesus** [flutter/flutter#94209]
Flutter: 2.5.3

How do I know if my app is already running?

I would like to prevent the code below from starting a new application if my engine is already running

```
        engine = FlutterEngine(this.getApplicationContext())
        val entrypoint: DartEntrypoint = DartEntrypoint.createDefault()
        engine.dartExecutor.executeDartEntrypoint(entrypoint)
```

**Comment by stuartmorgan** [comment]
If you are manually creating engine instances, it's up to you to keep track of them. There is no global registry of engines.
