### ISSUE TITLE
Flutter not running Vivo iqoo z3

### ISSUE THREAD

**Issue by rishikesh2003** [flutter/flutter#94206]
Hi, I am trying to run flutter on my iqoo z3 device. The app starts without no problem but there is only a white screen. No other content on the application. My device is running android 11 Funtouch OS

**Comment by danagbemava-nc** [comment]
Hi @rishikesh2003,

Do you see anything in your console? 

And can you share what you see in your console? 

Thank you

**Comment by rishikesh2003** [comment]
No, I just see the app installs correctly and gradle build finishes. No errors in the console.

**Comment by danagbemava-nc** [comment]
Kindly share the output of `flutter run -v`

**Comment by rishikesh2003** [comment]
The output of `flutter run -v` as follows. Everything seems pretty normal to me. It normally works on other devices like samsung. But Iqoo z3 having problems
`[  +70 ms] executing: uname -m
[  +21 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +3 ms] executing: [/home/rishikesh2003/snap/flutter/common/flutter/] git -c
log.showSignature=false log -n 1 --pretty=format:%H
[ +136 ms] Exit code 0 from: git -c log.showSignature=false log -n 1
--pretty=format:%H
[   +5 ms] 18116933e77adc82f80866c928266a5b4f1ed645
[   +1 ms] executing: [/home/rishikesh2003/snap/flutter/common/flutter/] git tag
--points-at 18116933e77adc82f80866c928266a5b4f1ed645
[ +176 ms] Exit code 0 from: git tag --points-at
18116933e77adc82f80866c928266a5b4f1ed645
[   +1 ms] 2.5.3
[  +29 ms] executing: [/home/rishikesh2003/snap/flutter/common/flutter/] git
rev-parse --abbrev-ref --symbolic @{u}
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/rishikesh2003/snap/flutter/common/flutter/] git
ls-remote --get-url origin
[   +5 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +174 ms] executing: [/home/rishikesh2003/snap/flutter/common/flutter/] git
rev-parse --abbrev-ref HEAD
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +104 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping
update.
[   +9 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[ +674 ms] executing: /home/rishikesh2003/Android/Sdk/platform-tools/adb devices
-l
[ +272 ms] List of devices attached
                    3084769632000G3        device usb:1-3 product:2011i
                    model:I2011 device:2011 transport_id:1


                    adb server version (39) doesn't match this client (41);
                    killing...
                    * daemon started successfully
[  +15 ms] /home/rishikesh2003/Android/Sdk/platform-tools/adb -s 3084769632000G3
shell getprop
[ +239 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[   +8 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[ +205 ms] Skipping pub get: version match.
[ +472 ms] Generating
/home/rishikesh2003/coding-projects/quiz_app/android/app/src/main/java/io/flutte
r/plugins/GeneratedPluginRegistrant.java
[  +81 ms] ro.hardware = qcom
[  +26 ms] Initializing file store
[  +89 ms] Skipping target: gen_localizations
[  +17 ms] Skipping target: gen_dart_plugin_registrant
[        ] Skipping target: _composite
[   +3 ms] complete
[   +7 ms] Launching lib/main.dart on I2011 in debug mode...
[   +5 ms]
/home/rishikesh2003/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart
--disable-dart-dev
/home/rishikesh2003/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux
-x64/frontend_server.dart.snapshot --sdk-root
/home/rishikesh2003/snap/flutter/common/flutter/bin/cache/artifacts/engine/commo
n/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names
--experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
/tmp/flutter_tools.BYRMSP/flutter_tool.RXGPBM/app.dill --packages
/home/rishikesh2003/coding-projects/quiz_app/.dart_tool/package_config.json
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts
--track-widget-creation --filesystem-scheme org-dartlang-root
--initialize-from-dill
build/c075001b96339384a97db4862b8ab8db.cache.dill.track.dill
--enable-experiment=alternative-invalidation-strategy
[  +65 ms] executing:
/home/rishikesh2003/Android/Sdk/build-tools/32.0.0-rc1/aapt dump xmltree
/home/rishikesh2003/coding-projects/quiz_app/build/app/outputs/flutter-apk/app.a
pk AndroidManifest.xml
[ +130 ms] Exit code 0 from:
/home/rishikesh2003/Android/Sdk/build-tools/32.0.0-rc1/aapt dump xmltree
/home/rishikesh2003/coding-projects/quiz_app/build/app/outputs/flutter-apk/app.a
pk AndroidManifest.xml
[   +1 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1e
               A: android:compileSdkVersionCodename(0x01010573)="11" (Raw: "11")
               A: package="com.example.quiz_app" (Raw: "com.example.quiz_app")
               A: platformBuildVersionCode=(type 0x10)0x1e
               A: platformBuildVersionName=(type 0x10)0xb
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1e
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw:
                 "android.permission.INTERNET")
               E: application (line=16)
                 A: android:label(0x01010001)="quiz_app" (Raw: "quiz_app")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A:
                 android:appComponentFactory(0x0101057a)="androidx.core.app.Core
                 ComponentFactory" (Raw:
                 "androidx.core.app.CoreComponentFactory")
                 E: activity (line=21)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A:
                   android:name(0x01010003)="com.example.quiz_app.MainActivity"
                   (Raw: "com.example.quiz_app.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type
                   0x12)0xffffffff
                   E: meta-data (line=35)
                     A:
                     android:name(0x01010003)="io.flutter.embedding.android.Norm
                     alTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=45)
                     A:
                     android:name(0x01010003)="io.flutter.embedding.android.Spla
                     shScreenDrawable" (Raw:
                     "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=49)
                     E: action (line=50)
                       A: android:name(0x01010003)="android.intent.action.MAIN"
                       (Raw: "android.intent.action.MAIN")
                     E: category (line=52)
                       A:
                       android:name(0x01010003)="android.intent.category.LAUNCHE
                       R" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=59)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw:
                   "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[  +31 ms] executing: /home/rishikesh2003/Android/Sdk/platform-tools/adb -s
3084769632000G3 shell -x logcat -v time -t 1
[  +23 ms] <- compile package:quiz_app/main.dart
[ +359 ms] --------- beginning of main
                    11-26 16:04:17.042 E/Unknow  (10293): [TXCMMapFile.cpp,
                    _cleanup, 511]:failed mapping file
[  +11 ms] executing: /home/rishikesh2003/Android/Sdk/platform-tools/adb version
[   +4 ms] Android Debug Bridge version 1.0.41
           Version 31.0.3-7562133
           Installed as /home/rishikesh2003/Android/Sdk/platform-tools/adb
[   +1 ms] executing: /home/rishikesh2003/Android/Sdk/platform-tools/adb
start-server
[   +4 ms] Building APK
[  +11 ms] Running Gradle task 'assembleDebug'...
[  +95 ms] Using gradle from
/home/rishikesh2003/coding-projects/quiz_app/android/gradlew.
[ +106 ms] executing:
/home/rishikesh2003/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7
784292/jre/bin/java -version
[+1231 ms] Exit code 0 from:
/home/rishikesh2003/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7
784292/jre/bin/java -version
[        ] openjdk version "11.0.10" 2021-01-19
           OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
           OpenJDK 64-Bit Server VM (build 11.0.10+0-b96-7249189, mixed mode)
[   +1 ms] executing: [/home/rishikesh2003/coding-projects/quiz_app/android/]
/home/rishikesh2003/coding-projects/quiz_app/android/gradlew -Pverbose=true
-Ptarget-platform=android-arm64
-Ptarget=/home/rishikesh2003/coding-projects/quiz_app/lib/main.dart
-Pdart-defines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== -Pdart-obfuscation=false
-Ptrack-widget-creation=true -Ptree-shake-icons=false
-Pfilesystem-scheme=org-dartlang-root assembleDebug
[+3057 ms] Starting a Gradle Daemon, 1 busy and 1 incompatible and 1 stopped
Daemons could not be reused, use --status for details
[+17797 ms] > Task :app:compileFlutterBuildDebug
[        ] [  +44 ms] executing: uname -m
[        ] [  +22 ms] Exit code 0 from: uname -m
[        ] [        ] x86_64
[        ] [   +3 ms] executing:
[/home/rishikesh2003/snap/flutter/common/flutter/] git -c
log.showSignature=false log -n 1 --pretty=format:%H
[        ] [   +3 ms] Exit code 0 from: git -c log.showSignature=false log -n 1
--pretty=format:%H
[        ] [        ] 18116933e77adc82f80866c928266a5b4f1ed645
[        ] [        ] executing:
[/home/rishikesh2003/snap/flutter/common/flutter/] git tag --points-at
18116933e77adc82f80866c928266a5b4f1ed645
[        ] [   +9 ms] Exit code 0 from: git tag --points-at
18116933e77adc82f80866c928266a5b4f1ed645
[        ] [        ] 2.5.3
[        ] [   +6 ms] executing:
[/home/rishikesh2003/snap/flutter/common/flutter/] git rev-parse --abbrev-ref
--symbolic @{u}
[        ] [   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic
@{u}
[        ] [        ] origin/stable
[        ] [        ] executing:
[/home/rishikesh2003/snap/flutter/common/flutter/] git ls-remote --get-url
origin
[        ] [   +2 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +39 ms] executing:
[/home/rishikesh2003/snap/flutter/common/flutter/] git rev-parse --abbrev-ref
HEAD
[        ] [   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] stable
[        ] [  +32 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is
not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required,
skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required,
skipping update.
[        ] [   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not
required, skipping update.
[        ] [  +61 ms] Artifact Instance of 'MaterialFonts' is not required,
skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required,
skipping update.
[        ] [   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is
not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required,
skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required,
skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required,
skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required,
skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required,
skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required,
skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required,
skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required,
skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required,
skipping update.
[        ] [  +61 ms] Initializing file store
[        ] [  +33 ms] Skipping target: gen_localizations
[        ] [  +37 ms] Skipping target: gen_dart_plugin_registrant
[        ] [   +1 ms] kernel_snapshot: Starting due to {}
[        ] [  +11 ms]
/home/rishikesh2003/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart
--disable-dart-dev
/home/rishikesh2003/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux
-x64/frontend_server.dart.snapshot --sdk-root
/home/rishikesh2003/snap/flutter/common/flutter/bin/cache/artifacts/engine/commo
n/flutter_patched_sdk/ --target=flutter --no-print-incremental-dependencies
-DFLUTTER_WEB_AUTO_DETECT=true -Ddart.vm.profile=false -Ddart.vm.product=false
--enable-asserts --track-widget-creation --no-link-platform --packages
/home/rishikesh2003/coding-projects/quiz_app/.dart_tool/package_config.json
--output-dill
/home/rishikesh2003/coding-projects/quiz_app/.dart_tool/flutter_build/3da9a942bd
e033d2abb2d585c00e130a/app.dill --depfile
/home/rishikesh2003/coding-projects/quiz_app/.dart_tool/flutter_build/3da9a942bd
e033d2abb2d585c00e130a/kernel_snapshot.d package:quiz_app/main.dart
[+5988 ms] [+7241 ms] kernel_snapshot: Complete
[ +600 ms] [ +525 ms] debug_android_application: Starting due to {}
[+1499 ms] [+1559 ms] debug_android_application: Complete
[ +499 ms] [ +512 ms] Persisting file store
[        ] [   +5 ms] Done persisting file store
[  +99 ms] [  +34 ms] build succeeded.
[        ] [  +38 ms] "flutter assemble" took 10,118ms.
[ +299 ms] [ +261 ms] ensureAnalyticsSent: 255ms
[        ] [   +3 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [   +3 ms] exiting with code 0
[ +199 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[        ] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[  +99 ms] > Task :app:generateDebugBuildConfig UP-TO-DATE
[ +499 ms] > Task :app:checkDebugAarMetadata UP-TO-DATE
[ +100 ms] > Task :app:cleanMergeDebugAssets
[        ] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders NO-SOURCE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[  +99 ms] > Task :app:mergeDebugAssets
[ +199 ms] > Task :app:copyFlutterAssetsDebug
[        ] > Task :app:generateDebugResValues UP-TO-DATE
[        ] > Task :app:generateDebugResources UP-TO-DATE
[        ] > Task :app:mergeDebugResources UP-TO-DATE
[        ] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[        ] > Task :app:extractDeepLinksDebug UP-TO-DATE
[ +200 ms] > Task :app:processDebugMainManifest UP-TO-DATE
[   +1 ms] > Task :app:processDebugManifest UP-TO-DATE
[        ] > Task :app:processDebugManifestForPackage UP-TO-DATE
[ +196 ms] > Task :app:processDebugResources UP-TO-DATE
[ +799 ms] > Task :app:compileDebugKotlin UP-TO-DATE
[        ] > Task :app:javaPreCompileDebug UP-TO-DATE
[        ] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :app:compileDebugSources UP-TO-DATE
[        ] > Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
[        ] > Task :app:compressDebugAssets UP-TO-DATE
[        ] > Task :app:processDebugJavaRes NO-SOURCE
[  +99 ms] > Task :app:mergeDebugJavaResource UP-TO-DATE
[        ] > Task :app:checkDebugDuplicateClasses UP-TO-DATE
[        ] > Task :app:dexBuilderDebug UP-TO-DATE
[        ] > Task :app:desugarDebugFileDependencies UP-TO-DATE
[  +99 ms] > Task :app:mergeExtDexDebug UP-TO-DATE
[        ] > Task :app:mergeDexDebug UP-TO-DATE
[        ] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[  +99 ms] > Task :app:mergeDebugNativeLibs UP-TO-DATE
[        ] > Task :app:stripDebugDebugSymbols UP-TO-DATE
[        ] > Task :app:validateSigningDebug UP-TO-DATE
[  +99 ms] > Task :app:packageDebug UP-TO-DATE
[+1100 ms] > Task :app:assembleDebug
[ +199 ms] Deprecated Gradle features were used in this build, making it
incompatible with Gradle 7.0.
[   +1 ms] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See
https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_li
ne_warnings
[   +1 ms] BUILD SUCCESSFUL in 33s
[        ] 32 actionable tasks: 5 executed, 27 up-to-date
[ +441 ms] Running Gradle task 'assembleDebug'... (completed in 35.8s)
[ +792 ms] calculateSha: LocalDirectory:
'/home/rishikesh2003/coding-projects/quiz_app/build/app/outputs/flutter-apk'/app
.apk
[ +589 ms] ✓  Built build/app/outputs/flutter-apk/app-debug.apk.
[   +2 ms] executing:
/home/rishikesh2003/Android/Sdk/build-tools/32.0.0-rc1/aapt dump xmltree
/home/rishikesh2003/coding-projects/quiz_app/build/app/outputs/flutter-apk/app.a
pk AndroidManifest.xml
[   +5 ms] Exit code 0 from:
/home/rishikesh2003/Android/Sdk/build-tools/32.0.0-rc1/aapt dump xmltree
/home/rishikesh2003/coding-projects/quiz_app/build/app/outputs/flutter-apk/app.a
pk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1e
               A: android:compileSdkVersionCodename(0x01010573)="11" (Raw: "11")
               A: package="com.example.quiz_app" (Raw: "com.example.quiz_app")
               A: platformBuildVersionCode=(type 0x10)0x1e
               A: platformBuildVersionName=(type 0x10)0xb
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1e
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw:
                 "android.permission.INTERNET")
               E: application (line=16)
                 A: android:label(0x01010001)="quiz_app" (Raw: "quiz_app")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A:
                 android:appComponentFactory(0x0101057a)="androidx.core.app.Core
                 ComponentFactory" (Raw:
                 "androidx.core.app.CoreComponentFactory")
                 E: activity (line=21)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A:
                   android:name(0x01010003)="com.example.quiz_app.MainActivity"
                   (Raw: "com.example.quiz_app.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type
                   0x12)0xffffffff
                   E: meta-data (line=35)
                     A:
                     android:name(0x01010003)="io.flutter.embedding.android.Norm
                     alTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=45)
                     A:
                     android:name(0x01010003)="io.flutter.embedding.android.Spla
                     shScreenDrawable" (Raw:
                     "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=49)
                     E: action (line=50)
                       A: android:name(0x01010003)="android.intent.action.MAIN"
                       (Raw: "android.intent.action.MAIN")
                     E: category (line=52)
                       A:
                       android:name(0x01010003)="android.intent.category.LAUNCHE
                       R" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=59)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw:
                   "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +1 ms] Stopping app 'app.apk' on I2011.
[        ] executing: /home/rishikesh2003/Android/Sdk/platform-tools/adb -s
3084769632000G3 shell am force-stop com.example.quiz_app
[ +146 ms] executing: /home/rishikesh2003/Android/Sdk/platform-tools/adb -s
3084769632000G3 shell pm list packages com.example.quiz_app
[ +128 ms] package:com.example.quiz_app
[   +5 ms] executing: /home/rishikesh2003/Android/Sdk/platform-tools/adb -s
3084769632000G3 shell cat /data/local/tmp/sky.com.example.quiz_app.sha1
[  +84 ms] ffb2a11cbfba609b5c6a552fd6b6daad405eb31f
[   +1 ms] Latest build already installed.
[        ] executing: /home/rishikesh2003/Android/Sdk/platform-tools/adb -s
3084769632000G3 shell -x logcat -v time -t 1
[ +232 ms] --------- beginning of main
                    11-26 16:05:17.845 I/Unknow  (10293): [asyn_socket_base.cpp,
                    CloseSocket, 258]:AsynBaseSocket socket close done|fd:234|
[  +25 ms] executing: /home/rishikesh2003/Android/Sdk/platform-tools/adb -s
3084769632000G3 shell am start -a android.intent.action.RUN -f 0x20000000 --ez
enable-background-compilation true --ez enable-dart-profiling true --ez
enable-checked-mode true --ez verify-entry-points true
com.example.quiz_app/com.example.quiz_app.MainActivity
[ +124 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000
cmp=com.example.quiz_app/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
[ +580 ms] W/FlutterActivityAndFragmentDelegate(11195): A splash screen was
provided to Flutter, but this is deprecated. See
flutter.dev/go/android-splash-migration for migration steps.
[  +52 ms] I/flutter (11195): Observatory listening on
************************************
`

**Comment by rishikesh2003** [comment]
One  more thing I can't do hot reload or restart while connected to this device IQOO z3

**Comment by rishikesh2003** [comment]
It is a problem with flutter or the device itself?

**Comment by danagbemava-nc** [comment]
Several Vivo users have reported similar cases. 

That issue is being tracked https://github.com/flutter/flutter/issues/82520. 

Kindly follow up there for more information. 

Closing from here as duplicate.

**Comment by rishikesh2003** [comment]
Ok, Thank you for your response
