### ISSUE TITLE
[Web] Flutter was unable to create enough overlay surfaces

### ISSUE THREAD

**Issue by bambinoua** [flutter/flutter#94215]
We use `google_maps_flutter_web` package in our flutter web app. As they know this package is based on `HtmlElementView`. Over the Google Maps widget we use our own widgets. To intercept pointer events on our widgets we use `pointer_interceptor` package (`InterceptPointer` widget) which is just a wrapper for `child`:

```dart
Stack(
  children: [
    Positioned.fill(
      HtmlElementView(viewType: '__viewType__'),
    ),
    wrappedChildWidget,
  ],
)
```

It seems there is some limit of using other `HtmlElementView` widgets in flutter because we get this warning message in debug window:

_Flutter was unable to create enough overlay surfaces. This is usually caused by too many platform views being displayed at once. You may experience incorrect rendering._

We inspect the elemens tab on Chrome inspector. When the page containing Google Maps widget widget is open first we noticed the few `div`s under `flt-glass-pane`, i.e. Google Maps itself and our 4 widgets which are over GoogleMaps and wrepped by `PointerIntercept`:
```
<flt-platform-view slot="flt-pv-slot-0"><div id="plugins.flutter.io/google_maps">...</div></flt-platform-view>
<flt-platform-view slot="flt-pv-slot-1"><div style="width: 100%, height: 100%"></flt-platform-view>
<flt-platform-view slot="flt-pv-slot-2"><div style="width: 100%, height: 100%"></flt-platform-view>
<flt-platform-view slot="flt-pv-slot-3"><div style="width: 100%, height: 100%"></flt-platform-view>
<flt-platform-view slot="flt-pv-slot-4"><div style="width: 100%, height: 100%"></flt-platform-view>
```

**No warnings.**

Then we click on dropdown button (on top of the page) which opens dropdown menu with some items which (certainly) overlap the GoogleMaps widget each menu item also wrapped with `PointerInterceptor`.

So we see

```
<flt-platform-view slot="flt-pv-slot-0"><div id="plugins.flutter.io/google_maps">...</div></flt-platform-view>
<flt-platform-view slot="flt-pv-slot-1"><div style="width: 100%, height: 100%"></flt-platform-view>
<flt-platform-view slot="flt-pv-slot-2"><div style="width: 100%, height: 100%"></flt-platform-view>
<flt-platform-view slot="flt-pv-slot-3"><div style="width: 100%, height: 100%"></flt-platform-view>
<flt-platform-view slot="flt-pv-slot-4"><div style="width: 100%, height: 100%"></flt-platform-view>
<flt-platform-view slot="flt-pv-slot-5"><div style="width: 100%, height: 100%"></flt-platform-view>
<flt-platform-view slot="flt-pv-slot-6"><div style="width: 100%, height: 100%"></flt-platform-view>
<flt-platform-view slot="flt-pv-slot-7"><div style="width: 100%, height: 100%"></flt-platform-view>
<flt-platform-view slot="flt-pv-slot-8"><div style="width: 100%, height: 100%"></flt-platform-view>
<flt-platform-view slot="flt-pv-slot-9"><div style="width: 100%, height: 100%"></flt-platform-view>
```

The warning message

**Flutter was unable to create enough overlay surfaces. This is usually caused by too many platform views being displayed at once. You may experience incorrect rendering.**

is printed on debug console.

Then we click on some dropdown item and open the `Dialog` which is also wrapped with `PointerInterceptor` (to prevent moving of Google Maps while move mouse over the dialog). The dialog is opened, and its content is shown for a moment and than is overlapped by some white container so no any dialog's widgets visible (just white background). But we can close the dialog via close button which is present on dialog (but it is invisible)

We see this;
```
<flt-platform-view slot="flt-pv-slot-0"><div id="plugins.flutter.io/google_maps">...</div></flt-platform-view>
<flt-platform-view slot="flt-pv-slot-1"><div style="width: 100%, height: 100%"></flt-platform-view>
<flt-platform-view slot="flt-pv-slot-2"><div style="width: 100%, height: 100%"></flt-platform-view>
<flt-platform-view slot="flt-pv-slot-3"><div style="width: 100%, height: 100%"></flt-platform-view>
<flt-platform-view slot="flt-pv-slot-4"><div style="width: 100%, height: 100%"></flt-platform-view>
<flt-platform-view slot="flt-pv-slot-5"><div style="width: 100%, height: 100%"></flt-platform-view>
<flt-platform-view slot="flt-pv-slot-10"><div style="width: 100%, height: 100%"></flt-platform-view>
```

So I repeat it looks like there is a limit for use of <flt-platform-view> slots. And we actually don't understand why the maximum 10 additional `div`s creates a problem for page rendering?

flutter is 2.5.3 stable

P.S. Unfortunately we cannot provide the simple example because the real case is rather complex.

**Comment by darshankawar** [comment]
@bambinoua 
Does it happen using canvaskit rendering or with html ? The message you are seeing about `overlay surfaces` may not be specific to google maps, because it's been reported using `url_launcher` too. See these issues for reference: https://github.com/flutter/flutter/issues/88449, https://github.com/flutter/flutter/issues/91662.

**Comment by bambinoua** [comment]
It happen while I use debug mode in VS Code. As I know in debug mode the rendering is `auto`.
This issue is not related to `url_laucnher` because I didn't use it. But as I know `url_launcher` use `HtmlElementView` also. The problem as I see is in using of quoted widget.

Pleas re-read the issue again. `GoogleMap` widget uses `HtmlElementView` and I use `PointerInterceptor` widget (from similar package) to intercept mouse pointers on my own widgets which are over GoogleMap widget. Both `GoogleMap` and `PointerInterceptor` use `HtmlElementView` which in its turn creates and HTML element `flt-platform-view` when render the result HTML code. You may see my HTML code rows. So the problem when flutter processess `HtmlElementView` widgets.

**Comment by darshankawar** [comment]
@bambinoua 
With new stable release and work on platform-views and HtmlElementView, please try upgrading to latest and see if you still get same behavior or not.

**Comment by bambinoua** [comment]
@darshankawar it looks like working! Thanks a lot!
