### ISSUE TITLE
I have no idea about the crash, need help

### ISSUE THREAD

**Issue by OHeroJ** [flutter/flutter#94226]
<img width="1121" alt="Screen Shot 2021-11-26 at 10 03 08 AM" src="https://user-images.githubusercontent.com/12316547/143515991-712e4c06-2997-4ce6-9ac1-affb28b3f534.png">

```dart
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6.1 20G224 darwin-x64, locale en-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.62.2)
[✓] Connected device (3 available)

• No issues found!
```

**Comment by maheshmnj** [comment]
Hey @OHeroJ, Please note that the issue tracker is not to provide help with your code but to track issues in the framework. Please try asking on community forums like StackOverflow or Reddit and you might get some help if you clearly describe the issue with a sample code.

Closing as this isn't an issue with flutter if you disagree feel free to write in the comments and I will reopen it.

Thank you.
