### ISSUE TITLE
share file to wechat

### ISSUE THREAD

**Issue by jleisurely** [flutter/flutter#94227]
## Steps to Reproduce

On iOS platform, when sharing files, it will prompt "unsupported sharing type, cannot be shared to wechat". I have found a solution to this problem, which requires the "file://" and conversion to NSURL before adding the file to the activityItems of UIActivityController

like this
 let pathStr : String = String(format: "file://%@",call.arguments as! CVarArg)
                  let url = NSURL.fileURL(withPath:pathStr)
                  let alert = UIActivityViewController.init(activityItems: [url ?? "haha"], applicationActivities: nil)
                  controller .present(alert, animated: true, completion: nil)
**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @jleisurely, what package are you using to share the files?
