### ISSUE TITLE
Having issues regarding cloning a single branch of a repository

### ISSUE THREAD

**Issue by Coder-Pritam** [flutter/flutter#94238]
* Where: Script 'C:\flutter\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1005 * What went wrong: Execution failed for task ':app:compileFlutterBuildDebug'. > Process 'command 'C:\flutter\flutter\bin\flutter.bat'' finished with non-zero exit value 1 * Try: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights. * Get more help at https://help.gradle.org BUILD FAILED in 2m 34s ********************************************************* WARNING: This version of flutter_tts will break your Android build if it or its dependencies aren't compatible with AndroidX. See https://goo.gl/CP92wY for more information on the problem and how to fix it. This warning prints for all Android build failures. The real root cause of the error may be unrelated. ********************************************************* Exception: Gradle task assembleDebug failed with exit code 1

**Comment by danagbemava-nc** [comment]
Hi @Coder-Pritam,

Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?


Thank you
