### ISSUE TITLE
Poor error message when building for Android and license checks fail

### ISSUE THREAD

**Issue by johnmccutchan** [flutter/flutter#9423]
Reproduction steps:

```
$ flutter create delete_me
$ cd delete_me
$ flutter run
```

Got this:

```
Launching lib/main.dart on Nexus 7 in debug mode...
Running 'gradle assembleDebug'...                         
Checking the license for package Android SDK Build-Tools 25.0.2 in /usr/local/google/home/johnmccutchan/Android/Sdk/licenses
Warning: License for package Android SDK Build-Tools 25.0.2 not accepted.
Checking the license for package Android SDK Platform 25 in /usr/local/google/home/johnmccutchan/Android/Sdk/licenses
Warning: License for package Android SDK Platform 25 not accepted.

FAILURE: Build failed with an exception.

* Where:
Build file '/usr/local/google/home/johnmccutchan/delete_me/android/build.gradle' line: 20

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Failed to notify project evaluation listener.
      > You have not accepted the license agreements of the following SDK components:
        [Android SDK Build-Tools 25.0.2, Android SDK Platform 25].
        Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
        Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html
      > Could not get unknown property 'compileDebugJavaWithJavac' for project ':app' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

1. 'android' and ':app' are meaningless to me.
2. Failed to notify project evaluation listener. -- what?
3. You have not accepted the license agreements of the following SDK components:

`
Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
        Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html
`

I have no idea how to install these components or how accept the license agreement. 

4.   `> Could not get unknown property 'compileDebugJavaWithJavac' for project ':app' of type org.gradle.api.Project.` -- what?

5. `* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.`

I tried running with `--info` and got:

```
$ flutter run --info
Could not find an option named "info".

Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
```

**Comment by eseidelGoogle** [comment]
FYI @jakobr-google

**Comment by johnmccutchan** [comment]
For the record I had to do the following to fix this:

1. Launch Android studio 2.2
2. Figure out that I want the the SDK manager
3. Install Android SDK 25

Try again. Failed same way. Realized that my system has multiple versions of Android Studio installed.

4. Launch Android Studio 2.3.
5. Install Android SDK 25.

Success.

**Comment by johnmccutchan** [comment]
Related: https://github.com/flutter/flutter/issues/8093

**Comment by mit-mit** [comment]
I think the right solution to this is to make Flutter more self-contained. As part of `flutter setup` we should download an Android SDK in the versions we need.

**Comment by johnmccutchan** [comment]
@mit-mit Probably. But, as it stands today my Flutter getting started experience has significantly regressed.

**Comment by eseidelGoogle** [comment]
@mit-mit can you help us triage if this needs to be in M2?  Can we mitigate this for M2?

**Comment by mit-mit** [comment]
@johnmccutchan had you manually changed the SDK path in either of the two Android Studio's? I'm puzzled about what is going on here, as AFAICT they both drop the SDK into `/Users/mit/Library/Android/sdk`

**Comment by johnmccutchan** [comment]
@mit-mit the issue is that I had never used Android Studio, never installed the SDKs, and never agreed to the EULAs.

**Comment by mit-mit** [comment]
I don't understand several aspects of this bug:

1. You state above that you never used Android Studio, nor installed SDKs. In that case, you should have seen several issues listed in `flutter doctor`. Was that not the case?
1. It's tagged 'regression'. What exactly is the part that regressed?
1. Comment https://github.com/flutter/flutter/issues/9423#issuecomment-294544648 says that AS 2.2 + SDK 25 did not work. I'd love to hear more about that. Did it not download the SDK into `~/Library/Android/SDK`?

**Comment by johnmccutchan** [comment]
@mit-mit 

1. To be clear there were two versions of Android Studio installed on my workstation (internal corp packages), but neither had ever been used.
2. My experience as a Flutter on Android developer regressed. It used to work just fine and then I got the confusing error messages seen above. 
3. One run of flutter doctor picked up Android Studio 2.2 as the current version of Android Studio and the next run of flutter doctor picked up Android Studio 2.3. Probably because I had used and setup Android Studio 2.3 in the meantime.

**Comment by mit-mit** [comment]
Re 2, it sounds like you have not build apps since we switched over to building with gradle? If so, that regression is by-design.

**Comment by johnmccutchan** [comment]
@mit-mit Correct I haven't built an app on Android for awhile but I don't understand you when you say this regression was "by-design". I have a hard time believing the gradle team intentionally design a system to-

1. That throws confusing error messages at the user.
3. Tell me I need to sign an EULA but provide no clear instructions on where / how to do that.
2. Suggests running flutter run with command line arguments it doesn't support.

**Comment by mit-mit** [comment]
Sorry for now being clear. The dependency on having Android Studio installed is by-design. The error messaging we have when that is not the case is definitely not as desired!

**Comment by eseidelGoogle** [comment]
Is this a duplicate of https://github.com/flutter/flutter/issues/8438?  Seems like one of these is an event blocker but maybe not both?

**Comment by eseidelGoogle** [comment]
@johnmccutchan can you tell me if this is a duplicate.  I can answer if it blocks the event once we have the kiosk machines.

**Comment by eseidelGoogle** [comment]
Assigning to @johnmccutchan for decision if dupe.

**Comment by johnmccutchan** [comment]
Closing as dupe.
