### ISSUE TITLE
Run flutter drive tests on web with test integration_test

### ISSUE THREAD

**Issue by VeArnold** [flutter/flutter#94245]
Flutter Drive tests were allowed for web (the PR in the comment has been merged), but this clause to error still exists:
https://github.com/flutter/flutter/blob/341e771b125b0a41f900ba781b41711f57cb7de8/packages/flutter_tools/lib/src/commands/test.dart#L417-L420

To elaborate running:
`flutter -d chrome drive --driver=test_driver/integration_driver.dart --target=integration_test/app_test.dart`
works fine, but running:
`flutter -d chrome test integration_test`
fails with:
`Web devices are not supported for integration tests yet.`

I guess there might be some underlying issues to get this sorted (and thus for the error to still be thrown)?

In any case, as it is actually possible to run integration tests on web devices (even if not in that way) then the error is misleading.

**Comment by darshankawar** [comment]
@VeArnold 
Although I get the same message in console after trying to run `flutter test integration_test -d chrome`, which PR are you referring to ?

**Comment by VeArnold** [comment]
@darshankawar I am referring to the PR linked in `flutter/packages/flutter_tools/lib/src/commands/test.dart` line 418, wherein the line states: 

`// TODO(jiahaog): Support web. https://github.com/flutter/flutter/pull/74236 `

**Comment by darshankawar** [comment]
Thanks for the pointer. Yes, it seems the linked PR was merged, but we are still getting the message in the console.
Keeping it open for further insights from @jiahaog

**Comment by jiahaog** [comment]
Thanks for reporting this, indeed the PR has been merged but this is still not supported yet. I'm not actively working on this currently, but work is tracked in https://github.com/flutter/flutter/issues/66264, and I sent #94597 to fix the todo 🙂
