### ISSUE TITLE
memory leak in engine's MakeSkSurfaceFromBackingStore

### ISSUE THREAD

**Issue by saurik** [flutter/flutter#94241]
I'm reading through the code trying to figure out why there is both a destruction_callback on FlutterSoftwareBackingStore as well as a collect_backing_store on FlutterCompositor, and, while I'm finding a lot of things that feel strange, this bit is almost certainly a bug:

https://github.com/flutter/engine/blob/ea734ba7f8de9c6e2bb6b30efa1f53b5aec6d3c6/shell/platform/embedder/embedder.cc#L549-L569

```c++
  struct Captures {
    VoidCallback destruction_callback;
    void* user_data;
  };
  auto captures = std::make_unique<Captures>();
  captures->destruction_callback = software->destruction_callback;
  captures->user_data = software->user_data;
  auto release_proc = [](void* pixels, void* context) {
    auto captures = reinterpret_cast<Captures*>(context);
    if (captures->destruction_callback) {
      captures->destruction_callback(captures->user_data);
    }
  };

  auto surface = SkSurface::MakeRasterDirectReleaseProc(
      image_info,                               // image info
      const_cast<void*>(software->allocation),  // pixels
      software->row_bytes,                      // row bytes
      release_proc,                             // release proc
      captures.release()                        // release context
  );
```

We see captures being allocated using std::make_unique but then immediately (before any fail-able line of code) being .release()d to be passed as a context pointer to MakeRasterDirectReleaseProc... but that effectively means that the entire concept of this being a "unique pointer" is meaningless, right? As a minimal modification to this code I guess I'd recommend using new instead of std::make_unique so you can throw a delete of captures at the end of release_proc (though I don't know anything about MakeRasterDirectReleaseProc, and so that might also not be safe if it doesn't guarantee calling release_proc in case of failure).

**Comment by chinmaygarde** [comment]
Yes, there is a small leak here. It's the captures struct that needs to be deleted in the callback. So something like:
```
  auto release_proc = [](void* pixels, void* context) {
    auto captures = reinterpret_cast<Captures*>(context);
    if (captures->destruction_callback) {
      captures->destruction_callback(captures->user_data);
    }
    delete captures;
  };
```

> though I don't know anything about MakeRasterDirectReleaseProc, and so that might also not be safe if it doesn't guarantee calling release_proc in case of failure

Following the Skia code, it looks like Skia will not call the release proc for a `null return of surface (but the allocation is 
super small). So we would need to patch for that case as well.

```
  auto surface = SkSurface::MakeRasterDirectReleaseProc(
      image_info,                               // image info
      const_cast<void*>(software->allocation),  // pixels
      software->row_bytes,                      // row bytes
      release_proc,                             // release proc
      captures.get()                        // release context
  );
  // ...
  if (surface) {
    captures.release(); // Skia has assumed ownership of the struct.
  }
```

After the initial report, I was worried there was a leak of the surface itself. But the invocation of the destruction callback on the embedder should avoid that. So the leak is much smaller.

> while I'm finding a lot of things that feel strange

Care to elaborate? All this piece of code is doing is invoking the callback when Skia is done with the surface and Skia vends a C like API for the invocation of a caller supplied callback along with context.

> As a minimal modification to this code I guess I'd recommend using new instead of std::make_unique so you can throw a delete of captures at the end of release_proc

Not sure I buy this recommendation. There can only be one case where Skia can successfully assume ownership of the allocation (in which case, we can release our claim to the unique pointer). OTOH, there can be many possible failure cases. Which is why the rough policy is "always use a unique pointer but release the claim only on successful transfer of ownership. For all error cases, the unique pointer will reclaim allocations.". If we had used a raw pointer, we would have to remember to delete it on each error case. Obviously less of an issue here because there are so few error checks.

**Comment by saurik** [comment]
> Not sure I buy this recommendation.

@chinmaygarde FWIW, the primary reason I made that recommendation is that it honestly wasn't clear to me (despite--or maybe very likely because of--having done development in C++ continually since 1998... I thereby tended to develop my own classes for this) that you are always allowed to simply call delete on the result of calling release on an object created by std::make_unique (without adding it back to second unique_ptr and letting it do whatever potentially-magic deallocation process it might require), and I was trying to suggest something that would at least be better.

If you are actually sure that you can use delete after .release() on std::make_unique (and I just checked the documentation and I do think you are right about that) then I agree that just adding that is both still better than (and even more minimal than!) my "minimal recommendation" (though again, as you did appreciate, still not fully correct... I do believe you are on the right path towards such, by moving the .release() to after the ownership transfer and using more RAII).

It is maybe also useful to note that my mental model of code like this (such as which uses .release() as an argument) was "I guess the developer here, potentially under some deadline, was just trying to make it work and wasn't/isn't that interested in subtle levels of correctness but was fighting with a linter that refused to allow them to use new/delete so they came up with a 'clever hack' to use std::make_unique and then call .release() on it in order to get a memory allocation that the linter would pass"; and so, when I recommend a "minimal modification", it is to make it more correct in the happy path but frankly also to (awkwardly) make it more obvious that the code *isn't* fully correct (as in making the code look worse is a feature), not to actually fix the code (which I would generally expect to be a battle in such a scenario).

> Thinking about this some more. A more accurate implementation would...

I personally also agree with this thought process and am *delighted* you are looking at this as "how to really fix this" rather than merely "how to quickly patch it" ;P. Like, seriously: this is great... if anything, I am sad that I have wasted so much of your time now typing prose here :D. I am glad I filed the bug (which I was honestly a bit loathe to do). I will file further bugs as I see them (and be less cynical with and out more effort into my suggestions).

> > while I'm finding a lot of things that feel strange

> Care to elaborate? All this piece of code is doing...

In the original context of my sentence I was talking about a more high-level thought process of my attempt "to figure out why there is both a destruction_callback on FlutterSoftwareBackingStore as well as a collect_backing_store on FlutterCompositor", and so the "a lot of things that feel strange" was about all of the things I had looked at in this file and other surrounding files, some of which are more architectural issues, which I then narrowed into one specific "bit" (the snippet here) that "is almost certainly a bug" (and so seemed worthy enough to actually bring up, as my just listing things that felt strange but might be correct is probably a waste of everyone's time). I was not referring to this specific snippet of code as having "a lot of things that feel strange" (and then only one of which I noted). (That said, were I to comment even more deeply on this code, I guess I would note that that reinterpret_cast might feel required, but C++ kind of hopes you use static_cast there). If you really do care I will happily bring up things that I am not as sure are bugs.

**Comment by bleroux** [comment]
Fixed by https://github.com/flutter/engine/pull/30735
