### ISSUE TITLE
Future to Stream: read Array object in Firebase Firestore

### ISSUE THREAD

**Issue by pipodesignstudio** [flutter/flutter#94242]
I'm developing a favorites List with this information structure: Collection('users') => Doc ('uid') => FavoritesList(array of saved ids).

In order to render it on screen I have develop the following Future:

```
Future<List<Product?>> getFavoriteProduct(String? uid) async {
    final resp = await _firestore.collection('users').doc(uid).get();
    Map<String, dynamic> data = resp.data() as Map<String, dynamic>;
    var likedProds = data['liked_products'] as List<dynamic>;
    // print(likedProds);

    for (var id in likedProds) {
      final String? prodId = id;
      final prodResp =
          await _firestore.collection('products').doc(prodId).get();
      var productData = prodResp.data() as Map<String, dynamic>;
      final Product product = Product.fromFirestore(productData);
      userLikedProducts.add(product);
    }

    return userLikedProducts;
  }
```
As you can see, I access to the Array in the first place and then I'm looping in using another Future inside to get a Product(model) from the Id.

This is the implementation in the front-end screen:

```
body: FutureBuilder(
            future: productService.getFavoriteProduct(user.uid),
            builder:
                (BuildContext context, AsyncSnapshot<List<Product?>> snapshot) {
              final products = productService.userLikedProducts;
              if (products.isEmpty) {
                return Text('Vacío');
              }
              if (products.isNotEmpty) {
                print(products.length);
                return ListView.builder(
                    itemCount: products.length,
                    itemBuilder: (BuildContext context, int index) {
                      final product = products[index];
                      return ListTile(
                        title: Text('${product.productName}'),
                      );
                    });
              }
              return const Center(child: CircularProgressIndicator());

```
This code works perfectly, however it is not realtime. So, in example when the user remove an id in the List, the change doesn't appear until the user calls the method getFavoriteProduct(). 

So I think I need to work this with a StreamBuilder. However I can't figure out how to manage the sanpshots insted. 

Has anyone ever struggle with this situation...?

Thanks in advance
![image](https://user-images.githubusercontent.com/67048178/143573455-1cea6f0a-780b-440f-bb33-19af04df753c.png)

**Comment by stuartmorgan** [comment]
See https://flutter.dev/community#community-grid for resources where you can get help with your own code; the issue tracker is for bug reports and feature requests in Flutter itself.
