### ISSUE TITLE
The option to change the "Runner" name in Runner.xcarchive when building a flavor

### ISSUE THREAD

**Issue by sems** [flutter/flutter#94250]
## Use case
It could already be an option, but I can not find any resources about it. Currently there isn't an option to build multiple 'flavors' at the same time or one after the other in bulk. This is because, to my current knowledge, each time you run the `flutter build ipa --flavor <flavor-name>` for different flavors; the `build/ios/archive/Runner.xcarchive`-file will be overwritten. The time to validate and distribute is much longer than building a single app flavor (at least in my case).

## Proposal
The possibility to change the name of the `Runner.xcarchive` file when building a specific flavor. The same that `$(APP_DISPLAY_NAME)` option does in the `info.plist` for the app-name. It is unclear to me if this is related to issue #9767

**Comment by jmagman** [comment]
Flutter doesn't hardcode this, Xcode derives this from `PRODUCT_NAME` just like any Xcode project, so set that differently per flavor/configuration.  The [flavors example app](https://github.com/flutter/flutter/tree/master/dev/integration_tests/flavors):

```
$ flutter build ipa --flavor paid
Archiving com.yourcompany.flavors.paid...
Running pod install...                                           1,414ms
Running Xcode build...
 └─Compiling, linking and signing...                      1,922ms
Xcode archive done.                                         27.7s
Built /Users/m/Projects/flutter/dev/integration_tests/flavors/build/ios/archive/Paid App.xcarchive.
```
Where `TARGET_NAME` is `Paid App`
https://github.com/flutter/flutter/blob/361d416e6abb66bf601c5a6600fbc37706bb6c14/dev/integration_tests/flavors/ios/Runner.xcodeproj/project.pbxproj#L709


https://github.com/flutter/flutter/blob/361d416e6abb66bf601c5a6600fbc37706bb6c14/dev/integration_tests/flavors/ios/Runner.xcodeproj/project.pbxproj#L220
