### ISSUE TITLE
While Installing Desktop app made with flutter in windows 7,it is showing  Create process failed ; code 216.

### ISSUE THREAD

**Issue by venky9885** [flutter/flutter#94254]
when Installing Desktop windows app made with flutter
After Installing 1st Error I got is :   This program requires Windows service pack 1 or later
How ever i have solved it using youtube video,After solving the error Second time its showing another error that is   Create process failed ; code 216...... 
check the error in below picture
![rderror](https://user-images.githubusercontent.com/59081163/143603149-05dfe55b-e17e-4ffa-b88e-091199fa65a1.png)

**Comment by stuartmorgan** [comment]
Flutter does not support 32-bit Windows machines.

**Comment by venky9885** [comment]
Pl read my issue clearly,
I am not asking about installing flutter on 32 bit windows,
I have made a desktop app using flutter which supports 32 bit architecture ,its working fine in win10,11,8, But its not Installing in windows 7 ,32-bit service pack 1

**Comment by stuartmorgan** [comment]
> Pl read my issue clearly,
> I am not asking about installing flutter on 32 bit windows

I did. 32-bit Windows is not a target that Flutter supports.

> I have made a desktop app using flutter which supports 32 bit architecture

There is no way to do this (unless you forked Flutter and built the engine from source after modifying it to work for 32-but targets, in which case the issues you are having is with your changes.)

**Comment by venky9885** [comment]
Thank you for Your reply and support
