### ISSUE TITLE
[in_app_purchase] iOS simulator test error

### ISSUE THREAD

**Issue by mdmota** [flutter/flutter#94269]
I already have my sandbox user registered. When running the App in the emulator, when I call InAppPurchase.instance.restorePurchases() this Sig in window appears.

I've already tried to enter the sandbox username and password but the console gives an error:
Instance of 'SKError'

in_app_purchase: ^1.0.9

**Comment by darshankawar** [comment]
@mdmota 
Can you provide `flutter doctor -v` and a complete minimal reproducible code sample ?

**Comment by mdmota** [comment]
![image](https://user-images.githubusercontent.com/21266037/143856452-7911a358-5f00-4653-9632-e23ab43c2cf4.png)

**Comment by mdmota** [comment]
> @mdmota Can you provide `flutter doctor -v` and a complete minimal reproducible code sample ?

![image](https://user-images.githubusercontent.com/21266037/143856530-9ab4588d-8fad-4af5-b564-ca0059618866.png)

**Comment by mdmota** [comment]
in_app_purchase: ^1.0.9

main.dart
```
if (defaultTargetPlatform == TargetPlatform.android) {
    InAppPurchaseAndroidPlatformAddition.enablePendingPurchases();
  }
  getIt.registerSingleton<AssinaturaController>(AssinaturaController());
  await SystemChrome.setPreferredOrientations(<DeviceOrientation>[DeviceOrientation.portraitUp, DeviceOrientation.portraitDown, DeviceOrientation.landscapeLeft, DeviceOrientation.landscapeRight])
      .then((_) => runZonedGuarded<Future<void>>(() async {
    runApp(MyApp());
  }, FirebaseCrashlytics.instance.recordError));



`void initState() {
.......
initListenPurchases();
}
Future<void> initListenPurchases() async {
    await GetIt.I<AssinaturaController>().initListenPurchases();
  }
```


```
@action
  Future<void> initListenPurchases() async {
    available = await inAppPurchase.isAvailable();

    if (available) {
      final Stream purchaseUpdated = InAppPurchase.instance.purchaseStream;
      subscription = purchaseUpdated.listen((purchaseDetailsList) {
        purchases.clear();
        purchases.addAll(purchaseDetailsList);
        _listenToPurchaseUpdated(purchaseDetailsList);
      }, onDone: () {
        subscription!.cancel();
      }, onError: (error) {
        //subscription!.cancel();
      });
    }

    await InAppPurchase.instance.restorePurchases();
  }
```

`

when call await InAppPurchase.instance.restorePurchases();

Emulator show dialog sigin screen(note that i didn't click on anything to purchase):
![aaa](https://user-images.githubusercontent.com/21266037/143857250-2e4ab01f-946d-464b-b804-ca5b86e66f34.jpg)

After filling in the login and password with the test data of the sandbox user, it returns the error:
![SKerror code 0b](https://user-images.githubusercontent.com/21266037/143857858-de6ff14f-25ea-46d0-a830-ef204e5e48e9.png)

**Comment by darshankawar** [comment]
@mdmota 
Can you try to login with registered test sandbox account and then try to see if you still get the same popup or no ? That way we will know if this is an issue with sandbox user registration not being recognized or coming from the plugin code.
Thanks.

**Comment by mdmota** [comment]
After a few conversations. I understand that this test with sandbox only funiocna on physical device.
When I log into the device it works.

**Comment by darshankawar** [comment]
@mdmota 
Thanks for the update. That means you are probably hitting https://github.com/flutter/flutter/issues/82398 ?

**Comment by mdmota** [comment]
The sandbox login window is normal.
My implementation issues were resolved by switching lib from inAppPurchases to RevenueCat
