### ISSUE TITLE
Docs: WidgetOfTheWeek video for Flexible: Code uses empty containers that don't render

### ISSUE THREAD

**Issue by chonghorizons** [flutter/flutter#94270]
From the screenshot below, from https://api.flutter.dev/flutter/widgets/Flexible-class.html

The video uses

```lang-dart
  Column: children: [
    Container(color: Colors.cyan),
    Container(color: Colors.teal),
    Container(color: Colors.indigo),
  ]
```

Which is very clear, but unfortunately, empty Containers don't render. So, what one gets is an empty screen when this code is tried.

![Screenshot 2021-11-26 16 51 24](https://user-images.githubusercontent.com/36284839/143663029-e2ce533c-d83c-4151-a04c-5af1d0550e7d.png)

**Comment by chonghorizons** [comment]
I made a dartpad of this to demonstrate
https://dartpad.dev/?id=fdd8c049f84e3329dcdbf515f40f3c9e&null_safety=true

**Comment by chonghorizons** [comment]
Suggested Fix: Add a text Widget as the child of Container. This is what is done in the great *Understanding Layout* page when describing Flexible and how it is rendered. https://docs.flutter.dev/development/ui/layout/constraints#:~:text=of%20its%20children.-,Example%2027,-content_copy

Like

Hello!
Welcome!
Greetings!

**Comment by r-mzy47** [comment]
Hello. in this  

> From the screenshot below, from https://api.flutter.dev/flutter/widgets/Flexible-class.html
> 
> The video uses
> 
> ```
>   Column: children: [
>     Container(color: Colors.cyan),
>     Container(color: Colors.teal),
>     Container(color: Colors.indigo),
>   ]
> ```
> 
> Which is very clear, but unfortunately, empty Containers don't render. So, what one gets is an empty screen when this code is tried.
> 
> ![Screenshot 2021-11-26 16 51 24](https://user-images.githubusercontent.com/36284839/143663029-e2ce533c-d83c-4151-a04c-5af1d0550e7d.png)

Hello. you should specify your Containers size. by default, the height of a Container inside the column is zero. but by wrapping the containers in flexible (like the screenshot) the column height is filled by Containers.

**Comment by chonghorizons** [comment]
Thanks! I tried this again with Flexibles and empty containers and it works [DartPad](https://dartpad.dev/4c873c8bdfadc18641507a43d199c6ea).

I could have sworn it wasn't rendering right before, even wrapped with `Flexibles`. But, it's working now.
