### ISSUE TITLE
[webview_flutter] google pay doesn't work in webview

### ISSUE THREAD

**Issue by picaoao** [flutter/flutter#94289]
I'm currently running stripe checkout embedded in a **webview_flutter** widget.

While apple pay works (on iOS device), **google pay doesn't work** (on Android), and the pay button doesn't show.

From the logs (see below), it seems some browser API is not present within the embedded view browser.

## Steps to Reproduce

Hard to come with a way of triggering the issue since I'm running stripe checkout (which does the job of invoking google pay API) in JS.
Anyway the error seems clear with the log output below.

Let me know if you still need a way of reproducing it to understand what is going on.

**Expected results:** 

The Google Pay button is showed, similar to the Apple Pay button when running on iOS.

**Actual results:**

No Google Pay button is showed.
I get the following logs in console.

<details>
  <summary>Logs</summary>

```
Unrecognized feature: 'payment'.", source: https://js.stripe.com/v3/fingerprinted/js/stripe-66f0bb408972c349950a6b99c765bf9d.js (1)
```

```
Uncaught ReferenceError: PaymentRequest is not defined", source: https://pay.google.com/gp/p/js/pay.js (265)
```

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6.1 20G224 darwin-arm, locale en-PT)
    • Flutter version 2.5.3 at /Users/ricardo.oliveira/dev/flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision 18116933e7 (6 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/ricardo.oliveira/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.0)
    • VS Code at /Users/ricardo.oliveira/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.55

• No issues found!

```

</details>

**Comment by stuartmorgan** [comment]
This is apparently a limitation imposed by Google Play; see https://stackoverflow.com/questions/55869022/android-chrome-webview-access-to-google-pay-is-not-working

The plugin simply provides access to the system web view from Flutter; it is subject to whatever limitations the webview is.
