### ISSUE TITLE
[tool_crash] YamlException

### ISSUE THREAD

**Issue by thirtsa-t** [flutter/flutter#94297]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
YamlException
```
#0      Parser.parse (package:yaml/src/parser.dart:59:7)
#1      Loader.load (package:yaml/src/loader.dart:51:25)
#2      loadYamlDocument (package:yaml/yaml.dart:69:25)
#3      loadYamlNode (package:yaml/yaml.dart:54:5)
#4      loadYaml (package:yaml/yaml.dart:41:5)
#5      FlutterManifest.createFromString (package:flutter_tools/src/flutter_manifest.dart:42:47)
#6      FlutterManifest.createFromPath (package:flutter_tools/src/flutter_manifest.dart:36:28)
#7      ManifestAssetBundle.build (package:flutter_tools/src/asset.dart:291:72)
<asynchronous suspension>
#8      ResidentWebRunner._updateDevFS (package:flutter_tools/src/isolated/resident_web_runner.dart:492:26)
<asynchronous suspension>
#9      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:283:41)
<asynchronous suspension>
#10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19042.1348], locale en-US)
    • Flutter version 2.5.3 at D:\flutter_windows_2.5.2-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (6 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.62.3)
    • VS Code at C:\Users\User\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.28.0

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.45
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 96.0.1054.29

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 3595343e20a61ff16d14e8ecc25f364276bb1b8b
### Plugins
image_picker-0.8.4+4
image_picker_for_web-2.1.4
path_provider-2.0.7
path_provider_android-2.0.8
path_provider_ios-2.0.7
path_provider_linux-2.1.2
path_provider_macos-2.0.3
path_provider_windows-2.0.4

**Comment by innos123** [comment]
> ## Command
> ```
> flutter run
> ```
> 
> ## Steps to Reproduce
> 1. ...
> 2. ...
> 3. ...
> 
> ## Logs
> YamlException
> 
> ```
> #0      Parser.parse (package:yaml/src/parser.dart:59:7)
> #1      Loader.load (package:yaml/src/loader.dart:51:25)
> #2      loadYamlDocument (package:yaml/yaml.dart:69:25)
> #3      loadYamlNode (package:yaml/yaml.dart:54:5)
> #4      loadYaml (package:yaml/yaml.dart:41:5)
> #5      FlutterManifest.createFromString (package:flutter_tools/src/flutter_manifest.dart:42:47)
> #6      FlutterManifest.createFromPath (package:flutter_tools/src/flutter_manifest.dart:36:28)
> #7      ManifestAssetBundle.build (package:flutter_tools/src/asset.dart:291:72)
> <asynchronous suspension>
> #8      ResidentWebRunner._updateDevFS (package:flutter_tools/src/isolated/resident_web_runner.dart:492:26)
> <asynchronous suspension>
> #9      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:283:41)
> <asynchronous suspension>
> #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
> <asynchronous suspension>
> ```
> 
> ```
> [✓] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19042.1348], locale en-US)
>     • Flutter version 2.5.3 at D:\flutter_windows_2.5.2-stable\flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision 18116933e7 (6 weeks ago), 2021-10-15 10:46:35 -0700
>     • Engine revision d3ea636dc5
>     • Dart version 2.14.4
> 
> [✗] Android toolchain - develop for Android devices
>     ✗ Unable to locate Android SDK.
>       Install Android Studio from: https://developer.android.com/studio/index.html
>       On first launch it will assist you in installing the Android SDK components.
>       (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
>       If the Android SDK has been installed to a custom location, please use
>       `flutter config --android-sdk` to update to that location.
> 
> 
> [✓] Chrome - develop for the web
>     • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
> 
> [✓] Android Studio (version 2020.3)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
> 
> [✓] VS Code (version 1.62.3)
>     • VS Code at C:\Users\User\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension version 3.28.0
> 
> [✓] Connected device (2 available)
>     • Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.45
>     • Edge (web)   • edge   • web-javascript • Microsoft Edge 96.0.1054.29
> 
> ! Doctor found issues in 1 category.
> ```
> 
> ## Flutter Application Metadata
> **Type**: app **Version**: 1.0.0+1 **Material**: true **Android X**: false **Module**: false **Plugin**: false **Android package**: null **iOS bundle identifier**: null **Creation channel**: stable **Creation framework version**: [3595343](https://github.com/flutter/flutter/commit/3595343e20a61ff16d14e8ecc25f364276bb1b8b)
> 
> ### Plugins
> image_picker-0.8.4+4 image_picker_for_web-2.1.4 path_provider-2.0.7 path_provider_android-2.0.8 path_provider_ios-2.0.7 path_provider_linux-2.1.2 path_provider_macos-2.0.3 path_provider_windows-2.0.4

**Comment by danagbemava-nc** [comment]
Hi @thirtsa-t, thanks for filing the issue.

Please provide your `pubspec.yaml`.

Thank you
