### ISSUE TITLE
[Proposal] Allow customisation of `TabBar` `InkWell`

### ISSUE THREAD

**Issue by nayeemtby** [flutter/flutter#94290]
## Use case
When decorating the indicator in TabBar developers may need a way to make the InkWell of the same shape as the indicator.
Video of Problem: https://youtu.be/S2qBpaE2wOo
The Indicator has rounded corners but the InkWell does not.

## Proposal
Add a way to make the indicator shape match the InkWell shape, like a parameter to pass the border Radius, or the shape.

**Comment by innos123** [comment]
> ## Use case
> When decorating the indicator in TabBar developers may need a way to make the InkWell of the same shape as the indicator. Video of Problem: https://youtu.be/S2qBpaE2wOo The Indicator has rounded corners but the InkWell does not.
> 
> ## Proposal
> Add a way to make the indicator shape match the InkWell shape, like a parameter to pass the border Radius, or the shape.
