### ISSUE TITLE
Unify Android artifact / version checks

### ISSUE THREAD

**Issue by johnmccutchan** [flutter/flutter#9429]
Currently there are duplicated checks (e.g. java location and version) in `lib/src/android/android_workflow.dart` and `lib/src/android/android_studio.dart`. 

There should be one canonical Java locator / version checker that is shared between all components that need it (Android build steps, Flutter doctor checks, etc).

**Comment by johnmccutchan** [comment]
Related https://github.com/flutter/flutter/issues/9134

**Comment by johnmccutchan** [comment]
@jakobr-google @mit-mit

**Comment by zoechi** [comment]
Related #10351

**Comment by pedromassangocode** [comment]
Assuming that the files in question are:
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_studio.dart
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_workflow.dart

This issue is still valid.

**Comment by andrewkolos** [comment]
Closing as superseded by https://github.com/flutter/flutter/issues/124252 as I didn't realize this issue existed until I already added a mention of #124252 in [some code docs.](https://github.com/flutter/flutter/pull/124233/files#diff-065ee95a7a011b1987cb5522cf9b8c5b802410e117d92ffc0359d6950df6129fR475)
