### ISSUE TITLE
analyzer SDK and meta SDK have a conflict when i use command line  “flutter pub run build_runner build”

### ISSUE THREAD

**Issue by feels-good** [flutter/flutter#94303]
when i use command line  “flutter pub run build_runner build”,there is a conflict from analyzer SDK and meta SDK , but they are  no configured in my project. my config are this 
![image](https://user-images.githubusercontent.com/65146067/143735996-1d5edc60-4820-4ef1-be75-045680c8fbbe.png)
and track log is this
![image](https://user-images.githubusercontent.com/65146067/143736071-6355e1ba-35b3-41f3-91c6-a37eec93dc8e.png)
having hope for response!

**Comment by feels-good** [comment]
flutter sdk version is 2.5.1

**Comment by darshankawar** [comment]
@feels-good 
Can you try to upgrade to latest stable and see if it helps ?
Also use the latest version of https://pub.dev/packages/build_runner/install
