### ISSUE TITLE
Support builder history view on flutter build dashboard

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#94319]
The builder history is lost when moving flaky tests from prod to staging. This makes it a lot more difficult to investigate different failure modes, and look at a history (or lack thereof) of flakes.

E.g.: https://ci.chromium.org/p/flutter/builders/staging/Linux_android%20flutter_gallery__back_button_memory?limit=100

vs. 

https://ci.chromium.org/p/flutter/builders/prod/Linux_android%20flutter_gallery__back_button_memory (which no 404s).

/cc @CaseyHillers @godofredoc

**Comment by CaseyHillers** [comment]
Is there an issue with using https://flutter-dashboard.appspot.com/#/build? The Flutter build dashboard sorts the builds by the commits and their run order, and MILO only sorts by the run order.

**Comment by CaseyHillers** [comment]
To be explicit, this isn't an issue in the build dashboard as it'll correctly link you to the build page (whether it's staging or prod)

**Comment by zanderso** [comment]
In the flaky test workflow, the bot puts links to builds in issues, for example https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android%20flutter_gallery__back_button_memory/995/overview.

That page has a link to https://ci.chromium.org/p/flutter/builders/prod/Linux_android%20flutter_gallery__back_button_memory, which is now dead.

https://ci.chromium.org/p/flutter/builders/prod/Linux_android%20flutter_gallery__back_button_memory is a lot easier to use than https://flutter-dashboard.appspot.com/#/build since you just follow the link that's already on the build page instead of switching to a new tab. https://ci.chromium.org/p/flutter/builders/prod/Linux_android%20flutter_gallery__back_button_memory also has more information displayed like the commit hash, the commit time, the build number, etc. that is hidden in https://flutter-dashboard.appspot.com/#/build.

I think it would be good to revisit the decision to conflate "staging" with "flaky" since we seem to be introducing a lot of complexity to achieve that, and I don't fully understand what the advantages are. Why can't we keep tests marked flaky running on prod? /cc @godofredoc @keyonghan

**Comment by CaseyHillers** [comment]
> I think it would be good to revisit the decision to conflate "staging" with "flaky" since we seem to be introducing a lot of complexity to achieve that, and I don't fully understand what the advantages are. Why can't we keep tests marked flaky running on prod? /cc @godofredoc @keyonghan

There's discussion in go/flutter-staging-infra. The core reasons we moved are
1. Flutter's LUCI metrics were getting noise from the flaky tests, which is why we moved them to staging
2. This approach minimizes the environments infra has to maintain, which in turn should reduce complexity (infra only needs to maintain prod, staging, try for metrics purposes instead of cloning each for a flaky tests version)
3. To simplify the infra configs, ci.yaml should contain the staging configs as well
  A. There's still complexity here as I haven't finished migrating the devicelab_staging starlark into the framework's ci.yaml

@keyonghan what do you think about updating the flaky issue bot to point to the flutter dashboard? We can add a query parameter to filter by the target name.

**Comment by zanderso** [comment]
Keeping noise out of LUCI metrics sounds like a goal that could be achieved a different way. For example we could do a better job of categorizing LUCI/infra vs. build/test steps.

However, I don't really understand why making the LUCI metrics look clean is a goal by itself. Why do we need to filter noise out of the LUCI metrics?

**Comment by keyonghan** [comment]
Is it possible we keep the console for both staging and prod?

**Comment by keyonghan** [comment]
Flutter build dashboard shows builds both in staging and prod pools, and it would be handy to have a direct query support in url to show historical data. Updated the title to reflect that.

Could you help with the query support @CaseyHillers?
After that, I will update the flake bot to point to new links.

**Comment by CaseyHillers** [comment]
This is available via https://flutter-dashboard.appspot.com/#/build?taskFilter=Mac_android%20microbenchmarks

The target name will need to be url encoded.
