### ISSUE TITLE
InteractiveViewer needs ability to programatically set scale scroll speed

### ISSUE THREAD

**Issue by longtimedeveloper** [flutter/flutter#94315]
@justinmc

## Use case
When using the InteractiveViewer to display large images (height & width), when the mouse scroll wheel is moved, the scale jumps rapidly between detents of the mouse scroll wheel. 

## Cause
Mouse scroll wheel vertical movement is controlled using the Control Panel Applet, Mouse, Wheel, Vertical Scrolling setting.

The default value on Windows is 3.

If I change that value to 1, the jumpy scaling is reduced.  However, the vertical scrolling in all other applications such as an Internet Browser is greatly reduced.  

## Alternate 
I tried to limit the mouse wheel scrolling by using JavaScript.  Unfortunately, this didn't work.  The solution works on plain HTML, CSS, and JavaScript pages, but not a Flutter Web app.

## Proposal
To the InteractiveViewer widget, add a user-settable double property `mouseWheelSensitivity` that either increases or decreases the effective delta changes between mouse wheel movements.

`mouseWheelSensitivity`  should default to 1.0 so that this enhancement would not break any applications.

When testing, I recommend using a large image 2570 x 1926.  The below link is to a game board that I'm using in a game I'm writing.  After downloading this image, open it in your favorite editor and save it as a JPG image as the PNG is 12 MB.  The JPG comes in a 2.8 MB.

I recommend testing using different screen resolutions so you can see the user experience when scrolling the mouse wheel with various screen resolutions and `mouseWheelSensitivity` settings.

[https://github.com/tim-koehler/ScotlandYard/blob/master/resources/map.png](https://github.com/tim-koehler/ScotlandYard/blob/master/resources/map.png)

**Comment by maheshmnj** [comment]
Hi @longtimedeveloper,

There is a similar issue describing this case https://github.com/flutter/flutter/issues/76765, Please follow up there for further updates, Closing this issue as a duplicate. If you disagree feel free to write in the comments and I will reopen it.

Thank you.

**Comment by longtimedeveloper** [comment]
@maheshmnj, wow, that issue has been hanging around for almost a year.
