### ISSUE TITLE
ClassCastException: android.view.AbsSavedState$1 cannot be cast to io.flutter.embedding.android.FlutterSplashView$SavedState

### ISSUE THREAD

**Issue by songhai** [flutter/flutter#94329]
1、when I  from flutter1.22.3 upgrade  to   flutter2.5.3 ，I  encountered two similar crashes  probabilistic happen，crash log is below
2、other info：My  Activity   extends   the   FlutterFragmentActivity
3、About this crash, I review the flutter source code, maybe because the FlutterFragmentActivity contains a non-random integer as a viewid，example，if  the viewid equals  the FlutterView's id  or the  FlutterSplashView‘s id，the This crash is going to happen
4、In addition recommendations：I find FlutterSplashView class's onRestoreInstanceState method is not robust enough，I recommend you look at the Android Framework's TextView 's onRestoreInstanceState implementation 
```
    @Override
    public void onRestoreInstanceState(Parcelable state) {
        if (!(state instanceof SavedState)) {
            super.onRestoreInstanceState(state);
            return;
        }

        SavedState ss = (SavedState) state;
        super.onRestoreInstanceState(ss.getSuperState());
        ...........
        ...........
      }
```

<details>
<summary>crash log</summary>

```
-------------------------the first  log   below-------------------------
---java.lang.ClassCastException: android.view.AbsSavedState$1 cannot be cast to io.flutter.embedding.android.FlutterSplashView$SavedState
io.flutter.embedding.android.FlutterSplashView.onRestoreInstanceState(FlutterSplashView.java:102)
android.view.View.dispatchRestoreInstanceState(View.java:20065)
android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3902)
android.view.View.restoreHierarchyState(View.java:20043)
androidx.fragment.app.Fragment.restoreViewState(Fragment.java:573)
androidx.fragment.app.FragmentStateManager.restoreViewState(FragmentStateManager.java:346)
androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1354)
androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1432)
androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1495)
androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2617)
androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2569)
androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433)
android.app.Activity.performStart(Activity.java:7986)
android.app.ActivityThread.handleStartActivity(ActivityThread.java:3528)
android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:226)
android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:206)
android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:178)
android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:102)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:2229)
android.os.Handler.dispatchMessage(Handler.java:107)
android.os.Looper.loop(Looper.java:238)
android.app.ActivityThread.main(ActivityThread.java:7798)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:512)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)


-------------------------the  second  log   below-------------------------

---java.lang.ClassCastException: android.view.View$BaseSavedState cannot be cast to io.flutter.embedding.android.FlutterSplashView$SavedState
io.flutter.embedding.android.FlutterSplashView.onRestoreInstanceState(FlutterSplashView.java:102)
android.view.View.dispatchRestoreInstanceState(View.java:21048)
android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4204)
android.view.View.restoreHierarchyState(View.java:21026)
androidx.fragment.app.Fragment.restoreViewState(Fragment.java:573)
androidx.fragment.app.FragmentStateManager.restoreViewState(FragmentStateManager.java:346)
androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1354)
androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1432)
androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1495)
androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2617)
androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2569)
androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1450)
android.app.Activity.performStart(Activity.java:8382)
android.app.ActivityThread.handleStartActivity(ActivityThread.java:4113)
android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:235)
android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:215)
android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:187)
android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:105)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:2532)
android.os.Handler.dispatchMessage(Handler.java:109)
android.os.Looper.loop(Looper.java:228)
android.app.ActivityThread.main(ActivityThread.java:8731)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:613)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1085)

```

</details>

**Comment by jukiginanjar** [comment]
I also have the same issue, please help to fix this 🙏

**Comment by darshankawar** [comment]
@songhai 
This should have been fixed already per this old issue, https://github.com/flutter/flutter/issues/47635 and maybe you need to add pro-guard rules in gradle file to make it work. See [this](https://github.com/flutter/flutter/issues/47635#issuecomment-596796532) issue comment for your reference and see if it helps to resolve.

**Comment by songhai** [comment]
> 



> @songhai This should have been fixed already per this old issue, #47635 and maybe you need to add pro-guard rules in gradle file to make it work. See [this](https://github.com/flutter/flutter/issues/47635#issuecomment-596796532) issue comment for your reference and see if it helps to resolve.

#47635   crash log is：  android.view.View$BaseSavedState cannot be cast to d.b.b.a.i$d      ，but  my log  is  different，my  log  not contain  d.b.b.a.i$d

**Comment by songhai** [comment]
> I also have the same issue, please help to fix this 🙏

Can you show me your key crash log，Let me make sure you have the same problem AS me

**Comment by songhai** [comment]
> pro-guard rules

it is unrelated with  pro-guard rules，and it is probabilistic happen

**Comment by darshankawar** [comment]
> when I from flutter1.22.3 upgrade to flutter2.5.3

Can you check [this](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects) migration document and see if it helps ?

**Comment by songhai** [comment]
> 

I  checked，but  not   help  me；  can  you  read  my  info  key 3、 and  key 4  ，then  check  the  flutter  java  framewok， OK ？  THANKS

**Comment by jukiginanjar** [comment]
Hi sorry, I think my issue is similar to this https://github.com/flutter/flutter/issues/48016

**Comment by darshankawar** [comment]
> 3、About this crash, I review the flutter source code, maybe because the FlutterFragmentActivity contains a non-random integer as a viewid，example，if the viewid equals the FlutterView's id or the FlutterSplashView‘s id，the This crash is going to happen

@songhai Can you provide us a concrete example showing this case so that we can properly analyze this behavior ?

**Comment by songhai** [comment]
> 
this is my  code
```
public class FlutterBaseActivity extends FlutterFragmentActivity {
 

    @Override
    public void onCreate(@Nullable Bundle savedInstanceState, @Nullable PersistableBundle persistentState) {
        super.onCreate(savedInstanceState, persistentState);
    }

    @Override
    public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);//1.17需要手工注册

    }



    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
    }



}


```


The  crashes probabilistic happen，not  100% crash，The probability is 2 in 10000；    so  I write the  3 and 4，i  hope you  improve  the  code  robust。

4、In addition recommendations：I find FlutterSplashView class's onRestoreInstanceState method is not robust enough，I recommend you look at the Android Framework's TextView 's onRestoreInstanceState implementation
```
Android TextView souce code below:  it can robust enough
    @Override
    public void onRestoreInstanceState(Parcelable state) {
        if (!(state instanceof SavedState)) {
            super.onRestoreInstanceState(state);
            return;
        }

        SavedState ss = (SavedState) state;
        super.onRestoreInstanceState(ss.getSuperState());
        ...........
        ...........
      }
```

**Comment by darshankawar** [comment]
> public class FlutterBaseActivity extends FlutterFragmentActivity {

@songhai 
I see that you are extending from `FlutterFragmentActivity` but I think since Flutter 2.0, you'll need to extend from `FlutterActivity`. See this document again https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects#full-flutter-app-migration

**Comment by songhai** [comment]
> 
i use  io.flutter.embedding.android.FlutterFragmentActivity not from the package. io.flutter.app,   when i use flutter 1.22.6 version i user  io.flutter.embedding.android.FlutterFragmentActivity too, the crash not occur， and   i  need fragment ，i  must use FlutterFragmentActivity 。


You give me the  url is  from io.flutter.app to io.flutter.embedding.android to migration，the content of this url  has nothing to do with this problem

**Comment by darshankawar** [comment]
@songhai 
Thanks for the details and patience. I am trying to look at the crash log you provided in detail. Is the crash coming from production mode or in debug mode ?

**Comment by songhai** [comment]
> production mode
Coming from production mode，not 100% crash，The probability is 2 in 10000

**Comment by darshankawar** [comment]
Keeping it open for further investigation.

/cc @blasten

**Comment by gyh124** [comment]
I got the same crash，Can you solve，flutter sdk2.5.1

BRAND=Redmi
DEVICE=lmipro
MODEL=Redmi K30 Pro Zoom Edition
PRODUCT=lmipro
DISPLAY=RKQ1.200826.002 test-keys
CPU_ABI=arm64-v8a
AndroidOS=11
DATE=2021-12-14-11:17:20
Foreground=false
java.lang.ClassCastException: android.view.View$BaseSavedState cannot be cast to io.flutter.embedding.android.FlutterSplashView$SavedState
at io.flutter.embedding.android.FlutterSplashView.onRestoreInstanceState(FlutterSplashView.java:102)
at android.view.View.dispatchRestoreInstanceState(View.java:20856)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4008)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4014)
at android.view.View.restoreHierarchyState(View.java:20834)
at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2185)
at android.app.Activity.onRestoreInstanceState(Activity.java:1737)
at android.app.Activity.performRestoreInstanceState(Activity.java:1690)
at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1357)
at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3543)
at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2108)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:236)
at android.app.ActivityThread.main(ActivityThread.java:7876)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
