### ISSUE TITLE
Draw Text inverting background video pixels?

### ISSUE THREAD

**Issue by duzenko** [flutter/flutter#94323]
I have a flutter widget with a Stack consisting a background video player and some flutter widgets (Text, etc) on top of it.

The text is white and looks good when the video is dart, however sometimes video is light and the text gets lost.

I realize that I can put a semi-transparent rectangle under the text, however it would be much nicer to invert background pixels when drawing text itself.

I think Canvas's blend operations can't be used here as the video is a separate widget.

**Comment by maheshmnj** [comment]
Hi @duzenko, This issue doesn't seem to describe a bug or a feature request in the flutter framework. if You need help with your code please try using one of out forums at https://flutter.dev/community.

Closing as this isn't an issue with flutter if you disagree feel free to write in the comments and I will reopen it.

Thank you.
