### ISSUE TITLE
Will it possible to set  frame rate in image for gif file in the future?

### ISSUE THREAD

**Issue by xibici** [flutter/flutter#94334]
sorry,my english is pool,hope every can understand what i am talking about.

Will it possible to add a new params for Image.network function to set  frame rate when flutter loading a gif picture in the future?
i know when using some packages  can set frame rate ,but it is in local gif file,but can not set in base64 code gif and network gif.

Because it is showing crazy frame rate in specific gif.

**Comment by darshankawar** [comment]
@xibici 
Are you experiencing the frame rate issue on mobile or web ?
Is the GIF playing too fast or slow or stops after some time ?
Can you provide us an example of the GIF along with a sample code and `flutter doctor -v` ?
Thanks.
