### ISSUE TITLE
iphone release build is showing wrong icons in actual device. But in emulator it is showing correct icons

### ISSUE THREAD

**Issue by Manjunath093** [flutter/flutter#94331]
iphone release build is showing wrong icons in emulator it is showing correct icons
expected icons is forward_ios_arrow
but wrong icon is getting folder_special

flutter doctor -v results

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-x64, locale en-GB)
• Flutter version 2.5.3 at /Users/manjup/Downloads/flutter
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision 1811693 (6 weeks ago), 2021-10-15 10:46:35 -0700
• Engine revision d3ea636dc5
• Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
• Android SDK at /Users/manjup/Library/Android/sdk
✗ cmdline-tools component is missing
Run path/to/sdkmanager --install "cmdline-tools;latest"

[✓] Chrome - develop for the web
• Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin can be installed from:
```

contents inside file flutter/bin/cache/material_fonts.stamp is below 

flutter_infra_release/flutter/fonts/bd151aa3c2f7231344411a01dba4ef61b3cd56b2/fonts.zip

**Comment by darshankawar** [comment]
@Manjunath093 
Can you provide a minimal complete reproducible code sample along with icons you are using that are not showing up properly ?

**Comment by Manjunath093** [comment]
here is a piece of code i am using for icons
Icon(
                Icons.arrow_forward_ios,
                size: 50,
                color: ColorConstants.chathams_blue.withOpacity(0.7),
              )

**Comment by darshankawar** [comment]
@Manjunath093 
Tried above code snippet using latest stable and master on iphone device (OS 14.4.1) in release mode and saw no issues. The icon is rendered properly and as-is.

<img width="329" alt="Screenshot 2021-12-01 at 11 16 27 AM" src="https://user-images.githubusercontent.com/67046386/144180434-b52b53a4-8c03-4a97-9e94-8e50601b0475.png">
