### ISSUE TITLE
[Android Crash] at dart::Dart::Init, on gaming phones

### ISSUE THREAD

**Issue by lengzds** [flutter/flutter#94337]
There is an online crash in our application caused by flutter. We think it may be accidental, or maybe it only reproduces under certain situations. We use FlutterFragment in our Application. Now it crashes when the application is opened.

There are only the following types of mobile phones that have problems. All of them are gaming phones.
- ASUS-I005DA
- ASUS-I005DB
- ZTERED MAGIC 5G
- Lenovo L79031
- NX669J
- M2007J1SC

<details>
  <summary>Logs</summary>

This is my flutter sdk info:

```
Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18116933e7 (6 weeks ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4
```

This is the crash log:

```
signal 11 code 1 at address 0x4
 backtrace:
 #0 pc 0x43e85a /data/app/**/lib/arm/libflutter.so
 #1 pc 0x51d84a /data/app/**/lib/arm/libflutter.so
 #2 pc 0x19316a /data/app/**/lib/arm/libflutter.so
 #3 pc 0x19938e /data/app/**/lib/arm/libflutter.so
 #4 pc 0x159830 /data/app/**/lib/arm/libflutter.so
 basic:
 ABI: arm pid: 7407  tid: 7407
```

This is what I parsed:

```
#0 pc 0x43e85a dart::Dart::Init(unsigned char const*, unsigned char const*, _Dart_Isolate* (*)(char const*, char const*, char const*, char const*, Dart_IsolateFlags*, void*, char**), bool (*)(void**, char**), void (*)(void*, void*), void (*)(void*, void*), void (*)(void*), void (*)(), void* (*)(char const*, bool), void (*)(unsigned char**, int*, void*), void (*)(void const*, int, void*), void (*)(void*), bool (*)(unsigned char*, int), _Dart_Handle* (*)(), bool, Dart_CodeObserver*)
/b/s/w/ir/cache/builder/src/out/android_release/../../third_party/dart/runtime/vm/object.cc:2608
#1 pc 0x51d84a Dart_Initialize
/b/s/w/ir/cache/builder/src/out/android_release/../../third_party/dart/runtime/vm/dart_api_impl.cc:1212
#2 pc 0x19316a DartVMInitializer::Initialize(Dart_InitializeParams*)
/b/s/w/ir/cache/builder/src/out/android_release/../../flutter/runtime/dart_vm_initializer.cc:21
#3 pc 0x19938e flutter::Shell::Create(flutter::PlatformData const&, flutter::TaskRunners, flutter::Settings, std::__1::function<std::__1::unique_ptr<flutter::PlatformView, std::__1::default_delete<flutter::PlatformView> > (flutter::Shell&)> const&, std::__1::function<std::__1::unique_ptr<flutter::Rasterizer, std::__1::default_delete<flutter::Rasterizer> > (flutter::Shell&)> const&, bool)
/b/s/w/ir/cache/builder/src/out/android_release/../../flutter/shell/common/shell.cc:142
#4 pc 0x159830 std::__1::unique_ptr<flutter::Shell, std::__1::default_delete<flutter::Shell> >::release()
/b/s/w/ir/cache/builder/src/out/android_release/../../third_party/libcxx/include/memory:2583
```
</details>

<details>
<summary>Other Info</summary>

There is some device info and java logcat data:

[pre_d_device_info.txt](https://github.com/flutter/flutter/files/7618053/pre_d_device_info.txt)

[pre_p_status.txt](https://github.com/flutter/flutter/files/7618063/pre_p_status.txt)
[pre_d_logcat_log.txt](https://github.com/flutter/flutter/files/7618057/pre_d_logcat_log.txt)

[pre_d_logcat_log.txt](https://github.com/flutter/flutter/files/7618060/pre_d_logcat_log.txt)
[pre_p_status.txt](https://github.com/flutter/flutter/files/7618061/pre_p_status.txt)

</details>

**Comment by danagbemava-nc** [comment]
Hi @lengzds, thanks for filing the issue. 

Can you reproduce this crash locally? 

If so kindly provide a complete minimal reproducible code sample so that we can better address this issue. 

Thank you

**Comment by lengzds** [comment]
> If so kindly provide a complete minimal reproducible code sample so that we can better address this issue.

I found a nx659 phone and tried many times, but I can't reproduce this crash locally.

**Comment by danagbemava-nc** [comment]
Hi @lengzds, please provide the full output of `flutter doctor -v`. 

> We use FlutterFragment in our Application

Can you provide the sample code that uses `FlutterFragment`? 

If you could also provide any configuration files such as `build.gradle`, `AndroidManifest.xml` that has any special configuration you might be using, that may be helpful. 

Please provide you `pubspec.yaml` as well.

Thank you

**Comment by lengzds** [comment]
flutter doctor -v
```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.5.3 at /Users/zhangdaishuai/fvm/versions/2.5.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (7 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/zhangdaishuai/Library/Android/sdk
    • Platform android-31, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Community Edition (version 2018.1.6)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (2 available)
    • TAS AN00 (mobile) • XPL5T19A26011401 • android-arm64  • Android 10 (API 29)
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 96.0.4664.55
```

How we use Fragment?

We will add FlutterFragment into our FragmentPagerAdapter at MainActivity.onCreate.

![image](https://user-images.githubusercontent.com/19568198/144181496-09338a4a-5800-4405-b15b-0ee5cc45f1cb.png)


AndroidManifest like this, we add many intent-filter to our MainActivity, but I think It has nothing to do with this.

![image](https://user-images.githubusercontent.com/19568198/144181941-27b6ea6d-7a5f-4fba-8092-d35802840556.png)

This is the settings related to flutter in the AndroidManifest:

```
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
```



This is my pubspec.yaml:

```
name: app_all
description: A new flutter module project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_rating_bar: ^3.0.0
  percent_indicator: 2.1.6
  expandable: 5.0.1
  cupertino_icons: ^0.1.2
... ...
```

At last, I must emphasize that only a few fixed mobile phones will have problems. They will crash at the app launch, caused by Dart::Init.

**Comment by danagbemava-nc** [comment]
Hi @lengzds, it is always better to copy/paste the code sample than to send screenshots of code samples. 

Since we know that the app crashes at launch, can you please provide a complete sample in a repo that crashes at launch? 

Please provide the versions of `android` the affected devices are running on as well. 

Thank you
