### ISSUE TITLE
Issue from website page Material Components Widgets

### ISSUE THREAD

**Issue by yehoan** [flutter/flutter#94330]
From URL: https://www.flutterchina.club/widgets/materialdesign.md  
link is empty   
![image](https://user-images.githubusercontent.com/22631753/143835736-dc324b54-56e8-4955-9e49-3ca1eeeebd40.png)

**Comment by danagbemava-nc** [comment]
The flutter china website is maintained by the community, not the flutter team. 
Kindly file the issue https://github.com/flutterchina/website/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc.

Closing as this is out of scope of this issue tracker. 

Thank you
