### ISSUE TITLE
[Proposal] update roadmap for some basic 2022 items 

### ISSUE THREAD

**Issue by neiljaywarner** [flutter/flutter#94346]
- update roadmap for some basic 2022 items. Last update was february 2021, it's linked in the new learning journey on the new website (which is awesome)
- consider giving us a hint when the next official conference is

**Comment by maheshmnj** [comment]
Hi @neiljaywarner, Please keep an eye on this wiki https://github.com/flutter/flutter/wiki/Roadmap for updates. The team will update it when there are any updates to share.

Closing as this issue doesn't seem to describe a bug or feature request in flutter.

**Comment by neiljaywarner** [comment]
What I'm trying to say is that the page you linked has no 2022 info.
It's a roadmap that describes past timeline not future as 2021 and 2020 are nearly gone and gone respectively

**Comment by neiljaywarner** [comment]
@maheshmnj  see above

**Comment by maheshmnj** [comment]
> What I'm trying to say is that the page you linked has no 2022 info.

@neiljaywarner I do understand your proposal, The wiki page will be updated with the 2022 roadmap when the team thinks is the right time or if they have an update to share, We don't need to track this as an issue, The issue tracker is only to track the bugs and feature requests in the Flutter framework, so this issue has been closed.

Thank you.

**Comment by neiljaywarner** [comment]
Got it. My apologies

....sent from my phone

**Comment by maheshmnj** [comment]
Hi @neiljaywarner, just came back to let you know that the roadmap for 2022 has been updated https://github.com/flutter/flutter/wiki/Roadmap
