### ISSUE TITLE
[path_provider] getExternalStorageDirectory returns a path with "files" folder already created?

### ISSUE THREAD

**Issue by YohanWadia** [flutter/flutter#94345]
Hi,
I have a simple question about the path_provider package... from you example.

- Why is it that when I call getExternalStorageDirectory it returns me a path with a "files" folder already created? is this the expected behavior?
- isnt the ExternalStorageDirectory's path suppose to end at: **storage/emulated/0/Android/data/myAppPkgName**  ??
- is there any way I can avoid this from happening and only receive the path without that extra **files** folder being created ??

thanks

**Comment by stuartmorgan** [comment]
It returns the result of the Android `getExternalFilesDir` call, as documented. Flutter doesn't control the behavior of the Android API; if you believe that path is incorrect you'd need to file a bug against Android.
