### ISSUE TITLE
Flutter Issue During Running App

### ISSUE THREAD

**Issue by ErKaran98** [flutter/flutter#94354]
To avoid unexpected runtime failures, or future build failures, try to migrate this app to the V2 embedding.
![Untitled](https://user-images.githubusercontent.com/87260509/143909376-8f3e4ea6-1e51-484a-a5d4-0508bceda7b0.png)

**Comment by dinurymomshad** [comment]
It clearly says what needs to be done in the terminal. So why list it as issue? @ErKaran98
