### ISSUE TITLE
multi-second delay before first progress message from 'flutter run'

### ISSUE THREAD

**Issue by skybrian** [flutter/flutter#9435]
On Linux at 1df6917b60b38115a436d6bddaddacb087ea0fb4

To reproduce:
```
flutter create click
cd click
flutter run
```

I see a multi-second delay before the first progress message:

```
Launching lib/main.dart on Android SDK built for x86 64 in debug mode...
```

This is rather disconcerting, particularly when launching from within IDEA where UI responsiveness is expected. We should print the first progress message sooner, so the user knows to be patient.

**Comment by devoncarew** [comment]
PR in progress (in the flutter repo).
