### ISSUE TITLE
32 bit iOS devicelab devices need manual recovery

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#94351]
From the tree, it looks like the 32-bit iOS devices in the lab have been failing for the past few days. Typically, they require manual recovery.

**Comment by CaseyHillers** [comment]
This was blocked on https://github.com/flutter/flutter/issues/94351

I +2'd the bots latest roll in https://flutter-review.googlesource.com/c/infra/+/23720 and the bots should become available in 10 minutes.

**Comment by CaseyHillers** [comment]
These tests are running now, but they are failing on the upgrade to the latest MacOS. I filed https://github.com/flutter/flutter/issues/94480 to track as it'll require extra work outside of the infra team.
