### ISSUE TITLE
[local_auth] canCheckBiometrics returns `false` after user fails face ID and PIN authentication multiple times on iOS

### ISSUE THREAD

**Issue by jbx1** [flutter/flutter#94370]
On iOS, if Face ID fails multiple times, the device falls back to PIN authentication, and if it fails 5 times it disables it temporarily. At this point, the widget is incorrectly returning `false` to `canCheckBiometrics` during that 1 minute period or so. 

Plugin version: 1.1.8

## Steps to Reproduce

1. Install app on iOS that uses local_auth
2. Fail authentication with Face ID multiple times, until the iOS device disables biometric authentication temporarily.
3. Restart the app. 
3. Call `canCheckBiometrics` and it will return `false`. 

**Expected results:** 
canCheckBiometrics() should return `true` when biometric authentication is temporarily disabled by the iOS device for security reasons.

**Actual results:** 
`canCheckBiomterics()` returns `false` when biometric authentication is temporarily disabled by the iOS device for security reasons.

An app depending on this function will misinterpret this as no biometrics are available. 

If this is the intended behaviour of `canCheckBiometrics()` then the documentation needs to be updated to state this. Currently the doc only says: 

`Returns true if device is capable of checking biometrics`. It does not specify that it only returns what is currently available.

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on Mac OS X 10.15.7 19H15 darwin-x64, locale
    en-MT)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Community Edition (version 2020.1.2)
[✓] Connected device (2 available)
```

**Comment by danagbemava-nc** [comment]
Hi @jbx1, thanks for filing the issue. 

Please provide the version of `local_auth` you're using and a complete minimal reproducible code sample unless the `local_auth` example app is enough to reproduce this issue.

Thank you

**Comment by jbx1** [comment]
Version 1.1.8. It can be regenerated with the example app. I have updated the details.

**Comment by danagbemava-nc** [comment]
Hi @jbx1, after failing Face ID until it is disabled and restarting the app, this is what I see when I try to authenticate.
I used the example app. 

![IMG_3168](https://user-images.githubusercontent.com/88313112/144429067-12b82fbb-88bc-46b2-9f04-2ff8b32f3176.PNG)

**Comment by jbx1** [comment]
OK I think the confusing part comes from the `canCheckBiometrics` returning `false` during this period. 

I think what is happening is that during this period it returns `false`, because the list of available biometrics becomes temporarily empty.  The description is not clear that this is referring to whether it can check biometrics now, since the description is just `Returns true if device is capable of checking biometrics`.

**Comment by danagbemava-nc** [comment]
> The description is not clear that this is referring to whether it can check biometrics now, since the description is just `Returns true if the device is capable of checking biometrics`.

I guess the documentation can be updated to state that it's true unless biometrics are not available.  

> canCheckBiometrics() should return true when biometric authentication is temporarily disabled by the iOS device for security reasons.

Can you confirm that this behaviour matches native behaviour? 
Because once the biometrics is disabled, I believe the call to get available biometrics will return an empty list, which effectively means that biometrics is not available.

**Comment by jbx1** [comment]
It seems this only happens on iOS. I am not sure what happens natively. 

It could be that this is actually the intended behaviour, and it is just a question of clarifying the documentation because the description of `isDeviceSupported()` says: 
`/// Returns true if device is capable of checking biometrics or is able to fail over to device credentials.`

while `canCheckBiometrics()` says: 
` /// Returns true if device is capable of checking biometrics`

One would think that the difference between both is just whether one can fallback to device credentials, and the other will not. When in fact the difference is more subtle in case of iOS. `canCheckBiometrics()` will change its return value depending on the current device locking situation, while `isDeviceSupported()` is consistent in its return value.

**Comment by danagbemava-nc** [comment]
> while `isDeviceSupported()` is consistent in its return value.

I believe this is due to the fact that for `iOS`, the plugin code just returns `result(@YES)`, whereas `canCheckBiometrics` defers to `getAvailableBiometrics` and returns a value based on whether or not available biometrics is empty. 

Android has a different implementation for `isDeviceSupported`. 

But I believe it shouldn't be that much of an issue to update the docs so it is more clear as to what the actual behavior for `canCheckBiometrics` should be. 

I'll do some investigation to see what the native behavior is, because the plugins do try to match native behaviour. If you can also confirm, that will be appreciated.
