### ISSUE TITLE
Canvas.drawAtlas seem to not draw anything

### ISSUE THREAD

**Issue by vlidholt** [flutter/flutter#9439]
## Steps to Reproduce

Since updating Flutter to the latest version Canvas.drawAtlas seem to be broken and draw nothing. 

## Flutter Doctor

```
[✓] Flutter (on Mac OS X 10.12.3 16D32, channel master)
    • Flutter at /Users/vik/Projects/flutter
    • Framework revision b52d659406 (13 hours ago), 2017-04-17 15:44:41 -0700
    • Engine revision c24a0e5175
    • Tools Dart version 1.23.0-dev.11.7

[✓] Host Executable Compatibility
    • Downloaded executables execute on host

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/vik/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3, Build version 8E162
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.0

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2016.3.4)
    • Dart plugin version 163.13137
    • Flutter plugin version 0.1.11.1

[✓] Connected devices
    • Nexus 5X • 01023965355db590 • android-arm • Android 6.0 (API 23)

```

**Comment by eseidelGoogle** [comment]
Looks like you're testing on Android, correct?  CC @chinmaygarde

**Comment by vlidholt** [comment]
That's correct. Just tried it and can confirm it works on iOS.

**Comment by eseidelGoogle** [comment]
Maybe this broke in wiring up the Vulkan backend.  @chinmaygarde or @jason-simmons would know.

**Comment by vlidholt** [comment]
I also noticed some other drawing api:s changed (e.g. drawVertices), but no mention of the changes on the mailing list.

**Comment by eseidelGoogle** [comment]
We recently wrote and implemented a breaking changes policy: https://flutter.io/design-principles/#handling-breaking-changes which includes mailing the list, but that was only in the last couple weeks so likely some changes have slipped through without notice.  We're quickly trying to burn down the last of our planned API breaking changes: https://github.com/flutter/flutter/labels/prod%3A API stability

**Comment by Hixie** [comment]
Ah, we had no tests and no code for drawVertices and drawAtlas so we assumed it wasn't used.

cc @chinmaygarde @jason-simmons FYI.

**Comment by vlidholt** [comment]
Looks like drawAtlas only works on the iOS Simulator, not on a real device. :(

**Comment by eseidelGoogle** [comment]
@vlidholt does this block your app?

**Comment by vlidholt** [comment]
@eseidelGoogle This is a blocker for me. :/ I have a pretty large update with lot's of bug fixes for Android (including Hans' tab bar fixes) pending that would be nice to get out.

**Comment by eseidelGoogle** [comment]
Can do.  Thanks for being clear.

**Comment by jason-simmons** [comment]
I tried an example using drawAtlas on Android and got an assertion failure in SkImage_Gpu::asTextureProxyRef.

This happens because the image decoder is constructing texture images on the IO thread using the resource GrContext and then handing the images to the GPU thread which tries to render them using a different context.  Unlike drawImage/drawImageRect, the drawAtlas code path is checking for the difference in contexts.

The engine needs to use SkCrossContextImageData

**Comment by eseidelGoogle** [comment]
In progress in https://github.com/flutter/engine/pull/3616.

**Comment by eseidelGoogle** [comment]
@vlidholt our understanding from Skia is we can't get this done for another few weeks as the API provided doesn't fit our needs.  We intend to fix this soon, but it not for a few weeks at the earliest.

**Comment by vlidholt** [comment]
Thanks for the update!

**Comment by chinmaygarde** [comment]
https://github.com/flutter/engine/pull/3616 was abandoned due to texture memory managed issues. After further discussions with the Skia team, a new API is being built to solve this. The patches for the same are under review at https://skia-review.googlesource.com/c/14180/.

**Comment by eseidelGoogle** [comment]
Any update here? @brianosman

**Comment by brianosman** [comment]
Ah, sorry - I had made a note in the chat room, forgot about this bug, though. The new API was landed (https://skia-review.googlesource.com/c/15895/). That should allow you to construct "real" images that can be safely used (as far as we understand your usage requirements), without the additional thread hop.
