### ISSUE TITLE
setState in webview_flutter is not working as expected.

### ISSUE THREAD

**Issue by nalnir** [flutter/flutter#94407]
I have fairly easy thing I want to do. If page is not loaded yet I want to show CircularProgressIndicator.

My code:
```
class WebViewComponent extends StatefulWidget {
  final String url;
  WebViewComponent({
    Key? key,
    required this.url,
  });

  @override
  _WebViewComponentState createState() => _WebViewComponentState();
}

class _WebViewComponentState extends State<WebViewComponent> {
  @override
  Widget build(BuildContext context) {
    final Completer<WebViewController> webViewController = Completer<WebViewController>();
    bool isLoading = true;

    @override
    void initState() {
      super.initState();
      if (Platform.isAndroid) {
        WebView.platform = SurfaceAndroidWebView();
      }
    }

    return Stack(children: [
      WebView(
        initialUrl: widget.url,
        javascriptMode: JavascriptMode.unrestricted,
        onWebViewCreated: (WebViewController controller) {
          webViewController.complete(controller);
        },
        onPageFinished: (String url) {
          setState(() {
            isLoading = false;
          });
        },
        gestureRecognizers: Set()..add(Factory<VerticalDragGestureRecognizer>(() => VerticalDragGestureRecognizer())),
        gestureNavigationEnabled: true,
      ),
      isLoading ? const Center(child: CircularProgressIndicator()) : Container()
    ]);
  }
}
```

I set isLoading to false only after the Page is finished loading. But the the CircularProgressIndicator is still visible even after state has changed.

**Comment by stuartmorgan** [comment]
This is a bug in the code you have provided; `isLoading` has been declared as a local variable, so changing it won't affect future calls to `build`.

Closing as this is odd not a Flutter bug.

**Comment by nalnir** [comment]
Sill

> This is a bug in the code you have provided; `isLoading` has been declared as a local variable, so changing it won't affect future calls to `build`.
> 
> Closing as this is odd not a Flutter bug.

Silly me, completely overlooked I put it inside the build method. Sorry for an unnecessary ticket. Fixed by putting it before the build.
