### ISSUE TITLE
Issue: NestedScrollView error when AppBar is null

### ISSUE THREAD

**Issue by anhln8x** [flutter/flutter#94413]
Dear all,

NestedScrollView error when AppBar is null.

The error occurs when the user tries to perform the scroll up and down gesture many times and reverse quickly.

Temporary fix: Set AppBar with toolbarHeight = 0 (Hide Appbar)

Sorry, I don't have the skills to elaborate on this. I made a video of the problem.

[https://www.youtube.com/watch?v=-9lEp-BYFFw](https://www.youtube.com/watch?v=-9lEp-BYFFw)

Sample source code:
```
Widget? _buildBody() {
    return SafeArea(
      top: false,
      child: NestedScrollView(
        floatHeaderSlivers: true,
        headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
          return [_buildSliverAppBar()];
        },
        body: Container(
          child: PageView(
            controller: _pageController,
            onPageChanged: _handlePageChanged,
            children: _viewports,
            //physics: const NeverScrollableScrollPhysics(), // No sliding
          ),
        ),
      ),
    );
  }
```

<details>
<summary>console error log</summary>

```
======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/nested_scroll_view.dart': Failed assertion: line 980 pos 16: 'extra >= 0.0': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      _NestedScrollCoordinator._getMetrics (package:flutter/src/widgets/nested_scroll_view.dart:980:16)
#3      _NestedScrollCoordinator.createInnerBallisticScrollActivity (package:flutter/src/widgets/nested_scroll_view.dart:948:9)
#4      _NestedScrollCoordinator.goBallistic.<anonymous closure> (package:flutter/src/widgets/nested_scroll_view.dart:887:16)
#5      _NestedScrollCoordinator.beginActivity (package:flutter/src/widgets/nested_scroll_view.dart:857:66)
#6      _NestedScrollCoordinator.goBallistic (package:flutter/src/widgets/nested_scroll_view.dart:884:5)
#7      ScrollDragController.end (package:flutter/src/widgets/scroll_activity.dart:412:14)
#8      ScrollableState._handleDragEnd (package:flutter/src/widgets/scrollable.dart:653:12)
#9      DragGestureRecognizer._checkEnd.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:486:47)
#10     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:193:24)
#11     DragGestureRecognizer._checkEnd (package:flutter/src/gestures/monodrag.dart:486:5)
#12     DragGestureRecognizer.didStopTrackingLastPointer (package:flutter/src/gestures/monodrag.dart:393:9)
#13     OneSequenceGestureRecognizer.stopTrackingPointer (package:flutter/src/gestures/recognizer.dart:387:9)
#14     DragGestureRecognizer._giveUpPointer (package:flutter/src/gestures/monodrag.dart:402:5)
#15     DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:321:7)
#16     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:94:12)
#17     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:139:9)
#18     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:400:8)
#19     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:137:18)
#20     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:123:7)
#21     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:440:19)
#22     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:420:22)
#23     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:278:11)
#24     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#25     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#26     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#27     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#31     _invoke1 (dart:ui/hooks.dart:185:10)
#32     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
#33     _dispatchPointerDataPacket (dart:ui/hooks.dart:98:31)
(elided 5 frames from class _AssertionError and dart:async)
Handler: "onEnd"
Recognizer: VerticalDragGestureRecognizer#4138b
  start behavior: start
====================================================================================================
I/ViewRootImpl@75d498[MainActivity]( 4407): ViewPostIme pointer 0
I/ViewRootImpl@75d498[MainActivity]( 4407): ViewPostIme pointer 1

======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 629 pos 12: '_drag == null': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      ScrollableState._handleDragDown (package:flutter/src/widgets/scrollable.dart:629:12)
#3      DragGestureRecognizer._checkDown.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:416:51)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:193:24)
#5      DragGestureRecognizer._checkDown (package:flutter/src/gestures/monodrag.dart:416:7)
#6      DragGestureRecognizer.addAllowedPointer (package:flutter/src/gestures/monodrag.dart:276:7)
#7      GestureRecognizer.addPointer (package:flutter/src/gestures/recognizer.dart:112:7)
#8      RawGestureDetectorState._handlePointerDown (package:flutter/src/widgets/gesture_detector.dart:1479:18)
#9      RenderPointerListener.handleEvent (package:flutter/src/rendering/proxy_box.dart:2882:29)
#10     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:420:22)
#11     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:278:11)
#12     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#13     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#14     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#15     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#19     _invoke1 (dart:ui/hooks.dart:185:10)
#20     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
#21     _dispatchPointerDataPacket (dart:ui/hooks.dart:98:31)
(elided 5 frames from class _AssertionError and dart:async)
Handler: "onDown"
Recognizer: VerticalDragGestureRecognizer#4138b
  start behavior: start
====================================================================================================

```

</details>

**Comment by darshankawar** [comment]
@anhln8x 
Can you provide `flutter doctor -v` and a complete minimal reproducible code sample ?
Thanks.

**Comment by anhln8x** [comment]
Hi @darshankawar 

My "flutter doctor -v":

`D:\Work\go>flutter doctor -v
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19043.1348], locale en-US)
    • Flutter version 2.5.3 at C:\flutter_windows_2.5.3-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (7 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Anhln\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Connected device (3 available)
    • SM N985F (mobile) • 192.168.1.215:5555 • android-arm64  • Android 11 (API 30)
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 96.0.4664.45
    • Edge (web)        • edge               • web-javascript • Microsoft Edge 96.0.1054.34

• No issues found!
`
Code sample:
`import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  static const String _title = 'NestedScrollView Sample';

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: _title,
      home: MainPage(),
    );
  }
}

class MainPage extends StatefulWidget {
  const MainPage({Key? key}) : super(key: key);

  @override
  State<MainPage> createState() => _MainPageState();
}

class _MainPageState extends State<MainPage> with SingleTickerProviderStateMixin {
  late AnimationController _animationController;

  @override
  void initState() {
    super.initState();

    _animationController = AnimationController(vsync: this, duration: const Duration(milliseconds: 200));
  }

  @override
  void dispose() {
    super.dispose();
    _animationController.dispose();
  }

  @override
  Widget build(BuildContext context) {
    _animationController.forward();

    return NotificationListener<UserScrollNotification>(
      onNotification: _handleScrollNotify,
      child: Scaffold(
        body: NestedScrollView(
          headerSliverBuilder: (_, __) {
            return <Widget>[
              const SliverAppBar(
                pinned: false,
                snap: true,
                floating: true,
                title: Text("Appbar"),
                iconTheme: IconThemeData(color: Colors.white),
              ),
            ];
          },
          body: ListView.builder(
            itemCount: 20,
            itemBuilder: (BuildContext context, int index) {
              return ListTile(
                title: Center(child: Text('Item ${index + 1}')),
              );
            },
          ),
        ),
        bottomNavigationBar: SizeTransition(
          sizeFactor: _animationController,
          axisAlignment: -1.0,
          child: BottomNavigationBar(
            items: const <BottomNavigationBarItem>[
              BottomNavigationBarItem(
                icon: Icon(Icons.home),
                label: 'Home',
              ),
              BottomNavigationBarItem(
                icon: Icon(Icons.business),
                label: 'Business',
              ),
              BottomNavigationBarItem(
                icon: Icon(Icons.school),
                label: 'School',
              ),
            ],
            currentIndex: 0,
          ),
        ),
      ),
    );
  }

  bool _handleScrollNotify(UserScrollNotification notification) {
    AxisDirection axisDirection = notification.metrics.axisDirection;
    if (axisDirection == AxisDirection.down || axisDirection == AxisDirection.up) {
      switch (notification.direction) {
        case ScrollDirection.forward:
          _animationController.forward();
          break;
        case ScrollDirection.reverse:
          _animationController.reverse();
          break;
        case ScrollDirection.idle:
          // TODO: Handle this case.
          break;
      }
    }
    return false;
  }
}
`
Thank you for your reply.

**Comment by darshankawar** [comment]
@anhln8x 
Sorry for coming back a bit late on this. I ran your code sample on latest stable and master on Android device but didn't get the exception you reported. I swiped back and forth (up and down) quickly for some time but didn't see any error in the logs:

```
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...
W/FlutterActivityAndFragmentDelegate(10128): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
Debug service listening on ws://127.0.0.1:61587/VWHR1nPjqI8=/ws
Syncing files to device SM A260G...
I/zygote  (10128): Do partial code cache collection, code=28KB, data=30KB
I/zygote  (10128): After code cache collection, code=28KB, data=30KB
I/zygote  (10128): Increasing code cache capacity to 128KB
I/zygote  (10128): Do partial code cache collection, code=62KB, data=51KB
I/zygote  (10128): After code cache collection, code=62KB, data=51KB
I/zygote  (10128): Increasing code cache capacity to 256KB

```
