### ISSUE TITLE
[proposal] make the default counter app android 12 ready

### ISSUE THREAD

**Issue by aoatmon** [flutter/flutter#94411]
## Steps to Reproduce

1. ~clone this [repo](https://github.com/aoatmon/android_12_issue)  or~  run `flutter create android_12_issue` then apply these [changes](https://github.com/aoatmon/android_12_issue/pull/1/commits/01bada28af286574f21118bfbba1be119e22eacf)
2. ~if you cloned the app run `sh initialize_signing.sh` otherwise~ run the commands from this [file](https://github.com/aoatmon/android_12_issue/blob/master/initialize_signing.sh)

3. run `flutter build apk --release`
4. transfer the file from `android/build/outputs/apk/release/app-release.apk` to a device running `android 12`
5. attempt to install the app

**Expected results:** app installs (or at least prompt to install from "unsafe sources")

**Actual results:** 
![ezgif-2-323d93f990f3](https://user-images.githubusercontent.com/85128136/144053294-bc9eeeca-fc05-4b50-aa8d-0adc1c9855d3.gif)

### code sample

[sample app](https://github.com/aoatmon/android_12_issue)

<details>
  <summary>doctor</summary>
  
  ```console
  [✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-x64, locale en-EE)
    • Flutter version 2.5.3 at /Users/francesco/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (7 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/francesco/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • Pixel 3a (mobile) • 965AY0WP5C • android-arm64  • Android 12 (API 31)
    • macOS (desktop)   • macos      • darwin-x64     • macOS 12.0.1 21A559 darwin-x64
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 96.0.4664.55

• No issues found!
  ```

</details>

please note that `flutter run --release` works well

[stackoverflow mirror](https://stackoverflow.com/questions/70170181/setting-both-compilesdkversion-targetsdkversion-to-31-causes-there-was-a-prob)

**Comment by imihirpaldhikar** [comment]
This might be issue due to your signing keys.

**Comment by aoatmon** [comment]
> This might be issue due to your signing keys. Because of which Android fails to verify the apk package.

@imihirpaldhikar 
I'm not sure, if I set `targetSdkVersion 30` works well using the same key

**Comment by darshankawar** [comment]
@aoatmon 
Can you check [this](https://www.fixcrunch.com/android-problem/there-was-a-problem-parsing-the-package/) article and see if it helps ?

**Comment by aoatmon** [comment]
> @aoatmon Can you check [this](https://www.fixcrunch.com/android-problem/there-was-a-problem-parsing-the-package/) article and see if it helps ?

I'm not sure exactly what part of this article should help:

- `Incompletely downloaded file` => I'm not downloading anything
- `Not suitable for current OS version` => I'm using a physical device listed in the doctor above (runs android 12)
- `Security Issues` "Android smartphone is set to install apps only downloaded from the official store." => LOL no!
- `Corrupted APK file` => maybe, if so it's clearly a flutter issue 
- `Changes to the manifest file` => I didn't change the manifest

following the [steps](https://github.com/flutter/flutter/issues/94411#issue-1067222586) above do you experience the behavior I described? 
if you need more details I'll be glad to provide it.

please note that I'm experiencing the issue in `production` 
the provided [sample](https://github.com/aoatmon/android_12_issue) is just the minimal setup to reproduce this behavior

**Comment by aoatmon** [comment]
@darshankawar 
the behavior is fixed with this [commit](https://github.com/aoatmon/android_12_issue/commit/b2d3351dd558845b60b88434a1ba91b22584ef5e)
I'd like to change the nature of this issue to `proposal`
apply the changes of both commits ([first](https://github.com/aoatmon/android_12_issue/pull/1/commits/01bada28af286574f21118bfbba1be119e22eacf), [second](https://github.com/aoatmon/android_12_issue/commit/b2d3351dd558845b60b88434a1ba91b22584ef5e)) in the default counter app

**Comment by darshankawar** [comment]
@aoatmon 
Thanks for digging in. Can you check [this](https://github.com/flutter/flutter/pull/91934) merged PR into master see if it helps already ?
You may need to switch to latest master to see the change made in it.

**Comment by iapicca** [comment]
> @aoatmon Thanks for digging in. Can you check [this](https://github.com/flutter/flutter/pull/91934) merged PR into master see if it helps already ? You may need to switch to latest master to see the change made in it.

@darshankawar 
the pr contains one of the steps I'm suggesting, namely updating the manifest
what I'm suggesting includes also:
- update gradle
- update kotlin
- bump `compileSdkVersion` and `targetSdkVersion` to 31

as shown [above](https://github.com/flutter/flutter/issues/94411#issuecomment-983564891)

**Comment by aoatmon** [comment]
@darshankawar 
the pr seems to be specific to the target `targetSdkVersion ` and manifest,
changing only those allow the app to compile but with a lot of deprecation warning
it would be nice if a comprehensive upgrade to android 12 would be taken in consideration
