### ISSUE TITLE
Problem with the cursor not going to the center after writing () using the keyboard app.

### ISSUE THREAD

**Issue by hatano0x06** [flutter/flutter#94410]
## Steps to Reproduce

1. install `simeji` application from google play ( https://play.google.com/store/apps/details?id=com.adamrocker.android.input.simeji&hl=ja&gl=US )
2. set to use simeji application for keyboard
3. Execute `flutter run` on the code sample
4. tap symbol（記号 in japanese) at left top
5. tap `paren` and select `()`
6. input あかさ

**Expected results:** 
`(あかさ)` is displayed in the textfield.

https://user-images.githubusercontent.com/7422251/144053570-e673e1a4-c644-4051-b6a7-06a7fdf27697.mp4

**Actual results:** 
`()あかさ` is displayed in the textfield.

https://user-images.githubusercontent.com/7422251/144053592-7af515f2-dba7-4e0b-ba22-0319e3275237.mp4

<details>
<summary>Code sample</summary>

```

import 'package:flutter/material.dart';

class SamplePage extends StatefulWidget {

  SamplePage(): super();

  @override
  SamplePageState createState() => SamplePageState();
}

class SamplePageState extends State<SamplePage> with WidgetsBindingObserver {

  @override
  void initState(){
    super.initState();
  }

  Widget build(BuildContext context){
    
    Widget bodyScaffold = Scaffold(
      body: Container(
        padding : EdgeInsets.only(top: 200, left:10, right:10),
        child   : TextField()
      ),
    );

    return bodyScaffold;
  }
}


```

</details>

<details>
  <summary>Logs</summary>

`flutter doctor -v`

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19043.1348], locale ja-JP)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.62.3)
[√] Connected device (3 available)
```

</details>

**Comment by darshankawar** [comment]
@hatano0x06 
This sounds similar to https://github.com/flutter/flutter/issues/72980. Can you try the same scenario on latest master and see if it works ?

**Comment by hatano0x06** [comment]
@darshankawar 
thanks
I checked try on master and found this problem is resolved

**Comment by darshankawar** [comment]
Glad to know. Closing this since this is fixed on master and per above comment.
