### ISSUE TITLE
Initial layout with SkShaper is slower

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#94419]
To reproduce:

1. Add tracing to `RenderParagraph.performLayout`
2. Run the following app:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool _showText = false;
  final List<Widget> children = List.generate(9, (index) {
    return ListTile(
      leading: CircleAvatar(
        child: Text('G$index}'),
      ),
      title: Text(
        'Foo contact from $index-th local contact',
        overflow: TextOverflow.ellipsis,
      ),
      subtitle: Text('+91 88888 8800$index'),
    );
  });

  @override
  Widget build(BuildContext context) {

    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: !_showText
          ? Container()
          : OverflowBox(
              alignment: Alignment.topCenter,
              maxHeight: double.infinity,
              child: Column(
                children: children,
              ),
            ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          setState(() {
            _showText = !_showText;
          });
        },
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
```
3. Click the FAB once and in the trace look at the frame that layouts all the list tiles.

On a low-powered Android device with SkShaper enabled it takes on average 1.4ms per RenderParagraph layout for the three strings in the list tile. With libtxt this average is around 0.9ms.

Subsequent layouts of the same strings in "fresh" RenderParagraphs (pressing the FAB again and again to make the list tiles disappear and appear again) is faster. Both libtxt and SkShaper average around 0.5ms here.

The higher cost of the initial layout is significant because it happens at a time where the performance budget is already tight, e.g. when a new screen needs to be build for the first time. With libtext, it takes about 27ms to initially lay out all the RenderParagraphs in the list tiles, whereas with SkShaper it takes 36ms.

**Comment by goderbauer** [comment]
If we don't have benchmarks that capture this, we should add some.

**Comment by jason-simmons** [comment]
Some factors that are affecting performance on this example:
* SkParagraph has higher fixed overhead for each layout call regardless of the contents of the text.
* Libtxt/Minikin has a different caching strategy that will cache words within the text.  This example repeatedly lays out strings that mostly contain the same words, so Libtxt/Minikin's cache can save significant work.
* SkParagraph's ellipsize implementation does more work but should produce higher quality results.

The difference between Libtxt and SkParagraph performance will depend on the workload.
I would expect SkParagraph to perform better on longer text strings with fewer repeated words.  In that case the fixed overhead is a smaller part of the overall layout time.  And for longer strings SkParagraph's strategy of making one HarfBuzz `hb_shape` call for the whole string may be faster than the Libtxt/Minikin per-word shaping and caching.

@Rusino

**Comment by jason-simmons** [comment]
This is a trace of an SkParagraph `ParagraphImpl::layout` call for a paragraph containing one character.  This was captured on a low-powered device.

![image](https://user-images.githubusercontent.com/14226037/144526454-78d0ebed-ebb0-4282-96f6-3a69b7e06220.png)

Some noteworthy parts:
* `computeCodeUnitProperties` (18% of the total time).  This is calling ICU APIs to determine attributes of the characters in the text.
* HarfBuzz `hb_shape` (18%)
* `append` in SkShaper_HarfBuzz (12%) - this calls OneLineShaper's `runBuffer` and `commitRunBuffer`
* `OneLineShaper::finish` (5%)
* `ParagraphCache::updateParagraph` (10%)

**Comment by chinmaygarde** [comment]
Marking this as P3 as this is an active ongoing investigation. I don't see any concrete action items from it just yet. Perhaps a list of traces for https://github.com/flutter/flutter/issues/94063.

**Comment by JsouLiang** [comment]
In WidgetsBinding process the Flutter framework will 'warm up text shaper', this operation will create string "-" and special the width constraint is 60 then engine will FontCollection and minikin::Layout the string. The purpose of that is reduce the app text layout when app running.
But the "warm up text shaper" is in Flutter.UI Thread, it will block the App lunch.
My question is: while app start, the engine dispatch a thread to warm up text shaper?

**Comment by JsouLiang** [comment]
Anyone following this?

**Comment by dnfield** [comment]
@JsouLiang this is more that laying out a new string is expensive the first time, rather than an initial call being expensive. There are some people actively working on this

**Comment by JsouLiang** [comment]
“There are some people actively working on this” might i follow this active?

**Comment by dnfield** [comment]
@goderbauer do we have a public doc on this, or anything to update on the issue here? My knowledge right now is we're working with the SkShaper folks to optimize layout for some common cases (renering static text that does not need to save/calculate offsets for cursor positioning, perhaps avoid ICU lookups on text we know ICU won't help), and potentially breaking up shaping and linebreaking so that it can be a two step process kicked off asynchronously.

**Comment by jason-simmons** [comment]
I spent some time looking at SkParagraph profiles and trying to reduce data copying and other redundant work.

Some improvements that landed recently:
https://skia-review.googlesource.com/c/skia/+/483022
https://skia-review.googlesource.com/c/skia/+/481796
https://skia-review.googlesource.com/c/skia/+/481239

**Comment by Rusino** [comment]
The example above is not a valid test for performance. It has text that is almost always repeating:
'Foo contact from $index-th local contact', '+91 88888 8800$index'.
As a result word-based cache in libtxt wins over whole string cache in SkParagraph. In real life, however, words repetitions happen  not so often. I suggest we fix the test (for instance, add $index to ALMOST all words in the line) and see how the results change.
I am fairly sure this is what causes the performance difference. SkParagraph shapes every line every time, libtxt - only indexes, combining the rest of the line from already shaped words (shaping is the most expensive operation!).
Now, we can optimize the initial layout performance anyway but I don't want it to be tied to this bug (SkParagraph is slower).
I also want to have a correct base line for future improvements.

**Comment by goderbauer** [comment]
Average initial RenderParagraph layout with SkParagraph: 1.384 ms
Average initial RenderParagraph layout with libtxt: 1.389 ms

@Rusino Your theory sounds plausible :). Is there a reason why SkParagraph shouldn't have a similar word-cache, though? Since it seems to give us a speed-up in some scenario?

[Traces.zip](https://github.com/flutter/flutter/files/8101084/Archive.2.zip)

This is now with injecting the index everywhere:

![screencap](https://user-images.githubusercontent.com/1227763/154775507-3967f41d-131c-4ab8-a061-de05ad421f1f.png)

**Comment by zanderso** [comment]
What is the status of this issue?

**Comment by dnfield** [comment]
We need to add this as a benchmark to CI.

SkShaper has made some improvements recently that should have improved this. It's shown in some benchmarks here: https://flutter-engine-perf.skia.org/e/?begin=1648251309&end=1649785870&queries=executable%3D._txt_benchmarks%26test%3DSkParagraphFixture_ShortLayout&requestType=0&xbaroffset=27006

I'm going to see if we can add this one to CI.

**Comment by zanderso** [comment]
AFAICT all work items mentioned in this issue are complete. If there's any further follow-up required, it should be filed as a new issue.
