### ISSUE TITLE
Please add a fork of double-conversion library to googlesource mirror.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#94427]
I want to add a dependency on this library: https://github.com/google/double-conversion
To do that, I think I need a mirror in https://flutter.googlesource.com so I can add it to the DEPS file in the engine. The latest released revision would be fine.

It's something that Chrome maintains and uses, so it's also mirrored here: https://source.chromium.org/chromium/chromium/src/+/main:base/third_party/double_conversion/
But I don't think I can use it directly from there in our DEPS.

**Comment by CaseyHillers** [comment]
I created the intial repo at https://flutter.googlesource.com/third_party/double-conversion/

I'm currently working through an issue where the oncall isn't able to do force pushes to initialize the repo.

**Comment by CaseyHillers** [comment]
@gspencergoog this is available now.

Before closing this, I'm waiting for permissions to be granted so this fork will auto mirror from the github source.

**Comment by CaseyHillers** [comment]
@godofredoc I still lack permissions. Can you run

```
gob-ctl <<EOF
update {
 repo: "flutter/third_party/double-conversion"
 meta {
   remote_config {
     url: "git://gitub.com/google/double-conversion.git"
     fetch_poll_frequency_sec: 3600
     fetch: "+refs/heads/*:refs/heads/*"
     fetch: "+refs/tags/*:refs/tags/*"
   }
 }
}
EOF
```

to enable the mirror and mark this as closed?

**Comment by godofredoc** [comment]
Done!
