### ISSUE TITLE
Web app launched from VSCode takes 5x memory usage over published app

### ISSUE THREAD

**Issue by mat100payette** [flutter/flutter#94426]
I can hardly provide full steps, but basically the app takes tremendously more ram when launched from VSCode than fetched from published website.

![PerfProfileImages](https://user-images.githubusercontent.com/20545324/144118750-159eb1a3-37de-4e1d-8238-1bd93b43d896.jpg)

You can see in red the memory usage from the single VSCode launched instance (at the same app state, in **Release mode** !) reaches 1.3Gb.
In blue are two instances of the published app in another chrome window.

So I'm wondering, how am I supposed to profile my app if even the release mode launched from vscode takes an astronomical amount of ram compared to the identical published version ?

<details>
  <summary>Logs</summary>

```
```

```
No issues found! (ran in 5.2s)
```

```
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [version 10.0.18363.1916], locale fr-CA)
    • Flutter version 2.5.3 at C:\Flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (7 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.62.3)
    • VS Code at C:\Users\matpa\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.28.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.45
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 96.0.1054.29

! Doctor found issues in 2 categories.
```

</details>

**Comment by darshankawar** [comment]
@mat100payette 
Since you said `launched from VSCode` shows this behavior, does the same occur if you directly launch through command line ?
Can you also try the same using default counter app from VScode and see what you get ? Also, it will be good to get some code sample that makes such a huge memory usage. Do you use lot of images or other elements that takes a bit time to render ?
Such details would be useful to analyze this behavior better.

**Comment by mat100payette** [comment]
> @mat100payette Since you said `launched from VSCode` shows this behavior, does the same occur if you directly launch through command line ? Can you also try the same using default counter app from VScode and see what you get ? Also, it will be good to get some code sample that makes such a huge memory usage. Do you use lot of images or other elements that takes a bit time to render ? Such details would be useful to analyze this behavior better.

I tried serving the release build from python http server locally, and that also reaches 1.4Gb ram.

I don't think counter app will show any of these symptoms given how small it is :/
My app fetches a large list (2-3k) of image urls to display using `Image.network`, arranged in a non-paginated (on purpose) `GridView`.

**Comment by darshankawar** [comment]
> My app fetches a large list (2-3k) of image urls to display using `Image.network`, arranged in a non-paginated (on purpose) `GridView`.

Thanks for the update. Would be good to provide a minimal code sample involving above so that we can take a look at it better.

**Comment by mat100payette** [comment]
@darshankawar I don't have minimal code for this. If you've never seen this or have no clue how to approach it then I guess I'm out of luck...

**Comment by darshankawar** [comment]
@mat100payette 
There are couple of related / similar issues, see if they resemble your case:

https://github.com/flutter/flutter/issues/84565
https://github.com/flutter/flutter/issues/81790
