### ISSUE TITLE
[web] Rendering issues and crash with iOS15's Safari and macOS Monterey's Safari

### ISSUE THREAD

**Issue by tk512** [flutter/flutter#94420]
The linked ticket should be reopened as the issue still persists on iOS 15.1.

sunjianan9900's comment is in correct:

"This has fixed on ios 15.1 & macOS Monterey 12"

_Originally posted by @sunjianan9900 in https://github.com/flutter/flutter/issues/89655#issuecomment-952852026_

**Comment by darshankawar** [comment]
Will need to go through the entire thread from linked issue and understand correct and current status of the issue. Does the fix made by team mentioned [here](https://github.com/flutter/flutter/issues/89655#issuecomment-935115790) and [here](https://github.com/flutter/flutter/issues/89655#issuecomment-935200644) doesn't work at your end using latest master ?

**Comment by tk512** [comment]
@darshankawar  thanks for your quick reply. The workaround proposed (see below) works fine, but I assumed that there would be a Flutter fix not requiring any hacks/workaround.

If this is going to be added to the documentation however then it is probably OK - and we can go ahead and close this ticket. What do you think ?

```
<script type="text/javascript">
  if (platform.name.toLowerCase() == "safari" && parseInt(platform.version.split(".")[0]) >= 15) {
   HTMLCanvasElement.prototype.getContext = function (orig) {
     return function(type) {
       return type !== "webgl2" ? orig.apply(this, arguments) : null
     }
   }(HTMLCanvasElement.prototype.getContext)
  }
</script>
```

**Comment by maheshmnj** [comment]
Hi @tk512, I believe the linked issue is same as  https://github.com/flutter/flutter/issues/92495?
