### ISSUE TITLE
 [tool_crash] ProcessException: Process exited abnormally:Command line invocation: /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -listUser defaults from command line: IDEPackageSupportUseBuiltinSCM = YESResolved source packages: GoogleMaps-SP-main: (null)xcodebuild: error: Could not resolve package dependencies: Packages are not supported when using legacy build locations, but the current project has them enabled. Command: xcrun, OS error code: 74

### ISSUE THREAD

**Issue by edmundciego** [flutter/flutter#94448]
## Command
```
flutter build ios
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Process exited abnormally:
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -list

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

Resolved source packages:
  GoogleMaps-SP-main: (null)

xcodebuild: error: Could not resolve package dependencies:
  Packages are not supported when using legacy build locations, but the current project has them enabled. Command: xcrun, OS error code: 74
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:124:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:276:19)
<asynchronous suspension>
#2      XcodeProjectInterpreter.getInfo (package:flutter_tools/src/ios/xcodeproj.dart:470:30)
<asynchronous suspension>
#3      IosProject.projectInfo (package:flutter_tools/src/project.dart:619:29)
<asynchronous suspension>
#4      IosProject.buildSettingsForBuildInfo (package:flutter_tools/src/project.dart:601:35)
<asynchronous suspension>
#5      IosProject._parseProductBundleIdentifier (package:flutter_tools/src/project.dart:543:50)
<asynchronous suspension>
#6      IosProject.productBundleIdentifier (package:flutter_tools/src/project.dart:520:41)
<asynchronous suspension>
#7      BuildableIOSApp.fromProject (package:flutter_tools/src/ios/application_package.dart:118:36)
<asynchronous suspension>
#8      FlutterApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/flutter_application_package.dart:83:15)
<asynchronous suspension>
#9      _BuildIOSSubCommand.buildableIOSApp (package:flutter_tools/src/commands/build_ios.dart:212:26)
<asynchronous suspension>
#10     _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:244:33)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.0.1 21A559 darwin-x64, locale en-US)
    • Flutter version 2.2.3 at /Users/edmundciego/Documents/src/flutter
    • Framework revision f4abaa0735 (5 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/edmundciego/Library/Android/sdk
    • Platform android-Sv2, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.55

• No issues found!

```

## Flutter Application Metadata
**Type**: null
**Version**: 1.2.0+9
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
android_intent-2.0.2
cloud_firestore-0.14.4
cloud_firestore_web-0.2.1+2
firebase_auth-0.18.4+1
firebase_auth_web-0.3.2+3
firebase_core-0.5.3
firebase_core_web-0.2.1+1
firebase_messaging-7.0.3
firebase_storage-5.2.0
firebase_storage_web-0.1.1+1
flutter_facebook_auth-2.0.2+1
flutter_facebook_auth_web-1.0.6
flutter_facebook_login-3.0.0
flutter_plugin_android_lifecycle-2.0.5
fluttertoast-8.0.1-nullsafety.0
geolocator-6.2.1
geolocator_web-1.0.1
google_map_location_picker-4.1.7
google_maps_flutter-2.0.6
google_sign_in-4.5.9
google_sign_in_web-0.9.2
image_picker-0.7.5+4
image_picker_for_web-2.0.0
import_js_library-1.0.2
location-3.0.2
location_web-1.0.1
package_info-2.0.2
path_provider-2.0.4
path_provider_linux-2.1.2
path_provider_macos-2.0.3
path_provider_windows-2.0.4
shared_preferences-2.0.5
shared_preferences_linux-2.0.3
shared_preferences_macos-2.0.2
shared_preferences_web-2.0.2
shared_preferences_windows-2.0.3
sign_in_with_apple-2.5.4
sqflite-2.0.0+4
url_launcher-6.0.2
url_launcher_linux-2.0.2
url_launcher_macos-2.0.2
url_launcher_web-2.0.4
url_launcher_windows-2.0.2
video_player-1.0.1
video_player_web-0.1.4+1
wakelock-0.2.1+1
wakelock_web-0.1.0+3
webview_flutter-1.0.7

**Comment by danagbemava-nc** [comment]
Hi @edmundciego, you appear to be on an older version of flutter. 

This issue was reported in https://github.com/flutter/flutter/issues/57083 and fixed. 

Kindly upgrade to the latest version of stable and run the flutter build command again to see if you still experience this issue. 

```
flutter upgrade
flutter build ios
```

Closing as this has already been fixed. 

If you still experience this issue after the upgrade, kindly leave a comment below with the output of `flutter doctor -v` and I will reopen this. 

Thank you
