### ISSUE TITLE
Undeleteable files

### ISSUE THREAD

**Issue by noahsalvadordenjo** [flutter/flutter#94452]
Hi i couldn't find a way to submit a feature request for Android but flutter is from google, so i would like the ability to create undeleteabe files with my flutter app

**Comment by mamuseferha** [comment]
Hi @noahsalvadordenjo this doesn't seem like an issue that can be solved with flutter. I'll go ahead and close this now, if you disagree please write in the comments and I will reopen it. Thank you.
