### ISSUE TITLE
[IOS]Build failure: xcode_backend.sh: No such file or directory Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by combi-35** [flutter/flutter#94466]
Hi,
I recently switched from an intel Macbook to an M1.
My application is running on intel Macbook but not on the M1.
Both PCs use the same flutter and packages version.
Other smaller flutter apps are running fine on M1.

If running the specific app I got 
```
Xcode's output:
↳
    /bin/sh: /Users/lukas/Flutter/flutter/packages/flutter_tools/bin/xcode_backend.sh: No such file or directory
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in parallel
```

I tried updating pods, flutter clean, restarting pc but no success.

`flutter run --verbose`
[flutter run](https://github.com/flutter/flutter/files/7634678/log.txt)

## Logs

<details>
<summary>flutter doctor --v</summary>

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-arm, locale de-AT)
    • Flutter version 2.5.3 at /Users/lukas/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (7 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/lukas/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 62.0.3
    • Dart plugin version 212.5632

[✓] Connected device (2 available)
    • iPhone 13 (mobile) • D3C991E6-C342-4571-BBFC-7FDDDA9B6AE8 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 96.0.4664.55

• No issues found!

```

</details>

**Comment by maheshmnj** [comment]
Hi @combi-35, Thanks for filing the issue. Did you try `flutter clean`? 

>  /bin/sh -c /Users/lukas/Library/Developer/Xcode/DerivedData/Runner-awltaysunljaqnbrpahqqevxpcwi/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Script-9740EEB61CF901F6004384FC.sh
               /bin/sh: /Users/lukas/Flutter/flutter/packages/flutter_tools/bin/xcode_backend.sh: No such file or directory
               Command PhaseScriptExecution failed with a nonzero exit code
               
Looking at the logs, This issue Looks related to build configurations. Can you please share a screenshot of your build configurations by opening your project in xcode 

1. run from the root of your project `open ios/Runner.xcworkspace`
2. Open your Project Runner build settings > Info tab.
3. Expand Debug, Profile, Release, and any other configurations and share a screenshot here.
And share your `pubspec.yaml`, and the `Podfile`too.


Thanks

**Comment by combi-35** [comment]
Hi @maheshmnj,
thanks for the reply.
Yes I did run flutter clean.

Here is my screenshot
<img width="1197" alt="Bildschirmfoto 2021-12-02 um 12 23 28" src="https://user-images.githubusercontent.com/56366138/144413246-209e9b31-ec9f-4c84-8c32-21e5df259e35.png">

And here pubspec and Podfile
[Podfile](https://github.com/flutter/flutter/files/7641459/Podfile.txt)
[pubspec](https://github.com/flutter/flutter/files/7641460/pubspec.txt)

**Comment by maheshmnj** [comment]
thanks for the info @combi-35, Your build configurations looks fine, and I was able to build the ios app with same dependencies heres what I did.

- I created a new flutter project (stable 2.5.3)
- added  all your dependencies to pubspec.yaml
- updated Podfile same as yours
- changed minimum deployment target via xcode to 11.0
- `flutter clean` and `flutter pub get`

And the app built successfully, Can you please try deleting the `podfile.lock` and try running
```
flutter clean
flutter pub get
flutter run -v 
```
and see if it works and share the output logs if it fails (as a text file)

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.5.3 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (7 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • B622CBB7-F906-4FA7-8F49-FACEAAC905AB • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5
      (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.0.1 21A559 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 96.0.4664.55

• No issues found!
```
</details>


Thanks

**Comment by combi-35** [comment]
I already deleted podfile.lock and re-run suggested commands, but I did it again with no luck.
Here is my [log.txt](https://github.com/flutter/flutter/files/7649087/log.txt)

I even tried to remove all plugins, assets and everthing except a basic main.dart. Still the same error, I dont know what to do, the project is basically empty now.

**Comment by maheshmnj** [comment]
Thanks for the info @combi-35, I am not able to reproduce the issue, The app does build fine for me on `stable 2.5.3` with your dependencies in pubspec.yaml and the exact podfile by following the [steps mentioned above](https://github.com/flutter/flutter/issues/94466#issuecomment-985239853), Leaving this issue open for further investigation from the team.


cc: @jmagman

**Comment by combi-35** [comment]
I actually got it running.. I deleted ios folder and re-created it with `flutter create .`
I don't now what got messed up in ios folder, because like I said on my other intel Macbook everthing is running fine.
It'd be great if we could find out what went wrong.

**Comment by maheshmnj** [comment]
@combi-35 can you please attach the minimal project to find what caused the build failure?

**Comment by jmagman** [comment]
>     /bin/sh: /Users/lukas/Flutter/flutter/packages/flutter_tools/bin/xcode_backend.sh: No such file or directory

Does this path exist?  Is your Flutter SDK at `/Users/lukas/Flutter/flutter`?

**Comment by combi-35** [comment]
@jmagman,
after checking I see there is one "Flutter" folder to much as it was installed like so on my other Macbook.
But `FLUTTER_ROOT is /Users/lukas/flutter` so this correct, I cant see where the wrong path got pasted.

**Comment by combi-35** [comment]
Hey @jmagman,
can you give me a hint, where I can correct the path or why this happend?
Thanks!

**Comment by jmagman** [comment]
> can you give me a hint, where I can correct the path or why this happend?

Are you sure you're running Flutter from `/Users/lukas/flutter` and not `/Users/lukas/Flutter/flutter`?  It should be correcting it on every run based on where your `flutter` binary is.
What's the output of `which flutter`?

**Comment by combi-35** [comment]
Yes I am, here is the output `/Users/lukas/flutter/bin/flutter`.

**Comment by jmagman** [comment]
> But `FLUTTER_ROOT is /Users/lukas/flutter` so this correct, I cant see where the wrong path got pasted.

Where do you see that?  Did you set that explicitly somewhere?  In your logging it says 
`FLUTTER_ROOT = /Users/lukas/Flutter/flutter`

**Comment by combi-35** [comment]
I assumed that the installation path and Flutter Root are the same.
Flutter is installed on `/Users/lukas/flutter`.

It is possible that I changed something in the past because of an error. But looking through the project settings I cant find anything regarding flutter root.

**Comment by jmagman** [comment]
I'm not sure then.  `FLUTTER_ROOT` should be set based on where your install path is.  Does it reproduce after `flutter clean`?  What's the output of:
```
$ grep -riI  "/Users/lukas/Flutter/flutter" /Users/lukas/Development/engago-app/
```
