### ISSUE TITLE
Create an app bar parallax transition effect for iOS

### ISSUE THREAD

**Issue by xster** [flutter/flutter#9446]
Native iOS navigations have a different transition for the body vs the app bar. While the body has a parallax + x axis and z axis slide, the app bar has a parallax cross fade.

**Comment by brettpappas** [comment]
It seems like this used to work in the Flutter Gallery app based on this 1 second video:
https://www.youtube.com/watch?v=rFJsfqra_-g

I just tried it and I get the transition effect where the new app bar slide on top of the previous one so I'm not sure what happened.

**Comment by xster** [comment]
Remaining task: 

- [ ] RTL
- [ ] Back swipe gesture
