### ISSUE TITLE
[Feedback] Incomplete/Incorrect instructions at CodeLabs "Write Your First Flutter App, part 2"

### ISSUE THREAD

**Issue by wsegatto** [flutter/flutter#94463]
I'm new to Flutter.

The CodeLabs exercise "Write Your First Flutter App, part 2" has incorrect steps and final full code solution.
https://codelabs.developers.google.com/codelabs/first-flutter-app-pt2/#6

The app bar title and trailing icon remains with white color font despite the theme change.
The code displayed as example is supposed to yield the following:

![image](https://user-images.githubusercontent.com/35738729/144241834-54ad9e33-c64f-44cc-9b36-fd88f53c15d8.png)

However, the actual result is the following:

![image](https://user-images.githubusercontent.com/35738729/144241899-162819a6-0939-4ee7-8558-3c563a5172b0.png)

Just bringing that up to your attention as feedback.
Best regards!

**Comment by wsegatto** [comment]
Hi Daniel!
Thank you for getting back so quickly. 
Well, the issue lies in the example itself, not really limited to my code.

You can use this one:
https://github.com/flutter/codelabs/blob/master/startup_namer/step8_themes/lib/main.dart

Thank you!

**Comment by danagbemava-nc** [comment]
I run the sample in the link provided and this is what I see on my end. See screenshots below. 

I'm not entirely sure how you're running into what looks like a white-on-white situation.  

<details>
<summary>screenshots</summary>

| android | iOS |
|--|--|
| ![Screenshot_1638425524](https://user-images.githubusercontent.com/88313112/144367753-2f52b195-1b2b-4b01-96d6-499cff7eebd6.png) | ![Simulator Screen Shot - iPhone 13 - 2021-12-02 at 06 10 35](https://user-images.githubusercontent.com/88313112/144367759-1043c768-8b5f-47c3-b1bd-63aee09a4607.png) |

</details>
