### ISSUE TITLE
[in_app_purchase] Apple In App Purchase value is £(USD value), not £(GBP value)

### ISSUE THREAD

**Issue by RedHappyLlama** [flutter/flutter#94476]
Hi,

I'm not yet sure if this is a Flutter issue or Apple issue - Apple have been investigating for a couple of weeks and seem to be struggling to find an answer.

The issue I'm having is that the purchase value being shown on the Apple In App Purchase pop-up is not correct. The value does not match the assigned value from the relevant tier in App Store Connect. The value being shown is the equivalent USD value, but with a £ symbol rather than $. 

For example one of the In App Purchases has a price from Tier 9. The value shown should be £7.99. The value that is actually being shown is £8.99. The USD price from Tier 9 is $8.99. 

Another of the In App Purchases has a price from Tier 15. The value shown should be £12.99. The value that is actually being shown is £14.99. The USD price from Tier 15 is $14.99. 

Interestingly we have another In App Purchase from Alternate Tier 3. The value shown should be £2.99. The value that is actually being shown is £2.99. The USD price from Tier 15 is $2.99. So it is correct by accident. 

Currently only tested with a couple sandbox users through test-flight. I have ensured that the location for the sandbox users is United Kingdom. Have not tested with a real user on a fully released version of the app due to this issue. 

[https://appstoreconnect.apple.com/WebObjects/iTunesConnect.woa/ra/ng/app/1537837191/pricingMatrix/consumable/1590212088](url)

Nothing unexpected from `flutter analyze`

Results from `flutter doctor -v`: 
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.6 20G165 darwin-x64, locale en-GB)
    • Flutter version 2.5.1 at 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (3 months ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

**Comment by darshankawar** [comment]
@RedHappyLlama 
I am not too sure if this could be an issue with the plugin or appstore front, but maybe you can checkout [this](https://github.com/flutter/flutter/issues/83905) open issue and see if it relatable to your case ?

**Comment by RedHappyLlama** [comment]
@darshankawar I've had a look, doesn't look to be related as I haven't used `PurchaseVerificationData.source `. Not sure if I should? 

purchase related code below:

```
  void initPurchaseController() {
    print('Purchase Controller Initialised');
    if (Platform.isAndroid) {
      device = 'android';
    } else if (Platform.isIOS) {
      device = 'apple';
    }
    print('device is: $device');
    final Stream<List<PurchaseDetails>> purchaseUpdated = inAppPurchase.purchaseStream;
    purchaseStream = purchaseUpdated.listen((purchaseDetailsList) {
      _listenToPurchaseUpdated(purchaseDetailsList);
    }, onDone: () {
      purchaseStream.cancel();
      print('Purchase Stream Done');
    }, onError: (error) async {
      print('Purchase Stream Error');
      print('error is: $error');
      final bool isAvailable = await checkStoreStatus();
      if (!isAvailable) {
        final snackBar = SnackBar(
          backgroundColor: myRedColour,
          content: Text(
            'Lost connection to the In-App Store. Please check your internet connection.',
            style: TextStyle(fontSize: 20.0),
            textAlign: TextAlign.center,
          ),
        );
        ScaffoldMessenger.of(context).showSnackBar(snackBar);
      }
    });
  }

  Future<bool> checkStoreStatus() async {
    final bool isAvailable = await inAppPurchase.isAvailable();
    print('Store is Available?: $isAvailable');
    return isAvailable;
  }

  Future<void> initStoreInfo({@required List<String> productIdList}) async {
    print('Store Info Initialised');
    final bool isAvailable = await checkStoreStatus();

    if (!isAvailable) {
      isStoreAvailable = isAvailable;
      products = [];
      purchases = [];
      notFoundIds = [];
      purchasePending = false;
      loading = false;
      return;
    }

    ProductDetailsResponse productDetailResponse =
        await inAppPurchase.queryProductDetails(productIdList.toSet());

    if (productDetailResponse.error != null) {
      print('products found');
      queryProductError = productDetailResponse.error.message;
      isStoreAvailable = isAvailable;
      products = productDetailResponse.productDetails;
      purchases = [];
      notFoundIds = productDetailResponse.notFoundIDs;
      purchasePending = false;
      loading = false;
      print('found the following products:');
      for (ProductDetails productDetails in products) {
        print(productDetails.title);
      }
      return;
    }

    if (productDetailResponse.productDetails.isEmpty) {
      print('no products found');
      queryProductError = null;
      isStoreAvailable = isAvailable;
      products = productDetailResponse.productDetails;
      purchases = [];
      notFoundIds = productDetailResponse.notFoundIDs;
      purchasePending = false;
      loading = false;
      return;
    }

    isStoreAvailable = isAvailable;
    products = productDetailResponse.productDetails;
    notFoundIds = productDetailResponse.notFoundIDs;
    purchasePending = false;
    loading = false;

    print('found the following products:');
    for (ProductDetails productDetails in products) {
      print('Title is: ${productDetails.title}');
      print('ID is: ${productDetails.id}');
      print('price is: ${productDetails.price}');
      print('raw price is: ${productDetails.rawPrice}');
      print('currency code is: ${productDetails.currencyCode}');
      print('currency symbol is: ${productDetails.currencySymbol}');
    }
  }

  purchaseItem() {
    print('Purchase item ID: ${products[0].id}');
    print('Purchase item title: ${products[0].title}');
    print('Purchase item price : ${products[0].price}');
    print('Purchase item raw price: ${products[0].rawPrice}');
    print('Purchase item currency code: ${products[0].currencyCode}');
    print('Purchase item currency symbol: ${products[0].currencySymbol}');

    final PurchaseParam purchaseParam = PurchaseParam(
      productDetails: products[0],
    );
    inAppPurchase.buyConsumable(purchaseParam: purchaseParam, autoConsume: true);
  }

  void _listenToPurchaseUpdated(List<PurchaseDetails> purchaseDetailsList) {
    print('Purchase Stream Updated');
    purchaseDetailsList.forEach((PurchaseDetails purchaseDetails) async {
      if (purchaseDetails.status == PurchaseStatus.pending) {
        showPendingUI();
      } else {
        if (purchaseDetails.status == PurchaseStatus.error) {
          handleError(purchaseDetails.error);
        } else if (purchaseDetails.status == PurchaseStatus.purchased ||
            purchaseDetails.status == PurchaseStatus.restored) {
          bool valid = await _verifyPurchase(purchaseDetails);
          if (valid) {
            deliverProduct(purchaseDetails);
          } else {
            _handleInvalidPurchase(purchaseDetails);
            return;
          }
        }
        if (Platform.isAndroid) {
          final InAppPurchaseAndroidPlatformAddition androidAddition =
              inAppPurchase.getPlatformAddition<InAppPurchaseAndroidPlatformAddition>();
          await androidAddition.consumePurchase(purchaseDetails);
        }
        if (purchaseDetails.pendingCompletePurchase) {
          await inAppPurchase.completePurchase(purchaseDetails);
          print('PURCHASE COMPLETE');
        }
      }
    });
  }

  void showPendingUI() async {
    print('purchase is pending');
    purchasePending = true;
  }

  void deliverProduct(PurchaseDetails purchaseDetails) async {
    print('product delivery');
    purchases.add(purchaseDetails);
    purchasePending = false;
    ScaffoldMessenger.of(context).removeCurrentSnackBar();
    downloadGuide();
  }

  Future<bool> _verifyPurchase(PurchaseDetails purchaseDetails) async {
    print('Verify Purchase');

    print('product ID: ${purchaseDetails.productID}');
    print('purchase ID: ${purchaseDetails.purchaseID}');
    print('transaction date: ${purchaseDetails.transactionDate}');
    print('pending complete purchase: ${purchaseDetails.pendingCompletePurchase}');

    // print('local data: ${purchaseDetails.verificationData.localVerificationData}');
    // print('server data: ${purchaseDetails.verificationData.serverVerificationData}');
    print('device is : $device');
    APIResponse registerPayment = await guideService.submitPayment(
      guideID: guide.id,
      appProductId: purchaseDetails.productID,
      reference: purchaseDetails.verificationData.localVerificationData,
      device: device,
    );

    if (guide != null) {
      try {
        if (registerPayment.error == true) {
          if (registerPayment.errorMessage == 'redirect') {
            await showDialog(
                context: context,
                barrierDismissible: false,
                builder: (BuildContext context) {
                  return RedirectDialog(callBackFunction: null);
                });
            return false;
          } else {
            return false;
          }
        } else {
          print('register payment result: ${registerPayment.data['success']}');
          return registerPayment.data['success'];
        }
      } catch (e) {
        print('validation error');
        return false;
      }
    }
    return false;
  }

  void _handleInvalidPurchase(PurchaseDetails purchaseDetails) async {
    print('Invalid Purchase');

    await showDialog(
        context: context,
        barrierDismissible: false,
        builder: (BuildContext context) {
          return OkDialog(
              content:
                  'We couldn\'t complete the purchase, please check your internet connection and try again. If the issue persists please contact support@guide-ai.com to resolve this.',
              title: 'Pending Purchase',
              callBackFunction: () {
                Navigator.pop(context);
              });
        });
  }

  void handleError(IAPError error) async {
    print('Purchase Error');
    purchasePending = false;
    updateLoadingState(newLoadingState: false);
    ScaffoldMessenger.of(context).removeCurrentSnackBar();
    await showDialog(
        context: context,
        barrierDismissible: false,
        builder: (BuildContext context) {
          return OkDialog(
              content:
                  'Sorry, we couldn\'t take payment, please check your internet connection and payment account, and try again.',
              title: 'Purchase Failed',
              callBackFunction: () {
                Navigator.pop(context);
              });
        });
  }
```

**Comment by darshankawar** [comment]
Keeping this issue open for further insights from the team, as I am not completely sure where the issue could be.

/cc @mvanbeusekom

**Comment by stuartmorgan** [comment]
> The issue I'm having is that the purchase value being shown on the Apple In App Purchase pop-up is not correct.

Are you talking about the native UI displayed by iOS? A screenshot would be helpful here.

**Comment by RedHappyLlama** [comment]
Hi,

See images below. The white text is what the native UI should be showing. 

![A5266D84-F601-4997-81AE-97E82B4D4CD8](https://user-images.githubusercontent.com/64426705/144705680-f93fdf73-87e2-4da2-a37c-c5fbf0ca5591.jpeg)
![5B8DCBB7-A78C-4E70-9D79-EBC1A486AD4E](https://user-images.githubusercontent.com/64426705/144705681-daa10331-334c-4273-a294-a0d6f8267cfc.jpeg)

**Comment by stuartmorgan** [comment]
@mvanbeusekom @cyanglaz I'm not familiar with the internals of this plugin; does the plugin have any involvement here? The UI is native, and I assume (perhaps incorrectly) that the price configuration is handled on the Apple side.

**Comment by RedHappyLlama** [comment]
Just FYI, yesterday we released the app to the App Store and the issue does not occur. Therefore I suggest the issue is on the Apple side, specifically with TestFlight.

**Comment by mvanbeusekom** [comment]
Just to be sure I did a double check of the code and the in_app_purchase plugin doesn't do any permutations on the price. All information is mapped directly as it is received from the Store Kit API.

This (together with findings mentioned by @RedHappyLlama) leeds me to believe this is indeed an issue on the side of Apple in TestFlight or Sandbox environment.

**Comment by stuartmorgan** [comment]
Given that, I'm going to close as it doesn't sound like there's anything to be done at our end. Please file a new issue if new information surfaces that suggests an issue with the plugin.
