### ISSUE TITLE
Please create a fork for no-response action

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#94471]
**Purpose:** We have submitted patches and expecting to use the action from the source but there has been no traction on getting a new release which has been blocking us for months.

**Repo:** https://github.com/lee-dohm/no-response
**Commit:** caff5e7de24d19659c31dda1ff2520a3f6a88370

**Comment by godofredoc** [comment]
\cc @stuartmorgan the process to request a third party fork is documented here: go/flutter-thirdparty-fork.

It only requires to open a bug stating the purpose, the repo, the commit and assigning it to the infra ticket queue.

**Comment by CaseyHillers** [comment]
@godofredoc @stuartmorgan should this instead be a github fork instead of a git-on-borg fork?

**Comment by godofredoc** [comment]
Keeping forks in a single place would help to simplify maintenance but not sure if we win/lose something on forking it to GoB. @stuartmorgan may know more about that

**Comment by stuartmorgan** [comment]
I've never created a GitHub action before; I don't know what limitations, if any, there are on how it is hosted.

**Comment by CaseyHillers** [comment]
Based on https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace#publishing-an-action, it sounds like you need to host the fork on GitHub for it to be publishable as an action.

If that's the case, can @stuartmorgan fork this? Or should we have an official actions repo in the flutter organization?

**Comment by godofredoc** [comment]
That sounds like adding a lot of maintenance + a level of indirection to publish things we don't own.

Are there any alternative to the action?

**Comment by stuartmorgan** [comment]
Based on https://docs.github.com/en/actions/creating-actions/about-custom-actions it doesn't sound like we need to publish it, just host it.

**Comment by godofredoc** [comment]
I managed to fix the code to allow to release a new version of the plugin in my own fork. The PR is here:

https://github.com/lee-dohm/no-response/pull/234

@stuartmorgan are you ok on using the version of my fork temporarily while the PR is landed and the new release created?

**Comment by stuartmorgan** [comment]
I'm happy with any solution that works and that the infra team is comfortable with.

**Comment by godofredoc** [comment]
We created a temporary fork on my name. Once the PRs are submitted and the new release is ready we will get it back to use lee-dohm/no-response

**Comment by godofredoc** [comment]
Closing this bug, we didn't get any traction with the no-response action team.
