### ISSUE TITLE
(One click) Quick fix for all const warning.

### ISSUE THREAD

**Issue by reddnavneet** [flutter/flutter#94472]
There is no option available to fix all possible "quick fix". My application consists of more than 200 const warnings and there is no option available to fix them all at once.

**Comment by bernaferrari** [comment]
There is already a fix for this, you should try Dart 2.15 which is going to be stable this December.

**Comment by darshankawar** [comment]
@reddnavneet 
Try per above comment, ie, you'll need to switch to latest master to see the change.

**Comment by reddnavneet** [comment]
Yes, working in the master channel. Thank you.
