### ISSUE TITLE
Remove cached Xcode cipd package from staging engine builders

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#94474]
I'm testing a new Xcode cipd package and had to reuse a ref by removing it from a bad package and adding it to a new one.  The old one is still cached on the staging bots I was using to test (`install xcode` only took 1 second).  

Remove the old cached package from `build828-m9`, `build829-m9`, `build830-m9`, and `build831-m9` so I can test the new package.
https://github.com/flutter/flutter/issues/85555

**Comment by jmagman** [comment]
@CaseyHillers (gardener) I don't have a Linux corp device to ssh into the swarming bots re https://chrome-internal.googlesource.com/infra/infra_internal/+/HEAD/doc/swarming_ssh.md would you mind taking a look?

**Comment by CaseyHillers** [comment]
I don't have access to the GOLO labs. I filed a proposal to add the engprod team to get access.

**Comment by CaseyHillers** [comment]
I filed https://bugs.chromium.org/p/chromium/issues/detail?id=1276140#c1 to review the request.

@godofredoc did this get finished?

**Comment by godofredoc** [comment]
Yes, we can close this issue.
