### ISSUE TITLE
Flutter tree greenness table is missing engine tree data since 11/15

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#94487]
![image](https://user-images.githubusercontent.com/2148558/144301733-9f11f89f-c063-4a6d-ab7b-8df3ac121484.png)

**Comment by CaseyHillers** [comment]
\cc @keyonghan

**Comment by CaseyHillers** [comment]
Looking at the `BuildStatus` tables, engine main was returning a green tree status since 11/23.

**Comment by keyonghan** [comment]
This is due to branch switch from master to main.

**Comment by keyonghan** [comment]
cl/413786473 to include data from main. Now dashboards are up-to-date.
