### ISSUE TITLE
Flutter iOS app should set `CADisableMinimumFrameDurationOnPhone` to true in info.plist by default

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#94508]
`CADisableMinimumFrameDurationOnPhone` is required for an iOS app not to be restricted to 60hz frame rate on iPhone 13 pro and beyond.
To support high frame rate for newer devices, we should enable this by default in the template.
For existing app, a migration is needed. 

Note that enabling this is not sufficient for a flutter app to reach higher frame rate. Some other work is required for that to happen.
See: 
- [viable refresh rate](http://flutter.dev/go/variable-refresh-rate)
- https://github.com/flutter/flutter/issues/90675

**Comment by Hixie** [comment]
here's a proposed api for the framework: https://github.com/flutter/flutter/compare/master...Hixie:freq

**Comment by jmagman** [comment]
Example for migrating this in existing apps: https://gist.github.com/jmagman/d7b76fc20ff5d5808f6ce26ea3d622e9
