### ISSUE TITLE
Engine -> Flutter roll failing on ANR when requesting timeline

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#94505]
Starting with the roll here https://github.com/flutter/flutter/pull/94484

```
08:38 +10: test/integration.shard/timeline_test.dart: Can connect to the timeline without getting ANR from the application                                                                             
Warning: test isolate is still active after 5 minutes. This is likely an app-not-responding error and not a flake. See https://github.com/flutter/flutter/issues/79498 for the bug this test is attempting to exercise.

18:19 +10 -1: test/integration.shard/timeline_test.dart: Can connect to the timeline without getting ANR from the application [E]                                                                      
  TimeoutException after 0:15:00.000000: Test timed out after 15 minutes.
  dart:isolate  _RawReceivePortImpl._handleMessage
```

Initially suspecting the Dart roll here https://github.com/flutter/engine/pull/30011, which includes additional timeline events from https://dart.googlesource.com/sdk.git/+/ab0d8dc3b15bca336a70171d90fabbea99595ec3.

Another lead is that the first failing roll was the first to use today's randomization seed.

**Comment by jason-simmons** [comment]
Confirmed that this started with https://github.com/dart-lang/sdk/commit/ab0d8dc3b15bca336a70171d90fabbea99595ec3

Dart has reverted that commit (https://github.com/dart-lang/sdk/commit/08fc11c44ced0aaf44a0cb53c6c5e74b67df0419)

**Comment by zanderso** [comment]
Closing as presumed fix since the Dart revert has landed on the Dart dev branch, and the roller can restart.
