### ISSUE TITLE
android manifest uses-feature override

### ISSUE THREAD

**Issue by selvam920** [flutter/flutter#94526]
in plugin
    <uses-feature android:name="android.hardware.usb.host" android:required="true"/>
in my application
    <uses-feature android:name="android.hardware.usb.host" android:required="false"/>

in release apk,
    <uses-feature android:name="android.hardware.usb.host" android:required="true"/>

it's not override and some devices not visible in play store but this feature is optional,

how to override in plugin manifest xml

**Comment by darshankawar** [comment]
@selvam920 
Your question is better suited for support channels like StackOverflow, so please ask the same there.
Closing as this sounds more like support question rather than bug / issue.
