### ISSUE TITLE
PlatformException(NotAvailable, Security credentials not available., null, null) with android 10

### ISSUE THREAD

**Issue by ADLsourceCode** [flutter/flutter#94538]
PlatformException(NotAvailable, Security credentials not available., null, null) with android 10
 when Biometric Hardware is not available but faceid and pin is available and Pin is enabled by default.

its works well with android 8.

Below is the code i am using:-

```

 const iosStrings = const IOSAuthMessages(
        cancelButton: 'cancel',
        goToSettingsButton: 'settings',
        goToSettingsDescription: 'Please set up your Touch ID.',
        lockOut: 'Please re-enable your Touch ID');

     const androidStrings = AndroidAuthMessages(
      cancelButton: 'cancel',
      goToSettingsButton: 'settings',
      goToSettingsDescription: 'Please set up your Touch ID.',
      signInTitle: 'User Authorization Required',
    );


    // if(canCheckBiometrics) {
    //   if(availableBiometics.length > 0) {
        try {
          authenticated = await auth.authenticate(
            localizedReason: 'Please authenticate to proceed',
            useErrorDialogs: true,
            biometricOnly: false,
            stickyAuth: true,
            iOSAuthStrings: iosStrings,
            androidAuthStrings: androidStrings,
            sensitiveTransaction: true,
          );
        }  catch (e) {
          print(e);
          Toast.show("Error authenticating : "+e.toString(),context,duration:3,gravity: Toast.center);
        }
        if (!mounted) return;
        if (authenticated) {
          setState(() {
            isFingerprint = true;
          });
        }
        else{
          // setState(() {
          //   isFingerprint = true;
          // });
          print(authenticated);
          Toast.show("Authentication Failed",context,duration:2,gravity: Toast.center);
        }
```

**Comment by darshankawar** [comment]
@ADLsourceCode 
Can you provide `flutter doctor -v`, plugin version (local_auth) and probably a complete minimal code ?
Thanks.

**Comment by ADLsourceCode** [comment]
@darshankawar 

below is the flutter doctor:-
`[✓] Flutter (Channel stable, 2.5.3, on Mac OS X 10.15.2 19C57 darwin-x64, locale en-IN)
    • Flutter version 2.5.3 at /Users/akshay/Downloads/flutter-2
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (7 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/akshay/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    ✗ Flutter requires a minimum Xcode version of 12.0.1.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.10.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.62.3)
    • VS Code at /Users/akshay/Downloads/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • vivo 2015 (mobile) • 192.168.0.104:5555 • android-arm64 • Android 10 (API 29)`

**Comment by darshankawar** [comment]
@ADLsourceCode 
Can you try scenario from [this](https://github.com/flutter/flutter/issues/80259#issue-855742180) issue and see if you get same exception or not ?
