### ISSUE TITLE
Exceptions in IDE during debugging flutter web

### ISSUE THREAD

**Issue by Wissperwind** [flutter/flutter#94549]
Hi,

I get exceptions in the IDE during debugging.
Unfortunately I can NOT copy them. Just take screenshots
![1](https://user-images.githubusercontent.com/20759873/144437159-93c4dbb0-b34a-4a71-b8a9-82e82964372a.PNG)
![2](https://user-images.githubusercontent.com/20759873/144437157-005aa507-8fae-42ca-a9f3-5f986c535133.PNG)
![3](https://user-images.githubusercontent.com/20759873/144437153-0a4ca453-d7e6-4155-9250-82b24c27ec42.PNG)

These are not exceptions in my code. These are framework exceptions or something reladet.
I can not view variable content anymore by hover tooltip.

Flutter doctor:
[√] Flutter (Channel master, 2.6.0-12.0.pre.790, on Microsoft Windows [Version 10.0.19043.1348], locale de-DE)
    • Flutter version 2.6.0-12.0.pre.790 at C:\Users\akilian\Flutter SDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3a18e6ee42 (10 days ago), 2021-11-22 13:01:00 +0300
    • Engine revision ad00d12833
    • Dart version 2.16.0 (build 2.16.0-35.0.dev)
    • DevTools version 2.8.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\akilian\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\akilian\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.45
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 95.0.1020.53

! Doctor found issues in 1 category.

**Comment by darshankawar** [comment]
@Wissperwind 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/87856
Please follow-up in it for further updates.
Closing this as a duplicate.
