### ISSUE TITLE
request on dart pub publish --dry-run

### ISSUE THREAD

**Issue by X-SLAYER** [flutter/flutter#94551]
I think it might be helpful to add a check on the package name to avoid any conflicts because that happened to me I created a new package with a name already in use and that caused an error for me and spend some time figuring it out

**Comment by stuartmorgan** [comment]
`pub` is not part of Flutter; it has [its own issue tracker](https://github.com/dart-lang/pub/issues) where bugs and feature requests for it should be filed.
