### ISSUE TITLE
Add selectionControls actions callback to SelectableText

### ISSUE THREAD

**Issue by iqfareez** [flutter/flutter#94558]
## Use case

User should be able to see a visual cue of some action is done.

## Proposal

On `selectionControls` toolbar for `SelectableText` (or any `EditableText`), we have **copy**, **paste**, **select all**. It would be nice if Flutter can add callback method when user press those action.

Example: User pressed copy and a toast will appear.

I don't think there are such package on pub.dev (correct me if i'm wrong)

![flutter_05 (Play Store Icon)](https://user-images.githubusercontent.com/60868965/144462044-c42ae33e-52f1-42bc-941a-e72363412ccc.png)

**Comment by danagbemava-nc** [comment]
Hi @iqfareez, it looks like you can do this if you create a custom `TextSelectionControl` and I did find this package on pub. 
https://pub.dev/packages/text_selection_controls

Do let me know if it suits your needs

**Comment by iqfareez** [comment]
Thank you for your response 👍. I'll check it out and get back to you asap.

**Comment by iqfareez** [comment]
Hi. I've tested it and I think it suits my use case. Tqsm!
