### ISSUE TITLE
[Web] Uncaught TypeError: Cannot read properties of null (reading 'toString')

### ISSUE THREAD

**Issue by bibash28** [flutter/flutter#94553]
![image](https://user-images.githubusercontent.com/18188709/144443984-420a5aab-2df6-4594-9f1f-fdbc02238543.png)

Flutter web release mode issue

Occurs sometimes when I press the back button.

Package used:
  auto_size_text: ^3.0.0-nullsafety.0
  cached_network_image: ^3.1.0
  carousel_slider: ^4.0.0
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.3
  devicelocale: ^0.5.0
  flutter_inappwebview: ^5.3.2
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.0.8
  font_awesome_flutter: ^9.1.0
  get_it: ^7.2.0
  http: ^0.13.3
  image_picker: ^0.8.4
  image: ^3.0.4
  intl: 0.17.0
  observable_ish: ^3.0.0
  package_info: ^2.0.2
  path_provider: ^2.0.2
  platform_device_id: ^1.0.1
  provider: ^5.0.0
  responsive_builder: ^0.4.1
  shared_preferences: ^2.0.7
  stacked: ^2.2.5
  url_launcher: ^6.0.10
  url_strategy: ^0.2.0
  flutter_rating_bar: ^4.0.0

GetIt Use
![image](https://user-images.githubusercontent.com/18188709/144444627-0a0b4c17-d924-41e6-b15c-329a92cdd624.png)

main.dart
![image](https://user-images.githubusercontent.com/18188709/144444830-647a2682-f254-4cfc-81e9-0c9580056553.png)

**Comment by maheshmnj** [comment]
Hi @bibash28, Please share a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) without any third-party plugins, along with the output of `flutter doctor -v`.

Please prefer sharing text snippets over image snippets.

Thanks

**Comment by bibash28** [comment]
Removing following code from web/index.html solved the issue

<script src="main.dart.js" type="application/javascript"></script>
