### ISSUE TITLE
installing libimobiledevice from brew is failing on M1 macs

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#94567]
We need the idevice_id command for ios hosts. The mac M1 machines (and possibly intel macs) are using brew (flutter/idevice.sls) to install libimobiledevice which contains the command. Currently the brew pkgs are for that are not working, and fail while trying to install the libimobiledevice-glue-1.0 depenency (https://issueexplorer.com/issue/libimobiledevice/libimobiledevice/1217).

**Comment by yusuf-goog** [comment]
According to https://libimobiledevice.org/ for mac, the recommended way is to mac ports to install it. If we install this way, then the pkg is installed correctly and salt state continue to apply successfully.

We will need to install macports on the hosts for this to work, just as we install brew on them.

**Comment by yusuf-goog** [comment]
https://turquoise-internal-review.googlesource.com/c/infra/salt/+/446070

**Comment by godofredoc** [comment]
This is fixed!
