### ISSUE TITLE
Devicelab linux6 causes tests flaky

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#94566]
Related issue:
[Linux_android image_list_jit_reported_duration is 3.00% flaky](https://github.com/flutter/flutter/issues/93804)
[Linux_android image_list_reported_duration is 3.00% flaky](https://github.com/flutter/flutter/issues/94034)

**Comment by keyonghan** [comment]
Manually quarantined the bot.

**Comment by keyonghan** [comment]
Actions on this phone:
From @godofredoc 
> This was phone related. All the failures were coming from linux-6 which was hanging during logcat collection causing the test to timeout.

> The only way I found to get the phone to a working state was factory resetting it. After the test started passing consistently.

**Comment by godofredoc** [comment]
@keyonghan can we check if the phone has a rotated screen?

**Comment by keyonghan** [comment]
The screen is on vertical mode:
![screen](https://user-images.githubusercontent.com/54558023/144486707-90df94a6-d2e1-4deb-aa06-001cd492e4ce.png)

**Comment by godofredoc** [comment]
That screen helps a lot, it means the test succeeded but collecting logcat hangs. We should have a timeout for killing logcat if it does not complete within certain time window.

**Comment by keyonghan** [comment]
@dnfield Per https://github.com/flutter/flutter/issues/93661#issuecomment-969239056, we want the logcat to keep running for memory benchmark iteration. What would be a good timeout here?

**Comment by dnfield** [comment]
In that case logcat was unexpectedly exiting during a test. As long as we're not killing it during a test we should be ok.

**Comment by godofredoc** [comment]
Linux-6 has had too many issues independently of the phones. We need to reprovision the host os

**Comment by keyonghan** [comment]
> Linux-6 has had too many issues independently of the phones. We need to reprovision the host os

/cc @yusuf-goog Is this something you can help when you are in the lab?

**Comment by yusuf-goog** [comment]
yes, i'll look at it when i'm in the lab.

**Comment by godofredoc** [comment]
I'll grab it to do local testing today!

**Comment by godofredoc** [comment]
Tests are now passing consistently!
