### ISSUE TITLE
AnimatedSize not implementing ImplicitlyAnimatedWidget, not inheriting onEnd

### ISSUE THREAD

**Issue by footurist** [flutter/flutter#94570]
## Steps to Reproduce
Look for the [`AnimatedSize`](https://api.flutter.dev/flutter/widgets/AnimatedSize-class.html) widget in the Flutter documentation. Notice that `AnimatedSize` does not inherit `ImplicitlyAnimatedWidget`, thus not inheriting `onEnd`.

**Expected results:**
`AnimatedSize` inherits `ImplicitlyAnimatedWidget`, like the other [`AnimatedFoos`](https://api.flutter.dev/flutter/widgets/ImplicitlyAnimatedWidget-class.html) in order to enable making use of `onEnd`.

**Actual results:** 
`AnimatedSize` does not inherit `ImplicitlyAnimatedWidget`.

## Thoughts
Any reason why this is the case? I noticed it when I encountered the need for the `onEnd` callback.

**Comment by darshankawar** [comment]
@footurist 
Can you take a look at below links and see if they help ?
https://github.com/flutter/flutter/pull/38979
https://github.com/flutter/flutter/issues/48046
