### ISSUE TITLE
mac only pyobjc being installed in linux salt states 

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#94576]
flutter/packages.sls includes pyobjc in linux states. need to remove to only mac install.

**Comment by yusuf-goog** [comment]
https://turquoise-internal-review.googlesource.com/c/infra/salt/+/446210

**Comment by godofredoc** [comment]
@yusuf-goog  Can we close this bug?

**Comment by yusuf-goog** [comment]
yes
