### ISSUE TITLE
Apple Silicon - rosetta error: attachment of code signature supplement failed: 1 - Can't install iOS app

### ISSUE THREAD

**Issue by RyanHedges** [flutter/flutter#94581]
## Problem

Building and running a flutter iOS app onto a physical device fails when running from the command line with a Rosetta error.

## Steps to Reproduce

1. Using a "MacBook Pro (16-inch, 2021)" with "Apple M1 Pro" chip.
2. Create a new project using `fvm flutter create basic_app`
3. Run the app with `fvm flutter run -d "iPad" --verbose`
4. See failure near:
    ```
    [  +28 ms] rosetta error: /var/db/oah/279281325309952_279281325309952/dc4c59bb1dff0aa884c28fadc13744445357b86b618be2a399f12b005e7422a0/ios-deploy.aot: attachment of code signature supplement failed: 1
   ```

## Attempts to Resolve

* Running the rossetta update using `sudo softwareupdate --install-rosetta --agree-to-license` as [documented here](https://github.com/flutter/flutter/wiki/Developing-with-Flutter-on-Apple-Silicon).
* Make terminal "Open using rosetta" as [described here](https://github.com/CocoaPods/CocoaPods/issues/9907#issuecomment-655870749), which includes restarting terminal as a shot in the dark 😬.
* Running `fvm flutter run` targeting a simulator **_is successful_**.
* Following the directions "Try launching Xcode and selecting "Product > Run" to fix the problem" **_is successful_** at installing and running on the connected iPad but the command line continues to fail after.
* Running `fvm flutter clean` at various points while debugging.

## Logs

<details>
<summary>Logs: fvm flutter doctor --verbose</summary>

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-arm, locale en-US)
    • Flutter version 2.5.3 at /Users/hedges/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (7 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/hedges/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • iPad mini (6th generation) (mobile) • B977FA69-7092-4DEF-A76A-91E461055585 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 96.0.4664.55

• No issues found!
```
</details>

[fvm flutter create basic_app --verbose.txt](https://github.com/flutter/flutter/files/7645358/fvm.flutter.create.basic_app.--verbose.txt)

[fvm flutter run -d "iPad" --verbose.txt](https://github.com/flutter/flutter/files/7645360/fvm.flutter.run.-d.iPad.--verbose.txt)

## Other info

* [`FVM`](https://fvm.app/) version `2.2.4`
* Computer is fairly new and basically only has flutter development environment setup.
* Noticed the problem when trying to build a project from an old computer that no longer worked on the new one.

**Comment by danagbemava-nc** [comment]
Hi @RyanHedges, thanks for filing the issue. 

I'm on a 2020 m1 MacBook pro. 13". 

I attempted to reproduce this, but it runs on my physical device just fine, although in my case, it's an iPhone, I don't think that has any bearing on the issue at hand. 

May I suggest the following? 
1. Try either the `master` or `beta` channels to see if you still experience this issue
2. Check if there's any pending os updates that you have to do and see if you still experience this issue after the update. There has been reports of this happening with other applications on SO and for some people, the issue was resolved after an update. https://stackoverflow.com/questions/68204296/mac-m1-chip-issues-with-rosetta-attachment-of-code-signature-supplement-failed

**Comment by hnspn** [comment]
had the same error
went away on reboot

**Comment by RyanHedges** [comment]
I am just circling back to this. It's no longer an issue for my computer and my iPad. I'm guessing it's because my computer has been rebooted since I first reported the problem. Thank you @danagbemava-nc and @hnspn for your help!
