### ISSUE TITLE
Definition of implicit copy assignment operator for 'EmbeddedViewParams' is deprecated because it has a user-declared copy constructor

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#94586]
On clang 10 (testing Xcode 13 in the engine) there's a new [`-Wdeprecated-copy`](https://clang.llvm.org/docs/DiagnosticsReference.html#wdeprecated-copy) warning turned on.

```
In file included from ../../flutter/flow/surface.h:11:
../../flutter/flow/embedded_views.h:213:3: error: definition of implicit copy assignment operator for 'EmbeddedViewParams' is deprecated because it has a user-declared copy constructor [-Werror,-Wdeprecated-copy]
  EmbeddedViewParams(const EmbeddedViewParams& other) {
  ^
../../flutter/shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm:311:40: note: in implicit copy assignment operator for 'flutter::EmbeddedViewParams' first required here
  current_composition_params_[view_id] = EmbeddedViewParams(*params.get());
                                       ^
1 error generated.
```
https://logs.chromium.org/logs/flutter/led/magder_google.com/c7ee21d3bfaa2de210bcace2cfe3a6e8bce17c4248e474988720cadc7566cf87/+/u/build_ios_debug_sim_arm64/stdout

`EmbeddedViewParams` has a [copy constructor](https://github.com/flutter/engine/blob/2962099077b36704071802ea5595f4a016a1c214/flow/embedded_views.h#L213) and is missing a copy assignment constructor.

To reproduce locally:

```
./flutter/tools/gn --no-goma --unoptimized --ios --simulator --simulator-cpu=arm64 && ninja -C out/ios_debug_sim_unopt_arm64
```

**Comment by jmagman** [comment]
```c++
EmbeddedViewParams& operator=(const EmbeddedViewParams& e) = default;
```
?

**Comment by jmagman** [comment]
@cyanglaz I think you're the most familiar with this code?

**Comment by chinmaygarde** [comment]
Neither the copy or the copy-assignment are necessary (defaulted or otherwise). We should just get rid of the copy ctor definition.
