### ISSUE TITLE
Add underline property to DropdownButtonFormField

### ISSUE THREAD

**Issue by jaesam** [flutter/flutter#94589]
## Use case

Same as DropdownButton

## Proposal

DropdownButton has underline property to customize the underline but DropdownButtonFormField does not have the same. I couldn't seem to find one that talks about this in any of the issues but I do not think I am the only one needs this property to be added to DropdownButtonFormField as well. 

Or add a disabled property to apply disabledBorder in InputDecorationTheme. Currently there are two ways of disabling DropdownButtonFormField (passing null to onChanged or items) but both do not seem to trigger the disabledBorder property.

**Comment by danagbemava-nc** [comment]
Hi @jaesam, you can already add an `Underline` to the `DropdownButtonFormField`. 

You can use the `InputDecoration` and set the border as `UnderlineInputBorder`. 

If you want to trigger the `disabledBorder`, you can set the `enabled` property of the `InputDecoration` to false.

Does this suffice?

```dart
DropdownButtonFormField(
              items: ['Me', 'You'].map((String value) {
                return DropdownMenuItem<String>(
                  value: value,
                  child: Text(value),
                );
              }).toList(),
              onChanged: (String? newValue) {
                print(newValue);
              },
              decoration: const InputDecoration(
                enabled: true,
                disabledBorder: UnderlineInputBorder(
                  borderSide: BorderSide(
                    color: Colors.red,
                    width: 2,
                    style: BorderStyle.solid,
                  ),
                ),
              ),
            ),
```
