### ISSUE TITLE
Backend API to manage reverts

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#94592]
After enforcing the auto-submit bot every PR will be forced to run the full set of validations before being submitted by the bot. In some cases we would like to speed up the process to land clean reverts as soon as possible to get the tree back to a green state.

The API should be able to determine if a revert is clean checking if the commit is the ToT for a given branch. Once a revert is identified as a clean revert the bot would be able to bypass some of the validations to speed up the process of landing the revert.

**Comment by CaseyHillers** [comment]
Another bonus would be having the tree status reopen the tree immediately if it was a clean revert.

**Comment by godofredoc** [comment]
@ricardoamador can you please update this bug with the selected approach to implement reverts?

**Comment by ricardoamador** [comment]
The approach to handling reverts will be done in two steps. 
Step 1:
Initially the auto-submit bot will handle reverts. A developer will need to add the 'revert' label to the pull request which will trigger the autosubmit bot to respond and validate the pull request. 

Step 2:
The logic for handling the revert pull requests will be move out of the auto-submit bot into it own bot. We will then add the necessary components for the revert bot to handle the 'revert' label directly.

Notes:
The pull request must link to a previous commit where the files in the current commit are the same or a subset of the files in the linked commit as we want to make sure we are reverting previous changes. 

Once validated the bot will merge the request without waiting for CI validation or an approving request from another developer.

{TODO: ricardoamador} Link the design doc for the revert feature here once it has been reviewed.

**Comment by ricardoamador** [comment]
go/pull-request-revert-api

**Comment by ricardoamador** [comment]
This is the working implementation as of 09-20-2023.
flutter.dev/go/automated-revert-workflow
