### ISSUE TITLE
CVE - Vulnerabilities <libflutter.so>

### ISSUE THREAD

**Issue by HLUO18-ford** [flutter/flutter#94593]
Our security team has scanned the flutter sdk we are using for our project and found that it contains cve security ， please check to see if there is a fix available.
[cve_vulnerabilities.xlsx](https://github.com/flutter/flutter/files/7647050/cve_vulnerabilities.xlsx)

**Comment by HLUO18-ford** [comment]
The email address of your security team seems to be incorrect and I can't reach them.

**Comment by darshankawar** [comment]
@HLUO18-ford 
What version of flutter sdk you scanned and found out the behavior ?
