### ISSUE TITLE
Show a screen when a notification arrives like WhatsApp incoming call feature

### ISSUE THREAD

**Issue by AmnNdm** [flutter/flutter#94606]
## Use case

I was developing an application which has video calling feature, everything is working perfectly in flutter except when it comes to handling a notification (which I want to act like WhatsApp's Incoming Call Feature) when the app is terminated. Basically I want to show a "Ringing Screen" when a notification for call arrives and automatically show this screen and require user interaction on it rather than on the notification banner. It works fine when the App is open and navigates to the "Ringing Screen" as required but I have no way to handle it in flutter when the app is terminated. Obviously we can achieve it through writing platform specific codes but then that just doesn't fit right with me as it not only would make the coding part longer but also because I want to handle it though Flutter.
Over the past week I've searched through the internet and found similar problems that required to open an alert screen when a specific high priority notification (notification for call in my case) arrives when the app is terminated but didn't find a single universal and easy solution. I was hoping if there could be a library in flutter that would let developers to easily handle push notifications in however way we want even when the app is terminated.
Yes I've seen Flutter Local Notification and other background process plugins/packages but they just don't fit this use case. Neither is there any other single package that refers to this problem providing a solution for both Android and IOS.

## Proposal

I want Flutter to have a package that would allow to handle push notification in a way that we can define our own UI (banner, alert dialog or a whole screen) for a specific notification.
Like for example no matter which state (terminated, open or in background) the app is, when an "on call" notification arrives, a "Ringing Screen" should open and ask for user to take an action (similar to an alert dialog but a screen) - the whole mechanism working like the WhatsApp's Incoming Call Feature.
Similarly for more flexibility if the UI element is user defined then developers can easily define their own notification widgets for both Android and IOS (i.e. a ringing screen for Android and a ringing banner for IOS etc.)

**Comment by stuartmorgan** [comment]
This isn't something we would build a first-party package for, as the use case is highly specific. We encourage any interested community members to collaborate on a third-party package.
