### ISSUE TITLE
[Proposal] support flutter sdk encrypt compile to bytecode

### ISSUE THREAD

**Issue by lozn** [flutter/flutter#94604]
## Use case

The flutter code is intended to be hidden or obfuscated and packaged into sdK-specific irreversible packages for use by third parties  
## Proposal
   I wrote an SDK for third party developers to use, but the Flutter code was exposed. I needed to compile the encrypted code to prevent third party users from seeing the source code  

For example, in Android development, complie to dex, android to-jar packages can be compiled as SDKS and provided to third parties, and the code names inside are scrambled and confused. To be confused with meaningless names , Hopefully Flututer will support it in the future.

**Comment by maheshmnj** [comment]
Hi @lozn, can you please take a look at this https://docs.flutter.dev/deployment/obfuscate and see if this answers your use case.
Thanks

**Comment by lozn** [comment]
The method mentioned in this link does not solve the requirement, this method can only be confused into the final compiled APK/IPA, and my requirement is confused into the SDK for third party to use.

**Comment by maheshmnj** [comment]
> The method mentioned in this link does not solve the requirement, this method can only be confused into the final compiled APK/IPA, and my requirement is confused into the SDK for third party to use.

@lozn Do you mean to obfuscate the source code before compilation? Can you please elaborate on this in detail?

Thanks
