### ISSUE TITLE
Many plugin examples are still using v1 embedding

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#94617]
I assume this will become a hard error at some point in the future, and for now it's causing a lot of spam in test output.

E.g., this analyze run:
https://api.cirrus-ci.com/v1/task/5668589068877824/logs/main.log
prints the v1 deprecation warning 23 times; it's a substantial portion of the output.

We should update all of these ASAP. I thought this had already been done (https://github.com/flutter/plugins/pull/4160, https://github.com/flutter/plugins/pull/4189) but apparently that didn't get everything.

/cc @blasten @camsim99

**Comment by blasten** [comment]
The new check is more strict, so it's possible that some of the conditions are failing.

`android_alarm_manager` seems migrated, e.g.:
https://github.com/flutter/plugins/blob/master/packages/android_alarm_manager/example/android/app/src/main/AndroidManifest.xml

@GaryQian assigning to you to add more logs to the output. For example, what checks are exactly failing.

**Comment by GaryQian** [comment]
The detection of v1 embedding explicitly checks for the presence of an XML metadata element of `flutterEmbedding` with value of `2`. Plugins don't have this, so the check needs to account for this and not show the warning.

**Comment by GaryQian** [comment]
Improved logging landed, should be able to easily identify where each message is coming from

**Comment by blasten** [comment]
Thanks.

https://api.cirrus-ci.com/v1/task/6616450099052544/logs/main.log

It seems like there's a bug. plugins don't have AndroidManifest.xml necessarily and even when they do, there's no migration needed.

**Comment by GaryQian** [comment]
Yeah, must have missed a short circuit somewhere. Plugins repo should be migrated already.
