### ISSUE TITLE
[Proposal][video_player][web] Provide a way to reliably check whether or not a video has buffered enough to play video consistently

### ISSUE THREAD

**Issue by NicolasDionB** [flutter/flutter#94630]
## Use case
On web, using `video_player`, if I start a video and wait for it to be buffered to start playing, it often results as it doesn't have enough data and falls back in buffering mode again. It all depends on the connection speed indeed but this makes playing unpredictable.

## Proposal
The latest version of `video_player` plugin sets buffering as `false` as soon as `onCanPlay` is called. To make the behavior more predictable, only the `onCanPlayThrough` should set it to `false`, as we can be sure that we have enough data to actually play the video, uninterrupted.

Another idea could be to have different status or at least some way of knowing if it is really buffered enough (onCanPlayThrough).

In the end, the important part for us is to be able to differentiate the buffer state and be able to tell if playing the video is actually doable.

**Comment by danagbemava-nc** [comment]
Hi @NicolasDionB, thanks for filing the issue. 

If I understand this correctly, you want a way to reliably tell whether or not a video has buffered enough to consistently play a video on web. 

Is that correct?

**Comment by NicolasDionB** [comment]
@danagbemava-nc That is correct! Being able to get this information is crucial. Thanks!

**Comment by ditman** [comment]
@NicolasDionB, do you have a sample app where we can test the changes to the plugin?

I think all you're proposing is deleting this line of code:

* https://github.com/flutter/plugins/blob/master/packages/video_player/video_player_web/lib/video_player_web.dart#L206

So only "onCanPlayThrough" removes the buffering state, but I want this to have a good way of testing different implementations. For example: ensuring that onCanPlay and onCanPlayThrough are always fired (after seeking, or when auto-playing)

**Comment by NicolasDionB** [comment]
@ditman I do not have a sample code right now as my implementation is kind of complex! But I can work on a working sample for sure.

But yeah, that specific line is the problem and if one is to remove it, we need to be sure it's still working correctly on all supported browsers. That's why I was suggesting that we add some extra information to be able to tell which handler really got the event. For instance, keeping the `isBuffering` as-is but have an extra property, `canPlayThrough` that could be use to reliably tell if I can actually start playing the video. Maybe that's just too much complexity but, that's an idea.

**Comment by ditman** [comment]
@NicolasDionB I think that if we want the videoplayer to keep buffering until `canPlayThrough`, we can just use the `isBuffering` and rely on the events that the browser is sending our way (instead of adding another layer of complexity around them!). If you prepare a sample repro app, we can verify it works without removing the buffering state in that particular event (that bit was added not too long ago, definitely wasn't "needed" in earlier versions of the plugin!)

**Comment by NicolasDionB** [comment]
@ditman I finally prepared a little repro app, based on the "Play and pause a video" found in this [documentation page](https://docs.flutter.dev/cookbook/plugins/play-video). It's not full proof but it illustrates the problem I found. Using a Network limiter, I can reproduce the problematic behavior. The button is disabled at first. As soon as the video player is initialized, I put it on pause, then when it reports `isBuffering=false`, I hit the Play button. The video plays as expected but after a few seconds (depending on the bandwith limit you set), if will fall back in buffering state. Hope this helps!

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

void main() => runApp(const VideoPlayerApp());

class VideoPlayerApp extends StatelessWidget {
  const VideoPlayerApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Video Player Demo',
      home: VideoPlayerScreen(),
    );
  }
}

class VideoPlayerScreen extends StatefulWidget {
  const VideoPlayerScreen({Key? key}) : super(key: key);

  @override
  _VideoPlayerScreenState createState() => _VideoPlayerScreenState();
}

class _VideoPlayerScreenState extends State<VideoPlayerScreen> {
  late VideoPlayerController _controller;
  late Future<void> _initializeVideoPlayerFuture;
  bool _playing = false;
  bool _isBuffering = true;

  @override
  void initState() {
    _controller = VideoPlayerController.network(
      'http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_2160p_60fps_normal.mp4',
    );

    _initializeVideoPlayerFuture = _controller.initialize().then((value) {
      _controller.addListener(() {
        // Monitor video status
        bool isBuffering = _controller.value.isBuffering;
        if (isBuffering != _isBuffering) print(isBuffering ? 'Buffering' : 'Buffering done');
        if (_controller.value.isPlaying != _playing || isBuffering != _isBuffering) {
          setState(() {
            _playing = _controller.value.isPlaying;
            _isBuffering = isBuffering;
          });
        }
      });
      // Pause at start so video buffering begins
      _controller.pause();
    });

    _controller.setLooping(true);

    super.initState();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Butterfly Video'),
      ),
      // Use a FutureBuilder to display a loading spinner while waiting for the
      // VideoPlayerController to finish initializing.
      body: FutureBuilder(
        future: _initializeVideoPlayerFuture,
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.done) {
            // If the VideoPlayerController has finished initialization, use
            // the data it provides to limit the aspect ratio of the video.
            return AspectRatio(
              aspectRatio: _controller.value.aspectRatio,
              // Use the VideoPlayer widget to display the video.
              child: VideoPlayer(_controller),
            );
          } else {
            // If the VideoPlayerController is still initializing, show a
            // loading spinner.
            return const Center(
              child: CircularProgressIndicator(),
            );
          }
        },
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _isBuffering
            ? null
            : () {
                // Wrap the play or pause in a call to `setState`. This ensures the
                // correct icon is shown.
                setState(() {
                  // If the video is playing, pause it.
                  if (_controller.value.isPlaying) {
                    _controller.pause();
                  } else {
                    // If the video is paused, play it.
                    _controller.play();
                  }
                });
              },
        // Display the correct icon depending on the state of the player.
        child: Icon(
          _playing ? Icons.pause : Icons.play_arrow,
        ),
      ),
    );
  }
}
```

**Comment by ditman** [comment]
Let me try to deploy your test app with a slightly modified version of the video player plugin, see if it improves the behavior!

**Comment by itsdani121** [comment]
if i want to play video as like youtube list that swipe and video automatically play and after screen out it stops so what is the procedure ?

**Comment by ditman** [comment]
> if i want to play video as like youtube list that swipe and video automatically play and after screen out it stops so what is the procedure ?

@itsdani121 please, post that question in [the 'flutter' tag of StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or the `#help` channel at flutter's [discord server](https://github.com/flutter/flutter/wiki/Chat).

**Comment by NicolasDionB** [comment]
@ditman Did you have time to test your modified version?

**Comment by ditman** [comment]
Yikes, no. Let me work on testing and landing this ASAP. Apologies @NicolasDionB, this fell through the cracks of my github notifications!

**Comment by ditman** [comment]
OK here we go:

```
$ flutter build web

Warning: You are using these overridden dependencies:
! video_player_web 2.0.8 from git https://github.com/ditman/plugins.git at d292a0 in packages/video_player/video_player_web
Running "flutter pub get" in issue_94630...                        890ms

💪 Building with sound null safety 💪

Compiling lib/main.dart for the Web...                             24.6s

$ firebase deploy

...
✔  Deploy complete!

Hosting URL: https://dit-videoplayer-tests.web.app
```

**Comment by ditman** [comment]
I've tested in Firefox, Safari and Chrome on MacOS and Chrome and Safari on iOS, and it seems to work well. Anybody else willing to give the webapp above a test?

**Comment by NicolasDionB** [comment]
Thaïs dire that, I've tested it on Chrome on Android and it works well, I'll test it on more browsers this week.

**Comment by ditman** [comment]
Thanks @NicolasDionB, I'll get the PR mergeable and try to add you there as a reviewer.

**Comment by ditman** [comment]
The PR is here: https://github.com/flutter/plugins/pull/5068

**Comment by NicolasDionB** [comment]
@ditman Looks all good to me. The `onCanPlayThrough` method has been supported on all browser for a long time now so this should work like a charm. Thanks for the PR!

**Comment by NicolasDionB** [comment]
Thanks guys for the fix. Quick question: is there a way to know when it's going to be available on the stable channel or the Flutter version?

**Comment by ditman** [comment]
@NicolasDionB this is a plugin. It's already [published](https://pub.dev/packages/video_player_web)!

Ensure that you're using video_player_web 2.0.8 (check your pubspec.lock file, it tells you what version is being downloaded).
