### ISSUE TITLE
why reload images in Flutter?

### ISSUE THREAD

**Issue by poison8** [flutter/flutter#94648]
After each picture is larger than 50kb, the redirect route will return and the picture will be reloaded. Is there a bug in flutter image Wdiget?

https://user-images.githubusercontent.com/15606445/144695779-1cfb861b-416f-4b9f-a75f-9d490efcc3af.mp4

**Comment by Sahil-kachhap** [comment]
> After each picture is larger than 50kb, the redirect route will return and the picture will be reloaded. Is there a bug in flutter image Wdiget?
> 
>  QQ.20211204114629.mp4

Thanks for filing this issue. Can you show any reproducible code for regenerating this issue . 

I am not sure but may be it has something to do with asynchronous programming. Are you fetching those images from any API ?

**Comment by poison8** [comment]
> 
this api is https://80put.wanmeiku.cn/api/api/yy.html

**Comment by darshankawar** [comment]
@poison8 
Please provide your `flutter doctor -v` and a [complete minimal reproducible code sample ](https://stackoverflow.com/help/minimal-reproducible-example)without any 3rd party plugins, so that we can take a look at the behavior properly.

Also, take a look at this documentation for your reference and see if it helps : https://docs.flutter.dev/cookbook/networking/fetch-data

**Comment by poison8** [comment]
Just use static arrays directly
class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

   List data=[
      "https://thumb.apqil.cn/image/6f434ee1e041ed58644fb14e56700120.png", 
      "https://thumb.apqil.cn/image/c7c25111e52e3ff713a67c9eab35a790.png", 
      "https://thumb.apqil.cn/image/90f2c0596a2632e61cc4a56f62c16ea6.png", 
      "https://thumb.apqil.cn/image/4b1b673c028719b57c3c16a2a46dc820.png", 
      "https://thumb.apqil.cn/image/f475d92eb81265ea2524159c24af7c8c.png", 
      "https://thumb.apqil.cn/image/9fff88cfe270046c74a1b020fa991e97.png", 
      "https://thumb.apqil.cn/image/84709d4cf0c24e0e755f2d8d90e9fad7.png", 
      "https://thumb.apqil.cn/image/a588a8d68acc0d2452f2d3c085673cfa.png",
      "https://thumb.apqil.cn/image/3c1d7895a413e43ab9f15dcbe5716705.png",
      "https://thumb.apqil.cn/image/4e8cdadc4c4842aee5a1ab17ec24f2fc.png",
      "https://thumb.apqil.cn/image/01053e14bd79da160f2122f4ad3dbd88.png",
      "https://thumb.apqil.cn/image/6abf0eae715c208cd0a2ba2ccefc1d4e.png",
      "https://thumb.apqil.cn/image/80c5d9e776d042dfc0e8c9083b6777f2.png",
      "https://thumb.apqil.cn/image/54378883fe0e61a1990f71d4b102b067.png",
      "https://thumb.apqil.cn/image/0e2164ce3236794d043930c395bae950.png",
      "https://thumb.apqil.cn/image/2468dd01fd832e4138557f7eeeeb8a7c.png",
      "https://thumb.apqil.cn/image/312930835cc2942c8a8e06c03a1cebe0.png",
      "https://thumb.apqil.cn/image/8d32c176f20e4ba8664b6daf704d67c0.png",
      "https://thumb.apqil.cn/image/9e6b8417263d2a1037bd48e181ae5649.png",
      "https://thumb.apqil.cn/image/4c494a26b862962253b5edd749d53885.png",
      "https://thumb.apqil.cn/image/a5fc301bef84e5033e35d691c2b4cfcb.png",
      "https://thumb.apqil.cn/image/99063a6d7f49d56217477c394c719061.png",
      "https://thumb.apqil.cn/image/e37d2c490da00833dedeb0faf74aa0e0.png",
      "https://thumb.apqil.cn/image/c0dd167df2b32459d9712e3b2e7471b4.png",
      "https://thumb.apqil.cn/image/e36bfd8d733c99457c88090bd08d4037.png",
      "https://thumb.apqil.cn/image/2c2fb704ee5b9e571644fb4c09441943.png",
      "https://thumb.apqil.cn/image/cd9a01aca5324a2ad73529fc807cffe8.png",
      "https://thumb.apqil.cn/image/7be2da2554bf69f1cb24986b7b368598.png"];



Widget _MovieList(List data) {
    return Container(
      margin: EdgeInsets.only(top: 10),
      padding: EdgeInsets.only(left: 20, right: 20),
      child: GridView.builder(
        physics: NeverScrollableScrollPhysics(),
        itemCount: data.length,
        shrinkWrap: true,
        padding: EdgeInsets.zero,

        addAutomaticKeepAlives:false,
        addRepaintBoundaries:false,
        addSemanticIndexes:false,
        cacheExtent:9999,
        gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
            childAspectRatio: 0.65,
            crossAxisCount: 3,
            crossAxisSpacing: 8,
            mainAxisSpacing: 3),
        itemBuilder: (context, index) {
          return InkWell(
            splashColor: Colors.transparent,
            onTap: () {
              Navigator.push(context, new MaterialPageRoute(builder: (context)=>Detail()));
            },
            child: Column(
              children: [
                Column(
                  children: [
                    Stack(
                      children: [
                        Container(
       
                            width: 300,
                            height: 290,
                            //  width: double.infinity,
                            // height: Adapt.px(280),
                            child: ClipRRect(
                              borderRadius: BorderRadius.circular(20),
                          
                              child: CachedNetworkImage(imageUrl: "${data[index]}",)
                              )
                            ),
  
                      ],
                    ),
                    SizedBox(
                      height: 15,
                    ),
                    Container(
                      padding: EdgeInsets.all(2),
                      //  alignment: Alignment.center,
                      width: double.infinity,
                      height: 40,
                      //  height:Adapt.px(80) ,
                      child: Text("سىناق",
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 19.6,
                          ),
                          maxLines: 1,
                          overflow: TextOverflow.ellipsis,
                          textAlign: TextAlign.center,
                          textDirection: TextDirection.rtl),
                    )
                  ],
                ),
              ],
            ),
          );
        },
      ),
    );
  }

 @override
  Widget build(BuildContext context) {
    
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        toolbarHeight: 0,
        title: Text(widget.title),
      ),
      body: Container(
        color:Colors.red,
        alignment: Alignment.center,

        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: 
        
         Container(
           color:Colors.red,
        
           child: SingleChildScrollView(
             child: Column(
                children:[
                  
      

          _MovieList(data),


                ],
              ),
           ),
          ),
              
                 

       
      
        ),
         
    );

  
  }
  

}






![image](https://user-images.githubusercontent.com/15606445/144958384-0402b367-27d4-4080-80b8-b5e29ea53c91.png)

**Comment by poison8** [comment]
@darshankawar  Just use static arrays directly     
After jumping to a page and back to the previous page, the picture will be reloaded

**Comment by darshankawar** [comment]
> Also, take a look at this documentation for your reference and see if it helps : https://docs.flutter.dev/cookbook/networking/fetch-data

Did you take a look at this link and see if it helps ?

**Comment by poison8** [comment]
@darshankawar 
This is a static array,not use fetch

**Comment by poison8** [comment]
@darshankawar 
List data=[
      "https://thumb.apqil.cn/image/6f434ee1e041ed58644fb14e56700120.png", 
      "https://thumb.apqil.cn/image/c7c25111e52e3ff713a67c9eab35a790.png", 
      "https://thumb.apqil.cn/image/90f2c0596a2632e61cc4a56f62c16ea6.png", 
      "https://thumb.apqil.cn/image/4b1b673c028719b57c3c16a2a46dc820.png", 
      "https://thumb.apqil.cn/image/f475d92eb81265ea2524159c24af7c8c.png", 
      "https://thumb.apqil.cn/image/9fff88cfe270046c74a1b020fa991e97.png", 
      "https://thumb.apqil.cn/image/84709d4cf0c24e0e755f2d8d90e9fad7.png", 
      "https://thumb.apqil.cn/image/a588a8d68acc0d2452f2d3c085673cfa.png",
      "https://thumb.apqil.cn/image/3c1d7895a413e43ab9f15dcbe5716705.png",
      "https://thumb.apqil.cn/image/4e8cdadc4c4842aee5a1ab17ec24f2fc.png",
      "https://thumb.apqil.cn/image/01053e14bd79da160f2122f4ad3dbd88.png",
      "https://thumb.apqil.cn/image/6abf0eae715c208cd0a2ba2ccefc1d4e.png",
      "https://thumb.apqil.cn/image/80c5d9e776d042dfc0e8c9083b6777f2.png",
      "https://thumb.apqil.cn/image/54378883fe0e61a1990f71d4b102b067.png",
      "https://thumb.apqil.cn/image/0e2164ce3236794d043930c395bae950.png",
      "https://thumb.apqil.cn/image/2468dd01fd832e4138557f7eeeeb8a7c.png",
      "https://thumb.apqil.cn/image/312930835cc2942c8a8e06c03a1cebe0.png",
      "https://thumb.apqil.cn/image/8d32c176f20e4ba8664b6daf704d67c0.png",
      "https://thumb.apqil.cn/image/9e6b8417263d2a1037bd48e181ae5649.png",
      "https://thumb.apqil.cn/image/4c494a26b862962253b5edd749d53885.png",
      "https://thumb.apqil.cn/image/a5fc301bef84e5033e35d691c2b4cfcb.png",
      "https://thumb.apqil.cn/image/99063a6d7f49d56217477c394c719061.png",
      "https://thumb.apqil.cn/image/e37d2c490da00833dedeb0faf74aa0e0.png",
      "https://thumb.apqil.cn/image/c0dd167df2b32459d9712e3b2e7471b4.png",
      "https://thumb.apqil.cn/image/e36bfd8d733c99457c88090bd08d4037.png",
      "https://thumb.apqil.cn/image/2c2fb704ee5b9e571644fb4c09441943.png",
      "https://thumb.apqil.cn/image/cd9a01aca5324a2ad73529fc807cffe8.png",
      "https://thumb.apqil.cn/image/7be2da2554bf69f1cb24986b7b368598.png"];

**Comment by poison8** [comment]
jumping to a page and back to the previous page, the picture will be reloaded

**Comment by darshankawar** [comment]
@poison8 
Can you try to wrap them in a `StatefulWidget` and extend `AutomaticKeepAliveClientMixin` in its state and see if it helps or still shows same behavior ?

**Comment by poison8** [comment]
> @poison8 Can you try to wrap them in a `StatefulWidget` and extend `AutomaticKeepAliveClientMixin` in its state and see if it helps or still shows same behavior ?

I have used wrap and all widgets are the same. Reload the picture. It’s because there is a bug in flutter itself.
With react-native, there is no such situation, flutter will have this kind of bug

**Comment by poison8** [comment]
> @poison8 Can you try to wrap them in a `StatefulWidget` and extend `AutomaticKeepAliveClientMixin` in its state and see if it helps or still shows same behavior ?

I’ve tested it all, and it’s still the same to reload, it seems that flutter itself has this bug

**Comment by darshankawar** [comment]
It seems you are hitting https://github.com/flutter/flutter/issues/68700, so please follow-up in it for further updates.
Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.

**Comment by poison8** [comment]
@darshankawar 
class _MyHomePageState extends State<MyHomePage> with AutomaticKeepAliveClientMixin {
  @override
bool get wantKeepAlive => true;


I've used it all, but still the same can't solve the problem, it seems that flutter has this kind of bug


It has been tested for more than a month. After all the methods have been tried, can the same be solved for me?
