### ISSUE TITLE
How To User Flutter Clipboard Get Picture

### ISSUE THREAD

**Issue by 3215466800** [flutter/flutter#94644]
How To User Flutter Clipboard Get Picture

[#32045](https://github.com/flutter/flutter/issues/32045)

**Comment by Qingzii** [comment]
me too

**Comment by 3215466800** [comment]
> me too

me too too

**Comment by Cwt-ting** [comment]
I also want to know

**Comment by suwenhao** [comment]
me too too

**Comment by 53390240** [comment]
me too too

**Comment by stuartmorgan** [comment]
Please do not intentionally file duplicates; it serves no useful purpose.

**Comment by 3215466800** [comment]
> Please do not intentionally file duplicates; it serves no useful purpose.

yes is no useful  but how To User Flutter Clipboard Get Picture??

#32045
