### ISSUE TITLE
Can I enable null-safety feature in Flutter 1.22.6 ?

### ISSUE THREAD

**Issue by ChannelYu** [flutter/flutter#94650]
Our team have two projects.  
One runs on version 2.5.3 which has been migrated to null-safety syntax,  while another older project is running on version 1.22.6. For some reason, we can't just upgrade the older to Flutter 2.x.    : ( 

And now, we want to add some code written using null-safety syntax From the new project to the older!!!

If we have to manually change something like
`string?.isNotEmpty` to `string != null && string. isNotEmpty `,
`size!.width` to `size.width` ,
`required xxx` to `@required xxx`
...
This will be a HUGE amount of work and may cause a lot of troubles!

But I'm amazed to see some source code on 1.22.6 already use null-safety syntax! (eg. flutter/src/painting/borders.dart)

So, how can we make a mixed-version program like yours ??

**Comment by darshankawar** [comment]
@ChannelYu 
null-safety was introduced as part of Dart 2.12 and Flutter 2, so I am not sure if you can use that feature in versions prior to the one I mentioned. 
Also, if you want to migrate your project to null-safety, take a look at this document and see if it helps. https://dart.dev/null-safety/migration-guide
Moreover, your question isn't actually a bug or feature request, so closing this from here. You may ask the same on support channels like StackOverflow.
