### ISSUE TITLE
Downloading Material fonts...  | Oops; flutter has exited unexpectedly.

### ISSUE THREAD

**Issue by MasterChenGitHub** [flutter/flutter#9465]
Mac-mini:dev Master$ flutter doctor
Downloading Dart SDK 1.23.0-dev.11.7...
######################################################################## 100.0%
Building flutter tool...
Downloading Material fonts...                            |
Oops; flutter has exited unexpectedly.
Sending crash report to Google.
|Crash report sent (report ID: 1d6f4c4e90000000)

**Comment by mit-mit** [comment]
Sorry to hear @MasterChenGitHub. Were you able to resolve this? Do you see the error on every run of doctor?

**Comment by waitaamon** [comment]
Building flutter tool...
Downloading Material fonts...                                    
Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 4e98f4f8a1255614)
Crash report written to /home/amon/flutterApp/flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.

still getting this error on ubuntu 17.10

**Comment by zoechi** [comment]
Sorry for not coming back to this earlier.
I assume this issue is stale. Please let us know if you're still seeing this problem.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
