### ISSUE TITLE
How to set Flutter engine compilation parameters

### ISSUE THREAD

**Issue by cj3479** [flutter/flutter#94658]
How to set Flutter engine compilation
such for iOS, -fno-rtti  -arch arm64   -fno-inline-functions   fobjc-call-cxx-cdtors -std=c++17 and so on 
like xcode build settings

**Comment by stuartmorgan** [comment]
The Flutter engine uses GN, which you can learn about [here](https://gn.googlesource.com/gn/)

In the future, Discord or a similar resource is the right place for questions; the issue tracker is for bug reports and feature requests.
