### ISSUE TITLE
live chat flutter display image live chat (There is a video explaining the problem)

### ISSUE THREAD

**Issue by AzzamSuliiman** [flutter/flutter#94660]
Hello everyone, I have a problem with displaying pictures in the conversation, there is a video explaining the problem

https://user-images.githubusercontent.com/92028153/144712279-4efca609-8a8e-4428-bd87-b29dedbe8f17.mp4

**this code of chat screen.dart**

`import 'dart:io' show File;

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:file_picker/file_picker.dart';
import 'package:firebase_auth/firebase_auth.dart' as firebase_auth;
import 'package:firebase_storage/firebase_storage.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:image_picker/image_picker.dart';
import 'package:uuid/uuid.dart';

import '../../../common/constants.dart';
import '../../../generated/l10n.dart';
import '../../../models/index.dart' show User;
import '../../../screens/base_screen.dart';
import '../../../services/index.dart';
import '../firebase_service.dart';
import 'chat_typing.dart';
import 'messages.dart';

firebase_auth.User? loggedInUser;

class ChatScreen extends StatefulWidget {
  final User? senderUser;
  final String? receiverEmail;
  final String? receiverName;

  const ChatScreen({
    required this.senderUser,
    required this.receiverEmail,
    required this.receiverName,
  });

  @override
  _ChatScreenState createState() => _ChatScreenState();
}

class _ChatScreenState extends BaseScreen<ChatScreen> {
  final messageTextController = TextEditingController();
  var uuid = const Uuid();
  String messagesText = '';
  File? imageFile;
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  String? documentId;
  String? imageUrl;

  get platform => null;
  Future getImage() async {
    ImagePicker _picker = ImagePicker();

    await _picker.pickImage(source: ImageSource.gallery).then((xFile) {
      if (xFile != null) {
        imageFile = File(xFile.path);
        uploadImage();
      }
    });
  }
  Future selectFile() async {
    final result = await FilePicker.platform.pickFiles(allowMultiple: false);

    if (result == null) return;
    final path = result.files.single.path!;

    File? file;
    setState(() => file = File(path));
    await uploadImage();
  }

  Future uploadImage() async {
    String fileName = Uuid().v1();
    int status = 1;

    await _firestore
        .collection('chatroom')
        .doc(documentId)
        .collection('chatscreen')
        .doc(fileName)
        .set({
      'sender': widget.senderUser!.email,
      'message': 'img',
      'type': 'img',
      'time': FieldValue.serverTimestamp(),
    });

    var ref =
    FirebaseStorage.instance.ref().child('images').child("$fileName.png");

    var uploadTask = await ref.putFile(imageFile!).catchError((error) async {
      await _firestore
          .collection('chatroom')
          .doc(documentId)
          .collection('chatscreen')
          .doc(fileName)
          .delete();

      status = 0;
    });

    if (status == 1) {
      var imageUrl = await uploadTask.ref.getDownloadURL();

      await _firestore
          .collection('chatroom')
          .doc(documentId)
          .collection('chatscreen')
          .doc(fileName)
          .update({"message": imageUrl});

      print(imageUrl);
    }
  }

  @override
  void afterFirstLayout(BuildContext context) async {
    try {
      final snapshot = await FirebaseServices()
          .firestore!
          .collection('chatRooms')
          .doc(widget.receiverEmail! + '-' + widget.senderUser!.email!)
          .get();
      if (!snapshot.exists) {
        setState(() {
          documentId = widget.senderUser!.email! + '-' + widget.receiverEmail!;
        });
      } else {
        setState(() {
          documentId = widget.receiverEmail! + '-' + widget.senderUser!.email!;
        });
      }

      //update unread
      final item = await FirebaseServices()
          .firestore!
          .collection('chatRooms')
          .doc(documentId)
          .get();
      if (item.exists) {
        List users = item.data()!['users'];
        final obj = users.firstWhere((o) => o['email'] == widget.receiverEmail,
            orElse: () => null);

        await FirebaseServices()
            .firestore!
            .collection('chatRooms')
            .doc(documentId)
            .set({
          ...item.data()!,
          'users': [
            {
              'email': widget.senderUser!.email,
              'name': widget.senderUser!.name,
              'unread': 0
            },
            {
              'email': widget.receiverEmail,
              'name': widget.receiverName,
              'unread': obj['unread']
            }
          ]
        }, SetOptions(merge: true));
      }

      //update chatwith
      await FirebaseServices()
          .firestore!
          .collection('users')
          .doc(widget.senderUser!.email)
          .set({'chatWith': widget.receiverEmail}, SetOptions(merge: true));
    } catch (e) {
      printLog(e.toString());
    }
  }

  void sendMessage({imgUrl, text}) {
    FirebaseServices()
        .firestore!
        .collection('chatRooms')
        .doc(documentId)
        .collection('chatScreen')
        .add({
      'text': text ?? '',
      'sender': widget.senderUser!.email,
      'createdAt': DateTime.now().toUtc().toIso8601String(),
      'image': imgUrl ?? '',
      "message": imageUrl
    });
    final message = imgUrl != null
        ? widget.senderUser!.name! + ' has sent an image.'
        : text;
    FirebaseServices()
        .firestore!
        .collection('chatRooms')
        .doc(documentId)
        .get()
        .then((snapshot) {
      var updates = {
        'userTyping': false,
        'adminTyping': false,
        'lastestMessage': message,
        'userEmail': widget.senderUser!.email,
        'createdAt': DateTime.now().toUtc().toIso8601String(),
        'isSeenByAdmin': true,
        'message': imageUrl,
      };
      int? unread = 0;
      if (snapshot.exists) {
        List users = snapshot.data()!['users'];
        final obj = users.firstWhere((o) => o['email'] == widget.receiverEmail,
            orElse: () => null);
        unread = obj['unread'];
      }
      updates['users'] = [
        {
          'email': widget.senderUser!.email,
          'name': widget.senderUser!.name,
          'unread': 0
        },
        {
          'email': widget.receiverEmail,
          'name': widget.receiverName,
          'unread': unread! + 1
        }
      ];

      FirebaseServices()
          .firestore!
          .collection('chatRooms')
          .doc(documentId)
          .set(updates, SetOptions(merge: true));

      //push notification
      FirebaseServices()
          .firestore!
          .collection('users')
          .doc(widget.receiverEmail)
          .get()
          .then((snapshot) {
        if (snapshot.exists) {
          /// Using user['chatWith'] does not fire notification for both MV and Manager
          /// And the "chatWith" element does not show up in the FireStore Database.
          // Map user = snapshot.data()!;
          // if (user['chatWith'] != widget.senderUser!.email) {
          if (widget.receiverEmail != widget.senderUser!.email) {
            Services().api.pushNotification(widget.senderUser!.cookie,
                receiverEmail: widget.receiverEmail,
                senderName: widget.senderUser!.email,
                message: message)!;
          }
        }
      }).catchError((e) {});
    }).catchError((e) {});
  }

  void updateTyping(bool status) {
    var document =
    FirebaseServices().firestore?.collection('chatRooms').doc(imageUrl);
    document?.update({'userTyping': status});
  }

  @override
  Widget build(BuildContext context) {
    if (documentId == null) {
      return Scaffold(
        body: Container(),
      );
    }

    return Scaffold(
      backgroundColor: Theme.of(context).backgroundColor,
      appBar: AppBar(
        systemOverlayStyle: SystemUiOverlayStyle.light,
        leading: IconButton(
          icon: const Icon(
            Icons.arrow_back_ios,
            color: Colors.white,
            size: 22,
          ),
          onPressed: () {
            if (Navigator.canPop(context)) {
              //update chatwith
              FirebaseServices()
                  .firestore!
                  .collection('users')
                  .doc(widget.senderUser!.email)
                  .set({'chatWith': null}, SetOptions(merge: true));
              Navigator.of(context).pop();
            } else {
              Navigator.pushNamed(context, '/home');
            }
          },
        ),
        title: Text(
          widget.receiverName.toString(),
          style: const TextStyle(color: Colors.white),
        ),
      ),
      body: SafeArea(
        child: Scrollbar(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            crossAxisAlignment: CrossAxisAlignment.stretch,

            children: <Widget>[
              MessagesStream(
                documentId: documentId,
                senderEmail: widget.senderUser!.email,
              ),
              TypingStream(
                isAdminLoggedIn: false,
                userEmail: widget.receiverEmail,
              ),
              Container(
                decoration: const BoxDecoration(
                  border: Border(
                    top: BorderSide(color: kTeal400, width: 2.0),
                  ),
                ),
                child: Row(
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: <Widget>[
                    Expanded(
                      child: TextField(
                        controller: messageTextController,
                        onChanged: (value) {
                          messagesText = value;

                          updateTyping(true);
                        },
                        onEditingComplete: () {
                          updateTyping(false);
                        },
                        decoration: InputDecoration(
                          contentPadding: const EdgeInsets.symmetric(
                              vertical: 10.0, horizontal: 20.0),
                          hintText: S.of(context).typeYourMessage,
                          border: InputBorder.none,
                          suffixIcon: IconButton(
                            onPressed: getImage,
                            icon: const Icon(Icons.attach_file),
                          ),
                        ),
                      ),
                    ),
                    IconButton(
                      onPressed: () {
                        messageTextController.clear();
                        if (messagesText.isNotEmpty) {
                          sendMessage(text: messagesText);
                        }
                        messagesText = '';
                      },
                      icon: const Icon(Icons.send),
                    ),

                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );

  }

}

class ShowImage extends StatelessWidget {
  final String imageUrl;

  const ShowImage({required this.imageUrl, Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final size = MediaQuery.of(context).size;

    return Scaffold(
      body: Container(
        height: size.height,
        width: size.width,
        color: Colors.black,
        child: Image.network(imageUrl),
      ),
    );
  }
}

**and this code of messages.dart**

`import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:intl/intl.dart';
import 'package:quiver/strings.dart';

import '../../../common/tools.dart';
import '../../../widgets/common/firestore_animated_list.dart';
import '../firebase_service.dart';

class MessagesStream extends StatefulWidget {
  final String? documentId;
  final String? senderEmail;

  const MessagesStream({this.documentId, this.senderEmail});

  @override
  _MessagesStreamState createState() => _MessagesStreamState();
}

class _MessagesStreamState extends State<MessagesStream>
    with SingleTickerProviderStateMixin {
  ScrollController? _scrollController;
  bool isAtTopOfChatList = true;

  @override
  void initState() {
    _scrollController = ScrollController();
    _scrollController!.addListener(_scrollListener);
    super.initState();
  }

  void _scrollListener() {
    if (_scrollController!.offset !=
            _scrollController!.position.minScrollExtent &&
        !_scrollController!.position.outOfRange) {
      setState(() {
        isAtTopOfChatList = false;
      });
    } else {
      setState(() {
        isAtTopOfChatList = true;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    final reference = FirebaseServices()
        .firestore!
        .collection('chatRooms')
        .doc(widget.documentId)
        .collection('chatScreen')
        .orderBy('createdAt', descending: true);
    return Expanded(
      child: Column(
//        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: <Widget>[
          Flexible(
            child: FirestoreAnimatedList(
              controller: _scrollController,
              reverse: true,
              query: reference,
              itemBuilder: (context, snapshot, animation, index) {
                var data = snapshot;
                return FadeTransition(
                  opacity:
                      CurvedAnimation(parent: animation, curve: Curves.easeIn),
                  child: MessageBubble(
                      index: index,
                      document: snapshot,
                      isMe: widget.senderEmail == data['sender']),
                );
              },
              physics: const ScrollPhysics(),
              key: null,
            ),
          ),
        ],
      ),
    );
  }
}

class ScrollToTopBubble extends StatelessWidget {
  final DocumentSnapshot? document;

  const ScrollToTopBubble({this.document});

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: BoxDecoration(
          color: Theme.of(context).primaryColor,
          borderRadius: const BorderRadius.only(
            topLeft: Radius.circular(3.0),
            topRight: Radius.circular(10.0),
            bottomLeft: Radius.circular(10.0),
            bottomRight: Radius.circular(10.0),
          )),
      child: const Padding(
        padding: EdgeInsets.symmetric(vertical: 10.0, horizontal: 15.0),
        child: Text(
          'opps',
          style: TextStyle(
            color: Colors.white,
            fontSize: 15.0,
          ),
        ),
      ),
    );
  }
}

class MessageBubble extends StatelessWidget {
  final int? index;
  final DocumentSnapshot? document;
  final bool? isMe;

  const MessageBubble({this.index, this.document, this.isMe});

  @override
  Widget build(BuildContext context) {
    var data = document!.data() as Map<String, dynamic>;

    var date = DateTime.parse(data['createdAt']).toLocal();
    var isRecent = DateTime.now().difference(date).inHours < 24;
    var dateFormat = isRecent
        ? DateFormat('h:mm a').format(date)
        : DateFormat('h:mm a - d/M').format(date);

    return Padding(
      padding: const EdgeInsets.only(right: 10.0, left: 10.0),
      child: Row(
        children: isMe!
            ? displayMyMessage(context, dateFormat)
            : displaySenderMessage(context, dateFormat),
      ),
    );
  }

  List<Widget> displaySenderMessage(context, dateFormat) {
    var theme = Theme.of(context);
    var data = document!.data()! as Map<String, dynamic>;

    return <Widget>[
      const Padding(
        padding: EdgeInsets.only(right: 10),
        child: Icon(Icons.person),
        // child: ImageTools.getCachedAvatar(
        //     'https://api.hello-avatar.com/adorables/60/${document!.data()!['sender']}.png'),
      ),
      Expanded(
        flex: 7,
        child: Padding(
          padding: const EdgeInsets.only(bottom: 10.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              Text(
                dateFormat.toString(),
                style: theme.textTheme.headline6!.copyWith(
                    fontSize: 10,
                    color: theme.colorScheme.secondary.withOpacity(0.5)),
              ),
              const SizedBox(
                height: 5.0,
              ),
              isBlank(data['image'])
                  ? Container(
                      decoration: BoxDecoration(
                          color: Theme.of(context).primaryColor,
                          borderRadius: const BorderRadius.only(
                            topLeft: Radius.circular(3.0),
                            topRight: Radius.circular(10.0),
                            bottomLeft: Radius.circular(10.0),
                            bottomRight: Radius.circular(10.0),
                          )),
                      child: Padding(
                        padding: const EdgeInsets.symmetric(
                            vertical: 10.0, horizontal: 15.0),
                        child: Text(
                          '${data['text']}',
                          style: const TextStyle(
                            color: Colors.white,
                            fontSize: 15.0,
                          ),
                        ),
                      ),
                    )
                  : GestureDetector(
                      onTap: () {
                        Navigator.push(
                          context,
                          MaterialPageRoute(builder: (_) {
                            return DetailedImage(
                              imageUrl: data['image'],
                            );
                          }),
                        );
                      },
                      child: ImageTools.image(
                        url: data['image'],
                        width: 200,
                        height: 200,
                        fit: BoxFit.cover,
                      ),
                    )
            ],
          ),
        ),
      ),
      const Expanded(
        flex: 3,
        child: SizedBox(
          width: 0,
          height: 0,
        ),
      )
    ];
  }

  List<Widget> displayMyMessage(context, dateFormat) {
    var theme = Theme.of(context);
    var data = document!.data()! as Map<String, dynamic>;

    return <Widget>[
      const Expanded(
        flex: 3,
        child: SizedBox(
          width: 0,
          height: 0,
        ),
      ),
      Expanded(
        flex: 7,
        child: Padding(
          padding: const EdgeInsets.only(bottom: 10.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.end,
            children: <Widget>[
              //in user chat screen, do not display user email, only display admin email
              Padding(
                padding: const EdgeInsets.only(right: 4.0),
                child: Text(
                  dateFormat.toString(),
                  style: theme.textTheme.headline6!.copyWith(
                      fontSize: 10,
                      color: theme.colorScheme.secondary.withOpacity(0.5)),
                ),
              ),
              const SizedBox(
                height: 5.0,
              ),
              isBlank(data['image'])
                  ? Container(
                      decoration: BoxDecoration(
                          color: Theme.of(context).primaryColorLight,
                          borderRadius: const BorderRadius.only(
                            topLeft: Radius.circular(10.0),
                            topRight: Radius.circular(10.0),
                            bottomLeft: Radius.circular(10.0),
                            bottomRight: Radius.circular(3.0),
                          )),
                      child: Padding(
                        padding: const EdgeInsets.symmetric(
                            vertical: 10.0, horizontal: 15.0),
                        child: Text(
                          '${data['text']}',
                          style: TextStyle(
                            color: Theme.of(context).colorScheme.secondary,
                            fontSize: 15.0,
                          ),
                        ),
                      ),
                    )
                  : GestureDetector(
                      onTap: () {
                        Navigator.push(
                          context,
                          MaterialPageRoute(builder: (_) {
                            return DetailedImage(
                              imageUrl: data['image'],
                            );
                          }),
                        );
                      },
                      child: ImageTools.image(
                        url: data['image'],
                        width: 200,
                        height: 200,
                        fit: BoxFit.cover,
                      ),
                    )
//                  : ImageTools.image(
//                      url: document.data['image'],
//                      width: 200,
//                      height: 200,
//                      fit: BoxFit.cover)
            ],
          ),
        ),
      ),
    ];
  }
}

class DetailedImage extends StatelessWidget {
  final String? imageUrl;

  const DetailedImage({this.imageUrl});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        systemOverlayStyle: SystemUiOverlayStyle.light,
        backgroundColor: Colors.black,
        leading: IconButton(
          icon: const Icon(
            Icons.arrow_back_ios,
            color: Colors.white,
            size: 22,
          ),
          onPressed: () {
            Navigator.of(context).pop();
          },
        ),
      ),
      body: ImageTools.image(
        url: imageUrl,
        fit: BoxFit.fitWidth,
        height: double.infinity,
        width: double.infinity,
      ),
      backgroundColor: Colors.black,
    );
  }
}
`

**Comment by AzzamSuliiman** [comment]
anyone help me?

**Comment by stuartmorgan** [comment]
See https://flutter.dev/community#community-grid for resources where you can get help with your own code. The issue tracker is for bug reports in Flutter itself.

If you believe this is due to a bug in Flutter, rather than your code, please isolate it to the specific Flutter code and file a new issue with a reduced test case, explaining the bug (as in, what Flutter API is not behaving correctly, rather that what in your code isn't working the way you want it to.)
