### ISSUE TITLE
Flutter Web: ExpansionTile not expanding inside an iFrame on Android Chrome

### ISSUE THREAD

**Issue by shashwatadi** [flutter/flutter#94661]
You can check the iframe version of the app: https://coaching.hypertroph.com
Original version: https://live.kohbee.com/#hypertroph

On Android Chrome, in some devices like Oneplus 7, the Expansion Tile does not expand.

I have used the iframe like this:

```
 <script>
        document.addEventListener('touchstart', {});
    </script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <style>
        iframe {
            width: 100% !important;
            min-width: 100%;
            height: calc(100vh) !important;
            align-self: center;
            border: 0;
        }
    </style>
    <iframe id="myIframe" frameBorder="0" src="https://live.kohbee.com/#hypertroph"></iframe>
```

**Comment by darshankawar** [comment]
@shashwatadi 
Can you provide `flutter doctor -v`, a complete `index.html` alongwith expected vs actual behavior ?
Thanks.
