### ISSUE TITLE
Scrollbar can not update UI when changing controller.offset from outside?

### ISSUE THREAD

**Issue by imiskolee** [flutter/flutter#94663]
hi:

I tried using a scrollbar and update offset from programming, but the scrollbar can not update without setState.

```dart 

Scrollbar(
 controller: mycontroller,
 child: ...
)


 //Timer: each 1s
   mycontroller.jumpTo(x  + 10);
   x += 10;
```

**Comment by danagbemava-nc** [comment]
Hi @imiskolee, thanks for filing the issue, please provide a complete minimal reproducible code sample as well as the output of `flutter doctor -v`. 

Thank you
