### ISSUE TITLE
[Web] RefreshIndicator is not shown on web browser

### ISSUE THREAD

**Issue by cdprete** [flutter/flutter#94677]
Hi.
I'm starting playing around with Flutter and I was trying to add the RefreshIndicator to the skeleton app, but this doesn't render at all on web, no matter if I use the `AlwaysScrollableScrollPhysics` or the `BouncingScrollPhysics(parent: AlwaysScrollableScrollPhysics())`.

The flutter doctor is actually the same in #94675.
I've tried with Chrome and Edge and I've the same issue on both.

Any clue?

Cheers,
Cosimo

**Comment by darshankawar** [comment]
@cdprete 
Thanks for the report. Although I do see the same behavior by wrapping `ListView` with `RefreshIndicator` which shows the progress indicator on mobile but not on web, but I am not sure if that's intended. Does the refresh indicator show up on a non-flutter web app ?

**Comment by cdprete** [comment]
Hi.
That's a good question. I honestly don't know if plain frontends support
such behaviors (I'm not a frontender).

But, if the widget is not applicable in the web scenario, I would expect to
get an error (or at least a warning) out instead of having the widget be a
NOOP (but still consuming resources since it's in the tree?)

Il Lun 6 Dic 2021, 09:47 darshankawar ***@***.***> ha scritto:

**Comment by darshankawar** [comment]
@cdprete 
I believe you are hitting https://docs.flutter.dev/release/breaking-changes/default-scroll-behavior-drag
Please check the migration guide and use the updated code as mentioned https://docs.flutter.dev/release/breaking-changes/default-scroll-behavior-drag#migration-guide and see if it works.

**Comment by cdprete** [comment]
@darshankawar that did indeed the trick.
There is a caveat, though: now the list is always scrollable.

Having a look at `ListView`, it seems like it always creates an `AlwaysScrollableScrollPhysics` if certain "conditions" are met, which is the case if you - like me - follow the migration guide but don't add the `ScrollController` because nowhere it's there written it's really needed and why it's needed.

That said, the issue is indeed fixed and I would just improve the docs if I would be at your place (e.g.: add the links to the migration in the docs of the scrollable default widgets and explain why `ScrollController` is _always_ needed).

**Comment by darshankawar** [comment]
@cdprete 
Thanks for the update. Since your original issue has been resolved, I'll close this one.
Regarding your other behavior you discovered, please file a new issue and we'll address it.
