### ISSUE TITLE
New Cupertino Widget: iOS15 settings list

### ISSUE THREAD

**Issue by tomasbaran** [flutter/flutter#94674]
It would be cool to have a widget for the settings in our flutter apps that would match the native iPhone Settings. I'm talking about the one that got changed from iOS14 -> iOS15:
![ios settings](https://user-images.githubusercontent.com/25743901/144721606-1f7317f7-1ad7-4e87-9e10-9b7365cb7ebe.png)

I'm not sure how many people would find it useful. Let's see.

**Comment by darshankawar** [comment]
@tomasbaran 
From above screenshots, I understand that `Do not disturb` is changed to `Focus`. Is that what you are looking to change / introduce a widget for ?

**Comment by tomasbaran** [comment]
I didn't even notice that :) haha. No, that's not what I mean. I mean the list of item that are grouped in a column. In iOS 14 they were from the edge to the edge in iOS 15 they have a padding and are grouped in a rounded rectangle. The potential widget I'm talking about is the grouped column of settings items (or let's say settings list)

**Comment by maurice0800** [comment]
@tomasbaran 
I have created a pub which you might find useful: 
https://pub.dev/packages/ce_settings

**Comment by darshankawar** [comment]
@tomasbaran 
Please try per above comment and see if it helps to achieve your use case.
