### ISSUE TITLE
Pigeon: using `Map` or `dynamic` throws `Generic type arguments must be nullable in field "data"` error

### ISSUE THREAD

**Issue by ben-xD** [flutter/flutter#94689]
As per the Pigeon [docs](https://pub.dev/packages/pigeon#feedback), I am tagging @gaaclarke to get help on this. Thanks in advance.

## Attempt 1
I've tried to define a class using:
```dart
class RemoteMessage {
  Notification? notification;
  Map<String, dynamic>? data;
}
```

Unfortunately, I get an error message:
```bash
Error: pigeons/push.dart:6: Generic type arguments must be nullable in field "data" in class "RemoteMessage".
Error: pigeons/push.dart:6: Generic type arguments must be nullable in field "data" in class "RemoteMessage".
```

## Attempt 2
I also tried making `dynamic` optional as well:
```dart
class RemoteMessage {
  Notification? notification;
  Map<String, dynamic?>? data;
}
```

In that case, I get only 1 instance of the error:
```bash
Error: pigeons/push.dart:6: Generic type arguments must be nullable in field "data" in class "RemoteMessage".
```
## Attempt 3
If I make the **key** type optional, i.e. `Map<String?, dynamic>? data;`, I get the error:
```
Unhandled exception:
FileSystemException: Cannot open file, path = './android/app/src/main/java/dev/flutter/pigeon/Pigeon.java' (OS Error: No such file or directory, errno = 2)
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356:9)
<asynchronous suspension>
pub finished with exit code 255
```

## Summary

It looks like Pigeon doesn't support `Map` or `dynamic`, although it should already support generics: https://github.com/flutter/flutter/issues/63468.

**Comment by darshankawar** [comment]
@ben-xD 
Can you provide `flutter doctor -v` ?
The package's readMe says below:

<img width="772" alt="Screenshot 2021-12-06 at 2 27 54 PM" src="https://user-images.githubusercontent.com/67046386/144816949-c474f84f-ba15-4c4d-8d64-7cdf119ba7e3.png">

See if above points helps

**Comment by ben-xD** [comment]
Hey @darshankawar

I re-read those points and they do **not** assist me 😊

Here is my `flutter doctor`:
```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.5.3 at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (7 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/zen/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Users/zen/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7784292/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/zen/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7784292/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/zen/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7784292/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • iPhone SE BB🔫 (mobile) • 00008030-00044D301AD3402E • ios            • iOS 15.1 19B74
    • Chrome (web)            • chrome                    • web-javascript • Google Chrome 96.0.4664.55

• No issues found!
```

**Comment by darshankawar** [comment]
Thanks for the update.

**Comment by stuartmorgan** [comment]
I'm confused about what exactly this issue is intended to be about. What you have labelled attempts 1 and 2 are, as noted above, documented limitations in Pigeon at the moment.

As for attempt 3:

> If I make the **key** type optional, i.e. `Map<String?, dynamic>? data;`, I get the error:
> 
> ```
> Unhandled exception:
> FileSystemException: Cannot open file, path = './android/app/src/main/java/dev/flutter/pigeon/Pigeon.java' (OS Error: No such file or directory, errno = 2)
> #0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356:9)
> <asynchronous suspension>
> pub finished with exit code 255
> ```

This doesn't seem to have anything to do with `Map`, so I'm not sure how you concluded from this that `Map` isn't supported. Are you saying that you only get missing directory errors for the output file if you use `Map`? That seems very unlikely.

@darshankawar 

> I see the same behavior on latest stable and master.

Which of the behaviors did you verify?

**Comment by ben-xD** [comment]
> are, as noted above, documented limitations in Pigeon at the moment.

Oh, I guess you're saying the **key** type of a Map **should** be optional too. That's confusing to me, what does a `null` key in a map actually mean? 

## Attempt 4:

After fixing the `flutter pub run pigeon` command, the Attempt 3 error is avoided, but a new error is generated. The current Pigeon now looks like:
```dart
class RemoteMessage {
  Notification? notification;
  Map<String?, dynamic>? data; // <-- This is line 5, referred to in the error
}
```

Giving an **error**:
```
Error: pigeons/push.dart:5: Generic type arguments must be nullable in field "data" in class "RemoteMessage".
```

## What worked:
By adding `?` to dynamic, it worked. 
```
class RemoteMessage {
  Notification? notification;
  Map<String?, dynamic?>? data;
}
```

Thanks for your scrutiny @stuartmorgan, it looks like the code generation is working now. I'll now test it at runtime.

**Comment by ben-xD** [comment]
I've closed this issue but created a new one because the generated code when using a `Map<String?, dynamic?>` is erroneous.

**Comment by darshankawar** [comment]
> Which of the behaviors did you verify?

@stuartmorgan I tried the Attempt1 and 2 which had resulted in same error messages as OP and hence labeled.
