### ISSUE TITLE
[Web] DropDown Button/Menu Needs to Be Updated to work on the web, ButtonStyle

### ISSUE THREAD

**Issue by kornha** [flutter/flutter#94693]
Doing an anchored dropdown in Flutter Web is currently impossible (for production-level code) with the DropdownButton. 

1. It does not appropriately move with a **resized screen** on flutter web
2. The button does not expose a toggle feature
3. Unlike the TextButton, the DropDown button does not take in a ButtonStyle (and hence cannot be styled as the TextButton)

Therefore, a simple dropdown menu that is so frequent on the web is not doable in flutter at the moment. I think it would be a huge value add to make this work appropriately!

If I am mistaken, please point me to a better resource :)

**Comment by maheshmnj** [comment]
Hi @kornha, Thanks for filing the issue. 

> Doing an anchored dropdown in Flutter Web is currently impossible  

Can you please explain what exactly do you mean by `anchored dropdown` with the help of an image or a link to resource?
