### ISSUE TITLE
flutter clean command take very long to finish

### ISSUE THREAD

**Issue by jims57** [flutter/flutter#94708]
Why does `flutter clean` command take a very long time to finish on the **Terminal** of **Android Studio**?

If I am right, the previous version of **Flutter** has no such problem, I found that latest version(**V2.5.3**) often has this problem of taking a very long time to finish.

Is there any good solution or suggestion to improve the command? 

By the way, I am in China, is it possibly caused by the **China Great Firewall** which may lead to the slow connection to foreign sites?

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on Mac OS X 10.15.7 19H1419 darwin-x64, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.62.2)
[✓] Connected device (3 available)

```

**Comment by maheshmnj** [comment]
Hi @jims57, Thanks for filing the issue. Please share the console output of `flutter clean` and is it longer for a specific project or all projects? 

Thanks

**Comment by jims57** [comment]
![image](https://user-images.githubusercontent.com/1920873/144959506-97d062d7-b06f-4e48-9021-f644189176fd.png)
![image](https://user-images.githubusercontent.com/1920873/144959982-361f2bc3-80cc-4d90-9fc5-7b167f896c79.png)

**Comment by jims57** [comment]
![image](https://user-images.githubusercontent.com/1920873/144961779-11483de3-b901-4898-83a2-f5ae769ea019.png)

**Comment by maheshmnj** [comment]
@jims57 Well then it looks like flutter build is taking longer and not flutter clean is that correct?
if so Does the build take longer for ios or android or both?
 please share the complete output of `flutter run -v` in a text file.

Thank you.

**Comment by jims57** [comment]
@maheshmnj I upgraded MacOS to **Monterey** and ugraded **Xcode** to the latest **version 13.1**. 
After this, it seem work faster, I will take a fews day to see if this problem has been fixed. Thanks anyway.

**Comment by maheshmnj** [comment]
Sure, Thanks for the update.

**Comment by jims57** [comment]
@maheshmnj
