### ISSUE TITLE
Issue from website page 从互联网上获取数据

### ISSUE THREAD

**Issue by zhlgit** [flutter/flutter#94709]
From URL: https://www.flutterchina.club/cookbook/networking/fetch-data.md

使用iOS真机运行：
出现异常
SocketException (SocketException: Failed host lookup: 'jsonplaceholder.typicode.com' (OS Error: nodename nor servname provided, or not known, errno = 8))

主要代码：

Future<Post> fetchPost() async {
  var url = Uri.parse('https://jsonplaceholder.typicode.com/posts/1');
  final response = await http.get(url);
  final responseJson = json.decode(response.body);

  return Post.fromJson(responseJson);
}

class Post {
  final int userId;
  final int id;
  final String title;
  final String body;

  Post(
      {required this.userId,
      required this.id,
      required this.title,
      required this.body});

  factory Post.fromJson(Map<String, dynamic> json) {
    return Post(
      userId: json['userId'],
      id: json['id'],
      title: json['title'],
      body: json['body'],
    );
  }
}

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Fetch Data Example',
        theme: ThemeData(
          primarySwatch: Colors.blue,
        ),
        home: Scaffold(
          appBar: AppBar(
            title: const Text('Fetch Data Example'),
          ),
          body: Center(
            child: FutureBuilder<Post>(
              future: fetchPost(),
              builder: (context, snapshot) {
                if (snapshot.hasData) {
                  return Text(snapshot.data!.title);
                } else if (snapshot.hasError) {
                  return Text('${snapshot.error}');
                }

                return const CircularProgressIndicator();
              },
            ),
          ),
        ));
  }
}

开发工具：vccode 1.62.3
flutter 版本：flutter 2.5.3

**Comment by danagbemava-nc** [comment]
The flutterchina website is community maintained. 

Kindly file this issue here https://github.com/flutterchina/website/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc.

Closing as this is not an issue with flutter itself.
