### ISSUE TITLE
Flutter engine host_debug_unopt's shell_unittest.exe crashes on Windows

### ISSUE THREAD

**Issue by eggfly** [flutter/flutter#94707]
The `shell_unittest.exe` crashes on windows, Is it expected? 

<img width="976" alt="shell_unittest2exe" src="https://user-images.githubusercontent.com/922837/144796250-f1b7cc30-e32a-4ca3-96e8-5c86d8db7675.png">

<img width="958" alt="shell_unittest_windows" src="https://user-images.githubusercontent.com/922837/144796266-3a871a0b-26f1-4a36-8139-11029d8a8ecb.png">

My engine is on main branch and I build it with VS2019 Community version, with `tools\gn --no-goma --no-lto --unopt --no-prebuilt-dart-sdk`

The engine version(src\flutter's git revision) is: ffa298925553150ece8ad6b08090b0fa31d023a6
```
C:\Users\eggfly\flutter_engine\src\flutter>git log
commit ffa298925553150ece8ad6b08090b0fa31d023a6 (HEAD, origin/master, origin/main, origin/HEAD, main)
Author: skia-flutter-autoroll <skia-flutter-autoroll@skia.org>
Date:   Sun Dec 5 17:14:01 2021 -0500

    Roll Fuchsia Mac SDK from WohiTvz8h... to KQ60Vu3d7... (#30148)
```

**Comment by dnfield** [comment]
I think @bdero has been working on Windows tests related to this recently, he may know.

**Comment by chinmaygarde** [comment]
I thought I saw this static initialization bug on Windows in SwiftShader. @bdero just updated SwiftShader recently and the behavior may have changed.

**Comment by bdero** [comment]
I just successfully reproduced this on the commit mentioned in the OP as well as on ed6652f79e7cb3822c9952628d489ee439fb419f (commit just before I changed the [Windows Clang SDK](https://github.com/flutter/engine/pull/29736) switch, and confirmed swiftshader is pinned and building on its commit prior to updating: 5d1e85404), so it seems something else changed on my system that's preventing me from running the shell or embedder unittests against any commit.

Either way, this'll eventually block me as well so I'm trying to work it out at the moment.

**Comment by bdero** [comment]
I was able to work around this by cherry-picking [dc0f1319307](https://swiftshader-review.googlesource.com/c/SwiftShader/+/37608) in third_party/swiftshader. The `require_constant_initialization` clang attribute getting prepended seems to be what's fixing it. I'm still not sure what changed to introduce this issue for me, but I can migrate swiftshader forward past this commit as a permafix (albeit a bit tedious).
