### ISSUE TITLE
Potentially get wrong context when use platfromview

### ISSUE THREAD

**Issue by voicewitness** [flutter/flutter#94715]
We got a wrong EAGLContext When we use platform view in our app, when I look into this bad case, the obvious reason is that we did not set back the EAGLContext after the gl operations finished, but this obviously mistaken code works fine without using platform view, so I look into the engine code, then I got this potentially issue.
https://github.com/flutter/engine/blob/66a281107bcfd0283f469694980924e8f32b7a32/shell/platform/darwin/ios/ios_external_texture_gl.mm#L32
IOSExternalTextureGL will draw into the "currentContext" when it creates texture cache. In most cases, the currentContext works fine, but it will be affected when threads merged by using platform view, just like the bad case i got who followed the rule "Use the context after set it to your own".
To keep context affecting away, I wrote a pr just like the logic in Metal that uses the context received in constructor.

**Comment by voicewitness** [comment]
> @voicewitness Thanks for the report. Would be good to get your `flutter doctor -v` and possibly a minimal reproducible code sample that shows this behavior.

flutter doctor -v
[✓] Flutter (Channel stable/v1.22.6.xianyu, 1.22.6-xianyu, on macOS 12.0.1 21A559 darwin-x64, locale zh-Hans-CN)
    • Flutter version 1.22.6-xianyu at /Users/wuhang/Work/aliflutter
    • Framework revision 3c11cd0b72 (7 周前), 2021-10-19 11:48:38 +0800
    • Engine revision cfe09d4158
    • Dart version 2.10.5
The code and the logic remain the same in "ios_external_texture_gl.mm#L32" at the latest branch.
The "wrong context" scene occurred in a huge complex project, so the code sample. It takes a lot to make all conditions ready.

**Comment by darshankawar** [comment]
@voicewitness 
You are on very old version of flutter. Please upgrade to latest stable (2.5.3) and see if you still get same behavior or not.

**Comment by voicewitness** [comment]
> @voicewitness You are on very old version of flutter. Please upgrade to latest stable (2.5.3) and see if you still get same behavior or not.

Since the mechanism for thread-merging with platform-view and always using currentContext for external texture, it will create the same issue with given conditions. The cost between making our project upgrade to latest stable and creating sample is quite the same.

**Comment by voicewitness** [comment]
The issue exists in master, and I figure out how to fix it. Would you prefer review the pr.

**Comment by darshankawar** [comment]
@voicewitness 
Is there a way to get a reproducible code sample that highlights the issue ?

**Comment by chinmaygarde** [comment]
This can only be reproduced on iOS 8 and 9 since newer versions will use Metal.

**Comment by ColdPaleLight** [comment]
This problem needs to meet the following conditions: 
1. Platform view is used, so that thread merging occurs. 
2. The developer used an EAGLContext unrelated to flutter on the platform thread and forgot to restore it. 
3. Flutter's rendering backend is OpenGLES instead of Metal.

So it is very difficult to provide a reproducible code sample. But I am very confident that the associated PR can fix this issue :) .
