### ISSUE TITLE
Incorrect parsing of file content in latin1 encoding

### ISSUE THREAD

**Issue by stanojevicboban** [flutter/flutter#94716]
It seems that if I try to read an image file in order to retrieve magic numbers from it so I could better detect the mime type of the file, iOS doesn't appear to be friendly about it.

I am using the following code to extract the first 20 hex codes from the file:

```
List<int> fileBytes = File(path).readAsBytesSync().toList();
List<int> header = [];
int i = 0;
String output = '';
fileBytes.forEach((element){
  if(element == 0) return;
  if (i > 20) return;
  output += element.toRadixString(16) + " ";
  header.add(element);
  i++;
});
```

In addition to that, I am also trying to read the file content into a string, with the code below:

```
String output = File(path).readAsStringSync(encoding: latin1);
```

In order to replicate the issue, I am using [this image](https://www.maketecheasier.com/assets/uploads/2017/09/webp-logo.jpg.webp) as an example.

On Android the `header` variable gives me the following hex:
```
52 49 46 46 b0 5b 57 45 42 50 56 50 38 20 a4 5b 10 c6 1 9d 1
```

Looking at the [list of magic numbers](https://en.wikipedia.org/wiki/List_of_file_signatures) this hex codes is for the WebP image file, which is correct.

Even the file content (the `content` variable) starts with:
<img width="997" alt="android" src="https://user-images.githubusercontent.com/3943008/144821581-eb162701-0616-438c-8479-6e06bcaca94c.png">

However, running the same code on iOS, produces this for hex:
```
89 50 4e 47 d a 1a a d 49 48 44 52 2 bc 1 90 8 6 4c 3c
```

This corresponds to the PNG image format, which is wrong. Even the file content is incorrect, as it start as the code below:
<img width="997" alt="ios" src="https://user-images.githubusercontent.com/3943008/144821835-e9d85eaa-f108-4a5d-ab8b-f25f52caac2e.png">

I can say for certain that the problem is not with the iOS emulator as the same issue appears on a physical device. It is also appearing on iOS 14+ version (as I know iOS just recently introduced WebP support). Regardless, I don't believe the issue is with the image format support.

I am having a hard time understanding why the same file is being read so differently on iOS. On android, it is read exactly as it's expected, while on iOS it's like the OS is converting the file to a format it understand and gives that to the flutter app to use.

So, if there's anyone who can give me a better explanation on why this happens, I would be extrenely grateful.

**Comment by darshankawar** [comment]
@stanojevicboban 
Thanks for the report. Can you provide us `flutter doctor -v` and [complete minimal code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can use to verify this behavior ?

**Comment by stanojevicboban** [comment]
@darshankawar Here's the output of the `flutter doctor -v`:

```
flutter doctor -v
[✓] Flutter (Channel unknown, 1.24.0-10.2.pre, on macOS 11.6.1 20G224 darwin-x64, locale en-GB)
    • Flutter version 1.24.0-10.2.pre at /Users/lcf/flutter
    • Framework revision 022b333a08 (1 year, 1 month ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/lcf/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = /Users/lcf/Library/Android/sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_265-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[!] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Connected device (1 available)
    • iPhone 8 (mobile) • 5FA034BF-AEAE-43DF-8264-4A118731BEBD • ios • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)

! Doctor found issues in 1 category.
```

As for the code sample, I believe you can use the image from the link I've posted in the original comment and use the following to get the hex and text content of the file on two platforms:

```
List<int> fileBytes = File('path-to-file').readAsBytesSync().toList();
List<int> header = [];
int i = 0;
String output = '';
fileBytes.forEach((element){
  if(element == 0) return;
  if (i > 20) return;
  output += element.toRadixString(16) + " ";
  header.add(element);
  i++;
});

String output2 = File('path-to-file').readAsStringSync(encoding: latin1);

print('hex: ' + output);
print('text: ' + output2);
```

**Comment by stuartmorgan** [comment]
> List<int> fileBytes = File('path-to-file').readAsBytesSync().toList();

How exactly are you getting the file onto the device? This sounds like a build-time conversion, which makes the bundling of the image, not the reading, the important part of the reproduction steps.

**Comment by stanojevicboban** [comment]
@stuartmorgan I have a very big app that this issue is occurring, so I always forget to mention some details.

Unfortunately, the files are not bundled during build time, but rather I am using `file_picker` package to load a file that user has selected from their gallery, so the file is loaded during runtime instead.

**Comment by stuartmorgan** [comment]
You'll need to file an issue against that package then, as that's the step where file conversion would be happening.
