### ISSUE TITLE
when I used colour widget inside container while boxdecoration widget have colour ,give me exception 

### ISSUE THREAD

**Issue by idexxpro** [flutter/flutter#94712]
when I used colour widget inside container while boxdecoration widget have colour ,give me exception .
I suggest remove colour parameter from boxdecoration widget , I would be glad when it unduplicated the same parameter in container and boxdecoration .

**Comment by darshankawar** [comment]
@idexxpro 
Can you provide `flutter doctor -v` and a complete minimal reproducible code sample along with the exception that we can use to verify the behavior ? Please don't just describe the issue, also provide the code sample.
Thanks.
