### ISSUE TITLE
`flutter build ipa` breaks Xcode>Archive 

### ISSUE THREAD

**Issue by adamsmaka** [flutter/flutter#94720]
On Flutter 2.5.3 if you create a new project, you can use Xcode to Archive the app.

If you try `flutter build ipa` not only does it end with `Command PhaseScriptExecution failed with a nonzero exit code` but also Xcode Archive doesn't work anymore.

Reproducible on every new project.

Only `flutter clean` can fix the problem.

**Comment by darshankawar** [comment]
@adamsmaka 
Can you provide us `flutter build ipa --verbose` log ? The log will be huge so you can put that in a text file and share it here.
