### ISSUE TITLE
multicast_dns does not work on Android 11

### ISSUE THREAD

**Issue by kostadin24** [flutter/flutter#94725]
Using multicast_dns 0.3.1
It works OK on older Androids, but on Android 11 nothing is discovered.
Trying with example provided for mDNS discovery. Here is log:

```console
Launching lib\main.dart on Pixel 5 in debug mode...
Running Gradle task 'assembleDebug'...
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...
W/FlutterActivityAndFragmentDelegate( 4526): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
Debug service listening on ws://127.0.0.1:57954/KplXSL0l9DU=/ws
Syncing files to device Pixel 5...
E/Dart    ( 4526): Dart Socket ERROR: ../../third_party/dart/runtime/bin/socket_android.cc:147: `reusePort` not supported for Android.
I/chatty  ( 4526): uid=10279(com.example.hyphen) 1.ui identical 1 line
E/Dart    ( 4526): Dart Socket ERROR: ../../third_party/dart/runtime/bin/socket_android.cc:147: `reusePort` not supported for Android.
I/flutter ( 4526): Done.
```

**Comment by danagbemava-nc** [comment]
Hi @kostadin24, thanks for filing the issue.  

Please provide the output of `flutter doctor -v` and a complete minimal reproducible code sample. 

Also take a look at https://github.com/flutter/flutter/issues/27346 and [this comment](https://github.com/flutter/flutter/issues/27346#issuecomment-594021847) as well to see if it solves your issue. 

Thank you

**Comment by kostadin24** [comment]
Here is my Flutter info:
C:\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.18363.1854], locale bg-BG)
    • Flutter version 2.5.3 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (8 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\admin\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Connected device (2 available)
    • Pixel 5 (mobile) • 0B031FDD4001ZT • android-arm64  • Android 11 (API 30)
    • Chrome (web)     • chrome         • web-javascript • Google Chrome 95.0.4638.69

• No issues found!
Process finished with exit code 0

**Comment by kostadin24** [comment]
What info is missing?

**Comment by danagbemava-nc** [comment]
> Not sure about all Android versions. Have to test them one by one.

Have you been able to investigate this?

**Comment by kostadin24** [comment]
Tested on Android 9,10,11. In all cases seems to work OK.
Only speed of discovery is different. On Androids before 10 - constructor with factory works fine and fast.
On 10 and 11 Androids - empty constructor works faster.
