### ISSUE TITLE
TextField + inputFormatters + RegExp does not work correctly?

### ISSUE THREAD

**Issue by tremp-m** [flutter/flutter#94721]
hi
I want to constraint value length in TextField.
I wrote such code: `TextField(
              autofocus: true,
              keyboardType: TextInputType.number,
              inputFormatters: <TextInputFormatter>[
                FilteringTextInputFormatter.allow(RegExp(
                    r'^\d{0,4}'))
              ],
            ),`

result on gif
![reg_exp](https://user-images.githubusercontent.com/48671789/144843215-3c82a8cb-7eda-4a1a-9966-4143e51f5a82.gif)
what i did wrong? Why it's possible enter more then 4 digits?

**Comment by danagbemava-nc** [comment]
Hi @tremp-m, it isn't necessary for you to use a regex if you want to limit the number of characters in a `TextField`. 

The `TextField` has a maxLength property that you can use to set a maximum length for a `TextField`, documented https://api.flutter.dev/flutter/material/TextField/maxLength.html

In case you want to use an `InputFormatter` to limit the text, you can do so with a `LengthLimitingTextInputFormatter`  documented https://api.flutter.dev/flutter/services/LengthLimitingTextInputFormatter-class.html

**Comment by tremp-m** [comment]
thx for your reply. There is simplified example. Actualy i want use such regExp - 'r'^(\d{0,4})(\.\d{0,3}|)''

**Comment by danagbemava-nc** [comment]
Is there any reason in particular you insist on using a regex for this?

**Comment by tremp-m** [comment]
How i can do that without it? (using 'onChanged'?) I think it simplest way to do that...

**Comment by LongCatIsLooong** [comment]
`FilteringTextInputFormatter.allow` is typically used to filter user input using an allow list of characters/patterns. If you really want to use `FilteringTextInputFormatter.allow` for what you're doing try adding `$` to your regular expression.

**Comment by tremp-m** [comment]
hi. i think we don't understand each other. i want have such pattern for text input (numeric format):  xxxx.xxx - good, xxx - good, xxxx.x - good, x.x - good, xxxxx - bad, x.xxxx bad (max 4 digits before separator and max 3 after). How i can do this with "max length text formatter"? 
now i try RegExp(r'^(\d{0,4})(\.\d{0,3})*$') in FilteringTextInputFormatter.allow - result on GIF
![regexp_v2](https://user-images.githubusercontent.com/48671789/145024542-b5451699-6037-4bcf-9944-796294ce4701.gif)

**Comment by danagbemava-nc** [comment]
It looks like what you wanted to do was create an input mask, in which case I believe you can create your own custom `TextInputFormatter` and let it work according to how you want it. 

Alternatively, you can checkout this community package to see if that also suits your use case.

**Comment by tremp-m** [comment]
As i understood - main purpose of FilteringTextInputFormatter - constraint symbols, but not complex structures of symbols...?

**Comment by danagbemava-nc** [comment]
According to the [FilteringTextInputFormatter](https://api.flutter.dev/flutter/services/FilteringTextInputFormatter-class.html) docs

> Since this formatter only removes characters from the text, it attempts to preserve the existing TextEditingValue.selection to values it would now fall at with the removed characters

it may not be suited for the creation of an input mask. 

Perhaps @LongCatIsLooong can shed more light on this
