### ISSUE TITLE
Slow Engine builds. Goma issue?

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#94738]
Engine builds for this PR https://github.com/flutter/engine/pull/30160

and on prod for some builds of https://github.com/flutter/engine/commit/91f8db415af80bf42fe9b0e09359464ba84c3fb6

e.g. https://ci.chromium.org/p/flutter/builders/prod/Linux%20Android%20Debug%20Engine

Have been very slow. I'm guessing there is an issue with goma on the bots.

**Comment by keyonghan** [comment]
Yeah, Goma is not working correctly:
```
compiler_proxy: fail=0
 compiler_info: count=43 used=0 stores=0 store_dups=0 miss=0 fail=0
 goma: finished=0 cache_hit=0 local_cachehit=0 aborted=0 retry=0 fail=0
```

Checking to see if any regressions.

**Comment by keyonghan** [comment]
Seems only `Linux Android Debug Engine` hit the goma issue. Will wait to see if this is a transient issue.

**Comment by keyonghan** [comment]
But I do see a new version pushed this morning: https://chrome-infra-packages.appspot.com/p/fuchsia/third_party/goma/client/mac-amd64/+/

Filed fxbug.dev/89891 to track.

**Comment by keyonghan** [comment]
From Goma team: 

> It looks like a server side issue. Apparently the load balancer is firing HTTP 502 errors to clients consistently and that causes the Goma client to stop connecting to the Goma backend.

**Comment by keyonghan** [comment]
Goma is back working: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Android%20Debug%20Engine/13025/overview

Will monitor for a while before close.

**Comment by zanderso** [comment]
The Windows Engine prod builds are still taking a long time.

**Comment by chinmaygarde** [comment]
Windows builds still seem to be taking an inordinate amount of time ([1.5 hours and counting on this presubmit](https://github.com/flutter/engine/pull/30165/checks?check_run_id=4436244660)).

**Comment by keyonghan** [comment]
This is actively being investigated in fxbug.dev/89890:

The configuration for windows got GCed, and caused builder slow.
Goma team is working to regenerate those files.

**Comment by chinmaygarde** [comment]
Thanks for the update. I am curious, what is the timeout on these bots? The presubmits I linked earlier are going on for ~2h:35m right now. I thought the timeout was much lower but I am not complaining :)

**Comment by keyonghan** [comment]
It was set to 3 hours to handle goma misses: https://flutter.googlesource.com/infra/+/refs/heads/main/config/lib/ci_yaml/ci_yaml.star#306

But it seems set for release branches. @godofredoc is it ready to bring it back to the default ([one hour](https://github.com/flutter/engine/blob/main/.ci.yaml#L356))?

**Comment by chinmaygarde** [comment]
Bumping up the priority as the 3hr timeout is being tripped on presubmits. Effectively blocking any commits to `main`.

**Comment by keyonghan** [comment]
Bumping the goma bug ([fxbug.dev/89890](fxbug.dev/89890)) to p0 as well and will update here if any progress.

**Comment by keyonghan** [comment]
The windows image was broken and a new image is [being rolled](https://chrome-internal-review.googlesource.com/c/infradata/config/+/4312050). After that the configs should be unblocked.

**Comment by keyonghan** [comment]
[New configs](https://ci.chromium.org/ui/p/fuchsia/builders/prod/goma-windows-images/b8828482051843578817/overview ) have been generated, and should be propagated in the next a few hours.

**Comment by keyonghan** [comment]
New changes are picked up, and windows builders are running through: https://ci.chromium.org/p/flutter/builders/try/Windows%20UWP%20Engine.

Will keep monitoring for a while before close.

**Comment by keyonghan** [comment]
Closing as the issue has been addressed.
