### ISSUE TITLE
What if we want to get the Markdown content from an Url instead of Assets/hello.md. How do we do it??

### ISSUE THREAD

**Issue by dimstr** [flutter/flutter#94737]
Using a package flutter_markdown 0.6.8

**Comment by dimstr** [comment]
Using a package flutter_markdown 0.6.8

**Comment by stuartmorgan** [comment]
Please use one of the resources listed at https://flutter.dev/community#community-grid for help with your own projects; the issue tracker is for bug reports in Flutter itself.
