### ISSUE TITLE
ubuntu vscode flutter pub get  need to reload window to show suggetion

### ISSUE THREAD

**Issue by b14cknc0d3** [flutter/flutter#94736]
### Steps to Reproduce

1.after install package from `flutter pub add <plugin> and flutter pub get` or via vscode plugin
2. suggestion not coming for the installed plugin(**I'm 100% sure that plugin is downloaded) and showing package URL not found but if u run the code with terminal (flutter run ) there is no error. To show the suggestion need to reload the window
**(CRLT+SHIT+P) > reload widow
3. Every time i want to install the plugin i need to stop debugging and reload the window
### OS type - 
`
Linux username 5.11.0-41-generic #45~20.04.1-Ubuntu SMP Wed Nov 10 10:20:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
`
###VS_CODE_VERSION `1.62.3
ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
x64`
###  flutter doctor
`
[✓] Flutter (Channel stable, 2.5.3, on Ubuntu 20.04.3 LTS
    5.11.0-41-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices
    (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Community Edition (version 2021.2)
[✓] VS Code (version 1.62.3)
[✓] Connected device (3 available)
`

**Comment by darshankawar** [comment]
@b14cknc0d3 
Which plugin are you trying to add ?
Are you saying that after running `flutter pub add <plugin>` through terminal, you see the suggestions from the plugin properly, but not the same using vscode ?

**Comment by b14cknc0d3** [comment]
adding from any plugin through terminal or adding using vs_code extension it will not show suggestion from that plugin and vs code and after import showing error  Target URI doesn't exit.
example
1.install flutter_svg via vs_code flutter pubspec assist s or throung terminal
2. import 'package:flutter_svg/flutter_svg.dart';
3. it will show error Target of URI doesn't exit
4. but ignore the error and flutter run doesn't show it work,and only plugin is not recognized by vs code
5. to make that error disappear i need to reload vscode window

**Comment by darshankawar** [comment]
@b14cknc0d3 
This could be related to vscode plugin you are using for which there's dedicated repo to file issues: https://github.com/Dart-Code/Dart-Code/issues
Please file the same there. Closing from here. If you disagree, write in comments and I'll reopen it.

**Comment by b14cknc0d3** [comment]
I tested on android studio same error!
