### ISSUE TITLE
Roll recipes to start running from python 3

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#94745]
https://flutter-review.googlesource.com/c/recipes/+/23943

This was reverted last week due to some unrelated issues. Handing off to the next oncall to rollout and monitor

**Comment by keyonghan** [comment]
https://flutter-review.googlesource.com/c/recipes/+/23943 was landed. Keep monitoring.

**Comment by keyonghan** [comment]
Things seem clear. Closing.
