### ISSUE TITLE
Regression in hotRestartMillisecondsToFrame on hot_mode_dev_cycle_win__benchmark

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#94741]
Flagged by SkiaPerf here:

https://flutter-flutter-perf.skia.org/e/?begin=1637639584&end=1638722944&keys=Xcbf1dae7ff6433de9223ef79f0e054a1&requestType=0&xbaroffset=26742

On the Engine roll here:

https://github.com/flutter/flutter/pull/94519

The benchmark is a little noisy, but it looks like the floor has increased a few hundred millis or ~10%.

**Comment by chinmaygarde** [comment]
@jason-simmons is going to give a shot at reproducing this. But agreed that this is noisy. Also, there were periods of time a longer time that were consistently at the higher level. Potentially worth getting to the bottom of but lets timebox this effort.
<img width="1838" alt="Screen Shot 2021-12-06 at 10 38 10 AM" src="https://user-images.githubusercontent.com/44085/144903002-a07ceea9-5344-4ebd-af08-9a84848f475b.png">

**Comment by jason-simmons** [comment]
Traced this to https://github.com/flutter/engine/commit/69be405e868b7cca79c7bdaa27e9052e6b968218

**Comment by zanderso** [comment]
@rmacnak-google @iskakaushik any thoughts about how that change could affect hot restart times?

**Comment by chinmaygarde** [comment]
This is an acceptable regression. The VMs thread pools would create an unbounded number of threads earlier and now the thread count is capped to available device concurrency. This small regression is a worth creating fewer threads overall.
