### ISSUE TITLE
Hot restart stuck in Chrome until interacting with browser

### ISSUE THREAD

**Issue by otizhi** [flutter/flutter#94754]
## Steps to Reproduce

1. Execute `flutter run -d chrome` on the standard code sample created with `flutter create`
2. Chrome opens and shows familiar Flutter starter screen with number in middle and increment icon in bottom right.
3. Make any change to the code, e.g. change primary swatch: `primarySwatch: Colors.amber,` and save change
4. Press "r" in the terminal

**Expected results:** Color of app in Chrome should now change

**Actual results:** Terminal stuck at `Performing hot restart.....`

**Workaround:** Move mouse over Chrome. After this host restart completes.

**Flutter doctor:** Output of `flutter doctor`:

```
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.22000.348], locale en-US)
    • Flutter version 2.5.3 at C:\Users\user\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (7 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.62.3)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.29.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.45
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 96.0.1054.43
```

**Flutter analyze** Output of `flutter analyze`:
```
Analyzing abc...                                                     
No issues found! (ran in 1.8s)
```

**Comment by danagbemava-nc** [comment]
Hi @otizhi, this issue was initially reported https://github.com/flutter/flutter/issues/89874 and fixed over there. 

The fix is currently available on `master` and `beta` channels, you can check out either of those channels or wait until the fix is available in the `stable` channel.

Closing as this has already been fixed. 

Thank you
