### ISSUE TITLE
Flutter repository should not contain implicit null returns for functions with nullable return types

### ISSUE THREAD

**Issue by srawlins** [flutter/flutter#94759]
## Use case

Given a function with a nullable return type, it should not fall off the end of the function with an implicit return statement. All returns should be explicit, which prevents bugs where the developer forgot to return a value.

## Proposal

Add explicit return statements.

**Comment by goderbauer** [comment]
@srawlins Did you fix all instances with your PRs? Can we close this?

**Comment by srawlins** [comment]
Er, probably. 😁
