### ISSUE TITLE
[Linux] Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds.

### ISSUE THREAD

**Issue by biancabbeatriz** [flutter/flutter#94757]
## Steps to Reproduce

1. `git clone https://github.com/flutter/flutter.git`
2. `flutter`

## Logs

<details>
<summary>Logs</summary>

```
[kefd@kefd ~]$ flutter
Building flutter tool...
/home/kefd/flutter/bin/internal/shared.sh: line 24: /home/kefd/flutter/bin/cache/dart-sdk/bin/dart: No such file or directory
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)
```

```
[kefd@kefd ~]$ flutter doctor -v
Building flutter tool...
/home/kefd/flutter/bin/internal/shared.sh: line 24: /home/kefd/flutter/bin/cache/dart-sdk/bin/dart: No such file or directory
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)
```

</details>
The file exists, but flutter can't find. Already uninstalled and installed again and the error did not solve.

**Comment by maheshmnj** [comment]
HI @biancabbeatriz, Thanks for filing the issue. Can you please try this [Stackoverflow solution](https://stackoverflow.com/a/58283307/8253662) and see if this works.

**Comment by HankG** [comment]
I attempted to reproduce on a fully updated clean VoidLinux VM that I have. Following the manual installation procedures above I was able to get flutter to run without the above errors.

**Comment by biancabbeatriz** [comment]
> HI @biancabbeatriz, Thanks for filing the issue. Can you please try this [Stackoverflow solution](https://stackoverflow.com/a/58283307/8253662) and see if this works.

following the stackoverflow steps, deleting the cache folder, did not resolve the problem


> I attempted to reproduce on a fully updated clean VoidLinux VM that I have. Following the manual installation procedures above I was able to get flutter to run without the above errors.

should not be problem with the musl? i have the musl version of voidlinux.

still do not know what the error is...

**Comment by maheshmnj** [comment]
I think this generally happens when your internet is getting blocked. Can you please try running this in the terminal and share the output, to ensure your internet works
 ```
ping -c 3 google.com
```

**Comment by biancabbeatriz** [comment]
> I think this generally happens when your internet is getting blocked. Can you please try running this in the terminal and share the output, to ensure your internet works.
> 
> ```
> curl -I https://pub.dev
> ```
> 
> If your internet is working please also try restarting your system.

Output:
```
[kefd@kefd bin]$ curl -I https://pub.dev
HTTP/2 200 
date: Thu, 09 Dec 2021 06:25:27 GMT
content-type: text/html; charset="utf-8"
content-length: 29852
vary: Accept-Encoding
strict-transport-security: max-age=31536000; preload
referrer-policy: no-referrer-when-downgrade
x-frame-options: deny
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
content-security-policy: default-src 'self' https:;font-src 'self' data: https://fonts.googleapis.com/ https://fonts.gstatic.com/;img-src 'self' https: data:;manifest-src 'none';object-src 'none';script-src 'self' https://tagmanager.google.com https://www.googletagmanager.com/ https://www.google.com/ https://www.google-analytics.com/ https://ssl.google-analytics.com https://adservice.google.com/ https://ajax.googleapis.com/ https://apis.google.com/ https://unpkg.com/ https://www.gstatic.com/ https://apis.google.com/ https://gstatic.com;style-src 'self' https://unpkg.com/ https://pub.dartlang.org/static/ 'unsafe-inline' https://fonts.googleapis.com/ https://gstatic.com https://www.gstatic.com/ https://tagmanager.google.com
server: dart:io with Shelf
via: 1.1 google
```

in the error it says it does not find a file, where should be the problem? ( No such file or directory )
```
[kefd@kefd ~]$ flutter
Building flutter tool...
/home/kefd/flutter/bin/internal/shared.sh: line 24: /home/kefd/flutter/bin/cache/dart-sdk/bin/dart: No such file or directory
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)
```

**Comment by maheshmnj** [comment]
thanks for the info @biancabbeatriz. Can you please browse to the location and confirm if the dart executable is present at the specified location `/home/kefd/flutter/bin/cache/dart-sdk/bin/dart`.

**Comment by biancabbeatriz** [comment]
> thanks for the info @biancabbeatriz. Can you please browse to the location and confirm if the dart executable is present at the specified location `/home/kefd/flutter/bin/cache/dart-sdk/bin/dart`.

yes but when I try to run or cd it this throws an error
```
[kefd@kefd bin]$ ls
dart     dart2native   dartaotruntime  dartdoc  pub        snapshots
dart2js  dartanalyzer  dartdevc        dartfmt  resources  utils
[kefd@kefd bin]$ ./dart
bash: ./dart: No such file or directory
[kefd@kefd bin]$ cd dart
bash: cd: dart: Not a directory
```

**Comment by maheshmnj** [comment]
> yes but when I try to run or cd it this throws an error

This is fine because its a executable not a directory

**Comment by biancabbeatriz** [comment]
> > yes but when I try to run or cd it this throws an error
> 
> This is fine because its a executable not a directory

yes but when I try to run it this throws an error

```
[kefd@kefd bin]$ ./dart
bash: ./dart: No such file or directory
```

**Comment by maheshmnj** [comment]
> yes but when I try to run it this throws an error
> [kefd@kefd bin]$ ./dart

Oops sorry missed that, Yes this should have worked. I believe OS is not able to read that file.
 can you check if `sudo sh ./dart` works?

**Comment by biancabbeatriz** [comment]
> 

this works but throws another error:
```
[kefd@kefd bin]$ sudo sh ./dart
./dart: 1: Syntax error: Unterminated quoted string
```

**Comment by maheshmnj** [comment]
In that case it looks like the dart file has some syntax error can you try recloning the SDK?

**Comment by HankG** [comment]
> should not be problem with the musl? i have the musl version of voidlinux.

Yes that is what the problem is. I created a clean VoidLinux VM using the musl instead of glibc and can see the exact same error.

**Comment by biancabbeatriz** [comment]
> > should not be problem with the musl? i have the musl version of voidlinux.
> 
> Yes that is what the problem is. I created a clean VoidLinux VM using the musl instead of glibc and can see the exact same error.

Ok thank you. i'll change to glibc
