### ISSUE TITLE
Create a third_party/sqlite repository on flutter.googlesource.com

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#94773]
Flutter will use an SQLite database file to write a description of a sequence of scenes that can be read to play them back for further debugging and profiling (only present in debug & profile modes).

The SQLite sources are derived from the [amalgamated sources](https://github.com/sqlite/sqlite/tree/c436b3056d8da290fbd5870cea45e7547394051a#the-amalgamation) generated from either the upstream [Fossil](https://sqlite.org/src/doc/trunk/README.md) or [Git](https://github.com/sqlite/sqlite) repositories. Pulling in sources from the repository itself is not recommended both for performance (as outlined in the section on amalgamation) and size reasons (the entire repo is 140 MB at `--depth=1`)

A one-click mechanism to update and amalgamated sources, version information, and an optimized set of GN rules is present in https://github.com/chinmaygarde/sqlite. The new repo can either be initialized to https://github.com/chinmaygarde/sqlite/commit/ef1f9f4172161e176ba68a0bd401e15ddc2ea25c or left bare and I can fill it with the contents of that repo.

The LICENSE has been verified to be part of the ["unencumbered" list here](http://g3doc/company/thirdparty/licenses_generated). cc @Hixie in case he wants to verify the repo layout.

**Comment by keyonghan** [comment]
The repo is ready: https://flutter.googlesource.com/third_party/sqlite/, with initialization commit: https://github.com/chinmaygarde/sqlite/commit/ef1f9f4172161e176ba68a0bd401e15ddc2ea25c.
