### ISSUE TITLE
Appium Inspector not able to display the Flutter elements only for iOS

### ISSUE THREAD

**Issue by harnit-bakshi** [flutter/flutter#94776]
Hi,
Background:
We are trying to build A automation for our apps. Recently we chose Browserstack and Appium as our tools of choice as these can automate tests for any mobile platform

We started with Android and there were no issues, but when we started with iOS we noticed the following:
- We could get the list of elements from Appium Inspector if we inspect an iOS running within Simulator
- We could not get  list of elements from Appium Inspector if we inspect an iOS running on real device
- We could get the list of elements from Appium Inspector, if we enable Settings -> Accessibility -> Spoken Content -> Speak Selection, Speak Screen. I found this out through following this ticket: https://github.com/flutter/flutter/issues/17988. **See comment:** https://github.com/flutter/flutter/issues/17988#issuecomment-688674451

Seems like Flutter disables the list of elements if it's not a simulator

Is there a configuration or setting I can use to re-enable this on real devices please? 
I have tried using: RendererBinding.instance.setSemanticsEnabled(true). This did not work for me, if this is the solution can someone please mention where do I need to enable this setting and is there anything else I need to do?

**Comment by darshankawar** [comment]
@harnit-bakshi 
Flutter app don't yet fully support Appium yet, so the behavior you are seeing could be expected. See [this](https://github.com/flutter/flutter/issues/17988#issuecomment-899833465) comment  which indicates the required iOS support for appium isn't there yet. 
You may follow-up in this issue for further reference / updates on Flutter's support for Appium, https://github.com/flutter/flutter/issues/18060 and https://github.com/flutter/flutter/issues/17988 for accessibility related updates.
Closing from here.

**Comment by harnit-bakshi** [comment]
@darshankawar I have read all those tickets. My question relates to if I can see the elements for Flutter iOS app in Simulator then I should be able to see it in Real Device

So I am not even asking about Appium but generally questioning why is the List of Elements hidden for real device. Can you answer this specific question
