### ISSUE TITLE
Using FractionalOffset's const constructor emits analyzer warnings.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#9478]
Evaluation of this constant expression throws an exception:

const FractionalOffset(0.4,0.5)

**Comment by Hixie** [comment]
runtime exception or analyzer error?

**Comment by Hixie** [comment]
...and what's the error

**Comment by apwilson** [comment]
The error is: "Evaluation of this constant expression throws an exception"

**Comment by apwilson** [comment]
Analyzer warning

**Comment by Hixie** [comment]
Huh.

**Comment by apwilson** [comment]
If I change it to 'new' then analyzer is fine.  Maybe it's because of the asserts in the constructor?  I dunno.

**Comment by Hixie** [comment]
Are you sure you're passing exactly the above, and not null?

**Comment by eseidelGoogle** [comment]
Are we sure @apwilson is using the same version of the analyzer as we are? :)  With the same flags?

**Comment by apwilson** [comment]
yes

**Comment by apwilson** [comment]
Here's the entire file:

```
import 'package:flutter/widgets.dart';

///
class Foo {
  ///
  FractionalOffset bar() {
    return const FractionalOffset(0.4, 0.5);
  }
}

```

**Comment by apwilson** [comment]
My analysis options are here:

https://fuchsia.googlesource.com/sysui/+/master/.analysis_options

**Comment by apwilson** [comment]
It feels like a bogus analyzer error.  When I copy Fractional Offset into the above file the error goes away, if just doesn't like importing it for some reason

**Comment by apwilson** [comment]
Also, if I move the asserts *into* the constructor rather than being inlined the error goes away

**Comment by pylaligand** [comment]
See also: https://github.com/dart-lang/sdk/issues/29358.

**Comment by apwilson** [comment]
I think asserting in an initializer is the real problem.

**Comment by sethladd** [comment]
Does this help? https://github.com/flutter/flutter/issues/5865#issuecomment-270977906

**Comment by pylaligand** [comment]
It doesn't. The only difference in our case is that we're not calling the constructor in a different file from where it's defined.

**Comment by Hixie** [comment]
cc @bwilkerson

**Comment by apwilson** [comment]
This is fixed I believe.
