### ISSUE TITLE
Engine builders running Xcode 13 do not have any valid iOS simulator runtimes

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#94780]
Testing Xcode 13 cipd package in the engine shows no available iOS simulator runtimes.

`Mac Web Engine`  (note no runtimes listed, and devices `unavailable, runtime profile not found`):
```
== Device Types ==
iPhone 4s (com.apple.CoreSimulator.SimDeviceType.iPhone-4s)
...
iPad mini (6th generation) (com.apple.CoreSimulator.SimDeviceType.iPad-mini-6th-generation)
== Runtimes ==
== Devices ==
-- Unavailable: com.apple.CoreSimulator.SimRuntime.iOS-13-0 --
    iPhone 8 (19B472BA-C0FF-45EE-8CEF-9C6DDA134F18) (Shutdown) (unavailable, runtime profile not found)
    iPhone 8 Plus (5828F22B-BA3B-443D-B554-76FD75C67AF4) (Shutdown) (unavailable, runtime profile not found)
    iPhone 11 (DF95828D-5A62-4198-9214-67F1E3CE7A07) (Shutdown) (unavailable, runtime profile not found)
```
https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/magder_google.com/b6b2af5e756fd2f481aad07ffaa7d630973d972532a1139e128429a681287595/+/build.proto?server=chromium-swarm.appspot.com

`Mac Unopt` `IosUnitTests` also cannot find available simulators even though it wants the "default" iOS 15 simulator `-destination "platform=iOS Simulator,name=iPhone 11"`, which  resolves to iOS 15 `SDKROOT = iphonesimulator15.0`, and `iPhone 11`.  I see that device type is available in the downloaded cipd package at `Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/DeviceTypes/iPhone 11.simdevicetype`.  

https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/magder_google.com/330b67ac0733ed4e15440038e105b2621336d5f14c27a136641b9ed8f67409ce/+/build.proto?server=chromium-swarm.appspot.com

But the devicelab staging builders using the same Xcode cipd bundle shows only the iOS 15 runtime available, and `module_test_ios ` test is passing on simulators.
```
Executing: xcrun simctl list runtimes in /opt/s/w/ir/x/w/recipe_cleanup/tmp742h195q/flutter sdk with environment {BOT: true, LANG: en_US.UTF-8}
== Runtimes ==
iOS 15.0 (15.0 - 19A339) - com.apple.CoreSimulator.SimRuntime.iOS-15-0
"xcrun" exit code: 0
```
and shows an available iOS 15, iPhone 11 simulator:
```
{ platform:iOS Simulator, id:608E7473-09A7-4F41-AC12-0E673AEEF710, OS:15.0, name:iPhone 11 }
```
https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/magder_google.com/ed6964ff8e4b372114f572353080765155c66c27ef0527e7d99454b7b83e55c8/+/build.proto?server=chromium-swarm.appspot.com

https://logs.chromium.org/logs/flutter/led/magder_google.com/ed6964ff8e4b372114f572353080765155c66c27ef0527e7d99454b7b83e55c8/+/u/run_module_test_ios/test_stdout

Blocking https://github.com/flutter/flutter/issues/85555

**Comment by jmagman** [comment]
May be related to https://github.com/flutter/flutter/issues/91689, though by default the Xcode cipd package should at least contain the default iOS 15 SDK, which seems true in the passing `module_test_ios` test:
```
$ mac_toolchain install -help
Installs the requested parts of Xcode toolchain.

...
  -with-runtime
    	Whether to install the default iOS runtime to Xcode. Only works in ios kind. (default true)
```

**Comment by jmagman** [comment]
@godofredoc shot in the dark, but maybe the cached `depot_tools` `mac_toolchain` is out of date on this builder and predates the runtimes being pulled out, and is just downloading the Xcode bundle and not the runtime?
If you can SSH in, is there anything in `Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/`?

**Comment by jmagman** [comment]
Maybe it's because the cipd package is missing the tag `type:xcode_default`?  The chrome packages have that tag, but I had to upload the Xcode package without tags and then add them later to enforce unique refs.  If that's the problem though I'm not sure why it would be working on the devicelab machines.  I'll add the tag and see if that helpd.

**Comment by jmagman** [comment]
> I'll add the tag and see if that helps.

Actually I'll need the old cached version of Xcode cleared out first.

**Comment by jmagman** [comment]
> > I'll add the tag and see if that helps.
> 
> Actually I'll need the old cached version of Xcode cleared out first on `build828-m9` `build829-m9` `build830-m9` and `build831-m9` to test.

Realized `build829-m9` didn't have this Xcode ref cached, trying it out there with the updated tag: 
https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/magder_google.com/3b5ca91c35645075e60917649ffdd0cefb54497408748ac6b4dceca4f41ffb18/+/build.proto?server=chromium-swarm.appspot.com

**Comment by jmagman** [comment]
> > > I'll add the tag and see if that helps.
> > 
> > 
> > Actually I'll need the old cached version of Xcode cleared out first on `build828-m9` `build829-m9` `build830-m9` and `build831-m9` to test.
> 
> Realized `build829-m9` didn't have this Xcode ref cached, trying it out there with the updated tag: https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/magder_google.com/3b5ca91c35645075e60917649ffdd0cefb54497408748ac6b4dceca4f41ffb18/+/build.proto?server=chromium-swarm.appspot.com

Okay that didn't work, same issue:
```
The requested device could not be found because no available devices matched the request.
```

**Comment by jmagman** [comment]
> shot in the dark, but maybe the cached `depot_tools` `[CACHE]/osx_sdk/mac_toolchain` is out of date on this builder and predates [the runtimes being pulled out](https://g3doc.corp.google.com/company/teams/chrome/ios/docs/infra/xcode_upload.md?cl=head#upload-ios-runtimes), and is just downloading the Xcode bundle and not the runtime?

This is the problem, I ran `mac_toolchain help install-runtime` and it doesn't recognize that command: https://logs.chromium.org/logs/flutter/led/magder_google.com/9f9b8ee3ffe3cf1268fe2ac0a081104b8dbbe233f1b1524d5499ab6a9c1e006a/+/u/mac_toolchain_help/stdout

@godofredoc points out `mac_toolchain` is pinned: https://cs.opensource.google/flutter/recipes/+/main:recipe_modules/osx_sdk/api.py;l=18

**Comment by jmagman** [comment]
Tried on ToT from yesterday `8d058f4240fcfbaabd06ae2b5e5c2deff6f0b250`, simctl now shows iOS 15 runtime is available:
```
== Runtimes ==
iOS 15.0 (15.0 - 19A339) - com.apple.CoreSimulator.SimRuntime.iOS-15-0
```
https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/magder_google.com/a6bc41f3f2a961077ee670f0c8fc9f245f872be34700b46a284ee441103ff3d0/+/build.proto?server=chromium-swarm.appspot.com
https://logs.chromium.org/logs/flutter/led/magder_google.com/a6bc41f3f2a961077ee670f0c8fc9f245f872be34700b46a284ee441103ff3d0/+/u/simctl_list/stdout

**Comment by jmagman** [comment]
Simulator tests `IosUnitTests ` passed on that SHA https://logs.chromium.org/logs/flutter/led/magder_google.com/a6bc41f3f2a961077ee670f0c8fc9f245f872be34700b46a284ee441103ff3d0/+/u/test:_Host_Tests_for_ios_debug_sim/stdout

**Comment by jmagman** [comment]
@godofredoc I believe https://flutter-review.googlesource.com/c/recipes/+/23980 worked!  Simulator test passed with `13a233`:
https://logs.chromium.org/logs/flutter/led/magder_google.com/45c3baf31e6eacc957ea529a5bc6455699a6ea3cd1fc9198228d3d5a11277398/+/u/test:_Host_Tests_for_ios_debug_sim/stdout

Shall I close this?

**Comment by godofredoc** [comment]
Those are great news. Closing the bug!
