### ISSUE TITLE
Why is the google map repo not clonable?

### ISSUE THREAD

**Issue by nyck33** [flutter/flutter#94783]
This seems like a paradox where Google is saying, "Flutter cross-platform, easy to use" and then here: https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter/google_maps_flutter
I can't clone it to run the example.

**Comment by maheshmnj** [comment]
Hi @nyck33, The repository is https://github.com/flutter/plugins what you are looking at is a directory in the linked repository and Github doesn't allow cloning a directory (A third party tool might do).

Closing as this isn't really an issue with flutter.
