### ISSUE TITLE
google maps example does not work

### ISSUE THREAD

**Issue by nyck33** [flutter/flutter#94784]
Cloned the google maps folder only using this: https://askubuntu.com/a/645276/806813

Then had to move google_maps_flutter folder somewhere else.  (That's just what the error after flutter run said).

Had to change:
```
dependencies {
        classpath 'com.android.tools.build:gradle:3.3.2'
    }
```
Finally runs but maps don't even appear.  
I read something on Reddit and elsewhere that the google_maps plugin is not very good.  
That is really unfortunate.

**Comment by darshankawar** [comment]
@nyck33 
I just now tried the google_map_flutter plugin [example](https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter/google_maps_flutter/example) on iOS which ran properly for me without any issues:

<img width="365" alt="Screenshot 2021-12-07 at 1 43 04 PM" src="https://user-images.githubusercontent.com/67046386/144992227-43050358-52a7-4ba3-bca9-fc550205f814.png">
<img width="381" alt="Screenshot 2021-12-07 at 1 43 12 PM" src="https://user-images.githubusercontent.com/67046386/144992246-7289a3d6-85ce-41f1-b9a6-ab036664630e.png">

I suggest you to directly clone https://github.com/flutter/plugins repo and then try the example and see if you still get same behavior or not.

**Comment by nyck33** [comment]
@darshankawar  could you perform all operations?  I had another google map example app where it displays but operations don't work except maybe place a circle on the map.  

Also, where does the Hybrid Composition lines noted here go?
```
if (defaultTargetPlatform == TargetPlatform.android) {
  AndroidGoogleMapsFlutter.useAndroidViewSurface = true;
}
``` 
That came from here: https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter/google_maps_flutter#hybrid-composition

Which build.gradle and exactly where?  These things are not stated.  
Also perhaps hybrid composition does need to be used for any of the example operations to be performable?
Please flesh out the documentation as right now it is bare bones and pretty much impossible to follow.

**Comment by nyck33** [comment]
I can get the little "Go to the Lake" example working but not the other controls.

**Comment by nyck33** [comment]
I could get the example working now but it's all in Google speak:  ie.  what is change alpha, change info, change info anchor, etc etc etc.  There should be documentation on all these things you can try.

**Comment by nyck33** [comment]
I could get the example working now but it seems on map_ui.dart that myLocationButtonEnabled is true or even if it's toggled, I don't get the button.  This is a core feature.  I want to push that button and have it move from Sydney Australia to my current location but have no idea what's wrong because according to the API, that button should be there.

**Comment by nyck33** [comment]
For instance, here: https://pub.dev/documentation/google_maps_flutter_platform_interface/latest/google_maps_flutter_platform_interface/LatLng-class.html

That is terrible, +90 to -90 it should say "with the equator being zero and north being positive, south being negative" and same goes for longitude.

**Comment by nyck33** [comment]
on map_ui.dart there is no location marker.  I am looking at my city and my location but nothing.

**Comment by darshankawar** [comment]
@nyck33 
Tried the same example on Android too and was able to navigate and see all the categories working properly, ex: Map coordinates, Map click, camera control, animated, camera control, place marker, place polyline and so on.

If you have specific observations / use case from the maps example that isn't working, please log separate issues or club them together with actual vs expected behavior and then we can address it properly.

**Comment by nyck33** [comment]
#

> on map_ui.dart there is no location marker. I am looking at my city and my location but nothing.

**Comment by darshankawar** [comment]
> The my location does not work for sure in map_ui.dart. The my location button is enabled by default on map_ui.dart but it does not appear on the map. My location is enabled by default as well but it also does not work.

I believe you are hitting https://github.com/flutter/flutter/issues/46890. Please check that and see if your case is same as mentioned.

**Comment by nyck33** [comment]
@darshankawar oddly the button appears on my old LG-K210 but not my more recent Alcatel 1B.  But I implemented my own button now to move camera to my location so am going to close for the time being.  Thanks for your time and help.
