### ISSUE TITLE
Unable to create new PRs against flutter/plugins master

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#94790]
https://github.com/flutter/plugins/pull/4584 was landed to flutter/plugins `main` instead of `master`, due to a bot redirect that I didn't notice when reviewing. That commit doesn't actually exist on `main` though, nor is that the branch we are currently using—perhaps the mirroring overwrote it?

I tried opening a new copy of that PR, and a bot immediately re-targeted it to `main`. We need the ability to open and land PRs against `master`, since we haven't switched to `main` yet.

**Comment by stuartmorgan** [comment]
I have verified that this is happening to any new branch I try to open. It looks like the last unaffected PR was opened 15 hours ago, and the first bad PR 11 hours ago.

**Comment by stuartmorgan** [comment]
I found the UI to fix PR targets (I looked before, but missed it somehow), so this can be downgraded. Having a bot trying to sabotage every new PR to land on a branch that will silently eat the PR is still pretty bad though.

**Comment by keyonghan** [comment]
I guess the culprit is https://github.com/flutter/cocoon/pull/1493, which somehow changes the behavior of plugins repo.
/cc @CaseyHillers  could you help take a look?

**Comment by CaseyHillers** [comment]
The fix has been deployed. I'll monitor to see if this is still occurring.

**Comment by keyonghan** [comment]
> The fix has been deployed. I'll monitor to see if this is still occurring.

Verified it is fixed: https://github.com/flutter/plugins/pull/4592. Thanks!
