### ISSUE TITLE
Request to measure doctor success and fails in the wild

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#9479]
We're measuring how often doctor runs (yay!) but not sure if we measure how often doctor reports a success or failure. We're curious how many people might abandon Flutter because an install failed to successfully complete.

TBD:

* What is an install failure?

**Comment by sethladd** [comment]
cc @xster

**Comment by xster** [comment]
Done. I won't paste the link here but it's in behaviour->app speed->doctor. 
Too bad analytics has 3 semantically similar but technically orthogonal ways of measuring things so unfortunately we don't get the Behaviour Flow on success/failure for free
