### ISSUE TITLE
List of files variable type reset after calling the async List type of API

### ISSUE THREAD

**Issue by bhanuka96** [flutter/flutter#94795]
I am passing the List of Files to the function. That List of Files variable reset after calling the DB API. That API return type is List. And there is no way to reset `attachFiles` from another way.

**This is my function**

```dart
   List<File> attachFiles = [];

  Future postRequest(BuildContext context, PostModel postModel) async {
    List<RequirementModel> requirements = [];
    attachFiles = postModel.fileNotifierValues;
    print('attach files-1 : ${attachFiles?.length}');
    requirements = List.from(await db.checkRequirement(postModel.customerId, postModel.subCategory.subCategoryId));
    print('attach files-2 : ${attachFiles?.length}');
...
}
```

**Output result**
```
attach files-1 : 1
attach files-2 : 0
```

**checkRequirement function**

```dart
  Future<List<RequirementModel>> checkRequirement(String uid, String subId) async {
    var ref = _db
        .collection('requirement')
        .where('status', isEqualTo: 'Active')
        .where('customerId', isEqualTo: uid)
        .where('subCategory.id', isEqualTo: subId);

    List<RequirementModel> model = await ref.get().then((list) => list.docs.map((doc) => RequirementModel.fromForestore(doc)).toList());
    if ((model?.length ?? 0) != 0) {
      model.removeWhere((element) => element.enquiryPrivate == true);
      model.removeWhere((element) => element.isPromoInquiry == true);
      return model;
    } else {
      return [];
    }
  }
```

**flutter doctor -v**

> [✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-x64, locale
>     en-LK)
>     • Flutter version 2.5.3 at /Users/bhanukaisuru/dev/flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision 18116933e7 (8 weeks ago), 2021-10-15 10:46:35 -0700
>     • Engine revision d3ea636dc5
>     • Dart version 2.14.4
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
>     • Android SDK at /Users/bhanukaisuru/Library/Android/sdk
>     • Platform android-31, build-tools 30.0.3
>     • Java binary at: /Applications/Android
>       Studio.app/Contents/jre/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 13.1, Build version 13A1030d
>     • CocoaPods version 1.11.2
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 2020.3)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
> 
> [✓] VS Code (version 1.62.3)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.29.0
> 
> [✓] Connected device (2 available)
>     • PRA LX2 (mobile) • 6MU7N17A12000618 • android-arm64  • Android 8.0.0 (API
>       26)
>     • Chrome (web)     • chrome           • web-javascript • Google Chrome
>       96.0.4664.55
> 
> • No issues found!

**Comment by darshankawar** [comment]
@bhanuka96 
What's the expected behavior you are looking for ? The code seem to involve backend. Is there an easy way to replicate the behavior you are seeing ?
Also looking at the code sample you provided, this doesn't seem to be framework related behavior, at best, it could be related to Dart and also you can reach out on stackoverflow.

**Comment by bhanuka96** [comment]
@darshankawar This is not about the backend. I change my code into this. Now it's working fine.

**from**
`attachFiles = postModel.fileNotifierValue;`
**to**
`attachFiles = List.from(postModel.fileNotifierValue ?? []);`

Why doesn't this work to my previous code?

**Comment by darshankawar** [comment]
From the code you posted, you have `attachFiles` declared as an array of list `List<File> attachFiles = [];`, so it'll accept only an array object coming from `List.from(postModel.fileNotifierValue ?? []);`.

Closing this as resolved based on your comment above.
