### ISSUE TITLE
[Windows Desktop] Keyboard navigation not recognised by NVDA

### ISSUE THREAD

**Issue by chrisnorman7** [flutter/flutter#94791]
## Details

If you create the default flutter application with `flutter create counter`, then run that application under Windows with NVDA running, controls aren't accessible via the keyboard.

While the keyboard navigation keys like tab do appear to move focus (you can verify by tabbing to the button), those focus changes aren't picked up by NVDA.

You can use object navigation to navigate to the created widgets, but it is by no means intuitive.

**Target Platform:*Windows*
**Target OS version/browser:*Windows 10*
**Devices:*Desktop and laptop computers*

## Logs

<details>
<summary>Logs</summary>

```
Analyzing counter...                                            
No issues found! (ran in 1.1s)
```

```
[ÔêÜ] Flutter (Channel master, 2.6.0-12.0.pre.936, on Microsoft Windows [Version 10.0.19043.1348], locale en-GB)
    ÔÇó Flutter version 2.6.0-12.0.pre.936 at C:\Users\chris\flutter
    ÔÇó Upstream repository https://github.com/flutter/flutter.git
    ÔÇó Framework revision 47a8f440c7 (4 hours ago), 2021-12-06 21:47:20 -0800
    ÔÇó Engine revision 66a281107b
    ÔÇó Dart version 2.16.0 (build 2.16.0-80.0.dev)
    ÔÇó DevTools version 2.9.1

[ÔêÜ] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc2)
    ÔÇó Android SDK at C:\Users\chris\AppData\Local\Android\sdk
    ÔÇó Platform android-31, build-tools 31.0.0-rc2
    ÔÇó Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    ÔÇó Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    ÔÇó All Android licenses accepted.

[ÔêÜ] Chrome - develop for the web
    ÔÇó Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[ÔêÜ] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.3)
    ÔÇó Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    ÔÇó Visual Studio Community 2019 version 16.9.31129.286
    ÔÇó Windows 10 SDK version 10.0.19041.0

[ÔêÜ] Android Studio (version 2020.3)
    ÔÇó Android Studio at C:\Program Files\Android\Android Studio
    ÔÇó Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    ÔÇó Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    ÔÇó Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[ÔêÜ] VS Code, 64-bit edition (version 1.62.3)
    ÔÇó VS Code at C:\Program Files\Microsoft VS Code
    ÔÇó Flutter extension version 3.27.0

[ÔêÜ] Connected device (3 available)
    ÔÇó Windows (desktop) ÔÇó windows ÔÇó windows-x64    ÔÇó Microsoft Windows [Version 10.0.19043.1348]
    ÔÇó Chrome (web)      ÔÇó chrome  ÔÇó web-javascript ÔÇó Google Chrome 96.0.4664.45
    ÔÇó Edge (web)        ÔÇó edge    ÔÇó web-javascript ÔÇó Microsoft Edge 95.0.1020.53

ÔÇó No issues found!
```

</details>

**Comment by maheshmnj** [comment]
Hi @chrisnorman7, Thanks for filing the issue.

>  then run that application under Windows with NVDA running, controls aren't accessible via the keyboard.

Can you please share more about this what exactly is NVDA desktop and how to use it inorder to reproduce the issue.

Thanks

**Comment by crentava** [comment]
I'm not the original issue creater but I can do my best to explain this.
NVDA is a screen reader for the Windows platform. Visually impaired/blind individuals use it in order to operate their computer as well as use other applications such as those developed in flutter.
you can download it from www.nvaccess.org

**Comment by zersiax** [comment]
TO add onto what @crentava said, screen readers communicate with accessibility APIs in order to tell the user what's happening in an application. Normally, when the keyboard focus changes, the requisite accessibility events are fired that make sure a screen reader is able to tell the user the focus is now on the new control, which is control XYZ of type ABC and with value DEF, if applicable. Flutter UI elements currently do not appear to be emitting these properly.

**Comment by chrisnorman7** [comment]
Hi,
To add to what @crentava and @zersiax have already stated (which is far more detailed than I'd have been able to provide, so thank you for that), NVDA is one of the screen readers which are advertised as working with Flutter Web, according to the [accessibility](https://docs.flutter.dev/development/accessibility-and-localization/accessibility) page.

**Comment by maheshmnj** [comment]
Thanks for the detailed explanation. Leaving this issue open for further insights from the team.

**Comment by chrisnorman7** [comment]
Whoever is working on this, great job! I've just upgraded Flutter on the master branch, and it's working really well.

I won't close yet in case I find more things, but I just wanted to massively thank whoever has improved things this much.

**Comment by gspencergoog** [comment]
Thanks for the report! Closing for now. If you find any other issues, please open a new issue. (Desktop Triage)

**Comment by cbracken** [comment]
@chrisnorman7 thanks for testing all the new a11y work landing in the Windows embedder!

As you run into any issues please file bugs and (if you remember), CC me (@cbracken). I'll be out for a couple weeks, but glad to take a look when I'm back. Thanks again!
