### ISSUE TITLE
Checkout of engine source fails if no prebuilt Dart SDK is available

### ISSUE THREAD

**Issue by whesse** [flutter/flutter#94793]
The gclient checkout of the engine source tree now fails if there is no prebuilt SDK available for the Dart version being built.
Developers working on Dart changes need to be able to check out and build engine with tip-of-tree Dart and with unlanded changes to Dart.  The CI builders building Flutter with tip-of-tree versions of its dependencies also need this.

This can be fixed by adding a variable 'download_dart_sdk' to engine DEPS with default value true, that can be overridden
in these cases.

The failure started with a commit that makes it a failure when downloading the engine source tree and the prebuilt Dart SDK is not found: [#30093](https://github.com/flutter/engine/pull/30093).

I am uploading a PR with this proposed fix.

**Comment by dcharkes** [comment]
Link to a failing build: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8828515888595548081/+/u/gclient_runhooks/stdout

**Comment by CaseyHillers** [comment]
This might be related to https://github.com/flutter/flutter/issues/94492 - We're seeing issues related to the Dart SDK, and how infra needs to clobber the source checkout everytime to get it.

**Comment by whesse** [comment]
PR #30093 is landed, and our recipes now create a gclient solution with the custom var download_dart_sdk set to false.  Closing.

**Comment by whesse** [comment]
A change was landed to SDK downloads that stopped checking the download_dart_sdk variable.
Restoring that check in a new PR, https://github.com/flutter/engine/pull/33345
