### ISSUE TITLE
Null error when using a DropDownButton

### ISSUE THREAD

**Issue by mishadynin** [flutter/flutter#948]
I get a stack trace from deep inside rendering (see below.)

I might be violating some implicit invariants for the Dropdown component, by for example using 'null' as one of the DropDownMenuItem values; but I am not sure what invariants are there.

[stacktrace.txt](https://github.com/flutter/flutter/files/63363/stacktrace.txt)

**Comment by Hixie** [comment]
You need to make sure you pass the DropDownButton a "value", and that that value matches one of the items you pass in.

**Comment by mishadynin** [comment]
Yes, that was the problem.  I fixed it; would be nicer if the Flutter code failed fast, but obviously it's not high priority.  Closing the issue.

**Comment by Hixie** [comment]
I'm already on it.

**Comment by mishadynin** [comment]
Per our conversation: if you activate dropdown menu but then tap outside it, onChange() gets called with null.  This is an actual bug, and appears to be the cause of invalid values that triggered the above issue.
