### ISSUE TITLE
Flow should optimize away render target switches when the same effect can be achieved via paint options.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#9480]
Render target switches caused by `SkCanvas::saveLayer` are expensive on lower end devices. These are typically introduced by `flow` when there is an opacity layer or clip. However, there are many cases where only a single item (such as an image at a custom opacity) is rendered in this target. In such cases, the paint options (such as one expressing the opacity of the image) can be used to achieve the same effect.

`flow` should look for such optimizations.

**Comment by Hixie** [comment]
cc @liyuqian @chinmaygarde is this still relevant?

**Comment by chinmaygarde** [comment]
While there has been progress made on eliding render target switches introduced by the engine itself, there is a lot more to be done on this front. Currently, the opaqueness of the SkPicture presented to the engine hinders its capability to determine if the operation is a group opacity. We should be be able to affect such optimizations once we move to our picture format. Till then, this issue should be kept open.

**Comment by liyuqian** [comment]
@chinmaygarde : is there an issue that tracks the creation of our own picture format? The last news I knew is that Skia sent us https://source.corp.google.com/aosp-android10/external/skia/src/core/SkLiteDL.h

**Comment by dnfield** [comment]
Deduping this against https://github.com/flutter/flutter/issues/92874 which is more up to date now
