### ISSUE TITLE
Flutter for web in vs code is not working

### ISSUE THREAD

**Issue by PragGawande** [flutter/flutter#94803]
Hi,
I am able to run flutter application through this command in VSCode
flutter run -d chrome --web-renderer html

I want to specify a port while running the application
flutter run -d chrome --web-port 8002

But with above command , html is not rendered and I am getting canvaskiterror

Any idea how can we specify port and render html together??

I have also added parameters in launch.json file. But it is not working.

"version": "0.2.0",
    "configurations": [
        {
            "name": "openblue_companion_flutter_poc",
            "request": "launch",
            "type": "dart",
            "args": ["-d", "chrome","--web-port", "8002"],

        },

I can run the application only when html is rendered. But need to specify a port also.

**Comment by darshankawar** [comment]
@PragGawande 
Your question is better suited for support channels like StackOverflow, so please ask the same there.
Moreover, try running `flutter run -d chrome -h` to see various options you can pass as arguments to the command and see if it helps.
Closing from here as this isn't an issue or a feature request.
