### ISSUE TITLE
dart.exe missing

### ISSUE THREAD

**Issue by justinbalaguer** [flutter/flutter#94801]
![image](https://user-images.githubusercontent.com/26339491/145034362-263bf52a-60e5-4a1e-b017-000ff5bef77b.png)
here's the image of the unzip folder, no dart.exe

**Comment by darshankawar** [comment]
@justinbalaguer 
How did you download / install the sdk zip ? Are you saying when you unzip, you don't see `dart.exe` in it ?
From your screenshot, I see `dart.bat` and `flutter.bat` . Which files are you expecting more in it ?
