### ISSUE TITLE
Unable to open file

### ISSUE THREAD

**Issue by codewithmalik** [flutter/flutter#94807]
Hi Team,

I was working on a client’s app, the client requested that I should give the .apk file so that they can test it on their android device, I have followed the steps given on the flutter official website on how to deploy an app but it is not working. I send them the file using WhatsApp messenger. the client can't open the file, whenever they try to open the app-release.apk file it says "Unable to open file".

Please help me out.

**Comment by tsgregoryv** [comment]
Try enabling the following Android Developer Setting on your client's device --> Enable Installation of Unknown Apps.

**Comment by codewithmalik** [comment]
> Try enabling the following Android Developer Setting on your client's device --> Enable Installation of Unknown Apps.

I did but nothing change

**Comment by maheshmnj** [comment]
Hi @codewithmalik, please share the output of `flutter doctor -v` on which the app was built. Can you please also check if this issue occurs with the newly created flutter project?
 
 
 Thanks

**Comment by codewithmalik** [comment]
✓] Flutter (Channel stable, 2.5.4-0.0.pre.1, on macOS 12.0.1 21A559 darwin-x64, locale en-GB)
    • Flutter version 2.5.4-0.0.pre.1 at /Users/aoomle/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 360b53e625 (6 days ago), 2021-12-07 17:58:04 +0100
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/aoomle/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.63.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] VS Code (version 1.55.2)
    • VS Code at /Volumes/Mac/Apps/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.93
    ! Error: Abdulmalik’s iPhone is not connected. Xcode will continue when Abdulmalik’s iPhone is
      connected. (code -13)

• No issues found!

**Comment by maheshmnj** [comment]
Thanks for the info @codewithmalik, Your flutter version looks strange because as far as I know, the last stable release before `2.8.0` was `2.5.3`. Can you please try upgrading to the latest stable 2.8.0 by running 

```
flutter channel stable
flutter upgrade
```
and share the updated `flutter doctor -v`.

>  I send them the file using WhatsApp messenger. the client can't open the file, whenever they try to open the app-release.apk file it says "Unable to open file".

Additionally, can you please also check if sending files through other medium makes any difference and does this happen with a newly created a flutter project too.

Thanks

**Comment by codewithmalik** [comment]
Alright @maheshmnj, I will try that and get back to you. Thanks
