### ISSUE TITLE
PhysicalModel or Material widget color doesn't change with elevation like Card

### ISSUE THREAD

**Issue by PatrickWulfe** [flutter/flutter#94815]
## Steps to Reproduce

1. Create a PhysicalModel or Material widget with a color (easier to tell with non-white/black colors) and a Card using the same color, set them to the same elevation, and their colors will be different. You can even tell with the default dark theme.   The only time they're the same color is if the card's elevation is set to 0.

**Expected results:** 
I expected material widgets with the same color and elevation to render the same color.

**Actual results:** 
PhysicalModel and Material widgets only render the color at the elevation 0 color, making the UI inconsistent when trying to build other elements with elevation and have them be the same color.

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @PatrickWulfe, 

Please provide a complete minimal reproducible code sample as well as the output of `flutter doctor -v`. 

Thank you
