### ISSUE TITLE
Can't both mixin and extend a class with a factory default constructor

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#9482]
Consider this code:
```dart
class Superclass {
  const Superclass(this.foo);
  final int foo;
}

abstract class Mixin {
  factory Mixin(int baz) = _FixedMixin;
  int get baz;
  int get baz2 => baz * 2;
}

class _FixedMixin extends Mixin {
  _FixedMixin(this.baz);
  @override
  final int baz;
}

class Subclass extends Superclass with Mixin {
  Subclass(int foo, this.bar) : super(foo);
  final int bar;
  @override
  int get baz => foo + bar;
}

void main() {
  new Subclass(1, 2);
  new Mixin(3);
}
```

It won't compile because `illegal implicit call to factory 'Mixin()' in super class` in the constructor of `_FixedMixin`.

But if I add a named constructor in `Mixin` so I can defer to it in `_FixedMixin`, instead `Subclass` gets unhappy because `mixin class 'Mixin' must not have constructors`.

**Comment by eseidelGoogle** [comment]
Does this belong in flutter/flutter or dart-lang/sdk?

**Comment by Hixie** [comment]
oops. moved.
