### ISSUE TITLE
Create a third_party/inja repository on flutter.googlesource.com

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#94824]
Used for templating during the generation of headers from reflected shader information, this repository must be initialized to https://github.com/pantor/inja/commit/88bd6112575a80d004e551c98cf956f88ff4d445.

This dependency will only be used on the host and will not be included in shipped binaries.

**Comment by keyonghan** [comment]
@chinmaygarde I created the repo with the default branch `main`: https://flutter.googlesource.com/third_party/inja/. 
 Does this repo needs `default branch` to be `master`?

**Comment by chinmaygarde** [comment]
No, the branch doesn't matter if it will be synced manually (which I suppose it will be).

**Comment by keyonghan** [comment]
It is ready in: https://flutter.googlesource.com/third_party/inja/.

**Comment by chinmaygarde** [comment]
Thanks.
