### ISSUE TITLE
Hardware keyboard keys getting stuck on iOS

### ISSUE THREAD

**Issue by borjandev** [flutter/flutter#94836]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Run the code on iOS Simulator / real iOS device with Hardware Keyboard connected 
3. Click / Tap the first TextField, start holding a modifier key on the hardware keyboard 
3. Keep holding the modifier key on the hardware keyboard, click / tap the second text field, then release the modifier key

**Expected results:** 
... - KeyDownEvent
... - KeyUpEvent
**Actual results:** 
... - KeyDownEvent

**Narrowing down the issue**:

✅: No Issue ❗️: Issue reproduced

MacOS  ✅ 
Web Canvas Kit ✅ 
iPhone - iOS 15 + bluetooth hardware keyboard ❗️
iPad Pro - iOS 15 + magic keyboard ❗️ 

Possibly a cause for the issue below as when the KeyUpEvent hasn't been dispatched, the Flutter framework still identifies that the hardware key is pressed even though it isn't, and reading the values of the keys pressed from `RawKeyboard state` via a delayed future, even a few seconds after the key has been released, confirms that by reporting that the hardware key is still pressed which is incorrect
https://github.com/flutter/flutter/issues/87391#issue-957176214

[Expected results](https://user-images.githubusercontent.com/64651636/145136295-06199075-5985-451e-8e2f-5d7aba38de93.mov)
[Issue reproduced](https://user-images.githubusercontent.com/64651636/145136001-5409309d-d9e1-46e5-89c2-e3ae05479c13.mp4)

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(MyApp());
}

final outputController = TextEditingController();

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final defaultShortcuts = Map<ShortcutActivator, Intent>.from(WidgetsApp.defaultShortcuts);
    defaultShortcuts.addAll({CustomModifierKeysMonitor(): UselessIntent()});
    return MaterialApp(
      title: 'Ink',
      theme: ThemeData(
        appBarTheme: AppBarTheme(color: Colors.black),
        primaryColor: Colors.black,
      ),
      home: HomePage(),
      shortcuts: defaultShortcuts,
    );
  }
}

class HomePage extends StatelessWidget {
  HomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          TextField(
            controller: TextEditingController(text: 'Click me first then start holding a modifier key'),
            style: TextStyle(fontSize: 11),
          ),
          TextField(
            controller: TextEditingController(text: 'Keep holding the modifier key, then click me, then release the modifier key'),
            style: TextStyle(fontSize: 11),
          ),
          ElevatedButton(
            onPressed: () {
              FocusManager.instance.primaryFocus?.unfocus();
              outputController.text = '';
            },
            child: Text("START OVER"),
          ),
          TextField(
            maxLines: null,
            enabled: false,
            controller: outputController,
          ),
        ],
      ),
    ));
  }
}

class UselessIntent extends Intent {}

class CustomModifierKeysMonitor extends KeySet<LogicalKeyboardKey> with Diagnosticable implements ShortcutActivator {
  CustomModifierKeysMonitor()
      : super(
          LogicalKeyboardKey.control,
          LogicalKeyboardKey.shift,
          LogicalKeyboardKey.alt,
          LogicalKeyboardKey.meta,
        );

  @override
  Iterable<LogicalKeyboardKey> get triggers => keys
      .expand(
        (LogicalKeyboardKey key) => _unmapSynonyms[key] ?? <LogicalKeyboardKey>[key],
      )
      .toSet();

  @override
  bool accepts(RawKeyEvent event, RawKeyboard state) {
    outputController.text += '\n${event.logicalKey.debugName} - ${event.runtimeType}';
    return false;
  }

  static final Map<LogicalKeyboardKey, List<LogicalKeyboardKey>> _unmapSynonyms = <LogicalKeyboardKey, List<LogicalKeyboardKey>>{
    LogicalKeyboardKey.control: <LogicalKeyboardKey>[LogicalKeyboardKey.controlLeft, LogicalKeyboardKey.controlRight],
    LogicalKeyboardKey.shift: <LogicalKeyboardKey>[LogicalKeyboardKey.shiftLeft, LogicalKeyboardKey.shiftRight],
    LogicalKeyboardKey.alt: <LogicalKeyboardKey>[LogicalKeyboardKey.altLeft, LogicalKeyboardKey.altRight],
    LogicalKeyboardKey.meta: <LogicalKeyboardKey>[LogicalKeyboardKey.metaLeft, LogicalKeyboardKey.metaRight],
  };

  @override
  String debugDescribeKeys() {
    return '';
  }

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```

```

```
flutter analyze
Analyzing ...                                                    
No issues found! (ran in 2.1s)
```

```
flutter doctor -v                
[✓] Flutter (Channel master, 2.6.0-12.0.pre.949, on macOS 12.0.1 21A559 darwin-arm, locale en-MK)
    • Flutter version 2.6.0-12.0.pre.949 at /opt/homebrew/Caskroom/flutter/2.5.3/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision af9cf734e8 (3 hours ago), 2021-12-07 17:39:02 -0500
    • Engine revision 66a281107b
    • Dart version 2.16.0 (build 2.16.0-80.0.dev)
    • DevTools version 2.9.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/monterey/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (4 available)
```

</details>

<!--
      Consider also attaching screenshots and/or videos to better
      illustrate the issue.

      You can upload them directly on GitHub.
      Beware that video file size is limited to 10MB.
--

>

**Comment by darshankawar** [comment]
@borjandev 
Thanks for the detailed report. I see the same behavior after trying the scenario on iOS simulator and using magic keyboard connected via bluetooth. 

<img width="340" alt="Screenshot 2021-12-08 at 2 01 40 PM" src="https://user-images.githubusercontent.com/67046386/145175208-d52c7b39-7b02-47da-bc2d-a4d47e37cfbe.png">

Although, the behavior is working as expected on latest stable (2.5.3) wherein, KeyDownEvent and KeyUpEvent are reported properly, as below:

<img width="337" alt="Screenshot 2021-12-08 at 2 01 52 PM" src="https://user-images.githubusercontent.com/67046386/145175380-8af170c1-0fdf-4ba3-b6e9-87896290f33a.png">
<img width="339" alt="Screenshot 2021-12-08 at 2 02 05 PM" src="https://user-images.githubusercontent.com/67046386/145175386-5d2a0e12-b8a6-4993-ada4-dc901234cd70.png">

<details>
<summary> master flutter doctor -v </summary>

```
[✓] Flutter (Channel master, 2.6.0-12.0.pre.957, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.6.0-12.0.pre.957 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b59281ce52 (48 minutes ago), 2021-12-07 20:09:04 -0800
    • Engine revision 66a281107b
    • Dart version 2.16.0 (build 2.16.0-80.0.dev)
    • DevTools version 2.9.1

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0
    
[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 96.0.4664.55

! Doctor found issues in 1 category.


```

</details>

**Comment by borjandev** [comment]
The exact flutter pull request that introduced this issue on the master branch is : [#92977](https://github.com/flutter/flutter/pull/92977)

The exact cherry pick commit that introduced this issue on the beta branch is : [#262b70ece1aebf84f132c51ec4cf90be605ce61b](https://github.com/flutter/flutter/commit/262b70ece1aebf84f132c51ec4cf90be605ce61b)

**Comment by LongCatIsLooong** [comment]
IIRC prior to flutter/engine#29464 hardware keyboard doesn't work in text fields on iOS. But I might have overlooked something. Does this problem exist before https://github.com/flutter/flutter/commit/6434f8e84accdda85c9f507f93b01ddb95caebc3 ?

**Comment by borjandev** [comment]
> IIRC prior to [flutter/engine#29464](https://github.com/flutter/engine/pull/29464) hardware keyboard doesn't work in text fields on iOS. But I might have overlooked something. Does this problem exist before [6434f8e](https://github.com/flutter/flutter/commit/6434f8e84accdda85c9f507f93b01ddb95caebc3) ?

 [flutter/engine#29464](https://github.com/flutter/engine/pull/29464) seems to be a part of the 15 commit auto-roll at https://github.com/flutter/flutter/pull/92977 which is the exact PR which introduced this issue of the `KeyUpEvent`❗not firing on the Flutter master branch 
 
Prior to [flutter/engine#29464](https://github.com/flutter/engine/pull/29464) I believe the hardware keyboard works in text fields on iOS however it behaves slightly differently, as in my tests with the sample code provided in this issue, I was getting : 
 
**Expected results:**
... - KeyDownEvent
... - KeyUpEvent
**Actual results:**
... - KeyDownEvent
... - KeyDownEvent❗(duplicated)
... - KeyUpEvent

Great catch @LongCatIsLooong as https://github.com/flutter/flutter/commit/6434f8e84accdda85c9f507f93b01ddb95caebc3 seems to introduce the ```... - KeyDownEvent ❗ (duplicated)``` event which is still unwanted and ideally should be fixed, however the `KeyUpEvent` ✅  behaves as expected on https://github.com/flutter/flutter/commit/6434f8e84accdda85c9f507f93b01ddb95caebc3 thus its only related to the event duplication outlined above

**Comment by borjandev** [comment]
Just encountered an even more severe side-effect, since the "stuck" key doesn't get released on the framework level, it completely messes up the whole app shortcuts infrastructure to the point that it makes iOS / iPadOS + Hardware Keyboard apps borderline unusable

If the "shift" modifier key is stuck, then you try to use ex: 

`SingleActivator(LogicalKeyboardKey.keyS, meta: true) : SaveContentIntent()` as a shortcut

It wont work as the framework thinks that you are trying to activate something like

`SingleActivator(LogicalKeyboardKey.keyS, meta: true, shift: true) : ShredContentToPiecesIntent()` as a shortcut

Not to mention that since the majority of the shortcuts will have only a single modifier key enabled at one time, thus having `shift: false` by default, the moment that the "shift" key is stuck, suddenly all of the app shortcuts malfunction and stop getting registered or even worse, an incorrect `ShredContentToPiecesIntent()` gets triggered and the framework shreds the content instead of saving it.. 

To make it worse, I don't think that this hardware keys getting stuck is limited to only modifier keys, I believe any hardware keyboard key can get stuck by following the same steps of this issue and modifying the code to listen for other hardware keyboard keys as well instead of only modifier keys

**Comment by chinmaygarde** [comment]
@jmagman Are we reverting that commit pending a fix for these issues?

**Comment by jmagman** [comment]
> @jmagman Are we reverting that commit pending a fix for these issues?

Not sure.  https://github.com/flutter/engine/pull/29464 fixed https://github.com/flutter/flutter/issues/89378 which sounded pretty painful for people (60 👍) but this one is actually impacting real devices, not simulators. @LongCatIsLooong what do you think, I'm not familiar with this code.

**Comment by borjandev** [comment]
What makes it even more critical is that it's somehow made it's way to the latest stable 2.8.0 ❗️: Issue reproduced

<details>
  <summary>flutter doctor -v</summary>
  
  ```
[✓] Flutter (Channel stable, 2.8.0, on macOS 12.0.1 21A559 darwin-arm, locale en-MK)
    • Flutter version 2.8.0 at /Users/monterey/fvm/versions/2.8.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (5 days ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/monterey/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.63.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0
```
</details>

**Comment by borjandev** [comment]
@LongCatIsLooong 

> IIRC prior to [flutter/engine#29464](https://github.com/flutter/engine/pull/29464) hardware keyboard doesn't work in text fields on iOS. But I might have overlooked something. Does this problem exist before [6434f8e](https://github.com/flutter/flutter/commit/6434f8e84accdda85c9f507f93b01ddb95caebc3) ?

Upon thorough investigation, the commit that you mentioned  https://github.com/flutter/flutter/commit/6434f8e84accdda85c9f507f93b01ddb95caebc3 with the PR :  https://github.com/flutter/flutter/pull/92441 introduced the particular issue `hardware keyboard doesn't work in text fields on iOS.` (Pressing logical keyboard keys such as `LogicalKeybordKey.keyA` doesn't type 'a' in the TextField, modifier keys on the other hand are getting registered but are getting duplicated events in the reproduction code of this issue such as :

```
... - KeyDownEvent
... - KeyDownEvent❗(duplicated)
... - KeyUpEvent
... - KeyUpEvent❗(duplicated)
```

The last good commit where the things discussed in this issue, related to using a Hardware Keyboard on iOS TextFields, are working properly is https://github.com/flutter/flutter/commit/1daae0b0ae0e819019100415e53e574e5d154dbd which is the commit before https://github.com/flutter/flutter/commit/6434f8e84accdda85c9f507f93b01ddb95caebc3 with the PR :  https://github.com/flutter/flutter/pull/92441  
```
1. Pressing `LogicalKeybordKey.keyA` results in the letter `a` being typed on iOS TextFields ✅ 
2. There are no keys getting stuck on iOS TextFields ✅ 
3. The KeyDownEvent / KeyUpEvent of modifier keys are not getting duplicated on iOS TextFields ✅ 
```

After https://github.com/flutter/flutter/commit/6434f8e84accdda85c9f507f93b01ddb95caebc3 with the PR :  https://github.com/flutter/flutter/pull/92441 things start getting broken on iOS 

```
1. Pressing `LogicalKeybordKey.keyA` doesn't type anything in iOS TextFields ❗ 
2. There are no keys getting stuck on iOS TextFields ✅
3. The KeyDownEvent / KeyUpEvent of modifier keys are getting duplicated on iOS TextFields ❗
```

Then after https://github.com/flutter/flutter/commit/136592ae79e7ed5dee251e712b2f37a6bd10b8ae with PR: https://github.com/flutter/flutter/pull/92977 

```
1. Pressing `LogicalKeybordKey.keyA` results in the letter `a` being typed on iOS TextFields ✅ 
2. Keys are getting stuck ❗
3. The KeyDownEvent gets registered without duplication but there is no KeyUpEvent ❗
```

Stable 2.8.0 ❗️behaves the same as https://github.com/flutter/flutter/commit/136592ae79e7ed5dee251e712b2f37a6bd10b8ae with PR: https://github.com/flutter/flutter/pull/92977 

```
1. Pressing `LogicalKeybordKey.keyA` results in the letter `a` being typed on iOS TextFields ✅ 
2. Keys are getting stuck ❗
3. The KeyDownEvent gets registered without duplication but there is no KeyUpEvent ❗
```

Which means that it's currently broken on all official channels including latest stable

**Comment by LongCatIsLooong** [comment]
Thanks for the detailed information! It looks like the options are:
1. revert both flutter/engine#29464 & flutter/engine#29108 (fixes a crash on iOS 15 https://github.com/flutter/flutter/issues/87809. we can take an alternative approach to putting the text input view into the responder chain).
2. fix the bug forward. not sure what that takes /cc @gspencergoog

**Comment by LongCatIsLooong** [comment]
I think I know what went wrong. The iOS text input plugin creates a new UIView every time a Flutter text field gains focus, and make that UIView the first responder. The UIView is removed once the Flutter text field loses focus.

When that happens with a modifier key held down, UIKit actually still eventually sends the "up" event to the removed `UIView`, but since the `UIView` is now detached from the original responder chain, it won't be able to propagate the key event to its original `FlutterViewController`.
