### ISSUE TITLE
Merge bot fails to merge PR by using unrelated test checks

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#94838]
PR https://github.com/flutter/plugins/pull/4591 was created based on a local branch `renew_cirrus_key`, and got closed due to merge base branch to `main` (so all test were aborted).
Then another PR https://github.com/flutter/plugins/pull/4592 was created right after, using the same branch `renew_cirrus_key` but to base branch `master`.

Though all tests passed on the second PR, but `fluttergithubbot` refused to merge this PR by using the aborted test status in the first PR. My guess is the same branch caused confusion when querying the test checks.

Similar case happens on https://github.com/flutter/engine/pull/30186 and https://github.com/flutter/engine/pull/30185

**Comment by godofredoc** [comment]
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.
