### ISSUE TITLE
`flutter pub get` plugin from a private repository

### ISSUE THREAD

**Issue by dbb987** [flutter/flutter#94842]
I'm currently working on a project that needs to provide plug-ins for the user's Flutter app, but the current plugin Open Source to the user. My code is valuable and I don't want to Open Source. I must protect the code from disclosure

**Comment by maheshmnj** [comment]
Hi @dbb987,  If I understand correctly you want to have your plugin repo private and yet be able to use by others is that correct? if so I don't think that is possible with flutter at the moment because of flutter being open source.

**Comment by dbb987** [comment]
Yes, I'm so distressed. I don't know what to do. If the code is open source, it will lose too much. There are always some codes that don't want to be open source

**Comment by maheshmnj** [comment]
@dbb987, you can do this via ssh, make your plugin repo private, and make sure you have ssh agent setup and you can install the plugin like this 

```
 plugin_name:
    git:
      url: git@github.com:username/plugin_name.git
```

**Comment by dbb987** [comment]
Thank you for your timely reply. Thank you very much,I know this, but other people can also see the source code through this. I don't want people to see the code, so I will always be my loyal customer, otherwise others won't come to me when they see the code

**Comment by maheshmnj** [comment]
> but other people can also see the source code through this.

Ohh, you mean in the development environment through the IDE?

**Comment by dbb987** [comment]
Yes, plugins are open source. I know that to meet those who do not need open source code,  provide a special way to make it not easy to crack the code like . aar or .so. It would be nice to add a special non open source plugins
