### ISSUE TITLE
Hot Reload fails after replacing image

### ISSUE THREAD

**Issue by Farial-mahmod** [flutter/flutter#94841]
Hello, thanking the Flutter team for your awesome contributions.

After changing or replacing an image inside /assets/images, Hot Reload fails to detect the new image. It requires a restart of the Studio to show the image.

My Studio Version: Arctic Fox 2020.3.1
Flutter SDK: 2.5.3

So, if possible, allow Hot Reload to detect image replacements without a Studio restart.

**Comment by danagbemava-nc** [comment]
Hi @Farial-mahmod, thanks for filing the issue. 

Please provide the output of `flutter doctor -v` and a complete minimal reproducible code sample as well as clear steps to reproduce. 

FWIW, In my experience, it has never been necessary for me to restart my IDE of choice (vscode) whenever I replace an asset in my project to get `Hot Reload` working.
