### ISSUE TITLE
[webview_flutter_android] User agent string is reset after rebuild

### ISSUE THREAD

**Issue by jeiea** [flutter/flutter#94847]
## Steps to Reproduce

I'm tired of writing minimal reproducible repository, sorry for that. If my explanation is insufficient, please comment.

1. Build and run the following in **android**.
```
Column(children:[
  WebView(
    initialUrl: 'somewhere.net',
    userAgent: 'some user agent',
  ),
  ElevatedButton(onPressed: () => setState(() {}), child: Text('rebuild')),
])
```
2. Press the button.
3. Browse to other page in webview or create xhr.
4. Check user agent of the second request.

**Expected results:** it should send the user agent string `'some user agent'`.

**Actual results:** User agent string is set at first, but it reverted to the default in the second request in the webview page.

## Additional context
The following is brief tracking by debugger.

webview_flutter_android 2.3.0 [introduced this change](https://github.com/flutter/plugins/blame/3e29e9173980253ab31c210487dc6221fd6b03e2/packages/webview_flutter/webview_flutter_android/lib/webview_android_widget.dart#L420-L426). From [this](https://github.com/flutter/plugins/blob/3e29e9173980253ab31c210487dc6221fd6b03e2/packages/webview_flutter/webview_flutter/lib/src/webview.dart#L410-L426) `absent()` value is passed for presenting no change of user agent string, but `webView.settings.setUserAgentString('');` clear previously set user agent.

It broke my app behavior so I think this is a regression.

<details>
  <summary>Logs</summary>

```
> flutter analyze
The plugin `flutter_webview_plugin` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.
Analyzing app...                                                   

   info • Unused import: 'package:collection/collection.dart' • lib/pages/challenge/challenge_page.dart:1:8 • unused_import
   info • Unused import: 'package:collection/collection.dart' • lib/services/util.dart:1:8 • unused_import

2 issues found. (ran in 10.4s)
```

```
```

```
> flutter doctor -v
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-x64, locale en-KR)
    • Flutter version 2.5.3 at /Users/jeiea/.asdf/installs/flutter/2.0.0-stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (8 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/jeiea/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • SM G996N (mobile) • R3CR10909RV                              • android-arm64  • Android 11 (API 30)
    • iPhone (mobile)   • 3cab6ea47af788fbe8d5001e572f5d4c6bb69138 • ios            • iOS 15.1 19B74
    • Chrome (web)      • chrome                                   • web-javascript • Google Chrome 96.0.4664.93

! Doctor found issues in 1 category.
```

</details>

**Comment by maheshmnj** [comment]
Hi @jeiea, Thanks for filing the issue. Can you please clarify how you are checking the user agent of the request after setting it?
> Check user agent of the second request.

 Thanks

**Comment by jeiea** [comment]
Server would definitely know the user agent value. It seems to hard to prove the user agent value in client, also with reproducible repository. Maybe separate server is necessary.

**Comment by maheshmnj** [comment]
I believe this is the same issue as this https://github.com/flutter/flutter/issues/67975, but for IOS.

**Comment by jeiea** [comment]
No, it's not same. That issue was raised 1 year before, but I faced this as recent  regression. My issue is specific to android, due to platform dependent code.

That issue says user agent was not set from the beginning, but in my case user agent was set, but it reset from the next build.

**Comment by stuartmorgan** [comment]
@bparrishMines Please take a look ASAP, since this a regression from the Dart rewrite.

**Comment by workbooks** [comment]
I have the same behaviour affecting our app.

**Comment by Hulkye** [comment]
I have the similar problem，set userAgent during initialization, but it is not passed to the web page, Until i retreat：
```
dependencies:
  webview_flutter: 2.3.0
dependency_overrides:
  webview_flutter_android: 2.2.1
  webview_flutter_platform_interface: 1.4.0
  webview_flutter_wkwebview: 2.4.0

problem solved， but it's not what I want

**Comment by parkindani** [comment]
I had same issue so I manually modified my local webview_flutter_android package:

/lib/webview_android_widget.dart
```
  Future<void> _setUserAgent(WebSetting<String?> userAgent) {
    if (userAgent.isPresent && userAgent.value != null) {
      return webView.settings.setUserAgentString(userAgent.value!);
    }
    // Commented below line
    // return webView.settings.setUserAgentString('');
    // Added this line
    return Future.value();
  }
```

I know this is just temporary fix, so please fix it as soon as possible.

**Comment by workbooks** [comment]
Hi there,

I just want to make sure you got the right support team? Are you meaning to CC in Workbooks Support?

Kind Regards,​
Chris Crawford
Customer Support Analyst
T:
+44(0) 118 3030 101
E:
***@***.***
W:
www.workbooks.com<https://www.workbooks.com/>
Unit 9, Suttons Business Park,
​Suttons Park Avenue
​Reading RG6 1AZ
***@***.***<https://www.linkedin.com/company/workbooks-com>
***@***.***<https://twitter.com/workbooks>
***@***.***<https://www.workbooks.com/>

**Comment by workbooks** [comment]
Hi there,

I just want to make sure you got the right support team? Are you meaning to CC in Workbooks Support?


Kind Regards,​
Chris Crawford
Customer Support Analyst
T:
+44(0) 118 3030 101
E:
***@***.***
W:
www.workbooks.com<https://www.workbooks.com/>
Unit 9, Suttons Business Park,
​Suttons Park Avenue
​Reading RG6 1AZ
***@***.***<https://www.linkedin.com/company/workbooks-com>
***@***.***<https://twitter.com/workbooks>
***@***.***<https://www.workbooks.com/>

**Comment by workbooks** [comment]
Thank you Workbooks for contacting the Workbooks Support Team.
 


Your request has been raised under reference CASE-81492.

 

Please quote the above reference in all correspondence relating to this case, ensuring this is located within the subject line of your email. If you have any additional information that will help our support team with their investigations, you can also reply to this email.

 

For a new request, please remove the above reference number from your email subject line.

 

We will be prioritising your request according to ourterms of service, which is also summarised below for your convenience. Providing any further information about the impact on your company will help our team to prioritise further.



 

Kind Regards,
Workbooks Support
+44 (0) 118 3030 101 |  +1 305 260 6448

Visit our Knowledge Base | Watch our Training Videos


Our working hours are between 09:00 and 17:30 (UK Time) weekdays, excluding Public Bank Holidays.




 

Workbooks Support: Case Priorities


	 
	
		
			(1) Critical
			
			A problem in which the customer's production Workbooks systems are down or not functioning, or where there is a major feature failure or production data loss or corruption, or where there is a security breach which exposes customer data to third-parties. 
			
			
			We respond to all such cases within one hour and we aim to resolve them as soon as possible but no later than within one day of the case being raised. 
			
		
		
			(2) Urgent
			
			A problem which seriously affects the customer's use of their production Workbooks system for necessary business-level operations such that the customer's business is significantly disrupted. A workaround may exist but it is inconvenient or impractical.
			
			
			We respond within two working hours and we aim to resolve the issue as soon as practicable but within two working days or as otherwise agreed between Workbooks and the customer.
			
		
		
			(3) Normal
			
			Medium-to-low business impact problem which causes partial non-critical functionality loss. A problem has been identified but the resolution is not critical to the service being provided. This kind of problem impairs some operations but allows the customer to continue to function.
			
			
			We respond within the same working day, or if the call is received outside of working hours we will respond within the next working day. We aim to resolve such cases at the time of response or as soon as practicable or as otherwise agreed between Workbooks and the customer.
			
		
		
			(4) Minor
			
			Minor impact. The customer has a minor loss of operational functionality caused by a minor feature or partial service failure. This may be a minor issue with limited loss or no loss of functionality or impact to the customer's operation or where there is an easy circumvention or avoidance by the end user: a convenient workaround exists.
			
			
			We respond to such cases within three working days. We aim to resolve such cases at the time of response or as soon as practicable or as otherwise agreed between Workbooks and the customer.
			
		
		
			(5) Low
			
			Includes general usage questions, recommendations for future service enhancements or modifications, or where the service functionality does not match documented specifications or the customer would benefit from a new feature. There is no impact on the quality or performance of the customer production system.
			
			
			We respond to such cases within five working days. We aim to resolve such cases at the time of response or as soon as practicable or as otherwise agreed between Workbooks and the customer.
			
		
	



 

 

 

 

Workbooks Online Limited (Company No. 06393851) is registered in England and Wales operating from Unit 9, Suttons Business Park, Suttons Park Avenue, Reading, Berkshire, RG6 1AZ.

**Comment by stuartmorgan** [comment]
@workbooks Do not subscribe to GitHub issues with an email address that has an auto-responder configured. It is extremely disruptive.
