### ISSUE TITLE
ignoreSSLErrors feature is needed in **WebView** plugin

### ISSUE THREAD

**Issue by LakshanFernando** [flutter/flutter#94855]
## Use case

Already I used **[flutter_webview_plugin](https://pub.dev/packages/flutter_webview_plugin)**. Now I am supposed to migrate to the **[WebView](https://pub.dev/packages/webview_flutter)** plugin because it was deprecated in future. When I migrate it I wanted to use **ignoreSSLErrors** but the **WebView** plugin was not provided with that kind of stuff to ignore SSL errors.  I think it is more useful if having a built-in function to that.  Thank you.

**Comment by darshankawar** [comment]
@LakshanFernando 
I believe your use case is same as https://github.com/flutter/flutter/issues/36925, so please follow-up in it for further updates.
Closing this as a duplicate.
