### ISSUE TITLE
[Web] App crashes with `Bad UTF-8 encoding found while decoding string` while attempting to convert `dart:html` file to `dart:io` file

### ISSUE THREAD

**Issue by junndobit** [flutter/flutter#94857]
First of all, I am using Flutter for Web. I was trying to get a file, specifically an image from `dart:html` `FileUploadInputElement`. After that, I intended to convert the image to base64 so that I can convert the `dart:html` file to dart:io file since I badly need a `dart:io file` for the AwsS3Plugin and not the `html` one. So this is my code:

```dart
InkWell(
                  child: Image.asset(
                    userProfilePicture.isNotEmpty
                        ? userProfilePicture
                        : 'assets/upload_image.png',
                    height: 200,
                    width: 200,
                  ),
                  onTap: () {
                    pickProfilePicture();
                  },
                ),
```

 Inside the `pickProfilePicture()`:

```dart
void pickProfilePicture() {
      html.FileUploadInputElement uploadInput = html.FileUploadInputElement();
      uploadInput.click();

      uploadInput.onChange.listen((event) {
        final files = uploadInput.files;
        if (files!.length == 1) {
          final file = files[0];
          html.FileReader reader = html.FileReader();
          reader.readAsDataUrl(file);

          reader.onLoad.first.then((res) {
            final encoded = reader.result as String;
            final imageBase64 = encoded.replaceFirst(
                RegExp(r'data:image/[^;]+;base64,'),
                ''); // this is to remove some non necessary stuff
            io.File itemPicIoFile =
                io.File.fromRawPath(base64Decode(imageBase64));
            uploadProfilePicture(itemPicIoFile).then((value) {
              print(value);
            });
          });        }
      });
    }
```
    
 Inside uploadProfilePicture(io.File file):
 
```dart
 Future<String> uploadProfilePicture(io.File selectedFile) async {
      String extension = 'png';
      String fileNameWithExtension = "$userId\\profile_pic.$extension";
      String result = "";

      AwsS3 awsS3 = AwsS3(
          file: selectedFile,
          fileNameWithExt: fileNameWithExtension,
          awsFolderPath: userImagesFolderPath,
          poolId: poolId,
          region: region,
          bucketName: bucketName);

      setState(() {
        isLoading = true;
      });

      try {
        result = await awsS3.uploadFile;
      } catch (e) {
        print(e.toString());
        setState(() {
          isLoading = false;
        });
      }
      return result;
    }
```

**Comment by danagbemava-nc** [comment]
Hi @junndobit, thanks for filing the issue. 

Please provide the full output of `flutter doctor -v`, `flutter run -v`, and a complete minimal reproducible code sample without any third-party libraries that we can use to verify this. 

Thank you

**Comment by junndobit** [comment]
Thank you. Here are the things that you requested that might help.

flutter doctor -v :
[√] Flutter (Channel stable, 2.5.2, on Microsoft Windows [Version 10.0.17134.1130], locale en-PH)
    • Flutter version 2.5.2 at D:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (10 weeks ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Dobit\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2020.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.1.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code, 64-bit edition (version 1.61.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.29.0

[√] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.45

• No issues found!

flutter run --no-sound-null-safety -v:        //I added the no sound null safety since the awss3 plugin won't run without it

[ +122 ms] executing: [D:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +149 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 3595343e20a61ff16d14e8ecc25f364276bb1b8b
[   +1 ms] executing: [D:\src\flutter/] git tag --points-at 3595343e20a61ff16d14e8ecc25f364276bb1b8b
[ +115 ms] Exit code 0 from: git tag --points-at 3595343e20a61ff16d14e8ecc25f364276bb1b8b
[   +1 ms] 2.5.2
[  +20 ms] executing: [D:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +89 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[        ] executing: [D:\src\flutter/] git ls-remote --get-url origin
[  +82 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +222 ms] executing: [D:\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +91 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +140 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +7 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +113 ms] executing: C:\Users\Dobit\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +76 ms] List of devices attached
[  +10 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +160 ms] Skipping pub get: version match.
[  +33 ms] Found plugin aws_s3 at
C:\Users\Dobit\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\aws_s3-0.1.1+hotfix.5\
[  +60 ms] Found plugin file_picker at
C:\Users\Dobit\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\file_picker-4.2.7\
[  +13 ms] Found plugin firebase_analytics at
C:\Users\Dobit\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_analytics-8.3.4\
[   +6 ms] Found plugin firebase_analytics_web at
C:\Users\Dobit\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_analytics_web-0.3.0+1\
[   +5 ms] Found plugin firebase_core at
C:\Users\Dobit\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_core-1.9.0\
[   +5 ms] Found plugin firebase_core_web at
C:\Users\Dobit\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_core_web-1.1.0\
[   +6 ms] Found plugin flutter_plugin_android_lifecycle at
C:\Users\Dobit\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-2.0.5\
[  +26 ms] Found plugin modal_progress_hud_nsn at
C:\Users\Dobit\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\modal_progress_hud_nsn-0.1.0-nullsafety-1\
[ +346 ms] Found plugin aws_s3 at
C:\Users\Dobit\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\aws_s3-0.1.1+hotfix.5\
[  +35 ms] Found plugin file_picker at
C:\Users\Dobit\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\file_picker-4.2.7\
[   +4 ms] Found plugin firebase_analytics at
C:\Users\Dobit\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_analytics-8.3.4\
[   +5 ms] Found plugin firebase_analytics_web at
C:\Users\Dobit\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_analytics_web-0.3.0+1\
[   +3 ms] Found plugin firebase_core at
C:\Users\Dobit\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_core-1.9.0\
[   +5 ms] Found plugin firebase_core_web at
C:\Users\Dobit\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_core_web-1.1.0\
[   +5 ms] Found plugin flutter_plugin_android_lifecycle at
C:\Users\Dobit\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-2.0.5\
[  +22 ms] Found plugin modal_progress_hud_nsn at
C:\Users\Dobit\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\modal_progress_hud_nsn-0.1.0-nullsafety-1\
[  +55 ms] Generating
D:\Flutter-Projects\mantifly-web-app\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +216 ms] Launching lib\main.dart on Chrome in debug mode...
[ +221 ms] Updating assets
[ +227 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more
information see #56466.
[  +11 ms] Waiting for connection from debug service on Chrome...
[  +14 ms] Found plugin aws_s3 at
C:\Users\Dobit\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\aws_s3-0.1.1+hotfix.5\
[  +20 ms] Found plugin file_picker at
C:\Users\Dobit\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\file_picker-4.2.7\
[   +2 ms] Found plugin firebase_analytics at
C:\Users\Dobit\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_analytics-8.3.4\
[   +3 ms] Found plugin firebase_analytics_web at
C:\Users\Dobit\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_analytics_web-0.3.0+1\
[   +3 ms] Found plugin firebase_core at
C:\Users\Dobit\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_core-1.9.0\
[   +3 ms] Found plugin firebase_core_web at
C:\Users\Dobit\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_core_web-1.1.0\
[   +3 ms] Found plugin flutter_plugin_android_lifecycle at
C:\Users\Dobit\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-2.0.5\
[  +12 ms] Found plugin modal_progress_hud_nsn at
C:\Users\Dobit\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\modal_progress_hud_nsn-0.1.0-nullsafety-1\
[  +40 ms] Found plugin aws_s3 at
C:\Users\Dobit\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\aws_s3-0.1.1+hotfix.5\
[  +22 ms] Found plugin file_picker at
C:\Users\Dobit\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\file_picker-4.2.7\
[   +2 ms] Found plugin firebase_analytics at
C:\Users\Dobit\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_analytics-8.3.4\
[   +2 ms] Found plugin firebase_analytics_web at
C:\Users\Dobit\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_analytics_web-0.3.0+1\
[   +1 ms] Found plugin firebase_core at
C:\Users\Dobit\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_core-1.9.0\
[   +2 ms] Found plugin firebase_core_web at
C:\Users\Dobit\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_core_web-1.1.0\
[   +6 ms] Found plugin flutter_plugin_android_lifecycle at
C:\Users\Dobit\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-2.0.5\
[  +12 ms] Found plugin modal_progress_hud_nsn at
C:\Users\Dobit\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\modal_progress_hud_nsn-0.1.0-nullsafety-1\
[ +180 ms] <- reset
[  +12 ms] D:\src\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
D:\src\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
D:\src\flutter\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names
--experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
C:\Users\Dobit\AppData\Local\Temp\flutter_tools.f6c147d5\flutter_tool.fe5892ef\app.dill --libraries-spec
file:///D:/src/flutter/bin/cache/flutter_web_sdk/libraries.json --packages
D:\Flutter-Projects\mantifly-web-app\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false
--enable-asserts --track-widget-creation --filesystem-root
C:\Users\Dobit\AppData\Local\Temp\flutter_tools.f6c147d5\flutter_tools.347a5406 --filesystem-scheme org-dartlang-app--initialize-from-dill build\c7922d95bf4a2462b75c84a97c312edb.cache.dill.track.dill --platform
file:///D:/src/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --no-sound-null-safety
[   +9 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+19012 ms] Waiting for connection from debug service on Chrome... (completed in 19.4s)
[   +2 ms] Synced 31.0MB.
[   +1 ms] <- accept
[   +1 ms] Caching compiled dill
[+12342 ms] [CHROME]:
[   +7 ms] [CHROME]:DevTools listening on ws://127.0.0.1:61569/devtools/browser/eef78df8-100f-42a5-b9a7-83f23be6a700[ +621 ms] DwdsInjector: Received request for entrypoint at http://localhost:61531/main_module.bootstrap.js
[   +9 ms] MetadataProvider: Loading debug metadata...
[  +22 ms] MetadataProvider: Loaded debug metadata (no sound null safety)
[  +14 ms] DwdsInjector: Injected debugging metadata for entrypoint at
http://localhost:61531/main_module.bootstrap.js
[+6048 ms] ChromeProxyService: Initializing expression compiler for main_module.bootstrap.js with sound null safety:false
[ +128 ms] DevHandler: Debug service listening on ws://127.0.0.1:61597/e-8kcIS8pOU=/ws

[  +38 ms] This app is linked to the debug service: ws://127.0.0.1:61597/e-8kcIS8pOU=/ws
[  +20 ms] Debug service listening on ws://127.0.0.1:61597/e-8kcIS8pOU=/ws
[   +1 ms] Running with unsound null safety
[   +1 ms] For more information see https://dart.dev/null-safety/unsound-null-safety
[   +5 ms]   To hot restart changes while running, press "r" or "R".
[   +2 ms] For a more detailed help message, press "h". To quit, press "q".
[   +3 ms] An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:61597/e-8kcIS8pOU=
[+1139 ms] DevTools activation throttled until 2021-12-09 04:11:53.340215.


Steps to reproduce:
1. Make a widget that has an onTap(), onPressed(), etc that can call a function. Example in my case:
'InkWell(
                  child: Image.asset(
                    "assets/upload_image.png",           //Insert any asset image there
                    height: 200,
                    width: 200,
                  ),
                  onTap: () {
                    pickProfilePicture();       //This is the function to get a file from the user
                  },
                ),'
 2. This is the important imports and the function:
 
'import 'dart:io' as io;
import 'dart:html' as html;

 void pickProfilePicture() {
      html.FileUploadInputElement uploadInput = html.FileUploadInputElement(); //lets the user pick a file. Use my kiki_cat.png 
                                                                                                                               //to probably get the same error
      uploadInput.click();

       //Listen to when the user has picked a file/files
      uploadInput.onChange.listen((event) {
        final files = uploadInput.files;        //Chosen file/files
        if (files!.length == 1) {
          final file = files[0];
          html.FileReader reader = html.FileReader();
          reader.readAsDataUrl(file);

          reader.onLoad.first.then((res) {
            final encoded = reader.result as String;
            final imageBase64 = encoded.replaceFirst(         //The output is of type UInt8List to be used in dart:io File.fromRawPath()
                RegExp(r'data:image/[^;]+;base64,'),
                ''); 
            io.File itemPicIoFile =
                io.File.fromRawPath(base64Decode(imageBase64));        //Make a dart:io File from the base64
            print(itemPicIoFile); //Print the dart:io File object and this will crash the web app and prints that Bad UTF-8 encoding 
                                            //error to the console/terminal
        }
      });
    }'
    
 3. Here is the sample image that I chose when the error happened
 
![kiki_cat](https://user-images.githubusercontent.com/20215990/145268819-605f8dbf-2a6f-44b1-bb58-a1e9b49552b1.png)

**Comment by junndobit** [comment]
Also, this is what the error will look like after crashing and displaying it in the Debug Console:
![image](https://user-images.githubusercontent.com/20215990/145271018-fa16665c-7565-4339-a6ba-ad609e4cc5e0.png)

P.S. Those problems are not red ones but of "prefer const with constant constructors" and my TODOs.

**Comment by danagbemava-nc** [comment]
Issue is reproducible on `stable` and `master`. 

## Steps to reproduce
1. Run the code sample below
2. Click the FAB
3. Select an image

<details>
<summary>complete sample</summary>

```dart
// ignore_for_file: avoid_web_libraries_in_flutter

import 'dart:convert';

import 'package:flutter/material.dart';
import 'dart:io' as io;
import 'dart:html' as html;

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  String? error;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$error',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          html.FileUploadInputElement input = html.FileUploadInputElement();

          input.click();

          input.onChange.listen((event) {
            final files = input.files;
            if (files?.length == 1) {
              final file = files![0];
              html.FileReader reader = html.FileReader();
              reader.readAsDataUrl(file);

              reader.onLoad.first.then((res) {
                final encoded = reader.result as String;
                final imageBase64 = encoded.split(',')[1];

                io.File itemPicToFile =
                    io.File.fromRawPath(base64Decode(imageBase64));

                print(itemPicToFile);
              });
            }
          });
        },
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

```
</details>

<details>
<summary>crash log</summary>

[crash_log.txt](https://github.com/flutter/flutter/files/7682944/crash_log.txt)


</details>

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.8.0, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.8.0 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (9 hours ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:318:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1428:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1863:10)
      #15     runZonedGuarded (dart:async/zone.dart:1851:12)
      #16     runZoned (dart:async/zone.dart:1782:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:197:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:301:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:53:47)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1290:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (4 available)
    • Nexus (mobile)     • 00008020-001875E83A38002E            • ios            • iOS 15.0.2 19A404
    • iPhone 13 (mobile) • 7515F01A-C1B6-456E-8559-8D2383D3719D • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 96.0.4664.93

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel master, 2.6.0-12.0.pre.975, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.6.0-12.0.pre.975 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9b1bbdbd16 (2 hours ago), 2021-12-09 00:04:07 -0500
    • Engine revision 30b0105c72
    • Dart version 2.16.0 (build 2.16.0-85.0.dev)
    • DevTools version 2.9.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:198:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:302:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (4 available)
    • Nexus (mobile)     • 00008020-001875E83A38002E            • ios            • iOS 15.0.2 19A404
    • iPhone 13 (mobile) • 7515F01A-C1B6-456E-8559-8D2383D3719D • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 96.0.4664.93

! Doctor found issues in 1 category.
```
</details>

**Comment by ditman** [comment]
Hey @junndobit, I'm afraid `dart:io` is not supported on the Web, so this code will never work as is.

Is `class AwsS3` coming from [`package:aws_s3`](https://pub.dev/packages/aws_s3)? If you look at their pub.dev page, you'll see that that plugin does **not** support web either.

We have a couple of file/image pickers that are cross-platform (they return a custom [`cross_file` type](https://pub.dev/packages/cross_file)), but in your case, the S3 client you use must support web (this seems to be [the most official one](https://github.com/aws-amplify/amplify-flutter/issues?q=is%3Aissue+is%3Aopen+label%3AStorage), but it seems to be mobile only).

**You may also want to give Firebase a shot,** it works great with both Flutter native **and web.** You may be able to replace S3 with Firebase Storage:

* https://firebase.google.com/docs/storage (official docs)
* https://pub.dev/packages/firebase_storage (flutter+web plugin)
  * Flutterfire (Firebase + Flutter) plugins homepage: https://firebase.flutter.dev
