### ISSUE TITLE
video_player can't play blob link on safari web, but js project can!

### ISSUE THREAD

**Issue by chenyifan88** [flutter/flutter#94867]
**video_player 2.2.7**
**this picture is flutter project：**
<img width="594" alt="截屏2021-12-09 上午12 21 08" src="https://user-images.githubusercontent.com/40348648/145245786-77f3d615-0c59-4a43-9233-e5fc30d910b5.png">
**this picture is js project：**
<img width="594" alt="截屏2021-12-09 上午12 21 08" src="https://user-images.githubusercontent.com/40348648/145245946-4964ae81-ca42-45f9-aa60-c8fe01455fbc.png">

because，my m3u8 file is a encryped file, so I need decrypt it first，then use this code to play：
`String decrypted = PlatformAwareCrypto.decryptM3U8(res.data);`
 `final _blob = html.Blob([decrypted], 'application/x-mpegURL');`
 `final _url = html.Url.createObjectUrlFromBlob(_blob);`
`initVideo(_url);`

but it's not working on safari!  Help me!
I found the User-agent is not same in two pictures, but two project runing on same computer!

**Comment by chenyifan88** [comment]
[Uploading videotest.zip…]()

**Comment by chenyifan88** [comment]
[main.dart.zip](https://github.com/flutter/flutter/files/7683466/main.dart.zip)

the zip is a minimal complete reproducible code sample...

flutter doctor -v:

✓] Flutter (Channel stable, 2.5.3, on Mac OS X 10.15.4 19E287 darwin-x64, locale zh-Hans-KH)
    • Flutter version 2.5.3 at /Users/mac/fvm/versions/2.5.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (8 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/mac/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ! CocoaPods 1.9.1 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

**Comment by chenyifan88** [comment]
> Thanks a lot

**Comment by chenyifan88** [comment]
@darshankawar 
thanks for your watch...

**Comment by darshankawar** [comment]
@chenyifan88 
Thanks for the details. `dio` is 3rd party. Can you try to remove that plugin and relevant code and check if you still get same behavior ?

**Comment by chenyifan88** [comment]
[main.dart.zip](https://github.com/flutter/flutter/files/7685276/main.dart.zip)

I have tried, not working so.... still that error

**Comment by darshankawar** [comment]
I am getting below errors while running your code:

```
Error: PlatformException(MEDIA_ERR_SRC_NOT_SUPPORTED, DEMUXER_ERROR_COULD_NOT_OPEN: FFmpegDemuxer: open context failed, The video has been found to be unsuitable (missing or in a format
not supported by your browser)., null)


The following LateError was thrown building MyHomePage(dirty, state: _MyHomePageState#0dd47):
LateInitializationError: Field '_controller' has not been initialized.
```

**Comment by chenyifan88** [comment]
Yes, the error happen when running code on chrome.  my report error happen in safari

**Comment by chenyifan88** [comment]
I dont't why objecturl is not working on video_player

**Comment by chenyifan88** [comment]
test on browser: safari

dart:
[main.dart.zip](https://github.com/flutter/flutter/files/7690757/main.dart.zip)

js(have to put on a static server):
[index.html.zip](https://github.com/flutter/flutter/files/7690760/index.html.zip)

two minimal complete reproducible code sample

js working, dart not working.

**Comment by darshankawar** [comment]
@chenyifan88 
Check [this](https://github.com/flutter/flutter/issues/83602) issue and underlying comments and see if it helps.

**Comment by chenyifan88** [comment]
Thank you so much, I solved this problem.
must modify "video_player_web-2.0.4/lib/video_player_web.dart"  row 183

original code:
<img width="290" alt="截屏2021-12-10 下午9 53 32" src="https://user-images.githubusercontent.com/40348648/145584739-58da4299-da3f-4abf-8421-87f558dd4b07.png">

my code:
<img width="350" alt="截屏2021-12-10 下午9 53 53" src="https://user-images.githubusercontent.com/40348648/145584813-e48a460d-3da3-4c4a-aaea-87f4162c931d.png">

just add a sourceElement for my case, working! Yeah!

**Comment by darshankawar** [comment]
Closing this as resolved based on above comment.
