### ISSUE TITLE
rollback to ci.yaml mac software for release testing

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#94872]
We recently updated the mac ios and mac android testbed software versions (macos, ios, xcode). And need to do some testing of today's release on older versions. Rollback the versions in .ci.yaml to accomodate the testbed.

**Comment by CaseyHillers** [comment]
This shouldn't be necessary from the ci.yaml as it's versioned by the repo. The underlying issue is there are no bots of that type in the prod pool due to the migration to MacOS 12.
