### ISSUE TITLE
DeviceLab test fails due to adb logcat hang/timeout

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#94877]
Some DeviceLab tests have been failing due to adb logcat timeout, which just hangs and causes test flakes (https://github.com/flutter/flutter/issues/94036).

Example builds: 
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android%20flutter_gallery__back_button_memory/908/overview
https://ci.chromium.org/ui/p/flutter/builders/staging/Linux_android%20flutter_gallery__back_button_memory/50/overview

```
[flutter_gallery__back_button_memory] [STDOUT] Executing: /opt/s/w/ir/cache/android/platform-tools/adb -s ZY223HK9P7 shell input keyevent KEYCODE_BACK in /opt/s/w/ir/x/w/recipe_cleanup/tmpwmdh9lq1/flutter sdk/dev/integration_tests/flutter_gallery with environment {BOT: true, LANG: en_US.UTF-8}
[flutter_gallery__back_button_memory] [STDOUT] adb logcat: 12-03 18:53:22.896  1477 21891 W ActivityManager: Ignoring remove of inactive process: ProcessRecord{21bc038 0:io.flutter.demo.gallery/u0a221}
[flutter_gallery__back_button_memory] [STDOUT] "/opt/s/w/ir/cache/android/platform-tools/adb" exit code: 0
[flutter_gallery__back_button_memory] [STDOUT] adb logcat: 12-03 18:53:36.031  1477  4101 I ActivityManager: Killing 21638:com.android.defcontainer/u0a24 (adj 906): empty #13
[flutter_gallery__back_button_memory] [STDOUT] adb logcat: 12-03 18:53:48.465  1477  1477 I ActivityManager: Killing 22112:com.android.keychain/1000 (adj 906): empty #13
```

Cleaning up all app caches in the device seems to solve the timeout. /cc @godofredoc 
A [reboot logic](https://github.com/flutter/flutter/blob/master/dev/devicelab/lib/framework/framework.dart#L225) is already there every 30 runs, and we need to clean up the cache before the reboot.

**Comment by keyonghan** [comment]
This also happens on mac/android: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_android%20complex_layout_scroll_perf__memory/3282/overview

**Comment by godofredoc** [comment]
Is this happening only on these two tests?

**Comment by keyonghan** [comment]
> Is this happening only on these two tests?

Screen top rows, only these two hit the adb timeout. Will append if any others.
BTW: this is the bug re timeout on `VMServiceFlutterDriver`: https://github.com/flutter/flutter/issues/94899

**Comment by godofredoc** [comment]
Closing as obsolete.
