### ISSUE TITLE
Unable to find bundled Java version

### ISSUE THREAD

**Issue by byron-ojua** [flutter/flutter#94887]
## Steps to Reproduce

I am trying to get Flutter working on 14" Macbook Pro with M1 chip. I have referenced Bugs #81909 and 76215, but still wasn't able to resolve the issue.

1. I am following installation from this video: https://www.youtube.com/watch?v=fzAg7lOWqVE 
2. I have Android Studio Preview installed (Android Studio Chipmunk | 2021.2.1 Canary 5) I was going to install Arctic Fox, but the download link wasn't working. Got 404 error. (https://developer.android.com/studio)
3. Ran flutter Doctor -v in terminal. See Logs section.
4. SDK platforms/tools in screenshots below.
<img width="986" alt="Screen Shot 2021-12-08 at 12 57 41 PM" src="https://user-images.githubusercontent.com/23112580/145283488-3ed638f9-2187-4ed5-a099-2117414f7496.png">
<img width="987" alt="Screen Shot 2021-12-08 at 12 59 33 PM" src="https://user-images.githubusercontent.com/23112580/145283624-df7434dc-36f4-4b26-89b1-258f9e987135.png">
5. Ran Java -version. See Logs.

## Logs

<details>
<summary>Logs</summary>

```

<!-- If possible, paste the output of running `flutter doctor -v` here. -->
Last login: Wed Dec  8 10:17:26 on ttys000
byronojua-nice@Byrons-MacBook-Pro ~ % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-arm, locale
    en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[!] Android Studio
    ✗ Unable to find bundled Java version.
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
byronojua-nice@Byrons-MacBook-Pro ~ % flutter doctor -v
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-arm, locale
    en-US)
    • Flutter version 2.5.3 at /opt/homebrew/Caskroom/flutter/2.5.3/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (8 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/byronojua-nice/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = /Users/byronojua-nice/Library/Android/sdk
    • Java binary at: /Library/Internet
      Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_311-b11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Users/byronojua-nice/Downloads/Android Studio
      Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.93

! Doctor found issues in 1 category.
byronojua-nice@Byrons-MacBook-Pro ~ % 
```

byronojua-nice@Byrons-MacBook-Pro ~ % java -version
java version "1.8.0_311"
Java(TM) SE Runtime Environment (build 1.8.0_311-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.311-b11, mixed mode)

</details>

**Comment by maheshmnj** [comment]
Hi @byron-ojua, Thanks for filing the issue. I believe this is the same issue as https://github.com/flutter/flutter/issues/85904 flutter tool is unable to find the Java version due to the Preview version of Android studio. Please use the stable version until this gets resolved.

**Comment by byron-ojua** [comment]
Hello @maheshmnj,
The android studio link is now working. Thank you, that was exactly the resolution I needed.  Nice and concise for any future readers. I will attach the logs below as well. Thank you and this can be closed!

### Logs
Downloading Dart SDK from Flutter engine 40a99c595137e4b2f5b2efa8ff343ea23c1e16b8...
** Resuming transfer from byte position 56086528
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  151M  100  151M    0     0  26.4M      0  0:00:05  0:00:05 --:--:-- 28.4M
Building flutter tool...
Flutter is already up to date on channel stable
Flutter 2.8.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision cf44000065 (26 hours ago) • 2021-12-08 14:06:50 -0800
Engine • revision 40a99c5951
Tools • Dart 2.15.0
byronojua-nice@Byrons-MBP ~ % flutter doctor
Downloading package sky_engine...                                  386ms
Downloading flutter_patched_sdk tools...                           208ms
Downloading flutter_patched_sdk_product tools...                   167ms
Downloading darwin-x64 tools...                                  1,245ms
Downloading ios-deploy...                                           33ms
Downloading darwin-x64/font-subset tools...                         70ms
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.0, on macOS 12.0.1 21A559 darwin-arm, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] Connected device (1 available)

• No issues found!
byronojua-nice@Byrons-MBP ~ % flutter doctor -v
[✓] Flutter (Channel stable, 2.8.0, on macOS 12.0.1 21A559 darwin-arm, locale en-US)
    • Flutter version 2.8.0 at /opt/homebrew/Caskroom/flutter/2.5.3/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (26 hours ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/byronojua-nice/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = /Users/byronojua-nice/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.93

• No issues found!
byronojua-nice@Byrons-MBP ~ %
