### ISSUE TITLE
Intermittent failure to connect to chrome tabs on test bots

### ISSUE THREAD

**Issue by annagrin** [flutter/flutter#94886]
Part of issues causing web_tool_tests bot failures. See parent issue: https://github.com/flutter/flutter/issues/93256

From build https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_tool_tests/4272/overview

```
01:36 +3 -1: test/web.shard/vm_service_web_test.dart: Clients of flutter run on web with DDS enabled can validate flutter version in parallel [E]                                                      
  Exception: Received app.stop event while waiting for app.started event
  
  [+1795 ms] FormatException: Unexpected character (at character 1)
         <html>
         ^

         #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1405:5)
         #1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1272:9)
         #2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:937:22)
         #3      _parseJson (dart:convert-patch/convert_patch.dart:40:10)
         #4      JsonDecoder.convert (dart:convert/json.dart:612:36)
         #5      JsonCodec.decode (dart:convert/json.dart:216:41)
         #6      jsonDecode (dart:convert/json.dart:155:10)
         #7      ChromeConnection.getTabs (package:webkit_inspection_protocol/webkit_inspection_protocol.dart:44:10)
         <asynchronous suspension>
         #8      ChromeConnection.getTab (package:webkit_inspection_protocol/webkit_inspection_protocol.dart:57:25)
         <asynchronous suspension>
         #9      ChromiumLauncher._connect (package:flutter_tools/src/web/chrome.dart:401:9)
         <asynchronous suspension>
         #10     ChromiumDevice.startApp (package:flutter_tools/src/web/web_device.dart:134:17)
         <asynchronous suspension>
         #11     ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:307:9)
         <asynchronous suspension>
         #12     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
         <asynchronous suspension>

  Unable to connect to Chrome debug port: 40881
```

**Comment by annagrin** [comment]
@christopherfujino @yjbanov would you be able to help with this? It seems that the `http://localhost:<chrome devtools port>/json` returns an html page instead of json. This is not related to dwds, could it be an issue in  chrome or flutter tools?

Note that this issue seem to cause about 1% flakiness in web_tool_tests bots.

**Comment by annagrin** [comment]
@christopherfujino assigning this to you per our chat.

**Comment by zanderso** [comment]
This was flagged again in https://github.com/flutter/flutter/issues/97526 on the same tests.

@annagrin @yjbanov @christopherfujino Please evaluate the value of this test and consider whether we should just delete it.

**Comment by keyonghan** [comment]
Bumping the priority to P1 considering high flaky percentage.

**Comment by keyonghan** [comment]
Another instance: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_tool_tests/4893/overview

**Comment by keyonghan** [comment]
Another one: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_tool_tests/5556/overview

**Comment by keyonghan** [comment]
Another two:
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_tool_tests/5869/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_tool_tests/6010/overview

**Comment by annagrin** [comment]
filed an issue https://github.com/google/webkit_inspection_protocol.dart/issues/85 to retry getting the tab list. Not sure why chrome sometimes returns an html page instead of json.

**Comment by annagrin** [comment]
Fix is in https://github.com/flutter/flutter/pull/104218
