### ISSUE TITLE
tester.dispatchEvent with pointers is confusing

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#949]
The api for tesitng with pointer events looks something like this:
```dart
Point start = new Point(...);
Point end = new Point(...);
tester.dispatchEvent(pointer.down(start), start);
tester.pump();
tester.dispatchEvent(pointer.move(end), start);
tester.pump();
tester.dispatchEvent(pointer.up(), start);
tester.pump();
```

The fact you need to pass your starting point for all of the events - especially after having moved the pointer - is weird.

**Comment by abarth** [comment]
Yeah, we should give you some sort of object that does that work for you.

**Comment by abarth** [comment]
Closing as a duplicate of #1855, which has a plan for a solution.
