### ISSUE TITLE
[in_app_purchase] Update README for the deprecated `InAppPurchaseAndroidPlatformAddition.enablePendingPurchases` method

### ISSUE THREAD

**Issue by dw2kim** [flutter/flutter#94909]
Relates to #93837

The ReadMe still displays the instruction to initialize with the deprecated `InAppPurchaseAndroidPlatformAddition.enablePendingPurchases` method.

We need to remove the instruction in the ReadMe.

**Comment by mvanbeusekom** [comment]
@stuartmorgan I noticed the issue and reviewed the PR @dw2kim created (flutter/plugin#4597).  There is on issue with the CLA @dw2kim  needs to resolve, otherwise it looks good to me.

**Comment by dw2kim** [comment]
@mvanbeusekom & @stuartmorgan Thank you for the feedback. The PR is merged now, I'm closing this issue 👍
