### ISSUE TITLE
Delta cannot be found by ScaleUpdateDetails after update 2.8  

### ISSUE THREAD

**Issue by jahnli** [flutter/flutter#94907]
## Steps to Reproduce
![QQ截图20211209113212](https://user-images.githubusercontent.com/20943608/145330739-2abb3d8c-880c-40d1-ad35-1bcbf5677edc.png)

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @jahnli, this change is intended. Kindly see https://github.com/flutter/flutter/pull/85718#discussion_r662581303 

You should use `focalPointDelta` instead. 

Closing as this is an intended change.
