### ISSUE TITLE
Add (commented-out) fields to default pubspec.yaml that are needed for publishing on pub

### ISSUE THREAD

**Issue by szakarias** [flutter/flutter#9490]
The `pubspec.yaml` in the plugin created by `flutter create --plugin` is missing some fields which are required in order to publish on pub.

When running `pub publish` the output contains:

Missing requirements:
* Your pubspec.yaml must have an "author" or "authors" field.
* Your pubspec.yaml is missing a "description" field.
* Your pubspec.yaml is missing a "homepage" field.
* Your pubspec.yaml is missing a "version" field.

**Comment by Hixie** [comment]
What values should we put in, though?

I think it might be better for us to omit them (as we do today), than for us to put them in with default values that then get uploaded to the server.

**Comment by szakarias** [comment]
Good point. For the "description" field we actually already have a default value that should be changed. And we also have default values for other things so I guess the risk of uploading these is already there. For the `pubspec.yaml` we could maybe consider adding the required fields with default values and then comment them out. This way it's easy to see what is needed when you're already editing the file.

**Comment by Hixie** [comment]
Ah yes, having them commented out is a good idea. We should probably comment out the description too.

**Comment by mit-mit** [comment]
Fixed earlier in https://github.com/flutter/flutter/pull/10548
