### ISSUE TITLE
i am confused how to appoint the version of flutter module?

### ISSUE THREAD

**Issue by zk184174875** [flutter/flutter#94905]
i use flutter as a module in my android app by package the flutter module as aar.
i used flutter version 1.17.5 before and i get the dependence below and it works fine.
![image](https://user-images.githubusercontent.com/14051598/145326221-e900dd88-05b3-4520-a799-38fbf45888bd.png)
recently i want to update my flutter version into 2.5.3 ,everything is fine expect the dependence is not correct.it stilly get dependence as same as flutter version 1.17.5. and i got an error below
![image](https://user-images.githubusercontent.com/14051598/145327185-a81c2b46-4980-45da-a7fa-1011d0b593b2.png)

so i have to pull the dependence manually and it works.
![image](https://user-images.githubusercontent.com/14051598/145326871-16dec156-6f57-4bd3-936b-65b569e5bd9e.png)
i know it have to be the exactly the engine version matched.
![image](https://user-images.githubusercontent.com/14051598/145327466-b95eefe7-14b7-4a0b-9ce4-bedd82fe1deb.png)
but i am confused how to configure my flutter module to lead my android app get the correct version of flutter dependence?
hope to get an answer sooner .
thanks.

**Comment by darshankawar** [comment]
@zk184174875 
Please go through the official [documentation](https://docs.flutter.dev/development/add-to-app/android/project-setup) and see if it helps to answer your question.

**Comment by darshankawar** [comment]
What exactly is the issue you are facing ? Please don't post screenshots. Maybe steps that leads to the behavior you are seeing along with description.

**Comment by zk184174875** [comment]
> What exactly is the issue you are facing ? Please don't post screenshots. Maybe steps that leads to the behavior you are seeing along with description.

how to configure my flutter module to lead my android app get the correct version of flutter dependence?

**Comment by darshankawar** [comment]
@zk184174875 
in your android app, if you run ./gradlew sync, it should be able to fetch in / get current / correct version. Can you try that and see if it helps ?
