### ISSUE TITLE
Flutter 2.8: Icons SIX_FT_APART* renamed to SIX__FT_APART*?

### ISSUE THREAD

**Issue by boldt** [flutter/flutter#94918]
I realized, that four icons where renamed in Flutter 2.8:

* `SIX_FT_APART` --> `SIX__FT_APART `
* `SIX_FT_APART_SHARP` --> `SIX__FT_APART_SHARP` 
* `SIX_FT_APART_ROUNDED`  --> `SIX__FT_APART_ROUNDED `
* `SIX_FT_APART_OUTLINED` -->` SIX__FT_APART_OUTLINED `

They have a double low line (`__`) between `SIX` and `FT` now. 
What's the reason? Is that intended? If not, it should be reverted.

**Comment by danagbemava-nc** [comment]
Closing in favor of https://github.com/flutter/flutter/issues/94894. It appears to affect more than just the `six_ft_apart` icons as per https://github.com/flutter/flutter/issues/94894#issuecomment-989654131.
