### ISSUE TITLE
How can this error be fixed? url_launcher

### ISSUE THREAD

**Issue by majidpourdavood** [flutter/flutter#94926]
A problem occurred configuring project ':url_launcher_android'.
> Could not resolve all artifacts for configuration ':url_launcher_android:classpath'.
   > Could not find builder-3.4.2.jar (com.android.tools.build:builder:3.4.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/3.4.2/builder-3.4.2.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 23s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by maheshmnj** [comment]
Hi @majidpourdavood, Thanks for filing the issue. Please share output of `flutter doctor -v` and `flutter run -v`.

Thanks
