### ISSUE TITLE
Luci customer testing build has silent errors

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#94949]
Build:
https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20customer_testing/25595/overview
StdErr:
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8828331587598063249/+/u/Customer_testing/customer_testing/test_stderr

It looks like the customer test does not use `master` as a branch name, it is likely `main`.

Noticed while looking into https://github.com/flutter/flutter/issues/94948 that the Luci stderr had an exception.  It may be the root cause of https://github.com/flutter/flutter/issues/94948 if it is crashing and never executes the other tests.

Unfortunately, this does not fail the build, it passed. 😢  

```
Unhandled exception:
ProcessException: fatal: bad revision 'master'

  Command: git log --format=%H %cI master --
#0      git (file:///b/s/w/ir/x/w/flutter%20sdk/dev/tools/bin/find_commit.dart:78:5)
#1      findCommit (file:///b/s/w/ir/x/w/flutter%20sdk/dev/tools/bin/find_commit.dart:51:56)
#2      main (file:///b/s/w/ir/x/w/flutter%20sdk/dev/tools/bin/find_commit.dart:95:11)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
+ git -C ../../bin/cache/pkg/tests checkout
+ dart --enable-asserts run_tests.dart --skip-on-fetch-failure --skip-template ../../bin/cache/pkg/tests/registry/assorted_layout_widgets.test ../../bin/cache/pkg/tests/registry/DanTup_tiler.test ../../bin/cache/pkg/tests/registry/flutter_gallery.test ../../bin/cache/pkg/tests/registry/flutter_packages.test ../../bin/cache/pkg/tests/registry/flutter_reactive_ble.test ../../bin/cache/pkg/tests/registry/flutter_svg.test ../../bin/cache/pkg/tests/registry/provider.test ../../bin/cache/pkg/tests/registry/rainbowmonkey.test ../../bin/cache/pkg/tests/registry/template.test
```

**Comment by godofredoc** [comment]
Fixes:
https://flutter-review.googlesource.com/c/recipes/+/25660
https://flutter-review.googlesource.com/c/recipes/+/25080
