### ISSUE TITLE
Cirrus and Luci customer testing shards are different

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#94948]
Noticed in https://github.com/flutter/flutter/pull/92906 that 
- the Cirrus customer testing shard was failing ❌ , 
- but the Luci testing shard was passing ✅ .

I thought maybe the Cirrus shard was flaky, so I re-ran it, but it failed consistently.

Cirrus build: https://cirrus-ci.com/task/4572007045005312
Luci build: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20customer_testing/25595/overview

It looks like the Luci shard is not running as many tests as the Cirrus shard based on the stdout. There is an error in the Luci build though that may be the cause, filed https://github.com/flutter/flutter/issues/94949 in case it is separate.

**Comment by godofredoc** [comment]
Fixes:
https://flutter-review.googlesource.com/c/recipes/+/25660
https://flutter-review.googlesource.com/c/recipes/+/25080
