### ISSUE TITLE
Add an API to the scheduler to return the list of expected tasks for a given PR

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#94958]
We currently use filters to determine which tests will be running on presubmit depending on the paths that the PR touched. This makes the list of tests running on PRs variable.

The autosubmit bot needs to validate all the expected tests were run before attempting to land the PR in order to remove an injected latency of 1 hour to ensure that all the expected tasks were added to github.

As calculating the # of tests depend on the files of the pr and the logic in .ci.yaml is very costly to calculate in the autosubmit bot. Instead we can save the list of tests when calculated by the scheduler and then exposing an API for the autosubmit bot to call when deciding whether to land the PR or not.

**Comment by godofredoc** [comment]
\cc @Hixie @CaseyHillers

**Comment by CaseyHillers** [comment]
Cocoon's Scheduler has `getPresubmitTargets` which already does this - https://cs.opensource.google/flutter/cocoon/+/main:app_dart/lib/src/service/scheduler.dart;l=344;drc=c8313beb8aae656bc652ed061dc217a7ff9c15d8

Is this a request for an RPC to get this information?

**Comment by godofredoc** [comment]
The idea is to calculate this once per PR+commit and saving to the scheduler internal DB in a way that we can avoid too many requests to github APIs.

I was thinking more as an HTTP API but if RPC calls are allowed from different AppEngine instances that will also work. The bot in the future will be running on its own service within the same project (for flutter/dart) but if this is useful for some other teams we may want to deploy to different instances.

**Comment by godofredoc** [comment]
We'll need to revisit this when making the autosubmit bot generic for Dart & Flutter

**Comment by CaseyHillers** [comment]
Is this still needed? `ci.yaml validation` is intended to make sure everything for flutter-dashboard is adding to the GitHub checks.

**Comment by godofredoc** [comment]
Closing as obsolete.
