### ISSUE TITLE
Update Flutter tool to handle people currently on the dev channel to auto migrate/guide them onto another channel

### ISSUE THREAD

**Issue by khyati82** [flutter/flutter#94967]
This issue is related to removing dev channel from Flutter builds. This is updating the flutter tool to handle people currently on the dev channel to auto migrate/guide them onto another channel.

The work for removing dev channel is tracked as part of this master issue - #94962

**Comment by christopherfujino** [comment]
Fixing this involves restoring this code: https://github.com/flutter/flutter/commit/0b882698073d228a255aacb20a9084ae412838fc#diff-092e00109d9e1589fbc7c6de750e29a6ae512b2dd44e85d60028953561201605
