### ISSUE TITLE
Update wiki to reflect current customer promises

### ISSUE THREAD

**Issue by khyati82** [flutter/flutter#94969]
This issue is related to removing dev channel from Flutter builds. Update Flutter wiki to reflect right customer promises

The work for removing dev channel is tracked as part of this master issue - #94962

**Comment by Hixie** [comment]
I guess this is about just removing mention of the dev channel?

**Comment by khyati82** [comment]
Flutter dev and wiki updated with dev deprecation note

**Comment by Hixie** [comment]
I hope you don't mind, I edited some of the pages to more closely match the usual Flutter voice and to make more sense in the future (we often forget to update the wiki so it's usually best to write it as we want it to read 6 months later).
