### ISSUE TITLE
Remove dev channel from Flutter builds

### ISSUE THREAD

**Issue by khyati82** [flutter/flutter#94962]
This issue tracks all the action items required for removing dev channel from Flutter builds. The entire premise of the discussion (why and what) has been documented here for additional context.

# Implementation Tasks
- [x]  #94967
- [x]  #94969
- [x]  #94970
- [x] #94971
- [x] #94973
- [x] #94974. This bug is mirrored in dartpad repo to track backend work - [#2111](https://github.com/dart-lang/dart-pad/issues/2111)
- [x] #96428
- [x] [**Remove dev channel mention on website**](https://github.com/flutter/website/issues/6656)

**Comment by timsneath** [comment]
@khyati82 Another item to add to this list is that we should remove the `dev` channel from presubmit tests on the website (and anywhere else). See, for example, https://github.com/flutter/website/runs/4767648310?check_suite_focus=true
