### ISSUE TITLE
Remove dev channel support from DartPad

### ISSUE THREAD

**Issue by khyati82** [flutter/flutter#94974]
This issue is related to removing dev channel from Flutter builds. Remove dev channel from DartPad

The work for removing dev channel is tracked as part of this master issue - #94962

**Comment by domesticmouse** [comment]
DartPad (the front end) has already removed `dev` as an option before shipping the feature. I'm keeping `dev` as a backend option as we are thinking about exposing the version that google3 is currently running with as a replacement for `dev`.

This bug probably should be moved to, or at least mirrored in, the [DartPad issue tracker](https://github.com/dart-lang/dart-pad/issues).

**Comment by maheshmnj** [comment]
@khyati82, Should this be closed since this is being tracked here https://github.com/dart-lang/dart-pad/issues/2111?
