### ISSUE TITLE
[in_app_purchase] not updated README for 2.0.0

### ISSUE THREAD

**Issue by erperejildo** [flutter/flutter#94977]
I've moved from 1.0.9 to 2.0.0 (next version) and many breaking changes were introduced. In changelog (https://pub.dev/packages/in_app_purchase/changelog) I read this:

> Deprecates the InAppPurchaseAndroidPlatformAddition.enablePendingPurchases()
but in README (https://pub.dev/packages/in_app_purchase) we have this:
```
if (defaultTargetPlatform == TargetPlatform.android) {
    InAppPurchaseAndroidPlatformAddition.enablePendingPurchases();
  }
```

Also it became extremely complex to be integrated now with so many files when I only needed this before:
```
class PaymentQueueDelegate implements SKPaymentQueueDelegateWrapper {
  @override
  bool shouldContinueTransaction(
      SKPaymentTransactionWrapper transaction, SKStorefrontWrapper storefront) {
    return true;
  }

  @override
  bool shouldShowPriceConsent() {
    return false;
  }
}
```

I only have a paid version and a subscription.

---------

Also wanted to mentioned that I find these issues related to documentation quite often for important packages like this one or for `google_mobile_ads`:
https://github.com/googleads/googleads-mobile-flutter/issues/461
https://github.com/flutter/flutter/issues/93316#issuecomment-974014239
https://github.com/flutter/flutter/issues/89950

Changes on these 2 can modify earnings and cause bad reviews from users if that affects their accounts.

**Comment by stuartmorgan** [comment]
There was already a PR to fix this, it's just going through review: https://github.com/flutter/plugins/pull/4597

> Also wanted to mentioned that I find these issues related to documentation quite often for important packages like this one

Please continue to provide feedback (or PRs) when you do; that's how things get fixed.

> or for `google_mobile_ads`: [googleads/googleads-mobile-flutter#461](https://github.com/googleads/googleads-mobile-flutter/issues/461) [#93316 (comment)](https://github.com/flutter/flutter/issues/93316#issuecomment-974014239)

I'm not sure of the relevance here; the Flutter team doesn't control the documentation for plugins that aren't part of the Flutter project.

> Changes on these 2 can modify earnings and cause bad reviews from users if that affects their accounts.

Calling this deprecated method is a no-op, and cannot affect earnings or user experience.

**Comment by erperejildo** [comment]
> There was already a PR to fix this, it's just going through review: [flutter/plugins#4597](https://github.com/flutter/plugins/pull/4597)

But why are not documentation and code changes merged together? 2.0.0 was released 8 days ago.

> I'm not sure of the relevance here; the Flutter team doesn't control the documentation for plugins that aren't part of the Flutter project.

I'm talking about this one: https://pub.dev/packages/google_mobile_ads
<img width="110" alt="Screenshot 2021-12-10 at 10 55 41" src="https://user-images.githubusercontent.com/5629919/145554885-bed4d740-3198-42db-ac13-74436716ce09.png">
https://youtu.be/m0d_pbgeeG8?t=493

Not sure why is that on a different repo though.

> Calling this deprecated method is a no-op, and cannot affect earnings or user experience.

I was referring more about the documentation not reflecting the exact changes we have to make. For this example I shared https://github.com/flutter/flutter/issues/89950 I didn't know that part was failing. Definitely my fault because I didn't test it properly again after update it, but when reading the docs I didn't think I had to. So if that creates problems with purchases I can either have or bad reviews (if the user made a purchase and he's not retrieving a paid version) or less earnings (if he cannot make purchases).

**Comment by stuartmorgan** [comment]
> > There was already a PR to fix this, it's just going through review: [flutter/plugins#4597](https://github.com/flutter/plugins/pull/4597)
> 
> But why are not documentation and code changes merged together? 2.0.0 was released 8 days ago.

Because updating documentation is a manual process, and mistakes can happen.

> > I'm not sure of the relevance here; the Flutter team doesn't control the documentation for plugins that aren't part of the Flutter project.
> 
> I'm talking about this one: https://pub.dev/packages/google_mobile_ads <img alt="Screenshot 2021-12-10 at 10 55 41" width="110" src="https://user-images.githubusercontent.com/5629919/145554885-bed4d740-3198-42db-ac13-74436716ce09.png"> https://youtu.be/m0d_pbgeeG8?t=493

I'm not sure where the screenshot you've included is from, but it's not that package. `flutter.dev` is not the publisher of `google_mobile_ads`.

> Not sure why is that on a different repo though.

Because it's not part of the Flutter project.

**Comment by erperejildo** [comment]
> Because updating documentation is a manual process, and mistakes can happen.

Oh yeah, I totally understand that, but so do the code. What I mean is why not merging both together, code and info? (not sure if the process has to be like that for some reasons tbh)

> I'm not sure where the screenshot you've included is from, but it's not that package. `flutter.dev` is not the publisher of `google_mobile_ads`.

Hmm... maybe I had some other package open and took it from there, you're right, it's from google.dev, not flutter.dev (didn't notice this difference until now).

Just curious, what's the difference here? I thought all packages for Flutter made by Google were from flutter.dev.
Because, at least to me, ads and purchases are quite connected to each other being both the only ways to make money from our apps, and here there is a different team (I guess) supporting the other package.

Don't want to go too off-topic specially if that belongs to other team, but since this was related to README/documentation I wanted to mention that I find myself sometimes a bit lost trying to follow best approaches. `admob_firebase` deprecated by `google_mobile_ads`, Admob, mediation, AdSense, AdManager (which we can be also used now in that package), native or banners... The documentation changes too much between all of these and I can understand that some devs move to 3rd party companies to show their ads (which also translates to less profit for Google). Where is the best place to get support from all of this?

Normally Google/Flutter's packages are the most documented ones but also the most complicated one to setup properly. Is there any common place where we can gather all of this and try to put questions together?

More examples:
https://github.com/googleads/googleads-mobile-flutter/issues/461#issuecomment-989307070
https://github.com/googleads/googleads-mobile-flutter/issues/463

**Comment by stuartmorgan** [comment]
> > Because updating documentation is a manual process, and mistakes can happen.
> 
> Oh yeah, I totally understand that, but so do the code. What I mean is why not merging both together, code and info?

Because we forgot the README needed to be updated for that change. Again, mistakes happen. I'm not sure what more you are looking for here.

> I thought all packages for Flutter made by Google were from flutter.dev.

No, only packages maintained by the Flutter project are published by flutter.dev.

> Because, at least to me, ads and purchases are quite connected to each other

The team responsible for Google Mobile Ads is not involved with Apple Pay (unsurprisingly) or Google Play, which are the SDKs wrapped by in_app_purchase.

> `google_mobile_ads`, Admob, mediation, AdSense, AdManager (which we can be also used now in that package), native or banners... [...] Where is the best place to get support from all of this?

I can't advise you on the best place to get support on things that aren't part of the Flutter project.
