### ISSUE TITLE
Update recommendations for people who want to know which master build passed our tests

### ISSUE THREAD

**Issue by khyati82** [flutter/flutter#94971]
This issue is related to removing dev channel from Flutter builds. Update recommendations for people who want to know which master build passed our tests

The work for removing dev channel is tracked as part of this master issue - #94962

**Comment by Hixie** [comment]
So... what should we be recommending here? I don't really know of a good way to quickly pick a commit we know has passed all the tests (including google3 tests).

**Comment by khyati82** [comment]
We should just recommend to use master branch. We can build more confidence if we say that Google also uses master. branch.

**Comment by Hixie** [comment]
Google doesn't use the master branch. Google uses the dev branch, or what used to become the dev branch.

**Comment by khyati82** [comment]
I mean to say that they use the tip of the tree

**Comment by Hixie** [comment]
I don't think that's a recommendation that can work though. If we tell people just to "use master", they'll often find that things don't work, because our tree is not always green, and in particular, our tree often has regressions that are then caught when we try to roll the framework into Google. That was the whole point of having the dev branch.

**Comment by Hixie** [comment]
To clarify, I'm not saying you need to answer the question of what we should be recommending here, it was more of an open question. :-)

@eseidel Do you have a suggestion for what we should recommend fer people who want to know which master builds have passed all our tests? (meaning, including google3 tests, so just looking at the dashboard isn't enough)

**Comment by Hixie** [comment]
I've updated the channels page on our wiki to say to use beta instead.
