### ISSUE TITLE
Run user timing analytic should measure time to connect

### ISSUE THREAD

**Issue by xster** [flutter/flutter#9498]
The `flutter run` user timing currently measures the duration of the entire resident session which isn't very interesting. Measure time to execution instead of entire connection duration.

**Comment by sethladd** [comment]
Are we measuring/analyzing host machine characteristics? CPU/RAM/etc ? Those would be a factor to understanding build times on host machines.

Also, do you mean "run --release" or ... ? Which phases of the run, and for dev|profile|release ?

**Comment by xster** [comment]
Good idea, let's add all of these, run type, machine characteristics, success/fail

**Comment by xster** [comment]
#9501, #9500, #9499

**Comment by xster** [comment]
There's a generic mechanism to gather data for all commands is flutter_command. We should just have the abstract runCommand return a Future<CommandResult> instead of Future<Null>.
