### ISSUE TITLE
Flutter create command error message Could not find a file named "pubspec.yaml" in "C:\Users\<username>\Desktop\flutter\apptest". 

### ISSUE THREAD

**Issue by justbriang** [flutter/flutter#94985]
## Steps to Reproduce

This is happening on a windows pc
1. Open terminal and type flutter create <appname>

## Logs
![image](https://user-images.githubusercontent.com/42893623/145514063-7cfb72fc-cc10-45e9-b761-081f42ef0468.png)

<details>
<summary> $ flutter --verbose create foo </summary>

```

[ +113 ms] executing: [C:\flutter_root\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +636 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] cf4400006550b70f28e4b4af815151d1e74846c6
[   +1 ms] executing: [C:\flutter_root\flutter/] git tag --points-at cf4400006550b70f28e4b4af815151d1e74846c6
[  +43 ms] Exit code 0 from: git tag --points-at cf4400006550b70f28e4b4af815151d1e74846c6
[        ] 2.8.0
[  +31 ms] executing: [C:\flutter_root\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +30 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter_root\flutter/] git ls-remote --get-url origin
[  +19 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +136 ms] executing: [C:\flutter_root\flutter/] git rev-parse --abbrev-ref HEAD
[  +23 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +97 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +8 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.   
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.     
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.     
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +89 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[ +103 ms] Creating project foo...
[ +130 ms] Running "flutter pub get" in foo...
[   +8 ms] Using C:\flutter_root\flutter\.pub-cache for the pub cache.
[   +2 ms] executing: [C:\Users\judtbriang\Desktop\Mapps\foo/] C:\flutter_root\flutter\bin\cache\dart-sdk\bin\dart __deprecated_pub
--verbose get --no-precompile
[ +174 ms] FINE: Pub 2.15.0
[  +54 ms] ERR : Could not find a file named "pubspec.yaml" in "C:\Users\judtbriang\Desktop\Mapps\foo".
[   +1 ms] FINE: Exception type: FileException
[  +96 ms] FINE: package:pub/src/pubspec.dart 288:7                               new Pubspec.load
[   +1 ms]     | package:pub/src/package.dart 149:27                              new Package.load
[        ]     | package:pub/src/entrypoint.dart 177:24                           new Entrypoint
[        ]     | package:pub/src/command.dart 72:38                               PubCommand.entrypoint
[        ]     | package:pub/src/command.dart                                     PubCommand.entrypoint
[        ]     | package:pub/src/command/get.dart 52:11                           GetCommand.runProtected
[        ]     | package:pub/src/command.dart 180:45                              PubCommand.run.<fn>
[        ]     | package:pub/src/command.dart 180:33                              PubCommand.run.<fn>
[        ]     | dart:async                                                       new Future.sync
[        ]     | package:pub/src/utils.dart 109:12                                captureErrors.wrappedCallback
[        ]     | package:stack_trace                                              Chain.capture
[   +1 ms]     | package:pub/src/utils.dart 122:11                                captureErrors
[        ]     | package:pub/src/command.dart 180:13                              PubCommand.run
[        ]     | package:args/command_runner.dart 209:27                          CommandRunner.runCommand
[        ]     | package:pub/src/command_runner.dart 173:24                       PubCommandRunner.runCommand
[        ]     | package:pub/src/command_runner.dart 158:20                       PubCommandRunner.run
[        ]     | package:dartdev/dartdev.dart 45:56                               runDartdev
[        ]     | C:\b\s\w\ir\cache\builder\sdk\pkg\dartdev\bin\dartdev.dart 11:9  main
[        ]     | ===== asynchronous gap ===========================
[        ]     | dart:async                                                       Future.catchError
[        ]     | package:pub/src/utils.dart 109:52                                captureErrors.wrappedCallback
[        ]     | package:stack_trace                                              Chain.capture
[        ]     | package:pub/src/utils.dart 122:11                                captureErrors
[        ]     | package:pub/src/command.dart 180:13                              PubCommand.run
[        ]     | package:args/command_runner.dart 209:27                          CommandRunner.runCommand
[        ]     | package:pub/src/command_runner.dart 173:24                       PubCommandRunner.runCommand
[        ]     | package:pub/src/command_runner.dart 158:20                       PubCommandRunner.run
[        ]     | package:dartdev/dartdev.dart 45:56                               runDartdev
[        ]     | C:\b\s\w\ir\cache\builder\sdk\pkg\dartdev\bin\dartdev.dart 11:9  main
[  +54 ms] Running "flutter pub get" in foo... (completed in 396ms)
[   +1 ms] "flutter create" took 806ms.
[   +8 ms] pub get failed (66;     | C:\b\s\w\ir\cache\builder\sdk\pkg\dartdev\bin\dartdev.dart 11:9  main)
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _DefaultPub.batch (package:flutter_tools/src/dart/pub.dart:373:7)
           <asynchronous suspension>
           #2      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:254:7)
           <asynchronous suspension>
           #3      CreateBase.generateApp (package:flutter_tools/src/commands/create_base.dart:459:7)
           <asynchronous suspension>
           #4      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:292:31)
           <asynchronous suspension>
           #5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #13     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>


[ +274 ms] ensureAnalyticsSent: 266ms
[   +4 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +1 ms] exiting with code 66

<!-- If possible, paste the output of running `flutter doctor -v` here. -->
Flutter doctor -v
![image](https://user-images.githubusercontent.com/42893623/145514351-39237103-c8cf-4895-9c8e-64f7f666b965.png)


```
</details>

 . Yet I am able to fluttter run my already existing app

**Comment by darshankawar** [comment]
@justbriang 
I ran `flutter create apptest` using latest stable on Windows 10 machine which created the app folder properly without any issues.
From your screenshot, it shows it's `recreating project apptest...`.  whereas if you are trying to create a brand new flutter project, it should show `...creating project...`
Are you trying to run the command inside of an existing folder ?
Can you provide the project structure ?

**Comment by justbriang** [comment]
No I am trying the command for a fresh project. The screenshot was on my second try, with the command having already failed.

below is another try for a completely fresh app

![image](https://user-images.githubusercontent.com/42893623/145633920-0c4a9e26-2fab-4186-9e56-fdb71de85c5f.png)


Print out of the terminal logs

flutter create --verbose apptestflutter
[ +114 ms] executing: [C:\flutter_root\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +651 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] cf4400006550b70f28e4b4af815151d1e74846c6
[   +1 ms] executing: [C:\flutter_root\flutter/] git tag --points-at cf4400006550b70f28e4b4af815151d1e74846c6
[  +59 ms] Exit code 0 from: git tag --points-at cf4400006550b70f28e4b4af815151d1e74846c6
[        ] 2.8.0
[  +12 ms] executing: [C:\flutter_root\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +48 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter_root\flutter/] git ls-remote --get-url origin
[  +38 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +153 ms] executing: [C:\flutter_root\flutter/] git rev-parse --abbrev-ref HEAD
[  +46 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +156 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +9 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +314 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +95 ms] Creating project apptestflutter...
[ +566 ms] Running "flutter pub get" in apptestflutter...
[   +9 ms] Using C:\flutter_root\flutter\.pub-cache for the pub cache.
[   +2 ms] executing: [C:\Users\judtbriang\Desktop\flutter\apptestflutter/]
C:\flutter_root\flutter\bin\cache\dart-sdk\bin\dart __deprecated_pub --verbose get --no-precompile
[ +730 ms] FINE: Pub 2.15.0
[  +49 ms] ERR : Could not find a file named "pubspec.yaml" in "C:\Users\judtbriang\Desktop\flutter\apptestflutter".
[   +2 ms] FINE: Exception type: FileException
[  +37 ms] FINE: package:pub/src/pubspec.dart 288:7                               new Pubspec.load
[   +2 ms]     | package:pub/src/package.dart 149:27                              new Package.load
[   +7 ms]     | package:pub/src/entrypoint.dart 177:24                           new Entrypoint
[   +1 ms]     | package:pub/src/command.dart 72:38                               PubCommand.entrypoint
[   +1 ms]     | package:pub/src/command.dart                                     PubCommand.entrypoint
[   +1 ms]     | package:pub/src/command/get.dart 52:11                           GetCommand.runProtected
[   +2 ms]     | package:pub/src/command.dart 180:45                              PubCommand.run.<fn>
[   +1 ms]     | package:pub/src/command.dart 180:33                              PubCommand.run.<fn>
[        ]     | dart:async                                                       new Future.sync
[   +4 ms]     | package:pub/src/utils.dart 109:12                                captureErrors.wrappedCallback
[        ]     | package:stack_trace                                              Chain.capture
[        ]     | package:pub/src/utils.dart 122:11                                captureErrors
[        ]     | package:pub/src/command.dart 180:13                              PubCommand.run
[        ]     | package:args/command_runner.dart 209:27                          CommandRunner.runCommand
[        ]     | package:pub/src/command_runner.dart 173:24                       PubCommandRunner.runCommand
[   +3 ms]     | package:pub/src/command_runner.dart 158:20                       PubCommandRunner.run
[   +2 ms]     | package:dartdev/dartdev.dart 45:56                               runDartdev
[   +1 ms]     | C:\b\s\w\ir\cache\builder\sdk\pkg\dartdev\bin\dartdev.dart 11:9  main
[   +1 ms]     | ===== asynchronous gap ===========================
[   +5 ms]     | dart:async                                                       Future.catchError
[   +1 ms]     | package:pub/src/utils.dart 109:52                                captureErrors.wrappedCallback
[        ]     | package:stack_trace                                              Chain.capture
[        ]     | package:pub/src/utils.dart 122:11                                captureErrors
[   +2 ms]     | package:pub/src/command.dart 180:13                              PubCommand.run
[   +2 ms]     | package:args/command_runner.dart 209:27                          CommandRunner.runCommand
[        ]     | package:pub/src/command_runner.dart 173:24                       PubCommandRunner.runCommand
[   +1 ms]     | package:pub/src/command_runner.dart 158:20                       PubCommandRunner.run
[   +1 ms]     | package:dartdev/dartdev.dart 45:56                               runDartdev
[   +4 ms]     | C:\b\s\w\ir\cache\builder\sdk\pkg\dartdev\bin\dartdev.dart 11:9  main
[  +40 ms] Running "flutter pub get" in apptestflutter... (completed in 907ms)
[   +2 ms] "flutter create" took 2,061ms.
[   +9 ms] pub get failed (66;     | C:\b\s\w\ir\cache\builder\sdk\pkg\dartdev\bin\dartdev.dart 11:9  main)
[   +1 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _DefaultPub.batch (package:flutter_tools/src/dart/pub.dart:373:7)
           <asynchronous suspension>
           #2      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:254:7)
           <asynchronous suspension>
           #3      CreateBase.generateApp (package:flutter_tools/src/commands/create_base.dart:459:7)
           <asynchronous suspension>
           #4      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:292:31)
           <asynchronous suspension>
           #5      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1140:27)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #13     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>


[ +267 ms] ensureAnalyticsSent: 264ms
[   +5 ms] Running shutdown hooks
[   +2 ms] Shutdown hooks complete
[   +2 ms] exiting with code 66

**Comment by darshankawar** [comment]
@justbriang 
Can you provide `flutter doctor -v` and try to run `flutter create demotest --verbose` and see what you get ?

**Comment by justbriang** [comment]
flutter doctor -v

![image](https://user-images.githubusercontent.com/42893623/145868469-0cae00cf-3ac3-4ee2-8509-a3eac9e539ba.png)

**Comment by justbriang** [comment]
PS C:\Users\judtbriang\Desktop\flutter> flutter create demotest --verbose
[ +114 ms] executing: [C:\flutter_root\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +656 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] cf4400006550b70f28e4b4af815151d1e74846c6
[   +1 ms] executing: [C:\flutter_root\flutter/] git tag --points-at cf4400006550b70f28e4b4af815151d1e74846c6
[  +87 ms] Exit code 0 from: git tag --points-at cf4400006550b70f28e4b4af815151d1e74846c6
[        ] 2.8.0
[  +13 ms] executing: [C:\flutter_root\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +47 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter_root\flutter/] git ls-remote --get-url origin
[  +38 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +155 ms] executing: [C:\flutter_root\flutter/] git rev-parse --abbrev-ref HEAD
[  +46 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[ +106 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +7 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +80 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +6 ms] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +81 ms] Creating project demotest...
[ +648 ms] Running "flutter pub get" in demotest...
[   +8 ms] Using C:\flutter_root\flutter\.pub-cache for the pub cache.
[   +2 ms] executing: [C:\Users\judtbriang\Desktop\flutter\demotest/]
C:\flutter_root\flutter\bin\cache\dart-sdk\bin\dart __deprecated_pub --verbose get --no-precompile
[ +143 ms] FINE: Pub 2.15.0
[  +47 ms] ERR : Could not find a file named "pubspec.yaml" in "C:\Users\judtbriang\Desktop\flutter\demotest".
[   +1 ms] FINE: Exception type: FileException
[  +33 ms] FINE: package:pub/src/pubspec.dart 288:7                               new Pubspec.load
[   +3 ms]     | package:pub/src/package.dart 149:27                              new Package.load
[   +1 ms]     | package:pub/src/entrypoint.dart 177:24                           new Entrypoint
[   +1 ms]     | package:pub/src/command.dart 72:38                               PubCommand.entrypoint
[   +2 ms]     | package:pub/src/command.dart                                     PubCommand.entrypoint
[        ]     | package:pub/src/command/get.dart 52:11                           GetCommand.runProtected
[        ]     | package:pub/src/command.dart 180:45                              PubCommand.run.<fn>
[        ]     | package:pub/src/command.dart 180:33                              PubCommand.run.<fn>
[        ]     | dart:async                                                       new Future.sync
[        ]     | package:pub/src/utils.dart 109:12                                captureErrors.wrappedCallback
[        ]     | package:stack_trace                                              Chain.capture
[        ]     | package:pub/src/utils.dart 122:11                                captureErrors
[        ]     | package:pub/src/command.dart 180:13                              PubCommand.run
[   +6 ms]     | package:args/command_runner.dart 209:27                          CommandRunner.runCommand
[   +1 ms]     | package:pub/src/command_runner.dart 173:24                       PubCommandRunner.runCommand
[        ]     | package:pub/src/command_runner.dart 158:20                       PubCommandRunner.run
[        ]     | package:dartdev/dartdev.dart 45:56                               runDartdev
[   +1 ms]     | C:\b\s\w\ir\cache\builder\sdk\pkg\dartdev\bin\dartdev.dart 11:9  main
[        ]     | ===== asynchronous gap ===========================
[        ]     | dart:async                                                       Future.catchError
[        ]     | package:pub/src/utils.dart 109:52                                captureErrors.wrappedCallback
[        ]     | package:stack_trace                                              Chain.capture
[        ]     | package:pub/src/utils.dart 122:11                                captureErrors
[   +5 ms]     | package:pub/src/command.dart 180:13                              PubCommand.run
[   +3 ms]     | package:args/command_runner.dart 209:27                          CommandRunner.runCommand
[        ]     | package:pub/src/command_runner.dart 173:24                       PubCommandRunner.runCommand
[        ]     | package:pub/src/command_runner.dart 158:20                       PubCommandRunner.run
[        ]     | package:dartdev/dartdev.dart 45:56                               runDartdev
[        ]     | C:\b\s\w\ir\cache\builder\sdk\pkg\dartdev\bin\dartdev.dart 11:9  main
[  +28 ms] Running "flutter pub get" in demotest... (completed in 291ms)
[   +2 ms] "flutter create" took 1,226ms.
[   +6 ms] pub get failed (66;     | C:\b\s\w\ir\cache\builder\sdk\pkg\dartdev\bin\dartdev.dart 11:9  main)
[   +1 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _DefaultPub.batch (package:flutter_tools/src/dart/pub.dart:373:7)
           <asynchronous suspension>
           #2      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:254:7)
           <asynchronous suspension>
           #3      CreateBase.generateApp (package:flutter_tools/src/commands/create_base.dart:459:7)
           <asynchronous suspension>
           #4      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:292:31)
           <asynchronous suspension>
           #5      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1140:27)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #13     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>


[ +268 ms] ensureAnalyticsSent: 261ms
[   +5 ms] Running shutdown hooks
[   +2 ms] Shutdown hooks complete
[   +2 ms] exiting with code 66

**Comment by darshankawar** [comment]
@justbriang 
Can you try the same on another drive (ex: D ) instead of `C:\Users\judtbriang\Desktop\flutter` ?
I tried the same on my Windows 10 using latest stable and I am able to create new project without any issues. Maybe there's some permission issue due to which pub is failing and throwing 66.
