### ISSUE TITLE
[local_auth] Crash on some devices

### ISSUE THREAD

**Issue by konewuser** [flutter/flutter#94990]
## Steps to Reproduce
1. Run local_auth on LG V20, V30, Nokia 6
2. Trigger authenticate function
3. Force closed
`/art     (28056): Before Android 4.1, method android.graphics.PorterDuffColorFilter androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
D/AndroidRuntime(28056): Shutting down VM
D/TransportRuntime.SQLiteEventStore(28056): Storing event with priority=HIGHEST, name=FIREBASE_CRASHLYTICS_REPORT for destination cct
D/TransportRuntime.JobInfoScheduler(28056): Scheduling upload for context TransportContext(cct, HIGHEST, MSRodHRwczovL2NyYXNobHl0aWNzcmVwb3J0cy1wYS5nb29nbGVhcGlzLmNvbS92MS9maXJlbG9nL2xlZ2FjeS9iYXRjaGxvZ1xBSXphU3lCcnBTWVQ0RkZMMDlyZUhKaTZIOUZZZGVpU25VVE92Mk0=) with jobId=267530320 in 1000ms(Backend next call timestamp 1639109029742). Attempt 1
E/AndroidRuntime(28056): FATAL EXCEPTION: main
E/AndroidRuntime(28056): Process: com.paykool.bnpl, PID: 28056
E/AndroidRuntime(28056): java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
E/AndroidRuntime(28056): 	at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:843)
E/AndroidRuntime(28056): 	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:806)
E/AndroidRuntime(28056): 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:693)
E/AndroidRuntime(28056): 	at androidx.appcompat.app.AppCompatDialog.setContentView(AppCompatDialog.java:95)
E/AndroidRuntime(28056): 	at androidx.appcompat.app.AlertController.installContent(AlertController.java:232)
E/AndroidRuntime(28056): 	at androidx.appcompat.app.AlertDialog.onCreate(AlertDialog.java:279)
E/AndroidRuntime(28056): 	at android.app.Dialog.dispatchOnCreate(Dialog.java:436)
E/AndroidRuntime(28056): 	at android.app.Dialog.show(Dialog.java:314)
E/AndroidRuntime(28056): 	at androidx.fragment.app.DialogFragment.onStart(DialogFragment.java:691)
E/AndroidRuntime(28056): 	at androidx.fragment.app.Fragment.performStart(Fragment.java:3021)
E/AndroidRuntime(28056): 	at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:589)
E/AndroidRuntime(28056): 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:300)
E/AndroidRuntime(28056): 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
E/AndroidRuntime(28056): 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
E/AndroidRuntime(28056): 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
E/AndroidRuntime(28056): 	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
E/AndroidRuntime(28056): 	at android.os.Handler.handleCallback(Handler.java:751)
E/AndroidRuntime(28056): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(28056): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime(28056): 	at android.app.ActivityThread.main(ActivityThread.java:6247)
E/AndroidRuntime(28056): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(28056): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
E/AndroidRuntime(28056): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
Lost connection to device.
`

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
From the log, it's failing due to

`FATAL EXCEPTION: main E/AndroidRuntime(28056): Process: com.paykool.bnpl, PID: 28056 E/AndroidRuntime(28056): java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity`

Which is similar to https://github.com/flutter/flutter/issues/55638, so follow-up in it for further updates.
Closing this as duplicate.
