### ISSUE TITLE
camera：takePicture() displays the last photo taken

### ISSUE THREAD

**Issue by clycheng2015** [flutter/flutter#94991]
In my fluttle adnroid application, when I use takepicture to take photos for many times, the photos displayed are often taken in the last pose. For example, this time, when I preview and take photos with my head straight, the photos I took last time when my header was Sideways are displayed! It's terrible. 

camera: ^0.8.1+1

[✓] Flutter (Channel unknown, 2.5.0, on macOS 11.6.1 20G224 darwin-x64, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.2)
[✓] VS Code (version 1.38.0)
[✓] Connected device (3 available)

**Comment by clycheng2015** [comment]
Real machine model: Xiaomi mix 3

**Comment by darshankawar** [comment]
@clycheng2015 
You are using an old version of the plugin and framework. Current plugin version is `^0.9.4+5` and stable is 2.8.0. I recommend to upgrade both and try again to see if behavior still persists or not.
If yes, then provide updated `flutter doctor -v`, plugin version and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can use to verify.
Thanks.
