### ISSUE TITLE
Allow gestures to pass-through routes 

### ISSUE THREAD

**Issue by armandsLa** [flutter/flutter#94997]
## Use case

Currently it is not possible to present a new screen using `Navigator` and still be able to receive touches in a screen that lays below. 

This limitation does not allow to use `Navigator` for partly covering screen. A good example would be when a bottom-sheet-like screen needs to be presented above a full-screen map. In such cases map that lays below should still be able to receive touches so users can pan around.

Currently the only way to allow touch pass-through is to use `OverlayEntry`. It works but it is not ideal, especially when multiple screens needs to be presented.

## Proposal

Please consider adding a route or a setting to an existing routes that allows touch pass-through to previous screen. This change would allow to use `Navigator` though-out the app and would not require the use of `OverlayEntry`.

**Comment by goderbauer** [comment]
This should be doable with a custom Route. I believe it is the ModalRoute that introduces the pointer blocking.

**Comment by goderbauer** [comment]
I am going to close this per my previous comment.
