### ISSUE TITLE
Consider letting lightweight engines run in shared root isolate

### ISSUE THREAD

**Issue by ColdPaleLight** [flutter/flutter#94995]
## Update
design doc: https://flutter.dev/go/multiple-applications
flutter PR: https://github.com/flutter/flutter/pull/95408
engine PR: https://github.com/flutter/engine/pull/30372
sample: https://github.com/ColdPaleLight/multiple_flutters 
（We can control whether the lightweight engines are running in the shared isolate through the new parameter named `sharedIsolateMode` in the `FlutterEngineGroup` constructor）

https://user-images.githubusercontent.com/31977171/146780746-b8c62d92-3503-4957-9a5a-925c82033c4e.MP4

## Origin
I'm a the developer of a complex app named "XianYu", which is added the flutter by "add-to-app" way. It has a lot of flutter screens in it.
I'm also a the developer of "FlutterBoost"，which is a plugin that can let people easily add flutter by "add-to-app" way. It has 5.7k stars in github https://github.com/alibaba/flutter_boost .
I'm also a flutter team member and I have contributed some PR to the lightweight engine solution. 

Since I play these different roles, I think it's time to file this issue to explain why we need to let multiple lightweight engines run in shared root isolate.

When flutter was first designed, it was designed for the full flutter app. But in fact, there are a lot of applications that cannot be rewritten to full flutter app. Most of the flutter developers I know are maintaining their applications that are not full flutter apps. After flutter 1.12 version, flutter provides a "add-to-app" solution. But it's not easy to integration the flutter and run it well directly. In order to better integrate flutter into existing apps, developers from the community have developed some plugins for that. For example, we developed "flutter_boost". It is to allow multiple `FlutterActivity/FlutterViewController` to share the one `FlutterEngine`. The **benefits** of this are as follows:
* **There is only one `FlutterEngine` in the process, so the memory overhead will be the least.**
* **All dart codes corresponding to different FlutterActivity/FlutterViewController are in the same Isolate.**

Of course, such a solution also has **disadvantages** :
* **You can only show one Flutter screen at the same time.**
* **You may need to attach engine or detach engine when the page is switched.**

The Flutter 2.0 version provides the lightweight engine solution, which is a very good solution that solves the problem of high memory overhead for multiple engines. We want to use this solution to refactor our app, but we found that although these lightweight engines are running on the shared UI thread, they are running on different isolates. This has caused many problems. The classic case is that ImageCache can no longer be shared.   https://github.com/flutter/flutter/issues/72033  

In real applications, there are too many such cases, so I guess it is very difficult for developers to use the current lightweight engine solution to refactor their own apps, and the maintenance is also hard. 

At the same time I also noticed that there is an issue about how to let engines has a good communication https://github.com/flutter/flutter/issues/33288 . There are many ways here, such as lightweight isolate, DataSync, Platform Channel. But compared to how to make Isolate communication more convenient, I believe that developers are more concerned about how to make their own code run in the same Isolate. So I think the best solution is to let multiple lightweight engines run in the shared root Isolate.

## How to implement
At present, I have completed the exploration on whether the proposed solution can be completed, and I will share the design document in the near future. Let me briefly introduce how to implement this function：

At present, only one flutter application can run in the root Isolate, so we need to allow multiple flutter applications to run in the shared root Isolate. We can use `Zone` to isolate these flutter applications, different flutter applications run in different zones, and the zoneValues ​​of these zones store the application id. Then we can change some of the original singletons, such as WidgetsBinding, ui.window, and ui.platformDispatcher from one for each Isolate to one for each flutter application (or zone).
![image](https://user-images.githubusercontent.com/31977171/145582704-6cee295a-7fd4-4b90-8e2a-ee723bf78897.png)

Since multiple flutter applications may be running in root isolate, we need to add `application_id` to the code that communicates between dart and c++. The main change files are `hooks.dart` and `platform_configuration.cc`

Finally，the following are the changes needed on the engine side:
Object graph of the current lightweight engine:
![image](https://user-images.githubusercontent.com/31977171/145546520-6ea0419f-d677-4938-8a87-d20e6381e28f.png)

Object graph of the expected lightweight engine
![image](https://user-images.githubusercontent.com/31977171/145546747-3f1c040c-2c70-4ad4-9160-cc9b491ae8a9.png)

## Related issue
https://github.com/flutter/flutter/issues/72009
https://github.com/flutter/flutter/issues/33288
https://github.com/flutter/flutter/issues/72033

/cc @xster @gaaclarke @blasten @zoeyfan

**Comment by xster** [comment]
Is this roughly the same idea as flutter.dev/go/desktop-multi-window-support? i.e. the Dart program will have to have awareness of multiple PlatformDispatchers/FlutterViews etc?

**Comment by ColdPaleLight** [comment]
> Is this roughly the same idea as flutter.dev/go/desktop-multi-window-support? 

The two solutions have some similarities. For example, we both hope that there can be multiple windows in a root isolate.

But there are still many differences between the two solutions. The idea of ​​the multi-window solution is to manage multiple windows in one flutter application, and then run in one FlutterEngine. The engineering cost of this scheme is very high, and there are many problems to be solved. For example, how should the embedding API be changed, and how can rasterizer work with multiple surfaces? 

The solution I proposed, I call it multi-application, is an evolution of the lightweight engine solution. It is basically the same as the lightweight engine solution, except that these flutter applications run in the same root isolate. The engineering cost of multi-application will be much lower than that of multi-window. At present, multi-application can make https://github.com/flutter/samples/tree/master/add_to_app/multiple_flutter run well without change any code.

> i.e. the Dart program will have to have awareness of multiple PlatformDispatchers/FlutterViews etc?

In most cases, developers do not need to have awareness of multiple PlatformDispatchers and FlutterViews. But developers need to know roughly that the multi-application solution uses zones to isolate applications, but I guess this is not a big deal.

**Comment by xster** [comment]
Thanks. Without a cross-isolate interop solution, the multi-engine approach does need more work to make it land well so it's a worthwhile topic to continue exploring. 

Your approach sounds interesting but I'm not sure I fully understand it. I think going through the https://github.com/flutter/flutter/wiki/Chat#design-documents process could help us align more quickly. For instance, how does each widget binding retrieve its window/PlatformDispatcher properties? Where does the image cache sit in this proposal? 

It also sounds a bit like you have a running example with https://github.com/flutter/samples/tree/master/add_to_app/multiple_flutter too. That could help visualize what the proposal is too. 

cc @zanderso

**Comment by ColdPaleLight** [comment]
Hi, @xster 
Thank you for your suggestion, I have posted the design doc, draft PR and sample to the top of the post :) .
https://github.com/flutter/flutter/issues/94995#issue-1076596322

**Comment by knopp** [comment]
This seems great! Adding multiple views to single engine would require quite a bit of engine work, including significant breakage in the embedder API. This on the other hand, is much less invasive, doesn't require API breaks and accomplishes pretty much the same thing. I'm wondering if the fact that different engines/views need different zone active is going to be a problem in practice, but hopefully not.

This would also be a great motivation to implement lightweight isolate / sharing for desktop.

@ColdPaleLight, I haven't tried the example yet, I'm wondering if something like shared counter work:
```dart
final counter = ValueNotifier(0);
// engine1
counter.AddListener(() { this/*state in engine 1*/.setState(() { value = counter.value; }});
// engine2
counter.AddListener(() { this/*state in engine 2*/.setState(() { value = counter.value; }});

...
counter.value = counter.value + 1;
````

I think in theory it should work and refresh both engine views, because the `buildOwner` references `Bindings` directly and doesn't do lookup through `.instance`, but I might be missing something.

**Comment by ColdPaleLight** [comment]
Hi, @knopp 
Thank you for your reply. The "shared counter" is a good example. Unfortunately, if we don’t make any changes, it won’t work (I haven't found the root reason why it can’t work).

However, it is very easy to make it work. When we encounter this kind of case about `listener` registered in one `engine/application/zone` and called in another `engine/application/zone`. We can make some changes to let the `listener` execute in the correct `zone`. For example, we can use `Zone.bindCallback` to do this. I tried it and it works well.
``` dart
final counter = ValueNotifier(0);
// engine1 (application 1)
counter.AddListener(Zone.current.bindCallback(() { this/*state in engine 1*/.setState(() { value = counter.value; }}));
// engine2 (application 2)
counter.AddListener(Zone.current.bindCallback(() { this/*state in engine 2*/.setState(() { value = counter.value; }}));
...
counter.value = counter.value + 1;
```

We can also make it work without changing any code in the "shared counter" example, such as putting the logic of `Zone.bindCallback` in the `ChangeNotifier` class. This makes it more convenient for application developers to use.

**Comment by knopp** [comment]
I think that would mean that somewhere along the way, when scheduling update triggered from `setState()` binding is accessed through `.instance`, which will get binding from current zone and not the one from current element tree.

**Comment by ColdPaleLight** [comment]
> I think that would mean that somewhere along the way, when scheduling update triggered from `setState()` binding is accessed through `.instance`, which will get binding from current zone and not the one from current element tree.

Yes, I agree with you. So when multiple applications need to share data, the best practice is to let the listener run in the zone where it was registered. I tweaked the code of `ImageStreamListener` in this way, and solved the problem of multiple applications sharing ImageCache. https://github.com/flutter/flutter/pull/95408/commits/82db889093130eae3f766d9c6e02495d41ba2d11

**Comment by knopp** [comment]
I'm wondering if it would help to bind `buildOwner!.onBuildScheduled` to current zone to get this working.

**Comment by knopp** [comment]
That is indeed the case. 
```dart
buildOwner!.onBuildScheduled = Zone.current.bindCallback(_handleBuildScheduled);
```
Inside `WidgetsBinding.initInstances` take care of the refresh problem. Now you can trigger `setState` from value notifier without having to bind to the zone.

**Comment by ColdPaleLight** [comment]
@knopp 

I found the reason why it didn't work. A lot of my previous code implicitly depended on the applicationId in the zone.

This time I changed these codes so that `Binding` can find its corresponding `ui.window` and `ui.PlatformDispatcher`, and then let `platformDispatcher` use its own `_applicationId` instead of `Application.current.id` when calling the native method.

changes detail is in here
framework:
https://github.com/flutter/flutter/pull/95408/commits/20660acb5148b72372a7732b407bc1822e6ab6fa
engine:
https://github.com/flutter/engine/pull/30372/commits/2e295f53137dc6c39a9c65805a81a0b1acf52447

After making these changes,The "shared counter" can run well without binding the zone :) .

**Comment by knopp** [comment]
It does work with these changes. I think this is rather elegant solution. There are some minor quirks (i.e. you need to be in the right zone when accessing globalKey state), but overall it seems to be working quite well.

**Comment by ColdPaleLight** [comment]
> It does work with these changes. I think this is rather elegant solution. There are some minor quirks (i.e. you need to be in the right zone when accessing globalKey state), but overall it seems to be working quite well.

Yeah, currently, zone binding cannot be completely avoided. Because there are too many codes like `WidgetsBinding.instance`. But in the long run, we can actually mark a series of APIs such as `WidgetBinding.instance` as deprecated and gradually replace them.

**Comment by ColdPaleLight** [comment]
> Hi @ColdPaleLight , Is there any progress on this issue? #95408 is closed.

This proposal is a very big change for flutter, and the introduction of Zone will make it difficult to maintain later. 

I think we can follow the new solution https://flutter.dev/go/multiple-views of the google flutter team. Although they are currently focusing on the desktop side, they may expand to the mobile side in the future.

I'm going to close this issue since this proposal will not be implemented in the future.
