### ISSUE TITLE
Explain how the DefaultTextStyle is computed for MaterialApp.

### ISSUE THREAD

**Issue by MohamadNezar** [flutter/flutter#94993]
```
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Builder(
        builder: (context) => Container(
          color: Colors.white,
          child: Text(
            'مرحبا',
          ),
        ),
      ),
    );
  }
}
```
and this is result on screen
![image](https://user-images.githubusercontent.com/57882324/145537227-1f88b304-cf0a-4a88-8852-3a8e3cded0c8.png)

**Comment by darshankawar** [comment]
@MohamadNezar 
Can you provide `flutter doctor -v` ?

**Comment by MohamadNezar** [comment]
> @MohamadNezar Can you provide `flutter doctor -v` ?

[√] Flutter (Channel stable, 2.8.0, on Microsoft Windows [Version 10.0.19044.1348], locale en-US)
    • Flutter version 2.8.0 at C:\flutter_windows_2.0.0-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (35 hours ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Mohammad-N-Aldalati\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Mohammad-N-Aldalati\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31129.286
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.62.3)
    • VS Code at C:\Users\Mohammad-N-Aldalati\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1348]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 96.0.4664.93
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 96.0.1054.43

• No issues found!

**Comment by darshankawar** [comment]
@MohamadNezar 
Is this in debug mode or in release mode ?

**Comment by MohamadNezar** [comment]
> @MohamadNezar Is this in debug mode or in release mode ?

debug mode.

**Comment by darshankawar** [comment]
@MohamadNezar 
Can you please try the same on latest master and see if you still get same behavior ?

```
flutter channel master
flutter upgrade
```

**Comment by MohamadNezar** [comment]
> @MohamadNezar Can you please try the same on latest master and see if you still get same behavior ?
> 
> ```
> flutter channel master
> flutter upgrade
> ```

I try this, not working also, the same result.

**Comment by HansMuller** [comment]
This appears to work correctly with the current master branch. 

```dart
import 'package:flutter/material.dart';

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: const Scaffold(
        body: Text('مرحبا'),
      ),
    );
  }
}

void main() {
  runApp(MyApp());
}
```

**Comment by HansMuller** [comment]
The Scaffold widget creates a Material widget that becomes an ancestor of the Scaffold's body. The Material widget builds a [DefaultTextStyle](https://api.flutter.dev/flutter/widgets/DefaultTextStyle-class.html) for `Theme.of(context).textTheme.bodyText2` which ensures that the entire app inherits a default text style that has been properly localized.  Just using a Material widget instead of a Scaffold would work as well.
