### ISSUE TITLE
Figure out our linkability story

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#95]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Friday Jul 17, 2015 at 22:45 GMT_
_Originally opened as https://github.com/flutter/engine/issues/100_

---

See: https://github.com/flutter/engine/blob/master/sky/specs/linkability.md

**Comment by eseidelGoogle** [comment]
Closing in favor of https://github.com/flutter/flutter/issues/9768.
