### ISSUE TITLE
Preparing android app for using url_lancher with SDK > 30 opens urls in webview instead of new Browser Window

### ISSUE THREAD

**Issue by chrisDK1977** [flutter/flutter#95005]
Just adding 

```
<queries>
    <intent>
        <action android:name="android.intent.action.VIEW" />
        <data android:scheme="https" />
    </intent>
    <intent>
        <action android:name="android.intent.action.DIAL" />
        <data android:scheme="tel" />
    </intent>
    <intent>
        <action android:name="android.intent.action.SEND" />
        <data android:mimeType="*/*" />
    </intent>
</queries>
```

to the AndroidManifest.xml results that 

await launch(myURLl); 

opens the URL in a webview instead of a new Browser Window (simulator).

The dokumentation says:
**By default, Android opens up a browser when handling URLs.** You can pass forceWebView: true parameter to tell the plugin to open a WebView instead. If you do this for a URL of a page containing JavaScript, make sure to pass in enableJavaScript: true, or else the launch method will not work properly. On iOS, the default behavior is to open all web URLs within the app. Everything else is redirected to the app handler.

What could be the problem?

**Comment by danagbemava-nc** [comment]
Hi @chrisDK1977, thanks for filing the issue. 

Please provide a complete minimal reproducible code sample, the output of `flutter doctor -v`, and the version of `url_launcher` you're using. 

Thank you

**Comment by chrisDK1977** [comment]
Create a new Flutter Project, copy example-code from https://pub.dev/packages/url_launcher

add 

```
    <queries>
        <!-- If your app opens https URLs -->
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <data android:scheme="https" />
        </intent>
        <!-- If your app makes calls -->
        <intent>
            <action android:name="android.intent.action.DIAL" />
            <data android:scheme="tel" />
        </intent>
        <!-- If your sends SMS messages -->
        <intent>
            <action android:name="android.intent.action.SENDTO" />
            <data android:scheme="smsto" />
        </intent>
        <!-- If your app sends emails -->
        <intent>
            <action android:name="android.intent.action.SEND" />
            <data android:mimeType="*/*" />
        </intent>
    </queries>
```

at the end of the android manifest

and 

url_launcher: 6.0.10 
(below dependencies:)

to pubspec.yaml

lauch an API Level 30 simulator and click the button:

![image](https://user-images.githubusercontent.com/49610365/145578293-0f51cc0a-570a-450c-b1e9-dc0916b5556e.png)

C:\SDKs\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.19042.1348], locale de-DE)
    • Flutter version 2.0.4 at C:\SDKs\flutter
    • Framework revision b1395592de (8 months ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\ChristianKiefer\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Connected device (6 available)
...
    • Android SDK built for x86 (mobile) • emulator-5558 • android-x86    • Android 11 (API 30) (emulator)

**Comment by danagbemava-nc** [comment]
Hi @chrisDK1977, I attempted to reproduce this, but it always opened in a browser for me.
See video below.
You do appear to be using an older version of flutter, kindly upgrade to the latest version to see whether or not you still experience this issue. 


https://user-images.githubusercontent.com/88313112/145582706-b0a72d21-8e78-44c4-baff-7d6a76ba9704.mov

**Comment by chrisDK1977** [comment]
@danagbemava-nc you are right - an update solves the problem.

**Comment by danagbemava-nc** [comment]
Closing as solved based on [this comment](https://github.com/flutter/flutter/issues/95005#issuecomment-991025870
)
