### ISSUE TITLE
Support configure a custom launch url for flutter web

### ISSUE THREAD

**Issue by wangying3426** [flutter/flutter#95001]
Hi, 

When we develop with flutter for web, the default launch url is http://${web-hostname}:${web-port}. But when the page must use cookie with a specific domain, such as login information,  a cross-domain error will occur.

In order to solve the cross-domain problem to share cookie, a launch url that match the same-origin policy should be used when the browser is first opened, so we need to support configure a custom launch url for flutter web

For example:
first, we need to configure a url, such as "http://alchemy-boe.bytedance.net/."
<img width="821" alt="Screen Shot 2021-12-10 at 5 29 56 PM" src="https://user-images.githubusercontent.com/4476512/145551051-bc2568b6-3595-4ba2-83e3-f09aa27f4761.png">

second, the browser will be launched with the configured url.
<img width="753" alt="Screen Shot 2021-12-10 at 3 41 17 PM" src="https://user-images.githubusercontent.com/4476512/145550764-cdcdb035-9156-435d-adf2-1ebaa6257e73.png">

then, the flutter for web pages can access cookie under the  "http://alchemy-boe.bytedance.net"

We have used this solution in daily business development, and works fine.

**Comment by ditman** [comment]
A fix for this has been already merged, it seems! https://github.com/flutter/flutter/pull/95002

I'm going to close this issue as fixed, feel free to reopen if I made a mistake!
