### ISSUE TITLE
Google Maps Showing White Screen on Android

### ISSUE THREAD

**Issue by dandoii** [flutter/flutter#95017]
Hi, I have a GooMap widget on my dashboard of my app and it works perfectly on iOS but not at all on android. It just shows a white screen, this is only on the release build distributed through google play store for internal testing.

**Comment by WasserEsser** [comment]
If this only happens on release builds, could it be that you have added the API key in the AndroidManifest of the debug build (android/app/src/debug/AndroidManifest.xml) instead of the main one inside android/app/src/main?

**Comment by mamuseferha** [comment]
Hi @dandoii  
Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by dandoii** [comment]
Here is my flutter doctor, attached is a screenshot of what the emulator shows. Its on all android versions. Works perfectly on iOS

[✓] Flutter (Channel stable, 2.5.3, on macOS 11.5.2 20G95 darwin-arm, locale en-GB)
    • Flutter version 2.5.3 at /opt/homebrew/Caskroom/flutter/2.2.3/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (8 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK
![Screenshot_1639380040](https://user-images.githubusercontent.com/49167558/145769286-6902a175-b0f0-4412-864d-30cd9c77431c.png)
 version 31.0.0)
    • Android SDK at /Users/pauldando/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.63.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554             • android-arm64  • Android 12 (API 31) (emulator)
    • iPhone (mobile)             • 00008101-0018298A2EFA001E • ios            • iOS 14.7.1 18G82
    • Chrome (web)                • chrome                    • web-javascript • Google Chrome 96.0.4664.93

• No issues found!

**Comment by dandoii** [comment]
> Hi @dandoii
> Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
> Thank you

class GooMap extends StatefulWidget {
  //GooMap({Key key}) : super(key: key);

  final LocationData location;
  GooMap({required this.location});

  @override
  _GooMapState createState() => _GooMapState();
}

class _GooMapState extends State<GooMap> {
  // Location
  LocationData? _locationData;

  // Maps
  Set<Polygon> _polygons = HashSet<Polygon>();
  GoogleMapController? _googleMapController;

  // ignore: deprecated_member_use
  List<LatLng> polygonLatLngs = [];
  bool isEmpty = true;
  //ids
  int _polygonIdCounter = 1;

  // Type controllers
  bool _isPolygon = false; //Default
  TextEditingController latController = TextEditingController();
  List<String> colors = ["Green", "Orange", "Purple", "Blue"];
  String? selectedColor;
  List<String>? workFlowList;
  List<String>? viewList;
  bool hasViewed = true;

  @override
  void initState() {
    super.initState();

    _locationData = widget.location;
    getEverything();
  }
 void _setPolygon() {
    final String polygonIdVal = 'polygon_id_$_polygonIdCounter';

    _polygons.add(Polygon(
      polygonId: PolygonId(polygonIdVal),
      points: polygonLatLngs,
      strokeWidth: 2,
      strokeColor: Colors.yellow,
      fillColor: Colors.yellow.withOpacity(0.15),
    ));
  }
  getPolyGons() async {
    QuerySnapshot snapshot = await FirebaseFirestore.instance
        .collection("Locations")
        .doc(currentUser.id)
        .collection("LocationsList")
        .get();
    QuerySnapshot snapshot2 = await FirebaseFirestore.instance
        .collection("Activity")
        .doc(currentUser.id)
        .collection("userActivitys")
        .get();
    List<Activity> actRecList =
        snapshot2.docs.map((doc) => Activity.fromDocument(doc)).toList();
    List<PolygonLocation> locationList =
        snapshot.docs.map((doc) => PolygonLocation.fromDocument(doc)).toList();

    Set<Polygon> polys = HashSet<Polygon>();
    for (var item in locationList) {
      Color polyCol = Colors.yellow;
      if (item.colour == "Green") {
        polyCol = Colors.green;
      } else if (item.colour == "Orange") {
        polyCol = Colors.orange;
      } else if (item.colour == "Blue") {
        polyCol = Colors.blue;
      } else if (item.colour == "Purple") {
        polyCol = Colors.purple;
      }

      List<LatLng> latLngs = [];
      int counter = 0;
      for (var entry in item.lats) {
        latLngs.add(LatLng(entry, item.longs[counter]));
        counter++;
      }
      List<Activity> actList = [];

      for (var rec in actRecList) {
        DateTime tempDate = DateTime.fromMillisecondsSinceEpoch(
            rec.dateRecorded.millisecondsSinceEpoch);
        bool isDate = tempDate.year == DateTime.now().year &&
            tempDate.month == DateTime.now().month &&
            tempDate.day == DateTime.now().day;
        if (rec.location == item.name && isDate) {
          actList.add(rec);
        }
      }

      polys.add(Polygon(
        polygonId: PolygonId(locationList.indexOf(item).toString()),
        consumeTapEvents: true,
        points: latLngs,
        strokeWidth: 2,
        zIndex: 1,
        strokeColor: polyCol,
        fillColor: polyCol.withOpacity(0.15),
        onTap: () {
          if (!_isPolygon) {
            showDialog(
                context: context,
                builder: (BuildContext context) {
                  return AlertDialog(
                    scrollable: true,
                    title: Text(item.name),
                    actionsAlignment: MainAxisAlignment.center,
                    actions: [
                      Column(children: [
                        Text("Today's Activity's"),
                        for (var item in actList) buildActivityNav(item)
                      ])
                    ],
                  );
                });
          }
        },
      ));
    }
    setState(() {
      isEmpty = false;
      _polygons = polys;
    });
  }

submitPolygon(String name) async {
    List<double> longs = [];
    List<double> lats = [];

    for (var item in polygonLatLngs) {
      longs.add(item.longitude.toDouble());
      lats.add(item.latitude.toDouble());
    }

    FirebaseFirestore.instance
        .collection("Locations")
        .doc(currentUser.id)
        .collection("LocationsList")
        .doc(name)
        .set({
      "longs": longs,
      "lats": lats,
      "name": name,
      "colour": selectedColor
    });
  }

 @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: header(context, isAppTitle: true),
        drawer: Container(width: 250, child: buildTimeline()),
        floatingActionButton: !hasViewed
            ? Container(
                decoration: BoxDecoration(
                    color: Colors.white,
                    borderRadius: BorderRadius.all(Radius.circular(20))),
                child: Icon(Icons.mark_as_unread_outlined))
            : Text(""),
        floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,
        body: (isEmpty)
            ? loadingPolys()
            : Stack(
                children: <Widget>[
                  GoogleMap(
                    initialCameraPosition: CameraPosition(
                      target: LatLng(currentUser.lat, currentUser.long),
                      zoom: 16,
                    ),
                    mapType: MapType.hybrid,
                    polygons: _polygons,
                    myLocationEnabled: false,
                    myLocationButtonEnabled: false,
                    onTap: (point) {
                      if (_isPolygon) {
                        setState(() {
                          polygonLatLngs.add(point);
                          _setPolygon();
                        });
                      }
                    },
                  ),
                  Padding(
                    padding: EdgeInsets.all(10),
                    child: ExpandableFab(
                      distance: 75,
                      children: [
                        ElevatedButton(
                            onPressed: () {
                              showDialog(
                                  context: context,
                                  builder: (BuildContext context) {
                                    return AlertDialog(
                                      scrollable: true,
                                      title: Text('Submit Location'),
                                      actionsAlignment:
                                          MainAxisAlignment.center,
                                      actions: [
                                        Column(children: [
                                          Padding(
                                              padding:
                                                  EdgeInsets.only(top: 12.0),
                                              child: Text(
                                                "Name",
                                                style: TextStyle(
                                                    color: Colors.grey),
                                              )),
                                          SizedBox(height: 10),
                                          TextField(
                                            controller: latController,
                                            decoration: InputDecoration(
                                              hintText: "Enter Location Name",
                                            ),
                                          ),
                                          buildColorDrop(),
                                          ElevatedButton(
                                              child: Text("Submit"),
                                              onPressed: () {
                                                setState(() {
                                                  submitPolygon(
                                                      latController.text);
                                                  getPolyGons();
                                                  _isPolygon = false;
                                                  polygonLatLngs = [];
                                                });

                                                Navigator.pop(context);
                                              }),
                                        ])
                                      ],
                                    );
                                  });
                            },
                            child: Text(
                              'Submit Polygon',
                              style: TextStyle(
                                  fontWeight: FontWeight.bold,
                                  color: Colors.white),
                            )),
                        ElevatedButton(
                            onPressed: () {
                              setState(() {
                                if (_isPolygon) {
                                  _isPolygon = false;
                                } else {
                                  _isPolygon = true;
                                }
                              });
                            },
                            child: Text(
                              _isPolygon ? 'Draw Mode On' : "Draw Mode Off",
                              style: TextStyle(
                                  fontWeight: FontWeight.bold,
                                  color: Colors.white),
                            ))
                      ],
                    ),
                  ),
                ],
              ));
  }
}

**Comment by dandoii** [comment]
> If this only happens on release builds, could it be that you have added the API key in the AndroidManifest of the debug build (android/app/src/debug/AndroidManifest.xml) instead of the main one inside android/app/src/main?

unfortunately I see now it happens across the board on android

**Comment by dandoii** [comment]
> Hi @dandoii
> Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
> Thank you

Hope the code provided is sufficient !

**Comment by dandoii** [comment]
I've solved the issue, turns out I put my API key in the activity tag and not as a child of the application tag in the xml!
