### ISSUE TITLE
Record some non-identifying machine power class

### ISSUE THREAD

**Issue by xster** [flutter/flutter#9501]
Such as ranges of RAM size, ranges of core number etc.

**Comment by sethladd** [comment]
What's most important? Ideas for what the first set of data would be?

**Comment by xster** [comment]
We might not want to transmit anything too specific like ram size. Though a general bucketing of power would be nice. go/device-classifier

**Comment by Hixie** [comment]
I'm going to closet his since we didn't do it. If it's something we need in the future, we can just submit a PR. No need to track this in a bug.
