### ISSUE TITLE
[Proposal] add property to change ExpansionPanelList arrow icon color 

### ISSUE THREAD

**Issue by M97Chahboun** [flutter/flutter#95011]
As you look here (i add it locally) for i can change expandedIcon color.
![20211210_142240](https://user-images.githubusercontent.com/69054810/145583641-f81f5948-30cb-4cca-bc20-045d1a537402.jpg)
Thank you

**Comment by maheshmnj** [comment]
ExpansionPanelList currently doesn't support modifying icon color.

<img src="https://user-images.githubusercontent.com/31410839/145769420-84026e43-52df-43bb-b995-813d32ca3e35.png" width ="300">

**Comment by M97Chahboun** [comment]
Guys any updates ?
@dheerajv09 if you are busy I will working on it.
