### ISSUE TITLE
A Flutter app's Podfile.lock should be versionable

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#9502]
## Steps to Reproduce

Create a new app and build it for the simulator:

```
flutter create myapp
cd myapp
<add plugin dependency to pubspec.yaml>
flutter run -d i
git init
git add .
git commit
```

You've just committed a `Podfile.lock` file that contains local paths to your plugins and Flutter framework, e.g.

```
EXTERNAL SOURCES:
  Flutter:
    :path: /Users/jackson/git/flutter/bin/cache/artifacts/engine/ios
```

Everyone who builds the app will end up with a different `Podfile.lock`, and won't be sure whether to check in their version. Unfortunately, [adding `Podfile.lock` to `.gitignore` is not recommended by the CocoaPods team](http://guides.cocoapods.org/using/using-cocoapods.html#benefits-of-ignoring-the-pods-directory) because it makes builds non-reproducible.

I think we can address this by making some changes to the template app's [`Podfile`](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/create/ios.tmpl/Podfile).

Instead of having `.flutter-plugins` be a file, have it be a directory that contains contains a symbolic link called Flutter pointing to the Flutter framework directory, as well as symbolic links to the directories of all the plugin Pods.

Now the Flutter section of the Podfile looks like this:

```
  # Flutter Pods
  if Dir.exists? '../.flutter-plugins'
    Dir.foreach('../.flutter-plugins') { |name|
      next if name == '.' or name == '..'
      pod name, :path => "../.flutter-plugins/#{name}/ios"
    }
  end
```

### Benefits

  * Less boilerplate code in the Podfile
  * Going to the `ios/` directory and running `pod install` manually will actually work (after the first Flutter iOS build) instead of complaining that the `FLUTTER_FRAMEWORK_DIR` environment variable is not set.
  * The `Podfile.lock` will be the same for everyone. It will look like this:

```
DEPENDENCIES:
  - firebase_database (from `../.flutter-plugins/firebase_database/ios`)
  - firebase_storage (from `../.flutter-plugins/firebase_storage/ios`)
  - Flutter (from `../.flutter-plugins/Flutter/ios`)
  - google_sign_in (from `../.flutter-plugins/google_sign_in/ios`)
  - image_picker (from `../.flutter-plugins/image_picker/ios`)

EXTERNAL SOURCES:
  firebase_database:
    :path: ../.flutter-plugins/firebase_database/ios
  firebase_storage:
    :path: ../.flutter-plugins/firebase_storage/ios
  Flutter:
    :path: ../.flutter-plugins/Flutter/ios
  google_sign_in:
    :path: ../.flutter-plugins/google_sign_in/ios
  image_picker:
    :path: ../.flutter-plugins/image_picker/ios
...
```

While we are at it, I think we should add `Pods/` to `ios/.gitignore`, which is allowed according to the Cocoapods team. But that's more a matter of taste since (at least in theory) the contents of that directory should be the same for every developer as long as their Flutter engines are in sync.

**Comment by collinjackson** [comment]
@goderbauer @jakobr-google @mit-mit @mravn-google

**Comment by jakobr-google** [comment]
I like the idea in principle, but the Dart core team just spent a considerable amount of time and effort to move away from using symlinks for packages. We should make sure we understand their reasons before deciding.

**Comment by mit-mit** [comment]
Could the path use a FLUTTER_SDK_HOME variable or something like that?

**Comment by collinjackson** [comment]
I don't believe that Podfile.lock supports template expansion of environment variables.

Because flutter_tools requires a Mac to build Flutter iOS apps (and probably always will), I think it is safe to assume that symlinks work when flutter_tools is running on a Mac (and probably Linux too). Android builds on Windows can do something different.

Related bug: #9299

**Comment by jakobr-google** [comment]
The agreed solution is to add a .gitignore'd directory in ios/ containing symlinks to the pods, and only generate this when building for iOS (assuming that will only happen on platforms with sane symlinks).

We also keep the current .flutter-plugins file to avoid having to change Android (and older iOS) projects.

**Comment by eseidelGoogle** [comment]
@jakobr-google Is this something you are willing to do for M2?  Currently targeting May 5th for M2.

**Comment by jakobr-google** [comment]
Looking at it right now.

**Comment by eseidelGoogle** [comment]
@xster was working in this space, did you solve this too?

**Comment by eseidelGoogle** [comment]
Regardless, M2 ends this Friday, please let us know if you plan to hit that. :)

**Comment by xster** [comment]
I'm only involved very tangentially. I don't have a strong opinion but I really like Collin's proposal. (https://github.com/flutter/flutter/issues/9502#issuecomment-297144209 sounds functionally equivalent AFAICT?)

The #9580 cluster somewhat alleviates this because the majority of users won't end up changing this file until they 1- start using pub plugins, 2- install pod, 3- setup pod, 4- build flutter with pod. 

If I understand right, if user A flutter creates, never uses our plugin system and just goes into the ios folder and manually `pod install`s, checks in the various non-gitignored files, and user B checks out the same updated project but doesn't have cocoapods installed (and doesn't have the pods directory), user B can still flutter build ios?

**Comment by mit-mit** [comment]
I think thing this is an appealing idea, but I think it may be too risky to change this for I/O. Can we move this to the May milestone? cc @eseidel

**Comment by jakobr-google** [comment]
I ran into issues with the symlinks approach that I haven't been able to resolve yet, so this won't make it for I/O.

**Comment by eseidelGoogle** [comment]
@mit-mit you should always feel empowered to move bugs.

**Comment by mit-mit** [comment]
Unassigning as Jakob is currently busy with other tasks

**Comment by mit-mit** [comment]
Having spend the last week writing a small demo app with a few others, I can confirm that this issue is very, very irritating... Keeping in milestone 3.

@xster given this is iOS specific, is this something you can help with?

**Comment by xster** [comment]
I added it to my list. I'll likely get to it in February
