### ISSUE TITLE
Material/PhysicalModel should have a floating point elevation

### ISSUE THREAD

**Issue by xster** [flutter/flutter#9504]
I think this might be M2 API stability. Feel free to correctly re-prioritize.

I think we want a floating point elevation to be able to properly animate elevation transitions without step jumps.

**Comment by HansMuller** [comment]
I agree. Other Material implementations just use use linear interpolation to compute shadow parameters in between the elevations in the spec.

**Comment by eseidelGoogle** [comment]
Physical model will not be done in M2, so this can be M3.

**Comment by xster** [comment]
PhysicalModel isn't. The API is exposed via Material though

**Comment by Hixie** [comment]
The Material API wouldn't change though. It's just an `int`, and the animation is done when you switch from one to the other. The allowed values for the `Material` widget are defined by the Material spec.

**Comment by Hixie** [comment]
@jason-simmons you did this today, right?

**Comment by jason-simmons** [comment]
This has landed
