### ISSUE TITLE
[plugins] suppress android lint warnings regarding gradle version

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#95048]
There is a spamming in the Github UI, which shows a warning about gradle version. For example: https://github.com/flutter/plugins/runs/4462465513
```
A newer version of com.android.tools.build:gradle than 3.5.0 is available: 7.0.4. (There is also a newer version of 3.5.𝑥 available, if upgrading to 7.0.4 is difficult: 3.5.4)
```

We should suppress that warning so that important linter warning can be easier surfaced in the Github UI.

I tried to repro locally, but a ./gradlew lint doesn't show the same error in video_player. 

Related to: https://github.com/flutter/flutter/issues/88011

**Comment by vedantkulkarni** [comment]
hey can you specify , in which packages we have to suppress lint warnings regarding gradle version

**Comment by stuartmorgan** [comment]
All of them; this warning will appear in all packages at some point because we aren't continuously updating gradle versions.

**Comment by vedantkulkarni** [comment]
I can see that every package's gradle.build file has -> disable 'GradleDependency' in lint options, so what's the approach here, can you please guide me ?

**Comment by stuartmorgan** [comment]
`lint-android` is the plugin tools command that generates the report being parsed to create that UI. You should run it locally to see what the ID is.

**Comment by vedantkulkarni** [comment]
sorry , I'm not able to solve this issue

**Comment by stuartmorgan** [comment]
I checked locally, and the ID is `AndroidGradlePluginVersion`. I would expect we just need to suppress that everywhere.

**Comment by FXschwartz** [comment]
@stuartmorgan I checked three different packages, and the only warning I see is `WARNING:We recommend using a newer Android Gradle plugin to use compileSdk = 33` which can be suppressed with `android.suppressUnsupportedCompileSdk=33`

Is this a non-issue now?

**Comment by stuartmorgan** [comment]
> Is this a non-issue now?

No, see the bottom half of [this page](https://github.com/flutter/plugins/pull/7038/files) for instance, which has several of these.

**Comment by FXschwartz** [comment]
> AndroidGradlePluginVersion

While disabling the ID in each plugin I'm seeing some of these comments. Just want to confirm I'm good to uncomment the disable and remove the comment.

```
        // TODO(stuartmorgan): Enable when gradle is updated.
        // disable 'AndroidGradlePluginVersion'
```

**Comment by stuartmorgan** [comment]
IIRC I had to do that because of errors about it being an unrecognized option, so if it works now that should be fine.

**Comment by FXschwartz** [comment]
@stuartmorgan I believe this one can be closed now with my PR having been merged, correct?

**Comment by stuartmorgan** [comment]
Yes, thanks. It looks like the "-" between "Fixes" and the issue link in the PR description prevented GitHub's auto-close detection.
