### ISSUE TITLE
Linux Web Framework tests for release branches should checkout framework from same branch

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#95049]
Linux Web Framework tests fail very frequently on release branches because they checkout the latest version of the framework. To fix this problems we need to identify if a given PR is coming from a release branch and use the framework branch with the same name.

**Comment by godofredoc** [comment]
\cc @itsjustkevin @devoncarew @yjbanov this is the bug tracking the problems found with Linux Web Framework on release branches.

**Comment by godofredoc** [comment]
Examples:

https://ci.chromium.org/p/flutter/builders/prod/Linux%20stable%20Web%20Framework%20tests/27
https://ci.chromium.org/p/flutter/builders/prod/Linux%20stable%20Framework%20Smoke%20Tests/8

**Comment by CaseyHillers** [comment]
Closing as the release team hasn't seen these failures in the past few months
