### ISSUE TITLE
EditableText should show a loupe on iOS when moving the cursor

### ISSUE THREAD

**Issue by xster** [flutter/flutter#9507]
Theme text selection for iOS.

**Comment by xster** [comment]
(Searchable keyword: magnifier)

**Comment by cbracken** [comment]
Also worth noting that there are two different loupes for iOS, the round one for positioning and the rounded rect for selections.

I've little digging on this and if we want to have iOS provide this for us, I suspect should be solvable with a little more work on top of what we need for #9344. We'd need to subclass `UITextView` instead of `UIView` and to give the view a frame etc. Alternatively, we could reimplement ourselves.

**Comment by xster** [comment]
Having iOS provide it for us could be neat. But we would have to solve the philosophical divergence with the existing implementation in text_selection.dart I'm afraid.

**Comment by Hixie** [comment]
Cupertino widgets work is not on our near-term priority list. Moving to next milestone.

**Comment by xster** [comment]
getting it from the OS would definitely be worth trying. It's a departure from the Android text selection UI but it seems reasonable for something users are unlikely to modify.

**Comment by goderbauer** [comment]
SEO: magnifying glass

**Comment by vpdn** [comment]
I see the issue has been moved a few times from Q3/2018 to now Q1/2019. Is this still on the roadmap to be implemented? Thanks! 🙏

(We're working on a business app with lots of forms and this question keeps popping up).

**Comment by lifenautjoe** [comment]
This is a must for accessibility reasons. Any update on this?

**Comment by justinmc** [comment]
I'm unassigning myself so I don't stop anyone else from taking a look if there's interest, but I do intend to pick this up in the near future.

The current status is that there was a prototype built that still needs some work to match native behavior in iOS and Android.  There is a pretty big push for iOS text fidelity and this is on the list of things to implement.

**Comment by justinmc** [comment]
Does anyone know how to get the loupe to show up on iOS 13?  Long press and drag now just selects the text, and dragging the cursor looks like this:

![drag_cursor](https://user-images.githubusercontent.com/389558/60058442-44370880-969d-11e9-9d5d-1ae7a7d40806.gif)

**Comment by xster** [comment]
I wonder if they differentiated long press vs 3d touch. 3d touches can't be simulated on simulators and a mouse. Try with a magic trackpad.

**Comment by justinmc** [comment]
I tried it and 3d touch on the cursor starts dragging the cursor, and 3d touch elsewhere either moves the word or starts selection.

**Comment by tedhenry100** [comment]
This is critical! I cannot see the cursor under my finger and the app feels broken!! I'm using `TextFormField`.

**Comment by sdfsdhgjkbmnmxc** [comment]
+1

**Comment by d3xt3r2909** [comment]
Is there any progress on this one ?

**Comment by justinmc** [comment]
I'm quite sure that the loupe has been dropped from iOS 13 by Apple, so it seems that Flutter should not implement this feature.

However, Android Q has a similar feature now, so we may want to implement that loupe!

**Comment by tedhenry100** [comment]
Apple botched it by removing the loupe in iOS 13. 🤦‍♂️

They have been making fonts thicker thanks to user feedback so they might listen and bring back the loupe in iOS 14.

**Comment by vivchar** [comment]
I have the same issue, any update?

**Comment by justinmc** [comment]
The magnifying glass is back in iOS 15! https://9to5mac.com/2021/06/07/ios-15-brings-back-the-magnifying-glass-for-accurate-text-selection/

**Comment by matthew-carroll** [comment]
@justinmc be sure to invoice Apple for the time spent going back and forth :)

**Comment by Hacklone** [comment]
Without moving the cursor on long-press writing text in flutter is super clunky for iOS users :( 
So I think the main issue is not the loupe. 

Any plans on fixing cursor movement for iOS?

**Comment by kaseyrossanderson** [comment]
Now that it's back in the latest IOS 15 when is this going to be supported? We have request from our clients for this feature since it is strange behavior for users to see a different cursor effect in their app than the rest of the their phone.

Appreciate any update!

**Comment by justinmc** [comment]
It's on my plate to get this implemented soon, for iOS and Android.  No work done yet but I'll keep this updated.  I agree that Flutter really needs this.

**Comment by jenkliu** [comment]
Putting in an upvote for this – text editing is a core part of our app so this would significantly improve the user experience! 

Any updates on when it'll be on the roadmap? Thanks @justinmc !

**Comment by justinmc** [comment]
@jenkliu Yes, good timing!  @antholeole is taking on this project and starting some preliminary research.  We hope to ship something this summer for iOS and Android.  We'll keep this issue and https://github.com/flutter/flutter/issues/17617 updated with any progress.

**Comment by iosephmagno** [comment]
Any news about that? Magnifying glass is a core feature on ios textfield. Not having it looks like cross-platform, but even worse, common users would consider it just as a bug.

**Comment by antholeole** [comment]
@iosephmagno I'm working on it: development of the loupe is in full swing. Design doc should be out later this week 👍 

We hear you - I want this feature in too!

**Comment by matthew-carroll** [comment]
FYI - For those of you who **really** need it, you can build a magnifier yourself. I can't promise that you'll be able to respond to the right gestures when you try to apply it to a Flutter `EditableText`. But if you want to see how to build your own, check out implementation in `super_editor`: https://github.com/superlistapp/super_editor/blob/main/super_editor/lib/src/infrastructure/platforms/ios/magnifier.dart

**Comment by justinmc** [comment]
@kellysjung Done, thanks for catching that.  This should show the loupe in all of the same situations that native does.  If it doesn't please let me know by opening an issue and tagging me!

**Comment by justinmc** [comment]
Actually I spoke too soon, looks like longpress is currently broken but on the way soon: https://github.com/flutter/flutter/issues/108823
