### ISSUE TITLE
[google_maps_flutter] I expect to match the Marker's onTap area with the icon image

### ISSUE THREAD

**Issue by taku-kw** [flutter/flutter#95079]
In the current onTap area, tapping a position outside the icon image also reacts and feels uncomfortable.
As a result of checking the current onTap area, it is estimated to be a circle centered on latitude and longitude.
I expect it to react only when I tap the icon image.

**Comment by stuartmorgan** [comment]
The maps plugin's UI is all native UI from the underlying SDK. If you have feedback about the way it handles touches, you'll need to report it directly to Google Maps.

**Comment by taku-kw** [comment]
> The maps plugin's UI is all native UI from the underlying SDK. If you have feedback about the way it handles touches, you'll need to report it directly to Google Maps.

Thank you for reply & information!
I posted this issue to Google Maps SDK.
https://issuetracker.google.com/issues/210119725

Bye!
