### ISSUE TITLE
Curious !!

### ISSUE THREAD

**Issue by MrR1pp3r** [flutter/flutter#95082]
Well I recently upgrade my Flutter framework & create new app > via flutter create ~/animeHeaven

but when i run my app i see...
Its Installing Build-Tools Version : 29 & Platfrom Sdk - 31..
But I have Android 11 a.k.a API 30
I knew that no make sense.. because API 31 application can work on lower API.. but I'm curious about Build-Tool Version - 29.0.2

Everytime i make changes like add Google Sign or Firebase.. then its change into 29.0.3 or in different version... but WHY???

Also i see build.gradle file.. & after i see.. im too Curious, WHy you guys use default config from flutter_gradle.. 

Means.. how i change minimum gradle to 30.0.3 or 31.0.0

if i change in flutter_gradle/flutter.gradle then all new app which i create.. have same property...

PS: IF YOU MAKE ANY CHANGE THEN PLEASE RELEASE AN EXAMPLE TOO.... (FOR HOW TO CHANGE DEFAULT VALUE..)
OLD GRADLE FILE KINDA USEFULL...

**Comment by stuartmorgan** [comment]
Please use one of the resources listed at https://flutter.dev/community#community-grid for questions and discussion. The issue tracker is specifically for bug reports and feature requests.
