### ISSUE TITLE
Parsing local JSON file in the background

### ISSUE THREAD

**Issue by Mu7ammadRasul** [flutter/flutter#95095]
I love `Flutter` that is why i issue this, so basically i'm working on a project that depends on notifying users with a `local_notification` for an upcoming `task`, the `task` has a `date` and the date is a specific `time` that goes through `local_notification` in order to notify the user in time, i tried `Workmanager` and i understood of it's limitation that's why i'm left with no initial solution,
the `method` i have is:
```
void callbackDispatcher(){
  Workmanager().executeTask((taskName, inputData) {
   test() async {
    final String jsonString = await DefaultAssetBundle.of(context).loadString('assets/json/employee.json'); //context is not allowed
    final List result = json.decode(jsonString);

   return result.asMap().forEach((index, value) {
      var time= value['city']['Month'][DateTime.now().month-1]['day'][DateTime.now().day-1]['date'];
      var h = int.parse(time.toString().substring(0, 2));
      var m = int.parse(time.toString().substring(3, 5));

       NotificationAPI.showScheduledNotification(
                          id: 5,
                          title:'test',
                          body: 'test',
                          payload: 'payload',
                          h:h,
                          m:m, 
                          s: 0

                        );
       print('isha $h:$m');
   });
   }
    test();
    return Future.value(true);
  });
}
```
`initState`:
```
initState(){
    super.initState();
Workmanager().initialize(
      callbackDispatcher,
      isInDebugMode: true
    );

    Workmanager().registerPeriodicTask(
      "1",
      "workTimes",
      frequency: Duration(hours: 12)
    );
  listenNotification();
}
```
the json is parsing with a `context`, while it's not allowed to be ran in the `background`, what could be a solution for this case?

**Comment by stuartmorgan** [comment]
Please use one of the resources listed at https://flutter.dev/community#community-grid for questions and discussion. The issue tracker is specifically for bug reports and feature requests in Flutter itself.
