### ISSUE TITLE
[Web] Support minified index.html or minify it automatically when building

### ISSUE THREAD

**Issue by krisztianodor** [flutter/flutter#95097]
## Use case / Problem

There are features which are breaks if the index.html is minifed by the developer manually.

For example, the `serviceWorkerVersion` javascript variable does not update automatically when the web app is built so the users do not see the fresh app after deploy. The problem is that the value of `serviceWorkerVersion` is always `null` in the build. It is because in the minified index.html the affected part looks like this:

`var serviceWorkerVersion=null`

while the web.dart file is looking for this to change:

`var serviceWorkerVersion = null`

The version changer part in the flutter code:

https://github.com/flutter/flutter/blob/895beb04bb7ae9bed508b27a0f59c5328c7ea7c9/packages/flutter_tools/lib/src/build_system/targets/web.dart#L379-L383

There may be other places / features involved in the problem.

## Proposal

The best would be if flutter would minify the index.html (while also removing unnecessary comments) before doing anything with it. The built version should be minified anyway.

**Comment by ditman** [comment]
You should be able to post-process your flutter web app **after it's been built** inside `build/web`, I think?

(We've also made the index.html much smaller in the current stable, and split it into a flutter.js file and a small index.html file, so this might not be as much of an issue anymore?). See [the new index.html](https://github.com/flutter/gallery/blob/master/web/index.html#L76).
