### ISSUE TITLE
NestedScrollView

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#9510]
A common use case for SliverFillRemaining is to fill up a body with a background color. For instance, if I have a SliverList that happens to be too short, I would want the background color to match SliverList item background color. We used to be able to do this by defining a Container that expanded with a BoxDecoration. However something like this does not work:

```Dart
    return new SliverFillRemaining(
      child: new Container(
        decoration: new BoxDecoration(backgroundColor: Colors.white),
        child: new SliverList(...),
      ),
    );
```
Since Container expects a box layout object.

**Comment by abarth** [comment]
Does the following work instead:

```dart
    return new SliverFillRemaining(
      child: new Container(
        decoration: new BoxDecoration(backgroundColor: Colors.white),
        child: new ListView(...),
      ),
    );
```

SliverFillRemaining's child is a box, which means it should accept a Container.  Container's child is also a box, so it wants a ListView (which is a box) rather than a SliverList (which is a sliver).

**Comment by Hixie** [comment]
Nesting a ListView in a CustomScrollView is going to have weird effects.

Why not wrap the whole CustomScrollView in a container with the color?

**Comment by mehmetf** [comment]
Separation of concerns. We are trying to change content's background, not the entire scaffold's. Concrete example is tabs. You can have 5 tabs each with a different background body color. It would be ideal for widget that renders the body to decide what its background color should be not the scaffold.

It _can_ be done, it just doesn't make much sense.

**Comment by Hixie** [comment]
I just mean wrap the ScrollView in the container, not the whole Scaffold.

**Comment by mehmetf** [comment]
I understand but CustomScrollView isn't part of the tab body because it has to contain the app bar. It would be quite odd to structure the app so that each tab provides an app bar.

Besides, CustomScrollView is sort of equivalent to Scaffold.  When I was doing the migration to slivers, most of my scaffold code basically transformed to this:

```new Scaffold(body: new CustomScrollView(...));```

There's nothing much left in Scaffold :-) so to do what you are suggesting, I would do:

```new Scaffold(body: new Container(... , child: new CustomScrollView()));```

From app modularity point of view, this is equivalent to wrapping scaffold.

As I said Ian, all of this is possible. It is just a very counter-intuitive way of thinking about app design.

**Comment by Hixie** [comment]
Ah, if your specific case is a scrollable app bar with a tab bar which itself controls a page view inside the scroll view and which itself has further nested lists inside it, you want NestedScrollView, which hasn't landed yet. Under NestedScrollView, you would want to put the Container around the contents of each PageView.
NestedScrollView is https://github.com/flutter/flutter/pull/9070

**Comment by abarth** [comment]
NestedScrollView has landed.  I'm going to close this bug, but please feel free to re-open it if NestedScrollView doesn't meet your needs.  @Hixie has volunteered to answer questions about how to use NestedScrollView for this purpose.
