### ISSUE TITLE
[Typo] Wiki - Upgrading pre 1.12 Android projects

### ISSUE THREAD

**Issue by Prince-Mendiratta** [flutter/flutter#95105]
Hi team, thank you for your efforts!

Whilst going through the wiki for upgrading pre v1.12 projects, I noticed a small typo in the same. I have listed the details below - 

**Wiki Article** - https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects
**Incorrect part** - 
![image](https://user-images.githubusercontent.com/54077356/145702645-675b37f7-0fc3-42e7-8632-014d6e128ede.png)

**Correction** - It should be `from` instead of `to` on the highlighted text.

**Comment by stuartmorgan** [comment]
That's not a typo; it's correct as written. `AndroidManifest.xml` has a reference to `.MainActivity`; that reference needs to be changed.
