### ISSUE TITLE
[web] I have a few pages set to deferred.  I saw it fail to load, refresh fixed it

### ISSUE THREAD

**Issue by sgehrman** [flutter/flutter#95100]
I set up a bunch of pages deferred like below:

I visited my live site today and this shop page had a failure in the console.  Forgot to copy the exact error, but it was a failure to load of some kind.  Page worked fine after  a reload.

Is this rock-solid on the web?  I'll probably just remove it for now.

 ```dart
import 'package:chargebee_server/shop_widget/shop_panel/shop_panel.dart'
    deferred as shop;

Widget _shopPanel() {
    return FutureBuilder<dynamic>(
      future: shop.loadLibrary(),
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.done) {
          return  ShopPanelWidget();
        }
        return const SizedBox();
      },
    );
  }
```

**Comment by maheshmnj** [comment]
HI @sgehrman, Thanks for filing the issue. As per the [docs](https://docs.flutter.dev/perf/deferred-components) deffered components are only supported for Android as of today.

>   Note: This feature is currently only available on Android, taking advantage of Android and Google Play Stores’ dynamic feature modules to deliver the deferred components packaged as Android modules. Deferred code does not impact other platforms, which continue to build as normal with all deferred components and assets included at initial install time.
  
So inconsistency and unusual behavior on other platforms (web in your case) is expected.
