### ISSUE TITLE
Is it possible to set the value of bodyScrimColor?

### ISSUE THREAD

**Issue by Nbioni** [flutter/flutter#95122]
I'm developing a dashboard that clicking profile on the header will open an endDrawer that applies a background shadow only to the application body, I did this by calling the showBodyScrim event that allows me to pass whether we should present the background shading and its opacity.

I wish I could choose the background color of my bodyScrim. That is, I would like to be able to somehow set the value of "_bodyScrimColor".

My questions:

- Is there a better way to open an endDrawer without applying shading to my AppBar and being able to pick the drop shadow color? 
- If not, how could I choose the color of my bodyScrimColor?

![my_dashboard_example](https://user-images.githubusercontent.com/43020119/145725091-a86c7e82-c5fa-419e-bc1d-f2ae100a2572.gif)

**Comment by mamuseferha** [comment]
Hi @Nbioni, please see if this stackoverflow answer works for you https://stackoverflow.com/a/55961943. 

This doesn't seem like a bug or feature request so I'll go ahead and close this now. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by Nbioni** [comment]
I'm requesting a resource, this link you sent me doesn't serve me, because when I set "drawerScrimColor: Colors.black" it happens that when I open my drawer my AppBar is also overlaid by color. As already explained, I intend to shade only the application body, I managed to do this by setting "**drawerScrimColor: Colors.transparent**" and calling the function "**showBodyScrim**" which by default uses the color "**_bodyScrimColor = Colors.black**". However I would like to be able to choose the background color "bodyScrimColor"

`... drawerScrimColor: Colors.black,
 onEndDrawerChanged: (isEndDrawerOpened){
    isEndDrawerOpened ? _key.currentState!.showBodyScrim(true, 0.3) 
    : _key.currentState!.showBodyScrim(false, 0.3);
 }, ...`

![my_dashboard_example2](https://user-images.githubusercontent.com/43020119/145817770-56656ee7-ad77-4453-b1ab-6a336570bae5.gif)

`drawerScrimColor: Colors.transparent,
      onEndDrawerChanged: (isEndDrawerOpened){
        isEndDrawerOpened ? 
          _key.currentState!.showBodyScrim(true, 0.3) : 
        _key.currentState!.showBodyScrim(false, 0.3);
      }`

![my_dashboard_example](https://user-images.githubusercontent.com/43020119/145817930-3dac016b-c970-431b-84ee-036d5d5fbf4a.gif)

**Comment by mamuseferha** [comment]
Hi @Nbioni, can you provide a complete and minimal reproducible code sample so I can better understand you as well as your `flutter doctor -v`?
