### ISSUE TITLE
Dart roll is stopped for updates to customer tests

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#95129]
The most recent attempt is here https://github.com/flutter/flutter/pull/95128

The roll is failing because customer tests reference `Platform.packageRoot` which is removed from the Dart SDK starting with https://github.com/flutter/engine/pull/30251.

I will revert the Dart rolls back before that to unblock the Engine -> Framework roll.

**Comment by dnfield** [comment]
We probably want to get rainbow monkey to remove the use of deprecated API.. and/or provide a `dart fix` for it?

**Comment by zanderso** [comment]
@mit-mit @Hixie

**Comment by zanderso** [comment]
Downgrading from P0 since the Engine roll is moving again.

**Comment by mit-mit** [comment]
> or provide a dart fix for it?

I unfortunately don't think there is a meaningful automated fix for this. The `packageRoot` API wasn't just deprecated, it has been hardcoded to always return `null` (i.e. it was broken). If anyone was using it, they either didn't really need it (it did nothing), or they were dependent on it's broken behavoir. The right fix is to simply remove any use of it.

I should have posted a breaking change not though. I'll do that now.

**Comment by Hixie** [comment]
I think this is unblocked now?

**Comment by zanderso** [comment]
Should be unblocked, but we should observe Dart rolling through to the framework before closing. Current roll attempt is here: https://github.com/flutter/flutter/pull/95294. Looks like it's failing on ci.yaml validation? @CaseyHillers

**Comment by CaseyHillers** [comment]
I'll reschedule builds against the PR. I have a fix for this in https://github.com/flutter/cocoon/pull/1524

**Comment by CaseyHillers** [comment]
https://github.com/flutter/flutter/pull/95294 has merged
