### ISSUE TITLE
Bump tool to Gradle/AGP 7.0+  - OpenJDK 11

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#95131]
Link:
https://luci-milo.appspot.com/p/flutter/builders/staging/Mac_android%20run_release_test/412

The test validates the flutter release does not output errors to stderr but we are getting the following:

```
[run_release_test] [STDOUT] run:stderr: Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
[run_release_test] [STDOUT] run:stderr: Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
[run_release_test] [STDOUT] run:stderr: Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
[run_release_test] [STDOUT] run:stderr: Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
[run_release_test] [STDOUT] run:stderr: Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
```

**Comment by godofredoc** [comment]
\cc @blasten

**Comment by blasten** [comment]
To fix this issue, we need to migrate the example apps to Gradle 7.0. 

@godofredoc Based on the actionable items you shared after the last tree breakage, when would it be a good time to re-land the version bump?

**Comment by godofredoc** [comment]
Property changes are now validated on presubmit and limited capacity for devicelab is available for presubmit.

You can make the changes and temporarily enable the devicelab tests as part of your change. Once all the devicelab tests are passing you can remove the devicelab tests from presubmit before landing.

**Comment by godofredoc** [comment]
This issue has been on the ticket queue for more than a month with no updates. Moving out of the ticket queue.

**Comment by godofredoc** [comment]
@blasten is there anyone working on this?

**Comment by blasten** [comment]
@godofredoc Yes: https://github.com/flutter/flutter/pull/99723
