### ISSUE TITLE
Please Add Engineering notation of double variable in dart flutter 

### ISSUE THREAD

**Issue by alihassan143** [flutter/flutter#95143]

**Comment by darshankawar** [comment]
@alihassan143 
Can you elaborate on the use case (example) where you are facing this limitation and how adding the proposed notation would help to resolve the use case ?

**Comment by alihassan143** [comment]
double value =19862704051982800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;


    setState(() {
      scientific = value.toStringAsExponential(4).replaceAll("e", "x10");
      enotation = value.toStringAsExponential(4).toString();
    });
value.toStringAsExponential() that function only convert the double value into scientific notation but their is engineering notation that is available in other languages engineering notation is the power of 10 that is divisible by 3 i want that function in double so i can covert that engineering notation and show this value in screen

**Comment by darshankawar** [comment]
@alihassan143 
I think this need to be reported in dart lang repo: https://github.com/dart-lang/sdk/issues, so please open this issue in it.
Closing from here.
