### ISSUE TITLE
[tool_crash] RPCError

### ISSUE THREAD

**Issue by asyari-ft** [flutter/flutter#95152]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
RPCError
```

```
```
[✓] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.17763.2300], locale en-ID)
    • Flutter version 2.0.5 at E:\flutter
    • Framework revision adc687823a (8 months ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at E:\program files\MOBEL\android-sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_SDK_ROOT = E:\program files\MOBEL\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[✓] VS Code (version 1.63.0)
    • VS Code at C:\Users\STARK INDUSTRIES\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • RMX1971 (mobile) • 79ed35e1 • android-arm64  • Android 11 (API 30)
    • Chrome (web)     • chrome   • web-javascript • Google Chrome 96.0.4664.93

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: 4b50ca7f7fbf56be72e54cd200825b760416a356
### Plugins
firebase_core-1.2.0
firebase_core_web-1.1.0
firebase_messaging-10.0.0
firebase_messaging_web-2.0.0

**Comment by danagbemava-nc** [comment]
Hi @asyari-ft, this issue was fixed as per https://github.com/flutter/flutter/issues/70579#issuecomment-759653731. 

Kindly upgrade to the latest version of `stable` and let me know if you still experience this issue. 

Closing as this has already been fixed. 

If you still experience this issue after upgrading to the latest version of stable, kindly provide the new output of `flutter doctor -v` and steps to reproduce and I will reopen.

Thank you
