### ISSUE TITLE
Android external keyboard enter key is not working

### ISSUE THREAD

**Issue by selvam920** [flutter/flutter#95158]
i have checked flutter android app in android 9 TV, external keyboard enter key is not working.
There are two enter key in my keyboard, one is above shift key and another one is in keypad. in the keypad enter key is working fine but the above shift enter key is not working

Flutter 2.6.0-12.0.pre.999 • channel master • https://github.com/flutter/flutter.git
Framework • revision 895beb04bb (2 days ago) • 2021-12-10 18:54:10 -0800
Engine • revision 79f750d4a5
Tools • Dart 2.16.0 (build 2.16.0-85.0.dev) • DevTools 2.9.1

**Comment by danagbemava-nc** [comment]
Hi @selvam920, thanks for filing the issue. 

Please provide the full output of `flutter doctor -v` and the full log of `flutter run -v`. 

Thank you
