### ISSUE TITLE
Flutter In App Purchase Crashes on IOS when buyConsumable

### ISSUE THREAD

**Issue by akshayindia** [flutter/flutter#95166]
Hi Team,

I'm facing this issue in IOS while using the In-App purchase plugin. The plugin run when I clone it and seemed no issue but as soon as I integrate it with my application. My application got crashed I've attested the video as well. 

Also when I open my application again and if the purchase is done then it will ask to complete the earlier purchase then only you can do the next purchase but when I tried to debug the stream of data of purchase detail didn't come. 

I'm using Xcode 13 & IOS 15 simulator. I also tested this on a real device.

**Comment by akshayindia** [comment]
3. ... 

<details>'

on Xcode I'm seeing this error - Thread 1: "*** -[_NSPlaceholderData initWithContentsOfURL:options:maxLength:error:]: nil URL argument"



```dart
```

</details>

This contains flutter verbose output 

[flutter in app purchase.pdf](https://github.com/flutter/flutter/files/7704029/flutter.in.app.purchase.pdf)

**Comment by akshayindia** [comment]
The issue in Video format 

https://user-images.githubusercontent.com/36562389/145818495-6c6fc4e6-3a98-4f69-94ab-b38f18e99feb.mov

**Comment by akshayindia** [comment]
Small reproducible code - 



## Steps to Reproduce



1. Execute `flutter run` on the code sample 
// // ignore_for_file: unused_local_variable

// ignore_for_file: unused_local_variable


import 'dart:async';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:in_app_purchase_ios/in_app_purchase_ios.dart';


import 'package:in_app_purchase_platform_interface/in_app_purchase_platform_interface.dart';

import 'consumable_store.dart';

const Color appColor = Colors.orange;
Color? darkOrange = Colors.deepOrange[800];
Color? swiggyOrange = Colors.orange[900];

// const bool _kAutoConsume = true;





class PackageDetailScreen extends StatefulWidget {
  @override
  PackageDetailScreenState createState() => PackageDetailScreenState();
  static const routeName = '/checkoutIOS';

}

class PackageDetailScreenState extends State<PackageDetailScreen> {
  // ignore: invalid_use_of_visible_for_testing_member
  final InAppPurchaseIosPlatform _inAppPurchase = InAppPurchaseIosPlatform();
  List<String> _notFoundIds = [];
  List<ProductDetails> _products = [];
  List<PurchaseDetails> _purchases = [];
  List<String> _consumables = [];
  bool _isAvailable = false;
  bool _purchasePending = false;
  bool _loading = true;
  String? _queryProductError;
   String _kConsumableId1 = 'Stud001';
 String _kConsumableId2 = 'STU002';

 List<String> _kProductIds = <String>[
  "Stud001",
 "STU002"
];

  @override
  void initState() {
    print(88888);
    print(88888);

    print(88888);

    print(88888);

    final Stream<List<PurchaseDetails>> purchaseUpdated =
        _inAppPurchase.purchaseStream;
  purchaseUpdated.listen((purchaseDetailsList) {
    print(9999);
      _listenToPurchaseUpdated(purchaseDetailsList);
    }, onDone: () {
    print('akshay jain');
    }, onError: (error) {
      // handle error here.
    });
    initStoreInfo();
    super.initState();
  }

  Future<void> initStoreInfo() async {
    final bool isAvailable = await _inAppPurchase.isAvailable();
    if (!isAvailable) {
      setState(() {
        _isAvailable = isAvailable;
        _products = [];
        _purchases = [];
        _notFoundIds = [];
        _consumables = [];
        _purchasePending = false;
        _loading = false;
      });
      return;
    }



    ProductDetailsResponse productDetailResponse =
        await _inAppPurchase.queryProductDetails(_kProductIds.toSet());
    if (productDetailResponse.error != null) {
      setState(() {
        _queryProductError = productDetailResponse.error!.message;
        _isAvailable = isAvailable;
        _products = productDetailResponse.productDetails;
        _purchases = [];
        _notFoundIds = productDetailResponse.notFoundIDs;
        _consumables = [];
        _purchasePending = false;
        _loading = false;
      });
      return;
    }

    if (productDetailResponse.productDetails.isEmpty) {
      setState(() {
        _queryProductError = null;
        _isAvailable = isAvailable;
        _products = productDetailResponse.productDetails;
        _purchases = [];
        _notFoundIds = productDetailResponse.notFoundIDs;
        _consumables = [];
        _purchasePending = false;
        _loading = false;
      });
      return;
    }

    List<String> consumables = await ConsumableStore.load();
    setState(() {
      _isAvailable = isAvailable;
      _products = productDetailResponse.productDetails;
      _notFoundIds = productDetailResponse.notFoundIDs;
      _consumables = consumables;
      _purchasePending = false;
      _loading = false;
    });
  }

  @override
  void dispose() {
    // if (Platform.isIOS) {
    //   var iosPlatformAddition = _inAppPurchase;
    //   iosPlatformAddition.setDelegate(null);
    // }
 
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    
    List<Widget> stack = [];
    if (_queryProductError == null) {
      stack.add(
        ListView(
          children: [
            _buildConnectionCheckTile(),
            _buildProductList(),
            _buildConsumableBox(),
          ],
        ),
      );
    } else {
      stack.add(Center(
        child: Text(_queryProductError!),
      ));
    }
    if (_purchasePending) {
      stack.add(
        Stack(
          children: [
            Opacity(
              opacity: 0.3,
              child: const ModalBarrier(dismissible: false, color: Colors.grey),
            ),
            Center(
              child: CircularProgressIndicator(),
            ),
          ],
        ),
      );
    }

    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('IAP Example'),
        ),
        body: Stack(
          children: stack,
        ),
      ),
    );
  }

  Card _buildConnectionCheckTile() {
    if (_loading) {
      return Card(child: ListTile(title: const Text('Trying to connect...')));
    }
    final Widget storeHeader = ListTile(
      leading: Icon(_isAvailable ? Icons.check : Icons.block,
          color: _isAvailable ? Colors.green : ThemeData.light().errorColor),
      title: Text(
          'The store is ' + (_isAvailable ? 'available' : 'unavailable') + '.'),
    );
    final List<Widget> children = <Widget>[storeHeader];

    if (!_isAvailable) {
      children.addAll([
        Divider(),
        ListTile(
          title: Text('Not connected',
              style: TextStyle(color: ThemeData.light().errorColor)),
          subtitle: const Text(
              'Unable to connect to the payments processor. Has this app been configured correctly? See the example README for instructions.'),
        ),
      ]);
    }
    return Card(child: Column(children: children));
  }

  Card _buildProductList() {
    if (_loading) {
      return Card(
          child: (ListTile(
              leading: CircularProgressIndicator(),
              title: Text('Fetching products...'))));
    }
    if (!_isAvailable) {
      return Card();
    }
    final ListTile productHeader = ListTile(title: Text('Products for Sale'));
    List<ListTile> productList = <ListTile>[];
    if (_notFoundIds.isNotEmpty) {
      productList.add(ListTile(
          title: Text('[${_notFoundIds.join(", ")}] not found',
              style: TextStyle(color: ThemeData.light().errorColor)),
          subtitle: Text(
              'This app needs special configuration to run. Please see example/README.md for instructions.')));
    }

    // This loading previous purchases code is just a demo. Please do not use this as it is.
    // In your app you should always verify the purchase data using the `verificationData` inside the [PurchaseDetails] object before trusting it.
    // We recommend that you use your own server to verify the purchase data.
    Map<String, PurchaseDetails> purchases =
        Map.fromEntries(_purchases.map((PurchaseDetails purchase) {
      if (purchase.pendingCompletePurchase) {
        _inAppPurchase.completePurchase(purchase);
      }
      return MapEntry<String, PurchaseDetails>(purchase.productID, purchase);
    }));
    productList.addAll(_products.map(
      (ProductDetails productDetails) {
        // PurchaseDetails? previousPurchase = purchases[productDetails.id];
        return ListTile(
            title: Text(
              productDetails.title,
            ),
            subtitle: Text(
              productDetails.description,
            ),
            trailing: TextButton(
                    child: Text(productDetails.price),
                    style: TextButton.styleFrom(
                      backgroundColor: Colors.green[800],
                      primary: Colors.white,
                    ),
                    onPressed: () {
                       PurchaseParam purchaseParam = PurchaseParam(
                          productDetails: productDetails,
                          // applicationUserName: null,
                          // sandboxTesting: false,
                        );
                    

                        _inAppPurchase.buyConsumable(
                            purchaseParam: purchaseParam,
                            autoConsume: true);
                  
                    },
                  ));
      },
    ));

    return Card(
        child:
            Column(children: <Widget>[productHeader, Divider()] + productList));
  }
// no use
  Card _buildConsumableBox() {
    if (_loading) {
      return Card(
          child: (ListTile(
              leading: CircularProgressIndicator(),
              title: Text('Fetching consumables...'))));
    }
    if (!_isAvailable || _notFoundIds.contains(_kConsumableId1)) {
      return Card();
    }
    final ListTile consumableHeader =
        ListTile(title: Text('Purchased consumables'));
    final List<Widget> tokens = _consumables.map((String id) {
      return GridTile(
        child: IconButton(
          icon: Icon(
            Icons.stars,
            size: 42.0,
            color: Colors.orange,
          ),
          splashColor: Colors.yellowAccent,
          onPressed: () => consume(id),
        ),
      );
    }).toList();
    return Card(
        child: Column(children: <Widget>[
      consumableHeader,
      Divider(),
      GridView.count(
        crossAxisCount: 5,
        children: tokens,
        shrinkWrap: true,
        padding: EdgeInsets.all(16.0),
      )
    ]));
  }

 // no use
  Future<void> consume(String id) async {
    await ConsumableStore.consume(id);
    final List<String> consumables = await ConsumableStore.load();
    setState(() {
      _consumables = consumables;
    });
  }

  void showPendingUI() {
    setState(() {
      _purchasePending = true;
    });
  }

  void deliverProduct(PurchaseDetails purchaseDetails) async {
    print('Akshay you have done it');
    // DateFormat('yyyy-MM-dd HH:mm:ss').format(date);
         print(purchaseDetails.transactionDate);
      print(purchaseDetails.productID);
    // IMPORTANT!! Always verify purchase details before delivering the product.
    if (purchaseDetails.productID == _kConsumableId1) {
      print(purchaseDetails.transactionDate);
      print(purchaseDetails.productID);
      await ConsumableStore.save(purchaseDetails.purchaseID!);
      List<String> consumables = await ConsumableStore.load();
      setState(() {
        _purchasePending = false;
        _consumables = consumables;
      });
    } else {
      setState(() {
        _purchases.add(purchaseDetails);
        _purchasePending = false;
      });
    }
  }

  void handleError(IAPError error) {
    setState(() {
      _purchasePending = false;
    });
  }



  void _listenToPurchaseUpdated(List<PurchaseDetails> purchaseDetailsList) {
    print('all okay purchase');
    purchaseDetailsList.forEach((PurchaseDetails purchaseDetails) async {
      if (purchaseDetails.status == PurchaseStatus.pending) {
        showPendingUI();
      } else {
              print(purchaseDetails.status);

        if (purchaseDetails.status == PurchaseStatus.error) {
            print(PurchaseStatus.error.index);

          handleError(purchaseDetails.error!);
        } else if (purchaseDetails.status == PurchaseStatus.purchased){
    
            deliverProduct(purchaseDetails);
          
        }
    
        if (purchaseDetails.pendingCompletePurchase) {
          print (87676668686);
          await _inAppPurchase.completePurchase(purchaseDetails);
        }
      }
    });
  }

  

}

**Comment by akshayindia** [comment]
flutter doctor -v output 




[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-arm, locale en-IN)
    • Flutter version 2.5.3 at /Users/akshayjain/FlutterProjects/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (8 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/akshayjain/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.63.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • iPhone 12 (mobile) • 2440852B-E828-46AB-B781-5ADBA902C943 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0
      (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 96.0.4664.93

• No issues found!

</details>


<!--
      Consider also attaching screenshots and/or videos to better
      illustrate the issue.

      You can upload them directly on GitHub.
      Beware that video file size is limited to 10MB.


https://user-images.githubusercontent.com/36562389/145815623-dedd4b43-b70d-4431-bd60-7cf40980eaec.mov

**Comment by darshankawar** [comment]
@akshayindia 
Thanks for the report. Can you provide us the complete versbose log in a text file instead of pdf ? The pdf you shared has more than 1200 pages so it's tough to go through each of them.
What error does it throw when it crashes ? Can you provide the log of it as well ?
Also, what plugin version are you using ?

**Comment by akshayindia** [comment]
Hi,

The primarily cause of this issue is Google sign in package.

Either you can use Google sign in or Apple pay in app purchase.

If I use both (in app purchase & Google sign in) on in app purchase screen
the app got crashed.

**Comment by akshayindia** [comment]
I also tried in pubspec.yaml under dependency section -
In app purchase - any
Google sign in - any

& Other permutations and combinations of it & different versions of Google
sign in and in app purchase but the app crash on in app purchase screen.

So I finally removed the Google sign in dependency.

Also one last thing when buying consumer able I got in app purchase stream.
During the payment process if it some struck. Then buying it again show
error -

Your previous purchases is incomplete. But I am not any stream data.

**Comment by darshankawar** [comment]
> Either you can use Google sign in or Apple pay in app purchase.

Depending on which platform (Android or iOS) you are using `in_app_purchase`, you'll need to use either of them, probably not both at the same time, so I think this issue is sorted per your findings.



> Also one last thing when buying consumer able I got in app purchase stream. During the payment process if it some struck. Then buying it again show error - Your previous purchases is incomplete. But I am not any stream data.

For this, please file a new issue with all requested details in the issue template.
Closing from here as your original issue seems to have resolved after removing google_sign_in plugin.
