### ISSUE TITLE
Overscroll indicator appears on top the appbar rather than the scrollable area when slivers are used

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#9516]
When we use a scaffold setup like so:

```Dart
   body: new CustomScrollView(
      slivers: [
        new SliverAppBar(
            title: new AppBarTitle(title: gtString.notificationDetail)),
        new CardContainer(cards: [
           new NotificationInfoCard(timestamp: widget.timestamp),
           new NotificationAccountCard(timestamp: widget.timestamp),
           new NotificationSiteCard(timestamp: widget.timestamp),
       ]),
```

The overscroll indicator appears on top of the app rather than within the card container.

**Comment by Hixie** [comment]
Why is that wrong?

**Comment by mehmetf** [comment]
It is not wrong from eng point of view (as the entire area is scrollable).

It is wrong from UX point of view (only the body is scrollable, the app bar just happens to hide when you scroll).

**Comment by Hixie** [comment]
Do you have any UX guidelines on this? It's a subtle area (e.g. there are at least four different kinds of scrolling app bars and they may have different "correct" behaviour) so it would be ideal if there was something concrete we could look at...

**Comment by mehmetf** [comment]
I looked and I could not find a material design example for this. However:

- On iOS, we have elastic overscroll. It would be quite weird if the entire app was elastic since appbar can be pulled down. No other app has that behavior AFAIK.

- Same with Android. The overscroll indicator on native android implementation is under the appbar even with a collapsible one. This is natural on Android because the scrolling area is only the content.

**Comment by Hixie** [comment]
That makes sense.

**Comment by Hixie** [comment]
cc @HansMuller

**Comment by xster** [comment]
Merging into #13253
