### ISSUE TITLE
 Connection closed before full header was received

### ISSUE THREAD

**Issue by richard457** [flutter/flutter#95164]
Connection closed before full header was received on android 10 HTTP throws this error randomly.

**Comment by richard457** [comment]
ClientException: Connection closed before full header was received
  File "io_client.dart", line 66, in IOClient.send

**Comment by danagbemava-nc** [comment]
Hi @richard457, 

Please provide a complete minimal reproducible code sample, as well as the output of `flutter doctor -v` and `flutter run -v` as well as the full error logs. 

For future reference, please fill out the issue template the next time you're filing an issue. 

Thank you
