### ISSUE TITLE
we can't use the `const` keyword for `MultiChildRenderObjectWidget`s

### ISSUE THREAD

**Issue by mohammadtaherri** [flutter/flutter#95179]
in Flutter widgets are immutable and they often have `const constructor`.but for `MultiChildRenderObjectWidget`s we can't use `const` keyword because its constructor has a body and it can't have a const constructor.

The following code describes the `MultiChildRenderObjectWidget`'s constructor:

```
MultiChildRenderObjectWidget({Key? key, this.children = const <Widget>[]})
      : assert(children != null),
        super(key: key) {
    assert(() {
      for (int index = 0; index < children.length; index++) {
        // TODO(a14n): remove this check to have a lot more const widget
        if (children[index] == null) {
          throw FlutterError(
            "$runtimeType's children must not contain any null values, "
            'but a null value was found at index $index',
          );
        }
      }
      return true;
    }()); // https://github.com/dart-lang/sdk/issues/29276
  }
```
as you see the constructor's body checks that children should not be `null`.but after null safety this check is redundant because the input argument type is `List<Widget>` and therefore it can't accept a `null` value for child.therefore we can remove the constructor's body.

**Comment by nt4f04uNd** [comment]
See https://github.com/flutter/flutter/pull/92628

**Comment by darshankawar** [comment]
Also https://github.com/flutter/flutter/pull/88359#issuecomment-916471689 and see if it answers your question as why you can't use `const`.

**Comment by mohammadtaherri** [comment]
@darshankawar 
Thanks you.

**Comment by darshankawar** [comment]
Assuming the links answers your question, I am going ahead and closing this.
