### ISSUE TITLE
Setting dart version to 2.15 on beta channel errors

### ISSUE THREAD

**Issue by NebulaFox** [flutter/flutter#95173]
On version `2.8.0-3.3.pre` of the beta channel, setting the dart version in the `pubspec` returns

```
The current Dart SDK version is 2.15.0-268.18.beta.

Because App requires SDK version >=2.15.0 <3.0.0, version solving failed
```

## Steps to Reproduce

1. Switch to beta
2. Set dart version to 2.15
3. run `flutter pub get`

**Expected results:**

Dart 2.15 being supported in the beta channel, as it is released on stable.

**Actual results:** 

<details>
<summary>Error of flutter pub get</summary>

```
The current Dart SDK version is 2.15.0-268.18.beta.

Because App requires SDK version >=2.15.0 <3.0.0, version solving failed
```

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 2.8.0-3.3.pre, on Mac OS X 10.14.6 18G9323 darwin-x64, locale
    en-GB)
    • Flutter version 2.8.0-3.3.pre at /usr/local/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 262b70ece1 (12 days ago), 2021-12-01 13:00:48 -0800
    • Engine revision 06a7363b0c
    • Dart version 2.15.0 (build 2.15.0-268.18.beta)
```

</details>

**Comment by darshankawar** [comment]
Seeing the same behavior:

```
Running "flutter pub get" in ios_bug...                         
The current Dart SDK version is 2.15.0-268.18.beta.

Because ios_bug requires SDK version >=2.15.0 <3.0.0, version solving failed.
pub get failed (1; Because ios_bug requires SDK version >=2.15.0 <3.0.0, version solving failed.)
Process finished with exit code 1
```

Whereas, on latest stable (Dart 2.15), get no issues:

```
Running "flutter pub get" in ios_bug...                          2,609ms
Process finished with exit code 0
```

<details>
<summary> beta flutter doctor -v </summary>

```
[✓] Flutter (Channel beta, 2.8.0-3.3.pre, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.8.0-3.3.pre at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 262b70ece1 (12 days ago), 2021-12-01 13:00:48 -0800
    • Engine revision 06a7363b0c
    • Dart version 2.15.0 (build 2.15.0-268.18.beta)

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.0.0.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 96.0.4664.110

! Doctor found issues in 1 category.


```

</details>

**Comment by stuartmorgan** [comment]
@godofredoc This is something we should consider ways to improve as we refine the release process. Having the Dart version on stable ahead of beta (due to the `beta` tag in the version, which causes it to be treated as older) is confusing.

This specific case will be resolved once beta is updated again, but we should see if we can avoid having this gap every release.

**Comment by godofredoc** [comment]
@devoncarew @itsjustkevin @christopherfujino  FYI

**Comment by christopherfujino** [comment]
I thought there was some special handling of the dart sdk version where we pretend `1.2.3 >= 1.2.3-1`, but I don't see it here: https://dart.dev/tools/pub/pubspec#sdk-constraints

**Comment by christopherfujino** [comment]
oh, what we used to do was when promoting a beta to stable, double publish to both beta AND stable that week, and then the next week beta would get a newer version, which would solve this problem cc @itsjustkevin @devoncarew

**Comment by devoncarew** [comment]
Thanks @christopherfujino, that makes sense. I'm guessing this is documented somewhere; if so, do you have a link handy?

**Comment by stuartmorgan** [comment]
> The dev channel will also need to be considered.

See https://medium.com/flutter/whats-new-in-flutter-2-8-d085b763d181#34c4

**Comment by christopherfujino** [comment]
I am closing this as the beta channel is now newer than the stable channel. WRT documenting this, I have added this to an internal doc owned by @itsjustkevin who will is working on a definitive release process document.
