### ISSUE TITLE
SliverList does not support padding between items

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#9517]
ListView supports specifying padding for each item. Could we have a similar API for SliverList rather than adding padding to each item?

**Comment by abarth** [comment]
The padding in ListView wraps everything in the list.  It's just `new SliverPadding(padding: ..., child: new SliverList(...))`

We could add a feature to SliverList that put space between the children.

**Comment by abarth** [comment]
Can you confirm what you're looking for here?  `ListView.padding` adds padding that surrounds the items as a group, for example where the `***`s are in this diagram:

```
|-------------|
|*************|
|**|-------|**|
|**|   1   |**|
|**|-------|**|
|**|   2   |**|
|**|-------|**|
|**|   3   |**|
|**|-------|**|
|*************|
|-------------|
```

Are you asking for SliverList to do something like that or are you asking for the ability to put spacing between the items, for example where the `***`s are in this diagram:

```
|-------|
|   1   |
|-------|
|*******|
|-------|
|   2   |
|-------|
|*******|
|-------|
|   3   |
|-------|
```

**Comment by mehmetf** [comment]
Ah I see. Never mind then because the first one can be easily achieved by adding a SliverPadding around SliverList. It was not entirely clear from our UI which one was happening. Feel free to close.

**Comment by abarth** [comment]
Thanks.

**Comment by sakshamsang** [comment]
> Can you confirm what you're looking for here? `ListView.padding` adds padding that surrounds the items as a group, for example where the `***`s are in this diagram:
> 
> ```
> |-------------|
> |*************|
> |**|-------|**|
> |**|   1   |**|
> |**|-------|**|
> |**|   2   |**|
> |**|-------|**|
> |**|   3   |**|
> |**|-------|**|
> |*************|
> |-------------|
> ```
> 
> Are you asking for SliverList to do something like that or are you asking for the ability to put spacing between the items, for example where the `***`s are in this diagram:
> 
> ```
> |-------|
> |   1   |
> |-------|
> |*******|
> |-------|
> |   2   |
> |-------|
> |*******|
> |-------|
> |   3   |
> |-------|
> ```

please tell me how to add space in the second example.

**Comment by abegehr** [comment]
@sakshamsang, use a Padding() around your items. (This also adds padding above the first or bellow the last item.)
