### ISSUE TITLE
Flutter master version is lower than stable 

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#95178]
Current master version is something like this 2.6.0-12.0.pre1007

While the stable is 2.8.0

Can this be adjusted?

**Comment by maheshmnj** [comment]
cc: @christopherfujino

**Comment by jmagman** [comment]
This was fixed this morning, https://github.com/flutter/flutter/commit/a7917414dd919edb2e3198c2a8d2130e9275b414 was tagged as `2.9.0-0.0.pre`
```
Flutter 2.9.0-1.0.pre.86 • channel master • git@github.com:jmagman/flutter.git
```
@christopherfujino I believe you already fixed this in the conductor so the next release shouldn't have this problem?

**Comment by christopherfujino** [comment]
I did land a fix for this, but it appears to have not been robust enough. I will re-open https://github.com/flutter/flutter/issues/92809 to track updating the conductor ensure this does not happen again.
