### ISSUE TITLE
Problems to bundle assets in Flutter-Desktop

### ISSUE THREAD

**Issue by UliPrantz** [flutter/flutter#95198]
# Problem Description

There is no documentation available which explains how to bundle assets on Desktop (doesn't matter if MacOS, Windows or Linux). Because of that I would expect that the assets are bundled as normal. The problem is it seems like they aren't bundled at all. There would be some workaround with `flutter build bundle` but again how to handle that within Flutter? Is there anyway to bind in the assets directory? Specifically I want to bundle a `.so` library for `dart:ffi` and also some other assets like a predefined `env.yaml` config file.

# Steps to Reproduce

1. Just create a flutter app with desktop support and add some assets e.g. the standard assets already declared in the `pubspec.yaml`

**Expected results:** Assets should be available within the `DefaultAssets` or the `rootBundle`. Just like it is on Android and iOS

**Actual results:** It seems like assets aren't bundled at all or they are at a not defined place (which isn't mentioned in any documentation!)

**Comment by darshankawar** [comment]
@UliPrantz 
I think your case is similar to https://github.com/flutter/flutter/issues/59515 so please follow-up in it for further updates.
Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.
