### ISSUE TITLE
Engine -> Framework roll failing 

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#95195]
Starting with https://github.com/flutter/flutter/pull/95150 whose changes look unrelated, the engine is repeatedly failing to roll into the framework.

Some of the error messages in the failing tests indicate that the tool is looking for a file in the Android NDK that isn't there.

```
02:12 +14 -2: test/integration.shard/multidex_build_test.dart: simple build apk without FlutterMultiDexApplication fails [E]                                                                           
  Expected: contains 'Cannot fit requested classes in a single dex file'
    Actual: '\n'
              'FAILURE: Build failed with an exception.\n'
              '\n'
              '* What went wrong:\n'
              'Execution failed for task \':app:stripDebugDebugSymbols\'.\n'
              '> NDK at /opt/s/w/ir/cache/android/ndk-bundle did not have a source.properties file\n'
              '\n'
              '* Try:\n'
              'Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.\n'
              '\n'
              '* Get more help at https://help.gradle.org\n'
              '\n'
              'BUILD FAILED in 32s\n'
              'Gradle task assembleDebug failed with exit code 1\n'
              ''
  
  package:test_api                                      expect
  test/integration.shard/multidex_build_test.dart 57:5  main.<fn>
```

Is this fallout from https://github.com/flutter/flutter/pull/94975?

**Comment by godofredoc** [comment]
Creating a revert. I think it will apply cleanly:

https://github.com/flutter/flutter/pull/95196

**Comment by godofredoc** [comment]
It will also require a revert of https://flutter-review.googlesource.com/c/recipes/+/24240

**Comment by godofredoc** [comment]
Tree should be unblocked. Monitoring before closing.

**Comment by blasten** [comment]
"cmdline-tools component is missing" seems to be the culprit.

Full log https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8827954691682037425/+/u/run_module_test/test_stdout

**Comment by godofredoc** [comment]
To reland this change, please upload the new package to the internal and external namespace. Once the package is fully validated we can move to the external namespace.
