### ISSUE TITLE
Remove `download_dart_sdk.py` and use CIPD instead.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#95209]
[The script](https://github.com/flutter/engine/blob/037410127c51458b243b538346d73baa4c9da90d/tools/download_dart_sdk.py) tries to reproduce CIPD behavior when trying to download artifacts from GCS and has been a bit flaky. Instead of trying to reinvent CIPD, we should just use it instead. Except, those artifacts are not currently published to CIPD. The issue https://github.com/dart-lang/sdk/issues/40690 tracks uploading those artifacts. Once that is fixed, this issue tracks removing the script and updating DEPS to use CIPD to fetch the Dart SDK.

**Comment by zanderso** [comment]
Bumping to P2 since this is affecting local developer velocity especially on Windows.

**Comment by Hixie** [comment]
This is block on the Dart issue above.

**Comment by chinmaygarde** [comment]
Working on elevating the priority of the linked issue.

**Comment by chinmaygarde** [comment]
Updates in https://github.com/dart-lang/sdk/issues/40690#issuecomment-998921864.

**Comment by zanderso** [comment]
@godofredoc Would you be able to help @athomas with the items from https://github.com/dart-lang/sdk/issues/40690#issuecomment-998921864?

**Comment by godofredoc** [comment]
Updated permissions to the cipd packages to allow dart service account to upload packages to flutter and flutter_internal namespaces.

**Comment by chinmaygarde** [comment]
Progress is being tracked in the linked issue in `dart-lang/sdk`.

**Comment by chinmaygarde** [comment]
Progress detailed in https://github.com/dart-lang/sdk/issues/40690#issuecomment-1016199663

**Comment by chinmaygarde** [comment]
Progress is being on the linked issue.

**Comment by a-siva** [comment]
Updates

- Refactoring work needed for this has landed in Dart main, this has to be rolled to Dev, Beta and Stable before we start the CIPD uploads. Dev, Beta and Stable will be migrated in “days”. 
- would like to understand why this is a P1 issue?

Does Flutter need any additional artifacts that we don’t already build in the Dart SDK? We’re only have Dart SDKs for some platforms, but not for all of Flutter’s target platforms.

**Comment by zanderso** [comment]
This was marked P2 because the python script we currently use is prone to spiky flakyness. It can go a long time without flaking, but then flake a lot in a short time span, closing the tree for up to a day or more.

For platforms where Dart doesn't vend an SDK, Flutter can still build one out of the Engine repo, but I think since this is only needed host-side, all the platforms we support for that already have SDKs vended by Dart.

**Comment by chinmaygarde** [comment]
From @a-siva:

> The work remaining is the changes he made to main (tip of tree) need to be rolled into the dev/beta and stable branches too so that things will work seamlessly once the change is turned on

**Comment by chinmaygarde** [comment]
This isn't expected to see any movement for about a month.

**Comment by a-siva** [comment]
@sortie can you update the status here, looks like you landed some CLs, is the refactoring work for dealing with dev, beta and stable branches done ?

**Comment by athomas** [comment]
A change was landed that uploads Dart SDK to CIPD when we're building, you can see these packages here (note that there's only a dev "ref" because we haven't built beta or stable since this landed):

https://chrome-infra-packages.appspot.com/p/flutter/dart-sdk/linux-amd64/+/

**Comment by a-siva** [comment]
With respect to next steps

- should we cherry pick the change into the current 2.17 beta branch so that it is available in the beta branch
- 2.17 stable release would take care of the stable branch
- do we need to wait for a good dev 'ref' before updating the Flutter builds with the 'ref'

**Comment by godofredoc** [comment]
Moving it to P3 as this is a process change and it is not blocking anything.

**Comment by athomas** [comment]
We shouldn't pick this to beta, it will flow to beta and stable with the final 2.17 branchout. The work on the Flutter side isn't blocked by this, because it can be done on Engine's main branch until the next branchout to beta.

The refs are created by the dart-sdk builders which the autoroller seems to already wait for. So if it waits for all the relevant SDK builders to succeed, there will be CIPD packages uploaded. Note that the autoroller won't use the CIPD ref, because it is a moving pointer not a pin.

**Comment by godofredoc** [comment]
@chinmaygarde @zanderso seems like this has been unblocked, is there anyone working on the changes to the DEPS file?

**Comment by zanderso** [comment]
https://github.com/flutter/engine/pull/33345 isn't quite going to work. CIPD downloads the zip, extracts it, and then deletes the zip. But we need to retain the zip so that we can plumb it to the place where Flutter artifacts live.

@athomas @godofredoc is there any way to get CIPD to retain the zip file?

**Comment by godofredoc** [comment]
The unzipping steps of the cipd workflow happens automatically. We'll need to modify the archiving steps to generate a zip file out of the cipd content.

**Comment by zanderso** [comment]
This is done in https://github.com/flutter/engine/pull/33345

**Comment by zanderso** [comment]
https://github.com/flutter/engine/pull/33345 was reverted due to the signed Dart SDK mac binaries lacking the right entitlements for macOS.

**Comment by zanderso** [comment]
@christopherfujino @athomas for signing issue.

**Comment by christopherfujino** [comment]
The context on the revert:

1. https://github.com/flutter/engine/pull/33345 changed the way the engine gets the Dart SDK from an ad hoc Python script to DEPS and CIPD
2. The CIPD binaries sometimes(?) get codesigned without entitlements, which caused OOM errors in the Dart VM on some macOS versions https://github.com/flutter/flutter/issues/104387
3. I reverted this in https://github.com/flutter/engine/pull/33558 as a temporary workaround

We should re-enable CIPD downloads once we have determined this codesign operation adds the correct entitlements (or alternatively that it is not being codesigned at all, and all codesigning is handled by the Flutter process)

**Comment by athomas** [comment]
There's no signing issue on the Dart side, so I unassigned myself.

**Comment by christopherfujino** [comment]
Opened a reland of the CIPD change which will re-fix this in https://github.com/flutter/engine/pull/33569

**Comment by whesse** [comment]
This change removed the use of the "download_dart_sdk" flag in engine DEPS, so a gclient checkout always tries to download a Dart SDK from CIPD.  This makes it impossible to use a gclient checkout for a tip-of-tree SDK, or a patched SDK, and broke our iOS tip-of-tree builders, and our new monorepo system.

The gclient sync fails with the error that it cannot find the cipd package for that hash.

Could we replace the conditions for these download steps, adding in the "download_dart_sdk" flag?

**Comment by whesse** [comment]
Patch sent, https://github.com/flutter/engine/pull/33345
