### ISSUE TITLE
[web] WebGL: INVALID_ENUM: enable: invalid capability

### ISSUE THREAD

**Issue by sgehrman** [flutter/flutter#95222]
Noticed this in the console of my web app.  Latest flutter stable.

![gnome-shell-screenshot-5P2JE1](https://user-images.githubusercontent.com/287137/145909352-902075e4-5988-4960-af29-e753b3b74a8d.png)

**Comment by mamuseferha** [comment]
Hi @sgehrman 
Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by jdaev** [comment]
I have been having this same issue while resizing the window. The whole screen goes blank on resize.
