### ISSUE TITLE
Benchmark rasterization time regression related to presentation time

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#95232]
The rasterization time metrics have regressed in various benchmarks.

See https://flutter-flutter-perf.skia.org/e/?begin=1639177151&end=1639424651&keys=Xb33025e8bac42440632fae83a9cc5ab2&num_commits=50&request_type=1&xbaroffset=26859

This started with the https://github.com/flutter/flutter/commit/36709264b52632bc0820be6b03ae8d4fe9539194 engine roll.

Specifically the commit that enabled use of the `eglPresentationTimeANDROID` extension
(https://github.com/flutter/engine/commit/5502a0ad57b72252c1a23b7f6de2d61543f1ff73,
also see https://github.com/flutter/engine/commit/88948dee0733f2a49dfea52e208a9ba200c6ba6a)

@dnfield @chinmaygarde @iskakaushik

**Comment by dnfield** [comment]
This was expected to improve flutter_gallery__transition_perf. I'm having trouble finding that benchmark from a recent run though.

**Comment by dnfield** [comment]
Looking at the manual runs from staging, it did not show the same improvements I was seeing locally. Let's revert.

**Comment by zanderso** [comment]
It looks like there were also improvements to frame build times. Was that expected? https://flutter-flutter-perf.skia.org/e/?begin=1638331745&end=1639497543&keys=Xd99a686e8a4acf536c3feb88dc6c8779&requestType=0&xbaroffset=26859

**Comment by dnfield** [comment]
I'll try to look at the traces some more. This didn't work quite as I was seeing locally but it's possible it helped get more even scheduling

**Comment by dnfield** [comment]
If it can really help frame times like that it's worth keeping
