### ISSUE TITLE
How to prevent the keyboard from closing while navigating?

### ISSUE THREAD

**Issue by ali-1989** [flutter/flutter#95246]
flutter: 2.18

How to prevent the keyboard from closing while navigating?

I want to display a widget on the keyboard. Like the photo below. But when I navigate, the focus is lost and the keyboard is closed.
I used:

```
Navigator.of().push();
showModalBottomSheet();
showDialog();

```

and this:
`Overlay.of(context)?.insert(entry); `  --> The Overlayis placed under the keyboard

![cc](https://user-images.githubusercontent.com/30122089/145958564-bd185f10-4e1b-4d1e-ae03-8462eaffa290.gif)

[https://i.postimg.cc/FK6ftzpy/ezgif-com-gif-maker.gif](url)

**Comment by darshankawar** [comment]
@ali-1989 
Your question is better suited for support channels like StackOverflow, so please ask the same there. There are several similarly asked questions that should help you. https://stackoverflow.com/questions/61373774/how-to-avoid-keyboard-popping-out-while-navigating-to-next-screen
Closing from here, as this is more of a `how to` question than a bug or feature request.

**Comment by ali-1989** [comment]
thank you.
But my question is 180 degrees different from the question in the link above.
They want to close the keyboard while navigating, If I want to stay open, of course behind the new page.
