### ISSUE TITLE
devicelab_benchmark pool benchmarks are broken and not reporting results

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#95240]
A few months ago, several benchmarks were moved from prod to a new pool here:

https://ci.chromium.org/p/flutter/g/devicelab_benchmark/console#

This was with the understanding that the benchmarks would continue to report their results to SkiaPerf, and that the Engine sheriff would be notified when the benchmarks are failing. It looks like neither of those is happening.

We need to either keep these benchmarks working with proper notifications on failure, or move them back to prod.

**Comment by zanderso** [comment]
These haven't been reporting results to SkiaPerf since late October: https://flutter-flutter-perf.skia.org/e/?begin=1634679481&end=1635992134&queries=test%3DLinux_android_flutter_gallery__transition_perf&requestType=0

**Comment by keyonghan** [comment]
This is strange. Checking why they stopped reporting benchmarks.

**Comment by keyonghan** [comment]
Tests have been running successfully: https://ci.chromium.org/p/flutter/g/devicelab_benchmark/console?limit=200, but they just skipped uploading metrics to skia perf.
From properties, we do see `"upload_metrics": true,`: https://ci.chromium.org/ui/p/flutter/builders/staging/Linux_android%20flutter_gallery__transition_perf_e2e/852/overview

**Comment by keyonghan** [comment]
https://flutter-review.googlesource.com/c/recipes/+/19561 updated the recipes to use property `git_branch`, which is not enabled in staging configs. This caused the benchmarks to skip upload.

**Comment by keyonghan** [comment]
https://flutter-review.googlesource.com/c/infra/+/24360 to add the `git_branch` property.

BTW: we are planning to separate all benchmarks from other tree blocker tests in Q1, this way, all benchmarks are expected to run in prod pool.

**Comment by zanderso** [comment]
Benchmarks that are not consistently above the flaky threshold should still block the tree when they fail.

**Comment by keyonghan** [comment]
> Benchmarks that are not consistently above the flaky threshold should still block the tree when they fail.

Yeah, a smart logic should be enforced here. For example, if a benchmark consistently fails like 2 or 3 times, it will close the tree.

**Comment by keyonghan** [comment]
Metrics are being picked up: https://flutter-flutter-perf.skia.org/e/?queries=test%3Dflutter_gallery__transition_perf_hybrid  

Mac/ios breakage is being tracked in https://github.com/flutter/flutter/issues/95272

**Comment by keyonghan** [comment]
Mac/ios bots are back, and are running tests with success.
Results are being reported to Skia perf.
https://ci.chromium.org/p/flutter/g/devicelab_benchmark/console#

The final action to move them back to prod will be planned in Q1.
The remaining action here is add notification alert when these tests fail while still running in staging.

Adjusting the priority to P3.

**Comment by keyonghan** [comment]
Alert was implemented in https://flutter-review.googlesource.com/c/infra/+/24740, and is working as expected. Closing here.
