### ISSUE TITLE
Flutter Background Music/audio is Paused when recording with startVideoRecording()

### ISSUE THREAD

**Issue by thomasrafty** [flutter/flutter#95257]
Please help me as I am trying to build an app where the whole app revolves around recording video while audio is playing. Please help me I am desperate

**Comment by darshankawar** [comment]
@thomasrafty 
I think you are talking about this issue, https://github.com/flutter/flutter/issues/63836
If so, follow-up in it for further updates. Also, video player plugin yet doesn't seem to support playing music or audio in the background.
Closing this as duplicate.
