### ISSUE TITLE
Animated SlashScreen API Android 12 has inconsistent behaviour on backward Android OS  

### ISSUE THREAD

**Issue by glintpursuit** [flutter/flutter#95253]
**Implemented Animated FlashScreen using below guides** 

1. Flutter guide for [Android S](https://docs.flutter.dev/development/ui/advanced/splash-screen?tab=android-splash-alignment-kotlin-tab)
2. [Android Splash Screen API Guide](https://developer.android.com/guide/topics/ui/splash-screen)
3. [Migrate your existing splash screen implementation to Android 12 and higher](https://developer.android.com/guide/topics/ui/splash-screen/migrate)

**Issue**

1. Animated flash screen API does work on **Android 12** 
2. Animated flash screen API doesn't animate on **Android 11**, just shows the first image in Animation Icon list
3. Animated flash screen API doesn't animate on **Android 6**, just shows the first image in Animation Icon list & background color stays in the bottom navigation bar. 

![Screenshot 2021-12-14 at 3 43 24 PM](https://user-images.githubusercontent.com/46914085/145978693-445af96e-5122-488e-b72c-10b5fe09d13b.png)

4. Animated flash screen API doesn't show icon on Android 5.1, just shows the background color &  it stays in bottom navigation bar. 
![Screenshot_1639477354](https://user-images.githubusercontent.com/46914085/145980271-824f6272-ae08-4730-8a23-55e6fdc80cc1.png)

5. Unresolved reference: setDecorFitsSystemWindows. (Splash screen still runs w/o below line)
`WindowCompat.setDecorFitsSystemWindows(getWindow(), false)`

6. Animated icon won't show up at all after launching through Android Studio, we have to kill the app & relaunch it. 

## Steps to Reproduce
1. Implement Animated Splash Screen using above mention guide. 

`build.gradle`

```gralde
android {
   compileSdkVersion 31
   ...
}
dependencies {
   ...
   implementation 'androidx.core:core-splashscreen:1.0.0-alpha01'
}
```

`styles.xml`

```xml
<style name="Theme.App.Starting" parent="Theme.SplashScreen">
   // Set the splash screen background, animated icon, and animation duration.
   <item name="windowSplashScreenBackground">@color/...</item>

   // Use windowSplashScreenAnimatedIcon to add either a drawable or an
   // animated drawable. One of these is required.
   <item name="windowSplashScreenAnimatedIcon">@drawable/...</item>
   <item name="windowSplashScreenAnimationDuration">200</item>  # Required for
                                                                # animated icons

   // Set the theme of the Activity that directly follows your splash screen.
   <item name="postSplashScreenTheme">@style/Theme.App</item>  # Required.
</style>
```

`AndroidManifest.xml`

```xml
<manifest>
   <application android:theme="@style/Theme.App.Starting">
    <!-- or -->
        <activity android:theme="@style/Theme.App.Starting">
```

```kotlin
import android.os.Build
import android.os.Bundle
import androidx.core.view.WindowCompat
import io.flutter.embedding.android.FlutterActivity

class MainActivity : FlutterActivity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    // Aligns the Flutter view vertically with the window.
    WindowCompat.setDecorFitsSystemWindows(getWindow(), false)

    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
      // Disable the Android splash screen fade out animation to avoid
      // a flicker before the similar frame is drawn in Flutter.
      splashScreen.setOnExitAnimationListener { splashScreenView -> splashScreenView.remove() }
    }

    super.onCreate(savedInstanceState)
  }
}
```

**Comment by danagbemava-nc** [comment]
Hi @glintpursuit, thanks for filing the issue. Please provide the output of `flutter doctor -v`. 

Thank you

**Comment by glintpursuit** [comment]
hi @danagbemava-nc 

`flutter doctor -v
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.5 20G71 darwin-x64, locale en-IN)
    • Flutter version 2.5.3 at /Users/tech9/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (9 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/tech9/Library/Developer/Xamarin/android-sdk-macosx
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = /Users/tech9/Library/Developer/Xamarin/android-sdk-macosx
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.63.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.93
    ! Error: My iPhone 6 is not connected. Xcode will continue when My iPhone 6 is connected. (code -13)

• No issues found!
`

**Comment by danagbemava-nc** [comment]
Can you also share the logs of `flutter run -v` for the various versions of `android`?

Thank you

**Comment by glintpursuit** [comment]
@danagbemava-nc 

Please find attached log for 5.1 & 6.0 
[flutter run -v lollipop_5.1.txt](https://github.com/flutter/flutter/files/7716981/flutter.run.-v.lollipop_5.1.txt)
[flutter run -v  6.0.txt](https://github.com/flutter/flutter/files/7716980/flutter.run.-v.6.0.txt)
 
`<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="Theme.App.Starting" parent="Theme.SplashScreen">
        // Set the splash screen background, animated icon, and animation duration.
        <item name="windowSplashScreenBackground">@color/SplashScreenBackgroundColor</item>

        // Use windowSplashScreenAnimatedIcon to add either a drawable or an
        // animated drawable. One of these is required.
        <item name="windowSplashScreenAnimatedIcon">@drawable/animated_flash</item>
        <item name="windowSplashScreenAnimationDuration">900</item>  # Required for
        # animated icons

        // Set the theme of the Activity that directly follows your splash screen.
        <item name="postSplashScreenTheme">@style/NormalTheme</item>  # Required.
    </style>
    
    <style name="LaunchTheme" parent="@android:style/Theme.Light.NoTitleBar">
        
        <item name="android:windowBackground">@drawable/launch_background</item>
    </style>
    
    <style name="NormalTheme" parent="@android:style/Theme.Light.NoTitleBar">
        <item name="android:windowBackground">?android:colorBackground</item>
    </style>
    <color name="SplashScreenBackgroundColor" >#FFF6B926</color>
</resources>
`

**under drawable-v21>>animated_flash.xml**  

`<?xml version="1.0" encoding="utf-8"?>
<animation-list xmlns:android="http://schemas.android.com/apk/res/android"
    android:oneshot="true">
    <item android:drawable="@drawable/flashpng1" android:duration="400" />
    <item android:drawable="@drawable/flashpng2" android:duration="400" />
    <item android:drawable="@drawable/flashpng3" android:duration="300" />
</animation-list>`

**Comment by danagbemava-nc** [comment]
Can you also share the drawable files?

**Comment by glintpursuit** [comment]
@danagbemava-nc 
Please find attached images 

![flashpng1](https://user-images.githubusercontent.com/46914085/146204348-7608b289-5c79-49d1-9155-83014f87ad8d.png)
![flashpng2](https://user-images.githubusercontent.com/46914085/146204362-ba4c1b5f-5a7a-4467-8325-c2e2262dd9dd.png)
![flashpng3](https://user-images.githubusercontent.com/46914085/146204364-b2cc74ff-f596-4744-95e2-cd26ef788d93.png)

**Comment by danagbemava-nc** [comment]
Hi @glintpursuit, I do have one more request to make of you, can you confirm that the SplashScreen API itself is backwards-compatible on native android? 
I can repro the no animation on API below 12, but I do not a device running android 5/6, atm, so I can't confirm that and I would also like to know whether or not this is an android issue or a flutter issue. 

Thank you

**Comment by glintpursuit** [comment]
@danagbemava-nc 

Not sure on backward compatibility, but I believe there should be some way around it. 

It could be Android one, I am also looking for solution.

**Comment by danagbemava-nc** [comment]
It looks like the SplashScreen api itself isn't backwards compatible.
I created a small native android project and I could see that there's no exit animation played for the splash screen on android versions lower than 12. I have attached the sample I used below, can you confirm this? 

<details>
<summary>videos</summary>

| android 12 | android 11 |
| -- | -- | 
| <video src="https://user-images.githubusercontent.com/88313112/146506851-079cd9b0-7ba2-494b-92b4-8ebd4e010d89.mov" /> | <video src="https://user-images.githubusercontent.com/88313112/146506884-1f9ee060-09d4-4226-9472-6d552a069ee3.mov" /> |


</details>


[SplashTest.zip](https://github.com/flutter/flutter/files/7733340/SplashTest.zip)

**Comment by glintpursuit** [comment]
@danagbemava-nc 

Yes, Android 11 wont show animation. 

But below Android 6, we wont get any icon render on splash screen. 

Do we have any solution for handling it with different splash screen below Android 11.

**Comment by danagbemava-nc** [comment]
@glintpursuit

I did a little bit of searching and this is a bug in the SplashScreen API, or rather, it hasn't been implemented yet with the version of the library you're using. 

Release notes https://developer.android.com/jetpack/androidx/releases/core#core-splashscreen-1.0.0-alpha01.

**Comment by glintpursuit** [comment]
@danagbemava-nc, so let's wait for API update ?  

I am not sure how Gmail app is handling this, it has splash screen with animation.

**Comment by danagbemava-nc** [comment]
> so let's wait for API update ?

There's a new version out, https://developer.android.com/jetpack/androidx/releases/core#core_splashscreen_version_10_2. 

I'm not entirely sure if that version has the changes that you want but since this is a core android library, any issues with it are beyond the scope of flutter. 

It seems to be affecting native android devs too, see https://stackoverflow.com/questions/69812590/android-12-splash-screen-icon-not-displaying. 

Due to the above reason, I'm going to have to close this issue, as it is beyond the scope of flutter. 

Thank you
