### ISSUE TITLE
flutter unable to build IOS app in release mode with Xcode 13.1 ( Undefined symbols for architecture arm64)

### ISSUE THREAD

**Issue by venkata-reddy-boya** [flutter/flutter#95256]
**Error  msg :**  

```console
 Undefined symbols for architecture arm64:
      "_OBJC_CLASS_$_GULAppEnvironmentUtil", referenced from:
          objc-class-ref in FIRCLSApplication.o
    ld: symbol(s) not found for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in parallel
```
   
**Full error log msg :** 
[build_error.txt](https://github.com/flutter/flutter/files/7710781/build_error.txt)

The app is running in debug mode on a physical device but the issue occurs when I try to build a release version.

Below is the command used to build ios app in release mode 

```
flutter build ios --release --no-codesign --dart-define=ENV=STAG
```

`POD Files `

[Podfile.lock.txt](https://github.com/flutter/flutter/files/7710792/Podfile.lock.txt)
[Podfile.txt](https://github.com/flutter/flutter/files/7710793/Podfile.txt)

`packages` 
[packages_info.txt](https://github.com/flutter/flutter/files/7710920/packages_info.txt)

NOTE :
The same code is working with `XCODE 12.x` but I'm facing this issue with `XCODE 13.1`

 <details>
<summary> flutter doctor -v</summary>

```console 
[✓] Flutter (Channel stable, 2.5.1, on macOS 12.0.1 21A559 darwin-x64, locale en-GB)
    • Flutter version 2.5.1 at /Users/rr-reddy/Documents/soft/flutter_soft/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (3 months ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✗] Android toolchain - develop for Android devices
    • Android SDK at /Users/rr-reddy/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Connected device (2 available)
    • RR REDDY (mobile) • 00008030-000D749402D0402E • ios            • iOS 15.1 19B74
    • Chrome (web)      • chrome                    • web-javascript • Google Chrome 96.0.4664.110

! Doctor found issues in 1 category.
```
</details>

**Comment by venkata-reddy-boya** [comment]
https://stackoverflow.com/questions/70280008/undefined-symbols-for-architecture-arm64-objc-class-fluttererror/70280105

**Comment by danagbemava-nc** [comment]
Hi @venkata-reddy-boya, please provide the output of `flutter build ios --release --no-codesign --dart-define=ENV=STAG
 -v`. 
 
 The output is likely to be huge so you can just put it into a .txt file and upload it here.

Thank you

**Comment by venkata-reddy-boya** [comment]
@danagbemava-nc  

i am closing #95256. 

This issue was resolved with [firebase_crashlytics](https://pub.dev/packages/firebase_crashlytics/changelog) version update 2.2.0 from 2.1.1

![Screenshot 2021-12-15 at 11 05 05 AM](https://user-images.githubusercontent.com/85147004/146129401-d48b19fc-0c0f-4717-b60e-7cb66e5a45dd.png)
