### ISSUE TITLE
[flutter_markdown] show more feature

### ISSUE THREAD

**Issue by SalahAdDin** [flutter/flutter#95258]
## Use case

Some **Instagram** like applications require to render full rich text on its description, and for this [**flutter_markdown**](https://pub.dev/packages/flutter_markdown), but it render itself the full content when normally we just want to see a short of the text and show the full content only if the user clicks on _show more_, for instance.

There is already a package who can give us this feature, [**readmore**](https://pub.dev/packages/readmore), but it does just work with string text, so we can't pass a component, _Markdown.body_, as string text.

## Proposal

The idea is to handle the showmore feature by extending/contracting the content at time a label show more/ show less is showed based on the content status, and the way to handle it, as the aforementioned package already does.

**Comment by stuartmorgan** [comment]
The `flutter_markdown` package's scope is just rendering Markdown itself. Additional functionality that's not part of Markdown, such as what you are describing, is something that the community is welcome to implement as a wrapper package.
