### ISSUE TITLE
Master & dev chanels using old version tag

### ISSUE THREAD

**Issue by Eclipsed-Ripper** [flutter/flutter#95250]
Recently Flutter released the 2.8.0 update, however, the versions/version tags on the master & dev branches are still on 2.6.0... This was not a problem until now. Some packages on pub.dev started to update their dependencies to the new flutter release version, 2.8.0.

When using the master branch, and the latest packages, this is what I get:

## Steps to Reproduce

1. Switch to the Dev or Master channels of flutter
2. Using newly updated pub.dev packages that depend on flutter 2.8.0
3. Running `flutter pub get` or `flutter pub upgrade`

**Expected results:**  Success

**Actual results:** 
![image](https://user-images.githubusercontent.com/89787979/145967980-52b09a82-4b91-48d0-9705-e2af8c6fab0c.png)

When running `flutter upgrade` on master:
![image](https://user-images.githubusercontent.com/89787979/145969784-4df5cee7-badb-4eac-af74-71e8f9b4bae6.png)

When running `flutter upgrade` on dev:
![image](https://user-images.githubusercontent.com/89787979/145970495-24b5f264-8cc0-48a5-86c2-a0e8b9ca81b5.png)

When running `flutter upgrade` on stable:
![image](https://user-images.githubusercontent.com/89787979/145971045-86c7a82a-7120-48a5-be25-fd1c293706ba.png)

**Comment by darshankawar** [comment]
> 2\. Using newly updated pub.dev packages that depend on flutter 2.8.0

Can you provide us an example of such package ?

**Comment by Eclipsed-Ripper** [comment]
The package that I'm using, that is currently giving me this issue is: extended_image: ^6.0.1

https://pub.dev/packages/extended_image

Haven't found any other packages at the moment, but I'm certain that other packages will start to surface.

**Comment by darshankawar** [comment]
I switched to latest master (2.9.0-1.0.pre.93) and then ran `flutter pub add extended_image` and then `flutter pub get` which ran properly without any issues:

```
dhs@Dhss-MacBook-Pro ios_bug % flutter pub get               
Running "flutter pub get" in ios_bug...                          2,489ms
dhs@Dhss-MacBook-Pro ios_bug % 

```

**Comment by Eclipsed-Ripper** [comment]
Yes. This morning when calling `flutter upgrade` on master, flutter then updated to the latest version. Thx for the assistance!!
