### ISSUE TITLE
Mac/ios staging tests are failing at Dismiss dialogs step

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#95272]
Most tests are failing consistently:
![Screen Shot 2021-12-14 at 10 23 24 AM](https://user-images.githubusercontent.com/54558023/146057455-f6b97c3f-5517-4743-803b-b6398164fc21.png)

Example: https://logs.chromium.org/logs/flutter/led/keyonghan_google.com/c3034cd7364ce75c119ec9fd94d99f7125ec61a7b6c63a7c29d8c5b8000c7345/+/u/Dismiss_dialogs/Run_app_to_dismiss_dialogs/stdout

Error message:
```
error: Provisioning profile "match Development *" doesn't include the currently selected device "Godofredo Contreras’s iPhone" (identifier 8d8cb75a74e5cbdf0fb2bb63d34441e44f9d46ef). (in target 'infra-dialogUITests' from project 'infra-dialog')
```

**Comment by keyonghan** [comment]
Tried `/opt/homebrew/bin/ideviceinstaller -l | grep flutter`, but it returns no application.

**Comment by keyonghan** [comment]
@godofredoc sent an update on the provision file, and this should be resolved soon.

**Comment by keyonghan** [comment]
Now tests kept failing at `install xcode` step with permission issue:
```
[E 2021-12-14 23:34:43] original error: permission denied

goroutine 1:
#0 mac_toolchain/install.go:211 - main.installXcode()
  reason: failed to create a folder /opt/flutter/xcode/13a233/XCode.app

#1 mac_toolchain/main.go:165 - main.(*installRun).Run()
#2 github.com/maruel/subcommands@v1.1.1/subcommands.go:395 - subcommands.Run()
#3 mac_toolchain/main.go:456 - main.main()
#4 runtime/proc.go:225 - runtime.main()
#5 runtime/asm_amd64.s:1371 - runtime.goexit()
```

**Comment by godofredoc** [comment]
Which test bed are you referring to? most of them are now passing tests

**Comment by keyonghan** [comment]
Seems only mac45 is experiencing the permission error: https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-45

**Comment by godofredoc** [comment]
ok, this should be fixed now. For the posterity: DeviceLab test beds require /opt/flutter/xcode to be writeable by the swarming user.

```sudo mkdir -p /opt/flutter/xcode && sudo chown -R swarming /opt/flutter/xcode```

**Comment by keyonghan** [comment]
Another bot mac23 is still hitting dismiss dialog step failure, but sounds a different issue: https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-23
```
Testing failed:
	infra-dialogUITests:
		infra-dialogUITests-Runner encountered an error (Failed to install or launch the test runner. If you believe this error represents a bug, please attach the result bundle at /Users/swarming/Library/Developer/Xcode/DerivedData/infra-dialog-ayzxmkyimrprakexnyiavfekoqad/Logs/Test/Test-infra-dialog-2021.12.14_18-33-01--0800.xcresult. (Underlying Error: Unable to launch dev.flutter.infra-dialogUITests.xctrunner. (Underlying Error: Request to launch dev.flutter.infra-dialogUITests.xctrunner failed. Device busy or Instruments is trying to launch several targets, and one of them is a foreground app. (Underlying Error: The operation couldn’t be completed. Device setup is not yet complete.))))
```

Last time we saw this, it is due to phone not ready (https://github.com/flutter/flutter/issues/79522)
Tried taking a screenshot on the device, but hit 
```
Could not start screenshotr service! Remember that you have to mount the Developer disk image on your device if you want to use the screenshotr service.
```
Sounds we need to mount the image 
```
ideviceimagemounter /opt/flutter/xcode/13a233/XCode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/<version>/DeveloperDiskImage.dmg  /opt/flutter/xcode/13a233/XCode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/<version>/DeveloperDiskImage.dmg.signature
```
But there is no `15.1` in xcode..

Any idea?

**Comment by godofredoc** [comment]
The 23 phone is on setup mode. We need to manually configure it along with the other 2 or 3 failing ones.

**Comment by keyonghan** [comment]
Manually quarantined mac23 for now.

**Comment by keyonghan** [comment]
mac14 has been hitting xcode permission issue. Just granted the correct permission, and it should be good.

**Comment by jmagman** [comment]
> mac14 has been hitting xcode permission issue. Just granted the correct permission, and it should be good.

Here's another one from mac-14 from an hour after this comment https://ci.chromium.org/p/flutter/builders/staging/Mac_ios%20hot_mode_dev_cycle_ios__benchmark/3?

**Comment by yusuf-goog** [comment]
mac-23 device upgraded, and needed setup - completed, un-quarantining it.
mac-40 device stuck on trust dialog - completed.
mac-45 seems to be fine and running.
will check on macs in other lab next.

**Comment by yusuf-goog** [comment]
mac-23 is no longer failing tasks.

**Comment by yusuf-goog** [comment]
mac-14 device stuck on upgrade dialog. cleared and un-quarantined it.
mac-13 host was stuck on mac upgrade screen. rebooted it.
