### ISSUE TITLE
Insufficient permissions to the resource in https://pub.dartlang.org package repository

### ISSUE THREAD

**Issue by TalebRafiepour** [flutter/flutter#95282]
## Steps to Reproduce

1. create flutter project
2. add some packages in pubspec.yaml and get all of them
3. delete flutter (SDK) and replace new flutter(SDK)
4. reopen the project and try "flutter pub get" get get depency hosted by pub.dartlang.org
5. "Insufficient permissions" error will happen and you can not get packages.

## Logs

Insufficient permissions to the resource in https://pub.dartlang.org package repository. You can modify credential using:
    pub token add https://pub.dartlang.org
Running "flutter pub get" in flutter_tools...                           
pub get failed (65;     pub token add https://pub.dartlang.org)

```
Flutter 2.8.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision cf44000065 (6 days ago) • 2021-12-08 14:06:50 -0800
Engine • revision 40a99c5951
Tools • Dart 2.15.0
```

**Comment by darshankawar** [comment]
> 3\. delete flutter (SDK) and replace new flutter(SDK)

Why would you want to delete sdk or why would anyone do that ? What use case are you trying to achieve by deleting sdk ?
Not sure if such a case would arise or devs would do that to be honest.

**Comment by TalebRafiepour** [comment]
> > 3. delete flutter (SDK) and replace new flutter(SDK)
> 
> Why would you want to delete sdk or why would anyone do that ? What use case are you trying to achieve by deleting sdk ? Not sure if such a case would arise or devs would do that to be honest.

Because I am in Iran, and I can not update my flutter version with CLI

**Comment by TalebRafiepour** [comment]
I just shut down my system and restart it, then it works :|

**Comment by TalebRafiepour** [comment]
> how did you solve this?

I think it was because of my vpn.
