### ISSUE TITLE
[share] iOS - Applications for opening a Word document are not displayed

### ISSUE THREAD

**Issue by mikrul85** [flutter/flutter#95292]
Hello. We are launching the app on a real iPad device. We have several applications installed for editing Word documents.

![1](https://user-images.githubusercontent.com/49406463/146092059-77b6fb2f-0459-40e3-a4be-841b610cd548.jpg)

In our application for the Word document, we launch the Share library.

![2](https://user-images.githubusercontent.com/49406463/146092262-05b3653c-c18f-4c56-97e1-63ec20435ce2.jpg)

There are no installed applications in the list for opening a Word document

![3](https://user-images.githubusercontent.com/49406463/146092547-b01ecdb6-c780-4bd0-b811-7c89b114939c.jpg)

**Comment by mamuseferha** [comment]
Hi @mikrul85 
The [share](https://pub.dev/packages/share) plugin has been deprecated in favor of [share_plus](https://pub.dev/packages/share_plus), and no further update are planned for the plugin. Consider migrating to [share_plus](https://pub.dev/packages/share_plus).

I'll go ahead and close this now, if you disagree, please write in the comments and I will reopen it.
Thank you
