### ISSUE TITLE
dart:ui's Color maybe should mention material's Colors

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#953]

**Comment by eseidelGoogle** [comment]
Looks like it doesn't yet:
http://docs.flutter.io/flutter/dart-ui/Color-class.html

**Comment by sethladd** [comment]
Ah, I think you mean: "link over to the material library's Colors class" ?

**Comment by sethladd** [comment]
PR: https://github.com/flutter/engine/pull/3494

**Comment by sethladd** [comment]
Done! :)
