### ISSUE TITLE
Failed to access the internal image decoder registry on this isolate

### ISSUE THREAD

**Issue by sjjvenu** [flutter/flutter#95311]
1. add to app project
2. destroy a flutter view and create a flutter view at same time cause this exception
3. single create and destroy is normal

**Expected results:** 

```
══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
The following _Exception was thrown resolving an image codec:
Exception: Failed to access the internal image decoder registry on this isolate. Please file a bug
on https://github.com/flutter/flutter/issues.

When the exception was thrown, this was the stack:
#0      _futurize (dart:ui/painting.dart:5394:5)
#1      ImageDescriptor.encoded (dart:ui/painting.dart:5262:12)
#2      instantiateImageCodec (dart:ui/painting.dart:2048:60)
<asynchronous suspension>

Path:
/Users/tdx/Library/Developer/CoreSimulator/Devices/BA20CD06-4113-460B-8232-FC0F805AD34F/data/Containers/Data/Application/E9A585D4-FF42-4CBC-A319-4458F950C0B1/Documents/home/webApp/app/../../flutter/red/IndexesPicker/nav_back.png
```

**Actual results:** 

can't load image

<details>
<summary>Code sample</summary>

```objective-c
FlutterEngineGroup * engineGroup = dic[@"engineGroup"];
    if (engineGroup == nil)
    {
        return nil;
    }
    FlutterEngine *newEngine = [engineGroup makeEngineWithEntrypoint:entrypoint libraryURI:nil];
    [GeneratedPluginRegistrant registerWithRegistry:newEngine];
    self = [super initWithEngine:newEngine nibName:nil bundle:nil];
```

```
[✓] Flutter (Channel flutter-2.5-candidate.5, 2.5.3, on macOS 11.6 20G165
    darwin-x64, locale en-CN)
    • Flutter version 2.5.3 at /Users/tdx/github/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (9 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version
    30.0.3)
    • Android SDK at /Users/tdx/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.63.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.1
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains localhost

[✓] Connected device (3 available)
    • iPhone (mobile)            • 7beb16a466c47eb51783b781476f45c0b297ec96 •
      ios            • iOS 14.5 18E199
    • iPhone 12 Pro Max (mobile) • BA20CD06-4113-460B-8232-FC0F805AD34F     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 96.0.4664.93
```

**Comment by darshankawar** [comment]
@sjjvenu 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can directly use to verify this ?


> 2\. destroy a flutter view and create a flutter view at same time cause this exception

Also provide steps to replicate this.

**Comment by sjjvenu** [comment]
> @sjjvenu Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can directly use to verify this ?
> 
> > 2. destroy a flutter view and create a flutter view at same time cause this exception
> 
> Also provide steps to replicate this.

I have a FlutterView in Some ViewController, when  push a FlutterViewController from the FlutterView, the FlutterView remove from superView and set nil,the FlutterViewController will show the exception


flutter doctor -v
`[✓] Flutter (Channel flutter-2.5-candidate.5, 2.5.3, on macOS 11.6 20G165
    darwin-x64, locale en-CN)
    • Flutter version 2.5.3 at /Users/tdx/github/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (9 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version
    30.0.3)
    • Android SDK at /Users/tdx/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.63.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0`

**Comment by darshankawar** [comment]
> [✓] Flutter (Channel flutter-2.5-candidate.5, 2.5.3,

Can you upgrade to latest (2.8.0) and try again ?
If not, we would need a complete minimal code sample that we can directly copy paste and run to verify this.
Thanks.

**Comment by sjjvenu** [comment]
> > [✓] Flutter (Channel flutter-2.5-candidate.5, 2.5.3,
> 
> Can you upgrade to latest (2.8.0) and try again ? If not, we would need a complete minimal code sample that we can directly copy paste and run to verify this. Thanks.

2.8.1 show the same error,I found the exception in this
![CF824AB95B64C7D8D7EBAAD645898828](https://user-images.githubusercontent.com/7379269/148187547-a9cc3335-02dc-4dbe-b9b0-57508de02e5f.jpg)
![image](https://user-images.githubusercontent.com/7379269/148187579-71f3b8b6-ebe4-4c92-bc6c-de598264b770.png)

**Comment by sjjvenu** [comment]
> > [✓] Flutter (Channel flutter-2.5-candidate.5, 2.5.3,
> 
> Can you upgrade to latest (2.8.0) and try again ? If not, we would need a complete minimal code sample that we can directly copy paste and run to verify this. Thanks.

my project is too large ,I need time to create a code sample

**Comment by darshankawar** [comment]
@sjjvenu 
Please provide one to address this issue properly.

**Comment by sjjvenu** [comment]
> @sjjvenu Please provide one to address this issue properly.

`- (FlutterEngine*)makeEngineWithEntrypoint:(nullable NSString*)entrypoint
                                libraryURI:(nullable NSString*)libraryURI
                              initialRoute:(nullable NSString*)initialRoute {
  NSString* engineName = [NSString stringWithFormat:@"%@.%d", self.name, ++_enginesCreatedCount];
  FlutterEngine* engine;
  if (self.engines.count <= 0) {
    engine = [[FlutterEngine alloc] initWithName:engineName project:self.project];
    [engine runWithEntrypoint:entrypoint libraryURI:libraryURI initialRoute:initialRoute];
  } else {
    FlutterEngine* spawner = (FlutterEngine*)[self.engines[0] pointerValue];
    engine = [spawner spawnWithEntrypoint:entrypoint
                               libraryURI:libraryURI
                             initialRoute:initialRoute];
  }
  [_engines addObject:[NSValue valueWithPointer:engine]];

  NSNotificationCenter* center = [NSNotificationCenter defaultCenter];
  [center addObserver:self
             selector:@selector(onEngineWillBeDealloced:)
                 name:FlutterEngineWillDealloc
               object:engine];

  return [engine autorelease];
}`

I found how to cause this issue,engine initWithName is normal,but when the first engine has been destroy,at the same time create engine will cause the problem,when I remain one engine,all the other engine create with spawnWithEntrypoint func,now is normal

**Comment by darshankawar** [comment]
@sjjvenu 
Does it mean the issue is resolved and can be closed ?

**Comment by sjjvenu** [comment]
> @sjjvenu Does it mean the issue is resolved and can be closed ?

2.8.1 still has the issue,I resolved the issue by change the engine source code

**Comment by darshankawar** [comment]
@sjjvenu 
In order to properly address this issue, we would need a reproducible code sample that we can use to replicate and verify.

**Comment by red282** [comment]
Maybe same as #90495.
