### ISSUE TITLE
stable 2.8.0 flutter_windows.dll crash on windows 10.0.14393

### ISSUE THREAD

**Issue by wujing-gxl** [flutter/flutter#95337]
In this scenario (https://github.com/flutter/flutter/issues/90503) function（ImmSetCompositionStringW） in engin\shell\platform\windows\text_input_manager_win32.cc will crash on windows 10.0.14393. 

Solution：Replace code 1 with code 2
```
// code1：
// Cancel composing and close the candidates window.
::ImmNotifyIME(imm_context.get(), NI_COMPOSITIONSTR, CPS_CANCEL, 0);
::ImmNotifyIME(imm_context.get(), NI_CLOSECANDIDATE, 0, 0);

// Clear the composing string.
wchar_t composition_str[] = L"";
wchar_t reading_str[] = L"";
::ImmSetCompositionStringW(imm_context.get(), SCS_SETSTR, composition_str,
                               sizeof(wchar_t), reading_str, sizeof(wchar_t));
```

```
// code2：
::ImmNotifyIME(imm_context.get(), NI_COMPOSITIONSTR, CPS_COMPLETE, 0);
```

reference resources：https://github.com/chromiumembedded/cef/blob/50f627b07e034f7312f0c9cdfce7493e18bc0643/tests/cefclient/browser/osr_ime_handler_win.cc#L219

**Comment by darshankawar** [comment]
@wujing-gxl 
Can you provide us `flutter doctor -v` and a minimal code sample that leads to the crash you are describing ?
Thanks.

**Comment by wujing-gxl** [comment]
[√] Flutter (Channel stable, 2.8.0, on Microsoft Windows [Version 10.0.17763.2300], locale zh-CN)
    • Flutter version 2.8.0 at D:\thirdsdk\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (7 days ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\wujing\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31515.178
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.63.0)
    • VS Code at C:\Users\wujing\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.29.0

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.17763.2300]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 96.0.4664.93

! Doctor found issues in 1 category.

**Comment by darshankawar** [comment]
@wujing-gxl 
Would also be good to get the crash log along with a code sample .

**Comment by jason-simmons** [comment]
@cbracken

**Comment by cbracken** [comment]
@wujing-gxl can you provide detailed steps to reproduce the crash you're observing? I'm not able to reproduce a crash on a Windows 10 (10.0.18363.1977) machine.
