### ISSUE TITLE
[image_picker] Set the image/video ratio, while taking a picture or recording a video

### ISSUE THREAD

**Issue by TolgaYld** [flutter/flutter#95333]
Hello :),

i have a new Idea for image picker. I can't set the ratio, while i taking a picture or recording a video. For example i want to take a picture or recording a video in widescreen format. It would be great, if i could do that, without image_cropper or other plugins.

thanks in advance :)

**Comment by maheshmnj** [comment]
Hi @TolgaYld, Thanks for filing the issue. Image_picker is mainly intended to pick a video and images from the device. Do third-party plugins like https://pub.dev/packages/image_cropper work for your use case?

**Comment by TolgaYld** [comment]
@maheshmnj  thank you first for your answer. :)

But I would think it would be great if I could adjust the ratio directly while recording. Our scaling is in widescreen format, thatswhy a lot of picture or video is lost, when i crop the image/video via image_cropper.

**Comment by maheshmnj** [comment]
thanks for the info.
