### ISSUE TITLE
cannot find symbol     info.put("sku", purchase.getSku()); in AndroidStudio

### ISSUE THREAD

**Issue by dumptyhumpty2014gmail** [flutter/flutter#95344]
```
.pub-cache\hosted\pub.dartlang.org\in_app_purchase_android-0.2.2\android\src\main\java\io\flutter\plugins\inapppurchase\Translator.java:64: error: cannot find symbol
    info.put("sku", purchase.getSku());
                            ^
  symbol:   method getSku()
  location: variable purchase of type Purchase
```

**Comment by dumptyhumpty2014gmail** [comment]
app is being built if I set in_app_purchase_android 0.1.5 in publ.spec

**Comment by dumptyhumpty2014gmail** [comment]
in_app_purchase_android: 0.2.1 is ok too

**Comment by dumptyhumpty2014gmail** [comment]
sorry. it was because "InAppPurchaseAndroidPlatformAddition.enablePendingPurchases();"

**Comment by dumptyhumpty2014gmail** [comment]
If I use kotlin 1.4.32 Bild is OK
but under kotlin 1.6.10 I catch this problem

**Comment by dumptyhumpty2014gmail** [comment]
when I set kotlin 1.6.10 I set billing 4.0.0 This is problem

**Comment by darshankawar** [comment]
@dumptyhumpty2014gmail 
Please provide `flutter doctor -v`, `pubspec.yaml` and proper description of the issue you are facing along with complete reproducible code sample and error log you are getting in properly formatted text.

**Comment by dumptyhumpty2014gmail** [comment]
I realized that it has to do with the migration to the new API billing 4.0.0 Different getSKU and getSKUs
And in_app_purchase don't support API 4.0.0
For example
Event log
20.12.2021
13:41	* daemon not running; starting now at tcp:5037

13:41	* daemon started successfully

13:44	Gradle sync started

13:47	Gradle sync finished in 3 m 8 s 151 ms

13:50	Executing tasks: [:app:assembleDebug] in project C:\apps\plugins-master\packages\in_app_purchase\in_app_purchase\example\android

13:51	Gradle build failed in 55 s 882 ms
 Error
C:\samsm\flutter_sdk\.pub-cache\hosted\pub.dartlang.org\in_app_purchase_android-0.2.2\android\src\main\java\io\flutter\plugins\inapppurchase\Translator.java:64: error: cannot find symbol
    info.put("sku", purchase.getSku());
                            ^
  symbol:   method getSku()
  location: variable purchase of type Purchase

flutter doctor
C:\apps\plugins-master\packages\in_app_purchase\in_app_purchase\example\androidflutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19044.1415], locale ru-RU)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.63.2)
[√] Connected device (3 available)

pubspec.yaml
name: in_app_purchase_example
description: Demonstrates how to use the in_app_purchase plugin.
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.0

  in_app_purchase:
    # When depending on this package from a real application you should use:
    #   in_app_purchase: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

dev_dependencies:
  flutter_driver:
    sdk: flutter

  integration_test:
    sdk: flutter
  pedantic: ^1.10.0

flutter:
  uses-material-design: true

Code from https://github.com/flutter/plugins/tree/master/packages/in_app_purchase/in_app_purchase

**Comment by darshankawar** [comment]
@dumptyhumpty2014gmail 
The plugin isn't yet migrated to Google Play Billing Library 4.0.0. There's an open issue for tracking that you can refer and follow-up on : https://github.com/flutter/flutter/issues/88664

For now, you'll have to use Library 3.0.0 or whichever is supported.
Closing this as a duplicate. If you disagree, write in comments and I'll reopen.

**Comment by dumptyhumpty2014gmail** [comment]
Please note about on pub.dev that the plugin isn't yet migrated to Google Play Billing Library 4.0.0
