### ISSUE TITLE
Regression: AutofillGroup not working on iOS for credentials

### ISSUE THREAD

**Issue by JoshJuncker** [flutter/flutter#95362]
The following is broken in 2.8, but works in 2.5.3. Hence labeled as a regression.

## Steps to Reproduce

1. Execute `flutter run` on the code sample  on iOS physical device
2. Tap on first form field in the middle
3. Tap on the iOS suggestion 'Passwords'
4. Select one of your devices credentials for autofill
5. Notice that only the username field is filled in, and not the password field

**Expected results:**
Username field filled in as well as password field (all fields in AutofillGroup) and focus switches to the last field (password field)

**Actual results:**
Only username field is filled in and focus stays on the username field.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
          body: Center(
        child: AutofillGroup(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: const <Widget>[
              TextField(
                autofillHints: [AutofillHints.username],
              ),
              TextField(
                autofillHints: [AutofillHints.password],
                obscureText: true,
              ),
            ],
          ),
        ),
      )),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>
```
An Observatory debugger and profiler on Josh’s iPhone is available at: http://127.0.0.1:64714/SV5WnnuEDLE=/
The Flutter DevTools debugger and profiler on Josh’s iPhone is available at: http://127.0.0.1:9103?uri=http://127.0.0.1:64714/SV5WnnuEDLE=/
Keyboard cannot present view controllers (attempted to present <UIKeyboardHiddenViewController_Autofill: 0x104a0ef60>)
```

```
Analyzing test_autofill...                                              
No issues found! (ran in 3.6s)
```

```
[✓] Flutter (Channel stable, 2.8.0, on macOS 12.1 21C52 darwin-x64, locale en)
    • Flutter version 2.8.0 at /Users/joshjuncker/fvm/versions/2.8.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (7 days ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/joshjuncker/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.63.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • Josh’s iPhone (mobile) • 00008101-0009201A3E98001E • ios            • iOS 15.2 19C56
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 96.0.4664.110
    ! Error: Josh’s iPhone is busy: Preparing the watch for development via Josh’s iPhone. Xcode will continue when
      Josh’s iPhone is finished. (code -10)

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report. I verified this on latest stable (2.8.0), previous stable (2.5.3) and can confirm the password is being filled out only in `username` field on latest stable, whereas, in 2.5.3, the same is being filled in `username` as well as `password` field. The current behavior also occurs on latest master.


1. Stable 2.8.0 and master 2.9.0-1.0.pre.107:

<img width="352" alt="Screenshot 2021-12-16 at 2 38 37 PM" src="https://user-images.githubusercontent.com/67046386/146341777-ebd65939-bcdd-4de6-a0bd-6432200bd3c9.png">


2. Stable 2.5.3:

<img width="348" alt="Screenshot 2021-12-16 at 2 38 50 PM" src="https://user-images.githubusercontent.com/67046386/146341879-204ad9f8-f04c-48d3-aa14-374470a5e90e.png">


<details>
<summary> stable, master flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.8.0, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.8.0 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (10 hours ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 93.0.4577.82


• No issues found!

[✓] Flutter (Channel master, 2.9.0-1.0.pre.107, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.9.0-1.0.pre.107 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 048e28ab3d (3 hours ago), 2021-12-15 22:59:12 -0500
    • Engine revision a05c4d23ec
    • Dart version 2.16.0 (build 2.16.0-115.0.dev)
    • DevTools version 2.9.1
    
[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 93.0.4577.82


• No issues found!




```

</details>

**Comment by darshankawar** [comment]
may be related: https://github.com/flutter/flutter/issues/86010

**Comment by djsjr** [comment]
Confirming Autofillhints broken in 2.8.0 for myself with slightly different results.

AutofillGroup is broken. When composed of email and newPassword hint textFields, it will suggest an email when focused on email and then separately suggest the saved password when focused on password textField (instead of suggesting entire saved email-password combo when focused on email within an AutofillGroup).

newPassword is also broken. Does not suggest a new password -or anything else for that matter.

email and givenName still work for me. 

Downgraded to 2.5.3 and everything works fine again.

**Comment by piuskamil** [comment]
It doesn't work for me too in v2.8.1. Only one field is filled at once in AutoFillGroup. 
It was working in the 2.5 version.

**Comment by MirceaX2Mobile** [comment]
Yes, it doesn't work for me too in v2.8.1
In my case the email field is not filled while in AutoFillGroup

**Comment by bssughosh** [comment]
> Yes, it doesn't work for me too in v2.8.1 In my case the email field is not filled while in AutoFillGroup

Yes I faced the same too

**Comment by bssughosh** [comment]
Any workaround for this or should we downgrade the flutter version?

**Comment by briankariuki** [comment]
AutofillGroup not working on android too. Flutter 2.8.0

**Comment by MirceaX2Mobile** [comment]
> Any workaround for this or should we downgrade the flutter version?

A workaround for iOS would be to use username autofillHint, for the email field. But this is not the best way…better downgrade the flutter version.

**Comment by piuskamil** [comment]
> > Any workaround for this or should we downgrade the flutter version?
> 
> 
> 
> A workaround for iOS would be to use username autofillHint, for the email field. But this is not the best way…better downgrade the flutter version.

Not sure about that.
Im using autofillHint.username and autofillHint.password and only one input  is filled at once in 2.8.1.

It was working in 2.5

**Comment by sylvain-flt** [comment]
Got the same issue, and password save popup does not works anymore.
Autofill only fill one element, and must be set as AutofillHints.username

May be useful: absolutely no logs is shown (even in -v mode)

Debugging on iOS 15.2 (iPhone 13 pro)


[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale fr-FR)
    • Flutter version 2.8.1 at /Users/sflattet/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/sflattet/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.31.20211214

[✓] Connected device (2 available)
    • ixn (mobile) • *********  • ios            • iOS 15.2 19C57
    • Chrome (web) • chrome                    • web-javascript • Google Chrome 96.0.4664.110

**Comment by sylvain-flt** [comment]
Any update for this issue?
currently holding production release for our app, until this is resolved.

**Comment by LongCatIsLooong** [comment]
I can't reproduce the problem using the code sample provided. I did the test using the current master branch. @JoshJuncker could you confirm that this is fixed on master?

**Comment by bssughosh** [comment]
> Any update for this issue? currently holding production release for our app, until this is resolved.

Same, even we have held off the release because of this. Please give out a new flutter version if this is fixed already.

**Comment by LongCatIsLooong** [comment]
I was able to reproduce the issue. Closing as a duplicate of https://github.com/flutter/flutter/issues/91354
