### ISSUE TITLE
my flutter page is transparent

### ISSUE THREAD

**Issue by Bmask00** [flutter/flutter#95371]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
Execute flutter run iterm logs:
Resolving dependencies...
  _fe_analyzer_shared 31.0.0 (32.0.0 available)
  analyzer 2.8.0 (3.0.0 available)
  characters 1.1.0 (1.2.0 available)
  json_annotation 4.1.0 (4.4.0 available)
  json_serializable 5.0.2 (6.1.1 available)
  path_provider 2.0.7 (2.0.8 available)
  path_provider_linux 2.1.2 (2.1.4 available)
  pubspec_parse 1.1.0 (1.2.0 available)
  vector_math 2.1.0 (2.1.1 available)
Got dependencies in /Users/bmask/Desktop/sohu-code/MPTC-Flutter/flutterw/tools!
Package flutter_wrapper is currently active at path "/Users/bmask/Desktop/sohu-code/MPTC-Flutter/flutterw/tools".
Activated flutter_wrapper 0.0.1 at path "/Users/bmask/Desktop/sohu-code/MPTC-Flutter/flutterw/tools".
================================================
target packages:

================================================
Launching lib/main.dart on iPhone 12 Pro in debug mode...
Running Xcode build...
 └─Compiling, linking and signing...                        28.6s
Xcode build done.                                           44.0s
Syncing files to device iPhone 12 Pro...                            81ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on iPhone 12 Pro is available at: http://127.0.0.1:51913/-NIOQnEwbC0=/
Activating Dart DevTools...                                      1,090ms
The Flutter DevTools debugger and profiler on iPhone 12 Pro is available at:
http://127.0.0.1:9100?uri=http://127.0.0.1:51913/-NIOQnEwbC0=/

2. ... 
a. cd my_flutter
b. flutter pub get
c.  cd MyApp_flutter
d. pod install
e. xcode run
d. click show flutter button
e. result as mp4 video
 
3. my build message export
[Build MyApp_flutter_2021-12-16T09-48-18.txt](https://github.com/flutter/flutter/files/7724048/Build.MyApp_flutter_2021-12-16T09-48-18.txt)

4.the demo video

https://user-images.githubusercontent.com/96166407/146295418-d14a987c-cae4-4982-b70c-8577b050a29a.mp4

**Comment by Bmask00** [comment]
@darshankawar Yes , I facing same issue as #94554 .

**Comment by Bmask00** [comment]
@darshankawar  There is my code source https://github.com/MrBMask/FluttterDemo you can clone and run your mac as my step.....

**Comment by darshankawar** [comment]
please follow-up in https://github.com/flutter/flutter/issues/94554.
closing this as a duplicate. please don't open multiple issues for same reason.
