### ISSUE TITLE
[tool_crash] ProcessException: The system cannot find the file specified. Command: "C:\Users\pitipat\Desktop\Flutter 2 Bootcamp\calculate\android\gradlew.bat", OS error code: 2

### ISSUE THREAD

**Issue by Wanwiset123** [flutter/flutter#95378]
## Command
```
flutter build apk
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
Oops; flutter has exited unexpectedly: "ProcessException: The system cannot find the file specified.

  Command: "C:\Users\pitipat\Desktop\Flutter 2 Bootcamp\calculate\android\gradlew.bat" -q
  -Ptarget-platform=android-arm,android-arm64,android-x64 -Ptarget=lib\main.dart
  -Pbase-application-name=android.app.Application -Pdart-obfuscation=false -Ptrack-widget-creation=true
  -Ptree-shake-icons=true assembleRelease".
A crash report has been written to C:\Users\pitipat\Desktop\Flutter 2 Bootcamp\calculate\flutter_01.log.
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+ProcessException%3A+The+system+cannot+find+the+file+specified.%0D%0A%0A++Command%3A+%22C%3A%5CUsers%5Cpitipat%5CDesktop%5CFlutter+2+Bootcamp%5Ccalculate%5Candroid%5Cgradlew.bat%22+-q+-Ptarget-platform%3Dandroid-arm%2Candroid-arm64%2Candroid-x64+-Ptarget%3Dlib%5Cmain.dart+-Pbase-application-name%3Dandroid.app.Application+-Pdart-obfuscation%3Dfalse+-Ptrack-widget-creation%3Dtrue+-Ptree-shake-icons%3Dtrue+assembleRelease

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
https://git.io/JDa3T

**Comment by Wanwiset123** [comment]
> ## Command
> ```
> flutter build apk
> ```
> 
> ## Steps to Reproduce
> 1. ...
> 2. ...
> 3. ...
> 
> ## Logs
> Oops; flutter has exited unexpectedly: "ProcessException: The system cannot find the file specified.
> 
> Command: "C:\Users\pitipat\Desktop\Flutter 2 Bootcamp\calculate\android\gradlew.bat" -q -Ptarget-platform=android-arm,android-arm64,android-x64 -Ptarget=lib\main.dart -Pbase-application-name=android.app.Application -Pdart-obfuscation=false -Ptrack-widget-creation=true -Ptree-shake-icons=true assembleRelease". A crash report has been written to C:\Users\pitipat\Desktop\Flutter 2 Bootcamp\calculate\flutter_01.log. This crash may already be reported. Check GitHub for similar crashes. https://github.com/flutter/flutter/issues?q=is%3Aissue+ProcessException%3A+The+system+cannot+find+the+file+specified.%0D%0A%0A++Command%3A+%22C%3A%5CUsers%5Cpitipat%5CDesktop%5CFlutter+2+Bootcamp%5Ccalculate%5Candroid%5Cgradlew.bat%22+-q+-Ptarget-platform%3Dandroid-arm%2Candroid-arm64%2Candroid-x64+-Ptarget%3Dlib%5Cmain.dart+-Pbase-application-name%3Dandroid.app.Application+-Pdart-obfuscation%3Dfalse+-Ptrack-widget-creation%3Dtrue+-Ptree-shake-icons%3Dtrue+assembleRelease
> 
> To report your crash to the Flutter team, first read the guide to filing a bug. https://flutter.dev/docs/resources/bug-reports
> 
> Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you! https://git.io/JDa3T

**Comment by maheshmnj** [comment]
Hi @Wanwiset123, Thanks for filing the issue. Please share the complete output of `flutter doctor -v` and output of 
`flutter run -v` in a textfile to better address the isssue.
