### ISSUE TITLE
Add ignore SSL property in webview

### ISSUE THREAD

**Issue by devmanmath** [flutter/flutter#95389]
Hi,

I am using webview_flutter to load an url and I want to restrict http based url’s by providing ignoreSSL property to a webView. Can you please suggest or provide a solution to add ignoreSSL property.

**Comment by danagbemava-nc** [comment]
There's a similar request for this feature being tracked in https://github.com/flutter/flutter/issues/36925. 

Kindly follow up there for more information. 

Closing from here as duplicate.

**Comment by devmanmath** [comment]
Any update on how to add ignoreSSL error property to webView in flutter?
