### ISSUE TITLE
[image_picker][video_player] Black space on some video on iOS

### ISSUE THREAD

**Issue by LeGoffMael** [flutter/flutter#95381]
Some videos are not displayed properly using video_player on iOS (i did not faced this issue on android)

I noticed that if i replace image_picker by [wechat_assets_picker](https://pub.dev/packages/wechat_assets_picker) this error does not occur.

## Steps to Reproduce

I actually created a [repository](https://github.com/LeGoffMael/example_video_black_borders) to reproduce this problem (only using video_player and image_picker dependencies)

This problem occur only on some videos, but i am unable to find the reason.

I always have this issue with this video: 

https://user-images.githubusercontent.com/22376981/146317252-c784f6fd-33f5-4e45-b5be-d7a30f921fbe.mov

This video was recorded with my iphone 11 pro.

**Expected results:**

The video should be displayed without the black space

**Actual results:** 

the only error i found in log is :
```bash
[core] "Error returned from daemon: Error Domain=com.apple.accounts Code=7 "(null)""
```

<details>
<summary>screenshot</summary>

![IMG_6941](https://user-images.githubusercontent.com/22376981/146316865-cc885f0b-fb45-4c10-99ef-a9c0fc378f40.PNG)

</details>

<details>
<summary>Code sample</summary>

[https://github.com/LeGoffMael/example_video_black_borders](https://github.com/LeGoffMael/example_video_black_borders)

<details>
  <summary>Logs</summary>

```bash
[core] "Error returned from daemon: Error Domain=com.apple.accounts Code=7 "(null)""
```
</details>

**Comment by LeGoffMael** [comment]
I think the error is that the orientation of the video is considered horizontal when it is not

**Comment by LeGoffMael** [comment]
I finally managed to find a fixed process to reproduce this error:
this error occurred every time on : recorded video on portrait, cropped from the gallery.

### to reproduce:
1. open a video recorded with an iPhone (in portrait orientation)
2. crop it and change the ratio (make it more narrow for example)
3. save it
4. when reloading the video with image picker this issue should appear

**Comment by danagbemava-nc** [comment]
Hi @LeGoffMael, it looks like this has already been reported in https://github.com/flutter/flutter/issues/71299. 

Kindly follow up there for more information. 

Closing from here as duplicate.

Thank you
