### ISSUE TITLE
SnackBar duplicated on Master-Detail UI with two Scaffolds

### ISSUE THREAD

**Issue by nailgilaziev** [flutter/flutter#95394]
On multi panel UI (aka master-detail UI pattern for wide screen layouts for tablets or desktop), with two scaffolds in row, calling `.showSnackbar(...)`  cause showing duplicated SnackBar's on each Scaffolds.

disclaimer: There is no nested Scaffolds. 

## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Tap on button from one of the scaffold panels 

**Expected results:** 
Snackbar should be shown in the Scaffold that triggered it.
**Actual results:** 
Snackbar is shown twice. at the `left/master` and `right/details` Scaffolds.
<details>
<summary>Code sample</summary>

```
import 'package:flutter/material.dart';

void main(){
  runApp(MaterialApp(home:TwoPanelsHome()));
}

class TwoPanelsHome extends StatelessWidget {
  const TwoPanelsHome({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Row(
      children: [
        Expanded(child: TestScaffold('left/master')),
        Expanded(child: TestScaffold('right/details'))
      ],
    );
  }
}

class TestScaffold extends StatelessWidget {
  const TestScaffold(this.name, {Key? key}) : super(key: key);

  final String name;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(title: Text(name)),
        body: Center(
          child: ElevatedButton(
            onPressed: () {
              ScaffoldMessenger.of(context)
                  .showSnackBar(SnackBar(content: Text('hello from $name')));
            },
            child: Text('show snack from $name'),
          ),
        ));
  }
}

```

</details>

```
[✓] Flutter (Channel stable, 2.8.0, on macOS 12.0.1 21A559 darwin-x64, locale en-RU)
    • Flutter version 2.8.0 at /Users/ng/Tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (8 days ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0
```

</details>

<img width="721" alt="Screenshot 2021-12-16 at 13 15 38" src="https://user-images.githubusercontent.com/2749021/146352984-91fd09c8-708b-4e01-ad42-4bd44735d3aa.png">

**Comment by nailgilaziev** [comment]
looks like this piece of checking root scaffold logic is recently added here https://github.com/flutter/flutter/issues/77251 
For me current behaviour of duplicated scaffolds looks incompatible with Master-Detail UI pattern

**Comment by Piinks** [comment]
This is working as expected. There is one `ScaffoldMessenger` by default for each route, it sends a `SnackBar` to all descendent `Scaffold`s. If you add a `ScaffoldMessenger` above each `Scaffold` in your example, it will work as you expect.
Controlling the scope of `ScaffoldMessenger` is documented here: https://github.com/flutter/flutter/blob/82c00c12a60283e075e79e015cdbdb264b7f3ed4/packages/flutter/lib/src/material/scaffold.dart#L73

It does mention nested Scaffolds, so we should probably update it to reflect `nested Scaffolds or in cases where more than one Scaffold is visible`.


```dart
import 'package:flutter/material.dart';

void main(){
  runApp(MaterialApp(home:TwoPanelsHome()));
}

class TwoPanelsHome extends StatelessWidget {
  const TwoPanelsHome({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Row(
      children: [
        Expanded(
           // Add a ScaffoldMessenger here 
          child: TestScaffold('left/master'),
        ),
        Expanded(
          // Add a ScaffoldMessenger here
          child: TestScaffold('right/details'),
        )
      ],
    );
  }
}

class TestScaffold extends StatelessWidget {
  const TestScaffold(this.name, {Key? key}) : super(key: key);

  final String name;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(title: Text(name)),
        body: Center(
          child: ElevatedButton(
            onPressed: () {
              ScaffoldMessenger.of(context)
                  .showSnackBar(SnackBar(content: Text('hello from $name')));
            },
            child: Text('show snack from $name'),
          ),
        ));
  }
}
```

**Comment by nailgilaziev** [comment]
Thanks! Maybe you have similar answer for the same multi panel layout and `PopupMenuButton` unexpected behaviour described here https://github.com/flutter/flutter/issues/95425 :)

**Comment by Piinks** [comment]
(Triage) This issue has been resolved, there is additional handling for nested scaffolds now, as well as docs and examples. I am going to close it, but if there is still work to be done here, lave a comment and we can take another look. Thanks!
