### ISSUE TITLE
Introduce ES version build target flag for web

### ISSUE THREAD

**Issue by noherczeg** [flutter/flutter#95401]
## Use case

Currently the production build a Flutter web app produces ES5 output. ES6 / ESNext output would mean a significantly smaller bundle size, and faster startup speed.

## Proposal

The build tool should provide a flag where developers would be able to set the target platform. The default could be `ES5`, but we should be able to pick from others as well, e.g.: `ES6`, `ESNext`, etc...

**Comment by ditman** [comment]
I'm not sure that different ES versions are supported by the dart2js compiler. I'm going to add the `dependency:dart` to see what can be done.

**Comment by whiskeyPeak** [comment]
It looks like dart supports EC6 and has for a while now. Don't know whether Flutter makes use of this feature though.

https://github.com/dart-lang/sdk/issues/46545

**Comment by ditman** [comment]
@whiskeyPeak Flutter takes whatever dart2js does and uses that, so I my guess is that Flutter web is already in ES6 from the issue you linked.

I don't think that dart2js can be configured to output different sets of ES on demand (like going back to ES5 or using some feature from ES Next)

**Comment by kevmoo** [comment]
Going to close this out. We are very careful about upgrading the JS compiler to support a solid set of browsers.
