### ISSUE TITLE
 java.security.NoSuchAlgorithmException: Algorithm HmacPBESHA256 not available/ Debug build okay

### ISSUE THREAD

**Issue by iamwasimaftab** [flutter/flutter#95405]
Java.security.NoSuchAlgorithmException: Algorithm HmacPBESHA256 not available

FAILURE: Build failed with an exception.      (BUILD APK Getting error)

* What went wrong:
Execution failed for task ':app:packageRelease'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > com.android.ide.common.signing.KeytoolException: Failed to read key key from store "/Users/Cylinder/Downloads/W TV/23/new/keystore.jks": Integrity check failed: java.security.NoSuchAlgorithmException: Algorithm HmacPBESHA256 not available

**### And other error during Debug run in screenshot app run but  MP4 Video not playing also some error in screen**
![WhatsApp Image 2021-12-16 at 6 12 56 PM](https://user-images.githubusercontent.com/96113071/146388132-d2485954-0575-48a9-a1d6-040bce5145eb.jpeg)
![Screen Shot 2021-12-16 at 6 03 59 AM](https://user-images.githubusercontent.com/96113071/146388346-2a690814-027b-4d2f-977f-ef669cab9568.png)

**Comment by darshankawar** [comment]
@iamwasimaftab 
For `Integrity check failed: java.security.NoSuchAlgorithmException: Algorithm HmacPBESHA256 not available`, checkout https://stackoverflow.com/questions/67631927/error-building-aab-flutter-android-integrity-check-failed-java-security-n and see if it helps.

For red screen issue, that's code implementation issue for which a simple search over internet will provide you helpful links to resolve.

Closing from here as this isn't a framework issue.
