### ISSUE TITLE
Screen refresh stutters more since updating to latest Flutter version

### ISSUE THREAD

**Issue by vlidholt** [flutter/flutter#9541]
## Steps to Reproduce

After updating to the latest version of Flutter the app feels much less fluid and sometime stutters. It's most noticeable when scrolling, but it might be in transitions etc too.

Haven't got any numbers or anything to back it up, but it almost feels like the vsync is no longer matching the screen refresh. I see the same issue on both iOS and Android.

Last time I updated Flutter was at March 23, sorry I cannot narrow it down further.

## Flutter Doctor

Paste the output of running `flutter doctor` here.

[✓] Flutter (on Mac OS X 10.12.3 16D32, channel master)
    • Flutter at /Users/vik/Projects/flutter
    • Framework revision c794221f96 (32 hours ago), 2017-04-21 08:52:07 +0200
    • Engine revision a5b64899c9
    • Tools Dart version 1.23.0-dev.11.7

[✓] Host Executable Compatibility
    • Downloaded executables execute on host

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/vik/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3, Build version 8E162
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.0

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2016.3.4)
    • Dart plugin version 163.13137
    • Flutter plugin version 0.1.11.1

[✓] Connected devices
    • None

**Comment by eseidelGoogle** [comment]
@chinmaygarde @sethladd

**Comment by Hixie** [comment]
This isn't actionable (it's not exactly clear what the performance regression is). We believe we've improved performance since April though. Please open a new bug if there's a specific performance issue to resolve.
