### ISSUE TITLE
[Mobile] Hide all characters in a TextField, when obscureText is true

### ISSUE THREAD

**Issue by hongquanvn1998** [flutter/flutter#95416]
I need a config like boolean field can make hide all characters when i type on keyboard into textfield. It's very nice

**Comment by darshankawar** [comment]
@hongquanvn1998 
Currently, if we set `obscureText: true` and type in textfield, it first shows the char and then obscures it. Are you saying to fully obscure the text while typing ?

**Comment by hongquanvn1998** [comment]
yes. it my issue. I want to fully obscure the text while typing.

**Comment by Chinmay-KB** [comment]
Maybe instead of having a boolean, it can have an enum, ObscureType.NONE, ObscureType.FULL, ObscureType.ON_TYPE ?

**Comment by darshankawar** [comment]
Closing this as a duplicate of https://github.com/flutter/flutter/issues/80109. Please follow-up in it for further updates.
