### ISSUE TITLE
iOS background platform channels

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#95426]
This issue is to track the implementation of iOS background platform channels.

Original issue: https://github.com/flutter/flutter/issues/91635

This is originally implemented in https://github.com/flutter/engine/pull/29665 but got reverted in https://github.com/flutter/engine/pull/30289

**Comment by cyanglaz** [comment]
cc @gaaclarke @dnfield

**Comment by cyanglaz** [comment]
Marked as P3 to match the original issue.

**Comment by gaaclarke** [comment]
duplicate issue https://github.com/flutter/flutter/issues/91635
