### ISSUE TITLE
Installing other non-Dart dependencies when installing Flutter Desktop

### ISSUE THREAD

**Issue by ljfreelancer88** [flutter/flutter#95430]
## Use case
I'm trying to create a Desktop App for audio (mp3, wave, ogg, etc.) file which requires FFMPEG and other python packages. I have checked the documentation, but I didn't find any information. 

What I have in mind is when a user install the "Flutter Desktop", it checks if there's a FFMPEG and Python installed on their system. If there is none, in the background it will download all these dependencies online. After the installation, it will also download some python packages. It would be nice also to add a feature that can handle if something goes wrong during the dependencies/packages installation.

Maybe a configuration is something like the code below. It's just a draft, just to get the idea.

`init.json`

```json
"require": {
    "python": "^2.1",
    "ffmpeg": "^1.1"
},
"scripts": {
    "post-pip-install": [
        "python3 get-pip.py"
    ],
    "post-package-one-install": [
        "python3 -m pip install -U package1-goes-here"
    ],
    "post-package-two-install": [
        "python3 -m pip install -U package2-goes-here"
    ]
}
```

## Proposal

Add in the documentation a flutter-way on how to integrate/include/install other non-dart/non-flutter dependencies and packages.

Thank you so much!

**Comment by bernaferrari** [comment]
You are doing it wrong, in an over-engineered way.
You can call terminal using dart IO, so you just do:
```dart
final ProcessResult result =
      await Process.run('python3', ['pip', 'install', '-U', 'package2-goes-here'], workingDirectory: workingDirectory);
```

**Comment by stuartmorgan** [comment]
Runtime installation of other software is not in scope for Flutter. You're welcome to build such functionality in your own app, or as a package.
