### ISSUE TITLE
[web] Flutter app inside iframe: scroll and app header is working, Body is not responding

### ISSUE THREAD

**Issue by srivikramanbaskaran** [flutter/flutter#95446]
Hi,
Any suggestion will be so much helpful, My flutter web application is loading inside the iframe of another application(plain HTML). I am noticing some weird behavior: In the android browser scaffold body is scrollable and the button inside it are responding.

Steps to reproduce(download attachment):
1. Run Index.html in port 3000
2. Run main.dart in port 5000
3. In computer open chrome, Go to chrome://inspect and port forward 3000 & 5000
4. Launch android emulator (or) connect the physical device and open chrome application in it and URL: localhost:3000
5. Scroll the flutter iframe top to bottom last and try to click any button inside the scaffold body it won't respond(This issue is happening randomly, please try multiple times)

index.html

```<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
</head>
<body>
hello world
<div>
	<iframe src="http://localhost:5000/#/" width="100%" height="350vh"></iframe>
</div>
</body>
</html>
```

main.dart
```import 'package:flutter/material.dart';

void main() {
  runApp(SampleApp());
}

class SampleApp extends StatelessWidget {
  const SampleApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          actions: [
            FlatButton(
                onPressed: () {
                  print("app bar");
                },
                child: Text("app bar"))
          ],
        ),
        body: Scrollbar(child: SingleChildScrollView(child: Column(children: getColumnWidgets(),),),),
      ),
    );
  }

  List<Widget> getColumnWidgets() {
    var cells = <Widget>[];
    for(var i=0;i<40;i++) {
      cells.add(FlatButton(onPressed: () {
        print("sample");
      }, child: Text("sample")));
    }
    return cells;
  }
}
```

Thanks for any help in advance

**Comment by maheshmnj** [comment]
Hi @srivikramanbaskaran, Thanks for filing the issue. Can you please share what version of the flutter are you using?

Thanks

**Comment by srivikramanbaskaran** [comment]
Hi @maheshmnj, 
Sure, 
**Command used:** 
```flutter --version```
**Response:**
```Flutter 2.8.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision cf44000065 (9 days ago) • 2021-12-08 14:06:50 -0800
Engine • revision 40a99c5951
Tools • Dart 2.15.0```

Thanks

**Comment by maheshmnj** [comment]
HI @srivikramanbaskaran, Thanks for filing the issue. Can you please try using pointer interceptor as mentioned here and see if that helps https://github.com/flutter/flutter/issues/68903#issuecomment-747811526.

**Comment by srivikramanbaskaran** [comment]
@maheshmnj Tried pointer interceptor library for this issue, But it is not working

**Comment by maheshmnj** [comment]
> Scroll the flutter iframe top to bottom last and try to click any button inside the scaffold body it won't respond(This issue is happening randomly, please try multiple times)

@srivikramanbaskaran, I tried reproducing this, I was not able to verify it on a real device. However, on a simulator, the flutter view was not able to detect gestures but it works on a desktop. Is this the same issue you are referring to


Desktop(web) | IOS (web)
:-: | :-:
<video src='https://user-images.githubusercontent.com/31410839/146900385-a326ffbe-11d2-4539-a173-935f23c033df.mov' width=180/> | <video src='https://user-images.githubusercontent.com/31410839/146900392-1c8dd376-199f-4624-b28b-36b71ba2254c.mov' width=180/>
