### ISSUE TITLE
No information is given for 2.8.1 hotfix - the "Hotfixes to the Stable Channel" page has nothing

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/flutter#95444]
Hi thanks for the lib! When I want to know what is hotfixed for 2.8.1, I follow instruction of https://docs.flutter.dev/development/tools/sdk/releases and https://docs.flutter.dev/development/tools/sdk/release-notes:

>  Note: For information about bug-fix releases, see Hotfixes to the Stable Channel on the Flutter wiki.

But https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel says nothing about 2.8.1...

I guess someone just forgets to update the wiki ;)

**Comment by thphuc** [comment]
I did the same this morning when I wanted to see what's new :)

**Comment by maheshmnj** [comment]
Hotfix release notes for stable 2.8.1 are now available at https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel

**Comment by fzyzcjy** [comment]
:tada:

**Comment by maheshmnj** [comment]
Closing as the wiki is already updated.
