### ISSUE TITLE
PlatformView sometime not working

### ISSUE THREAD

**Issue by haoguo** [flutter/flutter#95449]
## Steps to Reproduce

Prepare a device with Harmony OS 2.0.0, maybe some version of android have this problem too.

1. Using a PlatformView such as WebView.
2. Execute `flutter run` on this device
3. Now it is fine
4. Close the app then relaunch it by just click the icon on the desktop
5. The PlatformView would not show up.

**Expected results:** The PlatformView show up.

**Actual results:** The PlatformView would not show up.

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel unknown, 2.8.1, on macOS 11.6 20G165 darwin-x64, locale zh-Hans)
    • Flutter version 2.8.1 at /Users/xxxx/Workspace/flutter
    • Upstream repository unknown
    • Framework revision 77d935af4d (11 hours ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1
```

</details>

<details>
  <summary>What I found</summary>
  I have two PlatformView used in our project. One is WebView and another is implemented by ourself. It works as I want on Android and iOS. I have a test device with Harmony OS 2.0.0. Found that if the application is launched by flutter run, the platform view works fine. If not, the platform view would not work. I have

```java
class ViewA implements PlatformView {

  private ViewB viewB;

  @Override
  public void onFlutterViewDetached() {}

  @Override
  public View getView() { return viewB; }

}

class ViewB extends FrameLayout {

  @Override
  protected void onDetachedFromWindow() {
  }

}
```
I found when it does not work, the ViewB::onDetachedFromWindow has been invoked but ViewA::onFlutterViewDetached has not been invoked. I did nothing so that the view should not be disposed or removed. I didn't figure out why this would behave differently between launched by ```flutter run``` or not. Specially the os is HarmonyOS but I guess some version android would have the same issue too. 

Call stack of ViewB::onDetachedFromWindow attached
![image](https://user-images.githubusercontent.com/8232111/146497382-05733092-ae50-41d3-99d9-8aacbdc1f0e9.png)

</details>

**Comment by darshankawar** [comment]
@haoguo 
Please check [this](https://github.com/flutter/flutter/issues/38437#issuecomment-528469296) issue comment regarding Flutter's support for Harmony OS, that will give you an idea that if it's specific to Harmony OS, then the behavior is expected since Flutter doesn't support that OS.

Also, regarding your comment on some Android device may show the same behavior, in order to properly verify that, please provide a [complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example
) that we can use to verify and confirm.

**Comment by haoguo** [comment]
@darshankawar 
Thanks for your help, finally solved this issue without big change.
Found that on HarmonyOS, VirtualDisplay platform view have some problems. Similar with #89146.
Change to hybrid composition can works.
