### ISSUE TITLE
Should we rename https://github.com/flutter/flutter project's branch name from master to main?

### ISSUE THREAD

**Issue by eggfly** [flutter/flutter#95457]
Just like https://github.com/flutter/engine repo:
It's 404 -> https://github.com/flutter/flutter/tree/main
The engines repo's master and main are same -> https://github.com/flutter/engine/tree/master -> https://github.com/flutter/engine/tree/main

**Comment by stuartmorgan** [comment]
Duplicate of https://github.com/flutter/flutter/issues/90476
