### ISSUE TITLE
FocusNode being disposed more than once

### ISSUE THREAD

**Issue by NebulaFox** [flutter/flutter#95469]
More of a discussion.

I was using `FocusNode`s with `TextField`s in an app. Because I was creating the `FocusNode`s in a `StatefulWidget` and following the [cookbook](https://docs.flutter.dev/cookbook/forms/focus), I called `dispose` in the `State` of the `StatefulWidget`.
I then started receiving errors that the `FocusNode.dispose` method was being called more than once. Checking `TextField`'s code, [I found it's calling dispose on the `focusNode`](https://github.com/flutter/flutter/blob/77d935af4db863f6abd0b9c31c7e6df2a13de57b/packages/flutter/lib/src/material/text_field.dart#L1025) – the `_effectiveFocusNode` is [here](https://github.com/flutter/flutter/blob/77d935af4db863f6abd0b9c31c7e6df2a13de57b/packages/flutter/lib/src/material/text_field.dart#L843) – leading to my error.

With the [cookbook](https://docs.flutter.dev/cookbook/forms/focus) and the documention in `FocusNode` saying I should be disposing, it is confusing why I would get the error.

> If, as is common, the hosting StatefulWidget is also the owner of the focus node, then it will also call dispose from its State.dispose (in which case the FocusAttachment.detach may be skipped, since dispose will automatically detach). If another object owns the focus node, then it must call dispose when the node is done being used. 

Taken from [`FocusNode` documentation](https://api.flutter.dev/flutter/widgets/FocusNode-class.htmlhttps://api.flutter.dev/flutter/widgets/FocusNode-class.html)

I think there is a bit of a design discussion or explanation that is needed here: when is it clear some widget/class is taking ownership of another widget/class that it will then dispose?

As a fix suggestion, maybe the documentation needs to be updated to reflect that `TextField` and other widgets/classes that use `FocusNode` will `dispose` of the `FocusNode` for me.

I will try and create an example to showcase the error, but it will require the `StatefulWidget` actually being disposed, which is why I believe that the cookbook example works without error.

**Comment by darshankawar** [comment]
@NebulaFox 
In order to properly address this, can you provide us an example that highlights the behavior you described ?

**Comment by NebulaFox** [comment]
Looks like I was calling dispose twice on a `FocusNode` so no issue to worry about.

Is it possible to get an explanation how the `dispose` of the `FocusNode` in the `TextField` and `dispose` done in app created `StatefulWidget` works, in that, how does `dispose` doesn't end up being called twice on the `FocusNode`. Thanks.

**Comment by darshankawar** [comment]
> `dispose` of the `FocusNode` in the `TextField` and `dispose` done in app created `StatefulWidget`

The focusNode should be disposed when the stateful widget that contains it is disposed and it's better to do this in stateful widget so that it manages FocusNode's lifetime in it. 
Regarding `focusnode` in the textfield scenario, maybe the textfield tries to remove the listener it added to the focusnode and hence disposing it after the app has disposed focusnode.

Hope above gives you an idea, so I am going ahead and closing this as resolved. If you still have any questions or doubts, write in comments and I'll reopen it.
Thanks.
