### ISSUE TITLE
Docs paths are missing

### ISSUE THREAD

**Issue by branflake2267** [flutter/flutter#9546]
## Steps to Reproduce
1. Goto: https://flutter.io/search/?cx=007067728241810524621%3Agm6vraqlc8c&ie=UTF-8&hl=en&q=http
2. Search for "dart convert" 

It appears the dart library paths are broken. 

![screen shot 2017-04-23 at 3 12 49 pm](https://cloud.githubusercontent.com/assets/1326504/25317918/b8e93440-2837-11e7-9db8-372dad812a1b.png)

**Comment by Hixie** [comment]
We recently renamed them. Google will catch up soon.
