### ISSUE TITLE
2.8.1 breaks IOS build ipa. With Cocoapod  Pods install error "Consistency issue: build setting IPHONEOS_DEPLOYMENT_TARGET has multiple values"

### ISSUE THREAD

**Issue by dickverweij** [flutter/flutter#95470]
after upgrading to 2.8.1 our ios build wont build anymore because of this error,

During the Pod-Install
              [Xcodeproj] Consistency issue: build setting `IPHONEOS_DEPLOYMENT_TARGET` has multiple values: `{"Release"=>"9.0", "Debug"=>"8.0", "Profile"=>"8.0"}`

If we downgrade to 2.8.0 it compile and builds fine.

Our PodFile:

```
# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks! 
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
    flutter_additional_ios_build_settings(target)
    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'

      # You can enable the permissions needed here. For example to enable camera
      # permission, just remove the `#` character in front so it looks like this:
      #
      # ## dart: PermissionGroup.camera
      # 'PERMISSION_CAMERA=1'
      #
      #  Preprocessor definitions can be found in: https://github.com/Baseflow/flutter-permission-handler/blob/master/permission_handler/ios/Classes/PermissionHandlerEnums.h
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',

        ## dart: PermissionGroup.calendar
         'PERMISSION_EVENTS=1',

        ## dart: PermissionGroup.reminders
        # 'PERMISSION_REMINDERS=1',

        ## dart: PermissionGroup.contacts
         'PERMISSION_CONTACTS=1',

        ## dart: PermissionGroup.camera
         'PERMISSION_CAMERA=1',

        ## dart: PermissionGroup.microphone
        # 'PERMISSION_MICROPHONE=1',

        ## dart: PermissionGroup.speech
        # 'PERMISSION_SPEECH_RECOGNIZER=1',

        ## dart: PermissionGroup.photos
         'PERMISSION_PHOTOS=1',

        ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
         'PERMISSION_LOCATION=1',
       
        ## dart: PermissionGroup.notification
         'PERMISSION_NOTIFICATIONS=1',

        ## dart: PermissionGroup.mediaLibrary
        # 'PERMISSION_MEDIA_LIBRARY=1',

        ## dart: PermissionGroup.sensors
        # 'PERMISSION_SENSORS=1',   
        
        ## dart: PermissionGroup.bluetooth
         'PERMISSION_BLUETOOTH=1',

        ## dart: PermissionGroup.appTrackingTransparency
        # 'PERMISSION_APP_TRACKING_TRANSPARENCY=1',

        ## dart: PermissionGroup.criticalAlerts
        # 'PERMISSION_CRITICAL_ALERTS=1'
      ]

    end
  end
end


```

**Comment by jonmountjoy** [comment]
I had this on a previous release, and the following fixed it for me (which I do on any new release):

* flutter clean
* rm pubspeck.lock # woohoo
* rm ios/Podfile.lock
* flutter pub get
* flutter build etc. 

I'm guessing that deleting the lock files may be overkill, but it seemed to do the trick.  For me.

**Comment by darshankawar** [comment]
@dickverweij 
Can you provide complete `flutter run --verbose` log ?

**Comment by dickverweij** [comment]
flutter run does work, it builds for chrome, 
I used flutter build ipa --verbose instead and I cropped the log from "runnng pod install" 

[verbose.txt](https://github.com/flutter/flutter/files/7751100/verbose.txt)

**Comment by dickverweij** [comment]
> I had this on a previous release, and the following fixed it for me (which I do on any new release):
> 
> * flutter clean
> * rm pubspeck.lock # woohoo
> * rm ios/Podfile.lock
> * flutter pub get
> * flutter build etc.
> 
> I'm guessing that deleting the lock files may be overkill, but it seemed to do the trick. For me.

did not work, We have also this issue on our automated build, which always builds from clean installs..

**Comment by darshankawar** [comment]
From the log, it seem to fail and throw:

`[!] An error occurred while processing the post-install hook of
the Podfile.`, so something from your podfile from `post_install` section it is complaining about.
Did you add this now or was it there earlier : `config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'` ?
Can you try to remove it and see if it helps ?

**Comment by dickverweij** [comment]
I added that earlier, because of 
[](https://stackoverflow.com/questions/64707834/xcode-12-deployment-warnings-iphoneos-deployment-target)

if I remove it helps indeed, it will build the ipa now..

**Comment by darshankawar** [comment]
If you add that entry, it'll specifically look for that version of the pods and hence you may have been seeing the issue. After removing it and it builds fine, I'll go ahead and close. If you disagree, write in comments and I'll reopen it.
