### ISSUE TITLE
Crossdart fails for plugins

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#9547]
Crossdart has no info for url_launcher:
https://pub.dartlang.org/packages/url_launcher + click 'source code'

Log file:
https://www.crossdart.info/p/url_launcher/0.1.1/log.txt

**Comment by eseidelGoogle** [comment]
I don't think this blocks M2.  But I'm glad we noticed. :)

**Comment by mit-mit** [comment]
I think the fix for this is to: 

1. get a Flutter SDK installed on the crossdart builder, and
1. set the environment variable FLUTTER_ROOT to the path of the Flutter SDK so that Pub/Dartdoc/etc. can locate the Flutter SDK.

**Comment by mit-mit** [comment]
A bit of experimentation to back this theory:
```
mit-macbookpro2:url-launcher mit$ dartdoc
Resolving dependencies...
Resolving dependencies...

The Flutter SDK is not available.
Depended on by:
- url_launcher
mit-macbookpro2:url-launcher mit$ export FLUTTER_ROOT=~/dev/github/flutter
mit-macbookpro2:url-launcher mit$ dartdoc
Resolving dependencies...
Got dependencies!
Generating documentation for 'url_launcher' into /Users/mit/tmp/plugins/packages/url-launcher/doc/api/
```

**Comment by astashov** [comment]
I tried that, now it complains:

```bash
$ pub get
Resolving dependencies... 
Could not find package sky_engine at "/flutter/bin/cache/pkg/sky_engine".
Depended on by:
- flutter 0.0.22 
```

I checked - there's no that sky_engine indeed. Where to get it?

**Comment by mit-mit** [comment]
Oh, sorry, I think we are missing a step: After the `git clone`, can you try to run `flutter\bin\flutter precache`?

**Comment by astashov** [comment]
Umm, it complains:

```
   Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎
```

I know, I know, but I really want to run it with root... Is there a way to workaround this?

**Comment by mit-mit** [comment]
Don't think that we [currently support that](https://github.com/flutter/flutter/blob/master/bin/flutter#L55); let me dig a bit and see if that can get changed!

**Comment by Hixie** [comment]
@astashov  Why do you want to run as root?

**Comment by astashov** [comment]
I just run everything in a GCE startup script, which is root by default. Maybe not a best decision, but would require some effort to change that. Curious why it's so bad to run it under root?

**Comment by mit-mit** [comment]
@astashov do you think you will be able to change your script to not run as root?

**Comment by mit-mit** [comment]
@astashov maybe a solution [like this](http://stackoverflow.com/questions/31846181/startup-script-not-as-root-google-cloud-compute-ubuntu-14-04-vm) would work (i.e., keep your current script, but call out to a second script that installs Flutter with a second non-root account)?

**Comment by mit-mit** [comment]
Also, note that we are seeing the exact same failure on dartdocs.org: https://github.com/flutter/flutter/issues/9796

**Comment by mit-mit** [comment]
@astashov did you have a chance to look at this?

**Comment by astashov** [comment]
No, not yet, sorry.

**Comment by mit-mit** [comment]
Would really like to see a resolution to this. Having 404s from plugin landing pages is not a good user experience. @astashov do you think you will get to this soon?

**Comment by astashov** [comment]
Don't have much time now, unfortunately. Actually, gonna try to look into it this night, will see what I could do there.

**Comment by eseidelGoogle** [comment]
We can remove the root restriction if absolutely necessary (or at a temporary flag to override the check).  Running as root inside a VM isn't really that harmful.  But letting normal users accidentally run as root is just handing them a footgun.

**Comment by mit-mit** [comment]
@astashov we removed the root restriction, can you try the fix from three weeks ago again?

**Comment by astashov** [comment]
Oh really? And I'm trying to run it not under root like right now... :)

**Comment by mit-mit** [comment]
Yes, sorry about flip-flopping. Just merged it in https://github.com/flutter/flutter/commit/97f7ddf2915d725e25ac2f06901e1b4cc8bbc5d2.

**Comment by Hixie** [comment]
@astashov Long term we want to put the restriction back, FWIW. But we wanted to unblock you.

**Comment by mit-mit** [comment]
@astashov is it working now with the root restriction removed? Or are you hitting new problems?

**Comment by astashov** [comment]
Hitting new problems - by some reason the script either ignores or doesn't see `FLUTTER_ROOT`. I'll continue investigating tonight.

**Comment by astashov** [comment]
Okay, I think it is fixed. I also think it'd work now even with the root restriction.

**Comment by mit-mit** [comment]
Excellent news, great to see this fixed. Thanks a lot!
