### ISSUE TITLE
Flutter websocket credential for web

### ISSUE THREAD

**Issue by MuharremCetin** [flutter/flutter#95476]
I need to use websocket in flutter web project. WebSocketChannel works, but I need to use authorization. So I need to add header information. I used IOWebSocketChannel for this, but the web platform does not support dart.io. Do you have any other solution?

**Comment by darshankawar** [comment]
@MuharremCetin 
Check [this](https://github.com/flutter/flutter/issues/45982) issue and underlying comments and see if it helps to answer your question.
