### ISSUE TITLE
GPUSurfaceMetal produce junk often

### ISSUE THREAD

**Issue by Renesanse** [flutter/flutter#95483]
Flutter (Channel stable, 2.8.0).
![Screenshot 2021-12-18 at 01 32 14](https://user-images.githubusercontent.com/42138594/146615542-452d04eb-59bc-4b56-a379-c4fd3b6a3e7e.png)
![Screenshot 2021-12-18 at 01 32 25](https://user-images.githubusercontent.com/42138594/146615556-60cbe6c7-1261-408d-989d-86c70f6621b4.png)

**Comment by mamuseferha** [comment]
Hi @Renesanse 
Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you
