### ISSUE TITLE
Memory regression on animation_with_microtasks_perf_ios__timeline_summary

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#95482]
On the Engine -> Framework roll here https://github.com/flutter/flutter/pull/95364

SkiaPerf reported a regression in memory footprint: https://flutter-flutter-perf.skia.org/e/?begin=1638589447&end=1639742351&keys=Xc9227e34ea819ed1d1d7c1f2ca07f395&requestType=0&xbaroffset=26919

My guess is that it's due to the change to enable compressed pointers on iOS: https://github.com/flutter/engine/pull/30333

/cc @a-siva

**Comment by chinmaygarde** [comment]
Per @a-siva the snapshot size could increase but the runtime memory usage should decrease. The regressions here seem to be related to runtime memory usage however. This warrants further investigation.
<img width="1149" alt="Screen Shot 2021-12-20 at 10 37 02 AM" src="https://user-images.githubusercontent.com/44085/146816288-71f90bec-00e0-4d4d-8c08-4028ef134d88.png">

**Comment by zanderso** [comment]
@a-siva Is this something we should be concerned about for the upcoming beta branch cut?

**Comment by a-siva** [comment]
Investigating and will report back

**Comment by rmacnak-google** [comment]
There are two effects here:

* One is that what was in the ReadOnlyData snapshot section is now in the Isolate snapshot section and deserialized into both the main isolate and the service isolate. (flutter/engine@6ffe7888ec277a697d6a1f5cd9cabc7b9ab55d9f decoupled the service isolate for Android but not iOS.) This affects profile mode but not release mode, and this benchmark is measuring in profile mode.
* madvise(DONTNEED) is lazy on macOS/iOS: the pages are not immediately released and RSS does not immediately decrease as on Linux/Android, but the pages will be released once there is memory pressure.

**Comment by a-siva** [comment]
@chinmaygarde  Do we know why decoupling the service isolate snapshot from the main isolate snapshot was not done for iOS?

**Comment by jason-simmons** [comment]
It should be possible to do that for iOS.  Someone familiar with the iOS platform would need to add the service isolate snapshot library to the iOS build and find a way to package it into the iOS embedding.

**Comment by zanderso** [comment]
Thanks @jason-simmons. I think we can lower the priority of this, but maybe @iskakaushik or @cyanglaz would be interested in the iOS side since it IIRC it was a pretty substantial memory footprint improvement.

**Comment by a-siva** [comment]
> Thanks @jason-simmons. I think we can lower the priority of this, but maybe @iskakaushik or @cyanglaz would be interested in the iOS side since it IIRC it was a pretty substantial memory footprint improvement.

yes, it is a substantial memory footprint improvement especially for large apps.

**Comment by jonahwilliams** [comment]
Closing as obsolete, compressed pointers were disabled
