### ISSUE TITLE
Additional config for iOS, macOS and Android in GTK Flutter codelab

### ISSUE THREAD

**Issue by cklanac** [flutter/flutter#95485]
Regarding step #4 in Get to know Firebase for Flutter

- https://firebase.google.com/codelabs/firebase-get-to-know-flutter#3
- https://github.com/flutter/codelabs/blob/master/firebase-get-to-know-flutter/steps/index.lab.md

It should be pointed out to the reader that the starter code has some changes to the `build.gradle` and Podfiles. If the reader (like me) tries to build the app by copying the source in the `lib` folder to a clean new flutter project (eg counter) then the following changes will be missing.

For Android you must update the `minSdkVersion` in the `Android/app/build.gradle` file to `minSdkVersion 21` or provide instructions on how/where to set the `flutter.minSdkVersion`

```
    defaultConfig {
        applicationId "com.example.gtk_flutter"

       minSdkVersion 21
        // minSdkVersion flutter.minSdkVersion // how to set?
        // targetSdkVersion flutter.targetSdkVersion  // how to set?
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

```

For iOS you must update the Podfile to `platform :ios, '10.0'` and should also update the iOS Deployment Target in xCode.

Likewise for macOS you must update the Podfile to `platform :osx, '10.12'` and should also update the iOS Deployment Target in xCode.

**Comment by domesticmouse** [comment]
The codelab has been updated to utilise `flutterfire` command line tooling, which handles these changes.
