### ISSUE TITLE
/Users/jing/.pub-cache/hosted/pub.flutter-io.cn/image_picker-0.7.5+4/ios/Classes/FLTImagePickerPhotoAssetUtil.m:5:9: In file included from /Users/jing/.pub-cache/hosted/pub.flutter-io.cn/image_picker-0.7.5+4/ios/Classes/FLTImagePickerPhotoAssetUtil.m:5:

### ISSUE THREAD

**Issue by zhangxiaobin123456** [flutter/flutter#95489]
I use    image_picker: ^0.7.0 #图片选择   in pubspec.yaml   
but run is failed

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.7 19H2 darwin-x64, locale
    zh-Hans-CN)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[!] Xcode - develop for iOS and macOS
    ✗ Xcode 11.0.0 out of date (12.0.1 is recommended).
      Download the latest version or update via the Mac App Store.
[✗] Chrome - develop for the web (Cannot find Chrome executable at
    /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[!] Android Studio (not installed)
[!] Connected device
    ! No devices available

help me,thanks

**Comment by zhangxiaobin123456** [comment]
supplement:
/Users/jing/.pub-cache/hosted/pub.flutter-io.cn/image_picker-0.7.5+4/ios/Classes/FLTImagePickerPhotoAssetUtil.m:26:42: Expected a type

/Users/jing/.pub-cache/hosted/pub.flutter-io.cn/image_picker-0.7.5+4/ios/Classes/FLTImagePickerPhotoAssetUtil.m:27:83: Property 'assetIdentifier' not found on object of type '__strong id'

**Comment by darshankawar** [comment]
@zhangxiaobin123456 
You are using an older version of image_picker. Current latest version is `0.8.4+4`. Also you are on older version of stable, current stable is 2.8.1. I recommend to upgrade both to latest and try again to see if it works or not.

If not, please provide `flutter doctor -v`, and complete minimal reproducible code sample that we can use to verify the issue.

**Comment by zhangxiaobin123456** [comment]
> @zhangxiaobin123456 You are using an older version of image_picker. Current latest version is `0.8.4+4`. Also you are on older version of stable, current stable is 2.8.1. I recommend to upgrade both to latest and try again to see if it works or not.
> 
> If not, please provide `flutter doctor -v`, and complete minimal reproducible code sample that we can use to verify the issue.

Thank you. I upgraded Xcode to solve this problem
