### ISSUE TITLE
Exception in thread "main" java.net.SocketTimeoutException: Read timed out

### ISSUE THREAD

**Issue by AbdallahR99** [flutter/flutter#95493]
I can't run the Flutter app, it's always giving me "Exception in thread "main" java.net.SocketTimeoutException: Read timed out"
I completely disabled my firewall and java websites works fine on the browser and I don't use any proxy

my flutter doctor -v results:
> [√] Flutter (Channel stable, 2.8.0, on Microsoft Windows [Version 10.0.22000.376], locale ar-EG)
>     • Flutter version 2.8.0 at C:\src\flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision cf44000065 (9 days ago), 2021-12-08 14:06:50 -0800
>     • Engine revision 40a99c5951
>     • Dart version 2.15.0
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
>     • Android SDK at C:\Users\abdal\AppData\Local\Android\Sdk
>     • Platform android-31, build-tools 31.0.0
>     • ANDROID_HOME = C:\Users\abdal\AppData\Local\Android\Sdk
>     • ANDROID_SDK_ROOT = C:\Users\abdal\AppData\Local\Android\Sdk
>     • Java binary at: E:\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
>     • All Android licenses accepted.
> 
> [√] Chrome - develop for the web
>     • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe
> 
> [√] Android Studio (version 2020.3)
>     • Android Studio at E:\Android\Android Studio
>     • Flutter plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
> 
> [√] VS Code (version 1.63.2)
>     • VS Code at C:\Users\abdal\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension version 3.29.0
> 
> [√] Connected device (4 available)
>     • JSN L22 (mobile)        • GBT4C18A11006410 • android-arm64  • Android 10 (API 29)
>     • sdk gphone x86 (mobile) • emulator-5554    • android-x86    • Android 11 (API 30) (emulator)
>     • Chrome (web)            • chrome           • web-javascript • Google Chrome 96.0.4664.110
>     • Edge (web)              • edge             • web-javascript • Microsoft Edge 96.0.1054.57
> 
> • No issues found!

the error log:
> Launching lib\main.dart on sdk gphone x86 in debug mode...
> lib\main.dart:1
> Exception in thread "main" java.net.SocketTimeoutException: Read timed out
> 	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
> 	at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
> 	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
> 	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
> 	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
> 	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:292)
> 	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
> 	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:754)
> 	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
> 	at java.base/sun.net.www.protocol.http.HttpURLConnection.doTunneling(HttpURLConnection.java:2085)
> 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:195)
> 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
> 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
> 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
> 	at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
> 	at org.gradle.wrapper.Download.download(Download.java:44)
> 	at org.gradle.wrapper.Install$1.call(Install.java:61)
> 	at org.gradle.wrapper.Install$1.call(Install.java:48)
> 	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
> 	at org.gradle.wrapper.Install.createDist(Install.java:48)
> 	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
> 	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
> Exception: Gradle task assembleDebug failed with exit code 1
> Exited (sigterm)

**Comment by darshankawar** [comment]
@AbdallahR99 
Can you create a new Flutter app and see if you still get same exception ?
Can you provide your android and app level `build.gradle` along with gradle version you are using ?

**Comment by AbdallahR99** [comment]
I fixed the problem by change the date format of Windows 11 to English

**Comment by darshankawar** [comment]
Closing this as resolved based on above comment.
