### ISSUE TITLE
Problems with breakpoints in plugin base with kotlin code

### ISSUE THREAD

**Issue by Josua2012** [flutter/flutter#95497]
Hi all,
I have created the base structure for a plugin following this example:
**https://blog.bam.tech/en/developer-news/how-to-debug-flutter-plugins-on-platformchannel** 
with the command:
`flutter create --template = plugin --platforms = android, ios bam_plugin`

Android studio 4.1.3 correctly loads the project and if I run it in debugging mode on a physical android device the **example runs correctly**, a breakpoint in the dart code works fine, however in the kotlin code of the plugin it does not stop the execution of the application.
Curiously, the kotlin file shows some warnings as can be seen in the following image:
![2021-12-18_12-07-59](https://user-images.githubusercontent.com/1523607/146639151-533c4ffe-af4b-42e7-a707-06201348fee9.jpg)

![2021-12-18_12-26-49](https://user-images.githubusercontent.com/1523607/146639277-787445ed-0225-46a3-8c24-2aaba427df73.jpg)

Flutter doctor indicates that everything is correct.
![2021-12-18_12-10-31](https://user-images.githubusercontent.com/1523607/146639159-2b2c9f93-70f7-4842-a65b-cbbdb968ce68.jpg)

The funny thing is that **everything works correctly**, except for the **breakpoints** in the code of the **kotlin file**.
Is this a bug? 

Thanks so much for the help. 
Regards,
Jose

**Comment by stuartmorgan** [comment]
The Dart debugger cannot be used to debug native code; this is expected behavior. You'd need to run the process under a Java/Kotlin debugger instead to debug that code.
