### ISSUE TITLE
ReactiveImagePicker Pass value to Firebase 

### ISSUE THREAD

**Issue by alshueiliproject** [flutter/flutter#95490]
hi 
I'm using ReactiveImagePicker with ReactiveFormBuilder
I have difficult to passing value from the ReactiveImagePicker   to the Firebase

 [refrence ](https://pub.dev/packages/reactive_image_picker/example)
https://stackoverflow.com/questions/51338041/how-to-save-image-file-in-flutter-file-selected-using-image-picker-plugin

 code `  file = File(_image.toString());
    final picker = ImagePicker();
    await ref.putFile(file);
    imageurl = await ref.getDownloadURL();
    print(imageurl);`

**Comment by darshankawar** [comment]
@alshueiliproject 
This doesn't seem to be a correct repo for your issue. I think you need to ask this in https://github.com/artflutter/reactive_forms_widgets/issues
Closing from here.
