### ISSUE TITLE
gl_version_string can't run flutter linux desktop apps if the user have a NVIDIA GPU card

### ISSUE THREAD

**Issue by bjarkan** [flutter/flutter#95500]
https://github.com/flutter/flutter/issues/85460

It's P4, but according to https://github.com/flutter/flutter/wiki/Triage
quote: 
P4 for bona fide bugs in current functionality (including regressions)
...
P2 issues are bugs that block top-tier customers from shipping soon, or breaks in core functionality affecting most users.

Let me explain... If I want to develop an app to sell it to a client that use Linux as Desktop, my app won't work if the client have a NVIDIA GPU card, ergo... **It is an issue that block not only top-tier customer, any customer from shipping theirs apps.** 

NVIDIA GPU card are too popular so, that issue #85460 is not triaged according to your rules... it needs to be P2, not P4. And we need it solved soon. 

Before people realize that flutter cannot deliver Linux desktop apps as promised in the web page, and change to another SDK, leaving flutter behind for another SDK.

P.D. #85460 was notified in Jun 28th 2021, still no work done at Dec 18th, almost 6 months ago.

**Comment by stuartmorgan** [comment]
Do not deliberately file duplicate issues because you don't like them way the original was prioritized. It will not change anything, it just wastes people's time.
