### ISSUE TITLE
To make developers know when an exception is not handled

### ISSUE THREAD

**Issue by josepcapotorres** [flutter/flutter#95508]
## Use case

Calling a method that can throw an exception inside another method.

## Proposal

I suggest you do what Java does: indicate which exceptions can be thrown on the method "header", through "throws" keyword.
As Clean Code says, the try-catch has to be used outside the method that can throw exceptions, not inside of it.
This way, if we call this method and we don't wrap it with a try-catch, Dart will notify us, in order to make Dart and apps more secure and stable.

[<img src="https://user-images.githubusercontent.com/50614497/146646387-c86f34af-c304-4cb8-a90f-12b1dff02f8f.png" width="400"/>](https://user-images.githubusercontent.com/50614497/146646387-c86f34af-c304-4cb8-a90f-12b1dff02f8f.png)

**Comment by bernaferrari** [comment]
You should open this on Dart/lang, not Flutter.

**Comment by josepcapotorres** [comment]
Thank you for the information. I thought that this feature would be interesting to be developed.

**Comment by stuartmorgan** [comment]
Closing since as mentioned above this is a request for the Dart language, so would need to be filed at https://github.com/dart-lang/language
