### ISSUE TITLE
[web] base href not working when deploying to Github pages.

### ISSUE THREAD

**Issue by CenaAshoori** [flutter/flutter#95503]
Hi everyone.
I know I can change the base href from the index.html after the build. but I think there is something wrong when you want to push these files on github.io pages.

##  for **username.github.io**
if base href be "/" the page will load and also it'll cached whole things.

but if you create a new organization and then add the repo and push all the build files to that repo and then create a webpage for it
the address gonna be like this: **organization.github.io/repo** and
## for **organization.github.io/repo**
if base href be "/" like this the page won't be load.

and if you change the base href to the "/repo/" it will load but next time you will refresh the tab on the browser you should wait as first time. and nothing actually cached in this case.

and if you go to developer mode of the browser and see the network tab you see that it can't find the flutter_service_worker.js
and the link of the **flutter_service_worker.js** is to the 
### https://organization.github.io/
and not
### https://organization.github.io/repo/
It seems with changing the **base href** of **index.html** it won't alert that all the files are after the "/repo/"

I'm trying to use this command 
## flutter build web --base-href=/repo/

but it not working actually. I test it in git bash and cmd and in both of them it doesn't work.
also i test this command with :

```
flutter build web --base-href /repo/
flutter build web --base-href="/repo/"
flutter build web --base-href "/repo/"
```
in all above example, the error was:
```
base-href should start and end with /
```
and as you can see in all above example it will,and i think the error is not related. or i'm doing wrong 😃 .

### i'll be appreciated if you type your hint that how can i deploy flutter project on a "organization.github.io/repo" page

**Comment by maheshmnj** [comment]
Hi @CenaAshoori, Thanks for filing the issue. Please ensure that when you run `flutter build web --base-href /repo/`, the    `build/web/index/html` contains `<base href="/repo/">`
 I tried deploying a web app to netlify with `basehref =/screen1/` and it seems to work fine here's a deployed app to verify. https://flutterroutes.netlify.app/

Can you please share your `flutter doctor -v`?

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.8.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (5 days ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 96.0.4664.110

• No issues found!
```
</details>

**Comment by CenaAshoori** [comment]
thanks for ur response.
**cmdline-tools** is the problem ?!
flutter doctor -v 

> [flutter] flutter doctor -v
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.18363.592], locale en-US)
    • Flutter version 2.8.1 at C:\flutter_2.8.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (5 days ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Cena\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.31005.135
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.63.2)
    • VS Code at C:\Users\Cena\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.29.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.18363.592]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 96.0.4664.45
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 96.0.1054.62

! Doctor found issues in 1 category.
exit code 0

**Comment by maheshmnj** [comment]
> thanks for ur response.
cmdline-tools is the problem ?!

It's working fine for me, Can you please confirm if this is working?

> Please ensure that when you run flutter build web --base-href /repo/, the build/web/index/html contains \<base href="/repo/">

**Comment by CenaAshoori** [comment]
This command :

**flutter build web --base-href /repo/**

won't run on my side. I write the error in first comment.

**Comment by maheshmnj** [comment]
>flutter build web --base-href /repo/
> won't run on my side. I write the error in first comment.

> base-href should start and end with /

This is strange this does work fine for me on `stable 2.8.1` on both windows and mac. From the error it looks like your cli tool is ignoring the `/` please try to run this on command prompt or bash terminal. 

```
mahesh@Maheshs-MacBook-Air-M1 counter_app % flutter build web --base-href /repo/
Running "flutter pub get" in counter_app...                      2,143ms

💪 Building with sound null safety 💪

Compiling lib/main.dart for the Web...                             20.5s
mahesh@Maheshs-MacBook-Air-M1 counter_app % 
```

Alternatively. You can manually try editing the `web/index.html` and set the base-href and then try to deploy the app.

**Comment by CenaAshoori** [comment]
I try with PowerShell and cmd this
and the error was:
`Couldn't find the placeholder for base href. Please add `<base href="$FLUTTER_BASE_HREF">` to web/index.html`


## I try put it manually:
From [THIS ADDRESS](https://github.com/Leitner-box/app/blob/master/index.html) you can see the code
and from [THIS ADDRESS](https://leitner-box.github.io/app/) you can load its github.io page.
the repo is : _github.com/Leitner-box/**app**_
the base href is : _<base href=**"/app/"**>_
Please open the developer mode and go to the Network tab and then tap on github.io page link. You'll see that some of the elements won't load and each time you'll refresh the page, **main.dart.js** download from the repository again (it should be cached in normal cases)

**Comment by maheshmnj** [comment]
@CenaAshoori thanks for the info. Is it possible for you to share the minimal and complete repository? Also when you run the app locally does the app start at `localhost:port/repo`?

>  and each time you'll refresh the page, main.dart.js download from the repository again (it should be cached in normal cases)

Probably that's a different issue, Please let's not mix two different issues, Feel free to file that as a separate issue.

**Comment by CenaAshoori** [comment]
Probably but i think the error's root is about this problem and project won't understand that all the files are after repo.
and this is into the console in network tab.
Uncaught (in promise) TypeError: Failed to execute 'addAll' on 'Cache': Request faile                      flutter_service_worker.js?v=953275899:1 



Which part of project ?do you need whole of it?
Also i run a local server and load the builded file and load index.html 
but again it won't understand the correct url and get the 404 error,

**Comment by CenaAshoori** [comment]
can i see your **flutter_service_worker.js** for [your project](https://flutterroutes.netlify.app/)
I think when I manually change the base href i should change the base url on **flutter_service_worker.js** also.

**Comment by maheshmnj** [comment]
> Can i see your flutter_service_worker.js for your project

sure here its is https://github.com/maheshmnj/triage_issues/blob/master/build/web/flutter_service_worker.js

> I think when I manually change the base href i should change the base url on flutter_service_worker.js and maybe other sections also.

I don't think so

**Comment by CenaAshoori** [comment]
Is it possible to build it again with:

###  flutter build web --base-href /repo/

Because i want to see the changes of build/web files after run this  command not default build. I want change the files manually.

**Comment by maheshmnj** [comment]
I did redeploy with `/repo/`  but the app doesn't load now is this the same issue?

**Comment by CenaAshoori** [comment]
Probably yes, but you are doing on your own server.
When you do it on own server it means that all files are after the **repo** folder

Assume base href in index.html be "/repo/"

ex:public_html/index.html
      public_html/repo/main.dart.js
      public_html/repo/flutter_service_worker.j
          .
          .
         


For organization.github.io/repo
I don't know how treat with it.



I think if you now create **organization** and then create **repo** and redeploy this project on
**organization**.github.io/**repo**

You'll see the issue.
I'll be appreciated if you do it.

**Comment by maheshmnj** [comment]
@CenaAshoori I built the sample  flutter app using  `flutter build web --base-href /repo/` and added all the files to https://github.com/maheshmnj/maheshmnj.github.io/tree/master/repo and the app is available now at https://maheshmnj.github.io/repo/

Feel free to check the files and leave your findings I will take a look at them once I am back. Will be on a holiday until Monday.

**Comment by CenaAshoori** [comment]
Thanks for your response again.
For the **username**.github.io/**repo** as i said there is no problem and will work.

But for the **organization**.github.io/**repo** won't be load.

I'll clone your repo maybe on my test organisation will work.

**Comment by CenaAshoori** [comment]
I try. and again it won't load.
you can check it out [HERE](https://github.com/Leitner-box/repo)

**Comment by maheshmnj** [comment]
> For the username.github.io/repo as i said there is no problem and will work.
But for the organization.github.io/repo won't be load.

Thanks for the info probably that's an issue with Github in that case. Not sure if flutter can do anything on this.
Leaving this issue open for further investigation from the team.

App deployed to GitHub pages with individual account works but doesn't load with organization account 
sample deployed app: https://leitner-box.github.io/app/

<img src="https://user-images.githubusercontent.com/31410839/147438474-5e5c369f-e258-470c-88fe-dc01c056bee5.png" height ="300">

cc @mdebbar

**Comment by mdebbar** [comment]
> I try with PowerShell and cmd this and the error was:
> 
> ```
> Couldn't find the placeholder for base href. Please add `<base href="$FLUTTER_BASE_HREF">` to web/index.html
> ```

@CenaAshoori this error message explains what you need to do to get it working. You need to add `<base href="$FLUTTER_BASE_HREF">` in your `web/index.html`. The source file that you linked to has `<base href="/">` which isn't going to work with the `--base-href` command line argument.



> App deployed to GitHub pages with individual account works but doesn't load with organization account
> sample deployed app: https://leitner-box.github.io/app/

@maheshmnj your `index.html` file has `<base href="/">` yet you are trying to load the website at `https://leitner-box.github.io/app/`. You need to set `<base href="/app/">` in your `index.html` in order for this to work.

**Comment by CenaAshoori** [comment]
You right, after adding `<base href="$FLUTTER_BASE_HREF"> in my web/index.html`  this command will work in cmd and powershell :
`flutter build web --base-href /repo/`.
GIt bash won't work :).

But still there is a problem and that is the site won't be cached.

**Comment by mdebbar** [comment]
@CenaAshoori is it similar to this issue: https://github.com/flutter/flutter/issues/68449 ?

**Comment by CenaAshoori** [comment]
Yes, Thank you guys 
After running `flutter build web --base-href /repo/`,
In `flutter_service_worker.js` I should change `CORE` list ( remove "/" from list )
**From:**
```js
const CORE = [
  "/",
"main.dart.js",
"index.html",
"assets/NOTICES",
"assets/AssetManifest.json",
"assets/FontManifest.json"];

```
**TO:** 
```js
const CORE = [
  //"/",
"main.dart.js",
"index.html",
"assets/NOTICES",
"assets/AssetManifest.json",
"assets/FontManifest.json"];

```
