### ISSUE TITLE
[in_app_purchase] google play strore not available  without restarting app after logging to google play

### ISSUE THREAD

**Issue by skaletaPL** [flutter/flutter#95513]
## Steps to Reproduce
1. On the device no google account is logged in
2. Run the app - in app purchase instance states it cannot access google play - InAppPurchase.instance.isAvailable = false
3. Log in to googgle account on the device
4. Go back to the app again (app was not shut down, was waiting in the background)
5. in_app_purchase still states isAvailable = false

How can I renew connection of InAppPurchase.instance to google play without restarting the app, creating instance from scratch?

in_app_purchase: ^1.0.6

[√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.19043.1415], locale pl-PL)
    • Flutter version 2.0.6 at C:\IT\Narzedzia\flutter
    • Framework revision 1d9032c7e1 (8 months ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

• Android SDK at C:\Users\skale\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 9 (API 28)
      (emulator)

• No issues found!

**Comment by darshankawar** [comment]
@skaletaPL 
You seem to be on older version of the plugin and framework. Please upgrade both (plugin to 2.0.1, framework to 2.8.1)to latest and try again to see if it helps.
