### ISSUE TITLE
running 'flutter doctor' flashes up red writing and window closes. 

### ISSUE THREAD

**Issue by sahujaunpuri** [flutter/flutter#95510]
running 'flutter doctor' flashes up red writing and window closes.

**Comment by bernaferrari** [comment]
Do you have a screen recording?

**Comment by mamuseferha** [comment]
Hi @sahujaunpuri 
Can you please run (making sure you run from your terminal and not from an IDE)

```
cd <your app folder>
flutter doctor -v
```

and provide the output.

Also, see links below if the solution works for you

https://stackoverflow.com/questions/64131473/flutter-running-command-flutter-instantly-closes-terminal
https://github.com/flutter/flutter/issues/72215

Thank you
