### ISSUE TITLE
Out of nowhere today I got error 'Unable to find a destination matching the provided destination specifier'

### ISSUE THREAD

**Issue by fuhrthom** [flutter/flutter#95512]
## Steps to Reproduce

1. I did connect my iPhone XS with iOS 15.1 
2. Opened VS Code and did run 'flutter run'

Running via Xcode works fine, no Errors. Cannot understand where is the problem. Rebooted system multiple times, rebooted vs code, tried it with IntelliJ, only Xcode is working, VS Code and IntelliJ are giving the same error. Please help me.

## Logs

<details>
<summary>Logs</summary>

thomas@MBPvonTomas2021 flutter_applications % flutter run --device-id 'XS von Thomas'
Launching lib/main.dart on XS von Thomas in debug mode...
Found saved certificate choice "Apple Development: Thomas Fuhr (XXX)". To clear, use "flutter config".
Signing iOS app for device deployment using developer identity: "Apple Development: Thomas XXX (XXX)"
Running pod install...                                              5,1s
Running Xcode build...                                                  
Xcode build done.                                           31,4s
Failed to build iOS app
Error output from Xcode build:
↳
    objc[60290]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x1f30f2b90) and
    /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1041c82c8). One of the two will be used. Which one is undefined.
    objc[60290]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x1f30f2be0) and
    /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1041c8318). One of the two will be used. Which one is undefined.
    xcodebuild: error: Unable to find a destination matching the provided destination specifier:
                { id:00008020-001025E6269A002E }

        The requested device could not be found because no available devices matched the request.

        Available destinations for the "Runner" scheme:
                { platform:macOS, arch:arm64, variant:Designed for [iPad,iPhone], id:00006001-001C18A80204801E }
                { platform:iOS Simulator, id:0CC36DDA-043F-4B25-AC99-44D60CE5A20A, OS:15.2, name:iPad (9th generation) }
                { platform:iOS Simulator, id:17C304E0-09FA-4989-B236-943F80A7EA13, OS:15.2, name:iPad Air (4th generation) }
                { platform:iOS Simulator, id:3B6FA7FD-A1D6-40D9-A10D-3EBF0AA5EC35, OS:15.2, name:iPad Pro (9.7-inch) }
                { platform:iOS Simulator, id:D243AB27-9E64-4BCB-A7F3-8369320CB56D, OS:15.2, name:iPad Pro (11-inch) (3rd generation) }
                { platform:iOS Simulator, id:16B2AC5C-F4E6-4E1B-AA89-3F52D0F4C4D4, OS:15.2, name:iPad Pro (12.9-inch) (5th generation) }
                { platform:iOS Simulator, id:3DB3D87B-1DE2-4958-B21B-1A625FC589A0, OS:15.2, name:iPad mini (6th generation) }
                { platform:iOS Simulator, id:1028C962-25E9-46CF-949A-EB3D6EF79722, OS:15.2, name:iPhone 8 }
                { platform:iOS Simulator, id:069624D5-09CA-4985-A2B8-6BF10D3AB7B1, OS:15.2, name:iPhone 8 Plus }
                { platform:iOS Simulator, id:AE4E108B-B5FE-4A34-B63E-48EA7D027EA0, OS:15.2, name:iPhone 11 }
                { platform:iOS Simulator, id:B12CDE70-B587-4DD5-AECE-C9464B578C3B, OS:15.2, name:iPhone 11 Pro }
                { platform:iOS Simulator, id:540555E5-C7AF-49C8-8776-5C0E98363806, OS:15.2, name:iPhone 11 Pro Max }
                { platform:iOS Simulator, id:D4B08200-025F-44A0-840A-43205169258E, OS:15.2, name:iPhone 12 }
                { platform:iOS Simulator, id:27062E40-843A-402E-95E3-6611B44CCCAC, OS:15.2, name:iPhone 12 Pro }
                { platform:iOS Simulator, id:0E8FAF33-5626-4E61-9A04-EC2CAF225667, OS:15.2, name:iPhone 12 Pro Max }
                { platform:iOS Simulator, id:09D5386C-D2D1-40DC-B69F-1AA24DC71400, OS:15.2, name:iPhone 12 mini }
                { platform:iOS Simulator, id:0EDB3E97-2DAC-413E-8225-26171E1F587D, OS:15.2, name:iPhone 13 }
                { platform:iOS Simulator, id:6BDDB574-7581-4679-8A69-BE62A35129B9, OS:15.2, name:iPhone 13 Pro }
                { platform:iOS Simulator, id:6BE3DD50-691A-4E1C-841D-2BDE9CE10BBA, OS:15.2, name:iPhone 13 Pro Max }
                { platform:iOS Simulator, id:D9EE7952-07E3-41DB-88A7-C72639A8DBFA, OS:15.2, name:iPhone 13 mini }
                { platform:iOS Simulator, id:BE5779BA-E61E-4140-B11A-F6F265662D90, OS:15.2, name:iPhone SE (2nd generation) }
                { platform:iOS Simulator, id:9F4FC537-41DC-4748-9E28-459E7FEDDBEF, OS:15.2, name:iPod touch (7th generation) }

        Ineligible destinations for the "Runner" scheme:
                { platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
                { platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
                { platform:iOS, id:00008020-001025E6269A002E, name:XS von Thomas, error:Device is busy (Preparing the watch for development via XS von Thomas) }

Could not build the precompiled application for the device.
════════════════════════════════════════════════════════════════════════════════
Building a deployable iOS app requires a selected Development Team with a 
Provisioning Profile. Please ensure that a Development Team is selected by:
  1- Open the Flutter project's Xcode target with
       open ios/Runner.xcworkspace
  2- Select the 'Runner' project in the navigator then the 'Runner' target
     in the project settings
  3- Make sure a 'Development Team' is selected under Signing & Capabilities > Team. 
     You may need to:
         - Log in with your Apple ID in Xcode first
         - Ensure you have a valid unique Bundle ID
         - Register your device with your Apple Developer Account
         - Let Xcode automatically provision a profile for your app
  4- Build or run your project again

For more information, please visit:
  https://flutter.dev/docs/get-started/install/macos#deploy-to-ios-devices

Or run on an iOS simulator without code signing
════════════════════════════════════════════════════════════════════════════════

Error launching application on XS von Thomas.

```
```

[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale
    de-DE)
    • Flutter version 2.8.1 at /Users/thomas/FlutterDev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (2 days ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 63.0.3
    • Dart plugin version 212.5632

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.2)
    • IntelliJ at /Volumes/Storage/IntelliJ/IntelliJ IDEA.app
    • Flutter plugin version 63.0.3
    • Dart plugin version 212.5632

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] VS Code
    • VS Code at /Volumes/Storage/VSCode/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • XS von Thomas (mobile) • 00008020-001025E6269A002E • ios            • iOS 15.1 19B74
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 96.0.4664.110
    ! Error: XS von Thomas is busy: Fetching debug symbols for XS von Thomas. Xcode will continue when XS von Thomas is finished. (code -10)

</details>

**Comment by fuhrthom** [comment]
Seems that it has been an certificate issue, removed it from key chain access and let xcode generate a new one. now its working again

**Comment by alexrainman** [comment]
I have the same error after running flutter upgrade. Cannot run my app on the device anymore.
