### ISSUE TITLE
Warning: Mapping new ns

### ISSUE THREAD

**Issue by regenin** [flutter/flutter#95514]
**When i run emulator i get this error. I've been struggling for an hour and couldn't figure it out. It started after the new update came.
Will it be fixed with the new update or is there a way to fix it? Also would ignoring this error and making an app cause problems?**

And last one this part is changed. I used to be able to adjust the versions, now it gives an error when it changes. I mean min and target SDK versions.

defaultConfig {
minSdkVersion flutter.minSdkVersion
targetSdkVersion flutter.targetSdkVersion
versionCode flutterVersionCode.toInteger()
versionName flutterVersionName
}

Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01

**Comment by regenin** [comment]
And last one this part is changed. I used to be able to adjust the versions, now it gives an error when it changes 

defaultConfig {
        minSdkVersion flutter.minSdkVersion
        targetSdkVersion flutter.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

**Comment by YadavGulshan** [comment]
I'm facing a similar issue, from the day I enabled Facebook authentication in my project. 
Maybe during the setup, I messed some configuration, 
I have gone through my configurations but I was unable to find any fix.
[Verbose Output](https://github.com/flutter/flutter/files/7740861/error.txt)

In this error output, I saw that I have somehow enabled the R8 configuration. I searched through all my configurations but I'm unable to find any viable config.
```
[+1717 ms] > Configure project :firebase_auth
[        ] WARNING: The option setting 'android.enableR8=true' is deprecated.
[        ] It will be removed in version 5.0 of the Android Gradle plugin.
[        ] You will no longer be able to disable R8
[ +393 ms] Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns
http://schemas.android.com/repository/android/common/01
[   +3 ms] Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns
http://schemas.android.com/repository/android/generic/01
[        ] Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns
http://schemas.android.com/sdk/android/repo/addon2/01
[        ] Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns
http://schemas.android.com/sdk/android/repo/repository2/01
[        ] Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns
http://schemas.android.com/sdk/android/repo/sys-img2/01
```

**Comment by YofarDev** [comment]
I had this error too and updating the Android Gradle Plugin version from 4.1.0 to 7.0.2 fixed it.

**Comment by mamuseferha** [comment]
Hi @regenin these are warnings not errors and are caused due to old gradle plugin version. Please see https://stackoverflow.com/a/68959921

You can set/change your minimum sdk in local.properties file or manually, see also https://stackoverflow.com/a/70316521

Please let me know if this works for you

**Comment by regenin** [comment]
> Hi @regenin these are warnings not errors and are caused due to old gradle plugin version. Please see https://stackoverflow.com/a/68959921
> 
> You can set/change your minimum sdk in local.properties file or manually, see also https://stackoverflow.com/a/70316521
> 
> Please let me know if this works for you

Gradle error gone it's working but min sdk isn't working.

```
flutter.buildMode=debug
flutter.versionName=1.0.0
flutter.versionCode=1
```

min sdk setting not showing

**Comment by MyDinnerIsReady** [comment]
I fixed this problem with install a new thing:
![image](https://user-images.githubusercontent.com/36349581/146866824-3fe12c2b-b57e-402e-93a4-8a880bce5d7e.png)
because one of my plugin with the config:
![image](https://user-images.githubusercontent.com/36349581/146866925-7a823339-89c7-4bba-831d-93d5274ede9e.png)

**Comment by regenin** [comment]
> 

The method you showed didn't work for me because of:

```
android {
    compileSdkVersion flutter.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```

This is how it looks when i first build the project and i choose sdk:

![1](https://user-images.githubusercontent.com/34914546/146985264-9aed8c06-4401-4589-ad43-2e874413e289.png)

I was using Sdk 30 before, when it gave an error, I downloaded 31:

![2](https://user-images.githubusercontent.com/34914546/146985367-aa640097-e052-491f-bf50-4735152d7be8.png)

I also downloaded 31 and 30 build tools, but when I started the application, it automatically downloaded 29.

![3](https://user-images.githubusercontent.com/34914546/146985557-6a2dd486-7b1e-4a19-8a5d-3e66a3a528b8.png)

I have no idea if there is a setting for this.

**Comment by anilpujara7** [comment]
> How to solve this this probleam in Flutter 

Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01

**Comment by Nan-Dev-Pro** [comment]
> I had this error too and updating the Android Gradle Plugin version from 4.1.0 to 7.0.2 fixed it.

Thanks a lot. Worked out for me
