### ISSUE TITLE
Error: The non-abstract class 'InternalSelectableMathState'   is missing implementations for these members:

### ISSUE THREAD

**Issue by muradkhan995** [flutter/flutter#95529]
For solutions, see https://dart.dev/go/unsound-null-safety
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_math_fork-0.3.3+1/lib/src/widgets/selectable.dart:407:7: Error: The non-abstract class 'InternalSelectableMathState'  
is missing implementations for these members:
 - TextSelectionDelegate.copySelection
 - TextSelectionDelegate.cutSelection
 - TextSelectionDelegate.pasteText
 - TextSelectionDelegate.selectAll
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class InternalSelectableMathState extends State<InternalSelectableMath>
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/services/text_input.dart:985:8: Context: 'TextSelectionDelegate.copySelection' is defined here.
  void copySelection(SelectionChangedCause cause);
       ^^^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/services/text_input.dart:965:8: Context: 'TextSelectionDelegate.cutSelection' is defined here.
  void cutSelection(SelectionChangedCause cause);
       ^^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/services/text_input.dart:973:16: Context: 'TextSelectionDelegate.pasteText' is defined here.
  Future<void> pasteText(SelectionChangedCause cause);
               ^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/services/text_input.dart:979:8: Context: 'TextSelectionDelegate.selectAll' is defined here.
  void selectAll(SelectionChangedCause cause);
       ^^^^^^^^^
Unhandled exception:
Bad state: Unsupported Null Safety mode NonNullableByDefaultCompiledMode.Invalid, in null.
#0      ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:472:9)
#1      JavaScriptBundler.compile (package:frontend_server/src/javascript_bundle.dart:152:33)
#2      FrontendCompiler.writeJavascriptBundle (package:frontend_server/frontend_server.dart:650:47)
<asynchronous suspension>
#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:558:9)
<asynchronous suspension>
#4      listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1135:11)
<asynchronous suspension>
the Dart compiler exited unexpectedly.

**Comment by stuartmorgan** [comment]
> /C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/**flutter_math_fork**-0.3.3+1/lib/src/widgets/selectable.dart:407:7: Error:

Errors in third-party packages need to be reported to the authors of those packages.

**Comment by alasheev** [comment]
got same error on flutter 2.8.1
on the other pc with flutter 2.5.3 - everything is fine

**Comment by stuartmorgan** [comment]
@alasheev I'm not sure why you downvoted my response. If you go look at the closed issues in that package you'll see that they in fact fixed this issue in the package months ago (when someone, correctly, reported the issue to them).

**Comment by markking79** [comment]
After reading @alasheev comment, I downgraded my Flutter version to 2.5.3 and things appear to be working again for me. https://docs.flutter.dev/development/tools/sdk/releases

**Comment by muazammursyid98** [comment]
try u update package provider to the latest version

**Comment by alasheev** [comment]
@stuartmorgan the thing is that downgrading to 2.5.3 fixed this bug. I would like to upgrade flutter to the newest version but i'm not allowed to(

**Comment by stuartmorgan** [comment]
> @stuartmorgan the thing is that downgrading to 2.5.3 fixed this bug.

Flutter has a clearly described breaking change policy. When breaking changes happen, affected code—in this case, code in third-party packages—has to be updated to account for the breaking changes.

> I would like to upgrade flutter to the newest version but i'm not allowed to

If you choose not to updated affected packages that you rely on to versions of those packages that have been updated for the breaking changes, then you won't be able update Flutter either. That's fundamental to the concept of breaking changes in Flutter.
