### ISSUE TITLE
Submitting the TextField leaves a blank area on Safari

### ISSUE THREAD

**Issue by shadyaziza** [flutter/flutter#95520]
Steps to reproduce:

1.  Focus the `TextField`
2. Start typing
3. Submit the `TextField`

Visual represntation for the issue:

https://user-images.githubusercontent.com/12971971/146666905-e62c1686-25cc-49ca-93db-8c5d7df00755.mp4

Minimal reproducible sample:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: FirstPage(),
    );
  }
}

class FirstPage extends StatefulWidget {
  const FirstPage({Key? key}) : super(key: key);

  @override
  State<FirstPage> createState() => _FirstPageState();
}

class _FirstPageState extends State<FirstPage> {
  late TextEditingController _controller;
  @override
  void initState() {
    _controller = TextEditingController();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [
          TextField(
            controller: _controller,
            onSubmitted: (_) {
              FocusScope.of(context).unfocus();
            },
          ),
          ElevatedButton(
              onPressed: () {
                Navigator.of(context).push(
                    MaterialPageRoute(builder: (_) => const SecondPage()));
              },
              child: const Text('go to second page')),
        ],
      ),
    );
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }
}

class SecondPage extends StatelessWidget {
  const SecondPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Center(
        child: Text('Second Page'),
      ),
    );
  }
}
```

More information on the issue:

- Reproduced on both versions of flutter: `stable 2.8.1` and on latest `master 2.9.0-1.0.pre.129` with both `debug` or `release` versions.
- Reproduced using either `canvaskit` or `html` renderers.
- Seems to be exclusive to Safari web browser on devices running iOS 15.
- Changing Safari tabs' settings from `Tab Bar` to `Single Tab` (i.e: reverting back the address bar to the top where it used to be) seems to solve the issue, but obviously we can not force users to choose one behavior over the other.
- We can notice another issue when I try to dismiss the keyboard it re pops everytime as if the `TextField` regains focus for some reason. I am not sure if the two issues are related, however, I consider the blank area at the bottom is my main focus since its sabotaging the entire user experience.

**Comment by danagbemava-nc** [comment]
HI @shadyaziza, there's already a similar issue describing what you're experiencing in https://github.com/flutter/flutter/issues/95010. Kindly follow up there for more information. 

Closing from here as duplicate. 

Thank you
