### ISSUE TITLE
i got warnings with Non-SDK API Usage Violation and not work release version on Samsung s21

### ISSUE THREAD

**Issue by isuruwe** [flutter/flutter#95527]
Non-SDK API Usage Violation Learn more
Your app uses 4 non-SDK interfaces, which are incompatible with Android P+.
Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray;
Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J
Landroid/util/LongArray;->get(I)J
Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J

[√] Flutter (Channel stable, 2.8.0, on Microsoft Windows [Version 10.0.19043.1348], locale
    en-US)
    • Flutter version 2.8.0 at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (11 days ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at D:\Androidsdk\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: D:\androidstudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at D:\androidstudio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Connected device (3 available)
    • M2101K6G (mobile) • 4654ab8a • android-arm64  • Android 11 (API 30)
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 96.0.4664.110
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 96.0.1054.43

• No issues found!
![image](https://user-images.githubusercontent.com/49168619/146682791-9f949555-57d0-4d71-8fb5-9eef2d0673f7.png)

**Comment by darshankawar** [comment]
@isuruwe 
Check [this](https://github.com/flutter/flutter/issues/36915#issuecomment-525668810) issue comment for detailed explaination for such warnings. Also [this](https://github.com/flutter/flutter/issues/36915#issuecomment-642369537) comment as why this isn't a flutter-specific issue.
Closing based on linked comments.
