### ISSUE TITLE
[Android]: AutofillHints are not showing up (ex: for [AutofillHints.email])

### ISSUE THREAD

**Issue by Kurczaak** [flutter/flutter#95522]
**Expected results:** TextFields show `autofillHint`
**Actual results:** No hints are shown

I'm running my app on a physical android device with Google configured as the auto-fill service but no hints are shown. The issue also remains when running the app on Google Chrome. Tried adding TextEditingControllers, validators, and working with TextFormFields
## Steps to Reproduce

``` dart
@override
  Widget build(BuildContext context) => Scaffold(
      appBar: AppBar(
        title: Text("Login"),
      ),
      body: AutofillGroup(
          child: Column(
        children: [
          TextField(
            autofillHints: [AutofillHints.email],
            keyboardType: TextInputType.emailAddress,
          ),
          TextField(
            autofillHints: [AutofillHints.password],
            keyboardType: TextInputType.text,
          ),
        ],
      )));
```

<details>
  <summary>Logs</summary>

[√] Flutter (Channel dev, 2.9.0-0.1.pre, on Microsoft Windows [Version 10.0.19041.1415], locale en-GB)
    • Flutter version 2.9.0-0.1.pre at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8f1f9c10f0 (5 days ago), 2021-12-14 13:41:48 -0800
    • Engine revision 234aca678a
    • Dart version 2.16.0 (build 2.16.0-80.1.beta)
    • DevTools version 2.9.1

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\kurcz\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • M2004J19C (mobile) • bac6e8410412 • android-arm64  • Android 10 (API 29)
    • Chrome (web)       • chrome       • web-javascript • Google Chrome 96.0.4664.110
    • Edge (web)         • edge   
</details>

EDIT 1:
I decided to open up a Widget Inspector and Details Tree of the widget shows that the autofillHints are not passed to the EditableText.
![image_2021-12-19_115717](https://user-images.githubusercontent.com/34412865/146672490-2fc89af2-1799-415d-acea-9837de1ab8b3.png)

EDIT 2:
I opened the text_field.dart file and the EditableText widget is missing widget.autofillHints value to be passed. Created a new pull request to solve this issue. This is my first PR so If I did something wrong, any suggestions would be more than welcome

**Comment by darshankawar** [comment]
@Kurczaak 
Check [this](https://github.com/flutter/flutter/issues/57320) similar issue and underlying comments and see if it helps.

**Comment by ThalapathySiva** [comment]
@darshankawar Hi I have gone through the comments too, but none of them is working but in the previous flutter version it was worked fine

**Comment by Vafin84** [comment]
Autofill of text fields also stopped working for me

**Comment by Lafannn** [comment]
@darshankawar I have same problem and fix of @Kurczaak is correct. I added comment to his PR for little improve but generally already fine and we need to push the PR to master branch ASAP. it is really annoying bug.

**Comment by darshankawar** [comment]
Ok, I revisited this issue and can confirm that the autofill hints are not showing up on latest stable and master versions.
What I mean is, the email address autofill hint for `autofillHints: [AutofillHints.email],` is not showing up on stable 2.8.0, 2.8.1 and on latest master version, but the same is showing up on stable 2.5.3, as below:

`autofillHints: [AutofillHints.email],` shows up in stable 2.5.3:

<img width="332" alt="Screenshot 2021-12-30 at 5 40 29 PM" src="https://user-images.githubusercontent.com/67046386/147750828-c3f96760-8322-4ce4-b1b5-e1f0bace158e.png">


But with same code, the email autofill hint is not showing up:

<img width="372" alt="Screenshot 2021-12-30 at 5 40 37 PM" src="https://user-images.githubusercontent.com/67046386/147750855-731805ac-7612-4bf4-8498-04df2f8d4a31.png">

I have auto-fill for Google service setup on Android Samsung A2Core device (OS 8).

Labeling this as a regression.


<details>
<summary> flutter doctor -v where issue occurs </summary>

```

[√] Flutter (Channel stable, 2.8.0, on Microsoft Windows [Version 10.0.19042.1415], locale en-US)
    • Flutter version 2.8.0 at D:\FlutterSDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (3 weeks ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Win\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31624.102
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.62.3)
    • VS Code at C:\Users\Win\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.28.0

[√] Connected device (4 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm    • Android 8.1.0 (API 27)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.19042.1415]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 96.0.4664.110
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 96.0.1054.62

• No issues found!


[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19042.1415], locale en-US)
    • Flutter version 2.8.1 at D:\FlutterSDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (13 days ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Win\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31624.102
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.62.3)
    • VS Code at C:\Users\Win\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.28.0

[√] Connected device (4 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm    • Android 8.1.0 (API 27)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.19042.1415]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 96.0.4664.110
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 96.0.1054.62

• No issues found!

[√] Flutter (Channel master, 2.9.0-1.0.pre.209, on Microsoft Windows [Version 10.0.19042.1415], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.2)
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.62.3)
[√] Connected device (5 available)
[√] HTTP Host Availability

• No issues found!

```
</details>

<details>
<summary> flutter doctor -v where it works as expected </summary>

```
[√] Flutter (Channel unknown, 2.5.3, on Microsoft Windows [Version 10.0.19042.1415], locale en-US)
    • Flutter version 2.5.3 at D:\FlutterSDK\flutter
    • Upstream repository unknown
    • Framework revision 18116933e7 (3 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Win\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31624.102
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.62.3)
    • VS Code at C:\Users\Win\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.28.0

[√] Connected device (5 available)
    • SM A260G (mobile)       • 5200763ebcfa861f • android-arm     • Android 8.1.0 (API 27)
    • Windows (desktop)       • windows          • windows-x64     • Microsoft Windows [Version 10.0.19042.1415]
    • Windows (UWP) (desktop) • winuwp           • windows-uwp-x64 •
    • Chrome (web)            • chrome           • web-javascript  • Google Chrome 96.0.4664.110
    • Edge (web)              • edge             • web-javascript  • Microsoft Edge 96.0.1054.62

• No issues found!


```
</details>

**Comment by LongCatIsLooong** [comment]
This looks like a duplicate of https://github.com/flutter/flutter/issues/94043

**Comment by zanderso** [comment]
Closing as duplicate.
