### ISSUE TITLE
when onpressed a async function, the app pending.

### ISSUE THREAD

**Issue by heliping** [flutter/flutter#95523]
## Steps to Reproduce

onpressed -----> Future Function ----> use while loop---->the app pending cannot press anywhere---> the loop stop, the app recovery

I want start a mqtt client to send mqtt message for loop. 
but when pressed the function, the while loop pended the app.

**Expected results:** the loop works in an async work, and the app can work rightly.

**Actual results:** the app is pending.

<details>

###UI
 children: [
                  SizedBox(width: 200),
                  MaterialButton(
                    child: Text('发送'),
                    onPressed: () {
                      BtnsendMsg();
                    },

####onpressed function
 mc = new MqttClient(false);

 BtnsendMsg() async {
    mc.MsgSend(clientid, topic, msgname, '3');
    print("back");
  }

####loop function
class MqttClient {
  bool isStop;

  MqttClient(this.isStop);
Future MsgSend(clientid, topic, msgname, interval) async {
    isStop = false;
    var cc = await clientGet(clientid);
    var msg = await msgGet(msgname);
    String host = "1.1.1.1";
    String msgdata = "1111";
    if (cc != null) {
      host = cc.host!;
    }
    if (msg != null) {
      msgdata = msg.msgdata!;
    }
    Future future = Future(() {
      while (isStop == false) {
        SendMsgOnce(host, clientid, topic, msgdata);
        sleep(Duration(seconds: 3));
      }
    });
    sleep(Duration(seconds: 30));
   
    isStop = true;
  }

<details>

**Comment by nt4f04uNd** [comment]
Dart isolate is single threaded, meaning if you block it with a sync loop like this, no other code will execute. Wrapping your code in async on its own does not defer its execution to other thread, so this behavior is expected.

You can see these resources for more information about this topic https://dart.dev/guides/language/language-tour#isolates

**Comment by heliping** [comment]
got it, thanks very much.
