### ISSUE TITLE
[Proposal] Separator constructor for Column and Row

### ISSUE THREAD

**Issue by alexeyinkin** [flutter/flutter#95521]
Currently the most accepted way to separate items in columns and rows is to include a separator manually:
```dart
Column(
  children: [
    Widget1(),
    SizedBox(height: 10),
    Widget2(),
  ],
),
```

If one has many children, this results in a lot of separator duplication. Or one might need some boilerplate like this:
```dart
Column(
  children: <Widget>[
    Widget1(),
    Widget2(),
  ].alternateWith(const SizedBox(height: 10)), // Some custom extension on List.
),
```

There is a comment on StackOverflow with 34 upvotes that suggests Column and Row to have some separation functionality built in:
https://stackoverflow.com/a/52774984/11382675

Possible solutions include:
* A parameter with separation width or height.
* A parameter with separator widget.
* A parameter with separator widget builder.
* `Column.separated` and `Row.separated` constructors to mirror `ListView.separated`.
* A method in `collection`'s `iterable_extensions` like `alternateWith` above which would be just as short.

I personally would prefer a method in `collection` as a more universal solution. But numeric separator size might have less overhead.

**Comment by Priyankg101** [comment]
Can someone please assign this issue to me?

**Comment by maheshmnj** [comment]
Hi @Priyankg101, assigning this issue to you please go through these wiki before you start  https://github.com/flutter/flutter/wiki/Issue-hygiene
https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo

**Comment by Piinks** [comment]
This reminds me of https://github.com/flutter/flutter/issues/16957, and may not be something we want to add to Row or Column since it can be done with a minimal amount of code. 
We try to avoid adding more and more parameters to widgets when a few lines of code will accomplish the same effect.

**Comment by alexeyinkin** [comment]
More duplicates: #18917, #55378 and even #95263 6 days ago.

**Comment by maheshmnj** [comment]
> This reminds me of #16957, and may not be something we want to add to Row or Column since it can be done with a minimal amount of code.
We try to avoid adding more and more parameters to widgets when a few lines of code will accomplish the same effect.

Closing based on the above response.
