### ISSUE TITLE
Routes should not be interactive during `CupertinoPageRoute` transitions

### ISSUE THREAD

**Issue by willlockwood** [flutter/flutter#95535]
## Use case

While working on a fidelity improvement for a separate issue, I noticed that during a page transition on native iOS, users can't interact with pages under transition, but they can in Flutter, which, while likely rare and difficult to notice, can lead to some strange visual behavior.

<details><summary>Native iOS:</summary>

https://user-images.githubusercontent.com/7915388/146695493-81c9c97e-350e-4702-9d56-610acdd45bf7.mov
</details>

<details><summary>Flutter</summary>

https://user-images.githubusercontent.com/7915388/146695451-325436bb-0daf-4ba2-b3a6-95afed383935.mov
</details>

## Proposal

Cupertino routes should intercept touches until transition animations are complete.

Things I still need to check/confirm (will update this issue once I've gathered the information):
- Whether there is a similar discrepancy between native and flutter for material route transitions/on Android, and
- What the ideal behavior is for modal dialogs and popups, and whether the Flutter implementations match their native counterparts

**Comment by danagbemava-nc** [comment]
Hi @willlockwood, looks like there's a similar proposal for this in https://github.com/flutter/flutter/issues/54090. 

Kindly follow up there for more information. 

Closing from here as duplicate. 

Thank you
