### ISSUE TITLE
how to build arm64 Linux desktop app in x86 Linux host?

### ISSUE THREAD

**Issue by Anima18** [flutter/flutter#95539]
how to build arm64 Linux desktop app in x86 Linux host?

**Comment by maheshmnj** [comment]
Hi @Anima18, cross builds (x86-arm or vice versa) is currently not supported, But this feature request is being tracked here https://github.com/flutter/flutter/issues/74929. Please follow up on that issue for further updates.  
Closing this issue as a duplicate.
