### ISSUE TITLE
How can I reduce the height and leave the maximum width for the camera in the camera package: ^ 0.9.4 + 5 (https://pub.dev/packages/camera)? 

### ISSUE THREAD

**Issue by dirtycreep** [flutter/flutter#95549]
How can I reduce the height and leave the maximum width for the camera in the camera package: ^ 0.9.4 + 5 (https://pub.dev/packages/camera) and the camera itself would not distort the photo?

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
MacBook-Pro-Aram:image_package aram$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.0, on macOS 12.0.1 21A559 darwin-arm, locale ru-RU)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc5)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[!] Xcode - develop for iOS and macOS (Xcode 13.2)
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on
        the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] Android Studio (version 2020.3)
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.62.3)
[✓] VS Code (version 1.61.1)
[✓] VS Code (version 1.58.2)
[✓] Connected device (5 available)

**Comment by darshankawar** [comment]
@dirtycreep 
I don't think that's possible since the camera plugin depends on native implementation and there's no way to change the actual height and width. You may ask the same on support channels like StackOverflow for any workarounds.
Closing from here.
