### ISSUE TITLE
[Windows] The script executes the `flutter build` without executing the subsequent commands

### ISSUE THREAD

**Issue by Chuanbin-Wang** [flutter/flutter#95548]
1. Run 'flutter create' to create new project.
2. add build.bat and add code
```
flutter build windows --release
echo "Build done"
mkdir release 
# copy release file.
```
3. run build.bat

Expected results:
the 'Build done' output and the release folder is created.

__Linux is ok__

Actual results:
![image](https://user-images.githubusercontent.com/76732400/146733645-d2a7ceff-dda1-4341-b282-93afe969aab3.png)

flutter version:
![image](https://user-images.githubusercontent.com/76732400/146733770-d2e8b7cb-370e-44d6-8f9a-aa9bd7f1574f.png)

**Comment by darshankawar** [comment]
> 2\. add build.bat and add code

@Chuanbin-Wang Any reason you are trying to add `build.bat` ?
According to [this](https://github.com/flutter/flutter/pull/32335) PR, the need to add `build.bat` was removed in the build workflow and support to build using `msbuild` was added.

**Comment by Chuanbin-Wang** [comment]
This build.bat is only used here as an example.
What I actually need to do is to perform various resource substitutions based on parameters before compiling, compile other sdk components, and after compiling, perform a series of checks and packaging and compression, and publish via some api, and send notifications.
All this is done through various scripts. Currently this script works fine under linux, but not under windows

**Comment by darshankawar** [comment]
> What I actually need to do is to perform various resource substitutions based on parameters before compiling, compile other sdk components, and after compiling, perform a series of checks and packaging and compression, and publish via some api, and send notifications.

Can you give us an example / use case for this.

**Comment by Chuanbin-Wang** [comment]
OK. But the source script file is on the intranet and can't be copied, so I'll roughly write the flutter-related part here

```
# The client folder is flutter project. 

echo "Start build for $1".

mkdir -o release/$1

# Do build other sdk 
./service/script/build_release.sh $1

# build flutter
cd client/assets

# replace the resources
rm -rdf config
rm -rdf icons

cp -r ./customer/$1/* ./
cd ..

flutter clean
flutter build linux --release -t "lib/main.$1.dart"

# copy files
cp -r ./build/linux/x64/release/bundle/* ./release/$1/client
# and other file copy
cp -r ../service/target/release/service/* ./release/$1/service/
......

# call api
......

```

**Comment by darshankawar** [comment]
Keeping it open and labeling for further insights on current and expected behavior.

/cc @stuartmorgan

**Comment by stuartmorgan** [comment]
> Expected results:
> the 'Build done' output and the release folder is created.

That is not what your script does; I recommend reading more about batch scripts, especially the `call` command.

> Linux is ok

Batch isn't just sh on Windows. They are different languages.

Closing as the problem here is that the wrapper script is written incorrectly; this has nothing to do with Flutter.
