### ISSUE TITLE
Failed to take screenshot Unknown method "_flutter.screenshot" is coming as error in Integration Testing in Chrome

### ISSUE THREAD

**Issue by skumarpk** [flutter/flutter#95542]
When I try to take screenshots with Integration Testing then it throwing an error as -
Failed to take screenshot
_flutter.screenshot: (-32601) Unknown method "_flutter.screenshot".

## Steps to Reproduce
Once app is launched in Chrome browser, try to take screenshot with BDD approach(Integration testing)
 then it shows error as -
Failed to take screenshot
_flutter.screenshot: (-32601) Unknown method "_flutter.screenshot".

**Expected results:** Should take screenshot

**Actual results:** showing error in Json/html report

This is code inside app_test.dart page -
    ..hooks = [HookExample(), AttachScreenshotOnFailedStepHook()]

**Comment by maheshmnj** [comment]
Hi @skumarpk, Thanks for filing the issue. Please share the output of `flutter doctor -v`, complete console logs and [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example).

Thank you.

**Comment by skumarpk** [comment]
This issue is only occurring in Chrome, same code working fine with Android device.

Please find attached flutter doctor output:
<img width="573" alt="flutter-doctor" src="https://user-images.githubusercontent.com/74889817/146892079-37c67b90-0dd2-4054-b65f-1ce0f2a7408a.png">

Below is the exception that occurring:

Failed to take screenshot
_flutter.screenshot: (-32601) Unknown method "_flutter.screenshot".
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1626:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2109:21)
#2      VmService.callServiceExtension (package:vm_service/src/vm_service.dart:2072:14)
#3      VmService.callMethod (package:vm_service/src/vm_service.dart:2062:12)
#4      VMServiceFlutterDriver.screenshot (package:flutter_driver/src/driver/vmservice_driver.dart:334:54)

#5      AttachScreenshotOnFailedStepHook.takeScreenshot (package:flutter_gherkin/src/flutter/hooks/attach_screenshot_on_failed_step_hook.dart:28:19)

#6      AttachScreenshotOnFailedStepHook.onAfterStep (package:flutter_gherkin/src/flutter/hooks/attach_screenshot_on_failed_step_hook.dart:18:32)

#7      AggregatedHook._invokeHooks (package:gherkin/src/hooks/aggregated_hook.dart:92:9)

#8      AggregatedHook.onAfterStep (package:gherkin/src/hooks/aggregated_hook.dart:85:7)

#9      FeatureFileRunner._runStep (package:gherkin/src/feature_file_runner.dart:349:5)

#10     FeatureFileRunner._runScenario (package:gherkin/src/feature_file_runner.dart:268:13)

#11     FeatureFileRunner._runScenarioInZone. (package:gherkin/src/feature_file_runner.dart:160:24)

**Comment by maheshmnj** [comment]
Thanks for the info @skumarpk, `flutter_gherkin`  is a third-party plugin issues related to it must be filed with the maintainer. Closing as this is not an issue with flutter.
