### ISSUE TITLE
[IOS] IOS build failure on iphone and works fine on simulator

### ISSUE THREAD

**Issue by lei2015li** [flutter/flutter#95554]
How can I solve this problem？
Thank you very much for your reply.

=================================
In order to adapt to the latest mobile phone, I upgraded the system.

It works normally in the old environment(Xcode 13.0, macOS 11.5 ), but it works abnormally in the new environment(Xcode 13.2, macOS 12.1).

log:

```console 
dyld: Library not loaded: @rpath/App.framework/App
  Referenced from: /private/var/containers/Bundle/Application/8B6E1086-F041-43A2-A01D-4506C5F815EC/D.box.app/D.box
  Reason: image not found
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/usr/lib/libMTLCapture.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
(lldb) 
```
environment：

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale
    zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.
[✓] Xcode - develop for iOS and macOS (Xcode 13.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] Connected device (3 available)

! Doctor found issues in 1 category.
```

```
leixiaoli@leixiaolideiMac ~ % flutter doctor -v
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 2.8.1 at /Users/leixiaoli/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (4 days ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/leixiaoli/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • iPhone-leiTest (mobile) • ce3df637b47d6c49d5e804424f6005d54109503b • ios
      • iOS 14.6 18F72
    • iPhone 11 (mobile)      • 57D3F5AB-812A-4BBB-9BC0-7D3EAFA754A3     • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)            • chrome                                   •
      web-javascript • Google Chrome 96.0.4664.110

! Doctor found issues in 1 category.
```

**Comment by maheshmnj** [comment]
Hi @lei2015li, Thanks for filing the issue. Please share the complete output of `flutter run -v` in a textfile, `pubspec.yaml`, and the podfile.

 Thanks

**Comment by lei2015li** [comment]
Thanks for your reply.

===================
Podfile：


platform :ios, '10.0'

target 'MyOneProject' do

  # flutter
  flutter_application_path = '../flutter_one_module/'
  load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
  # 引入flutter
  install_flutter_engine_pod
  install_all_flutter_pods(flutter_application_path)

end


===================

pubspec.yaml：


name: flutter_one_module
description: A new flutter module project.


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true


  module:
    androidX: true
    androidPackage: com.example.flutter_one_module
    iosBundleIdentifier: com.example.flutterOneModule

===========================
the information of "flutter run -v"

[https://github.com/lei2015li/common/blame/main/the%20information%20of%20%22flutter%20run%20-v%22.rtf](url)

**Comment by lei2015li** [comment]
> Hi @lei2015li, Thanks for filing the issue. Please share the complete output of `flutter run -v` in a textfile, `pubspec.yaml`, and the podfile.
> 
> Thanks

Thanks for your reply.

===================
Podfile：

platform :ios, '10.0'

target 'MyOneProject' do
flutter_application_path = '../flutter_one_module/'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

install_flutter_engine_pod
install_all_flutter_pods(flutter_application_path)
end

===================

pubspec.yaml：

name: flutter_one_module
description: A new flutter module project.

version: 1.0.0+1

environment:
sdk: ">=2.15.1 <3.0.0"

dependencies:
flutter:
sdk: flutter

cupertino_icons: ^1.0.2

dev_dependencies:
flutter_test:
sdk: flutter
flutter_lints: ^1.0.0

flutter:

uses-material-design: true

module:
androidX: true
androidPackage: com.example.flutter_one_module
iosBundleIdentifier: com.example.flutterOneModule

===========================
the information of "flutter run -v"

https://github.com/lei2015li/common/blame/main/the%20information%20of%20%22flutter%20run%20-v%22.rtf

**Comment by maheshmnj** [comment]
Thanks for the info @lei2015li looking at the flutter run logs it looks like the logs are incomplete 

```
[  +60 ms] Multiple devices found:\
[   +8 ms] iPhone-leiTest (mobile) \'95 ce3df637b47d6c49d5e804424f6005d54109503b \'95\
ios \'95 iOS\
           14.6 18F72\
[   +1 ms] iPhone 11 (mobile)      \'95 57D3F5AB-812A-4BBB-9BC0-7D3EAFA754A3     \'95\
ios \'95\
           com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)\
[   +1 ms] [1]: iPhone-leiTest (ce3df637b47d6c49d5e804424f6005d54109503b)\
[        ] [2]: iPhone 11 (57D3F5AB-812A-4BBB-9BC0-7D3EAFA754A3)\
\
}
```
You haven't provided an input to choose a device in order for the tool to start build execution. Please select a physical device and let the build fail and then share those complete logs.

**Comment by shiyongjian10** [comment]
upgrade ruby 2.6.6
