### ISSUE TITLE
[Proposal] Make stepper headers unclickable

### ISSUE THREAD

**Issue by tony123S** [flutter/flutter#95552]
I using Stepper class in my project.  Is there a way to make stepper header unclickable?

**Comment by maheshmnj** [comment]
Hi @tony123S, Thanks for filing the issue. Could you please specify the use case where you wouldn't want the user to tap on the header? In case you don't want user to move to previous step you  can handle it in `onStepTapped` something like this 

```dart
 onStepTapped: (int step) {
    if (step > currentStep) {
       setState(() {
          currentStep = step;
       });
   }
 },
```

**Comment by tony123S** [comment]
Hi @maheshmnj ,

In my app I have a form which consist of 4 steps. User require to fill up all the fields completely before move to next step.

**Comment by maheshmnj** [comment]
Thanks for the info @tony123S. Considering this issue as a valid proposal.

**Comment by tony123S** [comment]
Thanks you.

**Comment by tony123S** [comment]
I use this logic to make it unclickable.

```onStepTapped: (int index) {
        if (currentStep != index) {
          currentStep = currentStep;
        }
      },```

**Comment by maheshmnj** [comment]
I believe the plugin is supposed to handle header clicks by similar logic. Anyways we can wait for further insights from the team.

**Comment by Piinks** [comment]
> ```
> onStepTapped: (int index) {
>         if (currentStep != index) {
>           currentStep = currentStep;
>         }
>       },
> ```

If this works as intended, what is needed here?

**Comment by tony123S** [comment]
I think it can be closed now.
