### ISSUE TITLE
[integration_test] BUG: Taps are not propagated correctly to `AndroidView`s under v2.8

### ISSUE THREAD

**Issue by bjoernahrens** [flutter/flutter#95550]
Hello, with the recent update of 2.8 (and 2.8.1), integration tests that have been running fine under 2.2 and 2.5 are now breaking for me.

I'm working on an app that displays a Mapbox map using the [`mapbox_gl`](https://pub.dev/packages/mapbox_gl) package. This is implemented inside the package using `AndroidView` on Android. [(See here for the actual implementation.)](https://github.com/flutter-mapbox-gl/maps/blob/master/mapbox_gl_platform_interface/lib/src/method_channel_mapbox_gl.dart#L142-L148)
I'm running Integration Tests on an Android 10 phone (or emulator) using the SDK's `integration_test` package in which a tap on a symbol is made and a UI change is verified.

Under Flutter 2.5, everything ran just fine. 
With the upgrade to Flutter 2.8 (and 2.8.1), the tests fail. The tap on the `AndroidView` is not progressed to the underlaying code and thus no UI change is triggered.

_Note: This only applies to integration tests in particular, a release or debug build of the app works just as expected when tested manually._

__This issue is a major blocker in our development pipeline__

## Steps to Reproduce

I created a guide to create a minimal app that uses the `mapbox_gl` package. It openes a map and places two symbols on the map. When tapping a symbol, the title in the app bar changes with a name given to the symbol.
When you create the app using Flutter 2.5, the test will pass. Unter Flutter 2.8, the test will fail.

(Unfortunately, I'm not able to provide an app that uses the `AndroidView` directly. That's why I have to use the `mapbox_gl` package. However, the package depends on two tokens that have to be generated on mapbox.com that I cannot provide.)

- Create an app using `flutter create demo`
- Run `flutter pub add mapbox_gl` 
- Add `integration_test` to the `pubspec.yaml`:
  ```yaml
   dev_dependencies:
    flutter_test:
      sdk: flutter
    integration_test:
      sdk: flutter
  ```

- Generate `SDK_REGISTRY_TOKEN` and `MAPBOX_ACCESS_TOKEN` from mapbox.com. See [mapbox_gl repo](https://github.com/flutter-mapbox-gl/maps) for details.
  Export the `SDK_REGISTRY_TOKEN` in your shell and restart your IDE. The token is needed to download the Mapbox SDK during the build stage. The access token will be used directly in the code.
  
- Set the Android `minSdkVersion` to 29

- Replace the `main.dart` file and add the `map_widget.dart` file with the following code
<details>
<summary>main.dart</summary>

```dart
import 'package:demo/src/map_widget.dart';
import 'package:flutter/material.dart';

void main() async {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      onGenerateRoute: (RouteSettings routeSettings) {
        return MaterialPageRoute<void>(
          builder: (BuildContext context) {
            return const MapWidget();
          },
        );
      },
    );
  }
}

```

</details>

<details>
<summary>lib/src/map_widget.dart</summary>

```dart
import 'package:flutter/material.dart';
import 'package:mapbox_gl/mapbox_gl.dart';

class MapWidget extends StatefulWidget {
  const MapWidget({Key? key}) : super(key: key);

  @override
  _MapWidgetState createState() => _MapWidgetState();
}

class _MapWidgetState extends State<MapWidget> {
  String title = "Initial title";
  late MapboxMapController _controller;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      body: MapboxMap(
        accessToken:
            'pk.XXXXXXXXXXX_PLACE_ACCESS_TOKEN_HERE_XXXXXXXXXXX',  // <-- Place your Access Token here
        initialCameraPosition: const CameraPosition(
          target: LatLng(0, 0),
        ),
        onMapCreated: (controller) {
          _controller = controller;
          _controller.onSymbolTapped.add(_onSymbolTapped);
        },
        onStyleLoadedCallback: onStyleLoaded,
      ),
    );
  }

  void onStyleLoaded() {
    _controller
      ..addSymbol(
        const SymbolOptions(
          geometry: LatLng(0, 0),
          iconImage: 'airport-15',
          iconSize: 10,
        ),
        {'name': 'Large Airport'},
      )
      ..addSymbol(
        const SymbolOptions(
          geometry: LatLng(0, 100),
          iconImage: 'airport-15',
          iconSize: 5,
        ),
        {'name': 'Small Airport'},
      );
  }

  void _onSymbolTapped(Symbol symbol) {
    debugPrint("onSymbolTapped ${symbol.id}");
    setState(() {
      title = symbol.data!['name'];
    });
  }
}

```

</details>

- Add the `app_test.dart` file for the integration tests.

<details>
  <summary>integration_test/app_test.dart</summary>

```dart
import 'package:demo/main.dart' as demo;
import 'package:demo/src/map_widget.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();
  group('Integration test', () {
	  
	// This test passes
    testWidgets(
      "should have initial title",
      (WidgetTester tester) async {
        demo.main();
        await tester.pumpAndSettle();

        expect(find.text('Initial title'), findsOneWidget);
      },
    );

	// This test fails under Flutter 2.8.1, but passes under 2.5.3
    testWidgets(
      "should have 'Large Airport' title after tap on airport icon",
      (WidgetTester tester) async {
        demo.main();
        await tester.pumpAndSettle();

        // We tap the center of the widget because we know that the large airport is there
        final center = tester.getCenter(find.byType(MapWidget)); 
        debugPrint(center.toString());

        await tester.tapAt(center);
        await tester.pumpAndSettle();
        await Future.delayed(const Duration(seconds: 3));
        await tester.pumpAndSettle();
        await Future.delayed(const Duration(seconds: 5));

        expect(find.text('Large Airport'), findsOneWidget);
      },
    );
  });
}

```

</details>

<details>
  <summary>Logs</summary>

### Flutter 2.8.1

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.0.1 21A559 darwin-x64, locale
    en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version
    31.0.0-rc4)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.3)
[✓] VS Code (version 1.63.2)
[✓] VS Code (version 1.64.0-insider)
[✓] Connected device (2 available)

• No issues found!
```

### Flutter 2.5.3

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 2.5.3, on macOS 12.0.1 21A559 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc4)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] Android Studio (version 2020.3)
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.3)
[✓] VS Code (version 1.63.2)
[✓] VS Code (version 1.64.0-insider)
[✓] Connected device (2 available)

• No issues found!
```

`flutter analyze` did not find any issues.
</details>

**Comment by bjoernahrens** [comment]
@darshankawar
I tried to replicate the behavior myself, but wasn't successful, i.e. my implementation using AndroidView with a native Android button passed the integration test. The problem with mapbox_gl persists unfortunately, so there was definitely a breaking change in that regard between 2.5 and 2.8. As far as I know, mapbox_gl uses AndroidView, so I don't know about SurfaceAndroidView.

I will investigate further at a later point, but at least you're aware of this problem in case you/your team get similar reports or find issues like this.

**Comment by darshankawar** [comment]
@bjoernahrens 
Thanks for the update. I looked at the release notes for 2.8 specific to changes related to AndroidView and found out this PR which changed `id` to `viewId` for AndroidViewController` and others: https://github.com/flutter/flutter/pull/90294
But this doesn't seem to have any impact on your case.
Since your scenario works with AndroidView without using the plugin, could it be that there's something in the plugin itself ?
Have you reached out to the plugin owner to about it and see if it could be at their end ?

**Comment by bjoernahrens** [comment]
@darshankawar
Exactly, there's nothing in the release notes, so I assume it's an unintended bug.
I don't think it's the plugin itself. I checked out multiple versions of mapbox-gl that were released over the recent months. Every version worked fine with Flutter 2.2 and 2.5. Likewise, all those versions failed under Flutter 2.8.

**Comment by darshankawar** [comment]
Thanks for the update. If we take an example of `webview_flutter`, the latest version if it has `SurfaceAndroidView()` as default hybrid composition. Maybe the mapbox-gl package may need to incorporate this change ?

**Comment by bjoernahrens** [comment]
@darshankawar
Thanks for the tip. I cloned the mapbox-gl repo and implemented the `AndroidViewSurface` in place of the `AndroidView` myself to try it out.
Unfortunately, it did not change anything regarding the behavior. Taps on the map are still not recognized in integration tests, but work fine in release builds.

**Comment by darshankawar** [comment]
Thanks for the update. Since there doesn't seem to be an easy reproducible code sample to verify this, I am unable to confirm the behavior. (The code sample provided by @bjoernahrens would need to have access tokens generated and used in order to replicate the behavior).

I am labeling it for further input from the team.

/cc @jiahaog  @dnfield

**Comment by carlos-vw** [comment]
Hi, I am a colleague of @bjoernahrens, doing some tests on this topic I have seen that the event map#onMapLongClick is produced but not symbol#onTap when doing tapAt(offset)... does it tell you something @darshankawar? Thanks in advance.

**Comment by bartekpacia** [comment]
This is probably related to #111110
