### ISSUE TITLE
Creating a virtual display of size: [720, 2222222] may result in problems

### ISSUE THREAD

**Issue by mostafasaadamin** [flutter/flutter#95569]
this error appear and cause my app to crash

Creating a virtual display of size: [720, 2222222] may result in problems(https://github.com/flutter/flutter/issues/2897).It is larger than the device screen size: [720, 1440].

**Comment by bernaferrari** [comment]
do you have a sample?

**Comment by darshankawar** [comment]
@mostafasaadamin 
Provide `flutter doctor -v`, a minimal code sample and steps to replicate showing the error you highlighted.
