### ISSUE TITLE
[Windows]Android Emulator does not appear as device target in Android Studio 

### ISSUE THREAD

**Issue by via-lars** [flutter/flutter#95564]
## Steps to Reproduce

1. follow https://docs.flutter.dev/get-started/install/windows for "Windows Setup" 
(a) until https://docs.flutter.dev/get-started/test-drive?tab=androidstudio "Run the app", 
b) then (because Desktop app building doesn't work [related Issue](https://github.com/flutter/flutter/issues/95266))
c) refollow those steps for "Android Setup" to add Android build support and an AVD to Android Studio and open the already existing project
2. ![image](https://user-images.githubusercontent.com/23217105/146777760-d660e2a1-81f4-4c25-b54b-e3b4bbff1d8b.png)
3. ![image](https://user-images.githubusercontent.com/23217105/146777813-a4e067e6-ae52-47c5-a8d9-6f3a9adbdc32.png)

Result: Android Emulator device does not appear as device target in "run" toolbar in Android Studio despite documentation followed

## Logs

<details>
<summary>Logs</summary>

```
```

```
flutter doctor -v
[√] Flutter (Channel stable, 2.8.0, on Microsoft Windows [Version 10.0.19044.1415], locale de-DE)
    • Flutter version 2.8.0 at C:\Users\Hansen\Downloads\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (12 days ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\Hansen\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.0.31919.166
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.63.2)
    • VS Code at C:\Users\Hansen\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1415]
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 96.0.1054.57

! Doctor found issues in 1 category.

```

</details>

**Comment by maheshmnj** [comment]
Hi @via-lars, Thanks for filing the issue. When you launch the virtual device manually from the avd manager does the device launch and show up in the list of devices in android studio?

**Comment by via-lars** [comment]
Hi, yes, it does: 
![image](https://user-images.githubusercontent.com/23217105/146946442-0660d388-1430-4a27-9aba-d1359c9f2ab1.png)

once I manually launched the emulator via the Play-button in the AVD manager (although I got an error about adb not found the emulator launched) and then clicked the Play-Button in the "run" toolbar, the console output is `Running Gradle task 'assembleDebug'...` and after now some minutes the app actually displays inside the emulator.

So thank you!

But after closing the emulator, the drop down entry is gone again.

I guess i can work with having to launch the emulator separately first...

**Comment by maheshmnj** [comment]
thanks for the info. @via-lars, I suspect this issue to be related to android studio or the emulator, in the SDK settings under Android Sdk => Sdk tools

Can you please check if Android Emulator is enabled?

![image](https://user-images.githubusercontent.com/31410839/147043973-c0c27297-1e67-49d0-b489-40bbedefee18.png)

**Comment by via-lars** [comment]
Hello, it is.

**Comment by maheshmnj** [comment]
@via-lars If you run a native android project, Is the emulator shown in the list of devices?

**Comment by via-lars** [comment]
it is: 
![image](https://user-images.githubusercontent.com/23217105/147085774-8eb8d873-e033-4a95-b3fb-81967f808b72.png)

**Comment by maheshmnj** [comment]
Thanks for the info @via-lars, So this looks like a issue with [flutter-intellij](https://github.com/flutter/flutter-intellij) plugin. I would advise you to please file the issue in the dedicated repository. 
Additionally please check if any of the solutions in this issue helps https://github.com/flutter/flutter-intellij/issues/2084

Closing as this isn't really an issue with flutter sdk.
