### ISSUE TITLE
Unable to locate a Java Runtime

### ISSUE THREAD

**Issue by gegobyte** [flutter/flutter#95563]
I have downloaded Flutter on M1 Macbook Pro running macOS Monterey 12.1 by following the [official install instructions](https://docs.flutter.dev/get-started/install/macos). On running `flutter doctor -v`, I am getting unable to locate java runtime error. Running `which java` in terminal returns `/usr/bin/java`

## Steps to Reproduce

1. Installed Flutter by following official instructions for mac
2. Ran `flutter doctor -v`

## Logs

<details>
<summary>Logs</summary>

**flutter doctor -v**
```
The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.
The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale
    en-IN)
    • Flutter version 2.8.1 at /Users/chinmaysarupria/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (4 days ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/chinmaysarupria/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /usr/bin/java
    ✗ Could not determine java version

[✓] Xcode - develop for iOS and macOS (Xcode 13.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[!] Android Studio
    • Android Studio at /Users/chinmaysarupria/Library/Android/sdk/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Android Studio not found at
      /Users/chinmaysarupria/Library/Android/sdk/Contents
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.59.0)
    • VS Code at /Users/chinmaysarupria/Downloads/Visual Studio
      Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.110

! Doctor found issues in 2 categories.
```

</details>

**Comment by GautamSharma05** [comment]
Go to Applications then right click on Android Studio, then choose "Show Package Contents", create a new folder inside jre named jdk and copy the contents of jre to jdk

This is the link for the fix 👇👇👇
https://github.com/flutter/flutter/issues/76215#issuecomment-864407892

And flutter doctor gives 2 issues because you have no proper installation of Android studio try to install Android studio again and instal flutter plugin in Android studio

**Comment by gegobyte** [comment]
> Go to Applications then right click on Android Studio, then choose "Show Package Contents", create a new folder inside jre named jdk and copy the contents of jre to jdk
> 
> This is the link for the fix 👇👇👇 [#76215 (comment)](https://github.com/flutter/flutter/issues/76215#issuecomment-864407892)

Had tried that long ago, didn't work.

> And flutter doctor gives 2 issues because you have no proper installation of Android studio try to install Android studio again and instal flutter plugin in Android studio

Have already reinstalled Android Studio but still getting 2 installations of it in flutter doctor.

**Comment by GautamSharma05** [comment]
In

> flutter

In which directory you are trying to install Android studio?
Can you share the path please?

**Comment by gegobyte** [comment]
> In which directory you are trying to install Android studio?

/Applications/Android Studio.app/Contents

**Comment by GautamSharma05** [comment]
> > In which directory you are trying to install Android studio?
> 
> /Applications/Android Studio.app/Contents

1. And first you have to install flutter and dart plugin 
2. And go in Android studio and try to give proper path to your java jdk
3. And if you not install java jdk in your system first install java jdk in your system

**Comment by gegobyte** [comment]
> 1. And first you have to install flutter and dart plugin

Already installed the day I installed Android Studio



> 2. And go in Android studio and try to give proper path to your java jdk

How to do that? I guess that's already set properly as jdk comes with Android Studio.

> 3\. And if you not install java jdk in your system first install java jdk in your system

I have not installed anything separately, only followed flutter install instructions which does not mention about installing java separately. Had also searched about it and found that I need not install java separately as it comes bundled with Android Studio.

**Comment by GautamSharma05** [comment]
> > 1. And first you have to install flutter and dart plugin
> 
> Already installed the day I installed Android Studio
> 
> > 2. And go in Android studio and try to give proper path to your java jdk
> 
> How to do that? I guess that's already set properly as jdk comes with Android Studio.
> 
> > 3. And if you not install java jdk in your system first install java jdk in your system
> 
> I have not installed anything separately, only followed flutter install instructions which does not mention about installing java. Had also searched about it and found that I need not install java separately as it comes bundled with Android Studio.

But you install java jdk in your system for resolve this error try to install java jdk in your system

**Comment by darshankawar** [comment]
@gegobyte 

Check [this](https://github.com/flutter/flutter/issues/88348#issuecomment-900235328) comment which should resolve your issue. If not, write in comments and I'll reopen it.

Closing this as duplicate.

**Comment by gegobyte** [comment]
@darshankawar I tried changing the channel to beta and master but still getting the same error.

**Comment by darshankawar** [comment]
Please check [this](https://github.com/flutter/flutter/issues/76215) issue and underlying comments and see if they help.

**Comment by gegobyte** [comment]
@darshankawar Have tried all possible solutions on that link but nothing worked.

**Comment by gegobyte** [comment]
@darshankawar So now I finally downloaded java from java.com and the error is resolved.

**Comment by gegobyte** [comment]
> And flutter doctor gives 2 issues because you have no proper installation of Android studio try to install Android studio again and instal flutter plugin in Android studio

I finally got rid of double instances of android studio by running these commands:

```
flutter config --android-studio-dir=""

flutter config --android-sdk=""
```
