### ISSUE TITLE
Using Flutter requires a 1GB per-user download

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#9557]
Cocoapods requires a user-writeable per-user 1GB directory to function (at least currently).

This makes setup of kiosk/multi-user machines for Flutter development difficult.

We could solve this either by
1. making it possible to use a non-writeable cocoapods install
2. (dramatically) reducing the size of the cocoapods dependency

The second option is probably better for all users, but either would unblock us.

**Comment by eseidelGoogle** [comment]
I've asked @mit-mit to see if AAR can help here.

**Comment by eseidelGoogle** [comment]
Report from the user:

> Cocoapods is now a 1gb checkout (~200k commits)
This is fine-ish, but it looks like the folder needs to be user-writable. We clone the user's skeleton profile on checkin and including this 1gb (350k files) takes a long time. Is there a way to use Cocoapods from a non-writable location or perhaps to avoid a repo checkout all together?
>
> Some comedy ideas-
> * git checkout the repo as admin so it's always up-to-date every login
> * copy a sparse image (faster than 350k files) and mount that

**Comment by collinjackson** [comment]
One option would be to instruct the codelab users to edit their ios/Podfile to put in an alternative source, e.g.

source 'https://github.com/flutter/codelab_specs.git'

Then we could populate it with just the specs used by the code-lab. We'd need to make sure to include the dependencies of the plugin specs as well, e.g. 'Firebase/Database'.

If users forgot to follow this step, the codelab would still work, it would just take longer.

Another option would be to have a recent clone of the official CocoaPods Spec downloaded onto the codelab machines and copy it into the ~/.cocoapods/repos/master/ directory in a startup script.

Additional reading:

* [Private Cocoapods](https://guides.cocoapods.org/making/private-cocoapods.html)
* [Why CocoaPods doesn't use shallow copies](http://blog.cocoapods.org/Master-Spec-Repo-Rate-Limiting-Post-Mortem/)

**Comment by eseidelGoogle** [comment]
@samthor @mit-mit

**Comment by mit-mit** [comment]
I don't have any additional suggestions. The Private Cocoapods idea sounds promising to me.

**Comment by mit-mit** [comment]
Actually, one more idea: Maybe use [`git bundle`](https://git-scm.com/docs/git-bundle) to create a file bundle of cocoapods/Specs, put that bundle file on the codelab machine, and then in the startup script do something like:

```
mkdir ~/.cocoapods/repos
git clone -b master /files/specs.bundle master ~/.cocoapods/repos/master
```

I just did some spot checking of a smaller repo, and this appears to work.

**Comment by eseidelGoogle** [comment]
@collinjackson how many pods do the codelabs depend on?

**Comment by collinjackson** [comment]
I think it's currently just the Firebase and Google ones, but there may be some transitive dependencies I don't know about.

**Comment by eseidelGoogle** [comment]
We could also make kiosk-only `flutter create` modifications if absolutely needed.

**Comment by samthor** [comment]
What I've done for now is `git clone --no-checkout` and placed that in the "skeleton" user profile. This takes up ~426mb but is only 42 files, which is pretty fast to copy.

This reduces the space requirement a ton, and then it's only checked out (with its corresponding 300k files) when/if the user uses Flutter.

**Comment by collinjackson** [comment]
Sounds like a good compromise solution. Thank you so much for setting this up.

Do you know roughly how long it takes the first pod install to run, compared to before?

**Comment by collinjackson** [comment]
I think we can close the M2 issue since we now have a solution for kiosks. The Cocoapods setup is pretty slow if you're not at a kiosk, though... @xster is working on a mitigation in #9580

**Comment by xster** [comment]
I agree it's not an M2 issue anymore, though I still think we need a long term solution for users using a production plugin for the first time in the future, even if we called it out and had users do it as a separate operation. Since their spec repo will just keep growing larger and larger as more pods come into existence and people update existing pods. 

Unfortunately I don't have anything better to propose. Carthage not having a central repo is inconvenient though I assume plugin developers would have a single repo for dart and native code anyway and the discovery would be done via pub anyway.

**Comment by collinjackson** [comment]
It's reasonable to mirror the specs that are used by common plugins in a Flutter specs repo on GitHub, and make developers explicitly add a dependency on the Cocoapods master spec repo if they want to use pods that we haven't mirrored. Or plugins could declare in their pubspec.yaml whether they depend on the Flutter spec repo or the default spec repo.

Doing discovery of Carthage repos through pub seems reasonable, although we may run into problems if plugins depend on third-party SDKs that aren't in Carthage yet.

**Comment by xster** [comment]
Oh that's a great idea. Perhaps we can add docs for publishing to pub that we encourage developers to host their plugins for objective c separately have the pubspec-resolution-podfile-generate-fanciness point to a bridge to their host location known to pub or something and circumvent cocoapods as a discovery repository mechanism
