### ISSUE TITLE
flutter app building issue

### ISSUE THREAD

**Issue by aditya305** [flutter/flutter#95599]
Error:
![image](https://user-images.githubusercontent.com/41361167/146833560-e1d3127b-baf8-4df1-823f-ea2bb25b6641.png)

Flutter doctor -v
![image](https://user-images.githubusercontent.com/41361167/146833617-581a4773-95ca-45b3-9e2e-9f1bf8e7a590.png)

**Comment by NullByte08** [comment]
Hi, as the error mentions, in the code `super.addAllowedPointer(event)` `event` is an instance of `PointerEvent` class. But, `addAllowedPointer()` accepts an instance of `PointerDownEvent` class instead. Pls make the necessary changes in your code to solve this.

If this doesn't help, pls paste here the complete code where the error is happening. Please refrain from pasting screenshots, and paste your code and error messages in text. Use [this](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) for formatting code and [this](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections) for formatting large logs and errors.
