### ISSUE TITLE
[plugin] PR description not uploaded to CI after being edited, plugins "publishable" check continues to fail

### ISSUE THREAD

**Issue by hellohuanlin** [flutter/flutter#95594]
I had this issue when I was trying to land https://github.com/flutter/plugins/pull/4608. I got this error: 

```
No version change found, but the change to this package could not be verified to be exempt from version changes according to repository policy. If this is a false positive, please add a line starting with
No version change:
to your PR description with an explanation of why it is exempt.
```

So I updated the PR description and re-run the check, but still not working. 

I suspected that it's because the PR description is not uploaded after edited for some reason. In order to verify this assumption, I rehashed the commit, which will most likely trigger the whole pipeline, and the error is gone. 

For now, I figured that it may be helpful to include this as temp workaround in the error output.

**Comment by stuartmorgan** [comment]
The CI script that feeds the PR description into the repo tooling is very simple, so my assumption is that this is a fundamental behavior of Cirrus and/or GitHub and not something we can fix. (It is annoying; I didn't know it would work this way when I wrote the override logic.)

**Comment by hellohuanlin** [comment]
@stuartmorgan in this case i think my workaround is fine (just add the info to the error output)

**Comment by stuartmorgan** [comment]
Closing as resolved; we switched to a label because the description didn't work as expected.
