### ISSUE TITLE
Enable auto power on for mtv-43 NUCs

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#95606]
NUCs used for linux and windows test beds do not have the the option to auto power on after power failure. This causes the devices to stay off when there is a power outage.

https://www.intel.com/content/www/us/en/support/articles/000054773/intel-nuc/intel-nuc-mini-pcs.html

**Comment by yusuf-goog** [comment]
Tickets have been opened to manually power on the devices effected and fix the BIOS settings to auto power on. 

CL for device setup documentation changes have been sent as well.

**Comment by yusuf-goog** [comment]
Devices have been powered on. Bug is open to fix the BIOS setting.

**Comment by yusuf-goog** [comment]
b/211514845 is complete, BIOS settings should be updated.
