### ISSUE TITLE
[Bug iOS] FlutterViewController not call dealloc when popped, after version 2.2.3

### ISSUE THREAD

**Issue by CodeEagle** [flutter/flutter#95611]
```objective-c
#import "AppDelegate.h"

@interface RootVC : UIViewController

@end

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application
    didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    UIWindow *win = [[UIWindow alloc] init];
    win.rootViewController = [[UINavigationController alloc] initWithRootViewController:[[RootVC alloc] init]];
    [win makeKeyAndVisible];
    self.window = win;
  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}

@end


@interface VC : FlutterViewController
@end
@implementation RootVC

-(void)viewDidLoad {
    [super viewDidLoad];
}

- (void)viewDidAppear:(BOOL)animated {
    [super viewDidAppear:animated];
    NSLog(@"push");
    VC *vc = [[VC alloc] init];
    [self.navigationController pushViewController:vc animated:true];
}

@end

@implementation VC
- (void)dealloc {
    NSLog(@"dealloc");
}

-(void)viewDidLoad {
    [super viewDidLoad];
    NSLog(@"load");
}

@end

```

step to produce:

0. create module by running `flutter crreate -t module dealloc_demo`
1. replacing AppDelegate.m with code above
2. using 2.2.1 sdk to build and run app, when app apprear, press `< Back` button，will log `dealloc`，
3. using 2.8.0  sdk to build and run app, when app apprear, press `< Back` button，no `dealloc` log in console

**Comment by CodeEagle** [comment]
a bit more info.
also tested with `2.5.2` an `2.5.3`, either version logs `dealloc `

**Comment by darshankawar** [comment]
@CodeEagle 
Check [this](https://github.com/flutter/flutter/issues/94099#issuecomment-979707608) issue comment and see if it solves your issue.

**Comment by CodeEagle** [comment]
Maybe it works, I'm using version `2.9.0-0.1.pre` now

**Comment by darshankawar** [comment]
If its fixed on master, I will go ahead and close. If you disagree, write in comments and I'll reopen.
