### ISSUE TITLE
Rich Notification - Notification service extension not called on flutter iOS 

### ISSUE THREAD

**Issue by vijay-subramani** [flutter/flutter#95627]
Issue:- When getting remote notification have to show image using the imageurl in payload. In Android it’s working fine once we changed the payload. In iOS image not showing in push notification.

Issue facing on Notification Service Extension:- I have added the notification extension and added the code for modifying notification content. This configuration is working fine in native iOS app.

Added the same in the flutter iOS project but there it won’t work. While receiving push notification the extension is not getting called. Just receiving normal notification only. I have tried many scenarios to sort out this issue. Still it’s not working.

Steps i’ve followed:

* Added code to get notification permission
* Added Notification extension to the project
* Used automatically manage signing for profile configuration
* Added code to modify notification
* Added imageURL and mutable-content keys in payload

**Added the project and payload screenshots here**
<img width="1411" alt="Screenshot 2021-12-21 at 2 04 34 PM" src="https://user-images.githubusercontent.com/32050235/146926686-06dca12b-dad4-41e9-a304-86c0b4940137.png">

**Payload**
<img width="1019" alt="Screenshot 2021-12-21 at 2 01 49 PM" src="https://user-images.githubusercontent.com/32050235/146926604-25645be8-6b1d-4c95-bde3-293cf1058e89.png">

**Expected results:**

Notification with Image
![IMG_1056](https://user-images.githubusercontent.com/32050235/146926496-a789e510-ee8c-4850-85b1-1134e096366a.PNG)

**Actual results:**
getting normal push notification only
![IMG_1060](https://user-images.githubusercontent.com/32050235/146926410-3f149c47-698a-482b-bc60-aed7cee40e83.PNG)

**Comment by darshankawar** [comment]
@vijay-subramani 
Assuming you are using `firebase_messaging` plugin for this, issues related to it need to report in dedicated repo: https://github.com/FirebaseExtended/flutterfire/issues
Closing from here.

**Comment by vijay-subramani** [comment]
@darshankawar Thanks! reported issue there.
