### ISSUE TITLE
Image picker not compressing images on web

### ISSUE THREAD

**Issue by sondresorbye** [flutter/flutter#95628]
## Steps to Reproduce

Get an image from image_picker like this:

`
 await picker.pickImage(source: ImageSource.camera,
                                          imageQuality: 40,
                                          maxWidth: 700,
                                          maxHeight: 700)
`

**Expected results:**

The images are compressed and resized on android and ios, but not on web. 

**Actual results:**

The images are not compressed nor resized on flutter web.

**Comment by darshankawar** [comment]
@sondresorbye 
Earlier, `imageQuality` was not supported on web, but it was added as part of this PR : https://github.com/flutter/plugins/pull/4389. Can you try this fix and see if it helps ?
If not, can you provide `flutter doctor -v`, and web plugin version  ?

**Comment by sondresorbye** [comment]
Is this PR available in the latest version: 0.8.4+4? Why is this not mentioned in the release notes?

**Comment by sondresorbye** [comment]
I tested and the images are not compressed in the latest version available on pub

**Comment by darshankawar** [comment]
@sondresorbye 
Did you try the web version of the plugin ? https://pub.dev/packages/image_picker_for_web/changelog#214

**Comment by sondresorbye** [comment]
Can I just import this, or do I have to remove the image_picker package?

**Comment by darshankawar** [comment]
Yes, you can just import the web version of the plugin as mentioned in its readMe and verify https://pub.dev/packages/image_picker_web#getting-started

**Comment by sondresorbye** [comment]
Ok, thanks a lot
