### ISSUE TITLE
Opening or closing date and time pickers creates many missed frames, visible jank

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#9562]
On a Moto G4, I see visible jank and confirm many missed frames when opening or closing a date or time picker. Here's a chart:

![screenshot_20170424-110424](https://cloud.githubusercontent.com/assets/5479/25351622/08f5e23e-28de-11e7-9610-1ae04b52fa82.png)

**Comment by Hixie** [comment]
cc @cbracken

**Comment by cbracken** [comment]
Closing as a specific case of #813 for bug tracking-purposes.
