### ISSUE TITLE
Exception: Gradle task assembleDebug failed with exit code 1

### ISSUE THREAD

**Issue by mrbudbud** [flutter/flutter#95636]
Exception: Gradle task assembleDebug failed with exit code 1

     FAILURE: Build failed with an exception.
      * What went wrong:
      Could not open settings remapped class cache for bq3hllkgb26p0nrblf5gh8d37 (C:\Users\Authentification\.gradle\caches\6.3\scripts-remapped\settings_d8ohwnitaqxr6pkye1rcxerp7\bq3hllkgb26p0nrblf5gh8d37\settingsdeec0faa97453e2ce860d75e6bf1604b).
     > Could not open settings generic class cache for settings file 'D:\Mechatronicslab\Presensi-Dishub-Tanggamus\android\settings.gradle' (C:\Users\Authentification\.gradle\caches\6.3\scripts\bq3hllkgb26p0nrblf5gh8d37\settings\settingsdeec0faa97453e2ce860d75e6bf1604b).
      > BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 61

     *Try:
     Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

     * Get more help at https://help.gradle.org
     BUILD FAILED in 12s
      Exception: Gradle task assembleDebug failed with exit code 1
      Exited (sigterm)

## This is my gradle 
`dependencies {`
           `classpath 'com.android.tools.build:gradle:4.1.0'`
           `classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"`
    `}`

I tried to solve the problem at  [https://stackoverflow.com/questions/57238933/gradle-failure-a-problem-occurred-evaluating-project-app](url)  , it didn't solve my problem.

**Comment by darshankawar** [comment]
@mrbudbud 
What Java version are you using ?

The error `BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 61` seems to be coming from gradle which doesn't seem to be compatible with jdk version you are using. Try to downgrade your jdk version to a version less than what you are using and see if it helps.

See this similar issue for your reference: https://stackoverflow.com/questions/66893535/why-my-flutter-app-dont-run-bug-exception-in-phase-semantic-analysis-in-sou

Closing from here, as this isn't a Flutter issue. If you disagree, write in comments and I'll reopen it.
