### ISSUE TITLE
TabController.animateTo does not animate properly

### ISSUE THREAD

**Issue by mkranus** [flutter/flutter#95638]
1. It does not obey the duration provided, and always defaults to `kTabScrollDuration`
2. Does not obey the curve provided, and uses default value
3. Does not animate through the pages (eg. when animating from 1 to 5, it goes directly to 5 instead of animating through the 2, 3, 4)

## Steps to Reproduce

1. use the official TabController example (https://docs.flutter.dev/cookbook/design/tabs)
2. Modify the TabBarView to use an explicit TabController
3. use `controller.animateTo(2, duration: Duration(seconds: 5), curve: Curves.linear)`

**Expected results:** 
It should obey the provided duration and curve

**Actual results:** 
It uses default duration and curve, and moves directly to 2

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

Doctor summary:
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6.1 20G224 darwin-x64, locale en-US)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
[✓] Connected device (2 available)

```
```

</details>

**Comment by maheshmnj** [comment]
Hi @mkranus, Thanks for filing the issue.

There is a similar issue describing this case https://github.com/flutter/flutter/issues/16892, Please follow up there for further updates, Closing this issue as a duplicate. If you disagree feel free to write in the comments and I will reopen it.

Thank you.
