### ISSUE TITLE
Flutter map is not rendering in web

### ISSUE THREAD

**Issue by Abhishek8-198** [flutter/flutter#95659]
import 'package:flutter/material.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:latlong/latlong.dart' as latlong;
// import 'package:mapbox_gl/mapbox_gl.dart';
//
// class MapBoxWeb extends StatefulWidget {
//   @override
//   _MapBoxWebState createState() => _MapBoxWebState();
// }
//
// class _MapBoxWebState extends State<MapBoxWeb> {
//   MapboxMapController mapController;
//
//   void _onMapCreated(MapboxMapController controller) {
//     mapController = controller;
//   }
//
//   @override
//   void initState() {
//     super.initState();
//   }
//
//   @override
//   void dispose() {
//     mapController.dispose();
//     super.dispose();
//   }
//
//   @override
//   Widget build(BuildContext context) {
//     return Container(
//       height: MediaQuery.of(context).size.height,
//       width: MediaQuery.of(context).size.width,
//       child: MapboxMap(
//           accessToken:
//               'pk.eyJ1IjoiYWJoaS04MTk4IiwiYSI6ImNreGVxY2R4aDFiNWcyb3Bka2l0aXQwdXAifQ.40GzI4Y_AaCPrHLGMtEYnA',
//           onMapCreated: _onMapCreated,
//           onStyleLoadedCallback: () => addCircle(mapController),
//           initialCameraPosition: CameraPosition(
//               target: LatLng(28.479462047712307, 77.51447532422465), zoom: 14)),
//     );
//   }
//
//   void addCircle(MapboxMapController mapController) {
//     mapController.addCircle(CircleOptions(
//         geometry: LatLng(28.479462047712307, 77.51447532422465),
//         circleColor: '#23d2aa',
//         circleRadius: 15));
//   }
// }

class MapBoxWeb extends StatefulWidget {
  @override
  _MapBoxWebState createState() => _MapBoxWebState();
}

class _MapBoxWebState extends State<MapBoxWeb> {
  @override
  Widget build(BuildContext context) {
    return FlutterMap(
      options: new MapOptions(
        center: latlong.LatLng(28.479462047712307, 77.51447532422465),
        zoom: 13.0,
      ),
      layers: [
        new TileLayerOptions(
          urlTemplate:
              "https://api.mapbox.com/styles/v1/abhi-8198/ckxfstd77h3jp15s9zwkzz5em/wmts?access_token=pk.eyJ1IjoiYWJoaS04MTk4IiwiYSI6ImNreGVxY2R4aDFiNWcyb3Bka2l0aXQwdXAifQ.40GzI4Y_AaCPrHLGMtEYnA",
          additionalOptions: {
            'accessToken':
                'pk.eyJ1IjoiYWJoaS04MTk4IiwiYSI6ImNreGVxY2R4aDFiNWcyb3Bka2l0aXQwdXAifQ.40GzI4Y_AaCPrHLGMtEYnA',
            'id': 'mapbox.mapbox-streets-v8',
          },
        ),
        new MarkerLayerOptions(
          markers: [
            new Marker(
              width: 80.0,
              height: 80.0,
              point: latlong.LatLng(28.479462047712307, 77.51447532422465),
              builder: (ctx) => new Container(
                  child: IconButton(
                      icon: Icon(Icons.location_on),
                      color: Colors.red,
                      iconSize: 45.0,
                      onPressed: () {
                        print('Marker tapped');
                      })),
            ),
          ],
        ),
      ],
    );
  }
}

**Comment by danagbemava-nc** [comment]
The package doesn't list web as a supported platform on pub.dev, so that's probably why that is the case. 

![Screenshot 2021-12-22 at 08 04 36](https://user-images.githubusercontent.com/88313112/147057568-0b28dc63-9c96-43ab-91bd-dea61373c102.png)

Kindly file an issue on their repo https://github.com/fleaflet/flutter_map/issues as this is not maintained by the flutter team. 

Closing from here. 

Thank you

**Comment by Abhishek8-198** [comment]
Can you please suggest me any map package that i can use in web?
