### ISSUE TITLE
Flutter module iOS Release build issue - Engine run configuration was invalid

### ISSUE THREAD

**Issue by SatyaranjanMohapatra-BT** [flutter/flutter#95650]
I am writing a flutter module to be used inside a existing iOS app.
I am integrating the XCFramework built from flutter module as per Flutter module iOS integration guideline (Option B).
I am generating the release build using :
`flutter build ios-framework --no-profile --no-debug --output=../Build` 

But while loading the FlutterViewController I am getting the below mentioned error and App is getting stuck.

`Failed to find snapshot: /Users/suparno/Library/Developer/CoreSimulator/Devices/4B36B8DB-013C-444F-B732-3ACA56D99894/data/Containers/Bundle/Application/885FD0A0-E5F2-49D1-8734-80A285260225/BTB_Flutter_Wrapper.app/Frameworks/App.framework/flutter_assets/kernel_blob.bin
Metal API Validation Enabled
[VERBOSE-2:engine.cc(194)] Engine run configuration was invalid.
[VERBOSE-2:shell.cc(576)] Could not launch engine with configuration.
flutter: Observatory listening on http://127.0.0.1:53201/MZgdLNlfjK0=/
Writing analzed variants.`

This problem is not happening for the debug build.

Am I doing anything wrong here?

**Comment by darshankawar** [comment]
@SatyaranjanMohapatra-BT 
Can you provide `flutter doctor -v`, `flutter build ios-framework --no-profile --no-debug --output=../Build --verbose` ?

**Comment by SatyaranjanMohapatra-BT** [comment]
**flutter doctor -v**
`flutter doctor -v
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.5.3 at /Users/suparno/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (10 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/suparno/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.63.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (4 available)
    • sdk gphone arm64 (mobile) • emulator-5554                        • android-arm64  • Android 11 (API 30) (emulator)
    • BT IPhone 12Pro (mobile)  • 00008030-001915E43682402E            • ios            • iOS 15.2 19C56
    • iPhone 13 (mobile)        • 4B36B8DB-013C-444F-B732-3ACA56D99894 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • Chrome (web)              • chrome                               • web-javascript • Google Chrome 96.0.4664.110

! Doctor found issues in 1 category.`

**flutter build ios-framework --no-profile --no-debug --output=../Build --verbose**

[verbose_log.pdf](https://github.com/flutter/flutter/files/7762759/verbose_log.pdf)

**Comment by darshankawar** [comment]
@SatyaranjanMohapatra-BT 
From the verbose log you shared, it seems to show that the command you ran was completed successfully and build was generated and it also doesn't show any error log you shared earlier.

```
[ +672 ms] xcframework successfully written out to: /Volumes/WakkaoW/Development/GIT/btb-flutter-ios-wrapper/ MyHomeFramework/Fameworks/Build/Release/wifi_module.xcframework
[ +1 ms] ├─Building plugins... (completed in 23.4s)
[ +2 ms] #"Moving to ../Build/Release
[ +73 ms] └─Moving to ../Build/Release (completed in 73ms)
[ ] Frameworks written to /Volumes/WakkaoW/Development/GIT/ btb-flutter-ios-wrapper/MyHomeFramework/Fameworks/Flutter Module/../ Build.
[ +1 ms] "flutter ios-framework" took 141,329ms.
[ +128 ms] ensureAnalyticsSent: 114ms

```
Please provide us the complete log which has the errors you mentioned above.

**Comment by SatyaranjanMohapatra-BT** [comment]
There is no error while generating the XCFramework.
But when I am importing the XCFramework in our project and trying to load the FlutterViewController I getting.

`Failed to find snapshot: /Users/suparno/Library/Developer/CoreSimulator/Devices/4B36B8DB-013C-444F-B732-3ACA56D99894/data/Containers/Bundle/Application/885FD0A0-E5F2-49D1-8734-80A285260225/BTB_Flutter_Wrapper.app/Frameworks/App.framework/flutter_assets/kernel_blob.bin Metal API Validation Enabled [VERBOSE-2:engine.cc(194)] Engine run configuration was invalid. [VERBOSE-2:shell.cc(576)] Could not launch engine with configuration. flutter: Observatory listening on http://127.0.0.1:53201/MZgdLNlfjK0=/ Writing analzed variants.`

there is no more log printed as this is a release build.

debug build is working perfectly.

**Comment by darshankawar** [comment]
@SatyaranjanMohapatra-BT 
Can you confirm whether the `kernel_blob.bin` under `flutter_assets` in the `/Users/suparno/Library/Developer/CoreSimulator/Devices/4B36B8DB-013C-444F-B732-3ACA56D99894/data/Containers/Bundle/Application/885FD0A0-E5F2-49D1-8734-80A285260225/BTB_Flutter_Wrapper.app/Frameworks/App.framework/` path is present in debug mode as well as in release mode ?

Also confirm if your `Flutter.framework` and `App.framework` are the same debug or release mode. You can also try to run `flutter build ios --release` first and then followed by your command and see if it helps.
