### ISSUE TITLE
Flutter driver can not control a TextField without an initialized controller (`DriverError: Error in Flutter application: Uncaught extension error while executing get_text: Unsupported operation: Type TextField is currently not supported by getText`)

### ISSUE THREAD

**Issue by filmil** [flutter/flutter#95652]
## Steps to Reproduce

Try to run flutter driver test on a text field widget such as  this one:

```
// ...
TextField(key: ValueKey('foo'), maxLines:4),
// ...
```

Then attempt to test the widget using a flutter driver test: `driver.getText(find.byValueKey('foo'))`.

**Expected results:** 

You get the text from the TextField.  This is supposed to be supported since https://github.com/flutter/flutter/pull/48809.

**Actual results:** 

An error message appears:
```
  DriverError: Error in Flutter application: Uncaught extension error while executing get_text: Unsupported operation: Type TextField is currently not supported by getText
  #0      CommandHandlerFactory._getText (package:flutter_driver/src/common/handler_factory.dart:416:7)                                                                              
  <asynchronous suspension>                                                                                                                                                          
  #1      FlutterDriverExtension.call (package:flutter_driver/src/extension/extension.dart:373:31)                                                                                   
  <asynchronous suspension>                                                                                                                                                          
  #2      BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:602:18)                                                              
  <asynchronous suspension>                      
```

If however you modify the `TextField` to supply an explicitly initialize `TextFieldController` like so:

```
TextField(key: ValueKey('foo'), maxLines:4, controller: TextFieldController()),
```

everything works as expected.

I think the culprit is here: https://github.com/flutter/flutter/blob/master/packages/flutter_driver/lib/src/common/handler_factory.dart#L408

That line assumes that a controller is non-`null`, which is not always true, and then erroneously assumes that `TextField` is not supported with `getText` a [few lines below][flb].

[flb]: https://github.com/flutter/flutter/blob/master/packages/flutter_driver/lib/src/common/handler_factory.dart#L415

Granted, a `TextField` without a Controller is kinda useless, but it would be nice if the code correctly accounted for the possibility that `TextField.controller == null` for consistency's sake.  I haven't checked the other `Text*` widgets, but I would not be surprised if the same issue exists there too.

The `TextField.controller` docs say ["If null, this widget will create its own TextEditingController."][docs]  But this either happens lazily or not soon enough. For example if you just initialize an empty text field and do nothing with it, `TextField.controller` will remain `==null`, which causes the error above.

[docs]: https://api.flutter.dev/flutter/material/TextField/controller.html 

Sorry about the lack of a repro - I wanted to report this before I scurry off to something else, and it seems like the issue may be obvious even without a repro to an expertly eye.  I'm very happy to backfill with a repro case if this is not enough info.

**Comment by darshankawar** [comment]
@filmil 
Since `integration_test` is now recommended way to run integration tests, can you try by running `flutter test integration_test` command instead of using `flutter drive` and see if you still get same behavior ?

https://docs.flutter.dev/cookbook/testing/integration/introduction#5a-mobile

**Comment by filmil** [comment]
I will try. Though, my OS is Fuchsia, which IIRC does not have that option.

**Comment by darshankawar** [comment]
@filmil 
Can you please elaborate on `does not have that option.` ? You mean running `flutter integration test` command isn't available / supported on Fuchsia ?

**Comment by filmil** [comment]
> @filmil Can you please elaborate on `does not have that option.` ? You mean running `flutter integration test` command isn't available / supported on Fuchsia ?

As far as I know it indeed is as you summarize.  Fuchsia has its own build system - there is no `flutter integration test` command to be ran AFAIK. But I may be wrong, will check and report back.
