### ISSUE TITLE
[flutter_image] Web support

### ISSUE THREAD

**Issue by jcblancomartinez** [flutter/flutter#95671]
## Use case

Use NetworkImageWithRetry to retry certain exceptions when fetching images for web. 

## Proposal

NetworkImageWithRetry should support web.

Thanks.

Regards.

**Comment by danagbemava-nc** [comment]
Duplicate of https://github.com/flutter/flutter/issues/89481.

Kindly see https://github.com/flutter/flutter/issues/89481#issuecomment-914402919 and https://github.com/flutter/flutter/issues/39998 for why this isn't possible yet. 

Closing from here as duplicate
