### ISSUE TITLE
flutter command doesn't follow Unix conventions for stdout and stderr

### ISSUE THREAD

**Issue by skybrian** [flutter/flutter#9569]
Unix commands should sent primary output to `stdout` and any progress or error messages should go to `stderr`. That way if we pipe the output to another command, we'll still see progress or errors on the terminal and the downstream command doesn't need to handle them.

We don't currently follow this convention for the `flutter` command. See update_dart_sdk.sh for example, which uses 'echo' to send errors to stdout.

**Comment by zanderso** [comment]
This isn't planned. Rather, for the specific cases where we need machine readable output, the tool accepts the `--machine` flag and generates JSON output.
