### ISSUE TITLE
[video_player]Crash when get duration is zero

### ISSUE THREAD

**Issue by xiaowei-guan** [flutter/flutter#95707]
when playing live stream, player can't get duration when player prepared, will cause video player plugin crash.

https://github.com/flutter/plugins/blob/master/packages/video_player/video_player/lib/video_player.dart#L901-L910
```dart 
         children: <Widget>[
          LinearProgressIndicator(
            value: maxBuffering / duration,
            valueColor: AlwaysStoppedAnimation<Color>(colors.bufferedColor),
            backgroundColor: colors.backgroundColor,
          ),
          LinearProgressIndicator(
            value: position / duration,
            valueColor: AlwaysStoppedAnimation<Color>(colors.playedColor),
            backgroundColor: Colors.transparent,
          ),
```

**Comment by maheshmnj** [comment]
Hi @xiaowei-guan, Thanks for filing the issue. Can you please share 
- the complete crash logs
-  output of `flutter doctor -v`
-  the platform on which the app crashed
-  the version of video_player plugin
-  And a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example).

Thank you.

**Comment by xiaowei-guan** [comment]
crash log:
An Observatory debugger and profiler on Tizen 0 is available at: http://127.0.0.1:44741/d-8jrmBO8Fk=/

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following UnsupportedError was thrown building LinearProgressIndicator(100.0%, dirty,
dependencies: [_InheritedTheme, _EffectiveTickerMode, _LocalizationsScope-[GlobalKey#33d9d],
Directionality], state: _LinearProgressIndicatorState#1e3f2(ticker inactive)):
Unsupported operation: Infinity or NaN toInt

The relevant error-causing widget was:
  LinearProgressIndicator
  LinearProgressIndicator:file:///home/guanxw/.pub-cache/hosted/pub.flutter-io.cn/video_player-2.2.9/lib/video_player.dart:902:11

When the exception was thrown, this was the stack:
#0      double.toInt (dart:core-patch/double.dart:219:36)
#1      double.round (dart:core-patch/double.dart:182:34)
#2      ProgressIndicator._buildSemanticsWrapper (package:flutter/src/material/progress_indicator.dart:130:52)
#3      _LinearProgressIndicatorState._buildIndicator (package:flutter/src/material/progress_indicator.dart:389:19)
#4      _LinearProgressIndicatorState.build (package:flutter/src/material/progress_indicator.dart:414:14)
#5      StatefulElement.build (package:flutter/src/widgets/framework.dart:4782:27)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4665:15)
#7      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#8      Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#9      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643:5)
#10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4831:11)
#11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)
#12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#13     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6333:36)
#14     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6344:32)
#15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:3422:20)
#17     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6202:14)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#19     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6202:14)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#21     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6202:14)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#24     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#25     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#26     StatefulElement.update (package:flutter/src/widgets/framework.dart:4872:5)
#27     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#29     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#30     StatelessElement.update (package:flutter/src/widgets/framework.dart:4746:5)
#31     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#33     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#34     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#35     StatefulElement.update (package:flutter/src/widgets/framework.dart:4872:5)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#38     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#39     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#40     StatefulElement.update (package:flutter/src/widgets/framework.dart:4872:5)
#41     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#42     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5700:32)
#43     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6356:17)
#44     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#45     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6202:14)
#46     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#47     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6202:14)
#48     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#50     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#51     StatelessElement.update (package:flutter/src/widgets/framework.dart:4746:5)
#52     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#53     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5700:32)
#54     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6356:17)
#55     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#56     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6202:14)
#57     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#58     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6202:14)
#59     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#60     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6202:14)
#61     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#62     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6202:14)
#63     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#64     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6202:14)
#65     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#67     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#68     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#69     StatefulElement.update (package:flutter/src/widgets/framework.dart:4872:5)
#70     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#71     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6202:14)
#72     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#74     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#75     ProxyElement.update (package:flutter/src/widgets/framework.dart:5020:5)
#76     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#77     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6202:14)
#78     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#79     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6202:14)
#80     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#81     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6202:14)
#82     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#83     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6202:14)
#84     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#85     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#86     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#87     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#88     StatefulElement.update (package:flutter/src/widgets/framework.dart:4872:5)
#89     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#90     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6202:14)
#91     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#92     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6202:14)
#93     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#94     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#95     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#96     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#97     StatefulElement.update (package:flutter/src/widgets/framework.dart:4872:5)
#98     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#99     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6202:14)
#100    Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#101    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#102    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#103    StatelessElement.update (package:flutter/src/widgets/framework.dart:4746:5)
#104    Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#105    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#106    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#107    StatelessElement.update (package:flutter/src/widgets/framework.dart:4746:5)
#108    Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#109    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#110    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#111    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#112    StatefulElement.update (package:flutter/src/widgets/framework.dart:4872:5)
#113    Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#114    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#115    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#116    StatelessElement.update (package:flutter/src/widgets/framework.dart:4746:5)
#117    Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#118    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#119    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#120    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#121    StatefulElement.update (package:flutter/src/widgets/framework.dart:4872:5)
#122    Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#123    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#124    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#125    ProxyElement.update (package:flutter/src/widgets/framework.dart:5020:5)
#126    Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#127    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#128    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#129    StatelessElement.update (package:flutter/src/widgets/framework.dart:4746:5)
#130    Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#131    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#132    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#133    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#134    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2620:33)
#135    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#136    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#137    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
#138    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080:9)
#139    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#143    _invoke (dart:ui/hooks.dart:166:10)
#144    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#145    _drawFrame (dart:ui/hooks.dart:129:31)
(elided 3 frames from dart:async)

**Comment by xiaowei-guan** [comment]
output of flutter doctor -v:
guanxw@yuanzw:~/Tizen/plugins/packages/video_player/example$ flutter-tizen doctor -v
[✓] Flutter (Channel unknown, 2.5.3, on Ubuntu 20.04.3 LTS 5.4.0-91-generic, locale en_US.UTF-8)
    • Flutter version 2.5.3 at /home/guanxw/Tizen/flutter-tizen/flutter
    • Upstream repository unknown
    • Framework revision 18116933e7 (10 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Tizen toolchain - develop for Tizen devices
    • Framework revision 399090f47b (3 weeks ago), 2021-12-04 14:17:51 +0900
    • Engine revision d86ec05e37
    • Tizen Studio 4.5 at /home/guanxw/tizen-studio
    • .NET SDK 3.1.409 at /usr/bin/dotnet

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/diskB/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /home/diskB/Android/Sdk
    • Java binary at: /home/diskB/Android/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 4.1)
    • Android Studio at /home/diskB/Android/android-studio
    • Flutter plugin version 54.1.1
    • Dart plugin version 201.9335
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Linux (desktop)  • linux                 • linux-x64      • Ubuntu 20.04.3 LTS 5.4.0-91-generic
    • Chrome (web)     • chrome                • web-javascript • Google Chrome 96.0.4664.93
    • Tizen 0 (mobile) • 109.123.120.248:26101 • flutter-tester • Tizen 6.0

**Comment by xiaowei-guan** [comment]
I run video player plugin example on Tizen platform.
 video player version :  video_player: ^2.2.6

**Comment by maheshmnj** [comment]
@xiaowei-guan, I ran this [official sample code](https://github.com/flutter/plugins/blob/master/packages/video_player/video_player/example/lib/main.dart) using `video_player: ^2.2.6` on Xiaomi k20 pro (Android 11) and I could not reproduce the issue, Are there any known reproducible steps or does the issue occur only on tizen OS? 

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.8.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (11 days ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:5555 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos            • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 96.0.4664.110

• No issues found!
```
</details>

**Comment by swift-kim** [comment]
@xiaowei-guan Could you provide some stream URL that generates the crash?

**Comment by xiaowei-guan** [comment]
> 

@maheshmnj  @swift-kim  I run video player plugin sample  code with this live stream( https://host10a-fes.tvfellow.tv/stream1/id_webclient-3a4c7f05-a437-4c12-b432-b7ee191f6972/hls/tv/tr_BBC_World_News_Europe_HD/profiles.m3u8)

**Comment by maheshmnj** [comment]
@xiaowei-guan,  the live stream URL doesn't seem to stream any data the video player keeps loading but does not crash the app. Can you try upgrading to latest `stable 2.8.1` ?

<img src="https://user-images.githubusercontent.com/31410839/147475695-c27c03ee-a3e7-49bf-9221-884edac154bd.png" width ="300">

**Comment by xiaowei-guan** [comment]
> 

I ran video player plugin on galaxy_s20(android 9) , no crash issue. It may be a issue with Tizen video player.
