### ISSUE TITLE
Directory.listSync() Failed

### ISSUE THREAD

**Issue by jiabin87428** [flutter/flutter#95723]
getTemporaryDirectory with path_provider and do listSync()

error:
FileSystemException: Directory listing failed, path = '/var/mobile/Containers/Data/Application/BA809B25-43FA-4625-9209-583DA9B52DF7/Library/Caches/Snapshots' (OS Error: Operation not permitted, errno = 1)

**Comment by jiabin87428** [comment]
iPhone 5s
iOS 12.5.1

**Comment by darshankawar** [comment]
@jiabin87428 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example
) that shows this error ?

**Comment by jiabin87428** [comment]
> @jiabin87428
> Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this error ?

It has been resolved. The reason is that the system before iOS13 will place the Snapshots folder in the Caches folder. Snapshots has no operation permissions. So when you need do Directory.listSync(), you need to filter out Snapshots, like : 
if (file is Directory && !file.path.contains('Library/Caches/Snapshots'))  {
    file.listSync()
    ...
}

**Comment by xuwankang** [comment]
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: FileSystemException: Directory listing failed, path = '/var/mobile/Containers/Data/Application/6A489703-42DF-491B-925B-A28163D2F580/Library/Caches/Snapshots/' (OS Error: Operation not permitted, errno = 1)

`CupertinoButton(
                    onPressed: () async {
                      Directory tempDir = await getTemporaryDirectory();
                      //删除缓存目录
                      await delDir(tempDir);
                    },
                    child: Text('确定'),
                  ),`
`Future<Null> delDir(final FileSystemEntity file) async {
    if (file is Directory && file.existsSync() && !file.path.contains('Library/Caches/Snapshots')) {
      final List<FileSystemEntity> children = file.listSync();
      print(children);
      for (final FileSystemEntity child in children) {
        await delDir(child);
      }
    }
    await file.delete();
  }`
