### ISSUE TITLE
List of targets for flutter assemble

### ISSUE THREAD

**Issue by rsteube** [flutter/flutter#95736]
Is there a list of possible targets for `flutter assemble [TARGET]` somewhere?
I got [most of them](https://github.com/rsteube/carapace-bin/blob/master/completers/flutter_completer/cmd/action/target.go) from the code but am still trying to figure out the values for the following:

```go
//  // Android ABI specific AOT rules.
//  androidArmProfileBundle,
//  androidArm64ProfileBundle,
//  androidx64ProfileBundle,
//  androidArmReleaseBundle,
//  androidArm64ReleaseBundle,
//  androidx64ReleaseBundle,
//  // Deferred component enabled AOT rules
//  androidArmProfileDeferredComponentsBundle,
//  androidArm64ProfileDeferredComponentsBundle,
//  androidx64ProfileDeferredComponentsBundle,
//  androidArmReleaseDeferredComponentsBundle,
//  androidArm64ReleaseDeferredComponentsBundle,
//  androidx64ReleaseDeferredComponentsBundle,
```

```sh
flutter_completer/cmd/action on  master via 🐹 v1.17.5
❯ flutter assemble aot_assembly_profile                                                        rsteube@mpb
 COMPLETING argument
aot_assembly_profile             debug_bundle_windows_assets_uwp    profile_ios_bundle_flutter_assets
aot_assembly_release             debug_ios_bundle_flutter_assets    release_android_application
aot_elf_profile                  debug_macos_bundle_flutter_assets  release_bundle_linux_arm64_assets
aot_elf_release                  debug_macos_framework              release_bundle_linux_x64_assets
copy_assets                      kernel_snapshot                    release_bundle_windows_assets
copy_flutter_bundle              profile_android_application        release_bundle_windows_assets_uwp
debug_android_application        profile_bundle_linux_arm64_assets  release_ios_bundle_flutter_assets
debug_bundle_linux_arm64_assets  profile_bundle_linux_x64_assets    unpack_windows
debug_bundle_linux_x64_assets    profile_bundle_windows_assets      web_service_worker
debug_bundle_windows_assets      profile_bundle_windows_assets_uwp
```

**Comment by darshankawar** [comment]
@rsteube 
Check if [this](https://github.com/flutter/flutter/issues/95080) open issue is the same case as yours.

**Comment by rsteube** [comment]
@darshankawar 

Possibly, but i think the related issue is rather about the targets/subcommands of `flutter build [subcommand]` that are valid for the current project.
```
Available subcommands:
  aar         Build a repository containing an AAR and a POM file.
  apk         Build an Android APK file from your app.
  appbundle   Build an Android App Bundle file from your app.
  bundle      Build the Flutter assets directory from your app.
  linux       Build a Linux desktop application.
  web         Build a web application bundle.
```

I am looking for `flutter asssemble [target]` which as i understand are the substeps of the build targets.

**Comment by christopherfujino** [comment]
@rsteube this is not currently available. Is your use case for auto-completion? `flutter assemble` is not really intended to be directly called by users, but rather is transitively and reentrantly called as part of `flutter build ...` builds. We could add a new sub-command that lists these targets, but I'm not sure if it would actually benefit users much.

**Comment by rsteube** [comment]
@christopherfujino yes it's for shell completion. I added a flutter completer a while ago and just wanted to finish things up a bit. The targets i am missing are using util functions and thus just not as easy to figure out as the others. No need to cause any work on your side, just thought there might be a list somewhere.

**Comment by christopherfujino** [comment]
> @christopherfujino yes it's for shell completion. I added a flutter completer a while ago and just wanted to finish things up a bit. The targets i am missing are using util functions and thus just not as easy to figure out as the others. No need to cause any work on your side, just thought there might be a list somewhere.

Makes sense. To be honest, I'm surprised that this command shows when you run `flutter help`, as its usage is not guaranteed to be stable.

**Comment by rsteube** [comment]
@christopherfujino ok i managed to put a main function in `assemble.dart` and just [print them out](https://github.com/rsteube/carapace-bin/pull/825/files) :smile: . Sorry to bother you with this.

**Comment by christopherfujino** [comment]
> print them out

It's no bother, you wouldn't have known for sure unless you asked :)
