### ISSUE TITLE
Dart VM Observer cause app crashed -> error: unreachable code

### ISSUE THREAD

**Issue by ManInTheWind** [flutter/flutter#95731]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
**I make a page which List.builder 200 pic in NestedScrollView with ResizedImageHandler and the memory is fine;**
2. ... 
**when debug my app on VM Observer, and find out the reason of  the unreleased extenal memory,and I saw there lot of image quotation and when I clicked the "imageInfo" and will crash every time.** 
3. ... 
**Tap on Dart VM Observer -> persistent handles -> Inbound references -> ImageInfo  -> and then crash (everytime)**

**Expected results:** 

want to find out the _image References to the chain；

**Actual results:** 

the app is crash and seem to crash by the VM Observer,
`
../../third_party/dart/runtime/vm/object.cc: 19225: error: unreachable code
version=2.15.0 (stable) (Fri Dec 3 14:23:23 2021 +0100) on "ios_arm64"
pid=85762, thread=42755, isolate_group=main(0x103037e00), isolate=main(0x101052e00)
isolate_instructions=1078f34c0, vm_instructions=1078ee590
`
<details>
<summary>
Not available at present the code.sorry...
</summary>

```dart
```

</details>

<details>
<summary>
the crash log
</summary>

`flutter doctor -v`
![image](https://user-images.githubusercontent.com/32859126/147243664-595555b7-3549-4dbe-8674-48b475eb8a28.png)
------
**the crash log (1/2)**
![image](https://user-images.githubusercontent.com/32859126/147243134-ae5b4f2d-64ab-4d10-bbb5-5b61e0645717.png)

------
**the crash log (2/2)**
![image](https://user-images.githubusercontent.com/32859126/147243135-f03456fd-e99a-4af2-8867-62d19f398626.png)
------
**click the imageinfo of Inbound references  in Observer everytime will crash**
![image](https://user-images.githubusercontent.com/32859126/147243211-01b87712-1f73-476e-9cb0-7176bd754660.png)

```

```

</details>

**Comment by darshankawar** [comment]
@ManInTheWind 
Can you provide the code sample along with the crash log in text format instead of in screenshots ?
Thanks.
