### ISSUE TITLE
Google Map markers onTap shows inconsistent result if one marker is tapped multiple times

### ISSUE THREAD

**Issue by amalnaeem04** [flutter/flutter#95734]
Issue discussed [here](https://github.com/flutter/flutter/issues/59154) is still occurring for me for google_maps_flutter 2.1.1.

Restaurant name is different when a same marker is tapped again

`flutter doctor -v ` screenshot attached

```
for (int i = 0; i < restaurantsData!.length; i++) {
            marker = Marker(
              markerId: MarkerId(restaurantsData[i].merchantId.toString()),
              position: LatLng(restaurantsData[i].merchantLocation!.coordinates![1], restaurantsData[i].merchantLocation!.coordinates![0]),
              icon: BitmapDescriptor.fromBytes(markerIcon),
              onTap: () async {
                
                print(restaurantsData[i].merchantName);

                print(_browseMealsViewModel.pickUpRestaurantsData.inNetwork![i].merchantLocation!.coordinates);

              },
            );
          } 
```
          
![image](https://user-images.githubusercontent.com/59996613/147257408-5d494d78-2a4b-452e-8aab-0c51e5692a07.png)

**Comment by silicon-ninja** [comment]
Try using await.

**Comment by amalnaeem04** [comment]
it still doesn't work.

**Comment by silicon-ninja** [comment]
how are you sending the data to the widget to get update? steam builder?

**Comment by amalnaeem04** [comment]
I am getting restaurantsData from a backend API call and for each restauarant a marker is generated

**Comment by darshankawar** [comment]
@amalnaeem04 
Please upgrade to latest stable and try again to see if behavior still persists or not.
If yes, please provide a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example
) that shows the behavior.
