### ISSUE TITLE
Path_provider can't working on Android platform

### ISSUE THREAD

**Issue by vadimlukutin** [flutter/flutter#95741]
E/flutter (23905): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)

**Comment by stuartmorgan** [comment]
Duplicate of https://github.com/flutter/flutter/issues/95706
