### ISSUE TITLE
`ShellTest.DiscardLayerTreeOnResize` is flaky on presubmits.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#95751]
An [instance of the failure is here](https://cirrus-ci.com/task/5896295993835520?logs=test_host#L5544). The assertion failure is:

```
[ RUN      ] ShellTest.DiscardLayerTreeOnResize
../../flutter/shell/common/shell_unittests.cc:2373: Failure
Expected equality of these values:
  1
  external_view_embedder->GetSubmittedFrameCount()
    Which is: 2
[FATAL:flutter/fml/memory/weak_ptr.h(253)] Check failed: (checker_.checker).IsCreationThreadCurrent(). 
[ERROR:flutter/fml/backtrace.cc(116)] Caught signal SIGABRT during program execution.
Frame 0: 0x7fa680ecf42a abort
```

The test passed on re-run.

**Comment by cyanglaz** [comment]
I'm not able to reproduce this locally. If anyone has any luck reproduce this, please share the trick.
This test does not require `external_view_embedder`, but the current architecture requires `external_view_embedder` to be included in the test. It adds complicated thread merging logic into a simple test like this. I'm going to look into refactor this test so that it doesn't require thread merging, which can solve this issue as well.

**Comment by chinmaygarde** [comment]
> please share the trick

This is a flake so there may not be a fully reliable way of reproducing this. But, the best shot IMO would be to rerun the same test with same seed used by the bots. From the logs, the seed was 96731. So `--gtest_repeat=-1 --gtest_random_seed= 96731` ought to get you closest to the what the bot was doing.

If that fails, I would try running it with the [thread sanitizers](https://github.com/flutter/flutter/wiki/Using-Sanitizers-with-the-Flutter-Engine). But this would only be for data races and not race conditions.

Failing that, just good old fashioned reading the test to see if it non-racy or rewrite the test. Your intuituion that the test can be made less complicated is probably the right way to go.

**Comment by cyanglaz** [comment]
I tried to rerun with repeats=-1 and was unsuccessful to repro. Haven't tried the random_seed, I'll try that.
Yeah if I still can't repro it i'll rewrite the test. There was a TODO I left for that test to rewrite it to remove the thread merging from that test anyway.

**Comment by zanderso** [comment]
This is still failing https://cirrus-ci.com/task/5065923601104896

**Comment by chinmaygarde** [comment]
@cyanglaz Are you able to reason about this failure? Perhaps this is a different issue? Feel free to un-assign yourself if this is different from what you were originally trying to fix.

**Comment by cyanglaz** [comment]
The thread merging part of the test has been removed and the failure is probably not related to the race condition in the thread merging set up in the test. 
Maybe the test code I ended up with is wrong? Or the test failure actually indicates some issue with the current engine code?
CC @knopp @iskakaushik who might know more about this.
Could either of you review the current unittest and see if the test makes sense. https://github.com/flutter/engine/blob/main/shell/common/shell_unittests.cc#L2345

**Comment by chinmaygarde** [comment]
cc @iskakaushik Can you take a quick look at the test if you have some spare cycles?

**Comment by chinmaygarde** [comment]
@iskakaushik is OOO this week. I'll try to take a look at this this week but I am not sure I will be able to resolve it.

**Comment by christopherfujino** [comment]
From critical issue triage, assigning you @chinmaygarde per your comment

**Comment by ColdPaleLight** [comment]
I found another stack trace that looks similar, but in another test: `ShellTest.ResubmitFrame`.

https://cirrus-ci.com/task/5627663783034880?logs=test_host#L6132

```
[ RUN      ] ShellTest.ResubmitFrame
../../flutter/shell/common/shell_unittests.cc:1324: Failure
Expected equality of these values:
  1
  external_view_embedder->GetSubmittedFrameCount()
    Which is: 2
[FATAL:flutter/fml/memory/weak_ptr.h(253)] Check failed: (checker_.checker).IsCreationThreadCurrent(). 
[ERROR:flutter/fml/backtrace.cc(116)] Caught signal SIGABRT during program execution.
Frame 0: 0x7f47f47d842a abort
Frame 1: 0x273e7d9 Unknown
Frame 2: 0x273e7b8 fml::LogMessage::~LogMessage()
Frame 3: 0x268f73c fml::WeakPtrFactory<>::CheckThreadSafety()
Frame 4: 0x2683529 fml::WeakPtrFactory<>::~WeakPtrFactory()
Frame 5: 0x2628ca4 flutter::Shell::~Shell()
Frame 6: 0x234546b std::__1::default_delete<>::operator()()
Frame 7: 0x23453ec std::__1::unique_ptr<>::reset()
Frame 8: 0x2342c79 std::__1::unique_ptr<>::~unique_ptr()
Frame 9: 0x246e662 flutter::testing::ShellTest_ResubmitFrame_Test::TestBody()
Frame 10: 0x43953eb testing::internal::HandleSehExceptionsInMethodIfSupported<>()
Frame 11: 0x4385a27 testing::internal::HandleExceptionsInMethodIfSupported<>()
Frame 12: 0x43750d3 testing::Test::Run()
Frame 13: 0x4375794 testing::TestInfo::Run()
Frame 14: 0x4375d9d testing::TestSuite::Run()
Frame 15: 0x437f561 testing::internal::UnitTestImpl::RunAllTests()
Frame 16: 0x439882b testing::internal::HandleSehExceptionsInMethodIfSupported<>()
Frame 17: 0x4387467 testing::internal::HandleExceptionsInMethodIfSupported<>()
Frame 18: 0x437f15f testing::UnitTest::Run()
Frame 19: 0x41af591 RUN_ALL_TESTS()
Frame 20: 0x41af412 main
Frame 21: 0x7f47f47c42e1 __libc_start_main
Frame 22: 0x233176a _start
```

**Comment by zanderso** [comment]
From triage: We should consider disabling these tests.

**Comment by ColdPaleLight** [comment]
I filed a PR to disable these tests: https://github.com/flutter/engine/pull/32059

**Comment by zanderso** [comment]
@iskakaushik is planning to give deflaking these one more try.
