### ISSUE TITLE
[tool_crash] FileSystemException: Creation failed, path = 'C:\Users\gibbo\Documents\FLUTTER PROJS\cheking_vsc_two\lib' (OS Error: The system cannot find the file specified. , errno = 2)

### ISSUE THREAD

**Issue by MaxiFine** [flutter/flutter#95753]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

<details>
<summary>Logs</summary>

```
```

```Oops; flutter has exited unexpectedly: "FileSystemException: Creation failed, path = 'C:\Users\gibbo\Documents\FLUTTER PROJS\cheking_vsc_two\lib' (OS Error: The system cannot find the file specified.
, errno = 2)".
Unable to generate crash report due to secondary error: FileSystemException: Cannot create file, path = 'C:\Users\gibbo\Documents\FLUTTER PROJS\cheking_vsc_two\flutter_01.log' (OS Error: The system cannot find the file specified.
, errno = 2)
Please report a bug at https://github.com/flutter/flutter/issues.

Oops; flutter has exited unexpectedly: "FileSystemException: Creation failed, path = 'C:\Users\gibbo\Documents\FLUTTER PROJS\cheking_vsc_two\lib' (OS Error: The system cannot find the file specified.
, errno = 2)".
Unable to generate crash report due to secondary error: FileSystemException: Cannot create file, path = 'C:\Users\gibbo\Documents\FLUTTER PROJS\cheking_vsc_two\flutter_01.log' (OS Error: The system cannot find the file specified.
, errno = 2)
Please report a bug at https://github.com/flutter/flutter/issues.
Unhandled exception:
ProcessExit: 1
#0      _handleToolError (package:flutter_tools/runner.dart:172:7)
<asynchronous suspension>
#1      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:86:7)
<asynchronous suspension>
exit code 255

```

</details>

**Comment by danagbemava-nc** [comment]
Hi @MaxiFine, thanks for filing the issue. 

Please provide the output of `flutter doctor -v` and `flutter create <project_name> -v`.

Thank you

**Comment by MaxiFine** [comment]
FOR FLUTTER CREATE ERRORS.

[try_for_git1] flutter create --template app --overwrite .
Waiting for another flutter command to release the startup lock...
Creating project ....
  lib\main.dart (created)

Oops; flutter has exited unexpectedly: "FileSystemException: Creation failed, path = 'C:\Users\gibbo\Documents\FLUTTER PROJS\try_for_git1\lib' (OS Error: The system cannot find the file specified.
, errno = 2)".
Unable to generate crash report due to secondary error: FileSystemException: Cannot create file, path = 'C:\Users\gibbo\Documents\FLUTTER PROJS\try_for_git1\flutter_01.log' (OS Error: The system cannot find the file specified.
, errno = 2)
Please report a bug at https://github.com/flutter/flutter/issues.

Oops; flutter has exited unexpectedly: "FileSystemException: Creation failed, path = 'C:\Users\gibbo\Documents\FLUTTER PROJS\try_for_git1\lib' (OS Error: The system cannot find the file specified.
, errno = 2)".
Unable to generate crash report due to secondary error: FileSystemException: Cannot create file, path = 'C:\Users\gibbo\Documents\FLUTTER PROJS\try_for_git1\flutter_01.log' (OS Error: The system cannot find the file specified.
, errno = 2)
Please report a bug at https://github.com/flutter/flutter/issues.
Unhandled exception:
ProcessExit: 1
#0      _handleToolError (package:flutter_tools/runner.dart:172:7)
<asynchronous suspension>
#1      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:86:7)
<asynchronous suspension>
exit code 255

**Comment by danagbemava-nc** [comment]
Please provide the log written to `C:\Users\gibbo\Documents\FLUTTER PROJS\try_for_git1\flutter_01.log`.

Also, do you have this issue with just `flutter create foo`?

**Comment by MaxiFine** [comment]
Yes please, when I use command pallet or the terminal to run flutter
create, it will give me the same error.

**Comment by danagbemava-nc** [comment]
Please provide the logs written to `C:\Users\gibbo\Documents\FLUTTER PROJS\try_for_git1\flutter_01.log` as well as the output of `flutter doctor -v`. 

Thank you

**Comment by MaxiFine** [comment]
> Please provide the logs written to `C:\Users\gibbo\Documents\FLUTTER PROJS\try_for_git1\flutter_01.log` as well as the output of `flutter doctor -v`.
> 
> Thank you


FOR flutter doctor -v


[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19042.1415],
    locale en-US)
    • Flutter version 2.5.3 at C:\Flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\gibbo\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java  
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe       

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.63.2)
    • VS Code at C:\Users\gibbo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.31.20211214

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.110
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 96.0.1054.62

• No issues found!

**Comment by MaxiFine** [comment]
> Please provide the logs written to `C:\Users\gibbo\Documents\FLUTTER PROJS\try_for_git1\flutter_01.log` as well as the output of `flutter doctor -v`.
> 
> Thank you

For the flutter create Output

PS C:\Users\gibbo\Documents\FLUTTER PROJS\try_check1> flutter create maxcheck_2      
Creating project maxcheck_2...
FileSystemException: Creation failed, path = 'C:\Users\gibbo\Documents\FLUTTER
PROJS\try_check1\maxcheck_2' (OS Error: The system cannot find the file specified.   
, errno = 2)
Failed to flutter create at C:\Users\gibbo\Documents\FLUTTER
PROJS\try_check1\maxcheck_2.

**Comment by danagbemava-nc** [comment]
Hi @MaxiFine, can you upgrade to the latest version of flutter stable to see whether or not you still experience this issue? 

Thank you

**Comment by MaxiFine** [comment]
Alright Thank you

**Comment by MaxiFine** [comment]
> Hi @MaxiFine, can you upgrade to the latest version of flutter stable to see whether or not you still experience this issue?
> 
> Thank you

After the upgrade  ( this is the terminal output)


[working_now] flutter create --template app --overwrite .
Downloading package sky_engine...                                   4.4s
Downloading flutter_patched_sdk tools...                            8.3s
Downloading flutter_patched_sdk_product tools...                   10.4s
Downloading windows-x64 tools...                                   86.3s
Downloading windows-x64/font-subset tools...                        3.9s
Creating project ....
  lib\main.dart (created)

Oops; flutter has exited unexpectedly: "FileSystemException: Creation failed, path = 'C:\Users\gibbo\Documents\FLUTTER PROJS\working_now\lib' (OS Error: The system cannot find the file specified.
, errno = 2)".
Unable to generate crash report due to secondary error: FileSystemException: Cannot create file, path = 'C:\Users\gibbo\Documents\FLUTTER PROJS\working_now\flutter_01.log' (OS Error: The system cannot find the file specified.
, errno = 2)
Please report a bug at https://github.com/flutter/flutter/issues.

Oops; flutter has exited unexpectedly: "FileSystemException: Creation failed, path = 'C:\Users\gibbo\Documents\FLUTTER PROJS\working_now\lib' (OS Error: The system cannot find the file specified.
, errno = 2)".
Unable to generate crash report due to secondary error: FileSystemException: Cannot create file, path = 'C:\Users\gibbo\Documents\FLUTTER PROJS\working_now\flutter_01.log' (OS Error: The system cannot find the file specified.
, errno = 2)
Please report a bug at https://github.com/flutter/flutter/issues.
Unhandled exception:
ProcessExit: 1
#0      _handleToolError (package:flutter_tools/runner.dart:172:7)
<asynchronous suspension>
#1      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:85:7)
<asynchronous suspension>
exit code 255

**Comment by danagbemava-nc** [comment]
Hi @MaxiFine, can you try running `flutter create <foo> -v` again in a path that does not contain a space? Your `FLUTTER PROJS` directory has a space in the name. Please try again in a different path. 

Where <foo> is your project name. 

Thank you

**Comment by MaxiFine** [comment]
Hello Sir, please check ou this new error on the output.


[tryin_create] flutter create --template app --overwrite .
Waiting for another flutter command to release the startup lock...
Creating project ....
  lib\main.dart (created)

Oops; flutter has exited unexpectedly: "FileSystemException: Creation
failed, path = 'C:\Users\gibbo\Documents\NotepadFiles\tryin_create\lib' (OS
Error: The system cannot find the file specified.
, errno = 2)".
Unable to generate crash report due to secondary error:
FileSystemException: Cannot create file, path =
'C:\Users\gibbo\Documents\NotepadFiles\tryin_create\flutter_01.log' (OS
Error: The system cannot find the file specified.
, errno = 2)
Please report a bug at https://github.com/flutter/flutter/issues.

Oops; flutter has exited unexpectedly: "FileSystemException: Creation
failed, path = 'C:\Users\gibbo\Documents\NotepadFiles\tryin_create\lib' (OS
Error: The system cannot find the file specified.
, errno = 2)".
Unable to generate crash report due to secondary error:
FileSystemException: Cannot create file, path =
'C:\Users\gibbo\Documents\NotepadFiles\tryin_create\flutter_01.log' (OS
Error: The system cannot find the file specified.
, errno = 2)
Please report a bug at https://github.com/flutter/flutter/issues.
Unhandled exception:
ProcessExit: 1
#0      _handleToolError (package:flutter_tools/runner.dart:172:7)
<asynchronous suspension>
#1      run.<anonymous closure>.<anonymous closure>
(package:flutter_tools/runner.dart:85:7)
<asynchronous suspension>
exit code 255

**Comment by danagbemava-nc** [comment]
Hi @MaxiFine, kindly run 

`flutter create <foo> -v` without the `--overwrite` flag and share the output. 

Also, please provide the log in `C:\Users\gibbo\Documents\NotepadFiles\tryin_create\flutter_01.log`. 

Thank you
