### ISSUE TITLE
different keyboardType cutover, keyborad don't pop up

### ISSUE THREAD

**Issue by xxssd-awsl** [flutter/flutter#95759]
different keyboardType cutover, keyborad don't pop up, such as text and visiblePassword.
this error happens in OPPO K9 Pro, but it not happens in XIAOMI 10.
OPPO K9 Pro and XIAOMI 10 are mobile phone.

code here:
```
import 'package:flutter/material.dart';

class Test extends StatefulWidget {
  @override
  _TestState createState() => _TestState();
}

class _TestState extends State<Test> {

  @override
  void initState() {
    super.initState();
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      resizeToAvoidBottomInset: false,
      backgroundColor: Colors.white,
      appBar: AppBar(
        backgroundColor: Colors.blue,
        elevation: 0,
        iconTheme: IconThemeData(
          color: Colors.white,
        ),
      ),
      body: _bodyTree(),
    );
  }

  Widget _bodyTree() {
    final editText1 = TextField(
      keyboardType: TextInputType.visiblePassword,
    );
    final editText2 = TextField(

    );
    final bodyWidget = Column(
      crossAxisAlignment: CrossAxisAlignment.center,
      children: [
        SizedBox(height: 100),
        editText1,
        editText2,
      ],
    );
    return bodyWidget;
  }
}
```

**Comment by xxssd-awsl** [comment]
when i cutover keyboard in different page, such as use TextInputType.text in search page, use TextInputType.visiblePassword in login page, there are some logs in AS:
`W/IInputConnectionWrapper(14140): getTextBeforeCursor on inactive InputConnection W/IInputConnectionWrapper(14140): getTextAfterCursor on inactive InputConnection W/IInputConnectionWrapper(14140): getTextBeforeCursor on inactive InputConnection W/IInputConnectionWrapper(14140): getTextAfterCursor on inactive InputConnection`

**Comment by xxssd-awsl** [comment]
I found here[68571](https://github.com/flutter/flutter/issues/68571) has same question, and already closed. I had used @hardmen's code, it's useful in single page, but it can't solve the problem of different pages keyboard switch.

cost one day, i explore one solution between different pages keyboard cutover.
1. set all page one textfiled autofocus=true.
2. listen the textfield's focusnode
3. when focusnode.hasfocus=true, delay 0.1s unfocus
4. when focusnode.hasfocus=false, requestFocus
5. all textfield use 68571 @hardmen's code
PS: 3 4 run only once

**Comment by darshankawar** [comment]
@xxssd-awsl 
What flutter version are you using ? The issue you linked was fixed and merged, so upgrade to latest master or latest stable and see if you still get the same behavior or not.

**Comment by xxssd-awsl** [comment]
> @xxssd-awsl What flutter version are you using ? The issue you linked was fixed and merged, so upgrade to latest master or latest stable and see if you still get the same behavior or not.

flutter2.5.3 and flutter2.8.1,  I saw some solution of same issue, it's useful in on page. but it's not useful in different page textfield security keyboard cutover.

**Comment by xxssd-awsl** [comment]
> @xxssd-awsl What flutter version are you using ? The issue you linked was fixed and merged, so upgrade to latest master or latest stable and see if you still get the same behavior or not.

flutter2.5.3 and flutter2.8.1,  I saw some solution of same issue, it's useful in on page. but it's not useful in different page textfield security keyboard cutover.

**Comment by xxssd-awsl** [comment]
懒得写英语了，直接中文，部分机型的解决方案在前面了；但是最近又碰到一个机型出了特殊问题，鸿蒙2.0.1，他的2.0.0都没问题。
解决思路是
1. 判断手机型号，华为的特殊处理
2. 跟踪记录每次页面关闭时的键盘模式，是否是安全键盘
3. 每个页面自动获取焦点的那个输入框首次键盘类型使用上次关闭的键盘类型，然后在第一次失去焦点后使用预定的键盘类型并且局部刷新。

PS: 目前这种方法仅适用于我在开发过程中遇到的机型，感觉软键盘这方面每家都弄了些东西进去，不过可能鸿蒙弄的东西更多吧QWQ，辣鸡flutter
