### ISSUE TITLE
ColorFiltered, BlendMode.srcOut different drawing/

### ISSUE THREAD

**Issue by nt202** [flutter/flutter#95776]
## Steps to Reproduce
```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: Colors.white,
      ),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 100,
      height: 100,
      child: Stack(
        children: [
          Container(
            color: Colors.red,
          ),
          ColorFiltered(
            colorFilter: ColorFilter.mode(
              Colors.blueGrey.withOpacity(0.6),
              BlendMode.srcOut,
            ),
            child: Container(
              decoration: BoxDecoration(
                color: Colors.green,
                borderRadius: BorderRadius.circular(100 / 3.2),
              ),
            ),
          )
        ],
      ),
    );
  }
}
```
Left result - on desktop\mobile.
Right result - on web.

![image](https://user-images.githubusercontent.com/20559489/147348967-7e58bfe7-e61c-4d79-b131-a6160024d649.png)

I expected web result same as desktop\mobile. Is there any solution?

**Comment by darshankawar** [comment]
@nt202 
Can you provide `flutter doctor -v` and rendering mode you are using to run on web ?
Check [this](https://github.com/flutter/flutter/issues/69849) similar issue reported which has been fixed using canvaskit but the issue still remains using html renderer and see if it helps to resolve your issue using canvaskit.

**Comment by nt202** [comment]
@darshankawar Hello, I tried canvaskit. Interestingly html renderer doesn't show widget at all. 

| command                                                  | result                                                                                                          |
|----------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------|
| flutter run -d chrome --web-renderer canvaskit --profile | ![image](https://user-images.githubusercontent.com/20559489/147489591-1e330f2d-9539-4a64-a57d-e5bfdc1c0f3d.png) |
| flutter run -d chrome --web-renderer html --profile      | ![image](https://user-images.githubusercontent.com/20559489/147489772-59fcad9a-cbcf-4c33-ae79-1d9fd5d7c505.png) |
| flutter run -d chrome --web-renderer auto --profile      | ![image](https://user-images.githubusercontent.com/20559489/147489884-571b279a-e971-4350-8193-20ca7e616eee.png) |

**Comment by nt202** [comment]
<details> 
  <summary>flutter doctor -v</summary>
[✓] Flutter (Channel stable, 2.8.1, on Ubuntu 20.04.1 LTS 5.4.0-91-generic, locale en_US.UTF-8)
    • Flutter version 2.8.1 at /home/timur/Programs/flutter-1.17.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (11 days ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/timur/Android/Sdk
    • Platform android-31, build-tools 30.0.2
    • ANDROID_HOME = /home/timur/Android/Sdk
    • ANDROID_SDK_ROOT = /home/timur/Android/Sdk
    • Java binary at: /home/timur/Programs/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 4.2)
    • Android Studio at /home/timur/Programs/android-studio
    • Flutter plugin version 60.1.1
    • Dart plugin version 202.8531
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at /home/timur/Programs/idea-IU-212.5457.46
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5632

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.1 LTS 5.4.0-91-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 96.0.4664.45

• No issues found!
</details>

**Comment by darshankawar** [comment]
@nt202 
I think you are hitting the same issue as mentioned in the linked one, ie, with canvaskit, it works as expected:

<img width="531" alt="Screenshot 2021-12-28 at 11 15 28 AM" src="https://user-images.githubusercontent.com/67046386/147532406-b933ecfa-05fd-428f-8fe7-2659d548519c.png">


But using html rendering, it doesn't:

<img width="521" alt="Screenshot 2021-12-28 at 11 17 06 AM" src="https://user-images.githubusercontent.com/67046386/147532419-3a389f0e-6dfd-42c1-990b-bae70dbb9447.png">

And the same is mentioned in https://github.com/flutter/flutter/issues/69849#issuecomment-744794660 that it is fixed for canvaskit and issue is opened to be fixed for html rendering.
With this, I'll close this in favor of https://github.com/flutter/flutter/issues/69849.
Please follow-up in it for further updates.
Closing this as a duplicate.

**Comment by nt202** [comment]
@darshankawar 
I don't think this is the duplicate, canvaskit draw it wrongly.

Expected result is:
![image](https://user-images.githubusercontent.com/20559489/147541168-5fc248bf-9950-44f4-8bc7-718c20870856.png)

Because it is inside Container.

```
Container(
      width: 100,
      height: 100,
```

**Comment by darshankawar** [comment]
I think I see the same as expected result when I ran the sample on canvaskit:

<img width="732" alt="Screenshot 2021-12-29 at 10 33 28 AM" src="https://user-images.githubusercontent.com/67046386/147629097-a98bade8-5fce-4f37-bfbe-b267445766c3.png">

What exactly is the difference you see between the two ?

**Comment by nt202** [comment]
@darshankawar 
Grey area beyond the square. It spreads everywhere.

**Comment by nt202** [comment]
https://user-images.githubusercontent.com/20559489/147651054-3a3093c6-aee9-4a56-aff6-77751bf017dc.mp4
