### ISSUE TITLE
How can I make only the constrained box scrollable or any other kind of box for the given scenario

### ISSUE THREAD

**Issue by silicon-ninja** [flutter/flutter#95779]
Current State of the problem

**UI:**

<p align="center">

<img width="340" alt="Screenshot 2021-12-24 at 5 50 44 PM" src="https://user-images.githubusercontent.com/48326585/147352194-10228739-23d0-4a24-99bd-3a3e8605d4bb.png" >
</p>

**Code:**

<p align="center">

<img width="340" alt="Screenshot 2021-12-24 at 5 50 44 PM" src="https://user-images.githubusercontent.com/48326585/147352204-e659f255-e723-4c05-b780-334dc3d377d1.png" >
</p>

How can I make only the yellow boxes... and keep the red box positioned as it is or any other alternative 

Thank you.

**Comment by nt4f04uNd** [comment]
Help requests or questions belong to places like reddit or stackoverflow. This issue database is only for specific problems in the framework, if you believe, you found one, please follow the template and provide the information requested there.
