### ISSUE TITLE
Add Flutter to existing iOS app  in  release model launch app  it will blank screen problem

### ISSUE THREAD

**Issue by rooney0502** [flutter/flutter#95772]
I use the flutter module method for development.

Upgrade flutter SDK from 2.5.3 to 2.8.1.

If I use flutter 2.5.3, no matter it is debug or release, there will be no white screen problem.

After upgrading to 2.8.1, debug will not have a white screen problem, but release will have a white screen problem.

The same code, why is there a difference between 2.5.3 and 2.8.1?

My xcode is 13.2.1, how can I solve this problem?

**Comment by rooney0502** [comment]
I try  flutter clean & flutter pub get.
The white screen problem still exist.

**Comment by darshankawar** [comment]
@rooney0502 
Can you provide `flutter run --verbose` in properly formatted text ? Do you see any error in the logs during app launch ?
Also provide a complete minimal reproducible code sample or a sample github repo that we can clone that shows the issue you are facing.
Thanks.

**Comment by rooney0502** [comment]
> @rooney0502 Can you provide `flutter run --verbose` in properly formatted text ? Do you see any error in the logs during app launch ? Also provide a complete minimal reproducible code sample or a sample github repo that we can clone that shows the issue you are facing. Thanks.


I carefully checked the code, because there is a third-party library reporting an error in release mode, but this error is okay in debug mode. So I should check the code carefully, thank you for your reply.
