### ISSUE TITLE
How to upload native debug symbols of flutter app to Play Store?

### ISSUE THREAD

**Issue by gadgetreviews** [flutter/flutter#95778]
Hello,

When I build release of my app, I use following command.

```flutter build appbundle --obfuscate --split-debug-info=debug-info/```

So I generate obfuscated appbundle for android. Flutter generates 

```
app.android-arm64.symbols
app.android-arm.symbols
app.android-x64.symbols
```

files under ```debug-info/``` folder. I create a zip file containing 3 files under ```debug-info/``` folder and I upload this file to App Bundle Explorer at Google Play Developer Console. But Google Play Developer Console shows following error and does not accept this file.
```
The native debug symbols contain an unexpected file: app.android-x64.symbols.
The native debug symbols contain an unexpected file: app.android-arm.symbols.
The native debug symbols contain an unexpected file: app.android-arm64.symbols.
```
How should I upload native debug symbols to Google Play Developer Console?

Thanks

**Comment by darshankawar** [comment]
@gadgetreviews 
I think your case is similar to [this](https://github.com/flutter/flutter/issues/60240) open issue, so please follow-up in it for further updates.
Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.
