### ISSUE TITLE
Help, Platform.enviroment issue of macos release product

### ISSUE THREAD

**Issue by itlwy** [flutter/flutter#95775]
When I run in debug mode,the code `Platform.enviromemt` return to normal.
However, the returned content dose not contain the content of .bash_profile  in release mode.

 % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.4, on Mac OS X 10.15.5 19F101 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[!] Android Studio (version 2020.3)
    ✗ Unable to find bundled Java version.
[✓] IntelliJ IDEA Community Edition (version 2020.3)
[✓] VS Code (version 1.63.2)
[✓] Connected device (3 available)

! Doctor found issues in 1 category.

**Comment by stuartmorgan** [comment]
This is not a bug in Flutter (nor is it actually related to debug vs release). On macOS, the context that normally launches applications, such as when you launch them from Finder, does not load `.bash_profile`. It's only loaded into shell contexts like you get from Terminal.

So in any macOS application, regardless of whether it's created with Flutter or not, you will only see variables set in `.bash_profile` if you are manually launching applications from Terminal (or similar).
