### ISSUE TITLE
How do I add GestureDetector to a OverflowBox subwidget

### ISSUE THREAD

**Issue by yqy159** [flutter/flutter#95777]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@yqy159 
Your question is better suited for support channels like StackOverflow, so please ask the same there.
Closing from here, as this is more of a `how to` question rather than a bug or feature request.
