### ISSUE TITLE
webViewController.evaluateJavascript

### ISSUE THREAD

**Issue by zkenstein** [flutter/flutter#95788]
Is this no longer work? I tried to hide the header, but not working:

 ```
webViewController.evaluateJavascript(
                        "document.getElementsById('gridlove-header-responsive').style.display='none';");
```

## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @zkenstein, I see in your code that you have 

```javascript
document.getElementsById
```

`document.getElementsById` is not defined in javascript, that is why it is not working. 

the actual method you should be calling is 

```javascript
document.getElementById
```

Closing as this is not an actual issue with flutter. 

Thank you
