### ISSUE TITLE
[shared_preferences] iOS KVO can not observe the change of the key with dot in it which flutter shared_preferences produce

### ISSUE THREAD

**Issue by haohongwei** [flutter/flutter#95783]
I'd like to use KVO to observe changes to a value in an flutter shared_preferences. However, I'm finding that it's not working because the key in the shared_preferences that I'd like to observe contains dots(flutter.xxxx).
Can shared_preferences do not use the flutter. as the prefix of the key?

**Comment by darshankawar** [comment]
Closing this as a duplicate of https://github.com/flutter/flutter/issues/19144
