### ISSUE TITLE
Running flutter emulators --create always default to api 27

### ISSUE THREAD

**Issue by doankimhuy-it** [flutter/flutter#95785]
I have other system-images installed, but when running `flutter emulators--create`, it always asks for playstore api 27 image. I think it should find installed images instead of forcing to download another unnecessary image.

**Comment by darshankawar** [comment]
Currently, if we run `flutter emulators --create`, the tool shows below message:

`No suitable Android AVD system images are available. You may need to install these using sdkmanager, for example: sdkmanager "system-images;android-27;google_apis_playstore;x86`.

Is this what you are referring to ?
Also, as the message says to install the api 27 as an example, but you may install api of your choice, like `system-images;android-28` or so on.

**Comment by doankimhuy-it** [comment]
I've installed both `system-images;android-26;google_apis;x86_64` and `system-images;android-1;google_apis;x86_64` but when running the `flutter emulators --create` command, it always shows `No suitable Android AVD system images are available. You may need to install these using sdkmanager, for example: sdkmanager "system-images;android-27;google_apis_playstore;x86`

**Comment by doankimhuy-it** [comment]
I've just downloaded `system-images;android-31;google_apis_playstore;x86_64` and run the command again. It worked. Maybe the command only accept images with playstore API.

**Comment by darshankawar** [comment]
Having a playstore API is recommended since it gives more features to be used in the emulator.
With this, I will close this as non-issue. If you disagree, write in comments and I'll reopen it.
Thanks.
