### ISSUE TITLE
subject not working via Email

### ISSUE THREAD

**Issue by Willi180** [flutter/flutter#95799]
Hello,
`await Share.share(_parseHtmlString(post.content.toString()),
        subject: 'Интересная статья из приложения Мужской журнал');`

as a result vie Email part of text is used as a subject

**Comment by danagbemava-nc** [comment]
Hi @Willi180, 

are you using the [share](https://pub.dev/packages/share) or [share_plus](https://pub.dev/packages/share_plus) package? 

If the former, kindly note that it is no longer maintained and is recommended you use the latter.

If the latter, kindly file this issue over [here](https://github.com/fluttercommunity/plus_plugins/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)

**Comment by Willi180** [comment]
thanks for the answer i will try share plus

**Comment by danagbemava-nc** [comment]
If you do run into an issue with the `share_plus` package, kindly file the issue over on their repo.

Closing from here. 

Thank you
