### ISSUE TITLE
Error using image_picker library: ^0.6.0+10

### ISSUE THREAD

**Issue by wcamposdfbr** [flutter/flutter#95819]
> Bom dia, 
Estou enfrentando o seguinte erro abaixo quando tento implementar uma lista com imagens da galeria de fotos:

Good morning,
I am experiencing the following error below when I try to implement a list with images from the photo gallery:

<img width="960" alt="2021-12-26 (1)" src="https://user-images.githubusercontent.com/96662878/147407685-df4a7656-4013-4f75-befc-018123a78fd8.png">

> Desde já agradeço qualquer dica.

Thank you in advance for any tip.

**Comment by danagbemava-nc** [comment]
Hi @wcamposdfbr, 

You appear to be using an older version of the `image_picker` plugin. The recent version of the package should not have this issue. 

Kindly update to the latest version of `image_picker` and let me know if the issue still exists. 

If you are using an older version of flutter, you will need to update that as well. 

Thank you
