### ISSUE TITLE
[Windows] PlatformException(Clipboard error, Unable to open clipboard, 5, null);

### ISSUE THREAD

**Issue by kirill-21** [flutter/flutter#95817]
After updating flutter to 2.8.1 from 2.5.3 my app started throwing this error

<details>
<summary>logs</summary>

```bash

PlatformException(Clipboard error, Unable to open clipboard, 5, null);
 #0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:155)
 #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167)<asynchronous suspension>
 #2      Clipboard.hasStrings (package:flutter/src/services/clipboard.dart:69)<asynchronous suspension>
 #3      ClipboardStatusNotifier.update (package:flutter/src/widgets/text_selection.dart:1590)<asynchronous suspension>
```
</details>

I do not know how to reproduce it because it happens randomly (usually when app is minimized and not used). I catch this error with FlutterError.onError method;

Flutter version: 2.8.1 from stable channel. Platform: Windows.

**Comment by maheshmnj** [comment]
Hi @kirill-21, Thanks for filing the issue. Is this issue when compiling for Windows Desktop?  Can you please share complete logs of `flutter run -v` and complete output of `flutter doctor -v`?

**Comment by kirill-21** [comment]
> Hi @kirill-21, Thanks for filing the issue. Is this issue when compiling for Windows Desktop? Can you please share complete logs of `flutter run -v` and complete output of `flutter doctor -v`?

This is not the error which occurs during the compilation, it occurs while using the app, randomly(as i've said before more often when app is just minimized).

**Comment by maheshmnj** [comment]
> This is not the error which occurs during the compilation, it occurs while using the app, randomly(as i've said before more often when app is just minimized).

Sorry, I meant did you compile the app for windows Desktop or some other platform? I did get that the issue is a runtime error.  Complete logs would be helpful to investigate further. So, Please share `flutter run -v`. Also, Can you try to reproduce this issue in a newly created app? It looks related to `Clipboard`.

**Comment by kirill-21** [comment]
> > This is not the error which occurs during the compilation, it occurs while using the app, randomly(as i've said before more often when app is just minimized).
> 
> Sorry, I meant did you compile the app for windows Desktop or some other platform? I did get that the issue is a runtime error. Complete logs would be helpful to investigate further. So, Please share `flutter run -v`. Also, Can you try to reproduce this issue in a newly created app? It looks related to `Clipboard`.

Yes, i've built it for Windows platform, i do not how to reproduce it, if i knew i'd share it with you, i do not use clipboard in my app and i have no idea why it even tries to access the clipboard

**Comment by maheshmnj** [comment]
Thanks for the info @kirill-21, Not really sure How we can investigate further without any additional info.

**Comment by kirill-21** [comment]
> Thanks for the info @kirill-21, Not really sure How we can investigate further without any additional info.

You can try looking into the source code of  Clipboard methodchannel

**Comment by gspencergoog** [comment]
cc @justinmc

**Comment by justinmc** [comment]
Here's where that error comes from: https://github.com/flutter/engine/blob/e8bb6866b45b1cbb3ec6422b25480313c9b70fb6/shell/platform/windows/platform_handler_win32.cc#L210

This is all from my hasStrings projects (https://github.com/flutter/engine/pull/27749), which is related to checking the clipboard to see if it's possible to show the "Paste" button.

@stuartmorgan Do you have any idea why ScopedClipboard.Open would fail in situations like this?

**Comment by stuartmorgan** [comment]
`5` is `ERROR_ACCESS_DENIED`. I'm not very familiar with the API, but from some quick searching:
- The docs say "`OpenClipboard` fails if another window has the clipboard open."; it doesn't say what error code that would be, but maybe it's this?
- I found one claim that `OpenClipboard` only works when in the foreground; the docs don't say.

I think the code there should probably be changed to silently drop `ERROR_ACCESS_DENIED` and return false given the observed behavior.

**Comment by kevinxxq** [comment]
Is there any workaround for this issue?  
Is it only from SelectableText? 
It takes place the PC wakes up from sleeping, so I don't know what kind of operation will trigger it.  Thank you.

**Comment by kirill-21** [comment]
@justinmc Hi, not yet fixed. Screenshot from flutter 3.0
![image](https://user-images.githubusercontent.com/63228361/168448345-1c84042a-d341-4e37-9362-f5694a145891.png)

It happens when i press Win+L to go to lock screen

**Comment by kirill-21** [comment]
@maheshmnj can you reopen please?

**Comment by stuartmorgan** [comment]
The food isn't in 3.0. issues are closed when they are fixed on master, not in stable.
