### ISSUE TITLE
Cannot modify TextEditingController text from a listener

### ISSUE THREAD

**Issue by christian-lefty** [flutter/flutter#9582]
The following minimal example crashes the app at head:
(This breaks my workaround described at #9188 )  

PS it used to work at some point but I can't really do binary search since I've merged some API changes.

final controller = new TextEditingController();

    controller.addListener(() {
      String currentText = controller.text;
      debugPrint("This is the current text: $currentText");

      if (currentText == "christian") {
        controller.text = "chris";
      }
    });

    final input = new TextField(
      textAlign: TextAlign.center,
      controller: controller,
    );

    // This method is rerun every time setState is called, for instance
    // as done by the _incrementCounter method above.
    // The Flutter framework has been optimized to make rerunning
    // build methods fast, so that you can just rebuild anything that
    // needs updating rather than having to individually change
    // instances of widgets.
    return new Scaffold(
      appBar: new AppBar(
        // Here we take the value from the MyHomePage object that
        // was created by the App.build method, and use it to set
        // our appbar title.
        title: new Text(widget.title),
      ),
      body: new Center(
        child: input,
      ),
    );

*** Terminating app due to uncaught exception 'NSRangeException', reason: '-[__NSCFString substringWithRange:]: Range {5, 4} out of bounds; string length 5'
Lost connection to device.

**Comment by sethladd** [comment]
Only on iOS?

**Comment by sethladd** [comment]
cc @cbracken

**Comment by sethladd** [comment]
From our user: "Well it's pretty bad cause we can't get past our login screen,"

**Comment by sethladd** [comment]
cc @xster

**Comment by cbracken** [comment]
Thanks for reporting! Should be fixed by flutter/engine#3636, rolled into flutter in #9660.
