### ISSUE TITLE
[Image_picker_web] Unexpected Image name appear on top website

### ISSUE THREAD

**Issue by zeamays2298** [flutter/flutter#95826]
I use image picker to get image to my website , After I select the image, the image file name appears at the top of the web site
i use : 
  image_picker: ^0.8.4+4
  image_picker_for_web: ^2.1.4
![image](https://user-images.githubusercontent.com/96696433/147415585-269e0193-ce52-45e7-92c2-cd2e939f3c86.png)

**Comment by mamuseferha** [comment]
Hi @zeamays2298 
Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you
