### ISSUE TITLE
Text.rich textAlign does not work as expected

### ISSUE THREAD

**Issue by KristianBalaj** [flutter/flutter#95828]
Having the following widget:

```dart
Text.rich(
  TextSpan(
    text: 'Number: ',
    style: TextStyle(fontSize: 20),
    children: [
      TextSpan(
        text: project.catalogNumber,
        style: TextStyle(fontSize: 40),
      )
    ],
  ),
  textAlign: TextAlign.center,
 )
```

Results in following behaviour:

<img width="205" alt="image" src="https://user-images.githubusercontent.com/20045353/147418269-44959f1a-ef47-47fb-95e2-cba6acd69492.png">

<details>
<summary>flutter doctor -v</summary>

```console

[✓] Flutter (Channel beta, 2.9.0-0.1.pre, on macOS 12.0.1 21A559 darwin-x64, locale en-GB)
    • Flutter version 2.9.0-0.1.pre at /Users/kristian/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8f1f9c10f0 (12 days ago), 2021-12-14 13:41:48 -0800
    • Engine revision 234aca678a
    • Dart version 2.16.0 (build 2.16.0-80.1.beta)
    • DevTools version 2.9.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/kristian/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.110

• No issues found!


```
</details>

## Expected behaviour

I would expect the smaller text (the first text span) to be aligned to vertical center of the widget when using the parameter `textAlign: TextAlign.center`. 

## Actual behaviour

The first text span is actually aligned to the vertical bottom instead of the vertical center.

**Comment by jellynoone** [comment]
Hi! `textAlign`actually aligns the text `horizontally` not **vertically**.

There is a related issue which might help: #30159

**Comment by KristianBalaj** [comment]
You are right, this is actually a duplicate of #30159.

**Comment by darshankawar** [comment]
@KristianBalaj 
Since `textAlign` is to align text horizontally, does the solution mentioned in the linked issue, ie, using `WidgetSpan` to align it vertically help to resolve your case ? https://github.com/flutter/flutter/issues/30159#issuecomment-502875830

**Comment by KristianBalaj** [comment]
I've checked and it actually does not work.

The following code:

```dart
Text.rich(
  TextSpan(
    text: '',
    style: TextStyle(fontSize: 20),
    children: [
      WidgetSpan(
        alignment: PlaceholderAlignment.middle,
        child: Text('Number: '),
      ),
      TextSpan(
        text: project.catalogNumber,
        style: TextStyle(fontSize: 40),
      )
    ],
  ),
)
```

<img width="198" alt="image" src="https://user-images.githubusercontent.com/20045353/147462259-67c09b40-8935-4b68-a3f3-5667e4b8c6d7.png">

It is not centered to the middle.

**Comment by darshankawar** [comment]
@KristianBalaj 
That may be due to the difference in the font-size. If you keep same fontSize(20) throughout, the text is centered to the middle as below:

<img width="225" alt="Screenshot 2021-12-28 at 11 29 43 AM" src="https://user-images.githubusercontent.com/67046386/147533193-3c835ec0-f7c8-43d9-a43e-6e334e084810.png">

```
void main() {
  runApp(MaterialApp(
    home: Scaffold(
      body: Center(
        child: Text.rich(
          TextSpan(
              text: '',
              style: TextStyle(fontSize: 20, color: Colors.black),
              children: <InlineSpan>[
             //   TextSpan(text: 'hello'),
                WidgetSpan(
                  alignment: PlaceholderAlignment.middle,
                  child: Text(
                      'Number:',
                      style: TextStyle(fontSize: 20, color: Colors.black)
                  ),
                ),
                TextSpan(text: ' doctor',style: TextStyle(fontSize: 20)),
              ]
          ),
        )
      ),
    ),
  ));
}
```

**Comment by KristianBalaj** [comment]
Agreed, however this is not expected, I would expect it to center vertically.

Although, this is a minor issue and I don't see a use case where this couldn't be replaced by a row of texts 🤔

So we could maybe close this without resolution if you don't come up with any use case where the row cannot be used.

**Comment by jellynoone** [comment]
Hi, @KristianBalaj . I've just tested this out and it does work. For some reason the large text widget has to be wrapped in the `WidgetSpan`. Could you try out the bellow code?

```dart
Text.rich(
  TextSpan(
    style: TextStyle(fontSize: 20),
    children: [
      TextSpan(text: 'Number: '),
      WidgetSpan(
        alignment: PlaceholderAlignment.middle,
        child: Text(project.catalogNumber, style: TextStyle(fontSize: 40)),
      ),
    ],
  ),
);
```

**Comment by darshankawar** [comment]
See if above helps to answer your issue @KristianBalaj
