### ISSUE TITLE
The text in blockquote overlaps

### ISSUE THREAD

**Issue by 2372281891** [flutter/flutter#95824]
This happens in certain mobile browsers, such as **via** browser

**Comment by danagbemava-nc** [comment]
Hi @2372281891, 

Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Thank you

**Comment by 2372281891** [comment]
I'm very sorry. I'm on a business trip now. If you can, please go to the Google store to download the via browser and try to load the deployed Flutter web project

**Comment by danagbemava-nc** [comment]
A code sample will still be needed to figure out why that happens. 

You can provide that and whatever information is relevant whenever you're done with your trip.

Thank you.

**Comment by 2372281891** [comment]
Like this



---Original---
From: "Daniel ***@***.***&gt;
Date: Mon, Jan 3, 2022 14:07 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [flutter/flutter] The text in blockquote overlaps (Issue #95824)




 
A code sample will still be needed to figure out why that happens.
 
You can provide that and whatever information is relevant whenever you're done with your trip.
 
Thank you.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by danagbemava-nc** [comment]
Hi @2372281891, I'm not sure what I should be looking at. 

If you shared an attachment in the email response, kindly note that it won't appear in this thread. It is always better if you actually respond to the thread instead of replying via email. 

Thank you
