### ISSUE TITLE
Deeplink doesn't work when the app is killed or inactive in iOS

### ISSUE THREAD

**Issue by munyaaa** [flutter/flutter#95832]
Hi,
I have problem with the deeplink in iOS.  The deeplink won't open the correct page only if the app is killed or inactive (only the initial page/screen).  But it works perfectly on the app that run in the background or the active one.
After debugging, I found that `didFinishLaunchingWithOptions` in iOS file is not called when the app is killed.

iOS emulator version: iOS 15.2
Flutter version: 2.2.3

Any solution?

Thanks.

**Comment by darshankawar** [comment]
@munyaaa 
You are on older version of stable. Please upgrade to latest (2.8.1) and try again to see if it works.
If not, please provide a [complete minimal code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with steps to replicate that we can use to verify this behavior.
Thanks.

**Comment by munyaaa** [comment]
@darshankawar 
Inside `AppDelegate.swift`, after did the `NSLog` the `didFinishLaunchingWithOptions` is not called.
```swift
override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
) -> Bool {
    flutterViewController = window.rootViewController as? FlutterViewController
    deepLinkChannelService.setUpDeepLinkChannel(view: flutterViewController)
    handleDeeplinkUtil.handleDeeplinkWhenAppIsKilled(launchOptions, deepLinkChannelService: deepLinkChannelService)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
}
```
This the function inside `HandleDeeplinkUtil`
```swift
func handleDeeplinkWhenAppIsKilled(_ launchOptions: [UIApplication.LaunchOptionsKey: Any]?, deepLinkChannelService: DeepLinkChannelService) {
    if let deepLink = remoteNotification[DeepLinkConstants.DEEP_LINK_KEY] as? String {
    let isDeepLinkOpened = deepLinkChannelService.onDeepLinkReceived(deepLinkUrl: deepLink)
}
```

**Comment by darshankawar** [comment]
> please provide a [complete minimal code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with steps to replicate

@munyaaa
