### ISSUE TITLE
Increase the priority handling of WidgetsBindingObserver

### ISSUE THREAD

**Issue by ismanong** [flutter/flutter#95834]
First of all I am not sure if the feature proposed below is necessary, if it is not, please tell how to understand this issue. Because I'm sure I'm not as well thought out as the official Flutter.

Consider whether to increase the priority handling of WidgetsBindingObserver?

Features that encountered this issue.
Some widgets based on [OverlayEntry] need to intercept the return key, but for cleanliness, only want to subscribe to addObserver(this) only after initialization, and call removeObserver(this) to clear the instance when done.

Description.
Some are subscribed right after the program starts: the
Order of processing: [_MyAppState] -> [_WidgetsAppState], .... and finally to [RootBackButtonDispatcher].

Some are subscribed at an indeterminate time in the runtime, such as some CustomClasses.
Processing order: [_MyAppState] -> [_WidgetsAppState], .... [RootBackButtonDispatcher] -> [CustomClasses].
If any of the didPopRoute() before [CustomClasses] is processed as true, it will end and CustomClasses will not receive the callback properly.

**Comment by darshankawar** [comment]
@ismanong 
In order to properly address this issue, please provide a minimal code sample that highlights the case you mentioned along with expected vs actual result, so that'll help to verify.

**Comment by ismanong** [comment]
@darshankawar 
Example：[https://github.com/ismanong/issue_widgets_binding_observer](url)

**Comment by darshankawar** [comment]
Running your code sample shows me below:

<img width="327" alt="Screenshot 2021-12-30 at 10 47 50 AM" src="https://user-images.githubusercontent.com/67046386/147723940-504c069b-dd73-421d-9af5-a71cd617fa84.png">

Is your issue related to, when you press Android back button, it should be interpreted / intercepted to perform a specific operation ?
If so, have you looked at [WillPopScope](https://api.flutter.dev/flutter/widgets/WillPopScope-class.html) or [back_button_interceptor](https://pub.dev/packages/back_button_interceptor) plugin and check if it helps to address your case ?

**Comment by ismanong** [comment]
@darshankawar  [back_button_interceptor](https://pub.dev/packages/back_button_interceptor) can meet my needs

![image](https://user-images.githubusercontent.com/13862699/147812758-31ba7151-5677-494b-b228-9e271e910372.png)
After using
3 seconds before, click the return button, the Flutter default operation is executed.
After 3 seconds, binding a specific intercept action, clicking the return button, you can receive the intercept and callback correctly.

Thank you very much for your help! But is this action can be built into Flutter.

**Comment by darshankawar** [comment]
Thanks for confirming, but since not feature and functionality can be implemented in the framework, hence there are such helpful packages that can be used to suit the need.
Closing this as resolved based on your comment above.
