### ISSUE TITLE
fix documentation for NestedScrollView

### ISSUE THREAD

**Issue by subzero911** [flutter/flutter#95845]
https://api.flutter.dev/flutter/widgets/NestedScrollView-class.html

code examples have disappeared

![image](https://user-images.githubusercontent.com/12999702/147455775-1d1ecb2c-0812-4b83-9831-60f15dd8a7ef.png)

**Comment by domesticmouse** [comment]
What is showing up in the console?

**Comment by danagbemava-nc** [comment]
This is the only error I see in the console

![Screenshot 2021-12-27 at 20 18 51](https://user-images.githubusercontent.com/88313112/147504582-65011908-344a-40e4-8c2c-68919b3d2ac9.png)

**Comment by domesticmouse** [comment]
What is the full url of the resource that is erroring out with the 404? It should be visible in the network trace tab of chrome dev tools.

**Comment by danagbemava-nc** [comment]
It seems like it's the cupertino_icons 

https://flutter.github.io/cupertino_icons/css/icons.css

![Screenshot 2021-12-27 at 20 56 16](https://user-images.githubusercontent.com/88313112/147506698-fb0d5534-7a2d-494c-af1c-f176a2f84d89.png)

**Comment by nt4f04uNd** [comment]
Looks like a duplicate of https://github.com/flutter/flutter/issues/94978

@subzero911 you can use https://master-api.flutter.dev/flutter/widgets/NestedScrollView-class.html in the meantime, which renders master branch docs
