### ISSUE TITLE
According to dart SDK native_symbol_xx.cc, abi::__cxa_demangle will it cause slow compilation?

### ISSUE THREAD

**Issue by liliangwor** [flutter/flutter#95849]
native_symbol_xx ->LookupSymbolName.Because there are too many symbols in ios/andriod dylib, it will slow compilation??

**Comment by darshankawar** [comment]
@liliangwor 
Can you elaborate on what are you trying to report ?

**Comment by liliangwor** [comment]
sorry My English is very weak....I just read the SDK   but not verify it in practice..I think dart is finally converted to C + +, such as dart_ Handle, object and so on, then the dart SDK finds the IOS / Android system API through lookupsymbolname to call.it is right??

**Comment by darshankawar** [comment]
@liliangwor 
Thanks. Your question is better suited for support channels like Stackoverflow, so please ask the same there.
Closing from here, as this platfrom is used to track bugs and feature requests.

**Comment by liliangwor** [comment]
Thank you, my dear friend
