### ISSUE TITLE
 Null check operator used on a null value; #0      State.context (package:flutter/src/widgets/framework.dart:916)#1      _TooltipState._createNewEntry

### ISSUE THREAD

**Issue by kirill-21** [flutter/flutter#95851]
Unfortunately i can not give you any reproducible code because this error is caught by runZonedGuarded(error; stackTrace) method and reported to application's server. I've tried to recreate it myself but i have no idea how it appears. I notice these error reports since flutter 2.2.3 
```
Null check operator used on a null value; 
#0      State.context (package:flutter/src/widgets/framework.dart:916)
#1      _TooltipState._createNewEntry (package:flutter/src/material/tooltip.dart:535)
#2      _TooltipState.ensureTooltipVisible (package:flutter/src/material/tooltip.dart:517)
#3      _rootRun (dart:async/zone.dart:1420)
#4      _CustomZone.run (dart:async/zone.dart:1328)
#5      _CustomZone.runGuarded (dart:async/zone.dart:1236)
#6      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276)
#7      _rootRun (dart:async/zone.dart:1428)
#8      _CustomZone.run (dart:async/zone.dart:1328)
#9      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1260)
#10     SemanticsConfiguration._addArgumentlessAction.<anonymous closure> (package:flutter/src/semantics/semantics.dart:3249)
#11     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395)
#12     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192)
```
This is the way i make tooltip visible:
```
final GlobalKey<State<Tooltip>> _toolTipKey = GlobalKey<State<Tooltip>>();
final dynamic tooltip = _toolTipKey.currentState;
if(mounted && _toolTipKey.currentState?.mounted != null) {
  tooltip?.ensureTooltipVisible();
}
```

**Platform: Windows, Flutter version: 2.8.1 from stable channel**

**Comment by darshankawar** [comment]
> Null check operator used on a null value; 
> #0      State.context (package:flutter/src/widgets/framework.dart:916)
> #1      _TooltipState._createNewEntry (package:flutter/src/material/tooltip.dart:535)
> #2      _TooltipState.ensureTooltipVisible (package:flutter/src/material/tooltip.dart:517)

It seems to me that the `Tooltip` widget is destroyed before we create the entry and forward the controller.
It seemed to have been fixed here https://github.com/flutter/flutter/pull/57244 last year.
Can you possibly try the same on master and see if it replicates on it too ?

**Comment by kirill-21** [comment]
> > Null check operator used on a null value;
> > #0      State.context (package:flutter/src/widgets/framework.dart:916)
> > #1      _TooltipState._createNewEntry (package:flutter/src/material/tooltip.dart:535)
> > #2      _TooltipState.ensureTooltipVisible (package:flutter/src/material/tooltip.dart:517)
> 
> It seems to me that the `Tooltip` widget is destroyed before we create the entry and forward the controller. It seemed to have been fixed here #57244 last year. Can you possibly try the same on master and see if it replicates on it too ?

Unfortunately I myself can not reproduce this issue on my pc but according to logs from Flutter.onError and runZonedGuarder users of my app face this issue from time to time. By the way if it was fixed a year ago then why isn't it on a stable channel yet?

**Comment by darshankawar** [comment]
> By the way if it was fixed a year ago then why isn't it on a stable channel yet?

I am sure it must have made it to stable, but it was just to confirm if it replicates on master too.  Is it not coming from debug and possibly from production ?

Is there a way for you to find a pattern in debug mode, something like below and see if it possibly replicates ?

`Mouse over the widget -> tooltip starts waiting to appear -> select the widget before tooltip appears -> widget is rebuilt to change color -> tooltip error is thrown because context is null.`

**Comment by kirill-21** [comment]
> > By the way if it was fixed a year ago then why isn't it on a stable channel yet?
> 
> I am sure it must have made it to stable, but it was just to confirm if it replicates on master too. Is it not coming from debug and possibly from production ?
> 
> Is there a way for you to find a pattern in debug mode, something like below and see if it possibly replicates ?
> 
> `Mouse over the widget -> tooltip starts waiting to appear -> select the widget before tooltip appears -> widget is rebuilt to change color -> tooltip error is thrown because context is null.`

I've been developing my app since April(for 8 month) and can not reproduce this issue on my pc, if i could - i would record a gif or video with explanation how i did it

**Comment by darshankawar** [comment]
Labeling it for further investigation, as there isn't a reproducible use case to verify.

**Comment by kaciula** [comment]
@darshankawar  I am also getting this error from my users in crash reports. This happens on iPhone 11 in production and I cannot reproduce it.

I am building an OverlayEntry over my page, the user closes the overlay and immediately navigates back to a new page. And this is the moment when the crash occurs.

`0  ???                            0x0 State.context + 916 (framework.dart:916)

1  ???                            0x0 _HomeScreenState._buildConfirmEmailOverlayEntry.<fn>.<fn>.<fn> + 312 (home_screen.dart:312)
2  ???                            0x0 _InkResponseState._handleTap + 989 (ink_well.dart:989)
3  ???                            0x0 GestureRecognizer.invokeCallback + 193 (recognizer.dart:193)
4  ???                            0x0 TapGestureRecognizer.handleTapUp + 608 (tap.dart:608)
5  ???                            0x0 BaseTapGestureRecognizer._checkUp + 296 (tap.dart:296)
6  ???                            0x0 BaseTapGestureRecognizer.acceptGesture + 267 (tap.dart:267)
7  ???                            0x0 GestureArenaManager.sweep + 157 (arena.dart:157)
8  ???                            0x0 GestureBinding.handleEvent + 444 (binding.dart:444)
9  ???                            0x0 GestureBinding.dispatchEvent + 420 (binding.dart:420)
10 ???                            0x0 RendererBinding.dispatchEvent + 278 (binding.dart:278)
11 ???                            0x0 GestureBinding._handlePointerEventImmediately + 374 (binding.dart:374)
12 ???                            0x0 GestureBinding.handlePointerEvent + 338 (binding.dart:338)
13 ???                            0x0 GestureBinding._flushPointerEventQueue + 296 (binding.dart:296)
14 ???                            0x0 GestureBinding._handlePointerDataPacket + 279 (binding.dart:279)`

**Comment by mkobuolys** [comment]
I am also getting this error:
```
Null check operator used on a null value
#0      State.context (package:flutter/src/widgets/framework.dart:916)
#1      _AuthenticatedPagesWrapperState._handleNotificationMessage (package:example/navigation/pages/authenticated_pages_wrapper.dart:100)
#2      _rootRunUnary (dart:async/zone.dart:1436)
#3      _CustomZone.runUnary (dart:async/zone.dart:1335)
#4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#6      _DelayedData.perform (dart:async/stream_impl.dart:591)
#7      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706)
#8      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663)
#9      _rootRun (dart:async/zone.dart:1420)
#10     _CustomZone.run (dart:async/zone.dart:1328)
#11     _CustomZone.runGuarded (dart:async/zone.dart:1236)
#12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276)
#13     _rootRun (dart:async/zone.dart:1428)
#14     _CustomZone.run (dart:async/zone.dart:1328)
#15     _CustomZone.runGuarded (dart:async/zone.dart:1236)
#16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)
```

It happens only in production code, I was not able to reproduce the issue locally. I this case, the `_AuthenticatedPagesWrapperState._handleNotificationMessage` method uses context for navigation. Also, this function is triggered by the push notification, the app is freshly opened.

Flutter Doctor:
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
