### ISSUE TITLE
On Long Press to text filed and textform filed

### ISSUE THREAD

**Issue by Manishmg3994** [flutter/flutter#95871]
_Text Field_ widget should have a new property **onlongpress**  to fullfill the need with  **onTap** or other function because I was Trying to integrate permission handler ontap as decided it works and fullfill its duty but during this time there to my code I found a bypass as while long pressing it does not call ontap functionality and it makes text Field to copy or paste and this Longpressing  makes my code a total waste of time

**Comment by darshankawar** [comment]
@Manishmg3994 
Have you tried wrapping TextField or TextFormField with `GestureDetector` which exposes `onLongPress` method and see if it helps to achieve your use case ?
