### ISSUE TITLE
webview_flutter javascript channel can't communicate in release mode

### ISSUE THREAD

**Issue by Md-Abdul-Halim-Rafi** [flutter/flutter#95883]
I am using `webview_flutter` with version **3.0.0** in my app. I have heavy usage of two-way communication between flutter and javascript. Everything works on debug mode nicely. But, after I build the APK started to get some errors in the javascript channel. I tried with `flutter run --release` and got the same error.

In my web application (ReactJs), I am using channels in this way:

**_index.html_**

```
<div id="root">
    <script>
        function sendToFlutter(message) {
            if (flutterChannel) {
                flutterChannel.postMessage(message);
            }
        }
    </script>
</div>
```

calling is from React component like this:

```
window.sendToFlutter("hello-world");
```

My Webview setup from Flutter end:

```
 Completer<WebViewController> webViewCompleter = Completer<WebViewController>();
```

```
WebView(
    debuggingEnabled: false,
    initialUrl: "https://example.com",
    javascriptMode: JavascriptMode.unrestricted,
    onWebViewCreated: (WebViewController webViewController) {
        webViewCompleter.complete(webViewController);
    },
    javascriptChannels: <JavascriptChannel>{
        JavascriptChannel(
        name: "flutterChannel",
        onMessageReceived: (JavascriptMessage message) {

          if (message.message == "hello-world") {
            // Do something
          }
        })
    },
    navigationDelegate: (NavigationRequest request) {
        if (request.url.startsWith('https://www.youtube.com/')) {
            return NavigationDecision.prevent;
        }
        
        return NavigationDecision.navigate;
    },
    gestureNavigationEnabled: true,
    zoomEnabled: false,
    userAgent: Platform.isAndroid ? kAndroidUserAgent : kIosUserAgent,
);
```

When I call the channel from ReactJs, then I am getting this error:

```
TypeError: flutterChannel.postMessage is not a function
```

**Comment by danagbemava-nc** [comment]
Hi @... 

Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Please also provide the contents of your `pubspec.yaml`

Thank you

**Comment by danagbemava-nc** [comment]
Hi @Md-Abdul-Halim-Rafi,

Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Please also provide the contents of your `pubspec.yaml`

Thank you

**Comment by andraskende** [comment]
I have the same issue, javascriptChannels only works on local

might be related to #92548 ??

debug works local phone: "flutter run"
release app doesn't work: "flutter build appbundle"

    andras@andras nameday % flutter doctor -v
    [✓] Flutter (Channel stable, 2.8.1, on macOS 11.6.2 20G314 darwin-x64, locale en-US)
        • Flutter version 2.8.1 at /Users/andras/development/flutter
        • Upstream repository https://github.com/flutter/flutter.git
        • Framework revision 77d935af4d (5 weeks ago), 2021-12-16 08:37:33 -0800
        • Engine revision 890a5fca2e
        • Dart version 2.15.1

    [✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
        • Android SDK at /Users/andras/Library/Android/sdk
        • Platform android-31, build-tools 31.0.0
        • ANDROID_HOME = /Users/andras/Library/Android/sdk
        • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
        • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
        • All Android licenses accepted.

    [✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
        • Xcode at /Applications/Xcode.app/Contents/Developer
        • CocoaPods version 1.11.2

    [✓] Chrome - develop for the web
        • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

    [✓] Android Studio (version 2020.3)
        • Android Studio at /Applications/Android Studio.app/Contents
        • Flutter plugin can be installed from:
        🔨 https://plugins.jetbrains.com/plugin/9212-flutter
        • Dart plugin can be installed from:
        🔨 https://plugins.jetbrains.com/plugin/6351-dart
        • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

    [✓] VS Code (version 1.63.2)
        • VS Code at /Applications/Visual Studio Code.app/Contents
        • Flutter extension version 3.32.0

    [✓] Connected device (2 available)
        • Pixel 4a 5G (mobile) • 0C021JECB07125 • android-arm64  • Android 12 (API 31)
        • Chrome (web)         • chrome         • web-javascript • Google Chrome 97.0.4692.99

    • No issues found!


flutter run --verbose 
https://gist.github.com/andraskende/97f555e833fa94eadce4c11380bafd44


  import 'dart:io' show Platform;
  import 'package:flutter/material.dart';
  import 'package:font_awesome_flutter/font_awesome_flutter.dart';
  import 'package:provider/provider.dart';
  import 'package:webview_flutter/webview_flutter.dart';
  import 'package:nameday/widgets/calendaradd.dart';
  import '../services/app.dart';
  import '../services/theme.dart';

  class WebsiteView extends StatefulWidget {
    final String title;
    const WebsiteView({Key? key, required this.title}) : super(key: key);

    @override
    WebsiteViewState createState() => WebsiteViewState();
  }

  class WebsiteViewState extends State<WebsiteView> {
    String title = 'Nameday';
    String _platform = 'android';
    bool canback = false;
    bool canforward = false;

    @override
    void initState() {
      super.initState();
      title = widget.title;
      if (Platform.isIOS) {
        _platform = 'ios';
      }
      // Enable hybrid composition.
      if (Platform.isAndroid) WebView.platform = SurfaceAndroidWebView();
    }

    late WebViewController _controller;

    back() async {
      if (await _controller.canGoBack()) {
        await _controller.goBack();
      }
    }

    forward() async {
      if (await _controller.canGoForward()) {
        await _controller.goForward();
      }
    }

    bf() async {
      if (await _controller.canGoBack()) {
        setState(() {
          canback = true;
        });
      } else {
        setState(() {
          canback = false;
        });
      }
      if (await _controller.canGoForward()) {
        setState(() {
          canforward = true;
        });
      } else {
        setState(() {
          canforward = false;
        });
      }
    }

    @override
    Widget build(BuildContext context) {
      var providerApp = Provider.of<AppProvider>(context);
      var providerTheme = Provider.of<ThemeProvider>(context);

      return Scaffold(
        appBar: AppBar(
          leading: Padding(
            padding: const EdgeInsets.all(8.0),
            child: Image.asset('lib/assets/nameday.png'),
          ),
          title: Text(title),
          actions: <Widget>[
            canback
                ? IconButton(
                    onPressed: back,
                    icon: const Icon(FontAwesomeIcons.arrowLeft),
                  )
                : Container(),
            canforward
                ? IconButton(
                    onPressed: forward,
                    icon: const Icon(FontAwesomeIcons.arrowRight),
                  )
                : Container(),
            const SizedBox(width: 10),
          ],
        ),
        body: WebView(
          key: Key(providerApp.page),
          onWebViewCreated: (WebViewController webViewController) {
            _controller = webViewController;
            bf();
          },
          javascriptChannels: {
            JavascriptChannel(
              name: 'title',
              onMessageReceived: (JavascriptMessage message) {
                setState(() {
                  title = message.message;
                });
                bf();
              },
            ),
            JavascriptChannel(
              name: 'nameday',
              onMessageReceived: (JavascriptMessage message) {
                calAdd2(message.message);
              },
            ),
          },
          initialUrl: providerTheme.getDark()
              ? 'https://www.nameday.com/webview/' +
                  providerApp.page +
                  'theme=theme1&platform=' +
                  _platform
              : 'https://www.nameday.com/webview/' +
                  providerApp.page +
                  'theme=theme2&platform=' +
                  _platform,
          javascriptMode: JavascriptMode.unrestricted,
        ),
      );
    }
  }
