### ISSUE TITLE
Can't build the app after importing image_picker package

### ISSUE THREAD

**Issue by Alphanad** [flutter/flutter#95899]
## Steps to Reproduce

1. Import image_picker package to your flutter project.
2. Run pub get to get package (done successfuly).
3. Then run the app to build it and you'll face with the error!!!

## Logs

<details>
<summary>Logs</summary>

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find exifinterface-1.3.0.aar (androidx.exifinterface:exifinterface:1.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/exifinterface/exifinterface/1.3.0/exifinterface-1.3.0.aar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
Exception: Gradle task assembleDebug failed with exit code 1

[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19041.1348], locale en-US)
    • Flutter version 2.8.1 at F:\Programs\Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (12 days ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at F:\Programs\Android\sdk
    • Platform android-31, build-tools 30.0.2
    • ANDROID_HOME = F:\Programs\Android\sdk
    • Java binary at: F:\Programs\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.2)
    • Android Studio at F:\Programs\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] Connected device (3 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64    • Android 7.1.1 (API 25) (emulator)
    • Chrome (web)                          • chrome        • web-javascript • Google Chrome 96.0.4664.93
    • Edge (web)                            • edge          • web-javascript • Microsoft Edge 95.0.1020.44

• No issues found!

</details>

**Comment by danagbemava-nc** [comment]
Hi @Alphanad, please provide the complete output of `flutter run -v`. 

The output is likely to be huge, so please put it into a `.txt` file and attach it here. 

Thank you

**Comment by Alphanad** [comment]
Hey @danagbemava-nc, thanks for your help! i added log.txt . check in attached file.
[Uploading log.txt…]()

**Comment by Alphanad** [comment]
Hey @danagbemava-nc, thanks for your help! i added log.txt . check in attached file.
[log.txt](https://github.com/flutter/flutter/files/7785795/log.txt)
