### ISSUE TITLE
Error at flutter/ephemeral/.plugin_symlinks/quick_scanner/windows/CMakeLists.txt:13

### ISSUE THREAD

**Issue by aexces** [flutter/flutter#95898]
Launching lib\main.dart on Windows in debug mode...
lib\main.dart:1
NUGET.EXE not found.
CMake Error at flutter/ephemeral/.plugin_symlinks/quick_scanner/windows/CMakeLists.txt:13 (message):
  Please install this executable, and run CMake again.

Exception: Unable to generate build files
Exited (sigterm)

**Comment by maheshmnj** [comment]
HI @aexces, Thanks for filing the issue. Please share your  `CMakeLists.txt` file, `flutter doctor -v`, and steps to reproduce the issue.

Thanks

**Comment by stuartmorgan** [comment]
You are using a third-party plugin that has a dependency that isn't part of the standard tools required by Flutter (NuGet). If that plugin doesn't tell you in its README that you need to install that extra dependency, you should report that to the developer of the plugin.

Closing as this is not an issue with Flutter.
