### ISSUE TITLE
[Feature request] extending theme of TextButton

### ISSUE THREAD

**Issue by KristianBalaj** [flutter/flutter#95897]
There is no way to modify theme of the TextButton in a way where the TextButton will look like a link in a text.
This is a frequent use case mostly for web platforms where we want to use links in a text.

## Expected behaviour:
The following image shows a paragraph from the Flutter documentation. There are 2 links in the paragraph in a blue color. These buttons/links behave in a way when hovered they get brighter.

<img width="756" alt="image" src="https://user-images.githubusercontent.com/20045353/147551286-7c8d41f1-be23-4366-94b8-14455082e056.png">

Also, I'm not able to control behaviour of the textStyle when hovered/clicked etc. 
I would like to make the text underlined when hovered and clicked, too.

Also, I want to be able to disable background effects of the TextButton by a single flag and control only the textStyles.

## Possible solutions:

1. Add another type of button
2. Add theming options to the TextButton

**Comment by danagbemava-nc** [comment]
Hi @KristianBalaj, 

The `TextButton` has a style property which is of type `ButtonStyle` and most of the styles defined in there use `MaterialStateProperty` which has documentation https://api.flutter.dev/flutter/material/MaterialStateProperty-class.html. 

Does that not suffice for your use case?

**Comment by KristianBalaj** [comment]
Ouch you are right.
I was looking only in the  TextButton.styleFrom() method where it is not possible.

However , it looks to be possible with raw ButtonStyle.

**Comment by danagbemava-nc** [comment]
Given that this is already possible based on your comment above, I feel it is safe to close this issue. 

If you disagree, kindly leave a comment below and I will reopen. 

Thank you
