### ISSUE TITLE
In flutter web Openstreetmap images is not rendering

### ISSUE THREAD

**Issue by Abhishek8-198** [flutter/flutter#95902]
<img width="730" alt="image" src="https://user-images.githubusercontent.com/53220912/147569390-a7d571c4-7905-4db0-b75c-0b9a29c43e95.png">

```console
Failed to load network image.
Image URL: https://www.openstreetmap.org/?mlat=24.9661&mlon=85.0031#map=17/28.63260/77.23562.png
Trying to load an image from another domain? Find answers at:
https://flutter.dev/docs/development/platform-integration/web-images
```

<details>
<summary> flutter doctor -v</summary>

```console
[√] Flutter (Channel unknown, 2.2.3, on Microsoft Windows [Version 10.0.19043.1415], locale en-IN)
    • Flutter version 2.2.3 at C:\software\new-flutter\flutter_windows_2.5.3-stable\flutter
    • Framework revision f4abaa0735 (6 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\abhis\AppData\Local\Android\sdk
    • Platform android-32, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.110
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 96.0.1054.62

• No issues found!
```
</details>

**Comment by danagbemava-nc** [comment]
Hi @Abhishek8-198, you appear to be on an older version of flutter. 

Kindly upgrade to the latest version of flutter.

If you still experience this issue after the upgrade, kindly provide the updated `flutter doctor -v` as well as a complete minimal reproducible code sample and the content of your `pubspec.yaml` and the full output of `flutter run -v`, the output is likely to be huge so you can put it into a `.txt` file an attach it here. 

Thank you

**Comment by Abhishek8-198** [comment]
I am getting same issue.
My current flutter version 2.5.3


Flutter doctor -v
[√] Flutter (Channel unknown, 2.5.3, on Microsoft Windows [Version 10.0.19043.1415], locale en-IN)
    • Flutter version 2.5.3 at C:\software\new-flutter\flutter_windows_2.5.3-stable\flutter
    • Upstream repository unknown
    • Framework revision 18116933e7 (3 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\abhis\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.110
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 96.0.1054.62

! Doctor found issues in 1 category.


Flutter run -v
C:\Users\abhis\AndroidStudioProjects\web-mygraam>flutter run -v
[  +66 ms] executing: [C:\software\new-flutter\flutter_windows_2.5.3-stable\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +293 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 18116933e77adc82f80866c928266a5b4f1ed645
[        ] executing: [C:\software\new-flutter\flutter_windows_2.5.3-stable\flutter/] git tag --points-at 18116933e77adc82f80866c928266a5b4f1ed645
[  +52 ms] Exit code 0 from: git tag --points-at 18116933e77adc82f80866c928266a5b4f1ed645
[   +1 ms] 2.5.3
[   +7 ms] executing: [C:\software\new-flutter\flutter_windows_2.5.3-stable\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +30 ms] Exit code 128 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] fatal: HEAD does not point to a branch
[  +52 ms] executing: [C:\software\new-flutter\flutter_windows_2.5.3-stable\flutter/] git rev-parse --abbrev-ref HEAD
[  +29 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] HEAD
[  +42 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +7 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +61 ms] executing: C:\Users\abhis\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +38 ms] List of devices attached
[   +6 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +78 ms] Multiple devices found:
[  +23 ms] Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.110
[   +1 ms] Edge (web)   • edge   • web-javascript • Microsoft Edge 96.0.1054.62
[   +1 ms] [1]: Chrome (chrome)
[        ] [2]: Edge (edge)


My pubspec.ymal

name: mygraam
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  pin_entry_text_field: ^0.1.4
  dio: 3.0.10
  graphql_flutter: ^4.0.1
  shared_preferences: ^0.5.12+4
  get_it: ^5.0.6
  ars_progress_dialog: ^0.1.2
  shimmer: ^1.1.2
  graphql: ^4.0.1
  intl: 0.16.1
  rxdart: 0.24.1
  fluttertoast: ^8.0.8
  cached_network_image: ^2.5.1
  event_bus: ^1.1.1
  location: ^3.2.4
  geocoding: ^1.0.5
  jwt_decoder: ^1.0.4
  url_strategy: ^0.2.0
  jiffy: ^3.0.1
  image_picker_web: ^1.0.9
  image_picker: ^0.6.7+22
  flutter_typeahead: ^2.0.0
  file_picker: ^2.1.6
  flutter_map: ^0.11.0
  latlong: ^0.6.1
  mapbox_gl: ^0.10.0
  syncfusion_flutter_maps: ^19.1.58-beta

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

   uses-material-design: true

   assets:
     - grampanchayat_logo_white.png
     - grampanchayat_weblogo_white.png
     - Group.png
     - dash_ques.png
     - Image_1.png
     - rupees.png
     - bag.png
     - bell.png
     - rupees.png
     - ques_mark.png
     - pepoles.png
     - contact.png
     - speeker.png
     - logo_white.png
     - water.jpg
     - adobe.png
     - document.png
     - network.png
     - location.png
     - supply_image.png
     - Water_tap.png
     - Street_light.png
     - public_health.png
     - road.png
     - business_tax.png
     - house_tax.png
     - new_water_connection.png
     - water_tax.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

**Comment by danagbemava-nc** [comment]
Please provide the output of `flutter doctor -v` that contains the error you're getting. 

Thank you

**Comment by Abhishek8-198** [comment]
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\abhis\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

**Comment by danagbemava-nc** [comment]
Sorry, I meant the output of `flutter run -v` that shows the error you're getting.

**Comment by Abhishek8-198** [comment]
C:\Users\abhis\AndroidStudioProjects\web-mygraam>flutter run -v
[  +80 ms] executing: [C:\software\new-flutter\flutter_windows_2.5.3-stable\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +293 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 18116933e77adc82f80866c928266a5b4f1ed645
[        ] executing: [C:\software\new-flutter\flutter_windows_2.5.3-stable\flutter/] git tag --points-at 18116933e77adc82f80866c928266a5b4f1ed645
[  +60 ms] Exit code 0 from: git tag --points-at 18116933e77adc82f80866c928266a5b4f1ed645
[        ] 2.5.3
[   +9 ms] executing: [C:\software\new-flutter\flutter_windows_2.5.3-stable\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +41 ms] Exit code 128 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] fatal: HEAD does not point to a branch
[  +72 ms] executing: [C:\software\new-flutter\flutter_windows_2.5.3-stable\flutter/] git rev-parse --abbrev-ref HEAD
[  +41 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] HEAD
[  +49 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +79 ms] executing: C:\Users\abhis\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +52 ms] List of devices attached
[   +5 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +104 ms] Multiple devices found:
[  +29 ms] Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.110
[   +2 ms] Edge (web)   • edge   • web-javascript • Microsoft Edge 96.0.1054.62
[   +2 ms] [1]: Chrome (chrome)
[   +1 ms] [2]: Edge (edge)

**Comment by danagbemava-nc** [comment]
Hi @Abhishek8-198, the logs you have provided do not show the error you're getting. 

Please provide the logs that capture the error you're getting.

Better yet, you can provide a complete minimal reproducible code sample that will help to reproduce this issue. 

I suspect that this may be a CORS issue, in which case, there's nothing that flutter can do about it as CORS issues come from browsers and not flutter. 

If it is indeed a CORS issue, you may need to get a cors-proxy to help you with your issue. 

See https://flutter.dev/docs/development/platform-integration/web-images for more information. 

Thank you
