### ISSUE TITLE
The keyboard may pop twice when TextField's autofocus is true on some phone models.

### ISSUE THREAD

**Issue by wangying3426** [flutter/flutter#95905]
In Vivo and Huawei p40 pro mobile phone, we found that the keyboard will pop twice when TextField's autofocus is true.

### demo
https://user-images.githubusercontent.com/4476512/147572011-62e11ab8-cc51-4c99-8e24-20c15331c725.mp4

### code

[flutter_test_keyboard.zip](https://github.com/flutter/flutter/files/7784915/flutter_test_keyboard.zip)

```java 
import 'package:flutter/material.dart';
void main() {
  runApp(MyApp());
}
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: TextField(
        autofocus: true,
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), 
    );
  }
}
```

### flutter doctor -v

![飞书20211228-213715](https://user-images.githubusercontent.com/4476512/147572023-a1875f31-fd56-4189-a5ec-c6df0fcff0f6.png)

**Comment by maheshmnj** [comment]
Hi @wangying3426, Thanks for filing the issue. I see that you are using a very old version of flutter and Unfortunately we do not provide support to older versions I would advise you to please upgrade to latest `stable 2.8.1` and verify the issue. Please write back with the updated output of `flutter doctor -v` (as a text)  if you still encounter the issue after the upgrade.

Thank you.

**Comment by wangying3426** [comment]
> Yes，stable 2.0 has fixed this problem, but don‘t know which commit fix it. Could you tell me which commit fixed the problem? Because some online business will not be upgraded to the new version over a period of time, if possible, we can cherry-pick it firstly.

**Comment by maheshmnj** [comment]
Thanks for the update @wangying3426, I am sorry Unfortunately, I wouldn't be able to pinpoint the exact commit which fixed it. Probably you will have to figure out this by digging into the source code and comparing it.

Alternatively, if you can't upgrade to 2.0 then try to find flutter versions below 2.0.0  which fixes it and see if you can upgrade to that version.

**Comment by maheshmnj** [comment]
Closing as fixed in the new release.
