### ISSUE TITLE
[PROPOSAL] adding callback `onPressed` in `Container` widget(`Row`, `Col`)

### ISSUE THREAD

**Issue by ninjadev101** [flutter/flutter#95918]
## Use case

To achieve `Container` click, we are often using `GestureDectector` and other alternative solutions.
For most of developers, this is not the friendly way.

## Proposal

- Adding `onPressed` callback to handle clicking the container.

- Making `onPressed` not required parameter including `Container`, `Row`, `Col`.

**Comment by nt4f04uNd** [comment]
> To achieve `Container` click, we are often using `GestureDectector` and other alternative solutions.
> For most of developers, this is not the friendly way.

Why can't you wrap a Container in GestureDetector?

The Flutter's approach is to have each of the widgets in the framework to do its own thing, and be able to compose them with each other.

**Comment by ninjadev101** [comment]
Like other frameworks, Flutter needs to be clean and short in terms of code lines. Wrapping a container in GestureDetector works but if we add onPressed to the container, it will save us tons of code. And that is more friendly and increases code-code-readbility.

**Comment by erdzan12** [comment]
Simply create your own widget, using Container and GestureDetector, and use it everywhere you need it.

**Comment by nt4f04uNd** [comment]
> Like other frameworks, Flutter needs to be clean and short in terms of code lines. Wrapping a container in GestureDetector works but if we add onPressed to the container, it will save us tons of code. And that is more friendly and increases code-code-readbility.

It sounds like an exaggeration. GestureDetector is specific enough to be used just a few times in the whole app, and it's just a one more widget in the tree.

It also breaks a composability principle, as described above. I don't think we want to make this change.
