### ISSUE TITLE
[Proposal] Make columns sticky in DataTable.

### ISSUE THREAD

**Issue by Sadja18** [flutter/flutter#95927]
I have a dynamic method which builds a dynamic data table(because students data is returned at runtime after another fetch call) which is basically a report card entry widget in which number of subjects are specified on the API call at run time. 
Therefore, there is no way of knowing the total number of columns beforehand. 
Also, all the subjects cells in the following rows are text fields whose values are summed up and shown in the last column named Total Marks.
I am using vertical and horizontal scroll to mitigate the table dimensions overshooting the Screen size.
However, I would like to make the columns Roll_Number and Name sticky, so that they remain unaffected by horizontal scroll and column headers to be unaffected by vertical scroll.
Currently, DataTable does not support this feature. May I know when would this be implemented?

**Comment by maheshmnj** [comment]
Hi @Sadja18, Thanks for filing the issue. Looks like a valid proposal to me.

> May I know when would this be implemented?

We cannot provide eta for any of the issues and feature requests generally have lower priority. You may want to take a look at this wiki to understand how the issues are prioritized https://github.com/flutter/flutter/wiki/Issue-hygiene#priorities

**Comment by darshankawar** [comment]
@Sadja18 
There's similar open issue describing your case, #30770
Please follow-up there for updates.
Closing this as duplicate.

As a workaround, you may also take a look at this plugin which offers that feature, https://pub.dev/packages/table_sticky_headers

**Comment by Sadja18** [comment]
If the third party packages could solve my problem, I would gladly have
used them.
However, the package table_sticky_header has a hard time working if used
inside a futurebuilder. Also, the documentation of this package has scarce
info on how to customize it to my needs.

NAMAN MISHRA
