### ISSUE TITLE
p: image_picker opens camera instead of photolibrary

### ISSUE THREAD

**Issue by Alfaza0965** [flutter/flutter#95922]
While using image_picker: ^0.8.4+1 there seems to be an issue on physical IOS device running IOS 13.7
The following results in opening the camera instead of showing the photo library
 final List<XFile>? selectedImages = await imagePicker.pickMultiImage();

**Comment by darshankawar** [comment]
@Alfaza0965 
Current latest plugin version is `^0.8.4+4`, so upgrade to it and try again.
Also, try using the official plugin [example](https://pub.dev/packages/image_picker/example) and see if you still get same behavior or not.
