### ISSUE TITLE
[Flutter DartPad Error] Dartpad Firebase init error

### ISSUE THREAD

**Issue by 21600285-JaehyunPark** [flutter/flutter#95925]
## Steps to Reproduce

Firebase Nanochat which is the sample of DartPad dev cannot use Firebase because of the version of web/index.html

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

WARNING: FlutterFire for Web is explicitly tested against Firebase JS SDK version "8.10.0"
            but your currently specifying "8.6.1" by either the imported Firebase JS SDKs in your web/index.html
            file or by providing an override - this may lead to unexpected issues in your application. It is recommended that you change all of the versions of the
            Firebase JS SDK version "8.10.0":

            If you override the version manully:
              change:
                <script>window.flutterfire_web_sdk_version = '8.6.1';</script>
              to:
                <script>window.flutterfire_web_sdk_version = '8.10.0';</script>

            If you import the Firebase scripts in index.html, instead allow FlutterFire to manage this for you by removing
            any Firebase scripts in your web/index.html file:
                e.g. remove: <script src="https://www.gstatic.com/firebasejs/8.6.1/firebase-app.js"></script>

```
```

```
```

```
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @21600285-JaehyunPark, `dartpad` has a dedicated repo so you can file this issue over [there](https://github.com/dart-lang/dart-pad/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) so that it may be properly addressed. 

Closing as this is not a flutter issue. 

Thank you

**Comment by 21600285-JaehyunPark** [comment]
Thank you for your quick response! Bless you!

2021년 12월 29일 (수) 오후 4:30, Daniel Agbemava ***@***.***>님이 작성:
