### ISSUE TITLE
Hi @TahaTesser,Have you solved the problem yet？

### ISSUE THREAD

**Issue by zewsummer** [flutter/flutter#95936]
Hi @TahaTesser, 
I've updated the code and submitted it.
I used the latest master branch and didn't reproduce the problem. I believe you've fixed it. But when will it be merged into the stable version? Because our company is using stable branches.

_Originally posted by @jiangxklongmao in https://github.com/flutter/flutter/issues/86425#issuecomment-881526070_

**Comment by TahaTesser** [comment]
Hi @zewsummer 
If you can still reproduce the issue, please follow the new issue template and provide all the details, thanks.
