### ISSUE TITLE
snapcraft

### ISSUE THREAD

**Issue by bksubhuti** [flutter/flutter#95933]
## Steps to Reproduce
I'm using flutter 2.8 and did the snapcraft command.
Many things were done.
The script seems to be running flutter commands as root and tells me not to do this.
```
+ snapcraftctl build
flutter pub get
   Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎
```

Then I get an error , 
```
Your Flutter application is created using an older version of the Android
embedding. It is being deprecated in favor of Android embedding v2. Follow the
steps at

https://flutter.dev/go/android-project-migration

to migrate your project. You may also pass the --ignore-deprecation flag to
ignore this check and continue with the deprecated v1 embedding. However,
the v1 Android embedding will be removed in future versions of Flutter.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
The detected reason was:

  /root/parts/tipikata-pali-reader/build/android/app/src/main/AndroidManifest.xml uses
  `android:name="io.flutter.app.FutterApplication"`
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

"my": 1 untranslated message(s).
To see a detailed report, use the untranslated-messages-file 
option in the l10n.yaml file:
untranslated-messages-file: desiredFileName.txt
<other option>: <other selection> 


This will generate a JSON format file containing all messages that 
need to be translated.
Running "flutter pub get" in build...                              46.6s
This app is using a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to migrate this app
to the V2 embedding.
Take a look at the docs for migrating an app:
https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects
```

Then it fails here:
```
**The plugin `flutter_keyboard_visibility` requires your app to be migrated to the
Android embedding v2. Follow the steps on
https://flutter.dev/go/android-project-migration and re-run this command.
Failed to run 'flutter pub get' for 'tipikata-pali-reader': Exited with code 1.
Verify that the part is using the correct parameters and try again.**
```
**I can build apk fine.. I can flutter run for  linux app.**

I suspect that the snapcraft is out of date.

**Comment by danagbemava-nc** [comment]
Hi @bksubhuti, was your project created with `flutter 2.8` or it was created before that? 

If it's the latter, kindly follow https://flutter.dev/go/android-project-migration to migrate to the newest version of the android embedding. 

> I can flutter run for linux app.

The warning is for android apps, so linux builds won't be affected by this. 

> I can build apk fine

It is just a warning so you should still be able to run your apps just fine. 

> The plugin `flutter_keyboard_visibility` requires your app to be migrated to the
Android embedding v2.

This error likely means that you're still using an older version of the android embedding and that makes the package you're trying to use incompatible with your project.

**Comment by bksubhuti** [comment]
This was a project started earlier... and we upgraded a few times to a few different flutters.  i will look into this suggestion.

**Comment by danagbemava-nc** [comment]
Please also bear in mind that snap has it's own dedicated repo over [here](https://github.com/canonical/flutter-snap/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc). 

If you do run into any more issues with snap, kindly file the issues over there. 

Thank you

**Comment by bksubhuti** [comment]
Yes.. things are better now.  But now there are definitely more snap issues. and I think issues with the multipass and dbus.  It is related to flutter but I guess the snap team is on that part.  We can close.

**Comment by bksubhuti** [comment]
FYI issue filed here https://github.com/canonical/flutter-snap/issues/62
