### ISSUE TITLE
Would like an example of showing an OEM View over Flutter

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#9593]
This is a common request, and right now all we can do is point customers at apps like:
https://itunes.apple.com/nz/app/newsvoice/id1208421834?mt=8
which do this (for their add-a-comment view).

Would be good to have an example showing how to do this.  I'd like us to consider this for May.

**Comment by eseidelGoogle** [comment]
This is a more general version of https://github.com/flutter/flutter/issues/8863.

**Comment by amirh** [comment]
Closing as I believe this is obsolete with the platform views support.
