### ISSUE TITLE
controller.startVideoRecording not working as expected 

### ISSUE THREAD

**Issue by mobileapp-infinity** [flutter/flutter#95931]
here is my .dart file for video recording functionality, camera preview freezed after calling controller.startVideoRecording().

```dart
import 'dart:async';
import 'dart:convert';
import 'package:camera/camera.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:http/http.dart' as http;

class CameraPage extends StatefulWidget {
  final List<CameraDescription>? cameras;
  const CameraPage({Key? key, this.cameras}) : super(key: key);

  @override
  _CameraPageState createState() => _CameraPageState();
}

class _CameraPageState extends State<CameraPage> {
  late CameraController controller; //with WidgetsBindingObserver
  XFile? pictureFile;
  // late Stream takePhotoStream;
  late int time = 2000;
  Timer? timer;
  late RxBool isLoading = true.obs;
  late bool isError = false;

  @override
  void initState() {
    Future.delayed(const Duration(seconds: 0), () {
      initController();
    });
    super.initState();
  }

  void initController() async {
    controller = CameraController(widget.cameras![0], ResolutionPreset.low,enableAudio: false);
    await controller.initialize();
    isLoading.value = false;
    videoRecodeScreen();
  }

  // @override
  // void didChangeAppLifecycleState(AppLifecycleState state) async{
  //   if (state == AppLifecycleState.resumed) {
  //     controller != null
  //         ? controller.initialize()
  //         : null; //on pause camera disposed so we need call again "issue is only for android"
  //   }
  // }

  void videoRecodeScreen() async {
    await controller.startVideoRecording();
    // await controller.prepareForVideoRecording();
    print('video started');
    Future.delayed(const Duration(milliseconds: 10000)).then((value) async {
      pictureFile = await controller.stopVideoRecording();
      print('video stopped');
      Future.delayed(const Duration(seconds: 30)).then((value) {
        videoRecodeScreen();
      });
    });
  }

  // void studentSaveImageApo(
  //     {required String type,
  //     required String examId,
  //     required String examToken,
  //     required String examStudentID,
  //     required String studentimagePath}) async {
  //   // AppDialogs.showProgressDialog(context: context);
  //   // isLoading = true;
  //   // isError = false;
  //   final response = await http.post(
  //       Uri.parse(
  //           'https://demoefh.liveexam.net/screen/api/save_image.php?t=${type}&examid=${examId}&extoken=${examToken}&exam_std=${examStudentID}'),
  //       headers: {
  //         'Content-Type': 'application/json',
  //       },
  //       body: jsonEncode({
  //         "data": "${studentimagePath}",
  //       }));
  //   if (response.statusCode == 200) {
  //     // isLoading = false;
  //     // isError = false;
  //     // Get.back();
  //     print("Video Api Is Call");
  //     // Get.offAndToNamed(AppRoutes.EXAMSCREEN);
  //   } else {
  //     // isLoading = false;
  //     // isError = true;
  //     // Get.back();
  //     throw Exception(response.reasonPhrase);
  //   }
  // }

  // @override
  // void dispose() {
  //   // WidgetsBinding.instance!.removeObserver(this);
  //   controller.dispose();
  //   // takePhotoStream.drain();
  //   super.dispose();
  // }

  // @override
  // void didChangeAppLifecycleState(AppLifecycleState state) {
  //   if (state == AppLifecycleState.resumed) {
  //     AppDialogs.showDefaultDialogue(
  //         context: context,
  //         showdefaultText: "showdefaultText",
  //         onOkBtnClickListener: () {
  //           Navigator.pop(context);
  //         });
  //   }
  // }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Obx(
        () => isLoading.value == true
            ? const CircularProgressIndicator()
            : CameraPreview(controller),
      ),
    );
  }
//Obx(()=> isLoading.value == true ? const CircularProgressIndicator() : )
  // @override
  // Widget build(BuildContext context) {
  //   if (!controller.value.isInitialized) {
  //     return const SizedBox(
  //       child: Center(
  //         child: CircularProgressIndicator(),
  //       ),
  //     );
  //   }
  //   return Scaffold(
  //     body: SafeArea(
  //       child: Column(
  //         children: [
  //           Padding(
  //             padding: EdgeInsets.all(10.0),
  //             child: Center(
  //               child: SizedBox(
  //                 height: 150.0,
  //                 width: 300,
  //                 child: CameraPreview(controller),
  //               ),
  //             ),
  //           ),
  //           Padding(
  //             padding: EdgeInsets.all(20.0),
  //             child: ElevatedButton(
  //                 onPressed: () async {
  //                   pictureFile = await controller.takePicture();
  //                   setState(() {});
  //                 },
  //                 child: Text("capture Image")),
  //           ),
  //           if (pictureFile != null)
  //             Image.network(
  //               pictureFile!.path,
  //               height: 100.0,
  //             )
  //         ],
  //       ),
  //     ),
  //   );
  // }
}

// class RxString {}
```

**Comment by maheshmnj** [comment]
Hi @mobileapp-infinity, Thanks for filing the issue. I ran the [official sample code](https://pub.dev/packages/camera/example) and the camera preview seems to be working fine when video recording is enabled. 
Can you please share your output of `flutter doctor -v`, and do you see any errors in console when the freeze occurs?
Additionally can you please try running the official sample?

**Comment by mobileapp-infinity** [comment]
> Hi @mobileapp-infinity, Thanks for filing the issue. I ran the [official sample code](https://pub.dev/packages/camera/example) and the camera preview seems to be working fine when video recording is enabled. Can you please share your output of `flutter doctor -v`, and do you see any errors in console when the freeze occurs? Additionally can you please try running the official sample?
> 
> flutter doctor -v

Please check Below Information : 

[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19041.1415], locale en-IN)
    • Flutter version 2.8.1 at C:\Users\INFINITY\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (4 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\INFINITY\AppData\Local\Android\Sdk
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = C:\Users\INFINITY\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.63.2)
    • VS Code at C:\Users\INFINITY\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.32.0

[√] Connected device (3 available)
    • vivo 1802 (mobile) • AQRO6TYPN7OJOFFA • android-arm64  • Android 8.1.0 (API 27)
    • Chrome (web)       • chrome           • web-javascript • Google Chrome 97.0.4692.71
    • Edge (web)         • edge             • web-javascript • Microsoft Edge 97.0.1072.55

• No issues found!

**Comment by mobileapp-infinity** [comment]
In vivo Y83 not working after starting video recording ,I had been tried all the possible option but not working unfortunately.(vivo Y83)

**Comment by maheshmnj** [comment]
Thanks for the info @mobileapp-infinity, Please share the complete logs of `flutter run -v` in a text file. Also did you verify it on Another device?
