### ISSUE TITLE
Please update the roadmap 2022

### ISSUE THREAD

**Issue by realkimmy** [flutter/flutter#95930]

**Comment by maheshmnj** [comment]
Hi @realkimmy, The wiki page will be updated with the 2022 roadmap when the team thinks is the right time or if they have an update to share, We don't need to track this as an issue, The issue tracker is only to track the bugs and feature requests in the Flutter framework.

Closing this issue as invalid.

**Comment by maheshmnj** [comment]
Hi, just came back to let you know that the roadmap for 2022 has been updated https://github.com/flutter/flutter/wiki/Roadmap

**Comment by realkimmy** [comment]
Thank you
