### ISSUE TITLE
Flutter running multiple integration_tests fails upon launching main() root level widget from setUp() method.

### ISSUE THREAD

**Issue by rajeshpatil95** [flutter/flutter#95934]
Writing integration_test for my flutter-web wherein i am executing multiple tests clubbed in a group() by initiating **main()** root level widget from **setUp()** predefined method which supposed to get called before every test runs., just to reduce the redundancy of calling **app_test.main()** in every test.
But the test fails after it successfully executes first test..remaining all rest fails with assertion error ?.

**It works absolutely fine after moving **app_test.main()** inside to every **testWidgets()****.

**Code:**
`void main() async {
  group('Complete Authentication E2E Test', () {
    IntegrationTestWidgetsFlutterBinding.ensureInitialized();

    setUp(() {
      app.main();
    });

    testWidgets('Successful Login/Logout', (WidgetTester tester) async {
      await tester.pumpAndSettle(const Duration(seconds: 2));
      const username = 'gorike8673@d3bb.com';
      const password = '1qaZ2wsX';

      final loginScreenPage = LoginScreenPage(tester);
      await loginScreenPage.enterUsernameAndPassword(
          username: username, password: password);
      await loginScreenPage.clickLoginButton();
      await CommonUtils.pumpUntilFound(tester, find.byIcon(Icons.logout),
          timeout: const Duration(seconds: 5));
      expect(find.byIcon(Icons.logout), findsOneWidget);
      await loginScreenPage.clickLogoutButton();
      await CommonUtils.pumpUntilFound(tester, find.text('Username'),
          timeout: const Duration(seconds: 5));
      expect(find.text('Username'), findsOneWidget);
    });

    testWidgets('Login with empty Username and Password',
        (WidgetTester tester) async {
      await tester.pumpAndSettle(const Duration(seconds: 2));
      final loginScreenPage = LoginScreenPage(tester);
      await loginScreenPage.clickLoginButton();
      await CommonUtils.pumpUntilFound(tester, find.text('Failed'),
          timeout: const Duration(seconds: 5));
      expect(find.text('Failed'), findsOneWidget);
    });

    testWidgets('Login with only Password empty', (WidgetTester tester) async {
      await tester.pumpAndSettle(const Duration(seconds: 2));
      const username = 'gorike8673@d3bb.com';

      final loginScreenPage = LoginScreenPage(tester);
      await loginScreenPage.enterUsernameAndPassword(username: username);
      await loginScreenPage.clickLoginButton();
      await CommonUtils.pumpUntilFound(tester, find.text('Failed'),
          timeout: const Duration(seconds: 5));
      expect(find.text('Failed'), findsOneWidget);
    });

    testWidgets('Login with only Username empty', (WidgetTester tester) async {
      await tester.pumpAndSettle(const Duration(seconds: 2));
      const password = '1qaZ2wsX';

      final loginScreenPage = LoginScreenPage(tester);
      await loginScreenPage.enterUsernameAndPassword(password: password);
      await loginScreenPage.clickLoginButton();
      await CommonUtils.pumpUntilFound(tester, find.text('Failed'),
          timeout: const Duration(seconds: 5));
      expect(find.text('Failed'), findsOneWidget);
    });

    testWidgets('Login with invalid username, valid password',
        (WidgetTester tester) async {
      await tester.pumpAndSettle(const Duration(seconds: 2));
      const username = 'gorike8673';
      const password = '1qaZ2wsX';

      final loginScreenPage = LoginScreenPage(tester);
      await loginScreenPage.enterUsernameAndPassword(
          username: username, password: password);
      await loginScreenPage.clickLoginButton();
      await CommonUtils.pumpUntilFound(tester, find.text('Failed'),
          timeout: const Duration(seconds: 5));
      expect(find.text('Failed'), findsOneWidget);
    });

    testWidgets('Login with invalid password, valid username',
        (WidgetTester tester) async {
      await tester.pumpAndSettle(const Duration(seconds: 2));
      const username = 'gorike8673@d3bb.com';
      const password = '1qaZ';

      final loginScreenPage = LoginScreenPage(tester);
      await loginScreenPage.enterUsernameAndPassword(
          username: username, password: password);
      await loginScreenPage.clickLoginButton();
      await CommonUtils.pumpUntilFound(tester, find.text('Failed'),
          timeout: const Duration(seconds: 5));
      expect(find.text('Failed'), findsOneWidget);
    });
  });
}`

**Flutter doctor:**
`Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.8.0, on Microsoft Windows [Version 10.0.19043.1415], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.63.2)
[√] Connected device (2 available)

• No issues found!`

**Comment by darshankawar** [comment]
@rajeshpatil95 
Tried the scenario using latest stable and master on default counter app in which I had wrapped `app.main()` inside `setUP()` method as below and then ran the test which worked properly for me:

<details>
<summary> app_test.dart </summary>

```

import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
import 'package:int_test_sample/main.dart' as app;

void main() async {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  setUp(() {
    app.main();


    group('Counter end-to-end test', () {
      testWidgets('tap on the increment floating action button; verify counter',
              (WidgetTester tester) async {
            await tester.pumpAndSettle();
            // Finds the floating action button to tap on.
            final fab = find.byTooltip('Increment');
            // Emulate a tap on the floating action button.
            await tester.tap(fab);
            await tester.pumpAndSettle();
            expect(find.text('1'), findsOneWidget);
          });

      testWidgets('tap on the decrement floating action button; verify counter',
              (WidgetTester tester) async {
            await tester.pumpAndSettle();
            // Finds the floating action button to tap on.
            final fab = find.byTooltip('Decrement');
            // Emulate a tap on the floating action button.
            await tester.tap(fab);
            await tester.pumpAndSettle();
            expect(find.text('0'), findsOneWidget);
          });
    });
  });
}

```

</details>

```
dhs@Dhss-MacBook-Pro int_test_sample % flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart -d web-server --no-headless
Running "flutter pub get" in int_test_sample...                    581ms
Launching integration_test/app_test.dart on Web Server in debug mode...
Waiting for connection from debug service on Web Server...         18.5s
integration_test/app_test.dart is being served at http://localhost:50488
The web-server device requires the Dart Debug Chrome extension for debugging. Consider using the Chrome or Edge devices for an improved development workflow.
All tests passed.
Application finished.
dhs@Dhss-MacBook-Pro int_test_sample % 
```

Can you provide a minimal code sample including `main.dart` along with `app_test.dart` that we can use and verify ?

**Comment by rajeshpatil95** [comment]
@darshankawar thanks for your reply...After narrowing down the problem identified its browsers cookies that was creating an issue while automating, i cleared the cookies local storage in setUp() method before execution of each text case.
Hence closing the issue

thanks
