### ISSUE TITLE
Why isn't GLFW used as the default windowing system for all 3 desktop platforms? 

### ISSUE THREAD

**Issue by scotch-hub** [flutter/flutter#95941]
GLFW is cross-platform and under active development. This change would also simplify the development for flutter on the desktop and allow for a more unified code-base.

Am I missing something?

**Comment by stuartmorgan** [comment]
GLFW does not support a number of core goals of the desktop embedding architecture, including platform view support and add-to-app scenarios.

Anyone who wants a GLFW-based embedding is of course welcome to use one instead; several exist.
