### ISSUE TITLE
Using platform view flutter widgets overlapped by IOS native views

### ISSUE THREAD

**Issue by anumrukhsar** [flutter/flutter#95943]
I am using platform view to show IOS native widgets in flutter. But those native widgets overlap any flutter widget that open on it like popup as you seen here.
<img width="332" alt="Screenshot 2021-12-29 at 8 42 55 PM" src="https://user-images.githubusercontent.com/53735993/147693754-f0e118e7-f33c-4980-b849-acd25a851397.png">

**Comment by maheshmnj** [comment]
Hi @anumrukhsar, Please share a minimal and complete project along with the output of `flutter doctor -v`.

Thanks
