### ISSUE TITLE
Document Why MethodChannel.Result#success is marked with @UiThread

### ISSUE THREAD

**Issue by cyanlink** [flutter/flutter#95959]
## Steps to Reproduce

1. On Android, implement a custom MethodCallHandler.
2. Run the result.success in a new Thread on purpose, as shown in sample code below.
3. All works good on both Android and Dart. (unlike calling MethodChannel#invokeMethod on Android side where you will certainly get Exceptions)

I'm asking this question because I was trying to `invokeMethod` to Dart side in a `MethodCallHandler` callback, with TaskQueue enabled. This gave me the "not on main thread exception" (as they are in `DartMessenger.DefaultTaskQueue`), but the MethodChannel.Result#success did not.

**Expected results:** This function's annotation should be better documented to explain the necessity to run on UI thread.

**Actual results:** The function is marked `@UiThread`, but no such check is done in FlutterJNI by calling `ensureRunningOnMainThread`, and it all works normal, making the annotation a "false alarm".

<details>
<summary>Code sample</summary>

```kotlin
override fun onMethodCall(call: MethodCall, result: MethodChannel.Result) {
        when (call.method) {
            "getPics" -> Thread{result.success(true)}.run()
        }
    }
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
Labeling this as a documentation issue and for further input.

**Comment by darshankawar** [comment]
may be related : https://github.com/flutter/flutter/issues/36051

**Comment by stuartmorgan** [comment]
@gaaclarke Presumably this is just a stale annotation that we need to remove?

**Comment by cyanlink** [comment]
https://docs.flutter.dev/development/platform-integration/platform-channels?tab=type-mappings-kotlin-tab#channels-and-platform-threading

> The result of the platform side handlers can be invoked asynchronously and on any thread.

Documentation checks out.

**Comment by gaaclarke** [comment]
Yep, stale annotation.
