### ISSUE TITLE
[in_app_purchase] support only card transaction not working and showing UPI BHIM ,GOOGLE PAY transaction 

### ISSUE THREAD

**Issue by Sreejith93** [flutter/flutter#95952]
[in_app_purchase] support only card transaction not working and showing UPI BHIM ,GOOGLE PAY transaction 

![WhatsApp Image 2021-12-30 at 11 18 01](https://user-images.githubusercontent.com/56011221/147725296-bbab9597-4913-4191-9a0f-bb200715c81d.jpeg)

**Comment by danagbemava-nc** [comment]
Hi @Sreejith93, thanks for filing the issue. 

Help me understand something. 

Is your issue that you want only cards to be used for payment but the action sheet is showing other forms of payment? 

If so, how did you enforce that setting, and was it done with the `in_app_purchase` plugin?

If it was, please provide the version of `in_app_purchase` you're using as well as the output of `flutter doctor -v` as well as a complete minimal reproducible code sample. 

Thank you

**Comment by Sreejith93** [comment]
I want to use BHIM UPI , Gpay because most people are using this way
transaction.
I am using in_app_purchase 0.5.2 version.
iam not changing anything in app purchase section code from your code.only
working card payment transaction why? i want enable bhim upi gateway

**Comment by danagbemava-nc** [comment]
Hi @Sreejith93, unfortunately, the `in_app_purchase` plugin has no control over which payment methods are available for payment. 

You may need to contact Google play for more information. 

Closing as the `in_app_purchase` plugin doesn't have any control over the payment methods that are available.

Thank you

**Comment by Sreejith93** [comment]
Thanks, I'll check it out.
