### ISSUE TITLE
[shared_preferences] Inconsistent behaviour between platforms during testing

### ISSUE THREAD

**Issue by Pante** [flutter/flutter#95951]
Dart version: 2.15.1
Flutter version: 2.8.1
shared_preferences: 2.0.11

The behaviour of calling `SharedPreferences.getInstance()` without first setting mock values via `SharedPreferences.setMockInitialValues({})` is inconsistent between platforms.

The following snippet of code throws a `MissingPluginException` exception on MacOS (both Intel and M1) but not Windows and Linux:
```dart
void main() {
  
  setUp(() async {
    final preferences = await SharedPreferences.getInstance(); // throws an exception on MacOS
  });
  
}
```

This behaviour is surprising and inconsistent. In my opinion the above code snippet should either:
* Throw an exception on all platforms
* Work without having to set mock initial values on all platforms
* Be clearly documented that the behaviour is platform dependent

**Comment by maheshmnj** [comment]
Hi @Pante, Thanks for filing the issue. I do see the exception when running the counter app test on MacOS (not reproducible on windows).

```console
Connecting to VM Service at http://127.0.0.1:52460/3wTySzNN5MY=/ws
MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
dart:async                                                _Completer.completeError
SharedPreferences.getInstance
===== asynchronous gap ===========================
dart:async                                                _asyncErrorWrapperHelper
main.<fn>
main.<fn>

✖ Counter increments smoke test
Exited (1)
```

<details>
<summary>flutter doctor -v (macos)</summary>

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.8.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (2 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 96.0.4664.110

• No issues found!
```

```
[✓] Flutter (Channel master, 2.9.0-1.0.pre.205, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.9.0-1.0.pre.205 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6ec059c994 (2 days ago), 2021-12-28 00:29:08 -0500
    • Engine revision 31fcaf3ce4
    • Dart version 2.16.0 (build 2.16.0-134.0.dev)
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 96.0.4664.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

<details>
<summary>flutter doctor -v (windows)</summary>

```
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19042.1415], locale en-US)
    • Flutter version 2.8.1 at C:\flutter_sdk\stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (2 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\mahesh\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java      
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)    
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)      
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)        

[√] VS Code (version 1.61.2)
    • VS Code at C:\Users\mahesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.29.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.1415]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 96.0.4664.110
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 96.0.1054.53

• No issues found!
```

```
[√] Flutter (Channel master, 2.9.0-1.0.pre.206, on Microsoft Windows [Version 10.0.19042.1415], locale en-US)    • Flutter version 2.9.0-1.0.pre.206 at C:\flutter_sdk\master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision abac2cde75 (2 days ago), 2021-12-28 02:54:09 -0500
    • Engine revision 961c28e189
    • Dart version 2.16.0 (build 2.16.0-134.0.dev)
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)    
    • Android SDK at C:\Users\mahesh\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)        
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)      
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.61.2)
    • VS Code at C:\Users\mahesh\AppData\Local\Programs\Microsoft VS Code   
    • Flutter extension version 3.29.0

[√] Connected device (4 available)
    • Windows (desktop)       • windows • windows-x64     • Microsoft Windows [Version 10.0.19042.1415]      
    • Windows (UWP) (desktop) • winuwp  • windows-uwp-x64 • 
    • Chrome (web)            • chrome  • web-javascript  • Google Chrome 96.0.4664.110
    • Edge (web)              • edge    • web-javascript  • Microsoft Edge 96.0.1054.53

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>


@Pante Can you confirm if this is the same exception you are referring to?

**Comment by Pante** [comment]
> 

Yup! It's the exception that we encountered.

**Comment by stuartmorgan** [comment]
In general, attempting to use a plugin in tests (other than integration tests) will throw an exception. That's true for plugins in general, not just this one.

Window and Linux `shared_preferences` happen to be implemented without traditional plugin code, which means that they happen to work in tests.

> * Throw an exception on all platforms

This is not possible under the current implementation.

> * Work without having to set mock initial values on all platforms

Neither is this.

> * Be clearly documented that the behaviour is platform dependent

The fact that it happens to work on Windows and Linux is an implementation detail that is subject to change; documenting it would encourage people to (incorrectly) rely on that behavior.

**Comment by Pante** [comment]
> In general, attempting to use a plugin in tests (other than integration tests) will throw an exception. That's true for plugins in general, not just this one.
> 
> Window and Linux `shared_preferences` happen to be implemented without traditional plugin code, which means that they happen to work in tests.
> 
> > * Throw an exception on all platforms
> 
> This is not possible under the current implementation.
> 
> > * Work without having to set mock initial values on all platforms
> 
> Neither is this.
> 
> > * Be clearly documented that the behaviour is platform dependent
> 
> The fact that it happens to work on Windows and Linux is an implementation detail that is subject to change; documenting it would encourage people to (incorrectly) rely on that behavior.

I believe that there still is merit to documenting the behaviour. It doesn't have to be explicit in mentioning which platforms it works on or anything. In my mind, even a simple "You are required to set the initial mock values, otherwise the tests might not work as expected on all platforms." somewhere in will make the behaviour far less surprising.

**Comment by stuartmorgan** [comment]
Again, the fact that you shouldn't rely on it working in tests is true of **all** plugins. Documenting that in every individual plugin doesn't really make sense in that context.

**Comment by Pante** [comment]
> Again, the fact that you shouldn't rely on it working in tests is true of **all** plugins. Documenting that in every individual plugin doesn't really make sense in that context.

I agree that people shouldn't rely on plugins working during tests. But how would people know from a glance not to rely on plugins working during tests if it's not documented anywhere? It might be obvious to people with experience working with plugins, but what about those that aren't?

In this case, just tweaking an existing [line](https://pub.dev/packages/shared_preferences#testing) that already exists in the README of `shared_preferences` to "You _need to_ populate `SharedPreferences` with initial values in your tests before running your tests" removes any ambiguity. It doesn't have to be applied to *all* plugins, just `shared_preferences`.

Will a PR to change the phrasing in `shared_preferences` be welcomed?

**Comment by stuartmorgan** [comment]
> But how would people know from a glance not to rely on plugins working during tests if it's not documented anywhere?

It should be documented in a central location. I thought it already was, but I can't find it now so I've filed  https://github.com/flutter/flutter/issues/95970 to track fixing that.

> "You _need to_ populate `SharedPreferences` with initial values in your tests before running your tests" removes any ambiguity.

That statement isn't accurate. It's not true for integration tests (where plugins work as normal), it's not true for well-factored unit tests (which shouldn't hit `shared_preferences` in the first place), and it's not true if someone registers their own fake implementation for tests (which is something that central documentation would prominently cover).

**Comment by Pante** [comment]
> That statement isn't accurate. It's not true for integration tests (where plugins work as normal), it's not true for well-factored unit tests (which shouldn't hit `shared_preferences` in the first place), and it's not true if someone registers their own fake implementation for tests (which is something that central documentation would prominently cover).

Fair enough, thanks for the taking the time to clarify this.
