### ISSUE TITLE
Be consistent about analytics nesting in tools

### ISSUE THREAD

**Issue by xster** [flutter/flutter#9595]
For instance the `flutter run` timing event includes a `flutter flx` but doesn't include a `flutter build`.

**Comment by sethladd** [comment]
Is the bug "the timing of flutter run doesn't include flutter build" ?

**Comment by xster** [comment]
ya, either commands that include other commands should trigger a nested recording of everything or just record the top parent command only.

**Comment by pedromassangocode** [comment]
Is this still a valid issue? Is there  any way for me to verify if this is valid today?

It has been 3y now, so this may already be addressed.
Thank you

**Comment by xster** [comment]
@zanderso did a pretty big GA refactor and may have addressed this

**Comment by zanderso** [comment]
I think we should probably close this in favor of more specific issues if any remain.
