### ISSUE TITLE
Adding a new builder widget for ChangeNotifier

### ISSUE THREAD

**Issue by albertodev01** [flutter/flutter#95967]
## Use case

In the Flutter ecosystem there is a well-established way of listening to something that changes, for example:

  - A `ValueListenable` type has a `ValueListenableBuilder`
  - An `AnimationController` type has a `AnimatedBuilder`
  - A `PageRoute` type has a `PageTransitionsBuilder`
  - and so on...

So if you follow this pattern, a type that needs to be listened for changes has a `FooBuilder` widget associated. I would like to create a `ChangeNotifierBuilder` for consistency with the "builder" pattern we have.

Right now, we can use an `AnimatedBuilder` to listen for changes on a class mixed or extended with `ChangeNotifier` but this is not intuitive. Users might not know that both `ChangeNotifier` and `Animation<T>` extend `Listenable` (and so a `ChangeNotifier` can be used in an `AnimatedBuilder`).

I think that having a `ChangeNotifierBuilder` (a simple wrapper or subtype of `AnimatedBuilder`) would make more consistency in terms of naming builders. No performance benefits at all.

When you create a new Flutter app with `flutter create --template=skeleton myapp` there is a model class called `SettingsController` which uses a `ChangeNotifier`. It is listened in this way:

```dart
AnimatedBuilder(
  animation: settingsController,
  builder: (BuildContext context, Widget? child) { ... }
),
```

Since the builder is named " _**Animated**_ Builder" I wouldn't expect something that is not an animation (`settingsController`) to be attached (even if it perfectly works). The [ChangeNotifier](https://api.flutter.dev/flutter/foundation/ChangeNotifier-class.html) doc doesn't even mention that it can be listened into an `AnimatedBuilder` (this should be added too to clarify!). I would have preferred something like this:

```dart
ChangeNotifierBuilder(
  changeNotifier: settingsController,
  builder: (BuildContext context, Widget? child) { ... }
),
```

## Proposal

Right now we have the [`AnimatedWidget`](https://github.com/flutter/flutter/blob/77d935af4d/packages/flutter/lib/src/widgets/transitions.dart#L74) which listens on a generic `Listenable` widget.

The [`AnimatedBuilder`](https://github.com/flutter/flutter/blob/77d935af4d/packages/flutter/lib/src/widgets/transitions.dart#L1000) is simply a subtype that adds a builder function:

```dart
class AnimatedBuilder extends AnimatedWidget {
  const AnimatedBuilder({
    Key? key,
    required Listenable animation,
    required this.builder,
    this.child,
  }) : assert(animation != null),
       assert(builder != null),
       super(key: key, listenable: animation);

  final TransitionBuilder builder;

  final Widget? child;

  @override
  Widget build(BuildContext context) {
    return builder(context, child);
  }
}
```

I would like to create a very similar widget for a `ChangeNotifier` as well:

```dart
class ChangeNotifierBuilder<T extends ChangeNotifier> extends AnimatedBuilder {
  const ChangeNotifierBuilder({
    Key? key,
    required T changeNotifier,
    required this.builder,
    this.child,
  }) : assert(animation != null),
       assert(builder != null),
       super(
         key: key, 
         animation: changeNotifier,
         builder: builder,
         child: child,
       );
}
```
This would mean that people should `MyClass extends ChangeNotifier` instead of `MyClass with ChangeNotifier` to use this widget. The class would have the 'builder' word in the name, which would be consistent with the other "listening" builder widgets. 

For example, many people that use Flutter's built-in state management would also do something like this:

```dart
class Counter extends ChangeNotifier { ... }

class CounterState extends InheritedWidget {
  const CounterState ({
    Key? key,
    required this.counter,
    required Widget child,
  }) : super(key: key, child: child);

  final Counter counter;

  static CounterState of(BuildContext context) { ... }

  bool updateShouldNotify(CounterState old) { ... };
}

// And then in a widget
ChangeNotifierBuilder(
  changeNotifier: CounterState.of(context).counter,
  builder: (context, child) { ... }
);
```

May this be a good idea?

**Comment by nt4f04uNd** [comment]
Also related to https://github.com/flutter/flutter/issues/19255

**Comment by albertodev01** [comment]
@nt4f04uNd do I need to wait for some team member approval? Or can I already work on a PR?

**Comment by nt4f04uNd** [comment]
Actually, I'm a bit unsure if we want to create an alias for an existing API (AnimatedBuilder), just for the sake of it being more discoverable. This might confuse API users as well - why are there two classes doing the same thing?

It might be better to add some docs, and eventually fix #19255 instead.

Anyway, you could to ask about this in the Discord hackers-framework chat

**Comment by albertodev01** [comment]
Thank you, I will ask in the Discord channel!

I think that `AnimatedBuilder` is an alias of `AnimatedWidget` as well: it just adds a builder but nothing more. Maybe we could, for consistency, also have 

```dart
class ChangeNotifierBuilder<T extends ChangeNotifier> extends AnimatedWidget { ... }
```

so that the hierarchy would look like this
![te](https://user-images.githubusercontent.com/2848696/147822264-c02c284d-3d83-4aad-b540-dff9172f161e.png)
:

**Comment by albertodev01** [comment]
@Piinks would you mind giving a look at this as well whenever you get the chance? Thank you

**Comment by mateusfccp** [comment]
> Actually, I'm a bit unsure if we want to create an alias for an existing API (AnimatedBuilder), just for the sake of it being more discoverable. This might confuse API users as well - why are there two classes doing the same thing?

I am not sure... For example, we have `Align` and `Center`, that are mostly the same widget with different names, and I don't think it causes any confusion...

**Comment by goderbauer** [comment]
Based on the discussion in https://github.com/flutter/flutter/pull/97256 I am going to close this.
