### ISSUE TITLE
Flutter app not running on iOS after adding google_map_flutter package

### ISSUE THREAD

**Issue by pratikbaid3** [flutter/flutter#95962]
My current flutter app has the following dependencies
```yaml
  cupertino_icons: ^1.0.4
  flutter_launcher_icons: ^0.9.2
  flutter_svg: ^1.0.0
  pin_code_fields: ^7.3.0
  provider: ^6.0.1
  flutter_native_splash: ^1.3.2
  awesome_circular_chart: ^1.0.0
  http: ^0.13.4

  # Firebase
  firebase_auth: ^3.1.4
  firebase_core: ^1.10.6
```

This works fine but as soon as I add ```google_maps_flutter: ^2.1.1``` and try and run it, I get the following error:
```
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    /Users/pratikbaid/Desktop/Work/FlutterDev/gardenvision/ios/Runner/GeneratedPluginRegistrant.m:12:9: fatal error: module 'firebase_auth' not found
    @import firebase_auth;
     ~~~~~~~^~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in parallel
```

Note: It is working fine on android with the google_map_flutter package and without the package it is working fine on iOS

**Comment by danagbemava-nc** [comment]
Hi @pratikbaid3, thanks for filing the issue. 

Please provide the following
- full `flutter run -v`, output may be huge, so kindly put into a .txt file and attach it here
- `flutter doctor -v`
- `Podfile`
- `Podfile.lock`
- `project.pbxproj`
- `pubspec.lock`


Thank you
