### ISSUE TITLE
When multiple FlutterViewControllers share a Flutter engine, the keyboard pops up causing the page to freeze or even clutter

### ISSUE THREAD

**Issue by ylrs** [flutter/flutter#95961]
flutter sdk:  1.22.4

We solved this problem by overwriting the keyboardWillChangeFrame method in FlutterViewController, but hopefully it will be addressed directly in the new engine.
![image](https://user-images.githubusercontent.com/3962127/147752608-8c999813-0305-4c44-950b-5a6bf48478bf.png)

**Comment by maheshmnj** [comment]
Hi @ylrs, Thanks for filing the issue.

> flutter sdk: 1.22.4

You are using a very older version of flutter, unfortunately, we do not provide support to older versions. I would suggest you to please upgrade to latest stable version `2.8.1` using `flutter upgrade` and see if that fixes the issue.
If you still encounter the issue, please share the updated output of `flutter doctor -v` and steps to reproduce the issue along with a minimal and complete reproducible code sample.

Thank you.
