### ISSUE TITLE
Unwanted iOS15 pasting from clipboard info when interacting with TextField

### ISSUE THREAD

**Issue by koral--** [flutter/flutter#95964]
## Steps to Reproduce

1. Have some text in pasteboard
2. Execute `flutter run` on the code sample
3. Type something in TextField

Issue seems to occur on iPads with iOS 15.x - all such tested simulators and physical devices are affected (not only particular simulator from logs).
Issue was not reproducible on other devices like iPhones, iPods both physical and simulators, various iOS versions.
Issue occurs with default keyboard configuration (both on simulator and iOS guest settings side). Not only typing but just focusing/clicking on TextField also causes pop-up. Changing some keyboard settings (in iOS settings app) also causes that pop-up even though affected app is in background.
Issue does not occur if keyboard is in minimized mode. Also after disabling all the switches in iOS settings it stopped occurring.

Possibly related to: https://github.com/flutter/flutter/issues/60145

**Expected results:**
No pop-up is shown when interacting with TextField.

**Actual results:** 
`<my app> pasted from <source app>` pop-up is shown.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) => const MaterialApp(home: Scaffold(body: TextField()));
}

```

</details>

<details>
  <summary>Logs</summary>

No logs are produced during app run time.

```
% flutter analyze      
Analyzing untitled...                                                   
No issues found! (ran in 2.6s)
```

```
% flutter doctor -v    
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale en-US)
    • Flutter version 2.8.1 at /usr/local/Caskroom/flutter/2.2.0/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (2 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/koral/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • ANDROID_SDK_ROOT = /Users/koral/Library/Android/sdk
    • Java binary at: /Users/koral/.sdkman/candidates/java/current/bin/java
    • Java version OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.2+7)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • iPad Pro (12.9-inch) (5th generation) (mobile) • (stripped) • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)                                   • chrome                               • web-javascript • Google Chrome 96.0.4664.110

```

</details>

Video
https://user-images.githubusercontent.com/3340954/147751289-959355b4-07d9-4ce5-8ee1-c28d72577cda.mp4

**Comment by darshankawar** [comment]
@koral-- 
Have you already tried this on latest master to see if there too the behavior persists ?

```
flutter channel master
flutter upgrade
```

**Comment by koral--** [comment]
Indeed on master it does not happen.
Which existing issue/PR/commit caused this change so I can track that?

**Comment by darshankawar** [comment]
Thanks for confirming. This is the PR that fixed the issue and merged in master, https://github.com/flutter/flutter/pull/87678
Closing as this is already fixed.

**Comment by zambetpentru** [comment]
Greetings @darshankawar, I just came across the same issue and it is indeed fixed in master. My question is about the PR that you linked to above, is that the one as it appears to have been merged back in August?
