### ISSUE TITLE
'package:flutter/src/widgets/binding.dart': Failed assertion: line 849 pos 12: 'debugBuildingDirtyElements': is not true.

### ISSUE THREAD

**Issue by Souryadeep0325** [flutter/flutter#95971]
'package:flutter/src/widgets/binding.dart': Failed assertion: line 849 pos 12: 'debugBuildingDirtyElements': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

This is happening for any code be it the default dart code in flutter

**Comment by maheshmnj** [comment]
Hi @Souryadeep0325, Thanks for filing the issue. Please share the output of `flutter doctor -v` and steps to reproduce the issue.
