### ISSUE TITLE
Document why `TextEditingValue` constructor with no parameters creates an invalid selection.

### ISSUE THREAD

**Issue by marcglasberg** [flutter/flutter#95978]
Any reason why the constructor with no parameters creates an invalid selection, with `offset: -1`?

```
  const TextEditingValue({
    this.text = '',
    this.selection = const TextSelection.collapsed(offset: -1),
    this.composing = TextRange.empty,
  }) : assert(text != null),
       assert(selection != null),
       assert(composing != null);
```

This should be the same as clearing it:

```
void clear() {
    value = const TextEditingValue(selection: TextSelection.collapsed(offset: 0));
  }
```

So that these are equivalent:

```
controller.clear();
controller.value = const TextEditingValue();
```

If there is a valid reason for the constructor with no parameters to create an invalid object, this should be clearly stated in the docs.

**Comment by justinmc** [comment]
This `-1,-1` selection value has given me a lot of trouble as well.  Besides being confusing and poorly defined, there have been bugs where math was done on a `-1` from an invalid selection without realizing it.  There was an attempt to get rid of it and make selection nullable by @LongCatIsLooong (https://github.com/flutter/flutter/pull/79615), but it unfortunately ended up affecting more than expected.

If we can't clean the code up for now then I agree with you that we should clearly document it.  I've added a quick explanation in https://github.com/flutter/flutter/pull/96245.  Let me know what you think of it and if I should include anything else.

**Comment by marcglasberg** [comment]
@justinmc 

Why can't it be `offset: 0`? My suggestion:

```
const TextEditingValue({
    this.text = '',
    this.selection = const TextSelection.collapsed(offset: 0),
    this.composing = TextRange.empty,
  }) : assert(text != null),
       assert(selection != null),
       assert(composing != null);
```

**Comment by justinmc** [comment]
That would mean that the default is for a collapsed selection at the start of the field, whereas now the default is no selection.  Both sound fairly reasonable and it would be nice to be in sync with `clear`.  I'm not sure if changing it would break anything though.

**Comment by marcglasberg** [comment]
Running the tests should show us if something breaks.
