### ISSUE TITLE
[Proposal] Support for Shared data from other apps

### ISSUE THREAD

**Issue by kidsonfilms-python-rules** [flutter/flutter#95983]
## Use case

In the past, I have developed a simple [package](https://pub.dev/packages/sharer) to allow sharing data from other apps (such as YouTube) from the Share Menu to a Flutter app. I have learned that most of the code is found in the Android Java/Kotlin files or iOS Objective-C/Swift files. This makes it harder to implement as a package since it requires much less package support while it can still be easily bundled in Flutter itself, as it is a native Android or iOS feature.

## Proposal

My proposal is to integrate this into Flutter and have a small library of functions that can decode these shared messages (e.g. links, images, other media)

I have done an example of code (for Android) for sharing from my plugin which you can see below:
```xml
<!-- AndroidManifest.xml -->
<intent-filter>
            <action android:name="android.intent.action.SEND"/>
            <category android:name="android.intent.category.DEFAULT"/>
            <data android:mimeType="text/*"/>
            </intent-filter>
```
```java
// MainActivity.java
public class MainActivity extends FlutterActivity {
  ...

  private String sharedText;

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    // GeneratedPluginRegistrant.registerWith(this);
    Intent intent = getIntent();
    String action = intent.getAction();
    String type = intent.getType();

    if (Intent.ACTION_SEND.equals(action) && type != null) {
      if ("text/plain".equals(type)) {
        handleSendText(intent); // Handle text being sent
      }
    }

    new MethodChannel(getFlutterView(), "SharerPlugin").setMethodCallHandler(
      new MethodCallHandler() {
        @Override
        public void onMethodCall(MethodCall call, MethodChannel.Result result) {
          if (call.method.contentEquals("getSharedText")) {
            result.success(sharedText);
            sharedText = null;
          }
        }
      });
  }

  void handleSendText(Intent intent) {
    sharedText = intent.getStringExtra(Intent.EXTRA_TEXT);
  }
}
```
This feature would better help apps such as Messaging apps that could use this and not be bombarded with custom native plugins that need to be developed.

**Comment by maheshmnj** [comment]
Hi @kidsonfilms-python-rules, Thanks for filing the issue. There is a flutter_community plugin [share +](https://pub.dev/packages/share_plus) that helps you share files and text across apps would that help?

**Comment by kidsonfilms-python-rules** [comment]
Hi @maheshmnj 
From what I can tell, share_plus is used to share data **from** a flutter app to another external app. What I am proposing is the opposite, allowing other external apps to share content **to** your app, by having it registered in the platform's Share UI Menu.

For example, in the below screenshot is of the YouTube mobile app share screen. What I am proposing is having a Flutter app registered there (so it would show in that menu and have the ability to be selected) and having the native code built-into flutter to decode the shared data once the application launches from being selected (as it does for natively built applications)

![Screenshot_20211230-234041_YouTube.jpg](https://user-images.githubusercontent.com/58677791/147810412-ed6cd805-bae4-4cb6-aebc-16fddb59c0fc.jpg)

An example of shared data would be a link of a video from YouTube, or an image from the phone's gallery app and you can use that data inside of the Flutter app.

**Comment by maheshmnj** [comment]
Ah, I see thanks for the clarification. But I believe this can be achieved with a third-party plugin like https://pub.dev/packages/receive_sharing_intent.

**Comment by kidsonfilms-python-rules** [comment]
hi @maheshmnj sorry for the late reply

I'm proposing it be built into the framework since the plugin (which is not their fault, it's impossible otherwise) requires a ton of editing in native files such as the MainActivity.java, and it could be very daunting to Flutter-mainly developers and they could easily mess up. This is also a pretty basic native feature that should be included.

**Comment by maheshmnj** [comment]
Thanks for the info @kidsonfilms-python-rules.

**Comment by chinmaygarde** [comment]
This issue is in the domain of plugins. 

> requires a ton of editing in native files such as the MainActivity.java

While plugin authorship required editing native files, using plugins does not. In any case, we don't want to bloat the base engine with functionality that should be in a plugin in the first place. Closing as wont-fix.

cc @stuartmorgan Is there a plugins wishlist that I can add this to? As it stands, I don't think this is a good candidate for adding to the engine as something that is built-in.

**Comment by stuartmorgan** [comment]
> using plugins does not

In this case it does (especially on iOS; see the README for https://pub.dev/packages/receive_sharing_intent). But I don't really understand what the proposal here is in terms of the engine that would solve that.

> cc @stuartmorgan Is there a plugins wishlist that I can add this to?

We just use proposal issues. But I don't see how a 1P plugin would be useful here given https://pub.dev/packages/receive_sharing_intent. We generally don't re-invent existing plugins.
