### ISSUE TITLE
[animation] `CupertinoPageRoute`'s pop animation is janky with 2.8 on iOS

### ISSUE THREAD

**Issue by AlexV525** [flutter/flutter#95986]
Could be related to #91937. The same animation is working well with 2.5.

## Step to reproduce

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(title: 'Test App Demo', home: _Page());
  }
}

class _Page extends StatefulWidget {
  const _Page({Key? key}) : super(key: key);

  @override
  _PageState createState() => _PageState();
}

class _PageState extends State<_Page> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('$hashCode')),
      body: Center(
        child: TextButton(
          onPressed: () {
            Navigator.of(context).push<void>(
              CupertinoPageRoute<void>(builder: (_) => const _Page()),
            );
          },
          child: const Text('Test push'),
        ),
      ),
    );
  }
}
```
</details>

1. Run this code example on iOS devices, no matter with debug/profile/release mode.
2. Press the "Test push" button, wait until the page route animation is finished.
3. Swipe the page from left to right, which is the same behavior with iOS native.
4. The janky animation should be shown now.

https://user-images.githubusercontent.com/15884415/147801673-e8d3a25a-83d0-40af-aeea-0941b15fc540.mp4

#### Additional steps

1. If you complete the swipe with no pauses during the swipe, the animation will keep janky in the whole process.
2. Once you paused during the swipe, hold the pressing for a while then continue the swipe, the animation will become smooth as before.

https://user-images.githubusercontent.com/15884415/147801685-6792defa-2d6a-4424-8f4c-d69c7da3ee68.mp4

## Environments

**Target Platform:** iOS, and only happened on iOS devices.
**Target OS version/browser:** iOS 15.2 (shouldn't matter in this case)
**Devices:** iPhone 12

This is reproducible on the latest master too.

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.8.1 at /Users/alex/Documents/flutter-stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (2 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1
```

**Comment by SuhwanCha** [comment]
Sometimes , it looks janky on push too.

Device: iPhone SE2 , iOS 15.2

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale
    en-KR)
    • Flutter version 2.8.1 at /Users/suhwancha/development/GitHub/flutter
    • Upstream repository git@github.com:SuhwanCha/flutter.git
    • Framework revision 77d935af4d (2 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1
```

**Comment by willlockwood** [comment]
FWIW, I have been working recently to improve some fidelity stuff on this animation (see: https://github.com/flutter/flutter/pull/95537), and while working on that, I've noticed that with the updated edge shadow gradient, I **_think_** there should be easy performance wins to be had by refactoring the custom shadow drawing done here: https://github.com/flutter/flutter/blob/384c40e60615177a96134428cf59eb6026cd2022/packages/flutter/lib/src/cupertino/route.dart#L910-L962

This would be the case because the new gradient will be much simpler (only a few possible color values, and probably some possibility of drawing far fewer, wider boxes for each color rather than drawing a lot of 1px boxes)

**Comment by AlexV525** [comment]
> I could be wrong, if I'm misdiagnosing where this jank is coming from, but if I'm seeing it correctly, those performance wins would come from the new gradient being simpler to draw (only 4 possible color values, and probably some possibility of drawing far fewer, wider boxes for each color rather than drawing a lot of 1px boxes)

In my imagination, if there's a problem with painting, then the whole process would be janky, or the animation at some specific positions should be janky. But in this issue, the animation will become smooth once we paused at any positions. It's more like a control flow issue. Hard for me to find the combination between your thoughts and this one at present.

**Comment by willlockwood** [comment]
The connection is tenuous and circumstantial because I don't understand very much of the dynamics of what kinds of things cause what kinds of visible performance issues. I figured I saw something recently that seemed like it could reduce the complexity of some drawing during this animation, so it might be related. If you see that as a likely unrelated operation, I'm content with that conclusion 👍🏻

**Comment by nt4f04uNd** [comment]
https://github.com/flutter/flutter/issues/95838 might be related

**Comment by brianschardt** [comment]
I am experiencing this too on 2.8 not on 2.5

**Comment by AlexV525** [comment]
> #95838 might be related

Now I'm more considering if some scrollable basic infrastructures have regressions.

**Comment by jonataslaw** [comment]
This is definitely an issue for 2.8 or higher. 2.8.1 gás the same problem

**Comment by eggfly** [comment]
Maybe we can checkout to master branch and use `git bisect bad` and `git bisect good` command and compile the demo project for about 10+ times to help us find out the which is exactly the regression  commit. This method is not slow because is log2(N) and quick enough to find the root cause. We can find it by using bisect whether engine or framework commits.

**Comment by jmagman** [comment]
@willlockwood See https://github.com/flutter/flutter/issues/75789 and https://github.com/flutter/flutter/pull/75670 for why gradients were removed.

@eggfly If you can reliably reproduce this issue, bisecting would be helpful.

**Comment by AlexV525** [comment]
> Maybe we can checkout to master branch and use `git bisect bad` and `git bisect good` command and recompile and test the demo project for about 10+ times to help us find out the which is exactly the regression commit. This method is not slow because it is a log2(N) method and quick enough to find the root cause. We can find it by using bisect whether engine or framework commits.

Great idea. So I've done `bisect` from 81b963f to 01d0c53, and found the first bad commit that reproduces this issue is 01fc74e, which is an engine roll introduced by #90980. From the roll list, I think the most possible relation would be flutter/engine#28817. /cc @iskakaushik

**Comment by chinmaygarde** [comment]
Can you please attach a timeline trace of the scene in both versions (before and after the regression)?

**Comment by Ec7i9se** [comment]
Tested on 2.10.0-0.1.pre same effect, not fixed. Its critical issue since app no longer feels like native(( Tested ios 14.4.2 iPhone 12 pro. NOT reproducible on Android.  Xcode 13.2

**Comment by ezorrio** [comment]
@jmagman Facing the same issue. Trace from profile build attached
[dart_devtools_2022_1_19-1642611545228000.json.zip](https://github.com/flutter/flutter/files/7899050/dart_devtools_2022_1_19-1642611545228000.json.zip)
d

**Comment by AlexV525** [comment]
@chinmaygarde @jmagman 

- `01fc74e4`: [01fc74e4_dart_devtools_2022_1_25-1643093291088000.json.zip](https://github.com/flutter/flutter/files/7931236/01fc74e4_dart_devtools_2022_1_25-1643093291088000.json.zip)
- `2367a177`: [2367a177_dart_devtools_2022_1_25-1643092943162000.json.zip](https://github.com/flutter/flutter/files/7931238/2367a177_dart_devtools_2022_1_25-1643092943162000.json.zip)

**Comment by Ec7i9se** [comment]
@jmagman @chinmaygarde Good day! Sorry for late response. Right now tested on 2.10.0-0.2.pre, unfortunately the error presents. My timetrace(have i exported right thing?). I see, frames generation time not soo big but everyone see this freezes. Also attached videos, so you can see the gaps between page edge on each render frame on 2.5 and 2.10. On video it feels like it's not big deal but in real life it is, everyone said me that it's too bad. Unfortunately can't test in on iOS15 hardware. But on ios 14 it presents. Tested on iPhone 7 ios 13.4.1, also freezes.

[2.5_dart_devtools_2022_1_27-1643232934321000.txt](https://github.com/flutter/flutter/files/7945973/2.5_dart_devtools_2022_1_27-1643232934321000.txt)
[2.10.2_dart_devtools_2022_1_27-1643233685817000.txt](https://github.com/flutter/flutter/files/7945974/2.10.2_dart_devtools_2022_1_27-1643233685817000.txt)

2.5

https://user-images.githubusercontent.com/39343708/151256616-840dfa1f-0cea-4dc9-b199-0ca2b5d0ae40.MP4

2.10.2

https://user-images.githubusercontent.com/39343708/151256687-7c5aea9e-552a-499b-b907-383b01ff9350.MP4

If i can help some how, ask me

Best wishes!!

**Comment by Ec7i9se** [comment]
Not fixed in 2.10.0-0.3.pre. May i not to attach videos and timetraces :D

**Comment by b3nni97** [comment]
Is there anything you can currently do about the lags? Flutter version >= 2.8 are very janky on iOS no animation runs without frame drops. This currently keeps us from being able to release our app.

**Comment by Ec7i9se** [comment]
I've tested on 2.10.0 stable. Interesting behaviour, sometimes it stared to animate smooth. But the most cases are still laggy. This case is laggy
`
import 'dart:io';

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

@override
  Widget build(BuildContext context) {
    // TODO: implement build
    return CupertinoApp(
      home: Page1(),
    );
  }
}


class Page1 extends StatelessWidget {
  const Page1({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(

      backgroundColor: Colors.amber,
      child: Center(
        child: GestureDetector(
          onTap: () {
            Navigator.of(context).push(CupertinoPageRoute(builder: (context) => Page2(), title: "Page 2"));
          },
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Text("Page 1"),
            ],
          )
        ),
      ),
    );
  }
}

class Page2 extends StatelessWidget {
  const Page2({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(

      backgroundColor: Colors.white,
      child: Center(
        child: GestureDetector(
            onTap: () {
              Navigator.of(context).push(CupertinoPageRoute(builder: (context) => Page2(), title: "Page 2"));
            },
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Text("Page 1"),
              ],
            )
        ),
      ),
    );
  }
}



`

**Comment by desmeit** [comment]
I have extreme problems with 15.3. The animation for Bottom Sheet is extremely janky.

**Comment by AlexV525** [comment]
Raising the priority again for further investigation.
