### ISSUE TITLE
Your app is missing support for the following URL schemes

### ISSUE THREAD

**Issue by alpitilanam** [flutter/flutter#95999]
<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>com.googleusercontent.apps.xxxxxxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxl</string>
			</array>
		</dict>
	</array>
	
	
	I have used the above formate and also copied from GoogleService-Info.plist key REVERSED_CLIENT_ID. but still getting the " **Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Your app is missing support for the following URL schemes**:" Issue.
	In android, Google sign in is completely working but getting problem in IOS.

**Comment by darshankawar** [comment]
@alpitilanam 
Please see if you have the format correct ie, spaces and there are not additional spaces while trying to add the entry in the plist.
Also, try the google_sign_in plugin [example](https://github.com/flutter/plugins/tree/master/packages/google_sign_in/google_sign_in/example) or clone the flutter packages and then try to run the plugin example and see if you still get same behavior.
If yes, provide your `flutter doctor -v` and plugin version you are using.

**Comment by alpitilanam** [comment]
Thank you for the response @darshankawar,
I have already follow the same example but still getting the issue.

**Comment by darshankawar** [comment]
> If yes, provide your `flutter doctor -v` and plugin version you are using.

@alpitilanam
