### ISSUE TITLE
Checkboxes don't act like material widgets

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#96]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Friday Jul 17, 2015 at 22:45 GMT_
_Originally opened as https://github.com/flutter/engine/issues/104_

----

_From @Hixie on May 12, 2015 19:25_

The checkbox control doesn't have a splash around it when you tap it.

_Copied from original issue: domokit/mojo#163_

**Comment by FlutterIssues** [comment]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Hixie](https://github.com/Hixie)**
_Friday Jul 17, 2015 at 22:45 GMT_

----

_From @eseidelGoogle on June 8, 2015 20:15_

Fixed, no?

**Comment by FlutterIssues** [comment]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Hixie](https://github.com/Hixie)**
_Friday Jul 17, 2015 at 22:45 GMT_

----

_From @collinjackson on June 8, 2015 22:15_

I think ink splashes aren't implemented generally. Happy to work on that

**Comment by Hixie** [comment]
@abarth did this recently.
