### ISSUE TITLE
I want to hide the video progress indicator when not tapping or dragging.

### ISSUE THREAD

**Issue by kang86h** [flutter/flutter#96008]
I made an app that overlays a linear video progress indicator on a video player so that it can be dragged.

And I wanted to make the progress indicator disappear after a few seconds when not touched.

I first used the gesture detector on the container containing the indicator and set the HitTestBehavior to translucent.

I tried both stack and child data structures, and in the case of stack, I tried changing the order of each other, but I couldn't take any interaction other than the original function of the indicator.

How to implement an indicator that disappears after a few seconds when there is no touch?

**Comment by darshankawar** [comment]
@kang86h 
Your question is better suited for support channels like StackOverflow, so please ask the same there.
Closing from here as this is more of a `how to` question rather than a bug or feature request.
