### ISSUE TITLE
[Documentation] update `InteractiveViewer.builder` example to make it more performant

### ISSUE THREAD

**Issue by alelazar** [flutter/flutter#96005]
## Details

[https://api.flutter.dev/flutter/widgets/InteractiveViewer/builder.html](https://api.flutter.dev/flutter/widgets/InteractiveViewer/builder.html)

On line 114, change the `rowCount: 60` to anything small yet reasonable, like 250. Observe the scroll functionality drop to single digit framerate.

Not quite as small, but still reasonable values like 1,000 drop to fractional frames per second. 10,000 crashes the page on scroll. Debug lowers these thresholds but they are still quite apparent even in a release build.

Obviously, a list like this should be using more specialized widgets like Slivers. However the documentation, the original issue (#58603), the PR that added it (#77414) all talk about this as a performance constructor. This doesn't seem feasible in the current form.

EDIT: Removed some stuff now that I realized that `Positioned` works to turn the builder form into a viewport. It would be nice to have this better documented and perhaps available in a more explicit manner. 

`justinmc` thanks for all your work on making `InteractiveViewer` as powerful and easy to use as it currently is. 

**Target Platform:**
Web

**Target OS version/browser:**
OSX, both Chrome and Firefox

**Devices:**
Macbook Pro

**Comment by alelazar** [comment]
Based on the official [youtube video](https://www.youtube.com/watch?v=qax_nOpgz7E) on this builder form, the simple builder in the example is intended more for heavy cells rather than a large number of cells. 

It looks like using this form to have a "pure viewport" is possible by using `Positioned`. I had tried that but run into errors around layout: `NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE`. Will try again with this solid example.

That video is often not even on the first page of search results regarding interactive viewer builder - it's a lot more useful than the `go` example.

**Comment by alelazar** [comment]
#87370 seems to be building towards something similar

**Comment by alelazar** [comment]
That PR to update the example code should make it clearer for others in the future. 

Again, apologies if I missed something about this.

**Comment by HansMuller** [comment]
CC @justinmc
