### ISSUE TITLE
Issue closing AlertDialog box

### ISSUE THREAD

**Issue by gaurav1903** [flutter/flutter#96016]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2.  You can see the code below in code sample

**Expected results:** 
I was expecting that alertbox would close on pressing the complete details buttonn
**Actual results:** 
It didn't close ,,however the other lines in the function ran correctly
<details>
<summary>Code sample</summary>

```
Future<dynamic> givealert() async {
    BuildContext _context = context;
    return showDialog(
        context: context,
        builder: (ctx) => AlertDialog(
                title: Text("ALERT : Incomplete Details",
                    style: TextStyle(color: Colors.red)),
                actions: [
                  TextButton(
                      onPressed: () {
                        setState(() {
                          value = 4;
                        });
                        Navigator.of(_context, rootNavigator: true).pop();
                      },
                      child: Text("Complete details"))
                ]));
  }
```

</details>
So the value of "value" changes to 4 successfully on pressing button.
<details>
  

So far i have tried Navigator.of(context).pop();
Navigator.of(ctx).pop()
and the one in the example

None worked

**Comment by willlockwood** [comment]
Can you give a more complete example? I've copied your sample into the counter app and am not able to reproduce.

**Comment by gaurav1903** [comment]
i was accidentally running the function twice so i was getting 2 alertboxes on top of each other that's why it was taking more than one tap on the button to close..
Sorry for the trouble
