### ISSUE TITLE
There are errors in other files that have not been handled, but the codes that need to be used in the main function have no errors. How to force the main function to run in the IDEA editor? 

### ISSUE THREAD

**Issue by ddxl123** [flutter/flutter#96029]
There are errors in other files that have not been handled, but the codes that need to be used in the main function have no errors. How to force the main function to run in the IDEA editor? 

Every time I test a partial code, I need to comment out all the errors. Sometimes a lot of errors are reported, and the modification range is relatively large, and the comments are too troublesome.

**Comment by maheshmnj** [comment]
Hi @ddxl123, Thanks for filing the issue. 
 > There are errors in other files that have not been handled, but the codes that need to be used in the main function have no errors. 
 
Make sure your main file does not have imports of files that have errors and it should build fine.

Closing as this is neither a bug nor a feature request related to flutter framework..
