### ISSUE TITLE
Debugging iOS 14 background message (when the app is closed)

### ISSUE THREAD

**Issue by yoniker** [flutter/flutter#96038]
Trying to build a chat app, which gets FCM messages and shows notifications even when the app is closed.
Clearly something in my top level handleBackgroundMessages function for FCM is wrong as the notifications are not showing (on a physical device- iOS emulators don't work with FCM).

In Android I've debugged a similar situation with adb logcat (and logs/print command).
Obviously adb isn't available for an iPhone, and I don't know how to see the logs after the app is closed (I've tried to look at the console at xcode but no Flutter messages are showing).
Because I can't run the app again after it's closed (see https://docs.flutter.dev/development/ios-14 the application can no longer be re-launched by tapping the application’s icon) I'm installing it on my device via "flutter install release". 

How do I see the logs after install release, or otherwise how can I debug functionality (at least view flutter logs) when app is closed?

**Comment by darshankawar** [comment]
@yoniker 
Since you seem to be using firebase_messaging plugin, it has a different repo for tracking: https://github.com/FirebaseExtended/flutterfire/issues.


> How do I see the logs after install release, or otherwise how can I debug functionality (at least view flutter logs) when app is closed?

You can run the app in `--verbose` mode to see the logs. As far as debugging when app is closed, there should be a method in firebase_messaging to check whether the app is closed and what to do when it is the case.
Closing from here, as this isn't a Flutter issue.

**Comment by yoniker** [comment]
Running the app in --verbose doesn't give me any logs after the app is closed, as explained in the original question.
 
"there should be a method in firebase_messaging to check whether the app is closed" - it is not the plugin's responsibility to enable me to see logs from Flutter. And of course it doesn't. It's Flutter's responsibility to enable the user to (at minimum) view logs.

Reopen the issue, as your answer seems to be invalid.
