### ISSUE TITLE
Listener widget used in package doesn't work only on iPhone X and earlier iPhones

### ISSUE THREAD

**Issue by taku-kw** [flutter/flutter#96042]
I used package of "gesture_x_detector".
https://pub.dev/packages/gesture_x_detector

But I discovered that its callback of onTap in the package doesn't work only on iPhone X and earlier iPhones.
Upon investigating, I found that it was created by the Listener widget.
https://github.com/taodo2291/xgesture_flutter/blob/c9dfedfcee294a5281fed55e8b7523b65ced4f98/lib/gesture_x_detector.dart#L119

For further investigation, I put "gesture_x_detector" **as a local file** in my project.
Just doing so, onTap worked on the iPhones.
In other words, just doing so, Listener widget works on the iPhones.

I would like you to teach me about the cause.
Also, the solution when using "gesture_x_detector" **only as package**.

---

For reference, followings is the repository created in the investigate.
* I used "gesture_x_detector" as package (Doesn't Work only on iPhone X and earlier iPhones.)
https://github.com/taku-kw/x_gesture/tree/main
* I used "gesture_x_detector" as local file (Works including iPhone X and earlier iPhones.)
https://github.com/taku-kw/x_gesture/tree/x-gesture

**Comment by darshankawar** [comment]
@taku-kw 
Can you provide a minimal complete code sample without the said package, that shows the behavior ?

**Comment by taku-kw** [comment]
@darshankawar 
> Can you provide a minimal complete code sample without the said package, that shows the behavior ?

Here you are.
https://github.com/taku-kw/x_gesture/tree/x-gesture

**Comment by darshankawar** [comment]
@taku-kw 
What's the expected result you are looking for upon running the code ?

**Comment by taku-kw** [comment]
@darshankawar 
> What's the expected result you are looking for upon running the code ?
I expect that when I tap on display, tapped position change color of red.

> Is it only happening on iphone X and earlier simulators or on devices too ?
I confirmed only simulators, didn't device.

**Comment by darshankawar** [comment]
@taku-kw 
I verified on iOS simulator (12 Pro max) and observed that sometimes it recognizes the tap on single tap and sometimes on double tap, ie, you have to double tap to see the red dot. Have you notices this already ?

**Comment by taku-kw** [comment]
@darshankawar 
Yes, I recognize that is also a problem.
However, I haven't been able to investigate whether it is caused by the Listener widget.

**Comment by darshankawar** [comment]
@taku-kw 
I do see the same behavior upon running your code sample on iPhone 8 and 8 plus simulators, wherein, tapping or double tapping isn't recognized, but the same action is being recognized on iPhone 12 Prox max simulator.
I guess you are hitting [this](https://github.com/flutter/flutter/issues/72848), but exactly not similar case, but opposite of what's mentioned in the linked issue. Can you try [this](https://github.com/flutter/flutter/issues/72848#issuecomment-750918535) solution and see if it helps ?

**Comment by taku-kw** [comment]
@darshankawar 
As written there, I added SafeArea widget and tried.
https://github.com/taku-kw/x_gesture/tree/add_SafeArea

But unfortunately I confirmed that it doesn't work on iPhone 8 by simulator.

**Comment by darshankawar** [comment]
@taku-kw 
Can you try by framework's core `GestureDetector` instead of `XGestureDetector` from the package and see if it gives you same behavior ?

**Comment by taku-kw** [comment]
@darshankawar 
I created a branch that use GestureDetector instead of XGestureDetector.
https://github.com/taku-kw/x_gesture/tree/GestureDetector_instead

As a result, I confirmed that it works expectedly on iPhone 8 by simulator.
(I used onTapUp in GestureDetector to get tapped position.)

**Comment by darshankawar** [comment]
Thanks for verifying. Is it now safe to close as resolved ?, because the issue doesn't seem to occur using core framework widget, but using the third party plugin.

**Comment by taku-kw** [comment]
@darshankawar 
I'd like to have known cause that  the behavior of Listener widget is different between the package and the local file, 
but it's okay to close.

**Comment by darshankawar** [comment]
Closing based on above comment and unable to replicate using GestureDetector.
