### ISSUE TITLE
Flutter Multiplying double 0.0 by -1.0 gives -0.0 instead of 0.0 

### ISSUE THREAD

**Issue by hamzanajeeb-tp** [flutter/flutter#96056]
Code:
  
@override
Widget build(BuildContext context) {
  double num = 0.0;
  num = num * -(1.0);
  print('num');
  print(num); //  prints -0.0 instead of 0.0
  return Scaffold(
    appBar: AppBar(
      title: Text(widget.title),
    ),
    body: Center(
      child: Text(num.toString()) // Shows -0.0 on emulator and real device
  ));
}
![Screenshot from 2022-01-03 17-39-11](https://user-images.githubusercontent.com/61828976/147932704-acd4ff63-6ab7-42b5-ad2f-ad029088116b.png)

**Comment by stuartmorgan** [comment]
In the future please file bugs about Dart itself in the Dart issue tracker rather than the Flutter issue tracker.

However, this isn't a bug. Dart uses [IEEE-754](https://en.m.wikipedia.org/wiki/IEEE_754) doubles, which uses signed zeros.
