### ISSUE TITLE
WebView plugin not returning proper arrays from JS on iOS

### ISSUE THREAD

**Issue by mortenboye** [flutter/flutter#96053]
It seems that returning a JS array from a WebView widget using `runJavascriptReturningResult` does not return a well formatted array string on iOS, but it does on Android. 

Calling
`_webViewController?.runJavascriptReturningResult("function returnArray() { return [1, 2, 3];} returnArray();");`
returns

`[1,2,3]` on Android which is expected, but
`(1,2,3)` on iOS (Device and Simulator) which does not qualify as an array.

This is using `webview_flutter: ^3.0.0`

## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** The string "[1,2,3]" being returned.

**Actual results:** The string "(1,2,3)" being returned.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter WebView JS Array',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  WebViewController? _webViewController;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Flutter WebView JS Array'),
      ),
      body: WebView(
        initialUrl: '',
        javascriptMode: JavascriptMode.unrestricted,
        onPageFinished: (value) {
          print("page loaded - get array");
          _getArray();
        },
        onWebViewCreated: (webViewController) async {
          print("web view created");
          _webViewController = webViewController;
        },
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _getArray,
        child: const Icon(Icons.cloud_download),
      ),
    );
  }

  _getArray() async {
    var arrayString = await _webViewController?.runJavascriptReturningResult("function returnArray() { return [1, 2, 3];} returnArray();");
    print("ArrayString:\n$arrayString");
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
flutter: web view created
flutter: page loaded - get array
flutter: ArrayString:
(
    1,
    2,
    3
)
```

**Comment by danagbemava-nc** [comment]
Hi @mortenboye, please provide the version of `webview_flutter` you're using. 

Thank you

**Comment by stuartmorgan** [comment]
> `(1,2,3)` on iOS (Device and Simulator) which does not qualify as an array.

It does, just not a JSON array; it's the string representation of an NSArray. This is how WKWebView works, and is [the documented behavior](https://github.com/flutter/plugins/blob/master/packages/webview_flutter/webview_flutter/lib/src/webview.dart#L687-L695) of the plugin.

**Comment by mortenboye** [comment]
> > `(1,2,3)` on iOS (Device and Simulator) which does not qualify as an array.
> 
> It does, just not a JSON array; it's the string representation of an NSArray. This is how WKWebView works, and is [the documented behavior](https://github.com/flutter/plugins/blob/master/packages/webview_flutter/webview_flutter/lib/src/webview.dart#L687-L695) of the plugin.

I see, thank you.
