### ISSUE TITLE
Material Design Review requests Flutter Gallery target SDK 25+

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#9605]
"To be sure that the app is making use of all of the latest platform features/behaviors, be sure to use the latest targetSdkVersion (25 at this time). Currently, the app is @ API 21"

This was marked P2 so it will not block further Material Design Reviews, but seems easy enough to do?

**Comment by Hixie** [comment]
Not sure what this means exactly. @willlarche said he will look into it.

**Comment by willlarche** [comment]
We'll have to stay in rhythm with the Android SDK releases. There are occasionally small visual changes and the review here prevents those not getting adopted.

2018 is 26+ starting in [August](https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html). Every time it goes up, we need to go up if an app wants to get into the store.

We're already at 27 so no problems right now. If we resubmit, there shouldn't be a warning.
