### ISSUE TITLE
`flutter drive` confusingly different from `flutter run`: no build step?

### ISSUE THREAD

**Issue by mravn-google** [flutter/flutter#9606]
## Steps to Reproduce

On MacOS, developing a Flutter app. Android device plugged.

1. `$ flutter run`
1. Manually test app, find something to fix
1. Make code change
1. `R` restart app
1. Manually retest, works great now! So lets run the autottest...
1. `q` stop app
1. `$ flutter drive`
1. Be confused.
1. `$ flutter run`
1. Be more confused.

Observe: the app launched by `flutter drive` does not include the change made in step 3 above. Neither does the app launched by the subsequent `flutter run`.

## Flutter Doctor

```
[✓] Flutter (on Mac OS X 10.12.4 16E195, channel master)
    • Flutter at /Users/mravn/github/flutter
    • Framework revision 3c7e176a99 (21 hours ago), 2017-04-25 16:08:55 +0200
    • Engine revision a5b64899c9
    • Tools Dart version 1.23.0-dev.11.11

[✓] Host Executable Compatibility
    • Downloaded executables execute on host

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/mravn/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.2, Build version 8E2002
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2016.3.4)
    • Dart plugin version 163.13137
    • Flutter plugin version 12.0

[✓] WebStorm (version 2017.1.1)
    • Flutter plugin version 13.0

[✓] Connected devices
    • Nexus 5X • 00bff34682e4b2ab • android-arm • Android 7.1.2 (API 25)
```

**Comment by Hixie** [comment]
This doesn't fit our current priorities, so moving to the next milestone.

@sethladd This seems like a major bug, if it's still present; we might want to consider tweaking our priorities to allow this kind of thing to be included.

**Comment by sethladd** [comment]
@mit-mit would have a better idea here, but all things considered, I can imagine a simple fix is to be more aggressive with our rebuild logic. Better to be correct and slow, then fast and incorrect.

The work around for this in the meantime is "flutter clean && flutter build && flutter drive", yes?

**Comment by Panthro** [comment]
@mit-mit I'm current using `flutter clean && fluter drive`

**Comment by jonahwilliams** [comment]
Flutter drive currently includes a build step
