### ISSUE TITLE
Minor detail missing in CodeLab "Write Your First Flutter App, part 2" step 7

### ISSUE THREAD

**Issue by hendrikmattern** [flutter/flutter#96062]
Hi,

I'm currently working my way through the above mentioned Codelab. While this is an excellent tutorial, I noticed that in step 7 ("Change the UI using themes"), it is not mentioned explicitly that the `const` before `MaterialApp` has to be removed. Hence, if someone just adds the new lines of code to adapt the UI an error occurs. Therefore, a short notice in the documentation that the MaterialApp is no longer constant would be helpful for some users who do the changes "manually" instead of using copy&paste.

Many thanks

**Comment by domesticmouse** [comment]
Fixed: https://codelabs.developers.google.com/codelabs/first-flutter-app-pt2
