### ISSUE TITLE
[Proposal] Document availabilty of icons in a Flutter release

### ISSUE THREAD

**Issue by bernaferrari** [flutter/flutter#96064]
With Google Fonts constantly adding and removing fonts, it is hard to know which fonts are supported or not in Flutter.

Yesterday I wanted 'terminal' icon, it shows on the website but it is nowhere in Flutter (and I'm on Flutter Beta). Probably the next time icons are refreshed it will be there.

Meanwhile, icons such as Facebook, Adobe and WeChat were removed from the website but are still present on Flutter. Many things are unclear.

![image](https://user-images.githubusercontent.com/351125/147949651-482c0add-684b-4fd7-8428-d16e34889682.png)

**Comment by maheshmnj** [comment]
Hi @bernaferrari, Thanks for reporting, I agree there should be some clarity about the availability of material icons in a flutter version.

**Comment by werainkhatri** [comment]
I know this may not be as interactive as Google Fonts, but the [Icons](https://api.flutter.dev/flutter/material/Icons-class.html)' API Doc does document the available material icons. For the master branch, [this](https://master-api.flutter.dev/flutter/material/Icons-class.html) can be referred to.

**Comment by bernaferrari** [comment]
Oh, sure. But it is too time-consuming to see if it is in Flutter, what Flutter version contains it and why my version doesn't. Wish Google Fonts just showed 'not available in Flutter yet'.

**Comment by willlarche** [comment]
Adding @guidezpl . Is the goal to know version-by-version or just to make sure that Flutter is as up-to-date as possible? Because we can hopefully work with Fonts on the workflow there but it would always go into `Master`. Otherwise it's a front end of fonts.google.com change that's needed to give more info?

**Comment by bernaferrari** [comment]
My goal is to be able to see if the font I want is coming soon or will still take a while. Maybe having master + release comparison could be good enough, just saying (you need channel master for this font instead of stable) could help.

**Comment by willlarche** [comment]
Would a minimum Flutter version availability number be useful? like "🍄 _2.1.3_"

**Comment by bernaferrari** [comment]
Yeah. But for me what matters most is the channel. If you put '2.1.3-pre-beta' it would be useful.

**Comment by willlarche** [comment]
Thanks. Can't make any promises but we'll investigate. Thanks for using the icons!

**Comment by guidezpl** [comment]
Hi, the Google Fonts web team is responsible for the integration, so feedback can be filed via the website. For the Flutter side of things:
* https://master-api.flutter.dev/flutter/material/Icons-class.html lists icons available on the master channel 
* https://api.flutter.dev/flutter/material/Icons-class.html lists the icons available on the stable channel
* the [source file](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/icons.dart) for any version can be searched

Additionally, the merge commit for PRs adding icons lists all versions those icons are a part of (see https://github.com/flutter/flutter/wiki/Where%27s-my-Commit%3F), e.g.: 
<img width="389" alt="Screen Shot 2022-01-07 at 10 52 29" src="https://user-images.githubusercontent.com/6655696/148526131-0a4943f0-f95c-43c2-b6a8-f44df218e4fd.png">

Regarding `terminal_outlined`, it was added by the latest update https://master-api.flutter.dev/flutter/material/Icons/terminal_outlined-constant.html

All in all, I think it's sufficiently documented.

**Comment by bernaferrari** [comment]
> Google Fonts web team is responsible for the integration, so feedback can be filed via the website.

Yeah, but it is not public, so I'll never know what happened nor be able to discuss it, like here where we were talking about which branch is relevant.

> the merge commit for PRs adding icons lists all versions those icons are a part of
It is, but shall I manually search through the commit list and master list and stable list to see where the icon belongs? I think it would be easier for Google Fonts to just have a link "check if Flutter has this icon" or "check which branches this is", because right now you spend 5 minutes finding where the icon is.

**Comment by guidezpl** [comment]
There is an opportunity here to add `https://beta-api.flutter.dev/` but I don't know how much additional work that would involve. 

> It is, but shall I manually search through the commit list and master list and stable list to see where the icon belongs? I think it would be easier for Google Fonts to just have a link "check if Flutter has this icon" or "check which branches this is", because right now you spend 5 minutes finding where the icon is.

You can enter the icon name in th API docs search box to find out instantly whether an icon is available. 

> The icon page froze my browser (in PC) and the GitHub thing doesn't even show without 'raw'. It is too heavy and all I want is to know where is a single icon.

The APi docs definitely shouldn't freeze and I've never run into this, so it would be helpful to file a bug report with more details on flutter/website! I'm not sure why searching https://raw.githubusercontent.com/flutter/flutter/master/packages/flutter/lib/src/material/icons.dart is a problem

**Comment by bernaferrari** [comment]
This is probably going to be deprecated with Material Symbols https://github.com/flutter/flutter/issues/102560.
