### ISSUE TITLE
 FluxStore Listing - facebook login issue 

### ISSUE THREAD

**Issue by souqalshoorja** [flutter/flutter#96078]
Hi hope to have help fix this issue ,
when try to login via Facebook After clicking on the login by Facebook, it will be redirect to the permissions page for Facebook, and after I use the Facebook name and click on the name of the Facebook account on the mobile, an error message (Warning: the username or password is incorrect), noting that all the settings of the Facebook developers completed and it is from Firebase. enabled , 

…(note : login via google ,sms work fine ). hope to help

**Comment by darshankawar** [comment]
@souqalshoorja 
This doesn't seem to be Flutter framework issue. Please ask this in support channels like StackOverflow.
If you are using flutterfire plugin and it is you think causing the issue, raise the same in dedicated repo: 
https://github.com/FirebaseExtended/flutterfire/issues
Closing from here.
