### ISSUE TITLE
Flaky issues link to internal dashboards

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#96077]
See https://github.com/flutter/flutter/pull/95572

> [50 consecutive runs](https://dashboards.corp.google.com/flutter_check_prod_test_flakiness_status_dashboard?p=BUILDER_NAME:%22Mac_android%20run_release_test%22)

There should be a public link and access to the internal chart. As a work around, we could link to flutter-dashboard.appspot.com with a filter so non-Google contributors can audit flaky tests.

**Comment by CaseyHillers** [comment]
\cc @keyonghan @chunhtai

**Comment by godofredoc** [comment]
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.
