### ISSUE TITLE
local_auth and platform channel in the same application (help wanted)

### ISSUE THREAD

**Issue by ManuelG-Axtop** [flutter/flutter#96081]
Hello
I'm stuck with the following problem, I hope you can help me, thanks in advance. 
 
I have implemented a platform channel, I want to use the local_auth package and the problem is that in the Android MainActivity to use a platform channel you have to extend FlutterActivity and to use local_auth you have to extend FlutterFragmentActivity. 

I tried this that I saw in https://gitmemory.cn/repo/flutter/flutter/issues/91964, but it didn't work for me.
Change android:name=".MainActivity" to android:name="io.flutter.embedding.android.FlutterFragmentActivity".

Is it possible to use a platform channel and the local_auth package together?
If yes, could you explain me how it would be, please.

The first 3 pictures are the errors when I don't change the android.name. The last ones are when I change the android.name, but it doesn't recognize the registrarFor.
<img src = "https://user-images.githubusercontent.com/82979687/147971272-9fba95f0-e5d8-428a-a087-9ef884020ec1.jpeg" width = "800" height = "400" alt = "error1" align = "center" />

<img src = "https://user-images.githubusercontent.com/82979687/147971389-de2d2b3a-d869-4c46-92ae-4d6f092ec39e.jpeg" width = "800" height = "600" alt = "error2" align = "center" />

<img src = "https://user-images.githubusercontent.com/82979687/147971424-a890ea9e-63b5-4fe6-9575-169b6eb60084.jpeg" width = "800" height = "600" alt = "error3" align = "center" />

<img src = "https://user-images.githubusercontent.com/82979687/147971660-05b31e06-e1ae-4b7d-abdd-3a74b4bd9302.jpeg" width = "800" height = "400" alt = "error4" align = "center" />

<img src = "https://user-images.githubusercontent.com/82979687/147971715-38236672-abca-4e55-a3af-1c73c6670705.jpeg" width = "800" height = "600" alt = "error5" align = "center" />

<img src = "https://user-images.githubusercontent.com/82979687/147971817-0399f184-18f3-4edc-bf04-62ddc967c38d.jpeg" width = "800" height = "400" alt = "error6" align = "center" />

**Comment by danagbemava-nc** [comment]
Hi @ManuelG-Axtop, from what I can see, you're using the wrong import of `FlutterFragmentActivity`. As indicated by the line through the class, that class has been deprecated in favor of `FlutterFragmentActivity` from 
`io.flutter.embedding.android` but it appears you are using `io.flutter.app` instead.

The `FlutterFragmentActivity` class from the above package has an override of `configureFlutterEngine` which should allow you to register your channels without any issue.

**Comment by ManuelG-Axtop** [comment]
Wow that was very easy, everything works excellent, thank you very much for the help @danagbemava-nc, you are a pro.

Another doubt
`FlutterAndroidLifecyclePlugin.registerWith(registerFor("io.flutter.plugins.flutter_plugin_android_lifecycle.FlutterAndroidLifecyclePlugin")); LocalAuthPlugin.registerWith(registerFor("io.flutter.plugins.localauth.LocalAuthPlugin"));` 
In v2 this is not added in the `onCreate` because it is deprecated, right?

**Comment by danagbemava-nc** [comment]
> Another doubt
FlutterAndroidLifecyclePlugin.registerWith(registerFor("io.flutter.plugins.flutter_plugin_android_lifecycle.FlutterAndroidLifecyclePlugin")); LocalAuthPlugin.registerWith(registerFor("io.flutter.plugins.localauth.LocalAuthPlugin"));
In v2 this is not added in the onCreate because it is deprecated, right?

Yes, the changes that were made to the android embedding made it such that it was no longer required for you to do that. 

> Wow that was very easy, everything works excellent, thank you very much for the help

Given the above comment, I feel it safe to close this issue. 

Closing as solved. 

Thank you
