### ISSUE TITLE
App Crashes When Picking Images From Camera

### ISSUE THREAD

**Issue by twtindia** [flutter/flutter#96080]
I have an app where I had to take images from the camera more than 50 times. When I take the first 10 photos images picker works fine but when I click next and start picking the next cameras after the 19th image is clicked app crashes and in console, I get the message ("Lost connection to the device. Exited (sigterm)").

How can I solve this I need help very urgently. Please help

**Comment by danagbemava-nc** [comment]
Hi @twtindia, thanks for reporting this. Please provide the following information.

- version of image_picker being used
- devices experiencing this issue and OS versions
- output of `flutter doctor -v`
- a complete minimal reproducible code sample.
- any other relevant logs

Thank you
