### ISSUE TITLE
Add SPIR-V FragmentShader Support on Web

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#96086]
Looking at the current `FragmentShader` ([now `FragmentProgram`](https://github.com/flutter/engine/blob/02f543f19499169f1cbc1c2cf38a76cb712fc37d/lib/ui/painting.dart#L3755)) API, we can see that:

```
/// This API is in beta and does not yet work on web.
[...]
class FragmentProgram extends NativeFieldWrapperClass1 {
```

Looking at the roadmap (https://github.com/flutter/flutter/projects/207), I was not able to find any issues that track web support for the **SPIR-V API via FragmentShader**. I was also not able to find any related issues via search, so I figured I would create one so progress can be tracked cc @clocksmith @chriscraws.

## Use case

As Flutter is a multi-platform framework, it is crucial that functionality is supported on all platforms. This is why web support for SPIR-V is inherently useful.

## Proposal

Add support for `FragmentProgram` to CanvasKit.

**Comment by yjbanov** [comment]
Will close this as we are adding the existing GLSL 4-based shader support to web. From then on we will try to evolve along with AOT Flutter.

**Comment by thipokch** [comment]
> Will close this as we are adding the existing GLSL 4-based shader support to web. From then on we will try to evolve along with AOT Flutter.

@yjbanov do you know where i can track this?
