### ISSUE TITLE
[add2app] flutter 2.8.1 engine group entry point not working in release mode

### ISSUE THREAD

**Issue by millie-molly** [flutter/flutter#96098]
<img width="564" alt="Screen Shot 2022-01-04 at 4 40 16 PM" src="https://user-images.githubusercontent.com/93499150/148025333-77139a7b-239b-43e1-b06c-db8ea0353897.png">

in version  2.5.3, making multi engines is working, but after i upgraded a dart version to 2.8.1, did not working.

example in ios code,

let resetPwEngine = MillieDelegate.flutterEngines.makeEngine(withEntrypoint: "resetPassword", libraryURI: nil)
GeneratedPluginRegistrant.register(with: resetPwEngine)
super.init(engine: resetPwEngine, nibName: nil, bundle: nil)

withEntrypoint is not recognized unless main

Only debug mode can find the entry point. 
If I build release mode, it fails to make an engine. so I got black screen.

**Comment by danagbemava-nc** [comment]
Hi @millie-molly, this issue is known and is being tracked in https://github.com/flutter/flutter/issues/91841. 

Kindly follow up there for more information. 

Closing from here as duplicate. 

If you disagree, kindly leave a comment below and I will reopen. 

Thank you
