### ISSUE TITLE
webview_flutter miss viewport-fit: cover

### ISSUE THREAD

**Issue by hellohejinyu** [flutter/flutter#96094]
## Steps to Reproduce

https://github.com/flutter/plugins/blob/6a9de4f5a7c03cf24418febe01d9bfe09bdcc40b/packages/webview_flutter/webview_flutter_wkwebview/ios/Classes/FLTWKNavigationDelegate.m#L67-L72

**Expected results:** 

css like `env(safe-area-inset-bottom)` can work correctly.

**Actual results:** 

`env(safe-area-inset-bottom) ` can't work. because the code override meta label and miss `viewport-fit: cover`

**Comment by darshankawar** [comment]
@hellohejinyu 
Can you provide us a minimal code sample that shows the current actual result along with your `flutter doctor -v` ?

**Comment by hellohejinyu** [comment]
![image](https://user-images.githubusercontent.com/8766034/148028709-8517ca6e-f6f1-45ba-87a7-75cb072f75cf.png)

This has nothing to do with flutter itself, it is just a bug of `webview_flutter`, this problem can be reproduced in the latest 3.0.0.

https://github.com/flutter/plugins/blob/6a9de4f5a7c03cf24418febe01d9bfe09bdcc40b/packages/webview_flutter/webview_flutter_wkwebview/ios/Classes/FLTWKNavigationDelegate.m#L67-L72

If you set zoomEnabled to false, the plugin will directly add a viewport meta tag rudely, causing the original meta tag in the web page to become invalid.
