### ISSUE TITLE
Video freezes while recording.

### ISSUE THREAD

**Issue by vikramsinghrajpoot** [flutter/flutter#96095]
Using  camera: ^0.9.2+2 plugin
  sdk: ">=2.6.0 <3.0.0"
Flutter 2.5.3
Video freezes while recording.
Using iPhone i am on zoom call and parallel using my app and trying to record a video. After 1-4 sec recording freezes.

**Comment by darshankawar** [comment]
@vikramsinghrajpoot 
Current latest plugin version is `0.9.4+5` and stable is 2.8.1. I suggest you to upgrade both to latest and try again to see if you get same behavior or not.
If still yes, provide a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows the current behavior you are seeing along with steps to replicate.
