### ISSUE TITLE
The TextFiled Cursor Height can not fix height 

### ISSUE THREAD

**Issue by 1036711153** [flutter/flutter#96103]
![image](https://user-images.githubusercontent.com/13378233/148028995-68ab090a-c240-4f51-aa6d-d4b7e56763b7.png)

I find Android Device, Flutter TextFiled Cursor Height can change  when inputting some characters ;

we find this because follow two function

![image](https://user-images.githubusercontent.com/13378233/148029446-5dec578f-fada-44f0-941f-3b2946422569.png)

![image](https://user-images.githubusercontent.com/13378233/148029495-cbf2ea13-ad11-46e3-9e70-2f094d8b1f19.png)

When I replace the function judgment condition of android with that of IOS, it is fixed， follow two function change

![image](https://user-images.githubusercontent.com/13378233/148029590-2d08e099-9e9b-409f-972c-ca029686fb15.png)
![image](https://user-images.githubusercontent.com/13378233/148029629-3de8f3bf-3929-406d-a7d5-e7535795a6c4.png)

**Comment by danagbemava-nc** [comment]
Hi @1036711153, this is a known issue and is being tracked in https://github.com/flutter/flutter/issues/92080. 

Feel free to share your findings in that thread so that it may be properly addressed. 

Closing from here as duplicate. 

Thank you
