### ISSUE TITLE
proper exception/warning for null aware operator used on null value

### ISSUE THREAD

**Issue by Ritsz123** [flutter/flutter#96104]
## Use case
During the development I mistakenly used `!` (null check operator) on the null instance. 
In the console, I realized there was no special warning or exception thrown but just a log stating `Null check operator used on a null value`  Thankfully I was aware of the file in which I did the mistake but it will be very hard to find the error if more than one developer is working on the particular project.

## Proposal
Suggestion:
I think instead of just mentioning `Null check operator used on a null value` in the console if a proper warning or exception is thrown it will be very easy to track the file & line of error.

**Comment by danagbemava-nc** [comment]
Hi @Ritsz123, this is a core dart issue and as such should be filed on the dart repo. 
[Link to repo](https://github.com/dart-lang/sdk/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc). 

It seems like there might be a similar case in https://github.com/dart-lang/sdk/issues/47185, but if that issue isn't exactly what you're describing, kindly file a new issue on the dart repo. 

Closing from here. 

Thank you
