### ISSUE TITLE
[Documentation] Update `onDisposeAction` 

### ISSUE THREAD

**Issue by AlirezaDaryani** [flutter/flutter#96107]
In below link
https://api.flutter.dev/flutter/widgets/AutofillGroup/onDisposeAction.html

Flutter said that we can pass 'null'  to `onDisposeAction` for `AutofillGroup` widget, but after the null safety update, this is no longer the case.

**Comment by danagbemava-nc** [comment]
Hi @AlirezaDaryani, thanks for reporting the issue with the documentation. 

As for the issue you're facing, kindly file a new issue and provide a complete minimal reproducible code sample and any other relevant information. 

Thank you

**Comment by AlirezaDaryani** [comment]
Sure, I think issue will be fix with `null` value.
I will wait for this fix.

**Comment by AlirezaDaryani** [comment]
#95210 https://github.com/flutter/flutter/issues/94043

**Comment by danagbemava-nc** [comment]
We still need to update the documentation
