### ISSUE TITLE
[Camera][iOS] Microphone permission during video recording without audio

### ISSUE THREAD

**Issue by burcus** [flutter/flutter#96116]
## Use case

During video recording, audio isn't necessary. In this situation there is a parameter as  **enable audio**. When it's false video not recording the audio. So there is no need request unused permission e.g "NSMicrophoneUsage". But Apple says "API access this info so NSMicrophoneUsage need to be in Info.plist". Even if the application doesn't use it for its functionality, the user becomes suspicious when the microphone permission is requested.

## Proposal

NSMicrophoneUsage should not be required for video recording if it's not using.

**Comment by bernaferrari** [comment]
> But Apple says "API access this info so NSMicrophoneUsage need to be in Info.plist"

If Apple says so, it needs that, so it is correct by requesting it?

**Comment by darshankawar** [comment]
@burcus 
Since the pre-requisite to have `NSMicrophoneUsage` comes from Apple and it need to have that entry in the log for privacy purpose, I am not sure if the proposal would be feasible, as Apple during the review might come back with `NSMicroPhoneUsage is missing`. Is this helpful ?

**Comment by burcus** [comment]
Apple requires this information in the info.plist but when the "enable audio" is false, microphone permission is not requested from user. With your feedback, in this situtation we can close this issue, thanks.
