### ISSUE TITLE
how to move file or create file assets folder? 

### ISSUE THREAD

**Issue by kotran88** [flutter/flutter#96110]
I have file in /data/user/0/com.onofflab.traffic/app_flutter/assets/ble.jpeg
and want to move to project directory's assets folder. 

firstly I created blank file 
` final file = await File('assets/models/ble.jpeg').create(recursive: true);`
but it cause  FileSystemException: Creation failed, path = 'assets' (OS Error: Read-only file system, errno = 30)

how can I move file to assets folder ?

**Comment by stuartmorgan** [comment]
Please use one of the resources at https://flutter.dev/community#community-grid for questions about your own code; the issue tracker is only for feature request and bug reports for Flutter itself.
