### ISSUE TITLE
DraggableScrollableSheet: Null check operator used on a null value

### ISSUE THREAD

**Issue by RalphBergmannKMB** [flutter/flutter#96111]
Sorry but I don't have any steps to reproduce. All I have is this crash report in Firebase :( 

```
Non-fatal Exception: FlutterError
0  ???                            0x0 _DraggableScrollableSheetScrollPosition.goBallistic._tick + 707 (draggable_scrollable_sheet.dart:707)
1  ???                            0x0 AnimationLocalListenersMixin.notifyListeners + 155 (listener_helpers.dart:155)
2  ???                            0x0 AnimationController._tick + 830 (animation_controller.dart:830)
3  ???                            0x0 Ticker._tick + 238 (ticker.dart:238)
4  ???                            0x0 SchedulerBinding._invokeFrameCallback + 1145 (binding.dart:1145)
5  ???                            0x0 SchedulerBinding.handleBeginFrame.<fn> + 1058 (binding.dart:1058)
6  ???                            0x0 _LinkedHashMapMixin.forEach (dart:collection)
7  ???                            0x0 SchedulerBinding.handleBeginFrame + 1056 (binding.dart:1056)
8  ???                            0x0 SchedulerBinding._handleBeginFrame + 975 (binding.dart:975)
```

Right now it's only happening on iOS, but on the other hand, we have a lot more iOS users than Android users.
I found another bug ticket related to this: https://github.com/flutter/flutter/issues/89214

The [`goBallistic`](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart#L829) method creates an `AnimationController` named [`ballisticController`](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart#L859) and [adds](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart#L884) the [`_tick` method](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart#L867) to it as a listener.

In the `_tick` method is [this line of code](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart#L870):
```dart
extent.addPixelDelta(delta, context.notificationContext!);
```

I guess the bang operator `context.notificationContext!` is the problem.

But I also noticed that the `ballisticController` isn't disposed when the [owner object is disposed](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart#L822).

So the question is: Do we need to dispose the `ballisticController` when the owner is disposed?

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6.1 20G224 darwin-x64, locale de-DE)
    • Flutter version 2.8.1 at /Users/ralphbergmann/development/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

```

</details>

**Comment by RalphBergmannKMB** [comment]
Oh, I missed the [`_ballisticCancelCallback`](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart#L865), so disposing is probably not the problem.

**Comment by darshankawar** [comment]
Although it looks similar / related to https://github.com/flutter/flutter/issues/89214, I tried to replicate the same on latest stable but didn't get the said exception. 
@RalphBergmannKMB Is there a way for you to provide a pattern that leads to this exception ? Maybe you can try along the lines of the code sample mentioned in linked issue and see if you can try to replicate ?
