### ISSUE TITLE
[Tooling] Set a specific version of Flutter SDK

### ISSUE THREAD

**Issue by KristianBalaj** [flutter/flutter#96129]
There is a project that is dockerized and I want to set a specific version of the Flutter SDK in the docker compose to make it buildable even after half a year.

I can't see any option to set a specific version. I can set only the channels with e.g. `flutter channel beta`.

Is it possible to set a specific Flutter SDK channel and version?

**Comment by bernaferrari** [comment]
duplicate of https://github.com/flutter/flutter/issues/64238#issuecomment-678605514
you may want to use http://pub.dev/packages/fvm

**Comment by maheshmnj** [comment]
Hi @KristianBalaj, Does `git checkout 1.17.5 && flutter precache`  work as mentioned in the above-linked comment?

**Comment by KristianBalaj** [comment]
The fvm package seems to solve the issue.
