### ISSUE TITLE
Fuchsia SDK roll failing

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#96126]
The first failing roll was here https://github.com/flutter/engine/pull/30494. The failure is the build error:
```
../../flutter/shell/platform/fuchsia/flutter/vulkan_surface_producer.cc:137:22: error: use of undeclared identifier 'countof'
                     countof(device_extensions), device_extensions);
                     ^
1 error generated.
```

@chaselatta @arbreng

**Comment by chaselatta** [comment]
The countof error was fixed in an earlier PR but now it is failing due to an issue finding the zx::rights symbol.

**Comment by akbiggs** [comment]
Seems to be working again.

**Comment by zanderso** [comment]
Let's leave this open until the autoroller successfully lands a roll.

**Comment by akbiggs** [comment]
Sorry, I saw that the mac SDK roll was unblocked and jumped to conclusions. https://autoroll.skia.org/r/fuchsia-mac-sdk-flutter-engine

I think the other one is blocked because there's a PR where CQ is stuck. https://github.com/flutter/engine/pull/30686

**Comment by akbiggs** [comment]
@godofredoc Do you know how to fix things when CQ is stuck on a roll?

**Comment by chinmaygarde** [comment]
I've closed the linked roll so the roller will start another job. Per @zanderso, this may happen if the request to run the presubs times out. @goderbauer and company are reworking this mechanism right now.

**Comment by zanderso** [comment]
@akbiggs The build appears to be failing for a different reason now: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Fuchsia/34725/overview

**Comment by akbiggs** [comment]
Spoke with the SDK team and came up with https://github.com/flutter/buildroot/pull/542 to maybe fix it.

**Comment by akbiggs** [comment]
- Restarted the Linux SDK roller this morning. It was stopped yesterday because a CQ infra bug merged a roll PR with failing tests.
- Currently the roll seems broken because of https://github.com/flutter/flutter/issues/96503.

**Comment by akbiggs** [comment]
@chandarrengoog submitted https://github.com/flutter/engine/pull/30829 to manually roll the SDK with a fix.

The next automated SDK roll after that point failed because of what appears to be an issue with gclient: https://cirrus-ci.com/task/6318023396032512

**Comment by akbiggs** [comment]
Autoroll is working again https://autoroll.skia.org/r/fuchsia-linux-sdk-flutter-engine. Thanks @chandarrengoog for the fixes!
