### ISSUE TITLE
Can't deploy on Android or IOS with IDE

### ISSUE THREAD

**Issue by FaisalAbid** [flutter/flutter#9612]
Despite flutter doctor reporting I have both devices connected.

I did a flutter upgrade in the morning which I think could have caused it, since last night it was working fine.

I've restarted my mac and IDE also

<img width="497" alt="screenshot 2017-04-26 13 24 35" src="https://cloud.githubusercontent.com/assets/253700/25447580/b32680be-2a83-11e7-88ff-90420034649e.png">

[✓] Flutter (on Mac OS X 10.12.5 16F67a, channel master)
    • Flutter at /Users/FaisalAbid/Development/workspace/Verve/Elixer/flutter
    • Framework revision 21f57a85e8 (17 hours ago), 2017-04-25 17:40:28 -0700
    • Engine revision a5b64899c9
    • Tools Dart version 1.23.0-dev.11.11

[✓] Host Executable Compatibility
    • Downloaded executables execute on host

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/FaisalAbid/Library/Android/sdk/
    • Platform android-25, build-tools 25.0.2
    • ANDROID_HOME = /Users/FaisalAbid/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.2, Build version 8E2002
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.0

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.1.1)
    • Dart plugin version 171.4424
    • Flutter plugin version 13.0

[✓] Connected devices
    • Pixel XL • HT6A60208436                         • android-arm • Android 7.1.2 (API 25)
    • iPhone 6 • 420A0FA6-F4C4-442E-A398-A912FC17917E • ios         • iOS 10.3 (simulator)

**Comment by FaisalAbid** [comment]
Flutter run -d and pressing r is working for me, I can make do for now!

**Comment by eseidelGoogle** [comment]
@devoncarew @johnmccutchan not sure what to do here?

**Comment by devoncarew** [comment]
I see this locally - I'll bisect the flutter tool to get more info.

**Comment by devoncarew** [comment]
@tvolkert, looks like we no longer get device notifications in the IDE as of: 60c5ffc1a96571d0b457c3efdf73a3fa66c2c5f4

**Comment by FaisalAbid** [comment]
Works now thanks @tvolkert

**Comment by branflake2267** [comment]
Nice, upgrade flutter and reboot fixed it. Thanks!

**Comment by daharper** [comment]
Thank you!

**Comment by seriyvolk83** [comment]
I may be due to older xcodetools, than needed. Check Xcode->Preferences->Locations->Command Line Tools. 
Recently I switched from Xcode.11.2.1 tools to Xcode 9.4.1 tools (while using Xcode 11.2.1 app) and it was the reason.
