### ISSUE TITLE
_TooltipState should probably be public

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#96127]
The doc of TooltipTriggerMode.manual https://api.flutter.dev/flutter/material/TooltipTriggerMode.html said it can only be shown by calling `ensureTooltipVisible` on the _TooltipState. However the class itself is private. Right now users have to cast the state into dynamic to call the `ensureTooltipVisible`

**Comment by ggirotto** [comment]
We are also expecting to have access to this internal state.
