### ISSUE TITLE
VideoPlayer causes background to be removed on window resize

### ISSUE THREAD

**Issue by JacobSchantz** [flutter/flutter#96121]
I'm using the example video player on pub.dev. When I resize the google chrome window, the background turns white. Help would be appreciated, Thanks! Also let me know if you need any more information, I'd be happy to provide any other details.

**Comment by JacobSchantz** [comment]
import 'package:video_player/video_player.dart';
import 'package:flutter/material.dart';

void main() => runApp(VideoApp());

class VideoApp extends StatefulWidget {
  @override
  _VideoAppState createState() => _VideoAppState();
}

class _VideoAppState extends State<VideoApp> {
  VideoPlayerController _controller;

  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.network('https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4')
      ..initialize().then((_) {
        // Ensure the first frame is shown after the video is initialized, even before the play button has been pressed.
        setState(() {});
      });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Video Demo',
      home: Scaffold(
        body: Center(
          child: _controller.value.isInitialized
              ? AspectRatio(
                  aspectRatio: _controller.value.aspectRatio,
                  child: VideoPlayer(_controller),
                )
              : Container(),
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            setState(() {
              _controller.value.isPlaying ? _controller.pause() : _controller.play();
            });
          },
          child: Icon(
            _controller.value.isPlaying ? Icons.pause : Icons.play_arrow,
          ),
        ),
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
    _controller.dispose();
  }
}

**Comment by JacobSchantz** [comment]
`
<img width="909" alt="after_resizing" src="https://user-images.githubusercontent.com/94196051/148088723-56e96eba-5af8-4805-8476-d925ba783d5a.png">

<img width="830" alt="before_resizing" src="https://user-images.githubusercontent.com/94196051/148088736-64f0a6df-735f-4a4b-b735-4e97c76401fe.png">
`

**Comment by JacobSchantz** [comment]
Output of flutter doctor -v



[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-US)
    • Flutter version 2.8.1 at /Users/jakeschantz/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/jakeschantz/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 96.0.4664.110

• No issues found!

**Comment by danagbemava-nc** [comment]
Hi @JacobSchantz, thanks for reporting this. 

Do you see any errors in your console when you resize the browser window? You may need to check the chrome console tab. 
Also, does this issue occur with both `canvaskit` and `html` or it occurs with only one of them?

**Comment by JacobSchantz** [comment]
With canvaskit I'm getting this in the chrome console:
WebGL: INVALID_OPERATION: delete: object does not belong to this context

**Comment by danagbemava-nc** [comment]
I can see a similar issue describing what you're experiencing in https://github.com/flutter/flutter/issues/95259. 

Kindly follow up for more information in there. 

Closing from here as duplicate. If you disagree, leave a comment below and I will reopen. 

Thank you
