### ISSUE TITLE
Migrate 2 mac/android to linux/android

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#96149]
With https://github.com/flutter/flutter/issues/74522, 33 linux/android tests are newly enabled and there are only 8 mac/android tests remaining in prod pool (6 mac/android bots).

We need to migrate 3 android devices from mac to linux to better utilize the hardware.

**Comment by yusuf-goog** [comment]
Will move these over as soon as we get more linux hosts.

**Comment by godofredoc** [comment]
Updated to move only 2, 1 machine was already moved to staging.

**Comment by CaseyHillers** [comment]
Moving this out of the ticket queue as there doesn't appear to be any work for the oncall.

If there is, please add a comment adding what is needed, and re-add to the queue.

**Comment by godofredoc** [comment]
@keyonghan  Should we close this bug as obsolete?

**Comment by keyonghan** [comment]
This is still a valid request considering 8 mac/android tests remaining in prod pool (6 mac/android bots), but we need extra linux bots.

**Comment by godofredoc** [comment]
Closing as obsolete.
