### ISSUE TITLE
[Android] flutter app crash   

### ISSUE THREAD

**Issue by longxf** [flutter/flutter#96158]

**Comment by SuhwanCha** [comment]
Please update Flutter SDK to latest (2.8.1)

Commands
```
flutter channel stable
```

**Comment by maheshmnj** [comment]
Hi @longxf, Thanks for filing the issue.

> Flutter 2.0.7-0.0.pre.13 • channel flutter-2.0.6 

You are using an old version of flutter, I would advise you to please upgrade to latest `stable 2.8.1` using `flutter upgrade` and if the issue persists post upgrade please share the updated output of `flutter doctor -v` along with the complete logs of `flutter run -v` in a text file.

**Comment by longxf** [comment]
thanks
