### ISSUE TITLE
[webview_flutter] When sliding to the webview page, a vertical line appears

### ISSUE THREAD

**Issue by OHeroJ** [flutter/flutter#96156]
* Flutter : stable(2.8.0)
* iOS: iphone8 plus
* webview_flutter: 3.0.0

use [webview_flutter example](https://github.com/flutter/plugins/blob/a10ac2e0d8a8cd878fd0d0a54aa9a87c44c7d7c5/packages/webview_flutter/webview_flutter/example/lib/main.dart#L150), and change favoriteButton：

```dart
Widget favoriteButton() {
    return FloatingActionButton(
      onPressed: () {
        Navigator.of(context).push(MaterialPageRoute(builder: (context) {
          return Scaffold(
            appBar: AppBar(
              title: Text("Next"),
            ),
            body: Container(),
          );
        }));
      },
      child: Icon(Icons.favorite),
    );
```

when `Next` title page swipe to  pre page：

https://user-images.githubusercontent.com/12316547/148165308-f29b5bf7-2a4f-4844-8f17-90dbdead0746.mp4

a vertical line appears:

![image](https://user-images.githubusercontent.com/12316547/148165450-a2f11912-9af0-4542-9e15-9c4985780392.png)

**Comment by darshankawar** [comment]
@OHeroJ 
I tried the same on iOS simulator 12.3 and on iphone 6s but didn't see the line:

<img width="296" alt="Screenshot 2022-01-05 at 3 13 11 PM" src="https://user-images.githubusercontent.com/67046386/148196795-d7e7e222-14a8-4fa9-9b00-83c474685782.png">

Can you downgrade the plugin version to 2.8.0 and see if you still get same behavior ?

**Comment by OHeroJ** [comment]
> @OHeroJ I tried the same on iOS simulator 12.3 and on iphone 6s but didn't see the line:
> 
> <img alt="Screenshot 2022-01-05 at 3 13 11 PM" width="296" src="https://user-images.githubusercontent.com/67046386/148196795-d7e7e222-14a8-4fa9-9b00-83c474685782.png">
> 
> Can you downgrade the plugin version to 2.8.0 and see if you still get same behavior ?

This problem can be reproduced on the real machine。The models I can reproduce now：
* iphone8 plus
* iPhone14,2

**Comment by OHeroJ** [comment]
> @OHeroJ I tried the same on iOS simulator 12.3 and on iphone 6s but didn't see the line:
> 
> <img alt="Screenshot 2022-01-05 at 3 13 11 PM" width="296" src="https://user-images.githubusercontent.com/67046386/148196795-d7e7e222-14a8-4fa9-9b00-83c474685782.png">
> 
> Can you downgrade the plugin version to 2.8.0 and see if you still get same behavior ?

[webview_flutter] 2.8.0 same behavior in real machine（iPhone8 Plus）.

**Comment by darshankawar** [comment]
Since I don't have the specific physical device (iphone 8 plus), I don't see the said behavior. Although I tried replicating the same on iPhone 8 and iPhone 8 plus simulators and don't see the behavior.

<img width="302" alt="Screenshot 2022-01-06 at 12 35 07 PM" src="https://user-images.githubusercontent.com/67046386/148342754-38e94a0c-f560-45a6-8594-0b6fd780cf32.png">

Keeping it open and labeling it for further investigation.

**Comment by jmagman** [comment]
@cyanglaz https://github.com/flutter/flutter/issues/61340 ?

**Comment by maoemao** [comment]
I have the same line, iphone 8 plus 14.6,flutter verson2.5.1
![wecom-temp-7acb795c288140ead31946f44f5e3cf0](https://user-images.githubusercontent.com/15976038/149899729-92704890-57ca-4f9b-a9c4-0548596534bb.jpg)

**Comment by maheshmnj** [comment]
@maoemao  please follow up on the [linked issue ](https://github.com/flutter/flutter/issues/96156#issuecomment-1006837729)
