### ISSUE TITLE
proposal(dart) lint: avoid_positional_boolean_parameters

### ISSUE THREAD

**Issue by SuhwanCha** [flutter/flutter#96150]
## Use case

Bad case:
```dart
Task(true);
Task(false);
ListBox(false, true, true);
Button(false);
```

Good case:
```dart
Task.oneShot();
Task.repeating();
ListBox(scroll: true, showScrollbars: true);
Button(ButtonState.enabled);
```

## Proposal

How about adapting `avoid_positional_boolean_parameters` on Flutter 3.0?

[# - avoid_positional_boolean_parameters # would have been nice to enable this but by now there's too many places that break it](https://github.com/flutter/flutter/blob/2770e9d56bb214edc439b9f65548c54a2b30f58c/analysis_options.yaml#L74)

**Comment by SuhwanCha** [comment]
cc/ @Piinks 
I don’t know is it worth to change a lots of thing to apply avoid_positional_boolean_parameters, but I think it can be nice milestone from flutter 3.0

**Comment by Piinks** [comment]
@Hixie or @goderbauer may have more insight to this @SuhwanCha. The comment there appears to explain why this is not currently enabled.

**Comment by goderbauer** [comment]
> would have been nice to enable this but by now there's too many places that break it

This comment next to the lint is still true. I wish we had enabled that early on, but now it just appears to create a lot of unnecessary churn...

**Comment by goderbauer** [comment]
I am just going to close this since we don't have plans to turn this on.
