### ISSUE TITLE
[Web] Wrong canvas height when rotating device

### ISSUE THREAD

**Issue by javaherisaber** [flutter/flutter#96162]
## Steps to Reproduce

1. Create a new project with Web support
2. `flutter build web --web-renderer canvaskit --release`
3. Deploy on hosting server
4. Open website on iOS safari
5. Tap on **Add to Home Screen**
6. Open the app from the added shortcut in the home screen
7. At this point canvas height is Okay.
8. Rotate device to landscape and then portrait again
9. canvas height is half the previous size and it never returns to the correct state again, even restarting the app does not change the height.

This is a minimum sample project to showcase the issue:
https://github.com/javaherisaber/FlutterWebIssues

Tested on `Flutter 2.8.1 and 2.5.3` with `Dart 2.14.4 and 2.15.1`

**Expected results:** 
I expect to resize the app on rotate, and return to correct state

**Actual results:** 

Here is a demo video of what happens:

https://user-images.githubusercontent.com/29440700/148176804-b4f335af-4df7-40dc-abdf-52c13d774365.mp4

## Device
iPhone 6, ios 12.5.4

**Comment by danagbemava-nc** [comment]
Hi @javaherisaber, thanks for reporting this. 

Does this only happen with the `canvaskit` renderer? 
Also, what other devices are affected by this?

Please provide the output of `flutter doctor -v` as well. 

Thank you

**Comment by javaherisaber** [comment]
@danagbemava-nc 
The issue is the same with `html` renderer.
`iPhone 6 plus` is also affected, maybe this is a general issue on iOS and device agnostic.

Here is the `flutter doctor -v` output:
```
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19044.1415], locale en-US)
    • Flutter version 2.5.3 at C:\sdk\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\sdk\android
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.58.2)
    • VS Code at C:\Users\Mahdi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.110
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 96.0.1054.62

• No issues found!
```

**Comment by danagbemava-nc** [comment]
Hi @javaherisaber, I attempted to reproduce this on an iPhone XS running `iOS 15.0.2` and I was not able to reproduce this with either web-renderers. See videos below

What version of `iOS` was your `iPhone 6 plus` running?

<details>
<summary>videos</summary>

| html | canvaskit | 
| -- | -- |
| <video src="https://user-images.githubusercontent.com/88313112/148728614-c28f2ede-952c-496f-b428-eb8ee5fe81cd.MP4" /> | <video src="https://user-images.githubusercontent.com/88313112/148728572-45c17d8c-0df3-427c-a7e1-07f773f09e8d.MP4" /> |

</details>

**Comment by javaherisaber** [comment]
@danagbemava-nc 
My mistake, It was `iPhone 6s` and `iOS 13.4.1`.

**Comment by danagbemava-nc** [comment]
I do not have a device running that version of `iOS` and I had a colleague confirm with `iOS 14` where the issue did not reproduce. 

This might be an issue with older versions of `iOS`. 

Labeling for further investigation.

**Comment by yjbanov** [comment]
Putting back in the triage queue. I dropped the ball on this one.

**Comment by danagbemava-nc** [comment]
Hi @javaherisaber, can you test this on the latest version of flutter stable(3.7.5) to see if you're able to reproduce the issue?
