### ISSUE TITLE
flutter build fails inside container in one host but succeeds in another

### ISSUE THREAD

**Issue by muuin** [flutter/flutter#96160]
Any piece of the project that is running a “flutter build” command on startup fails to run when deployed to Live.  Verbose outputs of a failure on Live and a success on Test servers have been attached to this issue for comparison.  It appears that the following line is the root of the problem on Live:

    dart2js: Starting due to {}

On Test, the dart2js target is skipped, but it tries to invoke the dart2js target on Live and promptly errors out.

Just to rule it out, the following is the docker run command that were used on Test and all 3 Live attempts:

`
docker run --restart=always -d --name app-ui -p 3150:8080 -m 768m -v /var/run/docker.sock:/var/run/docker.sock v /srv/ui/web/config.yml:/app/config/default.yml app-ui:1.0.115 /app/server.sh
`
And the following is the command invoked inside server.sh
`
flutter build web --web-renderer html --release
`

Verbose outputs of a failure on Live and a success on Test servers:
[ui_flutter_build_test_output.txt](https://github.com/flutter/flutter/files/7812639/ui_flutter_build_test_output.txt)
[ui_flutter_build_live_output.txt](https://github.com/flutter/flutter/files/7812636/ui_flutter_build_live_output.txt)

**Comment by danagbemava-nc** [comment]
Hi @muuin, 

It looks like an exception message is missing from the logs of the live, will it be possible for you to retrieve that message for us? 

Also, are you able to reproduce this issue locally? 

Please provide the outputs of `flutter doctor -v` that is being used in both containers and locally, if you can reproduce it. 

Thank you
