### ISSUE TITLE
there is a issue is in generate route please check

### ISSUE THREAD

**Issue by MishraVaibhav1999** [flutter/flutter#96175]
https://github.com/flutter/flutter/blob/77d935af4db863f6abd0b9c31c7e6df2a13de57b/packages/flutter/lib/src/material/app.dart#L300

**Comment by MishraVaibhav1999** [comment]
onGenerateRoute: Router().onGenerateRoute,
is this possible in onGenerateRoute maybe this code is older but can any body help me.

**Comment by maheshmnj** [comment]
Hi @MishraVaibhav1999, Can you please elaborate more on the issue by updating the description with more details, error logs, output of `flutter doctor -v` and a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) to better address the issue
