### ISSUE TITLE
[plugin_platform_interface] Prevent use of `const Object()` as token

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#96178]
The documentation for the `plugin_platform_interface` plugin is confusing -- if you follow the instructions you'll get a token that doesn't work, which could lead to version lock (like what is going on now in the webview plugin, see https://github.com/flutter/flutter/issues/94051).

I have opened flutter/plugins#4640 PR with a fix.

**Comment by stuartmorgan** [comment]
> if you follow the instructions you'll get a token that doesn't work

Why doesn't it work when it's `const`? (If it doesn't work, ideally we should try to detect and error on that in addition to fixing the example.)

**Comment by collinjackson** [comment]
Because `const Object() == const Object()` but `Object() != Object()`.

See flutter/plugins#2417.

I've updated the PR to assert that the token is not `const Object()`. However, this makes it no longer a documentation-only update, so it's a much riskier change. I think that technically it is a breaking change but this package cannot ever be updated with a breaking change because it will version lock the ecosystem. So I made it a minor update.

**Comment by stuartmorgan** [comment]
> Because `const Object() == const Object()` but `Object() != Object()`. See [flutter/plugins#2417](https://github.com/flutter/plugins/pull/2417).

Ah, makes sense. Thanks!

> I think that technically it is a breaking change

I hadn't thought that through when I posted my comment. It's not just technically breaking though, it's breaking breaking for anyone who currently is doing it wrong (which is a bug, but not one that will cause all clients of the plugin to be actively broken). pub.dev shows well over a hundred packages using it, so we can't make that change.

> but this package cannot ever be updated with a breaking change because it will version lock the ecosystem.

Well, yes and no; if we could trust that everyone would follow advice to allow both 2.x and 3.x when updating there wouldn't be any locking. The lock issues would create back-pressure on anyone doing it wrong. But I think we can do it slightly differently and avoid that; I'll follow up on the PR.
