### ISSUE TITLE
[path_provider] get applicationDirPath for macos

### ISSUE THREAD

**Issue by DSMan97** [flutter/flutter#96176]
## Proposal

I wish to get the applicationDirPath in flutter for macos Desktop:
I want to access to  the Contens folder of macos app from flutter like: Flutter.app/Contents/...
  Flutter.app
      |
      Contents

Thanks in advanced

**Comment by stuartmorgan** [comment]
Can you elaborate on the use case here? `NSBundle` methods are usually the right way to access things in the bundle, not manual path construction.

**Comment by darshankawar** [comment]
@DSMan97 
Please check above comment and so that we can properly address this request.
