### ISSUE TITLE
Marker does not rotate on the web

### ISSUE THREAD

**Issue by Henk-Keijzer** [flutter/flutter#96189]
I wrote an app using the google_maps_flutter_platform_interface library. A custom marker properly rotates according to the rotation setting on Android, but not on the web, where the rotation is always 0 (north).

**Comment by darshankawar** [comment]
@Henk-Keijzer 
Can you provide `flutter doctor -v`, plugin version and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows the behavior you are seeing ?

**Comment by Henk-Keijzer** [comment]
This is the code I use to create the marker:

  Future<void> buildShips(ships) async {
    shipList = [];
    following = [];
    shipMarkerList = {};
    for (var k = 0; k < ships.length; k++) {
      shipList.add(ships[k]['name']);           // add the name to the shipList for the menu
      following.add(false);                     // set following to false
      shipMarkerList.addAll({MarkerId(ships[k]['name']) : Marker(
        markerId: MarkerId(ships[k]['name']),
        anchor: Offset(0.5, 0.5),
        icon: await shipMarkerIcon (shipMarkerColorTable[int.parse(ships[k]['colorcode'])], markerBackGroundColor),
        position: LatLng(ships[k]['lat'][0].toDouble(), ships[k]['lon'][0].toDouble()),
        rotation: ships[k]['course'][0].toDouble(),
        flat: true,
      )});
    }
  }

On web all icons are pointing to "north", on Android the are pointing in the direction indicated with "rotation"

**Comment by darshankawar** [comment]
@Henk-Keijzer 
We would need a complete minimal reproducible code sample that we can directly copy paste and run to verify the issue. The code you provided seem to have lot of custom variables that we can't directly use, so please provide a runnable code sample, along with `flutter doctor -v` and plugin version.
Thanks.

**Comment by Henk-Keijzer** [comment]
Hi Darshankawar, I added the following simple routine to my code and this has the same result on the website (flutter build web). I did not test it on the connected Chrome or Edge device, because it would otherwise use cross-domain connections (which is not allowed).

  Future<void> buildShip(ship) async {
    shipMarkerList.addAll({MarkerId(ship) : Marker(
      markerId: MarkerId(ship),
      anchor: Offset(0.5, 0.5),
      position: LatLng(52.2, 4.5),
      rotation: 90.0,
      flat: true,
    )});
  }

My guess is that it has to do with the fact that rotation in flutter is a double and in the Android Google SDK an integer.

This is the result of flutter doctor -v:

[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.22000.376], locale nl-NL)
    • Flutter version 2.8.1 at K:\AndroidStudioProjects\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[!] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\hwkei\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Connected device (3 available)
    • Nokia X20 (mobile) • AQKSLVH030M42600828 • android-arm64  • Android 12 (API 31)
    • Chrome (web)       • chrome              • web-javascript • Google Chrome 96.0.4664.110
    • Edge (web)         • edge                • web-javascript • Microsoft Edge 96.0.1054.62

! Doctor found issues in 1 category.

As far as I know I have the latest plugin version...

Flutter is already up to date on channel stable
Flutter 2.8.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 77d935af4d (3 weeks ago) • 2021-12-16 08:37:33 -0800
Engine • revision 890a5fca2e
Tools • Dart 2.15.1
Process finished with exit code 0

**Comment by Henk-Keijzer** [comment]
O, and BTW, I installed the command line tools and accepted the android licenses, but that did not make any difference,,,,
Thanks

**Comment by Henk-Keijzer** [comment]
There are more problems. I use the following to move the marker(s) to another position:

      shipMarkerList.addAll({MarkerId(track['name']) : Marker(
      markerId: MarkerId(track['name']),
      anchor: Offset(0.5, 0.5),
      icon: await shipMarkerIcon (shipMarkerColorTable[int.parse(track['colorcode'])], markerBackGroundColor),
      position: LatLng(calculatedLat, calculatedLon),
      rotation: calculatedRotation,
      flat: true,
      )});

The addALL replaces the marker with MarkerId in the list, or adds a new one of the marker is does not exist yet.
This works perfectly on Android, but on web, the markers do not move....

**Comment by darshankawar** [comment]
@Henk-Keijzer 
I think you are hitting same issue as reported here: https://github.com/flutter/flutter/issues/80578
Please follow-up in it for further updates.
Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.

**Comment by Henk-Keijzer** [comment]
Ok! Thanks so far.

**Comment by Henk-Keijzer** [comment]
Similar code for Polylines works ok!!
