### ISSUE TITLE
external_ui_integration_test_ios: texture suite texture rendering Expected: a numeric value within <5.0> of <29.1>

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#96188]
```
[external_ui_integration_test_ios] [STDOUT] stdout: [+8057 ms] flutter: Stopping .5x speed test...
[external_ui_integration_test_ios] [STDOUT] stdout: [ +250 ms] 00:22 [32m+0[0m[31m -1[0m: texture suite texture rendering [1m[31m[E][0m[0m
[external_ui_integration_test_ios] [STDOUT] stdout: [        ]   Expected: a numeric value within <5.0> of <29.1>
[external_ui_integration_test_ios] [STDOUT] stdout: [        ]     Actual: <0.2>
[external_ui_integration_test_ios] [STDOUT] stdout: [        ]      Which:  differs by <28.900000000000002>
```
https://ci.chromium.org/p/flutter/builders/prod/Mac_ios%20external_ui_integration_test_ios/3179
<img width=500 src="https://user-images.githubusercontent.com/682784/148277888-eeb45f12-8b5b-4191-af32-0201ca898806.png">

First seen with roll https://github.com/flutter/flutter/pull/96179.

**Comment by jmagman** [comment]
Assigning to external_ui_integration_test_ios test owner @zanderso

**Comment by jmagman** [comment]
Failing line:
https://github.com/flutter/flutter/blob/9c0bd18c40f1509e16079142c441bfee025da976/dev/integration_tests/external_ui/test_driver/main_test.dart#L48

**Comment by zanderso** [comment]
The Engine roll and engine change have been reverted. Closing.
