### ISSUE TITLE
Runtime quirks!

### ISSUE THREAD

**Issue by LarkAscending** [flutter/flutter#9619]
## Steps to Reproduce
1. Install Xcode 8.3.2.
1. Follow Flutter setup instructions on brand-new (corp) MacBook Pro.
1. Follow Flutter IntelliJ setup instructions, installing CE 2017.1.2, Flutter plugin 13.0 with Dart plugin 171.4424.
1. Do all Xcode post-install steps, installing homebrew, cocoapods, etc and running ios/Runner.xcworkspace, selecting Runner, etc.
1. Attach iPod touch device (configured w/cert, told to trust my cert).
1. Create new project with I/O codelab sample [Friendlychat app](). Walk through steps.
1. Run Friendlychat _in debug mode_ in IntelliJ.

Observe the following:
a. Really like the new hot reload icon. However it's enabled on toolbar, before any changes have been made to main.dart. Was expecting it to be disabled when there are no changes to hot reload.
b. After a successful change and hot reload, IntelliJ loses the connection to the device.
c. [This interesting message](http://www.openradar.me/11744455) is printed to the console when running a Flutter app (on iOS).

App does run fine. No syntax errors in IntelliJ.

## Logs

Run your application with `flutter run` and attach all the log output.
```
eastrue-macbookpro:TestFriendlyChat eastrue$ flutter run

Launching lib/main.dart on iPod touch in debug mode...

Running pod install...                                1.1s

Running Xcode build...                               16.0s

libMobileGestalt MobileGestaltSupport.m:153: pid 255 (Runner) does not have sandbox access for frZQaeyWLUvLjeuEK43hmg and IS NOT appropriately entitled

libMobileGestalt MobileGestalt.c:550: no access to InverseDeviceID (see <rdar://problem/11744455>)

Syncing files to device...                            5.9s



🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".

The Observatory debugger and profiler is available at: http://127.0.0.1:8100/

For a more detailed help message, press "h". To quit, press "q".

activate generator <_UIFeedbackKeyboardBehavior: 0x170109900: prepared=1> with style: TurnOn; activationCount: 1 -> 0; styleActivationCount: 1 -> 0

feedback engine <_UIFeedbackSystemSoundEngine: 0x1740a8520: state=0, numberOfClients=1, prewarmCount=0, _isSuspended=0> state changed: Inactive -> Activating

feedback engine <_UIFeedbackSystemSoundEngine: 0x1740a8520: state=3, numberOfClients=1, prewarmCount=0, _isSuspended=0> state changed: Activating -> Running

Requesting calls from host

Received requested calls from host: <private>

activate generator <_UIFeedbackKeyboardBehavior: 0x170109900: prepared=1> with style: TurnOn; activationCount: 2 -> 1; styleActivationCount: 2 -> 1

playing feedback <_UICustomDiscreteFeedback 0x17410b5b0; player: 0x1740a8520; delay: 0.000; effectiveSystemSoundID: 1104; feedbackType: None; effectiveEventType: 0> at time 33941.504298

deactivate generator <_UIFeedbackKeyboardBehavior: 0x170109900: prepared=1> with style: TurnOn; activationCount: 1 -> 2; styleActivationCount: 1 -> 2



Initializing hot reload...                                

Reloaded 409 of 424 libraries in 3,051ms.

deactivate generator <_UIFeedbackKeyboardBehavior: 0x170109900: prepared=0> with style: TurnOn; activationCount: 0 -> 1; styleActivationCount: 0 -> 1

feedback engine <_UIFeedbackSystemSoundEngine: 0x1740a8520: state=4, numberOfClients=0, prewarmCount=0, _isSuspended=0> state changed: Running -> Inactive

activate generator <_UIFeedbackKeyboardBehavior: 0x170109900: prepared=1> with style: TurnOn; activationCount: 1 -> 0; styleActivationCount: 1 -> 0

feedback engine <_UIFeedbackSystemSoundEngine: 0x1740a8520: state=0, numberOfClients=1, prewarmCount=0, _isSuspended=0> state changed: Inactive -> Activating

feedback engine <_UIFeedbackSystemSoundEngine: 0x1740a8520: state=3, numberOfClients=1, prewarmCount=0, _isSuspended=0> state changed: Activating -> Running

deactivate generator <_UIFeedbackKeyboardBehavior: 0x170109900: prepared=0> with style: TurnOn; activationCount: 0 -> 1; styleActivationCount: 0 -> 1

feedback engine <_UIFeedbackSystemSoundEngine: 0x1740a8520: state=4, numberOfClients=0, prewarmCount=0, _isSuspended=0> state changed: Running -> Inactive

Lost connection to device.

activate generator <_UIFeedbackKeyboardBehavior: 0x170109900: prepared=1> with style: TurnOn; activationCount: 1 -> 0; styleActivationCount: 1 -> 0

feedback engine <_UIFeedbackSystemSoundEngine: 0x1740a8520: state=0, numberOfClients=1, prewarmCount=0, _isSuspended=0> state changed: Inactive -> Activating

feedback engine <_UIFeedbackSystemSoundEngine: 0x1740a8520: state=3, numberOfClients=1, prewarmCount=0, _isSuspended=0> state changed: Activating -> Running

app will resign active

app will suspend

feedback engine <_UIFeedbackSystemSoundEngine: 0x1740a8520: state=4, numberOfClients=1, prewarmCount=0, _isSuspended=1> state changed: Running -> Inactive


deactivate generator <_UIFeedbackKeyboardBehavior: 0x170109900: prepared=0> with style: TurnOn; activationCount: 0 -> 1; styleActivationCount: 0 -> 1
```

Run `flutter analyze` and attach any output of that command also.
```
eastrue-macbookpro:TestFriendlyChat eastrue$ flutter analyze

Analyzing /Users/eastrue/IdeaProjects/TestFriendlyChat...

No issues found!

Ran in 4.1s
```
## Flutter Doctor

[✓] Flutter (on Mac OS X 10.12.4 16E195, channel master)
    • Flutter at /Users/eastrue/flutter
    • Framework revision ad1c497c03 (25 hours ago), 2017-04-25 10:34:43 -0700
    • Engine revision a5b64899c9
    • Tools Dart version 1.23.0-dev.11.11

[✓] Host Executable Compatibility
    • Downloaded executables execute on host

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/eastrue/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.2, Build version 8E2002
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1.2)
    • Dart plugin version 171.4424
    • Flutter plugin version 13.0

[✓] Connected devices
    • iPod touch • 9fbe53ba4d06927398644c5bd520d2aa18053017 • ios • iOS 10.3.1 (14E304)

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by LarkAscending** [comment]
Possibly related: on Linux w/attached Android device, seeing this error after the app has been running ~5 minutes:
```
Observatory connection never became ready.
Application finished.
```

**Comment by eseidelGoogle** [comment]
Is the device turning off during this?  @xster was working on making hot reload connections persist across screen off.

**Comment by johnmccutchan** [comment]
The `Lost connection to device.' message indicates:

1. The VM running on the device has exited (either because of a crash or the OS killing the process)
2. The HTTP server for the vm-service protocol has exited (unlikely).
3. (Android specific): `adb` died and we lost our port forwarding.

**Comment by xster** [comment]
The iOS outputs are quite noisy too. We should cull a bit more. (I don't think most are flutter related/relevant)

The iOS connection should persist for 180s after the screen locks though if it's killed by the OS, there should be a specific [message](https://github.com/flutter/engine/blob/master/shell/platform/darwin/ios/framework/Source/FlutterAppDelegate.mm#L41) shown.

**Comment by LarkAscending** [comment]
@eseidelGoogle Yes! that's the root cause for b. The borrowed device has a 1-minute timeout. Also, switching between devices takes more time. Was able to confirm that's what's happening. Glad @xster 's working on it...even improved error messages would be great. 

a. is still true, might be a bug. 
c. is also still happening. The error sounds like you won't be able to run your app (but you can).

**Comment by eseidelGoogle** [comment]
@LarkAscending would you be willing to break out a and c into separate bugs and close this one?

For b: Are you seeing the message @xster referenced above?

**Comment by eseidelGoogle** [comment]
Specifically I believe a) and c) are bugs.  And should be filed as:

a) Hot reload icon could be disabled when there are no local changes to load? https://github.com/flutter/flutter-intellij/issues/new is the tracker.
c) flutter logs should hide libMobileGestalt messages (http://www.openradar.me/11744455).  @xster and @cbracken  has fixed this kind of thing in the past.  The code in question is somewhere around here:
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/ios/devices.dart#L377

Android has log filtering:
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_device.dart#L673

**Comment by xster** [comment]
c) we can probably aggregate console noise in #8981

b) I'll come check with you tomorrow. I expect connection with intellij to be lost 180s after the 60s timeout. Though I also expected a message regarding it in the console.

**Comment by strootaay** [comment]
I am experiencing the same issue. I get the following error when I try to run a blank flutter project:

Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Observatory connection never became ready.
Application finished.

I am new to Flutter and Dart. Was following the steps mentioned in the Flutter Getting Started Guide: https://flutter.io/getting-started/

Android Studio, Flutter SDK and IntelliJ IDEA are properly configured.

flutter doctor returns the following:

[√] Flutter (on Microsoft Windows [Version 6.1.7600], locale en-IN, channel alph
a)
• Flutter at C:\flutter\flutter
• Framework revision b156a0f054 (7 days ago), 2017-08-11 22:01:40 -0700
• Engine revision fef7d827d6
• Tools Dart version 1.25.0-dev.9.0

[√] Android toolchain - develop for Android devices (Android SDK 25.0.2)
• Android SDK at C:\Users\Shoumik\AppData\Local\Android\sdk
• Platform android-25, build-tools 25.0.2
• Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
• Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Android Studio (version 2.3)
• Android Studio at C:\Program Files\Android\Android Studio
• Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] IntelliJ IDEA Community Edition (version 2017.2)
• Flutter plugin version 16.0
• Dart plugin version 172.3757.55

[√] Connected devices
• Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (A
PI 26) (emulator)

Android Studio Log suggests the following:

[1422750] INFO - tools.idea.ddms.adb.AdbService - Successfully connected to adb
2017-08-18 21:50:08,613 [1467656] INFO - ellij.vfs.persistent.FSRecords - Contents:16384 of 159278908, reuses:303 of 871192 for 915
2017-08-18 21:50:25,575 [1484618] INFO - .diagnostic.PerformanceWatcher - Unindexed files update took 74395ms; general responsiveness: 7/72 sluggish, 2/72 very slow; EDT responsiveness: 0/72 sluggish, 3/72 very slow

IntelliJ IDEA log shows the following:

[1114566] INFO - r.run.daemon.DaemonConsoleView - [{"event":"app.start","params":{"appId":"361063b6-f5cb-443b-9a38-a1483ba14907","deviceId":"emulator-5554","directory":"C:\Users\Shoumik\IdeaProjects\myapp","supportsRestart":true}}]
2017-08-18 22:19:35,235 [1115265] INFO - r.run.daemon.DaemonConsoleView - [{"event":"app.progress","params":{"appId":"361063b6-f5cb-443b-9a38-a1483ba14907","id":"0","progressId":null,"message":"Initializing gradle..."}}]
2017-08-18 22:19:36,992 [1117022] INFO - r.run.daemon.DaemonConsoleView - [{"event":"app.progress","params":{"appId":"361063b6-f5cb-443b-9a38-a1483ba14907","id":"0","progressId":null,"finished":true}}]
2017-08-18 22:19:36,998 [1117028] INFO - r.run.daemon.DaemonConsoleView - [{"event":"app.progress","params":{"appId":"361063b6-f5cb-443b-9a38-a1483ba14907","id":"1","progressId":null,"message":"Resolving dependencies..."}}]
2017-08-18 22:24:33,470 [1413500] INFO - r.run.daemon.DaemonConsoleView - [{"id":0,"result":true}]
2017-08-18 22:24:34,127 [1414157] INFO - .flutter.run.daemon.FlutterApp - StopApp myapp (Run)
2017-08-18 22:28:17,979 [1638009] INFO - ide.actions.ShowFilePathAction -
Exit code 1

**Comment by cbracken** [comment]
Fixed by #11969

**Comment by kangwang1988** [comment]
We're also continuously met the `Observatory connection never became ready` issue.Finally, it's found that's a timeout issue.i.e., when you flutter run command has run over 10min,but the web socket for observatory is still empty, an error will trigger. This can often occurs when your dependencies resolving or building take long.

This logic is in flutter's intellj plugin.Visit https://github.com/flutter/flutter-intellij/blob/master/third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java#L203 for more.

<img width="1034" alt="screen shot 2018-03-23 at 9 02 48 am" src="https://user-images.githubusercontent.com/817851/37806165-8b86477e-2e79-11e8-80bc-33b2630dd36b.png">

**Comment by devoncarew** [comment]
I filed this issue to track: https://github.com/flutter/flutter-intellij/issues/1988

but some more info here would be useful. @kangwang1988, specifically:

- you are running from IntelliJ (or Android Studio)?
- the app does take longer than 10 minutes to build (before it appears on the device, and is ready for us to connect to it with IntelliJ)?
