### ISSUE TITLE
canvas.drawImage(), PaintImage() doesn't work for Mobile Browser

### ISSUE THREAD

**Issue by bajsaa** [flutter/flutter#96208]
I am trying to get Canvas painted image. It works on web and phone. But when I test it on Mobile Browser the PaintImage() or canvas.drawImage() doesn't work and have error. When I remove PaintImage() it works and I have my canvas image. Any ideas how to solve it or other image drawing function for canvas? 
```
Future<ui.Image> getCanvasImage() async {
    Size imageSize = const Size(1200, 630);
    final recorder = ui.PictureRecorder();
    final canvas = Canvas(recorder,Rect.fromPoints(const Offset(0.0, 0.0), Offset(imageSize.width, imageSize.height)));
    canvas.drawRect(Rect.fromLTWH(0.0, 0.0, imageSize.width, imageSize.height),Paint()
          ..shader = ui.Gradient.linear(
              const Offset(0, 0), Offset(imageSize.width, imageSize.height), [
            const Color.fromRGBO(23, 74, 151, 1),
            const Color.fromRGBO(90, 168, 200, 1),
          ]));
    like = await loadUiImage('lib/assets/like.png');
    var rect = Rect.fromLTWH(
      100,100,100,100,
    );
    //canvas.drawImageRect(like, maskSourceRect, rect, paint);
    //canvas.drawImage(like, Offset.zero, Paint());
    paintImage(canvas: canvas, rect: rect, image: like, debugImageLabel: 'lake');
    final picture = recorder.endRecording();
    final img =
        picture.toImage(imageSize.width.toInt(), imageSize.height.toInt());
    return img;
}
Future<ui.Image> loadUiImage(String imageAssetPath) async {
  final ByteData data = await rootBundle.load(imageAssetPath);
  final Completer<ui.Image> completer = Completer();
  ui.decodeImageFromList(Uint8List.view(data.buffer), (ui.Image img) {
    return completer.complete(img);
  });
  return completer.future;
}
```

**Comment by maheshmnj** [comment]
Hi @bajsaa, Thanks for filing the issue. Please share a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) along with the output of `flutter doctor -v`.

Thank you.

**Comment by bajsaa** [comment]
[✓] Flutter (Channel stable, 2.8.1, on Mac OS X 10.15.7 19H15 darwin-x64, locale
    en-MN)
    • Flutter version 2.8.1 at /Users/bayasgalandashdorj/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/bayasgalandashdorj/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.0.0.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android
      10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google
      Chrome 96.0.4664.110
```
import 'dart:async';
import 'dart:typed_data';
import 'dart:ui' as ui;
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

class CanvasImage extends StatefulWidget {
  const CanvasImage({Key? key}) : super(key: key);

  @override
  _CanvasImageState createState() => _CanvasImageState();
}

class _CanvasImageState extends State<CanvasImage> {
  Uint8List? canvasImage;
  Future<ui.Image> getCanvasImage() async {
    ui.Image like;
    Size imageSize = const Size(1200, 630);
    final recorder = ui.PictureRecorder();
    final canvas = Canvas(
        recorder,
        Rect.fromPoints(
            const Offset(0.0, 0.0), Offset(imageSize.width, imageSize.height)));
    canvas.drawRect(
        Rect.fromLTWH(0.0, 0.0, imageSize.width, imageSize.height),
        Paint()
          ..shader = ui.Gradient.linear(
              const Offset(0, 0), Offset(imageSize.width, imageSize.height), [
            const Color.fromRGBO(23, 74, 151, 1),
            const Color.fromRGBO(90, 168, 200, 1),
          ]));
    like = await loadUiImage('lib/assets/like.png');
    var rect = const Rect.fromLTWH(100, 100, 100, 100);
    paintImage(
        canvas: canvas, rect: rect, image: like, debugImageLabel: 'lake');
    final picture = recorder.endRecording();
    final img =
        picture.toImage(imageSize.width.toInt(), imageSize.height.toInt());
    return img;
  }

  Future<ui.Image> loadUiImage(String imageAssetPath) async {
    final ByteData data = await rootBundle.load(imageAssetPath);
    final Completer<ui.Image> completer = Completer();
    ui.decodeImageFromList(Uint8List.view(data.buffer), (ui.Image img) {
      return completer.complete(img);
    });
    return completer.future;
  }

  void getCanvas() async {
    var image = await getCanvasImage();
    var byte = await image.toByteData(format: ui.ImageByteFormat.png);
    canvasImage = Uint8List.view(byte!.buffer);
    setState(() {});
  }

  @override
  void initState() {
    getCanvas();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: canvasImage == null ? Container() : Image.memory(canvasImage!));
  }
}
```

**Comment by bajsaa** [comment]
found the solution! its --web-renderer canvaskit

flutter run -d web-server --web-hostname 0.0.0.0 --web-port 8080 --no-sound-null-safety --release --web-renderer canvaskit

**Comment by maheshmnj** [comment]
Thanks for the update.
> found the solution! its --web-renderer canvaskit

Provided your last message, I feel it's safe to close the issue.

Closing as solved.
