### ISSUE TITLE
flutter连接mysql时执行查询语句报错

### ISSUE THREAD

**Issue by notture** [flutter/flutter#96204]
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: SocketException: Socket has been closed

添加查询语句报错：await conn.query(
      'CREATE TABLE users (id int NOT NULL AUTO_INCREMENT PRIMARY KEY, name varchar(255), email varchar(255), age int)');

**Comment by notture** [comment]
![2XRQ`T2DM(AHK6OUVTW~`E3(1).png](https://user-images.githubusercontent.com/77527176/148331581-df99860e-2d3d-4de2-aa98-70df74ea468a.png)

**Comment by danagbemava-nc** [comment]
Hi @notture, this seems like an issue with the `mysql1` package and not an issue with flutter. 

Kindly file the issue over on their own issue tracker over [here](https://github.com/adamlofts/mysql1_dart/issues). 

There even seems to be a similar issue in https://github.com/adamlofts/mysql1_dart/issues/112. 

Closing from here as this is an issue with a third-party package. 

Thank you
