### ISSUE TITLE
Add tile benchmark to dashboard

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#9620]
This is a follow-up to https://github.com/flutter/flutter/pull/9537

**Comment by Hixie** [comment]
@yjbanov This is done, no? Marking closed on the assumption that it's done.

**Comment by yjbanov** [comment]
No, this is not done yet, and I shouldn't be hogging this issue.

**Comment by goderbauer** [comment]
Fixed by https://github.com/flutter/flutter/pull/20105.
