### ISSUE TITLE
Can we let the bot remove the pull request's `needs test` label automatically after new commit contains a test?

### ISSUE THREAD

**Issue by eggfly** [flutter/flutter#96202]
As title. When initial commit doesn't contains a test but further commits contains tests, can we let the `needs test` lable to be removed automatically? cc @Hixie 😄

**Comment by Hixie** [comment]
Do we need a label at all?

Ideally the commit bot would do the final check based on the actual code and any `test-exempt: ...` comments, not based on the label.

**Comment by godofredoc** [comment]
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.
