### ISSUE TITLE
Warning regarding IPHONEOS_DEPLOYMENT_TARGET for GoogleSignIn plugin

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [flutter/flutter#96220]
Hello,

I see that new version of google_sign_in released (5.2.1) and one of changes is: 
```
5.1.1 Update minimum Flutter SDK to 2.5 and iOS deployment target to 9.0.
```

however, even after cleaning cahce, and pods i got 5.0.2 installed
![Screenshot 2022-01-06 at 11 24 51](https://user-images.githubusercontent.com/3918999/148368748-acbbd75c-bd75-4692-a15b-c8f646bbe400.png)

when building i get this warning:
```
warning: The iOS deployment target
    'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.2.99. (in target
    'GoogleSignIn' from project 'Pods')
```
 Here is flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6.1 20G224 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.63.2)
[✓] Connected device (2 available)
```

flutter version: 2.8.x

**Comment by stuartmorgan** [comment]
> in target 'GoogleSignIn' from project 'Pods'

The plugin's pod is "google_sign_in". "GoogleSignIn" is the pod for the underlying iOS SDK that the plugin depends on, which the Flutter team doesn't control.

**Comment by Fuadafdhal** [comment]
how to solve it?
