### ISSUE TITLE
`flutter analyze` should accept single dart files as parameter

### ISSUE THREAD

**Issue by MichaelTamm** [flutter/flutter#96231]
`flutter analyze` takes quite a while on a large code base. It would be helpful (e.g. for a Git pre-commit hook)
if it would be possible to specify the files, which should be checked. for example:

`flutter analyze lib/some_file.dart lib/some_other_file.dart` 

BTW, this is already implemented for `dart analyze`.

**Comment by danagbemava-nc** [comment]
Related issue https://github.com/flutter/flutter/issues/48229.
