### ISSUE TITLE
update-packages is failing due to conflicts between concurrent pub get processes

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#96240]
We are sometimes seeing failures in `flutter update-packages` when a `pub get` process throws an exception due to invalid filesystem state in the pub cache.

This seems to be happening especially often in Cirrus CI jobs.  Several Dart->engine and Skia->engine rolls recently failed due to this:
(examples: https://github.com/flutter/engine/runs/4730759888 and https://github.com/flutter/engine/runs/4723438043)

`update-packages` starts multiple concurrent instances of `pub get` in order to improve performance (see https://github.com/flutter/flutter/commit/01af8e5987e4ed1f4ea12675975e98bc0ebe87ac).
It looks like this may be unsafe if the `pub get` processes are simultaneously trying to download a package and update the pub cache.

`update-packages` also tries to prewarm the cache and force a download of the necessary packages before running `pub get` on the various Flutter subcomponents.

@gspencergoog What is the prewarm expected to handle?

The prewarm is parsing the `pubspec.yaml` files in the subcomponents and fetching their direct dependencies.  But it appears to be skipping the autogenerated transitive dependencies declared in those `pubspec.yaml` files.

If the transitive dependencies are pinned to a different version than the one fetched by the prewarm, then the `pub get` calls for the subcomponents will still need to download more packages.  That can result in conflicting cache writes that cause errors in `pub get`.

**Comment by gspencergoog** [comment]
The prewarm is expected to handle all of the packages and their dependencies. The idea is that it takes the union of all (transitive) packages used in the tree and makes a project that depends on those packages, and then runs `pub get` on that fake package to warm the cache. I don't see why it wouldn't download all of the transitive dependencies as well at that time.

One thing I could try is to run the subsequent `pub get` calls with `--offline`, which would prevent the command from even going to download new packages.  It should then fail version solving if it didn't get it in the initial `pub get` of the fake package.

**Comment by jason-simmons** [comment]
I tried capturing a `pubspec.yaml` for the fake package.  It had a dependency section containing the union of the direct dependencies but it excluded the autogenerated transitive dependencies (see https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/update_packages.dart#L751)

A fetch of the fake package will download some version of the transitive dependency packages.  But if the fake `pubspec.yaml` does not have a version constraint for the transitive packages, then the downloaded version may not match the exact version needed by subsequent `pub get` runs.

**Comment by gspencergoog** [comment]
Thanks, that makes sense. I'll see if I can add the transitive dependencies, with their version numbers.

**Comment by gspencergoog** [comment]
I think I have a fix for this: once I updated the fake project generation to include the version numbers of all the transitive dependencies, I can now run all of the remaining `pub get` runs with `--offline` successfully, and I don't have and extra version in my pub cache afterward.

I'll write up a test and send that out for review.

**Comment by TahaTesser** [comment]
This blocked https://github.com/flutter/flutter/issues/96018
