### ISSUE TITLE
Requesting FAQ answer: "Why doesn't Flutter have a markup?"

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#9624]
Prepping for our upcoming events, this question will come up a lot.

Does someone want to provide a short answer? I'll get it into the FAQ.

Thanks!

**Comment by sethladd** [comment]
cc @efortuna @emshack

**Comment by Hixie** [comment]
Here's an answer:
> We have found that having entirely dynamic interface generation allows for more flexibility, for example having dedicated widgets that provide bespoke behaviours, which a rigid markup language would not allow.  We have also found that our approach allows for features like hot reload and dynamic environment adaptations.
>
> Having said that, it is possible to create a custom language that is then converted to widgets on the fly. Since build methods are "just code", they can do anything, including interpreting markup and turning it into widgets. Several Flutter developers have written custom solutions to convert their own markup to widgets.

**Comment by sethladd** [comment]
Thanks! Assigning to me to markdownify.

**Comment by xster** [comment]
as the professional noob of the team, I suspect people are most likely curious about the latter (an android inflator like thing expanding shorthands) than the former (a mutually exclusive UI markup)

**Comment by sethladd** [comment]
Thanks! Added to the FAQ
