### ISSUE TITLE
[Android] Type mismatch: inferred type is ComponentActivity but ExclusiveAppComponent<Activity!> was expected

### ISSUE THREAD

**Issue by CharithaRathnayake** [flutter/flutter#96266]
I am getting an error in FlutterViewEngine of the sample code after the flutter upgrade. As mentioned in the error, the activityControlSurface . attachToActivity ( activity, lifecycle) has changed to  activityControlSurface . attachToActivity ( ExclusiveAppComponentActivity<Activity!>,lifecycle). 

Error:
Type mismatch: inferred type is ComponentActivity but ExclusiveAppComponent<Activity!> was expected

This is the use case.
    
    private fun hookActivityAndView() {
        // Assert state.
        activity!!.let { activity ->
            flutterView!!.let { flutterView ->
                platformPlugin = PlatformPlugin(activity, engine.platformChannel)

                engine.activityControlSurface.attachToActivity(activity, activity.lifecycle)
                flutterView.attachToFlutterEngine(engine)
                activity.lifecycle.addObserver(this)
            }
        }
    }

How to solve this?

**Comment by maheshmnj** [comment]
Hi @CharithaRathnayake,

There is a similar issue describing this case https://github.com/flutter/flutter/issues/93905, Please follow up there for further updates, Closing this issue as a duplicate. 

Thank you.

**Comment by 0xZOne** [comment]
@CharithaRathnayake

An optional solution is to construct an `ExclusiveAppComponent<Activity>`  and implement the `getAppComponent ` interface to returan `Activity` correctly.

The Java sample code is as follows:

```java
   class FakeExclusiveAppComponent implements io.flutter.embedding.android.ExclusiveAppComponent<Activity> {
        public void detachFromFlutterEngine() {
            // do nothing.
        }

        public Activity getAppComponent() {
            return getActivity();
        }
    }

    getFlutterEngine().getActivityControlSurface().attachToActivity(fakeAppComponent, getLifecycle());
```
