### ISSUE TITLE
I'm having some problems through installation and can't seem to get through them

### ISSUE THREAD

**Issue by Jaxon10117** [flutter/flutter#96265]
Hello Flutter Devs!

So I'm having some problems on my M1 Pro mac here.
1. When I try to install flutter to my path permanently it works all fine but after terminal restart it still says flutter command not found
 2. When using flutter doctor and trying to use these commands (path/to/sdkmanager --install "cmdline-tools;latest", flutter doctor --android-licenses) it just says "zsh: permission denied: /Users/jaxonhensch/android" where i installed it even in the /Users/[my user]/Library/Android and everywhere I go I can't find my problem.

Can you guys possibly help?

**Comment by maheshmnj** [comment]
Hi @Jaxon10117, 
> When I try to install flutter to my path permanently it works all fine but after terminal restart it still says flutter command not found

It seems like you did not add the flutter/bin path to your shell file (.zshrc), Please see https://docs.flutter.dev/get-started/install/macos#update-your-path 


> When using flutter doctor and trying to use these commands (path/to/sdkmanager --install "cmdline-tools;latest", flutter doctor --android-licenses) it just says "zsh: permission denied: /Users/jaxonhensch/android" where i installed it even in the /Users/[my user]/Library/Android and everywhere I go I can't find my problem.


The easiest way to install command-line tools is through Android studio Please see this https://stackoverflow.com/a/68492909/8253662

If you need further help I would encourage you to please look for solution on StackOverflow.

Closing as this is neither an issue nor a feature request with flutter.
