### ISSUE TITLE
unchecked or unsafe operations

### ISSUE THREAD

**Issue by sisalik1** [flutter/flutter#96262]
Whenever I build or run I get this error:
...device_info-2.0.3\android\src\main\java\io\flutter\plugins\deviceinfo\DeviceInfoPlugin.java uses unchecked or unsafe operations.

> [√] Flutter (Channel beta, 2.9.0-0.1.pre, on Microsoft Windows [Version 10.0.19042.1415], locale en-US)
    • Flutter version 2.9.0-0.1.pre at E:\stuff\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8f1f9c10f0 (3 weeks ago), 2021-12-14 13:41:48 -0800
    • Engine revision 234aca678a
    • Dart version 2.16.0 (build 2.16.0-80.1.beta)
    • DevTools version 2.9.1

> [√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\Voistlused\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: E:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

> [√] Android Studio (version 2020.3)
    • Android Studio at E:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

> [√] VS Code (version 1.54.1)
    • VS Code at C:\Users\Voistlused\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

> [!] Connected device
    ! No devices available

**Comment by darshankawar** [comment]
@sisalik1 
The log seems to be coming from `device_info` plugin which has been deprecated in favor of community plugin `device_info_plus` : https://pub.dev/packages/device_info#deprecation-notice
Try using the new plugin and see if you still get the same log or not. If yes, you'll need to open the issue in dedicated repo.
Closing from here.
