### ISSUE TITLE
[webview_flutter] Unable to upload files

### ISSUE THREAD

**Issue by jimodelid** [flutter/flutter#96274]
We're using an integration to Liveagent for tickets, chatservice etc. We've made an flutter app for our customers with a webview to the chatservice so they can get in contact with us easily. 

Running the link we open in the webview in the web, eg chrome, it works as intended, can upload files etc. but running it in the webview we're able to type to eachother but whenever we try to upload files through the upload form nothing happens apart from endless loading.

We've tried adding all sorts of rights for both android and ios without success. I suspect this will be the same issue trying to upload to any other html form as well using the plugin.

Using the latest downloadable stable version of flutter, dart and webview flutter.

**Comment by darshankawar** [comment]
@jimodelid 
Can you check if you are hitting [this](https://github.com/flutter/flutter/issues/27924) issue ?
If not, then In order to properly address this, can you provide us a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example
) without any 3rd party plugins, that shows the current behavior you are seeing ?

**Comment by jimodelid** [comment]
> @jimodelid 
> 
> Can you check if you are hitting [this](https://github.com/flutter/flutter/issues/27924) issue ?
> 
> If not, then In order to properly address this, can you provide us a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example
> 
> ) without any 3rd party plugins, that shows the current behavior you are seeing ?
> 
> 
> 
> 

It looks like it's the same issue yes, sorry for making a new issue to an already existing issue.

**Comment by darshankawar** [comment]
Closing this as a duplicate.
