### ISSUE TITLE
FlutterView can't be used as a transparent overlay

### ISSUE THREAD

**Issue by ds84182** [flutter/flutter#9627]
[In engine, the screen is filled with SK_ColorBLACK.](https://github.com/flutter/engine/blob/1c07ea530f2c78b7e303c96b19994ff897498c2a/shell/gpu/gpu_rasterizer.cc#L136) This makes it impossible to use FlutterView as a transparent overlay, since canvas clearing is in the hands of the engine instead of the flutter application.

I've solved this temporarily by punching a hole in the Skia canvas by drawing a rectangle with the paint ``new Paint()..blendMode = BlendMode.clear;`` using a BoxDecoration and a BoxPainter, but this isn't very intuitive.

I've also hit some Android specific snags. It would be great if FlutterView had a method named `useAsOverlay` that calls `setZOrderOnTop(true)` and `getHolder().setFormat(PixelFormat.TRANSLUCENT)`. Right now my Android code depends on FlutterView being a SurfaceView, but I'm not entirely confident that it'll remain that way.

**Comment by abarth** [comment]
We should probably make this an option on the Java side because I think there's a performance hit for setting `PixelFormat.TRANSLUCENT`

/cc @jason-simmons

**Comment by ds84182** [comment]
So some (possibly engine) change broke this """hack""".

I can still use the clear blend mode to punch a hole through the canvas to make transparent regions... However I don't think the main framebuffer gets cleared. I see glitchy tiling artifacts instead. What you see is GPU dependent, but most phone CPUs should show some glitchy tiles from the previous frame.

Here's the code I'm using on the Flutter side:

```dart
import 'package:flutter/widgets.dart';

class HolePuncherPainter extends CustomPainter {
  static final clearPaint = new Paint()
    ..color = new Color(0x00000000)
    ..blendMode = BlendMode.clear;

  const HolePuncherPainter();

  @override
  void paint(Canvas canvas, Size size) {
    canvas.drawRect(
        new Rect.fromLTWH(0.0, 0.0, size.width, size.height), clearPaint);
  }

  @override
  bool shouldRepaint(CustomPainter oldDelegate) {
    return true;
  }
}

/// Punches a hole through the canvas for the given [child].
class HolePuncher extends StatelessWidget {
  final Widget child;

  const HolePuncher({Key key, this.child}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return new CustomPaint(
      painter: const HolePuncherPainter(),
      child: child,
      willChange: false,
    );
  }
}
```

And here's the relevant snippets needed for hole punching to work (in Java):

```java
getFlutterView().setZOrderOnTop(true);
getFlutterView().getHolder().setFormat(PixelFormat.TRANSPARENT); // (Or PixelFormat.TRANSLUCENT)
```

**Comment by ds84182** [comment]
I think the bug is happening because the main framebuffer isn't being cleared with glClear. When punching a hole through the Skia canvas it actually puts a hole in an auxiliary framebuffer that gets composted to the main thread. Avoiding glClear is an optimization though, since you wouldn't want the GPU to spend time clearing framebuffer pixels that will (generally) get rewritten with a new result. Perhaps the first layer in the stack can turn off blending and instead replace all pixels in the destination framebuffer.

**Comment by ds84182** [comment]
I _think_ I know what changed. In the engine commit "When the surface does not support SRGB, render to an offscreen texture", the offscreen texture path does not clear the onscreen skia canvas in GPUSurfaceGL::PresentScreen, causing the punchthrough to see the uncleared pixels from the onscreen framebuffer. I've check my EGL extensions and I don't see anything pertaining to colorspace or sRGB.

https://github.com/flutter/engine/commit/ddaa125ca7845ee177ceca6078d0aae3a675c4a6#diff-5d38bce69c8511388c326277e128c0c3R221

**Comment by eseidelGoogle** [comment]
@ds84182 would you be willing to post a PR to fix?

**Comment by ds84182** [comment]
I don't really have the ability to build the engine currently (Linux laptop
has 0 drive space and I can't cross compile to Android on my Windows
laptop).

**Comment by mzgreen** [comment]
What is the current status of this one?

**Comment by MehdiChouag** [comment]
Is there anything new on this topic?

**Comment by eseidelGoogle** [comment]
This may be an easy fix.  I'm not aware of any status changes.  @mravn-google has also been looking into Hole-punching solutions which may have run into this as well, not sure.

**Comment by mravn-google** [comment]
If I recall correctly, my hole punching solution did not involve changes to Java code. I did make some changes to flutter/engine compositing, though, to ensure that holes were punched through every layer, including "physical models" (cards) and took proper account of transformations, clipping etc.

Details are available here: https://github.com/mravn-google/engine/commits/inline_maps

Please note that my holes experiment was discontinued due to the inherent problem of composing holes with other widgets (e.g. blending pixels visible through the hole with pixels painted by Flutter).

**Comment by Piasy** [comment]
@ds84182 I use your code, it works well in Nexus 5X, API 27, what device did you use?

**Comment by ds84182** [comment]
Moto Z Play. There's been a bunch of changes to how rendering works in Flutter since last April, so hole punching could have been fixed at any time in the last year. In my personal project I rewrote the OpenGL rendering bits to use a Texture instead of being an underlay, so I haven't depended on hole punching in a while.

**Comment by Piasy** [comment]
@ds84182 I got it, thanks! I'll try to test hole punching in different devices and verify its functionality.

By the way, if you render your own content into a texture, how do you compose it with flutter's content? write a custom flutter widget? or modify the flutter engine?

**Comment by ds84182** [comment]
You use the [Texture widget](https://docs.flutter.io/flutter/widgets/Texture-class.html) in the widgets library. [The video_player plugin uses the Texture widget to render videos into Flutter](https://github.com/flutter/plugins/tree/master/packages/video_player). On Android you can use EGL to set up an OpenGL context on the [SurfaceTexture](https://developer.android.com/reference/android/graphics/SurfaceTexture.html) given to you by Flutter, but for iOS I'm not too sure (but its probably possible!). [This example shows how to set up EGL on a SurfaceTexture (on Android)](https://github.com/egslava/Example-Android-TextureView-OpenGL-Stable/blob/master/app/src/main/java/ru/egslava/ktve/MainActivity.kt).

**Comment by ds84182** [comment]
I don't think it's a good idea to use TextureView. iirc TextureView will cause Android's normal view hierarchy to redraw after every Flutter frame, which adds CPU and GPU load. Meanwhile, SurfaceView uses the built in window compositing provided by SurfaceFlinger, which is certainly faster in most situations since 99% of phones composite using specialized hardware.

**Comment by mzgreen** [comment]
Another drawback of `SurfaceView` is that it doesn't support animations. You can't grab it and fade out for example. I think `TextureView` would be a better choice. It acts more like a normal Android view where `SurfaceView` is like punching a hole in a view hierarchy.

**Comment by ds84182** [comment]
I do see a use case for this, but it should be opt-in, since most Flutter users aren't going to mess with the FlutterView on the Android side.

In fact, most Flutter users aren't even going to use Android's native view hierarchy in addition to Flutter, so possibly in the future [Window.takeSurface](https://developer.android.com/reference/android/view/Window.html#takeSurface(android.view.SurfaceHolder.Callback2)) can be used to prevent Android from having to composite both Flutter's surface and the default surface provided to the Activity (this could be a performance win on older devices too, where there are memory constraints).

**Comment by mzgreen** [comment]
Actually I think we can even have both. GL related code can be abstracted away so supporting both TextureView and SurfaceView may not be so difficult.

**Comment by mklim** [comment]
Yeah, dug into it in more depth today and TextureView has some significant performance drawbacks like @ds84182 mentioned, thanks. Composition with it is always performed with OpenGL ES instead of done directly via SurfaceFlinger like in SurfaceView, and whenever it's updated it looks like composition is completely redone.

With that in mind, it makes more sense for this specific issue to keep the current implementation and add an Android specific helper method to `FlutterView.java` for using it as a transparent overlay like originally suggested. We could look into adding a TextureView version of FlutterView as a feature in its own right if there's a strong need for FlutterView to integrate better with the native view hierarchy in general.

**Comment by phanirithvij** [comment]
@mklim how can I use that method in my code? I'm a beginner and I just have the default code from `flutter create` right now in my `android/app/src/main/java/com/example/coolapp/MainActivity.java` i.e.
```java
package com.example.coolapp;

import android.os.Bundle;
import io.flutter.app.FlutterActivity;
import io.flutter.plugins.GeneratedPluginRegistrant;

public class MainActivity extends FlutterActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        GeneratedPluginRegistrant.registerWith(this);
    }
}
```
The mainactivity extends `FlutterActivity` but I see no `FlutterView` or `SurfaceView` or `TextureView` anywhere mentioned here.
A sample code demonstrating how to make the background transparent would be appreciated.

**Comment by Jon-Salmon** [comment]
I would not recommend doing this unless there is no alternative. In addition to the issues discussed above, to get touch events to be sent to both the flutter app and the android app requires manually routing events with an onTouchListener.

That being said, if you need to do this it is possible and can be made to work sufficiently well for a production app, although it does introduce a lot of additional complexities in other areas.

You need to call `flutterView.enableTransparentBackground();` in your android `onCreate` method.

You then need to wrap your app in a widget to puch a hole through the canvas onto the android app behind and add this to your scaffold `backgroundColor: Colors.transparent`

```
/// Punches a hole through the canvas for the given [child].
class HolePuncher extends StatelessWidget {
  final Widget child;

  const HolePuncher({Key key, this.child}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return new CustomPaint(
      painter: const HolePuncherPainter(),
      child: child,
      willChange: true,
    );
  }
}

class HolePuncherPainter extends CustomPainter {
  static final clearPaint = new Paint()
    ..color = new Color(0x00000000)
    ..blendMode = BlendMode.clear;

  const HolePuncherPainter();

  @override
  void paint(Canvas canvas, Size size) {
    canvas.drawRect(
        new Rect.fromLTWH(0.0, 0.0, size.width, size.height), clearPaint);
  }

  @override
  bool shouldRepaint(CustomPainter oldDelegate) {
    return true;
  }
}
```

**Comment by phanirithvij** [comment]
@Jon-Salmon `flutterView.enableTransparentBackground` was deprecated and then removed. I've been using

```kotlin
val transparentFlutterView = FlutterView(applicationContext, FlutterView.TransparencyMode.transparent)
```

And now this is deprecated as well.
