### ISSUE TITLE
[google_map_flutter] I don't want the camera to move when I click the marker

### ISSUE THREAD

**Issue by jsolra** [flutter/flutter#96271]
Hello,
I'm using the **[google_map_flutter]** package.

When I click the marker, I don't want the screen to move to the center of the marker.
Is there a way?

**Comment by darshankawar** [comment]
@jsolra 
Your question is better suited for support channels like StackOverflow, so please ask the same there.
If you think this is a bug or would like this to be a feature request, write in comments by providing all required details from the issue template and we'll address it.
If you are looking for a solution, as mentioned above, please ask the same in StackOverflow.
