### ISSUE TITLE
Cannot flutter create when offline

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#96286]
# Without flag 

## Repro steps

1. Download a stable macOS build from the releases page: https://docs.flutter.dev/development/tools/sdk/releases

2. Go offline (turn off wifi and anyther other network connection)

3. Extract the downloaded zip (e.g. ~/tmp/flutter)

4. Open a terminal, and run `~/tmp/flutter/bin/flutter create app1`

## Actual result

The command hangs:

```
mit-macbookpro4:tmp mit$ ./flutter/bin/flutter create app2
Running "flutter pub get" in flutter_tools...                          ⢿
```

If you run it with verbose, you can see it's failing trying to get to pub:
https://gist.github.com/mit-mit/17d8f6c21f8970fb6b9dba9e0f24c4cb

## Expected result

The command doesn't hang. We should probably detect that we're offline and pass the --offline flag? Looks like that might be tracked in https://github.com/flutter/flutter/issues/15717

# With flag 

## Repro steps

1. Download a stable macOS build from the releases page: https://docs.flutter.dev/development/tools/sdk/releases

2. Go offline (turn off wifi and anyther other network connection)

3. Extract the downloaded zip (e.g. ~/tmp/flutter)

4. Open a terminal, and run `~/tmp/flutter/bin/flutter create --offline app1`

## Actual result

The command fails trying to download some pub packages ([full log file](https://gist.github.com/mit-mit/5839997c24d6feba0174f36f095d0ba6)):

```
mit-macbookpro4:tmp mit$ ./flutter/bin/flutter --verbose create --offline foobar
...
[ +105 ms] MSG : Resolving dependencies...
[  +76 ms] SLVR: fact: flutter_tools is 0.0.0
...
[ +175 ms] MSG : Resolving dependencies...
...
[        ] SLVR: fact: flutter_tools depends on test 1.17.12
...
[  +13 ms] IO  : Get versions from https://pub.dartlang.org/api/packages/test.
[  +18 ms] IO  : HTTP GET https://pub.dartlang.org/api/packages/test
[        ]     | Accept: application/vnd.pub.v2+json
[        ]     | X-Pub-OS: macos
[        ]     | X-Pub-Command: get
[        ]     | X-Pub-Session-ID: DDBCDF1B-745B-4417-B0A9-ABE58D1EF131
[        ]     | X-Pub-Environment: flutter_cli:get
[        ]     | user-agent: Dart pub 2.15.1
[  +91 ms] IO  : HTTP error:
[        ]     | SocketException: Failed host lookup: 'pub.dartlang.org' (OS Error: nodename nor servname provided, or not known, errno = 8)

```

## Expected result

The command doesn't hang. 

Are the dependencies of the flutter tool not expected to be pre-populated into the cache? It looks like it doesn't have test 1.17.2:

```
mit-macbookpro4:pub.dartlang.org mit$ pwd
/Users/mit/tmp/flutter/.pub-cache/hosted/pub.dartlang.org

mit-macbookpro4:pub.dartlang.org mit$ ls -l | grep test
drwx------@  7 mit  primarygroup  224 Dec 16 20:31 file_testing-3.0.0
drwx------@ 14 mit  primarygroup  448 Dec 16 20:31 test-1.17.12
drwx------@ 10 mit  primarygroup  320 Dec 16 20:31 test_api-0.4.3
drwx------@  8 mit  primarygroup  256 Dec 16 20:31 test_core-0.4.2
```

**Comment by maheshmnj** [comment]
Hi @mit-mit, Thanks for filing the issue. I can reproduce the issue, the flutter create fails when offline with a newly downloaded flutter SDK on `stable  2.8.1`, 
Here are the complete [verbose logs ](https://github.com/flutter/flutter/files/7837222/logs.txt)


<details>
<summary>flutter doctor -v</summary>

```
mahesh@Maheshs-MacBook-Air-M1 Downloads % ~/Downloads/flutter/bin/flutter doctor -v   
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.8.1 at /Users/mahesh/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (4 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • B622CBB7-F906-4FA7-8F49-FACEAAC905AB • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5
      (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 96.0.4664.110

• No issues found!
```
</details>

**Comment by christopherfujino** [comment]
so `flutter create --offline` is a thing, but we should probably time out the pub get and then give the user a hint.

**Comment by jmagman** [comment]
See also https://github.com/flutter/flutter/issues/15717.

**Comment by mit-mit** [comment]
> so flutter create --offline is a thing

Yeah, but that doesn't work either! Updated the repro steps as this wasn't clear from the original ones.

**Comment by christopherfujino** [comment]
> > so flutter create --offline is a thing
> 
> Yeah, but that doesn't work either! Updated the repro steps as this wasn't clear from the original ones.

Ooh, that's even worse

**Comment by Jasguerrero** [comment]
Working on this issue found out that requesting PubDependencies as a default ArtifactSet on flutter_cache.dart was hitting the internet even though the --offline flag was on; replacing "universal" with "web" (only make pub dependencies run when the user is building for the web) seems like a good fix as @jonahwilliams and @christopherfujino suggested; following that path we skip the flutter pub get on the flutter_tool package and just do it inside the new "app1" folder. Will upload a PR soon.

**Comment by mit-mit** [comment]
Sorry, I'm not sure I understand the "universal"/"web" part? I don't think the Flutter tooling should do anything pub specific. It should just make sure that the needed versions are in the cache (currently they are not).

**Comment by Jasguerrero** [comment]
Yeah sorry that was kind of confusing, so in short there is a "flutter pub get" inside the flutter_tool when the create command run with or without the --ofline flag when it is not required to actually create the app; the PR will skip that with the "universal"/"web"

**Comment by mit-mit** [comment]
I don't undersstand how we can skip `flutter pub get` -- then we won't have a `pubspec.lock` and `.dart-tool/package_config.json` file, and the app wouldn't be able to run?

**Comment by Jasguerrero** [comment]
The wrong flutter pub get was inside the flutter_tool not in the actual app there is an extra pub get inside the newly created app which is not skipped

**Comment by Jasguerrero** [comment]
Right now when we call "flutter create --offline app1" the command invokes "flutter pub get" twice

1. Inside the flutter_tools package (which is the error is in your logs) this flutter pub get is to get the dwds debugging tool which is not needed to create the app on --offline (https://github.com/flutter/flutter/pull/65814)
2. Inside the newly created app1 folder we call pub get once again this one will fail even with offline if the pubcache has not been populated (the command exits with throwToolExit code 69 for missing dependencies)

The fix will be on step 1 to avoid doing that flutter pub get inside flutter tools

**Comment by mit-mit** [comment]
Why not rather update the caching script to actually populate the cache entries that `flutter_tools` needs?
https://github.com/flutter/flutter/blob/master/dev/bots/prepare_package.dart#L403

**Comment by Jasguerrero** [comment]
> Why not rather update the caching script to actually populate the cache entries that `flutter_tools` needs? https://github.com/flutter/flutter/blob/master/dev/bots/prepare_package.dart#L403

As I discussed over video call with @mit-mit the flutter_tools actually have all the dependencies needed but the first flutter pub get inside the futter_tools package was not passed the --offline flag so the fix for removing this unnecessary get stands.

**Comment by bitsydarel** [comment]
Can the flutter tooling also add support for **--offline** in the **flutter run** command ?

Basically also adding **--offline** flag to gradle commands ?

Because even if you do a **flutter pub get --offline**

You can't execute **flutter run** as this will still fail because no connection is available.

**Comment by Jasguerrero** [comment]
Reopening because this had to be reverted due to https://github.com/flutter/flutter/issues/100350
