### ISSUE TITLE
[camera] Captured picture dark on Android

### ISSUE THREAD

**Issue by theochampion** [flutter/flutter#96284]
Hi there,

I'm having issues with the latest `0.9.4+5` version of the `camera` plugin. When I run my app on Android, the camera preview look fine but once I capture, the image looks dark (probably exposure).

The issue seems to be coming from the rework of the Android in `9.0.1` https://pub.dev/packages/camera/changelog#091 since I don't get the issue in `0.8.1+7`.

The reproduce the issue, run this project https://github.com/jagrut-18/flutter_camera_app.
In the default config, it is using `0.8.1+7` so it should work fine:

Preview:
https://user-images.githubusercontent.com/14275989/148556155-d78aed4c-7832-4f93-81af-2d1bd12bebdf.png
Captured images:
https://user-images.githubusercontent.com/14275989/148556510-f1272afb-95e8-4a84-be36-48d0298b3d47.png

Now change the dependency of `camera` to `0.9.4+5` (don't forget to change the Android compileSdkVersion to 31 too)
Run again, now the captured pics will appear darker than preview.

Preview:
https://user-images.githubusercontent.com/14275989/148556976-081fb2a4-e48d-4de6-af0f-ac6e93fd4a36.png
Cpatured images:
https://user-images.githubusercontent.com/14275989/148557014-b34a2f4f-4c0f-4187-90c3-7b57fb46a68b.png

Anyone running into the same issue ?

PS: My device is a Pixel 4

**Comment by darshankawar** [comment]
@theochampion 
Does it only occur with images or with video too ?
Can you also check the same behavior on other Android device and see if it persists on it ?
Also, can you run the plugin's [example](https://pub.dev/packages/camera/example) on affected device and see if the behavior persists with it too ?
