### ISSUE TITLE
I have issue when run flutter desktop 

### ISSUE THREAD

**Issue by idexxpro** [flutter/flutter#96287]
flutter_window.obj : warning LNK4075: ignoring '/EDITANDCONTINUE' due to '/SAFESEH' specification [E:\Test odoo\testwindowsapp\build\windows\runner\testwindowsapp.vcxproj]
flutter_window.obj : error LNK2019: unresolved external symbol __imp__FlutterDesktopViewGetHWND referenced in function "public: struct HWND__ * 
__thiscall flutter::FlutterView::GetNativeWindow(void)" (?GetNativeWindow@FlutterView@flutter@@QAEPAUHWND__@@XZ) [E:\Test odoo\testwindowsapp\build\windows\runner\testwindowsapp.vcxproj]
utils.obj : error LNK2019: unresolved external symbol __imp__FlutterDesktopResyncOutputStreams referenced in function "void __cdecl CreateAndAttachConsole(void)" (?CreateAndAttachConsole@@YAXXZ) [E:\Test odoo\testwindowsapp\build\windows\runner\testwindowsapp.vcxproj]
win32_window.obj : error LNK2019: unresolved external symbol __imp__FlutterDesktopGetDpiForMonitor referenced in function "public: bool __thiscall Win32Window::CreateAndShow(class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &,struct Win32Window::Point const &,struct Win32Window::Size const &)" (?CreateAndShow@Win32Window@@QAE_NABV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@ABUPoint@1@ABUSize@1@@Z) [E:\Test odoo\testwindowsapp\build\windows\runner\testwindowsapp.vcxproj]
flutter_wrapper_app.lib(flutter_engine.obj) : error LNK2019: unresolved external symbol __imp__FlutterDesktopEngineCreate referenced in function "public: __thiscall flutter::FlutterEngine::FlutterEngine(class flutter::DartProject const &)" (??0FlutterEngine@flutter@@QAE@ABVDartProject@1@@Z) [E:\Test odoo\testwindowsapp\build\windows\runner\testwindowsapp.vcxproj]
flutter_wrapper_app.lib(flutter_engine.obj) : error LNK2019: unresolved external symbol __imp__FlutterDesktopEngineDestroy referenced in function "public: void __thiscall flutter::FlutterEngine::ShutDown(void)" (?ShutDown@FlutterEngine@flutter@@QAEXXZ) [E:\Test odoo\testwindowsapp\build\windows\runner\testwindowsapp.vcxproj]
flutter_wrapper_app.lib(flutter_engine.obj) : error LNK2019: unresolved external symbol __imp__FlutterDesktopEngineRun referenced in function "public: bool __thiscall flutter::FlutterEngine::Run(char const *)" (?Run@FlutterEngine@flutter@@QAE_NPBD@Z) [E:\Test odoo\testwindowsapp\build\windows\runner\testwindowsapp.vcxproj]
flutter_wrapper_app.lib(flutter_engine.obj) : error LNK2019: unresolved external symbol __imp__FlutterDesktopEngineProcessMessages referenced in function "public: class std::chrono::duration<__int64,struct std::ratio<1,1000000000> > __thiscall flutter::FlutterEngine::ProcessMessages(void)" (?ProcessMessages@FlutterEngine@flutter@@QAE?AV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@XZ) [E:\Test odoo\testwindowsapp\build\windows\runner\testwindowsapp.vcxproj]
flutter_wrapper_app.lib(flutter_engine.obj) : error LNK2019: unresolved external symbol __imp__FlutterDesktopEngineReloadSystemFonts referenced 
in function "public: void __thiscall flutter::FlutterEngine::ReloadSystemFonts(void)" (?ReloadSystemFonts@FlutterEngine@flutter@@QAEXXZ) [E:\Test odoo\testwindowsapp\build\windows\runner\testwindowsapp.vcxproj]
flutter_wrapper_app.lib(flutter_engine.obj) : error LNK2019: unresolved external symbol __imp__FlutterDesktopEngineReloadPlatformBrightness referenced in function "public: void __thiscall flutter::FlutterEngine::ReloadPlatformBrightness(void)" (?ReloadPlatformBrightness@FlutterEngine@flutter@@QAEXXZ) [E:\Test odoo\testwindowsapp\build\windows\runner\testwindowsapp.vcxproj]
flutter_wrapper_app.lib(flutter_engine.obj) : error LNK2019: unresolved external symbol __imp__FlutterDesktopEngineGetPluginRegistrar referenced in function "public: virtual struct FlutterDesktopPluginRegistrar * __thiscall flutter::FlutterEngine::GetRegistrarForPlugin(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?GetRegistrarForPlugin@FlutterEngine@flutter@@UAEPAUFlutterDesktopPluginRegistrar@@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) [E:\Test odoo\testwindowsapp\build\windows\runner\testwindowsapp.vcxproj]
flutter_wrapper_app.lib(flutter_engine.obj) : error LNK2019: unresolved external symbol __imp__FlutterDesktopEngineGetMessenger referenced in function "public: __thiscall flutter::FlutterEngine::FlutterEngine(class flutter::DartProject const &)" (??0FlutterEngine@flutter@@QAE@ABVDartProject@1@@Z) [E:\Test odoo\testwindowsapp\build\windows\runner\testwindowsapp.vcxproj]
flutter_wrapper_app.lib(flutter_view_controller.obj) : error LNK2019: unresolved external symbol __imp__FlutterDesktopViewControllerCreate referenced in function "public: __thiscall flutter::FlutterViewController::FlutterViewController(int,int,class flutter::DartProject const &)" (??0FlutterViewController@flutter@@QAE@HHABVDartProject@1@@Z) [E:\Test odoo\testwindowsapp\build\windows\runner\testwindowsapp.vcxproj]
flutter_wrapper_app.lib(flutter_view_controller.obj) : error LNK2019: unresolved external symbol __imp__FlutterDesktopViewControllerDestroy referenced in function "public: virtual __thiscall flutter::FlutterViewController::~FlutterViewController(void)" (??1FlutterViewController@flutter@@UAE@XZ) [E:\Test odoo\testwindowsapp\build\windows\runner\testwindowsapp.vcxproj]
flutter_wrapper_app.lib(flutter_view_controller.obj) : error LNK2019: unresolved external symbol __imp__FlutterDesktopViewControllerGetView referenced in function "public: __thiscall flutter::FlutterViewController::FlutterViewController(int,int,class flutter::DartProject const &)" (??0FlutterViewController@flutter@@QAE@HHABVDartProject@1@@Z) [E:\Test odoo\testwindowsapp\build\windows\runner\testwindowsapp.vcxproj]
flutter_wrapper_app.lib(flutter_view_controller.obj) : error LNK2019: unresolved external symbol __imp__FlutterDesktopViewControllerHandleTopLevelWindowProc referenced in function "public: class std::optional<long> __thiscall flutter::FlutterViewController::HandleTopLevelWindowProc(struct HWND__ *,unsigned int,unsigned int,long)" (?HandleTopLevelWindowProc@FlutterViewController@flutter@@QAE?AV?$optional@J@std@@PAUHWND__@@IIJ@Z) 
[E:\Test odoo\testwindowsapp\build\windows\runner\testwindowsapp.vcxproj]
flutter_wrapper_app.lib(core_implementations.obj) : error LNK2019: unresolved external symbol __imp__FlutterDesktopMessengerSend referenced in function "public: virtual void __thiscall flutter::BinaryMessengerImpl::Send(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,unsigned char const *,unsigned int,class std::function<void __cdecl(unsigned char const *,unsigned int)>)const " (?Send@BinaryMessengerImpl@flutter@@UBEXABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PBEIV?$function@$$A6AXPBEI@Z@4@@Z) [E:\Test odoo\testwindowsapp\build\windows\runner\testwindowsapp.vcxproj]
flutter_wrapper_app.lib(core_implementations.obj) : error LNK2019: unresolved external symbol __imp__FlutterDesktopMessengerSendWithReply referenced in function "public: virtual void __thiscall flutter::BinaryMessengerImpl::Send(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,unsigned char const *,unsigned int,class std::function<void __cdecl(unsigned char const *,unsigned int)>)const " (?Send@BinaryMessengerImpl@flutter@@UBEXABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PBEIV?$function@$$A6AXPBEI@Z@4@@Z) [E:\Test odoo\testwindowsapp\build\windows\runner\testwindowsapp.vcxproj]
flutter_wrapper_app.lib(core_implementations.obj) : error LNK2019: unresolved external symbol __imp__FlutterDesktopMessengerSendResponse referenced in function "public: void __thiscall <lambda_18bb8b2f970f177297dcaf44953dd18e>::operator()(unsigned char const *,unsigned int)" (??R<lambda_18bb8b2f970f177297dcaf44953dd18e>@@QAEXPBEI@Z) [E:\Test odoo\testwindowsapp\build\windows\runner\testwindowsapp.vcxproj]
flutter_wrapper_app.lib(core_implementations.obj) : error LNK2019: unresolved external symbol __imp__FlutterDesktopMessengerSetCallback referenced in function "public: virtual void __thiscall flutter::BinaryMessengerImpl::SetMessageHandler(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::function<void __cdecl(unsigned char const *,unsigned int,class std::function<void __cdecl(unsigned char const *,unsigned int)>)>)" (?SetMessageHandler@BinaryMessengerImpl@flutter@@UAEXABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$function@$$A6AXPBEIV?$function@$$A6AXPBEI@Z@std@@@Z@4@@Z) [E:\Test odoo\testwindowsapp\build\windows\runner\testwindowsapp.vcxproj]
flutter_wrapper_app.lib(core_implementations.obj) : error LNK2019: unresolved external symbol __imp__FlutterDesktopTextureRegistrarRegisterExternalTexture referenced in function "public: virtual __int64 __thiscall flutter::TextureRegistrarImpl::RegisterTexture(class std::variant<class flutter::PixelBufferTexture> *)" (?RegisterTexture@TextureRegistrarImpl@flutter@@UAE_JPAV?$variant@VPixelBufferTexture@flutter@@@std@@@Z) [E:\Test odoo\testwindowsapp\build\windows\runner\testwindowsapp.vcxproj]
flutter_wrapper_app.lib(core_implementations.obj) : error LNK2019: unresolved external symbol __imp__FlutterDesktopTextureRegistrarUnregisterExternalTexture referenced in function "public: virtual bool __thiscall flutter::TextureRegistrarImpl::UnregisterTexture(__int64)" (?UnregisterTexture@TextureRegistrarImpl@flutter@@UAE_N_J@Z) [E:\Test odoo\testwindowsapp\build\windows\runner\testwindowsapp.vcxproj]
flutter_wrapper_app.lib(core_implementations.obj) : error LNK2019: unresolved external symbol __imp__FlutterDesktopTextureRegistrarMarkExternalTextureFrameAvailable referenced in function "public: virtual bool __thiscall flutter::TextureRegistrarImpl::MarkTextureFrameAvailable(__int64)" 
(?MarkTextureFrameAvailable@TextureRegistrarImpl@flutter@@UAE_N_J@Z) [E:\Test odoo\testwindowsapp\build\windows\runner\testwindowsapp.vcxproj]  
E:\Test odoo\testwindowsapp\windows\flutter\ephemeral\flutter_windows.dll.lib : warning LNK4272: library machine type 'x64' conflicts with target machine type 'x86' [E:\Test odoo\testwindowsapp\build\windows\runner\testwindowsapp.vcxproj]
E:\Test odoo\testwindowsapp\build\windows\runner\Debug\testwindowsapp.exe : fatal error LNK1120: 22 unresolved externals [E:\Test odoo\testwindowsapp\build\windows\runner\testwindowsapp.vcxproj]

**Comment by stuartmorgan** [comment]
> warning LNK4272: library machine type 'x64' conflicts with target machine type 'x86'

32-bit Windows is not a supported target.
