### ISSUE TITLE
[Web]: Proposal to be able to build flutter web app with debug profile support

### ISSUE THREAD

**Issue by arturk** [flutter/flutter#96283]
`flutter build web` command is used to generate release build of flutter application. But for testing purposes we need to deploy debug version of the application to the local server. We need the support of the builds where assert instructions are executed to be able to access the render tree of the deployed application. At the moment it is possible to do with `flutter run -d chrome` but that is not the command that is used to generate files that can be put into the server

So something like `flutter build web --debug` can be beneficial especially when there is `flutter build web --profile` already exists.

**Comment by eggnstone** [comment]
> **We really need a build option that shows a stack trace with the exact line of code that is throwing the exception.**

Agreed!
In the meantime this may help:
`flutter build web --profile --dart-define=Dart2jsOptimization=O0`
(taken from https://stackoverflow.com/a/64511666/837507)

**Comment by arturk** [comment]
> > **We really need a build option that shows a stack trace with the exact line of code that is throwing the exception.**
> 
> Agreed! In the meantime this may help: `flutter build web --profile --dart-define=Dart2jsOptimization=O0` (taken from https://stackoverflow.com/a/64511666/837507)

This helps just a bit but does not provide full debug capabilities. For example in my tests in case of failure I attach to the report a widgets tree to shown what was on the screen during the failure and with what params. The flutter driver extension is capable of getting a widgets tree in debug mode but not in profile mode. I was still able to write a function that can collect a list of all widgets, but tree is way more comfortable.

**Comment by jarrodcolburn** [comment]
I really need something for use case for web: 
Build/run remotely -> Debug locally (in Chrome)

the only thing that even comes close is `-d web-server` which has missing features and seems to have been abandoned (requires Dart Chrome Extension and usually doesn't connect consistently).

Interestingly similar use case for Android:
Run remotely -> Debug locally in Android Emulator
can be accomplished by port forwarding `adb` over ssh.

This seems like it would be more technically complex, but it works.

**Comment by arthurfp** [comment]
110% Agree: "**We really need a build option that shows a stack trace with the exact line of code that is throwing the exception**."

IMO, This is one of hte most important features (I know companies that chose React over Flutter because of the problem with bug tracking/report)

**Comment by jstdk** [comment]
This feature is really needed, now I have to echo/output values into Text widgets in order test, like for example facebook_flutter_auth, since they do not longer allow oAuth2 redirects uri that have http. 

The only way expose a test version of the app local;ly is using ngrok & python, but then I loose the debug capabilities. 

build app : flutter build web
change dir : cd <pathProject>/web/build
up any server : python3 -m http.server 5000
up ngrok : ngrok http.server 5000
in mobile browser : "https://a824ccb9d545.ngrok.io " (example)

**Comment by makinghappen** [comment]
any hope this would be implemented?

**Comment by vasba** [comment]
Implement this please.
