### ISSUE TITLE
[image_picker][Web]: GIFs don't animate if selected from `photos` folder on the OS

### ISSUE THREAD

**Issue by m-j-g** [flutter/flutter#96290]
1.) Run the example image_picker app on web
2.) Pick a GIF
3.) Doesn't animate

**Comment by darshankawar** [comment]
@m-j-g 
Ran the image_picker plugin [example](https://github.com/flutter/plugins/tree/master/packages/image_picker/image_picker/example) on web and selected a GIF which plays / animates properly without any issues:


https://user-images.githubusercontent.com/67046386/148726558-800cc48a-e2fa-4dd9-97d2-85f485b49f5d.mov

**Comment by darshankawar** [comment]
@m-j-g 
Thanks for digging in. I do see the same behavior by selecting a GIF from `photos` folder:

<img width="878" alt="Screenshot 2022-01-11 at 11 42 09 AM" src="https://user-images.githubusercontent.com/67046386/148890630-ba76e9d8-d04f-47b9-958e-2319482b6e15.png">


Keeping it open to know if this is a OS limitation or potential plugin issue.

<details>
<summary> stable, master flutter doctor -v </summary>

```
[[✓] Flutter (Channel stable, 2.8.1, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.8.1 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (13 hours ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 93.0.4577.82


• No issues found!

[✓] Flutter (Channel master, 2.9.0-1.0.pre.295, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.9.0-1.0.pre.295 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 83bb08fb37 (14 hours ago), 2022-01-09 10:05:18 -0500
    • Engine revision 94786ae707
    • Dart version 2.16.0 (build 2.16.0-144.0.dev)
    • DevTools version 2.9.2
    • PATH =
      /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/binpplicat
      ions/Software_Setup/flutter/bin:/Users/dhs/triagemagic/bin/:/Users/dhs/doc
      uments/fluttersdk/flutter/bin:/emulator:/tools:/tools/bin:/platform-tools:
      /Users/dhs/.pub-cache/bin
    
[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 93.0.4577.82


• No issues found!




```

</details>

**Comment by yjbanov** [comment]
IIUC image picker is just a file picker in disguise. So we should be just getting the bytes for the GIF and animate it. Unless the OS is giving us malformed GIF bytes or something. Does this happen only in CanvasKit or in HTML too?

**Comment by ditman** [comment]
I don't have the `photos` folder on MacOS.... What is the `photos` folder? :)

**Comment by darshankawar** [comment]
> Does this happen only in CanvasKit or in HTML too?

Happens with both.



> What is the `photos` folder? :)

I think you have media or photos on your macOS, you'll see `photos` folder to choose from.

<img width="161" alt="Screenshot 2022-01-14 at 10 18 17 AM" src="https://user-images.githubusercontent.com/67046386/149453583-b754a405-a1be-4440-b4cf-1ecc1bea2369.png">
<img width="159" alt="Screenshot 2022-01-14 at 10 21 24 AM" src="https://user-images.githubusercontent.com/67046386/149453598-b9d30060-ecad-4129-a2ed-ac4cc55a9fa1.png">

**Comment by ditman** [comment]
To enable those special options in the finder, press `Cmd + ,` in a finder window (Opens "Finder Preferences"), then in the "Sidebar" tab, enable Movies/Music/Pictures:

<img width="381" alt="Screen Shot 2022-04-15 at 11 22 57 AM" src="https://user-images.githubusercontent.com/1255594/163607155-fd8118e2-54dc-429a-b227-d47fa35a6297.png">

**Comment by ditman** [comment]
When selecting from the Media/Photos section:

<img width="804" alt="Screen Shot 2022-04-15 at 12 10 42 PM" src="https://user-images.githubusercontent.com/1255594/163622496-4ee9cf23-052d-4898-81fc-3ba94ad050fd.png">

This is the file that the browser gets:

![Screen Shot 2022-04-15 at 11 59 20 AM](https://user-images.githubusercontent.com/1255594/163622737-bb16a78a-eb30-4783-a9ff-fa4cb394a7aa.png)

However when selecting straight from the Desktop directory:

<img width="804" alt="Screen Shot 2022-04-15 at 12 11 21 PM" src="https://user-images.githubusercontent.com/1255594/163622545-62df7ad3-50ee-43b6-9c62-856bce411521.png">

This is what the browser gets:

![Screen Shot 2022-04-15 at 12 02 49 PM](https://user-images.githubusercontent.com/1255594/163622745-5b1b0717-a8a7-4529-8492-ba7ae9651b10.png)

This happens with **ALL BROWSERS** on MacOS (verified in Safari, Firefox and Chrome), so it's probably an OS feature (?)

I don't think this feature can be disabled from the Browser, let me dig a little bit deeper.

**Comment by ditman** [comment]
I cannot find what's the name of this "feature", but you can see it's not related to flutter just by doing (in Firefox, for example):

1. File > Open File...
2. In the open file select "Photos" inside of "Media"
3. Select an "animated" file from there.
4. The selected file will *not* animate, and the URL will be something like:
   * `file:///Users/dit/Pictures/Photos%20Library.photoslibrary/resources/derivatives/masters/D/D37FEE2C-A39F-4872-BB6A-E33DA7A9EF81_4_5005_c.jpeg`

**The Open File dialog is feeding the browser a "preview" of the animated gif, and not the animated gif itself.**

**Comment by ditman** [comment]
@darshankawar do you think we can close this as "there's nothing we can do from the browser"?

**Comment by darshankawar** [comment]
Thanks @ditman for digging in. Really helpful to know the info you shared. I think we can close this since this doesn't seem specific to Flutter and may be an OS feature or a bug.

@m-j-g fyi.
