### ISSUE TITLE
UPI LAUNCHER

### ISSUE THREAD

**Issue by chetanxpatil** [flutter/flutter#96305]
## Use case
To launch UPI Link that can directly route users to select app and launch the payment

## Proposal
upi://pay?pa=chetan12patil@okhdfcbank&pn=Chetan%20Patil

The Upi link for payment look like above link . 
Where "upi" is the scheme, "pay" is the authority and "pa","pn" etc are the query paramaters. this will ease the process of payment. it will be very helpful if you can do so,

Example is this can help you 

Map<String, String> param = {
  'pa': 'chetan12patil@okhdfcbank',
  'pn': 'Chetan Patil',
};

 final xyz = Uri(scheme: "upi", queryParameters: param,host: "pay");

**Comment by stuartmorgan** [comment]
The first-party `url_launcher` plugin already allows launching arbitrary URLs.

**Comment by chetanxpatil** [comment]
url_launcher dont do the job of launching upi links.upi links are deeplinks which trigger upi appication

**Comment by stuartmorgan** [comment]
> url_launcher dont do the job of launching upi links.

Please file a new issue demonstrating your attempt to use `url_launcher` to launch such a URL and the issues you encountered.

> upi links are deeplinks which trigger upi appication

Launching other applications is the primary use case for `url_launcher`.
