### ISSUE TITLE
Missing access token uploading metrics

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#96317]
This is currently breaking the build.

Looks like there's an [infra problem uploading metrics](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8825658930672107153/+/u/Upload_metrics/upload_results/stdout)

```
AuthenticatedClientError:
  URI: https://flutter-dashboard.appspot.com/api/update-task-status
  HTTP Status: 401
  Response body:
Invalid access token
```

**Comment by keyonghan** [comment]
This is a transient issue, and the bot (win2) is passing ongoing tests well:
<img width="1251" alt="Screen Shot 2022-01-07 at 3 19 45 PM" src="https://user-images.githubusercontent.com/54558023/148619469-718b2f04-293c-4d1b-8073-622607a8b13b.png">

Now the tree is back to tree.

**Comment by godofredoc** [comment]
Haven't seen this in a few months
