### ISSUE TITLE
Investigate raster cache usage when partial repaint is enabled

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#96310]
On initial investigation per: https://github.com/flutter/engine/pull/29591#issuecomment-1007725505. It looks like there is significant change when we enable partial repaint on Android.

**Comment by zanderso** [comment]
I suspect the root cause of this will be pretty interesting to learn. Whatever the cause, I'm also interested to learn what effect the smarter RC admission policy that @gw280 is working on will have on it.

**Comment by GaryQian** [comment]
Following up on this, without @gw280, do we still have someone looking at this? This regression should still be live and is non-insignificant. @zanderso @iskakaushik

**Comment by zanderso** [comment]
There are a couple of refactors in-flight and in the planning stages that will likely affect this. First, raster cache decisions are getting moved around in https://github.com/flutter/engine/pull/31892. Second, @iskakaushik has some ideas about moving some/all of this work off of the raster thread that are in the early investigation stage.

Orthogonally, I'm not finding any SkiaPerf links that show the regression in CI. I think Kaushik might have only seen this regression locally. Do I remember that right @iskakaushik?

**Comment by zanderso** [comment]
Closing as stale. Partial repaint is disabled on Android altogether.
