### ISSUE TITLE
no such file or directory: /User/xx/development

### ISSUE THREAD

**Issue by oneluxyou** [flutter/flutter#96329]
## Steps to Reproduce
while I run
cd ~/development  in my Mac
it shows that
<img width="434" alt="image" src="https://user-images.githubusercontent.com/77523920/148635332-bc3f98eb-7735-4b36-adcb-0e0830e1ecd6.png">

1. ...
2. ...
3. ...

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by bernaferrari** [comment]
That's your filesystem, not flutter related
