### ISSUE TITLE
Google Sign In Web plugin to support Signing in without a pop up window.

### ISSUE THREAD

**Issue by ted-marozzi** [flutter/flutter#96327]
## Use case

The use case is when creating a web app the authenticates with Google Sign In, one may wish to have the page navigate to the google OAuth consent screen, instead of a pop up occurring. A big reason for this is many browser block pop up, in I believe iOS now ships with pop ups block by default (without any indication that a pop up was attempted). I can however sign into non flutter web apps on the same browser as they navigate to a different page instead of trying to spawn a pop up.

## Proposal
Something like this...

```dart
/// How do you want GoogleSignInOAuth screen to be shown to your user.
///
/// [popUp] is the default and [navigate] is only supported/relevant on the web as you can't navigate in place
/// in a mobile/desktop app.

enum LaunchType {
    popUp,
    navigate
}

// Client code
GoogleSignIn(launchType: LaunchType.navigate);
```
Let me know if something is unclear, this is essentially a blocker for my app.

**Comment by ted-marozzi** [comment]
Someone else having a problem that this would fix here: https://stackoverflow.com/questions/63801769/flutter-web-google-sign-in-not-working-on-mobile-browsers

**Comment by darshankawar** [comment]
@ted-marozzi 
Can you check if your case is similar to the one proposed here ? https://github.com/flutter/flutter/issues/64457

**Comment by ted-marozzi** [comment]
Yes it is, i'll leave a comment on that one. Thanks.
