### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by bubnenkoff** [flutter/flutter#9632]
Last release was more than 2 years ago. Maybe it's time to do new one?
I very hope to get at last basic Windows support in it.

**Comment by abarth** [comment]
We don't really use the release feature on GitHub.  The current advice is to just pull from the master branch.  We're experimenting with keeping an alpha branch updated on a weekly cadence as well.

**Comment by sethladd** [comment]
Also, you can developer Flutter apps on Windows now :)

https://flutter.io/setup-windows/

**Comment by bubnenkoff** [comment]
But there is instructions only for android. Is it's possible to develop for
iOS?

чт, 27 апр. 2017 г. в 18:54, Seth Ladd <notifications@github.com>:

**Comment by abarth** [comment]
I don't know of any way to create iOS binaries from Windows.  You can develop the UI using Windows and Android by setting the app's platform theme to iOS, but I don't know of any way of creating a releasable iOS binary on Windows.
