### ISSUE TITLE
Windows - Caps lock key is broken on windows

### ISSUE THREAD

**Issue by dannyvalentesonos** [flutter/flutter#96326]
## Steps to Reproduce

* Launch the app with caps lock key off
* type in the text field
* Notice that it will always type small letters, unless pressing the Shift key. Even with caps lock on, it will always type small letters

* Now, launch the app, but this time, with the caps lock key already on before launching
* This time, typing letters might come out in upper case, even if you turn the caps lock key off.

Sometimes, the repro above doesn't always happen. Instead, the caps lock might just never work, other times it might work randomly. The caps lock can work one time, and then turning it off won't work, and then hitting a few more times still does nothing.

Coming out of the flutter app, depending on the state of the caps lock that the app showed at the end, the caps lock key's state can actually be reversed for the rest of the operating system. The only way to correct it is to launch the flutter app again and try and get the caps lock state to toggle again until it actually matches the state of the physical key.

This happens with flutter version 2.5.3 (stable) and still happens with 2.8.1 (stable).

I'm running on a Windows Server 2019 VM inside of Virtual Box. The caps lock key otherwise works perfectly outside of the flutter app.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
            TextField(),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

```

</details>

I tried running with --verbose, but no logs came out.

```
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.17763.379], locale en-US)
    • Flutter version 2.8.1 at c:\flutter\2.8.1-stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.11.6)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
    • Visual Studio Enterprise 2019 version 16.11.31829.152
    • Windows 10 SDK version 10.0.18362.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.17763.379]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 97.0.4692.71

! Doctor found issues in 2 categories.

```

</details>

**Comment by dannyvalentesonos** [comment]
@maheshmnj Thank you for the response. I was able to verify on a real computer, running Windows 10 as you suggested, and the issue is not present. I wonder if the issue is with a VM, or Windows Server 2019? I assume flutter is using some OS hook for this, seeing how the caps lock was behaving badly for the rest of the OS after closing the flutter app in this state, so I wonder if it might be more of an issue with Windows Server doing things a little differently, as opposed to the fact I was running it in a VM. I unfortunately don't have a real machine to test this on with Windows Server.

**Comment by maheshmnj** [comment]
> I assume flutter is using some OS hook for this, seeing how the caps lock was behaving badly for the rest of the OS after closing the flutter app in this state,

Thanks for the info, This seems an issue with your VM or the Windows server in that case and not with Flutter.

> I unfortunately don't have a real machine to test this on with Windows Server.

I am going to close this issue for now, since this doesn't seem like an issue with flutter If you have any further info for us which concretely points that this issue is due to flutter feel free to file a new issue or write back with more details on this issue and I will reopen it.

Thank you.
