### ISSUE TITLE
fatal: unterminated line in .git/packed-refs: (flutter)

### ISSUE THREAD

**Issue by Shashwat2708** [flutter/flutter#96328]
I am facing the problem in the code below whenever I try to run anything. 
I also tried locating .git/packed-refs: file but I am not able to find it. Can someone please help me with this error.

``fatal: unterminated line in .git/packed-refs: ...  
Building flutter tool... 
Running pub upgrade... 
Running "flutter pub get" in [project_name]...                          
The current Flutter SDK version is 0.0.0-unknown.``

**Comment by darshankawar** [comment]
@Shashwat2708 
`"flutter pub get" in [project_name]... The current Flutter SDK version is 0.0.0-unknown.`, looks like the flutter version you installed may have been corrupted or your if you are using git, then it could be on older version, so just try to re-install the sdk and see if you still get the same error or not.

**Comment by Shashwat2708** [comment]
Yes..... In the .git folder flutter, there was a file "packed-refs" That i had to delete.

Everything worked fine after that

**Comment by darshankawar** [comment]
Closing as resolved.
