### ISSUE TITLE
Constructors should have the same dartdoc as their classes

### ISSUE THREAD

**Issue by werainkhatri** [flutter/flutter#96332]
Developers deal with constructors way more often than classes. The constructors should also have the same API doc along with their classes.

**Comment by dnfield** [comment]
Classes can have multiple consturctors, sometimes with different parameters/behaviors. Class level documentation also sometimes details more than just why you would construct an object but also its lifecycle or various methods on it in more detail.

What's the problem you're trying to solve? Is it that the IDE is showing you ctor docs when you'd rather see class docs, or are you seeing bad docs on ctors?

**Comment by werainkhatri** [comment]
Yeah, it's the IDE showing ctor docs when I would like to see a more detailed (class) doc. I have to resort to either converting the ctor to class or typing down the class name again just to view the doc, or go to the API website.

This may not be a common problem and maybe I'm doing something wrong.

**Comment by dnfield** [comment]
@DanTup or @jacob314 might have some good ideas there. Seems like it should be possible to have the IDE pull up class docs on ctors - though I'm not sure if that's actually controlled by the analyzer or not.

**Comment by DanTup** [comment]
Yep, this comes from the server. There's an existing issue at https://github.com/dart-lang/sdk/issues/28537 which I raised about supplying class constructors when constructor docs didn't exist, although a commenter suggested providing them all the time (which I think is the same as the request here).

**Comment by dnfield** [comment]
FWIW, in my own workflow, I tend to just `Cmd + Click` the constructor and then scroll up to see the class doc if I care enough. I find it difficult to read docs in IDE popups anyway, and Flutter style says to sort constructors at the top which makes this pretty easy.

**Comment by goderbauer** [comment]
Looks like this is tracked by https://github.com/dart-lang/sdk/issues/28537. Since this isn't really a flutter-specific issue, I am going to close this one here.
