### ISSUE TITLE
[web]: <platform and version for pwa installation to homescreen>

### ISSUE THREAD

**Issue by KwakMinSeok** [flutter/flutter#96335]
installing web app to homescreen is not available in ios 15.2 (version of my phone) example: https://github.com/flutter/gallery/. I've already googled whether it is the problem of version or I got it wrong how to install it. There could be some vague exprssions that I have used, so don't mind to ask me again :)

**Comment by danagbemava-nc** [comment]
This is a limitation of `iOS` in that it does not show the "Add <insert app name here> to home screen". 
If you want to install a PWA on `iOS`, tap on the `share` button and scroll to `Add to Home Screen` and add it there. 

Closing as this is not an issue with flutter, if you disagree, leave a comment below and I will reopen. 

Thank you

**Comment by KwakMinSeok** [comment]
thank you so much. this really help me a lot.

**Comment by KwakMinSeok** [comment]
thank you
