### ISSUE TITLE
Listening for key presses globally in flutter app (Web / Windows / Linux / MacOS)

### ISSUE THREAD

**Issue by Pr47h4m** [flutter/flutter#96333]
## Use case
When we need to add shortcuts for desktop users for example pressing ```ctrl+tab``` to switch tab of inside app or pressing ```/``` to focus the search field or pressing ```[ or ]``` to switch pages in our paginated content so we need global key listener (which don't need focus on specific element)

## Current scenario
We have ```KeyboardListener``` widget but it need focus on specific widget to perform properly

## Proposal
If their could be solution like ```Theme``` or ```MediaQuery``` which provides information anywhere in the app that will solve the problem

**Comment by jayjah** [comment]
@Pr47h4m Are you aware of the [shortcuts](https://api.flutter.dev/flutter/material/MaterialApp/shortcuts.html) property in the MaterialApp widget? May this be an option for your intention behaviour?

**Comment by maheshmnj** [comment]
Hi @Pr47h4m, Thanks for filing the issue. Adding [Shortcuts](https://api.flutter.dev/flutter/widgets/Shortcuts-class.html) to the root of your widget tree will allow you to trigger keypress events anywhere in your app.

**Comment by Pr47h4m** [comment]
Hello @jayjah @maheshmnj 
Thank you for your response 
I will try this.

**Comment by maheshmnj** [comment]
Closing this issue since this is possible using Shortcuts as mentioned above.
