### ISSUE TITLE
[Proposal] Allow disabling the display of leading for searchDelegate subclasses

### ISSUE THREAD

**Issue by Nass779** [flutter/flutter#96337]
## Use case

I want to use `searchDelegate` without automatically having a leading. I want to be able to use this space for the `TextField` for more flexibility in the design.

I couldn't find a way to do this without changing the `_SearchPage` code.

Expected design : 

![expected_design](https://user-images.githubusercontent.com/26410842/148644731-cc5faaf6-a1d1-4502-a600-bb988b96599e.png)

Current  design  with `buildLeading()`  returning `null` : 

![current](https://user-images.githubusercontent.com/26410842/148644737-6d304995-20fa-46ef-b7ac-f0263049f352.png)

## Proposal

Add one more property to `searchDelegate`:

- for example a boolean `"automaticallyImplyLeading"` which would be passed to the `_SearchPage` appBar.

**Comment by marcellocamara** [comment]
@Nass779 Did you find any approach to remove this spacement?

**Comment by Nass779** [comment]
Fixed with: https://github.com/flutter/flutter/pull/136165
