### ISSUE TITLE
[TextField] Focus is lost on TextField when executing setState(), when parent is changed between states

### ISSUE THREAD

**Issue by mzkai** [flutter/flutter#96345]
There seems be an issue with TextField, as it will loose focus if a Column parent to TextField is removed or added on setState(). I would expect that focus should be kept, whether or not I choose between the first or the second of the two code examples below. It should be noted that I have **only tried the example below on iOS simulator iPhone 13 iOS 15.2**.

The following code **will loose focus** on setState():
```
Widget build(BuildContext context) {
    return error ? Column(
            children: [
              createTextField(),
              showError(),
            ],
          )
        : createTextField();
  }
```

However, the following code **will keep focus** on setState():
```
Widget build(BuildContext context) {
    return Column(
      children: [
        createTextField(),
        if (error) showError(),
      ],
    );
  }
```

Flutter doctor output:
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.63.2)

**Comment by danagbemava-nc** [comment]
Hi @mzkai, thanks for filing this issue. 

Please provide a complete minimal reproducible code sample. 

Thank you
