### ISSUE TITLE
Publishing flutter plugin account verification failed

### ISSUE THREAD

**Issue by PostLiu** [flutter/flutter#96354]
`Waiting for your authorization...
Authorization received, processing...
It looks like accounts.google.com is having some trouble.
Pub will wait for a while before trying to connect again.
OS Error: 信号灯超时时间已到
, errno = 121, address = accounts.google.com, port = 54201
pub finished with exit code 69
`
then run flutter doctor -v
`[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.22000.376], locale zh-CN)
    • Flutter version 2.8.1 at D:\App\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at D:\App\StudioConfig\sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: D:\App\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Android Studio (version 2021.1)
    • Android Studio at D:\App\android-studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[☠] IntelliJ IDEA Ultimate Edition (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    X FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:318:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1428:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1863:10)
      #15     runZonedGuarded (dart:async/zone.dart:1851:12)
      #16     runZoned (dart:async/zone.dart:1782:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:197:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:301:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:53:47)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1290:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>

[√] Connected device (1 available)
    • Edge (web) • edge • web-javascript • Microsoft Edge 97.0.1072.55

! Doctor found issues in 2 categories.`

```
use curl google.com or curl accounts.google.com  can pass
`PS D:\aliface> curl accounts.google.com


StatusCode        : 200
StatusDescription : OK
Content           :
                    <!DOCTYPE html>
                    <html lang="zh">
                      <head>
                      <meta charset="utf-8">
                      <meta content="width=300, initial-scale=1" name="viewport">
                      <meta name="google-site-verification" content="LrdTUW9psUAMbh4Ia074-...
RawContent        : HTTP/1.1 200 OK
                    X-Frame-Options: DENY
                    x-auto-login: realm=com.google&args=continue%3Dhttps%253A%252F%252Faccounts.google.com%252F
                    Pragma: no-cache
                    Transfer-Encoding: chunked
                    Strict-Transport-Secu...
Forms             : {gaia_loginform}
Headers           : {[X-Frame-Options, DENY], [x-auto-login, realm=com.google&args=continue%3Dhttps%253A%252F%252Faccounts.google.com%252F], [Pragma, no-cache], [Transfer-Encod 
                    ing, chunked]...}
Images            : {@{innerHTML=; innerText=; outerHTML=<IMG class=circle-mask src="https://ssl.gstatic.com/accounts/ui/avatar_2x.png">; outerText=; tagName=IMG; class=circle- 
                    mask; src=https://ssl.gstatic.com/accounts/ui/avatar_2x.png}, @{innerHTML=; innerText=; outerHTML=<IMG alt=變更語言 src="//ssl.gstatic.com/images/icons/ui/c 
                    ommon/universal_language_settings-21.png">; outerText=; tagName=IMG; alt=變更語言; src=//ssl.gstatic.com/images/icons/ui/common/universal_language_settings- 
                    21.png}}
InputFields       : {@{innerHTML=; innerText=; outerHTML=<INPUT type=hidden value=PasswordSeparationSignIn name=Page>; outerText=; tagName=INPUT; type=hidden; value=PasswordSep
                    arationSignIn; name=Page}, @{innerHTML=; innerText=; outerHTML=<INPUT type=hidden>; outerText=; tagName=INPUT; type=hidden}, @{innerHTML=; innerText=; outer 
                    HTML=<INPUT type=hidden value=AFoagUWgG8MhBf_F99vE8rzoQU-QRScvEw:1641695968480 name=gxf>; outerText=; tagName=INPUT; type=hidden; value=AFoagUWgG8MhBf_F99vE 
                    8rzoQU-QRScvEw:1641695968480; name=gxf}, @{innerHTML=; innerText=; outerHTML=<INPUT type=hidden value=AU9NCcxPobHuhdUj5UY2-3hTBW8VDPhQPt8hVIezO2xJUEumqZtag6 
                    DIrRog40U-1fH9s6Ua7VOq4g name=ifkv>; outerText=; tagName=INPUT; type=hidden; value=AU9NCcxPobHuhdUj5UY2-3hTBW8VDPhQPt8hVIezO2xJUEumqZtag6DIrRog40U-1fH9s6Ua7 
                    VOq4g; name=ifkv}...}
Links             : {@{innerHTML=尋找我的帳戶 ; innerText=尋找我的帳戶 ; outerHTML=<A class=need-help href="https://accounts.google.com/signin/usernamerecovery?continue=https%3
                    A%2F%2Faccounts.google.com%2F&amp;hl=zh-HK">尋找我的帳戶 </A>; outerText=尋找我的帳戶 ; tagName=A; class=need-help; href=https://accounts.google.com/signin/ 
                    usernamerecovery?continue=https%3A%2F%2Faccounts.google.com%2F&amp;hl=zh-HK}, @{innerHTML=使用其他帳戶登入 ; innerText=使用其他帳戶登入 ; outerHTML=<A href= 
                    "https://accounts.google.com/AccountChooser?continue=https%3A%2F%2Faccounts.google.com%2F&amp;followup=https%3A%2F%2Faccounts.google.com%2F">使用其他帳戶登  
                    入 </A>; outerText=使用其他帳戶登入 ; tagName=A; href=https://accounts.google.com/AccountChooser?continue=https%3A%2F%2Faccounts.google.com%2F&amp;followup= 
                    https%3A%2F%2Faccounts.google.com%2F}, @{innerHTML=建立帳戶 ; innerText=建立帳戶 ; outerHTML=<A href="https://accounts.google.com/SignUp?continue=https%3A%2 
                    F%2Faccounts.google.com%2F">建立帳戶 </A>; outerText=建立帳戶 ; tagName=A; href=https://accounts.google.com/SignUp?continue=https%3A%2F%2Faccounts.google.co 
                    m%2F}, @{innerHTML=關於 Google ; innerText=關於 Google ; outerHTML=<A href="https://www.google.com/intl/zh-HK/about" target=_blank>關於 Google </A>; outerTe 
                    xt=關於 Google ; tagName=A; href=https://www.google.com/intl/zh-HK/about; target=_blank}...}
ParsedHtml        : mshtml.HTMLDocumentClass
RawContentLength  : 97679
`
```

**Comment by darshankawar** [comment]
@PostLiu 
Check below issue comments regarding same problem and see if they help:

https://github.com/flutter/flutter/issues/22481#issuecomment-510300559

https://github.com/flutter/flutter/issues/17070#issuecomment-524547940

Also, it could be a network issue at your end, so try to use another network provider and see if it helps.
Closing this from here. If you disagree, or still getting same error, write in comments and I'll reopen.
