### ISSUE TITLE
[google_maps_flutter_web] Info boxes when clicking on famous places

### ISSUE THREAD

**Issue by joshipucher** [flutter/flutter#96359]
How can I remove the information boxes that pops up when clicking on famous places on the map. I mean the info boxes that show the "View in Google Maps" links

**Comment by darshankawar** [comment]
@joshipucher 
Your question is better suited for support channels like StackOverflow, so please ask the same there.
Closing from here as this is more of a `how to` question instead of a bug report or feature request.
