### ISSUE TITLE
Broken link for the desktop support page

### ISSUE THREAD

**Issue by justinmc** [flutter/flutter#96379]
### Describe the problem

A URL given by the `flutter` command line tool leads to the wrong place: https://flutter.dev/multi-platform/desktop#add-desktop-support-to-an-existing-flutter-app

That should lead to a technical page about how to add desktop support for your app, but instead it leads to the main desktop page.  This used to work before flutter.dev was relaunched.

If you try to `flutter run` an app that hasn't been setup for desktop, you will get an error message directing you to that non-existent page, with the given URL:

```
Exception: No Linux desktop project configured. See https://flutter.dev/desktop#add-desktop-support-to-an-existing-flutter-app to learn about adding Linux support to a project.
```

### Expected fix

Add back the original content, and make sure the link from the flutter CLI tool points to it.

**Comment by darshankawar** [comment]
@justinmc 
There's an already similar open issue for this: https://github.com/flutter/flutter/issues/94398
Closing this as a duplicate.
