### ISSUE TITLE
[local_auth] IOS FaceID should fallback to Passcode but does not

### ISSUE THREAD

**Issue by yauheni-s-nyble** [flutter/flutter#96390]
On iOS the passcode as fallback is not shown for FaceID users, FaceID should fallback to Passcode but does not. The expected behaviour is that on FaceID not success, it's able to enter device pass.

**Expected results:** https://drive.google.com/file/d/1mJKBSuqRrje_iTOr3OBHd-TeCjodHmmL/view?usp=sharing

**Actual results:** https://drive.google.com/file/d/1mHB_aDOjAE4deiXVjwuWw97HKxSE84Vf/view?usp=sharing

<details>
  <summary>Logs</summary>

[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale
    ru-BY)
    • Flutter version 2.8.1 at /usr/local/Caskroom/flutter/2.2.3/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (4 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/jenik/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554
      • android-x86    • Android 11 (API 30) (emulator)
    • iPhone 13 Pro Max (mobile)         • 57F9FDFD-3FC2-43A8-8A4F-399FA2946EFD
      • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)                       • chrome
      • web-javascript • Google Chrome 96.0.4664.110

</details>

**Comment by darshankawar** [comment]
@yauheni-s-nyble 
Can you provide us a minimal code sample or try the official plugin [example](https://pub.dev/packages/local_auth/example) and see if you get same behavior or not.

**Comment by yauheni-s-nyble** [comment]
@darshankawar 
video above (links to google drive) from the official plugin example

**Comment by darshankawar** [comment]
Thanks. I think you mixed up actual vs expected results links in your original description.
Although I don't have FaceID enabled phone, I tried it with TouchID with which it fallsback on passcode, as expected.
But regarding FaceID, check this similar issue and see if it's same as your case: https://github.com/flutter/flutter/issues/22378

**Comment by yauheni-s-nyble** [comment]
I tried it and the problem is very similar to the one described here
https://github.com/flutter/flutter/issues/49703#issuecomment-761547943

**Comment by darshankawar** [comment]
Thanks for the link. I am labeling it as I am unable to replicate it (due to lack of FaceID enabled device).

**Comment by harsuu942** [comment]
I got the solutions

you have to add this line : context.localizedFallbackTitle = @"Enter password"; in authenticate function

will raise PR as well

**Comment by bhumesh** [comment]
@harsuu942 better to pass as argument, so that it will easy to customize the title for fallback option.

**Comment by bhumesh** [comment]
@darshankawar for Android it won't shows Use Pattern alongwith Touch ID pop up. However same code work in emulator prop
<img width="403" alt="android_device" src="https://user-images.githubusercontent.com/771585/151945705-f94453c1-6d66-454e-9bdf-5e1aae94c2b7.png">
![android_emulator](https://user-images.githubusercontent.com/771585/151945737-58099bb5-3e50-4f1e-bac6-b4334810198f.png)
erly.

**Comment by furaiev** [comment]
it was fixed via https://github.com/flutter/plugins/pull/3806 in version `1.1.11`, but was broken after the `2.0.0` release
