### ISSUE TITLE
[google_sign_in] Allow initialization from Dart without adding native config files

### ISSUE THREAD

**Issue by pr-Mais** [flutter/flutter#96391]
## Description

In the latest release of FlutterFire plugins, initialization of the `DEFAULT` Firebase App through Dart has been added, omitting the manual installation step, and enabling `flutterfire_cli` tool to make this step completely automatic.

Unfortunately, if the app is using `google_sign_in`, it requires developers to add back the manual installation step even though `firebase_auth` does support Dart-only initialization, as [mentioned here](https://firebase.flutter.dev/docs/auth/social#google).

## Proposal

Allowing `google_sign_in` to initialize from Dart will make it possible for `firebase_auth` users to completely migrate to use Dart initialization through [`flutterfire_cli`](https://firebase.flutter.dev/docs/cli).

**Comment by loolooii** [comment]
Any update on this?

**Comment by marcusrohden** [comment]
Hey guys any updates? thanks again.

**Comment by crisboarna** [comment]
Would be amazing to have this complete !

**Comment by tudor07** [comment]
Any updates? It's been 3 months already....

**Comment by ShahrearBinAmin** [comment]
Would love to get this fix!

**Comment by cyphl** [comment]
Finished migrating to dart-only initialization just to find out I'll have to rollback :(

**Comment by mono0926** [comment]
I've forked it and fixed: https://github.com/mono0926/plugins/tree/fix-flutterfire/packages/google_sign_in

Example:

- https://github.com/mono0926/flutter_playground/blob/ab5df00fff3da1d223f33f849de04c2d2c0b8f11/pubspec.yaml#L47-L54
- https://github.com/mono0926/flutter_playground/blob/main/lib/main_google_sign_in.dart

**Comment by loolooii** [comment]
Can I ask what's keeping this from being reviewed/merged?

**Comment by blaugold** [comment]
https://github.com/flutter/plugins/pull/5250 has been merged, so `GoogleService-Info.plist` is no longer required on iOS. 

It is still necessary to register `CFBundleURLTypes` in `Info.plist`, but that cannot be done at runtime, so `google_sign_in` cannot help with that.

**Comment by blaugold** [comment]
> Can CFBundleURLTypes list all the urls types of different firebase projects?

I don't see why not. `CFBundleURLSchemes` is an array which can contain more than one scheme that the app can handle. With a Xcode build script, you could remove all but one scheme in release builds to be safe.
