### ISSUE TITLE
what is scroll keep index by listview reverse insert at zero item best practice ?

### ISSUE THREAD

**Issue by rizzi37** [flutter/flutter#96398]
hello, 

when i use in `reverse list`, add a item like chat `message list`.

when `insert at zero index` , the old index will `offset by N`. so i must use `scrollpostion lib initindex keep offset index.` fix my old item.

i want to known it there a best practice ?

thanks.

**Comment by danagbemava-nc** [comment]
Hi, this issue tracker is for reporting issues or feature requests for the flutter. 

For recommendations on what to do with your personal code kindly see any of the communities in https://flutter.dev/community#community-grid. 

Closing as this is neither a bug report nor a feature request.

Thank you
