### ISSUE TITLE
[integration_test] Allow support for automating native OS windows in flutter-web. 

### ISSUE THREAD

**Issue by rajeshpatil95** [flutter/flutter#96407]
I am use integration_test package to write integration tests on Dart for flutter-web application. I have a feature to upload a document file picking from OS through browser. After much googling i didn't find any official support or workaround for automating this below native OS windows attached below.

<img width="745" alt="window" src="https://user-images.githubusercontent.com/41562370/148807236-98cb81ad-1f27-40db-81fa-224d10f23290.PNG">
These two GitHub issues are pretty much related to it:

- https://github.com/flutter/flutter/issues/86295

- https://github.com/flutter/flutter/issues/87440

**Comment by stuartmorgan** [comment]
This is exactly https://github.com/flutter/flutter/issues/86295; closing as a duplicate.

It's unlikely that it can be implemented for web though, due to the restrictions of the browser environment.
