### ISSUE TITLE
Do not re-run framework tests when draft PR is marked "Ready for Review"

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#96408]
For example, https://github.com/flutter/flutter/pull/96325 was created as a draft, and all tests passed on it.  When I marked the PR as ready, all the tests re-ran a second time.

**Comment by godofredoc** [comment]
@christopherfujino did your last pr in cocoon fixed this issue?

**Comment by christopherfujino** [comment]
Yup, good catch!
