### ISSUE TITLE
Polygon onTap doesn't work

### ISSUE THREAD

**Issue by tigermobiledev** [flutter/flutter#96410]
Hi, onTap Callback of Polygon doesn't work in my side.
version: google_maps_flutter: 2.1.1
My code is below.
What's wrong?
```
    Polygon(
          polygonId: PolygonId('PolygonId'),
          points: points,
          strokeWidth: 2,
          strokeColor: color,
          onTap: () {
             // Nothing happened.
          },
          fillColor: color.withOpacity(0.3),
        ),
```

**Comment by darshankawar** [comment]
@tigermobiledev 
Try adding `consumeTapEvents: true,` inside `Polygon` which hopefully should resolve the issue.
Closing for now. Write in comments if that isn' t the case.

**Comment by tigermobiledev** [comment]
@darshankawar  Thanks!, it works well.
