### ISSUE TITLE
Certain areas of app do not execute when app is backgrounded

### ISSUE THREAD

**Issue by danallen88** [flutter/flutter#96426]
We've observed that our app is running in response to external events when backgrounded (mostly on iOS), such as an update to our app being installed automatically from the App Store, or potentially from push notification delivery.  Is it normal for Flutter apps, with no custom background code or additional isolates, to have code executed in response to these events?  I expected our app code would only ever execute if the app were foregrounded, but we've added logging that shows that if the app gets updated, it will automatically launch the default route ('/') and begin executing our business logic with no intervention from the user.  Additionally, we've observed that sometimes it will perform navigation from the UI layer, and other times it should have executed that logic but did not, seemingly implying that our business logic layer was executing but the UI layer was not.

Thank you for any help you can provide in perhaps pointing to me to documentation that covers how the app can be initiated by the OS and which parts of the engine or framework are active during these states.

**Comment by bernaferrari** [comment]
Yes. It is a mess. 

https://developer.apple.com/documentation/uikit/app_and_environment/responding_to_the_launch_of_your_app/about_the_app_launch_sequence

**Comment by darshankawar** [comment]
Labeling this for further input from the team.

/cc @jmagman @goderbauer

**Comment by jkim259** [comment]
> Labeling this for further input from the team.
> 
> /cc @jmagman @goderbauer

Thank you for reviewing for us!

**Comment by jmagman** [comment]
Is this only happening on iOS 15?  If this has to do with the new pre-warming feature @bernaferrari pointed out then I wouldn't think the main storyboard `FlutterViewController` would be instantiated at all, since that would happen after `UIApplicationMain` where the `UIApplication` is created.

**Comment by danallen88** [comment]
That was our initial suspicion, but the analytics indicate this issue happens on iOS 14 as well.

**Comment by jmagman** [comment]
I suspect all apps would see this behavior then, not just Flutter apps...

**Comment by danallen88** [comment]
Absolutely.  So that goes back to my original question - what parts of the engine or framework are active during these events?  You've mentioned that the FlutterViewController shouldn't be executing at all, and yet it does. 

We've seen situations where logic from the framework's UI widgets is executed, and instances where it should have but didn't.  That's surely too flimsy to act on, but it has obvious implications for anyone writing a Flutter app - some system services - like the Keychain on iOS - are not available in these states, and consequently we have to be even more defensive in attempting access.

In the end I'm more interested in documentation on how Flutter's lifecycle interacts with these native OS events and states.  We unfortunately learned the hard way that you shouldn't rely on keychain access all the time, since our app unexpectedly started running without the user foregrounding it.  Maybe it was an unreasonable assumption that our application code would only execute when the app was foregrounded (absent custom isolates designed for background processes), but without extensive native app development experience I would not have intuited this from the Flutter documentation.

**Comment by jmagman** [comment]
>  You've mentioned that the FlutterViewController shouldn't be executing at all, and yet it does.

No, I meant that if this is related to the iOS 15 pre-warming feature then it shouldn't be executing.  But that feature seems unrelated.

> In the end I'm more interested in documentation on how Flutter's lifecycle interacts with these native OS events and states.

I can't think of anything particularly special Flutter is doing with app lifecycles that would change the OS launch behavior.   @cyanglaz can you think of anything?

> or potentially from push notification delivery

The OS _should_ launch the app on remote notification so the notification can be processed, so the behavior you're describing is expected.  If iOS decides to start apps when they are updated (maybe to allow the app to register for things?), then Flutter apps would also do so.

If you have cases where you only want Flutter code to run when the user explicitly launches your iOS app that's different from the default OS behavior, you could more closely control when `-[FlutterEngine run]` is called in your native Swift/Objective-C code based on the launch options dictionary [`UIApplicationLaunchOptions` values](https://developer.apple.com/documentation/uikit/uiapplicationlaunchoptionskey?language=objc).  See also [additional docs.](https://developer.apple.com/documentation/uikit/app_and_environment/responding_to_the_launch_of_your_app?language=objc#2922740)   

Check out the Flutter add-to-app instructions for an example of how to control when the `FlutterEngine` runs: https://docs.flutter.dev/development/add-to-app/ios/add-flutter-screen?tab=engine-swift-tab#create-a-flutterengine

**Comment by danallen88** [comment]
Thank you @jmagman, this documentation is helpful.  I appreciate your time and attention on this.

**Comment by jmagman** [comment]
If you're able to reproduce this locally, consider logging those `UIApplicationLaunchOptions` values, as well as anywhere you could be responding to notifications for clues as to what's launching the app.
Feel free to file new issues if you find bugs related to Flutter's handling of iOS app lifecycle events.
