### ISSUE TITLE
improve the iOS camera plugin thread model

### ISSUE THREAD

**Issue by hellohuanlin** [flutter/flutter#96429]
## Use case

This issue will be the main issue that tracks various threading problems in iOS camera plugin. 

## Proposal

We wrote up [a formal proposal](https://docs.google.com/document/d/1Znjp-BduXIb1Ix3JOE1YKyJi1Z0d6rB-2q6Lt7j8xSo/edit#heading=h.kv8nn0uaxog6) to improve the thread model, with detailed execution plan in the end. There are also a couple non-threading issues that we'd like to address in the spirit of "yak shaving". 

### We need to fix these threading related issues: 

- [x] Rename "dispatchQueue" to "sessionQueue"
- [x] Dispatch engine API calls on iOS main queue
- [x] Handle all SampleBuffer callbacks on the session queue
- [x] Write photo file in IO queue
- [x] Thread safety for state access
  - [x] Fix _dispatchQueue race condition which is causing a known crash
  - [x] Fix FLTSavePhotoDelegate's reference
  - [x] Fix _camera ivar
  - [x] Fix dispatch orientation change on the session queue (_deviceOrientation, _lockedCaptureOrientation, _isRecording)
- [x] Pixel buffer with queues

### These are optional cleanups not related to threading: 

- [ ] Handle system pressure for video writes 
- [x] Remove selfReference  https://github.com/flutter/plugins/pull/4780
- [x] Break up CameraPlugin.m
- [ ] Clean up properties and ivars

**Comment by jmagman** [comment]
I think this is already what https://github.com/flutter/flutter/issues/52578 is tracking.  Can we close this, and you can just add a comment to that issue with a link to your proposal?

**Comment by hellohuanlin** [comment]
@jmagman Looks like #52578 only tracks the crash with calling engine API on the background thread. Though either way is fine for me.

**Comment by hellohuanlin** [comment]
Re-opened this issue to track various threading related tasks [in the proposal](https://docs.google.com/document/d/1Znjp-BduXIb1Ix3JOE1YKyJi1Z0d6rB-2q6Lt7j8xSo/edit#heading=h.kv8nn0uaxog6)

**Comment by hellohuanlin** [comment]
im closing this issue since all required action items are complete.
