### ISSUE TITLE
 When I rotate the screen on the Ipad, the distortion occurs

### ISSUE THREAD

**Issue by ldhlfzysys** [flutter/flutter#96438]
https://user-images.githubusercontent.com/7666564/148868180-2cd77181-4fc1-4f44-a309-dc0bc5028489.mov

**Comment by darshankawar** [comment]
@ldhlfzysys 
Just providing a video of the current behavior may not be enough, please provide `flutter doctor -v`. From the video, where exactly does the distortion occur ?

**Comment by ldhlfzysys** [comment]
> @ldhlfzysys Just providing a video of the current behavior may not be enough, please provide `flutter doctor -v`. From the video, where exactly does the distortion occur ?

Each version has this problem. @darshankawar

**Comment by darshankawar** [comment]
@ldhlfzysys 
Tried the scenario with a sample app on ipad simulator (4th gen) but didn't observe any distortion while rotating.


https://user-images.githubusercontent.com/67046386/149133958-97f29f57-5faa-4f43-ae2a-c54ada216b72.mov

**Comment by ldhlfzysys** [comment]
thank you for your reply, 

screenshot of the video you sent.
![1642053620417](https://user-images.githubusercontent.com/7666564/149274290-314f62b2-cd5b-4933-b62a-64b733964f03.jpg)
![1642053628828](https://user-images.githubusercontent.com/7666564/149274294-c4ca2885-ff47-47b9-8cd1-4587b54170fd.jpg)

**Comment by darshankawar** [comment]
@ldhlfzysys 
I see there was a  similar issue reporting about same behavior, https://github.com/flutter/flutter/issues/30130, can you confirm if the same occurs on simulator or using device as well or it is specific to ipad ?
