### ISSUE TITLE
Mac14 is failing tests consistently

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#96444]
Manually quarantined the bot.

Consistently failed on dismiss dialog step.
```
Testing failed:
	Provisioning profile "match Development *" doesn't include the currently selected device "Godofredo Contreras’s iPhone" (identifier 039748b19bd44eeb273221ef804893a4f5896798).
	Testing cancelled because the build failed
```

An example build: https://ci.chromium.org/ui/p/flutter/builders/staging/Mac_ios%20new_gallery_ios__transition_perf/48/overview

<img width="1395" alt="Screen Shot 2022-01-10 at 9 20 30 PM" src="https://user-images.githubusercontent.com/54558023/148885790-7579b592-14eb-44ad-a7c4-6c2bca40f7eb.png">

**Comment by godofredoc** [comment]
The device is already in the provisioning profile. This may require to delete certificates and files and allow them to regenerate.

**Comment by godofredoc** [comment]
CL to update mobile provisioning is on review.

**Comment by godofredoc** [comment]
Phone added to provisioning profile.
