### ISSUE TITLE
Rename /layout to /box-constraints

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#9644]
The /layout page is about box constraints. It's a useful doc, but it's narrow in its scope. We might want to use /layouts for a more general overview of layout.

We should rename /layout to /box-constraints and add a redirect. Then, when /layout is needed, we'll link over to /box-constraints

**Comment by Hixie** [comment]
SGTM. Make sure you update the references to that page in the framework asserts when you do this. That page exists so that some of our error messages can point to it.

**Comment by Sfshaza** [comment]
Thank you! I should have done this long ago, but am not sure how to update the asserts.

**Comment by Sfshaza** [comment]
@hixie, I have renamed the file on the dash branch and set up a redirect:

      { "source": "/layout", "destination": "/development/ui/layout/box-constraints", "type": 301 },
