### ISSUE TITLE
crash on windows, when the keyboard case is switched

### ISSUE THREAD

**Issue by baneyue** [flutter/flutter#96446]
`
Should never encounter KeyData when transitMode is rawKeyData.
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 787 pos 16: 'false'#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:47:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      KeyEventManager.handleKeyData (package:flutter/src/services/hardware_keyboard.dart:787:16)
#3      PlatformDispatcher._dispatchKeyData.<anonymous closure> (dart:ui/platform_dispatcher.dart:375:61)
#4      _invoke2.<anonymous closure> (dart:ui/hooks.dart:189:15)
#5      _rootRun (dart:async/zone.dart:1428:13)
#6      _CustomZone.run (dart:async/zone.dart:1328:19)
#7      _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#8      _invoke2 (dart:ui/hooks.dart:188:10)
#9      PlatformDispatcher._dispatchKeyData (dart:ui/platform_dispatcher.dart:373:5)
#10     _dispatchKeyData (dart:ui/hooks.dart:93:31)
`

flutter doctor -v
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.17763.2366], locale zh-CN)
    • Flutter version 2.8.1 at D:\code\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (4 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at D:\androidsdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = D:\androidsdk\
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31729.503
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.17763.2366]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 96.0.4664.110

• No issues found!

**Comment by baneyue** [comment]
This is a necessary problem。

when i revet the #91792 to #88967 ，the problem is fix.

![image](https://user-images.githubusercontent.com/1902581/148896976-614f63f4-bef5-4c43-be0f-68e1343f213c.png)

**Comment by darshankawar** [comment]
@baneyue 
When you say keyboard case is switched, you mean, change it from lowercase to uppercase by pressing Shift key ?
Is it related to physical keyboard or virtual one ? And for English or non-English keyboard ?

**Comment by baneyue** [comment]
physical keyboard 

only press and up case switched

chinese keyboard

**Comment by darshankawar** [comment]
@baneyue 
Tried the scenario on a TextField and used Chinese keyboard and pressed SHIFT and then up or down key but didn't get the mentioned errors. I tried on latest master. If this doesn't represent your case, provide steps to replicate the behavior.

**Comment by mlsnatalie** [comment]
@darshankawar
when you build a windows app in debug model, Tried the scenario on a TextField and used Chinese keyboard and 
pressed CPAS LOCK and then up or down three or five times quickly, the windows app will crash.

**Comment by mlsnatalie** [comment]
@darshankawar

![图片](https://user-images.githubusercontent.com/11189469/149113187-bbae2b74-c02a-47a3-9032-8972c15bffde.png)


when you build a windows app in debug model,used Chinese keyboard,pressed CPAS LOCK and then up or down.

in flutter source code  “hardware_keyboard.dart”

in function "handleKeyEvent"

they code  “event is KeyDownEvent” does work only，
the code “event is KeyUpEvent” does not work.

press other key,  “event is KeyDownEvent” and “event is KeyUpEvent” both can work.

please try it.

Maybe you should try it on different computers.

Thank you!

**Comment by mlsnatalie** [comment]
@darshankawar

user Chinese input method which is from Windows10 system
