### ISSUE TITLE
Xcode 13 can not build IPA

### ISSUE THREAD

**Issue by chaseDeil** [flutter/flutter#96459]
problem:
Generate IPA with Xcode13, not working after installation。

Flutter: 1.9.1+hotfix.6
Xcode 13

Try using the official help documentation:
https://docs.flutter.dev/development/ios-project-migration

The IPA is successfully generated, but after installation it prompts "This APP cannot be installed because its integrity cannot be verified"

**Comment by SuhwanCha** [comment]
It doesn't seem to Flutter issue. And flutter 1.9.1 are no longer maintained

**Comment by darshankawar** [comment]
@chaseDeil 
You are on obsolete version of flutter. Please upgrade to latest stable and try again.
Closing for now, as the version you are on , isn't supported anymore.
