### ISSUE TITLE
[Windows][Desktop]:  `\t` char is rendered as boxes instead of whitespace

### ISSUE THREAD

**Issue by namangor04** [flutter/flutter#96455]
## Steps to Reproduce

1.Build and Run the code sample on Windows

**Expected results:** \t represented by whitespaces and not boxes

This result was achieved by :

``` dart
	str.replaceAll('\t', '  ');
```
![image](https://user-images.githubusercontent.com/64084226/148908712-cc6585bf-5bfc-42b6-b4b5-832d7df285b3.png)

**Actual results:** Seen \t represented by boxes

![image](https://user-images.githubusercontent.com/64084226/148908213-1a4c967c-df49-426b-8aa4-970e73fb5c6d.png)

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Material App Bar'),
        ),
        body: Center(
          child: Container(
            decoration: BoxDecoration(
              border: Border.all(color: Colors.black, width: 2),
            ),
            // ignore: prefer_const_constructors
            child: Text(
              'This is just a\n\tsample\n\t\tcode to show that\n\t\t tabs are represented by boxes\n\t\t and not white-spaces.' /* .replaceAll('\t', '  ') */,
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

**Comment by darshankawar** [comment]
@namangor04 
Can you provide `flutter doctor -v` ?

**Comment by namangor04** [comment]
Sure!

<details>
<summary>flutter doctor -v</summary>

[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.22518.1000], locale en-US)
    • Flutter version 2.8.1 at F:\SDKs\Flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (4 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at F:\SDKs\android_sdk
    • Platform android-32, build-tools 30.0.3
    • Java binary at: F:\IDEs\android_studio_ide\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31025.194
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1)
    • Android Studio at F:\IDEs\android_studio_ide
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.63.2)
    • VS Code at C:\Users\Naman Bharat Gor\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.1

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22518.1000]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 96.0.4664.110
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 97.0.1072.55

• No issues found!
</details>

**Comment by darshankawar** [comment]
Verified this using latest stable and master and seems to be specific to windows, while on macOS, the whitespace is rendered properly, but on windows, they are rendered as boxes:

![spac](https://user-images.githubusercontent.com/67046386/148948676-abcafd0d-db80-4cf2-800e-5c0e3b852214.png)

<details>
<summary> master, stable flutter doctor -v</summary>

```
[√] Flutter (Channel master, 2.9.0-1.0.pre.319, on Microsoft Windows [Version 10.0.19042.1415], locale en-US)
    • Flutter version 2.9.0-1.0.pre.319 at D:\FlutterSDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9c5b390710 (3 hours ago), 2022-01-11 05:10:15 -0500
    • Engine revision 748734adf2
    • Dart version 2.16.0 (build 2.16.0-154.0.dev)
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Win\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31624.102
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.62.3)
    • VS Code at C:\Users\Win\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.28.0

[√] Connected device (5 available)
    • SM A260G (mobile)       • 5200763ebcfa861f • android-arm     • Android 8.1.0 (API 27)
    • Windows (desktop)       • windows          • windows-x64     • Microsoft Windows [Version 10.0.19042.1415]
    • Windows (UWP) (desktop) • winuwp           • windows-uwp-x64 •
    • Chrome (web)            • chrome           • web-javascript  • Google Chrome 96.0.4664.110
    • Edge (web)              • edge             • web-javascript  • Microsoft Edge 97.0.1072.55

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
</details>

**Comment by namangor04** [comment]
Yes sir, i guess that might be something to do with windows 11 ?

**Comment by nt4f04uNd** [comment]
Duplicate of https://github.com/flutter/flutter/issues/79153
