### ISSUE TITLE
ssl handshake without hostname

### ISSUE THREAD

**Issue by rayku-chans** [flutter/flutter#96462]
Flutter Version：Flutter 2.8.1 • channel stable
Dart SDK version: 2.15.1 (stable)

I need to use the SNI method to make SNI requests, but I get an error when I use Flutter's httpClient/dio and other libraries for SNI requests: HandshakeException: Connection terminated during handshake
I am very sure that my server is normal, because I can access it using the URLConnection provided by Android or the third-party library Okhttp.
It is currently suspected that this error is caused by not carrying the hostname during the SSL handshake process, I hope it can be fixed

**Comment by darshankawar** [comment]
@rayku-chans 
Can you provide a minimal reproducible code sample using `http` package along with entire error log ? `dio` is a third party.
