### ISSUE TITLE
Unverified breakpoints in specific file using VSCode WEB

### ISSUE THREAD

**Issue by Dalimar95** [flutter/flutter#96473]
Hello i've got issue when trying to debug my app on chrome using vscode some files instantly have an unverified breakpoint.

Currently don't have time to create a simple example to reproduce the issue. But maybe anyone faced the issue and there is a known fix?

`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6 20G165 darwin-x64, locale en-GB)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc2)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.63.2)
[✓] Connected device (3 available)

! Doctor found issues in 1 category.`

**Comment by darshankawar** [comment]
@Dalimar95 
Without a reproducible code sample and an error log, we won't be able to verify or tell what exactly is causing the issue, so please provide the above details so that we can properly address the issue.
