### ISSUE TITLE
[in_app_purchase] isAvailable always returns false on emulator in debug mode

### ISSUE THREAD

**Issue by MilesAdamson** [flutter/flutter#96476]
App is approved and on the alpha channel on the google play store. The email I have logged in with on the device is on the list of approved testers. On Alpha builds, the in app purchases appear to be working just fine. On my emulator though, I cannot get `isAvailable` to return true. This is making development harder as I must test out the IAP process and UI on a release build without the debugger.

```
    final isAvailable = await _inAppPurchase.isAvailable();
    if (isAvailable) {
      // This is hit on release build from alpha channel, and the test card shows up
      await setRemoveAdsParam();
    } else {
      // My emulator ALWAYS hits this line, I cannot get isAvailable to return true for development
      debugPrint("In app purchases are not available");
    }
```

**Comment by stuartmorgan** [comment]
What image are you using for your emulator? Does it have Google Play Services?

**Comment by MilesAdamson** [comment]
Ah that was silly, it did not have Google Play Services. I made a new emulator and it works perfectly now
