### ISSUE TITLE
false positive for unused files when using barrels

### ISSUE THREAD

**Issue by cedvdb** [flutter/flutter#96488]
I'm having the message `LibraryHelper: Library package:some/path/file.dart is not loaded. This can happen for unreferenced libraries.` for a bunch of files when running my app, which I assume is to help the user to find unused files.

However the files are used, but the folder structure uses barrels to export subfolders which I guess is the reason why the library helper gives false positive for unused files.

IE:

```
  - lib
     - data_sources
        - subfolder_one
           ...
           subfolder_one.dart
        - subfolder_two
        data_sources.dart // exports subfolders
```

Maybe there is a contraindication in doing such thing ? In any case, the message is still wrong.

Flutter version:

Flutter (Channel master, 2.9.0-1.0.pre.299, on Ubuntu 20.04.3 LTS 5.10.16.3-microsoft-standard-WSL2, locale C.UTF-8)

**Comment by maheshmnj** [comment]
Hi @cedvdb, Thanks for filing the issue. Could you please help us with reproducible steps to investigate this issue further? 

Thanks

**Comment by PRID021** [comment]
I have the same problem. 
![image](https://user-images.githubusercontent.com/70733521/150461688-751bb53d-adda-418d-ba91-fba34b88c538.png)
This is my structure project

**Comment by frostsmaker** [comment]
LibraryHelper: Library package:some/path/file.dart is not loaded. This can happen for unreferenced libraries.

This is not an error because it didn't disturb your app. 
Even with this "notification", your app still running just fine.

I also wonder why it is showing up.

**Comment by cedvdb** [comment]
I believe it is because of barrels (ence the title), but I do not care enough to make a repro. Go ahead if you want.
