### ISSUE TITLE
Widgets inconsistently respect the parameters of most immediate MediaQuery above in the tree.

### ISSUE THREAD

**Issue by Scott-Tenera** [flutter/flutter#96493]
- I am constructing and adding my own MediaQuery into the widget tree.
- I am changing parameters on my new MediaQuery in relation to the MediaQuery above me in the widget tree.
- The values I am changing are _textScaleFactor_ along with _size_ in conjunction with _devicePixelRatio_.

- When I change the textScaleFactor, text widgets below the new MediaQuery change their text size accordingly.
- When I change size + devicePixelRatio, the scaffold and elevated button do not respect this change, and do not draw scaled.

The expected behaviour is the Widgets would consistently respect the parameters of the nearest MediaQuery. If I can modify textScaleFactor why can I not modify display size via size+devicePixelRatio, or vice versa? 

Observe the following minimal example and specifically refer to the commented variables....

```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      builder: (context, child) {
        var mediaQuery = MediaQuery.of(context);

        var newTextScaleFactor = 1.0; // varying this has effect
        var newDevicePixelRatio = 4.0; // varying this has no effect

        var physicalPixelWidth = mediaQuery.size.width * mediaQuery.devicePixelRatio;
        var physicalPixelHeight = mediaQuery.size.height * mediaQuery.devicePixelRatio;
        var newSize = Size(physicalPixelWidth / newDevicePixelRatio, physicalPixelHeight / newDevicePixelRatio);
        return MediaQuery(
          data: MediaQuery.of(context).copyWith(textScaleFactor: newTextScaleFactor, devicePixelRatio: newDevicePixelRatio, size: newSize),
          child: Navigator(
            onGenerateInitialRoutes: (state, routeName) => [
              MaterialPageRoute(
                builder: (_) {
                  return Overlay(initialEntries: [OverlayEntry(builder: (context) => const MyHomePage())]);
                },
              )
            ],
          ),
        );
      },
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Test App"),
      ),
      body: Center(
        child: ElevatedButton(
          onPressed: () {},
          child:  const Text("Test Text"),
        ),
      ),
    );
  }
}
```

**Comment by darshankawar** [comment]
@Scott-Tenera 
Upon running your code sample on latest stable (2.8.1), varying `newTextScaleFactor` and `newDevicePixelRatio` (e.g 0.5 and 2.0), the mediaQuery does make the effect and changes on screen are reflected:

<img width="331" alt="Screenshot 2022-01-12 at 1 30 04 PM" src="https://user-images.githubusercontent.com/67046386/149087104-afa61ffe-59fd-4d0b-9d1b-9bc70bcc001b.png">

If this isn't the expected behavior, then can you elaborate on expected vs actual result ?
Also provide your `flutter doctor -v` and the use case you are trying to achieve.

**Comment by Scott-Tenera** [comment]
@darshankawar . I would just like to confirm that mofifying newDevicePixelRatio without modifying newTextScaleFactor does result in a UI change. Does you scaffold appbar get larger? This is not what I am observing, so maybe there is a bug here that is only symptomizing in my environment.

As mentioned in the initial post, I expected the moodifying newDevicePixelRation (and by extension newSize) to result is a display scale change. Like you mentioned, this is what you are seeing, but not what I am seeing with the same code.

Did you test on an emulator?

I am specifically running on a emulator with the following config.ini using system image..
system-images;android-28;google_apis_playstore;x86_64
```
PlayStore.enabled=false
abi.type=x86_64
avd.ini.encoding=UTF-8
disk.dataPartition.size=6442450944
hw.accelerometer=yes
hw.audioInput=yes
hw.battery=yes
hw.cpu.arch=x86_64
hw.dPad=no
hw.device.hash2=MD5:869d76256fcdae165862720ddb8343f9
hw.device.manufacturer=Google
hw.device.name=Nexus 6P
hw.gps=yes
hw.lcd.density=480
hw.lcd.height=2560
hw.lcd.width=1440
hw.mainKeys=no
hw.sdCard=yes
hw.sensors.orientation=yes
hw.sensors.proximity=yes
hw.trackBall=no
image.sysdir.1=system-images/android-28/google_apis_playstore/x86_64/
tag.display=Google Play
tag.id=google_apis_playstore
```

flutter doctor - v
```
[✓] Flutter (Channel stable, 2.8.1, on Ubuntu 20.04.3 LTS 5.11.0-46-generic, locale en_CA.UTF-8)
    • Flutter version 2.8.1 at /home/tenera/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (4 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /usr/local/android-sdk
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /usr/local/android-sdk
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+8-Ubuntu-0ubuntu1.20.04)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version 1.63.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.32.0

[✓] Connected device (2 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64    • Android 9 (API 28) (emulator)
    • Chrome (web)                          • chrome        • web-javascript • Google Chrome 97.0.4692.71

! Doctor found issues in 2 categories.
```

**Comment by Scott-Tenera** [comment]
I just tested on a physical android device running Android 8.0, and changing newDevicePixelRatio had no effect.
@darshankawar Are you SURE you actually observed changes to newDevicePixelRatio having an effect, or was it just newTextScaleFactor.

**Comment by darshankawar** [comment]
> I would just like to confirm that when you modify newDevicePixelRatio without modifying newTextScaleFactor does result in a UI change. Correct?

I initialy updated both `newDevicePixelRatio` and `newTextScaleFactor` and saw the change. I later tried to just change `newDevicePixelRatio` which didn't change anything on screen, indicating it doesn't have any effect, that led me to this open issue which sounds similar to your case, https://github.com/flutter/flutter/issues/32115. Check that and underlying comments and see if it helps.
