### ISSUE TITLE
[windows][MethodChannel] How to move "result pointer" to another thread?

### ISSUE THREAD

**Issue by niuhuan** [flutter/flutter#96496]
**Target Platform: WINDOWS**
**Target OS version/browser: WINDOWS 10**
**Devices: Desktop**

## Logs

<details>
<summary>Logs</summary>

```
It works normally
```

</details>

this code is running normal, but is block ui control use mouse or key board, util method channel result, i want it running to another thread
my_method takes quite a long time
```c++
    void MethodsPlugin::HandleMethodCall(
            const flutter::MethodCall<flutter::EncodableValue> &method_call,
            std::unique_ptr<flutter::MethodResult<flutter::EncodableValue>> result
            ) {

        if (method_call.method_name().compare("invoke") == 0) {
            const auto *title = std::get_if<std::string>(method_call.arguments());
            auto* rspFlag = my_method((title)->c_str());
            result->Success(flutter::EncodableValue(std::string(rspFlag)));
        } else {
            result->NotImplemented();
        }

    }
```

I modify codes
```c++
// using thread
std::thread(my_function, title, move(result)); // application had crash
// using boost::thread
boost::thread(&my_function, title, move(result)); // method has been deleted, Not compiled successfully
```

I implemented this function with Thread{}.start on Mac. It doesn't block the UI, but I don't know how to do it on windows

**Comment by niuhuan** [comment]
I find other issue #22024

**Comment by stuartmorgan** [comment]
See https://flutter.dev/community#community-grid for resources where you can get help with your own code. Threading APIs are provided by your OS, not Flutter.

**Comment by niuhuan** [comment]
@stuartmorgan  thanks for your reply

**Comment by stuartmorgan** [comment]
Note that if what you want is for everything to be on a single background thread, rather than doing your own threading, you should vote for https://github.com/flutter/flutter/issues/93945
