### ISSUE TITLE
No mac android devicelab tests are running on presubmit

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#96501]
As part of the release workflow we run presubmit tests in the release branch candidate before the actual release. However we don't have any tests running on the Mac Android configuration and we didn't catch infra configuration errors for Mac Android test beds causing all of them to fail with an infra failure.

![image](https://user-images.githubusercontent.com/54371434/149052210-ab0199ba-da86-4ec0-8f3b-68655b20ea5b.png)

To prevent this issue from happening in future releases we need to move one Mac Android test bed to the try pool and make it run in presubmit for changes to .ci.yaml.

@keyonghan can you please help us identify the fastest test for Mac Android that we can use on presubmit?
@CaseyHillers can you please help us enabling the test on presubmit?

**Comment by godofredoc** [comment]
\cc @itsjustkevin

**Comment by keyonghan** [comment]
We now have only 7 Mac_android tests running in master, where [`Mac_android%20run_release_test`](https://ci.chromium.org/p/flutter/builders/prod/Mac_android%20run_release_test) took only ~2 mins.

Do we still want to run those mac/android on release? (https://github.com/flutter/flutter/pull/95365).

**Comment by godofredoc** [comment]
We would like to run at least one mac android test on presubmit. This is to catch errors on devicelab configurations on presubmit. An example of this is we failed to identify the mac android machines moved to mac 12 and we had to retry +20 builds manually on postsubmit with different parameters slowing down the release process by several hours.
