### ISSUE TITLE
Cloudbuild is triggering new builds for commits in master

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#96508]
Cloudbuild builds should only be triggered by changes in main, however it seems like both main and master trigger new builds.

![image](https://user-images.githubusercontent.com/54371434/149068457-f42eb780-8243-4378-91de-dd566846cde1.png)

**Comment by godofredoc** [comment]
@keyonghan can you please take a look?

**Comment by keyonghan** [comment]
The cloudbuild trigger is correctly pointing to `main` branch, but the cloud scheduler is with `"branchName": "master"`.
Updated to `"branchName": "master"`. Waiting for validation.

**Comment by keyonghan** [comment]
Cloudbuild is building against only main. Closing.
