### ISSUE TITLE
Whenever running a project getting this error 

### ISSUE THREAD

**Issue by Aryan3010** [flutter/flutter#96518]
Whenever I am trying to run a flutter project or even run any other flutter commands like flutter doctor or flutter clean or flutter get packages, I am running into this error. Even tried reinstalling flutter but facing the same issue.

<img width="1525" alt="Screenshot 2022-01-12 at 3 26 38 PM" src="https://user-images.githubusercontent.com/64428401/149117894-b21e786a-d1f3-4f67-b4e4-3bdf10635591.png">
`Building flutter tool...
.pub-cache/hosted/pub.dartlang.org/args-2.3.0/lib/command_runner.dart:9:8: Error: Error when reading '.pub-cache/hosted/pub.dartlang.org/args-2.3.0/lib/src/arg_parser.dart': No such file or directory
import 'src/arg_parser.dart';
       ^

.pub-cache/hosted/pub.dartlang.org/args-2.3.0/lib/args.dart:5:1: Error: Error when reading '.pub-cache/hosted/pub.dartlang.org/args-2.3.0/lib/src/arg_parser.dart': No such file or directory
export 'src/arg_parser.dart' show ArgParser;
^
.pub-cache/hosted/pub.dartlang.org/args-2.3.0/lib/src/arg_results.dart:7:8: Error: Error when reading '.pub-cache/hosted/pub.dartlang.org/args-2.3.0/lib/src/arg_parser.dart': No such file or directory
import 'arg_parser.dart';
       ^
.pub-cache/hosted/pub.dartlang.org/args-2.3.0/lib/command_runner.dart:14:8: Error: Error when reading '.pub-cache/hosted/pub.dartlang.org/args-2.3.0/lib/src/utils.dart': No such file or directory
import 'src/utils.dart';
       ^
developer/flutter/packages/flutter_tools/lib/src/reporting/crash_reporting.dart:8:8: Error: Error when reading '.pub-cache/hosted/pub.dartlang.org/http-0.13.4/lib/http.dart': No such file or directory
import 'package:http/http.dart' as http;
       ^
.pub-cache/hosted/pub.dartlang.org/vm_service-7.3.0/lib/vm_service.dart:7:1: Error: Error when reading '.pub-cache/hosted/pub.dartlang.org/vm_service-7.3.0/lib/src/dart_io_extensions.dart': No such file or directory
export 'src/dart_io_extensions.dart';
^
.pub-cache/hosted/pub.dartlang.org/async-2.8.2/lib/async.dart:13:1: Error: Error when reading '.pub-cache/hosted/pub.dartlang.org/async-2.8.2/lib/src/cancelable_operation.dart': No such file or directory
export 'src/cancelable_operation.dart';
^
.pub-cache/hosted/pub.dartlang.org/async-2.8.2/lib/src/byte_collector.dart:7:8: Error: Error when reading '.pub-cache/hosted/pub.dartlang.org/async-2.8.2/lib/src/cancelable_operation.dart': No such file or directory
import 'cancelable_operation.dart';
       ^
.pub-cache/hosted/pub.dartlang.org/async-2.8.2/lib/async.dart:25:1: Error: Error when reading '.pub-cache/hosted/pub.dartlang.org/async-2.8.2/lib/src/result/result.dart': No such file or directory
export 'src/result/result.dart';
^
.pub-cache/hosted/pub.dartlang.org/async-2.8.2/lib/src/result/error.dart:7:8: Error: Error when reading '.pub-cache/hosted/pub.dartlang.org/async-2.8.2/lib/src/result/result.dart': No such file or directory
import 'result.dart';`

**Comment by mraleph** [comment]
You have corrupted `.pub_cache`. If you have `.pub_cache` in Flutter installation directory - delete it, then run `dart pub cache repair`.

**Comment by maheshmnj** [comment]
Hi @Aryan3010, Please try the solution shared above and feel free to write back if you still encounter the issue.

**Comment by Aryan3010** [comment]
Great. Thanks a lot. That worked
