### ISSUE TITLE
[Proposal] Conditional bundling of assets

### ISSUE THREAD

**Issue by navaronbracke** [flutter/flutter#96514]
## Use case

I was looking into setting up different environment configurations for an application that is both a mobile app and a web app.
The usual setup for an environment config involves an `.env` file as an asset for the app.
For multiple environments / .env files, different entrypoints can be used with the `-t` flag for build & run.

However, switching between these targets has one problem.
In terms of developer experience, I'd expect to be able to just change the argument for `-t` _and nothing else_.

In practice, I'd have to edit the pubspec.yaml before each build / run.
Otherwise I would be including .env files that are not used at runtime.
(I.e. when running with `.env.test`, you don't need/want `.env.dev` in your assets,
 both to reduce file size and for security reasons)

Example:
For dev
```
flutter:
  assets:
    - .env.dev
    # - .env.test
```

For test
```
flutter:
  assets:
    # - .env.dev
    - .env.test
```

## Proposal

There should be a way to conditionally include an asset, based on a predefined condition.
Perhaps there could be an extra pubspec section or file that allows developers to setup an environment specific part.

Example:
```
# pubspec.yaml
flutter:
  assets:
   - shared_asset.png
   
  environment-configuration:
    my-custom-dev-env: # Entries with custom keys, but with the same structure as a regular app (assets / fonts / etc)?
      assets:
        - .env.dev
    my-custom-test-env:
      assets:
        - .env.test
```
Switching between `environment-configuration` entries could be done using a new flag for `flutter build / flutter run`?
By default nothing would be included.

**Comment by maheshmnj** [comment]
Hi @navaronbracke, Thanks for filing the issue. Labeling it as a valid proposal for further thoughts from the team.

**Comment by gnprice** [comment]
Does #21682 cover this use case?

If it doesn't already, then this feature sounds like something that would likely be good to include in the same design as that one. So that thread and its design doc https://flutter.dev/go/flavor-specific-assets would be a good place to explain this use case and see if and how it can be addressed as part of the same design.

**Comment by navaronbracke** [comment]
Yes, #21682 would make this issue redundant in my opinion, as the assets could be specified under the flavor.

Although, I did see that https://github.com/flutter/flutter/pull/139045 would make this a no-op for web.
In past web projects, I found it useful to specify an "environment" (akin to the Typescript idea of an "environment").

If we could make the flavor option work on the web in a similar way (i.e. just including the assets for the flavor option, but nothing else, since it doesn't apply) then I would consider this issue incorporated in that proposal.

**Comment by andrewkolos** [comment]
In response to the two previous comments: 

First off, thanks for thoughtful insights here! Here are my own thoughts. I don't consider this proposal to be *necessarily* redundant with #21682. My current perception of Flutter's flavors feature is that it was meant as a way to have multiple native-level build configurations on the platforms we support it for (currently Android and iOS)[^1]. In fact, if you try to use `--flavor` without defining flavors within your app's `android/app/build.gradle` file, the `flutter` CLI will exit with an error when trying to build the app[^2].

Said another way, even when https://github.com/flutter/flutter/pull/132985 lands and resolves #21682, trying to use flavors *specifically* as a mechanism to conditionally bundle assets would be a hassle for the app developer[^3]. However, there are still options here.

1. We could always redefine the flavors feature to be a Flutter-first feature. By this, I mean that we could make it possible to use `--flavor` without having to define or care about native-level configs. This would make even more sense if/when we add more flavor-related functionality to Flutter.
2. We could provide alternative ways to conditionally bundle assets. For example, consider the proposed syntax for conditionally bundling assets based on flavor:

```yaml
flutter:
  assets:
    - path: assets/dogfood/ # Only gets bundled when `--flavor` is set to `dogfood`
       flavors:
         - dogfood
```

We could augment this syntax to, for example, conditionally bundle assets based on environment variable(s):

```yaml
flutter:
  assets:
    - path: assets/dogfood/ # Only gets bundled when `BUILD=ENV` is set to `dogfood` during flutter run/build.
      env:
         - BUILD_ENV=dogfood
```

Of course, these two options aren't mutually exclusive. Still, we would have to ask ourselves the typical questions that come along with proposals, such as 1) how much time would this cost the project to implement and maintain, 2) how desired is this feature/how important is it compared to other work, 3) is there a better alternative, etc..

[^1]: https://github.com/flutter/flutter/pull/139045 is meant as a precaution to prevent users from depending on `--flavor` working on all platforms is it not supported for. To me, it is not obvious whether or not we should support on this on all platforms. This is why I wrote this PR to land before/along with https://github.com/flutter/flutter/pull/132985.
[^2]: https://github.com/flutter/flutter/pull/132985#discussion_r1408628102. Whether or not this was originally intended is unknown to me.
[^3]: Developers would have to follow all the instructions at https://docs.flutter.dev/deployment/flavors, and it could make upgrading to future versions of Flutter that change native setup more difficult.

**Comment by gnprice** [comment]
Thanks, that's quite informative.

I think it could get confusing if `--flavor` sometimes, but not always, had the effect of controlling which Android- or iOS-level flavor was used. That'd also mean that if you started using `--flavor` without having any native-level flavors, and then later wanted to have native-level flavors to control some other unrelated dimension in the native-level build, things might get sticky; I think the upshot there might be that you'd run into a complexity cliff, where before you can start using native-level flavors you have to migrate your existing `--flavor` flavors to also be native-level flavors.

Having some sort of separate way of making an asset conditional (i.e. this issue, then) makes sense to me. Perhaps through environment variables, or perhaps some command-line flag akin to `gradle -Pdogfood`. I appreciate that the syntax in #132985 is designed to be smoothly extensible that way.

The use case I personally have right now is to make it conditional on the target platform: include for Android, leave out for iOS. So perhaps that could look something like
```yaml
flutter:
  assets:
    - path: assets/for-android/
      platforms:
        - android
```

(It'd also be possible to get a similar effect using just #132985, but it'd be cumbersome in the way you describe, plus we'd have to take care to invoke `flutter build` and `flutter run` in special ways for each platform.)

Oh also: my current use case is specifically for a font asset, and until just now I'd forgotten that those have their own pubspec syntax separate from `flutter: assets: …`. Does #132985 cover fonts? If not then I guess we should split out a new issue for that — fonts were mentioned in the original #21682 description but I think it makes sense to track them as separate issues.

**Comment by navaronbracke** [comment]
@andrewkolos In relation to the build failing on Android, if you forget to specify the flavor option, I find it annoying that the tool first tries to build and then after a while exits with the error. I think we should do a tool exit early if we:
- are building for Android
- the Android project defines `productFlavors`
- the `--flavor` option is not given

Should I file a separate issue for that one?

**Comment by andrewkolos** [comment]
> @andrewkolos In relation to the build failing on Android, if you forget to specify the flavor option, I find it annoying that the tool first tries to build and then after a while exits with the error. I think we should do a tool exit early if:
> 
> * we are building for Android
> * the Android project defines `productFlavors`
> * the `--flavor` option is not given
> 
> Should I file a separate issue for that one?

Yep, feel free to file an issue for that and reference this issue in its description. I'll triage it.

**Comment by navaronbracke** [comment]
Filed https://github.com/flutter/flutter/issues/139286 to track the tool issue.

**Comment by MaiaFerreira04** [comment]
flutter:

  assets:
    - assets/comum/images/
    - path: assets/premium/images/
      flavors: 
        - premium
    - path: assets/free/images/
      flavors: 
        - free
It's giving this error:

Assets are required to be file paths (strings). Try converting the value to be a string.

But I researched a lot of information but none of it worked, even the recent post about it but I did exactly the same but it just gives this error and when emulating the app it gives this error:

Assent manifest contains a null or empty uri Assent manifest contains a null or empty uri

**Comment by andrewkolos** [comment]
@MaiaFerreira04 To avoid cluttering this thread, please file a separate issue. When do you, please post the pubspec in a [preformatted code block](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks). This will preserve the indentation so that me or another triager can properly reproduce your issue.

**Comment by hampsterx** [comment]
I find it funny that chatGPT said this which is not supported:

> To make an asset optional, you can use the ? (question mark) character to denote that the asset is optional. Here's an example:

```
flutter:
  assets:
    - assets/image1.png
    - assets/image2.png
    - assets/some_optional_asset.txt?
    - assets/another_optional_asset.json?
    ```

Given a "/" includes all the files the nullable syntax "?" seems reasonable :)

**Comment by navaronbracke** [comment]
@andrewkolos Since we now have flavor specific assets per https://github.com/flutter/flutter/pull/132985, I'm not sure if _this_ issue is still relevant? AFAIK flavors was the only conditional thing that I could come up with, unless people also want it to work with values coming from `Platform.environment` ?

**Comment by andrewkolos** [comment]
> @andrewkolos Since we now have flavor specific assets per #132985, I'm not sure if _this_ issue is still relevant? AFAIK flavors was the only conditional thing that I could come up with...

If flavor-conditional asset bundling is sufficient for the desired use case described in the issue, then I think it makes sense to close the issue (after tweaking the title slightly). I've gone ahead and done this, feel free to reopen if you disagree.

> ... unless people also want it to work with values coming from `Platform.environment`?

This would certainly be a valid request, and I would welcome that in a new issue. If this is specifically what some users following this issue wanted, then any of them are free to write up a new issue that links back to this one.

**Comment by amrgetment** [comment]
@andrewkolos Note that no flavors on Web, Linux, Windows so currently I use dart-define for web
flutter build ipa --release --flavor dev --dart-define flavor=dev

This is how I get the Environment Flavor

```
Flavor getEnvironmentFlavor() {
  // Flutter has the flavor you passed by cli '--flavor dev'
  // for mobile and desktop only
  // https://api.flutter.dev/flutter/services/appFlavor-constant.html
  const String defaultFlutterFlavor =
      String.fromEnvironment('FLUTTER_APP_FLAVOR') != ''
          ? String.fromEnvironment('FLUTTER_APP_FLAVOR')
          : '';

  if (defaultFlutterFlavor.isNotEmpty) {
    return Flavor.byName(defaultFlutterFlavor);
  }

  const String flavorEnv =
      bool.hasEnvironment('flavor') ? String.fromEnvironment('flavor') : '';
  return Flavor.byName(flavorEnv);
}
```
