### ISSUE TITLE
Make the 'Flutter doctor check' understand development for a specific platform

### ISSUE THREAD

**Issue by MdeBruin93** [flutter/flutter#96523]
## Use case

I know the title might be a vague, but please let me explain it. I'm currently running Flutter on my Windows 11 machine which runs perfectly fine. However, I have no interest in developing mobile apps on my Windows 11 machine as I prefer to use my Mac for that, so everytime I run the flutter doctor command on my Windows machine it's telling me that it found 2 issues. This is obvious since I do not have Android Studio installed and neither do I have the Android SDK installed, I just want to develop webapps/Windows desktop applications on my Windows machine. I do have the necessary components installed for that kind of development so there is no need to warn me about missing Android components.
I've been developing with Flutter for a while now so I know that I can ignore the errors/warnings, but for someone who is new to Flutter it might be confusing.

## Proposal

Extend the check done by the Flutter CLI to make people understand what they need to develop for a specific platform. In my case it should tell me that I'm all set for Web/Windows development, however for other platforms (Android, iOS etc.) I would require additional components and/or a different OS.

**Comment by darshankawar** [comment]
@MdeBruin93 
Can you check [this](https://github.com/flutter/flutter/issues/90357) issue and see if it'll serve your use case ?

**Comment by MdeBruin93** [comment]
@darshankawar , although I do see the similarities I don't see how it will serve my use case.
For as for as I can see that issue is related to not being able to detect all chromium based browsers. For me the issue is that all the requirements for web development are there, just missing tools for platforms I don't even want to target.

**Comment by stuartmorgan** [comment]
Could you post your `doctor` output and explain what precisely you are suggesting changing? It already has clearly labeled sections for each target platform, so it's not clear what you mean by "understand development for a specific platform"

**Comment by MdeBruin93** [comment]
@stuartmorgan , this is my current output of Flutter doctor:

```
[✓] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.22000.376], locale nl-NL)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Chrome - develop for the web
[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.4)
[!] Android Studio (not installed)
[✓] VS Code, 64-bit edition (version 1.63.2)
[✓] Connected device (3 available)
```

I think the Flutter CLI will make it a bit more clear if it would output something like this.

```
[✓] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.22000.376], locale nl-NL)

[✓] Chrome - develop for the web
[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.4)
[✓] VS Code, 64-bit edition (version 1.63.2)
[✓] Connected device (3 available)

[✓] All set for Web and Windows development

[✗] For Android development please install the requirement as listed below:
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.
[!] Android Studio (not installed)

[✗] For iOS and/or MacOS development you will need to use MacOS with Xcode.
[✗] For Linux development you will need to use Linux.
```

I think it will help developers new to Flutter to understand the Flutter CLI output a bit better, but maybe I'm wrong.

**Comment by stuartmorgan** [comment]
Android Studio isn't specific to Android development, it's one of the two editors that are supported by the Flutter team. So the grouping you have suggested there isn't correct.

 The part that is specific to Android is the section:
```
Android toolchain - develop for Android devices
```
