### ISSUE TITLE
MaterialIcons FileSize

### ISSUE THREAD

**Issue by cksoft0807** [flutter/flutter#96525]
MaterialIcons-Regular.otf has (for web) a huge file size of 1.3mb.
 If I deactivate it by  "uses-material-design: false" I miss important icons, for example for drawer or back button.

I would appreciate it if there was a possibility to include here only the most important icons and the others in a separate file.

**Comment by darshankawar** [comment]
@cksoft0807 
Try loading the fonts using [FontLoader](https://api.flutter.dev/flutter/services/FontLoader-class.html) and see if it helps.
