### ISSUE TITLE
image_picker 0.8.4+4 PlatformException(already_active, Image picker is already active, null, null)

### ISSUE THREAD

**Issue by nandhakumargdr** [flutter/flutter#96527]
Hi,

I'm getting `PlatformException(already_active, Image picker is already active, null, null)` on initiating the open camera functionality for the second time.

`XFile? image = await _picker.pickImage(source: ImageSource.camera);`

FYI, I'm using `image_picker 0.8.4+4`

I have noticed this is happening on my One Plus 5T mobile running Android 9 and on other few device, this problem is not happening.

This is my SDK flutter doctor -v

![image](https://user-images.githubusercontent.com/31739695/149152551-ce252f20-a089-4234-a347-589a3ab6ff5b.png)

**Comment by maheshmnj** [comment]
HI @nandhakumargdr, Thanks for filing the issue.

There is a similar issue describing this case https://github.com/flutter/flutter/issues/87896, Please follow up there for further updates, Closing this issue as a duplicate. If you disagree feel free to write in the comments and I will reopen it.

Thank you.
