### ISSUE TITLE
Integrity check failed: java.security.NoSuchAlgorithmException: Algorithm HmacPBESHA256 not available

### ISSUE THREAD

**Issue by DennisAshford** [flutter/flutter#96566]
I am trying to build an app bundle and getting the following error.

* What went wrong:
Execution failed for task ':app:signReleaseBundle'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Failed to read key upload from store "/Users/dennisashford/AndroidStudioProjects/fytfeedv10/android/app/upload-keystore.jks": Integrity check failed: java.security.NoSuchAlgorithmException: Algorithm HmacPBESHA256 not available

I believe I have narrowed it down to the Java versions used to generate the key file and Java JDK used to build the app bundle. It appears the key store file was generated using Java 17, and Android Studio is using Java 11 to build the app bundle. However, Java 11 cannot read the encryption. However, I have no idea how to specify within flutter or Android Studio which Java version to use to build the app bundle and sign the app using the uploaded key store file. I cannot regenerate a key either, as the app is already published. 

Flutter doctor -v
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6.1 20G224 darwin-x64, locale en-US)
    • Flutter version 2.8.1 at /Users/dennisashford/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (4 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/dennisashford/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.59.1)
    • VS Code at /Users/dennisashford/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554                        • android-x86    • Android 11 (API 30) (emulator)
    • iPhone 12 (mobile)                 • CCFE8FB8-8AEB-4D19-9A7B-B5AEE7F5F411 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)                       • chrome                               • web-javascript • Google Chrome 97.0.4692.71

**Comment by maheshmnj** [comment]
Hi @DennisAshford, Please ask support questions on the support forums like StackOverflow.  Additionally, you may check if this StackOverflow answer helps resolve the issue https://stackoverflow.com/a/67632064/8253662

Closing as this issue doesn't seem to describe a bug or a feature request in flutter.
