### ISSUE TITLE
Version 2.8.1 Running the application in the profile environment on Android devices is likely to have some text loading problems and tabbar at the bottom only has ICONS without text.

### ISSUE THREAD

**Issue by KirstenDunst** [flutter/flutter#96571]
Version 2.8.1 Running the application in the profile environment on Android devices is likely to have some text loading problems and tabbar at the bottom only has ICONS without text. The project was created under version 2.5.3 and runs under version 2.5.3 without problems. Therefore, I am not very clear whether the problem is with version 2.5.3 or version 2.8.1, and how to fix this problem?

**Comment by darshankawar** [comment]
@KirstenDunst 
Can you provide a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows the issue you described ?
