### ISSUE TITLE
How can I move video recored file to specific folder 

### ISSUE THREAD

**Issue by kotran88** [flutter/flutter#96579]
I recorded video with flutter app and path is /data/user/0/com.xxx.yyyyy/cache/REC4416034190188903245.mp4
how can I change file name and store it specific folder for example /storage/emulated/0/DCIM/CCd3

folder CCd3 is already exist.

how I get video file path is below. 
```
      XFile videoFile = await _cameraController.stopVideoRecording();
      File videoFile2 = File(videoFile.path);
```

**Comment by danagbemava-nc** [comment]
Hi @kotran88, the flutter issue tracker is for reporting issues with flutter. 

For help with personal code, kindly see https://flutter.dev/community#community-grid and visit any of those communities. 

Closing as this is neither a bug report nor a feature request. 

Thank you
