### ISSUE TITLE
Official fully functional example application that uses navigator 2.0

### ISSUE THREAD

**Issue by fctorial** [flutter/flutter#96586]
## Use case

Navigator 2.0 api is very inaccessible. Part of the reason is that there are no official examples that display how to use the api properly. There are indeed a bunch of medium posts, but many of which contradict each other and most of them do not cover the api in depth.

## Proposal

A complex official demo app that uses stock navigator 2.0 api without any third party libraries and contains multiple nested routers and navigator widgets, that works on every supported platform.

**Comment by darshankawar** [comment]
@fctorial 
I will direct you to this [repo](https://github.com/flutter/uxr/issues) where you can raise this proposal, as that link is dedicatedly maintained for navigation 2.0 related issues and discussion. Closing from here. If you disagree, write in comments and I'll reopen it to consider this proposal here.
