### ISSUE TITLE
[firebase_in_app_messaging] Unhandled Exception: PlatformException(firebase_core, Can't create handler inside thread Thread that has not called Looper.prepare(), null, null)

### ISSUE THREAD

**Issue by iLoveDocs** [flutter/flutter#96595]
### Minimal reproducible code

```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
 
  runApp(...);
}
```

On running the app on Android, I get the following error: 

> [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(firebase_core, Can't create handler inside thread Thread[pool-3-thread-1,5,main] that has not called Looper.prepare(), null, null)

I'm using `firebase_in_app_messaging: ^0.6.0+6`. The above code works on removing this package.

### Flutter doctor: 

```
[✓] Flutter (Channel dev, 2.9.0-0.1.pre, on macOS 12.0.1)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] Connected device (3 available)
```

### Platform

- [ ] iOS
- [x] Android

**Comment by stuartmorgan** [comment]
Issues with third-party plugins need to be reported to the plugin's developer.
