### ISSUE TITLE
IconButton Splash misaligned on adding `IconButton.icon.size`

### ISSUE THREAD

**Issue by maheshmnj** [flutter/flutter#96606]
## Steps to Reproduce

1. Run the second code snippet 
2.  hover cursor on the icon

### Expected Results: Icon splash should be center aligned 
<table>
  <tr>
    <td>code sample</td>
     <td>output</td>
  </tr>
 <tr>
<td>
  <pre>
 IconButton(
    splashRadius: 50,
    iconSize: 50,
    onPressed: () {},
    icon: const Icon(
    Icons.add,
))
</pre>
</td>
<td>
<img src="https://user-images.githubusercontent.com/31410839/149370532-e50aff05-304d-4538-8403-27d2cb34cfe4.png" width ="300"></td>
</tr>
 </table>

### Actual Results:  IconButton splash is not center-aligned
<table>
  <tr>
    <td>code sample</td>
     <td>output</td>
  </tr>
 <tr>
<td>
  <pre>
 IconButton(
    splashRadius: 50,
    onPressed: () {},
    icon: const Icon(
    Icons.add,
    size: 50,
)),

</pre>
</td>
<td>
<img src="https://user-images.githubusercontent.com/31410839/149371389-46a8bd3f-9d3e-4e85-a8f7-9aaca6df0ec6.png" width ="300"></td>
</tr>
 </table>

## Logs

<details>
<summary>flutter doctor -v</summary>

```
```

```
[✓] Flutter (Channel master, 2.9.0-1.0.pre.328, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.9.0-1.0.pre.328 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d290763941 (2 days ago), 2022-01-11 18:20:14 -0800
    • Engine revision 643b2787f4
    • Dart version 2.16.0 (build 2.16.0-159.0.dev)
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 97.0.4692.71

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by dheerajv09** [comment]
/// ### Icon sizes
///
/// When creating an icon button with an [Icon], do not override the
/// icon's size with its [Icon.size] parameter, use the icon button's
/// [iconSize] parameter instead.  For example do this:
///
/// ```dart
/// IconButton(iconSize: 72, icon: Icon(Icons.favorite), ...)
/// ```
///
/// Avoid doing this:
///
/// ```dart
/// IconButton(icon: Icon(Icons.favorite, size: 72), ...)
/// ```
///
/// If you do, the button's size will be based on the default icon
/// size, not 72, which may produce unexpected layouts and clipping
/// issues.
///

**Comment by darshankawar** [comment]
@maheshmnj 
Although I do see the same behavior, but since there are two properties namely `iconSize` which belongs to `IconButton` and `size` belonging to `Icon` widget that have different implementation. Looking at the usage of both these properties in the document:

iconSize (from IconButton):

```
`/// via an [IconTheme]. Setting the size here instead of in, for example, the
  /// [Icon.size] property allows the [IconButton] to size the splash area to
  /// fit the [Icon].`
```

size (from Icon):

```
`
/// If this [Icon] is being placed inside an [IconButton], then use
  /// [IconButton.iconSize] instead, so that the [IconButton] can make the splash
  /// area the appropriate size as well.
`
```

If we use `IconButton.icon.size`, then document says:

```
`If you were to set the size of the [Icon] using
  /// [Icon.size] instead, then the [IconButton] would default to 24.0 and then
  /// the [Icon] itself would likely get clipped.`
```

We can validate above by just wrapping `IconButton` inside a Container and give it a color, so that we know the Icon gets clipped as below:

<img width="126" alt="Screenshot 2022-01-14 at 1 01 41 PM" src="https://user-images.githubusercontent.com/67046386/149468718-cea7378f-5d3f-4a27-ae17-78c7113c8f36.png">

And hence we get to see the Splash being misaligned. So I think, using IconButton's `iconSize` is preferred way to pass the icon size.  Let me know what you think.

**Comment by maheshmnj** [comment]
Thanks for taking a look @darshankawar, I think the docs answer it.

Closing as this is working as intended.
