### ISSUE TITLE
[web] Size regression flutter_gallery_dart2js_size

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#96603]
https://flutter-flutter-perf.skia.org/t/?begin=1641927612&end=1641927613&subset=all
Commit: https://github.com/flutter/flutter/commit/9490917408a5715ac7a02b1c27f86c089f9cafe6

**Comment by yjbanov** [comment]
This did not affect the gzip size, which is the more important metric, so it's safe to let it through.
