### ISSUE TITLE
should keep path / activity when memory can't keep app open

### ISSUE THREAD

**Issue by edsonISA** [flutter/flutter#96604]
When the RAM memory is not able to maintain a flutter application, it restarts in its entirety, that is, if it is on route B it returns to route A, while in a native app it stays on route B.

I don't want the path to be saved when I close the app manually, but I want it to be saved when I return to the app and the RAM can't keep the app open.

https://user-images.githubusercontent.com/85927029/149370772-8d608b6d-c387-456d-88d3-07a0894bc2a6.mp4

The code is simple, it is nothing more than a button that opens another route

**Comment by darshankawar** [comment]
@edsonISA 
I think this is related to State restoration wherein the application state isn't maintained in situations like when the app is over memory. The same issue is raised here https://github.com/flutter/flutter/issues/84193. You can follow-up in it for further updates.
Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.

**Comment by edsonISA** [comment]
> @edsonISA Creo que esto está relacionado con la restauración del estado en el que el estado de la aplicación no se mantiene en situaciones como cuando la aplicación tiene demasiada memoria. Aquí se plantea el mismo problema #84193 . Puede hacer un seguimiento en él para obtener más actualizaciones. Cerrando esto como un duplicado. Si no está de acuerdo, escriba en los comentarios y lo reabriré.

yes, it's a duplicate, it speaks exactly the same
