### ISSUE TITLE
Long presubmit queue time on Fuchsia SDK roll

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#96602]
https://github.com/flutter/engine/pull/30836

**Comment by akbiggs** [comment]
Is it okay if I close the pull request to re-trigger the roll and CQ, or should we leave it open to debug?

**Comment by zanderso** [comment]
I believe the cause of the long queue times is already known, but in general it's good practice to try to roll in the earliest version of a dependency possible that has the fix. So, another option would be to close the auto roll, and do a manual roll to the same version or the first version with the fix.

**Comment by chaselatta** [comment]
Closing the issue since we closed the autoroll PR. Will open if it happens again.
