### ISSUE TITLE
mock_canvas.paints possibly doesn't track offsets

### ISSUE THREAD

**Issue by xster** [flutter/flutter#9662]
May be wrong usage on my part. Probably a question for @abarth. Figured it would be easier to ask in written form.

1. Tests in https://github.com/xster/flutter/commit/a04dbf3d0ec1bdb1dd9d4309923cd09009a26385 pumps a RenderedDecoratedBox with a BoxPainter.
2. At a specific time in the transition, pumping causes RenderedDecoratedBox (903640131) to use BoxPainter (761085511) to paint Rect.fromLTRB(-546.9, 0.0, 253.1, 600.0) onto canvas (849442582) via
```dart
#0      _CupertinoEdgeShadowPainter.paint (package:flutter/src/cupertino/page.dart:132:22)
#1      RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:1387:16)
```
3. Get RenderedDecoratedBox (903640131) via finder and expect it to paint a rect with Rect.fromLTRB(-546.9, 0.0, 253.1, 600.0).

The rect painted in 2 was not registered mock_canvas. Though the call to `expect(RenderDecoratedBox,  paints..)` actually caused another call to the RenderedDecoratedBox (903640131) to use the same BoxPainter (761085511) to paint Rect.fromLTRB(-800.0, 0.0, 0.0, 600.0) onto another canvas of type TestRecordingCanvas (441538567) via
```dart
#0      _CupertinoEdgeShadowPainter.paint (package:flutter/src/cupertino/page.dart:132:22)
#1      RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:1387:16)
#2      _TestRecordingCanvasPatternMatcher.matches (flutter/packages/flutter/test/rendering/mock_canvas.dart:330:22)
#3      _expect (package:test/src/frontend/expect.dart:154:17)
#4      expect (package:test/src/frontend/expect.dart:68:3)
#5      expect (package:flutter_test/src/widget_tester.dart:137:3)
```

It may be a feature difference, but since mock_canvas.dart:330:22 always passes in an Offset.zero whereas the real RenderFractionalTranslation calls `super.paint(context, offset + translation.alongSize(size))`, it doesn't seem possible currently to assert the rect offset of the draw.

**Comment by Hixie** [comment]
The `paints` expectations are in the coordinate space of the given painter (i.e. the Offset is always zero, as you note). If you want to see if it paints correctly when given a different offset, pass in a painter that calls the painter under test, with a different offset, for example:

```
  expect((PaintingContext context) => renderObject.paint(context, const Offset(20.0, 20.0)).. ... ...);
```

**Comment by xster** [comment]
Got it. I'm thinking in the wrong mindset and thought it was an integration test tool (asserts relative to the viewport). Thanks.
