### ISSUE TITLE
Remove use of the Jcenter repository in 3P plugins

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#96633]
Context: https://blog.gradle.org/jcenter-shutdown

The Flutter Gradle plugin should detect usage of the Jcenter repository, 
and delete it from the list of configured repositories.

**Comment by dolpheen** [comment]
@blasten 
Could you propose any workarounds until it is fixed? 
We have a dozen of 3p plugins, is the only way now to fork them?

**Comment by blasten** [comment]
@dolpheen do you want to try https://github.com/flutter/flutter/pull/96885?

**Comment by dolpheen** [comment]
@blasten jcenter now is up. So, I've done 2 tests. Please, see the logs attached for these two cases.
First one as it is - OK [buildlog_jcenter_is_up.txt](https://github.com/flutter/flutter/files/7910665/buildlog_jcenter_is_up.txt). 
Second one DNS for jcenter.bintray.com disabled - NOK [buildlog_jcenter_is_down.txt](https://github.com/flutter/flutter/files/7910666/buildlog_jcenter_is_down.txt)

**Comment by blasten** [comment]
@dolpheen are these logs with the fix from  #96885 applied? It should work in both cases.

**Comment by dolpheen** [comment]
@blasten Yes, these are builds with the patch applied. 
There can be seen messages "Flutter removed the jcenter repository" in both logs, but errors on jcenter (in second case when  jcenter.bintray.com disabled)

**Comment by christopherfujino** [comment]
@stuartmorgan do you know if this is resolved?

**Comment by stuartmorgan** [comment]
I don't see anything to do this automatically having landed, but I would guess that at this point any plugin that hasn't been abandoned has probably been updated already.

This probably would have been useful if it had been done immediately, but probably isn't now. Absent any indication of demand at this point I think we can just close this.
