### ISSUE TITLE
Could not build the application for the simulator (iOS)

### ISSUE THREAD

**Issue by khtggom** [flutter/flutter#96641]
## Steps to Reproduce
After flutter project, when run on ios simulator, it's failed by bleow.

## Logs

<details>
<summary>Logs</summary>

Could not build the application for the simulator.
Error launching application on iPhone 13.
"flutter run" took 25,444ms.

           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:674:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>

`flutter doctor -v`

[✓] Flutter (Channel stable, 2.8.1, on macOS 12.0.1 21A559 darwin-x64, locale ko-KR) • Flutter version 2.8.1 at /Users/hyoungtae/work_flutter/flutter • Upstream repository https://github.com/flutter/flutter.git • Framework revision 77d935af4d (4주 전), 2021-12-16 08:37:33 -0800 • Engine revision 890a5fca2e • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2) • Android SDK at /Users/hyoungtae/Library/Android/sdk • Platform android-31, build-tools 30.0.2 • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165) • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1) • Xcode at /Applications/Xcode.app/Contents/Developer • CocoaPods version 1.11.2

[✓] Chrome - develop for the web • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3) • Android Studio at /Applications/Android Studio.app/Contents • Flutter plugin can be installed from: 🔨 https://plugins.jetbrains.com/plugin/9212-flutter • Dart plugin can be installed from: 🔨 https://plugins.jetbrains.com/plugin/6351-dart • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

</details>

**Comment by ipriyam26** [comment]
did the project run on the android simulator? and is there anything in else the debug console as well?

**Comment by khtggom** [comment]
> did the project run on the android simulator? and is there anything in else the debug console as well?

Yes, androd and web both work fine.

**Comment by darshankawar** [comment]
@khtggom 
Can you provide `flutter run --verbose` ? The log will be huge so you can put that in a text file and share it here.
Also provide your `ios/podfile`.

**Comment by khtggom** [comment]
@darshankawar 
I send the log file as an attachment.
And the podfile does not exist.

[flutter_ios_log.rtf.zip](https://github.com/flutter/flutter/files/7869020/flutter_ios_log.rtf.zip)

**Comment by darshankawar** [comment]
From the log, it's failing due to below error:
```

`Target debug_unpack_ios failed: Exception: Binary /Users/hyoungtae/work/fluttertest/build/ios/Debug-iphonesimulator/Flutter.framework/Flutter does not
exist,
               cannot thin`
```

Which could be happening due to a corrupted download cache, and changing channels would have cleared out the bad framework and replaced it. 

Try changing channel from stable to master and get latest and try again to see if it helps.

**Comment by khtggom** [comment]
@darshankawar 
After reinstalling the flutter sdk, it works fine.
Thank you.

**Comment by khtggom** [comment]
Thank you.
