### ISSUE TITLE
flutter channel shows incorrect Android embedding v2 warning

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#96642]
When I run `flutter channel stable` (for example) in my root user directory, I see the following warning:

> Your Flutter application is created using an older version of the Android
embedding. It is being deprecated in favor of Android embedding v2.

This, however, makes no sense at all because my root user directory is **not** a Flutter project. It does, however, contain an `android` directory (which has nothing to do with the `android` directories you will find in Flutter projects).

## Steps to Reproduce

1. cd to a directory that contains a folder named `android`
2. `flutter channel stable` (or a different channel if you are already on stable)

<details><summary>Click to expand full logs</summary>

```
D:\>flutter channel stable
╔════════════════════════════════════════════════════════════════════════════╗
║ A new version of Flutter is available!                                     ║
║                                                                            ║
║ To update to the latest version, run "flutter upgrade".                    ║
╚════════════════════════════════════════════════════════════════════════════╝


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Warning
──────────────────────────────────────────────────────────────────────────────
Your Flutter application is created using an older version of the Android
embedding. It is being deprecated in favor of Android embedding v2. Follow the
steps at

https://flutter.dev/go/android-project-migration

to migrate your project. You may also pass the --ignore-deprecation flag to
ignore this check and continue with the deprecated v1 embedding. However,
the v1 Android embedding will be removed in future versions of Flutter.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
The detected reason was:

  No `D:\android\AndroidManifest.xml` file
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Switching to flutter channel 'stable'...
```

</details>

## Proposal

Before checking if there is an `AndroidManifest.xml` in an `android` directory and if that directory exists, check if the working directory **is a Flutter project**.  

### Steps

1. Check if the current working directory is a Flutter project → check for a `pubspec.yaml` file.
2. Check if there is an `android` directory.
3. Check for the `AndroidManifest.xml` file.

Currently, step 2. is missing.

**Comment by darshankawar** [comment]
@creativecreatorormaybenot 
I tried this case on a sample app and got a similar error but while running `flutter run`, but didn't get the same while switching to different channel. Is this specific to `flutter channel` command only or your request for other commands like `flutter run` as well ?

**Comment by creativecreatorormaybenot** [comment]
@darshankawar This is not specific to any `flutter` command, but it will only happen once and not appear thereafter. I think to reproduce it every time, you might need a clean Flutter installation.

**Comment by darshankawar** [comment]
Thanks for the update. After a clean installation, I do see the embedding warning as below while switching the channels:



> Your Flutter application is created using an older version of the Android
> embedding. It is being deprecated in favor of Android embedding v2.

Treating this as a proposal per above request.
