### ISSUE TITLE
flutter webapp-"index.html not found" thrown after preparing hosting and command 'flutter build web'. (and some other questions to ask)

### ISSUE THREAD

**Issue by KwakMinSeok** [flutter/flutter#96648]
this is my repo : https://github.com/KwakMinSeok/flutterwebapp
```
I followed this step buid,realease -> hosting(firebase) 
build, release > since I already had web folder in my project at the beginning, i just typed flutter build web.
hosting > created web project and add sdk as npm in web directory 
             > also i used webpack following this order..https://firebase.google.com/docs/web/module-bundling#entry_points
             >after i log in and test CLI, I command 'firebase init hosting' in the root of the project directory (nvm on)
             >lastly i command firebase deploy --only hosting in cmd and when i go back to the flutter terminal and comman 'flutter build 
                web' it shows "index.html not found"
I want to ask 1. how to fix the way to host above 2. if module bundling is necessary 
ps: sorry that I wrote it to messy... and used vague expressions, please don't mind to ask me again 
```
other things:
<flutter doctor>
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19042.1415], locale ko-KR)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.4)
[√] Android Studio (version 2020.3)
[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X FormatException: Unexpected extension byte (at offset 5)
[√] VS Code (version 1.63.2)
[√] Connected device (3 available)

! Doctor found issues in 1 category.
<flutter-channel> stable
<wondows> 10
<nvm> 1.1.9
<npm> 8.3.0
<firebase>10.1.0

**Comment by darshankawar** [comment]
@KwakMinSeok 
I think your question is better suited for support channels like StackOverflow, so please ask the same there.
Closing from here as this is more of a `how to` question. If you disagree, write in comments and I'll reopen if you think this is a bug in web framework.

**Comment by KwakMinSeok** [comment]
thank you for telling me where to ask
