### ISSUE TITLE
issue in installling facebook_app_events 0.14.7 plugin in my flutter project

### ISSUE THREAD

**Issue by sreeraj43** [flutter/flutter#96645]
I have getting error after adding facebook_app_events 0.14.7 plugin into my projects 
below is my flutter sdk version details
  Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1415], locale en-GB)
    • Flutter version 2.2.3 at C:\src\flutter
    • Framework revision f4abaa0735 (7 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
![appevents](https://user-images.githubusercontent.com/55575396/149459586-7e600050-9c51-406a-83d4-7f51d4bbb633.jpg)
please check and help me

**Comment by danagbemava-nc** [comment]
Hi @sreeraj43, `facebook_app_events` is a third party package. For any issues you're experiencing with it, kindly file an issue on their repo [here](https://github.com/oddbit/flutter_facebook_app_events/issues). 

Closing as this is package is not maintained by flutter. 

Thank you
