### ISSUE TITLE
ListView content vanishes when scrolled up

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#9665]
customer:tunes has a funny bug in their app (which we have not yet reduced) whereby their ListView when scrolled down works fine (on both iOS and Android), but then when scrolled *up* on Android the contents vanish.

This is what they had to say:

>I have isolated that odd Android ListView issue.  When I pull out the top banner carousel on our home screen, the issue goes away.  I had a hunch that might be where the problems were, because it’s a little bit complex up there as a TabBarView sitting in a Column above a TabPageSelector requiring a new TabController instance to drive the page selector which in return requires the widget to be a StatefulWidget with a TickerProviderStateMixin.  The mixin is needed to satisfy the requirement for a TickerProvider as the ‘vsync’ parameter in the TabController constructor.  Yikes.
>
>Anyway, I am reasonably confident based on documentation and examples that this was implemented correctly, and it does work on iOS just fine.

Working on getting a reproduction, but in case you have thoughts from the above @Hixie I've filed this.  (CC @FaisalAbid)

**Comment by eseidelGoogle** [comment]
@FaisalAbid did we have any further insight as to what might be causing this?

**Comment by eseidelGoogle** [comment]
https://github.com/flutter/flutter/issues/10453 might be a reproducible case of this?

**Comment by Hixie** [comment]
@FaisalAbid Does this still happen for you? I believe we fixed this in #10574.

**Comment by Hixie** [comment]
@FaisalAbid We're going to close this because we believe we've fixed it; please don't hesitate to reopen it if it's not fixed!
