### ISSUE TITLE
[tool] flutter command works only for the first time

### ISSUE THREAD

**Issue by mlsnatalie** [flutter/flutter#96653]
I install flutter sdk.
when I user flutter doctor first time, it works
then it dosen't work. other flutter command also doesn't work.
![图片](https://user-images.githubusercontent.com/11189469/149494442-200fc9b7-0cd0-4792-9635-e8e1458607c7.png)

**Comment by wklTomorrow** [comment]
path

**Comment by ramanjitsingh-hub** [comment]
You should try following the steps again and try to update the path. Check the link provided below
https://docs.flutter.dev/get-started/install/windows

**Comment by maheshmnj** [comment]
Hi @mlsnatalie, Could you please try running `flutter doctor -v`, If that doesn't give any output then, please try deleting the cache folder located at `flutter/bin` and re-run `flutter doctor -v`, if nothing works then I would recommend either reinstalling flutter or you may upgrade to `stable 2.8.1` by running `flutter upgrade`.
