### ISSUE TITLE
ListView set physics: const NeverScrollableScrollPhysics(), child wdiget GestureDetector can't trigger onTap event

### ISSUE THREAD

**Issue by believeZJP** [flutter/flutter#96656]
## Steps to Reproduce
I hope the child widget ontap  can be trigger

```dart

 @override
  Widget build(BuildContext context) {
    return ListView.builder(
       // NOTE： when set this, child widget can't be trigger!!!!!!
        physics:NeverScrollableScrollPhysics(),
        shrinkWrap: true,
        scrollDirection: Axis.horizontal,
        controller: _controller,
        itemBuilder: (context, index) {
          return _child();
        });
  }


Widget _child() {
    return new Row(children: _children());
  }

List<Widget> _children() {
    List<Widget> items = [];
    List list = widget.children;
    for (var i = 0; i < list.length; i++) {
      Container item = new Container(
        margin: new EdgeInsets.only(right: 10),
        child: GestureDetector(
          behavior: HitTestBehavior.translucent,
          child: list[i],
          onTap: () {
            //   this can't be trigger！！！！！！
            FlutterLogger.d('aaaaaaaa');


          },
        ) ,
      );
      items.add(item);
    }
    return items;
  }
```

**Comment by danagbemava-nc** [comment]
Hi @believeZJP, thanks for filing the issue. 

Please provide a complete minimal reproducible code sample as well as the output of `flutter doctor -v`. 

Thank you

**Comment by believeZJP** [comment]
> Hi @believeZJP, thanks for filing the issue.
> 
> Please provide a complete minimal reproducible code sample as well as the output of `flutter doctor -v`.
> 
> Thank you

https://codepen.io/believezjp/pen/YzrgNMJ this is a simple  sample.

**Comment by danagbemava-nc** [comment]
Hi @believeZJP, I ran your sample and the `onTap` was triggered just fine. Is there any more information that you can provide?

https://user-images.githubusercontent.com/88313112/149718087-112135c2-81aa-43ab-bd93-d1ae7818a3c8.mov

**Comment by believeZJP** [comment]
> Hi @believeZJP, I ran your sample and the `onTap` was triggered just fine. Is there any more information that you can provide?
> 
>  Screen.Recording.2022-01-17.at.06.21.12.mov

This is a new sample. I'm appreciated for your help!  https://codepen.io/believezjp/pen/ZEXPMVr


```bash

flutter doctor -v                                                        
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.3.1 20E241 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.0.4 at /Users/macintosh/fvm/versions/2.0.4
    • Framework revision b1395592de (10 个月前), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/macintosh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 56.0.3
    • Dart plugin version 203.8173

[✓] VS Code (version 1.60.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.3.1 20E241 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 97.0.4692.71

• No issues found!
```

**Comment by believeZJP** [comment]
https://user-images.githubusercontent.com/15198091/149802334-51574249-f311-4389-9976-1e3e9e76fff6.mov

**Comment by danagbemava-nc** [comment]
Hi @believeZJP, you appear to be on an older version of flutter. 

Kindly upgrade to the latest version of flutter and let me know whether or not you still experience this issue. 

If you do, please provide the updated `flutter doctor -v`. 

Thank you

**Comment by believeZJP** [comment]
> 

https://user-images.githubusercontent.com/15198091/149909707-8f59e2b6-38ae-4116-acd6-d736491f9e5a.mov

I still experience this issue, flutter version is 2.8.0

**Comment by believeZJP** [comment]
> Hi @believeZJP, you appear to be on an older version of flutter.
> 
> Kindly upgrade to the latest version of flutter and let me know whether or not you still experience this issue.
> 
> If you do, please provide the updated `flutter doctor -v`.
> 
> Thank you

I still experience this issue, flutter version is 2.8.0
https://user-images.githubusercontent.com/15198091/149909707-8f59e2b6-38ae-4116-acd6-d736491f9e5a.mov

**Comment by danagbemava-nc** [comment]
Hi @believeZJP, this isn't actually related to `NeverScrollablePhysics`, but rather how to handle actions when an animation is in progress. You can test this by replacing 

```dart
 _controller.animateTo(_offset, duration: widget.duration, curve: Curves.linear);
```

with 

```dart
        _controller.jumpTo(_offset);
```

May I know what exactly it is that you want to achieve in your app? Perhaps there's a different way to go about it?

**Comment by believeZJP** [comment]
> Hi @believeZJP, this isn't actually related to `NeverScrollablePhysics`, but rather how to handle actions when an animation is in progress. You can test this by replacing
> 
> ```dart
>  _controller.animateTo(_offset, duration: widget.duration, curve: Curves.linear);
> ```
> 
> with
> 
> ```dart
>         _controller.jumpTo(_offset);
> ```
> 
> May I know what exactly it is that you want to achieve in your app? Perhaps there's a different way to go about it?

Yes, I want to achieve this in my app. can you give me another way to solve this? I have been confused by this for a long time.

**Comment by danagbemava-nc** [comment]
Are your widgets going to be more complex than just `Text` widgets or are they just `Text` widgets?

**Comment by danagbemava-nc** [comment]
Conceptually, I'm not certain if the `Marquee` widget was meant to be an interactive element. 
Here's what I believe you can try.

You can attempt to detect if a hover is detected on the `ListView` and then pause the animation, then resume it when the hover event has ended. 

However, the hover event isn't available on mobile, so you might have to use a different to handle that. 

There's a similar issue already open that is meant to document how to handle gestures and animations at the same time in https://github.com/flutter/flutter/issues/14452
