### ISSUE TITLE
[macos] Platform views must be mutated on Main thread

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#96668]
There are a couple of kinks with the resize synchronizer that ought to be fixed before we can run with main thread as the raster thread. This currently blocks platform views to be enabled.

**Comment by esDotDev** [comment]
We would like to help move this along if it's possible, as our clients are quite anxious to get web_view working on macos. 

Would it be possible to provide more information on the current issue, and what work is left to do?

**Comment by patrick-fu** [comment]
Are there any updates on this?

**Comment by loic-sharma** [comment]
We're actively working on platform views for macOS. You can follow the progress here: https://github.com/flutter/flutter/issues/41722.

**Comment by knopp** [comment]
This needs to be done similar way we're flipping the surfaces, preferably at the exact same time. So some code restructuring will probably be needed.

The way it currently works: 
`[FlutterResizeSynchronizer requestCommit]` is called from raster thread. At this point a block to flip surfaces is scheduled to be executed on main thread and raster thread is blocked until this is performed.

It might be possible to bring a block that mutates the platform views as argument to [`FlutterResizeSynchronizer requestCommit`].
