### ISSUE TITLE
flutter web: 304 status

### ISSUE THREAD

**Issue by tazik561** [flutter/flutter#96675]
I am tring to launch my application as a web app. now when I run web app by `flutter run -d chrome` I get an error in inspector chrome and just chrome started and a white screen is appreared: 

    Uncaught TypeError: dartz.MonadOps$ is not a function
        at either.dart:77:1
        at Object.makeGenericType [as Either$] (classes.dart:243:51)
        at load__packages__dartz__dartz_dart (either.dart:77:1)
        at Object.execCb (require.js:1696:33)
        at Module.check (require.js:883:51)
        at Module.enable (require.js:1176:22)
        at Module.init (require.js:788:26)
        at callGetModule (require.js:1203:63)
        at Object.completeLoad (require.js:1590:21)
        at HTMLScriptElement.onScriptLoad (require.js:1717:29)
and this output in DevTools :
[![enter image description here][1]][1]

I am using flutter 2.0.6 sdk and  sdk: ">=2.7.0 <3.0.0"
I am using dartz: ^0.8.6.

  [1]: https://i.stack.imgur.com/KlQwZ.png

This is verbose out put:

    flutter run -d chrome -v
    [  +81 ms] executing: [/home/alt/fvm/versions/2.0.6/] git -c log.showSignature=false log -n 1 --pretty=format:%H
    [  +37 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
    [        ] 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
    [        ] executing: [/home/alt/fvm/versions/2.0.6/] git tag --points-at 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
    [  +23 ms] Exit code 0 from: git tag --points-at 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
    [        ] 2.0.6
    [  +46 ms] executing: [/home/alt/fvm/versions/2.0.6/] git rev-parse --abbrev-ref --symbolic @{u}
    [   +4 ms] Exit code 128 from: git rev-parse --abbrev-ref --symbolic @{u}
    [        ] fatal: HEAD does not point to a branch
    [  +26 ms] executing: [/home/alt/fvm/versions/2.0.6/] git rev-parse --abbrev-ref HEAD
    [  +18 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
    [        ] HEAD
    [  +42 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
    [   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
    [  +53 ms] executing: /mnt/SSDP/Sdk/android/platform-tools/adb devices -l
    [  +15 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
    [   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
    [  +79 ms] executing: /mnt/SSDP/Sdk/android/platform-tools/adb devices -l
    [  +24 ms] Skipping pub get: version match.
    [  +29 ms] Found plugin another_flushbar at /home/alt/.pub-cache/hosted/pub.dartlang.org/another_flushbar-1.10.13/
    [  +95 ms] Found plugin path_provider at /home/alt/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.28/
    [   +1 ms] Found plugin path_provider_linux at /home/alt/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-0.0.1+2/
    [   +2 ms] Found plugin path_provider_macos at /home/alt/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4+8/
    [   +3 ms] Found plugin path_provider_windows at /home/alt/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-0.0.5/
    [ +128 ms] Found plugin another_flushbar at /home/alt/.pub-cache/hosted/pub.dartlang.org/another_flushbar-1.10.13/
    [  +39 ms] Found plugin path_provider at /home/alt/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.28/
    [   +1 ms] Found plugin path_provider_linux at /home/alt/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-0.0.1+2/
    [        ] Found plugin path_provider_macos at /home/alt/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4+8/
    [   +1 ms] Found plugin path_provider_windows at /home/alt/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-0.0.5/
    [  +36 ms] Generating /mnt/SSDP/Project/Caspian/parsian_otp/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
    [  +95 ms] List of devices attached
    [   +3 ms] List of devices attached
    [  +70 ms] Launching lib/main.dart on Chrome in debug mode...
    [ +120 ms] Updating assets
    [ +132 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
    [   +3 ms] Waiting for connection from debug service on Chrome...
    [   +8 ms] Found plugin another_flushbar at /home/alt/.pub-cache/hosted/pub.dartlang.org/another_flushbar-1.10.13/
    [  +22 ms] Found plugin path_provider at /home/alt/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.28/
    [        ] Found plugin path_provider_linux at /home/alt/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-0.0.1+2/
    [        ] Found plugin path_provider_macos at /home/alt/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4+8/
    [        ] Found plugin path_provider_windows at /home/alt/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-0.0.5/
    [  +25 ms] Found plugin another_flushbar at /home/alt/.pub-cache/hosted/pub.dartlang.org/another_flushbar-1.10.13/
    [  +19 ms] Found plugin path_provider at /home/alt/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.28/
    [        ] Found plugin path_provider_linux at /home/alt/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-0.0.1+2/
    [        ] Found plugin path_provider_macos at /home/alt/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4+8/
    [        ] Found plugin path_provider_windows at /home/alt/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-0.0.5/
    [ +105 ms] <- reset
    [   +7 ms] /home/alt/fvm/versions/2.0.6/bin/cache/dart-sdk/bin/dart --disable-dart-dev /home/alt/fvm/versions/2.0.6/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root /home/alt/fvm/versions/2.0.6/bin/cache/flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill /tmp/flutter_tools.NTKHAG/flutter_tool.DUOFER/app.dill --libraries-spec file:///home/alt/fvm/versions/2.0.6/bin/cache/flutter_web_sdk/libraries.json --packages /mnt/SSDP/Project/Caspian/parsian_otp/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root /tmp/flutter_tools.NTKHAG/flutter_tools.IODTFM --filesystem-scheme org-dartlang-app --initialize-from-dill build/c7922d95bf4a2462b75c84a97c312edb.cache.dill.track.dill --platform file:///home/alt/fvm/versions/2.0.6/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --no-sound-null-safety
    [   +7 ms] <- compile org-dartlang-app:/web_entrypoint.dart
    [+33128 ms] Waiting for connection from debug service on Chrome... (completed in 33.3s)
    [        ] Synced 46.6MB.
    [        ] <- accept
    [        ] Caching compiled dill
    [ +511 ms] Using Google Chrome 97.0.4692.71 
    
    [ +275 ms] [CHROME]:
    [        ] [CHROME]:DevTools listening on ws://127.0.0.1:37211/devtools/browser/970d4a7b-bb48-4e78-8bd9-6c1c416e4eba
    [ +584 ms] DwdsInjector: Received request for entrypoint at http://localhost:44945/main_module.bootstrap.js
    [   +6 ms] MetadataProvider: Loading debug metadata...
    [  +36 ms] MetadataProvider: Loaded debug metadata
    [  +21 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:44945/main_module.bootstrap.js
    [+42537 ms] DwdsInjector: Received request for entrypoint at http://localhost:44945/main_module.bootstrap.js
    [        ] MetadataProvider: Loading debug metadata...
    [  +37 ms] MetadataProvider: Loaded debug metadata
    [   +9 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:44945/main_module.bootstrap.js

flutter doctor:
```
 Flutter (Channel unknown, 2.0.6, on Linux, locale en_US.UTF-8)
    • Flutter version 2.0.6 at /home/alt/fvm/versions/2.0.6
    • Framework revision 1d9032c7e1 (9 months ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /mnt/SSDP/Sdk/android/
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = /mnt/SSDP/Sdk/android
    • ANDROID_SDK_ROOT = /mnt/SSDP/Sdk/android/
    • Java binary at: /mnt/SSDP/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio
    • Android Studio at /mnt/SSDP/android-studio/
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /mnt/SSDP/android-studio/
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.63.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.32.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 97.0.4692.71

• No issues found!
```
I am using fvm

**Comment by maheshmnj** [comment]
Hi @tazik561, Thanks for filing the issue. You seem to be on the older version of flutter, Unfortunately we cannot provide support to older versions. I would advise you to please upgrade to latest `stable 2.8.1` by running `flutter upgrade`. Before you upgrade you may try the following, if you have not made any changes to `yourProject/web` directory since the project was created then you may try deleting `web` directory and recreating it using `flutter create .`

**Comment by tazik561** [comment]
I found my problem. One of my libraries was outdated. And with the increase, it's the version the problem is solved.

**Comment by maheshmnj** [comment]
Thanks for the update, Provided your last response, I feel it's safe to close the issue.
