### ISSUE TITLE
Include "FLUTTER_INSTALL" in PUB_ENVIRONMENT var when running `pub upgrade` on flutter_tools during install

### ISSUE THREAD

**Issue by kevmoo** [flutter/flutter#9668]
We're getting a LOT of hits for this tool in our pub telemetry. It gets run A LOT so it really skews our metrics.

**Comment by kevmoo** [comment]
See https://github.com/flutter/flutter/commit/358e1cd2e171e81067c9728df7508f0e72a76c3f

**Comment by sethladd** [comment]
Thanks! Would you be willing to send us a PR?

**Comment by eseidelGoogle** [comment]
Is this the call in question? https://github.com/flutter/flutter/blob/master/bin/flutter#L84

**Comment by kevmoo** [comment]
> Is this the call in question? https://github.com/flutter/flutter/blob/master/bin/flutter#L84

Yup.

**Comment by kevmoo** [comment]
@eseidelGoogle @sethladd Here's a PR with the "spirit" of the needed changes - https://github.com/flutter/flutter/pull/9670

You **don't** want me writing `bat` files.

We could run w/ this now and fix up later – or have one of your shell ninjas run with it.

Whatever...

**Comment by eseidelGoogle** [comment]
@goderbauer is probably the only person who you can get to write .bat in a reasonable time. :)

Can you help us understand how important this bug is?

**Comment by kevmoo** [comment]
> Can you help us understand how important this bug is?

Well, we really want a accurate/fair view of packages that users are really using.

Lots of folks (it seems) try to install Flutter – so much that one-off packages like `coverage` and `json_rpc_2` are showing up as top-20.

I'm going to write some custom logic to exclude clear flutter installs from the list – but having this "baked in" would make my job easier – and make it easier for us to track truly popular packages.

**Comment by kevmoo** [comment]
Personally, I don't know why this code wouldn't be written mostly in Dart.

Keeping these scripts in sync seems like a huge cost – and the overhead of calling Dart seems small compared to all of the downloading that's going on...
