### ISSUE TITLE
addTimingsCallback return wrong timestamp.

### ISSUE THREAD

**Issue by yeran1212** [flutter/flutter#96699]
when i used addTimingsCallback in a pure flutter app, i printed  vsyncStart, buildStart, buildFinish in FrameTimings. i found timestamp which should be monotonic is repeated. 

https://api.flutter.dev/flutter/scheduler/SchedulerBinding/addTimingsCallback.html
![7D94E093-61A6-41F8-B8AC-EC0FB8294E7B](https://user-images.githubusercontent.com/77652483/149621132-63f0a968-ce10-4279-b5e2-793a052fc5eb.png)

![printScreen](https://user-images.githubusercontent.com/77652483/149621073-dd3e15cc-a2aa-488c-b702-f33b7abea99f.png)

**Comment by maheshmnj** [comment]
Hi @yeran1212, Thanks for filing the issue. You seem to be using a old version of flutter, Could you please try upgrading to `stable 2.8.1` and see if that fixes the issue? If the issue persists please share the updated output of `flutter doctor -v` along with a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) to better address the issue.

Thanks

**Comment by chinmaygarde** [comment]
xref https://github.com/flutter/engine/pull/32283
