### ISSUE TITLE
addTimingsCallback method  return repeated vsync timestamp

### ISSUE THREAD

**Issue by yeran1212** [flutter/flutter#96698]
when used api below,

## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by danagbemava-nc** [comment]
Duplicate of #96699
