### ISSUE TITLE
[MacOS] - Provide error message when accessing String.fromEnvironment as non-const

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#96691]
Recently I added some `--dart-define` values to a Mac OS build. I quickly coded it like this:

```dart
final myValue = String.fromEnvironment("MY_VARIABLE");
```

This resulted in empty values for my various build variables. I was confused why this was happening. There weren't any error messages, just empty values. I decided to build the same project for web and see what happens. When I ran the web version, I got an error complaining about needing to use a const constructor. That's when I realized that apparently I **must** access these environment variables as `const`s:

```dart
const myValue = String.fromEnvironment("MY_VARIABLE");
```

That fixed my issue.

Flutter should provide appropriate error messages on Mac OS and any other platform when these variables are accessed in illegal ways. It's difficult to notice the issue if a developer isn't already aware of it.

Flutter version: Flutter 2.8.0 • channel stable

**Comment by danagbemava-nc** [comment]
Hi @matthew-carroll, I see a similar issue in https://github.com/flutter/flutter/issues/55870. 
Kindly follow up there for more information. 

Closing from here as duplicate. 

If you disagree, kindly leave a comment below and I will reopen. 

Thank you
