### ISSUE TITLE
Changing the border color of the OutlineInputBorder

### ISSUE THREAD

**Issue by latifulmousom** [flutter/flutter#96704]
I'm trying to change the border color of the OutlineInputBorder but tried inumerous ways and failed.

**Comment by ramanjitsingh-hub** [comment]
I found this  in the docs of OutlineInputBorder
`Input border's are decorated with a line whose weight and color are defined
/// by [borderSide]`


And in the box border this 
`[BorderSide], which is used to describe each side of the box.`

In this example, they have shown to change border-color

```dart
/// Container(
///   decoration: const BoxDecoration(
///     border: Border(
///       top: BorderSide(width: 1.0, color: Color(0xFFFFFFFF)),
///       left: BorderSide(width: 1.0, color: Color(0xFFFFFFFF)),
///       right: BorderSide(width: 1.0, color: Color(0xFF000000)),
///       bottom: BorderSide(width: 1.0, color: Color(0xFF000000)),
///     ),
///   ),
///   child: Container(
///     padding: const EdgeInsets.symmetric(horizontal: 20.0, vertical: 2.0),
///     decoration: const BoxDecoration(
///       border: Border(
///         top: BorderSide(width: 1.0, color: Color(0xFFDFDFDF)),
///         left: BorderSide(width: 1.0, color: Color(0xFFDFDFDF)),
///         right: BorderSide(width: 1.0, color: Color(0xFF7F7F7F)),
///         bottom: BorderSide(width: 1.0, color: Color(0xFF7F7F7F)),
///       ),
///       color: Color(0xFFBFBFBF),
///     ),
///     child: const Text(
///       'OK',
///       textAlign: TextAlign.center,
///       style: TextStyle(color: Color(0xFF000000))
///     ),
///   ),
/// )
```


Further, these lines are also included 
```///  * [BoxDecoration], which uses this class to describe its edge decoration.
///  * [BorderSide], which is used to describe each side of the box.
///  * [Theme], from the material layer, which can be queried to obtain appropriate colors
///    to use for borders in a material app, as shown in the "divider" sample above.```

**Comment by danagbemava-nc** [comment]
Hi @latifulmousom, the flutter issue tracker is for tracking issues with flutter. 

If you are having issues with your own code, kindly see any https://flutter.dev/community#community-grid to ask for help with your code. 

Seeing as there are ways to change the color of `OutlinedInputBorder`, this seems like and issue with your code. 

If you do have a legitimate bug to report, kindly provide all the necessary information when you're filing the issue. 

Closing as this seems like an issue with your code. 

Thank you
