### ISSUE TITLE
iOS integration tests with flavor: Unable to determine the executable path for Runner.app

### ISSUE THREAD

**Issue by oligazar** [flutter/flutter#96702]
i'm following the [integration tests documentation](https://github.com/flutter/flutter/tree/master/packages/integration_test#ios-device-testing).I cannot get it working and the reason, I think, is that my app uses flavors, but the example one does not.

So I added the `--flavor` flag to the build command:
```
fvm flutter build ios --flavor devo integration_test/simple_app_test.dart --release
```

The first issue I got on this line
```
xcodebuild -workspace Runner.xcworkspace -scheme Runner -config Flutter/Release.xcconfig -derivedDataPath $output -sdk iphoneos build-for-testing
```
So I replaced `Runner` scheme with `devo`:
```
xcodebuild -workspace Runner.xcworkspace -scheme devo -config Flutter/Release.xcconfig -derivedDataPath $output -sdk iphoneos build-for-testing
```

I got two failures, but the zip file was created:
```
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Firebase.h"
        ^
<porject_path>/ios/Pods/Firebase/CoreOnly/Sources/Firebase.h:15:9: error: 'FirebaseCore/FirebaseCore.h' file not found
#import <FirebaseCore/FirebaseCore.h>
        ^
<poroject_path>/ios/Runner/AppDelegate.swift:3:8: error: could not build Objective-C module 'Firebase'
import Firebase
       ^

** TEST BUILD FAILED **


The following build commands failed:
        CompileSwift normal arm64 <project_path>/ios/Runner/AppDelegate.swift (in target 'Runner' from project 'Runner')
        CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'Runner' from project 'Runner')
(2 failures)
```

Now, when I try to verify if my tests are successful with
```
xcodebuild test-without-building -xctestrun "../build/ios_integ/Build/Products/devo_iphoneos15.2-arm64.xctestrun" -destination id=43F00B06-1B89-4291-8FED-E775C5ADF456
```
I'm getting: `xcodebuild: error: Failed to build workspace temporary with scheme Transient Testing.
        Reason: Cannot test target “RunnerTests” on “iPhone 13 Pro”: Unable to determine the executable path for Runner.app`

So I need assistance in resolving `TEST BUILD FAILED` issue with `error: could not build Objective-C module 'Firebase'`, which in my opinion is the cause of the following `Unable to determine the executable path for Runner.app` issue

**Comment by maheshmnj** [comment]
Hi @oligazar, Thanks for filing the issue. Can you please share a minimal and complete reproducible project along with the output of `flutter doctor -v` to verify?

Thanks
