### ISSUE TITLE
Features on Demand in Flutter

### ISSUE THREAD

**Issue by Insha-Siddiquii** [flutter/flutter#96706]
## Use case

I am working on application with Flutter 2 version. The application has a global reach and have need of payment gateways and other conditional features that are only popular and required in specific regions. In order to reduce the initial application download size, I want to create separate modules for each payment gateway and features types and have them installed on user's device based on their registered locals after the user have installed the based apk/ipa

## Proposal

Looking for a flutter feature that should work as follows:

1. User can download and install features on demand, after they have installed the base apk/ipa of the application
2. The on demand features will only install when certain condition are met. for example region or local 
3. User can request to delete the feature on request from application after the some conditional aspects. In this way application size will be reduce

Attaching some link of Android Dynamic Delivery to get an idea in more detail.

- https://developer.android.com/guide/playcore/feature-delivery
- https://developer.android.com/google/play/publishing/multiple-apks

## End-Request
If the solution or feature are already present as **Deferred Component in Flutter**, please release it into stable channel with more examples and detailed documentation.

**Comment by maheshmnj** [comment]
Hi @Insha-Siddiquii, Thanks for filing the issue. This feature is currently supported by flutter for Android. Please take a look at this documentation https://docs.flutter.dev/perf/deferred-components

**Comment by maheshmnj** [comment]
> What I need to know is that does Feature Deferred Components currently available in stable channel of Flutter? or is it soon to release?

@Insha-Siddiquii, Please try upgrading to `stable 2.8.1` (This was able on master 2.6 back then, rolled to stable) it should work there.

>  Unfortunately I have seen app crashes when I follow the same documentation on Flutter version 2.2.3 stable.

if you see a similar crash on the `stable 2.8.1`, Feel free to file a new issue with all the requested details in the issue template.

Closing as this is neither a bug nor a feature request.

**Comment by Insha-Siddiquii** [comment]
@maheshmnj  thanks for the guide. the deferred component works successfully on stable 2.8.1. unfortunately i have observed some issues after uploading it on playstore. 

You can check a description and details of issue at: [Deferred Loading Placeholder keeps coming](https://github.com/flutter/gallery/issues/588)

It would be much helpful to provide state restoration of deferred component so that it could not show loading behavior each time, after once it installed.

**Comment by maheshmnj** [comment]
Thanks for the update @Insha-Siddiquii, I see you filed the issue in `flutter/gallery` it should be filed in `flutter/flutter` itself.

**Comment by Insha-Siddiquii** [comment]
> Thanks for the update @Insha-Siddiquii, I see you filed the issue in `flutter/gallery` it should be filed in `flutter/flutter` itself.

@maheshmnj  Thanks for reply. Yes, I have filed in  `flutter/flutter` as well. [Please check ](https://github.com/flutter/flutter/issues/97149)

Please let me know the possible way for the resolution.
