### ISSUE TITLE
bug of date difference inDays 

### ISSUE THREAD

**Issue by nobodyyu** [flutter/flutter#96701]
<summary>Code sample</summary>

test('Date', () {
    DateFormat formatter = DateFormat('yyyy/MM/dd');
    String start = "1975/02/11";
    String end = "1975/04/01";
    String end2 = "1975/04/02";

    print(formatter
        .parse(end)
        .difference(formatter.parse(start))
        .inDays
        .toString());
    print(formatter
        .parse(end2)
        .difference(formatter.parse(start))
        .inDays
        .toString());
  });

**Expected results:** 
49
50

**Actual results:** 
49
49

--
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6.1 20G224 darwin-x64,
    locale zh-Hant)
[✓] Android toolchain - develop for Android devices (Android SDK version
    31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Community Edition (version 2021.2.3)
[✓] VS Code (version 1.63.2)
[✓] Connected device (3 available)

• No issues found!

**Comment by nobodyyu** [comment]
there are 23 hours between 1975/4/1 and 1975/4/2

**Comment by stuartmorgan** [comment]
In the future please file bugs about Dart APIs in the Dart issue tracker, not here.

This is not a bug however; please read the `DateTime` class documentation, which explicitly covers this
