### ISSUE TITLE
package:flutter/src/rendering/sliver_fixed_extent_list.dart

### ISSUE THREAD

**Issue by Artfulbd** [flutter/flutter#96715]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by nt4f04uNd** [comment]
Please do not file empty issues. I'm assuming however that you are facing https://github.com/flutter/flutter/issues/95101, which is fixed on master.
