### ISSUE TITLE
App not building after upgrading to latest flutter 2.9 in master

### ISSUE THREAD

**Issue by viratshukla** [flutter/flutter#96711]
After upgrading from Channel master, 2.6.0-12.0.pre.826 to Channel master, 2.9.0-1.0.pre.384,
facing this issue, once run and trying to install the app

Launching lib/main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
../../../flutter/.pub-cache/hosted/pub.dartlang.org/platform-3.0.2/lib/src/interface/local_platform.dart:46:19: Error: Member not found: 'packageRoot'.
      io.Platform.packageRoot; // ignore: deprecated_member_use
                  ^^^^^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script '/Users/xxx/Development/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1102

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/xxx/Development/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 23s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by viratshukla** [comment]
flutter doctor    
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 2.9.0-1.0.pre.384, on macOS 12.0.1 21A559 darwin-x64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[!] Android Studio
    ✗ Unable to find bundled Java version.
[!] Android Studio
    ✗ Unable to find bundled Java version.
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Community Edition (version 2021.2.3)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 2 categories.

**Comment by nt4f04uNd** [comment]
This is an issue with the [platform](https://pub.dev/packages/platform) package, which was fixed in its 3.1.0 version and likely is transitive for you through some other package, which didn't update the version yet. Can you attach an output of `flutter pub deps`, so we can see what this package is?

In the meantime you can fix it by overriding the version in your `pubspec.yaml` like so

```yaml
dependency_overrides:
  platform: ^3.1.0
```

**Comment by stuartmorgan** [comment]
As noted this is an issue with needing to update one or more of your dependencies.

Closing as this is not a Flutter bug.

**Comment by maks** [comment]
@stuartmorgan one of the transitive deps that is causing this for me is the [current version of `path_provider`](https://github.com/flutter/plugins/blob/master/packages/path_provider/path_provider_platform_interface/pubspec.yaml), whose bugs I believe are supposed to be filled in this repo. Or should a new issue be opened for that?

**Comment by stuartmorgan** [comment]
@maks If `path_provider` were pinning a broken version of `platform` this would be the place to report that, but that's not the case. No change to `path_provider` is needed here.

Re-reading the original report, I'm not sure why @nt4f04uNd mentioned waiting for packages to update and suggested using overrides (a method of last resort) when there's no evidence in the report that either is necessary. Unless some dependency is pinning 3.0.2 (extremely unlikely), all that's needed is to run a package update on the app.

**Comment by nt4f04uNd** [comment]
> Re-reading the original report, I'm not sure why @nt4f04uNd mentioned waiting for packages to update and suggested using overrides

I'm sorry, I forgot about this command, and that 3.0.2 can be upgraded to 3.1.0 with it

**Comment by maks** [comment]
@stuartmorgan my apologies, I saw a reference to path_provider having `platform: 3.0.0` (pinned to 3.0.0) in a comment in a [SO thread](https://stackoverflow.com/questions/70363918/error-member-not-found-packageroot-how-to-solve-ignore-deprecated-member-u/70757512#comment125088312_70757512) and didn't notice that the commenter had got the dependency version spec string wrong and that its actually `platform: ^3.0.0`. 
I've left a comment on that SO answer to try to prevent future readers making the same mistake.
