### ISSUE TITLE
Optimise Container(color: ...)

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#9672]
Based on my experience porting app code after #9648, it seems to be very common to have a `Container `with just a `color`. Right now we do a lot of work to handle that case. It seems like we could special-case that particular case to be much more efficient.

**Comment by HansMuller** [comment]
Or a BackgroundColor widget?

**Comment by Hixie** [comment]
I meant a Container with a decoration that's just a color. The Container itself typically has other properties like width/height. But yeah, Container could use a widget like "ColoredBox" or something to handle this case.

**Comment by HansMuller** [comment]
Similarly, if I just want to add a background color, I could use `ColoredBox(color: color, child: ...)`, instead of   Container.

**Comment by liyuqian** [comment]
Is this still an active issue? Do we have a benchmark or metric that tracks this? @Hixie @HansMuller

**Comment by Hixie** [comment]
Nothing has changed in this area since I filed it. We don't have any benchmarks for specifically this case though I wouldn't be surprised if several of our benchmarks do exercise the relevant code.

**Comment by dnfield** [comment]
I had started this at one point and got caught up in trying to make it do more than it probably should (e.g. gradients).

A quick run of complex layout scroll perf suggests that this makes the benchmark faster (that app uses some `Container` that have `color` specified).

I'll put something up simple for this. If we want to support gradients it shouldn't be hard, or it shouldn't be too hard for someone else to just make a widget based on my simple one to do that.
