### ISSUE TITLE
Does flutter have a callback when the phone switches to the dark theme?

### ISSUE THREAD

**Issue by a250059653** [flutter/flutter#96728]
Does flutter have a callback when the phone switches to the dark theme?

**Comment by a250059653** [comment]
How does flutter monitor when the phone is switching the dark theme?

**Comment by adityathakurxd** [comment]
There's the [themeMode property](https://api.flutter.dev/flutter/material/MaterialApp/themeMode.html) that you can set to the system to use either the light or dark theme based on what the user has selected in the system settings.

``` dart
return MaterialApp(
      theme: ThemeData.from(
        colorScheme: ColorScheme.light(
          primary: Colors.deepPurple[600]!,
          secondary: Colors.red[600]!,
        ),
      ),
      darkTheme: ThemeData.from(
        colorScheme: ColorScheme.dark(
          primary: Colors.deepPurple[200]!,
          secondary: Colors.red[200]!,
        ),
      ),
      themeMode: ThemeMode.system,
      home: MyHomePage(),
    );
 ```
It'll use the Light or Dark theme depending on system settings.

**Comment by a250059653** [comment]
> There's the [themeMode property](https://api.flutter.dev/flutter/material/MaterialApp/themeMode.html) that you can set to the system to use either the light or dark theme based on what the user has selected in the system settings.
> 
> ```dart
> return MaterialApp(
>       theme: ThemeData.from(
>         colorScheme: ColorScheme.light(
>           primary: Colors.deepPurple[600]!,
>           secondary: Colors.red[600]!,
>         ),
>       ),
>       darkTheme: ThemeData.from(
>         colorScheme: ColorScheme.dark(
>           primary: Colors.deepPurple[200]!,
>           secondary: Colors.red[200]!,
>         ),
>       ),
>       themeMode: ThemeMode.system,
>       home: MyHomePage(),
>     );
> ```
> 
> It'll use the Light or Dark theme depending on system settings.

Thank you, is there a way to monitor the modified phone theme?

**Comment by adityathakurxd** [comment]
There is this approach for when the user changes the OS theme the app will listen and then change the theme according to it. You can read about it [here](https://thiagoevoa.medium.com/change-flutter-app-theme-according-to-the-system-theme-mode-c4a63d05128f).

**Comment by a250059653** [comment]
> There is this approach for when the user changes the OS theme the app will listen and then change the theme according to it. You can read about it [here](https://thiagoevoa.medium.com/change-flutter-app-theme-according-to-the-system-theme-mode-c4a63d05128f).

Thanks, can you provide a demo?

**Comment by ramanjitsingh-hub** [comment]
You can visit this site to learn more about the dark theme  [dark theme](https://www.geeksforgeeks.org/flutter-dark-theme/) or check [flutter docs ](https://docs.flutter.dev/cookbook/design/themes)

**Comment by maheshmnj** [comment]
Hi @a250059653, Thanks for filing the issue. Please refer to the [ThemeMode docs](https://api.flutter.dev/flutter/material/MaterialApp/themeMode.html) which specifies when the app switches between Dark and Light Theme.

> Determines which theme will be used by the application if both theme and darkTheme are provided.

> If set to ThemeMode.system, the choice of which theme to use will be based on the user's system preferences. If the MediaQuery.platformBrightnessOf is Brightness.light, theme will be used. If it is Brightness.dark, darkTheme will be used (unless it is null, in which case theme will be used.

*Please check the below code sample which notifies and changes the app theme on Systems Theme change*

<details>
<summary>minimal sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      darkTheme: ThemeData.dark(),
      themeMode: ThemeMode.system,
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    var window = WidgetsBinding.instance!.window;

    // This callback is called every time the brightness changes.
    window.onPlatformBrightnessChanged = (() {
      var brightness = window.platformBrightness;
      print('theme changed');
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(appBar: AppBar(), body: Container());
  }
}

```
</details>

If you need further help, Please try reaching out one of the forums at https://flutter.dev/community

 Closing as this is neither a bug nor a feature request.
