### ISSUE TITLE
[integration test] Application launch for 'package' did not return a valid pid nor a launch error. No such process

### ISSUE THREAD

**Issue by oligazar** [flutter/flutter#96720]
I need a help in making my integration tests work with Firebase Test Lab. But I'm getting a few errors when following steps from official iOS setup [guide](https://github.com/flutter/flutter/tree/master/packages/integration_test#ios-device-testing) 

## Steps to Reproduce

1. Follow [integration testing iOS setup guide](https://github.com/flutter/flutter/tree/master/packages/integration_test#ios-device-testing)
2. on step `xcodebuild -workspace Runner.xcworkspace -scheme <flavor_name>  -derivedDataPath $output -sdk iphoneos build-for-testing` I replaced Runner with my flavor name, and removed `-config Flutter/Release.xcconfig`, because when I used it I got `'FirebaseCore/FirebaseCore.h' file not found` error (more details [here](https://github.com/flutter/flutter/issues/96702)).
3. Then I execute `xcodebuild test-without-building -xctestrun "build/ios_integ/Build/Products/<flavor_name>_iphoneos15.2-arm64.xctestrun" -destination id=<device_id>`
**Expected results:**  All tests should pass

**Actual results:** 
The output differs depending on the device target.
I execute `fvm flutter build ios --flavor devo integration_test/simple_app_test.dart --release`
In case I use `--release` option, and then try to run tests on real device, I get 
```
Cannot create a FlutterEngine instance in debug mode without Flutter tooling or Xcode.

To launch in debug mode in iOS 14+, run flutter run from Flutter tools, run from an IDE with a Flutter IDE plugin or run the iOS project from Xcode.
Alternatively profile and release mode apps can be launched from the home screen.
```
If then I try the same command with `--simulator` option: `flutter build ios --flavor devo integration_test/simple_app_test.dart --simulator`, then I get following error:
```
Testing failed:
        RunnerTests:
                Runner encountered an error (Failed to install or launch the test runner. If you believe this error represents a bug, please attach the result bundle at /Users/oleksa/Library/Developer/Xcode/DerivedData/temporary-gmofqwmswzqnrcghqtthblxclstu/Logs/Test/Test-Transient Testing-2022.01.16_21-49-20-+0200.xcresult. (Underlying Error: Application launch for '<app_id>' did not return a valid pid nor a launch error. No such process))

** TEST EXECUTE FAILED **

```

Any suggestions are highly appreciated!

**Comment by danagbemava-nc** [comment]
Hi @oligazar, thanks for filing the issue. 

Please provide the output of `flutter doctor -v` as well as the verbose logs for the commands that you run. 

Can you also provide how you configured your flavors? (Screenshots might help in this case)

Thank you

**Comment by oligazar** [comment]
Hi @danagbemava-nc, thanks for reply. Here are details you've asked
<details>
  <summary>flutter doctor -v</summary>
    
    [✓] Flutter (Channel stable, 2.8.0, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.8.0 at /Users/oleksa/Development/flutter_sdk
    • Upstream repository [https://github.com/flutter/flutter.git](https://github.com/flutter/flutter.git)
    • Framework revision cf44000065 (6 weeks ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0
    
    [✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/oleksa/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.
    
    [✓] Xcode - develop for iOS and macOS (Xcode 13.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2
    
    [✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
    
    [✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
    🔨 [https://plugins.jetbrains.com/plugin/9212-flutter](https://plugins.jetbrains.com/plugin/9212-flutter)
    • Dart plugin can be installed from:
    🔨 [https://plugins.jetbrains.com/plugin/6351-dart](https://plugins.jetbrains.com/plugin/6351-dart)
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    
    [✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0
    
    [✓] Connected device (2 available)
    • iPhone 13 Pro (mobile) • 43F00B06-1B89-4291-8FED-E775C5ADF456 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2
    (simulator)
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 97.0.4692.71
    
    - No issues found!
   </details>

> flutter build ios --flavor devo integration_test/simple_app_test.dart --release -v

[FlutterBuildIosVerbose.txt](https://github.com/flutter/flutter/files/7884511/FlutterBuildIosVerbose.txt)

This one (with `-config`) fails:
> xcodebuild -workspace Runner.xcworkspace -scheme devo -config Flutter/Release.xcconfig -derivedDataPath "../build/ios_integ" -sdk iphoneos build-for-testing -verbose

[XcodebuildReleaseVerbose.txt](https://github.com/flutter/flutter/files/7884526/XcodebuildReleaseVerbose.txt)

>zip -r "ios_tests.zip" "Release-devo-iphoneos" "devo_iphoneos15.2-arm64.xctestrun"

[ZipReleaseVerbose.txt](https://github.com/flutter/flutter/files/7884563/ZipReleaseVerbose.txt)

This one (without `-config`) succeeds:
> xcodebuild -workspace Runner.xcworkspace -scheme devo -derivedDataPath "../build/ios_integ" -sdk iphoneos build-for-testing -verbose

[XcodebuildReleaseNoConfigVerbose.txt](https://github.com/flutter/flutter/files/7884537/XcodebuildReleaseNoConfigVerbose.txt)

But then when I run tests on real device I'm getting 

> Cannot create a FlutterEngine instance in debug mode without Flutter tooling or Xcode. To launch in debug mode in iOS 14+, run flutter run from Flutter tools, run from an IDE with a Flutter IDE plugin or run the iOS project from Xcode. Alternatively profile and release mode apps can be launched from the home screen.

> xcodebuild test-without-building -xctestrun "build/ios_integ/Build/Products/devo_iphoneos15.2-arm64.xctestrun" -destination id=<device_id>

[XcodeTestNoConfig.txt](https://github.com/flutter/flutter/files/7884579/XcodeTestNoConfig.txt)

**Comment by oligazar** [comment]
I was able to run test on a simulator though.
This is what worked for me:
```
output="../build/ios_integ"
product="build/ios_integ/Build/Products"
dev_target="15.2"

flutter build ios --flavor devo integration_test/simple_app_test.dart --debug --simulator

pushd ios
# xcodebuild -workspace Runner.xcworkspace -scheme devo -config Flutter/Debug.xcconfig -derivedDataPath $output -sdk iphonesimulator build-for-testing
xcodebuild -workspace Runner.xcworkspace -scheme devo -derivedDataPath $output -sdk iphonesimulator build-for-testing
popd

pushd $product
zip -r "ios_tests.zip" "Debug-devo-iphonesimulator" "devo_iphonesimulator$dev_target-arm64-x86_64.xctestrun"
popd
```
After that `xcodebuild test-without-building -xctestrun "build/ios_integ/Build/Products/devo_iphonesimulator15.2-arm64-x86_64.xctestrun" -destination id=<simulator_id>` succeeds.

Note, that I don’t use `-config Flutter/Debug.xcconfig` in `xcodebuild` command, because with it (for simulator) I get
> Failed to package <path>/<app_name>.
Command PhaseScriptExecution failed with a nonzero exit code
 ** TEST BUILD FAILED **
The following build commands failed:
        PhaseScriptExecution Run\ Script <path>/<project_name>/build/ios_integ/Build/Intermediates.noindex/Runner.build/Release-devo-iphonesimulator/Runner.build/Script-9740EEB61CF901F6004384FC.sh (in target 'Runner' from project 'Runner')

I'll add config files here
<details>
  <summary>Debug.xcconfig</summary>
#include "Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig"

#include "Generated.xcconfig"
</details>

<details>
  <summary>Generated.xcconfig</summary>
FLUTTER_ROOT=/Users/oleksa/fvm/versions/2.8.0
FLUTTER_APPLICATION_PATH=/Users/oleksa/Development/flutter/Memo/memo-flutter
COCOAPODS_PARALLEL_CODE_SIGN=true
FLUTTER_TARGET=/var/folders/tm/s0lcmjwn08b37d8d7c59j_sc0000gn/T/flutter_tools.q9iByT/flutter_test_listener.gY86ef/listener.dart
FLUTTER_BUILD_DIR=build
FLUTTER_BUILD_NAME=1.0.0
FLUTTER_BUILD_NUMBER=1
EXCLUDED_ARCHS[sdk=iphonesimulator*]=i386
DART_DEFINES=TUVNT19MT0NBTD10cnVl,TUVNT19BUFBfRU5WPWRldg==,TUVNT19BUElfUE9SVD03MDcw,TUVNT19BUElfUE9SVF9XRUI9NzA3MA==,TUVNT19BUElfVVJMPTAuMC4wLjA=,TUVNT19XRUJfQVBJX1VSTD0wLjAuMC4w,RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ==,SU5URUdSQVRJT05fVEVTVF9TSE9VTERfUkVQT1JUX1JFU1VMVFNfVE9fTkFUSVZFPWZhbHNl
DART_OBFUSCATION=false
TRACK_WIDGET_CREATION=true
TREE_SHAKE_ICONS=false
PACKAGE_CONFIG=/Users/oleksa/Development/flutter/Memo/memo-flutter/.dart_tool/package_config.json
</details>

In this regard I have a couple of questions

1. Why build fails with the generated config files?
2. It seems like `dev_tagrget` number is forced somehow, but I don’t know how. Is it possible to configure it?

**Comment by oligazar** [comment]
I tried uploading zip file created on the last step (without config) to Firebase TestLab and there I'm getting "Upload invalid: uploaded zip files must contain a single .xctestrun file and the contents of the DerivedData/Build/Products directory."

**Comment by oligazar** [comment]
I've found working configuration. I'll leave it here in case it helps somebody. 
```
output="../build/ios_integ"
product="build/ios_integ/Build/Products"
dev_target="12.0"

fvm flutter build ios --flavor <flavor_name> integration_test/simple_app_test.dart --release

pushd ios
xcodebuild -workspace Runner.xcworkspace -scheme <flavor_name> -config Release-<flavor_name> -derivedDataPath $output -sdk iphoneos build-for-testing
popd

pushd $product
zip -r "ios_tests.zip" "Release-<flavor_name>-iphoneos" "<flavor_name>_iphoneos$dev_target-arm64.xctestrun"
popd
```

**Comment by danagbemava-nc** [comment]
Hi @oligazar, is it safe to assume that your issue has been solved?
