### ISSUE TITLE
Url launcher could not launch url starting with https://192.168.

### ISSUE THREAD

**Issue by Joel7jones** [flutter/flutter#96734]
Hi Flutter team actually I was trying to implement url launcher with launch url starting with 192.168. but I was facing an exception like couldn't launch url is there any possibility to make it work below is my code.

```
urlLauncher(String url) async {
    if (await canLaunch(url)) {
      await launch(url, forceWebView: true, enableJavaScript: true);
    } else {
      throw 'Could not launch $url';
    }
  }
```

**Comment by darshankawar** [comment]
@Joel7jones 
Your question is better suited for support channels like StackOverflow so please ask the same there.
Closing from here. If you disagree or think there's a genuine bug in url launcher, then write in comments and I'll reopen it.
