### ISSUE TITLE
[tool_crash] ProcessException: No such file or directory Command: /home/christophe/flutter_sdk/flutter/bin/cache/dart-sdk/bin/pub, OS error code: 2

### ISSUE THREAD

**Issue by Christophenkoa** [flutter/flutter#96744]
## Command
```
flutter doctor
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: No such file or directory Command: /home/christophe/flutter_sdk/flutter/bin/cache/dart-sdk/bin/pub, OS error code: 2
```
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:390:33)
#1      Process.start (dart:io-patch/process_patch.dart:36:20)
#2      Lo

**Comment by darshankawar** [comment]
@Christophenkoa 
Not sure which flutter version you are on, but if you are not on latest version, you should try to upgrade which should resolve this exception. See this similar issue for your reference:  https://github.com/flutter/flutter/issues/91287
Closing this as a duplicate. If you disagree or still getting this exception after upgrade, write in comments and I'll reopen.
