### ISSUE TITLE
DOC: Improve Navigation Bar Docs

### ISSUE THREAD

**Issue by 2002Bishwajeet** [flutter/flutter#96750]
In **Material 3**, Bottom Navigation bar has been renamed to [Navigation Bar](https://m3.material.io/components/navigation-bar/overview)

Now, I could see that this widget has been implemented in Flutter 2.5 but the doc seems to be less informative about [it](https://api.flutter.dev/flutter/material/NavigationBar-class.html)

If we really compare between [Bottom Navigation Bar](https://api.flutter.dev/flutter/material/BottomNavigationBar-class.html) and [Navigation Bar](https://api.flutter.dev/flutter/material/NavigationBar-class.html) there is a lot of difference in them. Say for e.g there isn't any dart pad code to run and test on the browser itself. Also it doesn't mention about any assertions needed to follow or such.

 [Navigation Destination](https://api.flutter.dev/flutter/material/NavigationDestination-class.html) Widget needs a little refactoring too. I mean it needs a little more context about what it does

## Proposal

Add Dart Pad to the Navigation Bar docs so there must a live example of how this is actually different from the Material 2 Bottom Navigation Bar and maybe test some few properties and such. 
Add necessary assertions or by default styling properties of this widget

Also on further exploring finding related issues to Material 3, I found a generic issue #91605 related to the context. So mentioning it here as this is related a bit to it

**Comment by HansMuller** [comment]
CC @darrenaustin @rami-a @guidezpl

**Comment by Piinks** [comment]
Fixed in #97046
