### ISSUE TITLE
[IOS] Add optional boldTextOverride property for Text Widget

### ISSUE THREAD

**Issue by virskor** [flutter/flutter#96758]
## Details
Hope add boldTextOverride for Text widget, we do  not need boldTextOverride for text, but this property directly use boldTextOverride(context), can it be optional ?

```dart
  @override
  Widget build(BuildContext context) {
    final DefaultTextStyle defaultTextStyle = DefaultTextStyle.of(context);
    TextStyle? effectiveTextStyle = style;
    if (style == null || style!.inherit)
      effectiveTextStyle = defaultTextStyle.style.merge(style);
    if (MediaQuery.boldTextOverride(context))
      effectiveTextStyle = effectiveTextStyle!.merge(const TextStyle(fontWeight: FontWeight.bold));
```

[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale zh-Hans)
    • Flutter version 2.8.1 at /Users/virs/fvm/versions/2.8.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (5 周前), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/virs/Library/Android/sdk
    • Platform android-32, build-tools 30.0.3
    • ANDROID_HOME = /Users/virs/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (3 available)
    • iPhone (mobile) • 00008030-001231D80231802E • ios            • iOS 15.1 19B74
    • macOS (desktop) • macos                     • darwin-x64     • macOS 12.1 21C52 darwin-x64
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 97.0.4692.71

• No issues found!

**Comment by maheshmnj** [comment]
Hi @virskor, Could you please share a minimal and complete reproducible code sample explaining the issue.

Thanks

**Comment by virskor** [comment]
hi @maheshmnj  the code snipet above is from Flutter lib/src/widgets/text.dart and line 525.
```dart
if (MediaQuery.boldTextOverride(context))
```

i think this condition should be optional, because when IOS devices has set display as bold text, whole Flutter app will be rendered as bold font, Use MediaQuery(boldText:false) can help but not a perfect way.

Thanks

**Comment by virskor** [comment]
```dart
final Text helloworld = const Text("helloWorld", boldTextOverride: false);
```

like this.

**Comment by maheshmnj** [comment]
Thanks for the info, Currently when bold Text is enabled under accessibility in ios, All text in all the apps (including flutter) is set to bold. Users would want to override this behavior for certain Text widgets

Labeling this as a valid feature request.

**Comment by goderbauer** [comment]
You could just wrap the text in a custom MediaQuery that sets `boldText` to false.

**Comment by maheshmnj** [comment]
@virskor,  I can confirm the above solution provided works, Please take a look at the below code sample for reference.

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const MediaQuery(
              data: MediaQueryData(boldText: false),
              child: Text(
                'You have pushed the button this many times:',
              ),
            ),
            MediaQuery(
              data: const MediaQueryData(boldText: false),
              child: Text(
                '$_counter',
                style: Theme.of(context).textTheme.headline4,
              ),
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

```
</details>
 
 Closing as the solution has been provided.

**Comment by virskor** [comment]
too much mediaquery wrapper makes widget tree heavy

**Comment by maheshmnj** [comment]
You don't necessarily have to wrap each widget in MediaQuery you could also wrap the parent, e.g in the above code sample you could just wrap the body of the scaffold in MediaQuery and yet have the same result with a single MediaQuery.
