### ISSUE TITLE
Make `prefetchDefaultFontManager` on Android happen in parallel with loading of the Dart isolate

### ISSUE THREAD

**Issue by jiahaog** [flutter/flutter#96767]
[`prefetchDefaultFontManager`](https://github.com/flutter/engine/blob/ff468445bc493d1d5e054f12f9359a8904d3039c/shell/platform/android/io/flutter/embedding/engine/loader/FlutterLoader.java#L178) happens on a background thread during startup on Android. It looks like [`ShellSetupUISubsystem`](https://github.com/flutter/engine/blob/bdbd075d6233253f143bc844e981e90d82ae0d3c/shell/common/shell.cc#L274) / [`ShellSetupIOSubsystem`](https://github.com/flutter/engine/blob/bdbd075d6233253f143bc844e981e90d82ae0d3c/shell/common/shell.cc#L241) is blocked on the completion of this from the trace, though I couldn't figure out where in the engine is it blocked at. 

Trace below is collected from a Pixel 4, though I've seen it take 50 - 100ms on an Android Go device.

![image](https://user-images.githubusercontent.com/7111741/149920527-c6e7dfd8-e25b-4d9d-bfbe-e87939001cba.png)

Is it feasible to make `prefetchDefaultFontManager` non-blocking so starting the Dart isolate can happen at the same time?

#### Related:

- https://github.com/flutter/flutter/issues/91045
- https://github.com/flutter/engine/pull/18225

cc @dnfield @jason-simmons @xster

**Comment by dnfield** [comment]
I'm not sure what happened here, but I'm pretty sure this is not meant to be blocking and I've seen it run concurrently in the past...

**Comment by dnfield** [comment]
It looks like it depends on what executor service is passed in. Is `customer: money` overriding this?

**Comment by xster** [comment]
Does this issue have an internal bug?

**Comment by jiahaog** [comment]
Sorry, it looks like it might be a coincidence that the `prefetchDefaultFontManager` looks like its blocking. I'll try to get more data.

**Comment by jiahaog** [comment]
I was mistaken here, `prefetchDefaultFontManager` is not blocking setting up of the UI / IO subsystems. Apologies for the noise!
