### ISSUE TITLE
Create `PopScope` widget to detect the user leaves the current page

### ISSUE THREAD

**Issue by takassh** [flutter/flutter#96776]
## Use case
We often use `WillPopScope` widget so that we detect the user leaves the current page like this https://stackoverflow.com/questions/53038560/detect-if-the-user-leaves-the-current-page-in-flutter . However, somehow the widget have a bug https://github.com/flutter/flutter/issues/14203, and that usecase is not expected, according to the document below

> Registers a callback to veto attempts by the user to dismiss the enclosing ModalRoute.

**We just want to detect it on the pushed `ModalRoute` widget side without the veto.**

## Proposal

<details>
<summary>PopScope widget like WillPopScope widget</summary>

```
import 'package:flutter/widgets.dart';

class PopScope extends StatefulWidget {
  const PopScope({
    Key? key,
    required this.child,
    required this.onPop,
  })  : assert(child != null),
        super(key: key);

  final Widget child;

  final VoidCallback? onPop;

  @override
  State<PopScope> createState() => _PopScopeState();
}

class _PopScopeState extends State<PopScope> {
  ModalRoute<dynamic>? _route;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    if (widget.onPop != null) {
      _route?.removeScopedPopCallback(widget.onPop!);
    }
    _route = ModalRoute.of(context);
    if (widget.onPop != null) {
      _route?.addScopedPopCallback(widget.onPop!);
    }
  }

  @override
  void didUpdateWidget(PopScope oldWidget) {
    super.didUpdateWidget(oldWidget);
    assert(_route == ModalRoute.of(context));
    if (widget.onPop != oldWidget.onPop && _route != null) {
      if (oldWidget.onPop != null) {
        _route!.removeScopedPopCallback(oldWidget.onPop!);
      }
      if (widget.onPop != null) {
        _route!.addScopedPopCallback(widget.onPop!);
      }
    }
  }

  @override
  void dispose() {
    if (widget.onPop != null) {
      _route?.removeScopedPopCallback(widget.onPop!);
    }
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => widget.child;
}

```

</details>

**Comment by darshankawar** [comment]
@takassh 
Can you provide your use case in which `WillPopScope` doesn't work as expected ?

**Comment by takassh** [comment]
@darshankawar 

1. We can't swipe to go back on iOS.
2. We can't detect it if we use `pop()` before

```
WillPopScope(
      onWillPop: () {
        return Future.value(true);
      },
      child: Scaffold(...
```

**Comment by takassh** [comment]
I created a draft PR
https://github.com/flutter/flutter/pull/96858

**Comment by darshankawar** [comment]
@takassh 
Check this SO answer and see if it helps to resolve your case. https://stackoverflow.com/a/66227393

**Comment by takassh** [comment]
@darshankawar 
Oh... It looks great. it helps me.
Sorry for inconvenience.

BTW, since we often use that widget, it is good that flutter provides the widget officially.
What do you think?

**Comment by darshankawar** [comment]
Glad to know the link helped.
Closing this as resolved.
