### ISSUE TITLE
problem in nested for loop

### ISSUE THREAD

**Issue by gitman-2021** [flutter/flutter#96771]
Hello,
Im a flutter beginner, actually to the whole Software development domain,

So, I wanted to create a 4x2 grid,
Specifically with for loops, as to learn flutter, inside-out

The code below is intended to create 8 boxes in a grid of 4 rows and 2 columns, changing to a different row, at j==2, but its not happening, it continues to build the container in the first row, even after reaching j==0,

Also, may i get to know that how can i create block-of-code for ```for```, as done in other languages like ```for(...) {...}```, Altough i have already done something similar using ```for(...) ...[]```, but its merely a dumb copy-paste from [stackoverflow](https://stackoverflow.com/questions/56919966/creating-widgets-inside-nested-for-loop), [from](https://www.google.com/search?q=flutter+create+widget+for+loop+nesting),

```
import 'package:flutter/material.dart';
void main() {
  runApp(
    MaterialApp(
      home: Scaffold(
        body: Row(
          children: <Widget>[
            for (int i = 0; i < 4; i++) ...[
              Row(
                children: [
                  for (int j = 0; j < 2; j++) ...[
                    Column(
                      children: [
                        Container(
                          child: Row(
                            children: [
                              Column(
                                children: [
                                  Text(i.toString()),
                                  Text(j.toString()),
                                ],
                              ),
                              const Icon(Icons.keyboard_arrow_right_sharp),
                            ],
                          ),
                          margin: const EdgeInsets.all(5.0),
                          padding: const EdgeInsets.all(5.0),
                          decoration: BoxDecoration(
                            border: Border.all(
                              color: Colors.black,
                            ),
                          ),
                        ),
                      ],
                    ),
                  ]
                ],
              ),
            ]
          ],
        ),
      ),
    ),
  );
}
```

**Comment by danagbemava-nc** [comment]
Hi @gitman-2021, this seems like a query for one of the communities listed in https://flutter.dev/community#community-grid.

Kindly visit any of the communities listed on there so they can help you out with this. 

Closing as this seems like a request for assistance with personal code.

Thank you
