### ISSUE TITLE
Input method focus is lost when multiple edit boxes exist

### ISSUE THREAD

**Issue by liangweihao** [flutter/flutter#96772]
If there is more than one edit box on the current page, the focus is fine the first time you select it, but if you switch back and forth from one edit box to another, the one that already has the focus cannot get the focus again.
如果当前页面存在多个编辑框，第一次选中的时候焦点没有问题，但是如果在不同的编辑框来回切换就会导致之前已经获取过焦点的编辑框不能再次获取焦点。
The problems I found through the source code are as follows。

`editable_text.dart`  -》 `_formatAndSetValue` 
The source code:

```dart
 if (selectionChanged ||
        (userInteraction &&
        (cause == SelectionChangedCause.longPress ||
         cause == SelectionChangedCause.keyboard))) {
      _handleSelectionChanged(_value.selection, cause);
    }
```

Fixing code：

```dart
 if (selectionChanged ||
        (userInteraction &&
        (cause == SelectionChangedCause.longPress ||
        cause == SelectionChangedCause.tap||
         cause == SelectionChangedCause.keyboard))) {
      _handleSelectionChanged(_value.selection, cause);
    }
```

After my tests, the fixed code is ok, but I need the boss to confirm the problem。

**Comment by liangweihao** [comment]
@engine-flutter-autoroll

**Comment by danagbemava-nc** [comment]
Hi @liangweihao, thanks for reporting this. 

Please provide a complete minimal reproducible code sample with concrete steps to reproduce as well as the output of `flutter doctor -v` so that we may verify this.

Thank you

**Comment by liangweihao** [comment]
class SettingBodyFragment extends StatelessWidget {
  const SettingBodyFragment({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        const Align(
          child: Padding(
            padding: EdgeInsets.all(16.0),
            child: Text(
              '上传下载设置',
              style: TextStyle(
                fontWeight: FontWeight.bold,
                fontSize: 18,
                color: Colors.blue,
              ),
              textAlign: TextAlign.left,
            ),
          ),
          alignment: Alignment.centerLeft,
        ),
        Divider(
          endIndent: 16,
          height: 1,
          color: Colors.grey[400],
        ), // 分割线
        const SettingItemWidget(
          title: '最大上传任务数:',
          content: '3',
        ),
        const SettingItemWidget(
          title: '最大下载任务数:',
          content: '1',
        ),
        const SettingItemWidget(
          title: '超时时间(ms):',
          content: '60000',
        ),
        const SettingItemWidget(
          title: '分片大小(M):',
          content: '10',
        ),
        const SettingItemWidget(
          title: '并发分片下载数:',
          content: '5',
        ),
        const SettingItemWidget(
          title: '重试次数:',
          content: '5',
        ),
      ],
      mainAxisAlignment: MainAxisAlignment.start,
    );
  }
}
/ /设置的条目
class SettingItemWidget extends StatelessWidget {
  const SettingItemWidget(
      {Key? key, required this.title, required this.content})
      : super(key: key);
  final String title;
  final String content;
  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 8, horizontal: 20),
      child: Row(
        children: [
          Text(title + ""),
          Flexible(
            child: DecoratedBox(
              decoration: BoxDecoration(
                border: Border(
                  top: BorderSide(color: Colors.grey.shade400),
                  left: BorderSide(color: Colors.grey.shade400),
                  right: BorderSide(color: Colors.grey.shade400),
                  bottom: BorderSide(color: Colors.grey.shade400),
                ),
                borderRadius: BorderRadius.circular(5),
              ),
              child: Padding(
                child: getEditText(context, content),
                padding: const EdgeInsets.all(8),
              ),
            ),
          )
        ],
      ),
    );
  }
}

EditableText getEditText(BuildContext context, String content) {
  var textEditingController = TextEditingController(text: content);
  FocusNode focusNode = FocusNode();
  return EditableText(
    controller: textEditingController,
    focusNode: focusNode,
    textDirection: TextDirection.ltr,
    style: const TextStyle(color: Colors.blue),
    cursorColor: Colors.blue,
    backgroundCursorColor: Colors.blue,
    onChanged: (text) {
      toast(context, textEditingController.text);
    },
    autofocus: true,
  );
}

**Comment by liangweihao** [comment]
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.8.1 at /Users/xxx/Desktop/Project/code/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (5 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc1)
    • Android SDK at /Users/xxx/AndroidStudio/sdk
    • Platform android-31, build-tools 31.0.0-rc1
    • ANDROID_HOME = /Users/xxx/AndroidStudio/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Community Edition (version 2021.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.53.2)
    • VS Code at /Users/xxx/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • PACM00 (mobile) • NBWOA68PRKOZ8PKJ • android-arm64  • Android 10 (API 29)
    • macOS (desktop) • macos            • darwin-x64     • macOS 12.1 21C52 darwin-x64
    • Chrome (web)    • chrome           • web-javascript

**Comment by danagbemava-nc** [comment]
Hi @liangweihao, what are the steps to reproduce your issue?

**Comment by danagbemava-nc** [comment]
Hi @liangweihao, what are the steps to reproduce your issue?

**Comment by liangweihao** [comment]
举个例子：当有多个编辑框存在的时候，第一次鼠标选中A编辑框，此时是可以获取焦点的，然后我把鼠标选中B编辑框，此时焦点在B，当我经过第二次再次选中A编辑框的时候，他就无法获取输入焦点了，此时现象是没有A编辑框没有光标也不能输入内容。这里少说了一个环境，我是运行在浏览器中的。

**Comment by danagbemava-nc** [comment]
Can you share a screen recording? That may make it easier for me to see what exactly you're experiencing.

Thank you
