### ISSUE TITLE
[cocoon] Waiting for tree to go green is broken on type 'String' is not a subtype of type 'int' of 'index'

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#96780]
Example GraphQL response

```
{repository: {labels: {nodes: [{id: MDU6TGFiZWwyMjA3MzIxMTgx, pullRequests: {nodes: [{author: {login: CaseyHillers}, authorAssociation: MEMBER, id: PR_kwDOA8VHis4w0Dnk, baseRepository: {nameWithOwner: flutter/cocoon}, number: 1542, title: [README] Update for local+deploying server, mergeable: MERGEABLE, commits: {nodes: [{commit: {abbreviatedOid: 6061910, oid: 60619103e83f392c036d1a79bbf81f792e617c6c, committedDate: 2022-01-12T19:14:25Z, pushedDate: 2022-01-12T19:14:26Z, status: null, checkSuites: {nodes: [{conclusion: SUCCESS}]}}}]}, reviews: {nodes: [{author: {login: godofredoc}, authorAssociation: MEMBER, state: APPROVED}]}, labels: {nodes: [{name: waiting for tree to go green}]}}]}}]}}}
```

The likely culprit is https://github.com/flutter/cocoon/pull/1548

**Comment by CaseyHillers** [comment]
@yusuf-goog (current oncall) i'm going to rollback Cocoon's backend version to Friday

**Comment by yusuf-goog** [comment]
Sounds good, please confirm the rollback fixes this issue.

**Comment by CaseyHillers** [comment]
> Sounds good, please confirm the rollback fixes this issue.

Confirmed.

I have a test version I can use to validate the issue, and I'm working on a fix.

**Comment by CaseyHillers** [comment]
The issue was with the generated conclusions. The test was using a json object instead of a list of json objects.

## Incorrect test value

```json
"nodes":   {
  "conclusion": "SUCCESS"
}
```

## Correct prod value
```
"nodes": [
  {
    "conclusion": "SUCCESS"
  }
]
```

This was an issue because a human has to type by hand some generator code.

**Comment by godofredoc** [comment]
Actually I'll open a new one.
