### ISSUE TITLE
Flaky executions of flutter_tools suite

### ISSUE THREAD

**Issue by mravn-google** [flutter/flutter#9681]
## Steps to Reproduce

Execute `flutter_tools` test suite.

```
../../bin/cache/dart-sdk/bin/pub run test -rexpanded
```
It's flaky. Works on some runs, but at times I see failures like the one below. Not consistent which test it trips over.

Possibly related to similar failure on travis: https://travis-ci.org/flutter/flutter/jobs/226989178 (Unfortunately, I restarted it, so the failure doesn't show anymore. Several tests failed, the first without a stack trace). Similar behavior has been haunting AppVeyor runs as of late.

## Logs

```
00:06 +77: test/analyze_once_test.dart: analyze once flutter create
00:06 +78: test/analyze_once_test.dart: analyze once flutter create
00:06 +78 -1: test/analyze_once_test.dart: analyze once flutter create
00:06 +78 -1: test/adb_test.dart: adb getServerVersion
  SocketException: OS Error: Connection refused, errno = 61, address = 127.0.0.1, port = 57230
  package:flutter_tools/src/android/adb.dart 76:27   Adb._sendAdbServerCommand
  package:flutter_tools/src/android/adb.dart 53:12   Adb.getServerVersion
  test/adb_test.dart 32:40                           main.<fn>.<fn>
  test/src/context.dart 97:32                        testUsingContext.<fn>.<fn>
  package:flutter_tools/src/base/context.dart 76:26  AppContext._run
  package:flutter_tools/src/base/context.dart 66:13  AppContext.runInZone.<fn>
  dart:async                                         runZoned
  package:flutter_tools/src/base/context.dart 65:12  AppContext.runInZone
  test/src/context.dart 86:32                        testUsingContext.<fn>
  ===== asynchronous gap ===========================
  dart:async                                         _Completer.completeError
  package:flutter_tools/src/android/adb.dart 91:3    Adb._sendAdbServerCommand
  ===== asynchronous gap ===========================
  dart:async                                         _asyncErrorWrapperHelper
  package:flutter_tools/src/android/adb.dart 75:62   Adb._sendAdbServerCommand
  package:flutter_tools/src/android/adb.dart 53:12   Adb.getServerVersion
  test/adb_test.dart 32:40                           main.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async                                         Future.Future.microtask
  test/adb_test.dart 29:51                           main.<fn>.<fn>
  test/src/context.dart 97:32                        testUsingContext.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async                                         Future.Future.microtask
  test/src/context.dart 86:51                        testUsingContext.<fn>.<fn>
  package:flutter_tools/src/base/context.dart 76:26  AppContext._run
  ===== asynchronous gap ===========================
  dart:async                                         Future.Future.microtask
  package:flutter_tools/src/base/context.dart 72:48  AppContext._run
  package:flutter_tools/src/base/context.dart 66:13  AppContext.runInZone.<fn>
  dart:async                                         runZoned
  package:flutter_tools/src/base/context.dart 65:12  AppContext.runInZone
  test/src/context.dart 86:32                        testUsingContext.<fn>
  ===== asynchronous gap ===========================
  dart:async                                         Future.Future.microtask
  test/src/context.dart 69:30                        testUsingContext.<fn>
  
00:08 +79 -1: test/create_test.dart: create project
00:09 +80 -1: test/create_test.dart: create project
00:09 +81 -1: test/create_test.dart: create project
```

## Flutter Doctor

[✓] Flutter (on Mac OS X 10.12.4 16E195, channel master)
    • Flutter at /Users/mravn/github/flutter
    • Framework revision 8bf1a16502 (50 minutes ago), 2017-04-28 23:50:37 +0200
    • Engine revision da8ebf40bd
    • Tools Dart version 1.23.0-dev.11.11

[✓] Host Executable Compatibility
    • Downloaded executables execute on host

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/mravn/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.2, Build version 8E2002
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2016.3.4)
    • Dart plugin version 163.13137
    • Flutter plugin version 12.0

[✓] WebStorm (version 2017.1.1)
    • Flutter plugin version 13.0

[✓] Connected devices
    • None

**Comment by Hixie** [comment]
That these tests are flaky is definitely an issue, but we're tracking flake problems separately now. Since this bug doesn't give a precise issue, I'm going to close this in favour of our flake tracking spreadsheet for now.
