### ISSUE TITLE
`InputDecoration` properties `border` and `enabled` are included twice in `hashCode` override

### ISSUE THREAD

**Issue by rydmike** [flutter/flutter#96824]
## Steps to Reproduce

Looking at the `InputDecoration`  code in master (or any) channel, I noticed that the `InputDecoration.border` and `InputDecoration.enabled` are included twice in the `hashCode` override.

### `border` property included twice in the `hashCode` override

The `border` property can be found in the `hashCode` override here:

https://github.com/flutter/flutter/blob/5d5958f3588ee1ed25e31445d4b74b2a52c1025d/packages/flutter/lib/src/material/input_decorator.dart#L3595

and here:

https://github.com/flutter/flutter/blob/5d5958f3588ee1ed25e31445d4b74b2a52c1025d/packages/flutter/lib/src/material/input_decorator.dart#L3617

### `enabled` property included twice in the `hashCode` override

The `enabled` property can be found in the `hashCode` override here:

https://github.com/flutter/flutter/blob/5d5958f3588ee1ed25e31445d4b74b2a52c1025d/packages/flutter/lib/src/material/input_decorator.dart#L3596

and here:

https://github.com/flutter/flutter/blob/5d5958f3588ee1ed25e31445d4b74b2a52c1025d/packages/flutter/lib/src/material/input_decorator.dart#L3618

## Expected results

Expected to see the two properties listed only once in the `hashcode` override.

**Comment by darshankawar** [comment]
Thanks for the report. `border` and `enabled` properties are included twice.

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/input_decorator.dart
