### ISSUE TITLE
Not able to take picture in Realme x3 Superzoom Android 11

### ISSUE THREAD

**Issue by udaypratapsingh** [flutter/flutter#96838]
facing same issue getting this on take picture click
**Getting Logs**
```
: sending capture request
D/CameraCaptureCallback( 5143): CameraCaptureCallback | state: STATE_CAPTURING | afState: 2 | aeState: 2
2
D/CameraCaptureCallback( 5143): CameraCaptureCallback | state: STATE_CAPTURING | afState: null | aeState: null
```

**Code snippet I am using is** 

```
final cameras = await availableCameras();
    final camera = (arguments.docType == DocType.PROFILE_PHOTO ||
            arguments.docType == DocType.COVID_SELFIE)
        ? cameras[1]
        : cameras.first;
    _controller =
        CameraController(camera, ResolutionPreset.medium , enableAudio: false);
    _initializeControllerFuture = _controller.initialize().then((value) async {
      // FlashMode currentFlashMode = _controller.value.flashMode;
      // if (currentFlashMode != null)
      try {
        await _controller.setFlashMode(FlashMode.off);
      } catch (error) {}
      setState(() {});
    });
```

**Comment by darshankawar** [comment]
@udaypratapsingh 
Do you mean you are zooming in to 3x and then trying to take a picture ?
Does it throw any error in the log ?
Can you provide `flutter doctor -v`, camera plugin version you are using along with complete minimal reproducible code sample without any 3rd party plugins ?
Also try the same scenario using the camera plugin [example](https://github.com/flutter/plugins/tree/master/packages/camera/camera/example) and see if you are able to take picture or get same behavior.

**Comment by udaypratapsingh** [comment]
@darshankawar 
**Do you mean you are zooming in to 3x and then trying to take a picture ?**
No im not zooming its my device name only

**Does it throw any error in the log ?**
its giving me this log only and got Stuck
: sending capture request
D/CameraCaptureCallback( 5143): CameraCaptureCallback | state: STATE_CAPTURING | afState: 2 | aeState: 2
2
D/CameraCaptureCallback( 5143): CameraCaptureCallback | state: STATE_CAPTURING | afState: null | aeState: null

**Can you provide flutter doctor -v, camera plugin version you are using along with complete minimal reproducible code sample without any 3rd party plugins ?**
[✓] Flutter (Channel stable, 2.5.2, on macOS 11.5.2 20G95 darwin-x64, locale en-GB)
    • Flutter version 2.5.2 at /Users/udasingh2/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (4 months ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/udasingh2/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-15.0.2.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 15.0.2+7-27)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (2 available)
    • RMX2085 (mobile) • 33b39e08 • android-arm64  • Android 11 (API 30)
    • Chrome (web)     • chrome   • web-javascript • Google Chrome 97.0.4692.71
• No issues found!

**Also try the same scenario using the camera plugin example and see if you are able to take picture or get same behavior.**
Example is also giving the same error or you can say exception.

**Comment by udaypratapsingh** [comment]
@darshankawar 
Please find the camera screen code 

import 'dart:async';
import 'dart:io';

import 'package:camera/camera.dart';
import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:image_picker/image_picker.dart';
import 'package:path/path.dart' show join;
import 'package:path_provider/path_provider.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:scbrider/common/utils/app_constant.dart';
import 'package:scbrider/common/utils/app_enums.dart';
import 'package:scbrider/common/utils/app_theme.dart';
import 'package:scbrider/common/utils/app_widget_key_constant.dart';
import 'package:scbrider/common/utils/colors.dart';
import 'package:scbrider/common/utils/helpers.dart';
import 'package:scbrider/common/utils/localisation_strings.dart';
import 'package:scbrider/common/utils/pop_result.dart';
import 'package:scbrider/common/utils/system_ui_helper.dart';
import 'package:scbrider/core/AppRoutes.dart';
import 'package:scbrider/core_components/network_layer/connect_status_singleton.dart';
import 'package:scbrider/core_pack/caching/rider_preferences.dart';
import 'package:scbrider/core_pack/custom_widgets/RDAlert.dart';
import 'package:scbrider/core_pack/custom_widgets/RDDivider.dart';
import 'package:scbrider/core_pack/custom_widgets/RDLoadingIndicator.dart';
import 'package:scbrider/core_pack/i18n/language_constants.dart';
import 'package:scbrider/domain/entities/CameraModel.dart';
import 'package:scbrider/modules/camera_modules/camera_screen_module/bloc/upload_covid_selfie_filetoserver_bloc.dart';
import 'package:scbrider/modules/camera_modules/widgets/camera_overlay.dart';
import 'package:scbrider/modules/camera_modules/widgets/image_processor.dart';
import 'package:scbrider/rename_references/upload_loading_event_handler_bloc.dart';

List<CameraDescription> cameras;
const _bottomSheetHeight = 105.0;

class CameraScreen extends StatefulWidget {
  static const String id = "camera_screen";

  const CameraScreen({Key key}) : super(key: key);

  @override
  _CameraScreenState createState() => _CameraScreenState();
}

class _CameraScreenState extends State<CameraScreen>
    with WidgetsBindingObserver {
  CameraController _controller;
  Future<void> _initializeControllerFuture;
  CameraModel arguments;
  final UploadLoadingEventHandlerBloc uploadLoadingEventHandlerBloc =
      UploadLoadingEventHandlerBloc();

  CameraController get controller => _controller;

  Future<void> get initializeControllerFuture => _initializeControllerFuture;
  bool flash = false;

  set initializeControllerFuture(Future<void> value) {
    _initializeControllerFuture = value;
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    // App state changed before we got the chance to initialize.
    if (controller == null || !controller.value.isInitialized) {
      return;
    }
    if (state == AppLifecycleState.inactive) {
      controller.dispose();
    } else if (state == AppLifecycleState.resumed) {
      reInitialiseCamera();
    }
  }

  void reInitialiseCamera() async {
    //final cameraDescription = _controller.description;
    if (_controller != null) _controller.dispose();
     final cameras = await availableCameras();
    final camera = (arguments.docType == DocType.PROFILE_PHOTO ||
            arguments.docType == DocType.COVID_SELFIE)
        ? cameras[1]
        : cameras.first;
    _controller =
        CameraController(camera, ResolutionPreset.medium, enableAudio: false);
    // _controller = CameraController(cameraDescription, ResolutionPreset.medium,imageFormatGroup: ImageFormatGroup.jpeg ,
    //    enableAudio: false);
    _initializeControllerFuture = _controller.initialize().then((value) async {
      try {
        await _controller.setFlashMode(FlashMode.off);
      } catch (error) {}
      setState(() {});
    });
  }

  @override
  void initState() {
    super.initState();
    _initializeCamera();
    WidgetsBinding.instance?.addObserver(this);
  }

  Future<void> _initializeCamera() async {
    if (!mounted) {
      return;
    }
    if (!await Permission.camera.request().isGranted) {
      Navigator.pop(context);
      return;
    }
    final cameras = await availableCameras();
    final camera = (arguments.docType == DocType.PROFILE_PHOTO ||
            arguments.docType == DocType.COVID_SELFIE)
        ? cameras[1]
        : cameras.first;
    _controller =
        CameraController(camera, ResolutionPreset.medium , enableAudio: false);
    _initializeControllerFuture = _controller.initialize().then((value) async {
      // FlashMode currentFlashMode = _controller.value.flashMode;
      // if (currentFlashMode != null)
      try {
        await _controller.setFlashMode(FlashMode.off);
      } catch (error) {}
      setState(() {});
    });
    // setState(() {});
  }

  @override
  Widget build(BuildContext context) {
    arguments = ModalRoute.of(context)?.settings?.arguments;
    return Scaffold(
      backgroundColor: Colors.black,
      appBar: _buildAppBar(),
      body: FutureBuilder<void>(
        future: _initializeControllerFuture,
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.done) {
            _controller.lockCaptureOrientation(DeviceOrientation.portraitUp);
            return Stack(children: [
              // Center(child: CameraPreview(_controller)),
              // Center(child: cameraPreview),
              Center(
                child: CustomPaint(
                  foregroundPainter: CameraOverlay(docType: arguments.docType),
                  child: CameraPreview(_controller),
                ),
              ),
              Align(
                alignment: Alignment.bottomCenter,
                child: Container(
                  alignment: Alignment.center,
                  height: PADDING_100,
                  decoration: const BoxDecoration(
                    color: CustomColors.black,
                  ),
                  child: Row(
                    children: [
                      if (arguments.docType != DocType.MEAL_PICKED_UP &&
                          arguments.docType != DocType.FOOD_DELIVERED &&
                          arguments.docType != DocType.PROFILE_PHOTO &&
                          arguments.docType != DocType.COVID_SELFIE)
                        containerForGalleryButton(),
                      Spacer(),
                      Center(
                        child: InkWell(
                          key: const Key(Camera),
                          onTap: () => {onCaptureButtonPressed(context)},
                          child: Container(
                              padding: const EdgeInsets.all(12),
                              decoration: const BoxDecoration(
                                shape: BoxShape.circle,
                                gradient: const LinearGradient(
                                  colors: [
                                    CustomColors.primaryBtnGradient1,
                                    CustomColors.primaryBtnGradient2
                                  ],
                                  begin: Alignment.centerLeft,
                                  end: Alignment.centerRight,
                                ),
                              ),
                              child: const Icon(
                                Icons.camera_alt,
                                size: PADDING_24,
                                color: CustomColors.white,
                              )),
                        ),
                      ),
                      Spacer(),
                      Align(
                        alignment: Alignment.centerRight,
                        child: (arguments.docType == DocType.COVID_SELFIE ||
                                arguments.docType == DocType.PROFILE_PHOTO)
                            ? Container()
                            : containerForFalshButton(),
                      ),
                    ],
                  ),
                ),
              ),
              Column(
                children: [
                  (arguments.docType == DocType.DRIVER_LICENSE)
                      ? const SizedBox(height: PADDING_40)
                      : const SizedBox(height: PADDING_20),
                  Padding(
                    padding: const EdgeInsets.symmetric(horizontal: PADDING_16),
                    child: Align(
                      alignment: Alignment.topCenter,
                      child: Text(
                        _cameraTitleText(arguments),
                        style: AppTheme.button.copyWith(
                          color: CustomColors.neutral,
                        ),
                        key: const Key(Camera_Desc),
                        textAlign: TextAlign.center,
                      ),
                    ),
                  ),
                ],
              ),
              (arguments.docType == DocType.COVID_SELFIE)
                  ? Positioned(
                      bottom: PADDING_100,
                      child: Container(
                        alignment: Alignment.center,
                        width: MediaQuery.of(context).size.width,
                        height: PADDING_100,
                        decoration: const BoxDecoration(
                          color: Colors.transparent,
                        ),
                        child: Text(
                          getTranslated(
                              context, AppLocalisationStrings.covidSelfieNote),
                          style: AppTheme.button.copyWith(
                            color: CustomColors.neutral,
                          ),
                          key: const Key(covid_note),
                          textAlign: TextAlign.center,
                        ),
                      ),
                    )
                  : Offstage(),
              StreamBuilder<UploadLoadingEventHandlerBlocEvent>(
                  stream:
                      uploadLoadingEventHandlerBloc.uploadLoadingModelsStream,
                  initialData: uploadLoadingEventHandlerBloc.state,
                  builder: (context, snapshot) {
                    return snapshot.data ==
                            UploadLoadingEventHandlerBlocEvent.loadingStarted
                        ? RDLoadingIndicator()
                        : Offstage();
                  })
            ]);
          } else {
            return Container(
              color: CustomColors.black,
              child: Center(
                child: CircularProgressIndicator(
                  backgroundColor: CustomColors.primaryBtnGradient1,
                  valueColor: AlwaysStoppedAnimation<Color>(
                      CustomColors.primaryBtnGradient2),
                ),
              ),
            );
          }
        },
      ),
    );
  }

  AppBar _buildAppBar() {
    return AppBar(
      systemOverlayStyle: SystemUiHelper.getSystemUiOverlayStyle(),
      title: Text(
        cameraScreenTitleText(arguments),
        style: AppTheme.button.copyWith(
          color: CustomColors.neutral,
        ),
        key: const Key(Camera_Desc),
        textAlign: TextAlign.center,
      ),
      backgroundColor: CustomColors.black,
    );
  }

  /// This func will return the gallery button widget
  Widget containerForGalleryButton() {
    return Container(
      alignment: Alignment.centerLeft,
      child: IconButton(
        key: const Key(Gallery),
        padding: const EdgeInsets.only(left: PADDING_26),
        icon: SvgPicture.asset(
          "assets/icons/gallery_icon.svg",
          color: CustomColors.white,
        ),
        onPressed: () => {getImage()},
      ),
    );
  }

  Widget containerForFalshButton() {
    return Padding(
      padding: const EdgeInsets.only(right: PADDING_15),
      child: Container(
        alignment: Alignment.centerLeft,
        child: InkWell(
            key: const Key(Camera),
            onTap: () {
              onFlashCapture(context);
            },
            child: Icon(
              flash ? Icons.flash_on : Icons.flash_off,
              size: PADDING_24,
              color: CustomColors.white,
            )),
      ),
    );
  }

  /// This func will return the [String] for camera title.
  /// It will receive the [CameraModel].
  String _cameraTitleText(CameraModel data) {
    if (data.docType == DocType.DRIVER_LICENSE) {
      return getTranslated(context,
          AppLocalisationStrings.pleasePlaceYourDriverLicenseToFitFrame);
    } else if (data.docType == DocType.VEHICLE_REGISTRATION) {
      return getTranslated(context,
          AppLocalisationStrings.pleasePutTheCarRegistrationBookToFitFrame);
    } else if (data.docType == DocType.VEHICLE_WITH_FOOD_CARD) {
      return getTranslated(context, AppLocalisationStrings.foodCardImageText);
    } else if (data.docType == DocType.PROFILE_PHOTO) {
      return getTranslated(
          context, AppLocalisationStrings.cameraTitleTextForProfilePhoto);
    } else if (data.docType == DocType.MEAL_PICKED_UP) {
      return getTranslated(context,
          AppLocalisationStrings.cameraDescriptionMealPickedUPFoodPhoto);
    } else if (data.docType == DocType.FOOD_DELIVERED) {
      return getTranslated(context,
          AppLocalisationStrings.cameraDescriptionFoodDeliveredFoodPhoto);
    } else if (data.docType == DocType.COVID_SELFIE) {
      return getTranslated(
          context, AppLocalisationStrings.covidSelfieHeaderTitle);
    } else if (data.docType == DocType.EV_UPDATE) {
      return getTranslated(
          context, AppLocalisationStrings.pleasePlaceAnElectricMotorCycle);
    } else {
      return getTranslated(context, AppLocalisationStrings.cameraDescription);
    }
  }

  String cameraScreenTitleText(CameraModel data) {
    if (data.docType == DocType.DRIVER_LICENSE) {
      return getTranslated(context, AppLocalisationStrings.headerTitleForDL);
    } else if (data.docType == DocType.VEHICLE_REGISTRATION) {
      return getTranslated(context,
          AppLocalisationStrings.screenTitleForCameraVEHICLE_REGISTRATION);
    } else if (data.docType == DocType.VEHICLE_WITH_FOOD_CARD) {
      return getTranslated(context,
          AppLocalisationStrings.uploadPhotosOfVehiclesAndFoodDeliveryBoxes);
    } else if (data.docType == DocType.PROFILE_PHOTO) {
      return getTranslated(
          context, AppLocalisationStrings.uploadProfilePicture);
    } else if (data.docType == DocType.BACKGROUND_VERIFICATION_FORM) {
      return getTranslated(context, AppLocalisationStrings.criminalRecordCheck);
    } else if (data.docType == DocType.MEAL_PICKED_UP) {
      return getTranslated(context, AppLocalisationStrings.getFood);
    } else if (data.docType == DocType.FOOD_DELIVERED) {
      return getTranslated(context, AppLocalisationStrings.gotToCustomer);
    } else if (data.docType == DocType.EV_UPDATE) {
      return getTranslated(
          context, AppLocalisationStrings.uploadMotorcycleLease);
    } else {
      return "";
    }
  }

  void onFlashCapture(BuildContext context) async {
    setState(() {
      flash = !flash;
    });
    flash
        ? await _controller.setFlashMode(FlashMode.torch)
        : await _controller.setFlashMode(FlashMode.off);
  }

  void onCaptureButtonPressed(BuildContext context) async {
    try {
      await _initializeControllerFuture;
      final path1 = join(
        (await getApplicationDocumentsDirectory()).path,
        '${DateTime.now()}.png',
      );

      _controller.takePicture().then((XFile file) async {
        if (mounted) {
          try {
            await _controller.setFlashMode(FlashMode.off);
          } catch (error) {}
          setState(() => flash = false);
          await ImageProcessor.cropSquare(
            file.path,
            path1,
            false,
            context.size,
            docType: arguments.docType,
          );

          openPreviewScreen(path1);
        }
      });
    } catch (e) {
      FlashMode currentFlashMode = _controller.value.flashMode;
      if (currentFlashMode != null)
        await _controller.setFlashMode(FlashMode.off);
      setState(() => flash = false);
      Helpers.debugPrint(e);
    }
  }

  Future getImage() async {
    if (arguments.docType == DocType.BACKGROUND_VERIFICATION_FORM) {
      _showBottomSheet();
    } else {
      getImageFromGallery();
    }
  }

  Future<void> getImageFromGallery() async {
    final pickedFile = await ImagePicker().pickImage(
      source: ImageSource.gallery,
      maxHeight: 2500,
      maxWidth: 2500,
      imageQuality: 85,
    );
    openPreviewScreen(pickedFile.path);
  }

  Future<void> getPdfFromStorage() async {
    FilePickerResult result = await FilePicker.platform.pickFiles(
      type: FileType.custom,
      allowedExtensions: ['pdf'],
    );

    if (result != null) {
      openPreviewScreen(result.files.first.path, isPdf: true);
    }
  }

  void openPreviewScreen(String imagePath, {bool isPdf = false}) {
    if (imagePath == null) {
      return;
    }
    arguments.isPdf = isPdf;
    arguments.imagePath = imagePath;
    if (arguments.docType == DocType.FOOD_DELIVERED ||
        arguments.docType == DocType.MEAL_PICKED_UP) {
      Navigator.pushNamed(
        context,
        Routes.CamPreview,
        arguments: arguments,
      ).then((value) {
        // Helpers.print("value on camera screen ==> $value");
        if (value != null) Navigator.pop(context, value);
      });
    } else if (arguments.docType == DocType.COVID_SELFIE) {
      saveCOVIDSelfiePicHandler(imagePath, arguments);
    } else {
      Navigator.pushNamed(context, Routes.CamPreview, arguments: arguments);
    }
  }

  saveCOVIDSelfiePicHandler(String imagePath, CameraModel map) async {
    final UploadCovidSelfieFileBloc uploadCovidSelfieFileBloc =
        UploadCovidSelfieFileBloc();

    try {
      if (imagePath.isNotEmpty && File(imagePath) != null) {
        final fileSize = await File(imagePath).length();
        Helpers.debugPrint('File Size: $fileSize');
        if (fileSize == null || fileUploadSizeLimit < fileSize) {
          getAlertDialog().showAlertDialog(context);
          return;
        }
      }
    } catch (ex) {
      Navigator.of(context).pop();
      return;
    }

    if (!ConnectionStatusSingleton.getInstance().hasConnection()) {
      return;
    }

    final riderId = await RiderPreferences().getRiderId();
    uploadLoadingEventHandlerBloc.startLoading();

    uploadCovidSelfieFileBloc.uploadToFile(
        File(imagePath), "doc.png", map.docType, riderId);

    uploadCovidSelfieFileBloc.uploadCovidSelfieFileStateController.stream
        .listen((event) {
      Helpers.debugPrint('image upload result: $event');
      uploadLoadingEventHandlerBloc.stopLoading();
      if (event == null) {
        uploadCovidSelfieFileBloc.dispose();
        return;
      }

      Navigator.of(context).pop(
        PopWithResults(
          fromPage: Routes.Camera,
          toPage: Routes.Job,
          results: {"result": (event?.id ?? false) != ""},
        ),
      );
    });
  }

  RDAlert getAlertDialog() => RDAlert(
        isAlertImage: true,
        title: getTranslated(context, AppLocalisationStrings.fileSizeTitle),
        subTitle:
            getTranslated(context, AppLocalisationStrings.fileSizeSubtitle),
        primaryButtonTitle: getTranslated(context, AppLocalisationStrings.ok),
        secondaryButtonTitle: null,
        onPressedPrimary: null,
        onPressedSecondary: null,
      );

  @override
  void dispose() {
    WidgetsBinding.instance?.removeObserver(this);
    _controller?.dispose();
    super.dispose();
  }

  void _showBottomSheet() {
    showModalBottomSheet<void>(
      // shape: RoundedRectangleBorder(borderRadius: AppTheme.borderRadiusTop16),
      backgroundColor: Colors.transparent,

      context: context,
      builder: (context) {
        return Container(
          height: _bottomSheetHeight,
          padding: EdgeInsets.zero,
          margin: const EdgeInsets.fromLTRB(
            PADDING_16,
            0,
            PADDING_16,
            PADDING_16,
          ),
          decoration: const BoxDecoration(
            color: Colors.white,
            borderRadius: AppTheme.borderRadiusAll32,
          ),
          child: ClipRRect(
            borderRadius: AppTheme.borderRadiusAll32,
            child: Column(
              mainAxisSize: MainAxisSize.min,
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                Expanded(
                  child: TextButton(
                    onPressed: () {
                      Navigator.of(context).pop();
                      getImageFromGallery();
                    },
                    child: Text(
                      getTranslated(context, AppLocalisationStrings.gallery),
                      style:
                          AppTheme.button.copyWith(color: CustomColors.black),
                    ),
                  ),
                ),
                Padding(
                  padding: const EdgeInsets.symmetric(horizontal: PADDING_16),
                  child: const RDDivider(
                    height: 1,
                    dividerColor: CustomColors.neutral4b,
                  ),
                ),
                Expanded(
                  child: TextButton(
                    onPressed: () {
                      Navigator.of(context).pop();
                      getPdfFromStorage();
                    },
                    child: Text(
                      getTranslated(context, AppLocalisationStrings.browse),
                      style:
                          AppTheme.button.copyWith(color: CustomColors.black),
                    ),
                  ),
                ),
              ],
            ),
          ),
        );
      },
    );
  }
}

**Comment by darshankawar** [comment]
@udaypratapsingh 
The log you shared doesn't seem to contain any error or exception, so not exactly sure what could be causing this.
What behavior do you see while taking picture ? Does it hang ? Gets stuck ? Is there any specific steps to replicate the behavior ?
Also the code sample you shared is not minimal, we just want minimal reproducible code sample that'll be enough to replicate the issue without any additional / 3rd party plugin imports and related code.
