### ISSUE TITLE
Standardize testing environments of flutter_tools dependencies

### ISSUE THREAD

**Issue by xster** [flutter/flutter#9683]
Instead of using our own machines and deleting stuff to reproduce states of missing dependencies to test things like #9580, create an official process to test on unified initial environments.

Something lightweight like Docker is ideal. Then we can have different images for each development environment combinations. Definitely seems possible for Android SDK https://hub.docker.com/r/runmymind/docker-android-sdk/~/dockerfile/. There's even a flutter image  https://hub.docker.com/r/brianegan/flutter/. Not sure how easy it is to get xcode running in docker though. 

Otherwise we can create images of OS X in virtualbox

**Comment by xster** [comment]
Seems only possible to create linux based images in docker. Can't test the macosx paths there.

**Comment by xster** [comment]
Seems like the simplest way (to simulate mac) is to take a mac, install https://my.vmware.com/web/vmware/details?downloadGroup=FUS-857&productId=527&rPId=16242. Then it has an option to create a guest VM instance from the host machine's own recovery partition. Seems like a good way to test since we can snapshot various conditions.

cc @cbracken cause I think you're testing stuff

**Comment by cbracken** [comment]
@xster -- edited your comment to prettify the download link for VMWare Fusion.

**Comment by zoechi** [comment]
Is this a dup of #8963?

**Comment by iapicca** [comment]
Hi @xster 
I see there's an open [issue ](https://github.com/flutter/flutter/issues/8963)addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
