### ISSUE TITLE
Waiting for tree to go green is failing consistently

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#96836]
There are two types of errors. The first one is a problem with the json result translation:

```
_checkPRs error in flutter/plugins: type 'List<dynamic>' is not a subtype of type 'List<Map<String, dynamic>>?' in type cast
```

The second one is because the queries to graphql are timing out for roll PRs with 100s of checks:

```
OperationException(linkException: ServerException(originalException: null, parsedResponse: Response(data: null, errors: [GraphQLError(message: Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `AF2A:5A52:4325712:9340D0F:61E78945` when reporting this issue., locations: null, path: null, extensions: null)], context: Context({ResponseExtensions: Instance of 'ResponseExtensions'}))), graphqlErrors: [])
```

**Comment by godofredoc** [comment]
Setting as P0 as this is blocking all the rolls and affecting everyone using the waiting for tree to go green label.

**Comment by godofredoc** [comment]
\cc @CaseyHillers who was working on a similar issue.

**Comment by CaseyHillers** [comment]
I rolled back to a good version. I thought I fixed this in https://github.com/flutter/cocoon/pull/1552, but it looks like I need another cast.

For the second issue, I'm not sure why we're still seeing timeouts. I'll look into other ways we can speed up the graphql query.

**Comment by CaseyHillers** [comment]
Another issue popped up: The tree status is being marked as failing, and removing the label.

I'm going to revert my original change as it didn't speed up the query.

**Comment by CaseyHillers** [comment]
I did some research into how to optimize the graphql queries:
1. Lower pagination amounts. Right now we query for 100 pull requests with the waiting for tree to go green label. This isn't a normal amount, and it's more likely to be around 10 max. We can lower this amount which would speed up the query (likely by a factor of 5)
2. Multiple pass through. We can break the query into multiple parts. Eg (A) Get node ids of pull requests with waiting for tree to go green (B) Query these node ids for the PR state that we need to process auto-submission.

I'll send a PR for (1) as it's a quick fix. (2) can likely be done with a single PR, but I'd like to see the impact (1) has.

If necessary, it may be quicker to instead rely on webhooks for when the label is added, and track those PRs in datastore to be polled.

**Comment by godofredoc** [comment]
+1 to lower the pagination amounts. Relying on webhooks and datastore may not be an option as the auto-submit bot will be the first part to be separated to a microservice or independent service. The context is we would like to make the auto-submit bot configurable and generic enough to be used on both dart and flutter repositories.

**Comment by CaseyHillers** [comment]
The pagination decrease wasn't enough. I'm adding

```
{
  rateLimit {
    limit
    cost
    remaining
    resetAt
  }
}
```

to our github graphql queries to try and debug this more.

**Comment by godofredoc** [comment]
Still failing for the framework, checking what can be removed from the current queries to speed up the queries.

**Comment by CaseyHillers** [comment]
I tried adding pagination (gets 1 pull request at a time, and make multiple graphql requests), and that still timed out.

The issue is that the labels -> pull request query is very expensive. Removing the label query, and leaving it for something that is scanned in Cocoon made the graphql query take <1 second.

I'm currently investigating the feasibility of removing the querying from GraphQL, and using `package:github` for it. For now, removing the label will still need to be a GraphQL mutation

**Comment by CaseyHillers** [comment]
I created a proposal in https://flutter.dev/go/autosubmit for fixes necessary. I'll start working on MVP tomorrow and throughout next week.

**Comment by godofredoc** [comment]
Fixed with https://github.com/flutter/cocoon/pull/1677
