### ISSUE TITLE
How to export package:flutter_gen/gen_l10n/app_localizations.dart which is in sub package

### ISSUE THREAD

**Issue by zmtzawqlp** [flutter/flutter#96839]
I'm try to support internationalization by following the guid form https://docs.flutter.dev/development/accessibility-and-localization/internationalization

The different is that i put the different function into different package. 

I create core_lib package for main project, something like following:

<img width="289" alt="截屏2022-01-19 下午1 35 42" src="https://user-images.githubusercontent.com/16477333/150070343-3395556f-a768-47b9-adc5-155627850a07.png">

1. export it in core_lib.dart

```dart
library core_lib;

export 'package:flutter_gen/gen_l10n/app_localizations.dart';

```
2. import it in main.dart

```dart
import 'package:flutter/material.dart';
import 'package:core_lib/core_lib.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
      supportedLocales: AppLocalizations.supportedLocales,
      localizationsDelegates: AppLocalizations.localizationsDelegates,
    );
  }
}
```
It has code hints but has build error
<img width="614" alt="截屏2022-01-19 下午1 46 51" src="https://user-images.githubusercontent.com/16477333/150071531-a3d5d51d-a4fd-4479-885d-11435732916d.png">

so how can i use it in such case?

and by the way vscode is not work good even i put localization in main project, it always to be not  identified, something like https://stackoverflow.com/questions/64574620/target-of-uri-doesnt-exist-packageflutter-gen-gen-l10n-gallery-localizations

log from vscode

```
[Error - 1:30:05 PM] Request completionItem/resolve failed.
  Message: No such element: AppLocalizations in package:core_lib/core_lib.dart
  Code: -32602 
AppLocalizations
[Error - 1:30:09 PM] Request completionItem/resolve failed.
  Message: No such element: AppLocalizations in package:core_lib/core_lib.dart
  Code: -32602 
AppLocalizations
[Error - 1:30:12 PM] Request completionItem/resolve failed.
  Message: No such element: AppLocalizations in package:core_lib/core_lib.dart
  Code: -32602 
AppLocalizations
```

`flutter doctor -v`

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.0.1 21A559 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.8.1 at /Users/zmtzawqlp/Documents/flutter/2.8.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (5 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/zmtzawqlp/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/zmtzawqlp/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (3 available)
    • MI 6 (mobile)   • 5a4b233b • android-arm64  • Android 8.0.0 (API 26)
    • macOS (desktop) • macos    • darwin-x64     • macOS 12.0.1 21A559 darwin-x64
    • Chrome (web)    • chrome   • web-javascript • Google Chrome 97.0.4692.71
```

the demo is attached, please check it.

[flutter_localizations_test.zip](https://github.com/flutter/flutter/files/7894344/flutter_localizations_test.zip)

**Comment by zmtzawqlp** [comment]
i found an issue refer to this https://github.com/flutter/flutter/issues/84979
and i try to change l10n.yaml as following. yes it will not generate files in lib/l10n.
```
arb-dir: l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-dir: lib/l10n
synthetic-package: false
```
wordaround is  run following command: 
flutter gen-l10n --arb-dir l10n --template-arb-file app_en.arb --output-localization-file app_localizations.dart --output-dir lib/l10n --no-synthetic-package

**Comment by darshankawar** [comment]
> wordaround is run following command:
> flutter gen-l10n --arb-dir l10n --template-arb-file app_en.arb --output-localization-file app_localizations.dart --output-dir lib/l10n --no-synthetic-package

Does this command help you to export the package properly ?
If so, this case is similar to the one you linked to https://github.com/flutter/flutter/issues/84979

**Comment by zmtzawqlp** [comment]
> > wordaround is run following command:
> > flutter gen-l10n --arb-dir l10n --template-arb-file app_en.arb --output-localization-file app_localizations.dart --output-dir lib/l10n --no-synthetic-package
> 
> Does this command help you to export the package properly ? If so, this case is similar to the one you linked to #84979

yes, but it can't create files with flutter packages get

**Comment by darshankawar** [comment]
@zmtzawqlp 
Please follow-up in the linked issue for further updates. Closing this as a duplicate and the command mentioned with `--no-synthetic-package` seems to resolve your original question.
