### ISSUE TITLE
Status bar area problem

### ISSUE THREAD

**Issue by NARIKODANHRIDUL** [flutter/flutter#96833]
i used "SystemChrome.setEnabledSystemUIMode(SystemUiMode.manual,
      overlays: []); " to make the status bar hide when not needed , now its working as needed but now the status bar area is completely black, i wanted my scaffold to extend to that area also.... what should i do ??

**Comment by darshankawar** [comment]
@NARIKODANHRIDUL 
Your question is better suited for support channels like StackOverflow so please ask the same there.
Closing from here as this isn't a bug or a feature request.
