### ISSUE TITLE
Detect devicelab iPhones with bad cables

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#96832]
When the charging cables fail in the devicelab, iPhones show blocking UI that the battery is dead, or the device isn't supported:

<img src="https://user-images.githubusercontent.com/682784/150046636-f6cdc42a-ce47-4a76-96bf-a0ea5420a0e7.png" width=400> <img src="https://user-images.githubusercontent.com/682784/150046702-16089949-6e06-49d8-925d-7de5460602db.png" width=400>

This currently manifests as test flakes, like https://github.com/flutter/flutter/issues/96794.  Instead, this should be detected as an infra failure so the bots can be quarantined until the cable is replaced.

The Infra dialog UI test could be updated to fail if either of these two dialogs is present.
https://github.com/flutter/cocoon/blob/f5d0471044e3d66d2e6e1aabbbeeecff5c0c1f5a/device_doctor/tool/infra-dialog/infra-dialogUITests/infra_dialogUITests.swift#L8

**Comment by godofredoc** [comment]
Is there a different way to detect the issue? the infra dialog check runs during task execution which is already too late for quarantining the device as the task will fail.

Do you know if we can precompile the application and use in the health checks? the current blocker is that building and running the application requires xcode which is not available during the bot health checks.

**Comment by yusuf-goog** [comment]
@jmagman FYI, I have cables on order which should hopefully minimize these occurrences as well. 

A check would be helpful though.

**Comment by jmagman** [comment]
> Is there a different way to detect the issue? the infra dialog check runs during task execution which is already too late for quarantining the device as the task will fail.

It's probably dismissing the battery one since it's handling `Close`, but then it's popping up later.  And the `Dismiss` button isn't handled at all.  Hmm, could we at least have that dialog check fail with an infra_failure if those dialogs are present?  It won't quarantine but at least it won't show up as a test failure.

> Do you know if we can precompile the application and use in the health checks? the current blocker is that building and running the application requires xcode which is not available during the bot health checks.

I expect those dialogs are present even on the home screen, a particular app doesn't need to be launched.  I'm not sure how you'd detect the dialog without Xcode installed, though.

**Comment by yusuf-goog** [comment]
All mac-ios cables have been swapped out. Please let me know if you notice these dialog's popping up again.

**Comment by CaseyHillers** [comment]
@keyonghan is this something you can help with?

**Comment by jmagman** [comment]
> could we at least have that dialog check fail with an infra_failure if those dialogs are present? It won't quarantine but at least it won't show up as a test failure.

I can do this piece of it, which won't auto-quarantine, but will at least show up as an infra failure instead of a flaky test.

**Comment by godofredoc** [comment]
Instead of dealing with the system dialogs we can focus on quarantining based on the power level. Checking with one 6S from the lab I found the battery is worn out and we need to replace that phone. Quarantining on power level will help us identify the phones we need to replace and remove flakiness at the same time.

**Comment by yusuf-goog** [comment]
@godofredoc how did you detect the worn out battery?

**Comment by godofredoc** [comment]
I brought the phone home for testing and noticed that the full charged battery only lasted 4 hours when idle.

**Comment by jmagman** [comment]
I think `ideviceinfo -q com.apple.mobile.battery -k BatteryCurrentCapacity` will get you the current battery percentage.  `idevicediagnostics ioregentry AppleSmartBattery` on newer devices gives all kinds of data about the battery, maybe some hints in there to detect worn out batteries.

But I don't think the battery info will help with `This accessory may not be supported`--that's usually a bad cable re:data, it may be charging fine.

**Comment by jmagman** [comment]
> I expect those dialogs are present even on the home screen, a particular app doesn't need to be launched.

I have an almost-dead phone and wasn't able to prompt the Low Battery dialog even when I launched an app...

**Comment by keyonghan** [comment]
With https://github.com/flutter/cocoon/pull/1562 to detect bad iOS cables, and https://github.com/flutter/cocoon/pull/1565 to check battery level (in prod already), closing the bug here. Please help reopen if any further issues.
