### ISSUE TITLE
BottomNavigationBar is hiding behind android nav buttons. 

### ISSUE THREAD

**Issue by jeen0404** [flutter/flutter#96847]
before updating to flutter   2.9.0-1.0.pre.384 bottomNavigationBar was working fine with all the android devices but after updating my app started showing bottomNavigationBar behind the android nav buttons(for iOS it is working fine).

I'm adding screenshot here for reference 

<img src="https://user-images.githubusercontent.com/34714530/150100527-8beecc01-b00e-4f71-82e5-16b50f0fc7c1.jpeg" width ="300">

here is my Scaffold code sample 
<img width="554" alt="Screen Shot 2022-01-19 at 14 33 11" src="https://user-images.githubusercontent.com/34714530/150100665-a1b16358-7f34-4693-84f6-278b419a624e.png">

flutter doctor :
<img width="855" alt="Screen Shot 2022-01-19 at 14 33 52" src="https://user-images.githubusercontent.com/34714530/150100727-435605d4-98a7-4ec3-99e1-cb5cc0670857.png">

**Comment by maheshmnj** [comment]
Hi @jeen0404, Thanks for filing the issue . I ran the [official sample code](https://api.flutter.dev/flutter/material/BottomNavigationBar-class.html) and I was not able to reproduce the issue on the latest master channel. Please share a minimal and complete reproducible code sample. 

<img src="https://user-images.githubusercontent.com/31410839/150114537-571cda0e-3ee7-47e0-88d0-6fb15941355e.png" width ="300">

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.9.0-1.0.pre.398, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.9.0-1.0.pre.398 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8017883a5d (7 hours ago), 2022-01-18 23:04:01 -0500
    • Engine revision 7a33b4b3fb
    • Dart version 2.17.0 (build 2.17.0-27.0.dev)
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:5555 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos            • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 97.0.4692.71

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

ps: Please prefer sharing textual logs and snippets over images in the future.

Thanks

**Comment by maheshmnj** [comment]
@aksaini0045 Please share the output of `flutter doctor -v` a minimal and complete sample code and the device info on which the issue is reproducible.

**Comment by aksaini0045** [comment]
flutter doctor -v output:
<img width="566" alt="image" src="https://user-images.githubusercontent.com/91606150/151556780-49df4da0-7f2d-43bf-aa96-ed531961ecdf.png">
![image](https://user-images.githubusercontent.com/91606150/151556912-5da02add-bad1-4311-bb3d-8776e70ed41c.png)
device-oppo a3s
others are redmi,tecno
(not remember model now)

**Comment by aksaini0045** [comment]
and now I changed my flutter version to 2.8.1 and the problem has gone

**Comment by maheshmnj** [comment]
> I don't know why its showing 2.10 yesterday it was 2.9 and I didn't upgrade
is it due to channel 'master' ?? please suggest as I am new to flutter

@aksaini0045, Thats definitely weird flutter doesn't get upgraded unless you manually upgrade it by running 
`flutter upgrade` If you encounter this issue again feel free to file a new issue with the reproducible steps.

**Comment by maheshmnj** [comment]
Everyone who is facing the BottomNavigation bar issue Please try upgrading to `stable 2.8.1` and if the issue persists Please share a minimal and complete reproducible code sample along with the device name on which the issue occurs.

Thanks
