### ISSUE TITLE
Webview reload when text field get clicked

### ISSUE THREAD

**Issue by Amr1440** [flutter/flutter#96842]
Webview gets reloaded whenever I click on webview text field and keyboard does not appear .

I'm using   webview_flutter: ^3.0.0

<details>
<summary>flutter doctor -v</summary>
 
```console
 [✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale en-SA)
    • Flutter version 2.8.1 at /Users/amr/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (5 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/Amr/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Connected device (4 available)
    • ONEPLUS A6003 (mobile)     • 2834792c                             • android-arm64  • Android 11 (API 30)
    • sdk gphone x86 (mobile)    • emulator-5554                        • android-x86    • Android 11 (API 30) (emulator)
    • iPhone 13 Pro Max (mobile) • BF39C4C7-23EB-4AE8-96CE-5249244310DB • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 97.0.4692.71

• No issues found! 
```
</details>

**Comment by danagbemava-nc** [comment]
Hi @Amr1440, thanks for reporting this. 

Please provide a complete minimal reproducible code sample as well as any relevant logs and concrete steps to reproduce. 

Also, what platform do you experience this issue with? 

Thank you

**Comment by Amr1440** [comment]
Platform is : Android & IOS 
Logs : nothing appears when I click text field 
Code sample :
`import 'package:flutter/foundation.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:mytaqah/helper/constant.dart';
import 'package:webview_flutter/webview_flutter.dart';

class SupportFollowUpScreen extends StatefulWidget {
  const SupportFollowUpScreen({Key key}) : super(key: key);

  @override
  State<SupportFollowUpScreen> createState() => _SupportFollowUpScreenState();
}

class _SupportFollowUpScreenState extends State<SupportFollowUpScreen> {
  var loadingPercentage = 0;
  final Set<Factory> gestureRecognizers =
      [Factory(() => EagerGestureRecognizer())].toSet();
  WebViewController _webViewController;

  @override
  Widget build(BuildContext context) {
    return Directionality(
        textDirection: TextDirection.rtl,
        child: Scaffold(
          resizeToAvoidBottomInset: true,
          appBar: AppBar(
            centerTitle: true,
            automaticallyImplyLeading: false,
            elevation: 0.0,
            backgroundColor: blueTaqati,
            title: const Text('نظام ساعد'),
          ),
          body: ClipRRect(
              borderRadius: BorderRadius.circular(20.0),
              child: Stack(
                children: [
                  WebView(
                    initialUrl: 'https://www.google.com/',
                    javascriptMode: JavascriptMode.unrestricted,
                    gestureRecognizers: gestureRecognizers,
                    onWebViewCreated: (WebViewController controller) {
                      _webViewController = controller;
                    },
                    onPageStarted: (url) {
                      setState(() {
                        loadingPercentage = 0;
                      });
                    },
                    onProgress: (progress) {
                      setState(() {
                        loadingPercentage = progress;
                      });
                    },
                    onPageFinished: (url) {
                      setState(() {
                        loadingPercentage = 100;
                      });
                    },
                  ),
                  if (loadingPercentage < 100)
                    LinearProgressIndicator(
                      value: loadingPercentage / 100.0,
                    ),
                ],
              )),
        ));
  }
}`

**Comment by danagbemava-nc** [comment]
Hi @Amr1440, can you share a screen recording of what exactly you're seeing? I attempted to reproduce with your sample, but it wasn't reloading when I opened the `TextField`.

<details>
<summary>screen recording</summary>

https://user-images.githubusercontent.com/88313112/150130834-e48204e7-5721-4cfe-b4ad-05a912fcbfdd.mp4

</details>

**Comment by Amr1440** [comment]
https://user-images.githubusercontent.com/52917852/150134104-458d33e2-d759-4d34-8aa2-b6176b98fbaf.mov

**Comment by danagbemava-nc** [comment]
Please provide the url that is being used in the screen recording shared.

**Comment by Amr1440** [comment]
www.stackoverflow.com

**Comment by danagbemava-nc** [comment]
Hi @Amr1440, I'm still not able to reproduce your issue. Find the code sample I'm using below. 

I would advise you to check your code well, there may be some event that is happening that may be causing the `Webview` to reload. See screen recording below

<details>
<summary>screen recording</summary>

https://user-images.githubusercontent.com/88313112/150289977-2ebeab17-da5d-40a2-aebe-81f358944423.mov

</details>


<details>
<summary>code sample</summary>

```dart
// ignore_for_file: avoid_print

import 'package:flutter/foundation.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(
    const MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Issue Example',
      home: SupportFollowUpScreen(),
    ),
  );
}

class SupportFollowUpScreen extends StatefulWidget {
  const SupportFollowUpScreen({Key? key}) : super(key: key);

  @override
  State<SupportFollowUpScreen> createState() => _SupportFollowUpScreenState();
}

class _SupportFollowUpScreenState extends State<SupportFollowUpScreen> {
  var loadingPercentage = 0;

  final Set<Factory<OneSequenceGestureRecognizer>> gestureRecognizers = {
    Factory(() => EagerGestureRecognizer())
  };

  late WebViewController _webViewController;

  @override
  Widget build(BuildContext context) {
    return Directionality(
      textDirection: TextDirection.rtl,
      child: Scaffold(
        resizeToAvoidBottomInset: true,
        appBar: AppBar(
          centerTitle: true,
          automaticallyImplyLeading: false,
          elevation: 0.0,
          title: const Text('نظام ساعد'),
        ),
        body: ClipRRect(
          borderRadius: BorderRadius.circular(20.0),
          child: Stack(
            children: [
              WebView(
                // initialUrl: 'https://www.google.com/',
                initialUrl: 'http://www.stackoverflow.com/',
                javascriptMode: JavascriptMode.unrestricted,
                gestureRecognizers: gestureRecognizers,
                onWebViewCreated: (WebViewController controller) {
                  _webViewController = controller;
                },
                onPageStarted: (url) {
                  setState(() {
                    loadingPercentage = 0;
                  });
                },
                onProgress: (progress) {
                  setState(() {
                    loadingPercentage = progress;
                  });
                },
                onPageFinished: (url) {
                  setState(() {
                    loadingPercentage = 100;
                  });
                },
              ),
              if (loadingPercentage < 100)
                LinearProgressIndicator(
                  value: loadingPercentage / 100.0,
                ),
            ],
          ),
        ),
      ),
    );
  }
}

```
</details>

**Comment by Amr1440** [comment]
Maybe the issue is related to navigation bar when it get used in-conjunction with webview ?

**Comment by danagbemava-nc** [comment]
I'm not entirely certain. Kindly provide the sample that was used in your repro video in https://github.com/flutter/flutter/issues/96842#issuecomment-1016435889, preferably without any third-party packages or plugins. 

Thank you
