### ISSUE TITLE
Desktop App build issue

### ISSUE THREAD

**Issue by Gulafsha16** [flutter/flutter#96840]
syncing of data using floor is working fine with build attached to vs code but doesn't works when retrieved form build folder.
command :flutter build windows
flutter version : 2.8.1

**Comment by maheshmnj** [comment]
HI @Gulafsha16, I am having hard time understanding the issue could you please rephrase the issue description and share the reproducible steps along with the build output that your are seeing?

Thanks

**Comment by maheshmnj** [comment]
@Gulafsha16 [floor](https://pub.dev/packages/floor) is a third-party plugin, any issues related to that must be filed in its dedicated repository. 

Closing as this issue is not related to flutter. If you disagree feel free to write in the comments and I will reopen it.

Thank you.
