### ISSUE TITLE
Should we clean up the leak vm after the last shell is destroyed as a default behavior?

### ISSUE THREAD

**Issue by eggfly** [flutter/flutter#96843]
The current `leak_vm` in settings.h defaults to true.

In pure Flutter apps, this doesn't matter. In "add-to-app" scenario, this default setting's advantages and disadvantages are below:
* Pros: It can use for the behavior of "warming-up" the current process's Dart VM instance and leave it for the next engine, it faster than destroying the leak VM;
* Cons: It leaks the VM related memory and resources.

Related issue and change:
* https://github.com/flutter/flutter/issues/95903
* https://github.com/flutter/engine/pull/30541

**Comment by chinmaygarde** [comment]
We tried flipping the switch when the flag was first added it and the pushback was strong because of the reasons you mentioned. Right now, the guidance would be to make this behavior opt-in.
