### ISSUE TITLE
Mixed development of Caton on ios15 crash info : [MLTDebugDevice traceStream] unrecognized selector

### ISSUE THREAD

**Issue by zeqinjie** [flutter/flutter#96861]
## issue

1. In the native app, when the native page is opened on flutter page, it will get stuck when returning to the flutter page. It is strange that the problem occurs on IOS 15, but it is normal when run on IOS 14 system. What's more strange is that it's normal for me to debug IOS 15 with Xcode, but there's a problem with the release package
2. check find is was crash on iOS15 , crash info : `[MLTDebugDevice traceStream] unrecognized selector ` .cause caton

## log
![image](https://user-images.githubusercontent.com/8444646/150160632-aa1919e9-8179-4f0a-8b7b-5dc51972a930.png)

## Crash 
![{f220cacf-bc6f-4a09-aca5-61772dcf1773}](https://user-images.githubusercontent.com/8444646/150293739-d29a36a4-8d3d-4366-9e2f-463e67df3294.png)

**Comment by danagbemava-nc** [comment]
Hi @zeqinjie, by mixed development do you mean your app is an add-to-app scenario? 

Also, can you please provide a complete minimal reproducible code sample as well as the output of `flutter doctor -v`? 

Thank you

**Comment by zeqinjie** [comment]
We found that it was caused by using libMTLCapture.dylib ， remove it was fine
-  Don't refer to this article  [https://www.jianshu.com/p/9e167d6cf884](url)
