### ISSUE TITLE
More Linux/Android resources for staging are needed

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#96864]
Flaky tests and benchmark get moved to staging and need some number of consecutive non-flaky runs in order to move back to prod. However, it looks like staging is under-provisioned, and so achieving that number of runs is going to take a long time. As an example `Linux_android opacity_peephole_fade_transition_text_perf__e2e_summary`, has only been run on 6 out of the last 70 framework commits. There are several other benchmarks that appear to be receiving similar treatment. For contrast `Linux_android animated_placeholder_perf__e2e_summary` has been run on 50 out of the last 70 commits.

Marking P2 to determine whether this is really due to insufficient resources or rather due to a bug in scheduling.

/cc @godofredoc

**Comment by keyonghan** [comment]
We have three linux bots running tasks in staging, three are 4 in idle status (1 motog4 (M), 3 samsung) which are not being scheduled to run tests ever.

A couple of things to move forward:
1) I don't think we need to run all linux/android devicelab tests in staging (https://ci.chromium.org/p/flutter/g/devicelab_staging/console). This consumes most of resources, and causes builds queued up and run in batches. The next time we need to validate any new configs/hardware, we can enable them back to validate and then skip after.
2) We have a KR to support high-end phones in Q1 to make sure benchmarks are collected smoothly. We need to start a plan to run tests in those new testbeds. 

As a short-time workaround, we can limit the number of devicelab tests running in the staging pool, giving room for the real flaky tests validation.

**Comment by keyonghan** [comment]
https://flutter-review.googlesource.com/c/infra/+/25440 to skip ~35 tests migrated from mac/android.

**Comment by keyonghan** [comment]
I believe those flaky tests are now being picked up frequently enough. Here are the top ones
<img width="261" alt="Screen Shot 2022-01-20 at 9 39 42 AM" src="https://user-images.githubusercontent.com/54558023/150392599-97995484-99eb-4837-a211-ce5a8c02ad13.png">

**Comment by godofredoc** [comment]
This issue has been mitigated removing a subset of tests from staging.

**Comment by zanderso** [comment]
Thanks! I think we can close this as fixed, and I'll re-open or file a new one as needed.

**Comment by zanderso** [comment]
It still seems like there is a capacity issue.
<img width="591" alt="Screen Shot 2022-01-20 at 7 33 20 PM" src="https://user-images.githubusercontent.com/6343103/150461196-46596dd2-4574-4613-88d9-9ebb31d48578.png">

Also, there are only two windows bots on staging? They've both been offline for 9+ hours.

<img width="836" alt="Screen Shot 2022-01-20 at 7 36 07 PM" src="https://user-images.githubusercontent.com/6343103/150461362-9fda1887-971c-429a-a20e-4dcb8cc62209.png">

**Comment by keyonghan** [comment]
Yeah, builds are queued up quickly especially when we have several commits merged around the same time.

There are currently 3 linux staging bots running 25 staging linux/android tests, whereas there are 17 linux prod bots running 83 prod linux/android test (with current 90th% queue time 22min, SLO 35 min).

It makes sense to me to migrate, say 2 bots, from prod to staging to help validate the flaky tests for now. We can expand the prod capacity when new bots are available.

For windows bots, opened https://github.com/flutter/flutter/issues/97017.

**Comment by keyonghan** [comment]
Instead of migrating bots between prod and staging, https://flutter-review.googlesource.com/c/infra/+/25566 to run devicelab staging linux tests in A02 testbeds. 
Only benchmarks and `bringup:true` ones are now running on motoG4. This way we are reducing 10 more tests.

**Comment by keyonghan** [comment]
Linux staging builders are being picked up and run in a timely manner now. Will monitor for a while before close.
<img width="112" alt="Screen Shot 2022-01-26 at 3 18 02 PM" src="https://user-images.githubusercontent.com/54558023/151263242-bdab96ce-ed31-4b93-bb9a-c358754580f6.png">

**Comment by keyonghan** [comment]
Builds are running at a frequent pace. Closing.
