### ISSUE TITLE
How does flutter use sqflite or dio in multiple flutter engines?

### ISSUE THREAD

**Issue by ddxl123** [flutter/flutter#96862]
Can a 'Dio dio = Dio()' or 'await openDatabase(path)' be created in each engine?
So if there are 10 engines, I have to create 'Dio dio = Dio()' or 'await openDatabase(path)' 10 times? 

doctor:
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.22533.1001], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.2)
[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
[√] VS Code (version 1.63.2)
[√] Connected device (2 available)

• No issues found!

**Comment by darshankawar** [comment]
@ddxl123 
Your question is better suited for support channels like StackOverflow, so please ask the same there.
Closing from here. If you disagree, write in comments and I'll reopen it.
