### ISSUE TITLE
Defer CocoaPods dependency to as late as possible

### ISSUE THREAD

**Issue by xster** [flutter/flutter#9686]
Not sure I fully understand the current state of plugin tooling but somewhat related to #9580, wondering if it's possible to either
- Have `flutter create` not create a Podfile for iOS
- Have mac._runPodInstall inspect the Podfile more closely to see if any dependencies actually exist rather than check the presence of the file

And only create the CocoaPods dependency when (I don't really know the state of these):
- Use inserts a dart+native plugin in pubspec
- Does something in #7814 and make Podfile declarations while generating the native files

The messaging `Warning: CocoaPods version 1.0.0 or greater not installed. Skipping pod install.` is a bit ambiguous as it does not state what the consequences of continuing is. (#9035)

cc @collinjackson @cbracken

**Comment by collinjackson** [comment]
I played around with this a little bit, and it seems like if there are zero pods in the Podfile, `pod install` finishes fast without downloading the master Cocoapods repo.

So I think we could make this line conditional on whether there are >0 plugins installed.
```
pod 'Flutter', :path => ENV['FLUTTER_FRAMEWORK_DIR']
```

In the simple hello world case it will run quickly, and only download the Cocoapods master spec if you add some plugins.

**Comment by xster** [comment]
I'm overlapping some comments in #9580. Though there's still the case where the user doesn't have cocoapods installed at all. I assume our dart code can't really easily realize whether there's plugins requested by inspecting the podfile without cocoapods. 

Then we're in an uncertain state and tell the user we're potentially missing stuff but we're not sure. 

Maybe the cheaper solution is just to improve the `Warning: CocoaPods version 1.0.0 or greater not installed. Skipping pod install.` message in those case and add that `you don't really have to worry about this if you haven't added any plugins to your project. If you don't know what plugins are, see https://flutter.io/blah. If you're not sure if you did, also don't worry. The build will probably fail anyway and you'll know, then you can install cocoapods by following instructions in flutter doctor` or some more succinct version of it.

**Comment by collinjackson** [comment]
The Flutter tools know if you have plugins installed using the contents of your `.flutter-plugins` file. That could be used to decide whether to run pod install (or not). We could just not bother to try if there are no plugins in the app, and make devs do it manually when they add pods manually.

Improving the warning to make it sound less problematic also seems reasonable to me. If the user already has Cocoapods on their system they likely have a recent-ish Cocoapods repo, so `pod install` won't take forever. It's really the case where they are just now installing Cocoapods installed that we need to be wary of a `pod install` that will run ever for the first time.
