### ISSUE TITLE
Flutter iOS app won't run on a simulator

### ISSUE THREAD

**Issue by alt-DooM** [flutter/flutter#96873]
## What have I tried

1. Flutter clean
2. Delete PodFiles and podfile.lock
3. Delete and recreate ios folder
4. Change deployment version

**Actual results:** 

This:
[FlutterRunOutput.txt](https://github.com/flutter/flutter/files/7900191/FlutterRunOutput.txt)

The app works on Android so far, and I have successfully published it on the Play Store to test (if that helps at all)

 Unfortunately I am not sure how to provide a reproducible issue since this is a pretty big app that I have been developing for android mostly and now just wanted to implement iOS as well. If there are any tips on how to reproduce the issue please let me know

<details>
  <summary>Logs</summary>

Flutter run verbose:
[FlutterRunVerbose.txt](https://github.com/flutter/flutter/files/7900215/FlutterRunVerbose.txt)

Flutter Analyse:
```

Analyzing balkan_streak...                                              

   info • The value of the local variable 'children' isn't used • lib/screens/progress_screen.dart:74:32 • unused_local_variable
   info • The operand can't be null, so the condition is always false • lib/screens/registration_screen.dart:324:54 • unnecessary_null_comparison
   info • Name non-constant identifiers using lowerCamelCase • lib/widgets/coupon_redeem.dart:39:19 • non_constant_identifier_names
   info • The operand can't be null, so the condition is always true • lib/widgets/coupon_redeem.dart:58:34 • unnecessary_null_comparison
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final:
          CustomCheckbox.isChecked • lib/widgets/custom_checkbox.dart:4:7 • must_be_immutable
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final:
          GameCardWidget.lockVisibleLeft, GameCardWidget.lockVisibleRight, GameCardWidget.colorLeft, GameCardWidget.colorRight •
          lib/widgets/game_card.dart:7:7 • must_be_immutable
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final:
          SettingsCard.text • lib/widgets/settings_card.dart:3:7 • must_be_immutable

7 issues found. (ran in 5.9s)
```

Flutter Doctor -v:

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.4 20F71 darwin-x64, locale en-ME)
    • Flutter version 2.8.1 at /Users/danijelpantovic/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (5 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for
      detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at
    /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for
      detailed instructions).

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (1 available)
    • iPhone 8 Plus (mobile) • 5BE9C34C-E0BA-49C7-A726-D49938A7F2AC • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)

! Doctor found issues in 3 categories.
```

Podfile:

```dart
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup
platform :ios, '12.0'
target 'Runner' do
  use_frameworks!
  use_modular_headers!
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Analytics'
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
     flutter_additional_ios_build_settings(target)
   target.build_configurations.each do |config|
    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
   end
  end
 end
```

Pubscpec:

```dart
name: montenegro_streak_project
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.1.0
  firebase_core: ^1.2.0
  http: ^0.13.3
  firebase_database: ^8.1.0
  firebase_auth: ^3.2.0
  provider: ^5.0.0
  persistent_bottom_nav_bar: any
  cached_network_image: ^3.0.0
  material_dialogs: ^1.1.1
  lottie: ^1.2.1
  url_launcher: ^6.0.15
  cloud_functions: ^3.1.1
  firebase_messaging: ^11.1.0
  flutter_local_notifications: ^9.1.0
  email_validator: any
  flutter_pw_validator: ^1.3.0
  flutter_launcher_icons: ^0.9.2
  change_app_package_name: ^1.0.0
  auto_size_text: ^3.0.0
  marquee: ^2.2.0
  shared_preferences: ^2.0.9
  step_progress_indicator: ^1.0.1
  dotted_line: ^3.1.0
  screenshot: ^1.2.3
  connectivity_plus: ^2.2.0

  
  
  
  
 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "images/new_logo_balkan_streak.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SofiaProMedium
      fonts:
        - asset: fonts/sofiapromedium.OTF
    - family: SofiaProLight
      fonts:
        - asset: fonts/sofiaprolight.OTF
    - family: SofiaProSemiBold
      fonts:
        - asset: fonts/sofiaprosemibold.OTF
    - family: SofiaProBold
      fonts:
        - asset: fonts/sofiaprobold.OTF
    - family: Trueno
      fonts:
        - asset: fonts/trueno.otf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```

</details>

**Comment by darshankawar** [comment]
@alt-DooM 
From the log you provided, it seems to be failing due to:

```
`GeneratedPluginRegistrant.h:10:9: error: could not build module 'Flutter'
    #import <Flutter/Flutter.h

<unknown>:0: error: failed to emit precompiled header    `
```

Can you attach your `ios/Runner.xcodeproj/project.pbxproj` ?

**Comment by alt-DooM** [comment]
> @alt-DooM From the log you provided, it seems to be failing due to:
> 
> ```
> `GeneratedPluginRegistrant.h:10:9: error: could not build module 'Flutter'
>     #import <Flutter/Flutter.h
> 
> <unknown>:0: error: failed to emit precompiled header    `
> ```
> 
> Can you attach your `ios/Runner.xcodeproj/project.pbxproj` ?

Here it is:
[RunnerProject.txt](https://github.com/flutter/flutter/files/7905076/RunnerProject.txt)

**Comment by darshankawar** [comment]
@alt-DooM 
Do you see `Run Script` inside `Targets` in Xcode  or have `Install builds only` checked ?
Also, can you confirm if you by any chance have Anaconda or ruby or python installed ?

**Comment by alt-DooM** [comment]
> @alt-DooM
> Do you see `Run Script` inside `Targets` in Xcode or have `Install builds only` checked ?
> Also, can you confirm if you by any chance have Anaconda or ruby or python installed ?

This is what is in the Run Script:
<img width="692" alt="Screenshot 2022-01-21 at 12 12 29" src="https://user-images.githubusercontent.com/83878827/150517668-c97c65f4-8ed9-4b56-897c-5295831a7cda.png">

I do have only python installed

**Comment by darshankawar** [comment]
@alt-DooM 
Does it run properly through Xcode ? If not, can you provide the xcode error log too ?

**Comment by alt-DooM** [comment]
> @alt-DooM Does it run properly through Xcode ? If not, can you provide the xcode error log too ?

I get 38 build errors on it, I'm not sure where can I view the logs for the issues ?

**Comment by darshankawar** [comment]
@alt-DooM 
Can you try to create a fresh app and run it on simulator and see if it still gives you same error or not ?

**Comment by alt-DooM** [comment]
> @alt-DooM
> Can you try to create a fresh app and run it on simulator and see if it still gives you same error or not ?

Fresh app works without issues, but this one that I have been working on for a couple months now gives me a heap of errors for some reason
<img width="234" alt="Screenshot 2022-01-25 at 16 24 29" src="https://user-images.githubusercontent.com/83878827/151005979-a5113ac9-4047-431b-96a3-3f38c7950a7b.png">

**Comment by darshankawar** [comment]
@alt-DooM 
In you `ios/podfile`, try adding below inside `post_install` section and see if it helps:

```
    target.build_configurations.each do |config|
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
    end
```

e.g:

```
post_install do |installer|
   installer.pods_project.targets.each do |target|
     flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
    end
```

**Comment by darshankawar** [comment]
> @alt-DooM In you `ios/podfile`, try adding below inside `post_install` section and see if it helps:
> 
> ```
>     target.build_configurations.each do |config|
>       config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
>     end
> ```
> 
> e.g:
> 
> ```
> post_install do |installer|
>    installer.pods_project.targets.each do |target|
>      flutter_additional_ios_build_settings(target)
>     target.build_configurations.each do |config|
>       config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
>     end
> ```

If above doesn't work, try below:

`config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64 x86_64'`

**Comment by alt-DooM** [comment]
> @alt-DooM In you `ios/podfile`, try adding below inside `post_install` section and see if it helps:
> 
> ```
>     target.build_configurations.each do |config|
>       config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
>     end
> ```
> 
> e.g:
> 
> ```
> post_install do |installer|
>    installer.pods_project.targets.each do |target|
>      flutter_additional_ios_build_settings(target)
>     target.build_configurations.each do |config|
>       config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
>     end
> ```

First solution:
[firstSolution.txt](https://github.com/flutter/flutter/files/7941220/firstSolution.txt)

Second solution:
[secondSolution.txt](https://github.com/flutter/flutter/files/7941232/secondSolution.txt)

**Comment by alt-DooM** [comment]
> > @alt-DooM In you `ios/podfile`, try adding below inside `post_install` section and see if it helps:
> > ```
> >     target.build_configurations.each do |config|
> >       config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
> >     end
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > e.g:
> > ```
> > post_install do |installer|
> >    installer.pods_project.targets.each do |target|
> >      flutter_additional_ios_build_settings(target)
> >     target.build_configurations.each do |config|
> >       config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
> >     end
> > ```
> 
> If above doesn't work, try below:
> 
> `config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64 x86_64'`

Tried this as well as the second solution but no luck

Is it worth it to create a new project and copy files over to it or would that be too much of a hassle ?

**Comment by darshankawar** [comment]
@alt-DooM 
From the error screenshot you shared earlier, it seems to be pointing to objective C files. Is your project developed in Objective C ? 


> Is it worth it to create a new project and copy files over to it or would that be too much of a hassle ?

You may try that which will be generated in Swift.

**Comment by alt-DooM** [comment]
> @alt-DooM From the error screenshot you shared earlier, it seems to be pointing to objective C files. Is your project developed in Objective C ?
> 
> > Is it worth it to create a new project and copy files over to it or would that be too much of a hassle ?
> 
> You may try that which will be generated in Swift.

Nope, everything is in Dart

Not sure what else to try honestly, are there any xcode settings I should be aware of ?

**Comment by yahu1031** [comment]
No @alt-DooM he meant ios language must be set to swift. And try recreating project

**Comment by bantunes22** [comment]
I've same problem with this plugin. 

Build is ok, but when running we got this error:

`Symbol not found: _OBJC_CLASS_$_Reachability`

PS: The app is using OBJ-C, we need this because of some native SDK's.

**Comment by alt-DooM** [comment]
> No @alt-DooM he meant ios language must be set to swift. And try recreating project [like this](https://stackoverflow.com/questions/49069957/create-a-flutter-project-with-swift)

Oh okay, so just to make sure we are on the same page, I can create a project and it will run fine, but when trying to run a project I have transferred from Windows to Mac I get these errors

**Comment by darshankawar** [comment]
@bantunes22 
That sounds like a different issue, so please file a new issue using template.

@alt-DooM 


> And try recreating project [like this](https://stackoverflow.com/questions/49069957/create-a-flutter-project-with-swift)

**Comment by alt-DooM** [comment]
> @bantunes22 That sounds like a different issue, so please file a new issue using template.
> 
> @alt-DooM
> 
> > And try recreating project [like this](https://stackoverflow.com/questions/49069957/create-a-flutter-project-with-swift)

Okay so just to make sure we are on the same page, you suggest I create a new project following the steps from the link you provided, then transfer all the needed files from my old project that we are currently trying to fix ?

Can that new project be the same as this one or will I run into publishing issues on Google Play or iOS Store if package names are different and such ?

**Comment by yahu1031** [comment]
If package names are different then it will make an issue. So, make sure your package names are the same, and make sure you have implemented your native functionalities if you have any. The code change won't make any effect AFAIK.

**Comment by alt-DooM** [comment]
> @bantunes22 That sounds like a different issue, so please file a new issue using template.
> 
> @alt-DooM
> 
> > And try recreating project [like this](https://stackoverflow.com/questions/49069957/create-a-flutter-project-with-swift)

The issue has been fixed by creating a new project on my Mac device then transferring all the code to it.

So I guess some paths are hardcoded into the project it seems since transferring it from Windows to Mac via File Transfer or Dropbox and stuff like that does not work

**Comment by yahu1031** [comment]
@alt-DooM I don't think so. Cause whenever you move files from mac to windows, You will be creating a separate folder with mac code. And the rest folder is original code that will be automatically migrated AFAIK(Correct me if I'm wrong). And if you are talking about the package paths, Then they will be autocorrected when you run flutter pub get. So That might not be an issue too.

**Comment by darshankawar** [comment]
@yahu1031 Thanks for your input.

@alt-DooM Considering your last comment, I am going ahead and closing this as resolved. If you face similar behavior again, feel free to open a new issue with all required details.

Thanks.
