### ISSUE TITLE
Input validation

### ISSUE THREAD

**Issue by arcas0803** [flutter/flutter#9689]
This is a request not an issue. Is possible to set in the validator a correct answer. For example if you are trying to verify a password in a second input field paint green as the input is correct. 
Use the validator to show errors and success.

**Comment by eseidelGoogle** [comment]
@xster or @cbracken might know?

**Comment by xster** [comment]
Sounds like you already found it but TextFormField.validator is the right place to start. See an example in https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/material/text_form_field_demo.dart for instance.

**Comment by Hixie** [comment]
As far as I can tell this is already possible, as @xster describes above. Please open a new bug if we misunderstood. Thanks!
