### ISSUE TITLE
Separate auto-submit logic to its own service

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#96896]
The auto-submit bot is currently used to enforce code review, testing and tree openness rules for Flutter repositories. This functionality can be generalized to be used to Dart GitHub repositories.

The steps to make this generic are:

- [x] Separate the bot functionality to its own service
- [x] Abstract it as a github application

**Comment by godofredoc** [comment]
\cc @CaseyHillers @keyonghan

**Comment by godofredoc** [comment]
@keyonghan  are we already reading configurations from the repos under test or the org undertest?

**Comment by keyonghan** [comment]
> @keyonghan are we already reading configurations from the repos under test or the org undertest?

What configs? 
Webhook is configured/triggered on repo level;
Git authentication is on project level (relying on installation id).

**Comment by keyonghan** [comment]
No, the bot is not referencing any configs from there.
