### ISSUE TITLE
Flutter 2.8.1 DropdownButtonFormField unable to set initial value (Web)

### ISSUE THREAD

**Issue by s33m0n** [flutter/flutter#96905]
## Steps to Reproduce
- Testing on **Flutter 2.8.1 Stable for Web**. Debug is working as expected but when deployed to **test** or **production**, it fails.
- DropdownButton is fine, only issue is with **DropdownButtonFormField**!
- When you set initial value for DropdownButtonFormField, the Dropdown is (looks) empty.
- After selecting value from the Dropdown, it's successfully set and visible.
- It worked in previous Flutter version 2.5.3 Stable.
- Issue looks very similar to this one [issue-56716](https://github.com/flutter/flutter/issues/56716)

**Expected results:**
- Expecting initial value to be shown same as it was in Flutter 2.5.3 Stable.

**Actual results:**
- DropdownButtonFormField shows as empty

<details>
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-CZ)

[✓] Chrome - develop for the web
[✗] Flutter IDE Support (No supported IDEs installed)
[✓] Connected device (1 available)
</details>

**Comment by s33m0n** [comment]
This is a very basic example that shows DropdownButton and DropdownButtonFormField. 
- DropdownButton works as expected and shows initially set value.
- DropdownButtonFormField unfortunately doesn't show the initially set value.
- When run in debug, everything is working as expected but DropdownButtonFormField is not working properly when we deploy it on the web (production)

```
import 'package:flutter/material.dart';

class MinimalDropdown extends StatefulWidget {
  const MinimalDropdown({Key? key}) : super(key: key);

  @override
  State<MinimalDropdown> createState() => _MinimalDropdownState();
}

class _MinimalDropdownState extends State<MinimalDropdown> {
  String? selectedValue = 'A';

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        DropdownButton<String>(
          value: selectedValue,
          items: ['A', 'B', 'C']
              .map(
                (String item) => DropdownMenuItem<String>(
                  child: Text(item),
                  value: item,
                ),
              )
              .toList(),
          onChanged: (String? value) {
            setState(() {
              selectedValue = value;
            });
          },
        ),
        DropdownButtonFormField<String>(
          value: selectedValue,
          items: ['A', 'B', 'C']
              .map(
                (String item) => DropdownMenuItem<String>(
                  child: Text(item),
                  value: item,
                ),
              )
              .toList(),
          onChanged: (String? value) {
            setState(() {
              selectedValue = value;
            });
          },
        ),
      ],
    );
  }
}
```

**WEB / Deployment**
```
flutter build web --release --web-renderer canvaskit -t lib/main.dart"
```

**WEB / index.html**
```
<script>
  window.flutterWebRenderer = 'canvaskit';
</script>
```

**Comment by danagbemava-nc** [comment]
I've deployed a sample app to firebase hosting using your sample and the commands you run and the `DropdownButtonFormField` is working as expected. Site can be found https://test-2f735.web.app/#/. Is there any more information that you can provide?

<details>
<summary>file contents</summary>

`web/index.html`

```html
<!DOCTYPE html>
<html>

<head>
  <!--
    If you are serving your web app in a path other than the root, change the
    href value below to reflect the base path you are serving from.

    The path provided below has to start and end with a slash "/" in order for
    it to work correctly.

    For more details:
    * https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base

    This is a placeholder for base href that will be replaced by the value of
    the `--base-href` argument provided to `flutter build`.
  -->
  <base href="$FLUTTER_BASE_HREF">

  <meta charset="UTF-8">
  <meta content="IE=Edge" http-equiv="X-UA-Compatible">
  <meta name="description" content="A new Flutter project.">

  <!-- iOS meta tags & icons -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="it">
  <link rel="apple-touch-icon" href="icons/Icon-192.png">

  <!-- Favicon -->
  <link rel="icon" type="image/png" href="favicon.png" />

  <title>it</title>
  <link rel="manifest" href="manifest.json">
</head>

<body>
  <!-- This script installs service_worker.js to provide PWA functionality to
       application. For more information, see:
       https://developers.google.com/web/fundamentals/primers/service-workers -->
  <script>
    var serviceWorkerVersion = null;
    var scriptLoaded = false;
    function loadMainDartJs() {
      if (scriptLoaded) {
        return;
      }
      scriptLoaded = true;
      var scriptTag = document.createElement('script');
      scriptTag.src = 'main.dart.js';
      scriptTag.type = 'application/javascript';
      document.body.append(scriptTag);
    }

    if ('serviceWorker' in navigator) {
      // Service workers are supported. Use them.
      window.addEventListener('load', function () {
        // Wait for registration to finish before dropping the <script> tag.
        // Otherwise, the browser will load the script multiple times,
        // potentially different versions.
        var serviceWorkerUrl = 'flutter_service_worker.js?v=' + serviceWorkerVersion;
        navigator.serviceWorker.register(serviceWorkerUrl)
          .then((reg) => {
            function waitForActivation(serviceWorker) {
              serviceWorker.addEventListener('statechange', () => {
                if (serviceWorker.state == 'activated') {
                  console.log('Installed new service worker.');
                  loadMainDartJs();
                }
              });
            }
            if (!reg.active && (reg.installing || reg.waiting)) {
              // No active web worker and we have installed or are installing
              // one for the first time. Simply wait for it to activate.
              waitForActivation(reg.installing || reg.waiting);
            } else if (!reg.active.scriptURL.endsWith(serviceWorkerVersion)) {
              // When the app updates the serviceWorkerVersion changes, so we
              // need to ask the service worker to update.
              console.log('New service worker available.');
              reg.update();
              waitForActivation(reg.installing);
            } else {
              // Existing service worker is still good.
              console.log('Loading app from service worker.');
              loadMainDartJs();
            }
          });

        // If service worker doesn't succeed in a reasonable amount of time,
        // fallback to plaint <script> tag.
        setTimeout(() => {
          if (!scriptLoaded) {
            console.warn(
              'Failed to load app from service worker. Falling back to plain <script> tag.',
            );
            loadMainDartJs();
          }
        }, 4000);
      });
    } else {
      // Service workers not supported. Just drop the <script> tag.
      loadMainDartJs();
    }
  </script>

  <script>
    window.flutterWebRenderer = 'canvaskit';
  </script>
</body>

</html>
```

`lib/main.dart`

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(home: MinimalDropdown());
  }
}

class MinimalDropdown extends StatefulWidget {
  const MinimalDropdown({Key? key}) : super(key: key);

  @override
  State<MinimalDropdown> createState() => _MinimalDropdownState();
}

class _MinimalDropdownState extends State<MinimalDropdown> {
  String? selectedValue = 'A';

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        DropdownButton<String>(
          value: selectedValue,
          items: ['A', 'B', 'C']
              .map(
                (String item) => DropdownMenuItem<String>(
                  child: Text(item),
                  value: item,
                ),
              )
              .toList(),
          onChanged: (String? value) {
            setState(() {
              selectedValue = value;
            });
          },
        ),
        DropdownButtonFormField<String>(
          value: selectedValue,
          items: ['A', 'B', 'C']
              .map(
                (String item) => DropdownMenuItem<String>(
                  child: Text(item),
                  value: item,
                ),
              )
              .toList(),
          onChanged: (String? value) {
            setState(() {
              selectedValue = value;
            });
          },
        ),
      ],
    );
  }
}
```
</details>

<details>
<summary>video </summary>


https://user-images.githubusercontent.com/88313112/151306418-f1d3378b-b06f-4928-9b5f-da73a0c1b407.mov



</details>

**Comment by s33m0n** [comment]
Thank you @danagbemava-nc for your time testing the project.

I spent hours debugging the problem in our project. It seems that out of 20 or so Widgets (screens), there are 3 of them with deep subtree causing above issue.

Problem is that at every location (Screen) the issue seems to be different and doesn't make any sense as why it happens. 
These Widgets are not even used during testing of this issue. They are just compiled.

One example is this:

```
import 'package:collection/collection.dart';

Template? _originalTemplate;

@override
  void didUpdateWidget(covariant TournamentRowWidget oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (oldWidget.availableTemplates != widget.availableTemplates) {
      setState(() {
        availableTemplates = widget.availableTemplates;
        _originalTemplate = availableTemplates.firstWhereOrNull(
          (Template template) => template.id == tournament.clientTemplate?.id,
        );

        _chosenTemplate = _originalTemplate;
      });
    }
  }
```

`_originalTemplate` is variable that is used as value of a DropdownButtonFormField.

The above code causes the **DropdownButtonFormField** to **NOT** show the value at the start. **ANY** DropdownButtonFormField, **ANYWHERE** in the code won't have the "initial" value shown until user actually selects some value from the Dropdown.

I would like to stress out again that this part of code is NOT used anywhere, meaning that it just sits somewhere in the dart file and it's not even presented to the user. 

We use **flutter_bloc**, **Beamer** (navigation) and other packages. We suspected that they could cause some issues  but we isolated 3 issues that when those part of code is commented, it starts working, regardless of packages used. 

When we comment those 2 lines with firstWhereOrNull, the issue disappears and the strangest thing is when we swap **firstWhereOrNull** with **singleWhereOrNull** it starts working too.

As I said, I spend more than 12hours debugging this code and it just doesn't make any sense. Unfortunately I can't share code from our project here so is there any way (Discord, ...) I could contact someone from support to show them the issues and discuss it further?

**Comment by danagbemava-nc** [comment]
Hi @s33m0n, there may very well be a bug in flutter that we need to fix. If that is the case, I would very much appreciate it if you could isolate the code that causes the issue into a reproducible sample so that we can fix the issue. 

Thank you

**Comment by s33m0n** [comment]
This will be pretty hard to reproduce. I am trying to make a reproducible sample but our project is pretty big and I haven't had luck pinpointing the source of the problem...

**Comment by danagbemava-nc** [comment]
Without a complete minimal reproducible sample, the issue is not actionable. Let's keep this open until you can come up with either a sample or a pattern of reproduction.

**Comment by s33m0n** [comment]
Ok, Just an update... So I pinpointed it to two packages that we use. 
First one is **synchronized**: [https://pub.dev/packages/synchronized](https://pub.dev/packages/synchronized)
Second one is **graphql**: [https://pub.dev/packages/graphql](https://pub.dev/packages/graphql)

For the first package, wrapping the method inside a **Lock** causes this issue.
For the second package, only use of a specific code (initializing a Client object from **graphql** package) causes this issue. This is pretty strange in my opinion. 

Both packages were not updated for 8+ months. Could this be an issue between dart versions bundled inside the stable versions?
Keeping in mind that there were no issues with previous stable **Flutter version 2.5.3**

In the meantime I am still trying to reproduce the minimal sample.

**Comment by danagbemava-nc** [comment]
> Could this be an issue between dart versions bundled inside the Flutter stable versions?

There's a possibility, I just checked the changelog for flutter 2.8, and the only PR that was filed related to `DropdownButtonFormField` was a documentation PR and `DropdownButtonFormField` uses a `DropdownButton` underneath, so there's a chance the issue lies elsewhere. 

Do bear in mind that for this to be a framework issue, we will need a sample without any third-party packages since framework issues ideally should be reproducible using only the code from the framework/dart.

**Comment by s33m0n** [comment]
[danagbemava-nc](https://github.com/danagbemava-nc) Another small update. I was able to "fix" this issue by editing Flutter's `Form.dart` class like this.
So essentially removing the `late` keyword and settings the `widget.value` inside the `initState()`

```
 /// The current state of a [FormField]. Passed to the [FormFieldBuilder] method
 /// for use in constructing the form field's widget.
 class FormFieldState<T> extends State<FormField<T>> with RestorationMixin {
-  late T? _value = widget.initialValue;
+  T? _value;
+
+  @override
+  void initState() {
+    super.initState();
+    _value = widget.initialValue;
+  }

  ...
  ...

 }
```

Can you please look into this as to why it could work with this approach? Thank you

**Comment by danagbemava-nc** [comment]
Hi @s33m0n, from what I can see, the commit that added the line of code you removed has been in the framework since before v.2.5.3. This is the commit https://github.com/flutter/flutter/commit/3eeadc28f36213f426361968c13b3657bc698cef. 

Since you didn't encounter this issue prior to 2.8.1, I'm not entirely sure that the issue has been "fixed" completely. 

We will need a sample or pattern which consistently reproduces the issue to take this forward.
