### ISSUE TITLE
[image_picker]  `_picker.pickMultiImage` launches camera instead of gallery on IOS 12

### ISSUE THREAD

**Issue by dirkvranckaert** [flutter/flutter#96903]
I'm using the image_picker dependency for my application and I'm using it both for image and video selection.

However for video selection I used to execute `_picker.pickMultiImage(..)` which seems to be working fine on Android and on latest iOS devices.
However users are now reporting that on iOS12 this triggers the camera instead of the image pickers.

The release notes state: 
```
0.8.1
Add a new method getMultiImage to allow picking multiple images on iOS 14 or higher and Android 4.3 or higher. Returns only 1 image for lower versions of iOS and Android.
```

So I would suspect if I run this on an iOS12 device to just launch the single image picker instead, however I suspect that in this fallback scenario that is implemented the image source is defaulted to camera instead of gallery.

To make it work however I needed to write myself something like this:
```dart
    if (Platform.isIOS) {
      var operatingSystemVersion = Platform.operatingSystemVersion;
      logger.d("Detected iOS device. Version: $operatingSystemVersion");
      var iosVersion = double.parse(operatingSystemVersion.split(" ")[1]);
      if (iosVersion < 14.0) {
        logger.d("iOS device does not support multi image selection, falling back to single image selection");
        var imageFiles = _picker.pickImage(
          source: ImageSource.gallery,
          imageQuality: 50,
          maxWidth: 1024,
          maxHeight: 1024,
        );
        imageFiles.then((file) {
          if (file != null) {
            AnalyticsManager.event(AnalyticsEvent.ON_EDIT_MESSAGE_ADD_ATTACHMENT_IMAGE_SELECTED, parameters: {"count": 1});
            Navigator.pop(context);
            _openAttachmentsPane();
            logger.d("Image file selection done");
            _processImageAttachmentfile(MXFile(file));
          } else {
            AnalyticsManager.event(AnalyticsEvent.ON_EDIT_MESSAGE_ADD_ATTACHMENT_IMAGE_SELECTION_CANCELLED);
            logger.d("No image selected...");
          }
        });
        return;
      }
    }
```

So this works for me, however I think it should be fixed in the library to fallback to the gallery source instead of the camera source.

**Comment by darshankawar** [comment]
@dirkvranckaert 
Since I don't have iOS 12 to confirm this behavior, do you by any chance have iOS 12 to confirm this ?

**Comment by dirkvranckaert** [comment]
@darshankawar Yes I tried on a iOS 12.4 simulator and could verity this issue. 
That is how I also verified my workaround to be working correctly.

But since you need to launch the single image picker with a source specified and the default is `camera` I assume it's just a 'mistake' in which the source is either not or wrongly specified in the fallback scenario.

**Comment by darshankawar** [comment]
Thanks for confirmation. Labeling it for further input from the team, as I don't have iOS 12 (simulator or device) to verify this behavior.

**Comment by jmagman** [comment]
> as I don't have iOS 12 (simulator or device) to verify this behavior.

@darshankawar for future reference, you can download different simulator runtime versions in Xcode > Window > Devices and Simulators > Simulators > + > OS Version > Download more simulator runtimes...

**Comment by ENUUI** [comment]
Copied from [image_picker](https://github.com/flutter/plugins/blob/main/packages/image_picker/image_picker/ios/Classes/FLTImagePickerPlugin.m).
```
 if ([@"pickMultiImage" isEqualToString:call.method]) {
    if (@available(iOS 14, *)) {
      self.result = result;
      _arguments = call.arguments;
      [self pickImageWithPHPicker:0];
    } else {
      [self pickImageWithUIImagePicker];
    }
  }
```

```
- (void)pickImageWithUIImagePicker {
  _imagePickerController = [[UIImagePickerController alloc] init];
  _imagePickerController.modalPresentationStyle = UIModalPresentationCurrentContext;
  _imagePickerController.delegate = self;
  _imagePickerController.mediaTypes = @[ (NSString *)kUTTypeImage ];

  int imageSource = [[_arguments objectForKey:@"source"] intValue];

  self.maxImagesAllowed = 1;

  switch (imageSource) {
    case SOURCE_CAMERA:
      [self checkCameraAuthorization];
      break;
    case SOURCE_GALLERY:
      [self checkPhotoAuthorization];
      break;
    default:
      self.result([FlutterError errorWithCode:@"invalid_source"
                                      message:@"Invalid image source."
                                      details:nil]);
      break;
  }
}
```
`_arguments` has never been assigned a value in versions below IOS 14.

`source` is also not in the parameter of `pickMultiImage`.

**Comment by ENUUI** [comment]
> Copied from [image_picker](https://github.com/flutter/plugins/blob/main/packages/image_picker/image_picker/ios/Classes/FLTImagePickerPlugin.m).
> 
> ```
>  if ([@"pickMultiImage" isEqualToString:call.method]) {
>     if (@available(iOS 14, *)) {
>       self.result = result;
>       _arguments = call.arguments;
>       [self pickImageWithPHPicker:0];
>     } else {
>       [self pickImageWithUIImagePicker];
>     }
>   }
> ```
> 
> ```
> - (void)pickImageWithUIImagePicker {
>   _imagePickerController = [[UIImagePickerController alloc] init];
>   _imagePickerController.modalPresentationStyle = UIModalPresentationCurrentContext;
>   _imagePickerController.delegate = self;
>   _imagePickerController.mediaTypes = @[ (NSString *)kUTTypeImage ];
> 
>   int imageSource = [[_arguments objectForKey:@"source"] intValue];
> 
>   self.maxImagesAllowed = 1;
> 
>   switch (imageSource) {
>     case SOURCE_CAMERA:
>       [self checkCameraAuthorization];
>       break;
>     case SOURCE_GALLERY:
>       [self checkPhotoAuthorization];
>       break;
>     default:
>       self.result([FlutterError errorWithCode:@"invalid_source"
>                                       message:@"Invalid image source."
>                                       details:nil]);
>       break;
>   }
> }
> ```
> 
> `_arguments` has never been assigned a value in versions below IOS 14.
> 
> `source` is also not in the parameter of `pickMultiImage`.
I tried to fix. [4706](https://github.com/flutter/plugins/pull/4706)

**Comment by mvanbeusekom** [comment]
@ENUUI's analysis was correct and points out two bugs:

1.  The `ImagePicker.pickMultiImage` call doesn't define a `source` parameter as part of the arguments. This makes sense since you cannot pick multiple images from the camera and for this reason the iOS 14+ `PHPicker` control doesn't support selecting images from the camera. This means the expected behaviour here should be to always show the gallery which is does on iOS 14+ but on iOS 13 and lower the `ImagePicker.pickMultiImage` method will fallback on the implementation using the `UIImagePicker` control which defaults to showing the camera if no source is supplied. 
2. When make a call to `ImagePicker.pickMultiImage` on pre-iOS 14 devices the supplied `arguments` and `result` are not made available to the `UIImagePicker` control. This means that supplied dimensions are not taken into account and a result is never delivered back to Dart on pre-iOS 14 devices.

The PR created by @ENUUI was not complete, so I decided to create a new PR (#4718) myself containing a fix for both issues.
