### ISSUE TITLE
Flexible and Expanded not working as expected

### ISSUE THREAD

**Issue by KristianBalaj** [flutter/flutter#96917]
Having the following code sample

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Column(
        children: [
          const Icon(Icons.description),
          const Flexible(
            child: SizedBox(
              height: 80,
            ),
          ),
          SizedBox(
              height: 90,
              child: ElevatedButton(onPressed: () {}, child: const Text('A'))),
          SizedBox(
            height: 90,
            child: ElevatedButton(onPressed: () {}, child: const Text('B')),
          ),
          SizedBox(
            height: 90,
            child: ElevatedButton(onPressed: () {}, child: const Text('C')),
          ),
          const Spacer(),
          SizedBox(
            height: 90,
            child: ElevatedButton(onPressed: () {}, child: const Text('D')),
          ),
        ],
      ),
    );
  }
}
```
</details>

I get the following behaviour:
<img width="95" alt="image" src="https://user-images.githubusercontent.com/20045353/150344029-811655ce-46fa-4149-9b2c-af8c26230746.png">

## Actual behaviour
 As you can see there is an empty space underneath the last Button (the D button). This is not expected behaviour since there is the `Spacer` widget (`Expanded`) that should fill all the available space.

## Expected behaviour
I would expect the D button to be at the bottom of the `Column`.

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale en-GB)
    • Flutter version 2.8.1 at /Users/kristian/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (5 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/kristian/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • iPhone SE (2nd generation) (mobile) • 6A55A945-BAAC-44E8-A90A-F96F8780E4C1 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 97.0.4692.71

• No issues found!
```
</details>

**Comment by arnold-parge** [comment]
It doesn't make sense to add a `SizedBox` (_a widget with known height_) in a `Flexible`.

Just remove the Flexible and it will work as expected.

**Comment by KristianBalaj** [comment]
Yeah, but I wanted to achieve a behaviour where in case of missing space the sizedbox would shrink and be of size maximally 80 units.

**Comment by darshankawar** [comment]
@KristianBalaj 
`Flexible` and `Expanded` widgets are really vast subjects and we would probably need to look into them as how they function and their usage to clearly understand their correct implementation. You may check out these articles and see if they help.
https://medium.com/@apmntechdev/flutter-expanded-and-flex-cfd4e9f1e069
https://medium.com/flutter-community/flutter-layout-cheat-sheet-5363348d037e

**Comment by KristianBalaj** [comment]
I didn't find any clue of this issue in neither of the articles.

I find it a bug resulting in a combination of Flexible and Expanded in a single Flex widget.

**Comment by darshankawar** [comment]
@KristianBalaj 
Can you try to make use of `Align` which has `alignment: Alignment.bottomCenter` property and see if it helps ?

**Comment by KristianBalaj** [comment]
@darshankawar nope that does not help.

**Comment by darshankawar** [comment]
@KristianBalaj 
Does adding `height` and `MainAxisAlignment.spaceEvenly` properties help ?
Since you are using `Expanded` + `Flexible` both at the same time, we might have to make use of other properties like above.
