### ISSUE TITLE
'Build Project' action doesn't work for flutter projects

### ISSUE THREAD

**Issue by darrellpf** [flutter/flutter#9691]
## Steps to Reproduce

Make a new flutter project

Intellij says frameworks detected
  - configure
 - click Android manifest.xml
  - message is Android Facet added
Click the build button
Error : Android source generator : [Android] Android Manifest.xml file not found

## Flutter Doctor
[✓] Flutter (on Linux, channel master)
    • Flutter at /home/darrell/flutter
    • Framework revision a4ba761bea (26 hours ago), 2017-04-28 16:01:14 -0700
    • Engine revision da8ebf40bd
    • Tools Dart version 1.23.0-dev.11.11

[✓] Host Executable Compatibility
    • Downloaded executables execute on host

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /home/darrell/Android/Sdk
    • Platform android-25, build-tools 25.0.2
    • Java binary at: /home/darrell/android-studio/jre/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b736)

[✓] Android Studio (version 2.4)
    • Android Studio at /home/darrell/android-studio
    • Gradle version 3.4.1
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b736)

[✓] IntelliJ IDEA Community Edition (version 2017.1)
    • Dart plugin version 171.4424.10
    • Flutter plugin version 13.0

[✓] Connected devices
    • None

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by eseidelGoogle** [comment]
@devoncarew would know.

**Comment by eseidelGoogle** [comment]
Could you give me more information on what parts don't work?  Is it the Android/Java integration in IntelliJ?  Or when you hit the Run button it doesn't run on the attached device?  Something else?

**Comment by darrellpf** [comment]
Intellij Android/Java integration is broken.

When a new project is made Intellij does detect that an Android facet it required. The event log says

5/1/17
8:56 AM	Frameworks detected: Android framework is detected in the project Configure

Clicking Configure brings up a "Setup Frameworks" dialog.

![image](https://cloud.githubusercontent.com/assets/2779084/25584818/72c3e5f8-2e4c-11e7-9fc2-7fef23629e27.png)

with Android and AndroidManfest.xml checked. Selecting AndroidManifest.xml puts a message in the bottom of the dialog saying

Andriod facet will be added to the "Andoid Module". Clicking OK in the dialog results in a presumably workable project.

Clicking "Build Project" at the top of the IDE results in 

Error:Android Source Generator: [android] AndroidManifest.xml file not found

Opening the project structure dialog shows that an Android module SDK has been chosen.

Since the project fails to build at all the Run button is not highlighted.

**Comment by devoncarew** [comment]
Adding @skybrian for general expertise on our Android source support.

> Since the project fails to build at all the Run button is not highlighted.

This issue is likely orthogonal - Flutter projects don't use or need the the build support from Build Project. The run button should be enabled if you have a flutter launch configuration selected in the pulldown (all flutter projects should at least have one for `main.dart`), and a device connected and detected. W/ this bit at the end of flutter doctor: `[✓] Connected devices • None`, the run button should become enabled once you connect a device.

**Comment by skybrian** [comment]
Confirmed that "Build Project" results in that error. Apparently IDEA's Android integration expects the manifest file to be at module root, but it's actually in android/app/src/main.

(Building the project does work if you don't enable Android framework, but it only compiles the Java files to .class files.)

I tried removing the "android" module and importing android/app/src/main into IDEA as an Android module. It gets further but doesn't know where to find the Flutter classes.

**Comment by devoncarew** [comment]
I'm splitting the run-button-not-enabled issue out into https://github.com/flutter/flutter-intellij/issues/971.

What's left in this issue is that Build Project doesn't work, which seems related to our choice of where we put the manifest file. /cc @jakobr-google, @mit-mit to see if we can re-locate where that file is.

**Comment by mit-mit** [comment]
@devoncarew can you elaborate? We put `androidmanifest.xml` in `src/main`, which is the same location the file is located when you create a new project in Android Studio.

**Comment by devoncarew** [comment]
From @skybrian's comment above, which says that Build Project is looking in the module root.

**Comment by skybrian** [comment]
Maybe we need to set the module root differently. I'll take a look.

**Comment by skybrian** [comment]
I found a way to get it to build:
- Go to Project Structure->Modules
- choose "android"
- remove the all content roots
- add android/app/src/main (which contains AndroidManifest.xml)

Now it should build the apk.

However, Android Integration automatically creates an "android" run configuration, and if I attempt to run that, it fails. I see:

```
05/02 17:31:17: Launching android
$ adb push /Users/skybrian/tmp/click6/out/production/android/android.apk /data/local/tmp/com.yourcompany.click6
$ adb shell pm install -r "/data/local/tmp/com.yourcompany.click6"
Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]
```

So I'm not sure if we want to lead users in this direction? Do we even want to support Android integration when it's going to bypass "flutter run" and hot reload, and do its own thing?

**Comment by skybrian** [comment]
I wonder if there's some way to suppress this notice in the event log:

```
Frameworks detected: Android framework is detected in the project 
```

**Comment by devoncarew** [comment]
If we want, we can suppress that by writing out the correct preferences:
<img width="1021" alt="screen shot 2017-05-03 at 8 44 17 am" src="https://cloud.githubusercontent.com/assets/1269969/25668875/bd3a73f4-2fdc-11e7-98d0-3a36c84f2c31.png">

**Comment by eseidelGoogle** [comment]
Triaging bugs, looks like skybrian looked at this.  Not sure if this belongs in flutter/flutter or flutter-intellij.  Marking M5 for now, please feel free to adjust.

**Comment by mit-mit** [comment]
This issue was moved to flutter/flutter-intellij#989
