### ISSUE TITLE
integration_test invoking 'takeScreenshot' on iOS causes MissingPluginException (No implementation found for method captureScreenshot)

### ISSUE THREAD

**Issue by bwaide** [flutter/flutter#96923]
## Steps to Reproduce

- Create a new project with "flutter create"
- Add dependencies to pubspec.yaml
```
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
```
- Add folder 'integration_test' with file 'app_test.dart' and the following code with just an additional call to binding.takeScreenshot
- On Android this works great. On iOS, on the Simulator as well as an attached device - I get the following error.
```
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
import 'package:screenshot_test/main.dart' as app;

void main() {
  //IntegrationTestWidgetsFlutterBinding.ensureInitialized();
  IntegrationTestWidgetsFlutterBinding binding = IntegrationTestWidgetsFlutterBinding.ensureInitialized() as IntegrationTestWidgetsFlutterBinding;

  group('end-to-end test', () {
    testWidgets('tap on the floating action button, verify counter',
            (WidgetTester tester) async {
          app.main();
          await tester.pumpAndSettle();

          // Verify the counter starts at 0.
          expect(find.text('0'), findsOneWidget);

          // Finds the floating action button to tap on.
          final Finder fab = find.byTooltip('Increment');

          // Emulate a tap on the floating action button.
          await tester.tap(fab);

          // Trigger a frame.
          await tester.pumpAndSettle();

          await binding.takeScreenshot('test');

          // Verify the counter increments by 1.
          expect(find.text('1'), findsOneWidget);
        });
  });
}

```
- execute 'flutter test integration_test/app_test.dart'
- chose an iOS device or simulator
-

**Expected results:** 
Same result as without the added "takeScreenshot" and the same as running the same code on Android.

**Actual results:**
```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following MissingPluginException was thrown running a test:
MissingPluginException(No implementation found for method captureScreenshot on channel
plugins.flutter.io/integration_test)

When the exception was thrown, this was the stack:
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

The test description was:
  tap on the floating action button, verify counter
═════════════════════════════════════════════════════════════════════════════════════

```
<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

Analyzing screenshot_test...                                            

   info • Avoid `print` calls in production code • test_driver/integration_test.dart:17:5 • avoid_print

1 issue found. (ran in 1.9s)

```
```

[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale en-DE)
    • Flutter version 2.8.1 at /Users/bjornwaide/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (5 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/bjornwaide/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Connected device (4 available)
    • SM A127F (mobile)  • RZ8RB08JF0Z                          • android-arm64  • Android 11 (API 30)
    • iWaide (mobile)    • 00008030-001428201E29802E            • ios            • iOS 15.1 19B74
    • iPhone 11 (mobile) • 278C4915-2D09-49D1-85E4-5B092551627A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2
      (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 97.0.4692.71

• No issues found!

```
```

</details>

**Comment by darshankawar** [comment]
@bwaide 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/91668
Please follow-up in it for further updates.
Closing this as a duplicate.
