### ISSUE TITLE
Make selectionOverlay customizable in CupertinoDatePicker

### ISSUE THREAD

**Issue by JulianBissekkou** [flutter/flutter#96925]
## Use case
Implementing a slightly adjusted version of the `CupertinoDatePicker`.

## Proposal
`CupertinPicker` provides an option to set `selectionOverlay` and it would be nice if `CupertinoDatePicker` does the same as well. I would propose a builder that gives the developer the ability to create the `selectionOverlay` for every column. 
For example, if we have day, month, and year on the picker the builder would be called 3 times for every column.

```dart
CupertinoDatePicker(
  selectionOverlayBuilder: (context, index, columnCount) {
    return _MyCustomSelectionOverlay();
  }
);
```

**Comment by darshankawar** [comment]
@JulianBissekkou 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/79559
Please follow-up in it for further updates.
Closing this as a duplicate.
