### ISSUE TITLE
assets-for-api-docs repo has expired cirrus token

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#96933]
The cirrus/GCP token for the assets-for-api-docs repo is https://github.com/flutter/assets-for-api-docs/blame/master/.cirrus.yml#L1 is 4 months old and (I think) expired. For example, this PR's pre-submit tests are failing: https://github.com/flutter/assets-for-api-docs/pull/174

**Comment by yusuf-goog** [comment]
Fix is in.
