### ISSUE TITLE
Framework `super.didChangeDependencies()` order

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#96930]
[Docs say](https://api.flutter.dev/flutter/widgets/State/didUpdateWidget.html):

> Implementations of this method should start with a call to the inherited method, as in super.didUpdateWidget(oldWidget).

I'm not sure if the order affects anything, but there are some places in the framework, where it's called the last. I think it should be refactored to match the docs.

**Comment by albertodev01** [comment]
I am working on a PR to fix this

**Comment by albertodev01** [comment]
PR to fix this is here: https://github.com/flutter/flutter/pull/96944

**Comment by nt4f04uNd** [comment]
Actually, it looks like we've looked up the wrong doc with @albertodev01 - [didChangeDependencies](https://api.flutter.dev/flutter/widgets/State/didChangeDependencies.html) docs actually don't say that.

@goderbauer do you have thoughts of what should be in the docs for didChangeDependencies regarding this?

**Comment by goderbauer** [comment]
The order here doesn't really matter too much, so I don't think we need to document anything.
