### ISSUE TITLE
Memory usage balloons in embedder_unittests after >400-500 iterations

### ISSUE THREAD

**Issue by gw280** [flutter/flutter#96945]
Spin off from https://github.com/flutter/flutter/issues/96807

When debugging that issue I ran `embedder_unittests` through Instruments and also just on the command line but monitoring memory usage using Activity Monitor.

In `host_profile`, Activity Monitor shows our memory usage staying at around 10-20MB for >1000 iterations, so that's great.

In `host_debug` though, after around 400-500 iterations I saw memory usage in Activity Monitor balloon to >1GB. 

Instruments shows a lot of leaked objects in both cases, but I haven't drilled too far down to see what's going on.

Given that we don't tend to run with a large number of iterations this isn't a particularly high priority but we should definitely investigate at some point.

cc @chinmaygarde @zanderso @iskakaushik

**Comment by jonahwilliams** [comment]
I don't think this issue is worth tracking.
