### ISSUE TITLE
[flutter_conductor] verify_binaries_codesigned test broken

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#96956]
The verify_binaries_codesigned test is not testing the correct commit.

The recipe change https://flutter.googlesource.com/recipes/+/06c55d9a14a7d7e5cd70a69315a2bccf6c6fa83d%5E%21/#F0 was an effort to fix this, but it did not work.

**Comment by christopherfujino** [comment]
Note, for this test we are creating a clone using the local disk as the remote; this was a speed optimization, but I suspect it's adding complexity to this setup. We should just clone the framework from GitHub like normal.

**Comment by godofredoc** [comment]
Test is now fixed:

https://flutter-review.googlesource.com/c/recipes/+/25640
https://flutter-review.googlesource.com/c/recipes/+/25602
https://flutter-review.googlesource.com/c/recipes/+/25602
