### ISSUE TITLE
App crashes on Android enabled Chromeboook

### ISSUE THREAD

**Issue by grouma** [flutter/flutter#9695]
## Steps to Reproduce

1) Download Flutter gallery or any released Flutter app e.g. Newsvoice.
2) Launch application on Android enabled Chromebook, e.g. Pixel 2
3) Notice application crashes immediately

**Comment by eseidelGoogle** [comment]
FYI @vlidholt.  I'm not sure what architecture Android-enabled-chromebook's use.  We currently only provide ARM binaries for the Flutter Engine.

@grouma do you have the ability to get a crash report from the device?

**Comment by grouma** [comment]
I have an option to create a crash report but don't know if I'm able to get at the logs. I'm also not certain where this report gets sent.

**Comment by grouma** [comment]
As of Chrome 61 this no longer is an issue. I'm able to run the Flutter Gallery on both a Pixel 2 and a PixelBook. Woot!

**Comment by tvolkert** [comment]
Can this be closed now?

**Comment by grouma** [comment]
I believe so.
