### ISSUE TITLE
Ninja failure building engine on Windows

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#96958]
On building the engine on Windows (gWindows machine if relevant), I get the following failure at the very end of the build:
```
[1886/1886] STAMP obj/default.stamp
Traceback (most recent call last):
  File "C:\src\depot_tools\ninjalog_uploader_wrapper.py", line 126, in <module>
    sys.exit(main())
  File "C:\src\depot_tools\ninjalog_uploader_wrapper.py", line 79, in main
    config = LoadConfig()
  File "C:\src\depot_tools\ninjalog_uploader_wrapper.py", line 32, in LoadConfig
    'is-googler': ninjalog_uploader.IsGoogler(),
  File "C:\src\depot_tools\ninjalog_uploader.py", line 48, in IsGoogler
    l = p.stdout.splitlines()[0]
IndexError: list index out of range
```

This appears as though it _may_ be a Googler-specific failure involving uploading ninja logs of the build.

Repro steps. From the engine/src/flutter directory:
1. Sync to `cd65368f9dec3bbc98992225978a4b7f164322f7` (committed on 2022-01-21)
2. `gclient sync -D`
3. `autoninja -C ../out/host_debug_unopt`

**Comment by jason-simmons** [comment]
`IsGoogler` is trying to run `goma_auth info`

What output do you see if you run that command in your setup?

**Comment by cbracken** [comment]
Just came back to dump in an update and yeah, the issue is that if you're not logged in `goma_auth info` generates no output to stdout; it writes "Not logged in" to stderr. The `splitlines` call on line 48 assumes output and blows up.

I'll file an upstream bug with depot_tools, or figure out how to send them a patch and tack the bug on here.

**Comment by cbracken** [comment]
Filed https://bugs.chromium.org/p/chromium/issues/detail?id=1289469

**Comment by cbracken** [comment]
Actually looks like a fix just landed in https://chromium.googlesource.com/chromium/tools/depot_tools/+/3dc0172a6b629edf575bf4851653ce6aa6635d8a

**Comment by cbracken** [comment]
This can be fixed by running `update_depot_tools`.
