### ISSUE TITLE
onChange property on DefaultTabController

### ISSUE THREAD

**Issue by Velkamhell97** [flutter/flutter#96962]
actually it can not be possible detect when a TabBarView change the current page with a swipe gesture, it only notifies in the onTap property of TabBar, this is frustrating because we can not sync up these events to trigger any function, so please add this feature in recent versions, i can make my own version of this pull request, but only if i set a custom TabController for TabBar and
TabBarView

```
int _tab = 0;

@override
void initState() {
 super.initState();

 _tabController = TabController(
  length: _tabs.length, 
  vsync: this
 );

 _tabController.animation!.addListener(_tabListener);
}

void _tabListener(){
 if(_tab != _tabController.animation!.value.round()){
  setState(() {
   _tab = _tabController.animation!.value.round();
  });
 }
}
```

however i need set the listener in the initState of my widget, which means that if i use a state management approach and i need to change tabs lenght, the initState dont execute again and the controller does not update, so would be wonderful if you can add a function on DefaultTabController that handles the swipe page changes, thanks for all!.

**Comment by darshankawar** [comment]
@Velkamhell97 
Check [this](https://github.com/flutter/flutter/issues/53155) similar issue which was fixed by adding an interactive example as how to listen for page updates using DefaultTabController and see if it helps to achieve your case.
