### ISSUE TITLE
Plugins repo PRs are marked "This branch is out-of-date with the base branch" with no merge conflicts

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#96972]
Seen in https://github.com/flutter/plugins/pull/4683:

![Screen Shot 2022-01-20 at 5 39 53 PM](https://user-images.githubusercontent.com/682784/150450014-75772c1d-4738-40dd-b76a-3f15dd3b2005.png)

PR was rebased onto top of tree before it was put out for review.  By the time it was reviewed, two more, non-conflicting commits were merged (in different packages), and the PR says `This branch is out-of-date with the base branch`.

**Comment by jmagman** [comment]
Maybe this message is expected, but I was confused as to whether I had to keep rebasing my PR.

**Comment by jmagman** [comment]
Hmm, it still hasn't merged.

**Comment by yusuf-goog** [comment]
@jmagman If you click the "Update branch" button, does it pull in changes correctly from main and allow a merge?

**Comment by jmagman** [comment]
Trying now, will see what happens once the tests pass.

Even if it does merge, it's not desirable to need to rebase every PR and run all the tests whenever an upstream commit happens. I haven't seen this on flutter/flutter, I wonder what's different in flutter/plugins.

**Comment by yusuf-goog** [comment]
In the backend, I'm seeing these logs:

`Info
2022-01-21 13:05:12.169 PST
Is pull request #4683 mergeable: MERGEABLE
`
`
Info
2022-01-21 13:05:12.169 PST
Skipping PR#4683 because it needs to land after 2022-01-21 22:01:05.000Z and current time is 2022-01-21 21:05:12.169702Z
`

**Comment by godofredoc** [comment]
That message means that we haven't removed the 1h injected latency for the plugins repo. Maybe we want to reduce it to 10 mins as we did for cocoon and packages.

https://cs.opensource.google/flutter/cocoon/+/main:app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart;l=28

**Comment by jmagman** [comment]
Here's another https://github.com/flutter/plugins/pull/4619

**Comment by jmagman** [comment]
Whether or not it gets merged by the bot, why is GitHub showing that message and button on the plugins repo?

**Comment by CaseyHillers** [comment]
@godofredoc @stuartmorgan do you know if in the plugins github admin settings that "Requires branches to be up to date before merging" was enabled recently? That would require PRs to be on ToT before being merged.

**Comment by stuartmorgan** [comment]
I can't see the admin page. I asked if settings had been changed in the repository recently in Discord, but didn't get a response.

If it was enabled, I'd really like to know why since it wasn't something anyone had discussed with me.

**Comment by godofredoc** [comment]
The admin page had `Require branches to be up to date before merging` enabled. This most likely happened when we migrated master to main. The check has been disabled, please let me know if that fixes the issue.

**Comment by CaseyHillers** [comment]
![successful merge](https://user-images.githubusercontent.com/2148558/151039625-c815b1dd-d770-4ae1-945d-21b640bdda91.png)

This appears fixed. Please reopen if this is re-occurring.

**Comment by stuartmorgan** [comment]
> The admin page had `Require branches to be up to date before merging` enabled. This most likely happened when we migrated master to main. The check has been disabled, please let me know if that fixes the issue.

Can you check flutter/packages? I think it needs to be fixed there as well.

**Comment by godofredoc** [comment]
Done, just updated it on packages repo!

**Comment by stuartmorgan** [comment]
Thanks!
