### ISSUE TITLE
Blank screen appears when resizing platform view

### ISSUE THREAD

**Issue by groovysoul** [flutter/flutter#96983]
Hello everyone. 
I have a question about an issue when the keyboard comes up on an Android device with OS 12.
I am showing the map through the Android native view. When the keyboard is raised, the platform view is resized and a blank screen appears sometimes. Is there any way to avoid resizing the platform view?

**Comment by darshankawar** [comment]
@groovysoul 
You seem to be asking for a solution for which support platforms like StackOverflow is the correct platform to get answers.
If you think that's a genuine bug , provide `flutter doctor -v`, a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can directly use and run that shows the behavior you are reporting along with a short video that clearly shows the issue.

**Comment by richhong38** [comment]
Hello, I'm groovysoul colleague. I think platform view doesn't work as I expected.

- How test
    -  Open up keyboard for typing (You may see platform view is shaking a little bit)
    -  Close keyboard
    - Platform view turns into white if you keep repeating above actions
I attach repo and video please help us.

Repo: [test_android_ui](https://github.com/richhong38/test_android_platform_view)
video: File attached to repo (video.zip)
