### ISSUE TITLE
[MethodChannel] exception needs more information.

### ISSUE THREAD

**Issue by endless7** [flutter/flutter#96987]
Needs more information about how this happened, like method name....
![image](https://user-images.githubusercontent.com/33014143/150498021-6d834464-ab8b-4c20-bf8e-9fd63ad7ca04.png)

**Comment by danagbemava-nc** [comment]
Hi @endless7, can you provide the plugin that is causing the error? 

I believe MethodChannel provides a way for the developers to provide information about error messages, so if it is missing, it is likely, that the developer of the plugin didn't provide the information.

**Comment by endless7** [comment]
@danagbemava-nc in that picture, i don't know why it throw exception, it's hard to trace, need more information like method name, channel name, arguments.

**Comment by danagbemava-nc** [comment]
Hi @endless7, I completely understand. 

Can you share your `pubspec.yaml` as well as the output of `flutter doctor -v`?

**Comment by endless7** [comment]
@danagbemava-nc 

[✓] Flutter (Channel master, 2.9.0-1.0.pre.364, on macOS 11.6 20G165 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.9.0-1.0.pre.364 at /Users/thendlessky/flutter
    • Upstream repository git@github.com:endless7/flutter.git
    • Framework revision 32dcaed254 (6 days ago), 2022-01-20 18:28:58 +0800
    • Engine revision f121c1fe68
    • Dart version 2.17.0 (build 2.17.0-11.0.dev)
    • DevTools version 2.9.2
    • Pub download mirror https://dart-pub.byted.org
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/thendlessky/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 97.0.4692.99

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

**Comment by danagbemava-nc** [comment]
Hi @endless7,  

Please provide your `pubspec.yaml` as well.
