### ISSUE TITLE
These problems occur after upgrading the latest version of flutter, how can I solve them?

### ISSUE THREAD

**Issue by 132056135** [flutter/flutter#96981]
## Steps to Reproduce

1. Running "flutter pub get" in KyeeSaas...
Cannot create link, path = 'D:\devflutter\flutter\.pub-cache\_temp\dird8658750\ios\Classes\FLTPackageInfoPlugin.m' (OS Error: Client does not have required privileges。
, errno = 1314)
pub get failed (66; , errno = 1314))

2. ...
3. ...

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@132056135 
Can you provide `flutter doctor -v` and complete error log ?
