### ISSUE TITLE
Performing hot restart... during flutter run or debug

### ISSUE THREAD

**Issue by yangchen1993** [flutter/flutter#96989]
## Steps to Reproduce

1.  ...When I modified the code click save
2. ...The system keeps prompting "Performing hot restart..."

**Expected results:** Able to perform hot reload normally

</details>

**Comment by danagbemava-nc** [comment]
Hi @yangchen1993, do you also have this issue when you use either `Android Studio` or the `flutter run` tool?

**Comment by yangchen1993** [comment]
> Hi @yangchen1993, do you also have this issue when you use either `Android Studio` or the `flutter run` tool?

yes,even I use terminal.It's not about tools

**Comment by yangchen1993** [comment]
<img width="942" alt="WX20220125-153445@2x" src="https://user-images.githubusercontent.com/13759880/150932317-080c683d-5fe3-4ba2-8f65-d689b4f1e7ba.png">
is this ok?

**Comment by danagbemava-nc** [comment]
We need to gather some more information. 

Kindly create a dummy flutter project.
Then run `flutter run -v`
Make some changes and save the file then try to hot restart. 
The output of all this is going to be very large, so kindly put it into a .txt file and attach it here. 

Alternatively, you could run `flutter run -v > log.txt`, but you'll have to be monitoring the file for changes and that may not be convenient for you.

**Comment by yangchen1993** [comment]
I know the problem,It's because when i use chrome to set the device to iphone,Appears suddenly while in use: “Error: Bad state: Not connected to an application.”
<img width="533" alt="WechatIMG121" src="https://user-images.githubusercontent.com/13759880/150948508-3b3141c0-aff1-4135-ad98-6c141aeee228.png">

**Comment by yangchen1993** [comment]
ok,i get it.it's about navigate.userAgent.thank u

**Comment by danagbemava-nc** [comment]
Have you found the cause of the issue?
