### ISSUE TITLE
Cannot signin using google signin

### ISSUE THREAD

**Issue by kingmaker000** [flutter/flutter#96999]
I have used google sign in earliarly and there was no issue. Now i am using the same code but I am facing platform exception when use google sign in. Google sign in package was now updated. But when using older package I am facing "Google does not verified this app" problem. When using the newer version , I am facing that platform exception error.

**Comment by darshankawar** [comment]
@kingmaker000 
Please don't open multiple issues for same reason. I see you have already filed https://github.com/flutter/flutter/issues/96998, so please follow per the comment in it and provide enough details so we can properly address the issue.
Closing as self-duplicate.
