### ISSUE TITLE
StatefulWidget "reassemble" not working on web

### ISSUE THREAD

**Issue by KMACEL** [flutter/flutter#96994]
Hi.

My problem is that it doesn't go into "reassemble() " when reloading or hot reloading on the Web.

I'm developing an application with Nats, but a socket stays open every "reload". If it enters "reassemble()" or "dispose()" I can turn it off.

**Comment by darshankawar** [comment]
@KMACEL 
Can you elaborate on the issue by providing `flutter doctor -v`, a minimal code sample along with actual vs expected behavior you are looking to have ?

**Comment by KMACEL** [comment]
@darshankawar Thanks for reply.

flutter doctor -v
[✓] Flutter (Channel stable, 2.8.1, on Ubuntu 20.04.3 LTS 5.11.0-46-generic,
    locale en_US.UTF-8)
    • Flutter version 2.8.1 at /home/mertacel/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (5 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/mertacel/Android/Sdk/
    • Platform android-32, build-tools 30.0.3
    • ANDROID_HOME = /home/mertacel/Android/Sdk/
    • Java binary at: /home/mertacel/Other/Android/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 4.1)
    • Android Studio at /home/mertacel/Other/Android/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.63.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.32.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.3 LTS
      5.11.0-46-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 97.0.4692.99

• No issues found!

---------------------------------
No callbacks to reassemble() in web development. ("hot restart" or "restart") 

class StatefulTest extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return _StatefulTest();
  }
}

class _StatefulTest extends State<StatefulTest> {
  @override
  Widget build(BuildContext context) {
    return Container();
  }

  @override
  void reassemble() {
    debugPrint("Here not working on web");
    super.reassemble();
  }
}

**Comment by darshankawar** [comment]
@KMACEL 
You may be seeing this behavior because hot reload isn't supported on web yet. See this open issue for your reference: https://github.com/flutter/flutter/issues/53041

**Comment by KMACEL** [comment]
@darshankawar thank you.
