### ISSUE TITLE
[tool_crash] ProcessException: The paging file is too small for this operation to complete. Command: C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe, OS error code: 1455

### ISSUE THREAD

**Issue by logispire** [flutter/flutter#96990]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=cc82f03c0005 --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: The paging file is too small for this operation to complete.
 Command: C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe, OS error code: 1455
```
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:401:33)
#1      Process.start (dart:io-patch/process_patch.dart:38:20)
#2      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:42:22)
#3      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:691:24)
#4      _run (package:flutter_tools/src/base/error_handling_io.dart:567:20)
#5      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:690:12)
#6      DefaultResidentCompiler._compile (package:flutter_tools/src/compile.dart:762:37)
#7      DefaultResidentCompiler._recompile (package:flutter_tools/src/compile.dart:657:14)
#8      _RecompileRequest._run (package:flutter_tools/src/compile.dart:367:16)
#9      _CompilationRequest.run (package:flutter_tools/src/compile.dart:345:30)
#10     DefaultResidentCompiler._handleCompilationRequest (package:flutter_tools/src/compile.dart:694:23)
#11     _rootRunUnary (dart:async/zone.dart:1436:47)
#12     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#13     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#14     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#15     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#16     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
#17     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
#18     _rootRun (dart:async/zone.dart:1420:47)
#19     _CustomZone.run (dart:async/zone.dart:1328:19)
#20     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
#22     _rootRun (dart:async/zone.dart:1428:13)
#23     _CustomZone.run (dart:async/zone.dart:1328:19)
#24     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
```
```
[✓] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.22000.434], locale en-US)
    • Flutter version 2.8.1 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (5 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Ruchit Mavani\AppData\Local\Android\sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: C:\Program Files\Common Files\Oracle\Java\javapath\java.exe
    ✗ Could not determine java version

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code, 64-bit edition (version 1.63.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.22.0

[✓] Connected device (3 available)
    • Redmi Note 5 (mobile) • cc82f03c0005 • android-arm64  • Android 8.1.0 (API 27)
    • Chrome (web)          • chrome       • web-javascript • Google Chrome 97.0.4692.71
    • Edge (web)            • edge         • web-javascript • Microsoft Edge 97.0.1072.62

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.2+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 18116933e77adc82f80866c928266a5b4f1ed645
### Plugins
android_path_provider-0.3.0
cached_video_player-2.0.0-dev.1
connectivity_plus-2.2.0
connectivity_plus_linux-1.2.0
connectivity_plus_macos-1.2.1
connectivity_plus_web-1.2.0
connectivity_plus_windows-1.2.0
file_picker-4.3.0
firebase_analytics-8.3.4
firebase_analytics_web-0.3.0+1
firebase_core-1.11.0
firebase_core_web-1.5.3
firebase_messaging-11.2.5
firebase_messaging_web-2.2.6
flutter_local_notifications-9.2.0
flutter_pdfview-1.2.1
flutter_plugin_android_lifecycle-2.0.5
fluttertoast-8.0.8
image_cropper-1.4.1
image_picker-0.8.4+4
image_picker_for_web-2.1.4
path_provider-2.0.8
path_provider_android-2.0.11
path_provider_ios-2.0.7
path_provider_linux-2.1.4
path_provider_macos-2.0.4
path_provider_windows-2.0.4
permission_handler-8.1.4+2
shared_preferences-2.0.11
shared_preferences_android-2.0.9
shared_preferences_ios-2.0.8
shared_preferences_linux-2.0.3
shared_preferences_macos-2.0.2
shared_preferences_web-2.0.2
shared_preferences_windows-2.0.3
sqflite-2.0.1
video_player-2.2.10
video_player_web-2.0.5
video_thumbnail-0.4.3
volume_watcher-2.0.1
wakelock-0.5.6
wakelock_macos-0.4.0
wakelock_web-0.4.0
webview_flutter-3.0.0
webview_flutter_android-2.8.2
webview_flutter_wkwebview-2.7.1

**Comment by danagbemava-nc** [comment]
I did not see a similar issue open. 
Labeling for further investigation.

**Comment by danagbemava-nc** [comment]
I cannot reproduce this issue using the command above. A look online also seems to indicate that is a memory issue. https://stackoverflow.com/questions/69912123/paging-file-too-small-for-this-operation-to-complete-error-when-attempting-to

Given that this issue has not had any activity or duplicates since it was filed, I'll be closing this as stale. 

If anyone runs into this issue, kindly file a new issue provide all the relevant information. 

Thank you
