### ISSUE TITLE
Checkboxes in PopupMenuItems don't respond to taps on the menu item

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#97]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Friday Jul 17, 2015 at 22:45 GMT_
_Originally opened as https://github.com/flutter/engine/issues/105_

----

_From @Hixie on May 12, 2015 19:25_

The checkbox control doesn't automatically get checked when you tap on a menu item that contains it.

_Copied from original issue: domokit/mojo#162_

**Comment by FlutterIssues** [comment]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Hixie](https://github.com/Hixie)**
_Friday Jul 17, 2015 at 22:45 GMT_

----

_From @abarth on June 11, 2015 19:43_

This is fixed in stocks2.

**Comment by FlutterIssues** [comment]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Hixie](https://github.com/Hixie)**
_Friday Jul 17, 2015 at 22:45 GMT_

----

No it's not. :-)

**Comment by FlutterIssues** [comment]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Hixie](https://github.com/Hixie)**
_Friday Jul 17, 2015 at 22:45 GMT_

----

_From @abarth on June 11, 2015 20:30_

Apparently this bug isn't about tapping on the checkbox itself but upon the text associated with the check box.

**Comment by Hixie** [comment]
This is fixed in stocks now.
