### ISSUE TITLE
TabBar and TabBarView should allow zero or one elements

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#970]
Currently at least two tab labels/views are required.

An application that displayed search results in a TabBar/TabBarView or just the latter, would expect the classes to work no matter how many elements were specified.

**Comment by eseidelGoogle** [comment]
@alardizabal ran into this today.

**Comment by eseidelGoogle** [comment]
My understanding from @alardizabal is that this is mostly about programming convenience and not having to handle the n=1 case separately when dealing with dynamic data.

**Comment by Hixie** [comment]
@HansMuller Is this something you can take a look at?

**Comment by HansMuller** [comment]
Yes, I can do it.
