### ISSUE TITLE
Build and release an Android app

### ISSUE THREAD

**Issue by codewithmalik** [flutter/flutter#97004]
Hi I have followed flutter.dev instruction on how deploy an app but I end up with is error below

FAILURE: Build failed with an exception.

* What went wrong:
Gradle could not start your build.
> Cannot create service of type TaskExecuter using method ProjectExecutionServices.createTaskExecuter() as there is a problem with parameter #17 of type ReservedFileSystemLocationRegistry.
   > Cannot create service of type ReservedFileSystemLocationRegistry using method ProjectExecutionServices.createReservedFileLocationRegistry() as there is a problem with parameter #1 of type List<ReservedFileSystemLocation>.
      > Could not create service of type ExecutionHistoryStore using ExecutionGradleServices.createExecutionHistoryStore().
         > Cannot lock execution history cache (/Users/aoomle/Documents/Prototypes/Freelancer/pokdoc_doctor/android/.gradle/6.7/executionHistory) as it has already been locked by this process.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Running Gradle task 'assembleRelease'...                            3.3s
Gradle task assembleRelease failed with exit code 1
aoomle@Abdulmaliks-MBP pokdoc_doctor %

**Comment by darshankawar** [comment]
@codewithmalik 
The error you are getting seems to be coming from Gradle itself:

```
Could not create service of type ExecutionHistoryStore using ExecutionGradleServices.createExecutionHistoryStore().
> Cannot lock execution history cache (/Users/aoomle/Documents/Prototypes/Freelancer/pokdoc_doctor/android/.gradle/6.7/executionHistory) as it has already been locked by this process.
```

This may be causing by running gradle in a folder where you lack permissions. Ensure that your project and gradle home have rwx on linux/macOS and/or do not require admin permissions on windows.

Closing from here. If you disagree, write in comments and I'll reopen.

**Comment by codewithmalik** [comment]
Thanks @darshankawar, Please how do i fix it

**Comment by Pictor13** [comment]
The only thing that fixed it for me was a restart of IntelliJ IDEA.

Otherwise....
In the same directory as the file from the error, is there any ` .lock` file?
(in this case close to `.gradle/6.7/executionHistory/executionHistory.bin`, from your project folder). 

```
ls .gradle/6.7/executionHistory
-rw-r--r--  1 yoyo  unicorn    14M Feb 14 00:33 executionHistory.bin
-rw-r--r--  1 yoyo  unicorn    39B Feb 14 00:36 executionHistory**.lock**
```
Deleting the `.lock` file **might** free-up the permission.
`rm .gradle/6.7/executionHistory/executionHistory.lock`

However, it didn't solve the problem for me.
