### ISSUE TITLE
Building the iOS app on Github Actions gets stuck at `Running script 'Run Script'`

### ISSUE THREAD

**Issue by long1eu** [flutter/flutter#97007]
If I build the app on my local machine it work, but when on Github Actions with macos-11 the build doesn't go past 
```
Running script 'Run Script'
```

Is there a way to debug this phase? I'm building the app using fastlane.

**Comment by maheshmnj** [comment]
Hi @long1eu, Your question is mostly suited for support channels like StackOverflow or you could file this issue in the Fastlane repo. Closing as this issue isn't related to flutter if you disagree feel free to write in the comments with more details about the issue and I will reopen it.

Thank you.
