### ISSUE TITLE
Facebook audience network only show test ads after release on play store

### ISSUE THREAD

**Issue by dananee** [flutter/flutter#97018]
Hello I have some issue with Facebook audience network  package it only shows test i don't where the problem is coming from 

I have 1k installed on google play store I use mediation with AdMob the request are coming but no impression 
It says "We haven't received a bid request"
This is the  code i use to implment ads:

`FacebookBannerAd(
 placementId: "IMG_16_9_APP_INSTALL#1289551311527753_1289580521524832",
  bannerSize: BannerSize.STANDARD,
  listener: (result, value) {},
   ),`

**Comment by maheini** [comment]
I'd recommend to open a Issue on their Repo, or asking on Stackoverflow.

The Facebook audience network repo : https://github.com/dreamsoftin/facebook_audience_network/

**Comment by darshankawar** [comment]
Please open the issue in dedicated repo: https://github.com/dreamsoftin/facebook_audience_network/issues
closing from here.
