### ISSUE TITLE
Improve documentation for data driven fixes

### ISSUE THREAD

**Issue by werainkhatri** [flutter/flutter#97031]
Following need to be addressed in order to improve documentation for data-driven fixes.
- [x] `fix_data.yaml` should instruct adding tests in `test_fixes/`.
- [x] `test_fixes/README.md` should document how fixes can be tested locally.
- [x] Both of the above should be documented in the [data-driven fixes wiki](https://github.com/flutter/flutter/wiki/Data-driven-Fixes).
- [ ] State the purpose and use of *uri*s in the References section of the [wiki](https://github.com/flutter/flutter/wiki/Data-driven-Fixes).

cc @Piinks (if you have any other ideas/places that should be documented)

**Comment by Hixie** [comment]
@werainkhatri Is this still on your radar? Looks like you got really close!

**Comment by Hixie** [comment]
(reached out to @werainkhatri on Discord)

**Comment by werainkhatri** [comment]
Hey @Hixie! I'll try to see if I can make some time this week.

[Ignore the close re-open actions, the GH app was malfunctioning]

**Comment by goderbauer** [comment]
(triage) We think this is all done.
