### ISSUE TITLE
Cocoon fails to update dashboards though tasks have finished running

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#97039]
Flutter dashboard:
<img width="1228" alt="Screen Shot 2022-01-21 at 4 32 28 PM" src="https://user-images.githubusercontent.com/54558023/150616877-4132f1fd-fc0a-446e-8f78-a7949e4c4b77.png">

Though tasks have finished from luci side:
![Screen Shot 2022-01-21 at 4 34 01 PM](https://user-images.githubusercontent.com/54558023/150616961-d7c3fb29-1a5c-4efb-bc92-de636895c7ca.png)

**Comment by yusuf-goog** [comment]
The results seem to be populating albeit slowly.

**Comment by yusuf-goog** [comment]
Checking to see if there are any apparent backend issues showing in the logs.

**Comment by yusuf-goog** [comment]
Looks like refresh-chromebot-status is seeing buildbucket errors:

<pre>
BuildBucketException: [500]: Internal Server Error

#0      BuildBucketClient._postRequest (package:cocoon_service/src/service/buildbucket.dart:70:5)
<asynchronous suspension>
#1      BuildBucketClient.batch (package:cocoon_service/src/service/buildbucket.dart:97:36)
<asynchronous suspension>
#2      LuciService.getBuilds (package:cocoon_service/src/service/luci.dart:190:41)
<asynchronous suspension>
#3      LuciService.getBuildsForBuilderList.<anonymous closure> (package:cocoon_service/src/service/luci.dart:121:49)
<asynchronous suspension>
#4      RetryOptions.retry (package:retry/retry.dart:131:16)
<asynchronous suspension>
#5      LuciService.getBuildsForBuilderList (package:cocoon_service/src/service/luci.dart:119:7)
<asynchronous suspension>
#6      LuciService.getBranchRecentTasks (package:cocoon_service/src/service/luci.dart:69:32)
<asynchronous suspension>
#7      RefreshChromebotStatus.get (package:cocoon_service/src/request_handlers/refresh_chromebot_status.dart:68:75)
<asynchronous suspension>
#8      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:46:22)
<asynchronous suspension>
#9      ApiRequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/api_request_handler.dart:149:7)
<asynchronous suspension>
#10     ApiRequestHandler.service (package:cocoon_service/src/request_handling/api_request_handler.dart:148:5)
<asynchronous suspension>
#11     main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:260:9)
<asynchronous suspension>
</pre>

**Comment by yusuf-goog** [comment]
Looks like the errors started appearing continuously around 2.26pm today:
![image](https://user-images.githubusercontent.com/91688203/150619259-95d0ccbd-2719-48ad-85d7-081751a6cc54.png)

**Comment by yusuf-goog** [comment]
Looks like our latest changes to cocoon were deployed at 8am today.

**Comment by yusuf-goog** [comment]
LUCI team sees that our requests are timing out in Datastore queries. Seems like it might have been due to some indexes that were deleted today.

Those indexes are being regenerated and should be ready in a few hours.

**Comment by yusuf-goog** [comment]
Dashboard has caught up and no more errors showing up in logs.
