### ISSUE TITLE
[FlexibleSpaceBar] Extended flexible space bar

### ISSUE THREAD

**Issue by CyJaySong** [flutter/flutter#97042]
## Proposal

I need [FlexibleSpaceBar] to be transformed from [CollapseMode.none] to [CollapseMode.pin] when it collapse in [SliverAppBar]. And the content in [FlexibleSpaceBar] can change state according to the collapse height. like the effect in the video. I have extended [FlexibleSpaceBar], implemented this feature, and have submitted pr for sharing it with more people.

https://user-images.githubusercontent.com/29367599/150617605-4ff42620-bafd-4c3b-8451-df494ccb97f7.mp4

**Comment by darshankawar** [comment]
@CyJaySong 
What is the current limitation are you facing using FlexiSpacBar ? From the video you attached, it isn't clear as what you would like to achieve. In the PR, I see the demo code provided, but I couldn't spot any difference in the video demos provided in it. So please provide us a sample use case with current limitation along with your fix (using new Blendmodes you introduced) that'll help to achieve the case.
Thanks.

**Comment by CyJaySong** [comment]
@darshankawar  In the UI design of the SliverAppBar with a relatively high height, there is generally no single collapse effect. So I added a combined mode of [CollapseMode.none] and [CollapseMode.pin] . Added `backgroundBuilder` for flexibly building appropriate content based on height when collapsing

**Comment by darshankawar** [comment]
@CyJaySong 
Can you check if [this](https://github.com/flutter/flutter/pull/92160) helps to achieve your case ?

**Comment by CyJaySong** [comment]
@darshankawar No, the goals are different

**Comment by CyJaySong** [comment]
@darshankawar  [CollapseMode.nonePin] You can use `nonePinBoundar` as the boundary to use [CollapseMode.none] and [CollapseMode.pin] two collapse effects respectively

**Comment by darshankawar** [comment]
Keeping it open and labeling it for further input from the team.

Demo code: https://github.com/flutter/flutter/pull/96835#issuecomment-1018543609

/cc @Piinks

**Comment by Piinks** [comment]
Hi @CyJaySong I am not entirely sure I understand this feature request.
Can you provide sample code so we can understand the expected behavior? This may already be possible.

**Comment by CyJaySong** [comment]
@Piinks In fact, this PR is two extensions, one is a new collapse mode consisting of `nonePinBoundar` and `CollapseMode .nonePin`, and the other is `backgroundBuilder`

**Comment by Piinks** [comment]
>  this PR is two extensions, one is a new collapse mode consisting of `nonePinBoundar` and `CollapseMode .nonePin`, and the other is `backgroundBuilder`

If the PR contains more than one feature, it may be best to split it into multiple PRs, one for each feature.

**Comment by CyJaySong** [comment]
@Piinks However, I have submitted this pr. In addition, have I explained these two new features clearly?

**Comment by Piinks** [comment]
I am pretty sure this is already possible in the framework, but without some sample code of your use case with your proposed code changes (as requested above and in the PR) I can't really tell.
