### ISSUE TITLE
FormatException: Unexpected extension byte (at offset 5)

### ISSUE THREAD

**Issue by leemke** [flutter/flutter#97041]
just following the instructions in the error message that flutter doctor reported.

Here is the full text of the message:

.
lawrenceemke@JET:/usr/bin$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on Debian GNU/Linux 11 (bullseye) 5.10.91-13997-ge796c79ffe45, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ Format Exception: Unexpected extension byte (at offset 5)
[✓] Connected device (2 available)

! Doctor found issues in 2 categories.
lawrenceemke@JET:/usr/bin$ 

I am trying to run flutter under Intelli Idea 
I believe I installed all of the required software as listed on your web-site
I used Intelli "Jetbrains-toolbox" to install Android-SDK and all appropriate 
plugins

**Comment by Hexer10** [comment]
This is already fixed in #96325. The fix has landed only in the master channel currently, if you don't want to switch channel you have to wait for it to be released in the another channels as well.

**Comment by leemke** [comment]
how do i switch to the master channel

**Comment by darshankawar** [comment]
This issue was previously reported in #94060 and has since been fixed. The fix is on master but it hasn't rolled out to stable yet. It should sometime in the future.

To switch to master:

```
flutter channel master
flutter upgrade
```
Closing this as a duplicate.
