### ISSUE TITLE
Hardware button

### ISSUE THREAD

**Issue by ironanurag** [flutter/flutter#97052]
## Use case

`There is no way to register physical button event, and the existing package are not working anymore flutter should provide this package`

**Comment by darshankawar** [comment]
@ironanurag 
Can you elaborate your use case by providing `flutter doctor -v` and a minimal code sample that shows current limitation and what exactly are you proposing ?

**Comment by ironanurag** [comment]
I am creating an app that starts by holding volume up button but i couldn't
find any way to do it.

**Comment by darshankawar** [comment]
@ironanurag 
Your question / issue is better suited for support channels like StackOverflow, so please ask the same there.
Closing from here.
