### ISSUE TITLE
Dismiss Alert dialog on LongPress

### ISSUE THREAD

**Issue by mohammedX6** [flutter/flutter#97051]
I need to dismiss the AlertDialog on LongPress

**Comment by filipagh** [comment]
@mohammedX6  wrap AlertDialog with `GestureDetector` and set `onLongPress` like
```
GestureDetector(
        onLongPress: () {Navigator.pop(context);},
        child: AlertDialog(
      title: Text("Test"),
      content: Text("Done..!"),
    )
)
```

**Comment by darshankawar** [comment]
@mohammedX6 
Please ask support questions / code assistance on stackoverflow.
Closing from here.
