### ISSUE TITLE
The following assertion was thrown building Form-[LabeledGlobalKey<FormState>#31819](state: FormState#b9efc):

### ISSUE THREAD

**Issue by RaufAfzal** [flutter/flutter#97057]
Hey Anybody can help me with this error i am not understanding the error when i switch back to my login page it give me a error and i am not understanding the error

**Comment by RaufAfzal** [comment]
![2](https://user-images.githubusercontent.com/81850803/150638575-ddcdea6b-3a31-455f-bdd3-24a8894e7844.PNG)

**Comment by danagbemava-nc** [comment]
Hi @RaufAfzal, please provide a complete minimal reproducible code sample as well as the output of `flutter doctor -v`. 

Thank you
