### ISSUE TITLE
[Windows] Build failed without clalify error if asset file not exist 

### ISSUE THREAD

**Issue by ivk1800** [flutter/flutter#97065]
## Steps to Reproduce

1. create new project ```flutter create myapp```
2. add to pubspec not exit asset file: 
```
flutter:
  assets:
    - assets/somefile.txt
```
4. check warning in your IDE
3. run app

**actual result:**
build failed with error:
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(240,5): error MSB8066: пользовательская сборка для "..\myapp\build\windows\CMakeFiles\2dc32e292af62a6e4b8b352773afe775\flutter_windows.dll.rule;..\myapp\build\windows\CMakeFiles\469176a6d3b8459cb97902e5168c5d4b\flutter_assemble.rule" завершила работу с кодом 1. [..\myapp\build\windows\flutter\flutter_assemble.vcxproj]
Exception: Build process failed.
```

**expected result:**
the error clarify the asset is missing

<details>
  <summary>flutter doctor</summary>

[✓] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19042.1466], locale ru-RU)
    • Flutter version 2.8.1 at [some_path]
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (5 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31112.23
    • Windows 10 SDK version 10.0.19041.0
</details>

**Comment by stuartmorgan** [comment]
What's the error message if you do a verbose build?

This will need an update to the Windows build regex.

**Comment by ivk1800** [comment]
Why it is error not included to final?

if run ```flutter run -d windows -v```
<details>
  <summary>logs</summary>
[ +142 ms]   [ +143 ms] Error detected in pubspec.yaml:
[        ]   [        ] No file or variants found for asset: packages/app/assets/somefile.txt
[        ]   [        ] This asset was included from package app.
[   +1 ms]   [   +2 ms] Persisting file store
[  +22 ms]   [  +22 ms] Done persisting file store
[  +16 ms]   [  +15 ms] Target debug_bundle_windows_assets failed: Exception: Failed to bundle asset files.
[        ]              #0      copyAssets (package:flutter_tools/src/build_system/targets/assets.dart:57:5)
[        ]              <asynchronous suspension>
[        ]              #1      BundleWindowsAssets.build (package:flutter_tools/src/build_system/targets/windows.dart:227:29)
[        ]              <asynchronous suspension>
[        ]              #2      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:839:9)
[        ]              <asynchronous suspension>
[        ]              #3      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:606:16)
[        ]              <asynchronous suspension>
[        ]              #4      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:317:32)
[        ]              <asynchronous suspension>
[        ]              #5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
[        ]              <asynchronous suspension>
[        ]              #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]              <asynchronous suspension>
[        ]              #7      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
[        ]              <asynchronous suspension>
[        ]              #8      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
[        ]              <asynchronous suspension>
[        ]              #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]              <asynchronous suspension>
[        ]              #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
[        ]              <asynchronous suspension>
[        ]              #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
[        ]              <asynchronous suspension>
[        ]              #12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]              <asynchronous suspension>
[        ]              #13     main (package:flutter_tools/executable.dart:94:3)
[   +1 ms]              <asynchronous suspension>
[        ]   [   +8 ms] "flutter assemble" took 3┬а413ms.
[        ]   [   +3 ms]
[        ]              #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
[        ]              #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:334:7)
[        ]              <asynchronous suspension>
[        ]              #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
[        ]              <asynchronous suspension>
[        ]              #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]              <asynchronous suspension>
[        ]              #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
[        ]              <asynchronous suspension>
[        ]              #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
[        ]              <asynchronous suspension>
[        ]              #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]              <asynchronous suspension>
[        ]              #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
[        ]              <asynchronous suspension>
[        ]              #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
[        ]              <asynchronous suspension>
[        ]              #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]              <asynchronous suspension>
[        ]              #10     main (package:flutter_tools/executable.dart:94:3)
[        ]              <asynchronous suspension>
[ +191 ms]   [ +196 ms] ensureAnalyticsSent: 195ms
[        ]   [        ] Running shutdown hooks
[        ]   [        ] Shutdown hooks complete
[        ]   [        ] exiting with code 1
[  +45 ms] C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(240,5): error MSB8066: пользовательская сборка для
"myapp\launch\build\windows\CMakeFiles\8826b86ab6adcdfd6fb844f2dbda2470\flutter_windows.dll.rule;myapp\launch\build\windows\CMakeFiles\90ee28a13b9c899a9456f66f7ffbb23a\flutter_assemble.rule"
завершила работу с кодом 1. [myapp\launch\build\windows\flutter\flutter_assemble.vcxproj]

</details>

**Comment by stuartmorgan** [comment]
The regex will need to be updated so that it matches:
```
[ +142 ms] [ +143 ms] Error detected in pubspec.yaml: [ ] [ ] No file or variants found for asset: packages/app/assets/somefile.txt [ ] [ ] This asset was included from package app
```


> Why it is error not included to final?

Because it wasn't caught by the filter that extracts errors from the full output.

**Comment by stuartmorgan** [comment]
For anyone interested in fixing this, [this](https://github.com/flutter/flutter/blob/20ff180ae83460f2f8f83be8aaddbb875e8daa59/packages/flutter_tools/lib/src/windows/build_windows.dart#L284) is the regex that needs to be updated.

**Comment by miltosdoul** [comment]
Hello, I'm a bit new to open source, thought I'd give this a go since it has the "good first contribution" label. 

Played around with regex a bit and the below code seems to match the required string from the example given:
`final RegExp errorMatcher = RegExp(r':\s*(?:warning|(?:fatal )?error).*?:|\[.*(?:from package).*?\.');`
(added `|\[.*(?:from package).*?\.` to regex).

although I'm not sure if matching "from package" is the best way to do this.

I might get a chance to test it in code in the next few days, but I'm not able to right now, so if anyone tests it and it works alright, let me know if I should make a pull request.

Thanks!

**Comment by stuartmorgan** [comment]
> although I'm not sure if matching "from package" is the best way to do this.

There's no reason that a string containing "from package" should be assumed to be an error.

`Error detected in pubspec.yaml:`, however, is unambiguously an error.

**Comment by miltosdoul** [comment]
Thanks for the spot, I got so caught up in trying to match the string that I forgot to check for an actual error 😅

This should work properly now:
`final RegExp errorMatcher = RegExp(r':\s*(?:warning|(?:fatal )?error).*?:|\[.*?(?:Error detected).*?(?:from package ).*?\.');`
(added  `|\[.*?(?:Error detected).*?(?:from package ).*?\.`)

Kept the "from package" in so it stops matching at that point.

Let me know how it looks.

**Comment by stuartmorgan** [comment]
> Kept the "from package" in so it stops matching at that point.

What do you mean "so it stops matching"? It's a line-by-line filter.

I'm not sure why you are making the expression so complicated when the string "Error detected in pubspec.yaml:" is simple and unambiguous all by itself.

**Comment by miltosdoul** [comment]
Ahh I see, I was falsely assuming that it wasn't line-by-line for some reason. In that case, as you said, I suppose something like `|.*(?:Error detected in pubspec.yaml:).*` would work great.

At any rate, I will test this properly tomorrow and submit a PR.

Also, thanks for going through this with me, I am new at working on issues on here and this has been a good learning experience.

**Comment by stuartmorgan** [comment]
Why are you wrapping a single, non-optional string in a non-matching group?
