### ISSUE TITLE
[path_provider] Allow getApplicationSupportDirectory() to omit company directory

### ISSUE THREAD

**Issue by barbalex** [flutter/flutter#97062]
## Steps to Reproduce
```dart
Directory appSupDir = await getApplicationSupportDirectory();
print(appSupDir.path);
```

**Expected results:** 

```
C:\Users\alexa\AppData\Roaming\myAppsName
```

**Actual results:** 

```
C:\Users\alexa\AppData\Roaming\app\myAppsName
```

The `C:\Users\alexa\AppData\Roaming` folder on my windows pc contains 65 folders created by apps. All of them directly under `C:\Users\alexa\AppData\Roaming`. None under `C:\Users\alexa\AppData\Roaming\app`.

It seems to make no sense to return the app subfolder.

**Comment by stuartmorgan** [comment]
> It seems to make no sense to return the app subfolder.

There is no code in the plugin that adds an `app` subdirectory.

Did you set your `CompanyName` to "app"?

**Comment by barbalex** [comment]
The only code containing `CompanyName` in my project is: `windows/runner/Runner.rc`. Which wasn't generated by me. And seems to be a `Microsoft Visual C++ generated resource script`.

Is it documented how the path is generated on windows?

**Comment by stuartmorgan** [comment]
> The only code containing `CompanyName` in my project is: `windows/runner/Runner.rc`.

That's expected. What is its value?

> Which wasn't generated by me.

It was generated for you by `flutter create`, like everything else, with initial values based on the parameters you passed.

> Is it documented how the path is generated on windows?

I don't think so. It follows the common Windows practice of using the application name, with a containing folder of the company name if set.

**Comment by barbalex** [comment]
@stuartmorgan  thanks for great help!

> What is its value?

As you correctly guessed: app.

It was 

> generated for you by flutter create

Thanks for teaching me basic flutter 😆. As you may have guessed: I am  a flutter noob (web dev).

> It follows the common Windows practice of using the application name, with a containing folder of the company name if set.

So if I don't want a company named folder, can I set an empty value in Runner.rc?
```
VALUE "CompanyName", "" "\0"
```
Or will that have other consequences?

**Comment by stuartmorgan** [comment]
> So if I don't want a company named folder, can I set an empty value in Runner.rc?

I'm not sure that the plugin will currently handle that correctly. If it doesn't, feel free to file a bug.

> Or will that have other consequences?

I don't know what other effects that might have within Windows in general, since it's a required key.

What is the use case for not including this directory? It's common practice, and it avoids the potential of two different applications that happen to have the same name from trying to use the same directory. In theory we could provide API to optionally disable that part of the path generation, but it's not clear to me what the value of such API would be.

**Comment by barbalex** [comment]
> I'm not sure that the plugin will currently handle that correctly

I tested it and it omits the company folder when `CompanyName` is `""` 👍 

> What is the use case for not including this directory? It's common practice, and it avoids the potential of two different applications that happen to have the same name from trying to use the same directory

I guess you are right and what you say makes sense. So (hopefully) not being to old to learn I will set the `CompanyName` as expected.

Thanks for great advice!
