### ISSUE TITLE
Chip does not expand in height for multiline Text

### ISSUE THREAD

**Issue by TheCarpetMerchant** [flutter/flutter#97074]
```
import 'package:flutter/material.dart';

void main() {
  runApp(
    const MaterialApp(
      home: Scaffold(
        body: Chip(
          label: Text('Str\nStr'),
        ),
      ),
    )
  );
}
```

Put that code into a DartPad and you'll see only one 'Str'.  `softWrap` and `overflow` do not change the result. Wrapping `Chip` with a `SizedBox(height: 100)` just extends the Chip without extending the Text, as other layout shenanigans I tried do.
I will of course be making my own widget, but this seems like an oversight. We should be able to make 2-lines chips.

**Comment by danagbemava-nc** [comment]
Hi @TheCarpetMerchant, I'm not entirely sure that would be in line with the material design specs. 
From what I see on the material spec for the `Chip` widget, it would appear that it is intended for the text to be just one line. 

https://m3.material.io/components/chips/specs
https://m3.material.io/components/chips/guidelines
https://material.io/components/chips

**Comment by TheCarpetMerchant** [comment]
Ah, I don't suppose the team would like to go around that then. Still, having the option to do so would be useful.

**Comment by danagbemava-nc** [comment]
I'm not certain, but can you share a real-world code sample in which you've needed a chip label to be more than 1 line? Perhaps that would make a better argument for the implementation of it or there may be a better way to go about implementing this.

**Comment by TheCarpetMerchant** [comment]
Oh simply because I'll have a good number of chips, sorted in a few categories. So I'd like the chips to show which category they're from.
You could also arrange the UI the have a title and group the chips by category, but the category really is only informative ; you're rather going to search for what you want using the fact they're sorted alphabetically. Which you'd lose if you group them by category.

**Comment by danagbemava-nc** [comment]
I'm not sure I fully understand your scenario. 
Do you perhaps have a visual representation that you can share?

**Comment by danagbemava-nc** [comment]
Hi @TheCarpetMerchant, can you try the sample below and see if it suits your needs? 

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Center(
        child: SizedBox(
          width: 300,
          child: Chip(
            label: Text(
              'Category\nName',
              overflow: TextOverflow.visible,
              softWrap: true,
              maxLines: 2,
            ),
            clipBehavior: Clip.none,
          ),
        ),
      ),
    );
  }
}
```
</details>

**Comment by TheCarpetMerchant** [comment]
Hey that works ! Perfect for me, didn't think to specify `maxlines` as `Text` usually reacts correctly to a `\n`. Good thinking @danagbemava-nc , I'm closing the issue then ! Have a good day.
