### ISSUE TITLE
Performance regression in raster times on android_view_scroll_perf__timeline_summary

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#97079]
SkiaPerf has detected a performance regression in rater times on the Engine roll here: https://github.com/flutter/flutter/pull/96980

A commit related to the benchmark appears to be https://github.com/flutter/engine/pull/30264.

https://flutter-flutter-perf.skia.org/e/?begin=1642722918&end=1642789127&keys=X7a5f4d5efc625314dab01a9ed5ff3015&num_commits=50&request_type=1&xbaroffset=27242

/cc @WasserEsser @blasten @cyanglaz

**Comment by chinmaygarde** [comment]
The revert has landed.
