### ISSUE TITLE
FAQ: Running Flutter app on a Chromebook

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#9708]
We'd like to explicitly state if this is known to work, or not, and if we support it, or not.

**Comment by abarth** [comment]
It is known not to work.

**Comment by eseidelGoogle** [comment]
Noteably https://github.com/flutter/flutter/issues/9695

**Comment by sethladd** [comment]
Chrome OS systems supporting Android Apps: https://sites.google.com/a/chromium.org/dev/chromium-os/chrome-os-systems-supporting-android-apps

**Comment by raju-bitter** [comment]
Did anyone test with the Samsung Chromebook Plus http://www.samsung.com/us/computing/chromebooks/12-14/xe513c24-k01us-xe513c24-k01us/? It has a “OP1” hexa-core ARM Cortex-A72/A53 processor.
https://www.arm.com/products/processors/cortex-a/cortex-a72-processor.php

**Comment by sethladd** [comment]
@mehmetf have you run a Flutter app on a chromebook?

**Comment by mehmetf** [comment]
Yes, and it works. https://github.com/flutter/flutter/issues/9695 is closed.

We are currently tracking open issues with it at https://github.com/flutter/flutter/labels/platform-arc

**Comment by sethladd** [comment]
Addressed by https://github.com/flutter/website/pull/750
