### ISSUE TITLE
Missing scrolling inertia on iPadOS when using trackpad

### ISSUE THREAD

**Issue by singularity-s0** [flutter/flutter#97084]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Connect an external trackpad to iPad (in this case, I am using the Magic Keyboard)
3. Use the two-finger scroll gesture

**Expected results:** 
Scrolling animation should not stop when I lift my fingers from the trackpad. It should have inertia, just like when using touch input or when scrolling on computers.

**Actual results:** 
Scrolling animation stops abruptly when I lift my fingers from the trackpad.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    var text = "Example Text ";
    for (var i in Iterable.generate(100)) {
      text = text + i.toString() + '\n';
    }
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: SingleChildScrollView(
        child: Text(
          text,
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
No log at all! even with --verbose (except at build time) 
I guess scroll event simply isn't logged.
```

```
Analyzing flutter_application_1...                                      
No issues found! (ran in 3.0s)
```

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale en-US)
    • Flutter version 2.8.1 at /Users/user/Projects/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (5 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (3 available)
(devices omitted)
```

</details>

Video:

https://user-images.githubusercontent.com/12184989/150663131-6f110a09-8e41-490f-902d-eb7c89a938fb.MP4

Comparing trackpad scroll vs finger scroll (the transparent dot indicates trackpad is being used)

**Comment by darshankawar** [comment]
@singularity-s0 
By missing scrolling inertia, do you mean when we try to flung scrollbar, it doesn't scroll correct ? 
If so, can you check if [this](https://github.com/flutter/flutter/issues/78688) issue is similar to your case ?

**Comment by singularity-s0** [comment]
> @singularity-s0 
> 
> By missing scrolling inertia, do you mean when we try to flung scrollbar, it doesn't scroll correct ? 
> 
> If so, can you check if [this](https://github.com/flutter/flutter/issues/78688) issue is similar to your case ?
> 
> 

Hi, thanks for the reply.

No, this issue has nothing to do with scrollbar. As you can see in the video no scrollbar activity is involved.

This issue occurs when one uses the two-finger scroll gesture on iPad. It is only reproducible (and quite obvious) on iPad with (external) trackpad. Scrolling with other input is not affected.

**Comment by singularity-s0** [comment]
> @singularity-s0 
> 
> By missing scrolling inertia, do you mean when we try to flung scrollbar, it doesn't scroll correct ? 
> 
> If so, can you check if [this](https://github.com/flutter/flutter/issues/78688) issue is similar to your case ?
> 
> 

Hi, thanks for the reply.

No, this issue has nothing to do with scrollbar. As you can see in the video no scrollbar activity is involved.

This issue occurs when one uses the two-finger scroll gesture on iPad. It is only reproducible (and quite obvious) on iPad with (external) trackpad. Scrolling with other input is not affected.

**Comment by darshankawar** [comment]
@singularity-s0 
Can you try to see what does `ScrollPosition.isScrollingNotifier` returns if you use two-finger gesture to scroll using trackpad ? Does it return false or true using something like:

```
final ScrollController controller = ScrollController();

  @override
  void initState() {
    controller.addListener(() {
      // always prints "scrolling = true"
      print('scrolling = ${controller.position.isScrollingNotifier.value}');
    });
    super.initState();
  }

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }
```

**Comment by singularity-s0** [comment]
It prints all `false` when scrolling with trackpad and all `true` when scrolling with finger.

**Comment by darshankawar** [comment]
@singularity-s0 
Thanks for verifying. Based on your finding, I believe you are hitting https://github.com/flutter/flutter/issues/75591, so I suggest you to follow-up in it for further updates.
Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.
