### ISSUE TITLE
Flutter app is slow performing UI render after success api request on physical device (iPhone 12 pro max) compare to simulator (iOS)

### ISSUE THREAD

**Issue by cpuell** [flutter/flutter#97097]
## Details

We have an app written with openAPI generator. We also use  pull-to-refresh pub ( https://pub.dev/packages/pull_to_refresh ) It worked fine until we migrated the app to null-safety handling. 

Now we see the app is doing the auto refresh, but takes very long on a physical device compare to running the app in a simulator.

We do not see error messages. Any suggestion how to debug?

**Target Platform:** Flutter Mobile
**Target OS version/browser:** iOS 15.x
**Devices:** iPhone 12 Pro Max

**Comment by danagbemava-nc** [comment]
Hi @cpuell, thanks for filing the issue. 

Can you provide the output of `flutter doctor -v`? 

> Now we see the app is doing the auto refresh, but takes very long on a physical device compare to running the app in a simulator.

Is this referring to the network request or is it something else? 

Also, what mode are you experiencing this issue with? `debug`/`profile`/`release`?

Since you're experiencing this with a third party package, I believe it would be best to file an issue with them so they can properly investigate. 

Thank you

**Comment by cpuell** [comment]
Hello @danagbemava-nc 

the refresh is on page change (open page) also on drag down to refresh, it is a network refresh. 

I would assume it has something to do with openAPIGenerator, which got manually adjusted instead of using the generator, but worth noting, it is working fine on simulator.

Below is the flutter doctor:

`usernameDevicee ios % flutter doctor -v
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.2 21D5039d darwin-x64, locale de-DE)
    • Flutter version 2.8.1 at /Users/username/Development/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (vor 6 Wochen), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/username/Library/Android/sdk
    • Platform android-31, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (3 available)
    • iPhone (mobile) • 00008101-001454861E01001E • ios            • iOS 15.2.1 19C63
    • macOS (desktop)       • macos                     • darwin-x64     • macOS 12.2 21D5039d darwin-x64
    • Chrome (web)          • chrome                    • web-javascript • Google Chrome 97.0.4692.99
    ! Error: iPhone is busy: Preparing the watch for development via iPhone. Xcode will continue when iPhone is finished. (code -10)

• No issues found!`

**Comment by danagbemava-nc** [comment]
I'm not entirely sure I understand. 
Can you share some screen recordings of how the app behaves on the simulator vs how it behaves on the physical device?
