### ISSUE TITLE
any solution??  when i play mp4 video then getting ther crash error for android tv

### ISSUE THREAD

**Issue by iamwasimaftab** [flutter/flutter#97094]
E/flutter ( 6778): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: Source error, null, null)

**Comment by darshankawar** [comment]
Closing this as a duplicate of https://github.com/flutter/flutter/issues/75995
