### ISSUE TITLE
Add a way to adjust icons' font weight

### ISSUE THREAD

**Issue by thorvalld** [flutter/flutter#97092]
for the moment there is no way to adjust an icon's font weight and it would be useful to be able to adjust an icon's weight (light, normal, bold are considerably the most needed ones)

**Comment by darshankawar** [comment]
@thorvalld 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/86636
Please follow-up in it for further updates.
Closing this as a duplicate.
