### ISSUE TITLE
SliverList inside SliverList

### ISSUE THREAD

**Issue by Hellomik2002** [flutter/flutter#97107]
I've run into large scrolling lists. Sometimes you need to write multiple recursive SliverLists.
I used one package (https://pub.dev/packages/sliver_tools) to solve this problem but you can't use MutliSliverList as Builder.
This doesn't work properly if you have 10,000 items (lazy loading, etc.)
Also, you can't add a background color for Sliver Lists, which is a little problematic.
Let's find a new way to implement this or something like that?

**Comment by darshankawar** [comment]
@Hellomik2002 
Can you provide `flutter doctor -v, a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows the current behavior / limitation you are facing ? And what are you trying to achieve exactly ?

**Comment by Hellomik2002** [comment]
For example, you have list items in a list and they have a background color.
I could do Column, with SliverList (Builder) but they can have 100 items inside

![Screen Shot 2022-01-24 at 23 25 54](https://user-images.githubusercontent.com/30003495/150833345-1168d98d-78d2-493a-8f31-eb972090702b.png)

**Comment by darshankawar** [comment]
> a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows the current behavior / limitation you are facing ?

@Hellomik2002

**Comment by Hellomik2002** [comment]
EXAMPLE

```
import 'dart:developer';

import 'package:flutter/material.dart';

const sssColor = [
  Colors.red,
  Colors.orange,
  Colors.cyan,
  Colors.brown,
  Colors.lime,
];

class TrainerMainPage extends StatelessWidget {
  const TrainerMainPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(),
      body: CustomScrollView(
        slivers: [
          const SliverToBoxAdapter(
            child: SizedBox(height: 30),
          ),
          const SliverToBoxAdapter(
            child: SizedBox(height: 30),
          ),
          const SliverToBoxAdapter(
            child: SizedBox(height: 30),
          ),
          const SliverToBoxAdapter(
            child: SizedBox(height: 30),
          ),
          ...List.generate(
            10000,
            (_) => SliverList(
              delegate: SliverChildBuilderDelegate((ctx, _) {
                return Container(
                  height: 50,
                  color: sssColor[_ % sssColor.length],
                );
              }),
            ),
          )
        ],
      ),
    );
  }
}
```

**Comment by darshankawar** [comment]
@Hellomik2002 
Can you take a look at `NestedScrollView` and see if it helps to achieve your purpose ? https://api.flutter.dev/flutter/widgets/NestedScrollView-class.html

Also, take a look at [this](https://gist.github.com/hariangr/0c54129602a38b6570dec8b4a62ba998) gist and see if it helps.

**Comment by Hellomik2002** [comment]
NestedScrollView is a good solution but not for this purpose.
Here I have another problem.
I have a huge number of items that contain an almost equally huge number of items inside them. The NestedScrollView does not serve the purpose of loading this data as a high flowing builder. I need something more adaptive to higher loads. Again, what has the feature of "Nested" in NestedScrollView is the header, whilst I need this feature in body. Are there any widgets from material.dart of any 3rd party packages that can help me execute this without changing their library?

**Comment by darshankawar** [comment]
@Hellomik2002 
I would suggest you to ask this question on support channels like StackOverflow to get a solution on how to implement nested sliverlist to achieve your use case and to know about any 3rd party plugins to do the same.
Closing from here. If you are looking to propose a change in the sliverlist or a bug, then write in comments and I'll reopen it.

**Comment by Hellomik2002** [comment]
Slivers are limited, NestedScrollView can not nest Scroll from another scroll, You can not combine a lot of Scroll widgets in Nested Sliver List.
 I don't want to write List.generate(10 000)
 or Write Super hard logic to implement that.
 Slivers have a lot of limits, You can not put background Color for Example
 of course I can put Container or DecoratedBox widget, but the Phone will be forced to render all Items, and if you have 10k items it is inappropriate.
 If you change the background color of every item, You will see a lines between them with the Color of the under widget.

**Comment by darshankawar** [comment]
@Hellomik2002 
It seems you highlighted current limitation of Slivers. I suggest you to open a new issue and use the new issue template and fill out all requested details and clearly highlighting the limitation or current behavior you are seeing and what changes you would like to see using it, that'll help us to address the issue properly.
