### ISSUE TITLE
[desktop]: desktop:windows (win32) Unable to access Windows::Data and Windows::Pdf

### ISSUE THREAD

**Issue by dillibabu1802** [flutter/flutter#97117]
We have developed a plugin which is support in android, iOS, web and macOS. Now, we are planning to provide support in Windows. So followed the guidelines provided in [https://docs.flutter.dev/desktop#add-desktop-support-to-an-existing-flutter-app](https://docs.flutter.dev/desktop#add-desktop-support-to-an-existing-flutter-app) .

But, we are unable to access the following namespace and their classes.
1. Windows:Data , Windows:Data:Pdf - even after including #include <windows.data.pdf.h>
2. Windows::Storage

Documentation for accessing windows builtin namespace and class are missing.

We also found the same headers is found in different platform folder and don't know which to be used. ex. #include <windows.data.pdf.h> and #include <winrt/Windows.Data.Pdf.h>.

There are few class which is just define and no proper document IPdfDocumentStatics from ABI::Windows::Data::Pdf

Is this restricting from Flutter Windows ? Can any one help me ?

**Comment by stuartmorgan** [comment]
> But, we are unable to access the following namespace and their classes.

It's not clear what this means exactly, but configuring your native build to use whatever libraries you need is up to you; it's not within the score of Flutter itself.

> Documentation for accessing windows builtin namespace and class are missing.

There is nothing Flutter-specific about calling Windows code from within your plugin, so this isn't within the scope of Flutter documentation.



> We also found the same headers is found in different platform folder and don't know which to be used. ex. #include <windows.data.pdf.h> and #include <winrt/Windows.Data.Pdf.h>.

These are not Flutter headers; we can't help with using them.



> and no proper document IPdfDocumentStatics from ABI::Windows::Data::Pdf

These aren't part of Flutter. Issues with documentation of code needs to be addressed to the author of that code.

Closing as there is no Flutter issue described here.

**Comment by dillibabu1802** [comment]
@stuartmorgan , is the Flutter windows is taken care by Flutter ?

I am writing all these codes in this folder structure (windows->XXX_windows_plugin.cpp), I thought flutter is responsible for importing the cpp libraries headers. Please let us know to whom should we check on this. 
[windows_plugin.zip](https://github.com/flutter/flutter/files/7927090/windows_plugin.zip)

**Comment by stuartmorgan** [comment]
> I thought flutter is responsible for importing the cpp libraries headers.

Flutter is responsible for invoking your build file. You are responsible for configuring that build file correctly.

Flutter has no idea what you might want to import or link against so can't possibly do it for you.

> Please let us know to whom should we check on this

If you are looking for help with your own code, see https://flutter.dev/community#community-grid for some resources.
