### ISSUE TITLE
Flutter TextField how to support text edit?

### ISSUE THREAD

**Issue by luckrill** [flutter/flutter#97110]
My requirements

* Get the content selected by the user (the content selected by the mouse). Easy to copy, or delete.
* Get the line where the cursor is located, and get the whole line where the cursor is located.
* Support shortcut key operations, such as line header, line end, file header, file end, line deletion, line copy, etc. 

The above requirements can be easily realized if other GUI frameworks are adopted. 
But when using flutter, I still don't know how to do it.

**Comment by luckrill** [comment]
Where to ask flutter general usage questions？

**Comment by brunoalod** [comment]
You should ask on https://flutter.dev/community. Not sure this belongs here.

**Comment by luckrill** [comment]
Maybe Stackoverflow is suitable for asking my questions
