### ISSUE TITLE
flutter-devicelab-mac-4 in boot loop

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#97119]
flutter-devicelab-mac-4 is in a boot loop becoming healthy for long enough time to be picked up by tasks and the bot getting killed after a couple of minutes.

**Comment by yusuf-goog** [comment]
Will take a look at this device when I'm in the lab.

**Comment by godofredoc** [comment]
It is actually the host, if we have access to remotely power it off I'd suggest to do that as all the ios flakiness is coming from that test bed.

**Comment by yusuf-goog** [comment]
Host has been powered down.

**Comment by keyonghan** [comment]
Re-imaged the bot, and filed [t/209191069](http://m.guts.corp.google.com/?ticket=209191069) to create a new DNS entry.

- [ ] install salt
- [ ] enable swarming user auto login

**Comment by yusuf-goog** [comment]
Sure. What were you able to comeplete with the host already?

**Comment by keyonghan** [comment]
> Sure. What were you able to comeplete with the host already?

Re-imaged the bot and got the dns set up.

**Comment by yusuf-goog** [comment]
Completed setup of the bot according to the docs. Minor update to the doc for clarity. Created bug to update the ideviceinstaller state to work with M1 macs.

@keyonghan Its failing on the device now. I expect something to do with idevice installation location. Can you take a look:

Device healthcheck failed: codesigning_cert: 0 valid identities found;device_pair: Executable idevicepair failed with exit code 1.;battery_level: Executable ideviceinfo failed with exit code 255.;
--

Note that had to install ideviceinstaller as:

arch -arm64 brew install ideviceinstaller

**Comment by yusuf-goog** [comment]
Looks like we need to clear the pairing dialog on the device. Will do this when I'm in the lab.

**Comment by keyonghan** [comment]
Bot is online.
