### ISSUE TITLE
Android Splash Transition Animation

### ISSUE THREAD

**Issue by JsouLiang** [flutter/flutter#97123]
Hey, In my application, I want to close the splash view transition animation.
This is the current effect:

https://user-images.githubusercontent.com/10297030/150783101-49a2f3dd-412b-41a8-af02-98bc0eae3c32.mp4

Look above video, you will see the icon will flash in the green view.

Here is my demo: https://github.com/JsouLiang/splash

I think this not a bug, it's look like a feature: Allow user to set the splash transition animation time.
I read the engine code the Splash has transition animation, and the duration is 500ms
``` java
// DrawableSplashScreen.java
@Override
  public void transitionToFlutter(@NonNull Runnable onTransitionComplete) {
    if (splashView == null) {
      onTransitionComplete.run();
      return;
    }

    splashView
        .animate()
        .alpha(0.0f)
        .setDuration(crossfadeDurationInMillis)  // this is 500ms
        .setListener(
            ...);
  }
```
I think may be we can through the meta-data to allow user set the transition animation duration

**Comment by darshankawar** [comment]
@JsouLiang 
I think your question is better suited for support channels like StackOverflow, so please ask the same there.
Closing from here as it looks like you are looking for code assistance. If you disagree or think this is a bug, write in comments and provide all required details as asked in new issue template.

**Comment by darshankawar** [comment]
@JsouLiang 
Is this a proposal to allow user to set the splash transition animation time ?

@eggfly 
Not sure why did you remove `in triage` label, as I was in process of triaging it.

**Comment by JsouLiang** [comment]
@darshankawar em, this issue's description look like a bug, i will edit it.

**Comment by eggfly** [comment]
@darshankawar  Because JsouLiang will later issue a Pull Request to fix this issue, this is the issue for tracking that PR.

**Comment by JsouLiang** [comment]
@darshankawar hey, I found the splash view logic has changed, it's my problem, sorry
