### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by ezharfahmi** [flutter/flutter#97121]
I kept getting this error message when im running my web on server

this is my base href
`<base href="/web-aotg/">`

manifest.json
<img width="383" alt="Screenshot 2022-01-24 at 3 28 20 PM" src="https://user-images.githubusercontent.com/15267061/150739694-09c41d8f-1e03-4208-a36f-2880d1e437d6.png">

and i declare the link rel like this
`<link rel="manifest" crossorigin="use-credentials" href="manifest.json"/>`

i kept getting this error message
<img width="430" alt="Screenshot 2022-01-24 at 3 29 15 PM" src="https://user-images.githubusercontent.com/15267061/150739832-6420f31e-ab0e-4ae2-95bb-464077d988fd.png">

manifest.json is at the root same with index.html and i notice that the manifest.json is dynamic like this 

`https://urls/web-aotg/manifest.json?1643008869579`

**Comment by maheshmnj** [comment]
Hi @ezharfahmi, Thanks for filing the issue. If i understand correctly when change the base href your app isn't loading at `domain/web-aotg`, is that correct?  If so, Please take a look at [this comment](https://github.com/flutter/flutter/issues/95503#issuecomment-1002949153) and see if it helps resolve the issue. if the issue persists please share the complete output of `flutter doctor -v`
