### ISSUE TITLE
Remove iPhone 4S devices from CI

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#97148]
Following the 2.10 stable cycle, the iPhone 4S devices can be removed from the devicelab. See the RFC at [flutter.dev/go/rfc-32-bit-ios-support](http://flutter.dev/go/rfc-32-bit-ios-support). This can happen as soon as the devices are no longer needed for testing the 2.10 release.

/cc @godofredoc @jmagman

**Comment by yusuf-goog** [comment]
@zanderso who should provide final ok that this device can be removed?

**Comment by zanderso** [comment]
We have consensus, so this can go ahead as soon as the 2.10 release cycle no longer needs the devices.

**Comment by CaseyHillers** [comment]
Moving out of ticket queue and into better flutter releases due to there being no immediate action

**Comment by jmagman** [comment]
The `Mac_ios32` tests should be removed before the device is yanked.

https://github.com/flutter/flutter/blob/b7424c619ca527b9b8bbd14e82ac5267bcc31893/.ci.yaml#L112
https://github.com/flutter/flutter/blob/b7424c619ca527b9b8bbd14e82ac5267bcc31893/.ci.yaml#L3473
etc

**Comment by jmagman** [comment]
@CaseyHillers is this done?

**Comment by CaseyHillers** [comment]
No, while this is done on tip of tree, we have to wait for it to roll through to stable (unless we want to CP it).

Assigning to @yusuf-goog to track as he'll likely be the one to remove them from the lab.

**Comment by jmagman** [comment]
Flutter 3 has shipped, I think it's safe to remove from the lab?

**Comment by godofredoc** [comment]
Context: the configs were deleted a long time ago, the removal request is for the hardware.

**Comment by jmagman** [comment]
+1 just an opportunity to replace it with a newer iPhone to add to available devicelab capacity. This doesn't impact engineering at all, no rush.

**Comment by yusuf-goog** [comment]
mac-11 device has been swapped out. Waiting for it to be added to the provisioning profile (https://github.com/flutter/flutter/issues/104762). Closing this.
