### ISSUE TITLE
Create different themes for buttons within the ThemeData() widget. 

### ISSUE THREAD

**Issue by Wenutz** [flutter/flutter#97151]
## Use case

In my app I want to give the customer the choice between a dozen of themes. So I am creating a theme changer.
My themes contain various **outlinedButtons()** with different colors (like in the picture). I know how to set up a theme for all of these  **outlinedButtons()** with a themedata() widget. I also know how to set up a special theme for a particular**outlinedButtons()** by wrapping it in a theme() widget. However, setting up the theme changer with a dozens themes is really painful with this type of design.  

![c6039f55f3ac67bf863bb7740480cb58](https://user-images.githubusercontent.com/71794625/150840215-fc0dd302-299c-4dfb-81ab-845f56e40f87.jpg)

## Proposal

It would be great if we could set up different themes for outlined buttons directly  in the themeData() widget. We can do that with text(bodytext1,bodytext2, headline1, headline2...). Something like outlinedButtonTheme1, outlinedButtonTheme2 would be great.

**Comment by danagbemava-nc** [comment]
Hi @Wenutz, I'm not entirely sure having multiple global themes for buttons is a good idea. Text having different themes makes sense conceptually because each "level" of Text serves a particular purpose and even then, we do not have multiple themes for each level of text. 

Moreover, I believe what you're trying to achieve can be done by defining the necessary colors that you may need in your app. Because when you switch themes, what you're essentially doing is "changing colors". 

So you can define custom buttons for each of the "sections" that have different colors and retrieve the colors from the main theme. 

For example, in the code below, when the primary color changes, the color of the Button should also change accordingly. 

```dart
class SectionOneButton extends StatelessWidget {
  // some extra parameters

  @override
  Widget build(BuildContext context) {
    final color = Theme.of(context).primaryColor;

    return OutlinedButton(
      onPressed: () {},
      child: Text('some text'),
      style: OutlinedButton.styleFrom(
        backgroundColor: color,
      ),
    );
  }
}
```

You may also check out this package https://pub.dev/packages/stacked_themes which allows you to set multiple themes

**Comment by Wenutz** [comment]
Yes I can make custom colors for custom buttons but I thought it would make sense to have it done within the themeData widget. 
I also think the whole colorScheme class confusing. What is the difference between these colors and the colors we set in ThemeData widget? Better documentation and examples "for dummies" would help. Most of the ones found online center around setting light and dark themes.

**Comment by danagbemava-nc** [comment]
> I also think the whole colorScheme class confusing. What is the difference between these colors and the colors we set in ThemeData widget

There's an open issue that seeks to provide more documentation about how the whole `ColorScheme` works in https://github.com/flutter/flutter/issues/36624. You may follow up there for more information. 
There's also ongoing work to update the Material Theme System in https://github.com/flutter/flutter/issues/91772. 

>  Most of the ones found online center around setting light and dark themes.

I believe the concept can be applied from these examples. You aren't bound to use only those themes in your applications. 

You can also check out this third-party package which might help you understand how the flutter theme system works https://pub.dev/packages/flex_color_scheme

**Comment by rydmike** [comment]
Hi @Wenutz in a companion app to the above [FlexColorScheme](https://pub.dev/packages/flex_color_scheme) package mentioned by @danagbemava-nc above you can dynamically change between 36 (72 if you count light and dark separately) different themes dynamically on the fly in the app. You can find a live Web version of that app here: https://rydmike.com/flexcolorschemeV4Tut5

I think the theme switching capabilities used in it might be applicable for your dozen user changeable themes as well.

The package docs contains tutorials with increasing complexity, ending up with the above rather involved "Themes Playground" demo and companion app, that will actual also generate copy/paste theme config setup code for the package, for the theme you are looking at / have configured in the app.

In any case, the general principle used in it, to switch among different themes is applicable to any `ThemeData` themes you don't need the package for that. The package actually only assist in creating fancy standard `ThemeData` objects. 

The code in included examples also show how the theme switching is done and even the source of the **ThemesPlayground** companion app is open source. It is bundled in the package sample as example 5, but examples 3 and 4 use the same theme switching principle and they might be simpler to follow. 

In the examples, the selected themes and all config options for them, are also persisted locally, using a service abstraction and 3 alternative implementations, mem only, (no persisted) and two alternative implementations persisting settings using Hive and Shard Preferences. packages.

> **Disclosure** I'm the author of FlexColorScheme.
> I am also working on some cool new feature for the package, to properly utilize the new colors in Flutter 2.10 released updated M3 based `ColorScheme`, plus more confidgurable color seeding for it than Flutter SDK currently provides via `ColorScheme.fromSeed`. Those will be some pretty cool new stuff and features coming to an updated version of the package a bit later. Even so, it still just at the end of the day makes an even fancier `ThemeData` object. Which can be tricky to code manually, I don't even bother anymore, I just use my own package :D
