### ISSUE TITLE
[BUG] video player on iOS unable to play video if filename has non-english asian characters

### ISSUE THREAD

**Issue by premingiet** [flutter/flutter#97168]
I have some thai characters in my filename, now issue is, on android, the video player is playing perfectly, but on iOS, its unable to initialize the controller at all. Please fix this issue.

```How to reproduce this bug```
use the default example of video player and use a physical iphone device. Pick a local video file, which has asian characters in it. Specifically i tried with thai characters. Now do same thing for android. You will notice, on android its able to play the file but on iOS its unable because of characters in filename.

```i am using```
video_player: 2.2.7

```flutter doctor -v command output```
```dart
[✓] Flutter (Channel beta, 2.10.0-0.2.pre, on macOS 12.1 21C52 darwin-arm, locale en-IN)
    • Flutter version 2.10.0-0.2.pre at /Users/prem/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 73adb1406a (5 days ago), 2022-01-19 17:02:56 -0600
    • Engine revision 74b74b10ea
    • Dart version 2.16.0 (build 2.16.0-134.1.beta)
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/prem/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (3 available)
    • RMX1992 (mobile)       • 52be8e85                  • android-arm64  • Android 11 (API 30)
    • prem’s iPhone (mobile) • 00008110-000578A611A1801E • ios            • iOS 15.2.1 19C63
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 97.0.4692.71

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

**Comment by darshankawar** [comment]
@premingiet 
Current video_player version is `^2.2.15`, so can you upgrade to it and try to see if you still get same behavior ?
Also, curious to know, how do you have a video with a filename on iOS :) ? I never saw such a thing.

**Comment by premingiet** [comment]
by video with a filename i meant, i received a video file from someone, and that video-file had its name in asian characters. For example 
> อักษรไทย.mp4

also ```video_player version is ^2.2.15``` had same issue.

okay i just fixed the issue. Actually local file path String needs to be encoded with ```Uri.encodeFull```  in order to encode path with ```percent-encoding``` for controller to recognise and play the video file. Here is how i fixed the issue.

```dart
final String _localFilePath = "";
final String _encoded = Uri.encodeFull(_localFilePath);
final io.File _videoFile = io.File(_encoded);
controller = VideoPlayerController.file(_videoFile); 
```

This also fixed the issue of video player where if local filename or path had ```space``` in it, then also previously it was not playing video, but by this method, now it ```supports all file path with or without spaces``` and also ```fixes the issue if file name or file path has non-english or asian characters in it.```

**Comment by darshankawar** [comment]
Thanks for the update and resolution. Closing this as resolved per above comment.
