### ISSUE TITLE
Is it safe to delete cache folder inside Flutter SDK?

### ISSUE THREAD

**Issue by bhanuka96** [flutter/flutter#97178]
I need to save space on my computer, So, is it safe to delete entire cache folder in flutter SDK? Full path is `.../flutter/bin/cache`

**Comment by jonahwilliams** [comment]
Yes, provided you want to redownload everything the next time you use Flutter

**Comment by bhanuka96** [comment]
@jonahwilliams Thanks it's better not to delete.
