### ISSUE TITLE
[in_app_purchase][Android]: crashes when buyNonConsumable products from the Play Store

### ISSUE THREAD

**Issue by GuruCM** [flutter/flutter#97186]
**I am facing an issue after upgrade targetsdk to 30 and implementing using '[in_app_purchase] 2.0.1' plugin.**

What I did so far:
1. added 3 products on Play Store that are visible and active.
2. with "in_app_purchase: ^1.0.6" submitted build for alpha testing, since that is required for in-app purchase to work.
3. For "in_app_purchase: ^1.0.6" working properly with no issues 
4. I am trying to update app so have to upgrade targetsdk 30 or above, using "[in_app_purchase] 2.0.1" 

Code:
5. Using : in_app_purchase: 2.0.1 

````
final InAppPurchase _inAppPurchase = InAppPurchase.instance;
@override
  void initState() {
    if (defaultTargetPlatform == TargetPlatform.android) {
      InAppPurchaseAndroidPlatformAddition.enablePendingPurchases();
    }
}


void initStore()
{
 _isStoreAvailable  = await _inAppPurchase.isAvailable();
         log("_isStoreAvailable:$_isStoreAvailable");
        if(_isStoreAvailable){
          List<String> _kProductIds = [..._pSubscriptionList.map((e) => e.mSku.toString())] ;
          _StoreProductDetailResponse = await _inAppPurchase.queryProductDetails(_kProductIds.toSet());
		  // here getting all product-Details from play-store
        }
}

void startbuy(){		  
	try {
	
		PurchaseParam purchaseParam = GooglePlayPurchaseParam( productDetails: productDetails,  applicationUserName: <package-id> ) ;
		await _inAppPurchase.buyNonConsumable(  purchaseParam: purchaseParam);
		//app crashes here below is error log
		} 
		catch (e) {
			print(e);
		}

}
````
6. At the moment _inAppPurchase.buyNonConsumable(  purchaseParam: purchaseParam) crashes every single time with the following log:
Error Log:

```
java.lang.NoSuchMethodError: No virtual method setReplaceSkusProrationMode(I)Lcom/android/billingclient/api/BillingFlowParams$Builder; in class Lcom/android/billingclient/api/BillingFlowParams$Builder; or its super classes (declaration of 'com.android.billingclient.api.BillingFlowParams$Builder' appears in /data/app/~~-Q8OPX9acI_0LdwzF33swg==/<package-id>-wPRF8RoVurOYBXVdRGygqg==/base.apk)
E/AndroidRuntime( 9134): 	at io.flutter.plugins.inapppurchase.MethodCallHandlerImpl.launchBillingFlow(MethodCallHandlerImpl.java:266)
E/AndroidRuntime( 9134): 	at io.flutter.plugins.inapppurchase.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:126)
E/AndroidRuntime( 9134): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/AndroidRuntime( 9134): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:178)
E/AndroidRuntime( 9134): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$handleMessageFromDart$0$DartMessenger(DartMessenger.java:206)
E/AndroidRuntime( 9134): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$6ZD1MYkhaLxyPjtoFDxe45u43DI.run(Unknown Source:12)
E/AndroidRuntime( 9134): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime( 9134): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 9134): 	at android.os.Looper.loop(Looper.java:233)
E/AndroidRuntime( 9134): 	at android.app.ActivityThread.main(ActivityThread.java:8068)
E/AndroidRuntime( 9134): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 9134): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
E/AndroidRuntime( 9134): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
I/Process ( 9134): Sending signal. PID: 9134 SIG: 9
```

**Flutter doctor results:**
```

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19044.1466], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.63.1)
[√] Connected device (3 available)

• No issues found!
```

**Comment by darshankawar** [comment]
@GuruCM 
Check [this](https://stackoverflow.com/questions/62363025/in-app-purchase-crashes-when-fetching-products-from-the-play-store-in-flutter) link and underlying solution and see if it helps.

**Comment by GuruCM** [comment]
@darshankawar  Hi , 
thank you for replaying 

[this ](https://stackoverflow.com/questions/62363025/in-app-purchase-crashes-when-fetching-products-from-the-play-store-in-flutter) link is not helpful , as i am using only "[in_app_purchase] 2.0.1"

previous version "in_app_purchase: ^1.0.6" working properly with no issues
when i am trying to update my app , google plays tore require to have targetSDK version 30 or greater , for this reason 
made targetsdk 30  using "[in_app_purchase] 2.0.1"

Able to get all product details from store , only when i call buy method crashes every single time with the above error log :
```_inAppPurchase.buyNonConsumable(  purchaseParam: purchaseParam)```

**Comment by darshankawar** [comment]
@GuruCM 
What version of `implementation 'com.android.billingclient:billing` are you using in gradle file ?

**Comment by GuruCM** [comment]
@darshankawar  
Hi , Using :  billingclient:billing version : 3.0.2
`implementation 'com.android.billingclient:billing:3.0.2'`

Read somewhere to remove  billingclient:billing from app gradle file so tried removing billingclient:billing , don't work

I am share my project and app/gradle and Android Manifest file , please see if i am missing anything 

1. android/app/build.gradle:

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 30

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        // disable 'InvalidPackage'
        disable 'MissingTranslation'
        abortOnError false
        disable 'InvalidPackage'
    }

    defaultConfig {
        applicationId project.APP_ID // from key-store-file
        minSdkVersion 21
        targetSdkVersion 30
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            signingConfig signingConfigs.debug
        }
    }
    buildToolsVersion '30.0.0'
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.android.billingclient:billing:3.0.2'
    implementation 'com.android.support:multidex:1.0.3'

}


apply plugin: 'com.google.gms.google-services'

```


2. android/build.gradle
```
buildscript {
    ext.kotlin_version = '1.4.32'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.4'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}  ```



3. Android manifest: 

``` 
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="app_id">

    <uses-sdk tools:overrideLibrary="com.google.zxing.client.android" />
      
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="com.android.vending.BILLING" />
	```
	
  ``` <application
       android:name="io.flutter.app.FlutterApplication"
        android:label="sample_app"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize"
            android:usesCleartextTraffic="true">
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>

        </activity>
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>

 ```

**Comment by darshankawar** [comment]
Since the Google Play Billing library for `in_app_purchase` isn't yet migrated to 4.0.0 which I think may be required since you said to have upgraded to Android 30: https://github.com/flutter/flutter/issues/88664 and hence the error : `No virtual method setReplaceSkusProrationMode(I)Lcom/android/billingclient/api/BillingFlowParams$Builder; in class Lcom/android/billingclient/api/BillingFlowParams$Builder; or its super classes (declaration of 'com.android.billingclient.api.BillingFlowParams$Builder' appears in /data/app/~~-Q8OPX9acI_0LdwzF33swg==/<package-id>-wPRF8RoVurOYBXVdRGygqg==/base.apk)
E/AndroidRuntime( 9134): 	at io.flutter.plugins.inapppurchase.MethodCallHandlerImpl.launchBillingFlow(MethodCallHandlerImpl.java:266)`


I am going ahead and labeling it for further input from the team.

/cc @mvanbeusekom

**Comment by GuruCM** [comment]
hi @darshankawar  @mvanbeusekom 
is there any config / code change required from my side to fix ?

**Comment by stuartmorgan** [comment]
> Since the Google Play Billing library for `in_app_purchase` isn't yet migrated to 4.0.0 which I think may be required since you said to have upgraded to Android 30

I'm not sure why you believe this is related; there's no requirement yet to use 4.0.

**Comment by stuartmorgan** [comment]
> Read somewhere to remove billingclient:billing from app gradle file so tried removing billingclient:billing , don't work

Do you have any other dependencies that include this library? The error you are seeing can be caused by multiple inclusion of the library.

**Comment by dgilperez** [comment]
We just got hit by this. We use _purchases_flutter_ as well, that upgraded to Billing 4.0 a few versions ago: https://pub.dev/packages/purchases_flutter/changelog#340

Is there anything we can do to use both libraries at this point? Is there any work going on to push _in_app_purchase_ to support the latest version? 

Using: 

```
  in_app_purchase: ^2.0.1
  purchases_flutter: ^3.9.2
```

Flutter doctor: 
```
> Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6 20G165 darwin-x64, locale es-ES)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.63.2)
[✓] Connected device (3 available)
```

Thanks :)

**Comment by gupinot** [comment]
"flutter channel stable && flutter upgrade && flutter pub upgrade" fixes this issue for me.

**Comment by rguntha** [comment]
I would like to use both flutter_inapp_purchase (for IOS) and in_app_purchase (for Android) in my app.

But I am unable to use, as the app crashes with the above mentioned exception.

flutter_inapp_purchase uses the billing client version 4.0

Even when I set the billing_client version to 3.0.0 in build.gradle, the app crashes.

Is there any way I can make both of them to work together, without resorting to keeping multiple branches, one for IOS where only flutter_inapp_purchase is in the pubspec.yaml and one for in_app_purchase in pubspect.yaml for Android?

**Comment by BasharShehab** [comment]
This package is currently useless. You can use flutter_inapp_purchases instead, but for some reason I don't get purchaseUpdated updates when there's an error in payment or user cancelled

**Comment by Paul-cbt** [comment]
Same issue here.

```
√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.19044.1586], locale en-US)
    • Flutter version 2.10.3 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (3 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\paulc\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.65.2)
    • VS Code at C:\Users\paulc\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.36.0

[√] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19044.1586]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 99.0.4844.74
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 99.0.1150.46

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

**Comment by darshankawar** [comment]
@dgilperez 

> We just got hit by this. We use _purchases_flutter_ as well, that upgraded to Billing 4.0 a few versions ago: https://pub.dev/packages/purchases_flutter/changelog#340

There's currently no requirement for `in_app_purchase` to use Billing 4.0, but since you are using community plugin that uses Billing 4.0, I guess the conflict could be causing it. Is there a way for you to confirm if the crash occurs only using `in_app_purchase` plugin ?

@Paul-cbt 
Are you using any other similar community plugin or this is purely using Flutter's first party plugin `in_app_purchase` ?

**Comment by dgilperez** [comment]
@darshankawar the crash occurs when using the two packages together. But I ended up switching to revenuecat completely. The current state of this package made it unusable for us.

**Comment by NitoBa** [comment]
I was having the same problem here. I was using two packages to make in-app purchases. The packages were:
`flutter_inapp_purchase: ^5.1.2` and `in_app_purchase: ^3.0.2` removed the `in_app_purchase: ^3.0.2`
and the purchases started working again and the app didn't crash. 
Apparently using two packages was causing this problem.

I'm using the flutter at version 2.10.3

**Comment by Paul-cbt** [comment]
> 

@darshankawar I'm not using any other other plugins...

crash with:
`E/AndroidRuntime( 5494): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/AndroidRuntime( 5494): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
E/AndroidRuntime( 5494): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
E/AndroidRuntime( 5494): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
E/AndroidRuntime( 5494): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime( 5494): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 5494): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime( 5494): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime( 5494): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5494): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime( 5494): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/Process ( 5494): Sending signal. PID: 5494 SIG: 9
`

**Comment by Paul-cbt** [comment]
Fixed with changing build.gradle from:
`   def billing_version = "4.1.0"
    implementation "com.android.billingclient:billing:$billing_version"
    implementation platform('com.google.firebase:firebase-bom:29.1.0')
    implementation 'com.google.firebase:firebase-analytics'
     implementation 'com.android.billingclient:billing:3.0.2'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"`

to: `  

    // implementation "com.android.billingclient:billing:$billing_version"
    implementation platform('com.google.firebase:firebase-bom:29.1.0')
    implementation 'com.google.firebase:firebase-analytics'
    // implementation 'com.android.billingclient:billing:3.0.2'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"`

**Comment by bloehle13** [comment]
Dropping from version 4.0.0 to 3.0.2 did the trick for me too!

`    // def billing_version = 4.0.0
    def billing_version = "3.0.2"
    implementation "com.android.billingclient:billing:$billing_version"`

**Comment by rguntha** [comment]
@bloehle13 So are you using both  flutter_inapp_purchase and in_app_purchase  in your app?

> Dropping from version 4.0.0 to 3.0.2 did the trick for me too!
> 
> ```
>     def billing_version = "3.0.2"
>     implementation "com.android.billingclient:billing:$billing_version"
> ```

@bloehle13 So are you using both  flutter_inapp_purchase and in_app_purchase  in your app?
