### ISSUE TITLE
[Chromebook]: App fails to launch on chrome browser with `Failed to launch browser after 3 tries.` log

### ISSUE THREAD

**Issue by ANIL80531** [flutter/flutter#97191]
### ## Steps to Reproduce
**export CHROME_EXECUTABLE="/usr/bin/garcon-url-handler"**

<details>
<summary> error log </summary>

```

anil80531@penguin:~/myapp$ flutter run -v
[ +333 ms] executing: uname -m
[ +158 ms] Exit code 0 from: uname -m
[   +1 ms] aarch64
[  +35 ms] executing: [/home/anil80531/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +24 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 7ec334827ac708edfa6986217b3a41b0814af411
[   +3 ms] executing: [/home/anil80531/flutter/] git tag --points-at 7ec334827ac708edfa6986217b3a41b0814af411
[  +48 ms] Exit code 0 from: git tag --points-at 7ec334827ac708edfa6986217b3a41b0814af411
[   +7 ms] executing: [/home/anil80531/flutter/] git describe --match *.*.* --long --tags 7ec334827ac708edfa6986217b3a41b0814af411
[ +123 ms] Exit code 0 from: git describe --match *.*.* --long --tags 7ec334827ac708edfa6986217b3a41b0814af411
[   +3 ms] 2.9.0-0.0.pre-491-g7ec334827a
[  +64 ms] executing: [/home/anil80531/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +28 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/master
[   +1 ms] executing: [/home/anil80531/flutter/] git ls-remote --get-url origin
[  +30 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +392 ms] Unable to locate an Android SDK.
[  +23 ms] executing: [/home/anil80531/flutter/] git rev-parse --abbrev-ref HEAD
[  +38 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +2 ms] master
[ +307 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +22 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +370 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +20 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +542 ms] Skipping pub get: version match.
[ +611 ms] Generating /home/anil80531/myapp/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +609 ms] Launching lib/main.dart on Chrome in debug mode...
[ +676 ms] Updating assets
[ +418 ms] Waiting for connection from debug service on Chrome...
[ +370 ms] <- reset
[  +39 ms] /home/anil80531/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/anil80531/flutter/bin/cache/dart-sdk/bin/snapshots/frontend_server.dart.snapshot --sdk-root /home/anil80531/flutter/bin/cache/flutter_web_sdk/
--incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
/tmp/flutter_tools.SGYKSU/flutter_tool.KAVVBG/app.dill --libraries-spec file:///home/anil80531/flutter/bin/cache/flutter_web_sdk/libraries.json --packages
/home/anil80531/myapp/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation
--filesystem-root /tmp/flutter_tools.SGYKSU/flutter_tools.URRREJ --filesystem-scheme org-dartlang-app --initialize-from-dill
build/b1b715402d823b7fd5c2b68d2edcb2ce.cache.dill.track.dill --platform
file:///home/anil80531/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk_sound.dill --sound-null-safety
[  +64 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+175554 ms] Waiting for connection from debug service on Chrome... (completed in 176.0s)
[  +28 ms] Synced 29.3MB.
[   +5 ms] <- accept
[   +4 ms] Caching compiled dill
[+3371 ms] Using 
[  +12 ms] executing: uname -m
[  +86 ms] Exit code 0 from: uname -m
[   +1 ms] aarch64
[+2485 ms] Failed to launch browser after 3 tries. Command used to launch it: /usr/bin/garcon-url-handler
                    --user-data-dir=/tmp/flutter_tools.SGYKSU/flutter_tools_chrome_device.EAXMOE --remote-debugging-port=39741
--disable-background-timer-throttling
                    --disable-extensions --disable-popup-blocking --bwsi --no-first-run --no-default-browser-check --disable-default-apps --disable-translate
                    http://localhost:43879
[  +57 ms] "flutter run" took 185,517ms.
[  +44 ms] Failed to launch browser. Make sure you are using an up-to-date Chrome or Edge. Otherwise, consider using -d web-server instead and filing an issue
at
           https://github.com/flutter/flutter/issues.
[  +12 ms] 
           #0      ChromiumLauncher._spawnChromiumProcess.<anonymous closure> (package:flutter_tools/src/web/chrome.dart:294:13)
           #1      _runUserCode (dart:async/stream_pipe.dart:11:23)
           #2      Stream.firstWhere.<anonymous closure> (dart:async/stream.dart:1647:9)
           #3      _rootRun (dart:async/zone.dart:1418:47)
           #4      _CustomZone.run (dart:async/zone.dart:1328:19)
           #5      _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
           #6      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)
           #7      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:7)
           #8      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #9      _ForwardingStream._handleDone (dart:async/stream_pipe.dart:99:10)
           #10     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:161:13)
           #11     _rootRun (dart:async/zone.dart:1418:47)
           #12     _CustomZone.run (dart:async/zone.dart:1328:19)
           #13     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
           #14     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)
           #15     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:7)
           #16     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #17     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
           #18     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
           #19     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
           #20     _LineSplitterSink.close (dart:convert/line_splitter.dart:154:11)
           #21     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
           #22     _rootRun (dart:async/zone.dart:1418:47)
           #23     _CustomZone.run (dart:async/zone.dart:1328:19)
           #24     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
           #25     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)
           #26     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:7)
           #27     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #28     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
           #29     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
           #30     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
           #31     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:305:20)
           #32     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:81:18)
           #33     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
           #34     _rootRun (dart:async/zone.dart:1418:47)
           #35     _CustomZone.run (dart:async/zone.dart:1328:19)
           #36     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
           #37     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)
           #38     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:7)
           #39     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #40     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:782:19)
           #41     _StreamController._closeUnchecked (dart:async/stream_controller.dart:637:7)
           #42     _StreamController.close (dart:async/stream_controller.dart:630:5)
           #43     _Socket._onData (dart:io-patch/socket_patch.dart:2321:21)
           #44     _rootRunUnary (dart:async/zone.dart:1442:13)
           #45     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
           #46     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
           #47     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
           #48     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
           #49     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
           #50     _StreamController._add (dart:async/stream_controller.dart:648:7)
           #51     _StreamController.add (dart:async/stream_controller.dart:596:5)
           #52     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1846:35)
           #53     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1315:18)
           #54     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
           #55     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
           #56     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:122:13)
           #57     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)
           
           
[ +320 ms] ensureAnalyticsSent: 311ms
[  +12 ms] Running shutdown hooks
[  +11 ms] Shutdown hooks complete
[  +28 ms] exiting with code 1




flutter doctor -v
[✓] Flutter (Channel master, 2.9.0-1.0.pre.491, on Debian GNU/Linux 11 (bullseye) 5.4.157-17191-g6575d22de694, locale en_US.UTF-8)
    • Flutter version 2.9.0-1.0.pre.491 at /home/anil80531/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7ec334827a (4 hours ago), 2022-01-24 19:50:10 -0800
    • Engine revision 83cfdcc8f1
    • Dart version 2.17.0 (build 2.17.0-51.0.dev)
    • DevTools version 2.9.2

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/garcon-url-handler

[✓] VS Code (version 1.63.2)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • unknown

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>

**Comment by darshankawar** [comment]
@ANIL80531 
I am assuming you have chromOS and trying to run on web using Chromebook ?
Can you let us know which instructions you followed to install and run the app ?
Thanks.

**Comment by ANIL80531** [comment]
I cloned master repo
Set chrome executable to garcon url handler in crostini and flutter doctor
detected chrome which is out side of crostini VM when I tried this first
time a few weeks ago it worked for first time but later it never worked
although it still open 3 tried tab in chrome but shows failed to connect
chrome.

**Comment by ANIL80531** [comment]
I tried flutter create myapp
cd myapp
Flutter run -d chrome

**Comment by darshankawar** [comment]
@ANIL80531 
Does that mean, running a fresh app too shows the same behavior ?
Can you follow steps mentioned in this document and see if you get through ? https://docs.flutter.dev/get-started/install/chromeos
Also, can you provide hardware specification of the machine on which you are running this ? e.g: total RAM supported.

**Comment by darshankawar** [comment]
Thanks for the details. Labeling it for further investigation.
Maybe related: https://github.com/flutter/flutter/issues/76456

/cc @Hixie

**Comment by ANIL80531** [comment]
Same even after flutter upgrade

## Logs

<details>
<summary>Logs</summary>


anil80531@penguin:~/myapp$ flutter run -v
[ +518 ms] executing: uname -m
[ +203 ms] Exit code 0 from: uname -m
[   +2 ms] aarch64
[  +44 ms] executing: [/home/anil80531/flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[  +57 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 4fa0e0d449f37e929697c414e13410d4dff1434f
[   +8 ms] executing: [/home/anil80531/flutter/] git tag --points-at
4fa0e0d449f37e929697c414e13410d4dff1434f
[ +100 ms] Exit code 0 from: git tag --points-at 4fa0e0d449f37e929697c414e13410d4dff1434f
[  +13 ms] executing: [/home/anil80531/flutter/] git describe --match *.*.* --long --tags
4fa0e0d449f37e929697c414e13410d4dff1434f
[ +185 ms] Exit code 0 from: git describe --match *.*.* --long --tags
4fa0e0d449f37e929697c414e13410d4dff1434f
[   +3 ms] 2.10.0-0.0.pre-334-g4fa0e0d449
[  +65 ms] executing: [/home/anil80531/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +28 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/master
[   +2 ms] executing: [/home/anil80531/flutter/] git ls-remote --get-url origin
[  +33 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +523 ms] executing: [/home/anil80531/flutter/] git rev-parse --abbrev-ref HEAD
[  +37 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] master
[ +309 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +24 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +438 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +19 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +717 ms] Skipping pub get: version match.
[ +767 ms] Generating
/home/anil80531/myapp/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +718 ms] Launching lib/main.dart on Chrome in debug mode...
[ +706 ms] Updating assets
[ +429 ms] Waiting for connection from debug service on Chrome...
[ +367 ms] <- reset
[  +44 ms] /home/anil80531/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/anil80531/flutter/bin/cache/dart-sdk/bin/snapshots/frontend_server.dart.snapshot --sdk-root
/home/anil80531/flutter/bin/cache/flutter_web_sdk/ --incremental --target=dartdevc
--debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true
--output-dill /tmp/flutter_tools.BMAPLS/flutter_tool.KVGAJY/app.dill --libraries-spec
file:///home/anil80531/flutter/bin/cache/flutter_web_sdk/libraries.json --packages
/home/anil80531/myapp/.dart_tool/package_config.json -Ddart.vm.profile=false
-Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root
/tmp/flutter_tools.BMAPLS/flutter_tools.PBKHNP --filesystem-scheme org-dartlang-app
--initialize-from-dill build/b1b715402d823b7fd5c2b68d2edcb2ce.cache.dill.track.dill --platform
file:///home/anil80531/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk_sound.dill
--sound-null-safety
[  +60 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+149004 ms] Waiting for connection from debug service on Chrome... (completed in 149.4s)
[   +8 ms] Synced 29.3MB.
[   +5 ms] <- accept
[   +3 ms] Caching compiled dill
[ +500 ms] Using 
[  +16 ms] executing: uname -m
[  +33 ms] Exit code 0 from: uname -m
[   +1 ms] aarch64
[+3637 ms] Failed to launch browser after 3 tries. Command used to launch it:
/usr/bin/garcon-url-handler
                    --user-data-dir=/tmp/flutter_tools.BMAPLS/flutter_tools_chrome_device.FWGDPY
                    --remote-debugging-port=36433 --disable-background-timer-throttling
--disable-extensions
                    --disable-popup-blocking --bwsi --no-first-run --no-default-browser-check
--disable-default-apps
                    --disable-translate http://localhost:46251
[  +40 ms] "flutter run" took 157,706ms.
[  +36 ms] Failed to launch browser. Make sure you are using an up-to-date Chrome or Edge.
Otherwise,
           consider using -d web-server instead and filing an issue at
           https://github.com/flutter/flutter/issues.
[   +5 ms] 
           #0      ChromiumLauncher._spawnChromiumProcess.<anonymous closure>
           (package:flutter_tools/src/web/chrome.dart:294:13)
           #1      _runUserCode (dart:async/stream_pipe.dart:11:23)
           #2      Stream.firstWhere.<anonymous closure> (dart:async/stream.dart:1647:9)
           #3      _rootRun (dart:async/zone.dart:1418:47)
           #4      _CustomZone.run (dart:async/zone.dart:1328:19)
           #5      _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
           #6      _BufferingStreamSubscription._sendDone.sendDone
(dart:async/stream_impl.dart:394:13)
           #7      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:7)
           #8      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #9      _ForwardingStream._handleDone (dart:async/stream_pipe.dart:99:10)
           #10     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:161:13)
           #11     _rootRun (dart:async/zone.dart:1418:47)
           #12     _CustomZone.run (dart:async/zone.dart:1328:19)
           #13     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
           #14     _BufferingStreamSubscription._sendDone.sendDone
(dart:async/stream_impl.dart:394:13)
           #15     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:7)
           #16     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #17     _SinkTransformerStreamSubscription._close
(dart:async/stream_transformers.dart:87:11)
           #18     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
           #19     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
           #20     _LineSplitterSink.close (dart:convert/line_splitter.dart:154:11)
           #21     _SinkTransformerStreamSubscription._handleDone
           (dart:async/stream_transformers.dart:132:24)
           #22     _rootRun (dart:async/zone.dart:1418:47)
           #23     _CustomZone.run (dart:async/zone.dart:1328:19)
           #24     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
           #25     _BufferingStreamSubscription._sendDone.sendDone
(dart:async/stream_impl.dart:394:13)
           #26     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:7)
           #27     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #28     _SinkTransformerStreamSubscription._close
(dart:async/stream_transformers.dart:87:11)
           #29     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
           #30     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
           #31     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:305:20)
           #32     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:81:18)
           #33     _SinkTransformerStreamSubscription._handleDone
           (dart:async/stream_transformers.dart:132:24)
           #34     _rootRun (dart:async/zone.dart:1418:47)
           #35     _CustomZone.run (dart:async/zone.dart:1328:19)
           #36     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
           #37     _BufferingStreamSubscription._sendDone.sendDone
(dart:async/stream_impl.dart:394:13)
           #38     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:7)
           #39     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #40     _SyncStreamControllerDispatch._sendDone
(dart:async/stream_controller.dart:782:19)
           #41     _StreamController._closeUnchecked (dart:async/stream_controller.dart:637:7)
           #42     _StreamController.close (dart:async/stream_controller.dart:630:5)
           #43     _Socket._onData (dart:io-patch/socket_patch.dart:2321:21)
           #44     _rootRunUnary (dart:async/zone.dart:1442:13)
           #45     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
           #46     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
           #47     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
           #48     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
           #49     _SyncStreamControllerDispatch._sendData
(dart:async/stream_controller.dart:774:19)
           #50     _StreamController._add (dart:async/stream_controller.dart:648:7)
           #51     _StreamController.add (dart:async/stream_controller.dart:596:5)
           #52     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1846:35)
           #53     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1315:18)
           #54     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
           #55     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
           #56     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:122:13)
           #57     _RawReceivePortImpl._handleMessage
(dart:isolate-patch/isolate_patch.dart:193:5)
           
           
[ +276 ms] ensureAnalyticsSent: 257ms
[   +8 ms] Running shutdown hooks
[   +3 ms] Shutdown hooks complete
[   +2 ms] exiting with code 1-->

```
```

**Comment by ANIL80531** [comment]
I hope this method works cause I don't want to run two chrome in parallel (one native and one in crostini) which hang my system.

**Comment by Hixie** [comment]
@ANIL80531 just out of interest, how much RAM does your Chrome OS device have?

**Comment by yjbanov** [comment]
Is `/usr/bin/garcon-url-handler` expected to be compatible with Chrome/Chromium binaries downloaded as Windows/Linux/macOS programs? I've never tried it.

**Comment by yjbanov** [comment]
@ANIL80531 Would you mind opening a separate feature request for Flutter to support developing web apps on ChromeOS devices? Whether we should use `/usr/bin/garcon-url-handler` or some other method to launch and manage the browser on ChromeOS would be an investigation to conduct as part of adding this feature. Right now it's too unclear if this is the right approach. We have never tried it, and we don't run any tests that would make sure that this doesn't break in the future even if it does work by accident.

**Comment by yjbanov** [comment]
Closed as this is not an existing Flutter feature. Let's open a new feature request instead.
