### ISSUE TITLE
Android Splash View Animation

### ISSUE THREAD

**Issue by JsouLiang** [flutter/flutter#97190]
This issue is related to this: https://github.com/flutter/flutter/issues/97123
I think this may be not a bug, it's look like a feature: `Allow user to set the splash transition animation time`.
I read the engine code the Splash has transition animation, and the duration is 500ms
```java
// DrawableSplashScreen.java
@Override
  public void transitionToFlutter(@NonNull Runnable onTransitionComplete) {
    if (splashView == null) {
      onTransitionComplete.run();
      return;
    }

    splashView
        .animate()
        .alpha(0.0f)
        .setDuration(crossfadeDurationInMillis)  // this is 500ms
        .setListener(
            ...);
  }
```
I think may be we can through the `meta-data` to allow user set the transition animation duration

**Comment by darshankawar** [comment]
@JsouLiang 
Let's track in the linked issue. I'll reopen it.
Closing from here.

**Comment by JsouLiang** [comment]
@darshankawar Thank you
