### ISSUE TITLE
why VsyncWaiterAndroid need call postFrameCallback on platfrom thread?

### ISSUE THREAD

**Issue by klaxxisegv** [flutter/flutter#97192]
i'm learning Flutter engine source code recently, but one thing really make me confused.

Android request vsync on platrform thread.
```
void VsyncWaiterAndroid::AwaitVSync() {
  auto* weak_this = new std::weak_ptr<VsyncWaiter>(shared_from_this());
  jlong java_baton = reinterpret_cast<jlong>(weak_this);

  task_runners_.GetPlatformTaskRunner()->PostTask([java_baton]() {
    JNIEnv* env = fml::jni::AttachCurrentThread();
    env->CallStaticVoidMethod(g_vsync_waiter_class->obj(),     //
                              g_async_wait_for_vsync_method_,  //
                              java_baton                       //
    );
  });
}
```

why not call directly `asyncWaitForVsync` like ios platform？

`Choreographer.getInstance() .postFrameCallback` support to be called on any thread.

**Comment by darshankawar** [comment]
Keeping it open and labeling it for further input from the team.

/cc @chinmaygarde

**Comment by ColdPaleLight** [comment]
We did try that on Android, https://github.com/flutter/engine/pull/29889.
But it was reverted for some reason, we will try to reland again after this issue https://github.com/flutter/flutter/issues/94371 fixed.
