### ISSUE TITLE
VS Code: Refactor does not appear on editor context menu

### ISSUE THREAD

**Issue by andim27** [flutter/flutter#97201]
## Steps to Reproduce

1. VS Code ver 1.63
2. Flutter (Channel stable, 2.8.1, on Linux Mint 20.3 5.4.0-96-generic, locale en_US.UTF-8)
3. flutter doctor - all is ok

## Logs

<details>
<summary> Refactor does not appear on editor context menu.No refactor menu if press ctl+. OR ctl+space OR mouse right click on widget</summary>

```
```

```
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @andim27, can you share a screen recording that shows the issue you're experiencing?

**Comment by andim27** [comment]
> Hi @andim27, can you share a screen recording that shows the issue you're experiencing?

 I can mention what if I open project this menu appears from ~15 min of working.And  I saw it happens when gradle doing many tasks in background
![vs_code_no_error](https://user-images.githubusercontent.com/4599713/151014381-df7f2c92-ccae-4cf7-9224-e132d7004955.png)
![vs_code_refactoring_error](https://user-images.githubusercontent.com/4599713/151014395-408bafed-2477-46ce-85ef-052ee734f313.png)

**Comment by danagbemava-nc** [comment]
I'm not entirely sure that the flutter plugin for vscode has any control over that context menu you're seeing. 
Regardless, the vscode plugin lives in its own repo over [here](https://github.com/Dart-Code/Dart-Code/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc). 

Kindly file this issue there so it may be properly addressed. 

Closing from here. 

Thank you
