### ISSUE TITLE
NumberFormat.currency(locale: 'eu_EU', symbol: '€');  to double converter

### ISSUE THREAD

**Issue by Patrick386** [flutter/flutter#97207]
I want to convert NumberFormat form to double.
ex: 25,000.25 € --> 25000.25 (double)

`NumberFormat.currency(locale: 'eu_EU', symbol: '€'); `

I want to display amount including currency symbol in textfield and get double value on enter.
Many people want to input various currencies in textfield, and many issues arise.
You should provide a clear function for this part.

**Comment by danagbemava-nc** [comment]
Hi @Patrick386, the `NumberFormat` class is a part of the `intl` package which has its dedicated repo [here](https://github.com/dart-lang/intl/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc). I would advise you file this issue over there. 

Closing as the `NumberFormat` class exists outside of flutter. 

If you disagree, kindly leave a comment below and I will reopen. 

Thank you
