### ISSUE TITLE
Launching lib/main.dart on Linux in debug mode... lib/main.dart:1 CMake Error

### ISSUE THREAD

**Issue by Saleque474** [flutter/flutter#97216]
CMake Error at /usr/share/cmake-3.16/Modules/CMakeTestCXXCompiler.cmake:53 (message):
  The C++ compiler

    "/usr/bin/clang++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/sasaj/Desktop/Programming/Running_Project/folder7/babu_e/build/linux/x64/debug/CMakeFiles/CMakeTmp

    Run Build Command(s):/usr/bin/ninja cmTC_320a1 && [1/2] Building CXX object CMakeFiles/cmTC_320a1.dir/testCXXCompiler.cxx.o
    [2/2] Linking CXX executable cmTC_320a1
    FAILED: cmTC_320a1 
    : && /usr/bin/clang++    -L/snap/flutter/current/usr/lib/gcc/x86_64-linux-gnu/8 -L/snap/flutter/current/usr/lib/x86_64-linux-gnu -lblkid -lgcrypt -llzma -lpthread -ldl -L/snap/flutter/current/usr/lib/ CMakeFiles/cmTC_320a1.dir/testCXXCompiler.cxx.o  -o cmTC_320a1   && :
    /usr/bin/ld: cannot find -lgcrypt
    /usr/bin/ld: cannot find -llzma
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    ninja: build stopped: subcommand failed.

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)

**Comment by Saleque474** [comment]
Note that: I have "llzma" and "lgcrypt" installed in "/usr/lib"  but it is finding the library in "lib/bin" . why?

**Comment by Saleque474** [comment]
I deleted my flutter SDK and reinstalled it. then it fixed my problem.

**Comment by maheshmnj** [comment]
> I deleted my flutter SDK and reinstalled it. then it fixed my problem.

Thanks for the update, provided your last message I feel its safe to close the issue. if you encounter any issues in the future feel free to file a new issue.
