### ISSUE TITLE
Webview changed the default font for a very small size

### ISSUE THREAD

**Issue by paulobreim** [flutter/flutter#97217]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by stuartmorgan** [comment]
If you have a bug to report, please file a new issue and fill out the template. The information requested there is necessary for an issue to be actionable.
