### ISSUE TITLE
Could not build the application for the simulator. Error launching application on iPhone 13.

### ISSUE THREAD

**Issue by andesappal** [flutter/flutter#97226]
## Steps to Reproduce

1. Initiate iOS simulator (iPhone 13, iOS 15.2 in this case), select it on Android Studio, then execute `flutter run` on the code sample
2. On the Run tab I get
![image](https://user-images.githubusercontent.com/54340176/151031059-52c5e38c-f865-47b3-acdc-53796cf2620f.png)

**Expected results:** i expected this see the app running on the simulated iPhone, as I have even already archived the app on Xcode to send it to the App Store Connect. 

**Actual results:** I get the figure on Step 2

<details>
<summary>Code sample</summary>

```dart
```

</details>

@TahaTesser on anticipation to https://github.com/flutter/flutter/issues/86933#issuecomment-886566587, I have attached an image of my Xcode architecture, please see below on logs
<details>
  <summary>Logs</summary>

![image](https://user-images.githubusercontent.com/54340176/151030855-137106f6-f2b3-4a7b-be4c-4b1648da5738.png)

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@andesappal 
Please don't post screenshots of the error log as it we cannot copy it and verify. Provide your `flutter doctor -v` and `flutter run --verbose` log along with `ios/podfile`. The verbose log will be huge so you can put that in a text file and share it here.

**Comment by andesappal** [comment]
`flutter run --verbose`: https://gist.github.com/andesappal/0952874b044caa8f7cdbd728ea7c8549

`flutter doctor -v`: https://gist.github.com/andesappal/d91d0ab767e212468670357f4ca997f8

podfile: https://gist.github.com/andesappal/47bf60935d59ea94dfd4e95298ace8aa

@darshankawar thanks

**Comment by darshankawar** [comment]
@andesappal 
From the verbose log you shared above, it seems to be failing due to `Target file "lib/main.dart" not found.`, so you need to confirm that you are running the app from root of your project. There doesn't seem to be any other issue mentioned in it, so I am going to close that as not a flutter issue. If you disagree, write in comments and I'll reopen it.
