### ISSUE TITLE
Samsung devices in staging are failing tests consistently

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#97235]
10 devicelab linux/android tests are newly enabled on samsung devices, but both linux18 and linux19 are failing tests consistently:
https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-linux-19
https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-linux-18

<img width="1312" alt="Screen Shot 2022-01-25 at 11 09 50 AM" src="https://user-images.githubusercontent.com/54558023/151043096-e5cdda4c-28e7-4566-961a-4c1bed68a0b0.png">
.

**Comment by keyonghan** [comment]
I believe these samsung bots were initially validated running some devicelab tests. @yusuf-goog do you think you can help check what's happening on these bots?

**Comment by yusuf-goog** [comment]
Yes, I'll take a look at these setups.

**Comment by yusuf-goog** [comment]
linux-18 is showing device is missing, I'll go to the lab and poke at it.

linux-19 seems to be more interesting. The testbed seems to be up and processing tasks.

**Comment by yusuf-goog** [comment]
linux-18,19,20 are now all online.

Unplugged and replugged linux-18.

Also, set screen lock to none.

**Comment by keyonghan** [comment]
These tests failed when `_getWakefulness`. Seems these samsung devices return different values compared to motoG4.
```
[fullscreen_textfield_perf__e2e_summary] [STDERR] Task failed: Bad state: No element
[fullscreen_textfield_perf__e2e_summary] [STDERR] 
[fullscreen_textfield_perf__e2e_summary] [STDERR] Stack trace:
[fullscreen_textfield_perf__e2e_summary] [STDERR] dart:core                                                  Iterable.single
[fullscreen_textfield_perf__e2e_summary] [STDERR] package:flutter_devicelab/framework/devices.dart 508:71    AndroidDevice._getWakefulness
[fullscreen_textfield_perf__e2e_summary] [STDERR] ===== asynchronous gap ===========================
[fullscreen_textfield_perf__e2e_summary] [STDERR] dart:async                                                 _asyncErrorWrapperHelper
[fullscreen_textfield_perf__e2e_summary] [STDERR] package:flutter_devicelab/framework/framework.dart         _TaskRunner._performTask.<fn>
[fullscreen_textfield_perf__e2e_summary] [STDERR] package:stack_trace                                        Chain.capture
[fullscreen_textfield_perf__e2e_summary] [STDERR] package:flutter_devicelab/framework/framework.dart 272:11  _TaskRunner._performTask
[fullscreen_textfield_perf__e2e_summary] [STDERR] package:flutter_devicelab/framework/framework.dart 167:43  _TaskRunner.run
[fullscreen_textfield_perf__e2e_summary] [STDERR] 
[fullscreen_textfield_perf__e2e_summary] [STDERR] Task failed: Bad state: No element
```
