### ISSUE TITLE
Infra test flake: simple build appbundle mismatched golden no-validate-deferred-components 

### ISSUE THREAD

**Issue by justinmc** [flutter/flutter#97246]
The test `simple build appbundle mismatched golden no-validate-deferred-components` appears to have failed flakily [here](https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20tool_integration_tests_2_6/64/overview).

**Comment by godofredoc** [comment]
\cc @Piinks can you please take a look?

**Comment by Piinks** [comment]
This is not a golden file image test from what I can tell, it is using the term golden to refer to file generation from call to build. I am not familiar with it and it is not a test from https://flutter-gold.skia.org/

**Comment by Piinks** [comment]
Looking at the history, it appears to be a tool test based on the change that added it

**Comment by godofredoc** [comment]
Thanks for checking! @christopherfujino anything from the failure that looks familiar?

**Comment by keyonghan** [comment]
This is a dup of https://github.com/flutter/flutter/issues/101609.
