### ISSUE TITLE
StreamBuilder ConnectionState Always remain in waiting state when Stream is empty or has no events?

### ISSUE THREAD

**Issue by parteekpassi** [flutter/flutter#97241]
When using streams and it has no events (No data Available in database table), then Streambuilder connectionState always remains in waiting state.

It seems like that this is how flutter stream is designed, it remains in waiting state while looking for an event and once an event has added (Data available in database table) it changes its connectionState to active.

In my Case: when streambuilder is looking for a stream event then it should display CircularProgressIndicator widget while in waiting state (it should be for a couple of seconds while getting data stream), but when stream is empty and there is no event to add, we want to display user an Empty Widget saying "No Records Found" instead of CircularProgressIndicator and when data found then display our custom widget.

As a user point of view, Displaying CircularProgressIndicator widget while connectionstate is in waiting state looks like it takes time to load data from database (which is a forever process), although there is No data Available in database table.

So we need a way to know when There is No Data to add on stream then instead of showing CircularProgressIndicator we can display widget saying No Data Available, instead of stuck in waiting state.

Example:

  Widget build(BuildContext context) {

          return StreamBuilder<StreamActionEvent<dynamic>>(
          stream: _stream,
          builder: ( context, AsyncSnapshot<StreamActionEvent<dynamic>> snapshot ) {
  
                      if (snapshot.hasError) {
                            return const Text('Error');
                      } else if (snapshot.connectionState == ConnectionState.waiting) { // I am getting stuck here when there is no data
                           return Center(
                                 child: CircularProgressIndicator(),
                            );
                      } else if (snapshot.connectionState == ConnectionState.active) {
                                 ItemsList.add(snapshot.data);
                                
                                if(ItemsList.isEmpty)
                                          return Text('No Data Found');
                               else
                                           return ListView.builder...;
                      }
   });

**Comment by danagbemava-nc** [comment]
Hi @parteekpassi, thanks for filing the issue. 

Please provide the output of `flutter doctor -v` and `flutter run -v` that shows the behavior you're experiencing. Please provide a complete minimal reproducible code sample without any third-party libraries. 

Thank you
