### ISSUE TITLE
Linux Fuchsia SDK roll is failing

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#97255]
The first failed roll attempt was here https://github.com/flutter/engine/pull/31043.

It looks like the flags of the `pm` tool have changed?
```
python3 ../../build/gn_run_binary.py ../../fuchsia/sdk/linux/tools/x64/pm -o gen/flutter/shell/platform/fuchsia/flutter/integration_flutter_tests/embedder/child-view2/child-view2 -m gen/flutter/shell/platform/fuchsia/flutter/integration_flutter_tests/embedder/child-view2/child-view2/child-view2.manifest -n child-view2 -version 0 build -output-package-manifest gen/flutter/shell/platform/fuchsia/flutter/integration_flutter_tests/embedder/child-view2/child-view2/package_manifest.json -depfile
flag provided but not defined: -version
Usage: pm [-k key] [-m manifest] [-o output dir] [-t tempdir] <command> [-help]
```

/cc @arbreng

**Comment by chaselatta** [comment]
This is my mistake, I missed this flag when checking for usages. Removing it here and will turn the rollers back on when it lands https://github.com/flutter/engine/pull/31069

**Comment by chaselatta** [comment]
reenabling the rollers since the fix landed.

**Comment by chaselatta** [comment]
The roll is still failing due to another reason now. I paused the rollers and am reopening this issue.

**Comment by chaselatta** [comment]
The roller is successfully rolling again.
