### ISSUE TITLE
ITMS-90338: Non-public API usage - Macbook Air 2020 M1

### ISSUE THREAD

**Issue by javierpr0** [flutter/flutter#97250]
I have submitted my application more than 7 times to the appstore via XCode Archive but they reject it with the following message:

`ITMS-90338: Non-public API usage - The app references non-public symbols in Frameworks/Flutter.framework/Flutter: _IOIteratorNext, _IOObjectRelease, _IORegistryEntryCreateCFProperties, _IORegistryEntryGetChildIterator, _IOServiceGetMatchingServices, _IOServiceNameMatching, _kIOMasterPortDefault, _ptrace. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/`

I have already tried the following steps:

- `flutter clean`
- removing Flutter.framework with `rm -r`
- `flutter build ios --release`

But I still have the same problem

`flutter doctor -v` shows this:

```
[✓] Flutter (Channel stable, 1.22.6, on macOS 12.1 21C52 darwin-arm, locale
    es-419)
    • Flutter version 1.22.6 at /Applications/flutter
    • Framework revision 9b2d32b605 (1 year ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/eduardeveloper/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    ✗ Cannot execute /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java to determine the
      version

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.2.1, Build version 13C100
    • CocoaPods version 1.11.2

[!] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin installed
    • Dart plugin installed

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

 
[!] Connected device                          
    ! No devices available

! Doctor found issues in 3 categories.
```
I have done a lot of research and in all the solutions I have found the `flutter buid ios --release`, but it hasn't helped me. Has anyone had a similar problem or know how to solve this specific problem?

**Comment by darshankawar** [comment]
@javierpr0 
This was [fixed](https://github.com/flutter/flutter/issues/37850) already. You are on very old version of Flutter, you'll need to upgrade to latest to see the fix.
Closing this as a duplicate.
