### ISSUE TITLE
Use generic flutter/infra builders for release infrastructure

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#97265]
Even though the release branches have their own copy of the .ci.yaml if a builder configuration is renamed/removed it impacts release branches presubmit because the builds enumerated in the release branch .ci.yaml file does not exist anymore.

**Comment by godofredoc** [comment]
\cc @itsjustkevin @CaseyHillers

**Comment by CaseyHillers** [comment]
Once https://github.com/flutter/flutter/issues/95037 is implemented, we can move this to a bootstrap builder in LUCI. That would allow for the targets to run in presubmit for release branches.

**Comment by CaseyHillers** [comment]
I created https://github.com/CaseyHillers/cocoon/commit/aad6569f7338a06e959191bf6e6f430081d280cf to port the initial models over. LUCI hasn't enabled the RPC yet for Cocoon to use, so this is still blocked.

**Comment by godofredoc** [comment]
Obsolete with the migration to dart-internal.
