### ISSUE TITLE
[path_provider] run release mode failed in iOS project 

### ISSUE THREAD

**Issue by dujj** [flutter/flutter#97279]
use flutter like https://docs.flutter.dev/development/add-to-app/ios/project-setup with Option A - Embed with CocoaPods and the Flutter SDK

setup:
1. new a iOS project FlutterHost
2. cd FlutterHost
3. flutter create --org='com.flutter.host.module' --template='module' module
4. cd module
5. flutter pub add path_provider
6. cd ..
7. pod init
8. modfy podfile like: A
9. pod install
10. open FlutterHost.xcworkspace run in debug mode on device success
11. change debug to release failed and log:
```
2022-01-26 14:32:50.847951+0800 FlutterHost[8767:4538391] Metal API Validation Enabled
2022-01-26 14:32:51.028210+0800 FlutterHost[8767:4538642] [VERBOSE-2:shell.cc(94)] Dart Unhandled Exception: NoSuchMethodError: No top-level getter 'testMyApp' declared.
Receiver: top-level
Tried calling: testMyApp, stack trace: #0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:218)
2022-01-26 14:32:51.028437+0800 FlutterHost[8767:4538642] [VERBOSE-2:dart_isolate.cc(718)] Could not resolve main entrypoint function.
2022-01-26 14:32:51.028495+0800 FlutterHost[8767:4538642] [VERBOSE-2:dart_isolate.cc(202)] Could not run the run main Dart entrypoint.
2022-01-26 14:32:51.028818+0800 FlutterHost[8767:4538642] [VERBOSE-2:runtime_controller.cc(384)] Could not create root isolate.
2022-01-26 14:32:51.028912+0800 FlutterHost[8767:4538642] [VERBOSE-2:shell.cc(574)] Could not launch engine with configuration.

```
12. set path_provider to 1.0.0 run in release mode success

[Demo](https://github.com/dujj/FlutterHost)
I found generated_main.dart in .dart_tool, other vm:entry-point like :
@pragma('vm:entry-point')
void testMyApp() => runApp(const MyApp());
lost...

flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.0.1 21A559 darwin-x64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.63.2)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by darshankawar** [comment]
@dujj 
I cloned the demo and ran `pod init` and then `pod install` but getting below error:

```
dhs@Dhss-MacBook-Pro FlutterHost % pod install

[!] Invalid `Podfile` file: cannot load such file -- ./module/.ios/Flutter/podhelper.rb.

 #  from /Users/dhs/Documents/NCFlutter/FlutterHost/Podfile:5
 #  -------------------------------------------
 #  flutter_application_path = './module'
 >  load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
 #  
 #  -------------------------------------------
dhs@Dhss-MacBook-Pro FlutterHost % 
```

**Comment by dujj** [comment]
@darshankawar  
1.cd module 
2. flutter pub get
3.pod install
flutter pub get will create .ios

**Comment by darshankawar** [comment]
@dujj 
Thanks, I was missing `flutter pub get` earlier. But running above command and then from root of `FlutterHost`, ran `open FlutterHost.xcworkspace` gives me `files cannot be opened` in Xcode.

**Comment by dujj** [comment]
@darshankawar 
My colleague followed these steps successfully:
1. git clone FlutterHost
2. cd FlutterHost
3. cd module
4. flutter pub get
5.cd ..
6. pod install
7. open FlutterHost.xcworkspace

My xcode version : Version 13.2.1 (13C100)

**Comment by darshankawar** [comment]
> you mean you can't see the files under module.

Yes. I get below when running `open FlutterHost.xcworkspace`:

<img width="932" alt="Screenshot 2022-01-27 at 11 51 57 AM" src="https://user-images.githubusercontent.com/67046386/151303446-2aa13314-469c-4dbd-a52b-6e4835582108.png">

I don't use vscode. Is there any other way to make it run ?

**Comment by dujj** [comment]
Due to the lack of understanding of the environment for development, I can't understand why it can't be opened, but the example is very simple, you can follow the steps below:
1. Use Xcode to create a new iOS App project FlutterHost
2. In the FlutterHost directory, use Flutter create module like this:
flutter create --org='com.flutter.host.module' --template='module' module
3. cd module execute command: flutter pub add path_provider and flutter pub get
4. cd .. to the FlutterHost directory
5. pod init
6. pod install
7. open FlutterHost.xcworkspace with Xcode
8. Use FlutterHost/ViewController.swift and module/lib/main.dart in demo to replace

**Comment by darshankawar** [comment]
@dujj 
Thanks for the details. I looked again at the error log you shared originally and it seems to be same as https://github.com/flutter/flutter/issues/91841, so the issue doesn't seem to be specific to `path_provider`, but using add2app. So I suggest you to follow-up in it for further updates.
Closing this as a duplicate.
