### ISSUE TITLE
Facing issue while installing flutterfire_cli on Windows

### ISSUE THREAD

**Issue by preet18** [flutter/flutter#97277]
C:\>dart pub global activate flutterfire_cli
Resolving dependencies...
The current Dart SDK version is 2.14.0-377.7.beta.

Because every version of flutterfire_cli depends on xml >=5.3.0 which requires SDK version >=2.14.0 <3.0.0, flutterfire_cli is forbidden.
So, because pub global activate depends on flutterfire_cli any, version solving failed.

**Comment by thunderstorm010** [comment]
Try `flutter upgrade` as there is a new version?

**Comment by darshankawar** [comment]
@thunderstorm010 
`flutterfire_cli` issues need to be reported in dedicated repo: https://github.com/invertase/flutterfire_cli/issues
Closing from here.
