### ISSUE TITLE
why is MyApp needed, using it vs directly running runApp(MaterialApp(home: ...

### ISSUE THREAD

**Issue by gitman-2021** [flutter/flutter#97274]
May i ask what is the difference between the following pieces of code:

```
void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: const MyHomePage(),
    );
  }
}
```
vs
```
void main() {
  runApp(
    const MaterialApp(
      home: MyHomePage(),
    ),
  );
}
```
Thanking you...

**Comment by mkay-42069** [comment]
You could do that, but not viable if you have a growing project. But most people put for example providers, bloc, localization etc. inside of runApp, that’s why MyApp exists. It’s just cleaner.

**Comment by danagbemava-nc** [comment]
Hi @gitman-2021, kindly see https://stackoverflow.com/questions/51312843/what-is-the-difference-between-runappnew-myapp-and-runappnew-materialapp.

For future reference, kindly ask these types of questions on `StackOverflow` or any of the communities https://flutter.dev/community#community-grid. 

The flutter issue tracker for feature requests and bug reports. 

Closing as this is neither a bug report nor feature request. 

Thank you
