### ISSUE TITLE
flutter scroll_aware_image_provider opt

### ISSUE THREAD

**Issue by denghewenai** [flutter/flutter#97288]
## Use case

Flutter optimizes the image loading in fast sliding. If it is in the process of fast sliding, the loading will be delayed here. I have such an optimization project here, which needs to load hundreds of pictures through the network. If you quickly slide to the bottom, the result of the optimization at this time is that you still need to wait for the previous pictures to be loaded before loading the latter pictures. At this time, the load time is blocked on the network request. If the scroll_aware_image_provider is modified here, the fast sliding delay is loaded, and then delayed for 1s, the effect of quickly displaying the bottom image when sliding to the bottom can be achieved. But this approach is not elegant, is there a better solution for optimization?

## Proposal
![A22E5634-6559-4C4A-A64E-6879194E99AC](https://user-images.githubusercontent.com/13479936/151153182-53adfdfe-3c42-476d-a673-f6847b6301fc.png)

**Comment by darshankawar** [comment]
@denghewenai 
Can you provide `flutter doctor -v` and a minimal reproducible code sample that shows the current behavior you are facing ? along with your proposed change ?

**Comment by denghewenai** [comment]
./flutter doctor -v
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.0.1 21A559 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 2.8.1 at /Users/denghewen/fvm/versions/2.8.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (6 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1
    • Pub download mirror https://flutter.alibaba-inc.com
    • Flutter download mirror http://aliuc-flutter-storage.alibaba.net/uc

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/denghewen/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Unknown CocoaPods version installed.
        Flutter is unable to determine the installed CocoaPods's version.
        Ensure that the output of 'pod --version' contains only digits and . to
        be recognized by Flutter.
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Connected device (3 available)
    • PEYM00 (mobile) • HY8XVOJJ8DX44TB6 • android-arm64  • Android 11 (API 30)
    • macOS (desktop) • macos            • darwin-x64     • macOS 12.0.1 21A559
      darwin-x64
    • Chrome (web)    • chrome           • web-javascript • Google Chrome
      97.0.4692.99

**Comment by darshankawar** [comment]
> If it is in the process of fast sliding, the loading will be delayed here. I have such an optimization project here, which needs to load hundreds of pictures through the network. If you quickly slide to the bottom, the result of the optimization at this time is that you still need to wait for the previous pictures to be loaded before loading the latter pictures. At this time, the load time is blocked on the network request.

Would also need a self contained minimal code sample showcasing the current behavior.
Thanks.
