### ISSUE TITLE
Feature request: onFocus and onBlur support

### ISSUE THREAD

**Issue by paolosoares** [flutter/flutter#9728]
The project:mulligan spec has a set of input widgets that do server-side input validation when a widget loses focus, but Flutter has no specific hooks for such event.

There might be a workaround using a StatefulWidget and keeping track of the last know focus state, but that would be a bit too hacky and would need to be repeated every time one wants to react to these events.

**Comment by paolosoares** [comment]
@cbracken @tvolkert

**Comment by Hixie** [comment]
Can you clarify what you mean by "loses focus"? In particular, does this include dismissing the IME keyboard (but keeping keyboard physical focus), does it include popping up a dialog on top (but keeping focus for when the dialog returns), or other such cases?

**Comment by paolosoares** [comment]
"Loses focus", in this case, wouldn't include dismissing the IME keyboard. It woul be caused by either:

1. While editing a form input, pressing "next/done" on the Android keyboard, which would either move focus to the next input or submit the form;
2. Tapping on another UI element that would request.

In our case, we just do show an error label on top of the input. No dialogs.

**Comment by abarth** [comment]
It sounds like you already know that you can listen to the FocusNode.  You're just looking to remove the overhead of remembering the old "is focused" level to generate the "lost focus" edge.

**Comment by paolosoares** [comment]
Yes. I believe that this "onFocus" and "onBlur" is a common enough idiom, on par with "onTap", for example, so it shouldn't be something that would only be possible with some state/object listener juggling act.

**Comment by abarth** [comment]
Makes sense.

**Comment by dspoonia7** [comment]
Hey Guys, any updates on this? @zoechi

**Comment by hyiso** [comment]
Hey, any progress on this ?

**Comment by YeungKC** [comment]
Now you can use 

```dart
Focus(
  onFocusChanged: (value) {
    ...
  },
  child: Builder(BuildContext context) => TextField(focusNode: Focus.of(context)),
);
```


I believe it also solves the issue.
And because of the discussion at https://github.com/flutter/flutter/pull/69323, I recommend closing this issue.

cc @justinmc @Hixie

**Comment by justinmc** [comment]
That makes sense to me, I'll go ahead and close this unless anyone objects.  I also wasn't aware of the Focus widget before.

**Comment by sbaz44** [comment]
> Now you can use
> 
> ```dart
> Focus(
>   onFocusChanged: (value) {
>     ...
>   },
>   child: Builder(BuildContext context) => TextField(focusNode: Focus.of(context)),
> );
> ```
> 
> I believe it also solves the issue.
> And because of the discussion at #69323, I recommend close this issue.
> 
> cc @justinmc @Hixie

this wont work if you want to validate whether the textfield is empty. By default the textfeild will empty(Example: while registering). As soon as I tap on any textfield it will throw the error that THIS FIELD CANNOT BE EMPTY. This is wrong. validation should occur if I tap on the textfield and leave it empty and go for the second field to fill.

onFocusChanged runs wheneven we focus on the textfield.

Correct me If I am wrong.

**Comment by justinmc** [comment]
@sbaz44 Have you tried using [AutovalidateMode](https://master-api.flutter.dev/flutter/widgets/FormField/autovalidateMode.html)?  If that doesn't solve the problem, could you open a full new issue for this and tag me?
