### ISSUE TITLE
[flutter_lints]Document use of analysis_options.yaml in a a local package included in a flutter project

### ISSUE THREAD

**Issue by viniciusps01** [flutter/flutter#97285]
I did create an inner package which includes an pubspec.yaml file. Since then 
my analysis_options.yaml has an error:
```The include file package:flutter_lints/flutter.yaml in project_name/analysis_options.yaml cannot be found```

After searching for a solution I've discovered how to solve the issue. Unfortunely I'm not sure
what cause this. 

To solve this the only thing we need to is to add a analysis_options.yaml (can be empty) to our innner package.

Running `flutter doctor -v` I have:
```
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [versÃ£o 10.0.19044.1466], locale pt-BR)
    • Flutter version 2.8.1 at C:\Users\Vinicius\Documents\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (6 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\Vinicius\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.63.2)
    • VS Code at C:\Users\Vinicius\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.32.0

[√] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 7.0 (API 24) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 97.0.4692.99
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 97.0.1072.62

• No issues found!
```

## Steps to Reproduce

1. Create a inner project without a analysis_options.yaml file

project folder structure
```--lib
--packages
----my_pack
------lib
------pubspec.yaml
--pubspec.yaml
--analysis_options.yaml
```

2. Then you should be able to see the error message in you analysis_options.yaml file

3. Now add a analysis_options.yaml file to your inner project 

project folder structure
```--lib
--packages
----my_pack
------lib
------pubspec.yaml
------analysis_options.yaml
--pubspec.yaml
--analysis_options.yaml
```

4. Now the error is gone

**Comment by maheshmnj** [comment]
Hi @viniciusps01, Thanks for filing the issue. I believe this is working as intended, when you have a nested package you need to have a separate analysis options YAML file, Could you please describe what's your proposal regarding this behavior?

**Comment by viniciusps01** [comment]
There isn't other proposal. I just think should have some comprehensive log message addressing this. 
Since this can be a little bit trick to solve without wasting some time looking around in the internet
and doing some try and fail.

**Comment by maheshmnj** [comment]
> There isn't other proposal. I just think should have some comprehensive log message addressing this.
Since this can be a little bit trick to solve without wasting some time looking around in the internet
and doing some try and fail.

Thanks for the clarification. This looks more like a documentation issue.
