### ISSUE TITLE
New flutter/packages autoroller seemingly blocked on review

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#97296]
I'm switching flutter/packages over to an autorolled, pinned version of Flutter instead of "whatever is currently on `master`", but the new autoroller doesn't appear to be able to land PRs. Here's it's first roll:
https://github.com/flutter/packages/pull/557
It's passed all tests and has the `waiting for tree to go green` label, but is just sitting there. The GitHub UI shows:
```
Merging is blocked
Merging can be performed automatically with 1 approving review.
```

which I don't see on, e.g., engine->flutter rolls. Do we need special permissions set up in the repo for this?

/cc @godofredoc

**Comment by godofredoc** [comment]
Permissions have been fixed!
