### ISSUE TITLE
Camera Plugin Stop Background Thread

### ISSUE THREAD

**Issue by migol06** [flutter/flutter#97290]
I experience a run time error and recorded ANR in firebase crashlytics for Camera Plugin. 

```
Here's the error. Camera Plugin highlighted to the first line stopBackgroundThread(Camera.java) 
io.flutter.plugins.camera.Camera.stopBackgroundThread (Camera.java)
io.flutter.plugins.camera.Camera.close (Camera.java)
io.flutter.plugins.camera.MethodCallHandlerImpl.onMethodCall (MethodCallHandlerImpl.java)
io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage (MethodChannel.java)
io.flutter.embedding.engine.dart.DartMessenger.invokeHandler (DartMessenger.java)
io.flutter.embedding.engine.dart.DartMessenger.lambda$handleMessageFromDart$0 (DartMessenger.java)
io.flutter.embedding.engine.dart.DartMessenger.lambda$handleMessageFromDart$0$DartMessenger (DartMessenger.java)
io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$6ZD1MYkhaLxyPjtoFDxe45u43DI.run (-.java) 

```
However, if I restarted the application the camera works

**Comment by darshankawar** [comment]
@migol06 
Can you provide camera plugin version on which you are seeing this error along with your `flutter doctor -v`?
Are you able to replicate it locally ? If so, can you provide a minimal reproducible code sample that will possibly show this error along with exact steps to replicate ?

**Comment by migol06** [comment]
Hi @darshankawar, the camera plugin version is  camera: ^0.9.4+5. 

Here's the flutter doctor result.
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19043.1466], locale en-US)
    • Flutter version 2.8.1 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (6 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Miguel\AppData\Local\Android\sdk
    • Platform android-31, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.2.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.63.2)
    • VS Code at C:\Users\Miguel\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 97.0.4692.99
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 96.0.1054.53

• No issues found!

And I follow the documentation of camera plugin in pub.dev

Here's the code
-Main Method
List<CameraDescription>? cameras;

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  cameras = await availableCameras();
  await Firebase.initializeApp();
  FlutterError.onError = FirebaseCrashlytics.instance.recordFlutterError;
  FirebaseCrashlytics.instance.setCrashlyticsCollectionEnabled(true);
  runApp(const MyApp());
}

Camera
CameraController? controller;

@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: ESAppBar(
        onTap: () {
          showAboutDialog(
              context: context,
              applicationName: 'Live Camera',
              applicationIcon: Image.asset(
                'assets/images/eyessistant.png',
                scale: 5,
              ),
              children: [const ESText('Lorem Ipsum Dolor')]);
        },
      ),
      body: Stack(children: [
        Center(child: CameraPreview(controller!)),
        ESText(detectedImage)
      ]),
    );
  }
}

Also, Firebase crashlytics records this error on Android 11. Other Versions of android was working fine

**Comment by darshankawar** [comment]
@migol06
What does `ESAppBar` and `ESText` represent ? It looks like custom code.
Can you try the camera plugin [example](https://github.com/flutter/plugins/tree/main/packages/camera/camera/example) on same device and see if you still get same behavior ?

**Comment by migol06** [comment]
It is a custom widget @darshankawar. Okay, I will update you if there's an error thrown. Thanks

**Comment by Wian-TMC** [comment]
I get the exact same error and behaviour using ```camera: ^0.9.4+6```. When using the camera preview, and a push notification comes through, it causes an App Not Responding (ANR).

```
io.flutter.plugins.camera.Camera.stopBackgroundThread (Camera.java)
io.flutter.plugins.camera.Camera.close (Camera.java)
io.flutter.plugins.camera.MethodCallHandlerImpl.onMethodCall (MethodCallHandlerImpl.java)
io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage (MethodChannel.java)
io.flutter.embedding.engine.dart.DartMessenger.invokeHandler (DartMessenger.java)
io.flutter.embedding.engine.dart.DartMessenger.lambda$handleMessageFromDart$0 (DartMessenger.java)
io.flutter.embedding.engine.dart.DartMessenger.lambda$handleMessageFromDart$0$DartMessenger (DartMessenger.java)
io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$6ZD1MYkhaLxyPjtoFDxe45u43DI.run (-.java)
```

Flutter doctor:
```
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6.2 20G314 darwin-x64, locale en-ZA)
    • Flutter version 2.8.1 at /Users/wiansnyman/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (7 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/wiansnyman/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/wiansnyman/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 97.0.4692.99

• No issues found!
```
