### ISSUE TITLE
Make flutter app buildable for both aar and apk with single project.

### ISSUE THREAD

**Issue by wangmir** [flutter/flutter#97293]
## Use case

I'm currently developing application with flutter, and my application should be embedded to the other android native application because of business reason. 

But in this case, there are two difficulties.

1. I cannot build my application independently.
2. My application cannot be debugged in the same way as usual flutter application.

## Proposal

How about enable aar build using normal flutter project? I realized that there are not much different, so it can be possible (some point I failed, but official support can be helpful).

**Comment by darshankawar** [comment]
> How about enable aar build using normal flutter project?

@wangmir `flutter build aar` is specifically used when flutter module is integrated with native Android. You can read more about aar in this article https://docs.flutter.dev/development/add-to-app/android/project-setup,

So I am not sure if the same command will be applicable or feasible for a normal Flutter project, so I am going ahead and closing this. If you disagree, write in comments and I'll reopen it.

**Comment by wangmir** [comment]
When we make aar with `flutter build aar`, it cannot be debugged using usual flutter debugging feature, thus this flutter aar feature should be launched as independent flutter application too to ease debugging too. 

So, I think if there are available method to build both aar and apk using same project with same dependency and same lib directory, I think it worth..
