### ISSUE TITLE
dart file doesnt work

### ISSUE THREAD

**Issue by fofam3** [flutter/flutter#97297]
hello i am a in flutter and Dart file doesnt work in vscode
![image](https://user-images.githubusercontent.com/45842651/151204412-5bb7b5c9-8e0f-4b00-9a40-83d2d28f1670.png)

**Comment by maheshmnj** [comment]
Hi @fofam3, Thanks for filing the issue. Can you please elaborate on the issue, What doesn't work? Also can you share the output of `flutter doctor -v`?
