### ISSUE TITLE
When I rotate screen with drawer open and my finger keep touch drawer , some problem happen

### ISSUE THREAD

**Issue by tain335** [flutter/flutter#973]
![screenshot_2015-12-17-09-45-02](https://cloud.githubusercontent.com/assets/5304597/11859134/3d73d7c0-a4a3-11e5-9c2c-b29f2d669d62.png)

**Comment by Hixie** [comment]
@eseidelGoogle Please to verify.

**Comment by HansMuller** [comment]
This is no longer a reproduceable bug.
