### ISSUE TITLE
[flutter_releases] release branch names do not align with release versions

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#97309]
For example, 2.10.x release branch is named `flutter-2.8-candidate.16` https://github.com/flutter/flutter/pull/97259.

The root cause is that we failed to notify the internal google roll team to increment the y while creating the first roll after an initial open source beta release.

To fix we will likely need to manually create the correct branch for an internal roll (the roll script does not support creating an arbitrary branch name).

cc @itsjustkevin @godofredoc

**Comment by CaseyHillers** [comment]
Marking as fixed.

Me and Kevin have been keeping this in sync since the release team now owns the internal releases as well.
