### ISSUE TITLE
Disallow `flutter run`-ing on 32-bit development devices

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#97329]
Following the 2.10 stable cycle, Flutter will no longer build for 32-bit iOS devices. See the RFC at [flutter.dev/go/rfc-32-bit-ios-unsupported](http://flutter.dev/go/rfc-32-bit-ios-unsupported).

Mark 32-bit devices as unsupported targets for `flutter commands`, and fail if they are targeted
```
$ flutter devices
3 connected devices:

iPhone 4s (mobile) • 1754b457ae0324670be2493c147bf08bdad86907 • ios            • iOS 9.3.6 13G37 (unsupported)
macOS (desktop)    • macos                                    • darwin-x64     • macOS 12.1 21C52 darwin-x64
Chrome (web)       • chrome                                   • web-javascript • Google Chrome 97.0.4692.99
```

https://github.com/flutter/flutter/blob/9e88fe328efcf42d3037a965b39269f0805cd4ce/packages/flutter_tools/lib/src/ios/devices.dart#L306
should become:
```dart
  bool isSupported() => cpuArchitecture == DarwinArch.arm64;
```

**Comment by jmagman** [comment]
Blocked by https://github.com/flutter/flutter/issues/97148

**Comment by zanderso** [comment]
To clarify, after the 2.10 stable cycle, we can stop *testing* on 32-bit iOS on Flutter's CI. However, it's only after the branch cut for the Q2 stable (probably 2.13) that we'll be able to remove support completely.
