### ISSUE TITLE
Linux web_tests flakes on `Connection refused+timeout`

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#97324]
part of [#97036](https://github.com/flutter/flutter/issues/97036))
These data is based on Q4 2021 flakes that happened from 10/01/2021 to 01/13/2022

1 flake on `Linux web_tests_1`: [3181](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_tests_1/3181/overview) (happened on 12/26/2021)
1 flake on `Linux web_tests_6`: [3113](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_tests_6/3113/overview) (happened on 12/17/2021)

```
00:03 +9: test/widgets/constrained_box_test.dart: ConstrainedBox intrinsics - infinite                                                                                                                 [+3168 ms] Serving tests at http://localhost:39033/static/index.html?managerUrl=ws%3A%2F%2Flocalhost%3A39033%2F1&debug=false
[  +37 ms] Using Chromium 84.0.4147.0 

[  +89 ms] [CHROME]: Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
[   +2 ms] [CHROME]: 
[        ] [CHROME]: DevTools listening on ws://127.0.0.1:37219/devtools/browser/b8d6b95a-1916-4d8b-bb27-347b04bdc46f

00:04 +9: test/widgets/constrained_box_test.dart: ConstrainedBox intrinsics - infinite                                                                                                                 
[+2004 ms] SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = localhost, port = 36118
           #0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:682:35)
           #1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1817:26)
           #2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27:23)
           #3      Socket._startConnect (dart:io-patch/socket_patch.dart:2038:22)
           #4      Socket.startConnect (dart:io/socket.dart:792:21)
           #5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2439:18)
           #6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2808:12)
           #7      _HttpClient._getConnection (dart:_http/http_impl.dart:2813:12)
           #8      _HttpClient._openUrl (dart:_http/http_impl.dart:2697:12)
           #9      _HttpClient.getUrl (dart:_http/http_impl.dart:2574:48)
           #10     ChromeConnection.getUrl (package:webkit_inspection_protocol/webkit_inspection_protocol.dart:75:33)
           #11     ChromeConnection.getTabs (package:webkit_inspection_protocol/webkit_inspection_protocol.dart:41:26)
           #12     ChromeConnection.getTab (package:webkit_inspection_protocol/webkit_inspection_protocol.dart:57:31)
           <asynchronous suspension>
           #13     ChromiumLauncher._connect (package:flutter_tools/src/web/chrome.dart:401:9)
           <asynchronous suspension>
           #14     BrowserManager.start (package:flutter_tools/src/test/flutter_web_platform.dart:677:29)
           <asynchronous suspension>
           #15     FlutterWebPlatform.load (package:flutter_tools/src/test/flutter_web_platform.dart:463:25)
           <asynchronous suspension>
           #16     Loader.loadFile.<anonymous closure> (package:test_core/src/runner/loader.dart:224:25)
           <asynchronous suspension>
           #17     new LoadSuite.<anonymous closure>.<anonymous closure> (package:test_core/src/runner/load_suite.dart:97:21)
           <asynchronous suspension>

00:05 +9: test/widgets/constrained_box_test.dart: ConstrainedBox intrinsics - infinite                                                                                                                 
00:05 +9 -1: compiling /b/s/w/ir/x/w/flutter/packages/flutter/test/painting/shape_border_test.dart [E]                                                                                                 
  Failed to load "/b/s/w/ir/x/w/flutter/packages/flutter/test/painting/shape_border_test.dart":
  Unable to connect to Chrome debug port: 37219
   SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = localhost, port = 36118
  package:flutter_tools/src/base/common.dart 10:3                  throwToolExit
  package:flutter_tools/src/web/chrome.dart 406:9                  ChromiumLauncher._connect
  ===== asynchronous gap ===========================
  package:flutter_tools/src/test/flutter_web_platform.dart 677:29  BrowserManager.start
  ===== asynchronous gap ===========================
  package:flutter_tools/src/test/flutter_web_platform.dart 463:25  FlutterWebPlatform.load
  ===== asynchronous gap ===========================
  package:test_core/src/runner/loader.dart 224:25                  Loader.loadFile.<fn>
  ===== asynchronous gap ===========================
  package:test_core/src/runner/load_suite.dart 97:21               new LoadSuite.<fn>.<fn>
```

**Comment by keyonghan** [comment]
Another flake on `Linux web_tests_0`: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_tests_0/3539/overview

**Comment by yjbanov** [comment]
Checked the last 200 builds. There was one failure of this kind. Is it worth the P2 label?

**Comment by keyonghan** [comment]
> Checked the last 200 builds. There was one failure of this kind. Is it worth the P2 label?

Thanks for the question! Actually we do not currently have a clear standard how we prioritize flaky bugs (except P1 which means a percentage > 2%). Most of the shard tests have relatively low flaky percentage on each test level, but they have been contributing to ~10% commit-level flakiness as a whole.

Put the P2 here considering the flake happened twice in Dec, and it is still reproducible till now. Yeah, it is true that the percentage is low compared to other high flaky ones, but would appreciate the team to help triage on these bugs to see if this can be easily fixed or otherwise this should be skipped/removed. Considering our current SLO on commit flakiness percentage is 5%, we would like to push here a bit to either get a fix or skip the test.

On the other hand, based on historical flaky bugs in the pool, they most likely remain in the pool without being picked up or fixed, but keep affecting the tree intermittently over the time.

/cc @Hixie @godofredoc @zanderso  for any comments.

**Comment by yjbanov** [comment]
Let's look into it then.

**Comment by christopherfujino** [comment]
@yjbanov is there any update on this one?

**Comment by keyonghan** [comment]
One more flake: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_tests_3/3927/overview

**Comment by yjbanov** [comment]
Update: since this looks like an instance of Chromium crashing on us upgrading Chromium from 84 to 96 can help, which is what I'm working on now (https://github.com/flutter/flutter/pull/100073)

**Comment by yjbanov** [comment]
Chromium 96 upgrade landed 5 days ago. I haven't seen any flakes yet, but maybe I'm not looking in the right place (I just eyeballed the build history on various builders, such as https://ci.chromium.org/p/flutter/builders/prod/Linux%20web_tests_5?limit=200). I'm tempted to close this, but I'm not sure what the right process is.

**Comment by yjbanov** [comment]
With some guidance from @keyonghan, I decided to close this issue. Chromium 96 upgrade, while speculative, seems to have at least reduced the flakiness to a point that there hasn't been a flake in about a week. If new flakes show up, let's have the flake bots open a new issue.
