### ISSUE TITLE
The embedder library for android can't be built because it has a dependency on android shell and throws `ld.lld: error: undefined symbol: _binary_icudtl_dat_start` error on compile

### ISSUE THREAD

**Issue by mnovakovic** [flutter/flutter#97347]
I am trying to build the `//shell/platform/embedder:flutter_engine_library` target for Android (on Mac) but it fails in the link phase with `"ld.lld: error: undefined symbol: _binary_icudtl_dat_start"`. 

The particular line of code where this symbol is requested is in `"shell/common/switches.cc:83"`. The `"switches.cc"` belongs to `"//shell/common"` target, which `"//shell/platform/embedder:flutter_engine_library"` depends on, however the `"//shell/platform/android:icudtl_object"` target which adds the `_binary_icudtl_dat_start` symbol is only added in `"//shell/platform/android:flutter_shell_native"`.

This means that I can't produce the embedder for Android unless I add a dependency on `"//shell/platform/android:icudtl_object"` to `embedder:flutter_engine_library` or change the code in some other way. Is this a KP? I also find it a little unintuitive that the flutter engine library (embedder) depends on `"//shell/common"`, especially since https://github.com/flutter/flutter/wiki/Custom-Flutter-Engine-Embedders states that "The Flutter engine API has no platform specific dependencies, has a stable ABI and is available in its entirety in a single C header file available here."

Steps to repro on my mac:
1. `flutter/tools/gn --no-goma --target-os android --android-cpu arm64 --runtime-mode debug --embedder-for-target `
2. `ninja -C out/android_debug_arm64 flutter_engine_library`

**Comment by darshankawar** [comment]
Thanks for the report. Labeling it for further input from the team.

/cc @chinmaygarde

**Comment by chinmaygarde** [comment]
Building a standalone embedder library on Android that is separate from the existing embedder is a known issue. I suppose no has needed it so far and hence it hasn't been wired up. Even after you fix the linker error, some tinkering to make features like event loop interop work correctly needs to happen. The changes aren't particularly invasive but it does mean supporting a new target that is linux like but works on Android.

I am marking this as a new feature.

**Comment by zanderso** [comment]
@mnovakovic if you can give some more details about your use case or the high-level problem that you're trying to solve, it could help us find the right priority for this issue.
