### ISSUE TITLE
Remove 32-bit iOS builds from engine including `arm7v` slice of `Flutter.xcframework` and `gen_snapshot_armv7`

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#97342]
Following the 2.10 stable cycle, Flutter will no longer build for 32-bit iOS devices. See the RFC at [flutter.dev/go/rfc-32-bit-ios-unsupported](http://flutter.dev/go/rfc-32-bit-ios-unsupported).

Stop building the iOS `arm7v` engine artifacts, bundled in the `Flutter.xcframework`.

**Comment by jmagman** [comment]
Tool half of this fix is at https://github.com/flutter/flutter/pull/97344.  Should be included in the engine roll that removes `armv7` from the engine artifacts.

**Comment by jmagman** [comment]
Engine spots (there may be more):
https://github.com/flutter/engine/blob/2962099077b36704071802ea5595f4a016a1c214/sky/tools/create_ios_framework.py#L22
https://github.com/flutter/engine/blob/02806cc0d9b642aa6589595b97be79738ad5d577/sky/tools/create_macos_gen_snapshots.py#L21
https://github.com/flutter/engine/blob/2962099077b36704071802ea5595f4a016a1c214/lib/snapshot/BUILD.gn#L210-L215

**Comment by chinmaygarde** [comment]
So excited about this!

**Comment by jmagman** [comment]
The tool is no longer building `arm7v` as of https://github.com/flutter/flutter/issues/97328, ready for the engine side.  @zanderso is practically cackling at the desk next to me imagining deleting this code.  Assigning to him.

**Comment by jmagman** [comment]
The xcframework part was done in https://github.com/flutter/engine/pull/32664.  Once that rolls into g3 and we know we don't need to revert @zanderso can rip out the 32-bit step from the builders.

**Comment by zanderso** [comment]
This is done with https://flutter-review.googlesource.com/c/recipes/+/29582.
