### ISSUE TITLE
flutter_gallery__back_button_memory timing out after Engine roll

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#97351]
Starting with the Engine roll here https://github.com/flutter/flutter/pull/97313

flutter_gallery__back_button_memory is timing out. Here is an example.

https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android%20flutter_gallery__back_button_memory/1090/overview

It's a big Engine roll, but there are only a few non-roll commits that look like they could have affected this benchmark on Android:

@blasten for https://github.com/flutter/engine/pull/30893 and https://github.com/flutter/engine/pull/30611
@ColdPaleLight  for https://github.com/flutter/engine/pull/31045

Please test your Engine PRs with this test.

**Comment by ColdPaleLight** [comment]
@zanderso @blasten 
I investigated and found out that https://github.com/flutter/engine/pull/30893 was causing the test to fail.
/cc @GaryQian
