### ISSUE TITLE
AssetImage loading difference in web and android

### ISSUE THREAD

**Issue by Rishaba-Jain** [flutter/flutter#97377]
I was trying AssetImage on Chrome and Android emulator. For the below shown folder structure, I found that using `Image(image: AssetImage('assets.png'))` works in Chrome and not in Android Emulator.
I expect it not to be working on Chrome as well.
Using `Image(image: AssetImage('assets/assets.png'))`  works in both Chrome and Android as expected.
Kindly let me know if my expectations happen to be incorrect.

Folder Structure:
```
app
└── ....
└── lib
└── assets
        └── assets.png
```
## Steps to Reproduce
In a basic flutter program, create a folder **assets** at the same level as **lib**, and add any image inside the **assets** folder, say **assets.png**.
Load the said image using the below code:
`Image(image: AssetImage('assets.png'))`

Please run in Chrome and Android as well.
**Chrome :** 
<img src="https://user-images.githubusercontent.com/71686718/151381152-74ad419b-cbd2-4590-8424-bc317995694f.PNG" width="400"/>

**Android :**
<img src="https://user-images.githubusercontent.com/71686718/151381159-e66c3818-cb69-4a77-b30a-1b580408baa3.PNG" width="400"/>

Thanks !

**Comment by asashour** [comment]
Was ` pubspec.yaml` changed as hinted [here](https://docs.flutter.dev/development/ui/assets-and-images)?

**Comment by PrabeshPP** [comment]
hi @asashour 
Actually,without changing the pubspec.yaml chrome will show the Image but not the Android  phone.

**Comment by Rishaba-Jain** [comment]
`pubspec.yaml` is like this
```
flutter:
  uses-material-design: true
  assets:
    - assets/
```
According to the [document ](https://docs.flutter.dev/development/ui/assets-and-images)@asashour shared, the above specifications should show the image when we use
`Image(image: AssetImage('assets/assets.png'))` for the folder structure mentioned in the issue. It works in web and android.
(Note: we are mentioning the name of the folder too)

Currently `Image(image: AssetImage('assets.png'))` is loading the image in web, but not in android.

**Comment by maheshmnj** [comment]
Hi @Rishaba-Jain, This is a known inconsistency on the web, This is being tracked here https://github.com/flutter/flutter/issues/86833. Please follow up on the linked issue for further updates closing this issue as a  duplicate.
