### ISSUE TITLE
HTTP requests fails after upgrading to `2.10.0`

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#97387]
It seems that **only in release mode** (also in **profile mode**), the same HTTP requests (through the `http` package) start to fail.

## Bug details

The details of which call fails can be found in https://github.com/dart-lang/http/issues/662.

It seems that in:

https://github.com/dart-lang/http/blob/1e42ffa181b263f7790f276a5465832bff7ce615/lib/src/response.dart#L84

`['content-type']` is called on null, which should be impossible because `headers` is declared non-nullable.  
This happens only in release mode - in debug mode, the call works just fine.

### Steps to reproduce

Add a dependency to:

```yaml
algolia: ^1.0.4
```

```dart
const client = Algolia.init(
  applicationId: 'UTG3JCLE5Z',
  apiKey: '0d613ed594dc34a584d39bf456fe64ec',
);

final query = client.index('index').filters('foo:bar OR baz:two').query('test search');
```

Unfortunately, I have not yet been able to reproduce this with a plain HTTP request that does not require the package - I will try to do that later.

### Versions

This happens in the latest beta build:

```
Flutter 2.10.0-0.3.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision fdd0af78bb (2 days ago) • 2022-01-25 22:01:33 -0600
Engine • revision 5ac30ef0c7
Tools • Dart 2.16.0 (build 2.16.0-134.5.beta) • DevTools 2.9.2
```

**Comment by danagbemava-nc** [comment]
Hi @creativecreatorormaybenot, 

I tried to reproduce this on the latest `beta` and `master` but I was not able to reproduce. 
In all my tests, the requests were successful. 

<details>
<summary>code sample used</summary>

```dart
import 'package:algolia/algolia.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  String _query = '';

  void _incrementCounter() {
    try {
      const client = Algolia.init(
        applicationId: 'UTG3JCLE5Z',
        apiKey: '0d613ed594dc34a584d39bf456fe64ec',
      );

      final query = client
          .index('index')
          .filters('foo:bar OR baz:two')
          .query('test search');

      setState(() {
        _query = query.toString();
      });
    } catch (e) {
      setState(() {
        _query = e.toString();
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              _query,
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

```
</details>

Is there any more information you can provide?

**Comment by creativecreatorormaybenot** [comment]
@danagbemava-nc with your sample I am unfortunately also not able to reproduce it :/ I have the feeling this is some nasty compiler bug that only occurs in a **very** specific case. Do you know if there is any way for me to provide more information without sharing our full code?

**Comment by danagbemava-nc** [comment]
Hi @creativecreatorormaybenot, I'm not entirely certain unless you can find another context within which it reproduces and share the code for that instead.

**Comment by creativecreatorormaybenot** [comment]
@danagbemava-nc it is difficult because the bug is also super random to us. The _only_ difference is the Flutter version upgrade. There has to have been some change in `dart2js` that causes this, but I am not sure how to trace it down or how to even provide a reproducible sample from that.

**Comment by danagbemava-nc** [comment]
Without a reproducible sample it's going to be difficult for us to find out what the issue is. 

One way you may be able to find out what caused the issue is to bisect to see which version of flutter the issue first appears in, then we can trace from there to see any changes that were made that may have caused the issue.

**Comment by creativecreatorormaybenot** [comment]
Turns out that this is not caused by a specific Flutter version upgrade but instead by a plugin update.

I will leave the Dart SDK issue open instead.
