### ISSUE TITLE
Close the tree when the internal Google roll gets more than 5 business days behind

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#97388]
xref b/216576643

Today, FRoB updates individual PRs for presubmit tests, but this typically only runs a small set of smoke tests (and I believe engine/skia/dart rollers get special treatment). It is frequently the case that the google3 roll gets behind by several days or even weeks. The further behind it gets, the more regressions can pile up and the more painful it is to bisect them, fix them, and get the roll moving again. In the past we have manually closed the tree at times when the internal roll gets too far behind.

I'm proposing we treat the Google roll being behind by > 5 business days as a failing post submit test. We already treat failing contributed tests in post submit as a failure, but cannot do so as aggressively with the internal Google test suite because of how long it takes to run, how difficult it can be to schedule, and the frequent need for human intervention in getting the roll landed.

Incidentally, if we could solve all of these problems (e.g. run the Google tests quickly and regularly land the roll with no human intervention), that would only be more reason to more aggressively treat a Google roll failure in post submit as a tree closing failure (because it means something is seriously wrong).

I am prioritizing this as P5 by default, but IMHO it should get prioritized more highly as soon as we can get some consensus around this.

@Hixie @zanderso @tvolkert @godofredoc @renyou @xster

**Comment by christopherfujino** [comment]
cc @itsjustkevin

**Comment by zanderso** [comment]
This makes sense to me. I'd like to have some info about average roll latency to help think about the number of days after which the tree should be closed. If we're generally getting one roll a week, then a 5 day cutoff would mean we're closing the tree once a week, which is not great. If we have the stats we can aim for a cutoff that's 1 or 2 standard deviations out. The cutoff can shrink later if the roll latency decreases.

**Comment by dnfield** [comment]
https://github.com/flutter/flutter/pull/96926 would help with this, but my suggestion is that it be based on latency of the roll rather than immediately closing the tree if the roll is failing. 5 days is an arbitrary pick by me - I think it's probably good enough but I agree with @zanderso that we should get more data

**Comment by dnfield** [comment]
(and whenever I say days in this issue, I mean business days - we should not close the tree because a roll hasn't happened during a long holiday weekend or something)

**Comment by Hixie** [comment]
> The further behind it gets, the more regressions can pile up and the more painful it is to bisect them, fix them, and get the roll moving again.

Does closing the tree actually help with this? If so, how? It's not like it'll reduce the number of PRs, it'll just bunch them up.

> by > 5 business days

Looking at recent data, this would close the tree most of the time.

**Comment by keyonghan** [comment]
> cc @keyonghan who did some work on the roller latency dashboard

Created a temp internal [dashboard](https://dashboards.corp.google.com/edit/_1ef2c9ae_3a09_429f_b26a_4239c5b0d659) for each flutter-g3 roll latency over time. The median is around 5-6 days. A quick capture:
![Screen Shot 2022-01-27 at 10 54 02 AM](https://user-images.githubusercontent.com/54558023/151425078-6b877fc5-b3fe-460f-a2f0-92208371b2d7.png)

**Comment by dnfield** [comment]
@Hixie - the idea would be to close the tree to all commits except those that help get the roll going again - which is the same state we're in when other post submit failures close the tree. The main difference is that immediately reverting the commit when the tree got red is not going to be the answer.

This does help because it avoids introducing new commits to the roll that cause breakage.

Based on Keyong's data, it's a little hard to tell (those aren't business days, are they?). Can we get data for business days? If we have to bump the number up to 7 or 8 it would still be worthwhile rather than having an arbitrary process where the roller eventually goes "oh no" and asks the gardeners to close the trees.

**Comment by Hixie** [comment]
> @Hixie - the idea would be to close the tree to all commits except those that help get the roll going again - which is the same state we're in when other post submit failures close the tree. The main difference is that immediately reverting the commit when the tree got red is not going to be the answer.

I think there's a number of other differences. For example, when the tree re-opens, the exact same batch of commits as were going to land anyway will all land at once, so the next roll will be no easier, and the tree will eventually close again regardless. This differs from normal tree closures since those are usually short enough that the number of PRs that "batch up" is relatively small, *and they are tested individually* so that we're reasonably sure that they don't break anything.

Another big difference is that the tree will be closed for hours and hours (days maybe) while the roll is being tested, which can take a whole business day -- e.g. when working on #89451, my process is to make changes to the CL under test in the morning in time to catch the 12 o'clock [TAP train](https://www.google.com/books/edition/Software_Engineering_at_Google/WXTTDwAAQBAJ?hl=en&gbpv=1&dq=google+%22tap+train%22&pg=PT477&printsec=frontcover), and then look at the results at 4pm when they come back in, make the relevant changes to the PR, so that I can begin again the next day. It's not at all clear to me that closing the tree for days on end will be a net improvement to team productivity (let alone morale).

The biggest difference is that for most of the other sources of tree closures, a tree closure is an exceptional failure in the process, since we test things pre-commit. The exceptions are things like devicelab where the goal is to move them pre-commit in time (I'm not up to speed on how far along we are with that). With the Google roll, the _expectation_ is that there will be failures, because we don't run the tests ahead of trying to roll, so we are more or less guaranteed to have problems.


I'm not actually convinced that the actual roll is made any easier by closing the tree anyway. Anything that could be done by landing on trunk to make the roll work could be landed out-of-order on the branch being rolled. Why does closing the tree five days after the offending PR has landed help?

**Comment by Hixie** [comment]
> Incidentally, if we could solve all of these problems (e.g. run the Google tests quickly and regularly land the roll with no human intervention), that would only be more reason to more aggressively treat a Google roll failure in post submit as a tree closing failure (because it means something is seriously wrong).

(I do agree that if the rolls were quick and pre-commit testing comprehensive that this would be a much easier "yes" decision.)

**Comment by dnfield** [comment]
It's easier to deal with a roll that has _one_ really difficult commit than a roll that has _more than one_.

The problem today we have is like this: the roll is 10 commits behind. Commits 2, 5 and 7 need manual intervention or reverts. Commit 5 cannot be reverted without also reverting commit 9. The roller doesn't understand the interdependencies between commit 5 and 9, and so needs help from the authors of commit 5 and 9 to revert. The author of commit 9, so communication there ping pongs back and forth. In the mean time, 10 new commits have come in and commits 2 and 7 are successfully reverted. The roller finally gets commits 5 and 9 sorted, but now commit 16 is blocking and can't be easily reverted by the roller either. 

I do not believe this happens more than once per quarter currently (and sometimes only once every two quarters). I would be happy enough with a length of days such that the tree is only closed on this check once per quarter. My main concern right now is that the Flutter team has very little insight into this until they start getting bugs filed from internal teams about fixes they're unable to get through (or until they find that the performance improvement they made in the engine 3 weeks ago still isn't in google and missed a release cut that the customer was depending on).

**Comment by dnfield** [comment]
Put differently: if we find that 5 business days is closing the tree every week, we should make it more days until it is not closing the tree every week, and do whatever process improvements necessary to get it back down to 5 (or less than 5) days.

**Comment by jmagman** [comment]
I thought we were solving this with git branches?  The roll gets branched on commit 10, reverts and fixes for 2, 5, and 7 get merged there, and the master branch keeps chugging along.

**Comment by Hixie** [comment]
I don't understand why the process needs to work as you describe.

First, when you try to revert commit 5, you immediately find that there's a merge conflict, and without knowing anything about the commits you can tell that the offending commit is commit 9. You revert 9, then revert 5, update the PRs, reopen the issues.

Second, why does commit 16 matter? When a roll fails on commits 5 and 9, they are reverted upstream but that's not what gets rolled. They're also reverted on the branch being rolled. Commit 16 never enters the picture until long after the roll has landed.
 
Third, _if_ this kind of twice-a-year situation happens, the person who is best positioned to know that it is happening and that a tree closure would help is the person doing the roll, not an automated system that waits for 5 days to go by. If someone wants to pull the fire alarm and close the tree then that's totally fine, I've no objection to them being able to close the tree. No need for an automated system there.

**Comment by dnfield** [comment]
I talked a bit more with @hixie offline about this.

I think my major misconception here is that I was assuming we only got 5 business days behind a few times a year. It seems that is not the case. I think that this could still be useful as a check we have and try to drive down, even if it starts with some ridiculously high number.

My understanding is that @godofredoc and @athomas are going to be looking at ways to try to improve this. I'll leave this open for now since I think it could be relevant to that discussion, but marking it as waiting for response so that if we don't make any more progress on this idea in the next couple weeks it just gets closed (on the assumption that some better idea will emerge).

**Comment by CaseyHillers** [comment]
I think what we want is to give the ability for the internal roll gardener to be able to manually close the tree, and they can use their best judgement of when the roll is falling behind.

We can create alerts for the gardener based off Keyong's metrics This would require https://github.com/flutter/flutter/issues/74529 to be implemented to reduce the toil of closing the tree.

**Comment by dnfield** [comment]
Repeating my comment on the internal bug here:

I think at this point the consensus is there are two problems:

1. The roll is very frequently >5 days behind, which would mean this would close the tree too often.
2. Closing the tree isn't always necessary because of the use of release branches.

My main goal is to try to keep the roll closer to tip of tree. We can close this an explore other ways to do that.
