### ISSUE TITLE
Missing step in 'RandomWords' Flutter tutorial 

### ISSUE THREAD

**Issue by Silvagni** [flutter/flutter#97382]
I had previously followed another tutorial to install and setup AndroidStudio, I was able to follow the tutorial to create and run their sample app.  I wanted to follow a few more tutorials to cement my knowledge of Flutter and dart.  I found Google's codelab tutorial and followed it until I hit a roadblock with step 5:
    
https://codelabs.developers.google.com/codelabs/first-flutter-app-pt1#5

Thankfully, the tutorial provides completed code for each lesson that a student (i.e., me) can refer to if their code doesn't work. I discovered that the code for the RandomWords class has a change in the provided solution that is never discussed in the tutorial, and in fact is required to allow the step to compile and run.

Specifically, the provided solution code shows that RandomWords class coded as follows:

class RandomWords extends StatefulWidget {
  const RandomWords({Key? key}) : super(key: key);

  @override
  State<RandomWords> createState() => _RandomWordsState();
}

In the previous exercise, the student instructed to create this class as follows:

class RandomWords extends StatefulWidget {
  @override
  _RandomWordsState createState() => _RandomWordsState();
}
but there is no instruction that tell the student that two changes must be done to the RandomWords class:

1) The following line must be add:
const RandomWords({Key? key}) : super(key: key);

2) The line 
 _RandomWordsState createState() => _RandomWordsState();
must be changed to
State<RandomWords> createState() => _RandomWordsState();

I propose adding additional instructions to inform the user of the additional changes to the RandomWords class.  Without these two changes the program won't compile.

**Comment by goderbauer** [comment]
Removing framework since we don't manage the code labs.

**Comment by domesticmouse** [comment]
I believe this is now fixed.
