### ISSUE TITLE
How to get Flutter TextField onLongpress callback when textfield has focus?

### ISSUE THREAD

**Issue by visign3d** [flutter/flutter#97395]
How to get Flutter TextField onLongpress callback when textfield has focus?
```
TextField(onLongpress : ()=>...
```
i tried nearly all Gesturerecogniser gesture callbacks ,but none of them is firering on textfield exept the onPanUpdate. The behavior i am looking for is to unfocus the textfiels on longtap,and call some other functions. At the moment the textfield behaviour on longpress is selction of a word.

Detailed behaviour description :

1. text field is focused,cursor is blinking
2. Longpress on textfield
3. Override textfield on lonpress behaviour (By default textfield selects a word under the cursor)

**Comment by darshankawar** [comment]
@visign3d 
Your question is better suited for support channels like StackOverflow, so please ask the same there.
Closing from here.
