### ISSUE TITLE
The Action.overridable dartpad example fails to run

### ISSUE THREAD

**Issue by justinmc** [flutter/flutter#97397]
The DartPad example on this page in the docs gives the error "Error compiling to JavaScript". https://master-api.flutter.dev/flutter/widgets/Action/Action.overridable.html

CC @LongCatIsLooong

**Comment by safarmer** [comment]
The sample seems to compile just fine now, but the sample does not work as described. The delete intents are not sent. I also see the same behaviour on my code that tries to use the same intents where the intent is not triggered.

**Comment by LongCatIsLooong** [comment]
I believe that's because delete is handled by the browser for web.

**Comment by safarmer** [comment]
It also behaves the same (broken) way on iOS.

I think the widget docs are misleading as well since the demo only shows up when viewing the docs on web?

**Comment by safarmer** [comment]
My understanding is that the delete actions/intents are only handled by Flutter on a subset of supported platforms. Is this correct? Should this be called out in the documentation?

**Comment by LongCatIsLooong** [comment]
Just tested it works on iOS (I was too lazy to properly place the caret so I overrode the action to delete the entire section instead of single digit. Should be easy to do with `TextEditingValue.replaced` now).

**Comment by LongCatIsLooong** [comment]
It wasn't a good idea to use a shortcut in an `Action` example. I'll try to come up with something else.

@safarmer AFAIK the only exception is text editing on web. But I believe it's already documented elsewhere.

**Comment by safarmer** [comment]
@LongCatIsLooong no luck on iOS with your example verbatim. I think the issue is with IME vs physical keyboard? Did you test on iOS with a real device, or the simulator with input from your keyboard? I can get the demo to work on the simulator if I use my attached keyboard and not the on-screen software keyboard.

I am currently seeing this in the logs when I interact with the text fields though (once per focus change), but I think they are unrelated.

```
Can't find keyplane that supports type 5 for keyboard iPhone-PortraitTruffle-PhonePad; using 27170_PortraitTruffle_iPhone-Complex-Pad_Default
Can't find keyplane that supports type 5 for keyboard iPhone-PortraitTruffle-PhonePad; using 27170_PortraitTruffle_iPhone-Complex-Pad_Default
Can't find keyplane that supports type 5 for keyboard iPhone-PortraitTruffle-PhonePad; using 27170_PortraitTruffle_iPhone-Complex-Pad_Default
Can't find keyplane that supports type 5 for keyboard iPhone-PortraitTruffle-PhonePad; using 27170_PortraitTruffle_iPhone-Complex-Pad_Default
```

https://user-images.githubusercontent.com/716699/170406726-bcbadf71-5a6f-468e-bad9-d42beb959e8c.mp4

**Comment by LongCatIsLooong** [comment]
Ah right if you delete using the software keyboard it doesn't use Intent (yet). But I think it's possible to do so (at least on iOS): https://developer.apple.com/documentation/uikit/uikeyinput/1614572-deletebackward?language=objc

**Comment by safarmer** [comment]
Thanks @LongCatIsLooong. Do you know if adding support for software keyboard is on the roadmap? Or is it a case of implementing something in native code for iOS and passing the event back to Flutter myself?

**Comment by LongCatIsLooong** [comment]
For iOS this needs to be implemented in the flutter engine. https://github.com/flutter/flutter/issues/14809 is closed so I don't think anyone's currently working on it. I'll do some research to see if this is actually doable.
