### ISSUE TITLE
in_app_purchase issues on iOS

### ISSUE THREAD

**Issue by supardyke** [flutter/flutter#97398]
after creating my subscriptions on iOS 
i added this package to my app 
initialized the package on app start
when I try to getProducts it returns an empty array,

I have reached the apple team and they asked me to drop an issue here, been on this for weeks now.

is there a step by step approach to use this package??

**Comment by austinmalmberg** [comment]
Yes, many. Try going to www.google.com and typing `flutter` into the search box. That worked for me.

**Comment by PfernFSU** [comment]
Hey @supardyke - I think you did not post to the correct place. Any chance you meant to put this issue in the package repository instead of the Flutter repository?

**Comment by darshankawar** [comment]
@PfernFSU 
This is the correct repo to report `in_app_purchase` related issues since it is Flutter's first party plugin.

@supardyke 


> is there a step by step approach to use this package??

Ideally, the plugin's readMe should be the correct starting point to use the package which has an example for your reference: https://pub.dev/packages/in_app_purchase

**Comment by supardyke** [comment]
i have done every thing in the documentation but still it did not make the subscriptions show on the App

**Comment by darshankawar** [comment]
@supardyke 
In order to properly address your issue, provide your `flutter doctor -v`, `pubspec.yaml` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows current behavior and what are you expecting to work.

Thanks.
