### ISSUE TITLE
[multicast_dns] Web support

### ISSUE THREAD

**Issue by jeffaknine** [flutter/flutter#97415]
## Use case
I am building a streaming application where the user has the ability to cast to a chromecast.
The application is fully cross platform.

## Proposal
Is it possible to get multicast_dns support for web ? Or is there a technical reason why it wasn't implemented ?

**Comment by maheshmnj** [comment]
Hi @jeffaknine, Thanks for filing the issue. 

> Is it possible to get multicast_dns support for web ? Or is there a technical reason why it wasn't implemented ?

Keeping this issue open for further insights from the team

**Comment by jeffaknine** [comment]
I am guessing that it is linked to this issue #39998 ?

**Comment by stuartmorgan** [comment]
Browsers don't support UDP, so this cannot be implemented.

**Comment by jeffaknine** [comment]
So, how does a browser stream to a chromecast ?

**Comment by stuartmorgan** [comment]
That was poorly phrased. Browsers *themselves* can certainly use UDP, but they don't expose that ability to web content.

**Comment by yjbanov** [comment]
I'm not an expert on streaming but I've heard [WebRTC](https://webrtc.org/) mentioned a lot together with "streaming" and "web". There's nothing Flutter would need to do for you to use it. It's just a browser API that you can call directly without Flutter's assistance.
