### ISSUE TITLE
unawaited_futures not always working

### ISSUE THREAD

**Issue by sgehrman** [flutter/flutter#97410]
Not sure what changed, but I'm seeing some cases where unawaited_futures isn't flagging the missing awaits.

Not sure if this is the best example, but something like this.

I'm on the latest stable etc.

$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on Debian GNU/Linux 11 (bullseye) 5.10.0-10-amd64, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc4)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.63.2)
[✓] Connected device (2 available)

```
Future<String> test() async {
   return 'test';
}

Future<void> callTest() async {
    final data = test();   // needs an await here
    print(data);
}
```

**Comment by jonahwilliams** [comment]
I believe this is working as intended. The problem unawaited futures is trying to solve is identifying cases where a future value is neither "used" nor awaited. Passing the future to print counts as using it, the same as passing it to `unawaited()` would (which is really just a no-op function). If that weren't the case, then using the unawaited futures lint would prevent you from ever writing functions that accept futures

**Comment by sgehrman** [comment]
That case I sent was just an example, but I found this problem because I had a bug in my code that was clearly missing the await, but it wasn't flagged.  It's flagged in bunch of other cases, but not every one, I don't know why exactly.  It seems broken to me.  I don't pass futures around, If this were designed to be this way, then I would like a more strict lint flag always_unawaited_futures.

Unawaited future is probably the most common bug I've seen in my code and having that lint working 100% is incredibly important.

I'll see if I can find a pattern.

```
 Future<shelf.Response> _handleUpdates(
    shelf.Request request,
    String path,
  ) async {
    final params = request.requestedUri.queryParameters;

    final data = await ReleaseNotes.shared.notes(path, params);

    return ServerUtils.ok(
      request: request,
      body: Stream.value(data),
      filename: 'index.html', // for mime type
    );
  }
```
That's the code that just crashed on me.  The await was missing in await ReleaseNotes.

**Comment by jonahwilliams** [comment]
Can you point out the problem? I'm not seeing it

**Comment by sgehrman** [comment]
The line was
    final data = ReleaseNotes.shared.notes(path, params);

It needed the await, but the linter didn't warn
    final data = await ReleaseNotes.shared.notes(path, params);

**Comment by jonahwilliams** [comment]
So you accidentally created a stream<future<t>> instead of a stream<t>, I see. You might also solve this problem by tightening the type signature of your ServerUtils method so that it requires a specific stream type.

I don't think that you'd be able to augment the lint to flag that case though, because although rare a stream of a future is a perfectly legitimate type, and passing the future to the constructor counts as using it.

**Comment by darshankawar** [comment]
> You might also solve this problem by tightening the type signature of your ServerUtils method so that it requires a specific stream type.

@sgehrman Please check this and see if that helps to resolve your case.

**Comment by sgehrman** [comment]
@darshankawar 

That function takes a dynamic.  I can pass a String, Map, Stream etc.

Anyway, just wanted to recommend a stricter lint rule to catch this kind of bug.

Thanks

**Comment by darshankawar** [comment]
Thanks. Keeping it open and labeling for further input from the team.

**Comment by darshankawar** [comment]
@sgehrman 
Please check this issue comment for your reference related to `unawaited_futures` : https://github.com/flutter/flutter/issues/5793#issuecomment-274355004
