### ISSUE TITLE
non-JS module files deprecated.

### ISSUE THREAD

**Issue by Bharatjangid786** [flutter/flutter#97419]
![Screenshot (101)](https://user-images.githubusercontent.com/98579071/151505467-402dfe38-5b79-4f48-bc68-5d217a61e5e4.png)

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19042.1466], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.63.2)       
[√] Connected device (2 available) 

• No issues found!

**Comment by silverhairs** [comment]
I think this is something related to VSCode, @Bharatjangid786  can you provide your `launch.json` file, please?

**Comment by darshankawar** [comment]
@Bharatjangid786 
Check above link and see if it helps.
