### ISSUE TITLE
[tool_crash] NoSuchMethodError: NoSuchMethodError: The method 'containsKey' was called on null.Receiver: nullTried calling: containsKey("default_package")

### ISSUE THREAD

**Issue by TejasShukalPlutustec** [flutter/flutter#97427]
## Command
```
flutter --no-color pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
NoSuchMethodError: NoSuchMethodError: The method 'containsKey' was called on null.
Receiver: null
Tried calling: containsKey("default_package")
```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      Plugin._providesImplementationForPlatform (package:flutter_tools/src/plugins.dart:302:49)
#2      new Plugin._fromMultiPlatformYaml (package:flutter_tools/src/plugins.dart:130:9)
#3      new Plugin.fromYaml (package:flutter_tools/src/plugins.dart:85:21)
#4      _pluginFromPackage (package:flutter_tools/src/plugins.dart:341:17)
#5      findPlugins (package:flutter_tools/src/plugins.dart:363:27)
<asynchronous suspension>
#6      refreshPluginsList (package:flutter_tools/src/plugins.dart:1166:32)
<asynchronous suspension>
#7      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:300:5)
<asynchronous suspension>
#8      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:167:5)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.22000.318], locale en-IN)
    • Flutter version 2.2.3 at C:\src\flutter_windows_2.2.3-stable\flutter
    • Framework revision f4abaa0735 (7 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\PLUTUS\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Java\jdk-17.0.1\bin\java
    • Java version Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.63.2)
    • VS Code at C:\Users\PLUTUS\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 97.0.4692.99
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 97.0.1072.69

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.6+6
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 840c9205b344a59e48a5926ee2d791cc5640924c
### Plugins
assets_audio_player_plugin
assets_audio_player_web-3.0.3+6
connectivity-3.0.6
connectivity_for_web-0.4.0+1
connectivity_macos-0.2.1+2
device_info-2.0.3
dropbox_client-0.8.0
firebase_analytics-8.3.4
firebase_analytics_web-0.3.0+1
firebase_core-1.10.0
firebase_core_web-1.2.0
firebase_crashlytics-2.3.0
firebase_messaging-10.0.9
firebase_messaging_web-2.1.0
flutter_image_compress-1.1.0
flutter_local_notifications-8.2.0
flutter_video_cast-1.0.3
fluttertoast-8.0.8
integration_test-1.0.2+3
intercom_flutter-5.3.0
intercom_flutter_web-0.0.4
path_provider-2.0.4
path_provider_linux-2.1.1
path_provider_macos-2.0.2
path_provider_windows-2.0.4
permission_handler-8.1.6
shared_preferences-2.0.7
shared_preferences_linux-2.0.3
shared_preferences_macos-2.0.2
shared_preferences_web-2.0.2
shared_preferences_windows-2.0.3
sqflite-2.0.0+4
url_launcher-6.0.10
url_launcher_linux-2.0.2
url_launcher_macos-2.0.2
url_launcher_web-2.0.4
url_launcher_windows-2.0.2
video_player-2.1.15
video_player_web-2.0.6
video_player_web_hls-0.1.11+3
wakelock-0.5.6
wakelock_macos-0.4.0
wakelock_web-0.4.0
webview_flutter-2.0.13

**Comment by danagbemava-nc** [comment]
Hi @TejasShukalPlutustec, you appear to be on an older version of flutter. 

Can you upgrade to the latest to see whether or not this is still an issue? 

If it is, please provide the updated `flutter doctor -v`

Thank you

**Comment by TejasShukalPlutustec** [comment]
![image](https://user-images.githubusercontent.com/72876637/151548798-26350193-7a9f-4f05-b6bf-4e58b6871144.png)

**Comment by danagbemava-nc** [comment]
The flutter tooling has changed quite a bit since the version you're on. 

It's possible this issue may have been fixed in recent versions of flutter. Kindly upgrade and let me know if you still face this issue. 

Latest version of stable is `2.8.1`.

Thank you
