### ISSUE TITLE
[video_player] [Proposal] Improve handling for setPlaybackSpeed iOS edge case

### ISSUE THREAD

**Issue by navaronbracke** [flutter/flutter#97425]
## Use case

In the implementation of `VideoPlayerController.setPlaybackSpeed(value)`
there is an if-check that tries to circumvent an issue on iOS:

```
  Future<void> _applyPlaybackSpeed() async {
    if (_isDisposedOrNotInitialized) {
      return;
    }

    // Setting the playback speed on iOS will trigger the video to play. We
    // prevent this from happening by not applying the playback speed until
    // the video is manually played from Flutter.
    if (!value.isPlaying) return;

    await _videoPlayerPlatform.setPlaybackSpeed(
      _textureId,
      value.playbackSpeed,
    );
  }
```

This limits other platforms that do not have this implementation detail from using `setPlaybackSpeed()` when the video _is not_ playing. 

## Proposal

I'd propose an enum that controls the behaviour for this check.
On iOS, the strategy prevents changing the playback speed when the video is paused.
On other platforms, the strategy allows changing the playback speed when paused.

```
enum VideoPlayerPlaybackSpeedStrategy {
  /// Allow changing the playback speed even if the video is paused.
  /// This is the default for all platforms, except iOS.
  enabledWhenPaused,

  /// Prevent changing the playback speed if the video is paused.
  /// This is the default on iOS, as setting the playback speed on iOS
  /// will trigger the video to play.
  disabledWhenPaused,
}
```

```
  Future<void> _applyPlaybackSpeed() async {
    if (_isDisposedOrNotInitialized) {
      return;
    }

    if (!value.isPlaying && value.playbackSpeedStrategy == VideoPlayerPlaybackSpeedStrategy.disabledWhenPaused) { 
      return; 
    }

    await _videoPlayerPlatform.setPlaybackSpeed(
      _textureId,
      value.playbackSpeed,
    );
  }
```

**Comment by jmagman** [comment]
#3084

**Comment by stuartmorgan** [comment]
> This limits other platforms that do not have this implementation detail from using `setPlaybackSpeed()` when the video _is not_ playing.

I'm not clear on what the "limitation" is here; what problem are you trying to solve? The playback speed isn't relevant when it's not playing.

**Comment by navaronbracke** [comment]
I had a requirement where a user should be able to set the playback speed when the video is paused so that when it resumes, it starts playing at that speed.

**Comment by stuartmorgan** [comment]
> I had a requirement where a user should be able to set the playback speed when the video is paused so that when it resumes, it starts playing at that speed.

The plugin already handles that, so I'm still not sure what the issue here is.



> Since it ignores the setPlaybackSpeed() call when not playing

No it doesn't; the part you quoted isn't the entire function.

Do you have a reproduction case where it doesn't work, or is this issue report speculative based on reading part of the code?

**Comment by navaronbracke** [comment]
> The plugin already handles that, so I'm still not sure what the issue here is.
> Do you have a reproduction case where it doesn't work, or is this issue report speculative based on reading part of the code?
The latter was indeed my train of thought at the time of opening this issue. I'll double-check after the weekend. If it indeed doesn't work, then I'll reopen this issue.
