### ISSUE TITLE
Flutter Beacon : Beacon property values are not retrieved.

### ISSUE THREAD

**Issue by unoravi** [flutter/flutter#97423]
I have used almost all the dependencies on pub.dev to interact with beacon (BLE) devices. Interaction and signal emitting works proper as required. At the time of signal emit I want below beacon parameter values but did not found any values. I get RSSI value inaccurate in dependency "flutter_reactive_ble: ^5.0.2"

- Beacon Distance **(MUST REQUIRED)**
- Battery Percentage
- Beacon Acceleration
- Acceleration Threshold

Is there any dependency in which I can get accurate values of above parameters ?

Thanks

**Comment by danagbemava-nc** [comment]
Hi @unoravi, 

Kindly see any of the communities in https://flutter.dev/community#community-grid for asking support questions such as this. 

The flutter issue tracker is for reporting issues or feature requests for flutter. 

Seeing as this is neither a feature request nor a bug report related to flutter, I'm going to close this issue. 

PS: There are already issues open for first-party support for Bluetooth in https://github.com/flutter/flutter/issues/53493 and https://github.com/flutter/flutter/issues/23562

Thank you.
