### ISSUE TITLE
webview android This request has been blocked; the content must be served over HTTPS."

### ISSUE THREAD

**Issue by wywinstonwy** [flutter/flutter#97420]
I/chatty  (20703): uid=10146(com.qctt.cn.qctt_flutter) identical 1095 lines
I/chromium(20703): [INFO:CONSOLE(0)] "Mixed Content: The page at 'https://m.qctt.cn/newsinfo?version=9.2.0&id=1190657' was loaded over HTTPS, but requested an insecure image 'http://qcttapp.qiniudn.com/touxiang.png'. This request has been blocked; the content must be served over HTTPS.", source: https://m.qctt.cn/newsinfo?version=9.2.0&id=1190657 (0)

**Comment by maheshmnj** [comment]
Hi @wywinstonwy, Thanks for filing the issue. This issue looks same as https://github.com/flutter/flutter/issues/43595 where you are trying to load a mixed content, Could you please confirm if this is the same issue?
