### ISSUE TITLE
[google_maps_flutter ] New Google Map SDK 18.0.0 on Android

### ISSUE THREAD

**Issue by arusin-mind** [flutter/flutter#97429]
I received an email from Google for new Google Map SDK 18.0.0.
Now, you are using 17.0.0.
Could you please update this SDK references to 18.0.0?
Thanks.

**Comment by maheshmnj** [comment]
Hi @arusin-mind, Could you please point to the resource that you are referring to?

Thanks

**Comment by arusin-mind** [comment]
Hi @maheshmnj Thanks for your quick reply.
I mean the google_maps_flutter package : https://pub.dev/packages/google_maps_flutter

**Comment by maheshmnj** [comment]
Thanks for the info considering this as a proposal to update google maps SDK to 18 https://developers.google.com/maps/documentation/android-sdk/releases

**Comment by arusin-mind** [comment]
@maheshmnj Okay, thanks. :)
When you upgrade the package, could you please let me know?
Thanks again.

**Comment by maheshmnj** [comment]
sure will ping you here :)

**Comment by Aperico-com** [comment]
Please also let us have API exposure to the new renderer in 18 so we can use it in Flutter, many are looking forward to the improved performance:
https://developers.google.com/maps/documentation/android-sdk/renderer

**Comment by tuemaytinh1981** [comment]
Can you please give priority to update new render map sdk 18.0.2?. More than 3 months left 06/2022 is google map update new Map SDK for Android.

[https://developers.google.com/maps/documentation/android-sdk/config#step_4_add_the_maps_dependency](https://developers.google.com/maps/documentation/android-sdk/config#step_4_add_the_maps_dependency)
[https://developers.google.com/maps/documentation/android-sdk/renderer#how_to_try_the_new_renderer](https://developers.google.com/maps/documentation/android-sdk/renderer#how_to_try_the_new_renderer)

**Comment by maheshmnj** [comment]
@tuemaytinh1981 This issue is correctly prioritized as per the guidelines https://github.com/flutter/flutter/wiki/Issue-hygiene#priorities what exactly do you mean by 

> More than 3 months left 06/2022 is google map update new Map SDK for Android.

**Comment by raphael-bmec-co** [comment]
@tuemaytinh1981 I think the update to the new render map SDK 18.0.2 is optional so it won't be a breaking issue come 06/2022, maybe you can confirm this @maheshmnj?

**Comment by maheshmnj** [comment]
Not that I am aware of, But the links shared above don't seem to mention that its a mandatory update or there isn't any such hard and fast timeline attached.

**Comment by maheshmnj** [comment]
Closing as duplicate of https://github.com/flutter/flutter/issues/92651 Since that issue is prioritized.
