### ISSUE TITLE
Wrong help message in `flutter gen-l10n`

### ISSUE THREAD

**Issue by kaboc** [flutter/flutter#97430]
## Steps to Reproduce

1. Run `flutter gen-l10n --help`.
2. See the help of `--[no-]nullable-getter`.

**Expected results:** 

"If this value is set to false"

**Actual results:** 

"If this value is set to true"

> If this value is set to true,
> then a null check is performed on the returned value of
> Localizations.of(context), removing the need for null
> checking in user code.

## Additional context

A PR (#90180) by someone else to fix this has been closed without being merged because of a missing test.

I gave up fixing it myself, not knowing what test was needed, but I thought I should at least file an issue about it so that it'd catch someone's eye.

**Comment by darshankawar** [comment]
<img width="598" alt="Screenshot 2022-01-28 at 6 46 51 PM" src="https://user-images.githubusercontent.com/67046386/151553891-733fc302-d79a-47e3-8ed3-8cf22819219b.png">
