### ISSUE TITLE
Increase commit window for detecting flakes

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#97442]
The current flake bot use recent 100 commits to calculate flake percentage and file flaky bugs if exceeding 2%. However it happens that we just hit flakes/failures within the window. If considering a bigger range, the real flake percentage is way below the threshold.

We need to increase the window to a bigger number like 200+ commits if there are enough data. Another plus is an easy way to reset/flag the counter. For example when we have a fix, we can reset and then the bot will only pick up newer runs/commits.

On the other hand, sometimes we mark a test as flaky, then it runs in staging. When newly deflaked, it will start running in prod, where we will have limited runs in the beginning. For this case, we will use whatever is available as the denominator.

/cc @Hixie

**Comment by godofredoc** [comment]
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.
