### ISSUE TITLE
Is this diagram correct?

### ISSUE THREAD

**Issue by FaisalAbid** [flutter/flutter#9744]
The diagram is described currently as 
`The Flutter framework is organized into a series of layers, with each layer building upon the previous layer.`

However shouldn't the following diagram have Mater and Cupertino on the same level? Rather than Material building off Cupertino?

<img width="938" alt="screenshot 2017-05-02 19 52 15" src="https://cloud.githubusercontent.com/assets/253700/25643980/eed3591a-2f70-11e7-9be4-1838f2cf0143.png">

**Comment by abarth** [comment]
The diagram is correct.  Material re-uses some Cupertino widgets to implement https://material.io/guidelines/platforms/platform-adaptation.html

It's confusing enough that we should probably remove the diagram.

**Comment by abarth** [comment]
(There's another bug on file somewhere for removing the diagram.)

**Comment by FaisalAbid** [comment]
Ah okay thanks!

**Comment by sethladd** [comment]
I'd love to make material and cupertino as peers. I think there's value in the diagram, it shows the many capabilities of the system.

@abarth are you comfortable if we make this a "logical diagram" and thus put cupertino and material as peers?
