### ISSUE TITLE
Count runs rather than commits when detecting flakes

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#97440]
Existing flake bot counts commits when detecting flakes. For example, if a test fails 4 times and passes at the fifth run, we only count the flake once. However that should be 80% flaky already.

/cc @Hixie

**Comment by godofredoc** [comment]
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.
