### ISSUE TITLE
[webview flutter] flutter.dev in webview causes overlap of title app bar and content

### ISSUE THREAD

**Issue by neiljaywarner** [flutter/flutter#97451]
using webview with flutter.dev causes the "flutter" app bar/title to overlap the content of the page. It is concerning to me what other real-world sites may have similar issues.
This occurs on Android and ios both.

See: https://codelabs.developers.google.com/codelabs/flutter-webview#3

```
```

![Screenshot_20220128-125445](https://user-images.githubusercontent.com/3019617/151629661-7472dd23-4fb2-49bd-9460-82523c5f61be.png)

```
```

na-081md6tmbp:resident_app neil.warner$ ~/flutter/bin/flutter doctor -v
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6.2 20G314 darwin-x64, locale en-US)
    • Flutter version 2.8.1 at /Users/neil.warner/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (6 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/neil.warner/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Community Edition (version 2021.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 63.3.3
    • Dart plugin version 212.5632

[✓] Connected device (3 available)
    • iPhone 13 Pro Max (mobile) • 5A2B048E-7CEB-4ECB-8CA8-9ACC82E45BCE • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 11.6.2 20G314 darwin-x64
    • Chrome (web)               • chrome                               • web-javascr

</details>

**Comment by stuartmorgan** [comment]
You have JavaScript disabled. The plugin has no control over how sites behave without JS.

**Comment by neiljaywarner** [comment]
@stuartmorgan  i noticed that just now. however, it's still a bug in the documentation and/or example

**Comment by stuartmorgan** [comment]
The page you linked to says:
> As you scroll, you will notice parts of the page that might look a bit odd. This is because JavaScript is currently disabled and rendering flutter.dev properly requires JavaScript.

I'm not sure what you think is a bug here. This behaves as intended, and as documented.

**Comment by neiljaywarner** [comment]
I apologize

....sent from my phone
