### ISSUE TITLE
[flutter webview] Documentation on pub.dev and in codelab - ios webview doesn't work without modification

### ISSUE THREAD

**Issue by neiljaywarner** [flutter/flutter#97452]
pub.dev nor codelab mentions this but info.plist changes required for webview to work on ios (simulator at least
`  <key>io.flutter.embedded_views_preview</key>
    <string>YES</string>
`
see: https://pub.dev/packages/webview_flutter
and https://codelabs.developers.google.com/codelabs/flutter-webview#2

**Comment by stuartmorgan** [comment]
That hasn't been true for well over a year, which is why the docs don't say to add it.

**Comment by neiljaywarner** [comment]
@stuartmorgan  well. it didn't work for me without doing it.... Does it do any harm to leave it in?

**Comment by stuartmorgan** [comment]
> it didn't work for me without doing it

There is no code in the engine that reads that key, and hasn't been for more than a year. Whatever issue you had, it was not related to that unless you are running a very old version of Flutter.

 > Does it do any harm to leave it in?

Yes. Adding pointless, no-op steps to documentation makes the documentation worse.

**Comment by neiljaywarner** [comment]
I meant does it do any harm to leave it in my code
.... Will probably try to remove it Monday

....sent from my phone

**Comment by neiljaywarner** [comment]
I removed it and did flutter clean and deleted build directory and it works. <shrug> sorry about that.
