### ISSUE TITLE
[flutter-web] Add support for classes or  testID attribute that can be used to identify html tags

### ISSUE THREAD

**Issue by adrian-moisa** [flutter/flutter#97455]
I'm desperately trying to get Cypress to run on top of the html renderer. Out of all possible testing tools I am strongly favouring Cypress for many reasons. All I need is some sort of an id/class/attribute that can help me find the desired divs. I was looking for ids but I found this answer. Please don't force us to [misuse Semantics](https://stackoverflow.com/questions/58679661/testing-flutter-apps-with-cypress) for the sake of testing in Cypress. And no I don't desire to use the official testing tooling. I've had many experience in the past to reach the conclusion that Cypress is the way forward.

> 
> We cannot support adding stable IDs to HTML nodes generated by the engine because the DOM structure is not stable. There's no 1-to-1 correspondence between widgets and DOM nodes. However, you can use platform views where you can create your own DOM nodes and assign arbitrary attributes, including `id`.
> 

_Originally posted by @yjbanov in https://github.com/flutter/flutter/issues/95624#issuecomment-1006873329_

**Comment by adrian-moisa** [comment]
I'm going to share some extra info just to clarify that I really hope to see support for testing ids or plain old ids and classes. As long as the semantics can be tracked in the widgets tree, I suppose there's a way to mirror ids as well.

**Testing with Cypress**
Thanks to the HTML renderer in Flutter we had the possibility to test using Cypress. The beauty of this approach is that we can use the comfort of the browser developer tools to run the tests as close to real conditions as possible. Another benefit is the way Cypress deals with change detection in SPA frameworks. Cypress by default waits a certain amount of period until the change detection does its job. This spares us of the major pain of having to orchestrate change detection events inside the framework testing environment (Angular, React, Flutter, testing tools all have this drawback).

Another consideration is the severity of the bugs and the time spent on fixing them. From practice and experience I observed that the serious bugs show up in integration scenarios. These integration scenarios tend to be a lot harder to test in a unit testing fashion. When testing, our focus is on finding integration behaviours that don't work as expected. Thankfully, Cypress can be used to emulate both unit testing and integration testing. That means you have one tool that handle both scenarios if properly configured.

During the lifespan of the app the components themselves are changed quite often. Therefore more than half of the development effort for unit testing is spent on upgrading the tests. The difficult part of refactoring unit tests is that it requires careful analysis of the code that rigs the component for testing, the code that triggers the change and the code that evaluates the results. Testing code built with the unit testing provided by the framework has to deal with:
	- Setting up a testbed (declaring the dependencies)
	- Precise invocation of the methods that control the change detection mechanism
	- Blindly reading virtual dom and using super technical abstractions to reach to the template
	- Interpreting the results and checks to make sure we really testing what we think we are testing

All these operations are far easier to setup and maintain when dealing with the component as it is in the UI. This is where Cypress shines. Cypress is able to handle the components like any other regular DOM. It has built in async support which automatically waits until the change detection settles on the final state. It has short and concise syntax. Overall the life testing in Cypress is a lot easier. With the exception induced by Flutter DOM rendered, of not so easy to query the DOM. I'll explain down bellow.

Summary:
- Access to browser dev tools
- No need to hassle with change detection
- Unit testing eats up a lot of valuable time at refactoring
- Most bugs happen in integration

**Cypress Caveats**
In an ideal world, Flutter would provide a means of tagging elements with testingIds. For whatever internal reason the dev team decided not do so. This makes the job of composing queries to find elements in page is a bit harder. Since the flutter framework generates a super verbose dom tree we need to rely on other method for spotting elements in the hierarchy.

	- Search by text
	- Search by aria label (semantics for accessibility)

Search by text however has another caveat. For whatever reason, the Flutter framework often times outputs small canvas elements for small text fragments. This means sometimes you might not be able to find your element by using `cy.contains()`. A fix around this issue is to add the following property in the text fields that refuse to render as paragraphs. 

	https://github.com/flutter/flutter/issues/74986
        style: TextStyle(
          fontFeatures: const [FontFeature.proportionalFigures()],
        ),

Whenever you can't use text search, you can use Aria tags. Make sure to label your ids in such a way that they make sense for screen readers and users with disabilities. After all we will need to consider this demographic sooner or later. So we better start earlier than later. There are currently 2 ways available to setup these tags:

	https://stackoverflow.com/questions/58679661/testing-flutter-apps-with-cypress/69048640?noredirect=1#comment125341233_69048640
        Semantics(
          label: 'Article title',
          child: Container(...),
        ),


	Text(
          widget.article.author?.name ?? '',
          semanticsLabel: 'Author name',
        ),
	

These fixes are not a great solution but they do the job. Hopefully in the future the Flutter dev team will address the text rendering issue. And hopefully they will add support for ids and classes. Until that happens we have to work around these issues. Ruins a bit the fun of Cypress but it still is not a sufficient reason to abandon this approach. The benefits far outweigh the drawbacks.

**Comment by adrian-moisa** [comment]
I think this screenshot explains better why so much trouble for this:
![unknown](https://user-images.githubusercontent.com/11160141/151714486-3bbb6745-c5e8-4fff-8b01-dc9538531124.png)

**Comment by yjbanov** [comment]
I'm still of the opinion that looking into `<flt-glass-pane>` is the wrong method for this. However, being able to integrate with other testing tools is a reasonable feature request.

**Comment by slavap** [comment]
@adrian-moisa @yjbanov 
I'm successfully using integration testing based on semantics, it works fine with **both html and canvaskit** renderers. This post on stackoverflow helped me to start:  https://stackoverflow.com/a/70918545/714136
Semantics generated "by default" is sufficiently enough, I don't have many "custom" Semantics() in my large project.
In some cases it would be nice to be able to add classes or ids to DOM elements, but it will be limited to html renderer only.

```js
// First activate semantics:
document.querySelector('flt-glass-pane').shadowRoot.querySelector('flt-semantics-placeholder').click({force: true});

document.querySelector('flt-glass-pane').shadowRoot.querySelector('[aria-label="Search"]').click();

document.querySelector('flt-glass-pane').shadowRoot.querySelector('[aria-label="First Name *"]').focus();
document.querySelector('flt-glass-pane').shadowRoot.querySelector('[aria-label="First Name *"]').value = 'John';

document.querySelector('flt-glass-pane').shadowRoot.querySelector('[aria-label^="HOLD"]').click();
```

**Comment by adrian-moisa** [comment]
@slavap I'd recommend you alias these long queries for readability. I see that the Flutter team marked it as new feature. I hope that we will see testing ids soon. Until then we can alias the querying to make it easier to digest and hide this little nastiness from the tests.

**Comment by slavap** [comment]
@adrian-moisa Of course I'm not repeating document.querySelector('flt-glass-pane').shadowRoot in real code :-) It is just a simple example to help others to start with.

**Comment by adrian-moisa** [comment]
@darshankawar, @yjbanov Any updates on the testing ids? Almost one years since this ticket was filled and the feature requested. It would be extremely useful feature. I've been revisiting again unit testing and integration testing practices in Flutter and I'm simply not going to budge. I really want to test using Cypress, it deals away with `pump()` or `pumpAndSettle()`. 

I've worked for years with Angular and React testing libs and they have the same concepts of manually triggering the change detection. They are super prone to breaking and extremely finicky to maintain. In many scenarios it's simply more effort to test the feature than to develop. Cypress has majore advantages in this regard by skipping on waiting the changed detection process completely. It polls and when the layout is ready the test passes. That is tremendously useful for setting up more complicated test scenarios. Not to mention far easier to simulate mouse interactions. Plus the ability to hook AI plugins for detecting styling regressions. All these goodies, just one step away, simply by adding testing ids. I'm also looking to test adaptive behaviours. These will be far far easier tested in cypress due to the rich browser API wrapper.

Please consider adding support for this. Once an element has testing ID it should never render as canvas, always as html element. I've seen many places where Flutter decides for some reason to use canvas in html rendering instead of html elements. I'm about to start writing several thousand test cases... and I desperately need these testing ids. It's a simple change that yields major benefits. I lack the knowhow needed to contribute this feature myself. Thank you for reconsidering the priority on this ticket!

**Comment by AlexKenbo** [comment]
If this does not move, then the best idea is to generate these identifiers in the layout by inserting some artifacts from the widget (name or text)

**Comment by slavap** [comment]
@AlexKenbo approach I've mentioned earlier works just fine with both renderers: https://github.com/flutter/flutter/issues/97455#issuecomment-1058758602

**Comment by ricardolb** [comment]
> @adrian-moisa @yjbanov I'm successfully using integration testing based on semantics, it works fine with **both html and canvaskit** renderers. This post on stackoverflow (by @adrian-moisa) helped me to start: https://stackoverflow.com/a/70918545/714136 Semantics generated "by default" is sufficiently enough, I don't have many "custom" Semantics() in my large project. In some cases it would be nice to be able to add classes or ids to DOM elements, but it will be limited to html renderer only.
> 
> ```js
> // First activate semantics:
> document.querySelector('flt-glass-pane').shadowRoot.querySelector('flt-semantics-placeholder').click({force: true});
> 
> document.querySelector('flt-glass-pane').shadowRoot.querySelector('[aria-label="Search"]').click();
> 
> document.querySelector('flt-glass-pane').shadowRoot.querySelector('[aria-label="First Name *"]').focus();
> document.querySelector('flt-glass-pane').shadowRoot.querySelector('[aria-label="First Name *"]').value = 'John';
> 
> document.querySelector('flt-glass-pane').shadowRoot.querySelector('[aria-label^="HOLD"]').click();
> ```

Hi @slavap, were you able to handle the Text inputs in flutter web testing? I was able to do some testing as you mentioned here but when I got to a text input it simply does not work, focus does not do anything neither setting the value, it seems the actual text edit is only created when I click on the input..

thanks!

**Comment by slavap** [comment]
@ricardolb 
focus still works for me, BUT setting value, i.e. value = 'John' is not working anymore! Sounds like a new bug to me.

**Comment by adrian-moisa** [comment]
After a lot of hassle and seing this ticket not progressing I concluded that Cypress is out. There's too much hassle to get it running. I've had a look at https://github.com/leancodepl/patrol and https://github.com/fzyzcjy/flutter_convenient_test. Flutter convenient test seems to attempt to replicate Cypress straight away in Flutter. Initially I got really excited about the repo. However after trying to setup the first sample I noticed all sorts of problems slowing me down to finish a basic setup, including library conflicts. After looking closer at the code frequency graph I see that the repo is not seeing that much change. Doing some more digging I found Patrol, which seems to have far far better support in terms of documentation and commits. However the issue there is that they don't support web for now. I don't get it why so many libs ignore web when so many people are adopting Flutter for web.

**Comment by adrian-moisa** [comment]
I'm closing this ticket. It's clearly not a prio. I guess we are better off using a library that was built for Flutter from ground up. Anything but not the pumpAndSettle thing...

**Comment by bartekpacia** [comment]
Why close? It's common for issues to live around for a long time (or even eternity...)

> I don't get it why so many libs ignore web when so many people are adopting Flutter for web.

It costs a lot time to develop a high-quality library for 2 platforms, let alone all 6 that Flutter supports.

**Comment by slavap** [comment]
@adrian-moisa Please don't close it - this functionality is still needed by many.

@ricardolb 
In Flutter 3.13.6 it is working again, but now it is implemented differently than before!
```js
document.querySelector('flt-glass-pane').shadowRoot.querySelector('flt-semantics-placeholder').click({force: true});

document.querySelector('flt-semantics-host').querySelector('[aria-label="Search"]').click();

document.querySelector('flt-semantics-host').querySelector('[aria-label="First Name *"]').focus();
document.querySelector('flt-semantics-host').querySelector('[aria-label="First Name *"]').value = 'John';
```

**Comment by carlosfarfangalindoNL222** [comment]
@bartekpacia is right. This take lots of time. In meanwhile we can use the integration_test package.

Of course using patrol for web would be super amazing. So please keep pushing you guys at LeanCode!

**Comment by adrian-moisa** [comment]
I've been writing lately quite a few tests in Patrol. I can see it does the job nicely. Plus the maintainers team seems super active and responsive to tickets. There are some things that could be improved but overall I'm super pleased. The most important part is that it hides away the pumpAndSettle. So I'd say don't bother making a fish climb a tree. Use native dedicated tooling. With enough community build up we might see even a test runner resembling Cypress. As for the web only limitation, ain't such a big limitation after all. I've been able to setup a emulator device that has a 1080p resolutin and pixel density. Thus I can test on mobile the GUI as if it is rendered on the web. No difference at all. Plus I made a couple of testing utils that can force the viewport size to resize to tablet or mobile without leaving the emulator. This enables me to test all behaviours in one emulator. So, overall, I'm really happy. No major compormize made.

**Comment by jvv-g39** [comment]
> @adrian-moisa Please don't close it - this functionality is still needed by many.
> 
> @ricardolb In Flutter 3.13.6 it is working again, but now it is implemented differently than before!
> 
> ```js
> document.querySelector('flt-glass-pane').shadowRoot.querySelector('flt-semantics-placeholder').click({force: true});
> 
> document.querySelector('flt-semantics-host').querySelector('[aria-label="Search"]').click();
> 
> document.querySelector('flt-semantics-host').querySelector('[aria-label="First Name *"]').focus();
> document.querySelector('flt-semantics-host').querySelector('[aria-label="First Name *"]').value = 'John';
> ```
> 
> Pay attention that if you enter these commands in browser development tools console, then you have to activate tab with application after sending focus(), then return to console and enter .value =
> 
> **It would be really nice if someone finds how to eliminate or replace focus() to something else, because it is pretty inconvenient and unstable.**

The input field value doesn't show up in form. And `click()` on submit button does nothing. Only thing is that using ` document.querySelector('flt-glass-pane').shadowRoot.querySelector('flt-semantics-placeholder').click({force: true});` shows up the DOM element. But form input and submission doesn't work. I tried with focus and then setting the value, still it doesn't work. Any help on this please.

**Comment by jsloop42** [comment]
> @adrian-moisa Please don't close it - this functionality is still needed by many.
> 
> @ricardolb In Flutter 3.13.6 it is working again, but now it is implemented differently than before!
> 
> ```js
> document.querySelector('flt-glass-pane').shadowRoot.querySelector('flt-semantics-placeholder').click({force: true});
> 
> document.querySelector('flt-semantics-host').querySelector('[aria-label="Search"]').click();
> 
> document.querySelector('flt-semantics-host').querySelector('[aria-label="First Name *"]').focus();
> document.querySelector('flt-semantics-host').querySelector('[aria-label="First Name *"]').value = 'John';
> ```
> 
> Pay attention that if you enter these commands in browser development tools console, then you have to activate tab with application after sending focus(), then return to console and enter .value =
> 
> **It would be really nice if someone finds how to eliminate or replace focus() to something else, because it is pretty inconvenient and unstable.**

The input field value doesn't show up in form. And `click()` on submit button does nothing. Only thing is that using ` document.querySelector('flt-glass-pane').shadowRoot.querySelector('flt-semantics-placeholder').click({force: true});` shows up the DOM element. But form input and submission doesn't work. I tried with focus and then setting the value, still it doesn't work. Any help on this please.

**Comment by mdebbar** [comment]
We are soon going to make [Semantics.identifier](https://api.flutter.dev/flutter/semantics/SemanticsProperties/identifier.html) useful for DOM lookup. You'll be able to do something like this in your app:
```dart
Semantics(
  identifier: 'my-test-id',
  child: ...
)
```
and then, you can lookup the DOM element by doing:
```javascript
cy.get('[semantics-identifier="my-test-id"]')
```
Does this help with your use case?

**Comment by slavap** [comment]
@mdebbar @yjbanov 
And how this identifier: 'my-test-id' will be working in case of canvaskit renderer?
Currently
document.querySelector('flt-semantics-host').querySelector('[aria-label="Search"]').click();
**works for both html and canvaskit renderers**.

OR do you mean that my-test-id will be available through flt-semantics-host ?

**Comment by adrian-moisa** [comment]
@mdebbar I've long given up on Cypress for flutter and moved away to another testing library. I'm using Patrol and I'm satisfied enough to not consider ditching it. Would have been nice to benefit from a mature framework like Cypress but Patrol works as is and is good enough. Also it's confusing, I see that there are plans to removed the html renderer. I don't see how Cypress would work at all in that case.

**Comment by mdebbar** [comment]
> And how this identifier: 'my-test-id' will be working in case of canvaskit renderer?

Semantics work the same way in both the html or canvaskit renderer.

> Also it's confusing, I see that there are plans to removed the html renderer. I don't see how Cypress would work at all in that case.

If you are relying on semantics, they will continue to work the same way with the canvaskit renderer. The semantics system is independent from the renderer you use.

**Comment by ricardolb** [comment]
> > And how this identifier: 'my-test-id' will be working in case of canvaskit renderer?
> 
> Semantics work the same way in both the html or canvaskit renderer.
> 
> > Also it's confusing, I see that there are plans to removed the html renderer. I don't see how Cypress would work at all in that case.
> 
> If you are relying on semantics, they will continue to work the same way with the canvaskit renderer. The semantics system is independent from the renderer you use.

is there anyway we can test this already? I see this has been merged now
