### ISSUE TITLE
TODO workflow improvement idea

### ISSUE THREAD

**Issue by roman-petrov** [flutter/flutter#97470]
## Use case

There is a [flutter_style_todos](https://dart-lang.github.io/linter/lints/flutter_style_todos.html) rule and as I understand, it is designed to help with `TODO` comment audit. This comment style is used in Flutter code base.

## Proposal

I just have an idea which might improve `TODO` audit workflow. Instead of using `TODO(user-name)` comment as the linter rule suggests we may use `TODO(issue-labels)` comment, for example:

- `TODO(blocked)` -  The issue is blocked on third-party code or team
- `TODO(performance)` - Performance issue
- `TODO(tools)` -Tooling related issue
- `TODO(platform-web-performance)` - Web platform performance issue
- `TODO(easy-ux)` - Easy user experience related issue
- `TODO(code-smell)` - Code that needs refactoring

This is just a workflow idea which I started to use in my projects. Please feel free to if you think that it will not make Flutter workflow more effective.

**Comment by darshankawar** [comment]
Actually I found an original issue describing same case: https://github.com/flutter/flutter/issues/37519, so please follow-up in it for further updates.
Closing this as a duplicate.
