### ISSUE TITLE
Reconsidering allowing developers to download just the Android SDK tools

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#9747]
So I'm installing Flutter for Windows, watching the 1.8GB download chug along. And I'm wondering "why do I need the entire Android Studio? I just need the SDK". So I go to https://developer.android.com/studio/index.html and at the bottom are the links for just the CLI tools. At just 132MB. And I really want to download only those.

![capture3](https://cloud.githubusercontent.com/assets/5479/25648590/6736c61a-2f82-11e7-99a4-4af0bb209e0f.PNG)

I remember at one point it was hard to download just the SDK. But, now that these links are on the page that we direct users to anyway (and, other than being below the fold, don't seem to be hidden), I wonder if we can revisit our policy, and support our users that only need to download the SDK?

**Comment by abarth** [comment]
Sure, we can revisit it.  We might need SDK+gradle.

**Comment by sethladd** [comment]
Great! Thanks :) Also, my hard drive thanks you.

cc @mit-mit can you queue this up to take a look?

**Comment by Hixie** [comment]
We used to only need the SDK, but we moved to also needing Gradle, which is why we tell people to get the whole studio thing.

Ideally we'd automatically download the relevant parts (SDK, gradle, whatever) and not have to show the user anything at all (except maybe the EULA prompt if relevant).

**Comment by sethladd** [comment]
I'm hopefully there's a way to download gradle without the Studio.

**Comment by mit-mit** [comment]
There is: Gradle wrapper.

I'm all for this, but think we should go one step further and vend our own
Android SDK into /bin/cache.

**Comment by Hixie** [comment]
Yes, that would be ideal. SDK and Gradle and everything we need. :-)

**Comment by trekkerghost** [comment]
@sethladd I had the same question. I really didn't want to have two IDE's 
So I went and installed the android command line tools, used `sdkmanager` to install `platforms;android-25`, `build-tools;25.0.3`, installed `gradle-3-5` from its website and ran `flutter doctor` to to finish installing the Flutter SDK and related tools.
Created a sample project using the IntelliJ idea and run it. It just worked.

**Comment by zoechi** [comment]
Related to #9401

**Comment by iapicca** [comment]
Hi @sethladd  is this issue still meant to be open?

**Comment by christopherfujino** [comment]
Closing this as we no longer require Android Studio.
