### ISSUE TITLE
[webview_flutter] Gestures stop working in iOS13

### ISSUE THREAD

**Issue by jsleishen** [flutter/flutter#97475]
I'm having trouble responding to gestures when I load some web pages using webview_flutter
After the webpage is loaded successfully, and then click once, then the gesture operation can no longer be performed, whether it is click or drag.
Even affects flutter_widget click events.
These events only happen in the iOS13 series.

When I use native flutter, the above problem is not reproduced.

**Comment by darshankawar** [comment]
@jsleishen 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without any 3rd party plugins, that shows the behavior you are reporting ?
