### ISSUE TITLE
Allow to set minSdkVersion,compileSdkVersion,targetSdkVersion via local.properties

### ISSUE THREAD

**Issue by Antoniossss** [flutter/flutter#97481]
I had to change minSdkVersion to 21 and was struggling to do that. After googling around and failed to find robust way of doing it without hardcoding it into build.grande, this is what I have end up with

in app\build.gradle
```

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

flutter.minSdkVersion = Integer.parseInt(localProperties.getProperty("flutter.minSdkVersion", flutter.minSdkVersion.toString()));
flutter.compileSdkVersion = Integer.parseInt(localProperties.getProperty("flutter.compileSdkVersion", flutter.compileSdkVersion.toString()));
flutter.targetSdkVersion = Integer.parseInt(localProperties.getProperty("flutter.targetSdkVersion", flutter.targetSdkVersion.toString()));

android {
    compileSdkVersion flutter.compileSdkVersion

```

so this allows to simply override static values with content of local.properties. This could be alternatively placed in FlutterExtensions

**Comment by danagbemava-nc** [comment]
Hi @Antoniossss, looks like there's a similar issue in https://github.com/flutter/flutter/issues/95533 and there's already a PR in flight that is attempting to solve it in https://github.com/flutter/flutter/pull/95684. 

You may follow up in either of those for more information. 

Closing from here as duplicate. 

Thank you
