### ISSUE TITLE
Is Android Setup really optional for Windows developers?

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#9748]
Using Flutter on Windows pretty much means only for/with Android, yes?

That is, are there cases where someone would download Flutter SDK onto their windows machine, and not need/want to install Android (before doing anything useful, that is) ?

We currently have this line: "This step is optional, and can be performed at any time before using Flutter to develop apps for Android." but I'm curious, is it really optional? Don't I need to install Android SDK before using Flutter SDK on Windows? https://flutter.io/setup-windows/

(On the Mac page, it's kind of optional, so I understand why that line existed over there.)

**Comment by abarth** [comment]
That's right.
