### ISSUE TITLE
(Android) Doesn't load images from gallery when launch mode is in singleInstance

### ISSUE THREAD

**Issue by yarn-rp** [flutter/flutter#97486]
Hi there. Congrats for this excellent plugin, it has been a most have in all of my project. However, I have encountered an issue in Android devices when your declare in your main activity android:launchMode="singleInstance" instead of singleTop like the default config. Images from the default files app have no problems, however, if you switch to your gallery app, then images are not loaded after selection. ImagePicker.pickImage() just returns null. 

## Steps to Reproduce
Just go to your android/app/src/main/AndroidManifest.xml and change the lauchmode options. Should be something like this:
``` xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
   ...
   <application
        ...
        <activity
          android:name="com.yalantis.ucrop.UCropActivity"
          android:screenOrientation="portrait"
          android:theme="@style/Theme.AppCompat.Light.NoActionBar"
        />
        <activity
            android:name=".MainActivity"
            android:launchMode="singleInstance"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
```
Would be great to give some alternative to this feature...maybe it's something that we must include in the activity and I'm missing.

**Comment by danagbemava-nc** [comment]
Hi @yarn-rp, it looks like there's a similar issue already open describing what you're experiencing in https://github.com/flutter/flutter/issues/76856. It looks like it's not just an issue with the gallery, picking from google photos doesn't work either.

Kindly follow up there for more information. 

Closing from here as duplicate. 

Thank you
