### ISSUE TITLE
Bug: PictureRecorder does not generate images correctly using Canvas.

### ISSUE THREAD

**Issue by satochibi** [flutter/flutter#97491]
## Conclusion

- [Problem 1] When using PictureRecoder to generate an image using Canvas, the image is not generated correctly. In many environments, the x = 0 part of the image is not drawn.
- [Problem 2] ImageShader is not functioning properly on Android.
- [Problem 3] On Windows and android, when drawing using canvas.drawImage(), depending on the window size, the image may not be displayed correctly and a 1px copy of the image may be drawn.

## What I want to do

What I want to do is to express screen tones like a cartoon.
To make that happen, I'm going to use PictureRecorder to generate a screen tone image.
For the triangle Path, I set the screen tones in the ImageShader of the Paint class shader and observed how it looked.
I also used canvas.drawImage() to display the screen tone image in the center of the screen to see if the screen tone image was generated correctly.

In order to determine whether it is a bug in PictureRecorder or Canvas, I conducted the following experiments on iOS, Andoird, Windows(Win32), and macOS.
- [Experiment 1] Generate and draw an image from PictureRecoder
- [Experiment 2] Prepare a screen tone image (img/screentone.png) in advance and draw it.

## Environment

iOS, Android, and MacOS are built on my MacBook Air (2017).
<details>
<summary>Execution result of flutter doctor (macOS)</summary>

```
% flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.63.2)
[✓] Connected device (3 available)
```
</details>

For the Windows environment only, I have built and run Win32 applications in Visual Studio 2022.
<details>
<summary>Execution result of flutter doctor (Windows)</summary>

```console
flutter doctor 
Doctor summary (to see all details, run flutter doctor -v): 
[√] Flutter (Channel master, 2.10.0-1.0.pre.295, on Microsoft Windows 
    [Version 10.0.19043.1466], locale ja-JP) 
[√] Android toolchain - develop for Android devices (Android SDK version 
    32.0.0) 
[√] Chrome - develop for the web 
[√] Visual Studio - develop for Windows (Visual Studio Community 2022       
    17.0.5) 
[√] Android Studio (version 2020.3) 
[√] VS Code (version 1.63.2) 
[√] Connected device (3 available) 
[√] HTTP Host Availability
```
</details>

<details>
<summary>Code for [Experiment 1] (main.dart)</summary>

```dart
import 'package:flutter/material.dart';
import 'dart:ui' as ui;

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: const Text('PictureRecorder Test'),
        ),
        body: SizedBox(
          width: double.infinity,
          height: double.infinity,
          child: FutureBuilder(
            future: getPattern(),
            builder: (BuildContext context, AsyncSnapshot<ui.Image> snapshot) {
              return CustomPaint(
                painter: _SamplePainter(snapshot.data),
              );
            },
          ),
        ),
      ),
    );
  }
}

Future<ui.Image> getPattern() async {
  var pictureRecorder = ui.PictureRecorder();
  Canvas patternCanvas = Canvas(pictureRecorder);

  const colorList = [
    Colors.black,
    Color(0xffff7f7f),
    Color(0xffff7fff),
    Color(0xff7f7fff),
    Color(0xff7fbfff),
    Color(0xff7fffff),
    Color(0xff7fff7f),
    Color(0xffffff7f),
    Color(0xffffbf7f)
  ];

  final paintList = colorList
      .map((e) => Paint()
        ..color = e
        ..strokeWidth = 1
        ..style = PaintingStyle.stroke
        ..strokeJoin = StrokeJoin.round
        ..isAntiAlias = false)
      .toList();

  paintList.asMap().forEach((index, element) => patternCanvas.drawPoints(
      ui.PointMode.points, [Offset(index % 3, index / 3)], paintList[index]));

  final aPatternPicture = pictureRecorder.endRecording();

  return aPatternPicture.toImage(3, 3);
}

class _SamplePainter extends CustomPainter {
  final ui.Image? aPattern;

  _SamplePainter(this.aPattern);

  @override
  void paint(Canvas canvas, Size size) {
    if (aPattern != null) {
      final paint = Paint()
        ..strokeCap = StrokeCap.round
        ..style = PaintingStyle.stroke
        ..strokeWidth = 10
        ..isAntiAlias = false
        ..shader = ImageShader(aPattern!, TileMode.repeated, TileMode.repeated,
            Matrix4.identity().storage);

      var path = Path();
      path.moveTo(size.width / 2, size.height / 5);
      path.lineTo(size.width / 4, size.height / 5 * 4);
      path.lineTo(size.width / 4 * 3, size.height / 5 * 4);
      path.close();

      canvas.drawPath(path, paint);

      //Depending on the environment, the Offset(0, 0) point of the pattern is not displayed.
      canvas.drawImage(
          aPattern!, Offset(size.width / 2, size.height / 2), Paint());
    }
  }

  @override
  bool shouldRepaint(_SamplePainter oldDelegate) {
    return aPattern != oldDelegate.aPattern;
  }
}
```
</details>

<details>
<summary>Code for [Experiment 2] (main.dart)</summary>

```dart
import 'package:flutter/material.dart';
import 'dart:ui' as ui;

import 'dart:typed_data';
import 'package:flutter/services.dart';
import 'dart:async';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: const Text('PictureRecorder Test'),
        ),
        body: SizedBox(
          width: double.infinity,
          height: double.infinity,
          child: FutureBuilder(
            future: getPattern(),
            builder: (BuildContext context, AsyncSnapshot<ui.Image> snapshot) {
              return CustomPaint(
                painter: _SamplePainter(snapshot.data),
              );
            },
          ),
        ),
      ),
    );
  }
}

Future<ui.Image> getPattern() async {
  final ByteData data = await rootBundle.load("img/screentone.png");
  final Completer<ui.Image> completer = Completer();
  ui.decodeImageFromList(Uint8List.view(data.buffer), (ui.Image img) {
    return completer.complete(img);
  });
  return completer.future;
}

class _SamplePainter extends CustomPainter {
  final ui.Image? aPattern;

  _SamplePainter(this.aPattern);

  @override
  void paint(Canvas canvas, Size size) {
    if (aPattern != null) {
      final paint = Paint()
        ..strokeCap = StrokeCap.round
        ..style = PaintingStyle.stroke
        ..strokeWidth = 10
        ..isAntiAlias = false
        ..shader = ImageShader(aPattern!, TileMode.repeated, TileMode.repeated,
            Matrix4.identity().storage);

      var path = Path();
      path.moveTo(size.width / 2, size.height / 5);
      path.lineTo(size.width / 4, size.height / 5 * 4);
      path.lineTo(size.width / 4 * 3, size.height / 5 * 4);
      path.close();

      canvas.drawPath(path, paint);

      //Depending on the environment, the Offset(0, 0) point of the pattern is not displayed.
      canvas.drawImage(
          aPattern!, Offset(size.width / 2, size.height / 2), Paint());
    }
  }

  @override
  bool shouldRepaint(_SamplePainter oldDelegate) {
    return aPattern != oldDelegate.aPattern;
  }
}
```

</details>

### Screen tone image(img/screentone.png) used in [Experiment 2] (actually, 3x3pixel)
![screentone](https://user-images.githubusercontent.com/11977015/151690903-f86be83a-1a7f-4322-83e8-8a9bd0191e15.png)
The x=0 area refers to the black, blue, and green pixels in this image.

## Steps to Reproduce
1. Execute `flutter run` on the code sample

**Expected results:**
The screen tones should display correctly on any device.

**Actual results:**
The results are summarized below.

### MacBook Air (2017)

[Experiment 1] Generate and draw an image from PictureRecoder           
[Experiment 2] Prepare and draw a screen tone image in advance.

Experiment1 Result: Normal |Experiment 2 Result: Normal
:-------------------------:|:-------------------------:
![MacBookAir](https://user-images.githubusercontent.com/11977015/151690977-8323f20c-e01d-4bb8-9e5f-88bc974060f3.png) | ![スクリーンショット 2022-01-30 14 04 10](https://user-images.githubusercontent.com/11977015/151691001-0ed061d7-ba8d-4907-84ff-20180ec621c0.png)

### iPhone SE Gen2

[Experiment 1] Generate and draw an image from PictureRecoder Result: Point with x = 0 is not drawn.            |  [Experiment 2] Prepare and draw a screen tone image in advance.
:-------------------------:|:-------------------------:
![iPhoneSE2](https://user-images.githubusercontent.com/11977015/151691025-a3934945-2f83-4673-b094-d2069ca18661.PNG) | ![IMG_3594](https://user-images.githubusercontent.com/11977015/151691035-8e60562a-f697-4993-82b2-cb4a212d4e66.PNG)

#### [Experiment 1] Generate and draw an image from PictureRecoder

Experiment 1 Result: The point at x = 0 is not drawn.
**Also, the screen tone of the triangle path is not drawn correctly.**
Ideally, a 9x9 screen tone should be placed, but depending on the position, it may be 8x9 or 8x8.

#### [Experiment 2] Prepare and draw a screen tone image in advance.

Experiment 2 Result: The drawImage is not drawn correctly.
**The triangle path's screen tone is also not drawn correctly.**
Ideally, a 9x9 screen tone should be placed, but depending on the position, it is either 8x9 or 8x8.

Experiment 1 Result             |  Experiment 2 Result
:-------------------------:|:-------------------------:
![](https://user-images.githubusercontent.com/11977015/151691091-ee41847d-bf81-4a2a-bfab-902cc2f36499.png)  | ![](https://user-images.githubusercontent.com/11977015/151691122-890ee99a-02e9-43e1-91d7-5ef425ac5306.png)

#### [Experiment 1] Generate and draw an image from PictureRecoder
Result: The point at x = 0 is not drawn.
(In drawImage, the copy is drawn translucently, depending on the window size.)

#### [Experiment 2] Prepare and draw a screen tone image in advance.
Result: Normal in ImageShader.
(In drawImage, a copy is drawn translucently depending on the window size.)
(This may be a bug in canvas.drawImage() on Windows 10.)

Experiment 1 Result             |  Experiment 2 Result
:-------------------------:|:-------------------------:
![windows10](https://user-images.githubusercontent.com/11977015/151691206-3cc30904-a902-4e36-ab42-81e09ad32d1c.png) |  ![スクリーンショット 2022-01-30 141933](https://user-images.githubusercontent.com/11977015/151691232-fe40d505-8ead-4676-b29e-ac807b9c362d.png)

**Comment by satochibi** [comment]
In order to draw with 1px of physics, [I referred to this post](https://github.com/flutter/flutter/issues/32115#issuecomment-573334481).
When I did that, for some reason, it started to work correctly, except on Windows.

<details>
<summary>Code for [Experiment 1] (main.dart)</summary>

```
import 'package:flutter/material.dart';
import 'dart:ui' as ui;

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: const Text('PictureRecorder Test'),
        ),
        body: SizedBox(
          width: double.infinity,
          height: double.infinity,
          child: FutureBuilder(
            future: getPattern(),
            builder: (BuildContext context, AsyncSnapshot<ui.Image> snapshot) {
              return FakeDevicePixelRatio(
                fakeDevicePixelRatio: 1.0,
                child: CustomPaint(
                  painter: _SamplePainter(snapshot.data),
                ),
              );
            },
          ),
        ),
      ),
    );
  }
}

Future<ui.Image> getPattern() async {
  var pictureRecorder = ui.PictureRecorder();
  Canvas patternCanvas = Canvas(pictureRecorder);

  const colorList = [
    Colors.black,
    Color(0xffff7f7f),
    Color(0xffff7fff),
    Color(0xff7f7fff),
    Color(0xff7fbfff),
    Color(0xff7fffff),
    Color(0xff7fff7f),
    Color(0xffffff7f),
    Color(0xffffbf7f)
  ];

  final paintList = colorList
      .map((e) => Paint()
        ..color = e
        ..strokeWidth = 1
        ..style = PaintingStyle.stroke
        ..strokeJoin = StrokeJoin.round
        ..isAntiAlias = false)
      .toList();

  paintList.asMap().forEach((index, element) => patternCanvas.drawPoints(
      ui.PointMode.points, [Offset(index % 3, index / 3)], paintList[index]));

  final aPatternPicture = pictureRecorder.endRecording();

  return aPatternPicture.toImage(3, 3);
}

// https://stackoverflow.com/questions/70866283/custompainter-drawimage-throws-an-exception-object-has-been-disposed
// https://stackoverflow.com/questions/52752298/how-to-draw-different-pattern-in-flutter
class _SamplePainter extends CustomPainter {
  final ui.Image? aPattern;

  _SamplePainter(this.aPattern);

  @override
  void paint(Canvas canvas, Size size) {
    if (aPattern != null) {
      final paint = Paint()
        ..strokeCap = StrokeCap.round
        ..style = PaintingStyle.stroke
        ..strokeWidth = 10
        ..isAntiAlias = false
        ..shader = ImageShader(aPattern!, TileMode.repeated, TileMode.repeated,
            Matrix4.identity().storage);

      var path = Path();
      path.moveTo(size.width / 2, size.height / 5);
      path.lineTo(size.width / 4, size.height / 5 * 4);
      path.lineTo(size.width / 4 * 3, size.height / 5 * 4);
      path.close();

      canvas.drawPath(path, paint);

      //Depending on the environment, the Offset(0, 0) point of the pattern is not displayed.
      canvas.drawImage(
          aPattern!, Offset(size.width / 2, size.height / 2), Paint());
    }
  }

  @override
  bool shouldRepaint(_SamplePainter oldDelegate) {
    return aPattern != oldDelegate.aPattern;
  }
}

class FakeDevicePixelRatio extends StatelessWidget {
  final num fakeDevicePixelRatio;
  final Widget child;

  const FakeDevicePixelRatio(
      {Key? key, required this.fakeDevicePixelRatio, required this.child})
      : super(key: key);

  @override
  Widget build(BuildContext context) {
    final devicePixelRatio =
        WidgetsBinding.instance?.window.devicePixelRatio ?? 1;

    final ratio = fakeDevicePixelRatio / devicePixelRatio;

    return FractionallySizedBox(
        widthFactor: 1 / ratio,
        heightFactor: 1 / ratio,
        child: Transform.scale(scale: ratio, child: child));
  }
}

```
</details>




<details>
<summary>Code for [Experiment 2] (main.dart)</summary>

```
import 'package:flutter/material.dart';
import 'dart:ui' as ui;

import 'dart:typed_data';
import 'package:flutter/services.dart';
import 'dart:async';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: const Text('PictureRecorder Test'),
        ),
        body: SizedBox(
          width: double.infinity,
          height: double.infinity,
          child: FutureBuilder(
            future: getPattern(),
            builder: (BuildContext context, AsyncSnapshot<ui.Image> snapshot) {
              return FakeDevicePixelRatio(
                fakeDevicePixelRatio: 1.0,
                child: CustomPaint(
                  painter: _SamplePainter(snapshot.data),
                ),
              );
            },
          ),
        ),
      ),
    );
  }
}

Future<ui.Image> getPattern() async {
  final ByteData data = await rootBundle.load("img/screentone.png");
  final Completer<ui.Image> completer = Completer();
  ui.decodeImageFromList(Uint8List.view(data.buffer), (ui.Image img) {
    return completer.complete(img);
  });
  return completer.future;
}

// https://stackoverflow.com/questions/70866283/custompainter-drawimage-throws-an-exception-object-has-been-disposed
// https://stackoverflow.com/questions/52752298/how-to-draw-different-pattern-in-flutter
class _SamplePainter extends CustomPainter {
  final ui.Image? aPattern;

  _SamplePainter(this.aPattern);

  @override
  void paint(Canvas canvas, Size size) {
    if (aPattern != null) {
      final paint = Paint()
        ..strokeCap = StrokeCap.round
        ..style = PaintingStyle.stroke
        ..strokeWidth = 10
        ..isAntiAlias = false
        ..shader = ImageShader(aPattern!, TileMode.repeated, TileMode.repeated,
            Matrix4.identity().storage);

      var path = Path();
      path.moveTo(size.width / 2, size.height / 5);
      path.lineTo(size.width / 4, size.height / 5 * 4);
      path.lineTo(size.width / 4 * 3, size.height / 5 * 4);
      path.close();

      canvas.drawPath(path, paint);

      //Depending on the environment, the Offset(0, 0) point of the pattern is not displayed.
      canvas.drawImage(
          aPattern!, Offset(size.width / 2, size.height / 2), Paint());
    }
  }

  @override
  bool shouldRepaint(_SamplePainter oldDelegate) {
    return aPattern != oldDelegate.aPattern;
  }
}

class FakeDevicePixelRatio extends StatelessWidget {
  final num fakeDevicePixelRatio;
  final Widget child;

  const FakeDevicePixelRatio(
      {Key? key, required this.fakeDevicePixelRatio, required this.child})
      : super(key: key);

  @override
  Widget build(BuildContext context) {
    final devicePixelRatio =
        WidgetsBinding.instance?.window.devicePixelRatio ?? 1;

    final ratio = fakeDevicePixelRatio / devicePixelRatio;

    return FractionallySizedBox(
        widthFactor: 1 / ratio,
        heightFactor: 1 / ratio,
        child: Transform.scale(scale: ratio, child: child));
  }
}

```
</details>


## Experimental results
### MacBook Air (2017)
#### [Experiment 1] Generate and draw an image from PictureRecoder
Result: Normal


#### [Experiment 2] Prepare and draw a screen tone image in advance.
Result: Normal

### iPhone Simulator
#### [Experiment 1] Generate and draw an image from PictureRecoder
Result: Normal

#### [Experiment 2] Prepare and draw a screen tone image in advance.
Result: Normal

### Android(Emulator)
#### [Experiment 1] Generate and draw an image from PictureRecoder
Result: Normal

#### [Experiment 2] Prepare and draw a screen tone image in advance.
Result: Normal


### Windows 10 (Win32 application)
#### [Experiment 1] Generate and draw an image from PictureRecoder
Result: The point at x = 0 is not drawn.
![windows_test](https://user-images.githubusercontent.com/11977015/151741043-4988bc17-86f4-441f-a9ac-945938f2751d.png)

#### [Experiment 2] Prepare and draw a screen tone image in advance.
Result: Normal in ImageShader.
![windows_test_img](https://user-images.githubusercontent.com/11977015/151741035-75fe8d94-69bf-4de7-8ca8-11e3b5ac376c.png)

**Comment by maheshmnj** [comment]
Hi @satochibi, Thanks for filing the issue. I believe these three issues should be filed separately for better tracking. Could you please update the issue description with a single issue and file the rest of the two issues separately?
Also, please reference this issue in the newly filed issue.

**Comment by satochibi** [comment]
Thank you very much. However, I would like to discuss [Problem 1] only.
Apparently, when I run it on a high-definition display, the origin of the image acquisition created by PictureRecorder is not (0, 0), but (1, 0).
![screentone](https://user-images.githubusercontent.com/11977015/152627601-e35ad0db-81ff-42e7-9131-e4827283d3c7.png)

**Comment by maheshmnj** [comment]
Thanks for the info @satochibi, If I understand it right when you normally draw on the canvas, its properly drawn but when drawing the image created with PictureRecorder the image is shifted to 1 pixel on the right is that correct?
If so, How are you verifying that the image is shifted with both the outputs?

Could you please share a sample image used in the above reproducible could sample?

Thanks
