### ISSUE TITLE
Can add a start flag to show the layout border , like android

### ISSUE THREAD

**Issue by tain335** [flutter/flutter#975]

**Comment by eseidelGoogle** [comment]
There are lots of debug flags for the rendering system:
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/debug.dart

@devoncarew is in the process of exposing many of these in the flutter Atom plugin.

Can you tell me what the Android flag is?  It's possible we could/should respect it anyway?

**Comment by devoncarew** [comment]
Yup, the debugger from atom can toggle drawing rectangles around the widgets:

<img width="308" alt="screen shot 2015-12-17 at 9 31 20 am" src="https://cloud.githubusercontent.com/assets/1269969/11877026/a222c02a-a4a1-11e5-85fc-e880640c09b2.png">

![screen](https://cloud.githubusercontent.com/assets/1269969/11877013/946be3bc-a4a1-11e5-9c07-b005986bf629.png)

Those options will change and evolve as we figure out which flags are the best things to expose to end users.

**Comment by tain335** [comment]
Surprised! What plugin should install, I cannot find this tool bar in my atom editor. I haved install dart-lang plugin @0.5.0

**Comment by tain335** [comment]
Yeah,I found, but paddings and margins can use some color to display

**Comment by eseidelGoogle** [comment]
We don't have a specific debug flag for Padding or Margins, since they're just Widgets which know how to draw their children.  We certainly could add some code to RenderPadding to do such, i'm not sure if that's general-case enough for debug.dart. @Hixie?

**Comment by Hixie** [comment]
Padding and margin already do. They just display boxes like any other box. Happy to add more, just let me know what you think it should look like. (Probably in a new bug, one per thing you want.)

**Comment by Hixie** [comment]
Adding something for padding. See https://github.com/flutter/flutter/pull/1158.
