### ISSUE TITLE
Mic beep Sound or Sound of single Application Flutter

### ISSUE THREAD

**Issue by Bisharat62** [flutter/flutter#97513]
Can we Close All sounds of single application that will not effect other apps sound or general sound , or

i am working on voice recognition app , is there any solution to close mic beep sound , because i have to take repeatedly input from user and beep sound of mic start and stop is distrubing  
Thanks in advance

**Comment by darshankawar** [comment]
@Bisharat62 
Your question is better suited for support channels like StackOverflow, so please ask the same there.
Closing from here.
