### ISSUE TITLE
The APK failed to install, Error: Could not parsing error string 

### ISSUE THREAD

**Issue by vadivelvanavil** [flutter/flutter#97511]
I'm getting this error when install apk file in **Google Pixel6** mobile. 
**The APK failed to install, Error: Could not parsing error string** 
It needs to resolve in release apk file (flutter build apk -- release) not architecture apk file(arm,x86,x32)

This error i'm getting in Google Pixel 6 model mobile phone.
![Screenshot_10](https://user-images.githubusercontent.com/41718803/151749069-dfd085f4-81cc-4b59-9dc7-9e05baface0e.jpg)

**Comment by yash-chudasama** [comment]
Hi @vadivelvanavil, I think device is running Android 12. For app to run on Android 12, exported attribute must explicitly be defined in AndroidManifest.xml.

Just add "exported" attribute in activity tag in AndroidManifest.xml

Read this :
https://developer.android.com/about/versions/12/behavior-changes-12

**Comment by darshankawar** [comment]
@vadivelvanavil 
Check above solution and see if it helps to resolve the issue.

**Comment by vadivelvanavil** [comment]
> @vadivelvanavil Check above solution and see if it helps to resolve the issue.

Thanks for reply. It not helps to resolve my issue. 
Error: **"There was problem parsing a package"**

**Comment by darshankawar** [comment]
@vadivelvanavil 
Check below links and see if any of them help to resolve:


https://github.com/iBotPeaches/Apktool/issues/2250#issuecomment-579428652
https://github.com/iBotPeaches/Apktool/issues/2250#issuecomment-628408227
https://www.reddit.com/r/Flutter/comments/bxfgoz/flutter_release_apk_is_not_installing_on_device/

**Comment by vadivelvanavil** [comment]
I tried to run hello world application in Google Pixel 6, it doesn't allow to run, i think its google pixels issue.

**Comment by darshankawar** [comment]
Looks like it. You can reach out to google support for pixel phone and see if they would be able to help. https://support.google.com/pixelphone/?hl=en#topic=7078250

Closing from here. If you disagree, write in comments and I'll reopen it.

**Comment by vadivelvanavil** [comment]
Sure. Thanks for the help.
