### ISSUE TITLE
Unable to play URL from Youtube on Flutter Web

### ISSUE THREAD

**Issue by Lingareddyvinitha** [flutter/flutter#97514]
Hi I have tried implementing this video player on my flutter web following the instructions. It works well!

However, when I change the url from the example given to a url from youtube, it does not work, if shows the error:-

Error: PlatformException(MEDIA_ERR_SRC_NOT_SUPPORTED, No further diagnostic information can be determined or provided., The video has been found to be unsuitable (missing or in a format not supported by your browser)., null)

What's the issue?

```
  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.network(
      'https://www.youtube.com/watch?v=NsZ2nwWRH5c',
    );

    _controller.addListener(() {
      setState(() {});
    });
    _controller.setLooping(true);
    _controller.initialize().then((value) => _controller.play());
  }
  ```

**Comment by danagbemava-nc** [comment]
Hi @Lingareddyvinitha, thanks for filing the issue. 

Please provide the output of `flutter doctor -v` as well as `flutter run -v` that shows the error you're getting along with a complete minimal reproducible code sample. 

Also, what version of `video_player` are you using? 

Thank you

**Comment by hardik-kumbhani** [comment]
Hi @Lingareddyvinitha, You can't pass youtube link inside a video_player cause It'll only support direct video url like .mp4, .mov and etc.
`Example : https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4`

If you want to pass youtube link or respected v address to player then use `https://pub.dev/packages/youtube_player_flutter`

**Comment by stuartmorgan** [comment]
HTML isn't a video format, so this is expected behavior.

**Comment by Lingareddyvinitha** [comment]
Cann't we give youtube links to the video_player

**Comment by stuartmorgan** [comment]
No. You need to provide the URL to a video. A web page is not a video.

**Comment by Lingareddyvinitha** [comment]
> No. You need to provide the URL to a video. A web page is not a video.

![image](https://user-images.githubusercontent.com/47639732/151920358-93464f9a-dbd6-44dd-a830-c4b48bda2b12.png)

**Comment by hardik-kumbhani** [comment]
@Lingareddyvinitha, It's not a url gentleman when you open that url in browser then it will see it'll render webpage of youtube.

**Comment by Lingareddyvinitha** [comment]
okay, thank you
