### ISSUE TITLE
[image_picker][iOS]: download image from Gallery while Cellular Data is disabled

### ISSUE THREAD

**Issue by AndrewPiterov** [flutter/flutter#97515]
I work with `image_picker`, through which I select my photos from the `Photo Gallery`. Everything is OK with WiFi. But as soon as I go to Cellular mobile internet and turn off `Cellular Data` for `Photo`, I can't select a photo anymore. See error below. I would understand that because of the lack of synchronization over the mobile Internet, `image_picker` cannot request a picture from `Photo`. But how then do Instagram and Facebook Messenger work, are they all ok even with `Cellular Data` is disabled for `Photo`?

I call:

```dart
final image = await _picker.pickImage(source: ImageSource.gallery);
```

And I get when Cellular Data is disabled:

```bash
[default] [ERROR] Could not create a bookmark: NSError: Cocoa 257 "The file couldn’t be opened because you don’t have permission to view it." }
[claims] Upload preparation for claim 470C6865-2ABB-4F78-90B2-3D0BB2498BA3 completed with error: Error Domain=NSCocoaErrorDomain Code=260 "The file “version=1&uuid=102A95B5-AEE6-4E80-B326-7416748CB402&mode=compatible.jpeg” couldn’t be opened because there is no such file." UserInfo={NSURL=file:///private/var/mobile/Containers/Shared/AppGroup/15270B29-2CDA-4770-B0CC-408083D37A7B/File%20Provider%20Storage/photospicker/version=1&uuid=102A95B5-AEE6-4E80-B326-7416748CB402&mode=compatible.jpeg, NSFilePath=/private/var/mobile/Containers/Shared/AppGroup/15270B29-2CDA-4770-B0CC-408083D37A7B/File Provider Storage/photospicker/version=1&uuid=102A95B5-AEE6-4E80-B326-7416748CB402&mode=compatible.jpeg, NSUnderlyingError=0x2809a5dd0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
```

![2022-01-31 12 52 29](https://user-images.githubusercontent.com/10525569/151781225-547b1af4-dcac-4974-b1cc-7591ec0c2e23.jpg)

Thanks a lot!

**Comment by KristijanMitrik** [comment]
I am having the same issue
