### ISSUE TITLE
Flutter doesn't consistently reach 120 fps on macOS

### ISSUE THREAD

**Issue by KevinBrendel** [flutter/flutter#97530]
Similar to https://github.com/flutter/flutter/issues/90675, support 120 hz / ProMotion on the macOS platform.

EDIT: Flutter does appear to support 120 fps on macOS, but doesn't consistently reach it. See https://github.com/flutter/flutter/issues/97530#issuecomment-1028590690.

**Comment by darshankawar** [comment]
@KevinBrendel 
Can you please elaborate on the issue by providing a code sample ? Is there a current limitation that you are facing specific to macOS ?

**Comment by KevinBrendel** [comment]
@darshankawar 
I must admit that upon further investigation, the issue appears to be slightly different than I originally thought. Flutter does in fact appear to support 120 hz on macOS, but it appears to be nearly impossible to actually reach it. 

In my [minimal example project](https://github.com/KevinBrendel/smoothness_test), (running on the current stable release on an M1 Max with 32 GPU cores), the Flutter profiler shows performance well above 120 fps with no dropped frames:

<img width="821" alt="Flutter Profiler 2" src="https://user-images.githubusercontent.com/55455206/152279801-18849662-e457-4b0e-a6da-9b932a9ccec1.png">

<img width="1728" alt="Flutter Profiler" src="https://user-images.githubusercontent.com/55455206/152279843-f3955cc5-0cbc-416c-a2aa-382e70a79e86.png">

But visually, the performance is much lower and extremely inconsistent, with large amounts of stuttering resulting from large variations in frame-times. This can be confirmed by profiling the app using Xcode with the Game Performance template. This also confirms that some of the frames do in fact render within the 8.33 ms required to achieve 120 fps.

<img width="1782" alt="Xcode Profiler" src="https://user-images.githubusercontent.com/55455206/152280193-2ccbe164-82f1-40a2-a0aa-4a2396736ad1.png">

There appear to be some serious performance issues in the macOS implementation of Flutter that are not caught by the Flutter profiler. Colleagues confirmed that the performance issue also appears on Intel Macs. This same app runs smoothly on iPadOS.
The issue is not limited to animations, as I originally encountered it in a real project in a SingleChildScrollView as well as when manually handling scroll events.

**Comment by darshankawar** [comment]
@KevinBrendel 
Thanks for the details. Can you check if [this](https://github.com/flutter/flutter/issues/49757) issue is similar to your use case ?

**Comment by KevinBrendel** [comment]
@darshankawar 
It is definitely related to my issue. Running the linked code from that issue on the ProMotion display also only results in a 60 fps output in the Flutter code. (Although both the Flutter and Xcode profilers once again report much higher frame-rates.)
I am not sure if supporting higher frame-rates is the whole story, though, as I even experience dropped frames on 60 hz displays (although much less often than on 120 hz displays).

I don't know enough about the inner workings of Flutter, but it seems to me that the frames delivered by Flutter are not in sync with the frames delivered by the native application into which Flutter is embedded, resulting in the frame-rate mismatch and in the stutters (I have a hard time believing that these are actually performance issues).

**Comment by darshankawar** [comment]
Thanks for further details. I think following up in the linked issue : https://github.com/flutter/flutter/issues/49757 would help to better track your observation. You can also share your findings in that issue.
I am going ahead and closing this in favor of https://github.com/flutter/flutter/issues/49757. If you disagree, write in comments and I'll reopen it.
