### ISSUE TITLE
[plugin][examples] Add `flutter_lints` to the example and fix lint issues

### ISSUE THREAD

**Issue by TahaTesser** [flutter/flutter#97532]
This is not noticeable when cloning plugins repo but when the examples are copied to tested in a regular Flutter projects. 
The code contains lot of lint issues which should be updated to be tested in Flutter projects without updating the code or manually fixing the lint issues.

### Examples
- [x] `google_maps_flutter` -  https://github.com/flutter/plugins/pull/4716
- [ ] `webview_flutter` - 

and more...

**Comment by stuartmorgan** [comment]
Adding custom analysis settings in flutter/plugins is a non-goal. Closing in favor of https://github.com/flutter/flutter/issues/76229 which is the right way to fix lint issues in general.
