### ISSUE TITLE
Engine roll failed on 3h VS install timeout

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#97535]
In the Engine -> Framework roll here https://github.com/flutter/flutter/pull/97517, on "Windows tool_integration_tests_4_6", the infra step "Install VS build" timed out.

The 3h timeout seems like it might be too long:

https://ci.chromium.org/ui/p/flutter/builders/try/Windows%20tool_integration_tests_4_6/240/overview

P3 for now, and I will monitor the next roll attempt and escalate as needed.

**Comment by keyonghan** [comment]
This happened twice on 01/28: https://ci.chromium.org/ui/p/flutter/builders/try/Windows%20tool_integration_tests_4_6/200/overview
https://ci.chromium.org/ui/p/flutter/builders/try/Windows%20tool_integration_tests_4_6/195/overview

Hasn't hit the issue in these days. Will keep monitoring for a while, either close or move to technical debt if no more timeout.

**Comment by godofredoc** [comment]
Closing for now, if this continues to happen we'll need to pre populate in a bundle rather than installing directly from the network.
