### ISSUE TITLE
[flutter_conductor] ensure macOS arm Dart sdk is codesigned

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#97536]
before Flutter can distribute a macOS ARM Dart SDK, it must be codesigned and notarized.

**Comment by jmagman** [comment]
Part of https://github.com/flutter/flutter/issues/86926

**Comment by zanderso** [comment]
@christopherfujino Could you give a pointer into the conductor code that has the signing logic that needs to be modified?

**Comment by christopherfujino** [comment]
> @christopherfujino Could you give a pointer into the conductor code that has the signing logic that needs to be modified?

I've got a change ready, I just need to locally test it.

**Comment by christopherfujino** [comment]
The script is updated and I verified it on the commit: https://github.com/flutter/engine/tree/b0e6fe8e8006414b6a2c8f71ae4af8b1cb03dde4.
