### ISSUE TITLE
Give a Dart CI account access to trigger builds on engine staging

### ISSUE THREAD

**Issue by whesse** [flutter/flutter#97541]
We want a new Dart CI Luci builder to trigger the iOS profile engine build on staging with tip-of-tree Dart SDK commits and engine commits.  The Dart recipe for this builder is working already if run locally, but our CI builders run with a service account, that needs to be given buildbucket access.

The load, on a single staging builder (we think iOS profile engine is the best, to get build errors early and to upload engines that we can run benchmarks on), would be comparable to the existing engine builds, but we can work with Flutter to throttle it if necessary.
We are triggering the ios engine staging builder that uses the engine_v2 recipes, and just passing in the dart_sdk_rev as a gclient custom var property.  We will also pass in an archive property that uploads the builds to CAS, but that is not necessary at first.

We don't currently have separate service accounts for the try runs and the postsubmit (CI) runs - they run in the same pool, and our production runs that build releases run in a separate pool with different accounts.  If you have a tryjob / postsubmit job separation of service accounts that you want to maintain, we can work on this with you.

Discussion of this plan can happen on this issue or on the Dart/Flutter engprod mailing list, if you want.
The service account that needs permission to start buildbucket builds in the staging pool is shown in the error message:

Message: "user:dart-luci-try-builder@dart-ci.iam.gserviceaccount.com" does not have permission "buildbucket.builds.add" in bucket "flutter/staging"

Builds that we trigger on this builder appear without a commit reference, like builds 1391 and 1392 on https://luci-milo.appspot.com/p/flutter/builders/staging/Mac%20mac_ios_engine_profile , but we could also pass in a commit hash, in which case they would be indistinguishable from the existing builds with a pinned SDK.  Methods we have mentioned before, like build properties, tags, or a separate builder, could be used so the different builds aren't mixed together on the same console.

@athomas @godofredoc

**Comment by godofredoc** [comment]
Added the service account to `project-flutter-staging-schedulers` please let me know if it works.

**Comment by whesse** [comment]
Great, that seems to have worked - I did a led run of our builder, and it has triggered run https://ci.chromium.org/ui/p/flutter/builders/staging/Mac%20mac_ios_engine_profile/1414/overview
of the ios engine_v2 staging builder.  Further discussion of this new builder can happen on other channels, closing the issue.

**Comment by keyonghan** [comment]
@whesse How often this builder will be triggered from dart side? Would like to understand how this may affect existing queue time in staging, as we have some flaky tests that need validation in the staging pool.

**Comment by whesse** [comment]
We would like to trigger this on every Dart commit and every engine commit, but will start by just running it once daily.
We can find other ways of limiting it - the default scheduler will not schedule a next build until the existing one completes, so we would be limited to one build per (pending time + 15 minutes).
We could also exclude some engine commits (like just rolls of Dart or something else), and some Dart commits.
So we will start by just running one build per day (which isn't that useful, since Dart rolls in the engine more often than that)

**Comment by whesse** [comment]
I have now corrected the recipe, at https://dart-review.googlesource.com/c/recipes/+/231140, and a successful ios engine_v2 build triggered by this recipe is at https://ci.chromium.org/ui/p/flutter/builders/staging/Mac%20mac_ios_engine_profile/1430/overview

**Comment by keyonghan** [comment]
> So we will start by just running one build per day (which isn't that useful, since Dart rolls in the engine more often than that)

Once a day now should not affect much. Thanks for the info!

**Comment by whesse** [comment]
The builder will be added by https://dart-review.googlesource.com/c/sdk/+/232083

**Comment by whesse** [comment]
We would like to switch to our less open account, dart-luci-ci-builder@dart-ci.iam.gserviceaccount.com, that only
runs production builds, rather than that account dart-luci-try-builder@dart-ci.iam.gserviceaccount.com that runs all the try jobs and CI jobs. That seems to give better control over what builds can be triggered.

Please add the ci-builder account and remove the try-builder account.
Thanks.

**Comment by godofredoc** [comment]
Done!
