### ISSUE TITLE
Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libamsupport.dylib (0x203913130) and     /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x103bc02c8). One of the two will be used. Which one is undefined.

### ISSUE THREAD

**Issue by Jai05-techie** [flutter/flutter#97566]
Hi am facing an issue while running flutter project in MacBook Air M1 chip Lap. Tried all possibility couldn't find where is the exact problem.

All basic solutions like `flutter clean, flutter pub get, pod deintegrate & install, flutter build ios, flutter run` but still same issue. only on simulator not deploying.

Any solution for this. Thanks in advance.

**Error**

```
Launching lib/main.dart on iPhone 13 in debug mode...
Running pod install...                                              5.3s
Running Xcode build...                                                  
Xcode build done.                                           104.1s
Failed to build iOS app
Error output from Xcode build:
↳
    objc[25282]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libamsupport.dylib (0x203913130) and
    /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x103bc02c8). One of the two will be used. Which one is undefined.
    objc[25282]: Class AMSupportURLSession is implemented in both /usr/lib/libamsupport.dylib (0x203913180) and
    /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x103bc0318). One of the two will be used. Which one is undefined.
    ** BUILD FAILED **
```

**flutter doctor -v**

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.0.1 21A559 darwin-arm, locale
    en-IN)
    • Flutter version 2.8.1 at
      /Users/macsystem/Documents/developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (7 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/macsystem/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (2 available)
    • iPhone 13 (mobile) • 05EC9698-3C26-44B9-8DB0-B53C7B6576F3 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 97.0.4692.99
```

**Comment by darshankawar** [comment]
@Jai05-techie 
The error you are getting `Class AMSupportURLConnectionDelegate is implemented in both` is actually a warning from Xcode but it may not be the reason why your build is failing.

Can you provide `flutter run --verbose` which contains the error ? The log will be huge so you can put it in a text file and share it here.

Also, check [this](https://stackoverflow.com/a/69387639) similar SO issue link and see if it helps to resolve your error.

**Comment by liangjianqi** [comment]
hi,i have the same problem

Flutter 2.10.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision db747aa133 (3 days ago) • 2022-02-09 13:57:35 -0600
Engine • revision ab46186b24
Tools • Dart 2.16.1 • DevTools 2.9.2

**Comment by nagringapp** [comment]
Hi @darshankawar ,

The author didn't reply, but I'm facing exaclty the same issue:

When I run `flutter build ios  --release --flavor=prod` it runs fine, with no issue, but when I run `flutter build ipa  --release --flavor=prod` to send to Apple Store I get the same problem.

I'm on a MacBook Pro M1 MAX. find below the details:

`➜  app git:(dev) ✗ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.2, on macOS 12.0.1 21A559 darwin-arm, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.64.1)
[✓] Connected device (4 available)
[error - build ipa.txt](https://github.com/flutter/flutter/files/8102327/error.-.build.ipa.txt)

    ! Error: Caco’s iPhone 11 Pro is not connected. Xcode will continue when Caco’s iPhone 11 Pro is connected. (code -13)
[✓] HTTP Host Availability

• No issues found!`

Find attached the output from the command `flutter build ipa  --release --flavor=prod --verbose`

**Comment by cacothi** [comment]
Hi @darshankawar ,

The author didn't reply, but I'm facing exaclty the same issue:

When I run `flutter build ios  --release --flavor=prod` it runs fine, with no issue, but when I run `flutter build ipa  --release --flavor=prod` to send to Apple Store I get the same problem.

I'm on a MacBook Pro M1 MAX. find below the details:

`➜  app git:(dev) ✗ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.2, on macOS 12.0.1 21A559 darwin-arm, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.64.1)
[✓] Connected device (4 available)


    ! Error: Caco’s iPhone 11 Pro is not connected. Xcode will continue when Caco’s iPhone 11 Pro is connected. (code -13)
[✓] HTTP Host Availability

• No issues found!`

Find attached the output from the command `flutter build ipa  --release --flavor=prod --verbose` 
[error - build ipa.txt](https://github.com/flutter/flutter/files/8102328/error.-.build.ipa.txt)

**Comment by cacothi** [comment]
@darshankawar any position on this issue ?

**Comment by cacothi** [comment]
Hi Guys, I've found the issue in my code. The problem was on the Podfile

Before:
`

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

end

target 'ImageNotification' do
  use_frameworks!

  pod 'Firebase/Messaging'
  pod 'GoogleUtilities'

end

`

after (fixed)

`

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  pod 'GoogleUtilities'

end

target 'ImageNotification' do
  use_frameworks!

  pod 'Firebase/Messaging'
  pod 'GoogleUtilities'

end

`

Thanks

**Comment by Jai05-techie** [comment]
Hi all, i've done complete clean and install by below steps and it helped me to solve,

**_Step 1:_**

```
flutter clean
rm -Rf ios/Pods
rm -Rf ios/.symlinks
rm -Rf ios/Flutter/Flutter.framework
rm -Rf ios/Flutter/Flutter.podspec
rm ios/Podfile
```

**_Step 2:_**

```
cd ios
flutter pub get
pod cache clean --all
pod install

    or  (below for m1 chip incase above command thrown error in pod install)

#1 Install ffi
sudo arch -x86_64 gem install ffi

#2 Re-install dependencies
arch -x86_64 pod install

```
**_Step 3:_**

```
1. Open ios/Pods/Pods.xcodeproj in Xcode
2. Change the iOS Deployment info from 8.0 to 9.0
```
**_Step 4:_**

`From XCODE clean / build again / run. Hope this should work. Before please confirm whether all the build settings for iOS configured properly or not.`

**Note: In those above steps i faced one more issue from Firebase like "firebase import not found". Below added steps how i solved.**

**_Step 1:_** `open ios/Podfile`

`Check platform :ios, '10.0' is uncommented
`
**_Step 2:_**

add below code at end of Podfile

```
target 'CustomImageNotifications' do
  use_frameworks!
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
end 
```

**_Step 3:_** `pod install & open XCODE and clean / build.`

**_Hoping this answer may helps.! thanks_**

**Comment by darshankawar** [comment]
Closing this as resolved.
