### ISSUE TITLE
App crashes upon launch on iOS 14.7 and 14.8

### ISSUE THREAD

**Issue by Fnalsk** [flutter/flutter#97567]
## Steps to Reproduce

run this app:

https://apps.apple.com/app/id1605784768

and try to launch it

**Expected results:** 

App launches and user sees login screen

**Actual results:** 

App crashes immediately

This is difficult to test because Apple does not provide simulators for 14.7 and 14.8 - and hence I can't even do a `flutter run` to reproduce the crash. The app works fine on every other device that has been tested. I'm not even sure how I would reproduce this due to the lack of a simulator. I would go to the apple store and just buy a physical device, but then it'd be on iOS 15...

Given that I can't really know where the bug is and I don't have a minimal code sample, I'm not even sure someone can help. I do, however, have an error log reported by a user. I'm hoping the log looks like something someone has seen before and I get some direction on how to proceed.

<details>

<summary>Code sample</summary>

</details>

<details>
  <summary>Logs</summary>

```

{"app_name":"Runner","timestamp":"2022-01-30 23:09:44.00 +0000","app_version":"1.1.0","slice_uuid":"fc00a9f7-80c3-3bc4-80b1-f1d9dc824d31","adam_id":1605784768,"build_version":"24","platform":0,"bundleID":"app.pidgeon.pidgeon","share_with_app_devs":0,"is_first_party":0,"bug_type":"109","os_version":"iPhone OS 14.8 (18H17)","incident_id":"D3630127-83DF-4BBE-A2A4-C115225F57FC","name":"Runner"}
Incident Identifier: D3630127-83DF-4BBE-A2A4-C115225F57FC
CrashReporter Key:   9adac7d78f8dca4b20ae952f668be67069bd2e48
Hardware Model:      iPhone9,3
Process:             Runner [1129]
Path:                /private/var/containers/Bundle/Application/58E46D21-FA1E-4D8F-8A17-3673F71BCA10/Runner.app/Runner
Identifier:          app.pidgeon.pidgeon
Version:             24 (1.1.0)
AppStoreTools:       13C90b
AppVariant:          1:iPhone9,3:13
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           app.pidgeon.pidgeon [700]


Date/Time:           2022-01-30 23:09:43.7520 +0000
Launch Time:         2022-01-30 23:09:43.6888 +0000
OS Version:          iPhone OS 14.8 (18H17)
Release Type:        User
Baseband Version:    5.04.00
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Description: DYLD, dyld: Using shared cache: 2BEC66E4-84D4-3C6E-919C-830A676FA8AE | dependent dylib '@rpath/flutter_keyboard_visibility.framework/flutter_keyboard_visibility' not found for '/private/var/containers/Bundle/Application/58E46D21-FA1E-4D8F-8A17-3673F71BCA10/Runner.app/Runner'. chained fixups, seg_count exceeds number of segments
Highlighted by Thread:  0

Backtrace not available

Unknown thread crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000001   x2: 0x000000016f5a2000   x3: 0x00000000000000bf
    x4: 0x000000016f5a1c00   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0x0000000000000020   x9: 0x0000000000000009  x10: 0x666f207265626d75  x11: 0x746e656d67657320
   x12: 0x63786520746e756f  x13: 0x6d756e2073646565  x14: 0x7320666f20726562  x15: 0x0073746e656d6765
   x16: 0x0000000000000209  x17: 0x0000000000000091  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x000000016f5a1c00  x21: 0x00000000000000bf  x22: 0x000000016f5a2000  x23: 0x0000000000000001
   x24: 0x0000000000000006  x25: 0x000000016f5a28c8  x26: 0x0000000100c5c000  x27: 0x000000016f5a38b0
   x28: 0x000000016f5a3934   fp: 0x000000016f5a1bd0   lr: 0x0000000100c423a4
    sp: 0x000000016f5a1b90   pc: 0x0000000100c3ab64 cpsr: 0x00000000
   esr: 0x00000000  Address size fault

Binary images description not available



Error Formulating Crash Report:
Failed to create CSSymbolicatorRef - corpse still valid ¯\_(ツ)_/¯

EOF

```
</details>

**Comment by darshankawar** [comment]
@Fnalsk 
I installed the app on my iPhone 6s (OS 14.4.1) and it didn't launch for me as you mentioned.
Looking at the error log you shared, it points to:

`flutter_keyboard_visibility.framework/flutter_keyboard_visibility' not found for '/private/var/containers/Bundle/Application/58E46D21-FA1E-4D8F-8A17-3673F71BCA10/Runner.app/Runner'. chained fixups, seg_count exceeds number of segments`

It seems there's an issue using `flutter_keyboard_visibility` pod. Do you get any error if you open your xcworkspace in Xcode and it points to above pod not found ?

There's not much details to properly analyze the issue, so I suggest you to look at the code implementation specially at the code when you launch the app and see if you could find a pattern that leads to the error.

**Comment by Fnalsk** [comment]
It turned out to be an issue with the pods, as mentioned. Deleting the podfile and podfile.lock and rebuilding the app fixed it.
