### ISSUE TITLE
Gallery demo: Tapping Discard on iOS alert dialog prints "OK" in toast

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#9757]
We probably don't want to say "You tapped: OK" when you actually tapped on "Discard" :)

**Comment by sethladd** [comment]
Confirmed on Android and iOS. Not sure if this is specific to the gallery, or all the uses of the dialog.

cc @xster

**Comment by Skylled** [comment]
It looks like the demo in Gallery just pops the dialog and passes a string to the snackbar. Simple typo.
#9764 One line fix.

**Comment by sethladd** [comment]
Thanks @Skylled !
