### ISSUE TITLE
Wrong error output on iOS with paired Apple Watch

### ISSUE THREAD

**Issue by glebosotov** [flutter/flutter#97574]
## Steps to Reproduce

1. Connect a new device to the Mac or update the iOS/WatchOS
2. Try to run a flutter app

## Actual error
```
[        ]     xcodebuild: error: Unable to find a destination matching the provided destination specifier:
                        { id:******** }
           
                The requested device could not be found because no available devices matched the request.
           
                Available destinations for the "Runner" scheme:
                        { platform:iOS Simulator, id:********, OS:15.2, name:iPad mini (6th generation) }
                        { platform:iOS Simulator, id:********, OS:15.2, name:iPhone 11 }
                        { platform:iOS Simulator, id:********, OS:15.2, name:iPhone 13 Pro Max }
                        { platform:iOS Simulator, id:********, OS:15.2, name:iPhone 13 mini }
           
                Ineligible destinations for the "Runner" scheme:
                        { platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
                        { platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
                        { platform:iOS, id:********, name:Gleb’s  iPhone 11, error:Device is busy (Preparing the watch for development via Gleb’s  iPhone
11) }
......
[   +4 ms] 
           Building a deployable iOS app requires a selected Development Team with a 
           Provisioning Profile. Please ensure that a Development Team is selected by:
             1- Open the Flutter project's Xcode target with
                  open ios/Runner.xcworkspace
             2- Select the 'Runner' project in the navigator then the 'Runner' target
                in the project settings
             3- Make sure a 'Development Team' is selected under Signing & Capabilities > Team. 
                You may need to:
                    - Log in with your Apple ID in Xcode first
                    - Ensure you have a valid unique Bundle ID
                    - Register your device with your Apple Developer Account
                    - Let Xcode automatically provision a profile for your app
             4- Build or run your project again
           
           For more information, please visit:
             https://flutter.dev/docs/get-started/install/macos#deploy-to-ios-devices
           
           Or run on an iOS simulator without code signing
           
[   +1 ms] Error launching application on Gleb’s  iPhone 11.
```

## Expected outcome
```
error:Device is busy (Preparing the watch for development via Gleb’s  iPhone
11)

```
## Doctor
❯ flutter doctor -v
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.2 21D49 darwin-x64, locale en-US)
    • Flutter version 2.8.1 at /usr/local/Caskroom/flutter/2.8.1/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (7 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (3 available)
    • Gleb’s  iPhone 11 (mobile) •***           • ios            • iOS 15.4 19E5209h
    • iPhone 11 (mobile)          • *** • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 97.0.4692.99
    ! Error: Gleb’s  iPhone 11 is busy: Preparing the watch for development via Gleb’s  iPhone 11. Xcode will continue when Gleb’s  iPhone 11 is finished. (code
      -10)

! Doctor found issues in 2 categories.

## Note that doctor shows that the device is busy

**Comment by maheshmnj** [comment]
Hi @glebosotov, Thanks for filing the issue. This is a xcode bug, there have been similar reports  for this issue #95609 and #95117, Please see this comment https://github.com/flutter/flutter/issues/95117#issuecomment-995094721.

Additionally, you may refer [this comment](https://github.com/flutter/flutter/issues/95609#issuecomment-998707944) and see if it helps resolves the issue. 

Closing as its issue isn't related to flutter.
