### ISSUE TITLE
[google_maps_flutter] Adding label field to the marker 

### ISSUE THREAD

**Issue by jeffmilanes** [flutter/flutter#97577]
Hi, 

Can label be added to the `Marker` 

```
const Marker({
    required this.markerId,
    this.alpha = 1.0,
    this.anchor = const Offset(0.5, 1.0),
    this.consumeTapEvents = false,
    this.draggable = false,
    this.flat = false,
    this.icon = BitmapDescriptor.defaultMarker,
    this.infoWindow = InfoWindow.noText,
    this.position = const LatLng(0.0, 0.0),
    this.rotation = 0.0,
    this.visible = true,
    this.zIndex = 0.0,
    this.onTap,
    this.onDrag,
    this.onDragStart,
    this.onDragEnd,
  }) : assert(alpha == null || (0.0 <= alpha && alpha <= 1.0));
```

It seems that this is available in the google maps documentation

https://developers.google.com/maps/documentation/javascript/examples/marker-labels

**Comment by maheshmnj** [comment]
Hi @jeffmilanes, Adding text label to marker is not supported as of today, This feature request is being tracked here https://github.com/flutter/flutter/issues/26109. Please follow up there for further updates.

Closing this issue as a duplicate
