### ISSUE TITLE
Flutter project is not running on Chrome without internet connection

### ISSUE THREAD

**Issue by ombudev** [flutter/flutter#97579]
Flutter project is not running on Chrome without internet connection:

$ flutter run
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             40.8s
This app is linked to the debug service:
ws://127.0.0.1:39961/TfbzDLP3R7k=/ws
Debug service listening on ws://127.0.0.1:39961/TfbzDLP3R7k=/ws

💪 Running with sound null safety 💪

🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".

An Observatory debugger and profiler on Chrome is available at:
http://127.0.0.1:39961/TfbzDLP3R7k=

Performing hot restart...                                          298ms
Restarted application in 300ms.

**Comment by maheshmnj** [comment]
Hi @ombudev, Thanks for filing the issue. Offline support for web is currently not supported, There is a open feature request being tracked here #60069 Please follow up on the linked issue for further updates. Closing this issue as a duplicate.
Same as https://github.com/flutter/flutter/issues/94264 (closed).
