### ISSUE TITLE
[scheduler] Cocoon is missing webhook for created pull request

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#97587]
See https://github.com/flutter/engine/pull/31181

[The logs](https://cloudlogging.app.goo.gl/eXKKawokgNJnficR6) do not show any entries for the created. We can see some other checkruns that were created were processed (which is a different event).

TODO: Investigate why this pull request wasn't processed by Cocoon

**Comment by keyonghan** [comment]
Found the [log](https://pantheon.corp.google.com/logs/viewer?project=flutter-dashboard&organizationId=433637338589&resource=gae_app%2Fmodule_id%2Fdefault%2Fversion_id%2Fversion-f93c8a8&minLogLevel=0&expandAll=false&timestamp=2022-02-04T18:00:42.470000000Z&customFacets=&limitCustomFacetWidth=false&interval=NO_LIMIT&logName=projects%2Fflutter-dashboard%2Flogs%2Fappengine.googleapis.com%252Fstdout&logName=projects%2Fflutter-dashboard%2Flogs%2Fappengine.googleapis.com%252Fstderr&logName=projects%2Fflutter-dashboard%2Flogs%2Fappengine.googleapis.com%252Fnginx.request&logName=projects%2Fflutter-dashboard%2Flogs%2Fappengine.googleapis.com%252Frequest_log&scrollTimestamp=2022-02-01T11:17:53.917000000Z&advancedFilter=resource.type%3D%22gae_app%22%0Aresource.labels.project_id%3D%22flutter-dashboard%22%0Aresource.labels.version_id%3D%22version-f93c8a8%22%0Aresource.labels.module_id%3D%22default%22%0Aresource.labels.zone%3D%22us-central1-c%22%0Atimestamp%3D%222022-02-01T11:17:53.917000000Z%22%0AinsertId%3D%22184j75ag2i0rrs8%22) for webhook of this pr, and seems okay. @CaseyHillers is it something wrong from scheduling try builders side?

**Comment by CaseyHillers** [comment]
> Found the [log](https://pantheon.corp.google.com/logs/viewer?project=flutter-dashboard&organizationId=433637338589&resource=gae_app%2Fmodule_id%2Fdefault%2Fversion_id%2Fversion-f93c8a8&minLogLevel=0&expandAll=false&timestamp=2022-02-04T18:00:42.470000000Z&customFacets=&limitCustomFacetWidth=false&interval=NO_LIMIT&logName=projects%2Fflutter-dashboard%2Flogs%2Fappengine.googleapis.com%252Fstdout&logName=projects%2Fflutter-dashboard%2Flogs%2Fappengine.googleapis.com%252Fstderr&logName=projects%2Fflutter-dashboard%2Flogs%2Fappengine.googleapis.com%252Fnginx.request&logName=projects%2Fflutter-dashboard%2Flogs%2Fappengine.googleapis.com%252Frequest_log&scrollTimestamp=2022-02-01T11:17:53.917000000Z&advancedFilter=resource.type%3D%22gae_app%22%0Aresource.labels.project_id%3D%22flutter-dashboard%22%0Aresource.labels.version_id%3D%22version-f93c8a8%22%0Aresource.labels.module_id%3D%22default%22%0Aresource.labels.zone%3D%22us-central1-c%22%0Atimestamp%3D%222022-02-01T11:17:53.917000000Z%22%0AinsertId%3D%22184j75ag2i0rrs8%22) for webhook of this pr, and seems okay. @CaseyHillers is it something wrong from scheduling try builders side?

Contents of the log:
```
Processing check_run
```

We're looking for `Processing pull_request`. Instead, it looks like Cirrus received a webhook, but our app didn't.

**Comment by godofredoc** [comment]
Has this happened again or was a one off?

**Comment by keyonghan** [comment]
Seems a one-off. Please reopen if it happens again.
