### ISSUE TITLE
[url_launcher] app:minifyReleaseWithProguard

### ISSUE THREAD

**Issue by ABDULKARIMALBAIK** [flutter/flutter#97591]
*Hi everyone*
My android app is working fine in debug mode , but when i run app in release mode with proguard feature, throw exception :

**Exception :**
>FAILURE: Build failed with an exception.
What went wrong:
Execution failed for task ':app:minifyReleaseWithProguard'.
> java.io.IOException: Can't write [D:\ ...............\build\app\intermediates\shrunk_jar\release\minified.jar] (Can't read [D:\ ........\ ..........\.pub-cache\hosted\pub.dartlang.org\url_launcher_windows-2.0.2\android\build\intermediates\runtime_library_classes_jar\release\classes.jar(;;;;;;;**.class)] (Duplicate jar entry [io/flutter/plugins/urllauncher/BuildConfig.class]))
Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
Get more help at https://help.gradle.org

**Comment by danagbemava-nc** [comment]
Hi @ABDULKARIMALBAIK, thanks for filing the issue. 

Please provide the following information 

- output of `flutter doctor -v`
- output of `flutter build apk/appbundle -v` [The output may be huge so kindly put it into a .txt file and attach it here]
- your proguard config
- android/app/build.gradle
- your pubspec.yaml and pubspec.lock

Thank you

**Comment by ABDULKARIMALBAIK** [comment]
Hi flutter team
I fixed this error , I just removed android folder in url_launcher_windows
package

Please create pull request and fix the error

**Comment by danagbemava-nc** [comment]
> I fixed this error , I just removed android folder in url_launcher_windows

That doesn't seem right, the `url_launcher_windows` should not contain an android folder. 

Can you provide us with steps to reproduce so that we know the cause and how to fix it?

Thank you
