### ISSUE TITLE
[cocoon] Surface test flakiness in build dashboard

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#97597]
Currently test flakiness is only tracked by the flaky issue bot. Instead, it should be surfaceable in the build dashboard to match the flaky issue bot stats.

This would require adding test_flakiness to the task.proto in dashboard, and updating `TaskBox` to show the exclamation mark when task flakiness is true.

**Comment by CaseyHillers** [comment]
\cc @keyonghan

**Comment by keyonghan** [comment]
Thanks Casey.
Actually the `bringup: false` test flakiness has been surfaced. The missing part is the staging test flakiness triggered from test step (staging test flakiness triggered from task rerun has been surfaced as well).

**Comment by godofredoc** [comment]
@keyonghan should we close this one?

**Comment by keyonghan** [comment]
The test step flakiness for staging targets is still missing.

**Comment by keyonghan** [comment]
https://flutter-review.googlesource.com/c/infra/+/46240 to add alert template. Here is the new notification for a test flake build:

-------------
**Test flake in Engine on builder "flutter/staging/Windows Unopt"**

Builder "flutter/staging/Windows Unopt" flaked at 2023-06-20 23:47:42.991348474 +0000 UTC on step(s) "test: Host Tests for host_debug_unopt".

[Full details are available here.](https://ci.chromium.org/b/8777728767145772529)

Created at:	2023-06-20 23:09:00.600838836 +0000 UTC
Finished at:	2023-06-20 23:47:42.991348474 +0000 UTC
