### ISSUE TITLE
scorecards-analysis GitHub action should not run on forks

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#97599]
Running and failing and notifying me on my fork:
https://github.com/jmagman/flutter/actions/runs/1780628765

flutter/flutter and the [engine](https://github.com/flutter/engine/blob/main/.github/workflows/scorecards-analysis.yml) needs a `github.repository` check like:
https://github.com/flutter/flutter/blob/d010a85476db096cb06c566b151aa7498341a8c0/.github/workflows/no-response.yaml#L20

See also https://github.com/flutter/flutter/issues/87573
https://github.com/flutter/flutter/pull/88058
https://github.com/flutter/flutter/pull/87601

/cc @godofredoc

**Comment by jmagman** [comment]
The engine also needs the same. 
https://github.com/flutter/engine/blob/main/.github/workflows/scorecards-analysis.yml

**Comment by keyonghan** [comment]
@godofredoc Seems fixed. Could we close this bug?

**Comment by jmagman** [comment]
Still seeing this in cocoon.
https://github.com/jmagman/cocoon/actions/runs/2104814314
