### ISSUE TITLE
Install instructions mess up PATH on Windows

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#9759]
https://flutter.io/setup-windows/#clone-the-repo currently recommends to add flutter to the `PATH` with the following command:

```batch
setx PATH "%PATH%;<cd>\flutter\bin"
```

This is problematic because it messes up the `PATH` in a bad way (and the result differs depending on if the command is executed in PowerShell or CMD):

In CMD, the first `PATH` in the command references to the *user* PATH while the second instance (`%PATH%`) is expanded (by CMD) to the *combination* of user and system PATH. Essentially, this means that the command copies the system PATH into the user PATH and stores system+user PATH in the user PATH variable. This leads to duplication (some values are now present in system and user path) and it is also likely that the new user path will now be larger than the max length for env variables (1024 characters). This causes the PATH to get silently truncated (bad! some values that were in the PATH will get lost!).

In PowerShell it fails in a different way: The first `PATH` in the command still references to the *user* PATH. However, PowerShell does not expand `%PATH%` to anything and just writes the string `%PATH%;<cd>\flutter\bin` verbatim into the user PATH variable overwriting whatever used to be in the user PATH variable. The old values of the user path are lost!

What's the solution?

Unfortunately, there is no easy build-in way to append anything to the user PATH from CMD or PowerShell. Here are our options:

* We could redirect users to the Windows GUI for editing the PATH variable: 
     * Control Panel > User Accounts > User Accounts > Change my environment variables
     * Under "User variables" add a PATH user variable with the full path to `flutter\bin` as value. Or, if a variable with that name already exists, add the full path to `flutter\bin` to it separated by `;`.
* We could provide a script to modify the PATH variable directly in the registry. Example for CMD:
    * `for /f "skip=2 tokens=3*" %a in ('reg query HKCU\Environment /v PATH') do @if [%b]==[] ( @setx PATH "<path to flutter\bin>;%~a" ) else ( @setx PATH "<path to flutter\bin>;%~a %~b" )`
    * scary command
    * only works in CMD, would have to provide alternatives for other shells (e.g. PowerShell, etc)
* We could ask users to modify the PATH for the current session only:
   * in CMD: `set PATH=C:\src\flutter\bin;%PATH%`
   * in PowerShell: `$env:path="C:\sdfsdf sdf\bin;$env:path"`
   * PATH modification is not permanent, lost when current shell window is closed
   * need to provide different commands for different shells

Given that the first option is going to be the only one that will work independent of what shell is used, I'd vote for changing the documentation to that one.

**Comment by goderbauer** [comment]
/cc @LarkAscending FYI

I can work on a PR.

**Comment by eseidelGoogle** [comment]
FYI @mit-mit

**Comment by branflake2267** [comment]
I'll update my video asap.
