### ISSUE TITLE
How use AssetBundle load a Image from assets floader and display with AssetImage?

### ISSUE THREAD

**Issue by tain335** [flutter/flutter#976]
I try many times  but the app crash aways.And no other logs output
![_ _ jp 99_yo_ f qsln57p](https://cloud.githubusercontent.com/assets/5304597/11870365/076105b8-a502-11e5-927e-11bcf361cbb4.png)

**Comment by eseidelGoogle** [comment]
Strange that we don't have an example of this.  https://github.com/flutter/flutter/blob/b7a212f76e6030c614dfb81405f982dcf350973b/packages/flutter/lib/src/material/icon.dart#L73 is the only example I find.  I suspect it's a path question.

I'd try adding print's to the AssetBundle code and make sure the paths are resolving as you expect them to.  We probably should have flutter log in the asset system any time an asset load fails.

You can also just try `print(_bundle.urlForKey('assets/images/avatar.jpg')` and see if its returnign what you expect.

**Comment by eseidelGoogle** [comment]
Assets also need to be listed in `flutter.yaml` in order to get packed into the zip file and bundled with the app.  I don't know that we've documented that anywhere. :/  @abarth

**Comment by eseidelGoogle** [comment]
Actually, I'm wrong.  That's only for material-design-icons.  I'm investigating adding other assets to .flx (flutter's zip format) files now.

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/build.dart#L142 is the command which builds the .flx file.

**Comment by jimbeveridge** [comment]
AssetBundle and flutter.yaml work for non-Material Design projects.  Look at flutter/game.

**Comment by eseidelGoogle** [comment]
I also just added an example of using flutter.yaml assets: in https://github.com/flutter/flutter/issues/976.

We definitely need to make this more user friendly.  We certainly shouldn't crash.

**Comment by Hixie** [comment]
We have detailed docs on how to handle assets now.
