### ISSUE TITLE
[flutter_tools] DartDevelopmentServiceException: JSON-RPC error 100: Feature is disabled

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#97604]
From crash reporting on beta/2.10.0-0.3.pre

```
Thread 0 main threadDartDevelopmentServiceException: DartDevelopmentServiceException: JSON-RPC error 100: Feature is disabled.
at DartDevelopmentServiceImpl._startDDSServer(dds_impl.dart:185)
at <asynchronous gap>(async)
at DartDevelopmentServiceImpl.startService(dds_impl.dart:113)
at <asynchronous gap>(async)
at DartDevelopmentService.startDartDevelopmentService(dds.dart:88)
at <asynchronous gap>(async)
at DebugService.startDartDevelopmentService(debug_service.dart:152)
at <asynchronous gap>(async)
at DevHandler._createAppDebugServices(dev_handler.dart:442)
at <asynchronous gap>(async)
at DevHandler.loadAppServices(dev_handler.dart:229)
at <asynchronous gap>(async)
at Dwds.debugConnection(dwds.dart:91)
at <asynchronous gap>(async)
at WebDevFS.connect.<anonymous closure>(devfs_web.dart:686)
at <asynchronous gap>(async)
```

This gets called from the tool at https://github.com/flutter/flutter/blob/beta/packages/flutter_tools/lib/src/isolated/devfs_web.dart#L686

**Comment by yjbanov** [comment]
cc @annagrin

**Comment by annagrin** [comment]
@christopherfujino what would be the best way to repro this?

/cc @bkonyi - looks like DDS fails to start.

**Comment by bkonyi** [comment]
It looks like we're likely failing when we try and invoke `_yieldControlToDDS`. It'd be worth taking a look at dwds to make sure this is implemented.

**Comment by annagrin** [comment]
@bkonyi it is, in here: https://github.com/dart-lang/webdev/blob/40f826520a3b5ba3ba72f0864572a49410174c88/dwds/lib/src/dwds_vm_client.dart#L120

Not sure what happens in this particular case though, would be great to have a repro.

**Comment by samuelrajasingh** [comment]
facing the same Issue, is there a solution or a workaround for this

**Comment by sebastianmueller** [comment]
Hi, Merry Christmas!
I'm having the same issue with current stable flutter version. Any hints on how to mitigate or workaround this problem?

```
DartDevelopmentServiceException: DartDevelopmentServiceException: JSON-RPC error 100: Feature is disabled.

#0      DartDevelopmentServiceImpl._startDDSServer (package:dds/src/dds_impl.dart:213:7)
<asynchronous suspension>
#1      DartDevelopmentServiceImpl.startService (package:dds/src/dds_impl.dart:116:7)
<asynchronous suspension>
#2      DartDevelopmentService.startDartDevelopmentService (package:dds/dds.dart:97:5)
<asynchronous suspension>
#3      DebugService.startDartDevelopmentService (package:dwds/src/services/debug_service.dart:156:12)
<asynchronous suspension>
#4      DevHandler._createAppDebugServices (package:dwds/src/handlers/dev_handler.dart:468:7)
<asynchronous suspension>
#5      DevHandler.loadAppServices (package:dwds/src/handlers/dev_handler.dart:244:27)
<asynchronous suspension>
#6      Dwds.debugConnection (package:dwds/dwds.dart:91:30)
<asynchronous suspension>
#7      WebDevFS.connect.<anonymous closure> (package:flutter_tools/src/isolated/devfs_web.dart:694:15)
<asynchronous suspension>
```

[✓] Flutter (Channel stable, 3.3.10, on Ubuntu 18.04.6 LTS 4.15.0-156-generic, locale en_US.UTF-8)
    • Flutter version 3.3.10 on channel stable at xxx
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (13 days ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at xxx
    • Platform android-33, build-tools 30.0.3
    • ANDROID_SDK_ROOT = xxx
    • Java binary at: xxx
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✗] Linux toolchain - develop for Linux desktop
    ✗ clang++ is required for Linux development.
      It is likely available from your distribution (e.g.: apt install clang), or can be downloaded from https://releases.llvm.org/
    • cmake version 3.10.2
    ✗ ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded from https://github.com/ninja-build/ninja/releases
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 18.04.6 LTS 4.15.0-156-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 108.0.5359.98

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

```
## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 52b3dc25f6471c27b2144594abb11c741cb88f57
### Plugins
cloud_firestore-4.1.0
cloud_firestore_web-3.1.0
firebase_auth-4.1.3
firebase_auth_web-5.1.3
firebase_core-2.3.0
firebase_core_web-2.0.1
firebase_messaging-14.1.3
firebase_messaging_web-3.2.8
```

**Comment by annagrin** [comment]
@sebastianmueller and previous reporters  - we currently don't have a repro for this issue, would you be able to provide repro steps? I suspect that there might be too many existing vm clients of dwds so dwds fails to yield to DDS, so I wonder what else is running besides `flutter run -d chrome`.

My guess is that the `_yieldControlToDDS` extension method fails in dwds: https://github.com/dart-lang/webdev/blob/490d6a06f7ed75654bcfd5a0e8351f8a0f59df1c/dwds/lib/src/dwds_vm_client.dart#L134

Btw, the `details` needs to be replaced by `data` to show the full message, opened an issue for that: https://github.com/dart-lang/webdev/issues/1860
