### ISSUE TITLE
Hot reload throwing errors/generally not working on valid code changes

### ISSUE THREAD

**Issue by emshack** [flutter/flutter#9761]
@efortuna @collinjackson @eseidel @sethladd 

## Steps to Reproduce
I'm trying to get through my entire app-building workflow only using hot reload to update with changes, rather than ever fully restarting the app. However, I'm having an issue with adding a SizeTransition.

Before:
```
Widget build(BuildContext context) {
    return new Container(...);
}
```

After:
```
Widget build(BuildContext context) {
    return new SizeTransition(
        sizeFactor: new CurvedAnimation(
            parent: message.animationController, curve: Curves.easeOut
         ),
        axisAlignment: 0.0,
        child: new Container(...)
    );
}
```

When I hot reload after this change, I see a red screen where the Container should be. However, when I fully restart the app, it runs as expected.

## Flutter Doctor
[✓] Flutter (on Mac OS X 10.12.4 16E195, channel unknown)
    • Flutter at /Users/emshack/flutter
    • Framework revision acd75c0a3b (2 weeks ago), 2017-04-17 15:35:01 -0700
    • Engine revision c24a0e5175
    • Tools Dart version 1.23.0-dev.11.7

[✓] Host Executable Compatibility
    • Downloaded executables execute on host

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /Users/emshack/Library/Android/sdk
    • Platform android-23, build-tools 23.0.2
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/bin/java
    • Java version: Java(TM) SE Runtime Environment (build 1.8.0_60-b27)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.0

[✗] Android Studio (not installed)
    • Android Studio not found. Download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2016.3.4)
    • Dart plugin version 163.13137
    • Flutter plugin version 12.1

[✓] Connected devices
    • iPhone SE • 04E0234C-AA18-4FA5-9620-23A6D8E21E44 • ios • iOS 10.2 (simulator)

**Comment by Hixie** [comment]
Can you paste the exception you get on the console when doing this?

**Comment by collinjackson** [comment]
We ran into this during the codelab dry run; the issue is that you have some stale ChatMessages in your messages array that lack an `animationController` property. Hot-restarting the app will reset the contents of the array to be empty.

**Comment by sethladd** [comment]
I wonder if there's a way to listen to hot reload events and then register a "empty the array" callback for that "hot reload request" event that comes into the framework?

**Comment by collinjackson** [comment]
Most of the time you don't want to empty the array. That's why you're hot reloading.

Hot-restart is almost exactly as fast and it also empties the array for you.

**Comment by emshack** [comment]
Aha! Thanks so much! This fixed it.

**Comment by Hixie** [comment]
Is there something we should do to make this more intuitive? I didn't quite follow what happened here...

**Comment by emshack** [comment]
This page may need to be fleshed out... it is not immediately apparent to me that my situation fell under any of the three cases listed here that hot reload doesn't cover, as all I modified was a build function.

https://flutter.io/intellij-ide/#hot-reloads-vs-full-application-restarts

**Comment by collinjackson** [comment]
Yeah, it might be helpful to say something about how hot restart is also a good idea if you make changes to the member variables of a State and you want to re-initialize your States to their original configuration.

**Comment by sethladd** [comment]
Filed https://github.com/flutter/flutter/issues/9771
