### ISSUE TITLE
Symbolize stack traces dumped by Fuchsia on the FEMU target

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#97618]
Fuchsia+FEMU is a nontrivial test dependency to setup and maintain for developers, and so at least having symbolized stack traces when segfaults happen on FEMU would save many hours of debugging time.

For example, recurring FEMU segfaults blocked https://github.com/flutter/engine/pull/29391 for days.

**Comment by akbiggs** [comment]
@chandarrengoog Should https://flutter-review.googlesource.com/c/recipes/+/19661 have covered this or is this a separate recipe?

**Comment by bdero** [comment]
I just looked through a bunch of failed FEMU build logs to color this with more details, but there _are_ symbolized traces in the [stdout logs](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8823370770695324145/+/u/FEMU_Test/test:_Run_FEMU_Test_Suite_embedder_tests__3_/syslog). There appears to be a non-symbolized trace in the emulator logs that was tripping me up.

I looked through all of the failed FEMU builds past January 26th and didn't find any counterexamples, so I think they've been there the whole time!
