### ISSUE TITLE
Facing some issue while upgrading gradle from 6.5 to 7.0.2. My android code also contains flutter modules. Issue seems to be due to flutter module.

### ISSUE THREAD

**Issue by shweta30sharma** [flutter/flutter#97625]
Could not resolve all dependencies for configuration ':Android:debugRuntimeClasspath'.
Using insecure protocols with repositories, without explicit opt-in, is unsupported. Switch Maven repository 'maven5(http://download.flutter.io)' to redirect to a secure protocol (like HTTPS) or allow insecure protocols. See https://docs.gradle.org/7.0.2/dsl/org.gradle.api.artifacts.repositories.UrlArtifactRepository.html#org.gradle.api.artifacts.repositories.UrlArtifactRepository:allowInsecureProtocol for more details. 

Did anyone face this issue?

**Comment by darshankawar** [comment]
@shweta30sharma 
I think your question is better suited for support channels like StackOverflow, so please ask the same there.
Closing from here.
See below similar links with solutions and check if they help you to resolve the issue.

https://stackoverflow.com/questions/68585885/allow-insecure-protocols-android-gradle
https://github.com/gradle/gradle/issues/11905
https://exerror.com/using-insecure-protocols-with-repositories-without-explicit-opt-in-is-unsupported-switch-maven-repository/#:~:text=Maven%20repository%20Error%3F-,To%20Solve%20Using%20insecure%20protocols%20with%20repositories%20without%20explicit%20opt,Just%20as%20like%20below.

**Comment by shweta30sharma** [comment]
Okay @darshankawar. Will reach out to stackoverflow community. Also, thanks for the references.
