### ISSUE TITLE
Flutter create's git clone doesn't build ios

### ISSUE THREAD

**Issue by xster** [flutter/flutter#9763]
I think we created a missing edge case with #9464/#9085 for Mac wrt cocoapods

1. Check out flutter 7a57d3719 
2. brew uninstall cocoapods
3. flutter create project A
4. that project builds ok
5. git init, git add ., git ci -am
6. git clone project A into project B
7. try to build ios in project B

That project won't build because the Pod directory generated in project A isn't checked in by default. This creates a problem for team development since the references to Pod in Pod's parent directory is still present and building causes
```
    diff: /../Podfile.lock: No such file or directory
    diff: /Manifest.lock: No such file or directory
    error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
```

Perhaps we should make the `flutter create`'s general dependency on cocoapods reduced until the user needs to use cocoapods.

**Comment by xster** [comment]
cc @mit-mit @jakobr-google @cbracken 

Sorry for messing around cocoapods more. I think we're getting closer and closer though.

Just trying to explicitly list out a few assumed criteria to make the solution finding easier.

- [ ] We don't want source controlled files to keep changing as an effect of building #9085
- [ ] We don't want to force users to get cocoapods to run a blank vanilla project because it's expensive #9580
- [ ] Up until the project has a proper dependency on cocoapods (i.e. uses plugins), teams with members that have cocoapods and that don't have cocoapods should all be able to build using the same checked in code 
- [ ] If a project uses plugins and then stops using them, the checked in project should still work on another computer without cocoapods

To satisfy all of the above, I tentatively propose (please violently scrutinize, I'm not sure I caught all the details)

- [ ] `flutter create` doesn't include any traces of cocoapods. Not in ios/Pods and not ios/Podfile, ios/Podfile.lock, ios/Runner.xcodeproj/project.pbxproj etc either.
- [ ] Let none of the example projects refer to cocoapods unless they actually use plugins
- [ ] Let cocoapods create everything once the user starts plugins
- [ ] Run something like `pod deintegrate` when users remove all plugins

**Comment by cbracken** [comment]
> We don't want source controlled files to keep changing as an effect of building.

One exception I think would be acceptable is when a project changes state from no pod deps to having pod deps, I'd be fine with checking in the additional build phases. Otherwise we end up effectively having to `pod install; buildl; pod deintegrate` on each run.

**Comment by cbracken** [comment]
> `flutter create` doesn't include any traces of cocoapods. Not in ios/Pods and not ios/Podfile, ios/Podfile.lock, ios/Runner.xcodeproj/project.pbxproj etc either. [...] Let none of the example projects refer to cocoapods unless they actually use plugins

I _like_ this from the position of boilerplate reduction. To be clear, I think having the `Pods` and `Frameworks` folders in the `xcworkspace` is probably fine though.

**Comment by cbracken** [comment]
> Run something like pod deintegrate when users remove all plugins

For the base case, this seems really nice. One potential edge-case to consider: are there cases where a user might add CocoaPods without it being specific to a Flutter plugin?

**Comment by mit-mit** [comment]
Yes, hybrid apps. I think even the flutter_view sample does that.

**Comment by cbracken** [comment]
One more point re:
> flutter create doesn't include any traces of cocoapods.

The vast majority of real-world apps will depend on pods, so I don't think our goal should necessarily be to avoid any mention of them in the default project.

If we're going to assume all real-world projects rely on plugins, then it's probably fair to require Cocoapods to be installed for real-world projects. The main reason it'd be really nice to have the default initial project (and some of our examples) not require Cocoapods is to allow people new to the framework to try it out with low overhead and do some quick experimenting without 100s of MB of download first.

I _like_ the idea from the perspective of boilerplate reduction -- which is perhaps a separate bug. On that end of things, I think the requirements are:
* Any file that isn't `.gitignore`d should be meaningful/editable to the developer. Everything else should be generated on the fly and not checked in.
* We shouldn't expect any file that's .gitignored to be present. You should be able to `fluter create` then `git add .`, push to a repo, blow everything away, clone it back and it still works.

**Comment by xster** [comment]
I agree with https://github.com/flutter/flutter/issues/9763#issuecomment-299047535

https://github.com/flutter/flutter/issues/9763#issuecomment-299047565, you meant just the folder references right? Not the actual folder on disk (in case of Pods)

https://github.com/flutter/flutter/issues/9763#issuecomment-299048082 in those cases, users have to likely modify the Podfile itself. I think we should defer the running of `pod install` to the user in those cases. i.e. only automatically run `pod install/deintegrate` in `flutter build ios` only if the Podfile's hash matches our version.

**Comment by cbracken** [comment]
> you meant just the folder references right? 

Yep.

**Comment by xster** [comment]
wrt 

> flutter create doesn't include any traces of cocoapods. Not in ios/Pods and not ios/Podfile, ios/Podfile.lock, ios/Runner.xcodeproj/project.pbxproj etc either.

I just tested it. We're actually not that far from it at all. 

I tried `flutter create`. Then go into the project and delete all traces of cocoapods. Everything builds fine. Then add url_launcher: ^0.3.0 to the pubspec, install cocoapods and run flutter build ios. 

The only things we're missing is 
- making the Podfile (we'd want to have it managed by Dart code anyway to solve https://github.com/flutter/flutter/issues/9763#issuecomment-299053463). 
- and linking ios/Flutter/[Debug|Release].xcconfig to ios/Pods/Target Support Files/Pods-Runner/Pods-Runner.[debug|release].xcconfig

**Comment by jakobr-google** [comment]
I'm not sure if it's a good idea to de-integrate pods if we go from having plugins to not having plugins. If we want to, then yes, we can only do it if the user hasn't modified the Podfile. Does `pod deintegrate` blow away the xcworkspace?

You'll also have to handle the case where users have manually added a Podfile, and some time later start using plugins. You'll need to have a way to add our plugin boilerplate code to their existing Podfile - maybe just detect this situation and tell them what to do manually (they must know how, since they've already added their own Podfile).

And I'd prefer always running `pod install` if there is a Podfile (assuming that it now only exists if the project is using pods, either directly or through plugins). And make it an error to not have CocoaPods installed if there is a Podfile - maybe only if the app uses plugins.

Since we now only run `pod install` if someone has added a Podfile, we could also automatically run `pod setup` as a separate long-running step before invoking `pod install` if we detect the repo hasn't been initialized yet. That'd be nice of us, and still make it apparent what's going on.

**Comment by cbracken** [comment]
> I'd prefer always running pod install if there is a Podfile

Agreed. Less conditional execution means simpler code and testing and a more predictable for developers.

> we could also automatically run pod setup as a separate long-running step before invoking pod install if we detect the repo hasn't been initialized yet

I really like the idea of trying to _detect_ that `pod setup` needs to be run, but from a developer experience point of view, I'd much rather we bail out with an error message indicating that `pod setup` needs to be run and that it can be a time-consuming step, rather than opting me into a 10-15 minute step (my experience on a 50Mbps connection) that I didn't explicitly know I was going to get.  For users who want to run it immediately, they can. For the few people working from a non-ideal office/home environment with a decent connection or 15 mins to spare, they can defer till later.

**Comment by xster** [comment]
Closing this bug since its primary issue is fixed. Will open children bugs for other minor issues discovered during investigation.
### Whether to also generate Podfile via dart and not check in a static Podfile
I feel a bit more strongly about this one. I think we should 'manage' the contents of a Podfile from flutter tools directly. This will 'permit' the injection of flutter's Podfile script in a hybrid case after a user already has a Podfile or allow 'versioning' of Podfiles as we find bugs or add improvements, we can 'update' and existing Podfile which may have hybrid user entries without deleting the whole file. This way, we don't need to create a Podfile in the initial `flutter create` either.

### Whether to automatically trigger `pod install` on pubspec plugins or on Podfile presence
Umm, I don't really have a strong opinion on this. I'm slightly leaning on the side of, if the user made any manual changes to Podfile himself, he should probably manage his own executions of `pod install`. If there is also usage of pubspec plugins, we can of course warn/remind him to keep running `pod install` manually to keep things up to date.

### Whether to clean with `pod deintegrate` if no plugins are left
I think this one's probably pretty simple especially if we manage the Podfile via dart. If it's a vanilla Podfile purely generated by the flutter tools, we can `pod deintegrate` and clean everything up. If the user has his own entries, don't. 

### Whether to automatically `pod setup`
I think from #9580, we shouldn't. It takes a really long time and consumes a lot of bandwidth and disk space. We should let the user install it themselves.
