### ISSUE TITLE
The documentation for bottom_sheet has a typo

### ISSUE THREAD

**Issue by prasadsunny1** [flutter/flutter#97636]
## Proposal
The [documentation page for bottom_sheet](https://api.flutter.dev/flutter/material/showModalBottomSheet.html) has a typo.

Please look at [this paragraph/line ](https://github.com/flutter/flutter/blob/77d935af4db863f6abd0b9c31c7e6df2a13de57b/packages/flutter/lib/src/material/bottom_sheet.dart#L629)
It says _"The [isDismissible] parameter specifies whether the bottom sheet will be dismissed when user taps on the scrim."_
I think the last word "scrim" is a typo and the author meant "screen".

This can be fixed by a tiny PR. But before that someone has to say that it really is a miss and approve this issue

**Comment by maheshmnj** [comment]
Hi @prasadsunny1, Thanks for filing the issue. I am not sure if that's a typo, This PR introduced it https://github.com/flutter/flutter/commit/dd43da71febaafc58852000a61a6bc1ac4fb57ef

https://github.com/flutter/flutter/blob/77d935af4db863f6abd0b9c31c7e6df2a13de57b/packages/flutter/lib/src/material/bottom_sheet.dart#L628-L630

@shihaohong can you please confirm if this is intended.

**Comment by HansMuller** [comment]
It's not a typo although the term theatrical term "scrim", which is used by analogy here, might be confusing. It's referring to the widget stacked behind the bottom sheet that fills its navigator and handles (dismiss) tap gestures.
