### ISSUE TITLE
rebuild screen when open textFormField related to theme data

### ISSUE THREAD

**Issue by k-ahmednagy** [flutter/flutter#97639]
hello , iam getting strange error on my app , when open form field widget are rebuild and keyboard automatic down , after days searching i got where the issue is in themeData in materialApp 
 - error has fix when remove **checkboxTheme** from theme in materialApp , and wrap my checkbox in custom theme

**Comment by danagbemava-nc** [comment]
Hi @k-ahmednagy, thanks for filing this issue. 

Please provide the output of `flutter doctor -v` as well as a complete minimal reproducible code sample. 

Thank you

**Comment by k-ahmednagy** [comment]
> Hi @k-ahmednagy, thanks for filing this issue.
> 
> Please provide the output of `flutter doctor -v` as well as a complete minimal reproducible code sample.
> 
> Thank you

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.63.2)
[✓] Connected device (1 available)

• No issues found!

```
// widget rebuild after open textFormField
Column(
            children: [
              TextFormField(),
            ],
          )
```

rebuild issue showing after add

**Comment by danagbemava-nc** [comment]
Hi @k-ahmednagy, your code sample is not complete. 

Please provide a  [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

Thank you
