### ISSUE TITLE
Comma doesnt work on Samsung Android Keyboard with Flutter

### ISSUE THREAD

**Issue by YannBemba40** [flutter/flutter#97635]
My Samsung Galaxy Tab s4 (SM-T830) comma button key is disabled.

Although I'm using a TextFormField of type number with a keyboardType of TextInputType.numberWithOptions(decimal: true) it doesn't work.

![mRYrE](https://user-images.githubusercontent.com/97102349/152138834-33cb7c6a-5fd2-400d-9b25-18d95dfa1943.png)

**Comment by YannBemba40** [comment]
Here the problem :
![mRYrE](https://user-images.githubusercontent.com/97102349/152124496-e1617750-2bea-472a-84c3-eefc20e9c539.png)

**Comment by kauzige** [comment]
I think we have the same problem, check my issue : https://github.com/flutter/flutter/issues/97634

**Comment by YannBemba40** [comment]
Unfortunately your problem is not mine. Me my comma button is disabled while you it's another problem

**Comment by danagbemava-nc** [comment]
Hi @YannBemba40, I see a similar issue being tracked in https://github.com/flutter/flutter/issues/61175. It seems like this is a general Samsung issue as there was a similar issue reported on the Xamarin Forms repo https://github.com/xamarin/Xamarin.Forms/issues/1898. It seems to be related to locales. 

Closing as duplicate as a similar issue is already being tracked in https://github.com/flutter/flutter/issues/61175.

If you disagree, leave a comment below and I will reopen. 

Thank you
