### ISSUE TITLE
Few mp4 video not playing getting this error

### ISSUE THREAD

**Issue by iamwasimaftab** [flutter/flutter#97644]
<details>
<summary>logs</summary>

```console
E/libc    ( 9028): Access denied finding property "vendor.display-size"
E/libc    ( 9028): Access denied finding property "vendor.display-size"
I/ExoPlayerImpl( 9028): Init 5b44a88 [ExoPlayerLib/2.15.1] [generic_x86, AOSP TV on x86, Google, 30]
I/flutter ( 9028): https://mydomain.com/api/subtitles/by/episode/11/4F5A9C3D9A86FA54EACEDDD635185/0214e686-443a-4924-8c6a-95d1de438a25/
E/ExoPlayerImplInternal( 9028): Playback error
E/ExoPlayerImplInternal( 9028):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal( 9028):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:624)
E/ExoPlayerImplInternal( 9028):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:596)
E/ExoPlayerImplInternal( 9028):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal( 9028):       at android.os.Looper.loop(Looper.java:223)
E/ExoPlayerImplInternal( 9028):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal( 9028):   Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
E/ExoPlayerImplInternal( 9028):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:389)
E/ExoPlayerImplInternal( 9028):       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
E/ExoPlayerImplInternal( 9028):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1014)
E/ExoPlayerImplInternal( 9028):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:409)
E/ExoPlayerImplInternal( 9028):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal( 9028):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal( 9028):       at java.lang.Thread.run(Thread.java:923)
E/flutter ( 9028): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: Source error, , null)



I/VideoCapabilities( 9028): Unsupported profile 4 for video/mp4v-es
I/OMXClient( 9028): IOmx service obtained
D/SurfaceUtils( 9028): connecting to surface 0xeb847e08, reason connectToSurface
I/MediaCodec( 9028): [OMX.google.h264.decoder] setting surface generation to 9244673
D/SurfaceUtils( 9028): disconnecting from surface 0xeb847e08, reason connectToSurface(reconnect)
D/SurfaceUtils( 9028): connecting to surface 0xeb847e08, reason connectToSurface(reconnect)
E/ACodec  ( 9028): [OMX.google.h264.decoder] setPortMode on output to DynamicANWBuffer failed w/ err -1010
I/ACodec  ( 9028): codec does not support config priority (err -1010)
I/OMXClient( 9028): IOmx service obtained
I/ACodec  ( 9028): codec does not support config priority (err -2147483648)
I/ACodec  ( 9028): codec does not support config operating rate (err -2147483648)
I/yal.alenwan_ot( 9028): Background young concurrent copying GC freed 23169(1064KB) AllocSpace objects, 3(124KB) LOS objects, 12% free, 7397KB/8413KB, paused 1.997ms total 101.811ms
D/MediaCodec( 9028): [OMX.google.h264.decoder] setting dataspace on output surface to #104
W/Gralloc4( 9028): allocator 3.x is not supported
D/SoftwareRenderer( 9028): setting dataspace on output surface to #104
D/AudioTrack( 9028): getTimestamp_l(34): device stall time corrected using current time 7532772997815
```
</details>

**Comment by danagbemava-nc** [comment]
Hi @iamwasimaftab, thanks for filing the issue. 

Please provide the output of `flutter doctor -v` as well as the version of `video_player` you're using. 

Please also provide a sample URL/video that you are experiencing this issue with as well as a complete minimal reproducible code sample.

Thank you

**Comment by iamwasimaftab** [comment]
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-x64, locale en-AE)
    • Flutter version 2.5.3 at /Users/Cylinder/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (4 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/Cylinder/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Connected device (2 available)
    • AOSP TV on x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 98.0.4758.80

! Doctor found issues in 1 category.
Cylinder@w-Mac-Pro Application % 


Package Name                              Current   Upgradable  Resolvable  Latest   

direct dependencies:                     
carousel_slider                           *3.0.0    *3.0.0      4.0.0       4.0.0    
flutter_facebook_auth                     *3.5.7    *3.5.7      4.0.1       4.0.1    
flutter_html                              *2.1.5    *2.1.5      *2.1.5      2.2.1    
fluttertoast                              *7.1.8    *7.1.8      8.0.8       8.0.8    
logger                                    *1.0.0    *1.0.0      1.1.0       1.1.0    
retrofit                                  *2.2.0    *2.2.0      3.0.1       3.0.1    
shared_preferences                        *2.0.12   2.0.13      2.0.13      2.0.13   
video_player                              *2.2.17   *2.2.17     *2.2.17     2.2.18   
wakelock                                  *0.5.6    *0.5.6      *0.5.6      0.6.1+1  

dev_dependencies: all up-to-date.        

transitive dependencies:                 
async                                     *2.8.1    *2.8.1      *2.8.1      2.8.2    
characters                                *1.1.0    *1.1.0      *1.1.0      1.2.0    
ffi                                       *1.1.2    *1.1.2      *1.1.2      1.2.0    
flutter_facebook_auth_platform_interface  *2.8.0    *2.8.0      3.0.1       3.0.1    
flutter_facebook_auth_web                 *2.6.0+2  *2.6.0+2    3.0.0+1     3.0.0+1  
flutter_math_fork                         *0.3.3+1  *0.3.3+1    *0.3.3+1    0.6.1    
flutter_svg                               *0.22.0   *0.22.0     *0.22.0     1.0.3    
fwfh_text_style                           *2.5.1    *2.5.1      *2.5.1      2.7.3+1  
js                                        *0.6.3    *0.6.3      *0.6.3      0.6.4    
matcher                                   *0.12.10  *0.12.10    *0.12.10    0.12.11  
path                                      *1.8.0    *1.8.0      *1.8.0      1.8.1    
path_drawing                              *0.5.1+1  *0.5.1+1    *0.5.1+1    1.0.0    
path_parsing                              *0.2.1    *0.2.1      *0.2.1      1.0.0    
provider                                  *5.0.0    *5.0.0      *5.0.0      6.0.2    
source_span                               *1.8.1    *1.8.1      *1.8.1      1.8.2    
sqflite_common                            *2.0.1+1  *2.0.1+1    *2.0.1+1    2.2.0    
url_launcher_web                          *2.0.7    *2.0.7      *2.0.7      2.0.8    
vector_math                               *2.1.0    *2.1.0      *2.1.0      2.1.2    
webview_flutter                           *2.8.0    *2.8.0      *2.8.0      3.0.0    
win32                                     *2.3.6    *2.3.6      *2.3.6      2.3.10   

transitive dev_dependencies:             
test_api                                  *0.4.2    *0.4.2      *0.4.2      0.4.9    

1 upgradable dependency is locked (in pubspec.lock) to an older version.
To update it, use `flutter pub upgrade`.

7  dependencies are constrained to versions that are older than a resolvable version.
To update these dependencies, edit pubspec.yaml, or run `flutter pub upgrade --major-versions`.

**Comment by danagbemava-nc** [comment]
Please provide a sample url that we can use to verify this behavior. 

Thank you
