### ISSUE TITLE
Choose specific Dart version used by Flutter

### ISSUE THREAD

**Issue by ben-xD** [flutter/flutter#97640]
## Problem

I am trying to build an old Flutter application that uses an old version of Flutter and Dart. I can specify an older version of Flutter, but I cannot select the **version of Dart**. Take a look at a popular question which has not been solved: https://stackoverflow.com/questions/53682814/how-to-run-flutter-projects-with-different-older-dart-sdk-dependencies

## Steps to Reproduce

1. Install an older version of Flutter: e.g. `git checkout 1.17.0`
2. Run `flutter --version`:
```
Flutter 1.17.0 • channel unknown • unknown source
Framework • revision e6b34c2b5c (1 year, 9 months ago) • 2020-05-02 11:39:18 -0700
Engine • revision 540786dd51
Tools • Dart 2.8.1
```
3. Observe that the Flutter uses a relatively new release of Dart. And there is no way to override the Dart version used by Flutter. My app has a specific dart SDK constraint of, for example: `">=2.0.0 <2.2.0"`

**Comment by stuartmorgan** [comment]
> 3\. Observe that the Flutter uses a relatively new release of Dart.

It is not relatively new; it's the version that was current when that version of Flutter came out. It's exactly as old as the Flutter version you chose.

Flutter is tightly coupled to Dart, so you can't mix and match versions. If you really wanted to run a specific version of Flutter that it wasn't built with you would need to fork the framework and the engine and custom-build your own combination, which would almost certain include lots of changes to make them compatible.

**Comment by ben-xD** [comment]
Oh, I see @stuartmorgan. Thanks for your guidance :)
