### ISSUE TITLE
ChangeNotifier builder widget

### ISSUE THREAD

**Issue by AAAbramenko** [flutter/flutter#97643]
[ValueListenableBuilder](https://api.flutter.dev/flutter/widgets/ValueListenableBuilder-class.html) is provided in widgets library, but what about builder-widget for ChangeNotifier instance (not ValueListenable)? Simple counter example is [here](https://dartpad.dev/?id=5dd8decae34394966bb1ac0b3342bc1d)

**Comment by maheshmnj** [comment]
Hi @AAAbramenko, Thanks for filing the issue. Are you proposing that ChangeNotifierBuilder Widget is required ? 
which should work with ChangeNotifiers?

**Comment by AAAbramenko** [comment]
Yes, thats right. Now there two ways to listen ChangeNotifier:
- implement StatefulWidget as in example above;
- use provider package:
```dart
  Widget build(BuildContext context) {
    final notifier = context.watch<SomeChangeNotifier>() ;
  // Smth building
 }
```
'''

**Comment by brianegan** [comment]
Although it has a confusing name, `AnimatedBuilder` works for this use case. It is a Widget that listens to any `Listenable` object (`ChangeNotifier` is a `Listenable`) and rebuilds when notified.

**Comment by AAAbramenko** [comment]
Thanks a lot, AnimatedBuilder is what is needed.

**Comment by maheshmnj** [comment]
Additionally, you can find a complete example which uses `AnimatedBuilder` with `ChangeNotfier` in a new flutter template introduced in `stable 2.5` by running `flutter create -t skeleton sample`
