### ISSUE TITLE
[custom-devices] default "forwardPortSuccessRegex" value does not match

### ISSUE THREAD

**Issue by mbriand** [flutter/flutter#97641]
With custom devices, the `forwardPortSuccessRegex` is used to check if the port forwarding of the observatory service was installed successfully, by looking for a match in the standard output of the ssh process installing the port forwarding.

The default value of this regex, when a new device is added with `flutter custom-devices add` is `Linux`. However, I do not understand how this value was selected, as it does not relate to the output generated on my host (OpenSSH_8.4p1 / Ubuntu 21.10). All I have in standard output is `Pseudo-terminal will not be allocated because stdin is not a terminal.`, while port is correctly forwarded.

Is `Linux` supposed to be present in the output in some way ? @ardera, this was in #78113 and #82043, do you have more context ?

# Suggested solution

I believe the solution could either be:

- Using a value of `forwardPortSuccessRegex` that matches on all systems.
- Ask the user for a sensible value of `forwardPortSuccessRegex`.

# Implementation tentative

I've attached a patch below, working on my side. As I do not fully understand how the previous `Linux` value was supposed to work, it might break things, so I'm not opening a PR right now.

```
diff --git a/packages/flutter_tools/lib/src/commands/custom_devices.dart b/packages/flutter_tools/lib/src/commands/custom_devices.dart
index 4c144e1a35ac..a80226cfcba7 100644
--- a/packages/flutter_tools/lib/src/commands/custom_devices.dart
+++ b/packages/flutter_tools/lib/src/commands/custom_devices.dart
@@ -736,11 +736,12 @@ class CustomDevicesAddCommand extends CustomDevicesCommandBase {
           '-o', 'ExitOnForwardFailure=yes',
           if (ipv6) '-6',
           '-L', '$formattedLoopbackIp:\${hostPort}:$formattedLoopbackIp:\${devicePort}',
-          sshTarget
+          sshTarget,
+	  "echo 'Port forwarding success'; read"
         ]
         : null,
       forwardPortSuccessRegex: usePortForwarding
-        ? RegExp('Linux')
+        ? RegExp('Port forwarding success')
         : null,
 
       screenshotCommand: screenshotCommand.isNotEmpty
-- 
```

**Comment by ardera** [comment]
This is the output of the forward port command for me:
```
C:\Users\hanne>ssh -o BatchMode=yes -o ExitOnForwardFailure=yes -L 127.0.0.1:12345:127.0.0.1:12345 hpi4
Linux hpi4 5.10.83-v7l+ #1499 SMP Tue Dec 7 14:08:09 GMT 2021 armv7l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Sat Jan 29 15:26:01 2022 from 192.168.178.21

Wi-Fi is currently blocked by rfkill.
Use raspi-config to set the country before use.

pi@hpi4:~ $
```

If it fails it looks like this:
```
C:\Users\hanne>ssh -o BatchMode=yes -o ExitOnForwardFailure=yes -L 127.0.0.1:12346:127.0.0.1:12345 hpi4_
ssh: Could not resolve hostname hpi4_: Der angegebene Host ist unbekannt.

C:\Users\hanne>
```

I just used used the `Linux` in the output of the first command to detect a forward success. But yeah your way to do it is way better. I think the exact output of the shell is system-dependent, so might not be the best idea to match against it.

**Comment by mbriand** [comment]
Ok, thanks for your feedback, I can see how your setup differs from mine.

So yes, the shell output will definitely be system dependent, and we can probably not match reliably match against it. Generating our own log line so we can match against something predictive seems better.

I will open a PR soon, so we can discuss the implementation details.
