### ISSUE TITLE
Ignore coverage comment isn't working on async functions

### ISSUE THREAD

**Issue by maheini** [flutter/flutter#97648]
## Issue
I'm not able to ignore any async function via comments. Is there something I miss, or a bug? I always get Icov.info result `DA:10,0`

`Future<bool> test() async => Future.value(true); // coverage:ignore-line`
I run: `flutter test mytest.dart --coverage`

If I switch my function to non-async, it's working perfectly, the line isn't mentioned inside Icov.info.

## System & environment
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.22000.469], locale de-CH)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2021.1)
[√] Connected device (2 available)

• No issues found!

### More details
I tried to ignore hard-to-test cases like a wrapper function Future<bool> exists(File file) async => await file.exists();. It would benefit my Code if I would be able ignore the coverage, but however, the lines are still visible inside Icov.info as not tested.
If I change my Code from:
`Future<bool> test() async => Future.value(true); // coverage:ignore-line`
to:
`bool test() => true; // coverage:ignore-line`
The line isn't visible inside Icov.info, wich is as intended.

**Comment by danagbemava-nc** [comment]
Hi @maheini, this issue belongs in the [dart-lang/coverage](https://github.com/dart-lang/coverage/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) repo and it looks like you've already filed an issue over there. The maintainers will respond to you when they are able. 

Closing as the coverage package is not maintained by the flutter team. 

Thank you

**Comment by maheini** [comment]
Thanks @danagbemava-nc  for taking your time :). 
Yes, I did already opened a issue at dart-lang/coverage but since I didn't got any responce and dind't know where it belongs to I opened this a second one. But as you cleared up, I will switch to dart-lang/coverage and link my issue for anyone facing the same behaviour: https://github.com/dart-lang/coverage/issues/362
