### ISSUE TITLE
Flutter android template is inconsistent with Android Studio template wrt. manifest values

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#9765]
I would suggest moving the following information (generated by `flutter create`) out of the manifest and into the Gradle configuration:

- versionCode
- versionName
- minSdkVersion
- targetSdkVersion

Also, you might want to move the Application label (`android:label`) to strings for consistency.

**Comment by eseidelGoogle** [comment]
@jakobr-google

**Comment by eseidelGoogle** [comment]
@jason-simmons do you have any opinion on this?  I don't know much about gradle.

**Comment by mit-mit** [comment]
Compared our template against Android Studio (version 2.3.3) and we are indeed not consistent:

Flutter has the following in `android/app/src/main/AndroidManifest.xml`:

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.yourcompany.flutterapp"
    android:versionCode="1"
    android:versionName="0.0.1">

    <uses-sdk android:minSdkVersion="16" android:targetSdkVersion="21" />
    ...
```

Android Studio has it in `android/studioapp/app/build.gradle`:

```
android {
    compileSdkVersion 25
    buildToolsVersion "25.0.3"
    defaultConfig {
        applicationId "com.example.mit.studioapp"
        minSdkVersion 25
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
```

**Comment by namiwang** [comment]
FYI

the [android-release-guide](https://flutter.io/android-release/) needs some update to reflect these changes.

**Comment by mit-mit** [comment]
Good catch @namiwang! Working on resolving in https://github.com/flutter/website/pull/653
