### ISSUE TITLE
Run the SDK packaging recipe on an arm64 macOS host

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#97658]
Following https://github.com/flutter/flutter/pull/97278, the arm64 macOS Dart SDK can be packaged with the Flutter SDK. As part of the release process, creating a Flutter SDK like this requires running [this recipe](https://flutter.googlesource.com/recipes/+/refs/heads/main/recipes/flutter_2_8_0.py#62) (or its successor) on an arm64 macOS host.

It would be good to work out any kinks during the March beta release cycle so that the April cycle sets us up for success for the Q2 stable. /cc @godofredoc

**Comment by zanderso** [comment]
This is part of https://github.com/flutter/flutter/issues/86926

**Comment by godofredoc** [comment]
This is now complete.
