### ISSUE TITLE
[iOS] Trying to build on iOS device throws `Target debug_unpack_ios failed: Flutter.framework/Flutter does not contain .`. Also shows `arch\=undefined_arch` in log.

### ISSUE THREAD

**Issue by combi-35** [flutter/flutter#97659]
## Steps to Reproduce

I have an arm MacBook, running my app on simulator works after following the offical [guide](https://docs.flutter.dev/development/add-to-app/ios/project-setup#apple-silicon-arm64-macs).

Trying to run the app on my iOS device I get:
`None of the architectures in ARCHS (arm64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (arm64, arm64e, armv7, armv7s) which is not in EXCLUDED_ARCHS (arm64). (in target 'Runner' from project 'Runner')`

In the logs I see:
`arch\=undefined_arch`

I really don't know how to fix the issue, as hardcoding architectures probably would result in future errors.

Here are my build settings:
<img width="1445" alt="buildsettings_xcode" src="https://user-images.githubusercontent.com/56366138/152213629-cb263bfd-4720-4462-86d3-040248b941b6.png">

<details>
<summary>flutter run --verbose</summary>

[log.txt](https://github.com/flutter/flutter/files/7989130/log.txt)

</details>

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.0.1 21A559 darwin-arm, locale de-AT)
    • Flutter version 2.8.1 at /Users/lukas/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (7 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/lukas/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 63.3.3
    • Dart plugin version 212.5632

[✓] Connected device (2 available)
    • Lukas iPhone 11 (mobile) • 00008030-00126C201AD0802E • ios            • iOS 15.0 19A346
    • Chrome (web)             • chrome                    • web-javascript • Google Chrome 97.0.4692.99

• No issues found!

```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@combi-35 

From the verbose log, I see:

```
            [  +13 ms] Target debug_unpack_ios failed: Exception: Binary /Users/lukas/Development/and-less/app/build/ios/Debug-iphoneos/Flutter.framework/Flutter does not contain . Running lipo -info:
                       Architectures in the fat file: /Users/lukas/Development/and-less/app/build/ios/Debug-iphoneos/Flutter.framework/Flutter are: armv7 arm64 

                       #0      UnpackIOS._thinFramework (package:flutter_tools/src/build_system/targets/ios.dart:342:7)
                       #1      UnpackIOS.build (package:flutter_tools/src/build_system/targets/ios.dart:291:5)
                       #2      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:839:27)
                       <asynchronous suspension>
                       #3      Future.wait.<anonymous closure> (dart:async/future.dart)
                       <asynchronous suspension>
                       #4      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:777:32)
                       <asynchronous suspension>
                       #5      Future.wait.<anonymous closure> (dart:async/future.dart)
                       <asynchronous suspension>
                       #6      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:777:32)
                       <asynchronous suspension>
                       #7      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:606:16)
                       <asynchronous suspension>
                       #8      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:317:32)
                       <asynchronous suspension>
                       #9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
                       <asynchronous suspension>
                       #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                       <asynchronous suspension>
                       #11     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
                       <asynchronous suspension>
                       #12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
                       <asynchronous suspension>
                       #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                       <asynchronous suspension>
                       #14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
                       <asynchronous suspension>
                       #15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
                       <asynchronous suspension>
                       #16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                       <asynchronous suspension>
                       #17     main (package:flutter_tools/executable.dart:94:3)
                       <asynchronous suspension>

            [   +5 ms] 
                       #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
                       #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:334:7)
                       <asynchronous suspension>
                       #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
                       <asynchronous suspension>
                       #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                       <asynchronous suspension>
                       #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
                       <asynchronous suspension>
                       #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
                       <asynchronous suspension>
                       #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                       <asynchronous suspension>
                       #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
                       <asynchronous suspension>
                       #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
                       <asynchronous suspension>
                       #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                       <asynchronous suspension>
                       #10     main (package:flutter_tools/executable.dart:94:3)
                       <asynchronous suspension>
            Failed to package /Users/lukas/Development/and-less/app.
            Command PhaseScriptExecution failed with a nonzero exit code

            warning: None of the architectures in ARCHS (arm64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (arm64, arm64e, armv7, armv7s) which is not in EXCLUDED_ARCHS (arm64). (in target 'Runner' from project 'Runner')

```

And seeing `arch\=undefined_arch` in it as well. Probably the same was discussed in [this](https://github.com/flutter/flutter/issues/66104#issuecomment-719809502) issue but was left as-is due to lack of further details.

Can you provide `ios/Runner.xcodeproj/project.pbxproj` ?
Also can you try running on latest master too and see if you get same error or not ?

**Comment by combi-35** [comment]
Hi @darshankawar,
here is [project.pbxproj](https://github.com/flutter/flutter/files/7993342/project.txt).
Unfortunately changing to master results in the exact same error.

**Comment by darshankawar** [comment]
From `pbxproj`, `runOnlyForDeploymentPostprocessing = 0;` which seems to be as expected.
As I mentioned earlier, below error :

`[  +13 ms] Target debug_unpack_ios failed: Exception: Binary /Users/lukas/Development/and-less/app/build/ios/Debug-iphoneos/Flutter.framework/Flutter does not contain . Running lipo -info:
                       Architectures in the fat file: /Users/lukas/Development/and-less/app/build/ios/Debug-iphoneos/Flutter.framework/Flutter are: armv7 arm64 ` is the main point here, which seems to be incomplete, because it only says `does not contain .` but nothing afterwards.

I was hoping to see something like: `unsupport iOS arch` or `does not exist` followed by the archs.. 

This seems to be another case of `export arch\=undefined_arch` as written in the verbose log. A similar one which was observed [here](https://github.com/flutter/flutter/issues/66104#issuecomment-719809502) but probably didn't get a chance to go further into it due to lack of more details on it.

/ cc @jmagman for further input on this scenario.

**Comment by jmagman** [comment]
You're building for a physical iOS device (not simulator), which is an arm device.  But `arm64` is marked as an `Excluded architecture`, in your logs I see `EXCLUDED_ARCHS=arm64`.  Your screenshot is showing the build settings for "Project" but we need to know what the settings are for "Target".

Can you attach `ios/Runner.xcodeproj/project.pbxproj` and a screenshot of the same build settings, but the `Runner` target (not project).

**Comment by combi-35** [comment]
> Hi @darshankawar, here is [project.pbxproj](https://github.com/flutter/flutter/files/7993342/project.txt). Unfortunately changing to master results in the exact same error.

If not mistaken the [project.pbxproj](https://github.com/flutter/flutter/files/7993342/project.txt) should be the correct file.

Here is the screenshot of `Runner` build settings:
<img width="1462" alt="runner" src="https://user-images.githubusercontent.com/56366138/152426465-d53c7a45-f784-4200-8456-0be40ecc4977.png">

**Comment by jmagman** [comment]
> > Hi @darshankawar, here is [project.pbxproj](https://github.com/flutter/flutter/files/7993342/project.txt). Unfortunately changing to master results in the exact same error.
> 
> If not mistaken the [project.pbxproj](https://github.com/flutter/flutter/files/7993342/project.txt) should be the correct file.

Sorry, I missed that you had already attached it.

Your problem is here:
```
				EXCLUDED_ARCHS = arm64;
				"EXCLUDED_ARCHS[sdk=iphonesimulator*]" = arm64;
```
You've excluded `arm64`, but that's the physical phone architecture.  I don't know why you manually updated `EXCLUDED_ARCHS` in so many spots, but I suggest you completely remove all `EXCLUDED_ARCHS` from that file, and let Flutter manage the allowed architectures for you based on what plugins you're using and what simulator types are available.
