### ISSUE TITLE
Use ARM macOS frameworks, `gen_snapshot_x64` and `gen_snapshot_arm64` in the tool

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#97681]
From https://github.com/flutter/flutter/issues/60113#issuecomment-1028454740
> Following #97671 and https://flutter-review.googlesource.com/c/recipes/+/26040, `FlutterMacOS.framework` contains the lipo'd x64 and arm64 engine dylib, and two new `gen_snapshot` binaries are included with the engine artifacts as follows:
> 
> * `bin/cache/artifacts/engine/darwin-x64/gen_snapshot_x64`
> * `bin/cache/artifacts/engine/darwin-x64/gen_snapshot_arm64`
> * `bin/cache/artifacts/engine/darwin-x64-profile/gen_snapshot_x64`
> * `bin/cache/artifacts/engine/darwin-x64-profile/gen_snapshot_arm64`
> * `bin/cache/artifacts/engine/darwin-x64-release/gen_snapshot_x64`
> * `bin/cache/artifacts/engine/darwin-x64-release/gen_snapshot_arm64`
> 
> The tool should switch to using those `gen_snapshot`s, and then we can remove the `gen_snapshot` that's still there that doesn't have a suffix that specifies the architecture.

Additionally, remove arm64 `EXCLUDED_ARCHS` (see https://github.com/flutter/flutter/pull/72748) so the apps actually start getting built natively.

@zanderso @knopp

**Comment by knopp** [comment]
Are there any binary-only plugins? Cocoa-pods plugin shouldn't really care about target architecture, should it?

**Comment by knopp** [comment]
Also eventually we'd want to get lipo'd gen_snapshots as well.

**Comment by zanderso** [comment]
It might make sense to lipo `gen_snapshot_arm64`, but Dart currently does not support generating x64 code on an arm64 host.

**Comment by jmagman** [comment]
> Are there any binary-only plugins? Cocoa-pods plugin shouldn't really care about target architecture, should it?

Yes, you can bundle binaries.  That's what happened with `google_sign_in` and `google_maps_flutter`, they depend on pre-built SDKs which didn't contain ARM.
https://github.com/CocoaPods/Specs/blob/f052cc63fbbae6566e0998fde5b16decd90d8ef9/Specs/a/d/d/GoogleMaps/5.1.0/GoogleMaps.podspec.json#L350-L352
https://guides.cocoapods.org/syntax/podspec.html#vendored_frameworks

**Comment by jmagman** [comment]
Also need to revert https://github.com/flutter/flutter/pull/92508

**Comment by cbracken** [comment]
Fixed by #100271.
