### ISSUE TITLE
Would like an example showing deep linking into a Flutter app

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#9768]
This came up in conversation with @lukef this morning as a desired sample.

My understanding is it's possible to wire up link handling on iOS and Android and have those translate into Flutter routes, but we don't have an example of doing so.

**Comment by eseidelGoogle** [comment]
It sounds like @lukef successfully built this himself, so removing this from May.

**Comment by perlatus** [comment]
Direct link to where the android implementation is mentioned: https://github.com/flutter/flutter/issues/8711#issuecomment-304681212

**Comment by sethladd** [comment]
Closing this particular issue, because https://github.com/flutter/flutter/issues/11607 is the general request for documentation + example/sample.
