### ISSUE TITLE
Configure flutter/impeller with all our CI automation

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#97686]
We just created flutter/impeller: https://github.com/flutter/impeller

We need to:

- [ ] configure some sort of CI for this repo. @chinmaygarde, can you describe what kinds of tests you have and what infrastructure they will need?
- [ ] tell the autocommit bot should monitor this repo
- [ ] add a dashboard to show CI status
- [ ] add a "luci-status" check on PRs to report tree greenness on this repo
- [ ] configure this repo for scorecard security checking (.allstar should already be set up)
- [ ] configure the "requires test" and autolabeling bot to know about this repo (@chinmaygarde can you describe the appropriate heuristics for telling if a PR in this repo has tests?)
- [x] add a test that verifies that all files have the right license header (can be copied [from the framework repo](https://github.com/flutter/flutter/blob/master/dev/bots/analyze.dart#L407)) - @chinmaygarde you might be best placed to do this
- [x] make sure there is a LICENSE file in the root of the repo that matches the engine/LICENSE file exactly (@chinmaygarde will do this one)

**Comment by CaseyHillers** [comment]
This would make a good use of the go/flutter-infra-office-hours (Google internal link). The tl;dr from the infra side is:

1. Ensure the flutter-dashboard github app is installed for flutter/impeller
2.  Update Cocoon's configs to look at flutter/impeller (https://github.com/flutter/cocoon/blob/main/app_dart/lib/src/service/config.dart)
3. Add a .ci.yaml and related roller for the repo to generate LUCI builders
4. Add LUCI recipes (or we can create a generic recipe if needed where you can specify the tests in a yaml like we do for cocoon)

**Comment by godofredoc** [comment]
1) added `flutter/impeller` to the list of repositories enabled in the flutter-dashboard app. This is the only step that requires admin permissions to the repo.

4) engine_v2 recipes should be the easiest way to build and test this repository

**Comment by bdero** [comment]
It looks like the scorecard check started failing in impeller starting on one of my commits yesterday, but I'm not sure how to diagnose the problem. Is there a different dashboard that has more diagnostic/actionable output? I'm not seeing any here: https://github.com/flutter/impeller/runs/5327601854?check_suite_focus=true

**Comment by Hixie** [comment]
That's odd. Can you file a [new infra bug](https://github.com/flutter/flutter/issues/new?assignees=&labels=team%3A+infra&template=6_infrastructure.md&title=) for that?

**Comment by bdero** [comment]
Sure, done: https://github.com/flutter/flutter/issues/99185

**Comment by zanderso** [comment]
Before we jump into this, I think we first need to decide whether to simply bring the impeller source into the Engine repo directly instead of having a separate repo. We might discuss other motivations, but it's only in a separate repo now to help us bootstrap.

**Comment by chinmaygarde** [comment]
I'll figure out the licenses stuff this week. In the engine sync last week, we discussed moving the repo entirely into the engine repo but decided against it at this time. Instead, re-evaluating the decision on a week by week basis.

**Comment by godofredoc** [comment]
Sounds good, please let us know if it is decided to keep the repo to enable CI on it.

**Comment by chinmaygarde** [comment]
I'll ping this thread as we re-evaluate. For now, it is a separate repo. I've completed the action items related to licenses.

**Comment by zanderso** [comment]
At the meeting last week, we decided to re-evaluate again this week.

**Comment by zanderso** [comment]
This is obsolete. Impeller has moved into the Engine repo.
