### ISSUE TITLE
PopupMenuButton issues

### ISSUE THREAD

**Issue by purutechno** [flutter/flutter#97699]
## Use case

I am using PopupMenuButton to display a list of suggestions to the user so that they can select from the suggestions. We should use PopupMenuItem to display each suggestion as required by PopupMenuButton. However, the width of the PopupMenuItem is not expanding to fit the entire screen regardless of my approach to wrap it with 
- SizedBox or Container with max width of the screen,

<img src = "https://user-images.githubusercontent.com/44781006/152297349-3d6b04ee-3eed-4dc0-ad0f-c84d02715d46.jpg" width = "300">

The width of the suggestion list is somewhat fixed by default which prevents it from taking the available space. I found more about it in this issue :
https://github.com/flutter/flutter/issues/92591#issuecomment-953417550

 Also, The safeArea[ top-bottom ] of PopupMenuButton cannot be removed. This can be registered as a separate issue but I left it here in the same one for consideration.
 

I cannot find a solution for this issue yet.

## Proposal

Flutter should provide a default way for PopupMenuItem to adjust to the full screen width by:
- Using a boolean value that might be called setFullScreenWith

On setFullScreenWith value set to true , the PopupMenuItem takes the full width of the screen, else it will have the default property.

**Comment by maheshmnj** [comment]
Hi @purutechno,

There is a similar issue describing this case https://github.com/flutter/flutter/issues/64918, Please follow up there for further updates, Closing this issue as a duplicate. If you disagree feel free to write in the comments and I will reopen it.

Thank you.
