### ISSUE TITLE
Dart -> Engine roll failing on removed script

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#97692]
The `run_binary_size_analysis` script was removed in https://dart.googlesource.com/sdk.git/+/e32d98cd0608adda0bfb9bd983d3a566fa030561, with the roll in https://github.com/flutter/engine/pull/31224, but it is referenced by an Engine recipe https://flutter.googlesource.com/recipes/+/refs/heads/main/recipes/engine.py#427

See the presubmit check that failed on the roll attempt here: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Android%20AOT%20Engine/31807/overview.

@rmacnak-google

**Comment by a-siva** [comment]
A revert was submitted for this last night here https://dart-review.googlesource.com/c/sdk/+/231600, I am going to restart the roller.
