### ISSUE TITLE
File transfer using scp command.

### ISSUE THREAD

**Issue by sitakanta136** [flutter/flutter#97694]
We are working on IoT Project.
Requirement:
Need to transfer file Mobile to Remote location using SCP command ? 
Other SFTP and FTP not supported remote Gateway. Please suggest how can we send files to a remote location using the SCP command.

**Comment by danagbemava-nc** [comment]
Hi @sitakanta136, kindly see any of the communities in https://flutter.dev/community#community-grid for help in asking support questions such as these. 

The flutter issue tracker is for bug reports or feature requests. 

Closing as this is neither of the above. 

Thank you
