### ISSUE TITLE
How to disable info of location in the map.

### ISSUE THREAD

**Issue by SittiphanSittisak** [flutter/flutter#97697]
How to disable info of location in the map.
I use a map-like button to show the dialog. 
When I click on the map at the location, the info will show like this video. How to disable it?

https://user-images.githubusercontent.com/59549741/152296123-c4665182-2ee1-460c-adc0-121406a3ae3a.mp4

**Comment by darshankawar** [comment]
@SittiphanSittisak 
Your question is better suited for support channels like StackOverflow, so please ask the same there.
Closing from here, as this isn't a bug or feature request.
