### ISSUE TITLE
Improve PlatformException.stacktrace documentation

### ISSUE THREAD

**Issue by ueman** [flutter/flutter#97698]
## Use case

I want to know in which cases and on what platforms the [`PlatformException.stacktrace`](https://api.flutter.dev/flutter/services/PlatformException/stacktrace.html) is set without having to look up the implementation for each platform in the engine.

## Proposal

Improve documentation for [`PlatformException.stacktrace`](https://api.flutter.dev/flutter/services/PlatformException/stacktrace.html).

**Comment by rafaelsetragni** [comment]
@ueman, how to pass the exception stack trace to dart channel using `result.error` method (PlatformException) on Android? And on iOS?

**Comment by ueman** [comment]
@rafaelsetragni currently the stacktrace is only set, if there's an exception during serialization of data for method channels. For your use case you should probably create a new issue.
