### ISSUE TITLE
Download File Using Azure Blob Storage.

### ISSUE THREAD

**Issue by sitakanta136** [flutter/flutter#97695]
Can we download a zip file using Azure blob storage?
Please help me to do this.  Is blocking my development!

**Comment by danagbemava-nc** [comment]
Hi @sitakanta136, kindly visit any of the communities in https://flutter.dev/community#community-grid for support questions such as this. 

The flutter issue tracker is for bug reports and feature requests. 

Closing as this is neither of the above. 

Thank you
