### ISSUE TITLE
Allow Unit, Widget and Integration tests to reside side by side with application (/lib) files

### ISSUE THREAD

**Issue by reyou** [flutter/flutter#97690]
## Use case
As an app developer, I like my test files to live close by the real application files. Such as;

1. lib/app.dart
2. lib/app_unit_test.dart
3. lib/app_int_test.dart

Because once the app gets larger, it is getting harder to navigate back-forth with app files and the tests. 

## Proposal
Allow Unit, Widget and Integration tests to reside side by side with application (/lib) files. 
Today I am getting errors like below if I am setting them side-by-side

![image](https://user-images.githubusercontent.com/6571483/152279051-172036d1-ea5e-44c6-9ccc-7e1c1309e0db.png)
![image](https://user-images.githubusercontent.com/6571483/152279108-e8fed96c-6fd6-4bea-9916-78b64eb2778a.png)

but if I move it in dedicated folder it works;

![image](https://user-images.githubusercontent.com/6571483/152279203-ecb60573-1ff2-4de1-8826-ba0ae1132abf.png)

**Comment by christopherfujino** [comment]
While this is a reasonable request, I think there is basically no chance that we would implement this because of the complexity involved. I apologize, but I am going to close this feature proposal.
