### ISSUE TITLE
[local_auth] allow app to use face id only once on ios

### ISSUE THREAD

**Issue by AliAlHourash** [flutter/flutter#97696]
local_auth allow app to use face id only once on ios physical devices, after that it show just dialog.
This video show the problem

[https://drive.google.com/file/d/1iQPVctQjhuAuuVxF4mqup85UyWPf5oPi/view?usp=sharing](url)
=======
I am using local_auth: ^1.1.10
flutter 2.8.1

**Comment by darshankawar** [comment]
@AliAlHourash 
From the video, I see that you first used FaceID to unlock and then tried using fingerprint (in red, on left) which shows a dialog. So can you please elaborate more on current use case and what are you proposing ?
