### ISSUE TITLE
Flutter should have its logo in the framework

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#977]
Maybe you still have to opt-in to including it in your app?  But if you want to have a "Made with Flutter" screen we need to have our logo somewhere.  Maybe we can provide a "Made with Flutter" widget.

Where I wanted to use this was in the Flutter Material Gallery example.

**Comment by abarth** [comment]
We should provide it as an asset that you can choose to include in your bundle.

**Comment by Hixie** [comment]
This should probably come as part of https://github.com/flutter/flutter/issues/109.

**Comment by abarth** [comment]
We do now: https://docs.flutter.io/flutter/material/FlutterLogo-class.html
