### ISSUE TITLE
'package:flutter/src/rendering/binding.dart': Failed assertion: line 369 pos 12: '!_debugMouseTrackerUpdateScheduled': is not true.

### ISSUE THREAD

**Issue by schilpr-TT** [flutter/flutter#97711]
```
═══════ Exception caught by scheduler library ═════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/rendering/binding.dart': Failed assertion: line 369 pos 12: '!_debugMouseTrackerUpdateScheduled': is not true.
package:flutter/…/rendering/binding.dart:369
2
```

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:

No idea how to reproduce, I'm refactoring code made by someone else, and figured with the request above it was a good idea to create the issue here as requested.

**Comment by darshankawar** [comment]
@schilpr-TT 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/84241
Please follow-up in it for further updates.
Closing this as a duplicate.
