### ISSUE TITLE
ThemeData not working

### ISSUE THREAD

**Issue by ishantsehrawat** [flutter/flutter#97712]
I am trying to make my appbar as the kPrimaryColor but it is still the default blue color

`theme: ThemeData(
        scaffoldBackgroundColor: kBackgroundColor,
        primaryColor: kPrimaryColor,
        colorScheme: const ColorScheme.light().copyWith(
          primary: kPrimaryColor,
        ),
        textTheme: Theme.of(context).textTheme.apply(
              bodyColor: kTextColor,
            ),
      ),`

FLutter Doctor
`[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19042.1466], locale en-IN)
    • Flutter version 2.8.1 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (7 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\Ishant\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter       
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.63.2)
    • VS Code at C:\Users\Ishant\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.34.0

[√] Connected device (2 available)
    • SM M205F (mobile) • 340104eed10b36a3 • android-arm64  • Android 10 (API 29)
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 84.0.522.52

! Doctor found issues in 1 category.`

![Screenshot_20220203-213047](https://user-images.githubusercontent.com/64154731/152379889-d9a4a105-e6c2-43a7-a646-a7d6b3a55790.jpg)

**Comment by HansMuller** [comment]
If you're checking to see if the AppBar's backgroundColor defaults to the ColorScheme's primary, this works as expected with the current version of Flutter:

```dart
class Test extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Scaffold(appBar: AppBar());
}

void main() {
  runApp(
    MaterialApp(
      theme: ThemeData(
        colorScheme: ColorScheme.light().copyWith(primary: Colors.green),
      ),
      home: Test(),
    ),
  );
}
```

It often makes more sense to use the component themes, like AppBarTheme, to configure components. This works as well:

```dart
class Test extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Scaffold(appBar: AppBar());
}

void main() {
  runApp(
    MaterialApp(
      theme: ThemeData.light().copyWith(
        appBarTheme: AppBarTheme(backgroundColor: Colors.green),
      ),
      home: Test(),
    ),
  );
}
```
![Screen Shot 2022-02-03 at 12 22 49 PM](https://user-images.githubusercontent.com/1377460/152422989-6c503626-8a31-4ab1-a522-f1f84cc645c4.png)

**Comment by darshankawar** [comment]
@ishantsehrawat 
Above solution should resolve your issue, so I'll go ahead and close.
If you disagree or have some other use case, write in comments and I'll reopen it.
