### ISSUE TITLE
We seem to be missing a case in our docs where hot restart is required

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#9771]
From user feedback: (https://github.com/flutter/flutter/issues/9761#issuecomment-299022368)

This page may need to be fleshed out... it is not immediately apparent to me that my situation fell under any of the three cases listed here that hot reload doesn't cover, as all I modified was a build function.

https://flutter.io/intellij-ide/#hot-reloads-vs-full-application-restarts

and then "it might be helpful to say something about how hot restart is also a good idea if you make changes to the member data stored in your State. Recreating your States ensures that old classes won't accidentally be used."

**Comment by sethladd** [comment]
@mit-mit can you help us with these docs?

**Comment by mit-mit** [comment]
Resolved with https://flutter.io/hot-reload/
