### ISSUE TITLE
Apple Watch app detection does not work for new Apple Watch projects

### ISSUE THREAD

**Issue by Rexios80** [flutter/flutter#97721]
## Steps to Reproduce

1. Create an Apple Watch app for a Flutter iOS app
2. Attempt to run the app

**Expected results:** 
Flutter detects that the project contains an Apple Watch app and adjusts the build settings accordingly

**Actual results:** 
Flutter cannot detect that new Apple Watch targets created by Xcode exist because the structure of Apple Watch targets changed. The build fails.

**Details**
Currently, Flutter looks for a `WKCompanionAppBundleIdentifier` key in plist files, but that key no longer exists in new Apple Watch projects.

The `watchkitapp` target no longer contains a plist by default, and the `watchkitextension` target contains a plist with the following contents:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>NSExtension</key>
	<dict>
		<key>NSExtensionAttributes</key>
		<dict>
			<key>WKAppBundleIdentifier</key>
			<string>dev.rexios.watchConnectivityExample.watchkitapp</string>
		</dict>
		<key>NSExtensionPointIdentifier</key>
		<string>com.apple.watchkit</string>
	</dict>
</dict>
</plist>
```

**Comment by darshankawar** [comment]
@Rexios80 
Currently Flutter does support Apple watch. See [this](https://github.com/flutter/flutter/issues/2056) issue and relevant comments for your reference.

https://github.com/flutter/flutter/issues/2056#issuecomment-248377630
https://github.com/flutter/flutter/issues/2056#issuecomment-561449188

So I am closing this in favor of above comments and link.

**Comment by Rexios80** [comment]
Uhhh I know. This is an issue with building a flutter app with a bundled Watch app.

**Comment by Rexios80** [comment]
@darshankawar Can you please reopen this?
