### ISSUE TITLE
In icon API docs add filtering and copy-to-clipboard for icon names

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#97727]
Request for the ability to filter icons in API docs by name, and copy the name to clipboard.

https://api.flutter.dev/flutter/cupertino/CupertinoIcons-class.html
https://api.flutter.dev/flutter/material/Icons-class.html

> We've (@bdlukaa and @henry2man) just implemented a new Icon Gallery for **FluentUI toolkit** (https://pub.dev/packages/fluent_ui), you can see it in action:
> 
> 1. Go to https://bdlukaa.github.io/fluent_ui/
> 2. On the side menu, press "Icons"
> 
> <img width="1246" alt="Captura de pantalla 2022-02-03 a las 11 38 05" src="https://user-images.githubusercontent.com/4610108/152326789-4afbc6a2-b4ef-4b9f-9905-6c0202691da1.png">
>
> One of the features I absolutely love from our new Icon gallery is the ability to filter the icons by name (please notice the upper right search box). This feature is inspired by the original Cupertino Icon Gallery ( take the wayback machine and see it in action in https://shuuji3.xyz/flutter-packages/third_party/packages/cupertino_icons/)
>
> Also please take notice of the _click-n-copy-to-clipboard™️_ feature that we've just implemented in FluentUI Icon Gallery (all icons are `Buttons`, every button press copies the full name of the icon into the [clipboard](https://pub.dev/packages/clipboard) ).
>
> So when you combine this two features, the (usually) very heavy task of choosing an icon for your app is now much much easier. 
>
> It could be great to have the Original Cupertino Icon Gallery again, and even better with our _click-n-copy-to-clipboard™️_  feature.

_Originally posted by @henry2man in https://github.com/flutter/flutter/issues/88754#issuecomment-1028847737_

**Comment by henry2man** [comment]
This is the original pull request made for Fluent UI: https://github.com/bdlukaa/fluent_ui/pull/124

The key point was the addition of a `Map<String, IconData>` in order to have something that could be used as a filter.

**Comment by jmagman** [comment]
Split this into two requests, filed:
https://github.com/dart-lang/dartdoc/issues/2932
https://github.com/dart-lang/dartdoc/issues/2933
