### ISSUE TITLE
Packaging recipes need updates

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#97735]
The packaging recipes are called flutter.py in the root directory, this is confusing because the recipe to test flutter/flutter repository is also called flutter.py but it lives inside <root>/flutter folder.

We need to move the recipe to the packaging folder and rename the recipe from flutter to packaging.

In addition to that we also need to make the properties used by packaging recipe consistent with the packaging documentation recipe. This means using `release_ref` property to override the buildbucket parameter which becomes handy when we need manual re-runs.

**Comment by godofredoc** [comment]
\cc @itsjustkevin @christopherfujino

**Comment by CaseyHillers** [comment]
Are these builders also something we can move to `.ci.yaml`? It seems like we can save some flutter/infra maintenance by migrating.

**Comment by christopherfujino** [comment]
> Are these builders also something we can move to `.ci.yaml`? It seems like we can save some flutter/infra maintenance by migrating.

These builders are fundamentally different from all the other builders in that they are only triggered by pushes to a release branch. Obviously we could extend .ci.yaml to support this.

**Comment by godofredoc** [comment]
Changes implemented in: 
https://flutter-review.googlesource.com/c/recipes/+/27101
