### ISSUE TITLE
During "flutter build ipa" add validation to check if app is ready for release

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#97730]
For all of these, either point to the docs, or inline instructions for how to fix it
#### Example warnings
1. App icon is still set to default, point to https://docs.flutter.dev/deployment/ios#add-an-app-icon or in-line how to change
2. App display name is set to package name (the default, probably not right)

#### Informational output
1. Build number https://docs.flutter.dev/deployment/ios#updating-the-apps-version-number
1. Minimum iOS version
2. App display name
2. Other settings from https://docs.flutter.dev/deployment/ios#review-xcode-project-settings

**Comment by jmagman** [comment]
@hellohuanlin you can test `flutter_gallery`
<img width="709" alt="Screen Shot 2022-10-06 at 3 05 27 PM" src="https://user-images.githubusercontent.com/682784/194427182-cb8fa7d7-630f-4413-b384-bfeca8a87c2c.png">


Around here the `xcodeBuildResult` property should be populated.  

https://github.com/flutter/flutter/blob/e99fc8e543fc232dbdef7d2b6defc7a502f1e87e/packages/flutter_tools/lib/src/commands/build_ios.dart#L136

From that you can get the build settings from `xcodeBuildResult.xcodeBuildExecution.buildSettings`. 
 `IPHONEOS_DEPLOYMENT_TARGET` will get you the minimum iOS version.

You can add property to `BuildableIOSApp` to the built `app` `Info.plist` path, then parse the Info.plist to get the "name" `CFBundleExecutable`, the version `CFBundleShortVersionString`, and you could alternatively get `MinimumOSVersion` instead of from the build settings.
https://github.com/flutter/flutter/blob/dcde8163cee7aa351f0ff7a51182e8d050c4b714/packages/flutter_tools/lib/src/ios/application_package.dart#L54-L62

**Comment by hellohuanlin** [comment]
The first approach (build_ios.dart) works. 

For the second approach(application_package.dart), I got the following error before hitting the breakpoint: 
```
Encountered error while creating the IPA:
error: exportArchive: Failed to register bundle identifier
error: exportArchive: No profiles for 'io.flutter.examples.gallery' were found
```
Does this mean that I need to setup Apple dev account (register ID & download profile)?

**Comment by jmagman** [comment]
> Encountered error while creating the IPA:

Exactly, it means you don't have the right certs installed.  For this bug you can ignore that, I think it makes sense to validate when the app archives successfully, even if it fails to create the IPA.

**Comment by hellohuanlin** [comment]
Idea: check for `com.example` placeholder identifier, in case developers forget to update

**Comment by hellohuanlin** [comment]
we may also want to validate the image size of app icons.  Xcode gives warning about the wrong size, but developers may directly replace images without using Xcode (me, for example).

**Comment by hellohuanlin** [comment]
@jmagman another idea is to validate if splash screen (Default.png) is still using template file. Our template seems to be an empty image rather than Flutter icon, so it may be easier for devs to forget.

**Comment by jmagman** [comment]
Thanks for all the work on these PRs, @hellohuanlin!  I'm going to close this meta issue, we can open new individual issues as needed.
