### ISSUE TITLE
PopupMenuButton Example Broken in Master Docs

### ISSUE THREAD

**Issue by justinmc** [flutter/flutter#97745]
The example on this docs page is broken: https://master-api.flutter.dev/flutter/material/PopupMenuButton-class.html

But it works on the stable docs page: https://api.flutter.dev/flutter/material/PopupMenuButton-class.html

**Comment by TahaTesser** [comment]
I have recently updated this example, not sure why it is broken, I will try looking into it

**Comment by justinmc** [comment]
Thanks!
