### ISSUE TITLE
[google_maps_flutter] How do I show the google_maps like a picture(no interaction)?

### ISSUE THREAD

**Issue by SittiphanSittisak** [flutter/flutter#97766]
I tried to use the Stack, the dialog, and the IgnorePointer to block the interaction of the google_maps but it does not work. The google_maps is always on top. 
How do I block the interaction of the google_maps?

**Comment by SittiphanSittisak** [comment]
Example:

https://user-images.githubusercontent.com/59549741/152469925-e3ae9fa5-7def-4037-95f9-f2b9fb6c34a3.mp4

**Comment by darshankawar** [comment]
@SittiphanSittisak 
Your question is better suited for support channels like StackOverflow, so please ask the same there.
Closing from here, as this is more of a code assistance question.
