### ISSUE TITLE
A few fidelity issues with Cupertino dialog

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#9776]
From the OEM toolkit:

![2017-05-03](https://cloud.githubusercontent.com/assets/5479/25682128/d007a388-300b-11e7-8c21-7fc84e80d1d2.jpg)

From Flutter:

![screenshot_20170503-142211](https://cloud.githubusercontent.com/assets/5479/25682173/0c765e72-300c-11e7-8a54-cb8af4d3eac1.png)

![screenshot_20170503-142211](https://cloud.githubusercontent.com/assets/5479/25682180/0f9000a4-300c-11e7-9087-20cc1294cb01.png)

A few things I notice:

* the font size in the description text is smaller than on OEM
* the default answer (e.g. "Don't Allow") isn't bold (it appears to be bold on the OEM version)
* flutter version doesn't use the frosted glass

**Comment by sethladd** [comment]
cc @xster

**Comment by xster** [comment]
The touch target is also incorrect. It's only the text area of the button rather than the entire button surface

**Comment by abarth** [comment]
@xster The frosted glass effect can be done with the https://docs.flutter.io/flutter/widgets/BackdropFilter-class.html widget.

**Comment by xster** [comment]
Thanks
Seth pointed me to http://stackoverflow.com/questions/43550853/how-do-i-do-the-frosted-glass-effect-in-flutter as well :)

Sorry to keep bugging you on Sunday :S

**Comment by xster** [comment]
Just missing #9874 but otherwise done.
