### ISSUE TITLE
Flutter Doctor reports an error with IntelliJ IDEA Community Edition

### ISSUE THREAD

**Issue by dumanli** [flutter/flutter#97779]
IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message
      below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)

IntelliJ IDEA 2021.3.2 (Community Edition)
Build #IC-213.6777.52, built on January 28, 2022
Runtime version: 11.0.13+7-b1751.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.13.0-28-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 1988M
Cores: 8
Registry:
    documentation.show.toolbar=true

Non-Bundled Plugins:
    org.jetbrains.intellij.scripting-javascript (1.0)
    net.antelle.intellij-xcode-dark-theme (1.2.4)
    com.vecheslav.darculaDarkerTheme (1.2.0)
    com.samdark.intellij-visual-studio-code-dark-plus (2.5)
    com.markskelton.one-dark-theme (5.4.2)
    com.karateca.jstoolbox (1.10)
    PythonCore (213.6777.52)
    Dart (213.5744.122)
    io.flutter (63.2.4)

Kotlin: 213-1.5.10-release-949-IJ6777.52
Current Desktop: ubuntu:GNOME

**Comment by darshankawar** [comment]
@dumanli 
The fix is currently available on master and will be rolled out in beta and stable per Flutter's release guidelines.
See https://github.com/flutter/flutter/issues/94060#issuecomment-1018801980 issue comment for your reference.
Closing this as a duplicate.
