### ISSUE TITLE
Git error. Command: with exit code 128

### ISSUE THREAD

**Issue by zionnite** [flutter/flutter#97780]
Hello everyone, 

attempting to use this package in my flutter application 

```
plain_notification_token:
    git:
      url: git@github.com:zionnite/plain_notification_token.git
```

![Screen Shot 2022-02-04 at 9 02 00 AM](https://user-images.githubusercontent.com/10984801/152496010-93a70922-4ba2-470f-9644-cc3294649491.png)

Have deleted `/.pub-cache` yet error still persist

please what do I need to Do?

**Comment by zionnite** [comment]
I was able to resolve this error and I change the code to this

```
  plain_notification_token:
    git:
      url: https://github.com/zionnite/plain_notification_token.git
```
I was able to run the `pubspec.yaml` 
![Screen Shot 2022-02-04 at 9 48 18 AM](https://user-images.githubusercontent.com/10984801/152501941-9134adef-02ba-4fac-8597-fbbdf0efbcc7.png)
file but I encounter another issue while running the flutter app for android

below is the screenshot

**Comment by darshankawar** [comment]
The errors are pointing to the third party plugin you are using, so you'll need to report it in dedicated repo: https://github.com/kikuchy/plain_notification_token/issues

Closing from here, as this isn't a Flutter issue.
