### ISSUE TITLE
Show video in OS Windows

### ISSUE THREAD

**Issue by Mullexoll** [flutter/flutter#97794]
How i can show video in my flutter project in OS Windows?

**Comment by darshankawar** [comment]
@Mullexoll 
By `video` are you referring to `video_player` ? If so, the plugin doesn't yet support on Windows. You can check out the list of plugins supported on Windows here: https://medium.com/flutter/announcing-flutter-for-windows-6979d0d01fed

Closing from here. If this isn't a correct interpretation of your quetion, write in comments and I'll reopen, or ask support questions on StackOverflow.
