### ISSUE TITLE
Fixed header in WebView flutter

### ISSUE THREAD

**Issue by soukainader** [flutter/flutter#97809]
I'm new to flutter and I'm making a hybrid app with flutter and I removed the footer, but I want to fix the header and I don't know how doing it please can someone help me!!!!

**Comment by stuartmorgan** [comment]
Please see https://flutter.dev/community#community-grid for resources where you can get help with your own projects; the issue tracker is for bug reports and feature requests in Flutter itself.

Closing as this is not a Flutter issue.
