### ISSUE TITLE
import Java library (.jar) as dependencies to Flutter Windows JVM

### ISSUE THREAD

**Issue by Dargoz** [flutter/flutter#97804]
## Proposal

I've an old library, written in Java. When I created JVM based apps it's make me still can use my library and create a Desktop Apps (like using Compose Desktop Application and add dependencies through gradle).
reference : https://www.jetbrains.com/lp/compose-mpp/
Is it possible for Flutter to have that kind of features ?

**Comment by stuartmorgan** [comment]
A Flutter Windows application has no JVM; adding it would make a simple application *much* larger (approximately 5x IIRC), and add a lot of startup and memory overhead, for a feature almost nobody would use.

If you want to modify your own project to package and load the JVM you could, but it's not something that would be built into Flutter.

(/cc @cbracken FYI)
