### ISSUE TITLE
Windows Desktop build saving build file "app.so" in wrong folder

### ISSUE THREAD

**Issue by starkc1** [flutter/flutter#97814]
## Steps to Reproduce
1. Create new Flutter App
2. Run Flutter App on Desktop without changing anything
3. Gets Error "Can't load AOT data from ..\build\windows\runner\Debug\data\app.so no such file."

## Issue Discovered
1. Found that the app.so is being placed in the build\windows folder
![BuildResults](https://user-images.githubusercontent.com/19864910/152578807-6830bbdf-fc40-4505-8217-1f88616df7cf.png)

## Steps Taken Already
1. Tried running in chrome as web app, works without issue
2. Moved the app.so manually to the correct location, works without issue, but rebuilds make a new app.so in the wrong location

Expected results: Application Running

Actual results: Crashes Looking for app.so file

**Comment by starkc1** [comment]
Found a Fix for this. I was running Visual Studio 2022 Preview.
Uninstalling and installing Visual Studio 2022, seemed to fix the issue

**Comment by irufano** [comment]
Try to update windows sdk to 10(10.0.20348.0) version

**Comment by stuartmorgan** [comment]
I'm hiding the problematic workarounds posted above. Copying files to locations that aren't supposed to exist in the first place is a bad idea, and will cause other, more subtle problems.
