### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: The system cannot find the file specified., errno = 2

### ISSUE THREAD

**Issue by drajtechs** [flutter/flutter#97816]
## Command
```
flutter pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot open file, OS Error: The system cannot find the file specified.
, errno = 2
```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:539:18)
#3      _File.readAsStringSync (dart:io/file_impl.dart:584:18)
#4      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:96:16)
#5      ErrorHandlingFile.readAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:209:22)
#6      _runSync (package:flutter_tools/src/base/error_handling_io.dart:556:14)
#7      ErrorHandlingFile.readAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:208:12)
#8      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:240:50)
<asynchronous suspension>
#9      PackagesGetCommand._runPubGet (package:flutter_tools/src/commands/packages.dart:130:7)
<asynchronous suspension>
#10     PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:163:5)
<asynchronous suspension>
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#15     CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
```
```
[✓] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19044.1466], locale en-US)
    • Flutter version 2.0.5 at C:\src\flutter
    • Framework revision adc687823a (10 months ago), 2021-04-16 09:40:20 -0700
    • Engine )
    • Android SDK at C:\Users\Dr Aj\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_321-b07)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.63.2)
    • VS Code at C:\Users\Dr Aj\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.34.0

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 97.0.4692.99
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 97.0.1072.76

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.1+2
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 1aafb3a8b9b0c36241c5f5b34ee914770f015818
### Plugins
facebook_audience_network-0.9.0
firebase_auth-0.20.1
firebase_auth_web-0.3.3
firebase_core-0.7.0
firebase_core_web-0.2.1+3
firebase_messaging-8.0.0-dev.15
firebase_messaging_web-0.1.0-dev.6
flutter_facebook_auth-1.0.2+2
flutter_inappwebview-4.0.0+4
flutter_local_notifications-4.0.1+2
flutter_native_admob-2.1.0+3
fluttertoast-7.1.8
gdpr_dialog-2.0.1
get_version-0.2.2
google_mobile_ads-0.12.1
google_sign_in-4.5.9
google_sign_in_web-0.9.2
image_gallery_saver-1.6.9
image_picker-0.6.2
import_js_library-1.0.2
in_app_review-1.0.4
package_info-0.4.3+4
path_provider-1.6.28
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+8
path_provider_windows-0.0.5
permission_handler-5.0.1+2
receive_sharing_intent-1.4.5
share-0.6.5+4
shared_preferences-0.5.12+4
shared_preferences_linux-0.0.2+4
shared_preferences_macos-0.0.1+11
shared_preferences_web-0.1.2+7
shared_preferences_windows-0.0.2+3
sqflite-2.0.0+3
url_launcher-5.7.10
url_launcher_linux-0.0.1+4
url_launcher_macos-0.0.1+9
url_launcher_web-0.1.5+3
url_launcher_windows-0.0.1+3
video_player-1.0.1
video_player_web-0.1.4+1
video_thumbnail-0.2.5+1
wakelock-0.2.1+1
wakelock_web-0.1.0+3
webview_flutter-1.0.7

**Comment by iapicca** [comment]
dupe? https://github.com/flutter/flutter/issues/97416
also @drajtechs you may want to run `flutter upgrade -f`

**Comment by darshankawar** [comment]
@iapicca Hi,
The one you linked has `WebDevFS.update (package:flutter_tools/src/isolated/devfs_web.dart:833:57)` log entry pointing to web, so it may not be dup.

This one seems to be coming from `pub` command `_DefaultPub.get (package:flutter_tools/src/dart/pub.dart:240:50)`.

@drajtechs As suggested above, before we label, first try to upgrade to latest stable and run the command again to see if you still get same crash or not.
