### ISSUE TITLE
Make Material AppBar search aware

### ISSUE THREAD

**Issue by xster** [flutter/flutter#9783]
Make this https://github.com/flutter/flutter/blob/b586a97ad25cd5d33b98573ef207578707a09f46/examples/stocks/lib/stock_home.dart#L286

Should probably handle auto suggests too

See also:
https://material.io/guidelines/patterns/search.html#search-in-app-search

**Comment by Hixie** [comment]
For the people who have marked this thumbs-up, what exactly do you want this to entail beyond what the stocks app does?

cc @willlarche

**Comment by xster** [comment]
For me, the main thing is Expandable search in https://material.io/guidelines/patterns/search.html#search-in-app-search (which seems more or less what the stock app does)

**Comment by goderbauer** [comment]
I believe that's implemented now with https://github.com/flutter/flutter/pull/17629?

**Comment by xster** [comment]
yay, awesome
