### ISSUE TITLE
[pigeon] implement nullsafe generics

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#97848]
Internal: b/292548232

Right now all type arguments have to be nullable for generic type arguments.  We should support non-null arguments.

**Comment by marianhlavac** [comment]
Does this include using enums as a type? We've seem to be struggling with having non-null enum types, but it might be a different issue.

**Comment by gaaclarke** [comment]
@marianhlavac better enum support is on our radar, there should be an issue for it.  That'd probably be implemented separately though.
