### ISSUE TITLE
Make a CupertinoSearchBar

### ISSUE THREAD

**Issue by xster** [flutter/flutter#9784]
See https://developer.apple.com/design/human-interface-guidelines/search-fields

Android sister request #9783. 

cc @sethladd

**Comment by xster** [comment]
This is in our list of immediate next things to do

**Comment by AppleEducate** [comment]
Looking forward to this!

**Comment by kerberjg** [comment]
@xster Any progress? Would you be potentially accepting PRs for this?

**Comment by xster** [comment]
Sure, we'd be happy to take PRs for it.

**Comment by mana-ai** [comment]
Does CupertinoSearchBar exist in flutter release now?

**Comment by EliasDeuss** [comment]
> Does CupertinoSearchBar exist in flutter release now?

Nope :(

**Comment by neckaros** [comment]
Does this include the fact that it should work with the Cupertino (sliver) AppBar ? Like for example in the contacts app

**Comment by UXDart** [comment]
is it possible to use this search bar atm? how? it was removed from "goals" what that means exactly? TIA

**Comment by UXDart** [comment]
should we use cupertion_controllers package? will be this included into flutter sdk?

**Comment by MichaelPriebe** [comment]
It seems like there is a Cupertino Search Bar in https://pub.dev/packages/native_widgets, but I literally cannot tell you how it works because it seems like it just doesn't...

**Comment by EliasDeuss** [comment]
@xster Will this get an updated milestone?

**Comment by AlexMeuer** [comment]
> This is in our list of immediate next things to do

What's the status of this? Is there any point waiting around for it or should we opt for other solutions?

**Comment by berrylawchingman** [comment]
No 1 location as said

**Comment by mahjiang** [comment]
Also looking forward to this. Any updates?

**Comment by DanielEdrisian** [comment]
I've been tasked with taking care of this. I'll assume the earliest this will be available is in 1 month. @AlexMeuer 

Just getting started haha. Will update you guys!

**Comment by AlexMeuer** [comment]
Fantastic. Let me know if you need/want any input.

**Comment by DanielEdrisian** [comment]
Ok, progress update: Got something that looks kinda like the UISearchTextField

https://youtu.be/ZoTgPsaMu6U

Some UI necessities going forward:
- [ ] Icons should increase/decrease with system font. Currently, this is not supported and I've only hard-coded the size of the search and x icons. Tracking here: https://github.com/flutter/flutter/issues/67792#issuecomment-707240962
- [ ]  UIKit's UITextField has differing content insets for both placeholders/text and cursor position. This isn't necessary for the search control to work, but it should be dealt with. Tracking here: https://github.com/flutter/flutter/issues/67951 The default font is also slightly narrower than what's seen in Flutter. Tracking here: https://github.com/flutter/flutter/issues/67953
- [ ] Add bookmark button option
- [ ] Make a search bar and add the search field to it
- [ ] Add a cancel button to the search field's trailing

Will keep you updated.

**Comment by xster** [comment]
That comparison tool is sooooo useful :D 
Solid!

**Comment by b3nni97** [comment]
Are you also working on a Sliver version of it?

**Comment by DanielEdrisian** [comment]
[CupertinoSearchTextField](packages/flutter/lib/src/cupertino/search_field.dart) is now available for use.

This doesn't yet support a sliver version. Working on that part soon.

**Comment by adeolaex** [comment]
> [CupertinoSearchTextField](packages/flutter/lib/src/cupertino/search_field.dart) is now available for use.
> 
> This doesn't yet support a sliver version. Working on that part soon.

It seems the link is broken. 

I also tried going through the official documentation, but it also returns the default `firebase page not found`
An updated link would be appreciated. 

<img width="1174" alt="Screenshot 2020-11-14 at PM 3 08 23" src="https://user-images.githubusercontent.com/42682873/99148969-44b5b200-268b-11eb-9849-482fdf34fe56.png">

**Comment by Alleckz** [comment]
@adeolaex Its in the Cupertino folder on GitHub. 
[https://github.com/flutter/flutter/blob/dev/packages/flutter/lib/src/cupertino/search_field.dart](url)

Currently only in the dev channel/branch.  [What is a channel in flutter?](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels)

**Comment by adeolaex** [comment]
@Alleckz Thanks for clarification. 

For a second there, the link you provided was opening up the issues page of flutter.

**Comment by Alleckz** [comment]
@adeolaex No problems. Ye, missed copying the link in the actual url filed inside the brackets. Fixed it directly.

**Comment by xster** [comment]
The api.flutter.dev site reflects the stable branch (where CupertinoSearchTextField isn't present on yet). See https://master-api.flutter.dev/flutter/cupertino/CupertinoSearchTextField-class.html for the doc on master/dev channels.

**Comment by Piinks** [comment]
The recently added atomic header slivers can achieve the scrolling effect of the search bar in the settings app, so we might not need a brand new scrolling version of https://master-api.flutter.dev/flutter/cupertino/CupertinoSearchTextField-class.html.

There is some sample code that shows how to achieve the Settings app revealing search bar here:
https://github.com/flutter/flutter/blob/master/examples/api/lib/widgets/sliver/pinned_header_sliver.1.dart

CupertinoSearchTextField might just need an update, or a new widget could wrap it with the new slivers we have for the effect.

Updated HIG is in: https://developer.apple.com/design/human-interface-guidelines/search-fields

There is a SearchBar widget in the material library now, would be worth looking to see if/where there are opportunities to align the two (with either the existing cupertino one or a new one - which might also help us decide what to do here).

**Comment by victorsanni** [comment]
@Piinks should this issue be closed to focus on the sliver requirements in https://github.com/flutter/flutter/issues/18103? Looks like this should have been closed by https://github.com/flutter/flutter/pull/68074.
