### ISSUE TITLE
flutter create fails (on certain project names)

### ISSUE THREAD

**Issue by cryptobrains** [flutter/flutter#97842]
Flutter seems to get confused about version dependencies when creating  a new blank project.

Steps to recreate:

`flutter create clock`

error message:

**Because clock depends on flutter_test from sdk which depends on clock 1.1.0, clock 1.1.0 is required.
So, because clock is 1.0.0+1, version solving failed.**

Results of

`flutter doctor -v`

[✓] Flutter (Channel stable, 2.10.0, on Mac OS X 10.15.7 19H1713 darwin-x64, locale en-CA)
    • Flutter version 2.10.0 at /Users/localuser/Dev/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (3 days ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/localuser/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Users/localuser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8092744/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Users/localuser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8092744/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] IntelliJ IDEA Ultimate Edition (version EAP IU-221.3427.89)
    • IntelliJ at /Users/localuser/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-1/221.3427.89/IntelliJ IDEA 2021.3 EAP.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.7 19H1713 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 97.0.4692.99

[✓] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by cryptobrains** [comment]
Expected behaviour: if the name is reserved it should not be creatable and an explicative error message should be shown instead of this.

**Comment by stuartmorgan** [comment]
Dart packages are a flat, global namespace. That means you cannot have two packages with the same name within the same project.

> Expected behaviour: if the name is reserved [...]

It's not reserved, it just happens to be the same as a package that you have a (transitive) dependency on. If you picked the name of a different existing package that you didn't depend on, then you'd be fine (unless you later tried to depend on it, at which point you'd have the same problem).

> an explicative error message should be shown instead of this.

Improvements to error messages in `pub get` resolution, which is what that error is, would need to be filed against pub: https://github.com/dart-lang/pub
