### ISSUE TITLE
pub publish on a plugin has warning

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#9785]
While `pub publish`ing a plugin I was given the following warning:

```
Suggestions:
* Don't depend on "flutter" from the sdk source. Use the hosted source instead. For example:

  dependencies:
    flutter: ^0.0.20

  Using the hosted source ensures that everyone can download your package's dependencies along with your package.

Package has 1 warning. Upload anyway (y/n)?
``` 

The offending line was generated by `flutter create --plugin`. Should I follow the suggestion? If yes, should we update what `flutter create --plugin` generates? Can we document somewhere what to do?

/cc @mit-mit

**Comment by mit-mit** [comment]
cc @szakarias @jakobr-google

**Comment by jakobr-google** [comment]
The warning is wrong. The "hosted" flutter package is just a very empty placeholder, and using sdk is correct. We should make sure pub doesn't emit this warning for flutter.

Which version of pub did you use?

**Comment by mit-mit** [comment]
We are also seeing this with `<flutter sdk dir>/bin/cache/dart-sdk/bin/pub`. We probably need to "teach" `pub` about this special case.

**Comment by mit-mit** [comment]
@kasperl @kevmoo any idea who might be able to help with this?

**Comment by goderbauer** [comment]
Looks like this warning is gone? At least I didn't see it when I just updated a bunch of plugins on pub.

**Comment by mit-mit** [comment]
@kevmoo did anything change in pub?

**Comment by mit-mit** [comment]
Yes, I think this is fixed. I tried with a fresh plugin and no warnings anymore. Closing.
