### ISSUE TITLE
how to implement Lazyload in Flutter ListView like whatsapp chat screen

### ISSUE THREAD

**Issue by krishnaaroNowapps** [flutter/flutter#97857]
I'm aware of typical lazy load functionality, now am trying to understand how **WhatsApp chat screen** fetching old chats if we scroll to top.

similarly I wanted to do **'lazy load' on reaching the top** of the conversation. in my case assume 10,000 conversations(Obviously can't fetch all 10k items in one shot) in a chat where stored in local.

Initially i'm fetching latest 250 records and auto scrolled to last item in `ListView.Builder()`.

have no clue how the fetch remaining conversations on the top of the List.

Please help me out to implement Lazy load here, looking forward for the solution.

**Comment by darshankawar** [comment]
@krishnaaroNowapps 
Your question is better suited for support channels like StackOverflow, so please ask the same there.
Closing from here since this is more of a code assistance question.
