### ISSUE TITLE
Use wasm?

### ISSUE THREAD

**Issue by godalming123** [flutter/flutter#97868]
## Use case

If you are using flutter web it can be quite slow.

## Proposal

You could use wasm (web assembly) I understand this may be a big port and hard to make dart compile into wasm but if this is possible it would be nice to track possible progress

**Comment by iapicca** [comment]
dupe https://github.com/flutter/flutter/issues/41062

although I don't agree with this statement
```
If you are using flutter web it can be quite slow.
```

**Comment by godalming123** [comment]
Ok
