### ISSUE TITLE
update android and ios folder   with  flutter  commend 

### ISSUE THREAD

**Issue by samithe7** [flutter/flutter#97879]
If there is a way to update  android and ios folder  auto that will be great. today i run  my flutter  app new android 12  amulator . this  show  an error  .after  try lot of thing  i  know i have to add  android:exported="true"  to   android\app\src\main\AndroidManifest.xml
file .

**Comment by darshankawar** [comment]
@samithe7 
Your description isn't clear so I am not sure what is the issue you are facing. Please elaborate with a use case and a code sample if possible.
