### ISSUE TITLE
Link moved on documentation

### ISSUE THREAD

**Issue by egemensoylu** [flutter/flutter#97870]
In documentation at [8. Set up basic security rules](https://firebase.google.com/codelabs/firebase-get-to-know-flutter#7)
Paragraph 3 - Instruction 1. has a link. 

In the Firebase console's Develop section, click Database, and then select the Rules tab (or [click here](https://console.firebase.google.com/project/_/database/firestore/rules) to go directly to the Rules tab).

when you follow the link, popup message appears says : "Link moved, update your bookmarks"

**Comment by danagbemava-nc** [comment]
Duplicate of #92905
