### ISSUE TITLE
Add Color Property to PopupMenuDivider()

### ISSUE THREAD

**Issue by behzodfaiziev** [flutter/flutter#97887]
## Use case
While improving dark mode of my app, I found that PopupMenuDivider() widget does not provide color property to be changed depending on theme mode.

## Proposal

This is the code (lib/src/material/popup_menu.dart) I made as a workaround and could have extracted this widget to my project file. However, I will have to always copy this widget everywhere where I have my apps. So,  I would like to have color property available by default.

 ```
const Duration _kMenuDuration = Duration(milliseconds: 300);
const double _kMenuCloseIntervalEnd = 2.0 / 3.0;
const double _kMenuHorizontalPadding = 16.0;
const double _kMenuDividerHeight = 16.0;
const double _kMenuMaxWidth = 5.0 * _kMenuWidthStep;
const double _kMenuMinWidth = 2.0 * _kMenuWidthStep;
const double _kMenuVerticalPadding = 8.0;
const double _kMenuWidthStep = 56.0;
const double _kMenuScreenPadding = 8.0;
const Color _kMenuDividerColor = Color(0xFF212121);   //Added this color as default. Any color can be.
 ```

 ```
class PopupMenuDivider extends PopupMenuEntry<Never> {

  const PopupMenuDivider(
      { Key? key, this.height = _kMenuDividerHeight, this.color = _kMenuDividerColor})
      : super(key: key);

  @override
  final double height;
  final Color color;


  @override
  bool represents(void value) => false;

  @override
  State<PopupMenuDivider> createState() => _PopupMenuDividerState();
}

class _PopupMenuDividerState extends State<PopupMenuDivider> {
  @override
  Widget build(BuildContext context) =>
      Divider(height: widget.height, color: widget.color);
}
 ```

## Results 

Before 
![BEFORE](https://user-images.githubusercontent.com/63793311/152662235-811cc552-128d-4a39-9d70-35e77c51182d.png)

After
![AFTER](https://user-images.githubusercontent.com/63793311/152662241-14e0f814-2606-4efa-bb49-268f3e0d5372.png)

**Comment by danagbemava-nc** [comment]
Hi @behzodfaiziev, I believe you should be able to use the `DividerTheme` to update the color of the `PopupMenuDivider` considering the `PopupMenuDivider` just ends up drawing a `Divider`. 

Does that not suffice?

**Comment by behzodfaiziev** [comment]
@danagbemava-nc  Thanks for clarifying that! 
I was trying to change `popupMenuTheme` to update color, instead of `DividerTheme`
Also, I could use `dividerColor` to change it accordingly to the theme mode.
