### ISSUE TITLE
Bundling SKSL shaders in iOS app causes very long delay on first launch

### ISSUE THREAD

**Issue by doppio** [flutter/flutter#97884]
I started noticing extremely long startup times when my app is first launched on iOS. I tracked it down to the fact that I'm now including my SKSL shaders as suggested by [the official documentation](https://docs.flutter.dev/perf/rendering/shader) to prevent jank. When I do not bundle the shaders, I don't have this issue, at the cost of extreme UI jank.

My app sits on the splash screen for about 6 seconds on first launch, which is a really poor first impression for my users. On subsequent launches, Flutter renders its first frame nearly instantaneously. I notice that the documentation mentions startup latency due to precompiling the shaders, but is 6000ms to be expected on a somewhat modern device? I worry a lot of users will download the app and dismiss it as broken.

I've provided my shader file in the repro steps below. It was generated by running my app on an iPhone X. The JSON file is 702 KB -- not sure if this is a typical size. My equivalent Android SKSL JSON file is 289 KB. Android does not have the same startup delay issue.

I'm on the most recent stable build of Flutter, and this seems to happen with earlier releases as well.

## Steps to Reproduce

1. Download [the JSON data](https://gist.githubusercontent.com/doppio/f4615b0e9510f3f03090c65b73acf0b5/raw/4548d6c3e97b0aa0a0038a60ae60e6bc1d3b9ee4/ios_sksl_shaders.json) of my pre-compiled SKSL shaders.
2. Create an empty Flutter project.
3. Run the Flutter project on a real iOS device in profile/release mode with the additional argument `--bundle-sksl-path=ios_sksl_shaders.json`, pointing to the correct path where you've downloaded the provided JSON.
4. Notice that the white splash screen remains visible for a very long time. In my testing, it's approximately 6 seconds on an iPhone X.
5. Close the app and relaunch it.
6. Notice that the app launches almost instantaneously on subsequent launches.

<details>
flutter doctor -v

```
[✓] Flutter (Channel stable, 2.10.0, on macOS 12.1 21C52 darwin-x64, locale en-US)
    • Flutter version 2.10.0 at /Users/bryson/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (4 days ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/bryson/Library/Android/sdk
    • Platform android-31, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.64.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (3 available)
    • iPhone X (mobile) • 8ca2a91e9a7b3818f0cd37d0aa1c08b65921f2a9 • ios            • iOS 15.2.1 19C63
    • macOS (desktop)   • macos                                    • darwin-x64     • macOS 12.1 21C52 darwin-x64
    • Chrome (web)      • chrome                                   • web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by techouse** [comment]
Strange. I do this all the time and do not notice anything like this.

My iOS SkSl is somewhere around 600-650 KB and I generate it on my iPhone 13 Pro Max. The app launches flawlessly on my iPhone 13 Pro Max and on my colleague's very old iPhone 6S.

**Comment by doppio** [comment]
I wonder if there's some specific shader in here that is especially expensive to compile. I don't think I'm doing anything too "special" -- the fanciest things I have are a few Rive animations and some SVG images.

**Comment by techouse** [comment]
You could try eliminating screen by screen and see where it starts killing the app.

**Comment by darshankawar** [comment]
@doppio 
I do see the same behavior as you reported. I ran a sample app in release mode on iPhone 6s (OS 14.4.1) and observed white screen for ~6 to 7 seconds.


https://user-images.githubusercontent.com/67046386/152781620-637f5ae9-bbda-48df-8276-b78117206042.MP4

But per above comment, try to see if any of the animations and svg images you mentioned earlier could be causing this delay or not.

**Comment by doppio** [comment]
I've experimented with this, and here's what I've found so far:

My modal dialogs have a blurred background, which I was animating as part of their transition. Not animating the blur value leads to a significant improvement, but simply having the blur there still seems to contribute a noticeable delay to first startup.

Not caching the shaders for my Rive animations reduces the first launch startup time by a second or so. This isn't a great option for me, since the Rive animations are used as part of onboarding, when it's critical to avoid jank.

**Comment by darshankawar** [comment]
@doppio 
So can we just use the same json file again or have you trimmed it down to minimize the delay ? If so, can you provide updated json ?

**Comment by doppio** [comment]
Here's my current JSON file, which was generated after removing the animation to the background blur: [ios_sksl_shaders.json](https://gist.githubusercontent.com/doppio/8cbfa7dbc30cbf35f0091fb45f8fef6d/raw/ce0d7cb9369e4a51796b862e5febb9eb9993a502/ios_sksl_shaders.json)

There's still a significant delay from my Rive animations, blurred (but not animated) background, and general app use. But it seems to cut off a few seconds of startup time compared to the original JSON I provided.

**Comment by darshankawar** [comment]
Thanks for the update. I do see ~ 7 seconds to load the home screen, as shown below:


https://user-images.githubusercontent.com/67046386/153542724-3d14a27e-b3c3-4307-81f3-7735f21d4545.mov

Verified on stable 2.10.0 version in release mode.

<details>
<summary> stable flutter doctor -v </summary>

```

[✓] Flutter (Channel stable, 2.10.0, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.10.0 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (9 days ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 14.4.1 18D61
    • macOS (desktop)           • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

</details>

**Comment by armandojimenez** [comment]
My ios app generates a 1 MB .json and it takes 5 seconds to show the first Flutter frame, a first bad impression. Is there any solution for this?

**Comment by jonahwilliams** [comment]
The solution for this is to use impeller. You should not bundle shaders with Impeller, it will do nothing. if you are having issues switching to impeller, please file a new bug this. We do not intended to do any work to make SkSL shader bundles faster/smaller.
