### ISSUE TITLE
Installation Instructions for Flutter plugins on pub are incorrect

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#9788]
The "Installing" tab on https://pub.dartlang.org/packages/firebase_messaging says I need to run `pub get` to install a plugin in my app. That's incorrect/misleading and doesn't work:

```shell
C:\src\example_app> pub get
Resolving dependencies...
The Flutter SDK is not available.
Depended on by:
- example_app
```

**Comment by mit-mit** [comment]
Hmm, will need to fix that!

For now, though, can you update the readme.md to have the first line under usage here:
https://pub.dartlang.org/packages/url_launcher

**Comment by mit-mit** [comment]
Tracking in https://github.com/dart-lang/pub-dartlang-dart/issues/125

**Comment by sethladd** [comment]
Cc @kevmoo

**Comment by mit-mit** [comment]
This was fixed!
