### ISSUE TITLE
FloatingActionButtons don't look like material speced ones

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#9789]
The new shadows for the floating action button have shifted significantly down and to the right and don't seem to match the material design's site for shadows: https://material.io/guidelines/material-design/elevation-shadows.html#elevation-shadows-shadows

old:
![old](https://cloud.githubusercontent.com/assets/142874/25686729/5525ebec-3025-11e7-8c48-da2d5847d7e1.jpg)

new:
![new](https://cloud.githubusercontent.com/assets/142874/25686733/595c90f8-3025-11e7-8890-65817fac0caa.jpg)

**Comment by abarth** [comment]
@jason-simmons Looks like something is off with the geometry computation.

**Comment by eseidelGoogle** [comment]
Do we need to resolve this before I/O?  FYI @sethladd

**Comment by apwilson** [comment]
I think this was fixed. Closing.
