### ISSUE TITLE
Flutter localizations not working on a shared plugin

### ISSUE THREAD

**Issue by svprdga** [flutter/flutter#97899]
## Steps to Reproduce

1. Create a flutter plugin and apply localizations following the [official documentation](https://docs.flutter.dev/development/accessibility-and-localization/internationalization).
2. In the example app within the plugin, also apply localizations.
3. Try to show a localized string from the library in the example app.

**Expected results:** 
The app executes and can handle both the app and library localizations.

**Actual results:** 
The app can't compile, the lib localizations can't be found

**Error message:**
```
../lib/plugin_translations.dart:5:8: Error: Error when reading '.dart_tool/flutter_gen/gen_l10n/lib_localizations.dart': No such file or directory
import 'package:flutter_gen/gen_l10n/lib_localizations.dart';
```

**Reproducible example:**
https://github.com/svprdga/flutter-plugin-localizations-issue

**Comment by danagbemava-nc** [comment]
Hi @svprdga, a similar issue was reported in https://github.com/flutter/flutter/issues/70840. Can you take a look at the thread to see if you're able to find a solution? 

This comment might help https://github.com/flutter/flutter/issues/70840#issuecomment-732548224

There's also an open issue to document how to use Internationalization with plugins and modules in https://github.com/flutter/flutter/issues/71911, you may thumbs up, so it gets more attention.

**Comment by svprdga** [comment]
Hi @danagbemava-nc, as commented in the thread that you suggested, I could accomplish the task by using the CLI instead of the configuration file.

Regarding the use of the configuration file, I don't really know if it's a bug or a misconfiguration from my side.

**Comment by danagbemava-nc** [comment]
> Regarding the use of the configuration file, I don't really know if it's a bug or a misconfiguration from my side.

Based on https://github.com/flutter/flutter/issues/70840#issuecomment-735453729, it seems like using the cli is the right way to go about it.

**Comment by svprdga** [comment]
> > Regarding the use of the configuration file, I don't really know if it's a bug or a misconfiguration from my side.
> 
> Based on [#70840 (comment)](https://github.com/flutter/flutter/issues/70840#issuecomment-735453729), it seems like using the cli is the right way to go about it.

OK, then I guess that the issue is resolved.

For future reference, the following command can create dart translation files successfully in a shared dependency:
`flutter gen-l10n --arb-dir=assets/l10n --template-arb-file=strings_en.arb --output-localization-file=app_localizations.dart --output-class=AppLocalizations --output-dir=lib/l10n --no-synthetic-package`
