### ISSUE TITLE
ListTile title East Asian text cannot be aligned on the WEB

### ISSUE THREAD

**Issue by gaowanliang** [flutter/flutter#97901]
Alphabetic characters are aligned normally, even including Arabic, but East Asian languages, including Chinese, Japanese, and Korean, are not centered. But it is normal on both Android and Windows side.

* Browser: Microsoft Edge
* Flutter version: 2.10.0
```dart
ListTile(
                  leading: SvgPicture.asset(
                    "assets/icons/menu_dashbord.svg",
                    color: Colors.white54,
                    height: 16,
                  ),
                  title: const Text(
                    "测试",//"テスト" ,"테스트"
                    style: TextStyle(color: Colors.white54),
                  ),
                )
```
![image](https://user-images.githubusercontent.com/41822468/152680384-834f0dcc-931a-4aaf-97df-b5c96e6ecd2b.png)
![image](https://user-images.githubusercontent.com/41822468/152680361-8731c88a-8cab-4341-b718-fc8e26805deb.png)
![image](https://user-images.githubusercontent.com/41822468/152680404-f9ae2113-332b-479b-b731-541a08c58f16.png)
![image](https://user-images.githubusercontent.com/41822468/152680411-45d223be-cdcb-4347-8adb-88b5974defa3.png)

**Comment by darshankawar** [comment]
@gaowanliang 
Although I didn't try the same on Edge, but can you try below code sample on same browser and see if you still get mis aligned behavior ?

```
return Scaffold(
      appBar: AppBar(
      ),
      body: Center(
        child: ListView(
          children: const <Widget>[
            Card(
              child: ListTile(
                leading: FlutterLogo(),
                title: Text('测试'),
              ),
            ),
            Card(
              child: ListTile(
                leading: FlutterLogo(),
                title: Text('Test'),
              ),
            ),
            Card(
              child: ListTile(
                leading: FlutterLogo(),
                title: Text('Test'),
              ),
            ),
         
            Card(
              child: ListTile(
                leading: FlutterLogo(),
                title: Text('测试'),
              ),
            ),
         
            Card(
              child: ListTile(
                leading: FlutterLogo(),
                title: Text('测试'),
              ),
            ),
          ],
        )
      ),
    );
```

With above code running on mac (chrome and safari), I see expected alignment:

<img width="186" alt="Screenshot 2022-02-07 at 5 25 26 PM" src="https://user-images.githubusercontent.com/67046386/152784059-35aff6b6-c12e-451e-b540-b032fbb485dd.png">

**Comment by gaowanliang** [comment]
I think this may be related to the English and Chinese top and bottom are not equal in width, the English top and bottom seem to be almost equal in width, while the Chinese obviously not equal in width.
![image](https://user-images.githubusercontent.com/41822468/152792509-887560b9-c32b-4eff-9db5-ffde56da1c50.png)
![image](https://user-images.githubusercontent.com/41822468/152792527-8ad94484-f722-4a12-b305-b73539df64c0.png)

**Comment by darshankawar** [comment]
@gaowanliang 
But are you able to see the misalignment still using the provided code or not ?
The one you pointed out above could be a different issue.

**Comment by gaowanliang** [comment]
@darshankawar The effect I saw was similar to the one you've shown, so I didn't attach mine again.
As for you thinking this is a separate issue, I think that's where the main problem lies. I notice that the top half of the English and Chinese are almost the same size in terms of distance. The image I showed at the beginning had the same feel to it. But the default size Chinese has a significantly larger font than the English, resulting in the bottom half being squeezed out very small. So visually it doesn't look centred, and the image I'm showing is only made more obvious by the fact that it's a custom image, making such a mismatch even more obvious.

**Comment by darshankawar** [comment]
@gaowanliang 
Thanks for further details. Can you try to use `textHeightBehavior` property and see if it helps to align the text better ?

example:

```
textHeightBehavior: TextHeightBehavior(
                applyHeightToFirstAscent: false,
                applyHeightToLastDescent: false,
              ),
```
