### ISSUE TITLE
[path_provider] compilation error on flutter 2.10.0

### ISSUE THREAD

**Issue by davsl** [flutter/flutter#97900]
```
../../../.pub-cache/hosted/pub.dartlang.org/platform-3.0.0/lib/src/interface/local_platform.dart:46:19: Error: Member not found: 'packageRoot'.
      io.Platform.packageRoot; // ignore: deprecated_member_use
```

**Comment by ps6067966** [comment]
platform: ^3.1.0
Problem solved after placing this in pubspec.yaml file.

**Comment by stuartmorgan** [comment]
Per the error message, this error comes from `package`, not `path_provider`. Closing as there is no Flutter bug here.

**Comment by stuartmorgan** [comment]
(Duplicate of https://github.com/flutter/flutter/issues/96711)
