### ISSUE TITLE
'padding.isNonNegative': is not true after updating to Flutter 2.10.0 in iOS

### ISSUE THREAD

**Issue by RomanSoviak** [flutter/flutter#97905]
After updating to the latest Flutter version my App shows a red screen after opening the keyboard in iOS.
App shows error on GestureDetector with error:
'padding.isNonNegative': is not true
 ```
     child: GestureDetector(
        behavior: HitTestBehavior.opaque,
        onTap: _unfocus,
        child: Stack(
          children: [
            _buildBackground(context),
            _buildBody(context),
          ],
        ),
      ),
```
How should I hide the keyboard in a new way or other solutions for dealing with that issue?

Flutter 2.10.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5f105a6ca7 (3 days ago) • 2022-02-01 14:15:42 -0800
Engine • revision 776efd2034
Tools • Dart 2.16.0 • DevTools 2.9.2

**Comment by maheshmnj** [comment]
Hi @RomanSoviak, Thanks for filing the issue. Please share a minimal and complete code sample to reproduce the issue along with the complete error log.

**Comment by RomanSoviak** [comment]
@maheshmnj The following assertion was thrown building RawGestureDetector(state: RawGestureDetectorState#6d7f7(gestures: [tap], behavior: opaque)):
'package:flutter/src/rendering/shifted_box.dart': Failed assertion: line 142 pos 12: 'value.isNonNegative': is not true.


https://user-images.githubusercontent.com/26696190/152748654-3b1d0079-598c-49af-9866-8875d0a00ceb.mp4

**Comment by RomanSoviak** [comment]
@maheshmnj I assume that issue concerns to this https://github.com/flutter/engine/pull/29281

**Comment by maheshmnj** [comment]
@RomanSoviak Please share a minimal sample code to investigate this further. Are you using any negative padding in your code sample?

**Comment by RomanSoviak** [comment]
@maheshmnj 
`
class AuthPage extends StatefulWidget {
  const AuthPage({
    Key? key,
  }) : super(key: key);

  @override
  _AuthPageState createState() => _AuthPageState();
}

class _AuthPageState extends State<AuthPage> with TickerProviderStateMixin {
  final _emailEditingController = TextEditingController();

  final _emailFocusNode = FocusNode();

  final _sheetController = SheetController();

  late final AnimationController _bodyFieldController = AnimationController(
    duration: _fieldAppearingDuration,
    vsync: this,
  );

  late final Animation<double> _bodyFieldAnimation =
      Tween<double>(begin: _shrinkSheetHeight, end: _fullSheetHeight)
          .animate(_bodyFieldController)
        ..addListener(() {
          setState(() {});
        });
  
  var _isShowPasswordField = false;

  final _scaffoldBodyKey = GlobalKey();
  final _slidingSheetKey = GlobalKey();

  String? _emailText;

  @override
  void initState() {
    super.initState();

    _initTextFieldListeners();
    _prefillTextFields();
  }

  @override
  void dispose() {
    _emailEditingController.dispose();

    _emailFocusNode.dispose();

    _bodyFieldController.dispose();

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return AnnotatedRegion(
      value: SystemUiOverlayStyle.light,
      child: GestureDetector(
        behavior: HitTestBehavior.opaque,
        onTap: _unfocus,
        child: Stack(
          children: [
            _buildBackground(context),
            _buildBody(context),
          ],
        ),
      ),
    );
  }

  Widget _buildBody(BuildContext context) {
    Future.delayed(
      FocusScope.of(context).hasFocus
          ? Duration.zero
          : Duration(milliseconds: 100),
      () => _sheetController.expand(),
    );

    return Padding(
      padding: EdgeInsets.only(
        bottom: _calculateBottomPadding(context),
      ),
      child: SlidingSheet(
        key: _slidingSheetKey,
        duration: Duration(milliseconds: 600),
        controller: _sheetController,
        closeOnBackButtonPressed: false,
        color: Colors.white,
        elevation: 10.0,
        cornerRadius: 20.0,
        snapSpec: const SnapSpec(
          positioning: SnapPositioning.relativeToSheetHeight,
        ),
        scrollSpec: const ScrollSpec(
          overscroll: false,
          physics: NeverScrollableScrollPhysics(),
        ),
        body: _buildContent(context),
        builder: (context, state) {
          return AnimatedBuilder(
            animation: _bodyFieldAnimation,
            builder: (BuildContext context, Widget? child) {
              return SizedBox(
                height: _bodyFieldAnimation.value,
                child: child,
              );
            },
            child: Scaffold(
              extendBody: true,
              resizeToAvoidBottomInset: false,
              backgroundColor: Colors.transparent,
              body: Column(
                children: [
                  const SizedBox(
                    height: 10.0 * 4,
                  ),
                  ..._buildForm(),
                ],
              ),
            ),
          );
        },
      ),
    );
  }

  Widget _buildBackground(BuildContext context) {
    return Container(
      color: Colors.green,
      height: double.infinity,
      width: double.infinity,
    );
  }

  Widget _buildContent(BuildContext context) {
    return Scaffold(
      key: _scaffoldBodyKey,
      resizeToAvoidBottomInset: false,
      backgroundColor: Colors.transparent,
      body: AnimatedPadding(
        duration: _keyboardPaddingDuration,
        padding: EdgeInsets.only(
          bottom: MediaQuery.of(context).viewInsets.bottom,
        ),
        child: ExpandScrollWrapper(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              SizedBox(height: MediaQuery.of(context).viewPadding.top),
              const SizedBox(
                height: 4 * 10.0,
              ),
              // _buildLogo(),
              const Spacer(flex: 2),
              // ..._buildTitle(),
              const SizedBox(
                height: 44 * 10.0,
              ),
              const Spacer(),
            ],
          ),
        ),
      ),
    );
  }

  List<Widget> _buildForm() {
    return [
      Padding(
        padding: EdgeInsets.symmetric(horizontal: 20),
        child: TextField(
          controller: _emailEditingController,
          focusNode: _emailFocusNode,
          textInputAction: TextInputAction.next,
          keyboardType: TextInputType.emailAddress,
        ),
      ),
      const SizedBox(height: 10.0),
    ];
  }

  double _calculateBottomPadding(BuildContext context) {
    return MediaQuery.of(context).viewInsets.bottom > 0
        ? MediaQuery.of(context).viewInsets.bottom -
            (_isShowPasswordField ? 16 * 10.0 : 13 * 10.0)
        : 0;
  }

  void _initTextFieldListeners() {
    _emailEditingController.addListener(() {
      if (_emailText != _emailEditingController.text) {
        setState(() {
          _emailText = _emailEditingController.text;
        });
      }
    });
  }

  void _prefillTextFields() {
    if (kDebugMode) {
      _emailEditingController.text = "test@gmail.com";
    }
  }

  bool _validateEmail(String email) => true;

  void _unfocus() => FocusManager.instance.primaryFocus?.unfocus();
}

class ExpandScrollWrapper extends StatelessWidget {
  final Widget child;

  /// This class is relatively expensive. Avoid using it where possible.
  const ExpandScrollWrapper({
    Key? key,
    required this.child,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (context, constraint) {
        return SingleChildScrollView(
          child: ConstrainedBox(
            constraints: BoxConstraints(minHeight: constraint.maxHeight),
            child: IntrinsicHeight(
              child: child,
            ),
          ),
        );
      },
    );
  }
}
`
I use   **sliding_sheet: ^0.5.2** in this code

**Comment by RomanSoviak** [comment]
@maheshmnj  Steps to reproduce: 
1. Run code, 
2. Select field
3. Click on green Containe

https://user-images.githubusercontent.com/26696190/152788988-82d9cc8a-d67b-452e-b485-5459ca279cee.mp4

**Comment by maheshmnj** [comment]
Thanks for the sample code @RomanSoviak, I am able to reproduce the issue on stable 2.10.0 and also on `stable 2.8.1`. I looked at your code sample and it seems to me that this issue is related to ViewInsets padding basically this method 
`bottom: _calculateBottomPadding(context)`, Since this issue reproduces with a third-party package we won't be able to investigate this further. Could you please try to eliminate the package and create a minimal sample code ? 

<details>
<summary>logs</summary>

```
Restarted application in 3,578ms.
I/flutter (29289): botton= 0.0
I/flutter (29289): botton= 0.0
I/flutter (29289): bottom= 0.0
Reloaded 1 of 625 libraries in 849ms.
D/MIUIInput(29289): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=262586171, downTime=262586171 } moveCount:0
D/MIUIInput(29289): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=262586228, downTime=262586171 } moveCount:0
I/flutter (29289): bottom= 0.0
I/flutter (29289): bottom= 22.90909090909091

════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building RawGestureDetector(state: RawGestureDetectorState#ebfc2(gestures: [tap], behavior: opaque)):
'package:flutter/src/rendering/shifted_box.dart': Failed assertion: line 142 pos 12: 'value.isNonNegative': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was
GestureDetector
When the exception was thrown, this was the stack
#2      RenderPadding.padding=
#3      Padding.updateRenderObject
#4      RenderObjectElement._performRebuild
#5      RenderObjectElement.update
#6      SingleChildRenderObjectElement.update
#7      Element.updateChild
#8      RenderObjectElement.updateChildren
#9      MultiChildRenderObjectElement.update
#10     Element.updateChild
#11     SingleChildRenderObjectElement.update
#12     Element.updateChild
#13     SingleChildRenderObjectElement.update
#14     Element.updateChild
#15     ComponentElement.performRebuild
#16     StatefulElement.performRebuild
#17     Element.rebuild
#18     StatefulElement.update
#19     Element.updateChild
#20     ComponentElement.performRebuild
#21     Element.rebuild
#22     StatelessElement.update
#23     Element.updateChild
#24     SingleChildRenderObjectElement.update
#25     Element.updateChild
#26     ComponentElement.performRebuild
#27     StatefulElement.performRebuild
#28     Element.rebuild
#29     BuildOwner.buildScope
#30     WidgetsBinding.drawFrame
#31     RendererBinding._handlePersistentFrameCallback
#32     SchedulerBinding._invokeFrameCallback
#33     SchedulerBinding.handleDrawFrame
#34     SchedulerBinding._handleDrawFrame
#38     _invoke (dart:ui/hooks.dart:151:10)
#39     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#40     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 5 frames from class _AssertionError and dart:async)
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by scheduler library ═════════════════════════════════
'package:flutter/src/rendering/object.dart': Failed assertion: line 2517 pos 12: 'attached': is not true.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by scheduler library ═════════════════════════════════
'package:flutter/src/rendering/object.dart': Failed assertion: line 2517 pos 12: 'attached': is not true.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by scheduler library ═════════════════════════════════
'package:flutter/src/rendering/object.dart': Failed assertion: line 2517 pos 12: 'attached': is not true.
════════════════════════════════════════════════════════════════════════════════
I/flutter (29289): bottom= 273.8181818181818

════════ Exception caught by widgets library ═══════════════════════════════════
Duplicate GlobalKey detected in widget tree.
════════════════════════════════════════════════════════════════════════════════

```
</details>

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:sliding_sheet/sliding_sheet.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Localizations Sample App',
      home: AuthPage(),
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text('text field sample'),
        ),
        body: Center(
            child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            TextField(
              maxLines: 4,
            ),
            ElevatedButton(onPressed: () {}, child: Text('Press me'))
          ],
        )));
  }
}

class AuthPage extends StatefulWidget {
  const AuthPage({
    Key? key,
  }) : super(key: key);

  @override
  _AuthPageState createState() => _AuthPageState();
}

class _AuthPageState extends State<AuthPage> with TickerProviderStateMixin {
  final _emailEditingController = TextEditingController();

  final _emailFocusNode = FocusNode();

  final _sheetController = SheetController();

  late final AnimationController _bodyFieldController = AnimationController(
    duration: Duration(milliseconds: 500),
    vsync: this,
  );

  late final Animation<double> _bodyFieldAnimation =
      Tween<double>(begin: 200, end: 400).animate(_bodyFieldController)
        ..addListener(() {
          setState(() {});
        });

  var _isShowPasswordField = false;

  final _scaffoldBodyKey = GlobalKey();
  final _slidingSheetKey = GlobalKey();

  String? _emailText;

  @override
  void initState() {
    super.initState();

    _initTextFieldListeners();
    _prefillTextFields();
  }

  @override
  void dispose() {
    _emailEditingController.dispose();

    _emailFocusNode.dispose();

    _bodyFieldController.dispose();

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return AnnotatedRegion(
      value: SystemUiOverlayStyle.light,
      child: GestureDetector(
        behavior: HitTestBehavior.opaque,
        onTap: _unfocus,
        child: Stack(
          children: [
            _buildBackground(context),
            _buildBody(context),
          ],
        ),
      ),
    );
  }

  Widget _buildBody(BuildContext context) {
    Future.delayed(
      FocusScope.of(context).hasFocus
          ? Duration.zero
          : const Duration(milliseconds: 100),
      () => _sheetController.expand(),
    );

    return Padding(
      padding: EdgeInsets.only(
        bottom: _calculateBottomPadding(context),
      ),
      child: SlidingSheet(
        key: _slidingSheetKey,
        duration: const Duration(milliseconds: 600),
        controller: _sheetController,
        closeOnBackButtonPressed: false,
        color: Colors.white,
        elevation: 10.0,
        cornerRadius: 20.0,
        snapSpec: const SnapSpec(
          positioning: SnapPositioning.relativeToSheetHeight,
        ),
        scrollSpec: const ScrollSpec(
          overscroll: false,
          physics: NeverScrollableScrollPhysics(),
        ),
        body: _buildContent(context),
        builder: (context, state) {
          return AnimatedBuilder(
            animation: _bodyFieldAnimation,
            builder: (BuildContext context, Widget? child) {
              return SizedBox(
                height: _bodyFieldAnimation.value,
                child: child,
              );
            },
            child: Scaffold(
              extendBody: true,
              resizeToAvoidBottomInset: false,
              backgroundColor: Colors.transparent,
              body: Column(
                children: [
                  const SizedBox(
                    height: 10.0 * 4,
                  ),
                  ..._buildForm(),
                ],
              ),
            ),
          );
        },
      ),
    );
  }

  Widget _buildBackground(BuildContext context) {
    return Container(
      color: Colors.green,
      height: double.infinity,
      width: double.infinity,
    );
  }

  Widget _buildContent(BuildContext context) {
    return Scaffold(
      key: _scaffoldBodyKey,
      resizeToAvoidBottomInset: false,
      backgroundColor: Colors.transparent,
      body: AnimatedPadding(
        duration: Duration(milliseconds: 600),
        padding: EdgeInsets.only(
          bottom: MediaQuery.of(context).viewInsets.bottom,
        ),
        child: ExpandScrollWrapper(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              SizedBox(height: MediaQuery.of(context).viewPadding.top),
              const SizedBox(
                height: 4 * 10.0,
              ),
              // _buildLogo(),
              const Spacer(flex: 2),
              // ..._buildTitle(),
              const SizedBox(
                height: 44 * 10.0,
              ),
              const Spacer(),
            ],
          ),
        ),
      ),
    );
  }

  List<Widget> _buildForm() {
    return [
      Padding(
        padding: const EdgeInsets.symmetric(horizontal: 20),
        child: TextField(
          controller: _emailEditingController,
          focusNode: _emailFocusNode,
          textInputAction: TextInputAction.next,
          keyboardType: TextInputType.emailAddress,
        ),
      ),
      const SizedBox(height: 10.0),
    ];
  }

  double _calculateBottomPadding(BuildContext context) {
    final bottom = MediaQuery.of(context).viewInsets.bottom;
    print('bottom= $bottom');
    return bottom > 0
        ? bottom - (_isShowPasswordField ? 16 * 10.0 : 13 * 10.0)
        : 0;
  }

  void _initTextFieldListeners() {
    _emailEditingController.addListener(() {
      if (_emailText != _emailEditingController.text) {
        setState(() {
          _emailText = _emailEditingController.text;
        });
      }
    });
  }

  void _prefillTextFields() {
    if (kDebugMode) {
      _emailEditingController.text = "test@gmail.com";
    }
  }

  bool _validateEmail(String email) => true;

  void _unfocus() => FocusManager.instance.primaryFocus?.unfocus();
}

class ExpandScrollWrapper extends StatelessWidget {
  final Widget child;

  /// This class is relatively expensive. Avoid using it where possible.
  const ExpandScrollWrapper({
    Key? key,
    required this.child,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (context, constraint) {
        return SingleChildScrollView(
          child: ConstrainedBox(
            constraints: BoxConstraints(minHeight: constraint.maxHeight),
            child: IntrinsicHeight(
              child: child,
            ),
          ),
        );
      },
    );
  }
}

```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.10.0, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.10.0 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (3 days ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:5555                     • android-arm64  • Android 11 (API
      30)
    • iPhone 12 Pro (mobile) • 14F40EC6-3B73-469A-A1C0-8CF0B152290F • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.1 21C52
      darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome
      98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

Thanks
