### ISSUE TITLE
Flutter web client at Windows 7, app runs in browser but buttons frozen

### ISSUE THREAD

**Issue by selmaskopljakovic** [flutter/flutter#97914]
Hello,
I have an issue with the web app client running in the browser on Windows 7. Unfortunately, some clients still use Windows 7. The app runs on the browser, but all buttons are disabled. It is the same issue with Chrome and Firefox which are updated. Do you have any idea how to fix this?

Thanks for any help!

**Comment by darshankawar** [comment]
@selmaskopljakovic 
On what flutter version do you see this behavior ? Can you provide `flutter doctor -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue along with a screenshot ?

**Comment by selmaskopljakovic** [comment]
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19041.1415], locale en-US)
    • Flutter version 2.5.3 at C:\Flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (4 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Selma Skopljakovic\AppData\Local\Android\sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code, 64-bit edition (version 1.46.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.12.2

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 98.0.4758.82
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 98.0.1108.43

• No issues found!


Chrome version 98.0.4758

The app shows in the browser and it looks normal. It loads well. 
The only problem is that no button works. 

In the console log, there is 
Uncaught (in promise) TypeError: Failed to execute 'addAll' on 'Cache': Request failed

And it is the same issue with Firefox.

For other clients, it works perfectly.


Thank you!

**Comment by darshankawar** [comment]
@selmaskopljakovic 
Since Windows platform has hit stable, I recommend you to upgrade to latest stable (2.10.0) and try again to see if it helps.
If not, as requested earlier, we would need a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue along with a screenshot ?

**Comment by selmaskopljakovic** [comment]
Ok @darshankawar, thank you! 
Will try today and get back to you.
