### ISSUE TITLE
Flutter build fails for real iPhone and sometimes simulator

### ISSUE THREAD

**Issue by albertjblack** [flutter/flutter#97920]
I have tried to fix the issue via multiple issues that have been posted in the past, but no solution worked:
When I try to run the app on my iPhone this happens:

<details>
<summary> log </summary>

```

Launching lib/main.dart on Pepe Tostado in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: 7LUG6G48P7
Running Xcode build...                                                  
Xcode build done.                                           11.9s
Failed to build iOS app
Error output from Xcode build:
↳
    objc[6043]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x1ec656b90) and
    /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x10620c2c8). One of the two will be used. Which one is undefined.
    objc[6043]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x1ec656be0) and
    /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x10620c318). One of the two will be used. Which one is undefined.
    ** BUILD FAILED **


Xcode's output:
↳
    Writing result bundle at path:
        /var/folders/rf/yf1dcr7j1gq65ksvxc7kjt280000gn/T/flutter_tools.zulbVb/flutter_ios_build_temp_dirxg7H4f/temporary_xcresult_bundle


    Failed to package /Users/albertjblack/Documents/CourseWork/InProgress/Flutter/unit4/shopapp.
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order

    Result bundle written to path:
        /var/folders/rf/yf1dcr7j1gq65ksvxc7kjt280000gn/T/flutter_tools.zulbVb/flutter_ios_build_temp_dirxg7H4f/temporary_xcresult_bundle


Could not build the precompiled application for the device.

```

</details>

**Comment by albertjblack** [comment]
I tried to run a fresh newly created app and still get the same error. I have a Macbook pro 2021 M1 chip

**Comment by albertjblack** [comment]
flutter run --verbose throws this:
               Failed to package /Users/albertjblack/Documents/CourseWork/InProgress/Flutter/unit6/testapp.
               Command PhaseScriptExecution failed with a nonzero exit code
           
           
               Result bundle written to path:
                /var/folders/rf/yf1dcr7j1gq65ksvxc7kjt280000gn/T/flutter_tools.WGc2aU/flutter_ios_build_temp_dirqtqAdo/temporary_xcresult_bundle
           
           
[  +19 ms] Could not build the precompiled application for the device.
[  +24 ms] Error launching application on Pepe Tostado.
[  +10 ms] "flutter run" took 21,445ms.
[   +6 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:687:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>
           
           
[ +113 ms] ensureAnalyticsSent: 109ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

**Comment by darshankawar** [comment]
@albertjblack 
Please provide complete `flutter run --verbose`. The log will be huge so you can put that in a text file and share it here.
Also provide your `ios/podfile` and `flutter doctor -v`.

**Comment by albertjblack** [comment]
Here is a link to the project: https://github.com/albertjblack/shopapp

For my pod file, I think flutter created the folders pods instead of Podfile.
I had to create the pod file in the iOS directory by 
>> pod init
>> pod install
but it said 
-----
Pod installation complete! There are 0 dependencies from the Podfile and 0 total pods installed.

[!] The Podfile does not contain any dependencies.

[!] Automatically assigning platform `iOS` with version `12.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).
-----

**Comment by inc16sec** [comment]
Facing the same issue.. This happened right after I've upgraded to 2.10.

**Comment by xcc3641** [comment]
Same issue.

**Comment by darshankawar** [comment]
@albertjblack 
From the verbose log you shared, it's failing due to below error:

```
[   +2 ms] Target debug_unpack_ios failed: Exception: Failed to
codesign

/Users/albertjblack/Documents/CourseWork/InProgress/Flutter/unit4/shopapp/bu
               ild/ios/Debug-iphoneos/Flutter.framework/Flutter with identity
               5D3D359A4E23A578AC2BA5E511A1F6BF7707BE6F.

/Users/albertjblack/Documents/CourseWork/InProgress/Flutter/unit4

/shopapp/build/ios/Debug-iphoneos/Flutter.framework/Flutter:
                          errSecInternalComponent
           
                          #0      _signFramework

(package:flutter_tools/src/build_system/targets/ios.dart:644:5)
                          #1      UnpackIOS.build

```

Indicating this is related to code signing and likely that the keychain where your signing cert is stored isn't unlocked.
You'll probably need to `security unlock-keychain` and isn't a Flutter issue.
https://superuser.com/questions/270095/when-i-ssh-into-os-x-i-dont-have-my-keychain-when-i-use-terminal-i-do/363840

This is related flutter website issue for your reference: https://github.com/flutter/website/issues/5906
Similar flutter issue raised for your reference: https://github.com/flutter/flutter/issues/83235

Closing from here as this isn't a Flutter issue. If you disagree, write in comments and I'll reopen it.

Simila
