### ISSUE TITLE
Add an option in `Scaffold` to not register to the `Scaffold` to the `ScaffoldMessengerState`

### ISSUE THREAD

**Issue by ValentinVignal** [flutter/flutter#97935]
## Use case

I need to wrap the entire app with a widget that displays a box above the keyboard. To do so, I used a `Scaffold`:

```dart
runApp(MaterialApp(
  builder: (_, child) {  // `child` is one of the many page of the app (ex: `MyPage`) which might contain a `Scaffold`.
    return Scaffold(
      body: Column(
        children: [
          Expanded(
            child: child,
          ),
          MyBox(), // <- Generic widget I need to display on top of the keyboard. It might contain some business logic, change its size etc...
        ],
      ),
    );
  },
));
```

The issue is that the page displayed might contain a `Scaffold` too (to display an `AppBar`, a `FloatingActionButton` , a `Drawer` etc.)

Ex:

```dart
class MyPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: MyAppBar(),
      floatingActionButton: MyFloatingActionButton(),
      body: MyBody(),
    );
  }
}
```

When I do
```dart
ScaffoldMessenger.of(context).showSnackBar(mySnackbar);
```
it uses the root `Scaffold` which is the one used to display `MyBox` and not the on in `MyPage` containing the `FloatingActionButton` or other elements.

It results in the `Snackbar` appearing on top of the `FloatingActionButton` (and not above it), because the `Scaffold` displaying it doesn't have the `FloatingActionButton`.

## Proposal

Add an boolean option to the `Scaffold` constructor (ex: `this.registerToScaffoldMessenger = true`), when it is set to `false`, it won't register the `Scaffold` to the `ScaffoldMessenger` at :
https://github.com/flutter/flutter/blob/ba01ec8faae9a9be3cd90ee2b7357a803b7a7178/packages/flutter/lib/src/material/scaffold.dart#L2656-L2669

could become:

```dart
@override 
 void didChangeDependencies() { 
   // Using maybeOf is valid here since both the Scaffold and ScaffoldMessenger 
   // are currently available for managing SnackBars. 
   final ScaffoldMessengerState? currentScaffoldMessenger = ScaffoldMessenger.maybeOf(context); 
   // If our ScaffoldMessenger has changed, unregister with the old one first. 
   if (_scaffoldMessenger != null && 
     (currentScaffoldMessenger == null || _scaffoldMessenger != currentScaffoldMessenger)) { 
     _scaffoldMessenger?._unregister(this); 
   } 
   // Register with the current ScaffoldMessenger, if there is one. 
   _scaffoldMessenger = currentScaffoldMessenger; 
  if (widget.registerToScaffoldMessenger) {
    _scaffoldMessenger?._register(this);
  }
```

**Comment by navaronbracke** [comment]
Assuming that there are multiple ScaffoldMessengers (i.e. a root + a nested one somewhere in the tree), I'd expect a different BuildContext to get a different ScaffoldMessenger. This is similar to how other inherited widgets work.
If I run this code sample and inspect the Widget tree with the Devtools, I see only one `ScaffoldMessenger`.
```
import 'package:flutter/material.dart';

void main() async {
  runApp(MaterialApp(
    home: Scaffold(body: Center(child: Text("foo"))),
  ),
);
```

You are going to need to insert your own ScaffoldMessenger in your widget tree, below the `MaterialApp`.

**Comment by ValentinVignal** [comment]
@navaronbracke what we did was to give a `kRootScaffoldMessengerKey = GlobalKey<ScaffoldMessengerState>()` to our `MaterialApp` to then call

```dart
kRootScaffoldMessengerKey.currentState!.showSnackBar(mySnackBar);
```

From anywhere in the app without a need for the `context` (so the services could do it). 

So adding a nested/scoped `ScaffoldMessenger` inside the `builder` of the `MaterialApp` would prevent us from using one common `kRootScaffoldMessengerKey`.

**Comment by ValentinVignal** [comment]
Sorry, after reading out the docs of the `builder` of the `MaterialApp`:

>A builder for inserting widgets above the [Navigator] or - when the [WidgetsApp.router] constructor is used - above the [Router] but below the other widgets created by the [WidgetsApp] widget, or for replacing the [Navigator]/[Router] entirely.

I can as you suggested add a `Scaffold` and then another `ScaffoldMessenger` below with our global key since it will be built once (and not once for every routes):

```dart
MaterialApp(
  builder: (context, child) {
    Scaffold(
      body: Column(
        children: [
          Expanded(
            child: ScaffoldMessenger(
              key: kRootScaffoldMessengerKey,
              child: child,
            ),
          ),
          MyBox(), // <- Generic widget I need to display on top of the keyboard. It might contain some business logic, change its size etc...
        ],
      ),
    );
  },
),
```

Thank you for you quick response, I'll close the issue since the requested feature doesn't have any motivation anymore.
