### ISSUE TITLE
Unable to find an option to add new flutter module to my android project

### ISSUE THREAD

**Issue by prasadsunny1** [flutter/flutter#97931]
## Steps to Reproduce

1. Open a native android project on Android studio
2. Follow [this](https://docs.flutter.dev/development/add-to-app) to add a new module
3. Going to File> New Module
<img width="717" alt="Screenshot 2022-02-07 at 11 34 14 AM" src="https://user-images.githubusercontent.com/11705392/152733352-f1cbfeb5-f0d2-4942-805e-ffbdb132feb1.png">
4. The following dialog that opens does not have an option to create a flutter module
<img width="749" alt="Screenshot 2022-02-07 at 11 35 23 AM" src="https://user-images.githubusercontent.com/11705392/152733517-3b4a349a-7053-4118-a6c6-01fb3546b056.png">

## Android Studio info
Android Studio Arctic Fox | 2020.3.1 Patch 4
Build #AI-203.7717.56.2031.7935034, built on November 21, 2021
Runtime version: 11.0.10+0-b96-7249189 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.2
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: com.bloc.intellij_generator_plugin, Dart, org.jetbrains.kotlin, io.flutter
Flutter Plugin v. 64.0.1

##Flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.0, on macOS 12.2 21D49 darwin-arm, locale
    en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] Android Studio (version 2020.3)
[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message
      below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
[✓] VS Code (version 1.64.0)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```

**Comment by darshankawar** [comment]
@prasadsunny1 
This looks either intellij [plugin](https://github.com/flutter/flutter-intellij/issues) issue or website [issue](https://github.com/flutter/website/issues/new?template=1_page_issue.yml&title=[PAGE%20ISSUE]:%20%27Add%20Flutter%20to%20existing%20app%27&page-url=https://docs.flutter.dev/development/add-to-app/&page-source=https://github.com/flutter/website/tree/main/src/development/add-to-app/index.md) which need to be updated to reflect latest AS changes if any.
So please open in dedicated repo.
Closing from here.
