### ISSUE TITLE
TextSelection toolbar should be hidden when scrolled

### ISSUE THREAD

**Issue by SuhwanCha** [flutter/flutter#97934]
## Use case

Provide more native-like features on text selection toolbar

## Proposal

Toolbar for text selection should be hidden when text field is scrolled.
Please check videos below, how native application works.

**Native Android (record from YouTube)**

https://user-images.githubusercontent.com/16171447/152736726-7f70be09-9bab-4ba2-8556-0dace92992b5.mov

**Native iOS (record from default Calendar app)**

https://user-images.githubusercontent.com/16171447/152736772-51fb7d23-bb0e-4eaf-9a3c-3669b9df0135.mov

**How Flutter works now**

https://user-images.githubusercontent.com/16171447/152736923-5ce971c1-34ec-445c-9cc8-789ec4d8b892.mov

**Comment by SuhwanCha** [comment]
cc @justinmc

**Comment by maheshmnj** [comment]
Hi @SuhwanCha, Thanks for filing the issue.

There is a similar issue describing this case  https://github.com/flutter/flutter/issues/52425, Please follow up there for further updates, Closing this issue as a duplicate. If you disagree feel free to write in the comments and I will reopen it.

Thank you.
