### ISSUE TITLE
[google_maps_flutter] (web) The GoogleMap widget is always on top.

### ISSUE THREAD

**Issue by SittiphanSittisak** [flutter/flutter#97930]
The GoogleMap widget is always on top.
I have tried to use stack, dialog, and IgnorePointer to block any action of the GoogleMaps but it's not working.
I think it is a bug. I can't play this with any widget. I am using the onTab of the GoogleMap to show the GoogleMap picker, when I click dialog, dropdown menu, the container in the stack, or icon button in the area of GooleMap, the GoogleMap will action it too or I click the icon button in the same position of pin location of GoogleMap, the GoogleMap will action by show info of this location.

In my opinion. I think it is a bug. The GoogleMap should be a general widget that can be used in a variety of ways.

-------------------------------------------------------------------------
You can find this issue in my video.
1. The Inkwell on a GoogleMap to show the GoogleMap picker.
At 9 seconds, I click at the pin of the location. 
After I closed the dialog, the info will show at 16 seconds. 
I already used Inkwell but GoogleMap is still active.
https://user-images.githubusercontent.com/59549741/152727927-e122bbeb-0f00-4af6-99b4-ea7d6ad2ae76.mp4

2. The IconButton with The Stack on the GoogleMap.
At 5 seconds, I click the IconButton on the blank area and the map will move to my location. 
At 15 seconds, I click the IconButton on the pin location. After this, the map will move to my location and move again to this pin location.
I already used the Stack and the IconButton is on the GoogleMap but the GoogleMap still active.
https://user-images.githubusercontent.com/59549741/152728378-ce077e9a-0ea5-4d47-a454-22e65aba69eb.mp4

3. The Dropdown Menu on GoogleMap.
At 17 seconds, I click the menu of the Dropdown on GoogleMap, and the GooleMap is active.
https://user-images.githubusercontent.com/59549741/152728702-3fd9021e-8899-43f0-88f5-aeeb0b5e832a.mp4

4. The DatePicker on GoogleMap.
At 17 seconds, I click the DatePicker on GoogleMap, and the GooleMap is active.
https://user-images.githubusercontent.com/59549741/152729043-f7122316-a626-4e9f-b2b2-90a91370aaea.mp4

5. The dialog with the context on The GoogleMap.
At 8 seconds, I click the dialog on GoogleMap, and The GooleMap is active.
At 20 seconds, you can see the info of the pin location is active too. The function of GoogleMap for show info is under the dialog but it is still active.
At 28 seconds, you can see the zoom function of The GoogleMap is active.
https://user-images.githubusercontent.com/59549741/152729878-b7969c8c-a4a0-4cfc-a2dc-0312d3ddb3b5.mp4

-------------------------------------------------------------------------

I am using google_maps_flutter: ^2.1.1 and google_maps_flutter_web: ^0.3.2+1 package.

flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 2.10.0-0.3.pre, on Microsoft Windows [Version 10.0.19042.1466], locale th-TH)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.63.2)
[√] Connected device (2 available)
[√] HTTP Host Availability

• No issues found!
```

Now, I am using google map static API for my project.
But this solution is waste the internet to download the map picture and I need to create a custom button and function for Google Maps.
I hope the developer will solve this.

**Comment by darshankawar** [comment]
@SittiphanSittisak 
Please provide a complete minimal reproducible code sample (e.g main.dart) without any 3rd party plugins along with exact steps to replicate that shows what exactly is the issue you are facing including actual vs expected behavior.

Thanks.

**Comment by darshankawar** [comment]
@SittiphanSittisak 
This is an underlying issue related to web framework and platform-views, which is tracked [here](https://github.com/flutter/flutter/issues/93887), so follow-up in it for further updates.
Closing this as a duplicate.
