### ISSUE TITLE
Input fields of Form does not validate when call validate() of form State

### ISSUE THREAD

**Issue by jeydi243** [flutter/flutter#97944]
Hi everyone! The desired behavior of the input fields does not work properly when call validate(), 
## Steps to Reproduce
1. clone this repo https://github.com/jeydi243/gesi-mobile.git
2. Execute `flutter run` in the project directory
3. On login Screen, without writing anything in all fields try to tap on button '**Agree and continue**'
4. The validator on each field should work and return the text of error
4. the function to check is in **Login.dart**, _connexion()_

**Expected results:** 
The result must be: 

- All fields state must be in error state and show error in bottom on each field
- the snackbar should not be seen

**Actual results:** 
The current state of form return `true` event if you type nothing in all field.

Thank you guys!

**Comment by danagbemava-nc** [comment]
Hi @jeydi243, I took a look at your code sample and you have a `Form` nested within another `Form` which is why the validation was failing. If you remove one of them and assign the `_formKey` appropriately, your issue should be solved. 

Closing as this is an implementation issue. 

Thank you
