### ISSUE TITLE
Supporting "Video Player" plugin for Windows desktop.

### ISSUE THREAD

**Issue by AndriiReverchuk** [flutter/flutter#97940]
Hello, do you plan to support desktop applications on Windows? I need a multi-platform video player including web.

**Comment by jeydi243** [comment]
Hi @AndriiReverchuk ! Desktop application support on Windows is already available. And the new 2.10 Version added more stability.
Please check [Flutter Destop Support](https://docs.flutter.dev/desktop) and The [Announcing Flutter for Windows](https://medium.com/flutter/announcing-flutter-for-windows-6979d0d01fed)

**Comment by AndriiReverchuk** [comment]
I am asking about  support "Video Player" plugin for Windows desktop.

**Comment by stuartmorgan** [comment]
Duplicate of https://github.com/flutter/flutter/issues/37673
