### ISSUE TITLE
 Could not get unknown property 'applicationVariants' for extension 'android' of type com.android.build.gradle.LibraryExtension.

### ISSUE THREAD

**Issue by Aaron-xyd** [flutter/flutter#97943]
Hi,
I created a flutter application in 1.22.4 ( the version of flutter SDK ) , then changed the flutter application to library, and then compiled it to aar through "gradle assembleRelease", and used it in my project. But only this version (1.22.4) can do this. When I upgrade the SDK, the following error will be reported when I recompile. How can I solve it, thank you.

error log:(this error is on the SDK version 2.10.0)

```
FAILURE: Build failed with an exception.
* Where:
Script '/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 978
* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Could not get unknown property 'applicationVariants' for extension 'android' of type com.android.build.gradle.LibraryExtension.
```

-------------------------
The steps I changed the appellation to library:
1. Change " apply plugin: 'com.android.application' " to " apply plugin: 'com.android.library' " in app/build.gradle;
2. Delete applicationId in defaultConfig of app/build.gradle;
3. Delete the following in AndroidManifest.xml
       <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
        </intent-filter>

**Comment by darshankawar** [comment]
@Aaron-xyd 
Your issue is better suited to be asked on support channels like StackOverflow.
See [this](https://stackoverflow.com/questions/45101309/could-not-get-unknown-property-for-applicationvariants-for-buildtype-decorated) similar issue and check if it helps to resolve your issue.
Closing, as this doesn't seem to be specific to Flutter.
