### ISSUE TITLE
InkWell with DropdownButton underneath stays focused

### ISSUE THREAD

**Issue by Scount** [flutter/flutter#97951]
I am using an Inkwell with a DropdownButton underneath it. If i press the DropdownButton and select something, it will close the list but stays focused. Also the Inkwell will stay focused. 
The problem occures on web and windows desktop, not observed on mobile.
I am using the stable channel with version 2.10. The previous version 2.5.3 on stable worked perfectly.

**Also on the official website** (https://api.flutter.dev/flutter/material/DropdownButton-class.html) the same behaviour can be observed.

official website:
![image](https://user-images.githubusercontent.com/13836859/152811585-34e63395-adb5-411d-a143-8ffc41d6d65c.png)
expected result:
![image](https://user-images.githubusercontent.com/13836859/152812354-b0db75c8-1293-4afc-9753-62fdf2a2a217.png)
own project:
![image](https://user-images.githubusercontent.com/13836859/152812232-e4e685cd-023b-4e4c-bb98-ea7e14afd18b.png)
expected result:
![image](https://user-images.githubusercontent.com/13836859/152812306-e834c5fb-f6d1-49dd-935c-59d27da9bbed.png)

**Expected results:** DropdownButton and Inkwell will be unfocused after selection on DropdownButton.

**Actual results:** DropdownButton and Inkwell will stay focused after selection on DropdownButton.

<details>
<summary>Code sample</summary>
``

```dart
    int id = 0;
    List<DropdownMenuItem<int>> items = [];
    for (int i = 0; i < 10; i++) {
      items.add(
        DropdownMenuItem<int>(
          value: i,
          child: AutoSizeText(
            i.toString(),
            maxLines: 2,
            minFontSize: 5,
          ),
        ),
      );
    }

    return InkWell(
      onTap: () {
        // stuff happens here
      },
      child: DropdownButton<int>(
        //borderRadius: BorderRadius.circular(10),
        isExpanded: true,
        hint: Text('Select'),
        menuMaxHeight: 400,

        value: id,
        items: items,
        onChanged: (int? value) {
          if (value != null) {
            setState(() {
              id = value;
            });
          }
        },
      ),
    );
```

</details>

<details>
  <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel stable, 2.10.0, on Microsoft Windows [Version 10.0.19044.1466], locale de-DE)
    • Flutter version 2.10.0 at C:\Users\Thorb\Documents\Flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (6 days ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Thorb\AppData\Local\Android\sdk
    • Platform android-31, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30717.126
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.2.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code
    • Flutter extension version 3.34.0

[√] VS Code, 64-bit edition (version 1.63.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.34.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1466]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 97.0.4692.99
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 98.0.1108.43

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by maheshmnj** [comment]
Hi @Scount, Thanks for filing the issue. I can reproduce the same behavior the InkSplash remains when the DropDownItem is selected. But looking at a material design makes me think that this is working as intended, Could you please check this link https://material-components.github.io/material-components-web-catalog/#/component/select 

Also, as of master 2.11.0 You don't need to add an InkWell because its already taken care by `DropdownButton`.

**Comment by Scount** [comment]
Hello @maheshmnj, thanks for the response. Thought it was a bug, cause it was implemented in the new version. Can not get my head around that decision, but well it is was it is.
Will close the issue.
