### ISSUE TITLE
Test owners should fail if unnecessary owners are added

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#97969]
In https://github.com/flutter/flutter/pull/97385, I removed the ios32 entries. This would have left unused owners for the 32 bit tests.

Instead, the validation should fail explicitly to ensure unused owners are removed.

**Comment by CaseyHillers** [comment]
\cc @keyonghan @chunhtai

**Comment by godofredoc** [comment]
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.
