### ISSUE TITLE
Chrome is not saving cookies when using flutter debug

### ISSUE THREAD

**Issue by morzan1001** [flutter/flutter#97963]
Hi all, I have written a PWA in Flutter and would quite like to test it locally as well. I use authentication via session cookies, because the application should only run on the web. When I deploy the app on a server everything works fine, but when I launch Chrome from my IDE to debug or develop the whole thing, the cookie saving from Chrome doesn't work anymore. 

I use 'String? cookies = document.cookie;' from the dart:html library to get the cookies. When requests are sent to the server it responds with the header "set-cookie:". The cookie is not saved by Chrome, the memory remains empty and my flutterapp can't see any cookies by using document.cookie. 

I'm not sure where exactly the problem lies, but I suspect Chrome. I have already looked in the settings and also allowed cookies from third parties. I also set "Access-Control-Allow-Origin" to wildcard on the server for testing purposes to make sure nothing is interfering. 

Maybe one of you has an idea, thanks in advance.

**Comment by maheshmnj** [comment]
Hi @morzan1001, Thanks for filing the issue. 
> The cookie is not saved by Chrome, the memory remains empty and my flutterapp can't see any cookies by using document.cookie.

I believe this is because in debug mode flutter launches a new instance of chrome on each run, could you try running `flutter run -d web-server` and try launching in the existing chrome window.

If the issue persists please share the output of `flutter doctor -v` along with a minimal sample code to reproduce the issue.

**Comment by morzan1001** [comment]
Hey, thanks for replying and for the first tip. Unfortunately it has no effect if I start chrome myself and then connect to the port or if I let flutter start chrome. :(

My Flutter Doctor actually shows me some problems, but as I found out with a bit of recherce it has to do with the Intellij plugin for Flutter and I don't think that is important for this. I have nevertheless attached the entire output.

`
[✓] Flutter (Channel stable, 2.10.0, on Ubuntu 21.10 5.13.0-28-generic, locale
    de_DE.UTF-8)
    • Flutter version 2.10.0 at /home/md/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (vor 6 Tagen), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).

[☠] IntelliJ IDEA Ultimate Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message
      below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle
      (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString
      (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read
      (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer
      (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes
      (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml
      (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion
      (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage
      (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate
      (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure>
      (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure>
      (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks
      (package:flutter_tools/src/doctor.dart:205:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:309:47)
      #20     DoctorCommand.runCommand
      (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand
      (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure>
      (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure>
      (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure>
      (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure>
      (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand
      (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure>
      (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure>
      (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.34.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 21.10 5.13.0-28-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 97.0.4692.99

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.
`

Also I have attached my Cookie Manager class with which I read cookies from the browser, but in fact you can already see via the development tools of Chrome that no cookies at all are stored in the browser that Flutter could read. This is as I said only the case when the app is used locally for testing and not when it is deployed on a server, here everything works fine.

`
import 'dart:html';

class CookieManager {
  static addToCookie(String key, String value) {
    document.cookie = '$key=$value;';
  }

  static String getCookie(String key) {
    String? cookies = document.cookie;
    List<String> listValues = cookies!.isNotEmpty ? cookies.split(';') : [];
    String matchVal = '';
    for (int i = 0; i < listValues.length; i++) {
      List<String> map = listValues[i].split('=');
      String _key = map[0].trim();
      String _val = map[1].trim();
      if (key == _key) {
        matchVal = _val;
        break;
      }
    }
    return Uri.decodeFull(matchVal);
  }
}
`

A typical request response pair from the server looks like this: 

Request:
`
GET /api/api/v1/csrf HTTP/1.1
Host: zertifinator.pen-net.de
Connection: keep-alive
sec-ch-ua: " Not;A Brand";v="99", "Google Chrome";v="97", "Chromium";v="97"
accept: application/json
sec-ch-ua-mobile: ?0
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36
sec-ch-ua-platform: "Linux"
Origin: http://localhost:46575
Sec-Fetch-Site: cross-site
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: http://localhost:46575/
Accept-Encoding: gzip, deflate, br
Accept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7
`

Response:
`
HTTP/1.1 204 No Content
Date: Tue, 08 Feb 2022 09:41:55 GMT
Server: Apache
Cache-Control: no-cache,no-store,must-revalidate
Access-Control-Allow-Origin: *
Set-Cookie: XSRF-TOKEN=eyJpdiI6IlJSVjFHNkppWStDdXRXUVdsTm1NQ2c9PSIsInZhbHVlIjoiMFNucmlMLys4TTN2WHRPeHVEVHN4bG1KME1YYlBHSXBpMlczTm1VT0FKVVgyOFRid0RYRmlvMERpRXRLNENUZXJ4cnh2UWJzekNpcXgvdW5nMjY5ZDJIQVcwUkFUdzVTV2F6TXNjMXRZWmJNL1ByY3NNY1U0Um9Ua3E4Zm9YZE8iLCJtYWMiOiI1OTJkMGNmOGVmOTBiZWJlZWJhNDNmM2I3N2I3Y2I2MjE1YTcyNzY1NjA4MzJiYmMwMzJhNDNiMTMzMzViMmRiIiwidGFnIjoiIn0%3D; expires=Tue, 08-Feb-2022 11:41:55 GMT; Max-Age=7200; path=/; samesite=lax
Set-Cookie: laravel_session=eyJpdiI6IlNsVndZQ3hjb0FacnZpV3dqcFRMS3c9PSIsInZhbHVlIjoiSWVXaTc0QVJNNFd4ekoyaHQ5RG5RcENnczFta2U4SFprWTNtdFB4eGkxNW80amp3ZVlYbTEzL090UUp0czQ3NU1ZTjk1NlF6NEdWczVJNGl4MEJnMGM5NlJ2VmVFOFZ6a0dXMFJ3bXl3dTRpN1hNQ0QwSm9sWG1ubFIyQmY3ZHQiLCJtYWMiOiI4MzNjMzg5ZTk3OTM5ZmY3MjQxODA1MmM0NmRlN2NlYzU4MWU2NjM3MTcyNDlkYTI1YjRiMDFmYTU3NTI3ZTE5IiwidGFnIjoiIn0%3D; expires=Tue, 08-Feb-2022 11:41:55 GMT; Max-Age=7200; path=/; httponly; samesite=lax
Strict-Transport-Security: max-age=31536000; includeSubdomains;
Access-Control-Allow-Credentials: true
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
`

As you can see here, the application correctly requests a CSRF token and in the response it is included as a cookie.

Thanks for the help!

**Comment by morzan1001** [comment]
So it turns out, of course, that's absolutely my fault. The cookie that should be set logically has a URL, but it is not "localhost". I have as a workaround renamed my localhost in /etc/hosts to the domain and set a few headers so that a connection is possible, and then it works. Sometimes you have to write your thoughts in an issue first to get the solution :)

Thanks for the help
