### ISSUE TITLE
DartDocs fail for plugins

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#9796]
_From @goderbauer on May 3, 2017 23:37_

http://www.dartdocs.org/documentation/url_launcher/0.3.1/ linked from https://pub.dartlang.org/packages/url_launcher returns a 404.

_Copied from original issue: flutter/plugins#17_

**Comment by mit-mit** [comment]
Looks like the same underlying issue as https://github.com/flutter/flutter/issues/9547

**Comment by mit-mit** [comment]
This has been resolved except for two packages where analysis fails (due to the `/example/` having additional `pubspec.yaml` requirements). The root issue for that is https://github.com/flutter/flutter/issues/10015.

**Comment by mit-mit** [comment]
@devoncarew the linked bug #10015 was resolved; can we resolve the present bug also?

**Comment by devoncarew** [comment]
I believe so.
