### ISSUE TITLE
Run macOS integration tests on M1 Macs

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#97977]
Suggest `native_ui_tests_macos`
https://github.com/flutter/flutter/blob/965397cfde1165a2735f517d8071f583786ac6a1/.ci.yaml#L3528
and test that exercises hot reload.  Maybe a no-upload version of `hot_mode_dev_cycle_macos_target__benchmark`?
https://github.com/flutter/flutter/blob/965397cfde1165a2735f517d8071f583786ac6a1/.ci.yaml#L3241

**Comment by jmagman** [comment]
@godofredoc is no-upload possible for framework benchmarks re: `hot_mode_dev_cycle_macos_target__benchmark`?
In the meantime, if we can get a configuration that runs `native_ui_tests_macos` on x86 and arm that would be a great start.

**Comment by jmagman** [comment]
See also https://github.com/flutter/flutter/issues/87508

**Comment by cbracken** [comment]
https://flutter-review.googlesource.com/c/infra/+/28183 enables the release launch test on the M1 mac staging pool.

**Comment by jmagman** [comment]
`hot_mode_dev_cycle_macos_target__benchmark` was done
https://github.com/flutter/flutter/blob/9489458650919d51c78f391a4defae7523b7c1b9/.ci.yaml#L3345

Closing this, we are running some on M1s so the harness etc is working, and we can file new issues as needed.
