### ISSUE TITLE
Possibility to specify android package name / iOS Bundle ID on new project creation

### ISSUE THREAD

**Issue by hundeva** [flutter/flutter#9797]
Currently, creating a new project with IntelliJ creates the following package name and Bundle ID: `com.yourcompany.$projectName`.

It is not that hard to manually follow up, and modify the package name / Bundle ID, but is fairly inconvenient. The new project wizard should ask for a project id, that could replace `com.yourcompany`, such as `$projectId.$projectName`.

**Comment by eseidelGoogle** [comment]
@collinjackson hit something like this yesterday by creating a project and then forgetting to change the resulting bundle ids.

Xcode has some smart templating we might be able to take advantage of.  It was (at least a long time ago?) possible to set COMPANY_NAME, and other variables which Xcode would then use when generating new files and projects.

**Comment by xster** [comment]
I think @hundeva is asking for Android as well. i.e. placing the package name in AndroidManifest.xml and (more tediously) have the right directory chain in java source

**Comment by Skylled** [comment]
This should be closed from #10290.

**Comment by xster** [comment]
+1. It's a dupe
