### ISSUE TITLE
Add integration tests to validate architectures of built macOS app

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#97978]
Something like https://github.com/flutter/flutter/blob/6ab00756a8e30f71f0dc30b1f12333479e7f2757/packages/flutter_tools/test/integration.shard/ios_content_validation_test.dart#L233
in [macos_content_validation_test](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/host_cross_arch.shard/macos_content_validation_test.dart).  Validate x86_64 is built in release mode.  When https://github.com/flutter/flutter/issues/60113 is complete, also check arm64[e] is also built in release mode.

**Comment by cbracken** [comment]
Dependent on https://github.com/flutter/flutter/issues/42281.

**Comment by jmagman** [comment]
Actually I already did this in https://github.com/flutter/flutter/pull/100811, forgot I filed this issue.

https://github.com/flutter/flutter/blob/f1f559df7384558edfa449c2aa571eb07a1ea1bf/packages/flutter_tools/test/host_cross_arch.shard/macos_content_validation_test.dart#L95-L103

**Comment by cbracken** [comment]
And just as bad, I forgot I reviewed it!
