### ISSUE TITLE
Swift plugin : cannot implement FlutterPlugin in my Plugin.swift file

### ISSUE THREAD

**Issue by rxlabz** [flutter/flutter#9798]
I created a [swift-based audio plugin](https://github.com/rxlabz/flutter_audio). Everything works fine when I use it in a swift-based Xcode project.

But... when I try to add it as a dependency in a project with ObjC-based Xcode project, I change the import in the PluginRegistry.h, and replace `#import "MyPlugin.h"`  by a `#import "MyProject-Swift.h"` the generated header which allow the use of swift-based plugin classes.

I can run the app from Xcode, but when I use `Flutter run` the PluginRegistry.h seems to be regenerated, and replace my manual changes by the original "MyPlugin.h" import.

## Flutter Doctor

```
[✓] Flutter (on Mac OS X 10.12.4 16E195, channel master)
    • Flutter at /Users/rxlabz/dev/tools/flutter
    • Framework revision ba4bba7498 (6 hours ago), 2017-05-03 22:50:24 -0700
    • Engine revision da8ebf40bd
    • Tools Dart version 1.23.0-dev.11.11

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/rxlabz/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.2, Build version 8E2002
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.0

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2016.3.6)
    • Dart plugin version 163.13137
    • Flutter plugin version 12.0

[✓] IntelliJ IDEA Ultimate Edition (version 2017.1)
    • Dart plugin version 171.4006
    • Flutter plugin version 13.0
```

**Comment by eseidelGoogle** [comment]
@szakarias or @mit-mit would know.

**Comment by rxlabz** [comment]
@eseidel  thanks, I will retry with the last plugin api/process, and will update the issue with updated symptoms if necessary.

**Comment by rxlabz** [comment]
There is no more PluginRegistry in new API, so I can close this issue... but I have some trouble to update my examples to the new API : I translated the GeneratedPluginRegistrant and the AppDelegate to Swift, it compiles, but when I launch the app it quits with this message **"Could not cast value of type 'Runner.AppDelegate' (0x100029518) to 'FlutterPluginRegistrar' (0x100faf9f0)"**. It's not a bug, I'm probably miss something... Here the complete log :

```
Launching lib/main.dart on rPhone in debug mode...
Running pod install...                                1,5s
Running Xcode build...                               11,8s
libMobileGestalt MobileGestaltSupport.m:153: pid 8037 (Runner) does not have sandbox access for frZQaeyWLUvLjeuEK43hmg and IS NOT appropriately entitled
libMobileGestalt MobileGestalt.c:550: no access to InverseDeviceID (see <rdar://problem/11744455>)
Could not cast value of type 'Runner.AppDelegate' (0x1000e5420) to 'FlutterPluginRegistrar' (0x1010639f0).
```
Here are the [sources ](https://github.com/rxlabz/flutter_swift_plugin_template2)... I'm stubborn, but I really don't know what I can try more :)

**Comment by rxlabz** [comment]
Sorry for this spam... last news. The Runner.AppDelegate cast issue was my bad.
But now I have a new cast problem : the FlutterPlugin protocol.
If I implement this protocol in the swift plugin file, the example project "cannot load underlying module for 'my_plugin_module'" in the GeneratedPluginRegistrant.swift file.
If I don't implement the protocol, the app compiles and run, but calling `registrar.addMethodCallDelegate(instance as! FlutterPlugin, channel:channel)`fails because the plugin class do not implement FlutterPlugin.
I'll leave it [here](https://github.com/rxlabz/FlutterSwiftPlugin-template), for now, any idea is welcome :)

**Comment by mit-mit** [comment]
Cc @mravn-google

**Comment by mravn-google** [comment]
Closed per https://github.com/flutter/website/pull/568

**Comment by mit-mit** [comment]
@rxlabz were you able to get your plugin code in Swift working? We published the editing instructions here: https://flutter.io/platform-plugins/#ios-platform-code-swift

**Comment by rxlabz** [comment]
@mit-mit sorry, my second daughter was kind enough to let me watch the two I/O flutter talks live, but decided to born right after :) i'll be back to my machine later this week, and will start by updating my swift plugin template, and try to publish a first  plugin based on it if everything works.

**Comment by mravn-google** [comment]
Wow. Congratulations!

**Comment by mit-mit** [comment]
No rush, big congrats on the daughter!
