### ISSUE TITLE
[in_app_purchase] Null check operator used on a null value

### ISSUE THREAD

**Issue by erperejildo** [flutter/flutter#97985]
My app was working fine on both iOS and Android but after updating to Flutter 2.10.0 I'm getting this issue:

```
    Unhandled Exception: Null check operator used on a null value
    E/flutter ( 8991): #0      Element.widget (package:flutter/src/widgets/framework.dart:3203:31)
    E/flutter ( 8991): #1      Provider._inheritedElementOf (package:provider/src/provider.dart:341:17)
    E/flutter ( 8991): #2      Provider.of (package:provider/src/provider.dart:293:30)
    E/flutter ( 8991): #3      Shop.getPastPurchases.<anonymous closure> (package:my_rents/services/shop.dart:123:20)
    E/flutter ( 8991): #4      _rootRunUnary (dart:async/zone.dart:1434:47)
    E/flutter ( 8991): #5      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
    E/flutter ( 8991): #6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
    E/flutter ( 8991): #7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
    E/flutter ( 8991): #8      _DelayedData.perform (dart:async/stream_impl.dart:591:14)
    E/flutter ( 8991): #9      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
    E/flutter ( 8991): #10     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
    E/flutter ( 8991): #11     _rootRun (dart:async/zone.dart:1418:47)
    E/flutter ( 8991): #12     _CustomZone.run (dart:async/zone.dart:1328:19)
    E/flutter ( 8991): #13     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
    E/flutter ( 8991): #14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
    E/flutter ( 8991): #15     _rootRun (dart:async/zone.dart:1426:13)
    E/flutter ( 8991): #16     _CustomZone.run (dart:async/zone.dart:1328:19)
    E/flutter ( 8991): #17     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
    E/flutter ( 8991): #18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
    E/flutter ( 8991): #19     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
    E/flutter ( 8991): #20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

My implementation:

```
    Future<List<PurchaseDetails>> getPastPurchases(BuildContext context) async {
        if (this.purchases.isEmpty) {
          final Stream<List<PurchaseDetails>> purchaseUpdated =
              inAppPurchase.purchaseStream;
    
          _subscription = purchaseUpdated.listen((purchaseDetailsList) {       
          }, onDone: () {
            _subscription.cancel();
          }, onError: (error) {
          });
    
          await inAppPurchase.restorePurchases(); // If I comment this line everything works
    
        }
        return this.purchases;
      }
```

More info:
`in_app_purchase: ^2.0.1
`
```
[✓] Flutter (Channel stable, 2.10.0, on macOS 11.6.2 20G314 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.62.0)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

Again, I made no changes on my code, just updating Flutter.

**Comment by stuartmorgan** [comment]
According to your exception stack, this line of your code is triggering the exception:

> Provider.of<AdState>(context, listen: false).toggleAds(context, true);

That line is in the callback you defined for in_app_purchase. Then you said:

> await inAppPurchase.restorePurchases(); // If I comment this line everything works

If you comment out the line that would cause your in_app_purchase to be called, then the line of your code that is triggering the exception will never run, so that's not surprising, but it's not clear to me why this is tagged as an in_app_purchase issue. Is there some reason you believe that calling your callback constitutes a bug in in_app_purchase?

**Comment by darshankawar** [comment]
@erperejildo 
Please check above comment. Also, it seems to be pointing to `provider` package that you might be using.
```

Provider._inheritedElementOf (package:provider/src/provider.dart:341:17)
    E/flutter ( 8991): #2      Provider.of (package:provider/src/provider.dart:293:30)
```

**Comment by erperejildo** [comment]
> According to your exception stack, this line of your code is triggering the exception:
> 
> > Provider.of(context, listen: false).toggleAds(context, true);
> 
> That line is in the callback you defined for in_app_purchase. Then you said:
> 
> > await inAppPurchase.restorePurchases(); // If I comment this line everything works
> 
> If you comment out the line that would cause your in_app_purchase to be called, then the line of your code that is triggering the exception will never run, so that's not surprising, but it's not clear to me why this is tagged as an in_app_purchase issue. Is there some reason you believe that calling your callback constitutes a bug in in_app_purchase?



> @erperejildo Please check above comment. Also, it seems to be pointing to `provider` package that you might be using.
> 
> ```
> 
> Provider._inheritedElementOf (package:provider/src/provider.dart:341:17)
>     E/flutter ( 8991): #2      Provider.of (package:provider/src/provider.dart:293:30)
> ```

Sorry for the confusion, I forgot to remove that part before pasting. It seems to be related but it's not:


https://user-images.githubusercontent.com/5629919/152952163-a2e57443-0877-4410-81eb-75431adeb27f.mov

**Comment by stuartmorgan** [comment]
> It seems to be related but it's no

It is part of the exception stack, so it is absolutely related. If you have an exception when you don't include that line, please provide the stack for it and the source for that reproduction case.

**Comment by erperejildo** [comment]
> > It seems to be related but it's not
> 
> It is the last part of the exception stack, so it is absolutely related. If you have an exception when you don't include that line, please provide the stack for it and the source for that reproduction case.

I don't have any exception stack, just that. At least in `getPastPurchases()`. Looking outside that function I only have this:
```
getUserExtraInfo() async {
    if (authService.getUser() != null) {
      // await Provider.of<MyRents>(context, listen: false).updatePortfolios(); HERE
      // available versions
      if (await shop.inAppPurchase.isAvailable()) {
        await shop.clearTransactionsIos();
        await shop.getProducts();
        await shop.getPastPurchases(context);
      }
    }
  }
```
But that doesn't change anything (and makes sense because this fails with the listener, not before).

**Comment by stuartmorgan** [comment]
This, from your report, is an exception stack:

> ```
> Unhandled Exception: Null check operator used on a null value
>     E/flutter ( 8991): #0      Element.widget (package:flutter/src/widgets/framework.dart:3203:31)
>     E/flutter ( 8991): #1      Provider._inheritedElementOf (package:provider/src/provider.dart:341:17)
>     E/flutter ( 8991): #2      Provider.of (package:provider/src/provider.dart:293:30)
>     E/flutter ( 8991): #3      Shop.getPastPurchases.<anonymous closure> (package:my_rents/services/shop.dart:123:20)
>```

It includes the line of your code I referenced. It is impossible to have this stack without that line of code, so if you have an exception when you remove that line of code, it must be different. We need that stack.

**Comment by erperejildo** [comment]
> This, from your report, is an exception stack:
> 
> > ```
> > Unhandled Exception: Null check operator used on a null value
> >     E/flutter ( 8991): #0      Element.widget (package:flutter/src/widgets/framework.dart:3203:31)
> >     E/flutter ( 8991): #1      Provider._inheritedElementOf (package:provider/src/provider.dart:341:17)
> >     E/flutter ( 8991): #2      Provider.of (package:provider/src/provider.dart:293:30)
> >     E/flutter ( 8991): #3      Shop.getPastPurchases.<anonymous closure> (package:my_rents/services/shop.dart:123:20)
> > ```
> 
> It includes the line of your code I referenced. It is impossible to have this stack without that line of code, so if you have an exception when you remove that line of code, it must be different. We need that new stack.

I have checked that I only got this error when user logs in manually but not when the app starts and it does automatically the first time (and trigger also `restorePurchases`). So only after second time we trigger this code it fails.

The issue was, first of all, the listen, executed +1 every time. Because of that, the context was incorrect inside the provider and complains about it.

In the example we have the `.listen` in a `initState()`, which is the best place for this, but in my case, I use a service without state. So I added the cancel also here:
```
_subscription = purchaseUpdated.listen((purchaseDetailsList) {
        if (purchaseDetailsList.isEmpty) {
          Provider.of<AdState>(context, listen: false).toggleAds(context, true);
        } else {
          // this.purchases.addAll(purchaseDetailsList);
          listenToPurchaseUpdated(context, purchaseDetailsList);
        }
        _subscription.cancel();
      }, onDone: () {
        _subscription.cancel();
      }, onError: (error) {
        // handle error here.
        _subscription.cancel();
      });
```
Not sure why this fails now after the update and not before because I had this code there for months, but anyway, working now. Thanks!
