### ISSUE TITLE
[in_app_purchase][Android]: queryPastPurchases returns empty list in release build (works fine in debug mode)

### ISSUE THREAD

**Issue by hbt1903** [flutter/flutter#97995]
## Steps to Reproduce

1. Run app in release mode with flutter run --release
2. Make a purchase for subscription (weekly)
3. Get subscription successfully
4. When subscription renews, queryPastPurchases returns empty string

** It works fine in debug mode on Android, and works fine both in release and debug mode on iOS**

**Expected results:** Fetch the past purchases with success

**Actual results:** Got an empty list of QueryPurchaseDetailsResponse

<details>
<summary>Code sample</summary>

<img width="588" alt="Ekran Resmi 2022-02-08 03 32 05" src="https://user-images.githubusercontent.com/26011820/152895369-048a4d3f-2afb-4831-800b-fe5cc068d91e.png">

**Comment by darshankawar** [comment]
@hbt1903 
Can you provide `flutter doctor -v`, plugin version and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows the issue ?

**Comment by hbt1903** [comment]
<details>
<summary>flutter doctor -v</summary>
[✓] Flutter (Channel stable, 2.10.0, on macOS 12.2 21D49 darwin-arm, locale tr-TR)

    • Flutter version 2.10.0 at /Users/hbt/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (7 days ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/hbt/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/AndroidStudio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.64.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (1 available)
    • Chrome (web)          • chrome          • web-javascript          •Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
</details>

<details>
<summary>Code Sample</summary>
I work for a company so it is not possible to provide a reproducable code sample since we handle a lot of work on our servers (like verification of receipts, storing receipt datas)

Basically I initialize the app with the following function and I expect to get past purchase details succesfully.

- Btw. I am sure that the **applicationUserName = UserService.instance** value does not change

```dart

Future<void> _initAndroid() async {
    InAppPurchaseAndroidPlatformAddition.enablePendingPurchases();
    _iap = InAppPurchase.instance;
    InAppPurchaseAndroidPlatformAddition _androidAddition = _iap.getPlatformAddition<InAppPurchaseAndroidPlatformAddition>();
    QueryPurchaseDetailsResponse _resp = await _androidAddition.queryPastPurchases(
      applicationUserName: UserService.instance.userId,
    );
    List<GooglePlayPurchaseDetails> _details = _resp.pastPurchases;
    pastPurchaseDetailsAndroid = _resp.pastPurchases;
    _details.forEach((element) async {
      _handleIAPResponse(
        await ReceiptVerifier.verifyReceiptAndroid(element),
      );
    });
  }

```

I expect to have **_details** a non-empty list after making a purchase.
It is empty only in the **release** mode on **Android**.
</details>

**Comment by darshankawar** [comment]
@hbt1903 
Can you check [this](https://github.com/flutter/flutter/issues/83342#issuecomment-850503066) issue comment and related code snippet and see if it helps ?

**Comment by hbt1903** [comment]
@darshankawar 
Thank you very much, I'll try it 👍 
But still, isn't it weird that working properly in debug mode?

**Comment by hbt1903** [comment]
@darshankawar 
_**restorePurchases**_ seems to works fine in release mode, thank you!
