### ISSUE TITLE
Forward `flutter packages` commands to `pub`

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#9799]
Currently we don't support publishing packages/plugins (i.e. `pub publish`), or running executables from packages (i.e. `pub run`, for example for package:intl) with the flutter command.

It would be great if we could forward all relevant pub subcommands to equivalent `flutter packages` commands. At least the following seem to make sense:

## Already supported

1. `flutter packages get` -> `pub get`
1. `flutter packages upgrade` -> `pub upgrade`

## Should be added

1. `flutter packages downgrade` -> `pub downgrade`, the opposite of upgrade
1. `flutter packages publish` -> `pub publish` to support publishing a plugin
1. `flutter packages deps` -> `pub deps` to show package dependencies
1. `flutter packages run` -> `pub run` to support running executables, e.g. for package:intl
1. `flutter packages cache` -> `pub cache` to manage the pub cache contents
1. `flutter packages version` -> `pub version` to see the pub version
1. `flutter packages uploader` -> `pub uploader` to manage [package uploaders](https://www.dartlang.org/tools/pub/cmd/pub-uploader)

## Can be ignored

1. `pub build`: web workflow, not relevant
1. `pub serve`: web workflow, not relevant
1. `pub help`: flutter has it's own help
1. `pub version`: flutter has it's own version, Dart SDK version is in flutter doctor
1. `pub global`: not a flutter workflow

**Comment by sethladd** [comment]
@mit-mit which of the proposed commands _requires_ the special flutter environment variable to work? I would prioritize those sooner than Milestone 5.

**Comment by mit-mit** [comment]
I don't think we should do these piecemeal. It should be pretty straightforward to just forward all the listed ones under should be added.

**Comment by Hixie** [comment]
I think we should close this as a general bug and track individual commands we feel strongly about independently in their own bugs (e.g. as in #10403).

**Comment by mit-mit** [comment]
OK, we can do that.
