### ISSUE TITLE
Identify and update documentation for how to contribute a sizable feature to Flutter & Dart

### ISSUE THREAD

**Issue by nuritzi** [flutter/flutter#97994]
As we start to encourage more contributions to happen, we should make sure we have great documentation to support them. For example, if X company wants to start contributing features, how do we collaborate with them?

This means also having a set of practices that allow us to collaborate with people who want to add new features, and that we have guidelines on the quality of contributions. 

TODOs: 

- [ ]  Identify any existing documentation around accepting contributions. If none exist, create a page on GItHub wiki

**Comment by CynthiaPeter** [comment]
Hello @nuritzi and @maheshmnj,

I was wondering if this is something I could contribute to with your help and guidiance.
Thank you.

**Comment by nuritzi** [comment]
@maheshmnj -- while you're right that the internal Google team will need to drive the decision-making part, we'll need to involve the wider community in various parts of this process! This was a placeholder issue, so I can see how it was unclear that was the case 😅 -- sorry about that and thanks for helping to triage this!!

@CynthiaPeter -- If you're interested, I'd love to collaborate on this with you! 

I'll try to add more details to this issue to help make it easier to contribute. One of the first things we need to do is identify the pages in [the wiki](https://github.com/flutter/flutter/wiki) where we talk about how to contribute a feature -- but there may be someone on the Google team who has a good idea of where these places are so that it's a bit easier to identify. 

Will report back in this issue soon! 

If you're on [the Flutter Discord](https://github.com/flutter/flutter/wiki/Chat) and want to chat about this issue, or any other that you see me post about, feel free to reach out! I'm `nuritzi` there too.

**Comment by Hixie** [comment]
this is largely done now:
https://github.com/flutter/flutter/blob/master/CONTRIBUTING.md
https://github.com/flutter/flutter/wiki/Contributor-access
https://github.com/flutter/flutter/wiki/Values
https://github.com/flutter/flutter/wiki/Issue-hygiene
https://github.com/flutter/flutter/wiki/Tree-hygiene
https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
https://github.com/flutter/flutter/wiki/Design-Documents

If there are specific questions that this doesn't cover, please let us know!
