### ISSUE TITLE
Checkboxes in PopupMenuItems don't position well

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#98]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Friday Jul 17, 2015 at 22:45 GMT_
_Originally opened as https://github.com/flutter/engine/issues/106_

----

_From @Hixie on May 12, 2015 19:25_

The checkbox control doesn't position well when used in a popup menu.

_Copied from original issue: domokit/mojo#161_

**Comment by HansMuller** [comment]
Addressed by CheckedPopupMenuItem - https://github.com/flutter/flutter/pull/2216
