### ISSUE TITLE
Sin/Cos canvas path

### ISSUE THREAD

**Issue by r-mzy47** [flutter/flutter#98008]
Hello. I was considering implementing a wave-like motion. so I need some sin or cos path. I have tried to implement it and make a pr to flutter engine and I need some help. 
[here](https://github.com/flutter/engine/blob/main/lib/ui/painting.dart) at `painting.dart` file in flutter engine, at line 2355: there is some `native` keyword. and is referencing to `Path_conicTo`. I could not find any documentation about this `native` keyword. and could you please help me how can I add sin/cos path functions?

Thanks in advance.

**Comment by danagbemava-nc** [comment]
> there is some `native` keyword. and is referencing to Path_conicTo

The `native` keyword from what I understand, means that the implementation of that method is deferred to a native call. Kindly see https://dart.dev/server/c-interop-native-extensions for more information. 

The actual implementation of `void conicTo(double x1, double y1, double x2, double y2, double w)` can be found in 
https://github.com/flutter/engine/blob/c797abff336f96a5cb9ae027ed6b34d0b6131bbf/lib/ui/painting/path.cc#L150-L153

In the future, kindly visit any of the communities in https://flutter.dev/community#community-grid for asking these kinds of questions. 

Closing as this is neither a feature request nor a bug report.  

Thank you
