### ISSUE TITLE
[windows 7] Sougou pinyin IME doesn't work with Textfield or CupertinoTextfield.

### ISSUE THREAD

**Issue by liqping** [flutter/flutter#98006]
1. flutter version: stable 2.10.0  dart 2.16.0
2. only windows 7
3. only input Chinese
4. word disorder and insert letter
5. video

https://user-images.githubusercontent.com/62126718/152928611-48064740-501a-46c6-9219-e4097bba6c3a.mp4

6.code

```dart
class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return Center(
      child: Column(
        children: [
          TextField(),
          CupertinoTextField(),

        ],
      ),
    );
  }
}
```
flutter doctor  -v

```
[√] Flutter (Channel stable, 2.10.0, on Microsoft Windows [Version 10.0.19043.1466], locale zh-CN)
    • Flutter version 2.10.0 at D:\fluter
    • Upstream repository https://gitee.com/mirrors/Flutter.git
    • FLUTTER_GIT_URL = https://gitee.com/mirrors/Flutter.git
    • Framework revision 5f105a6ca7 (6 days ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\liping\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: D:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.3)
    • Visual Studio at D:\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31424.327
    • Windows 10 SDK version 10.0.19041.0
```

**Comment by liqping** [comment]
https://user-images.githubusercontent.com/62126718/152930929-7ed5e980-d9b9-4830-b241-79cb694e0644.mp4

**Comment by maheshmnj** [comment]
Hi @liqping, Thanks for filing the issue. If I am understanding it correctly when you enter some characters and delete the cursor ends up in the middle of the text is that correct? 
Also if the characters are wrongly entered, could you please specify what English Keys needs to be pressed and what characters do you expect in the TextField?

Thanks

**Comment by wch1618** [comment]
Such problems will occur when you use input methods such as Sogou. You can add the following code to improve it,
`TextField(
        keyboardType: TextInputType.multiline,
        maxLines: null,
      ),`

**Comment by wch1618** [comment]
> 



> 1. flutter version: stable 2.10.0  dart 2.16.0
> 2. only windows 7
> 3. only input Chinese
> 4. word disorder and insert letter
> 5. video
> 
>  Rec.0001.mp4 
> 6.code
> 
> ```dart
> class _MyHomePageState extends State<MyHomePage> {
> 
>   @override
>   Widget build(BuildContext context) {
>     // TODO: implement build
>     return Center(
>       child: Column(
>         children: [
>           TextField(),
>           CupertinoTextField(),
> 
>         ],
>       ),
>     );
>   }
> }
> ```
> 
> flutter doctor -v
> 
> ```
> [√] Flutter (Channel stable, 2.10.0, on Microsoft Windows [Version 10.0.19043.1466], locale zh-CN)
>     • Flutter version 2.10.0 at D:\fluter
>     • Upstream repository https://gitee.com/mirrors/Flutter.git
>     • FLUTTER_GIT_URL = https://gitee.com/mirrors/Flutter.git
>     • Framework revision 5f105a6ca7 (6 days ago), 2022-02-01 14:15:42 -0800
>     • Engine revision 776efd2034
>     • Dart version 2.16.0
>     • DevTools version 2.9.2
>     • Pub download mirror https://pub.flutter-io.cn
>     • Flutter download mirror https://storage.flutter-io.cn
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
>     • Android SDK at C:\Users\liping\AppData\Local\Android\sdk
>     • Platform android-32, build-tools 32.0.0
>     • Java binary at: D:\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
>     • All Android licenses accepted.
> 
> [√] Chrome - develop for the web
>     • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe
> 
> [√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.3)
>     • Visual Studio at D:\Microsoft Visual Studio\2019\Community
>     • Visual Studio Community 2019 version 16.10.31424.327
>     • Windows 10 SDK version 10.0.19041.0
> ```



> 1. flutter version: stable 2.10.0  dart 2.16.0
> 2. only windows 7
> 3. only input Chinese
> 4. word disorder and insert letter
> 5. video
> 
>  Rec.0001.mp4 
> 6.code
> 
> ```dart
> class _MyHomePageState extends State<MyHomePage> {
> 
>   @override
>   Widget build(BuildContext context) {
>     // TODO: implement build
>     return Center(
>       child: Column(
>         children: [
>           TextField(),
>           CupertinoTextField(),
> 
>         ],
>       ),
>     );
>   }
> }
> ```
> 
> flutter doctor -v
> 
> ```
> [√] Flutter (Channel stable, 2.10.0, on Microsoft Windows [Version 10.0.19043.1466], locale zh-CN)
>     • Flutter version 2.10.0 at D:\fluter
>     • Upstream repository https://gitee.com/mirrors/Flutter.git
>     • FLUTTER_GIT_URL = https://gitee.com/mirrors/Flutter.git
>     • Framework revision 5f105a6ca7 (6 days ago), 2022-02-01 14:15:42 -0800
>     • Engine revision 776efd2034
>     • Dart version 2.16.0
>     • DevTools version 2.9.2
>     • Pub download mirror https://pub.flutter-io.cn
>     • Flutter download mirror https://storage.flutter-io.cn
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
>     • Android SDK at C:\Users\liping\AppData\Local\Android\sdk
>     • Platform android-32, build-tools 32.0.0
>     • Java binary at: D:\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
>     • All Android licenses accepted.
> 
> [√] Chrome - develop for the web
>     • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe
> 
> [√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.3)
>     • Visual Studio at D:\Microsoft Visual Studio\2019\Community
>     • Visual Studio Community 2019 version 16.10.31424.327
>     • Windows 10 SDK version 10.0.19041.0
> ```

Such problems will occur when you use input methods such as Sogou. You can add the following code to improve it,
`TextField( 
keyboardType: TextInputType.multiline,
 maxLines: null,
 ),`

**Comment by wch1618** [comment]
Such problems will occur when you use input methods such as Sogou. You can add the following code to improve it.
`TextField( 
keyboardType: TextInputType.multiline,
 maxLines: null,
 ),
`

**Comment by liqping** [comment]
@maheshmnj 
1. It works fine in windows 10. It happend only on windows 7.
2. Microsoft pinyin and google pinyin works fine , but It happend such as Sougou,baidu IME  on windows 7.
3. It happend any english  characters , but not specify.

**Comment by liqping** [comment]
@wch1618 thanks! I try~

**Comment by liqping** [comment]
@wch1618 It worsk fine only maxlines == null. How to limit lines? I need single line.

**Comment by wch1618** [comment]
>@[liqping](https://github.com/liqping)  Add limit logic in onChanged

**Comment by liqping** [comment]
@wch1618 thanks!

**Comment by liqping** [comment]
@wch1618 It is very inconvenient and Tedious！It is a solution now only.

**Comment by maheshmnj** [comment]
> 1. It works fine in windows 10. It happend only on windows 7.
> 2. Microsoft pinyin and google pinyin works fine , but It happend such as Sougou,baidu IME  on windows 7.
> 3. It happend any english  characters , but not specify.

Thanks for the info labeling this issue for further investigation.

**Comment by gspencergoog** [comment]
cc @cbracken

**Comment by dansunhappy** [comment]
google pinyin  and shift+ctrl 
![企业微信截图_16492998385285](https://user-images.githubusercontent.com/12166990/162111158-eb1233b2-1d0b-4dc5-83ed-19b0ef936ceb.png)

**Comment by 15563988825** [comment]
the same question

**Comment by fanfajin** [comment]
<img width="530" alt="11" src="https://user-images.githubusercontent.com/69191321/173212752-8bd2d5e1-bec5-4384-ab6a-f83af8699c5a.png">

**Comment by fanfajin** [comment]
https://user-images.githubusercontent.com/69191321/173213143-cea43183-f08e-4982-87fb-5f8ed603cc82.mp4

**Comment by fanfajin** [comment]
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.2, on Microsoft Windows [版本 10.0.22000.675], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Enterprise 2022 17.0.6)
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.68.0)
[√] Connected device (3 available)
[√] HTTP Host Availability
