### ISSUE TITLE
Collect framework benchmarks

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#98004]
This is the first step to separate benchmarks from other functional tests in framework.

Let's collect the benchmark list according to platforms here to track all benchmarks. 

The list can be retrieved by looking at a [commit folder in GCS](https://pantheon.corp.google.com/storage/browser/flutter-skia-perf-prod/flutter-flutter/2022?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&project=flutter-infra&prefix=&forceOnObjectsSortingFiltering=false). A commit which has all tasks passing on the [build dashboard ](https://flutter-dashboard.appspot.com/#/build) indicates all benchmarks are running successfully and have uploaded their metrics in GCS.

**Comment by KristinBi** [comment]
Overall 107 benchmark tests have been counted in flutter/flutter. According to platforms, they are:

Linux_android：63
analyzer_benchmark
android_stack_size_test
android_view_scroll_perf__timeline_summary
animated_image_gc_perf
animated_placeholder_perf__e2e_summary
backdrop_filter_perf__e2e_summary
backdrop_filter_perf__timeline_summary
basic_material_app_android__compile
color_filter_and_fade_perf__e2e_summary
color_filter_and_fade_perf__timeline_summary
complex_layout__start_up
complex_layout_android__compile
complex_layout_android__scroll_smoothness
complex_layout_scroll_perf__devtools_memory
complex_layout_scroll_perf__memory
complex_layout_scroll_perf__timeline_summary
complex_layout_semantics_perf
cubic_bezier_perf__e2e_summary
cubic_bezier_perf__timeline_summary
cubic_bezier_perf_sksl_warmup__e2e_summary
cubic_bezier_perf_sksl_warmup__timeline_summary
cull_opacity_perf__e2e_summary
cull_opacity_perf__timeline_summary
fading_child_animation_perf__timeline_summary
fast_scroll_heavy_gridview__memory
fast_scroll_large_images__memory
flutter_engine_group_performance
flutter_gallery__back_button_memory
flutter_gallery__image_cache_memory
flutter_gallery__memory_nav
flutter_gallery__start_up_delayed
flutter_gallery__start_up
flutter_gallery_android__compile
flutter_gallery_v2_web_compile_test
flutter_test_performance
frame_policy_delay_test_android
fullscreen_textfield_perf__timeline_summary
hello_world__memory
home_scroll_perf__timeline_summary
hot_mode_dev_cycle_linux__benchmark
image_list_jit_reported_duration
image_list_reported_duration
imagefiltered_transform_animation_perf__timeline_summary
large_image_changer_perf_android
linux_chrome_dev_mode
multi_widget_construction_perf__e2e_summary
new_gallery__crane_perf
new_gallery__transition_perf
opacity_peephole_col_of_alpha_savelayer_rows_perf__e2e_summary
opacity_peephole_col_of_rows_perf__e2e_summary
opacity_peephole_fade_transition_text_perf__e2e_summary
opacity_peephole_grid_of_alpha_savelayers_perf__e2e_summary
opacity_peephole_grid_of_opacity_perf__e2e_summary
opacity_peephole_one_rect_perf__e2e_summary
opacity_peephole_opacity_of_grid_perf__e2e_summary
picture_cache_perf__e2e_summary
picture_cache_perf__timeline_summary
platform_channels_benchmarks
platform_views_scroll_perf__timeline_summary
textfield_perf__e2e_summary
textfield_perf__timeline_summary
tiles_scroll_perf__timeline_summary
web_size__compile_test

Mac_ios： 21
animation_with_microtasks_perf_ios__timeline_summary
backdrop_filter_perf_ios__timeline_summary
basic_material_app_ios__compile
complex_layout_ios__compile
complex_layout_ios__start_up
complex_layout_scroll_perf_ios__timeline_summary
cubic_bezier_perf_ios_sksl_warmup__timeline_summary
flutter_gallery_ios__compile
flutter_gallery_ios__start_up
hello_world_ios__compile
hot_mode_dev_cycle_ios__benchmark
hot_mode_dev_cycle_macos_target__benchmark
large_image_changer_perf_ios
macos_chrome_dev_mode
microbenchmarks_ios
new_gallery_ios__transition_perf
platform_channels_benchmarks_ios
platform_views_scroll_perf_ios__timeline_summary
post_backdrop_filter_perf_ios__timeline_summary
simple_animation_perf_ios
tiles_scroll_perf_ios__timeline_summary

Mac_ios32: 1
flutter_gallery__transition_perf_e2e_ios32

Windows_android: 5
basic_material_app_win__compile
complex_layout_win__compile
flutter_gallery_win__compile
hot_mode_dev_cycle_win__benchmark
windows_chrome_dev_mode

Mac_android: 4
flutter_gallery_mac__start_up
hello_world_android__compile
hot_mode_dev_cycle__benchmark
microbenchmarks

Windows: 1
hot_mode_dev_cycle_win_target__benchmark

Linux: 3
technical_debt__cost
web_benchmarks_canvaskit
web_benchmarks_html

some benchmark tests are shown in flutter/flutter, but cannot be found in build dashboard and are not sure for the platforms: 9
flutter_gallery__transition_perf_e2e_ios
flutter_gallery__transition_perf_e2e
flutter_gallery__transition_perf_hybrid
flutter_gallery__transition_perf
flutter_gallery__transition_perf_with_semantics
flutter_gallery_ios__transition_perf
flutter_gallery_ios_sksl_warmup__transition_perf
flutter_gallery_sksl_warmup__transition_perf_e2e
flutter_gallery_sksl_warmup__transition_perf

**Comment by keyonghan** [comment]
> Mac_ios32: 1
   flutter_gallery__transition_perf_e2e_ios32

We can ignore this test, as ios32 ones are deprecated.

> some benchmark tests are shown in flutter/flutter, but cannot be found in build dashboard and are not sure for the platforms: 9
flutter_gallery__transition_perf_e2e_ios
flutter_gallery__transition_perf_e2e
flutter_gallery__transition_perf_hybrid
flutter_gallery__transition_perf
flutter_gallery__transition_perf_with_semantics
flutter_gallery_ios__transition_perf
flutter_gallery_ios_sksl_warmup__transition_perf
flutter_gallery_sksl_warmup__transition_perf_e2e
flutter_gallery_sksl_warmup__transition_perf

These are the legacy ones running in staging: https://ci.chromium.org/p/flutter/g/devicelab_benchmark/console

**Comment by godofredoc** [comment]
Obsolete!
