### ISSUE TITLE
How to test native code?

### ISSUE THREAD

**Issue by LeonardoRosaa** [flutter/flutter#98017]
Hey,

I did create a plugin and for this plugin there's unit tests on Android native code.

I try execute this command to run my tests:

```shell
./gradlew test       
```
I don't found nothing about how to fix it.

## Steps to Reproduce

1. Create a plugin;
2. Create an unit test to this plugin;
3. Try execute the unit test by command line.

## Logs

<details>
<summary>Logs</summary>
```
```

> Task :compileDebugKotlin FAILED
e: /home/leonardoororsaa/www/open_source/have_app/android/src/main/kotlin/com/leonardo/have_app/HaveAppPlugin.kt: (4, 28): Unresolved reference: NonNull
e: /home/leonardoororsaa/www/open_source/have_app/android/src/main/kotlin/com/leonardo/have_app/HaveAppPlugin.kt: (11, 8): Unresolved reference: io
e: /home/leonardoororsaa/www/open_source/have_app/android/src/main/kotlin/com/leonardo/have_app/HaveAppPlugin.kt: (12, 8): Unresolved reference: io
e: /home/leonardoororsaa/www/open_source/have_app/android/src/main/kotlin/com/leonardo/have_app/HaveAppPlugin.kt: (13, 8): Unresolved reference: io
e: /home/leonardoororsaa/www/open_source/have_app/android/src/main/kotlin/com/leonardo/have_app/HaveAppPlugin.kt: (14, 8): Unresolved reference: io
e: /home/leonardoororsaa/www/open_source/have_app/android/src/main/kotlin/com/leonardo/have_app/HaveAppPlugin.kt: (20, 23): Unresolved reference: FlutterPlugin
e: /home/leonardoororsaa/www/open_source/have_app/android/src/main/kotlin/com/leonardo/have_app/HaveAppPlugin.kt: (20, 38): Unresolved reference: MethodCallHandler
e: /home/leonardoororsaa/www/open_source/have_app/android/src/main/kotlin/com/leonardo/have_app/HaveAppPlugin.kt: (25, 35): Unresolved reference: MethodChannel
e: /home/leonardoororsaa/www/open_source/have_app/android/src/main/kotlin/com/leonardo/have_app/HaveAppPlugin.kt: (33, 5): 'onAttachedToEngine' overrides nothing
e: /home/leonardoororsaa/www/open_source/have_app/android/src/main/kotlin/com/leonardo/have_app/HaveAppPlugin.kt: (33, 38): Unresolved reference: NonNull
e: /home/leonardoororsaa/www/open_source/have_app/android/src/main/kotlin/com/leonardo/have_app/HaveAppPlugin.kt: (33, 68): Unresolved reference: FlutterPlugin
e: /home/leonardoororsaa/www/open_source/have_app/android/src/main/kotlin/com/leonardo/have_app/HaveAppPlugin.kt: (34, 19): Unresolved reference: MethodChannel
e: /home/leonardoororsaa/www/open_source/have_app/android/src/main/kotlin/com/leonardo/have_app/HaveAppPlugin.kt: (41, 5): 'onMethodCall' overrides nothing
e: /home/leonardoororsaa/www/open_source/have_app/android/src/main/kotlin/com/leonardo/have_app/HaveAppPlugin.kt: (41, 32): Unresolved reference: NonNull
e: /home/leonardoororsaa/www/open_source/have_app/android/src/main/kotlin/com/leonardo/have_app/HaveAppPlugin.kt: (41, 46): Unresolved reference: MethodCall
e: /home/leonardoororsaa/www/open_source/have_app/android/src/main/kotlin/com/leonardo/have_app/HaveAppPlugin.kt: (41, 59): Unresolved reference: NonNull
e: /home/leonardoororsaa/www/open_source/have_app/android/src/main/kotlin/com/leonardo/have_app/HaveAppPlugin.kt: (41, 75): Unresolved reference: MethodChannel
e: /home/leonardoororsaa/www/open_source/have_app/android/src/main/kotlin/com/leonardo/have_app/HaveAppPlugin.kt: (59, 5): 'onDetachedFromEngine' overrides nothing
e: /home/leonardoororsaa/www/open_source/have_app/android/src/main/kotlin/com/leonardo/have_app/HaveAppPlugin.kt: (59, 40): Unresolved reference: NonNull
e: /home/leonardoororsaa/www/open_source/have_app/android/src/main/kotlin/com/leonardo/have_app/HaveAppPlugin.kt: (59, 57): Unresolved reference: FlutterPlugin

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
7 actionable tasks: 1 executed, 6 up-to-date
```
```
</details>

<details>
<summary>Flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.10.0, on Ubuntu 20.04.2 LTS 5.13.0-28-generic, locale en_AU.UTF-8)
    • Flutter version 2.10.0 at /home/leonardoororsaa/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (6 days ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/leonardoororsaa/Android/Sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /home/leonardoororsaa/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7621141/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/leonardoororsaa/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7621141
    • Flutter plugin version 63.2.1
    • Dart plugin version 203.8452
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Android Studio (version 4.1)
    • Android Studio at /home/leonardoororsaa/Downloads/android-studio
    • Flutter plugin version 57.0.1
    • Dart plugin version 201.9380
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at /home/leonardoororsaa/.local/share/JetBrains/Toolbox/apps/IDEA-C/ch-0/211.7628.21
    • Flutter plugin version 58.0.3
    • Dart plugin version 211.7665

[✓] VS Code (version 1.56.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.2 LTS 5.13.0-28-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.90

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by darshankawar** [comment]
@LeonardoRosaa 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/10824, so please follow-up in it for further updates.
Also, check this wiki link and see if it helps. https://github.com/flutter/flutter/wiki/Plugin-Tests
Closing this in favor of linked issue.
