### ISSUE TITLE
FlutterEngineGroup  Exception:`Failed to access the internal image decoder registry on this isolate`

### ISSUE THREAD

**Issue by chrisLiuYan** [flutter/flutter#98013]
We created the FlutterEngine with the FlutterEngineGroup and found a problem. 

Specific steps:
1. navigationController push a FlutterViewController 
2. navigationController push a native page
3. app back to the background
4. app enter foreground
5. click the button and call navigationController's popToRootViewControllerAnimated to exit the stack

Repeat twice, on the third time
After entering the FlutterViewController, all images cannot be loaded

flutter version：2.8.1,2.10.0

As long as the FlutterViewController is not the top page of the stack, the background enters the foreground and popToRootViewControllerAnimated is called, this problem will occur, and it will crash in 2.5.3

![image](https://user-images.githubusercontent.com/11593845/152940627-fcf74b48-d7f8-4ded-ab8f-92da1cd1f110.png)

demo:
[multiple_flutters_module_ios.zip](https://github.com/flutter/flutter/files/8021686/multiple_flutters_module_ios.zip)

**Comment by chrisLiuYan** [comment]
@darshankawar It doesn't work

**Comment by darshankawar** [comment]
@chrisLiuYan 
Thanks. How do I use the zip you shared earlier to run and see the behavior ?

**Comment by chrisLiuYan** [comment]
1.Unzip and get two folders：multiple_flutters_ios、multiple_flutters_module

2.multiple_flutters_module：
flutter build ios 

3.multiple_flutters_ios
pod install
open MultipleFluttersIos.xcworkspace with Xcode

**Comment by darshankawar** [comment]
Thanks. Can you let us know exact steps to replicate along with actual vs expected results ?

**Comment by chrisLiuYan** [comment]
@darshankawar @TahaTesser 

exact steps:
1. click "Next"
2. click "Next"
3. enter background
4. enter foreground
5. click "PopToRoot"

Repeat twice, on the third time the problem has arisen.

**Comment by darshankawar** [comment]
@chrisLiuYan 
I followed above steps and ran it on physical device as well as on simulator using latest stable, but was unable to replicate the behavior you reported.
Also, as a note, I couldn't find `PopToRoot` button while navigating through the app.


https://user-images.githubusercontent.com/67046386/154065920-e4ce6288-3b19-4c23-8c58-f5ec6d4705a5.MP4



<img width="370" alt="Screenshot 2022-02-15 at 6 21 30 PM" src="https://user-images.githubusercontent.com/67046386/154065979-21578ed2-9ca3-48fc-b2d3-302aa3ed936a.png">

```

[✓] Flutter (Channel stable, 2.10.1, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.10.1 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (5 days ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

**Comment by chrisLiuYan** [comment]
> We created the FlutterEngine with the FlutterEngineGroup and found a problem.
> 
> Specific steps:
> 
> 1. navigationController push a FlutterViewController
> 2. navigationController push a native page
> 3. app back to the background
> 4. app enter foreground
> 5. click the button and call navigationController's popToRootViewControllerAnimated to exit the stack
> 
> Repeat twice, on the third time After entering the FlutterViewController, all images cannot be loaded
> 
> flutter version：2.8.1,2.10.0
> 
> As long as the FlutterViewController is not the top page of the stack, the background enters the foreground and popToRootViewControllerAnimated is called, this problem will occur, and it will crash in 2.5.3
> 
> ![image](https://user-images.githubusercontent.com/11593845/152940627-fcf74b48-d7f8-4ded-ab8f-92da1cd1f110.png)
> 
> demo: [multiple_flutters_module_ios.zip](https://github.com/flutter/flutter/files/8021686/multiple_flutters_module_ios.zip)

@darshankawar 
I'm so sorry, I replaced the sample project zip file`multiple_flutters_module_ios.zip` when this issue created ,cause I uploaded the old one at the start, so , can you redownload the `multiple_flutters_module_ios.zip` and try it again, thanks.

**Comment by darshankawar** [comment]
Thanks for the update. Using the latest code, I was able to replicate this behavior and see below:

<img width="375" alt="Screenshot 2022-02-16 at 11 56 12 AM" src="https://user-images.githubusercontent.com/67046386/154208599-b3a36bf4-a7f4-4df7-9ae4-21bc3cd5fee4.png">

`The exception received is: Failed to access internal image decoder registry on this isolate.`

The error probably seems to be coming from:

<img width="1024" alt="Screenshot 2022-02-16 at 11 59 45 AM" src="https://user-images.githubusercontent.com/67046386/154209055-51415a0a-0cfd-474d-bd4a-93e02a2d7089.png">


<details>
<summary> stable, master flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.10.1, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.10.1 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (5 days ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.


[✓] Flutter (Channel master, 2.11.0-0.0.pre.581, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.11.0-0.0.pre.581 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2097fe64f0 (37 minutes ago), 2022-02-16 06:20:22 +0200
    • Engine revision 4ea2394b8d
    • Dart version 2.17.0 (build 2.17.0-105.0.dev)
    • DevTools version 2.10.0

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.4 19E2269
      darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

**Comment by chinmaygarde** [comment]
cc @gaaclarke

**Comment by gaaclarke** [comment]
I haven't had a chance to reproduce it yet, but looking at the evidence I found a plausible explanation for the issue.

ImageDecoder is [owned by the Engine](https://github.com/flutter/engine/blob/fa29cf45b36096a5a5c7641197998efbc2516ace/shell/common/engine.h#L936), but the `UIDartState::Context` maintains a weak reference to it and `UIDartState::Context` is [shared between lightweight flutter engines](https://github.com/gaaclarke/engine/blob/9f99d99628ee4a658f4fff206f588592278ed6b0/runtime/dart_isolate.cc#L107).

So, I suspect we need to update the spawn's `Context` to point to the `Engine` associated with it, or we need to share the `ImageDecoder` between the engines.  I don't remember this showing up as a significant memory cost so there isn't much pressure to share them.

I'm also getting *deja vu* about this issue.  I wonder if we already fixed this and it got lost somehow.  Maybe it was just something similar.

**Comment by gaaclarke** [comment]
This is the PR I was thinking about that was related where we had a problem with ImageDecoders and lightweight flutter engines: https://github.com/flutter/engine/pull/29915

**Comment by gaaclarke** [comment]
So it seems like https://github.com/flutter/engine/pull/29915 fixed this problem for ImageDecoder, but there is still an issue related to the `ImageGeneratorRegistry`.

At [image_descriptor.cc#L79:L79](https://github.com/gaaclarke/engine/blob/9f99d99628ee4a658f4fff206f588592278ed6b0/lib/ui/painting/image_descriptor.cc#L79:L79):
```
(lldb) p (bool)dart_state->GetImageDecoder()
(bool) $3 = true
(lldb) p (bool)dart_state->GetImageGeneratorRegistry()
(bool) $4 = false
```

**Comment by gaaclarke** [comment]
I believe I've recreated the failure case in a unit test: https://github.com/flutter/engine/pull/31622
