### ISSUE TITLE
Remove `flutter_service_worker.js` when building web app with `--pwa-strategy=none`

### ISSUE THREAD

**Issue by jxstxn1** [flutter/flutter#98026]
When I build my web application with `--pwa-strategy=none` I get an empty `flutter_service_worker.js` file. Why is this file still created? I think it would make more sense if it is not created in this case.

**Comment by danagbemava-nc** [comment]
Hi @jxstxn1, it looks like this is working as intended. 
The `--pwa-strategy=none` is intended to 

```
Generate a service worker with no body. 
This is useful for local testing or in cases where the service worker caching functionality is not desirable
```

Is your intent to not support pwas or you just don't want to use the caching strategy?

**Comment by jxstxn1** [comment]
My main Intent is that the Current Caching Strategy make problems after I redeployed my application. Some Customers need to double reload until it works again.
So I used `--pwa-strategy=none`. My question is:
Why do we need to keep the empty file and don't delete it?

**Comment by danagbemava-nc** [comment]
I believe the code that registers the `serviceWorker` requires that the file be there. If the file is deleted it can't be referenced as there'll be an error thrown in the console.

I believe you should see that in your `index.html` file

**Comment by jxstxn1** [comment]
Then why don't we update the code so that this file is not necessary anymore 🤔
I see no reason except for the existing code in the `index.html` that we should keep this file with `--pwa-strategy=none`

**Comment by danagbemava-nc** [comment]
The `navigator.serviceWorker.register()` method requires that a service worker file be provided, otherwise, the registration of the serviceWorker fails. This isn't something that flutter has any control over. 

Kindly see https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerContainer/register for more information.
