### ISSUE TITLE
[Cupertino icons]Glyphs for car and car_fill from CupertinoIcons are broken

### ISSUE THREAD

**Issue by ivanmarincic** [flutter/flutter#98029]
## Steps to Reproduce

1. Open Cupertino Icons [documentation](https://api.flutter.dev/flutter/cupertino/CupertinoIcons-class.html)
2. Find [car](https://api.flutter.dev/flutter/cupertino/CupertinoIcons/car-constant.html) or [car_fill](https://api.flutter.dev/flutter/cupertino/CupertinoIcons/car_fill-constant.html) constant

**Expected results:** 

![image](https://user-images.githubusercontent.com/9920431/152994275-8670b095-da1c-4935-bb9a-54655815f0d2.png)

**Actual results:** 

![image](https://user-images.githubusercontent.com/9920431/152994327-54f1a6c4-39d9-48e1-a9e8-c0a8578a701d.png)

**Comment by guidezpl** [comment]
@xster I don't know much about `CupertinoIcons`, could you help provide some context for where the font comes from, how to generate it, etc.?

**Comment by maheshmnj** [comment]
Here's how the icon is supposed to look

*Screenshot from SF symbols*

<img width="690" alt="image" src="https://user-images.githubusercontent.com/31410839/153396712-151631dc-ed83-45c4-813f-3653ee4aa556.png">

**Comment by jahnli** [comment]
@maheshmnj   Can you tell me the address of the website in the screenshot?

**Comment by maheshmnj** [comment]
> @maheshmnj Can you tell me the address of the website in the screenshot?

@jahnli https://fonts.google.com/icons

**Comment by maheshmnj** [comment]
@jahnli The screenshot is from SF symbols app https://developer.apple.com/sf-symbols/

**Comment by jahnli** [comment]
@maheshmnj  It seems that there is only a material icon and no Cupertino icon

**Comment by jahnli** [comment]
@maheshmnj  thank you

**Comment by LongCatIsLooong** [comment]
Should be fixed in CupertinoIcons 1.08
