### ISSUE TITLE
Scaffold background doesn't repaint when window resizes?

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#9802]
This is on fuchsia.  I've a flutter app that has a scaffold with a background color.  When I resize the app the scaffold doesn't redraw its background.  We're seeing something similar with Material.

**Comment by apwilson** [comment]
If I just use a container with color set instead there's no painting issue.

**Comment by eseidelGoogle** [comment]
Is this a recent regression?

**Comment by yyoon** [comment]
We're having the same issue in a different app on fuchsia.
In our case, we're just using `Material`, not `Scaffold`. In our case we don't even have animations like in @apwilson 's app.

cc/ @jxson

**Comment by yyoon** [comment]
BTW, I believe this started to happen yesterday.

**Comment by eseidelGoogle** [comment]
@chinmaygarde @jason-simmons could this be related to the physical model layer changes?  Is there some easy way for us to test?

**Comment by eseidelGoogle** [comment]
Do we have the ability to bisect with Fuchsia and understand when it started to happen?

**Comment by zoechi** [comment]
Is this still an issue?

**Comment by zoechi** [comment]
This issue looks stale.
Please reopen if you think this is still an issue. (or add a comment to have it reopened)
