### ISSUE TITLE
Flutter signedapk build error in android studio

### ISSUE THREAD

**Issue by yassalahmad** [flutter/flutter#98036]
[](https://stackoverflow.com/posts/71035944/timeline)0

Task :app:compileFlutterBuildRelease Can't load Kernel binary: Invalid kernel binary format version. Dart snapshot generator failed with exit code 254 Can't load Kernel binary: Invalid kernel binary format version. Dart snapshot generator failed with exit code 254

## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @yassalahmad, please provide the following information. 

- The full `flutter run/build appbundle/apk -v` log depending on whether or not you're running debug or building an `apk` or `appbundle`
- Your `android/app/build.gradle`
- `flutter doctor -v`

Thank you
