### ISSUE TITLE
Add a --android-sdk option to `flutter config`

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#9803]
For cases where our `AndroidSdk` [discovery](https://github.com/flutter/flutter/blob/f79b3338821dbabf2b0d31d42cd419e9e89a9068/packages/flutter_tools/lib/src/android/android_sdk.dart#L68) can't find the user's desired Android SDK, we should provide the ability for the user to use `flutter config --android-sdk=...`.

Blocks https://github.com/flutter/flutter-intellij/issues/981

**Comment by skybrian** [comment]
We don't strictly need this in the Flutter plugin, because instead we can set the ANDROID_HOME environment variable when launching the subprocess. But perhaps using a flag instead would be more explicit?

**Comment by tvolkert** [comment]
Closing - we can re-open if we end up needing it.
