### ISSUE TITLE
app-release.apk results in auth failure, while running main.dart on Android Studio is auth success

### ISSUE THREAD

**Issue by andesappal** [flutter/flutter#98032]
## Steps to Reproduce

1. Run `flutter build apk -t lib/src/main.dart --split-per-abi` on the Terminal outside of Android Studio
2. Open `build/app/outputs/flutter-apk/app-release.apk`
3. Click on 'Sign in with Google', and get authentication failure. 
4. Check that the same app on Android Studio, running main.dart, signs in with Google without issues. 

**Expected results:**  I expected to sign in with Google on the APK without issues 

**Actual results:**  Did not sign in with Google on the APK. 

The noticeable difference this time is that I am building from an M1 processor. I am not sure if that has an effect. 

<details>
<summary>`flutter doctor -v`</summary>

```
kevin@Kevins-MacBook-Air ~ % flutter doctor -v
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6.2 20G314 darwin-arm, locale en-US)
    • Flutter version 2.8.1 at /Users/kevin/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (8 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/kevin/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] Connected device (3 available)
    • SM G996B (mobile) • RQCR1006DCV • android-arm64  • Android 12 (API 31)
    • macOS (desktop)   • macos       • darwin-arm64   • macOS 11.6.2 20G314 darwin-arm
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 98.0.4758.80

• No issues found!
kevin@Kevins-MacBook-Air ~ % 
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@andesappal 
Do you get any error message when the sign in fails ? If so, can you provide that ?
Also, what version of plugin are you using ?

**Comment by andesappal** [comment]
Hi @darshankawar. After changes made on https://github.com/flutter/flutter/issues/98055#issuecomment-1033741698, the app opens and closes, with a message:
![image](https://user-images.githubusercontent.com/54340176/153212824-bdc2751f-72df-45c4-9cdf-6599398deab2.png)

At the time when auth failed, I couldn't find any error/warning/problem messages on the Run log on Android Studio.

For auth I am using `firebase_auth: ^3.3.6`

**Comment by andesappal** [comment]
@darshankawar I also have one more information to share, which is that the app signs in the user without issues, on iOS. So auth failure is only happening with Android.

**Comment by darshankawar** [comment]
@andesappal 
`firebase_auth` is a 3rd party plugin and if issue is occuring due to it, you'll need to raise it in dedicated repo.
If this is specific to `google_sign_in` plugin, then you'll need to isolate this behavior to the plugin and see if you still get the same error or not.

**Comment by andesappal** [comment]
Hi Darshan, so https://github.com/flutter/flutter/issues/98223 was fixed, and now I am back to auth failure only on the APK
![image](https://user-images.githubusercontent.com/54340176/154097695-8d3311c8-2dd2-4135-9dc3-42e85598100d.png)

**Comment by andesappal** [comment]
iOS auth works fine

**Comment by andesappal** [comment]
It can't be a sign-in issue because I just signed in by running the app on
Android Studio

**Comment by darshankawar** [comment]
@andesappal 
This could be related to firebase_auth as you mentioned, but we would need error log or stack trace when it shows authentication failure. Also I see you have filed an issue in dedicated repo, so let's track it there.

Closing as this doesn't seem to be `google_sign_in` plugin related issue and may involve `firebase_auth`.

**Comment by andesappal** [comment]
Please reopen as we don't know for sure the cause of this issue.
