### ISSUE TITLE
[Web] Right to left text field has incorrect caret position.

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#98044]
## Steps to Reproduce

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';

void main() => runApp(const MaterialApp(
  debugShowCheckedModeBanner: false,
  home: Scaffold(
    body: TextField(
      textDirection: TextDirection.rtl,
    ),
  ),
));
```
![image](https://user-images.githubusercontent.com/47866232/153050437-fc6fec2a-9ad5-4f26-9742-9a53146a3b34.png)

This only happens on web. In Android it works correctly. This is likely a bug in TextPainter.getOffsetForCaret returns wrong offset in web implementation.

**Comment by chunhtai** [comment]
cc @mdebbar

**Comment by chunhtai** [comment]
how do i check which mode? I ran this using` fllutter run -d chrome`

**Comment by mdebbar** [comment]
Duplicate of https://github.com/flutter/flutter/issues/78550

@chunhtai you can check the `<body>` tag and see what `flt-renderer` it shows.
