### ISSUE TITLE
ld: framework not found url_launcher on Flutter 2.10.0 

### ISSUE THREAD

**Issue by ashish12s3** [flutter/flutter#98040]
I started facing an issue of `framework not found`, when upgraded flutter from 2.8.1 to 2.10.1. 
 I'm working on mac m1 
I tried pub and pod clean  with complete cache by using below command and also tried fresh setup on new system 
  ```
flutter clean
  pod cache clean 'FortifySec' --all
   rm -rf Pods
  pod deintegrate
  rm -rf ~/Library/Developer/Xcode/DerivedData/*
  rm -rf ~/Library/Caches/CocoaPods
  rm -rf ../pubspec.lock
  rm -rf .symlinks
  pod cache clean --all
  flutter pub cache clean
```
  attaching build log 
in flutter doctor all correct
 
[build.log](https://github.com/flutter/flutter/files/8025293/build.log)

**Comment by maheshmnj** [comment]
Hi @ashish12s3, Thanks for filing the issue. Does the app build fine when you run from xcode by running 
`open ios/Runner.xcworkspace` from root of project? 

Is this issue when running on a physical ios device or simulator or both?

Please attach 
- `pubspec.yaml`, 
- Podfile
- output of `flutter doctor -v`

**Comment by ashish12s3** [comment]
@maheshmnj 
Is this issue when running on a physical ios device or simulator or both?
for all case 

but my issue resolved by removing the entry from 

xcode-> target->build setting -> other flag 

```
-framwork
url_launcher
```

and remove all entries that create problems.
