### ISSUE TITLE
Bump path package version in next beta version

### ISSUE THREAD

**Issue by amanv8060** [flutter/flutter#98051]
The current version of the path package in flutter_test is 1.8.0 in both stable and beta versions.

The newer version is already used in master : 
https://github.com/flutter/flutter/blob/0ee8e0e6fe5457e7b94e15c933733d8c5239b59e/packages/flutter_test/pubspec.yaml#L18

so maybe it can be picked up for the next beta candidate?

**Comment by stuartmorgan** [comment]
It sounds like you are asking for a cherry-pick of this version change. What is the critical need (per [policy](https://github.com/flutter/flutter/wiki/Flutter-Cherrypick-Process)) for such a cherry-pick?

**Comment by amanv8060** [comment]
not cherrypick specifically, but just an issue to keep track that it gets bumped in the next beta candidate.

**Comment by stuartmorgan** [comment]
> not cherrypick specifically, but just an issue to keep track that it gets bumped in the next beta candidate

For future reference, there are only two ways something gets into beta:
- the normal process of landing before the branch point, in which case there's no need to track anything--everything that lands before the branch point is in the branch
- a cherry pick to the existing beta

So the only reason to file an issue is if you are requesting a cherry pick.
