### ISSUE TITLE
_CastError (Null check operator used on a null value)

### ISSUE THREAD

**Issue by learner00000** [flutter/flutter#98053]
I am trying to write a simple auto login method for my application but when my application wants to execute the following code it gives me the next error:

```
  Future<bool> _autoLogin() async {
    final prefs = await SharedPreferences.getInstance();
    if (!prefs.containsKey('userData')) {
      return false;
    } else {
      _isAuth.value = true;
    }
    final Map<String, Object> extractedUserData = Map<String, Object>.from(
        json.decode(prefs.getString('userData') as String));
    final expiryDate =
        DateTime.parse(extractedUserData['expiryDate'] as String);

    if (expiryDate.isBefore(DateTime.now())) {
      return false;
    }
    _token = extractedUserData['token'] as String;
    _userId = extractedUserData['userId'] as String;
    _expiryDate = expiryDate;
    _autoLogout();
    return true;
  }
```

Error: 
`_CastError (Null check operator used on a null value)
`
And it comes from this line of the code:
` final prefs = await SharedPreferences.getInstance();
`

What is the problem and how can I fix it?

**Comment by darshankawar** [comment]
@learner00000 
Are you calling `WidgetsFlutterBinding.ensureInitialized();` inside your `main()` method ? If not, can you add this line, like below and see if it helps ?

```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
```

If not, can you provide `flutter doctor -v`, plugin version and [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) ?
Thanks.

**Comment by learner00000** [comment]
> ```
>   WidgetsFlutterBinding.ensureInitialized();
> ```

Thank you for the answer. But the first solution didn't work!
You can find the whole project's code here: https://github.com/learner00000/test  (It's a small educational project)

Also for `flutter doctor -v`:

[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19044.1466], locale en-US)
    • Flutter version 2.8.1 at C:\Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (8 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\A\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.64.0)
    • VS Code at C:\Users\A\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.34.0

[√] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 97.0.4692.99
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 98.0.1108.43

• No issues found!

**Comment by darshankawar** [comment]
@learner00000 
Thanks for the repo, but it seems to have lot of 3rd party plugin code. In order to isolate it just to shared_preferences plugin, please provide a minimal reproducible code sample involving shared_preferences plugin, so that to narrow it down.

**Comment by darshankawar** [comment]
@learner00000 
Thanks, but I do see usage of `Get` package in the updated clone which is 3rd party. 

```
void main() async {
  Get.put(AuthController());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      getPages: [
        GetPage(
            name: authenticationScreenRoute,
            page: () => const AuthenticationScreen()),
        GetPage(name: homeScreenRoute, page: () => const HomeScreen()),
      ],
 
```

Please isolate the code to only `shared_preferences` plugin and core flutter components.

**Comment by learner00000** [comment]
> @learner00000 Thanks, but I do see usage of `Get` package in the updated clone which is 3rd party.
> 
> ```
> void main() async {
>   Get.put(AuthController());
> }
> 
> class MyApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return GetMaterialApp(
>       getPages: [
>         GetPage(
>             name: authenticationScreenRoute,
>             page: () => const AuthenticationScreen()),
>         GetPage(name: homeScreenRoute, page: () => const HomeScreen()),
>       ],
>  
> ```
> 
> Please isolate the code to only `shared_preferences` plugin and core flutter components.

I think it's a conflict between GetX and Shared Preferences libraries. Because the first version of my code was using Provider package and it was working. As soon as I replaced provider package with GetX, the error happened.

**Comment by darshankawar** [comment]
Thanks for the update. Please open this issue in getX plugin repo.
Closing from here.
