### ISSUE TITLE
Flake bot should independent on builder name changes

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#98069]
Per [flutter.dev/go/smart-flutter-benchmarks](http://go/smart-flutter-benchmarks), builder names will be updated to surface `benchmark`. This will affect flake bot when retrieving test owners: https://github.com/flutter/cocoon/blob/main/app_dart/lib/src/request_handlers/flaky_handler_utils.dart#L460

Instead of using `words[1]`, we should use `words[last]`.

**Comment by KristinBi** [comment]
Created a pull request to fix this issue: https://github.com/flutter/cocoon/pull/1596

**Comment by godofredoc** [comment]
Obsolete!
