### ISSUE TITLE
FAQ is missing "what's the difference between hot restart and hot reload?"

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#9806]
We have an answer at https://flutter.io/intellij-ide/#hot-reloads-vs-full-application-restarts but we can bring this up to a general Flutter FAQ (not just for IntelliJ).

I think copying this answer into faq.md should be sufficient. :)

**Comment by NagarjunaReddyP** [comment]
What is Hot Reload in Flutter:

Flutter hot reload features works with combination of Small r key on command prompt or Terminal. Hot reload feature quickly compile the newly added code in our file and sent the code to Dart Virtual Machine. After done updating the Code Dart Virtual Machine update the app UI with widgets. Hot Reload takes less time then Hot restart. There is also a draw back in Hot Reload, If you are using States in your application then Hot Reload preservers the States so they will not update on Hot Reload our set to their default values.

What is Hot Restart in Flutter:

Hot restart is much different than hot reload. In Hot restart it destroys the preserves State value and set them to their default. So if you are using States value in your application then After every hot restart the developer gets fully compiled application and all the states will set to their defaults. The app widget tree is completely rebuilt with new typed code. Hot Restart takes much higher time than Hot reload.
