### ISSUE TITLE
pub removal requires updates to framework luci recipes

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#98060]
See https://github.com/flutter/engine/pull/31332

**Comment by zanderso** [comment]
For example here https://flutter.googlesource.com/recipes/+/refs/heads/main/recipes/devicelab/devicelab_drone.py#98

**Comment by a-siva** [comment]
I have a CL to revert removal of the pub executable here https://dart-review.googlesource.com/c/sdk/+/232131, once this lands into the dev channel I will restart the roller.

**Comment by sigurdm** [comment]
Trying to fix this here: https://flutter-review.googlesource.com/c/recipes/+/26720

**Comment by godofredoc** [comment]
@sigurdm the change has landed can we close this issue?

**Comment by sigurdm** [comment]
Yes! Thanks
