### ISSUE TITLE
Ensure that apps can be installed on the latest version of Android

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#98082]
This will help test PRs like this: https://github.com/flutter/flutter/pull/98076.

Ideally, we use Android emulators to test these type of changes.
The device lab doesn't have a device running Android S to my knowledge.

cc @GaryQian

**Comment by godofredoc** [comment]
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.
