### ISSUE TITLE
pubspec.yaml packages are installed whose versions are incompatible with specified android version

### ISSUE THREAD

**Issue by jaded0** [flutter/flutter#98080]
## Steps to Reproduce
Specify android 30 in AndroidManifest.xml
Include package dependencies in pubspec.yaml using caret notation. Any package that has updates requiring android 31 _or_ has dependencies whose newest versions require android 31 will do. 

**Expected results:** 
pub get ought to install package versions which do not require android 31. 

**Actual results:** 
pub get completes, build completes, but when time comes to test the app on a pixel 6, an error shows:     
Error: ADB exited with exit code 1
Performing Streamed Install

adb: failed to install /home/jaden/StudioProjects/Cambrio/build/app/outputs/flutter-apk/app.apk: Failure [INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl1707845282.tmp/base.apk (at Binary XML file line #117): com.folioreader.ui.activity.SearchActivity: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present]
Error launching application on Pixel 6.

**Comment by stuartmorgan** [comment]
`pub` is not aware of anything related to Android versions. If you want the ability for applications and packages to express target OS version constraints you would need to [file a feature request against pub](https://github.com/dart-lang/pub/issues).

Closing as this is part of pub, not Flutter.
