### ISSUE TITLE
Mac9 is failing tests with Dismiss dialogs failure

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#98086]
<img width="1321" alt="Screen Shot 2022-02-08 at 5 37 42 PM" src="https://user-images.githubusercontent.com/54558023/153105315-6fa9d3ef-6487-48e9-8579-b254f9b792c6.png">

Example build: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20complex_layout_scroll_perf_ios__timeline_summary/3547/overview

Have uninstalled the app manually, and it should be good to go. But we need to track why device doctor failed to uninstall those apps when recovering.

**Comment by keyonghan** [comment]
The bot is still failing tests with 
```
Infra Failure: Step('Dismiss dialogs.Run app to dismiss dialogs') (retcode: 65)
```
@godofredoc do you mind take a look? I manually quarantined the bot for now.

**Comment by godofredoc** [comment]
Tests are now passing consistently.
