### ISSUE TITLE
severe battery drain

### ISSUE THREAD

**Issue by Livinglist** [flutter/flutter#98081]
## Details

**Target Platform: iPhone**
**Target OS version/browser: iOS15**
**Devices: iPhone 12**

I have recently made a Hacker News reader with Flutter - [Hacki](https://github.com/Livinglist/Hacki), everything seemed great until I discovered its severe battery drain. Attached below are screenshots from my iPhone 12, and as you can see, one hour of Hacki usage consumed three times more battery than Youtube app.

## Logs

<details>
<summary>Logs</summary>

```
Analyzing hacki...                                                      
No issues found! (ran in 3.1s)
```

```
[✓] Flutter (Channel stable, 2.10.0, on macOS 12.1 21C52 darwin-arm, locale en)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.64.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```

</details>

<p align="center">
   <img width="400" alt="Screen Shot 2020-03-03 at 1 22 57 PM" src="https://user-images.githubusercontent.com/7277662/153067358-1c51dcd4-b180-415a-86a0-a3f89b518c57.png"> 
   <img width="400" alt="Screen Shot 2020-03-03 at 1 22 57 PM" src="https://user-images.githubusercontent.com/7277662/153067369-d757a98c-cfd0-4015-bb3b-63ee84d2c784.png"> 
</p>

**Comment by jonahwilliams** [comment]
I grabbed some profile traces while interacting the app by navigating around:

[hacki_trace.txt](https://github.com/flutter/flutter/files/8028720/hacki_trace.txt)

What I can see is that SendPort.send is easily topping the cpu chart, which is quite surprising given that only strings are being sent back and forth:

![image](https://user-images.githubusercontent.com/8975114/153105484-109e8733-e438-4dcb-9302-5ea8e7eb88f5.png)

See also:

https://github.com/Livinglist/Hacki/blob/dc4b713ec644b7b5f2bde6275116d1bbe0abfbe1/lib/screens/widgets/link_preview/web_analyzer.dart


But this code doesn't use `compute` from flutter - and doesn't use Isolate.exit correctly for cheap copies. If you replace Isolate.spawn usage with `compute`, then you don't even see SendPort on the trace:

```diff
index 6c37326..67253a6 100644
--- a/lib/screens/widgets/link_preview/web_analyzer.dart
+++ b/lib/screens/widgets/link_preview/web_analyzer.dart
@@ -5,6 +5,7 @@ import 'dart:isolate';

 import 'package:collection/collection.dart' show IterableExtension;
 import 'package:fast_gbk/fast_gbk.dart';
+import 'package:flutter/foundation.dart';
 import 'package:html/dom.dart' hide Text;
 import 'package:html/parser.dart' as parser;
 import 'package:http/http.dart';
@@ -117,53 +118,47 @@ class WebAnalyzer {
   static Future<InfoBase?> _getInfoByIsolate(
       String? url, bool multimedia) async {
     final sender = ReceivePort();
-    final isolate = await Isolate.spawn(_isolate, sender.sendPort);
-    final sendPort = await sender.first as SendPort;
-    final answer = ReceivePort();
-
-    sendPort.send([answer.sendPort, url, multimedia]);
-    final res = await answer.first as List<String?>?;
+    final List<dynamic>? res =
+        await compute(_isolate, <dynamic>[url, multimedia]);

     InfoBase? info;
     if (res != null) {
       if (res[0] == '0') {
         info = WebInfo(
-            title: res[1], description: res[2], icon: res[3], image: res[4]);
+            title: res[1] as String,
+            description: res[2] as String,
+            icon: res[3] as String,
+            image: res[4] as String);
       } else if (res[0] == '1') {
-        info = WebVideoInfo(image: res[1]);
+        info = WebVideoInfo(image: res[1] as String);
       } else if (res[0] == '2') {
-        info = WebImageInfo(image: res[1]);
+        info = WebImageInfo(image: res[1] as String);
       }
     }
-
-    sender.close();
-    answer.close();
-    isolate.kill(priority: Isolate.immediate);
-
     return info;
   }

-  static void _isolate(SendPort sendPort) {
-    final port = ReceivePort();
-    sendPort.send(port.sendPort);
-    port.listen((dynamic message) async {
-      final sender = (message as List<dynamic>)[0] as SendPort;
-      final url = message[1] as String;
-      final multimedia = message[2] as bool;
-
-      final info = await _getInfo(url, multimedia);
-
-      if (info is WebInfo) {
-        sender.send(['0', info.title, info.description, info.icon, info.image]);
-      } else if (info is WebVideoInfo) {
-        sender.send(['1', info.image]);
-      } else if (info is WebImageInfo) {
-        sender.send(['2', info.image]);
-      } else {
-        sender.send(null);
-      }
-      port.close();
-    });
+  static Future<List<dynamic>?> _isolate(dynamic message) async {
+    final url = message[0] as String;
+    final multimedia = message[1] as bool;
+
+    final info = await _getInfo(url, multimedia);
+
+    if (info is WebInfo) {
+      return <dynamic>[
+        '0',
+        info.title,
+        info.description,
+        info.icon,
+        info.image
+      ];
+    } else if (info is WebVideoInfo) {
+      return <dynamic>['1', info.image];
+    } else if (info is WebImageInfo) {
+      return <dynamic>['2', info.image];
+    } else {
+      return null;
+    }
   }
   ```


![image](https://user-images.githubusercontent.com/8975114/153106760-f8f7d4ff-43b4-4f4a-b7e8-be70de772463.png)

I also noticed that several of the corner message guys are endlessly pumping frames. @Livinglist what sort of profiling have you already done on your app?

**Comment by Livinglist** [comment]
> I grabbed some profile traces while interacting the app by navigating around:
> 
> [hacki_trace.txt](https://github.com/flutter/flutter/files/8028720/hacki_trace.txt)
> 
> What I can see is that SendPort.send is easily topping the cpu chart, which is quite surprising given that only strings are being sent back and forth:
> 
> ![image](https://user-images.githubusercontent.com/8975114/153105484-109e8733-e438-4dcb-9302-5ea8e7eb88f5.png)
> 
> See also:
> 
> https://github.com/Livinglist/Hacki/blob/dc4b713ec644b7b5f2bde6275116d1bbe0abfbe1/lib/screens/widgets/link_preview/web_analyzer.dart
> 
> But this code doesn't use `compute` from flutter - and doesn't use Isolate.exit correctly for cheap copies. If you replace Isolate.spawn usage with `compute`, then you don't even see SendPort on the trace:
> 
> ```diff
> index 6c37326..67253a6 100644
> --- a/lib/screens/widgets/link_preview/web_analyzer.dart
> +++ b/lib/screens/widgets/link_preview/web_analyzer.dart
> @@ -5,6 +5,7 @@ import 'dart:isolate';
> 
>  import 'package:collection/collection.dart' show IterableExtension;
>  import 'package:fast_gbk/fast_gbk.dart';
> +import 'package:flutter/foundation.dart';
>  import 'package:html/dom.dart' hide Text;
>  import 'package:html/parser.dart' as parser;
>  import 'package:http/http.dart';
> @@ -117,53 +118,47 @@ class WebAnalyzer {
>    static Future<InfoBase?> _getInfoByIsolate(
>        String? url, bool multimedia) async {
>      final sender = ReceivePort();
> -    final isolate = await Isolate.spawn(_isolate, sender.sendPort);
> -    final sendPort = await sender.first as SendPort;
> -    final answer = ReceivePort();
> -
> -    sendPort.send([answer.sendPort, url, multimedia]);
> -    final res = await answer.first as List<String?>?;
> +    final List<dynamic>? res =
> +        await compute(_isolate, <dynamic>[url, multimedia]);
> 
>      InfoBase? info;
>      if (res != null) {
>        if (res[0] == '0') {
>          info = WebInfo(
> -            title: res[1], description: res[2], icon: res[3], image: res[4]);
> +            title: res[1] as String,
> +            description: res[2] as String,
> +            icon: res[3] as String,
> +            image: res[4] as String);
>        } else if (res[0] == '1') {
> -        info = WebVideoInfo(image: res[1]);
> +        info = WebVideoInfo(image: res[1] as String);
>        } else if (res[0] == '2') {
> -        info = WebImageInfo(image: res[1]);
> +        info = WebImageInfo(image: res[1] as String);
>        }
>      }
> -
> -    sender.close();
> -    answer.close();
> -    isolate.kill(priority: Isolate.immediate);
> -
>      return info;
>    }
> 
> -  static void _isolate(SendPort sendPort) {
> -    final port = ReceivePort();
> -    sendPort.send(port.sendPort);
> -    port.listen((dynamic message) async {
> -      final sender = (message as List<dynamic>)[0] as SendPort;
> -      final url = message[1] as String;
> -      final multimedia = message[2] as bool;
> -
> -      final info = await _getInfo(url, multimedia);
> -
> -      if (info is WebInfo) {
> -        sender.send(['0', info.title, info.description, info.icon, info.image]);
> -      } else if (info is WebVideoInfo) {
> -        sender.send(['1', info.image]);
> -      } else if (info is WebImageInfo) {
> -        sender.send(['2', info.image]);
> -      } else {
> -        sender.send(null);
> -      }
> -      port.close();
> -    });
> +  static Future<List<dynamic>?> _isolate(dynamic message) async {
> +    final url = message[0] as String;
> +    final multimedia = message[1] as bool;
> +
> +    final info = await _getInfo(url, multimedia);
> +
> +    if (info is WebInfo) {
> +      return <dynamic>[
> +        '0',
> +        info.title,
> +        info.description,
> +        info.icon,
> +        info.image
> +      ];
> +    } else if (info is WebVideoInfo) {
> +      return <dynamic>['1', info.image];
> +    } else if (info is WebImageInfo) {
> +      return <dynamic>['2', info.image];
> +    } else {
> +      return null;
> +    }
>    }
> ```
> 
> ![image](https://user-images.githubusercontent.com/8975114/153106760-f8f7d4ff-43b4-4f4a-b7e8-be70de772463.png)
> 
> I also noticed that several of the corner message guys are endlessly pumping frames. @Livinglist what sort of profiling have you already done on your app?

jokes on me, I haven't really done any serious profiling...only have used Flutter Performance for inspecting widget rebuild stats...

This is really helpful!

**Comment by jonahwilliams** [comment]
There might be more low hanging fruit, or perhaps some issues in the framework that your app could help us uncover. Please don't hesitate to file bugs if you see things that are odd or take a significant amount of time, I'm happy to look at any open source apps :D
