### ISSUE TITLE
Would like docs on IntelliJ visual Debugging features

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#9809]
We mention them here:
https://flutter.io/debugging/#visual-debugging

But I would expect to learn about the flutter panel here:
https://flutter.io/intellij-ide/

Maybe we have docs somewhere else?  @pq

**Comment by pq** [comment]
> Maybe we have docs somewhere else?

Nope, but you're right that https://flutter.io/intellij-ide/ is where some docs should go.
