### ISSUE TITLE
Gaps in the IntelliJ instructions on running your first app

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter#9810]
The instructions on [starting your first app in IntelliJ](https://flutter.io/getting-started/#creating-your-first-flutter-app) does not mention how to start a simulator or make a device available for deployment. The screenshot on the page assumes that an iOS simulator is running. 

![image](https://cloud.githubusercontent.com/assets/348942/25724480/f5361750-30d0-11e7-8ddc-8b0315a229b3.png)

At least 3 study participants didn't know what to do when they saw a grayed out Run button after they created a new Flutter project. I suggest we explain how to make a target available in the instructions (perhaps use a screenshot with the Target selector dropdown open) and also include a tooltip to the Run button in IntelliJ when it's in the disabled state.

**Comment by InMatrix** [comment]
CC: @mit-mit

**Comment by mit-mit** [comment]
Related product issue: https://github.com/flutter/flutter-intellij/issues/971

@devoncarew any current plans to resolve that, or should I go ahead and document this for now?

**Comment by devoncarew** [comment]
We should document this for now.

**Comment by InMatrix** [comment]
Thanks for the update! Can we add the same clarification in [flutter.io/getting-started/#running-your-flutter-app](flutter.io/getting-started/#running-your-flutter-app) as well? The PR only adds that to the IntelliJ Guide.

**Comment by mit-mit** [comment]
Good idea, see https://github.com/flutter/website/pull/589
