### ISSUE TITLE
[Proposal] Update Kotlin version for Android

### ISSUE THREAD

**Issue by halimpuckjava** [flutter/flutter#98105]
hi

when create a new flutter project (flutter 2.10.0) , kotlin version by default 1.3.50, so in runtime the flutter cant build project because kotlin version is obsolete (kotlin version for project = 1.3.50) , i suggest to updated kotlin version automatically with last stable version

**Comment by halimpuckjava** [comment]
thanks

its work fine, may be the issue in internet connection

**Comment by maheshmnj** [comment]
Thanks for the confirmation closing as solved
