### ISSUE TITLE
[Docs] Add an Interactive example for FocusTrap 

### ISSUE THREAD

**Issue by mtc-jed** [flutter/flutter#98111]
I have a screen with a bunch of stuff in it, and a single TextField at the bottom. I would like the TextField to lose focus (and the keyboard to disappear) whenever the user does something else, like clicking a button or a ListTile.

I've looked at FocusTrap but I can't seem to get it to do what I'd like. For now, I'm just calling FocusScope.of(context).unfocus() everywhere but that is _not_ a good way of doing things, I'm well aware.

What is the supposed way of achieving this ? If it is [FocusTrap](https://api.flutter.dev/flutter/widgets/FocusTrap-class.html), I'd love to get an example !

Thanks.

**Comment by HansMuller** [comment]
CC @gspencergoog

**Comment by gspencergoog** [comment]
@justinmc could the OP's issue actually be the bug in `FocusTrap` that you're looking at?

**Comment by mtc-jed** [comment]
If it it [#99434](https://github.com/flutter/flutter/pull/99434) you're talking about, then that particular change of behaviour would indeed be what I'm looking for. I hope this can be implemented.

For now, I am using a `abstract class MTCState<T extends StatefulWidget> extends State<T>` with an `unfocus()` function I'm calling every chance I get, but that doesn't cover all cases and makes for a lot of boilerplate. It is at least somewhat cleaner then calling `FocusScope.of(context).unfocus();` everytime.

**Comment by justinmc** [comment]
Glad to hear that PR would work!  I'm investigating some web failures and seeing if it's viable.

**Comment by gspencergoog** [comment]
`FocusTrap` is gone, and it's replacement, `TapRegion`, has examples.
