### ISSUE TITLE
lib/main.dart and pubspec.yaml not being created when I create a new project

### ISSUE THREAD

**Issue by Powske** [flutter/flutter#98114]
## Steps to Reproduce

1. Create a new flutter project within Android Studio
2. When the new project has been created the file structure is different to how it was before. very random
3. ...

## Logs

<details>
<summary>flutter doctor -v</summary>

```
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19042.1466], locale en-GB)
    • Flutter version 2.8.1 at C:\src\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (8 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\kiero\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 97.0.4692.99
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 97.0.1072.76

• No issues found!
```

</details>

<details>
<summary>screenshots</summary>

New file set up | How it is on old projects
-- | -- 
| ![image](https://user-images.githubusercontent.com/62574154/153187841-89b326a4-8a15-4fd0-b1b4-ada9dcc0d875.png) | ![image](https://user-images.githubusercontent.com/62574154/153188430-b95fc780-845c-45df-a531-86658f8bac71.png) | 

</details>

**Comment by danagbemava-nc** [comment]
Hi @Powske, do you have this issue when you run `flutter create <foo>` from the command line?

**Comment by Powske** [comment]
Hi @danagbemava-nc 
Thanks for the response. I get the syntax of the command is incorrect.

**Comment by danagbemava-nc** [comment]
Hi @Powske, my apologies. I used `<foo>` as a stand-in for the project name. 

I should have asked you to replace `<foo>` with any project name. 

Please try the command again with any project name.

**Comment by danagbemava-nc** [comment]
Hi @Powske, there shouldn't be unless you created the project in a folder that somehow conflicted with the file generation. 

I tried creating a project with android studio and everything worked as expected.
