### ISSUE TITLE
PlatformException (VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: Source error, null, null)

### ISSUE THREAD

**Issue by kavyabhargava** [flutter/flutter#98121]
I am trying to make a reels app. I am getting this error, I checked other answers for this question all of them said there is a problem with the video but I am using cloud-firestore URL, the same URL is working for the listview Widget but not for pageview. The screen becomes completely blank when I navigate to this screen.

PageViewScreen :

<details>
<summary>code sample</summary>

```dart
class _PageViewBuilderState extends State<PageViewBuilder> {
  var network = '';
  VideoPlayerController? videoPlayerController;
  @override
  void initState() {
    super.initState();
    videoPlayerController = VideoPlayerController.network(network)
      ..addListener(() {})
      ..setLooping(true)
      ..initialize().then((value) => videoPlayerController!.play());
  }

  int _currentPage = 0;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: StreamBuilder<QuerySnapshot<Map<String, dynamic>>>(
          stream:
              FirebaseFirestore.instance.collection('Imageurls').snapshots(),
          builder: (ctx, snapshot) {
            return !snapshot.hasData
                ? const Center(
                    child: CircularProgressIndicator(),
                  )
                : PageView.builder(
                    scrollDirection: Axis.vertical,
                    itemCount: snapshot.data!.docs.length,
                    onPageChanged: (int page) {
                      setState(() {
                        _currentPage = page;
                      });
                    },
                    itemBuilder: (BuildContext context, int index) {
                      return AspectRatio(
                        aspectRatio: VideoPlayerController.network(
                          snapshot.data!.docs[index].get('url'),
                        ).value.aspectRatio,
                        child: VideoPlayer(VideoPlayerController.network(
                          snapshot.data!.docs[index].get('url'),
                        )
                          ..addListener(() {})
                          ..setLooping(true)
                          ..initialize()
                              .then((value) => VideoPlayerController.network(
                                    snapshot.data!.docs[index].get('url'),
                                  ).play())),
                      );
                     
                    },
                  );
          }),
    );
  }
}
```
</details>

**Comment by maheshmnj** [comment]
HI @kavyabhargava, Thanks for filing the issue. 

> ((value) => VideoPlayerController.network(
                                    snapshot.data!.docs[index].get('url'),
                                  ).play())),

This seems to be incorrect, where you are trying to play the video without initialization. In case you disagree, please share a complete sample code by hardcoding the video source, to investigate further along with the complete 
output of `flutter doctor -v`.

Thanks

**Comment by kavyabhargava** [comment]
> HI @kavyabhargava, Thanks for filing the issue.
> 
> > ((value) => VideoPlayerController.network(
> > snapshot.data!.docs[index].get('url'),
> > ).play())),
> 
> This seems to be incorrect, where you are trying to play the video without initialization. In case you disagree, please share a complete sample code by hardcoding the video source, to investigate further along with the complete output of `flutter doctor -v`.
> 
> Thanks

Hi Mahesh,

This is flutter doctor -v  output:
PS C:\Flutter\news_app_admin> flutter doctor -v
[√] Flutter (Channel stable, 2.10.0, on Microsoft Windows [Version 10.0.19042.1466], locale en-US)
    • Flutter version 2.10.0 at D:\flutter_windows_2.5.1-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (9 days ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0       
    • DevTools version 2.9.2    

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Kavya bhargava\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java      
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)    
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.64.1)
    • VS Code at C:\Users\Kavya bhargava\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.34.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.1466]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 98.0.4758.82
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 98.0.1108.43

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category. 

I have initialized it, here : 
  ```
child: VideoPlayer(VideoPlayerController.network(
                          snapshot.data!.docs[index].get('url'),
                        )
                          ..addListener(() {})
                          ..setLooping(true)
                          ..initialize()
                              .then((value) => VideoPlayerController.network(
                                    snapshot.data!.docs[index].get('url'),
                                  ).play())),
```

The videolink is the firebase storage download link which is being saved in the firestore cloud

**Comment by maheshmnj** [comment]
@kavyabhargava when you do `VideoPlayerController.network` you are creating a new instance of `VideoPlayerController` and each instance must be initialized before calling play

**Comment by maheshmnj** [comment]
@kavyabhargava Your code sample below is playing the video before initialization.

```
 ..initialize()
  .then((value) => VideoPlayerController.network(
   snapshot.data!.docs[index].get('url'),
 ).play())),
```

It should be 

```dart
 ..initialize()
  .then((value) => VideoPlayerController.network(
   snapshot.data!.docs[index].get('url'),
 )..initialize()
  .then((value){
     controller.play(); /// play after initialization
}),
```

I do understand that with your nested VideoPlayerController you wouldn't have access to the controller to play the video.

tbh, nesting video controllers doesn't look like a good idea, I believe you are trying to change the video source dynamically if so, You should try following up on this issue https://github.com/flutter/flutter/issues/44690  Also you can try this workaround and see if it helps https://github.com/flutter/flutter/issues/44690#issuecomment-583768093

**Comment by kavyabhargava** [comment]
I did that but that is only getting audio and not video

**Comment by maheshmnj** [comment]
> I did that but that is only getting audio and not video

@kavyabhargava could you please share a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) to investigate this further? Also, is this issue with a specific video asset or all video assets?
