### ISSUE TITLE
[gen-l10n] Generated l10n files are not formatted with `dart format`

### ISSUE THREAD

**Issue by MichaelDark** [flutter/flutter#98122]
Usually, it is needed to maintain a single code style in the project, including formatting.
This lead us to use `dart format` tool in order to keep the code base formatted properly and in a readable state.
The problem is that output files, that are generated by `flutter gen-l10n` are not formatted, which is leading to conflicts and inconsistency. 

One of the possible solutions is to exclude these generated files from formatting, but [here](https://github.com/dart-lang/dart_style/issues/864) you can see that this feature is not planned (yes, we can find some [slow workarounds](https://github.com/dart-lang/dart_style/issues/864#issuecomment-544799251) for this, but it is not worth it).

Unfortunately, I am still not too close to contributing to Flutter, so I would like to ask to add a built-in`dart format` call after files generation.

**Comment by HansMuller** [comment]
Providing a way to apply a filter, like `dart format`, to gen_l10n's output sounds reasonable.

**Comment by cedvdb** [comment]
It should be done by default without intervention.

**Comment by MichaelDark** [comment]
@HansMuller Is it a big effort proposal or we can expect it to be in the next patch (2.10.1 for example)?

**Comment by HansMuller** [comment]
It's not a terribly big effort but I don't think it will be accepted for patch release.  Patch releases are for (roughly speaking) small low risk fixes for big bugs.

**Comment by MichaelDark** [comment]
@HansMuller So, in case of some urgent fixes, we can expect this issue fixed in the next patch release, right?

**Comment by MichaelDark** [comment]
@HansMuller I have just submitted PR that could resolve this issue #98701

**Comment by bartekpacia** [comment]
I see that #98701 is closed – sad. I'd love to see this getting fixed, having to `flutter format .` before every commit (because   hot reload calls `flutter gen-l10n`, which generates non-formatted l10n files) is annoying.

**Comment by zacherygentry** [comment]
Echoing @bartekpacia, I would also really really like to see this.

**Comment by zacherygentry** [comment]
> I see that #98701 is closed – sad. I'd love to see this getting fixed, having to `flutter format .` before every commit (because hot reload calls `flutter gen-l10n`, which generates non-formatted l10n files) is annoying.

Echoing @bartekpacia, I would also really really like to see this.

**Comment by bartekpacia** [comment]
Bumpy bump :)

**Comment by HansMuller** [comment]
Providing an option to apply a post-processing pass to the generated code seems quite reasonable.  @thkim1011 - see https://github.com/flutter/flutter/pull/98701#issuecomment-1138860096

**Comment by thkim1011** [comment]
Quick update: You can now run `flutter gen-l10n --format` to format files, or if using `l10n.yaml`, add `format: true`.
