### ISSUE TITLE
Windows tool_integration_tests_3_6 flakes on `flutter_build_null_unsafe_test`

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#98140]
(part of https://github.com/flutter/flutter/issues/97036)

Hit one flake on 02/08/2022:
- [ ] [flutter_build_null_unsafe_test.dart](https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20tool_integration_tests_3_6/234/overview)
```
11:00 +17 -1: test\integration.shard\flutter_build_null_unsafe_test.dart: flutter build apk --no-sound-null-safety [E]                                                                                 
  Expected: <0>
    Actual: <1>
  
  package:test_api                                                 expect
  test\integration.shard\flutter_build_null_unsafe_test.dart 79:7  main.<fn>
  dart:async                                                       runZoned
  test\src\common.dart 197:14                                      testWithoutContext.<fn>
  test\src\common.dart 196:18                                      testWithoutContext.<fn>
  test\src\common.dart 166:18                                      test.<fn>
  test\src\common.dart 161:5                                       test.<fn>
  ```

**Comment by zanderso** [comment]
To help debug this, the test should print the output from the subprocess when the exit code is non-zero here:

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/integration.shard/flutter_build_null_unsafe_test.dart#L79

@jmagman

**Comment by jmagman** [comment]
> To help debug this, the test should print the output from the subprocess when the exit code is non-zero here:

https://github.com/flutter/flutter/pull/98310

**Comment by christopherfujino** [comment]
Closing this as stale, if this is still flaking the bot will open a new issue
