### ISSUE TITLE
Webview doesn't download

### ISSUE THREAD

**Issue by KaviHarjani** [flutter/flutter#98143]
## Steps to Reproduce

**To recreate**
Run this code and try going to any stocks page and clicking on the export to excel button, it should show the download tab or download it, instead it does nothing in the flutter webview app

**Expected results:** 

Show download tab or download the file

**Actual results:** 

Nothing, it goes to the link and refreshes the page, no download popup or file getting download

<details>
<summary>Code sample</summary>

```

              body: WebView(
                initialUrl: "https://www.screener.in/",
                javascriptMode: JavascriptMode.unrestricted,
                userAgent: _proxyUserAgent,
                onWebViewCreated: (controller) {
                  this.controller = controller;
                },
                zoomEnabled: false,
                navigationDelegate: (NavigationRequest request) {
                  if (request.url.startsWith("https://www.screener.in/")) {
                    return NavigationDecision.navigate;
                  } else if (request.url.contains("google")) {
                    return NavigationDecision.navigate;
                  } else {
                    _launchURL(request.url);
                    return NavigationDecision.prevent;
                  }
                },
              ),

```

</details>

<details>
  <summary>Logs</summary>

Flutter run --verbose
```
![image](https://user-images.githubusercontent.com/30836518/153265415-1fbc3b09-35d3-4b67-bd64-e8c4442cdafb.png)
```

Flutter analyze
```
![image](https://user-images.githubusercontent.com/30836518/153265221-1cff9295-d23e-4811-af93-df6c03cbd6b3.png)
```

flutter doctor -v
```
![image](https://user-images.githubusercontent.com/30836518/153265659-a4626e94-a98a-494c-aa39-2393a30adc55.png)
```

</details>
![image](https://user-images.githubusercontent.com/30836518/153263373-b32af5a6-a5ad-4c4b-82aa-71a44652e4ce.png)

https://user-images.githubusercontent.com/30836518/153264657-250ad7d2-5000-4bc8-849f-b4464e2aa4a0.mp4

**Comment by THELEMITED** [comment]
My bad, I forgot that xml and ESC files are not located in the same identity matrix)':

**Comment by KaviHarjani** [comment]
Hey @THELEMITED didn't get you, I'm new to flutter 
And I tried the inapp plugin as well but that didn't work either
So I guess I might be missing something out

Any idea on how to get it to work?

**Comment by danagbemava-nc** [comment]
Hi @KaviHarjani, this is due to the fact that the `webview_flutter` plugin doesn't support downloads at the moment. 

There's an issue tracking this in https://github.com/flutter/flutter/issues/39321. Kindly follow up there for more information. 

Closing from here as duplicate. 

Thank you

**Comment by KaviHarjani** [comment]
Hey thanks @danagbemava-nc
