### ISSUE TITLE
Migrate xster/flutter-plugin-share to flutter/plugins

### ISSUE THREAD

**Issue by xster** [flutter/flutter#9816]
Move https://github.com/xster/flutter-plugin-share and wrap with the new plugin mechanism

**Comment by xster** [comment]
seems like I can't just start using it yet. I assume I still need to follow some instructions on 
https://www.dartlang.org/tools/pub/publishing to make it 'published'

**Comment by eseidelGoogle** [comment]
This is done, correct?

**Comment by xster** [comment]
Ah, I just learned that the plugins' APIs have been updated. Will have to change its usages in this package since the old APIs aren't available anymore. 

Then pub publish it.
