### ISSUE TITLE
error: Undefined name 'toPosts'.

### ISSUE THREAD

**Issue by youyou-him** [flutter/flutter#98169]
I'm going to get the QuerySnapshot and change it to Post Model.

```
return FirebaseFirestore.instance
      .collection(COLLECTION_POSTS)
      .where(KEY_USERKEY, isEqualTo: userKey)
      .snapshots()
      .transform(toPosts);
```

I wrote it like this, and there's an error. In the error, it says that there is no to Posts, but even though I made it into a class, I can't get an imprint even if I try to make it's an error.

```
final toPosts =
  StreamTransformer<QuerySnapshot, List<PostModel>>.fromHandlers(
      handleData: (snapshot, sink) async {
        List<PostModel> posts = [];
        snapshot.docs.forEach((documentSnapshot) {
            posts.add(PostModel.fromSnapshot(documentSnapshot));
        });
```

What should I do?
<img width="452" alt="스크린샷 2022-02-10 오후 12 08 07" src="https://user-images.githubusercontent.com/83145102/153335023-c3bf357e-8970-410b-9d18-56801b29b0af.png">

**Comment by darshankawar** [comment]
This seems to be related to `cloud_firestore` plugin which is 3rd party. Please open this issue in dedicated repo:  https://github.com/FirebaseExtended/flutterfire/issues

**Comment by youyou-him** [comment]
Thank you so much!
