### ISSUE TITLE
Android Emulator: strange host keyboard behavior with InkWell and TextField

### ISSUE THREAD

**Issue by dowski** [flutter/flutter#98172]
## Steps to Reproduce

1. Execute the sample code on an Android emulator (I was using Pixel 3 API 30)
2. Use the mouse to tap and focus the TextField in the middle of the screen
3. Use your computer's keyboard; press any letter and try to use the spacebar

**Expected results:** 
Text entered normally, spacebar advances the cursor.

**Actual results:** 
When text is entered, the entire screen turns gray. The spacebar isn't functional.

Using the mouse on the emulator's on-screen keyboard seems to work fine.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'InkWell+TextField Bug',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        body: InkWell(
          onTap: () {},
          child: const Center(child: TextField()),
        ),
      )
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
PS C:\Users\chris\AndroidStudioProjects\inkwell_textfield> flutter doctor -v
[√] Flutter (Channel stable, 2.5.2, on Microsoft Windows [Version 10.0.19044.1503], locale en-US)
    • Flutter version 2.5.2 at C:\Users\chris\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (4 months ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\chris\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.10.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.10.31424.327
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.63.2)
    • VS Code at C:\Users\chris\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5556 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19044.1503]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 98.0.4758.82
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 98.0.1108.43
    ! Device emulator-5554 is offline.

• No issues found!

```

</details>

**Comment by simranss** [comment]
It is because InkWell is the parent widget. When the TextField is clicked InkWell is focused turning the whole screen to grey. Try it without InkWell and then update it here it again.
If it solves the issue don't forget close this issue.

**Comment by darshankawar** [comment]
@dowski 
Check above comment / solution and see if it helps.

**Comment by dowski** [comment]
Thanks for the response. I know it's due to InkWell being the parent, but the behavior still seems buggy.

What I was trying to do was to have a Container wrapped in InkWell so it had visible touch response. Tapping the container expands it and reveals some TextFields.

At the very least, it seems like it would be useful to document the InkWell/TextField interaction. I actually noticed that the behavior is similar in DartPad, but simply focusing the TextField turns the background gray.

https://dartpad.dev/?id=f5654f18a7500aa9a6e7e3d2310fca6d

**Comment by dowski** [comment]
Honestly, maybe just this bug being filed is documentation enough of the issue. It looks like all kinds of other work is going to happen on ink-related-things in #73163.

Feel free to close if it's not something that warrants fixing.

**Comment by darshankawar** [comment]
@dowski 
Thanks for the update. Looking at the code implementation and its outcome, point to note is that, when we are using a textfield, it expects a tap action in it which in itself is a tap event and if we are wrapping it with an `InkWell` and trying to trigger `onTap`, then the tap events are getting conflicted and hence the gray screen behavior you reported earlier.
Maybe you can try to use `AbsorbPointer` or `IgnorePointer` to restrict the splash ripple effects.
