### ISSUE TITLE
Add share images support

### ISSUE THREAD

**Issue by xster** [flutter/flutter#9817]
#9816 only supports sharing text/links. Embedded image support

**Comment by xster** [comment]
@chinmaygarde looking for some advice to make sure I'm heading in the right direction. 

I assume I'd want to expand the sharing Dart API (https://github.com/flutter/plugins/pull/21) to also take in a ui.Image (or some async wrapper of it) in the `share` method. Get its corresponding CanvasImage's bytes on the other side and then make a UIImage with it?

**Comment by abarth** [comment]
What is the actual use case you're trying to address?  ui.Image represents a (possibly deferred) GPU-resident image.  If you want to share images from storage (e.g., the user's photo gallery), there might not be a reason to make them GPU-resident.  You might want something more like a file descriptor or some other handle to bytes (potentially not memory-resident at all).

**Comment by xster** [comment]
Sorry, didn't mean to get you to answer on Sunday. 

Thanks, that's the part I wasn't sure. I was trying to see if there were a central point that users already use to show images like ImageProvider that I can reuse to get bytes across in an efficient way to share everything from NetworkImages and stuff from the gallery. 

It seemed like all the actual bytes were stored in ui.Image in common with ImageProviders. Might be easier in person. I'll come chat with you in the morning.

**Comment by abarth** [comment]
Sounds good.

**Comment by eseidelGoogle** [comment]
@lukef mentioned this morning that Posse was likely to use/build share-sheet integration which would want to share images.

**Comment by eseidelGoogle** [comment]
Posse is now tech'd up on Plugins so this is no longer blocking them.  They currently believe they can build this themselves.

**Comment by xster** [comment]
Sounds like Posse has a custom implementation that shares image files, though they'll still be interested in sharing image bytes.

**Comment by Purus** [comment]
+1 for this request.

The plugin should support sharing both local and network images along with text.

**Comment by Purus** [comment]
I am working on this feature and Flutter team has provided feedback during
review. I am learning few stuffs to have it done.

Thanks,
R.Purusothaman

**Comment by Sun3** [comment]
ps: @Purus I have noticed that most plugins do not work in iOS with Swift 4 projects enabled. 

This is the Error:
```
Launching lib/main.dart on iPhone X in debug mode...
Xcode build done.
Failed to build iOS app
Error output from Xcode build:
↳
** BUILD FAILED **
Xcode's output:
↳
=== BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code with “Use of deprecated Swift 3 @objc inference” logging enabled, and then disable inference by changing the "Swift 3 @objc Inference" build setting to "Default" for the "Runner" target.
=== BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
/Users/marco/Documents/Flutter Projects/plugins_playground/ios/Runner/GeneratedPluginRegistrant.m:6:9: fatal error: 'share/SharePlugin.h' file not found
#import <share/SharePlugin.h>
^~~~~~~~~~~~~~~~~~~~~
1 error generated.
Could not build the application for the simulator.
Error launching application on iPhone X.
Exited (sigterm)
```

Thanks.

**Comment by modulovalue** [comment]
any updates on this? @Purus

**Comment by m-zeki** [comment]
will this issue be address soon? @Purus - or is there any other way to share an image file with a flutter app?

**Comment by jorgevvr** [comment]
Please, add support for sharing image or files, is hard to call specific api to who haven't experience with IOS for example. Like me lol.

**Comment by DenisStark77** [comment]
+1 for the sharing images in Share plugin

**Comment by PieterAelse** [comment]
Should this help? https://stackoverflow.com/questions/44181343/how-do-i-share-an-image-on-ios-and-android-using-flutter 

The answer from Simon has a Swift and Kotlin version.
The answer from Albert Lardizabal has Objective-C and Java version.

**Comment by d-wolf** [comment]
We put that functionality into a plugin: https://pub.dartlang.org/packages/esys_flutter_share.

`final ByteData bytes = await rootBundle.load('assets/image.png');`
`await EsysFlutterShare.shareImage('myImageTest.png', bytes, 'my image title');`

**Comment by jorgevvr** [comment]
@d-wolf Thank you for your help, i will try it soon.

**Comment by erperejildo** [comment]
@d-wolf `Share.files` doesn't exist

**Comment by higorlapacw** [comment]
Any news?

**Comment by maheshkumar2150** [comment]
Any News?

**Comment by allanwolski** [comment]
See https://github.com/flutter/plugins/pull/970

**Comment by ditman** [comment]
`share: ^0.6.5` has been tagged and [published](https://pub.dev/packages/share/changelog#065)!

**Comment by ditman** [comment]
(I'm going to reopen, because I see that part of the requirement was to share from bytes; #970 is based on paths.)

**Comment by chinmaygarg** [comment]
Any plugin in which I can share an app deep link with the offline image preview (base64) ?

**Comment by Trulsmatias** [comment]
Any updates on the option to share from bytes?

**Comment by MiguelSOliveira** [comment]
Hey guys, I see that this was merged: https://github.com/flutter/plugins/pull/970

But I can't seem to find Share.shareFile method using `share: ^2.0.1` in master? Can anyone help me? Was this reverted?

**Comment by ditman** [comment]
Are you looking for `Share.shareFiles`?:

* https://github.com/flutter/plugins/blob/04cf809f3f10f48fa860f8ad2f343b93cc54b1c4/packages/share/lib/share.dart#L56-L68

**Comment by MiguelSOliveira** [comment]
Hey @ditman, please correct me if I'm wrong, but I don't think that one will work as I want to share a memory "File" type, and that one takes a path to a file instead.

The link I provided works because it takes a "File" type variable, which is exactly what I want.

<img width="419" alt="image" src="https://user-images.githubusercontent.com/8149533/116481153-8d98a600-a87a-11eb-9e76-2be5b3eba078.png">

**Comment by ditman** [comment]
@MiguelSOliveira take a look at what was finally merged, I think the code you want is:

```dart
Share.shareFiles(['${directory.path}/image.jpg']);
```

No need to instantiate the `File` to share it (?)

**Comment by MiguelSOliveira** [comment]
you're totally right @ditman, I have to store and write to the file anyways so it's physically in the temporary directory and I can just use that path. Thanks!

**Comment by GoelBiju** [comment]
> Any updates on the option to share from bytes?

It would be nice to have support for sharing from bytes.

**Comment by stuartmorgan** [comment]
Closing, as share is now deprecated in favor of [share_plus](https://pub.dev/packages/share_plus).
