### ISSUE TITLE
[flutter_tools] the tool does not provide an override the maven.google.com web host

### ISSUE THREAD

**Issue by lxepoo** [flutter/flutter#98170]
I use win11. I also prompt ：
HTTP host https://maven.google.com/ is not reachable. Reason: An error occurred while checking the HTTP host

but I can open this URL.

E:\flutter>flutter doctor
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.0, on Microsoft Windows [Version 10.0.22000.318], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.7)
[√] Android Studio (version 2021.1)
[√] IntelliJ IDEA Community Edition (version 2021.2)
[√] VS Code, 64-bit edition (version 1.63.2)
[√] Connected device (3 available)
[!] HTTP Host Availability
    X HTTP host https://maven.google.com/ is not reachable. Reason: An error occurred while checking the HTTP host:

**Comment by darshankawar** [comment]
@lxepoo 
You seem to be accessing from China. Can you try to access it using a different network or provider and see if it helps?
The error seems to indicate a network related behavior.

**Comment by zzjin** [comment]
same issue here. seems there is no way to set `maven.google.com` to using proxy or mirror sites.

**Comment by lxepoo** [comment]
![image](https://user-images.githubusercontent.com/2084640/153561477-deeb84fa-2da9-4ad7-bc8d-4d27856823cf.png)

**Comment by lxepoo** [comment]
I can open this URL

**Comment by darshankawar** [comment]
This doesn't seem to be specific to Windows, as, a similar issue was reported on macOS. https://github.com/flutter/flutter/issues/98239

Labeling it for further insights on this.

/cc @christopherfujino

**Comment by icerking** [comment]
how to reslove this problem?

**Comment by christopherfujino** [comment]
We can make this host overridable via an environment variable, the way we do for cloud storage and pub. Does anyone know if there exists a mirror of maven in China?

**Comment by nathanwang** [comment]
I tried (#98293) but still not work.

> Oh wait, it looks like we already do that: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/gradle/flutter.gradle#L162
> 
> I think we just need to skip this check if the user has `FLUTTER_STORAGE_BASE_URL` set.

**Comment by ouyangshixiong** [comment]
> I tried (#98293) but still not work.
> 
> > Oh wait, it looks like we already do that: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/gradle/flutter.gradle#L162
> > I think we just need to skip this check if the user has `FLUTTER_STORAGE_BASE_URL` set.

me too.
```
(base) MacBook-Pro:~ ouyang$ 
(base) MacBook-Pro:~ ouyang$ env | grep FLUTTER_STORAGE_BASE_URL
FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
(base) MacBook-Pro:~ ouyang$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.1, on macOS 12.1 21C52 darwin-arm, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3)
[✓] VS Code (version 1.64.0)
[✓] Connected device (1 available)
[!] HTTP Host Availability
    ✗ HTTP host https://maven.google.com/ is not reachable. Reason: An error occurred while checking the HTTP host: Operation timed
      out

! Doctor found issues in 1 category.
```

**Comment by icerking** [comment]
这个问题太奇葩了

**Comment by yurenzhen** [comment]
**I also encountered the same problem, but I solved it in this way:**

### 1. Why is this problem?
I guess the person who encountered this problem is probably in the Chinese network environment, and you run the "fluent doctor" command in "CMD. Exe" of windows. In this "CMD. Exe" environment, even if your operating system uses VPN, it cannot be applied to the "CMD. Exe" command environment by default, so your VPN is in vain in "CMD. Exe"

### 2. How to solve this problem (this scheme is only for students with VPN)?
reference resources here: **https://juejin.cn/post/6844904070788956174**

Execute the following commands in "CMD. Exe" and then specify "fluent doctor"

set ALL_ PROXY=socks5://127.0.0.1:1086
set http_ proxy= http://127.0.0.1:1087
set https_ proxy= http://127.0.0.1:1087

now: try "fluent doctor"

**Remember: this scheme requires you to have a VPN first. This scheme requires you to have a VPN first. This scheme requires you to have a VPN first**

**我也遇到了同样的问题, 但我是这样解决该问题的:**
### 1.为什么会出现这个问题?
我猜遇到这个问题的人很可能是在中国网络环境, 并且你是在 windows 的 "cmd.exe" 中运行 "flutter doctor" 命令, 在该"cmd.exe"环境中,即使你的操作系统使用了VPN, 默认也是无法应用到"cmd.exe"命令环境中的, 所以你的VPN在"cmd.exe"中形同虚设.
### 2.如何解决该问题(此方案仅针对有VPN的同学)?
参考 https://juejin.cn/post/6844904070788956174
在"cmd.exe"中执行以下命令后, 再去指定"flutter doctor"即可OK
set ALL_PROXY=socks5://127.0.0.1:1086
set http_proxy=http://127.0.0.1:1087
set https_proxy=http://127.0.0.1:1087
**切记: 此方案要求你得先有个VPN, 此方案要求你得先有个VPN, 此方案要求你得先有个VPN.**

**Comment by mdddj** [comment]
* 第一步
<img width="349" alt="image" src="https://user-images.githubusercontent.com/29020213/154399274-f5dedc81-2bfa-4035-b3d1-ffd69da15c45.png">

* 第二步
在`cmd`输入复制的内容按回车

* 第三步

终端输入

```bash
curl https://maven.google.com/
```
如果看到这个输出,配置成功
```bash
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="https://maven.google.com/web/index.html">here</A>.
</BODY></HTML>
```

再次`flutter doctor`
<img width="525" alt="image" src="https://user-images.githubusercontent.com/29020213/154399998-2c8cf811-b2a4-49f4-970e-f874a627af6c.png">

**Comment by 18601673727** [comment]
Need a way to configure the host of `HTTP Host Availability` from `flutter doctor`, in my case, we want to check `https://maven.aliyun.com/repository/google/` instead of `https://maven.google.com/` @darshankawar

**Comment by icerking** [comment]
为什么不能有个更好的解决办法，中国境内避免出现这个问题

**Comment by 18601673727** [comment]
How funny it doesn't make any sense to check the availability to maven.google.com from mainland china, despite you being behind a firewall or not, critical infrastructure like maven.google.com have almost zero downtime so what's the point of checking? How about check internet availability instead?

**Comment by anmeng777** [comment]
I want to say some dirty words but I have kids, I'm affraid. So sad

**Comment by christopherfujino** [comment]
> Need a way to configure the host of `HTTP Host Availability` from `flutter doctor`, in my case, we want to check `https://maven.aliyun.com/repository/google/` instead of `https://maven.google.com/` @darshankawar

On master today, this check will be overridden if you configure `FLUTTER_STORAGE_BASE_URL`, which is what the tool will use for these artifacts if present.

**Comment by Iamzz-cn** [comment]
我找到了比较好的方法解决这个问题(我只在Windows11的PowerShell中试验过),前提是你需要有个VPN之类的梯子
原理:使PowerShell可以通过代理进行网络.理论上在Linux和MacOS也可以使用.
第一种方法:
打开PowerShell先运行如下命令
```
$env:ALL_PROXY="socks5://127.0.0.1:10808"
$env:HTTP_PROXY="http://127.0.0.1:10809"
$env:HTTPS_PROXY="http://127.0.0.1:10809"
$env:NO_PROXY="localhost,::1,127.0.0.1"
```
只在本次Terminal中生效,关闭Terminal后就不行了,
第二种方法:
在`环境变量->系统环境变量`中添加如下几个变量,里面的代理地址按需更改.地址的协议一定要带上不然会有问题
```
ALL_PROXY="socks5://127.0.0.1:10808"
HTTP_PROXY="http://127.0.0.1:10809"
HTTPS_PROXY="http://127.0.0.1:10809"
NO_PROXY="localhost,::1,127.0.0.1"
```
这种方法会在每次的Terminal中生效,但同时也会影响其他程序读取环境变量
第三种方法:
在`$PSHOME`目录中新建文件`Profile.ps1`(需要管理员权限)
`Profile.ps1`文件的说明在下面这个地址
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7
内容如下
```
$env:ALL_PROXY="socks5://127.0.0.1:10808"
$env:HTTP_PROXY="http://127.0.0.1:10809"
$env:HTTPS_PROXY="http://127.0.0.1:10809"
$env:NO_PROXY="localhost,::1,127.0.0.1"
```
之后每次打开PowerShell都会使用代理

**Comment by gzhulee** [comment]
> Here is the solution works https://blog.csdn.net/ouhuanquan/article/details/123134340
> 
> 1. Open ${FLUTTER_HOME}\packages\flutter_tools\lib\src\http_host_validator.dart
> 2. Change `https://maven.google.com/` to `https://dl.google.com/dl/android/maven2/`
> 3. Close Terminal
> 4. Open ${FLUTTER_HOME}\bin and delete cache directory
> 5. Reopen Terminal and exec `flutter doctor`

very good!

**Comment by YshowMofeng** [comment]
> Here is the solution works https://blog.csdn.net/ouhuanquan/article/details/123134340
> 
> 1. Open ${FLUTTER_HOME}\packages\flutter_tools\lib\src\http_host_validator.dart
> 2. Change `https://maven.google.com/` to `https://dl.google.com/dl/android/maven2/`
> 3. Close Terminal
> 4. Open ${FLUTTER_HOME}\bin and delete cache directory
> 5. Reopen Terminal and exec `flutter doctor`

有效

**Comment by a120476536** [comment]
> 我找到了比较好的方法解决这个问题(我只在Windows11的PowerShell中试验过),前提是你需要有个VPN之类的梯子 原理:使PowerShell可以通过代理进行网络.理论上在Linux和MacOS也可以使用. 第一种方法: 打开PowerShell先运行如下命令
> 
> ```
> $env:ALL_PROXY="socks5://127.0.0.1:10808"
> $env:HTTP_PROXY="http://127.0.0.1:10809"
> $env:HTTPS_PROXY="http://127.0.0.1:10809"
> $env:NO_PROXY="localhost,::1,127.0.0.1"
> ```
> 
> 只在本次Terminal中生效,关闭Terminal后就不行了, 第二种方法: 在`环境变量->系统环境变量`中添加如下几个变量,里面的代理地址按需更改.地址的协议一定要带上不然会有问题
> 
> ```
> ALL_PROXY="socks5://127.0.0.1:10808"
> HTTP_PROXY="http://127.0.0.1:10809"
> HTTPS_PROXY="http://127.0.0.1:10809"
> NO_PROXY="localhost,::1,127.0.0.1"
> ```
> 
> 这种方法会在每次的Terminal中生效,但同时也会影响其他程序读取环境变量 第三种方法: 在`$PSHOME`目录中新建文件`Profile.ps1`(需要管理员权限) `Profile.ps1`文件的说明在下面这个地址 https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7 内容如下
> 
> ```
> $env:ALL_PROXY="socks5://127.0.0.1:10808"
> $env:HTTP_PROXY="http://127.0.0.1:10809"
> $env:HTTPS_PROXY="http://127.0.0.1:10809"
> $env:NO_PROXY="localhost,::1,127.0.0.1"
> ```
> 
> 之后每次打开PowerShell都会使用代理

靠谱。。

**Comment by zangwill** [comment]
> > Here is the solution works https://blog.csdn.net/ouhuanquan/article/details/123134340
> > 
> > 1. Open ${FLUTTER_HOME}\packages\flutter_tools\lib\src\http_host_validator.dart
> > 2. Change `https://maven.google.com/` to `https://dl.google.com/dl/android/maven2/`
> > 3. Close Terminal
> > 4. Open ${FLUTTER_HOME}\bin and delete cache directory
> > 5. Reopen Terminal and exec `flutter doctor`
> 
> 有效

4. Open ${FLUTTER_HOME}\bin\cache and delete flutter_tools.snapshot

4 中不用删除整个 cache ，只需要删除 cache 目录下的 flutter_tools.snapshot 文件就可以，删掉整个 chche 后需要重新下很多东西

**Comment by luo10m** [comment]
> > > Here is the solution works https://blog.csdn.net/ouhuanquan/article/details/123134340
> > > 
> > > 1. Open ${FLUTTER_HOME}\packages\flutter_tools\lib\src\http_host_validator.dart
> > > 2. Change `https://maven.google.com/` to `https://dl.google.com/dl/android/maven2/`
> > > 3. Close Terminal
> > > 4. Open ${FLUTTER_HOME}\bin and delete cache directory
> > > 5. Reopen Terminal and exec `flutter doctor`
> > 
> > 
> > 有效
> 
> 4. Open ${FLUTTER_HOME}\bin\cache and delete flutter_tools.snapshot
> 
> 4 中不用删除整个 cache ，只需要删除 cache 目录下的 flutter_tools.snapshot 文件就可以，删掉整个 chche 后需要重新下很多东西

解决了！顶呱呱！
