### ISSUE TITLE
[Web] Web app deployed to GitHub Pages gives 404 when navigating to a route

### ISSUE THREAD

**Issue by mqhamdam** [flutter/flutter#98189]
## Steps to Reproduce

<details>
<summary>Code sample</summary>

<h2>index.html</h2>

[index.html](https://github.com/mqhamdam/web-mqhamdam/blob/master/index.html)

<h2>Router.dart</h2>

```
class AppRouter {
  static Route<dynamic> generateRoutes(RouteSettings settings) {
    switch (settings.name) {
      case initialPage:
        return MaterialPageRoute(
          builder: (context) => const HomeScreen(),
          settings: settings,
        );
      case aboutMePage:
        return MaterialPageRoute(
            builder: (context) => const AboutMeScreen(), settings: settings);
      case blogPage:
        return MaterialPageRoute(
          builder: (context) => Title(
              color: titleColor, title: 'Blog', child: const BlogScreen()),
          settings: settings,
        );
      default:
        return MaterialPageRoute(
          builder: (context) => Title(
              color: titleColor,
              title: '404 - NotFound',
              child: const NotFound()),
          settings: settings,
        );
    }
  }
}
```

<h2>route_names</h2>

```
const String initialPage = '/';
const String aboutMePage = '/about-me';
const String blogPage = '/blog';
```

</details>

Note*
1. I Uploaded web files from the build folder.
2. If I type https://example.com/blog it shows 404 not found(GitHub sample page).  
3. as you can see I deleted ```<base href='/'>```. however, it didn't help.

**Comment by maheshmnj** [comment]
Hi @mqhamdam, Thanks for filing the issue. I believe this issue is the same as this https://github.com/flutter/flutter/issues/89763. You need to make some configurations to make this work. Please refer this comment for the same https://github.com/flutter/flutter/issues/89763#issuecomment-925040018

**Comment by mqhamdam** [comment]
@maheshmnj thanks for your attention. I see there are solutions for netlify/firebase-hosting/ and apache. Do you know how to make it work using GitHub pages or amazon s3?
