### ISSUE TITLE
Cocoon retries of failing engine builds set flutter/flutter as trigger repo, not flutter/engine

### ISSUE THREAD

**Issue by whesse** [flutter/flutter#98183]
When builder https://luci-milo.appspot.com/p/flutter/builders/staging/Mac%20mac_ios_engine
fails, the retry builds triggered by cocoon send a buildbucket input trigger repo of flutter/flutter instead of the original flutter/engine.  These builds then fail.

For example build  1908  triggered by the scheduler has an trigger property

    "$recipe_engine/scheduler": {
    "hostname": "luci-scheduler.appspot.com",
    "triggers": [
      {
        "gitiles": {
          "ref": "refs/heads/main",
          "repo": "https://chromium.googlesource.com/external/github.com/flutter/engine",
          "revision": "6d9f479c58de71c56d11ab055d534316674d0cec"
        },

and a buildset 	commit/gitiles/chromium.googlesource.com/external/github.com/flutter/engine/+/6d9f479c58de71c56d11ab055d534316674d0cec

but the retry, build  1910, has no trigger property in the input properties, and the buildset is
commit/gitiles/chromium.googlesource.com/external/github.com/flutter/flutter/+/6d9f479c58de71c56d11ab055d534316674d0cec

**Comment by godofredoc** [comment]
Fixed. Please give it a try and reopen if it still fails.

**Comment by whesse** [comment]
These retries are still failing.  They are not retries manually triggered by someone using the cocoon UI, but automatic retry of a failing build, two times before giving up.  I think the source of them is cocoon.  So now, the builder

https://luci-milo.appspot.com/p/flutter/builders/staging/Mac%20mac_ios_engine
has one failing build due to a failure in compilation, followed by two failing builds which are infra failures due to the retries triggered by the first failing build, with the repo trigger problem still there.

**Comment by keyonghan** [comment]
https://github.com/flutter/cocoon/pull/1602 to fix.
