### ISSUE TITLE
I found this issue when I am trying to build my App   

### ISSUE THREAD

**Issue by abdulrahmanahme** [flutter/flutter#98190]
FAILURE: Build failed with an exception.

* Where:
Build file '[E:\food\Delivery]() man app\android\app\build.gradle' line: 53

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not get unknown property 'trueandroid' for DefaultConfig_Decorated{name=main, dimension=null, minSdkVersion=DefaultApiVersion{mApiLevel=21, mCodename='null'}, targetSdkVersion=DefaultApiVersion{mApiLevel=30, mCodename='null'}, renderscriptTargetApi=null, renderscriptSupportModeEnabled=null, renderscriptSupportModeBlasEnabled=null, renderscriptNdkModeEnabled=null, versionCode=1, versionName=1.0.0, applicationId=com.u6amtech.restaurant_delivery_boy, testApplicationId=null, testInstrumentationRunner=null, testInstrumentationRunnerArguments={}, testHandleProfiling=null, testFunctionalTest=null, signingConfig=null, resConfig=null, mBuildConfigFields={}, mResValues={}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}, mWearAppUnbundled=null} of type com.android.build.gradle.internal.dsl.DefaultConfig.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at [https://help.gradle.org]()

BUILD FAILED in 59s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by danagbemava-nc** [comment]
Hi @abdulrahmanahme, please provide the following information. 

- `android/build.gradle`
- `android/app/build.gradle`
- pubspec.yaml & pubspec.lock
- Full logs of either `flutter run -v` or `flutter build apk -v` depending on which command you are experiencing this issue with. The verbose logs is likely to be huge so kindly put it into a .txt file and attach it here. 

Thank you

**Comment by abdulrahmanahme** [comment]
I solved this error but l found another error could you help me .

**Comment by danagbemava-nc** [comment]
Hi @abdulrahmanahme, Kindly share the full error log and any other files that may be important to investigate the issue. 

Thank you

**Comment by abdulrahmanahme** [comment]
Thanks to you l solved the issue
