### ISSUE TITLE
Flutter ios 120hz refresh rate

### ISSUE THREAD

**Issue by jalal-zy** [flutter/flutter#98196]
My app is heavy on ios 15 iPhone 13 Pro Max with 120hz and scrolling listView is very slow. How can I make scrolling smooth on 120hz?

**Comment by darshankawar** [comment]
@jalal-zy 
Can you provide `flutter doctor -v`, a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with actual vs expected behavior ?

Thanks.

**Comment by jalal-zy** [comment]
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.5.2 20G95 darwin-arm, locale en-US)
    • Flutter version 2.8.1 at /Users/jalal/Documents/flutterFiles/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (8 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/jalal/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (4 available)
    • iPhone 11 Pro (mobile)     • C4BDA8B1-DE1A-4738-B995-C64B7F0068FF • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • iPhone 12 Pro (mobile)     • 8B0ED8FB-2FEB-4A49-A323-CF571180550F • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • iPhone 13 Pro Max (mobile) • D96CB636-DD6E-4850-9A02-DDFA765980C3 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 98.0.4758.80

• No issues found!

**Comment by jalal-zy** [comment]
https://user-images.githubusercontent.com/94610794/153771839-a758cb7e-0944-442e-86b7-70e4dec160bd.mp4

This is my result

**Comment by jalal-zy** [comment]
https://user-images.githubusercontent.com/94610794/153771892-8fa46bb5-f9a4-4385-808e-2d4d706dd968.mp4

This is expected

**Comment by darshankawar** [comment]
@jalal-zy 
Please try the same use case on latest stable (2.10.1) and see if you still get same behavior or not.
If yes, please provide a minimal code sample that we can run that shows this issue.

**Comment by jalal-zy** [comment]
@darshankawar I Updated to flutter stable (2.10.1), and I still have the same issue,
the app is laggy after the beginning, then if you set it in the background without a kill and then back active again, will become very normal and very smooth.

**Comment by jalal-zy** [comment]
import 'package:flutter/material.dart';
import 'package:get/get_navigation/src/root/get_material_app.dart';
import 'package:get/get_navigation/src/routes/get_route.dart';
import 'package:qatar_sale_flutter/home_screen.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      debugShowCheckedModeBanner: false,
      // selected theme (light or dark or classic)
      theme: buildTheme,
      // localization_files
    //  locale: LocalizationService.locale,
     // fallbackLocale: LocalizationService.fallbackLocale,
    ///  translations: LocalizationService(),
      //
      initialRoute: '/',
      getPages: pages,
    );
  }

  static List<GetPage> pages = [
  GetPage(name: '/', page: () => HomeScreen())];

  get buildTheme => /// classic theme
   ThemeData(
    brightness: Brightness.dark,

    /// primary
    primaryColor: const Color(0xFF751E3F),

    /// secondary
    secondaryHeaderColor: const Color(0xFFFFCD5A), //Color(0xFFF5B114),

    /// background
    backgroundColor: const Color(0xFF25000C),
    textTheme: const TextTheme(
      /// text and icons
      bodyText1: TextStyle(
        color: Color(0xFFEDE2E6),
      ),

      /// subtext
      bodyText2: TextStyle(
        color: Color(0xFFBA8F9F),
      ),

      /// success
      subtitle1: TextStyle(
        color: Color(0xFF27AE60),
      ),

      /// orange
      subtitle2: TextStyle(
        color: Color(0xFFFA8D00),
      ),
    ),

    /// hint or placeholder
    hintColor: const Color(0xFF4A0A1E),

    /// disable
    disabledColor: const Color(0xFF5E1832),

    /// light blue
    cardColor: const Color(0xFF0091FF),

    /// error color
    errorColor: const Color(0xFFFF4D00),

    /// custom font
    //fontFamily: Constant.appLanguage.isArabic ? 'Tajawal' : 'Nunito',
  );

}

**Comment by jalal-zy** [comment]
import 'dart:convert';

import 'package:extended_image/extended_image.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:get/get.dart';

import 'models/product.dart';

class HomeScreen extends StatelessWidget {
  HomeScreenModel viewModel = HomeScreenModel();

  @override
  Widget build(BuildContext context) {
    return GetBuilder<HomeScreenModel>(
        init: viewModel,
        builder: (controller) {
          viewModel = controller;
          return Scaffold(
            backgroundColor: Theme.of(context).backgroundColor,
            body: _buildListProducts(context),
          );
        });
  }

  Widget _buildListProducts(BuildContext context) {
    return ListView.builder(
      physics: AlwaysScrollableScrollPhysics(),
      itemCount: viewModel.productsList.length,
      //viewModel.productsList.length,
      itemBuilder: (contx, index) {
        // render product or ad
        final product = viewModel.productsList[index];
        return Column(
          children: [
            Container(
              padding: EdgeInsets.only(top: 17, bottom: 10, left: 10, right: 10),
              child: Column(
                children: [

                  /// image
                  Row(
                    children: [
                      Expanded(
                        child: Container(
                          color: Colors.transparent,
                          child: ClipRRect(
                            borderRadius: BorderRadius.circular(4.0),
                            child: ExtendedImage.network(
                              product.coverImage ?? '',
                              fit: BoxFit.fill,
                              cache: true,
                              loadStateChanged: (state) {
                                switch(state.extendedImageLoadState){
                                  case LoadState.completed:
                                    return state.completedWidget;
                                  case LoadState.failed:
                                    return Container(height: 0,);
                                  case LoadState.loading:
                                    return Container(height: 0,);
                                }
                              },
                              handleLoadingProgress: false,
                            ),


                            // child: CachedNetworkImage(
                            //   height: SizeConfig.screenWidth * 0.71,
                            //   fit: BoxFit.contain,
                            //   fadeInDuration: Duration.zero,
                            //   fadeOutDuration: Duration.zero,
                            //   placeholderFadeInDuration: Duration.zero,
                            //   imageUrl: product.coverImage ?? '',
                            //   maxHeightDiskCache: (SizeConfig.screenWidth * 0.71).toInt(),
                            //   maxWidthDiskCache: (SizeConfig.screenWidth - 10).toInt(),
                            //   placeholder: (context, url) => PlaceholderWidget(),
                            //   errorWidget: (context, url, error) =>
                            //       PlaceholderWidget(),
                            // ),
                          ),
                        ),
                      ),
                    ],
                  ),
                  SizedBox(
                    height: 5,
                  ),

                  /// category uri

                  /// title
                  Row(
                    children: [
                      Expanded(
                        child: Text(
                          product.title ?? '-',
                          maxLines: 2,
                          overflow: TextOverflow.ellipsis,
                        ),
                      ),
                    ],
                  ),
                  SizedBox(
                    height: 10,
                  ),


                  /// main/final price
                  Row(
                    crossAxisAlignment: CrossAxisAlignment.end,
                    children: [
                      Text(
                        product.startingPrice.toString(),
                      ),
                      SizedBox(
                        width: 2,
                      ),
                      Padding(
                        padding: const EdgeInsets.only(bottom: 6.0),
                        child: Text(
                          'Q.R', //product.timeAgo ?? '-',,
                        ),
                      ),
                    ],
                  ),
                ],
              ),
            ),

            /// line after cell
            Container(height: 1,
              color: Theme.of(context).disabledColor,)
          ],
        );
      },
    );
  }
}

class HomeScreenModel extends GetxController {
  List<ProductModel> productsList = [];

  HomeScreenModel() {
    _buildJsonList();
  }

  void _buildJsonList() async {
    final String response =
        await rootBundle.loadString('assets/test_json.json');
    final data = await json.decode(response);
    List<ProductModel> list = List<ProductModel>.from(
        data['list'].map((model) => ProductModel.fromJson(model)));
    productsList = list;
    update();
  }
}

**Comment by darshankawar** [comment]
@jalal-zy 
From the code you provided, you seem to be using `getx` package which is third party. In order to narrow down to framework issue, please provide only a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without any 3rd party plugins that we can directly use and which replicates the behavior you are reporting.

**Comment by jalal-zy** [comment]
@darshankawar
 Hello... I am sorry for being late... 
I have updated the Flutter version to the last one '2.10.3'.
Then my app still had scrolling issues and when added the following code:
```
if #available(iOS 15.0, *) {
                  let displayLink = CADisplayLink(target: self, selector: #selector(step))
         // displayLink.preferredFramesPerSecond = 120
          displayLink.preferredFrameRateRange = CAFrameRateRange(minimum:60, maximum:  120)
          DispatchQueue.main.asyncAfter(deadline: .now() + 0.2) {
              displayLink.add(to: .current, forMode: .default)

                  }
              }
```
after adding that it changes and smooth but it has shiver in all the app
even I removed 'GetX' and just loaded ListView.build with Text Cell

**Comment by jalal-zy** [comment]
I just use:

```
void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: HomeScreen(), //MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}
```

```
class HomeScreen extends StatelessWidget{
  const HomeScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold( appBar: AppBar(),
      body: ListView.builder(
        itemCount: 300,
          itemBuilder: (contx, index){
            return Column(
              children: [
                Container(height: 100, color: Colors.grey,),
                Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: Text('data test test',
                    style: TextStyle(color: Colors.orange, fontSize: 30),),
                ),
              ],
            );
          }, ),);
  }
}
```

**Comment by darshankawar** [comment]
@jalal-zy 
Check if your use case / issue is same as this: https://github.com/flutter/flutter/issues/96381

**Comment by jalal-zy** [comment]
@darshankawar 
No... it's not, I have jittering on a scroll the first time I open the app, but after resume from the background,
will be smooth,
I have updated my iOS version to the latest '15.4' and XCode 13.3

**Comment by jalal-zy** [comment]
![WhatsApp Image 2022-03-17 at 1 02 20 PM](https://user-images.githubusercontent.com/94610794/158807638-77a6b393-0df2-45d8-b63c-50d789155832.jpeg)
It seems like '120 fps' but in mobile like '60 fps'

**Comment by darshankawar** [comment]
@jalal-zy 
I tried with your code sample on latest master using iPhone device (OS 15.3.1) but don't see jitters first time when app opens, it scrolls properly and in Flutter performance, I see 60 fps:

<img width="436" alt="Screenshot 2022-03-18 at 11 16 03 AM" src="https://user-images.githubusercontent.com/67046386/158944850-0fb86749-0de8-4b81-ae43-7c0bb012ac55.png">

`Channel master, 2.13.0-0.0.pre.141`
`Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52`

**Comment by jalal-zy** [comment]
@darshankawar 
What is your iPhone?
120 fps it's just in iPhone 13 pro and 13 pro max

**Comment by jalal-zy** [comment]
I also tried to add these:
in info.plist file:

```
<key>CADisableMinimumFrameDurationOnPhone</key>
<true/>
```

And in appDelegate.swift:

```
if #available(iOS 15.0, *) {
                         let displayLink = CADisplayLink(target: self, selector: #selector(step))
                // displayLink.preferredFramesPerSecond = 120
                 displayLink.preferredFrameRateRange = CAFrameRateRange(minimum:20, maximum: 120, preferred: 120)
                 DispatchQueue.main.asyncAfter(deadline: .now() + 0.2) {
                     displayLink.add(to: .current, forMode: .default)

                         }
                     }

@objc func step(displaylink: CADisplayLink) {
}
```

**Comment by darshankawar** [comment]
> I have jittering on a scroll the first time I open the app,

Can you provide a short video that shows the jitter behavior ?

**Comment by darshankawar** [comment]
Never mind, I believe you are hitting https://github.com/flutter/flutter/issues/90675
Closing this as a duplicate.
