### ISSUE TITLE
MultipartFile is only supported where dart:io is available

### ISSUE THREAD

**Issue by MarioKangaroo** [flutter/flutter#98208]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Install this 2 dart package: 
  image_picker: ^0.8.4+4 "this is to pick up image from the PC, android or iOS"
  http: ^0.13.4. "this is for the request"
3. My flutter setup is:
Flutter 2.10.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5f105a6ca7 (9 days ago) • 2022-02-01 14:15:42 -0800
Engine • revision 776efd2034
Tools • Dart 2.16.0 • DevTools 2.9.2

4. When you try to use the next http method to upload the image on WEB flutter:

      var request = http.MultipartRequest(
          'POST', Uri.parse("${_baseUrl}/upload"));
      request.files.add(await http.MultipartFile.fromPath('image', filepath));
     var res = await request.send();
 

Note: The same code was working to (WEB, Android and iOS) using the previous version of Flutter and Dart, but now after update the Framework only is working to Android and iOS not for WEB.

**Expected results:** 

Correct upload image to our servers

**Actual results:** 

<details>
<summary>Unsupported operation: MultipartFile is only supported where dart:io is available</summary>

```dart
```
import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final ImagePicker _picker = ImagePicker();
  XFile? _imageFile;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            // const Text(
            //   'You have pushed the button this many times:',
            // ),
            TextButton(
                onPressed: () {
                  pickImageGallery()
                }, child: Text("Pikc up image to upload")),
          ],
        ),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }

  ///Select image from gallery
  Future<void> pickImageGallery() async {
    try {
      final pickedFile = await _picker.pickImage(source: ImageSource.gallery);
      _imageFile = await pickedFile;
      await uploadImage(_imageFile?.path);
    } catch (e) {
      print("Image Picker error $e");
    }
  }

  ///Http request POST to upload image
  Future<void> uploadImage(
    filepath,
  ) async {
    ///Put all the necesarie headers
    Map<String, String> headers = {
      "": "",
    };
    var request =
        http.MultipartRequest('POST', Uri.parse("${_baseUrl}images"));
    request.headers.addAll(headers);
    request.files.add(await http.MultipartFile.fromPath('image', filepath));
    var res = await request.send();
    var responseData = await res.stream.toBytes();
    var responseString = String.fromCharCodes(responseData);
    var d = jsonDecode(responseString);
    print("Response ${d.toString()}");
  }
}

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.0, on macOS 11.6 20G165 darwin-x64, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Community Edition (version 2021.2.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!

**Comment by kouseralamin** [comment]
Web does not support dart:io. To use multipart you need dart:io. As dart:io will not work you can not upload file using multipart header. There are alternative methods to upload files. But you need to make sure that the server can accept files in other method. These are some working codes in web and I can not say why the second one works in web:

This one uses application/octet-stream
```
Future<bool> gcloudUpload(String attachmentUploadUrl, XFile xFile) async {
  var _bytes = await xFile.readAsBytes();
  try {
    return await http.put(
        Uri.parse(attachmentUploadUrl),
        headers: {'Content-Type': 'application/octet-stream'},
        body: _bytes
    ).then((value) {
      if(value.statusCode == 200) {
        return true;
      } else {
        return false;
      }
    });
  } catch(e) {
    return false;
  }
}
```

And this one uses application/x-www-form-urlencoded with firebase token in header:
```
Future<bool> postImageUpload(int postId, XFile xFile) async {
  try {
    return await FirebaseAuth.instance.currentUser!.getIdToken().then((token) async {
      var _request = http.MultipartRequest('PATCH', Uri.parse('\$baseUrl/post/upload-image/$postId/'));
      _request.headers.addAll({'FirebaseAuthorization': 'Token $token' ,'Content-Type': 'application/x-www-form-urlencoded'});
      _request.files.add(
          http.MultipartFile.fromBytes(
              'image',
              await xFile.readAsBytes().then((value) {
                return value.cast();
              }),
              filename: xFile.path.toString() + xFile.name
          )
      );
      return await _request.send().then((value) {
        if(value.statusCode == 200) {
          return true;
        } else {
          return false;
        }
      });
    });
  } catch(e) {
    return false;
  }
}
```

You can get XFile by this package https://pub.dev/packages/file_selector

**Comment by darshankawar** [comment]
@MarioKangaroo 
Per above explaination, multipart depends on `dart:io` which won't work on web, so you can use the above solution and see if it works for you.
Alternatively, see if [this](https://github.com/flutter/flutter/issues/45782#issuecomment-561308203) helps. 

Closing, as this is WAI currently.

**Comment by natebosch** [comment]
> To use multipart you need dart:io. As dart:io will not work you can not upload file using multipart header.

This should not be the case.

It is specifically `MutlipartFile.fromPath` that does not work in the browser, because the browser does not support reading arbitrary file paths.

If you use a browser supported method to choose the file, and have it available as bytes or as a `String` you can use [`MultipartFile.fromString`](https://pub.dev/documentation/http/latest/http/MultipartFile/MultipartFile.fromString.html) or [`MultipartFile.fromBytes`](https://pub.dev/documentation/http/latest/http/MultipartFile/MultipartFile.fromBytes.html).
