### ISSUE TITLE
CalendarDatePicker should allow change the first day of the week

### ISSUE THREAD

**Issue by petrov-nikolay** [flutter/flutter#98206]
missing setting for selecting first day of week.
And no, setting up localization for the app is not an acceptable solution when only this behavior in this control is the problem.

**Comment by devj3ns** [comment]
Hey @petrov-nikolay, here are some comments taken from https://github.com/flutter/flutter/issues/30051 which was closed:

> Material Design Date Picker depends on material localization, which takes care of the changing of the first week based on locale. (In Android native, there is a legacy Calendar option that has a parameter to set the custom first day of the week but the material design date picker doesn't depend on this). Overriding this manual will break the Calendar for other locales.

> If you don't need to take care of different locales, I would suggest using a third-party calendar that can provide this custom feature. Since third-party packages can implement custom features without material guidelines.

**Comment by darshankawar** [comment]
@petrov-nikolay 
Based on above comment and explaination, I am going ahead and closing this as not a feasible solution.
If you disagree, write in comments and I'll reopen it.

**Comment by petrov-nikolay** [comment]
don't use locale changing param, just add an integer param to set first day of week and make it override the locale value if the param != null, it is in only 2 places in code, will solve the problem without breaking dependencies
