### ISSUE TITLE
[Android] Kotlin support library dependency no longer required

### ISSUE THREAD

**Issue by davidmigloz** [flutter/flutter#98212]
At the moment, all Flutter Android Kotlin templates contain a dependency on the Kotlin support library. E.g.:
https://github.com/flutter/flutter/blob/0e2f51dfd04eca2935318389a75e8bc112809342/packages/flutter_tools/templates/app_shared/android-kotlin.tmpl/app/build.gradle.tmpl#L67-L69

Starting from Kotlin 1.4, the Kotlin Gradle plugin adds the dependency on the standard library automatically by default: ([ref](https://kotlinlang.org/docs/whatsnew14.html#dependency-on-the-standard-library-added-by-default))

> You no longer need to declare a dependency on the stdlib library in any Kotlin Gradle project, including a multiplatform one. The dependency is added by default.
> 
> The automatically added standard library will be the same version of the Kotlin Gradle plugin, since they have the same versioning.
> 
> For platform-specific source sets, the corresponding platform-specific variant of the library is used, while a common standard library is added to the rest. The Kotlin Gradle plugin will select the appropriate JVM standard library depending on the kotlinOptions.jvmTarget compiler option of your Gradle build script.

The current Kotlin version in the templates is 1.6.10:
https://github.com/flutter/flutter/blob/1bfb7400c8ce546fd19ffd93b458ded583d9ada5/packages/flutter_tools/lib/src/android/gradle_utils.dart#L32

So the explicit dependency to the Kotlin support library dependency is no longer required.

**Comment by andesappal** [comment]
Hi @davidmigloz I get crashes with or without the Kotlin references https://github.com/flutter/flutter/issues/98223#issuecomment-1040338050
