### ISSUE TITLE
Rerun on Engine dashboard results in infra error

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#98228]
There is a failing build on the new Engine dashboard at https://flutter-dashboard.appspot.com/#/build?repo=engine&branch=main for https://ci.chromium.org/p/flutter/builders/prod/Linux%20Fuchsia%20FEMU. When I click the re-run button, it results in an infra error: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Fuchsia%20FEMU/7593/overview.

Luckily, it looks like our script here still works: https://github.com/flutter/engine/blob/main/tools/luci/build.py. When I polled the Engine team last year when this came up, the desire was to continue to use the Milo dashboard, so hopefully the script we've been using for re-builds will continue to work.

/cc @godofredoc @CaseyHillers

**Comment by godofredoc** [comment]
Fixed. Please give it a try and reopen if it still fails.

**Comment by godofredoc** [comment]
You'll need to reload the dashboard for the changes to be picked up.
