### ISSUE TITLE
Linux Fuchsia FEMU failure closing Engine tree

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#98229]
On an unrelated commit here https://github.com/flutter/engine/commit/e031e07f6f16bd8d9776b19180349a1787592ed8, the Engine tree is red on what looks like a missing file in the recipes repo:

https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Fuchsia%20FEMU/7594/overview

Also, it looks like that step is miscategorized as a test step, when I think it might be an infra step.

P0 since, I don't see what to revert to get the tree back open.

**Comment by zanderso** [comment]
Yup. This file was not moved under `engine/` 

https://flutter.googlesource.com/recipes/+/refs/heads/main/recipes/femu_test.resources/

**Comment by zanderso** [comment]
I reverted that roll here https://flutter-review.googlesource.com/c/infra/+/26744. No idea if the revert is going to get clobbered, though.

**Comment by godofredoc** [comment]
Those configurations are autogenerated from the engine configs. I believe the problem was caused by the latency on replicating the configs. Checking.

**Comment by godofredoc** [comment]
Seems like after the new configs roll the build is working properly: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Fuchsia%20FEMU/7597/overview

**Comment by godofredoc** [comment]
Tree is open!

**Comment by zanderso** [comment]
The re-run on Linux Fuchsia FEMU used the old configs following the revert above. I just landed another engine change, so now we'll see how the new config does. I guess I'll also have to re-do my change here that got caught in the shuffle: https://flutter-review.googlesource.com/c/recipes/+/26661

**Comment by godofredoc** [comment]
Yeah sorry about that. We have been doing a lot cleanup work to remove the forked recipes and organize the recipes inside their repo folders.
