### ISSUE TITLE
Integration test in ios

### ISSUE THREAD

**Issue by bigslider** [flutter/flutter#98232]
i found that Disconnected IOS simulator when run the test command.

flutter doctor :

> [✓] Flutter (Channel stable, 2.10.0, on macOS 11.4 20F71 darwin-arm, locale en-CN)
> [✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
> [✓] Xcode - develop for iOS and macOS (Xcode 13.1)
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 2021.1)
> [✓] IntelliJ IDEA Ultimate Edition (version 2021.2.2)
> [✓] VS Code (version 1.64.1)
> [✓] Connected device (3 available)
> [✓] HTTP Host Availability

run my test code.

> flutter test integration_test/flow/login/login_index_test.dart --flavor dev --no-sound-null-safety

log:

> Please choose one (To quit, press "q/Q"): 2
> 00:10 +0: loading /Users/xxxxx/integration_test/flow/login/login_index_test.dart                                                         
> Xcode build done.                                           21.9s
> 12:00 +0 -1: loading /Users/xxxxx/integration_test/flow/login/login_index_test.dart [E]                                                  
>   TimeoutException after 0:12:00.000000: Test timed out after 12 minutes.
>   package:test_api/src/backend/invoker.dart 333:28  Invoker._handleError.<fn>
>   dart:async/zone.dart 1418:47                      _rootRun
>   dart:async/zone.dart 1328:19                      _CustomZone.run
>   package:test_api/src/backend/invoker.dart 331:10  Invoker._handleError
>   package:test_api/src/backend/invoker.dart 287:9   Invoker.heartbeat.<fn>.<fn>
>   dart:async/zone.dart 1426:13                      _rootRun
>   dart:async/zone.dart 1328:19                      _CustomZone.run
>   package:test_api/src/backend/invoker.dart 286:38  Invoker.heartbeat.<fn>
>   dart:async-patch/timer_patch.dart 18:15           Timer._createTimer.<fn>
>   dart:isolate-patch/timer_impl.dart 395:19         _Timer._runTimers
>   dart:isolate-patch/timer_impl.dart 426:5          _Timer._handleMessage
>   dart:isolate-patch/isolate_patch.dart 192:12      _RawReceivePortImpl._handleMessage
> 12:00 +0 -1: Some tests failed.

**Comment by bigslider** [comment]
note: it works well on android simulator

**Comment by darshankawar** [comment]
@bigslider 
Can you provide the entire console log that shows the disconnect entry ?
Also can you confirm if you have properly set up integration_test for iOS per [this](https://github.com/flutter/flutter/tree/master/packages/integration_test#ios-device-testing) link ?
