### ISSUE TITLE
Black Screen When Flutter Open Translucent Activity

### ISSUE THREAD

**Issue by JsouLiang** [flutter/flutter#98230]
Hey, I found an issue, when Flutter app open a translucent activity after that entry background and then  back to the foreground, the Flutter screen will have black screen.

Here is the [demo link](https://github.com/dotcink/flutter-black-screen-below-translucent-activity)

https://user-images.githubusercontent.com/10297030/153533003-759547fe-79fd-43e5-8ad0-2181192ab1cd.mp4

**Comment by ColdPaleLight** [comment]
Dupe https://github.com/flutter/flutter/issues/89957

**Comment by danagbemava-nc** [comment]
Dedup'ing with https://github.com/flutter/flutter/issues/89957. 

Kindly follow up in https://github.com/flutter/flutter/issues/89957 for more information. 

Thank you
