### ISSUE TITLE
Allow SearchDelegate to alter TextField properties: `autocorrect` and `enableSuggestions`

### ISSUE THREAD

**Issue by BramDriesen** [flutter/flutter#98241]
## Use case

I have a screen with a custom search delegate. My search goes through names of local soccer teams (some with funky names). However during testing I noticed that the autocorrect sometimes would kick in and replace an **exact** match with a name with a real word. This was to me quite frustrating so I looked into the customisation options for the SearchDelegate class. I noticed a few of the TextField options could be set through the constructor, but none of the autocorrect related options.

## Proposal

Allow the following:

- `autocorrect`
- `enableSuggestions`

To override via the constructor similar to how you can override the `searchFieldLabel` text.

**Comment by fvisticot** [comment]
I have the same issue with the autocomplete feature...The text in the search bar becomes a "black rectangle"(cf. screenshot)  and User experience is degraded
Any workaround 
![IMG_F1AD7787FB4A-1](https://user-images.githubusercontent.com/153679/172045008-eebb3abc-fd95-47f4-8a28-28358e74e94f.jpeg)
?

**Comment by fvisticot** [comment]
> I have the same issue with the autocomplete feature...The text in the search bar becomes a "black rectangle"(cf. screenshot) and User experience is degraded Any workaround ![IMG_F1AD7787FB4A-1](https://user-images.githubusercontent.com/153679/172045008-eebb3abc-fd95-47f4-8a28-28358e74e94f.jpeg) ?

I found the issue with Theme customization 

```
textSelectionTheme: TextSelectionThemeData(
            cursorColor: Colors.black,
            selectionColor: Palette.ticatagBlueColor),
```

**Comment by AguinaldoAranda** [comment]
Due to this issue: https://github.com/flutter/flutter/issues/138464

I needed to set autocorrect = false and I can't..., I'll need to use another approach to search records...

**Comment by justinmc** [comment]
Looks like this has been fixed in https://github.com/flutter/flutter/pull/154932.

If there's any part of this that should still stay around, let me know and I'll reopen!
