### ISSUE TITLE
[webview_flutter] IOS Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service

### ISSUE THREAD

**Issue by deepak9166** [flutter/flutter#98247]
### Webview_flutter issue for ios

I update flutter sdk version 2.10 after facing issue in flutter webview [https://pub.dev/packages/webview_flutter](url), that version is **webview_flutter 3.0.0** 
Android app working fine, only ios is not working.

**flutter doctor -v**
```
✓] Flutter (Channel stable, 2.10.0, on macOS 12.0.1 21A559 darwin-x64, locale en-GB)
    • Flutter version 2.10.0 at /Users/himanshu/Documents/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (10 days ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Volumes/Data/android-sdk
    • Platform android-31, build-tools 30.0.2
    • Java binary at: /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
```
![Screenshot 2022-02-11 at 4 26 02 PM](https://user-images.githubusercontent.com/64632494/153581559-943ddef1-e0d4-4da3-aba5-9d2eff988a5c.png)

**Comment by maheshmnj** [comment]
Hi @deepak9166, Thanks for filing the issue. From your issue description it is still unclear to me, what exactly the issue is, Could you please add more info to the issue description? Also Please include the complete error log in the form of **Text**, along with the steps to reproduce the issue.

Thanks

**Comment by deepak9166** [comment]
Hi @maheshmnj,
Actually I'm using engati url ([](https://app.engati.com)), other url working perfect in ios, but engati url not working in ios.

after loading more time after i get this response: 
```
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
[ProcessSuspension] 0x138823f50 - TimedActivity::activityTimedOut:
```

**Comment by deepak9166** [comment]
> Hi @deepak9166, Thanks for filing the issue. From your issue description it is still unclear to me, what exactly the issue is, Could you please add more info to the issue description? Also Please include the complete error log in the form of **Text**, along with the steps to reproduce the issue.
> 
> Thanks

Hi @maheshmnj , i notice that actully issue with only iOS X only, other ios is working perfact.

**Comment by maheshmnj** [comment]
> Actually I'm using engati url , other url working perfect in ios, but engati url not working in ios.

@deepak9166 thanks for the info, I am quite not sure what that means. 

Please share a minimum and complete reproducible sample code to investigate further.

**Comment by deepak9166** [comment]
I just uninstall the old build from the app and install it again, it's working.
