### ISSUE TITLE
webview_flutter is loading web page as white screen

### ISSUE THREAD

**Issue by qq627314025** [flutter/flutter#98245]
https://tyhykc.com/admin/previewHelperDoc?id=35

```
log   I[/PressGestureDetector]()(19094): HiTouch restricted: Sub windows restricted.
D[/mali_winsys]()(19094): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000
D[/OpenGLRenderer]()(19094):   HWUI Binary is  enabled
W[/libEGL]()  (19094): load: so=libEGL_vr.so
W[/libEGL]()  (19094): dlopen failed: library "libEGL_vr.so" not found
W[/libEGL]()  (19094): load: so=libEGL_vr.so
W[/libEGL]()  (19094): dlopen failed: library "libEGL_vr.so" not found
D[/TelephonyManager]()(19094): getAllCellInfo calling app is com.hykc.cityfreight
W[/libEGL]()  (19094): load: so=libEGL_vr.so
W[/libEGL]()  (19094): dlopen failed: library "libEGL_vr.so" not found
W[/libEGL]()  (19094): load: so=libEGL_vr.so
W[/libEGL]()  (19094): dlopen failed: library "libEGL_vr.so" not found
W[/libEGL]()  (19094): load: so=libEGL_vr.so
W[/libEGL]()  (19094): dlopen failed: library "libEGL_vr.so" not found
I[/chromium]()(19094): [INFO:CONSOLE(5)] "Uncaught TypeError: Object.fromEntries is not a function", source: [https://cdn.ckeditor.com/ckeditor5/29.1.0/decoupled-document/ckeditor.js]() (5)
I[/chromium]()(19094): [INFO:CONSOLE(123)] "Uncaught ReferenceError: DecoupledEditor is not defined", source: [https://tyhykc.com/admin/previewHelperDoc?id=35]() (123)
D[/HwCust]()  (19094): Create obj success use class android.app.HwCustHwWallpaperManagerImpl
D[/HwRTBlurUtils]()(19094): check blur style for HwPhoneWindow, themeResId : 0x0103023e, context : android.app.Presentation$3@7391857, Nhwext : 0, get Blur : disable with , null
D[/OpenGLRenderer]()(19094):   HWUI Binary is  enabled
I[/PressGestureDetector]()(19094): onAttached begin
I[/PressGestureDetector]()(19094): onAttached end
I[/PressGestureDetector]()(19094): HiTouch restricted: Sub windows restricted.
D[/mali_winsys]()(19094): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000
D[/OpenGLRenderer]()(19094):   HWUI Binary is  enabled
W[/libEGL]()  (19094): load: so=libEGL_vr.so
W[/libEGL]()  (19094): dlopen failed: library "libEGL_vr.so" not found
```
```
hanqiang@MacBook-Pro-4  ~  flutter doctor -v
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale
    zh-Hans-US)
    • Flutter version 2.8.1 at /Users/hanqiang/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (8 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version
    32.0.0-rc1)
    • Android SDK at /Users/hanqiang/Library/Android/sdk
    • Platform android-31, build-tools 32.0.0-rc1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message
      below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle
      (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:318:42)
      #2      InputStream.readString
      (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read
      (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer
      (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes
      (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml
      (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion
      (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage
      (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate
      (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure>
      (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure>
      (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1428:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1863:10)
      #15     runZonedGuarded (dart:async/zone.dart:1851:12)
      #16     runZoned (dart:async/zone.dart:1782:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks
      (package:flutter_tools/src/doctor.dart:197:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:301:47)
      #20     DoctorCommand.runCommand
      (package:flutter_tools/src/commands/doctor.dart:53:47)
      #21     FlutterCommand.verifyThenRunCommand
      (package:flutter_tools/src/runner/flutter_command.dart:1290:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure>
      (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure>
      (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure>
      (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure>
      (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand
      (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure>
      (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure>
      (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.63.2)
    • VS Code at /Users/hanqiang/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (3 available)
    • HUAWEI NXT AL10 (mobile) • CJL7N15C15007365 • android-arm64  • Android
      8.0.0 (API 26)
    • macOS (desktop)          • macos            • darwin-x64     • macOS 12.1
      21C52 darwin-x64
    • Chrome (web)             • chrome           • web-javascript • Google
      Chrome 95.0.4638.69
```

**Comment by maheshmnj** [comment]
Hi @qq627314025, Thanks for filing the issue. What version of the webview plugin are you using? Is the blank screen when opening a specific webpage or any webpage. if the latter could you please verify if it works on other device/emulator?
Additionally, you may try upgrading to `stable 2.10.1`.

Thanks

**Comment by qq627314025** [comment]
First of all, thank you for your answer
I upgraded the latest version of fluent. The problem remains
I use other Android phones for testing and can load normally. The Android version is 10
• Flutter version 2.10.1 at /Users/hanqiang/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (4 days ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

• Android SDK at /Users/hanqiang/Library/Android/sdk
    • Platform android-31, build-tools 32.0.0-rc1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] VS Code (version 1.64.2)
    • VS Code at /Users/hanqiang/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (4 available)
    • HUAWEI NXT AL10 (mobile) • CJL7N15C15007365

[https://tyhykc.com/admin/previewHelperDoc?id=40]()

**Comment by maheshmnj** [comment]
@qq627314025, could you please clarify?
> Is the blank screen when opening a specific webpage or any webpage  

Please share the complete output of `flutter run -v` in a text file.

**Comment by qq627314025** [comment]
[+12189 ms] I/flutter (16601): https://tyhykc.com/admin/previewHelperDoc?id=40
[  +94 ms] I/WebViewFactory(16601): Loading com.google.android.webview version 70.0.3538.110 (code 353811050)
[   +2 ms] D/HwFLClassLoader(16601): USE_FEATURE_LIST had not init! 
[  +52 ms] I/zygote64(16601): Rejecting re-init on previously-failed class java.lang.Class<hs>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/webkit/TracingController;
[        ] I/zygote64(16601):   at java.lang.Class java.lang.Class.classForName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:-2)
[        ] I/zygote64(16601):   at java.lang.Class java.lang.Class.forName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:453)
[        ] I/zygote64(16601):   at java.lang.Class android.webkit.WebViewFactory.getWebViewProviderClass(java.lang.ClassLoader) (WebViewFactory.java:151)
[        ] I/zygote64(16601):   at java.lang.Class android.webkit.WebViewFactory.getProviderClass() (WebViewFactory.java:418)
[        ] I/zygote64(16601):   at android.webkit.WebViewFactoryProvider android.webkit.WebViewFactory.getProvider() (WebViewFactory.java:212)
[        ] I/zygote64(16601):   at android.webkit.WebViewFactoryProvider android.webkit.WebView.getFactory() (WebView.java:2467)
[        ] I/zygote64(16601):   at void android.webkit.WebView.ensureProviderCreated() (WebView.java:2462)
[        ] I/zygote64(16601):   at void android.webkit.WebView.setOverScrollMode(int) (WebView.java:2527)
[        ] I/zygote64(16601):   at void android.view.View.<init>(android.content.Context) (View.java:4552)
[        ] I/zygote64(16601):   at void android.view.View.<init>(android.content.Context, android.util.AttributeSet, int, int) (View.java:4684)
[        ] I/zygote64(16601):   at void android.view.ViewGroup.<init>(android.content.Context, android.util.AttributeSet, int, int) (ViewGroup.java:597)
[        ] I/zygote64(16601):   at void android.widget.AbsoluteLayout.<init>(android.content.Context, android.util.AttributeSet, int, int) (AbsoluteLayout.java:55)
[        ] I/zygote64(16601):   at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int, java.util.Map, boolean) (WebView.java:636)
[        ] I/zygote64(16601):   at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int) (WebView.java:581)
[        ] I/zygote64(16601):   at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int) (WebView.java:564)
[        ] I/zygote64(16601):   at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet) (WebView.java:551)
[        ] I/zygote64(16601):   at void android.webkit.WebView.<init>(android.content.Context) (WebView.java:541)
[        ] I/zygote64(16601):   at void io.flutter.plugins.webviewflutter.InputAwareWebView.<init>(android.content.Context, android.view.View) (InputAwareWebView.java:35)
[        ] I/zygote64(16601):   at void io.flutter.plugins.webviewflutter.WebViewHostApiImpl$InputAwareWebViewPlatformView.<init>(android.content.Context, android.view.View)
(WebViewHostApiImpl.java:212)
[        ] I/zygote64(16601):   at io.flutter.plugins.webviewflutter.WebViewHostApiImpl$InputAwareWebViewPlatformView
io.flutter.plugins.webviewflutter.WebViewHostApiImpl$WebViewProxy.createInputAwareWebView(android.content.Context, android.view.View) (WebViewHostApiImpl.java:64)
[        ] I/zygote64(16601):   at void io.flutter.plugins.webviewflutter.WebViewHostApiImpl.create(java.lang.Long, java.lang.Boolean) (WebViewHostApiImpl.java:340)
[        ] I/zygote64(16601):   at void
io.flutter.plugins.webviewflutter.GeneratedAndroidWebView$WebViewHostApi$-CC.lambda$setup$0(io.flutter.plugins.webviewflutter.GeneratedAndroidWebView$WebViewHostApi, java.lang.Object,
io.flutter.plugin.common.BasicMessageChannel$Reply) (GeneratedAndroidWebView.java:344)
[        ] I/zygote64(16601):   at void io.flutter.plugins.webviewflutter.-$$Lambda$GeneratedAndroidWebView$WebViewHostApi$zbaY0gjF2NpjRBZHNtAakdDOTww.onMessage(java.lang.Object,
io.flutter.plugin.common.BasicMessageChannel$Reply) (lambda:-1)
[        ] I/zygote64(16601):   at void io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(java.nio.ByteBuffer, io.flutter.plugin.common.BinaryMessenger$BinaryReply)
(BasicMessageChannel.java:217)
[        ] I/zygote64(16601):   at void io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(io.flutter.embedding.engine.dart.DartMessenger$HandlerInfo, java.nio.ByteBuffer, int)
(DartMessenger.java:296)
[        ] I/zygote64(16601):   at void io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(java.lang.String,
io.flutter.embedding.engine.dart.DartMessenger$HandlerInfo, java.nio.ByteBuffer, int, long) (DartMessenger.java:320)
[        ] I/zygote64(16601):   at void io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run() (lambda:-1)
[        ] I/zygote64(16601):   at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:808)
[        ] I/zygote64(16601):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:101)
[        ] I/zygote64(16601):   at void android.os.Looper.loop() (Looper.java:166)
[        ] I/zygote64(16601):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:7529)
[        ] I/zygote64(16601):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
[        ] I/zygote64(16601):   at void com.android.internal.os.Zygote$MethodAndArgsCaller.run() (Zygote.java:245)
[        ] I/zygote64(16601):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:921)
[        ] I/zygote64(16601): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.webkit.TracingController" on path: DexPathList[[zip file
"/data/hw_init/preas/app/WebViewGoogle/WebViewGoogle.apk"],nativeLibraryDirectories=[/data/hw_init/preas/app/WebViewGoogle/lib/arm64,
/data/hw_init/preas/app/WebViewGoogle/WebViewGoogle.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /product/lib64, /preas/lib64, /system/lib64, /vendor/lib64, /product/lib64, /preas/lib64]]
[        ] I/zygote64(16601):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:93)
[        ] I/zygote64(16601):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
[        ] I/zygote64(16601):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
[        ] I/zygote64(16601):   at java.lang.Class java.lang.Class.classForName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:-2)
[        ] I/zygote64(16601):   at java.lang.Class java.lang.Class.forName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:453)
[        ] I/zygote64(16601):   at java.lang.Class android.webkit.WebViewFactory.getWebViewProviderClass(java.lang.ClassLoader) (WebViewFactory.java:151)
[        ] I/zygote64(16601):   at java.lang.Class android.webkit.WebViewFactory.getProviderClass() (WebViewFactory.java:418)
[        ] I/zygote64(16601):   at android.webkit.WebViewFactoryProvider android.webkit.WebViewFactory.getProvider() (WebViewFactory.java:212)
[        ] I/zygote64(16601):   at android.webkit.WebViewFactoryProvider android.webkit.WebView.getFactory() (WebView.java:2467)
[        ] I/zygote64(16601):   at void android.webkit.WebView.ensureProviderCreated() (WebView.java:2462)
[        ] I/zygote64(16601):   at void android.webkit.WebView.setOverScrollMode(int) (WebView.java:2527)
[        ] I/zygote64(16601):   at void android.view.View.<init>(android.content.Context) (View.java:4552)
[        ] I/zygote64(16601):   at void android.view.View.<init>(android.content.Context, android.util.AttributeSet, int, int) (View.java:4684)
[        ] I/zygote64(16601):   at void android.view.ViewGroup.<init>(android.content.Context, android.util.AttributeSet, int, int) (ViewGroup.java:597)
[        ] I/zygote64(16601):   at void android.widget.AbsoluteLayout.<init>(android.content.Context, android.util.AttributeSet, int, int) (AbsoluteLayout.java:55)
[        ] I/zygote64(16601):   at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int, java.util.Map, boolean) (WebView.java:636)
[        ] I/zygote64(16601):   at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int) (WebView.java:581)
[        ] I/zygote64(16601):   at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int) (WebView.java:564)
[        ] I/zygote64(16601):   at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet) (WebView.java:551)
[        ] I/zygote64(16601):   at void android.webkit.WebView.<init>(android.content.Context) (WebView.java:541)
[        ] I/zygote64(16601):   at void io.flutter.plugins.webviewflutter.InputAwareWebView.<init>(android.content.Context, android.view.View) (InputAwareWebView.java:35)
[        ] I/zygote64(16601):   at void io.flutter.plugins.webviewflutter.WebViewHostApiImpl$InputAwareWebViewPlatformView.<init>(android.content.Context, android.view.View)
(WebViewHostApiImpl.java:212)
[        ] I/zygote64(16601):   at io.flutter.plugins.webviewflutter.WebViewHostApiImpl$InputAwareWebViewPlatformView
io.flutter.plugins.webviewflutter.WebViewHostApiImpl$WebViewProxy.createInputAwareWebView(android.content.Context, android.view.View) (WebViewHostApiImpl.java:64)
[        ] I/zygote64(16601):   at void io.flutter.plugins.webviewflutter.WebViewHostApiImpl.create(java.lang.Long, java.lang.Boolean) (WebViewHostApiImpl.java:340)
[        ] I/zygote64(16601):   at void
io.flutter.plugins.webviewflutter.GeneratedAndroidWebView$WebViewHostApi$-CC.lambda$setup$0(io.flutter.plugins.webviewflutter.GeneratedAndroidWebView$WebViewHostApi, java.lang.Object,
io.flutter.plugin.common.BasicMessageChannel$Reply) (GeneratedAndroidWebView.java:344)
[        ] I/zygote64(16601):   at void io.flutter.plugins.webviewflutter.-$$Lambda$GeneratedAndroidWebView$WebViewHostApi$zbaY0gjF2NpjRBZHNtAakdDOTww.onMessage(java.lang.Object,
io.flutter.plugin.common.BasicMessageChannel$Reply) (lambda:-1)
[        ] I/zygote64(16601):   at void io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(java.nio.ByteBuffer, io.flutter.plugin.common.BinaryMessenger$BinaryReply)
(BasicMessageChannel.java:217)
[        ] I/zygote64(16601):   at void io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(io.flutter.embedding.engine.dart.DartMessenger$HandlerInfo, java.nio.ByteBuffer, int)
(DartMessenger.java:296)
[        ] I/zygote64(16601):   at void io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(java.lang.String,
io.flutter.embedding.engine.dart.DartMessenger$HandlerInfo, java.nio.ByteBuffer, int, long) (DartMessenger.java:320)
[        ] I/zygote64(16601):   at void io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run() (lambda:-1)
[        ] I/zygote64(16601):   at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:808)
[        ] I/zygote64(16601):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:101)
[        ] I/zygote64(16601):   at void android.os.Looper.loop() (Looper.java:166)
[        ] I/zygote64(16601):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:7529)
[        ] I/zygote64(16601):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
[        ] I/zygote64(16601):   at void com.android.internal.os.Zygote$MethodAndArgsCaller.run() (Zygote.java:245)
[        ] I/zygote64(16601):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:921)
[        ] I/zygote64(16601): 
[        ] I/cr_LibraryLoader(16601): Time to load native libraries: 3 ms (timestamps 5197-5200)
[  +20 ms] I/chromium(16601): [INFO:library_loader_hooks.cc(36)] Chromium logging enabled: level = 0, default verbosity = 0
[        ] I/cr_LibraryLoader(16601): Expected native library version number "70.0.3538.110", actual native library version number "70.0.3538.110"
[   +7 ms] W/cr_ChildProcLH(16601): Create a new ChildConnectionAllocator with package name = com.google.android.webview, sandboxed = true
[   +6 ms] I/cr_BrowserStartup(16601): Initializing chromium process, singleProcess=false
[  +20 ms] E/GmsClient(16601): unable to connect to service: com.google.android.gms.safetynet.service.START on com.google.android.gms
[  +47 ms] E/GmsClient(16601): unable to connect to service: com.google.android.gms.usagereporting.service.START on com.google.android.gms
[  +63 ms] W/cr_media(16601): Requires BLUETOOTH permission
[        ] E/cr_PlatformSer-Internal(16601): Unable to determine Safe Browsing user opt-in preference
[   +4 ms] E/BufferQueueProducer(16601): [] Can not get hwsched service
[  +13 ms] W/libEGL  (16601): load: so=libEGL_vr.so
[        ] W/libEGL  (16601): dlopen failed: library "libEGL_vr.so" not found
[        ] W/libEGL  (16601): load: so=libEGL_vr.so
[        ] W/libEGL  (16601): dlopen failed: library "libEGL_vr.so" not found
[        ] D/HwCust  (16601): Create obj success use class android.app.HwCustHwWallpaperManagerImpl
[  +32 ms] W/VideoCapabilities(16601): Unrecognized profile/level 1/32 for video/mp4v-es
[        ] I/VideoCapabilities(16601): Unsupported profile 16384 for video/mp4v-es
[        ] I/VideoCapabilities(16601): Unsupported profile 16384 for video/mp4v-es
[        ] W/VideoCapabilities(16601): Unsupported mime video/x-pn-realvideo
[        ] W/VideoCapabilities(16601): Unsupported mime video/mpeg
[   +1 ms] W/VideoCapabilities(16601): Unrecognized profile/level 0/0 for video/mpeg2
[   +3 ms] W/VideoCapabilities(16601): Unrecognized profile/level 0/2 for video/mpeg2
[        ] W/VideoCapabilities(16601): Unrecognized profile/level 0/3 for video/mpeg2
[        ] W/VideoCapabilities(16601): Unrecognized profile/level 32768/2 for video/mp4v-es
[        ] W/VideoCapabilities(16601): Unsupported mime video/vc1
[  +17 ms] D/HwRTBlurUtils(16601): check blur style for HwPhoneWindow, themeResId : 0x0103023e, context : android.app.Presentation$3@970b7a0, Nhwext : 0, get Blur : disable with , null
[        ] D/HwRTBlurUtils(16601): check blur style for HwPhoneWindow, themeResId : 0x0103023e, context : android.app.Presentation$3@970b7a0, Nhwext : 0, get Blur : disable with , null
[        ] D/OpenGLRenderer(16601):   HWUI Binary is  enabled
[        ] I/VideoCapabilities(16601): Unsupported profile 4 for video/mp4v-es
[   +2 ms] W/cr_MediaCodecUtil(16601): HW encoder for video/avc is not available on this device.
[        ] D/OpenGLRenderer(16601):   HWUI Binary is  enabled
[   +1 ms] E/GmsClient(16601): unable to connect to service: com.google.android.gms.safetynet.service.START on com.google.android.gms
[        ] I/PressGestureDetector(16601): onAttached begin
[        ] I/PressGestureDetector(16601): onAttached end
[   +1 ms] I/PressGestureDetector(16601): HiTouch restricted: Sub windows restricted.
[  +21 ms] I/zygote64(16601): Do full code cache collection, code=250KB, data=170KB
[        ] I/zygote64(16601): After code cache collection, code=173KB, data=103KB
[  +14 ms] D/mali_winsys(16601): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000
[  +15 ms] W/libEGL  (16601): load: so=libEGL_vr.so
[        ] W/libEGL  (16601): dlopen failed: library "libEGL_vr.so" not found
[  +15 ms] W/libEGL  (16601): load: so=libEGL_vr.so
[        ] W/libEGL  (16601): dlopen failed: library "libEGL_vr.so" not found
[   +7 ms] W/libEGL  (16601): load: so=libEGL_vr.so
[        ] W/libEGL  (16601): dlopen failed: library "libEGL_vr.so" not found
[  +36 ms] W/libEGL  (16601): load: so=libEGL_vr.so
[        ] W/libEGL  (16601): dlopen failed: library "libEGL_vr.so" not found
[   +6 ms] W/libEGL  (16601): load: so=libEGL_vr.so
[        ] W/libEGL  (16601): dlopen failed: library "libEGL_vr.so" not found
[+3099 ms] I/chromium(16601): [INFO:CONSOLE(5)] "Uncaught TypeError: Object.fromEntries is not a function", source: https://cdn.ckeditor.com/ckeditor5/29.1.0/decoupled-document/ckeditor.js (5)
[  +70 ms] I/chromium(16601): [INFO:CONSOLE(123)] "Uncaught ReferenceError: DecoupledEditor is not defined", source: https://tyhykc.com/admin/previewHelperDoc?id=40 (123)
[ +108 ms] D/HwCust  (16601): Create obj success use class android.app.HwCustHwWallpaperManagerImpl
[   +3 ms] D/HwRTBlurUtils(16601): check blur style for HwPhoneWindow, themeResId : 0x0103023e, context : android.app.Presentation$3@de62d56, Nhwext : 0, get Blur : disable with , null
[   +3 ms] D/HwRTBlurUtils(16601): check blur style for HwPhoneWindow, themeResId : 0x0103023e, context : android.app.Presentation$3@de62d56, Nhwext : 0, get Blur : disable with , null
[   +1 ms] D/OpenGLRenderer(16601):   HWUI Binary is  enabled
[  +73 ms] W/libEGL  (16601): EGLNativeWindowType 0x76e4e56010 disconnect failed
[        ] I/PressGestureDetector(16601): onAttached begin
[        ] I/PressGestureDetector(16601): onAttached end
[        ] I/PressGestureDetector(16601): HiTouch restricted: Sub windows restricted.
[  +51 ms] D/mali_winsys(16601): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000
[   +3 ms] D/OpenGLRenderer(16601):   HWUI Binary is  enabled
[  +34 ms] W/libEGL  (16601): load: so=libEGL_vr.so
[        ] W/libEGL  (16601): dlopen failed: library "libEGL_vr.so" not found
[+2222 ms] D/TelephonyManager(16601): getAllCellInfo calling app is com.hykc.cityfreight
[ +180 ms] D/TelephonyManager(16601): getCellLocation calling app is com.hykc.cityfreight
[  +43 ms] D/TelephonyManager(16601): getAllCellInfo calling app is com.hykc.cityfreight
[+1407 ms] D/TelephonyManager(16601): getAllCellInfo calling app is com.hykc.cityfreight

**Comment by qq627314025** [comment]
The same website can be opened when I test with different mobile phones.
For the same mobile phone, I use the native loading method and can open it normally.
The same mobile phone can open other random web pages normally.
Some plain text web pages of our platform can also be opened on the same mobile phone.
For the same mobile phone, this problem will occur only when we open some web pages with mixed graphics and text. The normal progress is loaded, and then there is gray next to it, about 16 pixels, up, down, left and right. In the middle is the white screen.

**Comment by maheshmnj** [comment]
Thanks for the info to investigate further we would need a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) in a single file that we can copy and run it.

thanks

**Comment by qq627314025** [comment]
body: Obx(() {
          return Column(
            children: [
              state.jin_du.value == 1.0
                  ? Container()
                  : GFProgressBar(
                      margin: EdgeInsets.zero,
                      percentage: state.jin_du.value,
                      backgroundColor: contentColor,
                      progressBarColor: mainColor),
              Expanded(
                child: WebView(
                  initialUrl:
                      'https://tyhykc.com/admin/previewHelperDoc?id=39',
                  javascriptMode: JavascriptMode.unrestricted,
                  onProgress: (progress) {
                    state.jin_du.value = progress / 100.0;
                  },
                ),
              )
            ],
          );
        })

**Comment by maheshmnj** [comment]
> https://tyhykc.com/admin/previewHelperDoc?id=39

@qq627314025 the above URL you shared doesn't seem to load in the chrome browser.

**Comment by qq627314025** [comment]
Thank you. Thank you very much for your advice.
After I updated the browser kernel of my mobile phone, I found that the problem had been solved.

**Comment by maheshmnj** [comment]
Glad you solved it! 

Closing based on the above response.
