### ISSUE TITLE
FormatException: Unexpected extension byte (at offset 5)

### ISSUE THREAD

**Issue by idc77** [flutter/flutter#98254]
I'm aware it's a duplicate, but why isn't this backported?
Switching to master branch is not an option.

What exactly was the change that fixed this `flutter doctor` error with idea?

If you didn't aggressively close issues and limit people talking and exchanging ways to solve this you can not expect other issues to be opened.

**Comment by danagbemava-nc** [comment]
> What exactly was the change that fixed this flutter doctor error with idea?

There was an issue with the `archive`, the package used to decode the jar files. See https://github.com/flutter/flutter/issues/96018. 

You can fix this locally by following the instructions in https://github.com/flutter/flutter/issues/94060#issuecomment-1008040192. 

Closing as this has already been fixed. 

Thank you
