### ISSUE TITLE
Cannot invoke method afterEvaluate() on null object

### ISSUE THREAD

**Issue by BennyX8** [flutter/flutter#98259]
I just recently upgraded to flutter 2.10.0 and having issues building my application both locally and on CI with this verbose:

```
FAILURE: Build failed with an exception.

* Where:
Script '[/Users/user/res/flutter/packages/flutter_tools/gradle/flutter.gradle]()' line: 421

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Cannot invoke method afterEvaluate() on null object

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at [https://help.gradle.org]()

BUILD FAILED in 1s
Exception: Gradle task assembleDebug failed with exit code 1
```

**Comment by madatr** [comment]
same here

**Comment by AndrewPiterov** [comment]
the same

**Comment by madatr** [comment]
an obvious workaround would be to downgrade flutter to a previous version using `flutter downgrade <version>`, I downgraded to version `2.8.1` and all is well

**Comment by cgallarno** [comment]
bump

**Comment by BennyX8** [comment]
> an obvious workaround would be to downgrade flutter to a previous version using `flutter downgrade <version>`, I downgraded to version `2.8.1` and all is well

Didn't actually work for me

**Comment by BennyX8** [comment]
@cgallarno, Did  the workaround solve your issue?

**Comment by cgallarno** [comment]
`flutter downgrade` didn't actually downgrade (I got `There is no previously recorded version for channel "stable".`), but following this (https://stackoverflow.com/a/65280788) example to switch 2.8.1 did get my app to compile again.

**Comment by BennyX8** [comment]
> `flutter downgrade` didn't actually downgrade (I got `There is no previously recorded version for channel "stable".`), but following this (https://stackoverflow.com/a/65280788) example to switch 2.8.1 did get my app to compile again.

Alright, thanks

**Comment by topex-psy** [comment]
#97729 the issue is still open here. In my case I've disabled (commented out) my soundpool plugin and I can build my project on flutter 2.10.
