### ISSUE TITLE
Change ScreenOrientation on Windows, Linux,

### ISSUE THREAD

**Issue by hogdamian** [flutter/flutter#98251]
Hello,

i am trying to change the screen orientation using the services.dart package.
I discovered that changing the orientation in Windows and Linux is still not possible.

```dart
 void main() {
          WidgetsFlutterBinding.ensureInitialized();
          SystemChrome.setPreferredOrientations([DeviceOrientation.landscapeLeft]).then((_){
           runApp(MyApp());
          });
        } 
```

**Comment by darshankawar** [comment]
Please check [this](https://github.com/flutter/flutter/issues/74979) similar issue and underlying comments on `SystemChrome.setPreferredOrientations` behavior when it comes to desktops which should answer your question.
Closing this as a duplicate.
