### ISSUE TITLE
[shared_preferences] Safe to load only once

### ISSUE THREAD

**Issue by TheCarpetMerchant** [flutter/flutter#98257]
Is the SharedPreferences instance safe to load only once and then not load again until the app is restarted ?
This question applies to all Flutter supported platforms.

Hope I worded this sufficiently well to have it come up in future searches.

**Comment by stuartmorgan** [comment]
See https://flutter.dev/community#community-grid for resources where you can ask support questions. The issue tracker is specifically for bug reports and feature requests.
