### ISSUE TITLE
Add flutter.minSdkVersion to local.properties

### ISSUE THREAD

**Issue by cedvdb** [flutter/flutter#98269]
Some packages are relying on a value to be set either in local.properties or in build.gradle for the minSdk. With the newer releases of flutter this property is now  `flutter.minSdkVersion` in `build.gradle` but does not figure in local.properties.

Adding that value there would make it easier to know which value flutter is using for those packages. Also it wouldn't require the user to explicitly overwrite it so the package can know the value by reading local.properties.

**Comment by danagbemava-nc** [comment]
Hi @cedvdb, there's a similar issue reported in https://github.com/flutter/flutter/issues/95533 and there's a PR in flight to address this in https://github.com/flutter/flutter/pull/95684. 

Kindly follow up in either of them for more information.

Closing from here as duplicate. 

Thank you
