### ISSUE TITLE
The ci_yaml roller should support target level dimension override

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#98274]
Context: https://github.com/flutter/flutter/pull/98210 overrides OS and Xcode version on target level, only the properties Xcode version was rolled to corresponding target config: https://flutter-review.googlesource.com/c/infra/+/26740/2/config/generated/flutter/luci/cr-buildbucket.cfg

The dimension is currently referencing only on platform level: https://flutter.googlesource.com/infra/+/refs/heads/main/config/lib/ci_yaml/ci_yaml.star#315

The roller should support dimension override as well for cases where we need to override for specific targets.

**Comment by godofredoc** [comment]
This has been implemented.
