### ISSUE TITLE
`update-packages` error message because of `dart pub get` usage

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#98270]
## Reproduction
`flutter update-packages --force-upgrade`

## Seen results

The following error happens, but upgrading seems to have worked.

```
$ flutter update-packages --force-upgrade
Upgrading packages...
WARNING: the following packages use hard-coded version constraints:
  - flutter_gallery_assets: 1.0.2
  - flutter_template_images: 4.0.0
  - shelf: 1.1.4
  - video_player: 2.2.11
Running "flutter pub upgrade" in flutter_update_packages.5VmtFB...      2,612ms
Because release_smoke_test depends on integration_test from sdk which doesn't exist (the Flutter SDK is not available), version solving failed.

Flutter users should run `flutter pub get` instead of `dart pub get`.
pub get failed (69; Flutter users should run `flutter pub get` instead of `dart pub get`.)
```

## Expected results
No error message.

## flutter version

8cd540f449a717b33a5500fca7dedf86e2204d62

**Comment by christopherfujino** [comment]
hmmm...

**Comment by christopherfujino** [comment]
Hmm, this command works for me locally.

This is suspicious, and makes me think your local setup is wrong?

`Because release_smoke_test depends on integration_test from sdk which doesn't exist (the Flutter SDK is not available)`

**Comment by gaaclarke** [comment]
@christopherfujino I do have local changes in device_lab tests.  I'm running the `update-packages` in the flutter directory itself.  I don't have any local changes for or related to `release_smoke_test`.  Does it matter where you run that command from?

**Comment by gaaclarke** [comment]
I was able to get update-packages to work by going directly to master.  I was running it from a branch of master.  I'm not sure why my changes would have broken it but that was the workaround.
