### ISSUE TITLE
flutter create crashed on Windows

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#9828]
Output:

```
C:\Users\eli ladd\Code\myflutterapp>flutter create .

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 41485a7640000000)
Crash report written to C:\Users\eli ladd\Code\myflutterapp\flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.
```

```
C:\Users\eli ladd\Code\myflutterapp>flutter create .

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 41485a7640000000)
Crash report written to C:\Users\eli ladd\Code\myflutterapp\flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.

C:\Users\eli ladd\Code\myflutterapp>flutter --version
Flutter • channel master • https://github.com/flutter/flutter.git
Framework • revision 31000ef77e (2 days ago) • 2017-05-02 21:12:28 -0700
Engine • revision da8ebf40bd
Tools • Dart 1.23.0-dev.11.11
```

```
C:\Users\eli ladd\Code\myflutterapp>flutter --version
Flutter • channel master • https://github.com/flutter/flutter.git
Framework • revision 31000ef77e (2 days ago) • 2017-05-02 21:12:28 -0700
Engine • revision da8ebf40bd
Tools • Dart 1.23.0-dev.11.11

C:\Users\eli ladd\Code\myflutterapp>flutter doctor
[√] Flutter (on Microsoft Windows [Version 10.0.14393], channel master)
    • Flutter at c:\Users\eli ladd\Code\flutter
    • Framework revision 31000ef77e (2 days ago), 2017-05-02 21:12:28 -0700
    • Engine revision da8ebf40bd
    • Tools Dart version 1.23.0-dev.11.11

[√] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at C:\Users\eli ladd\AppData\Local\Android\sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Connected devices
    • None
```

**Comment by sethladd** [comment]
Crash log:

```
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter create .

## exception

RangeError: RangeError (index): Invalid value: Valid value range is empty: 0

```
#0      _StringBase.[] (dart:core-patch/string_patch.dart:227)
#1      _createPluginClassName (package:flutter_tools/src/commands/create.dart:237)
#2      CreateCommand._templateContext (package:flutter_tools/src/commands/create.dart:196)
#3      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:105)
<asynchronous suspension>
#4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:205)
<asynchronous suspension>
#5      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:156)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:262)
<asynchronous suspension>
#8      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#9      Future.Future.sync (dart:async/future.dart:208)
#10     CommandRunner.run (package:args/command_runner.dart:109)
#11     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:157)
#12     run.<anonymous closure> (package:flutter_tools/executable.dart:140)
<asynchronous suspension>
#13     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#14     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#15     _rootRun (dart:async/zone.dart:1120)
#16     _CustomZone.run (dart:async/zone.dart:1001)
#17     runZoned (dart:async/zone.dart:1465)
#18     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#19     run (package:flutter_tools/executable.dart:113)
<asynchronous suspension>
#20     main (package:flutter_tools/executable.dart:66)
<asynchronous suspension>
#21     main (file:///c:/Users/eli%20ladd/Code/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#22     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

## flutter doctor

```
[✓] Flutter (on Microsoft Windows [Version 10.0.14393], channel master)
    • Flutter at c:\Users\eli ladd\Code\flutter
    • Framework revision 31000ef77e (2 days ago), 2017-05-02 21:12:28 -0700
    • Engine revision da8ebf40bd
    • Tools Dart version 1.23.0-dev.11.11

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at C:\Users\eli ladd\AppData\Local\Android\sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Connected devices
    • None

```

**Comment by sethladd** [comment]
Something to do with plugins?

cc @mit-mit

**Comment by mit-mit** [comment]
This appears to be a Windows-specific path handling problem (it errors in `_createPluginClassName (package:flutter_tools/src/commands/create.dart:242)`, but the underlying problem is that the `name` argument passed to that function should have been a folder name, but it's actually passed an empty string. So this is an error in flutter tools.

**Comment by mit-mit** [comment]
You can work around this by passing `flutter create` a folder name rather than passing it just `.`.

**Comment by sethladd** [comment]
cc @goderbauer

**Comment by goderbauer** [comment]
My suggested fix for this would be to limit the arguments accepted by `flutter create` to only be legal dart package names. That would also fix https://github.com/flutter/flutter/issues/9564.

**Comment by sethladd** [comment]
works for me

**Comment by goderbauer** [comment]
Actually, I take that back, the real problem is a bug in package:path: https://github.com/dart-lang/path/issues/24
