### ISSUE TITLE
[camera] how can i control the camera speed in camera plugin?

### ISSUE THREAD

**Issue by shinewanna** [flutter/flutter#98313]
` _cameraController =
        CameraController(CameraHandler.cameras![0], ResolutionPreset.max);
    _cameraController!.initialize().then((_) {
    });`

There's no option for camera speed like shutter, how can I manage to use it?
Thank u for ur time.

**Comment by darshankawar** [comment]
@shinewanna 
Check this merged PR https://github.com/flutter/plugins/pull/4256 and see if it addresses your question.

**Comment by shinewanna** [comment]
I didn't find any related answer for my case, I wanna control the shutter or speed of the camera, like exposure ` _cameraController!.setExposureOffset(value);` but there's no option.

**Comment by darshankawar** [comment]
@shinewanna 
Check if this is similar to what you are looking for https://github.com/flutter/plugins/pull/3346
