### ISSUE TITLE
Where can know the flutter design ideas ?

### ISSUE THREAD

**Issue by tzsh1007** [flutter/flutter#98319]
I want to understand flutter's implementation ideas and design ideas at a deeper level, if you can say something more at the architectural level, it will be more conducive to daily development, and there is an important thing: where to get the inheritance relationship map of Flutter class

**Comment by darshankawar** [comment]
@tzsh1007 
Since this repo is more about tracking bugs and feature requests, I suggest you to ask this question on flutter's discord to get quick input directly from team. https://flutter.dev/community,  https://discord.com/invite/N7Yshp4
Closing from here.

**Comment by tzsh1007** [comment]
@darshankawar https://discord.com/invite/N7Yshp4 I can't sign up, So People from China can't do that 
![企业微信20220215-145501](https://user-images.githubusercontent.com/13128029/154008907-15fb8b4a-cd2c-42a3-a49b-7d160c593259.png)
