### ISSUE TITLE
RenderBox was not laid out

### ISSUE THREAD

**Issue by tamara-argentina** [flutter/flutter#98337]
I can't see the app I am creating, I just see the background color and I get this error:

RenderBox was not laid out: RenderPadding#7dc5d relayoutBoundary=up10 NEEDS-PAINT
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1929 pos 12: 'hasSize'

It was working perfectly fine till now

![screenshotBug](https://user-images.githubusercontent.com/75818001/153721929-e1b8e40e-dbb8-4727-9ae5-4f776f097dd2.png)
w

**Comment by maheshmnj** [comment]
Hi @tamara-argentina, Thanks for filing the issue. 

> Failed assertion: line 1929 pos 12: 'hasSize'

From the error, it looks like you have not provided size constraint to your widget.

Please share a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) along with the output of `flutter doctor -v` to better address the issue.

Thanks
