### ISSUE TITLE
com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 2261

### ISSUE THREAD

**Issue by BennyX8** [flutter/flutter#98341]
I've been trying to build my android project on Codemagic, I keep getting `MalformedJsonException`.
I am assuming the (firebase) google-services.json file encoded to base64 string is where the issue is arising from.

`* What went wrong:
Execution failed for task ':app:processReleaseGoogleServices'.
> com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 2261`.

**Comment by darshankawar** [comment]
@BennyX8 
Since this seems to be occuring while running on CICD tool, its better to raise this issue in dedicated service provider's repo or issue tracking.
If you are getting same error running locally, then write in comments and I'll reopen this issue.
Closing for now.
