### ISSUE TITLE
flutter pub outdated throws: `pub finished with exit code 69`

### ISSUE THREAD

**Issue by realkimmy** [flutter/flutter#98349]
## Steps to Reproduce

flutter pub outdated throws: `pub finished with exit code 69`

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel stable, 2.10.1, on macOS 12.2.1 21D62 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.10.1 at /Users/ying/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (3 days ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/ying/Library/Android/sdk
    • Platform android-31, build-tools 30.0.2
    • ANDROID_SDK_ROOT = /Users/ying/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[☠] IntelliJ IDEA Ultimate Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:205:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:309:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (5 available)
    • MI 9 (mobile)        • a423bb1a                             • android-arm64  • Android 11 (API 30)
    • WY's iPhone (mobile) • 00008020-000A1D110A32002E            • ios            • iOS 15.3.1 19D52
    • iPhone 13 (mobile)   • BA8AFB07-A790-407C-AED9-36F4F447D775 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)      • macos                                • darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)         • chrome                               • web-javascript • Google Chrome 98.0.4758.80
    ! Error: WY's iPhone is busy: Preparing the watch for development via WY's iPhone. Xcode will continue when WY's iPhone is finished. (code -10)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

```

</details>

**Comment by a2425rdl** [comment]
> 
> 
> ## Steps to Reproduce
> 
> 
> 
> flutter pub outdated throws: `pub finished with exit code 69`
> 
> **Expected results:** 
> 
> **Actual results:** 
> 
> <details>
> <summary>Code sample</summary>
> 
> 
> 
> ```dart
> ```
> 
> </details>
> 
> <details>
>   <summary>Logs</summary>
> 
> 
> 
> ```
> ```
> 
> 
> 
> ```
> ```
> 
> 
> 
> ```
> [✓] Flutter (Channel stable, 2.10.1, on macOS 12.2.1 21D62 darwin-x64, locale zh-Hans-CN)
>     • Flutter version 2.10.1 at /Users/ying/flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision db747aa133 (3 days ago), 2022-02-09 13:57:35 -0600
>     • Engine revision ab46186b24
>     • Dart version 2.16.1
>     • DevTools version 2.9.2
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
>     • Android SDK at /Users/ying/Library/Android/sdk
>     • Platform android-31, build-tools 30.0.2
>     • ANDROID_SDK_ROOT = /Users/ying/Library/Android/sdk
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • CocoaPods version 1.11.2
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 2021.1)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
> 
> [☠] IntelliJ IDEA Ultimate Edition (the doctor check crashed)
>     ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
>     ✗ FormatException: Unexpected extension byte (at offset 5)
>     • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
>       #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
>       #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
>       #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
>       #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
>       #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
>       #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
>       #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
>       #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
>       #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
>       #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
>       #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
>       #12     _rootRun (dart:async/zone.dart:1426:13)
>       #13     _CustomZone.run (dart:async/zone.dart:1328:19)
>       #14     _runZoned (dart:async/zone.dart:1861:10)
>       #15     runZonedGuarded (dart:async/zone.dart:1849:12)
>       #16     runZoned (dart:async/zone.dart:1780:12)
>       #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
>       #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:205:9)
>       #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:309:47)
>       #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
>       #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
>       <asynchronous suspension>
>       #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
>       <asynchronous suspension>
>       #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
>       <asynchronous suspension>
>       #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
>       <asynchronous suspension>
>       #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
>       <asynchronous suspension>
>       #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
>       <asynchronous suspension>
>       #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
>       <asynchronous suspension>
>       #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
>       <asynchronous suspension>
>       #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
>       <asynchronous suspension>
>       #30     main (package:flutter_tools/executable.dart:94:3)
>       <asynchronous suspension>
> 
> 
> [✓] VS Code (version 1.63.2)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.29.0
> 
> [!] Proxy Configuration
>     • HTTP_PROXY is set
>     ! NO_PROXY is not set
> 
> [✓] Connected device (5 available)
>     • MI 9 (mobile)        • a423bb1a                             • android-arm64  • Android 11 (API 30)
>     • WY's iPhone (mobile) • 00008020-000A1D110A32002E            • ios            • iOS 15.3.1 19D52
>     • iPhone 13 (mobile)   • BA8AFB07-A790-407C-AED9-36F4F447D775 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
>     • macOS (desktop)      • macos                                • darwin-x64     • macOS 12.2.1 21D62 darwin-x64
>     • Chrome (web)         • chrome                               • web-javascript • Google Chrome 98.0.4758.80
>     ! Error: WY's iPhone is busy: Preparing the watch for development via WY's iPhone. Xcode will continue when WY's iPhone is finished. (code -10)
> 
> [✓] HTTP Host Availability
>     • All required HTTP hosts are available
> 
> ! Doctor found issues in 2 categories.
> 
> ```
> 
> </details>
> 
> 
>

**Comment by darshankawar** [comment]
@realkimmy 
Can you provide the entire stacktrace that shows the error `pub finished with exit code 69` ?

I just tried the same and didn't replicate it for me:

```
dhs@Dhss-MacBook-Pro testdemo % flutter pub outdated
Showing outdated packages.
[*] indicates versions that are not the latest available.

Package Name                Current  Upgradable  Resolvable  Latest   

direct dependencies:       
cupertino_icons             *1.0.2   1.0.4       1.0.4       1.0.4    
shared_preferences          *2.0.12  2.0.13      2.0.13      2.0.13   
url_launcher                *6.0.18  6.0.20      6.0.20      6.0.20   

transitive dependencies:   
shared_preferences_android  *2.0.10  2.0.11      2.0.11      2.0.11   
shared_preferences_ios      *2.0.9   2.0.10      2.0.10      2.0.10   
shared_preferences_linux    *2.0.4   2.1.0       2.1.0       2.1.0    
shared_preferences_macos    *2.0.2   2.0.3       2.0.3       2.0.3    
shared_preferences_windows  *2.0.4   2.1.0       2.1.0       2.1.0    
url_launcher_android        *6.0.14  6.0.15      6.0.15      6.0.15   
url_launcher_ios            *6.0.14  6.0.15      6.0.15      6.0.15   
url_launcher_linux          *2.0.3   3.0.0       3.0.0       3.0.0    
url_launcher_macos          *2.0.3   3.0.0       3.0.0       3.0.0    
url_launcher_web            *2.0.6   2.0.8       2.0.8       2.0.8    
url_launcher_windows        *2.0.2   3.0.0       3.0.0       3.0.0    
win32                       *2.3.8   2.4.0       2.4.0       2.4.0    
xdg_directories             *0.2.0   0.2.0+1     0.2.0+1     0.2.0+1  

16 upgradable dependencies are locked (in pubspec.lock) to older versions.
To update these dependencies, use `flutter pub upgrade`.

```

Also check or try on a different network provider / connection.

**Comment by realkimmy** [comment]
This problem is caused by my proxy
