### ISSUE TITLE
[desktop:windows]: Horizontal resizing doesn't work on secondary display.

### ISSUE THREAD

**Issue by ZyphenVisuals** [flutter/flutter#98353]
Describe your issue and include the command you're running, flutter_desktop version, browser version

Issue found on the following flutter install:
`Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.1, on Microsoft Windows [Version 10.0.19044.1526], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.6)
[√] Android Studio (version 4.1)
[√] VS Code (version 1.64.2)
[√] Connected device (2 available)
[√] HTTP Host Availability`

Both in debug mode, as well as in the release build, Window application can't be resized horizontally when moved onto a secondary monitor (to the left of the primary one).

Important note: I am using fluent_ui and a FluentApp, not MaterialApp. Not sure if that affects scaling behavior however.

Also noticed that as long as the right edge of the app window is on the primary monitor it can still be resized horizontally, however it does lock onto the edge between the 2 screens for a while when passing through it.

Video demo of the error: https://www.youtube.com/watch?v=98VipG7K1DM

**Comment by darshankawar** [comment]
@ZyphenVisuals 
Since I don't have multiple monitors to verify this, but can you confirm if this behavior also occurs using default counter app with MaterialApp too ? Or is there a way to replicate this without involving monitors ?

**Comment by ZyphenVisuals** [comment]
Cannot replicate with default MaterialApp, neither after changing it to a FluentApp.

After some testing I narrowed down the problem to the package `window_manager`. I had already suspected it so I tested without importing or using it, but it seems the error appears right after installing it with `flutter pub add window_manager`, even if you never do anything with it.

Demonstration: https://youtu.be/R2KcCFDJOUs

I understand `window_manager` might be unrelated to the Flutter dev team. If so, I will close this issue and try submitting an issue on their page.

Thanks for the help!

**Comment by ZyphenVisuals** [comment]
Additional information: The error is unrelated to FluentAPP or fluent_ui. The exact same happens with the default Material Counter after performing `flutter pub add window_manager`, as shown in the last video.

**Comment by darshankawar** [comment]
Thanks for additional details. From what I understand, this seems to be happening after you add [window_manager](https://pub.dev/packages/window_manager), so you will probably need to report this in dedicated repo: https://github.com/leanflutter/window_manager/issues
I am closing from here. If you disagree, write in comments and I'll reopen it.
