### ISSUE TITLE
IntelliJ IDEA Ultimate Edition (the doctor check crashed)

### ISSUE THREAD

**Issue by yuthstyle88** [flutter/flutter#98364]
[☠] IntelliJ IDEA Ultimate Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this
      issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)

**Comment by timsneath** [comment]
Duplicate of #94060
