### ISSUE TITLE
Issue ID 95540 was closed by bot but still does not work on any channel (even dev) as of 2022-02-13

### ISSUE THREAD

**Issue by mzimmerm** [flutter/flutter#98379]
Issue ID 

https://github.com/flutter/flutter/issues/95540

was closed by bot but still does not work on any channel (even dev) as of 2022-02-13.

I am unable to reopen the issue. 

There are detail steps provided in the item to duplicate. The message is the same.

**Comment by darshankawar** [comment]
@mzimmerm 
A fix was made : https://github.com/flutter/flutter/pull/97157 and pushed onto master.
`dev` channel has been de-commissioned, so you'll need to switch to latest master using following commands and then run the code once again to see if issue still persists on it or not.
If yes, write in comments, I'll reopen the original issue so we can track it there.

`flutter channel master`
`flutter upgrade`

**Comment by mzimmerm** [comment]
@darshankawar : Let me test it this week and get back here.
