### ISSUE TITLE
app window cannot respond after display a few minutes lottie animation on Windows 7 service pack 1.

### ISSUE THREAD

**Issue by boyan01** [flutter/flutter#98382]
On windows 7 Service pack 1, after displaying the gif/lottie animation for a few minutes, the app window becomes a black screen and cannot respond.

## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. run with release on window 7. 
3. Wait a few minutes (about 3 minutes in my virtual machine)

**Expected results:** 

Animation works fine.

**Actual results:** 

Animation stopped, and move the mouse pointer up and the window will turn black.

<img width="1523" alt="image" src="https://user-images.githubusercontent.com/17426470/153800392-9705f179-bed5-4562-a6eb-a5ebe6f9a672.png">

<details>
<summary>Code sample</summary>

need add `lottie: ^1.2.1` to pubspec deps.

```dart
import 'package:flutter/material.dart';
import 'package:lottie/lottie.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
        body: Wrap(
          children: [
            Lottie.network(
              'https://mixin-assets.zeromesh.net/stickers/5eedde22-0434-46d5-87ff-65d8ba612c67/covers/5eedde22-0434-46d5-87ff-65d8ba612c67.json',
              width: 100,
              height: 100,
            ),
            Lottie.network(
              'https://mixin-assets.zeromesh.net/stickers/6a51ed77-27b8-4550-87aa-35fec3838641/covers/6a51ed77-27b8-4550-87aa-35fec3838641.json',
              width: 100,
              height: 100,
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
Flutter 2.11.0-0.0.pre.541 • channel master • https://github.com/flutter/flutter.git
Framework • revision ad612b59e5 (3 hours ago) • 2022-02-13 17:20:18 -0800
Engine • revision cef6370095
Tools • Dart 2.17.0 (build 2.17.0-104.0.dev) • DevTools 2.10.0
```

</details>

**Comment by darshankawar** [comment]
@boyan01 
Since `lottie` is a 3rd party plugin, can you try the same using this https://docs.flutter.dev/cookbook/images/network-image example and see if you still get same behavior with it too ?

**Comment by boyan01** [comment]
Actually displaying Gif with `Image` Widget will have the same error. It's just that the time it takes for this to happen with Lottie is shorter, and it's also a problem when displaying multiple Gifs for a long time.

**Comment by darshankawar** [comment]
Actually, there's similar open issue describing your case, https://github.com/flutter/flutter/issues/92571
Please follow-up in it for further updates.
Closing this as a duplicate.
