### ISSUE TITLE
[in_app_purchase] is there any way to check if someone refunded a non-consumable item?

### ISSUE THREAD

**Issue by MilesAdamson** [flutter/flutter#98383]
Currently having an issue:
- User buys a non-consumable item
- I mark it as bought in my system (in this case, removing ads)
- User refunds it
- It is still marked as bought and there is no obvious way to check a purchase history or refund status

Due to how purchase info is sent via [purchaseStream](https://pub.dev/documentation/in_app_purchase/latest/in_app_purchase/InAppPurchase/purchaseStream.html) there is no obvious way to check what purchases a user has made and possibly refunded. `restorePurchases` causes nothing to be piped into the stream. [purchaseStatus](https://pub.dev/documentation/in_app_purchase_platform_interface/latest/in_app_purchase_platform_interface/PurchaseStatus.html) does not have a value for refunded.

**Comment by darshankawar** [comment]
@MilesAdamson 
Is this on Android or iOS ?

Regarding `restorePurchases` not returning anything, there's an issue for tracking the same for iOS: https://github.com/flutter/flutter/issues/98113, whereas the same seems to be working for Android.

Also check this open issue to add refund functionality for iOS and see if your case is same as it: https://github.com/flutter/flutter/issues/95404

**Comment by MilesAdamson** [comment]
This is iOS so likely a duplicate of https://github.com/flutter/flutter/issues/98113, thanks for the response
