### ISSUE TITLE
Unable to switch camera when recording video.

### ISSUE THREAD

**Issue by NibhaJ** [flutter/flutter#98397]
Only the button toggles but not the camera preview. Is ther a way to achieve switching the camera when video recording is already going on?

**Comment by danagbemava-nc** [comment]
Hi @NibhaJ, is this something that you can do with your native camera app?

**Comment by NibhaJ** [comment]
Not in my native camera app but I have seen it in instagram.

**Comment by danagbemava-nc** [comment]
It looks like there's already an issue open requesting such a feature in https://github.com/flutter/flutter/issues/82467. Kindly follow up there for more information. 

Closing from here as duplicate. 

Thank you
