### ISSUE TITLE
RaisedButtons stay pressed

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#984]
Once pressed, RaisedButtons stay that way. Any of the gallery demos with a RaisedButton (like the bottom sheet demos) can be used to check this.

**Comment by abarth** [comment]
@Hixie did you fix this with e20ec39b81b6065c1a5787ed5a439781d612a051 ?

**Comment by Hixie** [comment]
Aha, I knew there was a bug about this. Searched for "highlight", "shadows", "shadow"', "buttons", "raised"... didn't try "RaisedButtons" or "pressed". D'oh.

Yeah, fixed it.
