### ISSUE TITLE
Gallery's AppBar should probably have 0.0 elevation on iOS

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#9840]
This is an easy one-line change that would make it look more like other Google iOS apps.

Gmail:
![Gmail](https://cloud.githubusercontent.com/assets/394889/25754335/9fccab82-3173-11e7-88db-e9324f9006a9.png)

Gallery
![Gallery](https://cloud.githubusercontent.com/assets/394889/25754348/ab469c8e-3173-11e7-9985-3172c8a92ffd.png)

**Comment by sethladd** [comment]
Just curious, have you checked a few other google apps (such as Inbox and/or Music) ?

**Comment by collinjackson** [comment]
Inbox is the same (zero elevation)

**Comment by sethladd** [comment]
Cool, thanks for checking.

**Comment by eseidelGoogle** [comment]
Should we just change AppBar itself to do this by default? :)  @HansMuller  https://material.io/guidelines/platforms/platform-adaptation.html

**Comment by HansMuller** [comment]
Yes, I think that would make sense. The[ platform-adaptation](https://material.io/guidelines/platforms/platform-adaptation.html) doesn't make it clear that the appbar should elevate when content is scrolled underneath. I think that's also supposed to be the default behavior however it's not done consistently on Android. I'd check on my iOS device but it's locked into some kind of iTunes login death spiral.

**Comment by Hixie** [comment]
@cbracken looked at other iOS apps and showed me that we do the same thing.
