### ISSUE TITLE
Is there a way to disable the app download option on flutter web?

### ISSUE THREAD

**Issue by rrrovalle** [flutter/flutter#98400]
When opening the application on a computer or browser in mobile a option for download or saving the page appears. There is some solution to disable this option?

**Comment by danagbemava-nc** [comment]
Hi @rrrovalle, you can try adding this to your <script> tag in your `index.html`.

```javascript
 window.addEventListener('beforeinstallprompt', function (e) {
      e.preventDefault();
      return false;
    });
```

In the future do note that the flutter issue tracker is reporting bugs and feature requests, not for asking such support questions. You may visit any of the communities in https://flutter.dev/community#community-grid for asking such support questions. 

Closing as this is neither a feature request nor a bug report. 

Thank you

**Comment by rrrovalle** [comment]
Thank you, friend!
