### ISSUE TITLE
type 'WidgetSpan' is not a subtype of type 'TextSpan'

### ISSUE THREAD

**Issue by carmel** [flutter/flutter#98406]
## Steps to Reproduce

```sh
flutter --version
Flutter 2.10.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision db747aa133 (5 days ago) • 2022-02-09 13:57:35 -0600
Engine • revision ab46186b24
Tools • Dart 2.16.1 • DevTools 2.9.2

```

In my code below, one section is an uncommented return statement and one section is a commented return statement. The commented part does not report an error, but the uncommented part reports the error as the title showed.

![image](https://user-images.githubusercontent.com/36031579/153872108-18bdae03-2153-4703-8d20-c8dc47475be4.png)

Although the commented part of the code can be run, I don't want to use it. Because that would cause the text to break down the middle, just like :

![Screenshot_2022-02-14-21-36-18-363_com christ e_book](https://user-images.githubusercontent.com/36031579/153880009-e02bd9a0-2374-496d-9bba-791de9eca33e.jpg)

which breaked at the place marked by the red box.

<details>
<summary>
dart code
</summary>

```dart
return SelectableText.rich(TextSpan(children: [
      WidgetSpan(
        child: Transform.translate(
          offset: const Offset(0.0, -7.0),
          child: Text(
            element.textContent,
            style: const TextStyle(fontSize: 10),
          ),
        ),
      ),
    ]));

    // return Text.rich(
    //   WidgetSpan(
    //     child: Transform.translate(
    //       offset: const Offset(0.0, -7.0),
    //       child: Text(
    //         element.textContent,
    //         style: TextStyle(fontSize: 10),
    //       ),
    //     ),
    //   ),
    // );
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by mozochek** [comment]
[`WidgetSpan`](https://api.flutter.dev/flutter/widgets/WidgetSpan-class.html) shoudn't be a subtype of `TextSpan`, becase text and widget is different. `WidgetSpan` is a subtype of `InlineSpan`, so you can write code like this:
```dart
const Text.rich(
  TextSpan(
    children: <InlineSpan>[
      TextSpan(text: 'Flutter is'),
      WidgetSpan(
        child: SizedBox(
          width: 120,
          height: 50,
          child: Card(
            child: Center(
              child: Text('Hello World!')
            )
          ),
        )
      ),
      TextSpan(text: 'the best!'),
    ],
  )
)
```

**Comment by carmel** [comment]
@danagbemava-nc hi, [here](https://github.com/carmel/flutter_issue_sample) is the samle repo

**Comment by carmel** [comment]
Any help? the same repo has another [issue](https://github.com/flutter/flutter/issues/98412).

**Comment by danagbemava-nc** [comment]
HI @carmel, the analyzer doesn't show any errors for me and I'm able to run the app just fine. 

At what point do you get the error? 

> Any help? the same repo has another [here](https://github.com/flutter/flutter/issues/98412).

Someone will take a look at it soon

**Comment by carmel** [comment]
Hi @danagbemava-nc  The code that reports the error is the following part, sorry for not submitting it before.

```dart
final String textContent = element.textContent;
    String text = '';
    for (int i = 0; i < textContent.length; i++) {
      text += _supscripts[textContent[i]] ?? '';
    }

    // return SelectableText.rich(TextSpan(text: text));
    return SelectableText.rich(
      TextSpan(
        children: [
          WidgetSpan(
            child: Transform.translate(
              offset: const Offset(0.0, -7.0),
              child: Text(
                text,
                style: const TextStyle(fontSize: 10),
              ),
            ),
          ),
        ],
      ),
    );
```

Debug in vscode automatically jumps here：

![image](https://user-images.githubusercontent.com/36031579/154050754-cfbc8698-48ef-49ab-b8b8-141ec2567865.png)

**Comment by danagbemava-nc** [comment]
Hi @carmel, the reason you're running into this issue is that the `flutter_markdown` `_mergeInlineChildren` method expects a type of `TextSpan` and since `WidgetSpan` is not a subtype of `TextSpan`, you get the error you're getting. Below is a sample from the code snippet that handles the `SelectableText` section of `_mergeInlineChildren`. That's why if you use `Text.rich` it works just fine. 

Does that make sense?

```dart
else if (mergedTexts.isNotEmpty &&
          mergedTexts.last is SelectableText &&
          child is SelectableText) {
        final SelectableText previous =
            mergedTexts.removeLast() as SelectableText;
        final TextSpan previousTextSpan = previous.textSpan!;
        final List<TextSpan> children = previousTextSpan.children != null
            ? List<TextSpan>.from(previousTextSpan.children!)
            : <TextSpan>[previousTextSpan];
        if (child.textSpan != null) {
          children.add(child.textSpan!);
        }
```

**Comment by carmel** [comment]
Oh, thank you, really!
