### ISSUE TITLE
Flutter deployment with Fastlane problem because of non null safety

### ISSUE THREAD

**Issue by Kiimlee** [flutter/flutter#98425]
Hello,

I have a Flutter app using Firebase, and I want to deploy with Fastlane to Firebase. Everything is going fine but I'm facing issue when executing "bundle exec fastlane app_name" or archive for iOS. This is a snapshot of what I see on the terminal when I'm failing to deploy the iOS app with Fastlane.

** ARCHIVE FAILED **

The following build commands failed:
	PhaseScriptExecution Run\ Script /Users/wkim/Library/Developer/Xcode/DerivedData/Runner-eyzlbaddawdwwnfutylnsjwylbrx/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release-iphoneos/Runner.build/Script-9740EEB61CF901F6004384FC.sh (in target 'Runner' from project 'Runner')
(1 failure)
[16:46:53]: Exit status: 65

+---------------+---------------------------------+
|                Build environment                |
+---------------+---------------------------------+
| xcode_path    | /Users/wkim/Downloads/Xcode.app |
| gym_version   | 2.204.3                         |
| export_method | development                     |
| sdk           | iPhoneOS15.0.sdk                |
+---------------+---------------------------------+

[16:46:53]: ▸  - package:quiver
[16:46:53]: ▸ For solutions, see https://dart.dev/go/unsound-null-safety
[16:46:53]: ▸ Failed to package /Users/wkim/Workspace/FlutterApps/notes_firebase_app.
[16:46:53]: ▸ Command PhaseScriptExecution failed with a nonzero exit code

and with android it seems the same issue.

I already tried to delete derived data, clean, pod uninstall and install and reboot computer. I know there is a run command for running on device or simulator, but I'm trying to deploy which is different. Hope someone could help me with this.

**Comment by darshankawar** [comment]
@Kiimlee 
Since you are experiencing this using Fastlane which is CICD and third party for Flutter, I suggest you to ask / raise this issue in dedicated repo of Fastlane.
Closing from here as this looks more of a service provider related issue. If you disagree or think this is a genuine bug in the framework, write in comments and I'll reopen it.
Thanks.
