### ISSUE TITLE
Embedding NuGet package inside Flutter application

### ISSUE THREAD

**Issue by farahmahmoud70** [flutter/flutter#98429]
Is there any way to Embedd a NuGet package as a plugin inside the Flutter application? or even write a plugin wrapping a NuGet package inside it?

**Comment by farahmahmoud70** [comment]
@stuartmorgan hello, I have seen your issue the thing is you're talking about windows only, so what if I want to use it for Android and IOS too same concept as xamarin.forms one NuGet for all platforms, Is it valid?

**Comment by stuartmorgan** [comment]
If you want to use a non-standard package manager for a given platform, it would be up to you to integrate it into the native build (and to document for any clients of the plugin that they need non-standard tooling). It's not a supported use case.
