### ISSUE TITLE
Mac45 is causing infra flakes on staging iOS tests

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#98426]
It looks like these started on an unrelated commit.

Not sure whether this is also the cause of https://github.com/flutter/flutter/issues/98419, but I am suspicious of it.

<img width="630" alt="Screen Shot 2022-02-14 at 8 18 58 AM" src="https://user-images.githubusercontent.com/6343103/153903143-f84ad223-208d-4553-b170-593676fd57fa.png">

/cc @jmagman

**Comment by keyonghan** [comment]
All these happened on Mac45, which hit 
```
Testing failed:
	infra-dialogUITests:
		infra-dialogUITests-Runner encountered an error (Failed to install or launch the test runner. If you believe this error represents a bug, please attach the result bundle at /Users/swarming/Library/Developer/Xcode/DerivedData/infra-dialog-ayzxmkyimrprakexnyiavfekoqad/Logs/Test/Test-infra-dialog-2022.02.14_03-19-08--0800.xcresult. (Underlying Error: Unable to launch dev.flutter.infra-dialogUITests.xctrunner. (Underlying Error: Request to launch dev.flutter.infra-dialogUITests.xctrunner failed. The operation couldn’t be completed. Unable to launch dev.flutter.infra-dialogUITests.xctrunner because it has an invalid code signature, inadequate entitlements or its profile has not been explicitly trusted by the user. : Failed to launch process with bundle identifier 'dev.flutter.infra-dialogUITests.xctrunner'. (Underlying Error: The operation couldn’t be completed. Unable to launch dev.flutter.infra-dialogUITests.xctrunner because it has an invalid code signature, inadequate entitlements or its profile has not been explicitly trusted by the user.))))
```

Sounds similar to https://github.com/flutter/flutter/issues/95272#issuecomment-995034974.

Quarantined for now, and it would be helpful to take a screenshot.

**Comment by godofredoc** [comment]
@keyonghan can you please take a look why the device recovery is not deleting the application on after-task.

Context for this issue is that salt states were broken and they didn't update the apple provisioning profile certificates. When the salt states got fixed they updated it and now the dismiss dialog application is trying to update the application in the phone which was created and signed with a different certificate.

**Comment by keyonghan** [comment]
From swarming log and several recent failed builds: the apps were indeed not un-installed. Checking if any error when calling device recovery.

**Comment by keyonghan** [comment]
Run locally from the bot, and it complains 
```
-bash: ideviceinstaller: command not found
```
Though we have appended `/opt/homebrew/bin:/opt/homebrew/sbin:` to the `PATH`, the current PATH in the bot is
```
echo $PATH
/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/salt/bin:/usr/local/sbin:/Library/Apple/usr/bin
```

**Comment by keyonghan** [comment]
New version lands in staging, and validated the recovery works.
