### ISSUE TITLE
flutter doctor can't find remote device nokia 3.4 connected with usb to debug with

### ISSUE THREAD

**Issue by noahsalvadordenjo** [flutter/flutter#98437]
chromeos Versie 98.0.4758.91 (Officiële build) (64-bits)
flutter version Flutter 2.11.0-0.0.pre.542
```
[✓] Flutter (Channel master, 2.11.0-0.0.pre.542, on Debian GNU/Linux 11 (bullseye) 5.4.163-17383-gbc0d0d65633b, locale en_US.UTF-8)
    • Flutter version 2.11.0-0.0.pre.542 at /home/noahbergh/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 1958656943 (22 hours ago), 2022-02-14 05:15:17 -0500
    • Engine revision b63614c306
    • Dart version 2.17.0 (build 2.17.0-104.0.dev)
    • DevTools version 2.10.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /home/noahbergh/Android/Sdk
    • Platform android-30, build-tools 32.1.0-rc1
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2021.1)
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] Connected device (1 available)
    • octopus (mobile) • emulator-5554 • android-x64 • Android 9 (API 28)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category
```

**Comment by danagbemava-nc** [comment]
Hi @noahsalvadordenjo, is the nokia device the only device that you have this issue with? 
Can you also check if you have enabled `usb debugging` in your `Developer options` on the nokia device?

**Comment by noahsalvadordenjo** [comment]
I dont have any other physical device but i will try to find one, for now the nokia device is my only option. if enabled usb debugging and changed the transport type to midi. now because of midi it sometimes finds the device as well but not always

**Comment by danagbemava-nc** [comment]
Hi @noahsalvadordenjo, what version of android is your device running and what USB modes are available to you?

**Comment by noahsalvadordenjo** [comment]
Android 11 and the usb modes available are file transfer, usb-tethering, midi, ptp and nothing

**Comment by danagbemava-nc** [comment]
Can you check if it works when you use the `nothing` mode? Also, do you have another USB cable you can check with? Sometimes if the USB cable isn't working properly, it becomes difficult to read the device.

**Comment by noahsalvadordenjo** [comment]
My computer is able now of finding my device thanks a lot i hop it will still find the device in the future as well

**Comment by danagbemava-nc** [comment]
Glad I could help. 

Closing based on https://github.com/flutter/flutter/issues/98437#issuecomment-1041797714. 

If you do get any more issues in the future, feel free to create a new one. 

Thank you

**Comment by noahsalvadordenjo** [comment]
Now it can't find my device again not event after a reboot

**Comment by danagbemava-nc** [comment]
Then this isn't an issue with `flutter doctor` or `flutter` for that matter. 

You need to check your connection to your system. You might need to replace your cable as well.
