### ISSUE TITLE
Shift flakey issue updates/notifications to Wednesday

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#98430]
I own a lot of tests, and would have more time to triage the notifications on Wednesday morning.

**Comment by keyonghan** [comment]
@zanderso does Tue. work for you? The metrics/slo review meeting is on Tue. afternoon, it would be helpful to know the flake status before the meeting.

**Comment by zanderso** [comment]
Can you explain that in some more detail? My understanding is that infra flake metrics and the day that the bot files issues should be orthogonal. Even if there is a dependence, the infra metrics will be out of sync for only one week.

For context, I have meetings all day Monday, and other triage work and meetings on Tuesday, so I'm proposing Wednesday because that's the most realistic time for me to go over the issues.

**Comment by keyonghan** [comment]
Thanks for the context! I am moving it to Wed, as mentioned, the async is not a big thing.

**Comment by zanderso** [comment]
Thanks!
