### ISSUE TITLE
Failed binding IPv4 listening socket: Address already in use (48) Engine creation error: Error Domain=com.apple.CoreHaptics Code=-4809

### ISSUE THREAD

**Issue by sadaqatdev** [flutter/flutter#98431]
Failed binding IPv4 listening socket: Address already in use (48) Engine creation error: Error Domain=com.apple.CoreHaptics Code=-4809

**Comment by sadaqatkarimi** [comment]
[✓] Flutter (Channel stable, 2.10.1, on Mac OS X 10.15.7 19H1615 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[!] Xcode - develop for iOS and macOS (Xcode 12.4)
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.64.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.

**Comment by darshankawar** [comment]
@sadaqatkarimi 
When you open an issue, please use the new issue template and fill out requested details, so that we'll have enough details to work with. Currently you just posted `flutter doctor` and error but that's not enough to analyze further.

When do you get this error ? provide entire verbose log in text format, `flutter doctor -v`, platform on which you are seeing this error along with exact steps to replicate this issue and a [minimal code sample.](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by sadaqatkarimi** [comment]
after upgrading flutter sdk from 1.22.6 to 2.10.1 , then get this error on ios 15.2.1

**Comment by sadaqatkarimi** [comment]
flutter doctor -v
[✓] Flutter (Channel stable, 2.10.1, on Mac OS X 10.15.7 19H1615 darwin-x64, locale en-GB)
    • Flutter version 2.10.1 at /Users/everythingapple/developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (7 days ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/everythingapple/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (2 available)
    • Sadaqat’s iPhone (mobile) • 890d48778e60263387e00cf13277c165448f3e6e • ios            • iOS 15.2.1 19C63
    • Chrome (web)              • chrome                                   • web-javascript • Google Chrome 98.0.4758.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
