### ISSUE TITLE
Install backtrace handlers on Windows on all unit-test runs.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#98432]
Today, we get [no backtraces](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8822275952465841889/+/u/test:_Host_Tests_for_host_debug_unopt/stdout) when tests fail on Windows. This is because the stub backtrace handler is being used on that platform. Installing the [real handler](https://github.com/flutter/engine/blob/6f4d644b8215e00e90f30d11aa829a2eac25ce15/fml/BUILD.gn#L104) (and fixing any Windows specific construction issues therein) would make failures on Windows more actionable.

**Comment by cbracken** [comment]
I believe this was done in flutter/engine#36202; taking a look.

**Comment by cbracken** [comment]
Looks like this was done. There are no windows-specific conditions around `enable_backtrace` any more. See: https://github.com/flutter/engine/blob/main/common/config.gni#L24 -- the remaining uses of this identifier are all general and not platform-specific.
