### ISSUE TITLE
Please create a branch in the flutter recipes

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#98449]
Please create a branch in the flutter recipes project using:

flutter branching commit: `a0abb7e89e1b5f2b5996110b523a66e56a774eb5`
branch name: `flutter-2.11-candidate.7`

Gardener instructions section

Use the date of the provided flutter commit to find the oldest commit in the
recipes repository whose creation date is less than or equal to the creation
date of the flutter commit. Please ensure there were no reverts after the
selected commit.

Once the commit has been identified run the following commands on a clean checkout
of the recipes folder:

* `git clone git checkout -b <branch name>`. Branch name will look like `flutter-2.8-candidate.16`
* `git reset --hard <commit>`.
* `git push origin <branch name>`

The next step is verify the [***testing_ref*** regex](https://flutter.googlesource.com/infra/+/refs/heads/main/config/lib/release_branches/branches.json#3) for beta|stable configurations match
the new branch. Failing to do this will prevent from running postsubmit builds.

The last step in the process is to update the engine and flutter infra configurations for the release channel(only needed for new beta|stable releases). You can run the following commands
to do that:

* `mkdir $HOME/infra_checkout && cd $HOME/infra_checkout`
* `git clone https://flutter.googlesource.com/infra && cd infra && git checkout -b configs`
* `alias generate_jspb="dart $HOME/flutter_checkouts/cocoon/app_dart/bin/generate_jspb.dart"`
* `generate_jspb <flutter|engine> <release_branch> > $HOME/infra_checkout/infra/config/generated/ci_yaml/<flutter|engine>_<beta|stable>_config.json`
* `./config/main.star`
* `git commit`
* `git push origin HEAD:refs/for/main`
* `Wait for the PR to be reviewed and submitted`

**Comment by godofredoc** [comment]
\cc @itsjustkevin FYI this is the bug to create a new branch, let's get the workflow tested.

**Comment by yusuf-goog** [comment]
Located commit here:
`git log a0abb7e89e1b5f2b5996110b523a66e56a774eb5`

Creation date is:
`Date:   Mon Jan 31 16:05:20 2022 -0500`

Searched through recipes commits here
https://flutter.googlesource.com/recipes/+log/refs/heads/main

Found oldest commit whose creation date is less than or equal to the creation
date of the flutter commit:
https://flutter.googlesource.com/recipes/+/4b5e5592b66e7ee9f7228bb2382e83b9c48aa510

Running commands:
`git checkout -b flutter-2.8-candidate.16`.  (NOTE: Removed `git clone` prefix, that seems in error)
`git reset --hard 4b5e5592b66e7ee9f7228bb2382e83b9c48aa510`
`git push origin flutter-2.8-candidate.16`

Getting the following error:
```
$ git push origin flutter-2.8-candidate.16
To https://flutter.googlesource.com/recipes
 ! [rejected]          flutter-2.8-candidate.16 -> flutter-2.8-candidate.16 (non-fast-forward)
error: failed to push some refs to 'https://flutter.googlesource.com/recipes'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

**Comment by godofredoc** [comment]
Those commands are part of the template. The branch name needs to be replaced with: `flutter-2.11-candidate.7` and the commit needs to be replaced with a good commit from recipes/main that is contemporary to `flutter/flutter/a0abb7e89e1b5f2b5996110b523a66e56a774eb5`

**Comment by yusuf-goog** [comment]
Fixed the branch name in the commands:
`git checkout -b flutter-2.11-candidate.7`
`git reset --hard 4b5e5592b66e7ee9f7228bb2382e83b9c48aa510`
`git push origin flutter-2.11-candidate.7`

I need permissions to push:
 ! [remote rejected]   flutter-2.11-candidate.7 -> flutter-2.11-candidate.7 (prohibited by Gerrit: not permitted: create)

**Comment by yusuf-goog** [comment]
Trying to create new branch via UI (https://flutter-review.googlesource.com/admin/repos/recipes,branches) also, throws a permissions error.

**Comment by yusuf-goog** [comment]
Permissions granted.

Created the branch `flutter-2.11-candidate.7` at `4b5e5592b66e7ee9f7228bb2382e83b9c48aa510` in the UI (https://flutter-review.googlesource.com/admin/repos/recipes,branches)

**Comment by yusuf-goog** [comment]
Manually verified that flutter-2.11-candidate.7 matches the beta branch regex here: https://flutter.googlesource.com/infra/+/refs/heads/main/config/lib/release_branches/branches.json#9

**Comment by yusuf-goog** [comment]
Since this is a beta release, updating the flutter and engine infra configs:
```
mkdir $HOME/infra_checkout && cd $HOME/infra_checkout
git clone https://flutter.googlesource.com/infra && cd infra && git checkout -b configs
alias generate_jspb="dart $HOME/flutter_checkouts/cocoon/app_dart/bin/generate_jspb.dart"
generate_jspb flutter flutter-2.11-candidate.7 > $HOME/infra_checkout/infra/config/generated/ci_yaml/flutter_beta_config.json

**Comment by yusuf-goog** [comment]
Some gotchas, make sure flutter/dart versions are as expected. Incorrect versions resulted in errors like:

```
../.pub-cache/hosted/pub.dartlang.org/github-8.5.0/lib/github.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.12.
export 'package:github/src/common.dart';
^
```

And when pushing the commit, if you get:
```missing Change-Id in message footer```
follow the instructions in the error message to install the hook and resubmit.

**Comment by yusuf-goog** [comment]
PR: https://flutter-review.googlesource.com/c/infra/+/26901

**Comment by yusuf-goog** [comment]
Would also be helpful to determine what the branch name is going to be and how to tell which type (beta, etc.) it is.

**Comment by yusuf-goog** [comment]
Note: once changes to ci.yaml were updated, running the process to update the engine and flutter infra configurations yielded no diffs, so the task is complete at this stage.

**Comment by godofredoc** [comment]
Just adding some more context:

We may want to refine the documentation for this kind of bugs as we needed several cherry picks to get the recipes for branch flutter-2.11-candidate.7 to a working state.

This is the list of additional cherrypicks:
* https://flutter-review.googlesource.com/c/recipes/+/27040
* https://flutter-review.googlesource.com/c/recipes/+/27081
* https://flutter-review.googlesource.com/c/recipes/+/27100
* https://flutter-review.googlesource.com/c/recipes/+/27101
* https://flutter-review.googlesource.com/c/recipes/+/27102

AI:
* Modify the docs to accept the target commit and the target branch as parameters
