### ISSUE TITLE
Problem with ImageProvider after upgraded to version 2.10 (or 2.8) if Paused App and then Resume it

### ISSUE THREAD

**Issue by csacchetti** [flutter/flutter#98444]
I have a problem with ImageProvider. Before I upgraded to version 2.10 (but it may be that the problem goes back to version 2.8) there was no problem whatsoever. After Yes. So I think this update has changed the handling, I think the caching, of these images.
I describe the problem scenario. 
I have the Home page that has some images (there are several in a DecorationImage list (with BorderRadius.circular) that naturally have an ImageProvider.
If I put the app in Pause and then do the Resume (this is very important because it is only by doing this before that the problem occurs) and then open an Image Page where all the images are contained and therefore also those in the Home, they are all shown except for those that are visible in the Home at that moment.
It seems that it assumes that these images are visible and does not reload them in the new page. Then naturally, by scrolling or doing various operations, they reappear. 
It seems to be a problem related to performance optimization, which avoids reloading images already on the screen, but in this case it does not recognize that a new page has been opened.
It should be noted that the problem only occurs if you first put the app in the background and then do the Resume.
Anyway, always, when I open for the first time the page with all the images, the ones that are visible in the Home are missing. If I try to change the images that are visible in the Home (scrolling the list with the images), the images that are not loaded in the Images Page also change, and they are exactly the ones that are now visible in the Home.
Of course before I upgraded to Flutter 2.10 (or maybe 2.8) with the exact same code, this problem was not there and everything worked correctly.
*** IMPORTANT*** The problem only occurs with AssetImage and not with FileImage. With NetworkImage and MemoryImage  I have not tried

**Comment by darshankawar** [comment]
@csacchetti 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with actual vs expected result you are looking for ?

Thanks.

**Comment by csacchetti** [comment]
Flutter doctor -v

[✓] Flutter (Channel stable, 2.10.1, on macOS 11.6 20G165 darwin-x64, locale it-IT)
    • Flutter version 2.10.1 at /Users/carlosacchetti/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (6 days ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/carlosacchetti/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Community Edition (version 2021.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (2 available)
    • iPhone  (mobile)  • ios            • iOS 14.7.1
      18G82
    • Chrome (web)          • chrome                    • web-javascript • Google Chrome
      98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by csacchetti** [comment]
For the example, it's tricky to extrapolate a small part from the app. The app is quite large. An example would need to be redone from scratch. 
Consider though that the same code doesn't have this problem before version 2.8 or 2.10. It was working perfectly before the update. 
What has changed in the handling of ImageProvider in either of these versions? This will definitely help us understand the problem better.

**Comment by darshankawar** [comment]
I see [this](https://docs.flutter.dev/release/breaking-changes/image-cache-and-provider) document link related to breaking changes for ImageProvider, but am not sure if this applies to your use case, but you can check and see if that's the case.

**Comment by csacchetti** [comment]
I am familiar with this document but for my knowledge it is not helpful.

**Comment by darshankawar** [comment]
@csacchetti 
How are you loading images ? Are you using loadingBuilder ? What's the size of the images that you are loading ? Are they big in size or regular size ? Having these details would be good to create a sample repro to verify this behavior.

**Comment by csacchetti** [comment]
I load image in this way:
```
                                   child: Container(
                                    decoration: BoxDecoration(
                                        borderRadius: BorderRadius.circular(
                                          myMethodProp(context, 10),
                                        ),
                                        image: DecorationImage(
                                          image: (widget.typeGridImage ==
                                                  TypeGridImage.editable
                                              ? FileImage(
                                                  File(p.join(
                                                      context
                                                          .read<ProviderPref>()
                                                          .pathDocumentsProv!,
                                                      myListImages[index]!
                                                          .path)),
                                                  scale: 1.0)
                                              : AssetImage(myListImages[index]!
                                                  .path!)) as ImageProvider,
                                          fit: BoxFit.cover,
                                        ),
                                      ),
```

The size of image are from 50 to 250 kb

the dimensions are different from 400 px to 1200 px

What makes me think that something has been changed in the flutter code, in my opinion on the cache management, is the fact that with the same code before it worked perfectly and after not.
Very important is also the fact that the problem occurs only after the app has been put in background (pause) and reactivated (resume).
Maybe the search for the change occurred with the update should be oriented also to the didChangeAppLifecycleState.

**Comment by darshankawar** [comment]
@csacchetti 
Please check [this](https://github.com/flutter/flutter/issues/80369) issue and [this](https://github.com/flutter/flutter/issues/95891#issuecomment-1009466794) issue comment and see if it's relatable with your use case.

**Comment by csacchetti** [comment]
I think that as you have already anticipated the problem is in these breaking changes  [https://docs.flutter.dev/release/breaking-changes/image-cache-and-provider](url)  but honestly I don't know what I have to change in my code for everything to return as before or at least not give me the problem anymore.

**Comment by csacchetti** [comment]
Or maybe it's simply a bug that occurs when you put the app in the background (pause) and bring it back active (resume). It may be that they didn't consider this situation in the change.

**Comment by csacchetti** [comment]
A workaround might be to reset the cache (of the AssetImages) when I resume  the app , but I don't know how to do that. If someone helps me I can do this test.

**Comment by csacchetti** [comment]
I tried to reproduce a simple example of the problem but the problem does not occur. The suspicion is that with updates of older versions  is not working. In fact the above problem is put in the breaking changes([https://docs.flutter.dev/release/breaking-changes/image-cache-and-provider). 
I say this because the simple example was done on a new project that was started with flutter already updated to version 2.10. While the problem remains in a project that was born long before version 2.10 and then was updated from time to time.
The thing that makes me suspect this is that while the old project updated with the same code requires cast "as ImageProvider<Object>", in the new project nothing is asked, even though there is the same code. This means that something underneath has changed and the two projects behave differently.
I wonder and I ask you if it is possible to move the files of my project to a new project, born with flutter 2.10 without having to rewrite everything?

**Comment by darshankawar** [comment]
> I wonder and I ask you if it is possible to move the files of my project to a new project, born with flutter 2.10 without having to rewrite everything?

Please check this [link](https://errorsfixing.com/recreate-flutters-ios-and-android-folder-with-swift-and-kotlin/) and see if it helps.

**Comment by csacchetti** [comment]
There is no way to avoid moving the whole app to a new project. Ok this breaking change (https://docs.flutter.dev/release/breaking-changes/image-cache-and-provider) but what is the alternative programming for those who don't have a new app?
Can anyone help me with this?

**Comment by csacchetti** [comment]
I want document with video the problem
The problem occurs in two situations. When scrolling through images, I go to background and then come back to scroll through images. The image that is selected at that moment (which is cached) disappears, then if I scroll back to active again it reappears and the problem doesn't occur anymore.

https://user-images.githubusercontent.com/46923349/155835970-4045826a-dbcd-4910-bbf3-d6e81685be39.mov


The second scenario is if I go to the background and then open a page where there are all the images, the ones that were visible in the first screen are not present (the two images that are missing are those that are visible in the first page and then in the cache. )


https://user-images.githubusercontent.com/46923349/155836189-62591371-89db-4dcb-b079-787bddf15935.mov

Of course if I scroll through everything it puts itself back in order. This happens the first time.
This shows that it is most likely the bracking mentioned in the link above. But I don't know how it can be solved.
This problem occurs in both iOS and Android
As I said before the upgrade everything was working perfectly so it's not a code issue

**Comment by darshankawar** [comment]
@csacchetti 
Thanks for further details and for your patience too on this. Looking at the videos you shared, I tried the same using `carousel_slider` [plugin](https://pub.dev/packages/carousel_slider) example and ran it on stable 2.10.2 but was unable to replicate the behavior.


https://user-images.githubusercontent.com/67046386/155931764-4a3343ab-a92f-4618-a97d-97521dff5ec0.mov

`Channel stable, 2.10.2`

I see that the images are trying to render again after coming back from background or tries to reload the image but it could be getting cached somehow.
This looks like a closer / similar issue that was fixed: https://github.com/flutter/flutter/issues/64558 Please go through that and see if any of the underlying comments helps.
Also, would be great if there's a minimal reproducible code sample as provided in the linked issue for proper analysis.

**Comment by csacchetti** [comment]
I've fixed it for the moment but in my opinion it remains a bug to fix. I'm not sure if it will be fixed in the 2.2.0 version next May.
In the meantime, however, I have solved in this way, I hope it can help others.

- The problem occurs with ImageProvider (AssetImage). But if you use Image.asset it doesn't show up. So this can be the first solution. Then if you wrap with ClipRRect you can add many functions like ImageProvider.

- Then if you are forced to use ImageProvider just replace AssetImage with ExactAssetImage. It has another function in itself, but in performing it it corrects this problem.

While waiting for this bug to be fixed you can use these two workarounds

**Comment by darshankawar** [comment]
@csacchetti 
Thanks for the feedback on this. Can you provide what exactly you fixed ?
I had tried to replicate it using `Image.network` but wasn't able to see the same behavior, which might indicate that there's more to it in order to replicate or debug further.



> * The problem occurs with ImageProvider (AssetImage). But if you use Image.asset it doesn't show up. So this can be the first solution. Then if you wrap with ClipRRect you can add many functions like ImageProvider.
> * Then if you are forced to use ImageProvider just replace AssetImage with ExactAssetImage. It has another function in itself, but in performing it it corrects this problem.

Is there a way to provide a code sample that includes this scenario ?

**Comment by csacchetti** [comment]
I'm at a loss to provide code because, as I said, my app is quite complex and if you make a simple example the problem doesn't arise. I think it's related to this issue though (#64558).
Probably when they made this change (https://docs.flutter.dev/release/breaking-changes/image-cache-and-provider) they didn't carefully consider what happens after the "resume" from background. I would suggest checking this out.
The fact that the code before goes and after doesn't simply by updating flutter, or changing AssetImage to Image.asset or ExactAssetImage is a sign that the problem is not in the code but in AssetImage. I hope I was clear and helpful

**Comment by darshankawar** [comment]
@csacchetti 
I would suggest you to also try the scenario using AssetImage on latest master to see if it persists on that version too.
