### ISSUE TITLE
Add a Dart api for Windows window messages

### ISSUE THREAD

**Issue by benthillerkus** [flutter/flutter#98456]
## Use case

On Windows, plugins can handle [window messages](https://en.wikipedia.org/wiki/Message_loop_in_Microsoft_Windows)[^1].
It would be good if these were accessible in Dart directly, without a custom plugin.

This would be useful in conjunction with the [`win32`](https://github.com/timsneath/win32) package, that allows you to interact with various Windows APIs without having to write a plugin and C++; which is great because that way you're able to use hot reload for example.
With *pure* Dart applications, you can manage the message event loop through `win32`, however with Flutter, it's managed by the windows runner[^2]. The runner then [forwards events to plugins](https://github.com/flutter/samples/blob/9720e2698b975454649f25ae583983f0c1db392c/desktop_photo_search/material/windows/runner/flutter_window.cpp#L44), but not to the Dart part of the Flutter app, even if no plugin can handle the message.

## Proposal

Flutter users should be able to handle window events without having to write plugins.

Such an API would allow users to define a handler function that, given the received code and parameters, should decide if it wants to handle the event and then act on it.

This functionality would fit well into the [flutter services library](https://api.flutter.dev/flutter/services/services-library.html), perhaps as a *`Win32WindowMessage`* wrapper on a  `MethodChannel` or something like that.

[^1]: For a concrete list of the different window messages, [here's the header file where they are defined](https://github.com/tpn/winsdk-10/blob/9b69fd26ac0c7d0b83d378dba01080e93349c2ed/Include/10.0.10240.0/um/WinUser.h#L1947)
[^2]: Here's someone who [already ran into this issue](https://github.com/timsneath/win32/discussions/197#discussioncomment-555710)

**Comment by stuartmorgan** [comment]
Window message handling returns a synchronous result, so it's not clear to me how you are proposing this work. There's no way to synchronously call into Dart.

**Comment by benthillerkus** [comment]
> Window message handling returns a synchronous result, so it's not clear to me how you are proposing this work. There's no way to synchronously call into Dart.

Maybe I'm misunderstanding your concerns, but why can't the message handling result just be copied and handled asynchronously in Dart?

Roughly like this:

1. A message is received in the flutter runner message queue
2. The runner tries to handle the message
3. The runner asks the registered plugins to handle the message
4. (new) The runner puts the message into a MethodChannel to Flutter
5. The next message can be handled
6. (asynchronous) At some point the Dart in the Flutter app receives the message from the method channel and can act on it.

I haven't looked at the code for that, but isn't Gamepad and Keyboard Input also forwarded from the OS into Dart? Wouldn't something similar to that work?

**Comment by benthillerkus** [comment]
My concrete use case is that I'm creating tray icons through win32 and want to be able to interact with them; for starters clicking on them should bring the app window into focus.
I can manipulate the window through win32, however to be notified that my icon was clicked, I'd need to be able to receive messages.

In practice, on the `NOTIFYICONDATA` struct you can specify a `uCallback`, which is typically a message type id like `WM_APP + 42`.
Inside a plugin you could then overload that MessageHandler function to deal with the `message == WM_APP + 42` case.

**Comment by maheshmnj** [comment]
Hi @benthillerkus, Thanks for filing the issue. Leaving this issue open for further insights from the team.

**Comment by stuartmorgan** [comment]
[wndProc](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nc-winuser-wndproc) is a synchronous function that returns a result.



> why can't the message handling result just be copied and handled asynchronously in Dart?

Handlers don't handle the result, handlers return the result. And they must do so synchronously. Consider the resize handler message, for instance, which must synchronously change values in order to do anything.

> Roughly like this:

You are missing a step where the code doing steps 1-4 must return a value indicating whether the message was handled, and in some cases synchronously change other values. Such, since it is synchronous, is before step 6 runs.

> I haven't looked at the code for that, but isn't Gamepad and Keyboard Input also forwarded from the OS into Dart? Wouldn't something similar to that work?

Only for messages where it's safe to unconditionally suppress them and then send new copies later. Not all messages work that way.

> Flutter users should be able to handle window events without having to write plugins.

Can you explain why a plugin that does the forwarding you describe--which anyone could use without having to rewrite it--wouldn't address your use case? Something that is both extremely platform-specific, and also will have caveats about which messages will and won't work, seems far better suited to a plugin.
