### ISSUE TITLE
Macbook M1 chip Flutter running on Android Studio Bumble Bee, Xcode 13.3.2 Beta - Fails firebase apps

### ISSUE THREAD

**Issue by maxelerate** [flutter/flutter#98461]
Hi All,

New Macbook M1 chip unable to compile Flutter Firebase simple applications.

I have tried several recommendations:
flutter clean
flutter pub get
cd ios
pod install
brew install cocoapods

 open podfile and update with this script

installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
end

1.Use Flutter ---> Tools---> Launch Xcode ios 

Build fails.

Please help,
Best Naveena
see failed build on Xcode

**Comment by maxelerate** [comment]
naveena@NaveenawamysAir rsvp % flutter doctor -v 
[✓] Flutter (Channel stable, 2.10.1, on macOS 12.0.1 21A559 darwin-arm, locale en-US)
    • Flutter version 2.10.1 at /Users/naveena/flutterTools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (5 days ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/naveena/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/naveena/Library/Android/sdk
    • Java binary at: /Users/naveena/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8139111/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] Android Studio (version 2021.1)
    • Android Studio at /Users/naveena/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8139111/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.64.0)
    • VS Code at /Users/naveena/Downloads/Jan2022/Visual Studio Code-2.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] VS Code (version 1.64.0)
    • VS Code at /Users/naveena/Downloads/Jan2022/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
naveena@NaveenawamysAir rsvp %

**Comment by maxelerate** [comment]
[✓] Flutter (Channel stable, 2.10.1, on macOS 12.0.1 21A559 darwin-arm, locale en-US)
   Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

• All Android licenses accepted.
  • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
[✓] Android Studio (version 2021.1)
[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by maxelerate** [comment]
flutter devices
2 connected devices:

iPhone 13 (mobile) • 89DAEDA3-ED05-4DAF-BCB1-939D09DE8E63 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)

**Comment by darshankawar** [comment]
@maxelerate 
firebase related issues are tracked here: https://github.com/FirebaseExtended/flutterfire/issues so please file the issue there by using the new issue template and fill out all requested details.
Closing from here.
