### ISSUE TITLE
Flutter Shader Mask Bounds Height off by a Pixel

### ISSUE THREAD

**Issue by kornha** [flutter/flutter#98464]
Image of error:

<img width="873" alt="image" src="https://user-images.githubusercontent.com/5386694/153984022-8e2f1e3c-7423-48c2-8993-e5355ace854b.png">

Notice the line at the top where the bounds should be.

Code to reproduce:

 ```
 Widget build(BuildContext context) {
    return BlockContainer(
      //Need to set height to set constraints on parallax image
      child: Container(
        height: 300,
        child: Stack(
          children: [
            _buildParallaxBackground(context),
            ShaderMask(
              blendMode: BlendMode.srcOut,
              shaderCallback: (bounds) =>
                  const LinearGradient(colors: [Colors.black], stops: [0.0])
                      .createShader(bounds),
              child: Center(
                child: Text(
                  "Hello, World!",
                  style: context.handwriting
                      .copyWith(fontSize: context.isMobile ? 60 : 100),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
```
Parallax background can be changed with another background, taken from Flutter website.

Issue found in 2.10.1

**Comment by danagbemava-nc** [comment]
Hi @kornha, can you provide the definition for the `BlockContainer` and `_buildParallaxBackground`? 

Better still, please provide a complete minimal reproducible code sample. 

Also, what platforms are you experiencing this issue on? 

The output of `flutter doctor -v` as well will also be helpful.

**Comment by kornha** [comment]
If it's unclear from here I can try and wrap a simpler code example to reproduce

**Comment by danagbemava-nc** [comment]
> I can try and wrap a simpler code example to reproduce

I would appreciate it if you could do this. In most cases, the simpler the example, the easier it is for the team to find out the root cause and how to fix it.
