### ISSUE TITLE
[Android] The flutter engine restarts the MainActivity when app moved to background

### ISSUE THREAD

**Issue by CalvinKai** [flutter/flutter#98478]
I use MethodChannel to start a new native activity named SecondActivity from flutter, and my MainActivity's launch mode is singleTask.When I push home button to set my flutter app to background and then click the icon to make it foreground,
I found the new started SecondActivity is destroyed and MainActivity is resumed. The log shows that the lifecycle method 
"onNewIntent" of MainActivity is touched. So it seems that when I turned the app into background, the flutter engine
will restart the MainActivity, so the activities in the stack which above of the MainActivity will all destroyed. Is that right and how to avoid this problem?

This is the Manifest file of my MainActivity:

**Comment by CalvinKai** [comment]
<activity
            android:name=".MainActivity"
            android:launchMode="singleTask"

            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>

**Comment by maheshmnj** [comment]
Hi @CalvinKai, Thanks for filing the issue. 

> I found the new started SecondActivity is destroyed and MainActivity is resumed. The log shows that the lifecycle method
"onNewIntent" of MainActivity is touched. So it seems that when I turned the app into background, the flutter engine
will restart the MainActivity, so the activities in the stack which above of the MainActivity will all destroyed. Is that right and how to avoid this problem?

Leaving this issue open for further insights from the team.

**Comment by CalvinKai** [comment]
> Leaving this issue open for further insights from the team

Thanks a lot ! Please let me know if there is any progress.

**Comment by chinmaygarde** [comment]
This seems working as intended. I would redirect this question to another channel like Discord or StackOverflow.
