### ISSUE TITLE
Plugin local_auth - Unable to choose type of biometric to use

### ISSUE THREAD

**Issue by hasinadevelop** [flutter/flutter#98480]
It would be possible to add a feature where you could choose the type of biometric to use?

**Comment by danagbemava-nc** [comment]
Hi @hasinadevelop, AFAIK at the moment, the underlying android API doesn't provide a way to select the specific biometric type to use, so the plugin cannot do that either. 

iOS on the other hand, at the moment, only has 1 type of biometric option per device at the moment, so the likelihood of them surfacing an API to choose the type of biometric to use is likely low. 

I'm going to close this issue for now, but feel free to open a new issue requesting this feature when the underlying platforms provide a way to implement this feature natively. 

Thank you
