### ISSUE TITLE
Remove `clipBehavior == Clip.none` conditions from widgets

### ISSUE THREAD

**Issue by TahaTesser** [flutter/flutter#98487]
https://github.com/flutter/flutter/pull/95593 made `Clip.none`a valid clipBehavior

So this means we no longer need to have `clipBehavior == Clip.none` condition in the code.

### Example

https://github.com/flutter/flutter/blob/d6d3283c8d7afe31dd0b613ac9b3e1f8d80d16b9/packages/flutter/lib/src/cupertino/form_section.dart#L294-L303

I've found the following widgets use this condition
- `Material`
- `CupertinoFormSection`
- `InteractiveViewer`

Context
https://github.com/flutter/flutter/pull/98252
https://github.com/flutter/flutter/issues/98483

**Comment by TahaTesser** [comment]
@nt4f04uNd 
I could only find this three widgets with this type of condition, if you notice any other ones, feel free to  comment 
Also, the docs already cover `Clip.none` behavior and since we're removing conditions we don't need to add docs about the preserving state?

**Comment by nt4f04uNd** [comment]
> Also, the docs already cover Clip.none behavior and since we're removing conditions we don't need to add docs about the preserving state?

Yeah, I think so
