### ISSUE TITLE
Color spaces in flutter

### ISSUE THREAD

**Issue by Fnalsk** [flutter/flutter#98491]
## Use case
I released a photo sharing app, and some professional photographers have asked about offering a wider color space than sRGB. I wasn't able to find documentation anywhere about whether flutter supports wider color spaces when displaying images, and if so, how to use those color spaces.

I'm assuming that simply displaying images through an `ImageProvider` uses the sRGB color space, though I could be wrong on this - if so please clarify. 

## Proposal
Provide some way to display images through a different color space such as Adobe RGB or ProPhoto RGB. If this doesn't yet exist in flutter, this is probably quite a large amount of work to implement correctly based on my limited knowledge of color spaces.

**Comment by darshankawar** [comment]
@Fnalsk 
Currently, the color is rendered using sRGB and ARGB format: https://api.flutter.dev/flutter/dart-ui/Color-class.html.
Can you provide us a code sample or an example wherein the current format is a limitation and what kind of image quality or color are you looking to have in the framework ?

**Comment by Fnalsk** [comment]
Just use any `ImageProvider` object to display an image. For example, try `FileImage(image)`. This shows the image rendered with sRGB, as per your link.

I did suggest what kinds of color spaces would ideally be made available - Adobe RGB or ProPhoto RGB.

There aren't really any code samples I can give...this is as simple as it gets with regards to an explanation of the potential feature.

**Comment by darshankawar** [comment]
@Fnalsk 
Thanks for the update. Have you already checked if there's any community plugin / package that offers this ?
I Just tried https://pub.dev/packages?q=RGB and saw quite a few plugins offering various color formats that can probably help your case.

**Comment by Fnalsk** [comment]
These aren't what I'm looking for.

These packages provide a way to convert between color space *representations* using colors other than red, green, blue. But they have nothing to do with how with the space itself actually is.

**Comment by darshankawar** [comment]
Please check [this](https://github.com/flutter/flutter/issues/55092) issue and see if it's related / similar to your use case.

**Comment by Fnalsk** [comment]
That issue is what I was looking for. But it seems its been open for a year and a half? Is it being worked on?

**Comment by darshankawar** [comment]
It has P4 priority label. You can check here what each priority label means and to get an idea as how Flutter approaches these type of labels. https://github.com/flutter/flutter/wiki/Issue-hygiene#priorities

With that said, I am going ahead and closing this as a duplicate. Please follow-up in it for further updates.
