### ISSUE TITLE
[Image_Picker 0.8.4+1] [IOS]

### ISSUE THREAD

**Issue by officialFlutterDeveloper** [flutter/flutter#98496]
`Camera] Failed to read exposureBiasesByMode dictionary: Error Domain=NSCocoaErrorDomain Code=4864 "*** -[NSKeyedUnarchiver _initForReadingFromData:error:throwLegacyExceptions:]: data is NULL`

I keep getting the above issue can anyone help me?

**Comment by darshankawar** [comment]
Closing this as duplicate of https://github.com/flutter/flutter/issues/79942
