### ISSUE TITLE
Enter data using keyboard (automation)

### ISSUE THREAD

**Issue by dlyusko** [flutter/flutter#98499]
Hello!
Is it possible to add keyboard support for flutter to have possibility to enter data from keyboard not through "element.sendKeys"? (Test automation)

PS: I described my problem [here](https://github.com/appium-userland/appium-flutter-driver/issues/247). 
<img width="1227" alt="Screenshot 2022-02-15 at 16 30 11" src="https://user-images.githubusercontent.com/84774025/154071927-804d9023-e06e-4bfc-b890-bbd4ee423035.png">

**Comment by maheshmnj** [comment]
Hi @dlyusko, Thanks for filing the issue.  If I understand correctly you are not able to enter text into the Textfield during the appium tests, is that correct? By "keyboard" do you mean the "physical keyboard" or the soft keyboard?
