### ISSUE TITLE
Icons.keyboard_command_key_outlined missing from Icons class

### ISSUE THREAD

**Issue by visign3d** [flutter/flutter#98497]
![image](https://user-images.githubusercontent.com/25665922/154070358-736914e0-33df-4d32-b950-993efc97ebd8.png)

![image](https://user-images.githubusercontent.com/25665922/154070234-65d14686-9789-4ae9-9f89-1f9e3a7533b2.png)

**Comment by danagbemava-nc** [comment]
Hi @visign3d, please provide the output of `flutter doctor -v`. 

Thank you

**Comment by visign3d** [comment]
`
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19043.1526], locale hu-HU)
    • Flutter version 2.8.1 at C:\Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (9 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\vikto\AppData\Local\Android\sdk
    • Platform android-31, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.62.0)
    • VS Code at C:\Users\vikto\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.27.0

[√] VS Code, 32-bit edition (version 1.32.3)
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    • Flutter extension version 3.27.0

[√] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 98.0.4758.82
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 98.0.1108.43

• No issues found!

`

**Comment by danagbemava-nc** [comment]
Hi @visign3d, you are on an older version of flutter. 

These icons are available on `stable 2.10+`, but there is an issue on the stable channel with how these new icons are rendered. That has already been reported in https://github.com/flutter/flutter/issues/97767 and there's a request for it to hotfixed into the new stable version. Kindly follow up in https://github.com/flutter/flutter/issues/97767 for more details. 

Closing from here as duplicate. 

Thank you
