### ISSUE TITLE
Make viewport width adjustable for tabView

### ISSUE THREAD

**Issue by Hari-07** [flutter/flutter#98506]
## Use case

If there's a pageview design, with a smaller viewport fraction than 1, but also having swipeable tabs for quickly accessing a later page, currently a complex arrangement with a pageview and tabview and the controllers listening to each other and making sure the animations are in sync is required

## Proposal

By simply making the viewport width an optional parameter on TabView, that defaults to 1, this sort of design is made much easier

**Comment by maheshmnj** [comment]
Hi @Hari-07, Thanks for filing the issue. I am quite not sure I understand the proposal completely could you please share a sample code that explains your use case?

**Comment by Hari-07** [comment]
Consider a Design Like this:

<img src="https://user-images.githubusercontent.com/22373191/154239808-bc890dc6-9b9f-4064-a3c2-3ea2e66d07ab.png" width="300">

With the current implementation, atleast to the best of my knowledge only way to do it is to either make my own tabbar, or use a tabbar and a pageview and write code to keep the controllers in sync. Since its not just a matter of indices and animations etc need to stay in sync it would require a non trivial amount of code

With the new change we can simply use a TabBar and TabBarView with a viewportFraction as a parameter.

I've written the code for it in https://gist.github.com/Hari-07/66ac2c2f68d18f28672f925536175c39
Pleas note that the ProposedImplementation in the gist will only work if you check out PR #98512

**Comment by maheshmnj** [comment]
Thanks for the info @Hari-07, That looks like a valid proposal to me.

https://user-images.githubusercontent.com/31410839/154264794-190edbe7-8185-403d-bd78-7782dec06216.mov
