### ISSUE TITLE
Ink responses are broken in Android

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#9851]
Buttons and other Ink-based widgets flicker on tap when using Android on a device or in the emulator.

This is the code to reproduce this issue:

```dart
@override
  Widget build(BuildContext context) {
    return new Material(
      color: new Color(0xFFFFFFFF),
      child: new Center(
        child: new FlatButton(
          onPressed: () {},
          child: new Text("MY BUTTON"),
        ),
      ),
    );
  }
```

[Sample Video (zip)](https://github.com/flutter/flutter/files/980459/button_issue.zip)

**Comment by Hixie** [comment]
cc @jason-simmons maybe fall-out from PhysicalModel?

**Comment by lukef** [comment]
I heard there is an issue with first time animations (i couldn’t find it sorry), but wanted to report that if you trigger a route animation then the button will function correctly **after** the first route animation completes unsuccessfully.

**Comment by eseidelGoogle** [comment]
The first-time animation issue I believe is https://github.com/flutter/flutter/issues/5363 which @chinmaygarde is working on currently.  Not sure if that's related to this or not.

**Comment by eseidelGoogle** [comment]
I posted your video on YT as well: https://youtu.be/NFmRqhQujIg

**Comment by eseidelGoogle** [comment]
This does seem likely to be related to physical modal layer.  Thoughts @jason-simmons?

**Comment by Hixie** [comment]
Can you confirm this still happens? We have not been able to reproduce it.

**Comment by lukef** [comment]
This appears to be fixed. Thanks.
