### ISSUE TITLE
[iOS] After using Non-matching face the "Try Face ID again" button does nothing.

### ISSUE THREAD

**Issue by carman247** [flutter/flutter#98515]
Just like the title says, after presenting a non-matching face on iOS the user is presented with a dialog and the "Try Face ID Again" button doesn't do anything.

I'm guessing it wouldn't because it hasn't been setup that way ... Maybe this dialog could be customised or removed completely? I don't know.

![Screenshot 2022-02-15 at 17 22 51](https://user-images.githubusercontent.com/31341463/154104463-e2e6877a-7e34-4fd9-9832-be29bd5f15e4.png)

**Comment by darshankawar** [comment]
@carman247 
If you look at [this](https://github.com/flutter/flutter/issues/96390) similar issue, the actual result is that if FaceId is not recognized, it doesn't fallback on passcode, which it ideally should, but currently it seems to be showing `Face not recogized`. 

Do you get the `Face not recognized` error as well, or are you getting some other behavior ?
You can try the plugin example and see the behavior matches with the linked issue or not.

**Comment by carman247** [comment]
@darshankawar I'm using a simulator and I've just discovered that after tapping "Try Face ID Again" you have to select **Features > Face ID > Non-matching Face / Matching Face**. Only then does it try again. I imagine it happens instantly on a real device.

You're right thought. It doesn't fallback on the passcode. However it did on one occasion after several attempts, but it wasn't automatic and I needed to call `localAuth.authenticate` again.

I'm not sure why it presented the passcode screen because it doesn't seem to be doing again.

I guess it's ok to close this issue as [this](https://github.com/flutter/flutter/issues/96390) is really the problem.

**Comment by carman247** [comment]
That being said, I think the sequence required to show the passcode screen while using a "simulator" is

**"Face ID" > Non-matching Face >  "Face Not Recognised" > Non-matching Face > Try Face ID Again > Non-matching Face > "Enter passcode for ..."**

Simply using "Non-matching face" after the "Face Not Recognised" message results in the "Face not recognised" error. You have to select it before AND aftre "Face Not Recognised" and then the passcode prompt is shown automatically.
