### ISSUE TITLE
[flutter_tools] Breaking changes in package:archive v3.2.0

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#98536]
In https://github.com/flutter/flutter/pull/98513, the tool tried to update package:archive from 3.1.11 -> 3.2.0, picking up the commit: https://github.com/brendan-duncan/archive/commit/e9955c37227834e4367e750e3649d34e36ddb747. However, this lead to several [analysis failures](https://cirrus-ci.com/task/6734364489809920) and even a test failure: https://cirrus-ci.com/task/6224191094521856.

This will be a breaking change as it will affect package:integration_test and package:flutter_driver.

To unblock PR #98513, the package will be pinned. This issue is to track writing a breaking change announcement, un-pinning the package, rolling, and making the flutter_tools changes.

**Comment by christopherfujino** [comment]
cc @zanderso

**Comment by zanderso** [comment]
@christopherfujino Can you connect the dots for me a little bit more in terms of how this affects users of `package:integration_test` and `package:flutter_driver`. It doesn't look like the analysis failures or test failures point to the issues with those packages.

**Comment by christopherfujino** [comment]
> @christopherfujino Can you connect the dots for me a little bit more in terms of how this affects users of `package:integration_test` and `package:flutter_driver`. It doesn't look like the analysis failures or test failures point to the issues with those packages.

If I am a customer with a Flutter app `foo` that depends on `package:archive` 3.1.11 and also `package:integration_test`, when I upgrade to the Flutter SDK version that has the `package:archive` roll, my app `foo` will also be upgraded to `package:archive` version 3.2.0, potentially causing my `foo` app code to break.

**Comment by zanderso** [comment]
Got it. Please correct me if I'm misreading, but it looks like this change did not break the customer_testing shard. In that case, following the process [on the wiki](https://github.com/flutter/flutter/wiki/Tree-hygiene#1-determine-if-your-change-is-a-breaking-change), all that is needed is tagging this issue with `severe: API break label`, and an announcement sent to flutter-announce@ that says, roughly:

> As part of the regular process of updating Flutter's dependencies, we are upgrading our dependence on `package:archive` from version 3.1.11 to version 3.2.0. This upgrade is necessary to bring in new versions of packages `vm_service`, `dds`, `dwds`, and `coverage`, which will improve the Flutter developer experience. This upgrade entails a breaking API change in `package:archive` described in detail in [this commit](https://github.com/brendan-duncan/archive/commit/e9955c37227834e4367e750e3649d34e36ddb747), and noted in the comment [here](https://github.com/brendan-duncan/archive/commit/e9955c37227834e4367e750e3649d34e36ddb747#r66762439). This change will affect Flutter apps that depend directly on `package:archive`, or which depend on it indirectly through `package:integration_test` or `package:flutter_driver`. Running `flutter analyze` on your app will flag locations that require updates. Apologies for any inconvenience.

**Comment by christopherfujino** [comment]
> Got it. Please correct me if I'm misreading, but it looks like this change did not break the customer_testing shard. In that case, following the process [on the wiki](https://github.com/flutter/flutter/wiki/Tree-hygiene#1-determine-if-your-change-is-a-breaking-change), all that is needed is tagging this issue with `severe: API break label`, and an announcement sent to flutter-announce@ that says, roughly:
> 
> > As part of the regular process of updating Flutter's dependencies, we are upgrading our dependence on `package:archive` from version 3.1.11 to version 3.2.0. This upgrade is necessary to bring in new versions of packages `vm_service`, `dds`, `dwds`, and `coverage`, which will improve the Flutter developer experience. This upgrade entails a breaking API change in `package:archive` described in detail in [this commit](https://github.com/brendan-duncan/archive/commit/e9955c37227834e4367e750e3649d34e36ddb747), and noted in the comment [here](https://github.com/brendan-duncan/archive/commit/e9955c37227834e4367e750e3649d34e36ddb747#r66762439). This change will affect Flutter apps that depend directly on `package:archive`, or which depend on it indirectly through `package:integration_test` or `package:flutter_driver`. Running `flutter analyze` on your app will flag locations that require updates. Apologies for any inconvenience.

Sounds good to me. I can send that email after rolling the package.

**Comment by christopherfujino** [comment]
This was rolled forward
