### ISSUE TITLE
Shared Preference values set in Flutter are not Accessible in Native Platform and Vice Versa

### ISSUE THREAD

**Issue by andrewalexanderbalogh** [flutter/flutter#98538]
Using Plugin
[shared_preferences](https://pub.dev/packages/shared_preferences) version 2.0.12

Expectation:
- Shared preference values set in Flutter should be accessible in Platform Native code
- Shared preference values set in Platform Native code should be accessible in Flutter

Reproduce:
1. Setup basic Platform Specific code using Platform channels as noted in example
[Calling platform-specific iOS and Android code using platform channels](https://docs.flutter.dev/development/platform-integration/platform-channels#example)

2. In the Android Code within the `MainActivity` Class, in the `configureFlutterEngine` function have
```kt
val sharedPreferences = PreferenceManager.getDefaultSharedPreferences(applicationContext)

with(sharedPreferences.edit()) {
    putInt("intFromAndroid", 82)
    apply()
}

val intFromFlutter = sharedPreferences.getInt("intFromFlutter", -1)
val intFromAndroid =  sharedPreferences.getInt("intFromAndroid", -1)
```

3. In the iOS Code within the `application(_:didFinishLaunchingWithOptions:)`  function have
```swift
UserDefaults.standard.setValue(23, forKey: "intFromIos")

let intFromFlutter = UserDefaults.standard.integer(forKey: "intFromFlutter")
let intFromIos = UserDefaults.standard.integer(forKey: "intFromIos")
```

4. In the Flutter/Dart code, within the `_getBatteryLevel()` function have
```dart
final prefs = await SharedPreferences.getInstance();
await prefs.setInt('intFromFlutter', 37);

final int? intFromAndroid = prefs.getInt('intFromAndroid');
final int? intFromIos = prefs.getInt('intFromIos');
```

Running the code then, I observe that;
- In Flutter/Dart code, `intFromIos` and `intFromAndroid` never return values. Only `intFromFlutter` will return a value
- In Android code, `intFromFlutter` never returns a value. Only `intFromAndroid` will return a value
- In iOS code, `intFromFlutter` never returns a value. Only `intFromIos` will return a value

**Comment by maheshmnj** [comment]
HI @andrewalexanderbalogh, could you please check this SO answer and see if this helps resolve your issue https://stackoverflow.com/a/56992844/8253662

Also, note that flutter stores its values on the Android Side with this name ["FlutterSharedPreferences"](https://github.com/flutter/plugins/blob/136f49b3e8ec8f96e222a71f17b32a16e9e3e649/packages/shared_preferences/shared_preferences_android/android/src/main/java/io/flutter/plugins/sharedpreferences/MethodCallHandlerImpl.java#L37)

**Comment by bagintz** [comment]
@maheshmnj do you know the flutter team would be open to a PR that allowed you to override the 
 `SHARED_PREFERENCES_NAME = "FlutterSharedPreferences"` value with our own?  That way we know for sure we can use the solution in the SO link above even if the package owners change this value in the package.

**Comment by maheshmnj** [comment]
@bagintz contributions are always welcome, For this case, I am quite not sure if that's a reasonable change. Probably you should discuss this on the discord with the appropriate team members or file a new issue with your proposal explaining the reasoning or the use case.
