### ISSUE TITLE
Remove unused parameter in hero code

### ISSUE THREAD

**Issue by mateusfccp** [flutter/flutter#98548]
The method `_startHeroTransition`, from `HeroController`, receives an `Animation<double> animation`, but does nothing with it.

**Comment by maheshmnj** [comment]
Hi @mateusfccp, Thanks for filing the issue. I can see the animation variable is not being used once the value is assigned

https://github.com/flutter/flutter/blob/9514106108d1be5e6ece944b3981b1c41111fcf9/packages/flutter/lib/src/widgets/heroes.dart#L896
