### ISSUE TITLE
Delete flutter/web_installers repo

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#98552]
The code provided by this repo is only used by one customer ([probably just this](https://github.com/flutter/engine/blob/476ed30ddc10d111d52a7c4ae84fc9584a62e83b/lib/web_ui/pubspec.yaml#L26)). Some of it is not used at all (see e.g. https://github.com/flutter/flutter/pull/97466/files removing a dependency on this repo). We should just inline the remaining useful functionality into the code that uses it and delete this repo.

**Comment by ahmednfwela** [comment]
I think it's a very useful repo for running integration tests on web

**Comment by yjbanov** [comment]
The repo has been archived. @ahmednfwela, feel free to steal the code. It's open-source! :)
