### ISSUE TITLE
Because flutter_tools depends on test any which doesn't exist (could not find package test at http://storage.flutter-io.cn), version solving failed.

### ISSUE THREAD

**Issue by hoodyicon** [flutter/flutter#98556]
C:\Users\mccar>flutter doctor
Flutter assets will be downloaded from http://storage.flutter-io.cn. Make sure you trust this source!
Because flutter_tools depends on test any which doesn't exist (could not find package test at http://storage.flutter-io.cn), version solving failed.
pub get failed (server unavailable) -- attempting retry 1 in 1 second...
Running "flutter pub get" in flutter_tools...

**Comment by maheshmnj** [comment]
Hi @hoodyicon, Thanks for filing the issue. It looks like you this issue is caused due to the Chinese firewall. could you please try the solution mentioned here https://github.com/flutter/flutter/issues/20809#issuecomment-414550239
