### ISSUE TITLE
Document how to use the software rendering backend on emulators.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#9856]
Currently, the software backend is only wired up on iOS simulators. According to @yjbanov, having a software backend on Android would help in wiring up the testing infrastructure on the bots.

**Comment by chinmaygarde** [comment]
Fixed by https://github.com/flutter/engine/pull/3719

**Comment by yjbanov** [comment]
Please, provide instructions for how to use it. Documenting them in this bug is good enough. I'll think of a more permanent place for them.

**Comment by zoeyfan** [comment]
@chinmaygarde I am triaging our bug database, and noticed this issue from 2017. Is this still relevant? Are we planning to do anything about it? If not, can we close it?

**Comment by yjbanov** [comment]
FWIW, it's no longer interesting to me.
