### ISSUE TITLE
[image_picker][iOS]: Sometimes plugin doesn't respond when picking an image from gallery.

### ISSUE THREAD

**Issue by mink-lparrouy** [flutter/flutter#98569]
Hi there,

I use the package image_picker (0.8.4 + 8) in my application in order to pick image from gallery. With a real iOS device (iOS 14) sometimes it doesn't work especially with image download from [unsplash](https://unsplash.com/). No error log are displayed.

`final granted = await \_handlePermission(context, [Permission.photos, if (Platform.isIOS) Permission.storage,]);
if (granted) {
await imagePicker.pickImage(source: ImageSource.gallery)
.catchError((Object o) {
print("Gallery error -- $o");
})
.then((file) => Navigator.of(context).pop(file));
}`
                                            
I followed every steps of the integration of the package. 
Do you know what happened ?

Thanks

**Comment by darshankawar** [comment]
@mink-lparrouy 
I tried the plugin [example](https://github.com/flutter/plugins/tree/main/packages/image_picker/image_picker/example) and ran it on iPhone 6s (OS 14.4.1), downloaded one image from `unsplash` and saved it in `images`, then using both types of photos permission, I was able to select the downloaded image which displays properly as below:


https://user-images.githubusercontent.com/67046386/154248249-6864f9db-8dc8-47e7-aaa5-2ac86668e387.MP4


Can you try the same example and see if you still get same behavior or not ?

**Comment by mink-lparrouy** [comment]
@darshankawar I tried the package example and it's the same behavior that in my application. I try to pick a picture it does not respond and i try again and I have an error that tell it cancel my first attempt which is normal.

The link to the picture that I used : https://unsplash.com/photos/6UEyVsw_1lU

And the video of my attempt.

https://user-images.githubusercontent.com/22906662/154251324-26e6f855-fc7c-4cc2-a58e-d6ed948a864e.mp4

**Comment by darshankawar** [comment]
I tried using the same image and it worked without any issues:

<img width="347" alt="Screenshot 2022-02-16 at 6 39 42 PM" src="https://user-images.githubusercontent.com/67046386/154271309-d4238279-8dc6-4228-a826-6f1c316fb0c5.png">


Can you provide your `flutter doctor -v` ?  Are you using M1 ?

**Comment by mink-lparrouy** [comment]
I am not using M1, I have a macbook pro form 2019.

The result of flutter doctor -v :

[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale fr-FR)
    • Flutter version 2.8.1 at /Users/louisparrouy/Documents/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (9 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/louisparrouy/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Connected device (3 available)
    • Pixel 5 (mobile) • 0A011FDD4004EV • android-arm64  • Android 12 (API 31)
    • macOS (desktop)  • macos          • darwin-x64     • macOS 12.1 21C52 darwin-x64
    • Chrome (web)     • chrome         • web-javascript • Google Chrome 98.0.4758.102

• No issues found!

**Comment by mink-lparrouy** [comment]
I upgrade Flutter to version 2.10.1 but the issue is still here unfortunately.

**Comment by darshankawar** [comment]
@mink-lparrouy 
This is strange. Can you confirm if the image you download from `unsplash` is in jpeg / jpg format or in any other format ?
Does the use case work for any other images you try to select from gallery or from other domain ?

**Comment by mink-lparrouy** [comment]
@darshankawar The format of the image is JPEG. I can pick other images yes, but with few images it doesn't work. The strange part is I have no error, I wait for a response that never arrived.

**Comment by darshankawar** [comment]
@mink-lparrouy 
Thanks for the details. Just one more test before I could go ahead and label it. Can you check if this is specific to the current plugin version or happens with previous plugin versions too ?

**Comment by mink-lparrouy** [comment]
@darshankawar I had this problem with a previous version of image_picker (0.8.4 +4). Thanks.

**Comment by darshankawar** [comment]
Thanks. I am going to label it for further insights as I am unable to replicate this behavior even after using more or less same config / devices. Also, per author, there's no error triggered if the image is not selected, for which this issue could be helpful once implemented: https://github.com/flutter/flutter/issues/95268

The images being picked are jpeg as stated earlier from `Unsplash` domain for example but works using other images.
Also, there are similar reports like below but they are specific to iOS simulator and trying to pick a specific image from simulator's gallery, which isn't the case here. For example: https://github.com/flutter/flutter/issues/82602

**Comment by AlonsoIbarra** [comment]
That appens to me too with an WEBP image.

**Comment by wellsysworld** [comment]
@darshankawar I've just had this issue using the Xcode simulator (iPhone 13, IOS 15.2). None of the test images in the simulator would load. I've also used the simulator to download a JPEG to make sure the image format was correct.

I've not made any changes to the app code for a few months. I was originally using plugin version 0.8.4+3 and tried updating to 0.8.4+9 but neither work.

After picking an image from the gallery, I went back in and tried to pick another and this was output to the VScode terminal:

[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: PlatformException(multiple_request, Cancelled by a second request, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
<asynchronous suspension>
#2      MethodChannelImagePicker.getImage (package:image_picker_platform_interface/src/method_channel/method_channel_image_picker.dart:188:20)
<asynchronous suspension>
#3      RegisterState.build.<anonymous closure> (package:XXX/pages/register.dart:337:51)
<asynchronous suspension>

I am on a M1 macbook and when it was working it was on a older Intel one.

Let me know if you need any more info?

**Comment by darshankawar** [comment]
@mink-lparrouy 
You probably are hitting https://github.com/flutter/flutter/issues/82602

**Comment by wellsysworld** [comment]
@darshankawar - yes, works for me on a real device, thanks!

**Comment by mink-lparrouy** [comment]
@darshankawar Yes I have the same error because the first attempt to select an image doesn't work so it cancelled the second request. For me it happened to a real device not on a simulator and I have not a M1. But it seems to be the same bug. Will the team look into it ?

**Comment by AlonsoIbarra** [comment]
Hello, that's happening to me too. I was loading an image downladed from web and the app creashes.
This is the log.
[+88429 ms] Process 2108 stopped
[   +3 ms] * thread #1, queue = 'com.apple.main-thread', stop reason =
EXC_BAD_ACCESS (code=1, address=0xff)
[        ]     frame #0: 0x000000019a295048 libobjc.A.dylib`objc_msgSend + 8
[        ] libobjc.A.dylib`objc_msgSend:
[        ] ->  0x19a295048 <+8>:  ldr    x13, [x0]
[        ]     0x19a29504c <+12>: and    x16, x13, #0xffffffff8
[        ]     0x19a295050 <+16>: mov    x15, x16
[        ]     0x19a295054 <+20>: ldr    x11, [x16, #0x10]
[        ] Target 0: (Runner) stopped.
[   +3 ms] ios-deploy exited with code 0
[ +346 ms] Service protocol connection closed.
[   +1 ms] Lost connection to device.
[   +4 ms] DevFS: Deleting filesystem on the device
(file:///private/var/mobile/Containers/Data/Application/381F8760-0D0C-4375-A2D6-A320
CE08C3F0/tmp/myappqoBmmf/myapp/)
[ +255 ms] Ignored error while cleaning up DevFS: TimeoutException after
0:00:00.250000: Future not completed
[  +16 ms] "flutter run" took 310,669ms.
[ +218 ms] ensureAnalyticsSent: 210ms
[   +3 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +1 ms] exiting with code 0

Im using an physical iphone with software version 15.3.1
image_picker version ^0.8.4+9

**Comment by jmagman** [comment]
@AlonsoIbarra If you are seeing a crash can you file a new issue and provide a full crash log?  This issue isn't tracking an app crash and we'd like to get more info.

**Comment by domtom1126** [comment]
I have just about the same error as the OP. [Here](https://stackoverflow.com/questions/71375525/why-wont-my-image-show-up-after-picking-from-image-picker-in-flutter) is my stackoverflow question about it with some code and a more detailed explanation. The package was working for months than all of the sudden it stopped working. I am able to select an image but after selection the image never shows up. Again, please check my SO question for more details.

**Comment by SnowZero** [comment]
I also have this problem, when using pickMultiImage, especially when the live photo is selected, there will be no response

**Comment by domtom1126** [comment]
@mink-lparrouy are there any updates or fixes that you've found. Ive encountered kind of the same thing. However it works if I create a fresh app with the image picker being the only functionality and it works. However it does not work on my real app.

**Comment by mink-lparrouy** [comment]
Hi @domtom1126 no I don't have any update. I wait until the flutter team fixes the issue.

**Comment by officialFlutterDeveloper** [comment]
facing this very same issue

sometimes selecting images returns no result

**Comment by ldt25290** [comment]
This issue happens on iOS simulator, please watch the video for more info 
https://user-images.githubusercontent.com/4800933/168730514-f1e9e4b5-764d-460c-978e-d39b370bd92e.mp4

<img width="1233" alt="image" src="https://user-images.githubusercontent.com/4800933/168730628-0ea63db3-1dd4-4a9c-b525-0c053d58caca.png">

**Comment by lucky-lusa** [comment]
I noticed a similar behavior on a real device. The Plugin does not respond, if you pick an image with the wrong extension. In my example the image on the phone is a png, but has a .jpg extension. 

Log result 
´´´
[claims] Upload preparation for claim 738E0CC2-88EA-433E-8AC4-44B7D3DECADA completed with error: Error Domain=NSCocoaErrorDomain Code=260 "Die Datei „version=1&uuid=12B61B2D-3D39-484A-97D5-0765A0FA4DA7&mode=compatible.jpeg“ konnte nicht geöffnet werden, da sie nicht existiert." UserInfo={NSURL=file:///private/var/mobile/Containers/Shared/AppGroup/52CCCA3E-CFC7-44FF-8BAC-56E9CF5769E4/File%20Provider%20Storage/photospicker/version=1&uuid=12B61B2D-3D39-484A-97D5-0765A0FA4DA7&mode=compatible.jpeg, NSFilePath=/private/var/mobile/Containers/Shared/AppGroup/52CCCA3E-CFC7-44FF-8BAC-56E9CF5769E4/File Provider Storage/photospicker/version=1&uuid=12B61B2D-3D39-484A-97D5-0765A0FA4DA7&mode=compatible.jpeg, NSUnderlyingError=0x28276f6f0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
´´´

Maybe this helps. Can we may improve the format detection?

**Comment by AJayBhimani74** [comment]
I am also facing the same issue in the real device. But it is happening randomly on the iPhone SE 14.7.1 

I am able to select the images most of the time, but sometimes the image select gallery popup crashes, and its not responding anything after that. 


`      final result = await ImagePicker().pickImage(source: event.imageSource);
        final filePath = result?.path;
        print("result ${filePath}");`
