### ISSUE TITLE
[_ImageState] keepStreamAlive not working

### ISSUE THREAD

**Issue by weiminghuaa** [flutter/flutter#98565]
The framework has no idea if `Page A` will ever come back again or not, but we do know that the widgets that are live on `Page B` might still need to be rendered soon. So we cache them even if they would not otherwise fit into the LRU cache.

If you want to cache the images on Page A because you _know_ you will be going back to it, you have to do that at the application level currently. I don't know if we have any easy way to do that, but using the `_liveImage` cache is not the right way.

Closing as WAI.

_Originally posted by @dnfield in https://github.com/flutter/flutter/issues/95891#issuecomment-1009466794_

**Comment by dnfield** [comment]
I don't think my comment makes sense as an I dependent issue. Please feel free to open a new one with a specific bug or feature request.

**Comment by weiminghuaa** [comment]
@dnfield Very Sorry, I made a error operate, I have some new discoveries. Wait a moment.

**Comment by weiminghuaa** [comment]
@dnfield I carefully analyzed the source code, in _ImageState, _stopListeningToStream method has a parameter: keepStreamAlive. When called by didChangeDependencies and dispose, it will be true and false respectively. But even if it's true in didChangeDependencies, when next time didChangeDependencies called, for example，page pop or push. _resolveImage method alway new Image Stream. So, there is a _imageStream keep alive, but _imageState cannot use it, right? If I'm wrong, very sorry.

ps: didChangeDependencies will alway call when page pop or push, because TickerMode.

**Comment by weiminghuaa** [comment]
This won't cause a problem because in _completerHandle method, _listenToStream will dispose and set to null. But I guess if _completerHandle can play more role. When page pop or push, Image don't need reload before dispose.
