### ISSUE TITLE
My app keeps white screen after launch on android platform

### ISSUE THREAD

**Issue by Inisit** [flutter/flutter#98566]
After the flutterSDK was upgraded, my app kept a white screen after launching on the Android platform,

```
`Launching lib\main.dart on DUK AL20 in debug mode...
Running Gradle task 'assembleDebug'...
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...
W/FlutterActivityAndFragmentDelegate( 2373): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
```
`

```
`[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19043.1466], locale zh-CN)
    • Flutter version 2.5.3 at E:\Android\Flutter\flutter
    • Upstream repository https://mirrors.tuna.tsinghua.edu.cn/git/flutter-sdk.git
    • Framework revision 18116933e7 (4 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4
    • Pub download mirror https://mirrors.tuna.tsinghua.edu.cn/dart-pub
    • Flutter download mirror https://mirrors.tuna.tsinghua.edu.cn/flutter

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at E:\Android\Sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = E:\Android\Sdk
    • Java binary at: E:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Users\edz\AppData\Local\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.4)
    • Visual Studio at d:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31515.178
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at E:\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code, 64-bit edition (version 1.57.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • DUK AL20 (mobile) • 127.0.0.1:7555 • android-x64    • Android 6.0.1 (API 23)
    • Windows (desktop) • windows        • windows-x64    • Microsoft Windows [Version 10.0.19043.1466]
    • Chrome (web)      • chrome         • web-javascript • Google Chrome 98.0.4758.102
    • Edge (web)        • edge           • web-javascript • Microsoft Edge 97.0.1072.62

• No issues found!
```
`
下方是android的环境版本
`
distributionUrl=https\://services.gradle.org/distributions/gradle-6.9-all.zip
  classpath 'com.android.tools.build:gradle:4.2.0'

 ext.kotlin_version = '1.5.10'

 compileSdkVersion 30

  minSdkVersion 21
  targetSdkVersion 30

`

**Comment by Inisit** [comment]
补充一下,app运行截图 
![image](https://user-images.githubusercontent.com/24307544/154220396-327bb420-e738-4c54-8249-010a34574165.png)

**Comment by darshankawar** [comment]
@Inisit 
As mentioned in the console log you shared:

`A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.`

Since 2.5 stable version, the implementation of Splash screen has changed, so you'll need to migrate your splash screen implementation to as mentioned in the document: https://docs.flutter.dev/development/ui/advanced/splash-screen#migrating-from-manifest--activity-defined-custom-splash-screens

Once you do that, the white screen behavior should be resolved.

Closing this for now as not an issue.

**Comment by Inisit** [comment]
我根据文档去掉了  **io.flutter.embedding.android.SplashScreenDrawable** 这个标签, 然后我新建了一个全新的项目,但是页面还是一直保持白屏状态, 报错日志如下:
`Launching lib\main.dart on DUK AL20 in debug mode...
Running Gradle task 'assembleDebug'...
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...
E/flutter ( 2058): [ERROR:flutter/shell/gpu/gpu_surface_gl.cc(53)] Failed to set up Skia Gr context.
E/flutter ( 2058): [ERROR:flutter/shell/common/platform_view.cc(85)] Failed to create platform view rendering surface
Debug service listening on ws://127.0.0.1:52374/bP14d_ctfY4=/ws
Syncing files to device DUK AL20...
E/flutter ( 2058): [ERROR:flutter/shell/gpu/gpu_surface_gl.cc(53)] Failed to set up Skia Gr context.
`
而且,我发现页面其实已经有了,我添加了日志,
![image](https://user-images.githubusercontent.com/24307544/154387471-0a0916e9-cf85-4222-88ad-7acc6865d860.png)
当我点击这个位置的时候
![image](https://user-images.githubusercontent.com/24307544/154387617-5f8986d6-982f-466d-b78d-8c5db2d797c6.png)
会有日志输出
![image](https://user-images.githubusercontent.com/24307544/154387685-dac11379-46dd-40b9-bcca-6c843658a76f.png)

**Comment by Inisit** [comment]
@darshankawar

**Comment by darshankawar** [comment]
@Inisit 
Can you provide entire console log ? What's the Android api version of the device / emulator you are running on ?

**Comment by dfourcfive** [comment]
i'm having same problem
tried with different flutter sdk versions (2.5.3,2.8,2.10.0,2.10.1)
tried to change target sdk(30,31,29) and compile sdk(29,30,31) and min sdk (18,19,20,21,22)
tested on sumsung s10,s10+,note10 real devices and emulators 
android 10/12/11 api 29,20

tested with two different complete apps but same problem
