### ISSUE TITLE
Missing const keyword for BorderRadius.circular

### ISSUE THREAD

**Issue by BirjuVachhani** [flutter/flutter#98575]
## Use case

`BorderRadius.circular` constructor depends on `BorderRadius.all` constructor which is `const` so `BorderRadius.circular` can also be `const` but it is not. If this is intentional then what is the intention behind it? Otherwise, it should be a `const `constructor.

`border_radius.dart` from Flutter SDK:
```dart
class BorderRadius extends BorderRadiusGeometry {
  /// Creates a border radius where all radii are [radius].
  const BorderRadius.all(Radius radius) : this.only(
    topLeft: radius,
    topRight: radius,
    bottomLeft: radius,
    bottomRight: radius,
  );

  /// Creates a border radius where all radii are [Radius.circular(radius)].
  BorderRadius.circular(double radius) : this.all( 
    Radius.circular(radius),
  );

```

## Proposal

`BorderRadius.circular` should be a const keyword.

### Flutter version

```
Flutter 2.10.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision db747aa133 (7 days ago) • 2022-02-09 13:57:35 -0600
Engine • revision ab46186b24
Tools • Dart 2.16.1 • DevTools 2.9.2

```

**Comment by danagbemava-nc** [comment]
Hi @BirjuVachhani, this is not possible at the moment. 

Kindly see https://github.com/flutter/flutter/issues/91971#issuecomment-948057803 as well as the discussion in https://github.com/flutter/flutter/pull/91239 for more information. 

Closing as this is currently not possible. 

Thank you

**Comment by BirjuVachhani** [comment]
@danagbemava-nc If I am not wrong, the linked threads states that it is not possible as `Radius.circular` is not a `const` constructor. I am not aware whether `Radius.circular` was or was not a `const ` constructor but it is now. So it seems to me that this is possible, unless it is decided to deprecate this.

**Comment by danagbemava-nc** [comment]
That isn't the case. We cannot make BorderRadius.circular const because the Radius object has to be created during construction.
