### ISSUE TITLE
Flutter webview allow unique WKProcessPool

### ISSUE THREAD

**Issue by EA-YOUHOU** [flutter/flutter#98577]
## Use case
Android webview already share same localstorage. But not the ios webview.
We would shared local storage between multiple webview.
(We would keep the possibility to execute scripts to a specific webview).

## Proposal
Use the WKProcessPool
https://stackoverflow.com/questions/36332208/two-wkwebviews-share-local-storage-but-only-after-restart

**Comment by danagbemava-nc** [comment]
This has been expressed in a different way before in an issue filed some time back. See https://github.com/flutter/flutter/issues/94591#issuecomment-985241204 for a similar comment. 

Kindly follow up there for more information. 

Closing from here as duplicate. 

If you disagree, kindly leave a comment below and I will repoen. 

Thank you
