### ISSUE TITLE
Error parsing base64 string - looks like general bug of dart

### ISSUE THREAD

**Issue by Miedziaq** [flutter/flutter#98585]
Im trying to parse html with some html viewer libraries on flutter packages
im getting the error during parsing te base64 image tag
i tried the same using Base64Decoder().convert(base) and i got the same,
so its definitely looks like bug in dart/flutter convert library.

the same base64string works in online parsers, and in c#, and in angular it works fine :) only flutter cannot parse it

exception: 

Exception has occurred.
FormatException (FormatException: Invalid character (at character 77)
/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAUEBAQEAwUEBAQGBQUGCA0ICAcHCBALDAkNExAUExIQ
                                                                                                                                                                   ^
)

code causing problem (there is only shortcut of base64 i used because its exceded body length of github:

`                  var base = '''/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAUEBAQEAwUEBAQGBQUGCA0ICAcHCBALDAkNExAUExIQ
EhIUFx0ZFBYcFhISGiMaHB4fISEhFBkkJyQgJh0gISD/2wBDAQUGBggHCA8ICA8gFRIVICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICD/wAARCAOyBaIDASIA
AhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQA
AAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3
ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWm
p6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEA
AwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSEx
BhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElK
U1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3
uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDzuSST
zX/eP94/xH1pvmSf89H/AO+jRJ/rX/3j/OrNrN9jstR1EWiXT2tuXSORdyliQBkfjXzdCjKvVjRh
vJ2+8/pzG4qGDw08TUWkFcreZJ/z0f8A76NHmSf89H/76Nb3w01PSPHHimHQdZ0mzsvPRmSeAup3
AZxjOK9ivfgr4dWBpo9QljVeThs/pivcx3DuOwM+Ssle19H0Pi8Px7lNbfmj6r/Js+f/ADJP+ej/
APfRo8yT/no//fRqS6iWC8nhRtyxuVB9QDUNfObH38WpRUl1HeZJ/wA9H/76NHmSf89H/wC+jTam
t7W6u2kW1t5JzGhkcRqW2oOrHHQD1oG7LVkfmSf89H/76NHmSf8APR/++jTaKB2HeZJ/z0f/AL6N
HmSf89H/AO+jTaXawO0qQfQjmgBfMk/56P8A99GjzJP+ej/99GjY46xsPqpptAaDvMk/56P/AN9G
jzJP+ej/APfRptFAWHeZJ/z0f/vo0eZJ/wA9H/76NNpQrN91SfoM0BoL5kn/AD0f/vo0eZJ/z0f/
AL6NN5BwQQfQ0UBYd5kn/PR/++jR5kn/AD0f/vo02igLDvMk/wCej/8AfRo8yT/no/8A30abRQFh
3mSf89H/AO+jR5kn/PR/++jTakhhmubiO3t4nmmlYIkaLlnY8AAdzRuJ2WrG+ZJ/z0f/AL6NHmSf
89H/AO+jSyxSQTPDNG0csbFWRxgqR1BHamUD0Y7zJP8Ano//AH''';
                  Uint8List _bytes;
  _bytes = Base64Decoder().convert(base);`

**Comment by luizprog** [comment]
did you  tried cover into " instead of  '''?

**Comment by Miedziaq** [comment]
i know, but in this way the html is coming from outlook. so how is it possible that it works in every other technology? 🤣
every other technologies like typescript/angular,  c#/.net core, and even https://base64-to-image.com/ dont have this kind of problems with it. You provides library to parse base64 so you should parse it properly huh? :).

Error is correct but not informative. 
what is that explanation ? :)
