### ISSUE TITLE
Performance Issue with Flutter 2.10. as compare with 2.81. the upgrade resembles 2.5 or 2.2 performance

### ISSUE THREAD

**Issue by akshayindia** [flutter/flutter#98589]
1.  Please tell us exactly how to reproduce the problem you are running into, and how you measured the performance.
Ans. You can install 1 plugin flutter-quill in Flutter 2.10 and Flutter 2.8 and you can find the performance issue.

2.  Please attach a small application (ideally just one main. dart file) that
     reproduces the problem. You could use https://gist.github.com/ for this.

Ans https://github.com/singerdmx/flutter-quill
Kindly multiply the document by 10 times.

3.  Switch flutter to the master channel and run this app on a physical device
     using profile or release mode. Verify that the performance issue can be
     reproduced there.

**Target Platform:** - Android
**Target OS version/browser:** - Android version 10.
**Devices:** POCO F1

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.10.1, on macOS 12.0.1 21A559 darwin-arm, locale en-IN)
    • Flutter version 2.10.1 at /Users/akshayjain/FlutterProjects/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (7 days ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/akshayjain/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.64.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (3 available)
    • POCO F1 (mobile)            • 289ff08a      • android-arm64  • Android 10 (API 29)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12 (API 31) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

```
</details>

Flutter 2.10 performance -
<img width="1439" alt="Screenshot 2022-02-16 at 9 30 28 PM" src="https://user-images.githubusercontent.com/36562389/154305667-d1b68e54-621a-4c51-bca4-39f3d9d1fb96.png">

**Comment by akshayindia** [comment]
W/Looper  ( 5816): Slow Looper main: doFrame is 694ms late because of 1 msg, msg 1 took 698ms (seq=270 running=624ms runnable=4ms io=33ms late=29ms h=android.os.Handler c=io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ)
I/OpenGLRenderer( 5816): Davey! duration=810ms; Flags=0, IntendedVsync=33713214395351, Vsync=33713897728657, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=33713917344794, AnimationStart=33713917423544, PerformTraversalsStart=33713917513440, DrawStart=33714020619846, SyncQueued=33714022485367, SyncStart=33714023213127, IssueDrawCommandsStart=33714023292138, SwapBuffers=33714023987138, FrameCompleted=33714025157815, DequeueBufferDuration=157000, QueueBufferDuration=816000,

**Comment by danagbemava-nc** [comment]
Hi @akshayindia, the screenshot you shared shows that the app was run in `debug` mode. Debug mode should not be used as an indicator of the performance of an app. Kindly run the app in `profile` or `release` mode to see whether or not the performance is better.

Also, the code sample that you have shared is a third-party package. I would advise that you report the issue to them.

From what I can see in the code, the package is quite complex so it will not make determining the root cause of the performance issues any easier for us. For this issue to be actionable, we will need a relatively small sample that demonstrates what the actual issue is, and preferably, that sample should not make use of any third-party packages.

Thank you

**Comment by PhungVanHoa** [comment]
My app has the same problem with version 2.10.1. Also, Flutter 2.10.1 uses more memory than Flutter 2.8 when starting the application and navigating between screens on Android

**Comment by danagbemava-nc** [comment]
Hi @PhungVanHoa, kindly file a new issue with the performance template and provide all the necessary information in that template. 

Thank you
