### ISSUE TITLE
Is there a way to stop flutter web resizing.

### ISSUE THREAD

**Issue by kjawadDeveloper1** [flutter/flutter#98594]
Right now if we decrease the height or width of the flutter web app it affects the content is there a way to stop the resize effect?

**Comment by darshankawar** [comment]
@kjawadDeveloper1 
I am not sure if there's a way to disable or restrict web window resizing, but what's the behavior are you seeing upon resizing ?
Thers's this similar issue open that you can track: https://github.com/flutter/flutter/issues/94429
