### ISSUE TITLE
[google_maps_flutter_web] Add Support for Custom Map Tile Overlays

### ISSUE THREAD

**Issue by martyfuhry** [flutter/flutter#98596]
## Use case

Google Maps for Android and iOS have supported custom map tile overlays since 1.2. They've been working great in our Android and iOS applications. We would like to also compile our application for the web, but google_maps_flutter_web doesn't support custom map tiles.

## Proposal

As of version 0.2.0, google_maps_flutter_web simply noops any functionality related to custom tile overlays. Instead, google_maps_flutter_web should implement custom tile overlays, as the [Google Maps Javascript platform supports this](https://developers.google.com/maps/documentation/javascript/examples/maptype-overlay). We would like to use tile overlays in our web application in the same way as our mobile applications.

**Comment by vanlooverenkoen** [comment]
We are also looking at this. All the other things seem to be working fine on web.

**Comment by AsturaPhoenix** [comment]
If there's active interest for this, I have a couple commits at https://github.com/flutter/plugins/compare/main...AsturaPhoenix:flutter-plugins:overlay that I could look into getting up to scratch for a pull request. So far I've only lightly tested it in my own use case (e.g. I haven't tried it in a mobile browser yet).

![image](https://user-images.githubusercontent.com/13222934/201755894-dbd891d5-9ea3-41b9-8e78-e0e60451f4c1.png)

**Comment by martyfuhry** [comment]
Thanks for the contribution @AsturaPhoenix! My team has been using your fork in our project and it's worked real well. You can imagine our excitement when my issue from nearly a year ago gets this kind of reply.

We are also seeing massive performance issues. I thought it would be around the serialization and deserialization of the tiles over the platform channels, but it seems like you've done a much more thorough investigation in the other issue you've linked to here (#116132).

We are very interested in improvement the performance, as well as getting this module merged into the main code repository, so if you can think of anything we could do in service of that, let us know. I'm very pleased with how quickly we were able to get your code working here. So thanks again!

**Comment by AsturaPhoenix** [comment]
@martyfuhry I think tests are the main thing standing between this and a pull request, so if you'd be willing to do that, that would be amazing. Otherwise, I can add a couple over the weekend and we can see where we are on Monday.

Regarding performance, it seems to me like that'll be a considerably larger discussion, but it looks like getting this into a PR might be a first step towards starting that discussion.

**Comment by Henk-Keijzer** [comment]
So, what is the situation here? Is someone actively working on this? Could I be of any help?
