### ISSUE TITLE
Add a way to raster cache the children of a Layer

### ISSUE THREAD

**Issue by flar** [flutter/flutter#98620]
The flutter::MergedContainerLayer mechanism was introduced to solve the problem of a Layer wanting to cache its children, but needing a stable layer::unique_id() under which to do so. This facility is used by OpacityLayer and ImageFilterLayer.

Once https://github.com/flutter/flutter/issues/92287 is fixed, we should be able to extend the tagged cache keys to indicate a new type of cache entry which caches the children of a layer. The list of child id's would have to be held by such a key for proper hash/== functionality, but that is fairly feasible and would simplify the implementations or the child-caching layers.

**Comment by JsouLiang** [comment]
@flar Hey, if in this task we should add a tag `kLayerChildren` in the `RasterCacheKeyType` which like this 
```
enum RasterCacheKeyType {..., kLayerChildern, };
```
Then we may be should add the `Prepare` method to support the layer children raster cache like this:
```
void RasterCache::Prepare(PrerollContext *context, std::vector<Layer*> layer_children, const SkMatrix& ctm) {
      RasterCacheKey cache_key(UniqueId(layer_children), RasterCacheKeyType::kLayerChildren, ctm);
      .....
}
```
Does above is your mean? Thanks.

**Comment by ColdPaleLight** [comment]
@flar I filed a PR for it. Please take a look when you have a chance, thank you. https://github.com/flutter/engine/pull/31875

**Comment by ColdPaleLight** [comment]
fixed by https://github.com/flutter/engine/pull/32378
