### ISSUE TITLE
Feedback from flutter create is a little misleading, or, creating emulators for our users

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#9862]
Here's what you see after you run "flutter run":

```

All done! In order to run your application, type:

  $ cd myflutterapp
  $ flutter run

Your main program file is lib/main.dart in the myflutterapp directory.
```

The phrase "in order to run your app, type flutter run" isn't exactly correct. You need to have a device or emulator installed. "flutter run" doesn't fire up an emulator for you.

Suggestion:

 Check if we can detect if Simulator, Hardware, or Android Emulator is installed or available to run. If so, give the user instructions for how to run the simulator or android emulator.

If we can't detect any way to run the app, suggest the user install either Simulator, Android Emulator, or plug in a device, and _then_ type _flutter run_.

Thanks!

**Comment by sethladd** [comment]
This might be useful: https://developer.android.com/studio/run/emulator-commandline.html

Here are commands to create new VMs: http://stackoverflow.com/questions/4974568/how-do-i-launch-the-android-emulator-from-the-command-line

**Comment by mit-mit** [comment]
Agree we should do this; I have this listed in the 'first hour doc', and did similar research to the one above a quarter ago, but for some reason can't find the bug for it.

**Comment by mit-mit** [comment]
@devoncarew did you look more into this? You mentioned recently that you had found some issue wrt. creating emulator instances? (Launching existing ones is a separate issue that I know we are are attacking in M15).

**Comment by devoncarew** [comment]
I had researched this a few weeks ago but haven't looked at it since then. No real updates :( I think this is captured in the first hour doc, but a sketch of this might be:

- add support into flutter_tools for enumerating and launching ios simulator and android emulators
- expose this through IntelliJ

and, as a follow-up:

- add support in flutter_tools for creating emulators
- expose in a `flutter setup` command ?
- expose in IntelliJ

**Comment by mit-mit** [comment]
Closing this bug: We are now tracking this in https://github.com/flutter/flutter/issues/13379.
