### ISSUE TITLE
[Proposal] Obfuscate flutter package/ plugin for distibution

### ISSUE THREAD

**Issue by akindone** [flutter/flutter#98633]
## Use case

this [doc](https://docs.flutter.dev/deployment/obfuscate) shows how to obfuscate the flutter app. But in my case, I write a flutter package, and I don't want to provider its source code while other flutter app using this package, just like android using .aar as dependency. I cound not find relative doc for this situation.

[stackoverflow link](https://stackoverflow.com/questions/71151818/can-obfuscated-code-for-flutter-package-or-flutter-plugin)

**Comment by maheshmnj** [comment]
Hi @akindone, Thanks for filing the issue. As far as I know, this is currently not possible. You could distribute your plugin via a private GitHub repository, But the IDE's would still expose the source code.

**Comment by akindone** [comment]
@maheshmnj  Thank you. Is there any way to make the code difficute to read like rename to meaningless word, or just support add snapshot as dependency?

**Comment by akindone** [comment]
Someone write a similar [issue](https://github.com/dart-lang/sdk/issues/42863#issuecomment-665115458)

> The Dart VM's AOT compiler (gen_snapshot) does support obfuscation via --obfuscate. Additionally a lot of symbolic information can be stripped via --dwarf-stack-traces --save-debugging-info=<file> (**).

But I don't know how to use the command in flutter. And I just don't not want to provider the source code directly

**Comment by maheshmnj** [comment]
> Is there any way to make the code difficult to read like rename to meaningless word, or just support add snapshot as dependency?

Not that I Know of regarding obfuscating the plugin.

I am labeling this issue as a documentation proposal and also for further insights from the team to make things clear about this usecase.

**Comment by stuartmorgan** [comment]
A non-source-based package option is something that would need to be filed at https://github.com/dart-lang/sdk and/or https://github.com/dart-lang/pub. Flutter doesn't have a separate package system from Dart.

(cc @devoncarew; relevant to recent discussion about binary formats)
