### ISSUE TITLE
First run of "flutter run" for Android is pretty slow

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#9863]
We don't print a spinner or any feedback, and we're very slow (1-2 minutes) to boot up our start project for the first time onto an emulator.

Here's what I was staring at:

```
C:\Users\sethladd\Documents\Code\myflutterapp\myflutterapp>flutter run
Launching lib/main.dart on Android SDK built for x86 in debug mode...
```

I almost Control-C'ed it.

Then, finally, I saw:

```
Running 'gradle assembleDebug'...                    18.0s
Built build\app/outputs/apk/app-debug.apk (21.6MB).
Installing build\app/outputs/apk/app.apk...           1.0s
E/libGLESv2_swiftshader( 3502): badness: unimplemented: IsColorRenderable vendor/transgaming/swiftshader_source/src/OpenGL/libGLESv2/utilities.cpp:1059
E/swiftshader( 3502): AndroidEnterDebugger
Syncing files to device Android SDK built for x86...  1.5s

🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:8100/
For a more detailed help message, press "h". To quit, press "q".
```

I think we should find a faster way to run, or print a spinner with an explanation after the "launching ... in debug mode" so we can clue the developer into what's going on and that it will take a while.

**Comment by Hixie** [comment]
Run it with -v, what's it actually doing?

**Comment by xster** [comment]
iOS sister issue
#9199

**Comment by Hixie** [comment]
Do you still see this?

**Comment by mit-mit** [comment]
On a "clean" machine this is likely populating the gradle cache (I see similar slowness in Android Studio on clean machines). But, yes, a progress spinner would be good.

**Comment by rjoshi91** [comment]
Hi, I updated Andriod to 3.1 which was having flutter & dart plugins but still when trying to create a new flutter app it works like forever to create one. i spent 1 hrs on the stuff. My device is good (Mac).

**Comment by Ray-Eldath** [comment]
On my device, the `Syncing files to device` seems **never gonna stop**...
![snipaste_2018-07-12_00-13-46](https://user-images.githubusercontent.com/7938763/42585537-7b5a012e-8568-11e8-85c9-a2f3f97d647a.png)
And the `main.dart` is just the [get started](https://flutter.io/get-started/codelab/) you provided...

**Comment by kdy1** [comment]
I somehow solved this issue.



```
org.gradle.jvmargs=-Xmx4096M -XX:MaxNewSize=3G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=false

```

`-XX:MaxNewSize=3G` is important. (peak ps eden space usage was 100% according to gradle build scan)

**Comment by gilton** [comment]
Sorry, @kdy1,  could you emphasize the path and the file where we can change this gradle file ?!
Thank you in advance!

**Comment by gilton** [comment]
Hi, @kdy1, thanks for your post. I really appreciated it! I'd ask for just one thing, could you emphasize the path and the file(s) where we could make those changes in gradle?!

Thanks in advance!

**Comment by gilton** [comment]
This first change proposed by @kdy1:
> I somehow solved this issue.
> 
> ```
> org.gradle.jvmargs=-Xmx4096M -XX:MaxNewSize=3G
> org.gradle.parallel=true
> org.gradle.caching=true
> org.gradle.configureondemand=false
> ```
> 
> `-XX:MaxNewSize=3G` is important. (peak ps eden space usage was 100% according to gradle build scan)
> 

Can be made in **myproject/android/gradle/gradle.properties**

However; the second I don't know yet. Does anyone have any suggestion?

**Comment by kdy1** [comment]
@gilton I'm not sure, but I think it was /android/app/build.grade

**Comment by zanderso** [comment]
This issue is pretty old, it's not a regression, and it's not really specific enough to be actionable.

**Comment by mahdiebi** [comment]
> 
> 
> ![screen shot 2018-03-27 at 11 18 28 pm](https://user-images.githubusercontent.com/17436001/37984994-54e7a2cc-3215-11e8-9f6e-d26eeec509c8.png)
> Hi, I updated Andriod to 3.1 which was having flutter & dart plugins but still when trying to create a new flutter app it works like forever to create one. i spent 1 hrs on the stuff. My device is good (Mac). Please suggest how to fix it. And always it asks SDK location whenever I create a new app.

wow -_-
I have this problem too, i do not have an idea what should i do

**Comment by mit-mit** [comment]
You could try `flutter run --verbose` in a terminal to understand how the time is being spent.

**Comment by AleksandarSavic95** [comment]
> I somehow solved this issue.
> 
> ```
> org.gradle.jvmargs=-Xmx4096M -XX:MaxNewSize=3G
> org.gradle.parallel=true
> org.gradle.caching=true
> org.gradle.configureondemand=false
> ```
> 
> `-XX:MaxNewSize=3G` is important. (peak ps eden space usage was 100% according to gradle build scan)
> ....

Thank You @kdy1 ! My build time dropped from 10+ minutes to only **three**! My `gradle,properties` file **_looked_** like this:
```
org.gradle.jvmargs=-Xmx1536M
android.enableR8=true
android.useAndroidX=true
android.enableJetifier=true
```
After I added lines that were missing, and updated the existing values (with values from Your answer) I got the speed boost.
