### ISSUE TITLE
flutter test coverage doesn't clean up temp folder

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#9865]
I'm not sure if this is intended or not. The test coverage option generates a `__temp_coverage0` directory as part of its step but doesn't ever clean it up. It might be better to use the system `/tmp` (or equivalent) to do this step or to clean up this folder afterwards.

**Comment by eseidelGoogle** [comment]
Probably just an accident, but low priority to fix.

**Comment by zoechi** [comment]
I can't reproduce. Do you think this is still an issue?

**Comment by lukef** [comment]
Doubtful this is still relevant. Close.
