### ISSUE TITLE
[camera] cache from imageStream causing invalid data

### ISSUE THREAD

**Issue by myoganugraha** [flutter/flutter#98657]
Hi there,

i'm implement barcode/qr scanner using camera, 
which using imageStream and result from that will parse using google ml kit

but sometimes when i just opened the camera preview screen, after repetitive open and scan the qr,
it will use data image from previous imageStream

thought it was imageStream cache or memory management issue,
tested it using google pixel 3 on android 12,
but rarely on ios device

has anyone experienced this too?

and can we limit streamImage frame to avoid high memory usage ?

i create a repo to reproduce the issue
[https://github.com/myoganugraha/reproduce_imagestream_cache](https://github.com/myoganugraha/reproduce_imagestream_cache)

```
flutter doctor -v
[✓] Flutter (Channel stable, 2.10.1, on macOS 12.2.1 21D62 darwin-x64, locale en-ID)
    • Flutter version 2.10.1 at /Users/myoganugraha/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (8 days ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/myoganugraha/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/myoganugraha/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.64.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (2 available)
    • Pixel 3 (mobile) • 8AFX0S11G • android-arm64  • Android 12 (API 31)
    • Chrome (web)     • chrome    • web-javascript • Google Chrome 98.0.4758.102
    ! Error: Nugraha’s iPhone is not connected. Xcode will continue when Nugraha’s iPhone is connected. (code -13)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
dependencies:
  bloc: ^8.0.2
  camera: ^0.9.4+12
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  google_ml_vision: ^0.0.7
```

thanks

**Comment by darshankawar** [comment]
@myoganugraha 
Based on the description, I think you are hitting https://github.com/flutter/flutter/issues/88173 and also looks similar to https://github.com/flutter/flutter/issues/60409.

Also, to confirm whether you have properly implemented `imageStream` or not, check this open issue and underlying comments and based on it, see if your implementation is missing anything or not. https://github.com/flutter/flutter/issues/26348

With that, I am going ahead and closing this as duplicate fo above two linked issues. You can follow-up in it and share your current findings in those for better tracking.
If you disagree or think this is a separate issue other than what I linked, write in comments and I'll reopen it.
