### ISSUE TITLE
documentation: Error in the FocusNode example

### ISSUE THREAD

**Issue by albertodev01** [flutter/flutter#98665]
In the [FocusScope](https://api.flutter.dev/flutter/widgets/FocusScope-class.html) documentation page there in an error in the dispose method:

```dart
@override
  void dispose() {
    super.dispose(); // <-- this should go last
    backdropNode.dispose();
    foregroundNode.dispose();
  }
```

**Comment by cbracken** [comment]
Thanks for filing, and for your fix!

**Comment by TahaTesser** [comment]
Closing as fixed
