### ISSUE TITLE
 when click ElevatedButton ,hide ElevatedButton and occur event

### ISSUE THREAD

**Issue by Chih-ming328** [flutter/flutter#98662]
when click ElevatedButton ,hide ElevatedButton and occur event

**Comment by maheshmnj** [comment]
Hi @Chih-ming328, Thanks for filing the issue. If I understand correctly you are trying to hide a button and yet get a tap response is that correct?

if so did you try using Opacity?

```dart
   Opacity(
         opacity: 0.0,
              child: ElevatedButton(
                onPressed: () {
                  print('tapped on the hidden button');
                },
                child: Text(
                  'Tap me',
                  style: Theme.of(context).textTheme.headline6,
                ),
              ),
            )
```  

In case this is not what you are looking for, please update the issue description with more details about what you are trying to achieve  with expected vs actual behavior.

Thanks
