### ISSUE TITLE
[google_sign_in] Authentication failure with release apk

### ISSUE THREAD

**Issue by andesappal** [flutter/flutter#98661]
Hi please see https://github.com/flutter/flutter/issues/98032 and https://github.com/FirebaseExtended/flutterfire/issues/8092#issuecomment-1043056345 thank you. 

None have been solved, and both have been closed!!!!

**Comment by andesappal** [comment]
Did you click on the first link above for correct understanding? All SHAs are set in Firebase, as is google-services.json. 

Please read the content of the messages I send before asking for information.

**Comment by maheshmnj** [comment]
> Please read the content of the messages I send before asking for information.

@andesappal it is required that you update the issue description, Anyone who looks at the issue doesn't need to go through all the thread in the linked issue.  

The issue that you linked doesn't seem to show any errors or logs, So it is unclear what you meant by the  

> Did not sign in with Google on the APK.

Neither does the linked issue show any sample code. To investigate this issue further, You would need to update the issue description with the `sample code`,  `error logs`, plugins that you are using in `pubspec.yaml`   

> flutter build apk -t lib/src/main.dart --split-per-abi

Does the issue occur only with split apks or fat apk too built with `flutter build apk`?


> Check that the same app on Android Studio, running main.dart, signs in with Google without issues.

Is this in debug mode or release?

**Comment by andesappal** [comment]
We've fixed the issue but still experimenting with results to be sure the issue is with Google Cloud

**Comment by andesappal** [comment]
Whenever the identity toolkit API is added to the restrictions list, the app signs in with Google. 
When it’s not part of the restrictions list, the app does not sign in with Google. 

@felangelov this could impact your Firebase login example. 

![image](https://user-images.githubusercontent.com/54340176/154694871-c58ba996-8212-49c0-8126-4b3b286efe8b.png)

Will close for now and re-open or create a new issue in case this comes back.

**Comment by andesappal** [comment]
The authentication failure is creaping up again

**Comment by andesappal** [comment]
Removed all restrictions from the Identity toolkit API and the APK is signing in again

**Comment by andesappal** [comment]
Cannot Google sign in with the release APK, once again. For my Android key, these are the allowed APIs the key can call:

Selected APIs:
App Engine Admin API
BigQuery API
Cloud Build API
Cloud Datastore API
Cloud Debugger API
Cloud Firestore API
Cloud Functions API
Cloud Logging API
Cloud Messaging
Cloud Monitoring API
Cloud Pub/Sub API
Cloud Resource Manager API
Cloud Runtime Configuration API
Cloud Scheduler API
Cloud SQL
Cloud Storage
Cloud Storage API
Cloud Testing API
Cloud Trace API
FCM Registration API
Firebase App Check API
Firebase App Distribution API
Firebase Cloud Messaging API
Firebase Installations API
Firebase Management API
Firebase Remote Config API
Firebase Rules API
Geolocation API
Google Cloud APIs
Google Cloud Storage JSON API
Identity Toolkit API
Legacy Cloud Source Repositories API
Maps JavaScript API
Mobile Crash Reporting API
Service Management API
Service Usage API
Token Service API

**Comment by Hixie** [comment]
> Please read the content of the messages I send before asking for information.

> I am tired of repeating myself.

This kind of communication style is a violation of our code of conduct, which requires participants to be actively welcoming. I have blocked your account from our organization for 30 days, please consider how you may participate in a more friendly manner if you would like to return.
