### ISSUE TITLE
[dashboard] Task times are off by an order of magnitude

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#98676]
It's likely these values are reading microseconds instead of milliseconds, which gets these off. The expect values in the example is expected to be 0 minutes for queue and 10 minutes for runtime.

![image](https://user-images.githubusercontent.com/2148558/154534572-6b093ddc-321b-4142-acd7-05ffc2d56235.png)

**Comment by keyonghan** [comment]
Now everything is in cocoon scheduler: https://github.com/flutter/flutter/issues/92300, and the issue is fixed.
