### ISSUE TITLE
"body" property is no longer present in Scaffold class

### ISSUE THREAD

**Issue by gomalley411** [flutter/flutter#98672]
hello, I'm working on the project and it's telling me to add this to my project inside `_ChatScreenState`:
``
    appBar: AppBar(title: Text('FriendlyChat')),
    body: _buildTextComposer(),    // NEW
``

but, for some reason it seems like the `body` element has either been removed from the `Scaffold` class or for some other reason it's not there. When I try to run my app it says it failed to compile. Any ideas why this is happening or how to fix?

**Comment by darshankawar** [comment]
@gomalley411 
I think you are referring to codelabs: https://codelabs.developers.google.com/codelabs/flutter#4
You can cross check the code implementation in this complete code sample (main.dart) provided at the bottom of the page to see if you are missing anything: https://github.com/flutter/codelabs/blob/master/friendly_chat/step_04/lib/main.dart
