### ISSUE TITLE
build.gradle errors (and unrecognized) in Intellij

### ISSUE THREAD

**Issue by darrellpf** [flutter/flutter#9867]
## Steps to Reproduce

Make a new project.

Open android/app/src/build.gradle

"Cannot resolve symbol 'GradleException'. From that point on all the keywords are also not resolvable.

![image](https://cloud.githubusercontent.com/assets/2779084/25774611/e59c73c0-3247-11e7-810e-8964477c8272.png)
Open android/app/build.gradle

All of the keywords are also not resolvable

![image](https://cloud.githubusercontent.com/assets/2779084/25774620/1582be32-3248-11e7-83af-893a24901d60.png)

In Android Studio modifying one of these files would cause a gradle sync message but none appears.

There doesn't seem to be a way to kick gradle... no menu items. Right clicking on the gradle files doesn't offer any gradle specific options.

## Flutter Doctor

[✓] Flutter (on Linux, channel master)
    • Flutter at /home/darrell/flutter
    • Framework revision 8cef5232d5 (17 hours ago), 2017-05-05 17:18:58 -0700
    • Engine revision 0071651ecb
    • Tools Dart version 1.23.0-dev.11.11

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /home/darrell/Android/Sdk
    • Platform android-25, build-tools 25.0.2
    • Java binary at: /home/darrell/android-studio/jre/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b736)

[✓] Android Studio (version 2.4)
    • Android Studio at /home/darrell/android-studio
    • Gradle version 3.4.1
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b736)

[✓] IntelliJ IDEA Community Edition (version 2017.1)
    • Dart plugin version 171.4424
    • Flutter plugin version 13.1

[✓] Connected devices
    • None

**Comment by eseidelGoogle** [comment]
FYI @devoncarew

**Comment by mit-mit** [comment]
Sorry the the late reply @darrellpf! After opening the project, did you get prompted to use gradle wrapper? Did you answer yes or no?

I think you may be hitting https://github.com/flutter/flutter/issues/9842. I listed a temporary workaround there.

**Comment by darrellpf** [comment]
[✓] Flutter (on Linux, locale en_US.UTF-8, channel master)
    • Flutter at /home/darrell/flutter
    • Framework revision 21441aa366 (11 hours ago), 2017-06-08 18:13:49 -0700
    • Engine revision 4d423b62b9
    • Tools Dart version 1.24.0-dev.6.7

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /home/darrell/Android/Sdk
    • Platform android-25, build-tools 25.0.3
    • ANDROID_HOME = /home/darrell/Android/Sdk
    • Java binary at: /home/darrell/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.4)
    • Android Studio at /home/darrell/android-studio
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1)
    • Flutter plugin version 14.0
    • Dart plugin version 171.4424.63

[✓] Connected devices
    • None

-----------------------

I followed the steps to reproduce above, making a new flutter project. I did press the fix for the ide's warning about being an android project but there was no prompt for gradle wrapper.

(I had though this was leading to another problem I'm having with android dependencies farther on in the file not being resolved for com.google packages, but commenting out the check doesn't fix that)

**Comment by mit-mit** [comment]
Can you clarify exactly (preferably with screenshots) which dialogs you get when you open in Android Studio, and what option you are selecting?

Does the project build for you using the flutter tool (i.e., `cd <location of project` + `flutter build apk`)?

**Comment by darrellpf** [comment]
![image](https://user-images.githubusercontent.com/2779084/27026350-47ab7d90-4f12-11e7-8d43-eb8f2dc8ea61.png)

![image](https://user-images.githubusercontent.com/2779084/27026379-61eeb488-4f12-11e7-977e-97bffe55cef0.png)

A frameworks detected dialog box opens in the bottom right area of the screen. If you wait for a bit that message disappears. You can click on dialog box, or after a minute or so the dialog disappears, though there is a remnant of the dialog left as a status message

![image](https://user-images.githubusercontent.com/2779084/27026523-dd70add2-4f12-11e7-91fa-dbe53d5b019a.png)

![image](https://user-images.githubusercontent.com/2779084/27026595-202f2e0a-4f13-11e7-9519-b0bdc4595490.png)

![image](https://user-images.githubusercontent.com/2779084/27026698-838b7a9e-4f13-11e7-8134-cb86164a5deb.png)

![image](https://user-images.githubusercontent.com/2779084/27026742-a233d64e-4f13-11e7-8db5-cb7d91997cbd.png)

Hovering over any keyword in other gradle files gives a "Cannot resolve symbol" Error

In an Android Studio project there is a tab that shows the gradle files and allows you to manipulate them.

![image](https://user-images.githubusercontent.com/2779084/27026924-4f28c6ac-4f14-11e7-8bd1-353341526bbf.png)

The projects typically run ok to start even though the errors show. However, when adding new Java files or modifying the gradle dependencies (to include com.google imports for instance) the projects may not run correctly.

My general observation is that the intelij environment and the flutter command line environment tend to be out of sync. What looks like a dead in the water intellij program may work with a workaround like using the flutter command line or re-opening the intellij project's subfolder in a new window as a separate project. I've been mystified at times how demo firebase projects or plugin projects seem to just work, but my guess there is that many are worked on in the command line and editor environment rather than the intellij enviroment.

**Comment by mit-mit** [comment]
Thanks for the rich detail! I can repro this now.

@skybrian is there anything we can do to get the gradle files recognized by IDEA?

**Comment by skybrian** [comment]
Yes, we don't have any Gradle support enabled within IDEA yet. Based on my experiments, I think it would be a big change to the Flutter plugin to get this to work.

In IDEA, I don't think you can get Gradle support unless you enable it at the project level using `New Project->Gradle` or `New Project->Android`. (I tried adding a Gradle module to a non-Gradle project and was unsuccessful.)

When Gradle support is turned on, IDEA modules are created automatically based on the contents of Gradle files. They are stored in `.idea/modules`. I don't know if Flutter modules can be made compatible with Gradle.

If you want to work on the Gradle files, my current recommendation is that you open the `android` directory within Android Studio.

**Comment by mit-mit** [comment]
Sounds like we unfortunately won't be able to support editing gradle files in IDEA., and that the better approach is to enable a more complete workflow in Android Studio.

@darrellpf the request to support more Flutter development in Android Studio is tracked in flutter/flutter-intellij#384, feel free to "up vote" that bug.

**Comment by nassimbjf** [comment]
Did you find the solution?

**Comment by bramvbilsen** [comment]
I'm using Android Studio and I'm having the exact same problem.

**Comment by mit-mit** [comment]
@bramvbilsen can you please file a new issue with a description of your steps and config?

**Comment by bramvbilsen** [comment]
@mit-mit I just found a fix: https://stackoverflow.com/a/42627497/5832842
The issue started after updating Android Studio.

**Comment by subzero911** [comment]
The same problem. If I open build.gradle, IntelliJ thinks that 'GradleException' is an error
Also, IntelliJ throws a strange error "can't load Android facet; disable feature?". I disabled it, seems like it doesn't affect build.
