### ISSUE TITLE
add go_router to flutter/packages

### ISSUE THREAD

**Issue by csells** [flutter/flutter#98688]
The [go_router package](https://pub.dev/packages/go_router) should be a 1P package in flutter/packages.

**Comment by erabti** [comment]
@csells excuse my ignorance, but what does it mean to be 1P package in flutter/packages? And how does this affect go_router development? @csells

**Comment by stuartmorgan** [comment]
Closing, since the main PR landed. @chunhtai Please make sure there are follow-up issues filed for remaining work (like the doc updates).
