### ISSUE TITLE
flutter create doesn't create a project with an IntelliJ run target/configuration (?)

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#9868]
I created a project with `flutter create`, and then opened it in IntelliJ. After I sorted out the Dart SDK issues, I noticed that there are zero run targets/configurations configured.

![capture6](https://cloud.githubusercontent.com/assets/5479/25775712/44b43a74-3260-11e7-9714-4e2dfcb0c1a8.PNG)

Curious, could we create new Flutter projects with IntelliJ run targets? We create the app with "lib/main.dart", we could tell IntelliJ to default run that as the default target/configuration.

**Comment by mit-mit** [comment]
I can't repro this. We create project with a run config (and have done so for quite a while).
