### ISSUE TITLE
Modify the docs to accept the target commit and the target branch as parameters

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#98696]
Update documentation for creating new branches. See #98449 for context.

**Comment by keyonghan** [comment]
This should be synced with @CaseyHillers 's latest recipes auto branch from cocoon.

**Comment by CaseyHillers** [comment]
Will be obsolete by https://github.com/flutter/flutter/issues/102325

Feature has been added, but I'm debugging some issues with being able to consistently have Cocoon create the branch from the GoB side
