### ISSUE TITLE
Empty space after Bananas in the Chips part of the Gallery demo

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#987]
Tapping the space makes the Chip go away, which makes me think that something needs to be there?

![screenshot_20151217-152908](https://cloud.githubusercontent.com/assets/5479/11885062/103d806e-a4d3-11e5-9f53-aa1cf535ef68.png)

**Comment by Hixie** [comment]
I bet this is a dupe of https://github.com/flutter/flutter/issues/915.

**Comment by abarth** [comment]
Yeah, it's supposed to have a close button.
