### ISSUE TITLE
[shared_preferences] Update to use plugin_platform_interface

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#98709]
The shared_preferences plugin should depend on the plugin_platform_interface plugin and it should use `PlatformInterface.verify` instead of `_verifyProvidesDefaultImplementations` and `isMock`.

## Steps to Reproduce

Implement `SharedPreferencesStorePlatform` and use `noSuchMethod` to implement `_verifyProvidesDefaultImplementations` and/or `isMock`.

**Expected results:** Not possible to implement `SharedPreferencesStorePlatform` using `implements` instead of `extends`.

**Actual results:** Platform implementation is broken by new methods added to `SharedPreferencesStorePlatform`.

/cc @stuartmorgan 

See also #98710

**Comment by stuartmorgan** [comment]
Thanks for filing this; I noticed it recently but forgot to file it to track. (Since it has moderate protection against doing the wrong thing it's not a fire like the webview mess.)
