### ISSUE TITLE
Developers would like to extend and customize the build scripts for producing their Flutter app

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#9870]
It would be handy for code generation purposes to have a form of pre-execution hook to perform code generation and other forms of build tasks that are required for proper execution of your application. It can also open the possibility for other libraries/tools to extend the flutter execution system.

As a suggestion, maybe a flutter project could have a `hooks` directory (could be something else, obviously) where a developer can add dart files (somewhat like how tests are defined). Any code in that directory would then be automatically executed before the `run` command is executed.

I'd be happy to work on a more concrete specification if you think something like this would be helpful.

**Comment by Hixie** [comment]
We use gradle for building on Android, and something similar on iOS; presumably those already support something like this?

**Comment by Hixie** [comment]
@sethladd see https://github.com/flutter/flutter/issues/10387

**Comment by mit-mit** [comment]
@Hixie yes, you can hook into the platform build systems but that is a pretty indirect way of doing it if you want to do something cross-platform, for example code injection of Dart.

**Comment by sethladd** [comment]
I've re-titled this issue to better reflect the overall user journey. There are many use cases that could be solved with a developer-customizable (or, developer extensible) build system.

* code generation before a hot reload
* image resizing
* downloading and processing data before a build
* hooking into specific APK optimization tasks in gradle

We don't necessarily have to build anything, but we probably want to document some paths here so our developers know what works and doesn't when trying to produce real apps that require customized pre and post processing. That is, it may be sufficient to document how to use gradle and xcode with Flutter, and document how to pre and post process your code for hot reload.

**Comment by tvolkert** [comment]
Closing as a dup of https://github.com/flutter/flutter/issues/25377

**Comment by ollydixon** [comment]
Please no, we don't want a repeat of a junk that is gradle!
