### ISSUE TITLE
[autosubmit] Process .github/autosubmit.yml configs

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#98706]
This will allow organizations to configure their autosubmit settings

**Comment by godofredoc** [comment]
@ricardoamador this is required for the enabling the bot in dart sdk

**Comment by ricardoamador** [comment]
Yes correct. I believe I opened a duplicated as part of my work for configurable autosubmit. I will close the duplicate and leave this open.

**Comment by ricardoamador** [comment]
The following pull requests address this feature request:
https://github.com/flutter/cocoon/pull/2661
https://github.com/flutter/cocoon/pull/2683
https://github.com/flutter/cocoon/pull/2684
https://github.com/flutter/cocoon/pull/2685
https://github.com/flutter/cocoon/pull/2686
https://github.com/flutter/cocoon/pull/2688
https://github.com/flutter/cocoon/pull/2689
