### ISSUE TITLE
[tool_crash] FileSystemException Creation failed OS Error No such file or directory errno=2

### ISSUE THREAD

**Issue by JiJiBo** [flutter/flutter#98724]
%23%23 Command%0A%60%60%60%0Aflutter build ios --release%0A%60%60%60%0A%0A%23%23 Steps to Reproduce%0A1. ...%0A2. ...%0A3. ...%0A%0A%23%23 Logs%0AFileSystemException%3A Creation failed%2C OS Error%3A No such file or directory%2C errno %3D 2%0A%60%60%60%0A%230      _Directory.createSync %28dart%3Aio%2Fdirectory_impl.dart%3A133%3A7%29%0A%231      ForwardingDirectory.createSync %28package%3Afile%2Fsrc%2Fforwarding%2Fforwarding_directory.dart%3A20%3A16%29%0A%232      ErrorHandlingDirectory.createSync.%3Canonymous closure%3E %28package%3Aflutter_tools%2Fsrc%2Fbase%2Ferror_handling_io.dart%3A433%3A22%29%0A%233      _runSync %28package%3Aflutter_tools%2Fsrc%2Fbase%2Ferror_handling_io.dart%3A597%3A14%29%0A%234      ErrorHandlingDirectory.createSync %28package%3Aflutter_tools%2Fsrc%2Fbase%2Ferror_handling_io.dart%3A432%3A12%29%0A%235      EngineCachedArtifact.updateInner %28package%3Aflutter_tools%2Fsrc%2Fcache.dart%3A918%3A19%29%0A%3Casynchronous suspension%3E%0A%236      CachedArtifact.update %28package%3Aflutter_tools%2Fsrc%2Fcache.dart%3A812%3A5%29%0A%3Casynchronous suspension%3E%0A%237      Cache.updateAll %28package%3Aflutter_tools%2Fsrc%2Fcache.dart%3A681%3A9%29%0A%3Casynchronous suspension%3E%0A%238      FlutterCommand.verifyThenRunCommand %28package%3Aflutter_tools%2Fsrc%2Frunner%2Fflutter_command.dart%3A1271%3A7%29%0A%3Casynchronous suspension%3E%0A%239      FlutterCommand.run.%3Canonymous closure%3E %28package%3Aflutter_tools%2Fsrc%2Frunner%2Fflutter_command.dart%3A1161%3A27%29%0A%3Casynchronous suspension%3E%0A%2310     AppContext.run.%3Canonymous closure%3E %28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A150%3A19%29%0A%3Casynchronous suspension%3E%0A%2311     CommandRunner.runCommand %28package%3Aargs%2Fcommand_runner.dart%3A209%3A13%29%0A%3Casynchronous suspension%3E%0A%2312     FlutterCommandRunner.runCommand.%3Canonymous closure%3E %28package%3Aflutter_tools%2Fsrc%2Frunner%2Fflutter_command_runner.dart%3A281%3A9%29%0A%3Casynchronous suspension%3E%0A%2313     AppContext.run.%3Canonymous closure%3E %28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A150%3A19%29%0A%3Casynchronous suspension%3E%0A%2314     FlutterCommandRunner.runCommand %28package%3Aflutter_tools%2Fsrc%2Frunner%2Fflutter_command_runner.dart%3A229%3A5%29%0A%3Casynchronous suspension%3E%0A%60%60%60%0A%60%60%60%0A%5B%E2%9C%93%5D Flutter %28Channel stable%2C 2.10.1%2C on macOS 12.1 21C52 darwin-arm%2C locale zh-Hans-CN%29%0A    %E2%80%A2 Flutter version 2.10.1 at %2FUsers%2Fnas%2FNasFlutter%2Fflutter%0A    %E2%80%A2 Upstream repository https%3A%2F%2Fgithub.com%2Fflutter%2Fflutter.git%0A    %E2%80%A2 Framework revision db747aa133 %288 days ago%29%2C 2022-02-09 13%3A57%3A35 -0600%0A    %E2%80%A2 Engine revision ab46186b24%0A    %E2%80%A2 Dart version 2.16.1%0A    %E2%80%A2 DevTools version 2.9.2%0A    %E2%80%A2 Pub download mirror https%3A%2F%2Fpub.flutter-io.cn%0A    %E2%80%A2 Flutter download mirror https%3A%2F%2Fstorage.flutter-io.cn%0A%0A%5B%E2%9C%93%5D Android toolchain - develop for Android devices %28Android SDK version 31.0.0%29%0A    %E2%80%A2 Android SDK at %2FUsers%2Fnas%2FLibrary%2FAndroid%2Fsdk%0A    %E2%80%A2 Platform android-31%2C build-tools 31.0.0%0A    %E2%80%A2 Java binary at%3A %2FApplications%2FAndroid Studio.app%2FContents%2Fjre%2FContents%2FHome%2Fbin%2Fjava%0A    %E2%80%A2 Java version OpenJDK Runtime Environment %28build 11.0.11%2B0-b60-7772763%29%0A    %E2%80%A2 All Android licenses accepted.%0A%0A%5B%E2%9C%93%5D Xcode - develop for iOS and macOS %28Xcode 13.2.1%29%0A    %E2%80%A2 Xcode at %2FApplications%2FXcode.app%2FContents%2FDeveloper%0A    %E2%80%A2 CocoaPods version 1.11.2%0A%0A%5B%E2%9C%93%5D Chrome - develop for the web%0A    %E2%80%A2 Chrome at %2FApplications%

**Comment by maheshmnj** [comment]
HI @JiJiBo, Please update the issue description with English characters looks when you copied the logs from the console it got encoded to some other form probably hexadecimal characters.

**Comment by iapicca** [comment]
dupe? https://github.com/flutter/flutter/issues/68958
