### ISSUE TITLE
when I click on other widget, SelectableText not deselect

### ISSUE THREAD

**Issue by ara-kurd-dev** [flutter/flutter#98725]
## SelectableText not deselect

In Windows and Mac, when text is selected from SelectableText and wanting to change the selection, both SelectableText remains as they're selected.

**Actual results:**
![image](https://user-images.githubusercontent.com/78718160/154618197-d904abf2-7111-456f-b33a-54a72e2670fb.png)

I've used UniqueKey but still not solved.

Im using Flutter (Channel stable, 2.10.0, on macOS 11.6 20G165 darwin-x64, locale en-IQ)
<details>
<summary>Code sample</summary>

```
Column(
children:[
 SelectableText(
      '1004',
      style: Theme.of(context).textTheme.bodyText2,
      textAlign: TextAlign.center,
    ),
SelectableText(
      '1005',
      style: Theme.of(context).textTheme.bodyText2,
      textAlign: TextAlign.center,
    ),
]
)

```

</details>

**Comment by darshankawar** [comment]
@ara-kurd-dev 
I think you are hitting same issue as https://github.com/flutter/flutter/issues/78909, so please follow-up in it for further updates.
Closing this as a duplicate.
