### ISSUE TITLE
Opacity Widget alignment issue since 2.8.x

### ISSUE THREAD

**Issue by ibrierley** [flutter/flutter#98738]
Hi, I help maintain Flutter_map https://github.com/fleaflet/flutter_map

Since Flutter 2.8.0 we've noticed small alignment issues (or maybe rounding issues or similar?), which looks like it's been isolated to the Opacity Widget. All was fine prior to 2.8.0. It looks like the edges of the widget can get adjusted by a pixel or so.

Here's one example with a screenshot at the top https://github.com/fleaflet/flutter_map/issues/1126 and in debugging, if we remove an Opacity widget in the code, the problem goes away. The widgets are typically inside Positioned widgets that may be scaled/translated, as its a map tiling project.

Here's another example (video at the top) https://github.com/fleaflet/flutter_map/issues/1156 again when we remove the Opacity widget from our code, all is correct.

So it feels like some alignment or calculation was changed in 2.8.0 ? I see there's a lot of updates for Opacity, so not sure what could have introduced it, or if our assumptions are incorrect.

Happy to try and help isolate in any way, but not quite sure how to debug at a pixel level type of thing.

**Comment by darshankawar** [comment]
> [fleaflet/flutter_map#1156](https://github.com/fleaflet/flutter_map/issues/1156)

@ibrierley Thanks for the report. I do see the behavior while zooming in and out that white lines emerge. In order to address this properly, can you provide a self contained but minimal reproducible code sample ? Does this only happen when a map is involved ? If so, probably using `google_maps_flutter` should be able to replicate the issue too.

**Comment by ibrierley** [comment]
Realistically, I don't think I'm capable. I've tried, but unable to replicate with anything simple (it's a pretty complex layout of widgets). I feel like it would need some ability to bisect flutter Git pull requests to try and isolate when the change happened (I'm happy to try and help if someone can explain how to achieve further testing like that).

I'm not sure google_maps_flutter is relevant, as I'm not sure they use the Opacity widget at all. I think it's all native beyond the basic outer widget ?

**Comment by darshankawar** [comment]
@ibrierley 
I see a fix made to `Opacity` not so long ago, https://github.com/flutter/flutter/pull/90017 maybe you can take a look at this fix and see if it's related.

**Comment by ibrierley** [comment]
Apologies, I hadn't seen this update. Not sure how I can check if this is related ? It sounds possible though.

**Comment by darshankawar** [comment]
@ibrierley 
In order to properly address this, a use case or code sample highlighting the issue would be helpful to take this issue forward.
