### ISSUE TITLE
Easy to lose track of which section of an article a user is looking at

### ISSUE THREAD

**Issue by xster** [flutter/flutter#9873]
Would be nice to have some floating outline/navigation bar for https://flutter.io/tutorials/layout since each section is often longer than a screen height tall. It's easy to lose track of which section I'm looking at and where it situates in the context of all sections. 

Would be nice to have the outline of the page follow you around as you scroll or have some pattern for secondary navigation

**Comment by sethladd** [comment]
Not a bad idea. Can you link/screenshot me to a page that does what you're looking for?

**Comment by xster** [comment]
Here's an example
https://developer.xamarin.com/guides/ios/getting_started/installation/device_provisioning/

**Comment by sethladd** [comment]
The dartlang.org site does a good job of this: https://www.dartlang.org/guides/language/sound-dart

**Comment by xster** [comment]
Oh ya, you're right. That one's totally great too

**Comment by Sfshaza** [comment]
What about borrowing the solution from www.dartlang?

https://www.dartlang.org/guides/language/language-tour

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1837](https://github.com/flutter/website/issues/1837) via [**ZenHub**](https://www.zenhub.com/)
