### ISSUE TITLE
Deprecate Material 2 text style properties

### ISSUE THREAD

**Issue by rami-a** [flutter/flutter#98746]
Now that [Material 3 text styles](https://github.com/flutter/flutter/issues/89853) have been added to the `TextTheme`, we can deprecate the Material 2 styles (just like we did for Material 1).

## Proposal

- Deprecate (and eventually remove following the official deprecation policy) M2 text styles from `TextTheme`, for example `display1`, `bodyText2`, etc.

**Comment by iapicca** [comment]
shold this be tracked in 
https://github.com/flutter/flutter/issues/91605 
https://github.com/flutter/flutter/projects/211 ?
