### ISSUE TITLE
Add a "gap" property like in CSS for Column, Row, ReorderableListView etc.

### ISSUE THREAD

**Issue by TheNavigateur** [flutter/flutter#98743]
## Use case

The need to have a gap between ListTiles in ReordableListView, and which doesn't become part of the visible rectangle that is drop-shadowed when dragging it, and which doesn't add the same extra space at the bottom of the list view. The same requirement in rows and columns minus the dragging aspect.

## Proposal

A "gap" property like in CSS for Column, Row, ReorderableListView etc.

**Comment by TheNavigateur** [comment]
Hi @darshankawar ! Unfortunately not. I have just tested this and it becomes part of the visible rectangle that is drop-shadowed when dragging the item which includes it in a ReorderableListView. It also off-centers the drag-handle to the center of the original tile plus the gap's height. Both of these are not desired behaviours. The "Gap" element is just a less-verbose version of "SizedBox". The desired behaviour is that only the layout item is dragged, not the gap, when dragging and dropping an item. Also, the drag handle should remain in the center of the layout item itself, and the gap shouldn't affect that. This would be similar to the "gap" property in CSS, where every item in the layout is given the same "spacing" from the next item. It could be, for example, `ReorderableListView( gap: 5 /*etc.*/)`. Is this any clearer?

**Comment by darshankawar** [comment]
@TheNavigateur 
Thanks for further details. Adding `gap` for reorderableListView seems to be a valid proposal. Related: https://github.com/flutter/flutter/issues/63527
Can you also please elaborate on how it would help in `Column` and `Row` ? What would be the use case for these widgets ?

**Comment by TheNavigateur** [comment]
@darshankawar it is a very common requirement to have a uniform gap between column and/or row elements, and a `gap` property would significantly reduce verbosity and remove the requirement to logically exclude the last element from having its own spacing, in for-loops for example. The `gap` property in CSS was a significant relief for many against all the other solutions that were previously required to do the same.

**Comment by darshankawar** [comment]
There has been similar requests to add a `gap` widget https://github.com/flutter/flutter/issues/56783 and to add a spacing parameter to row and column https://github.com/flutter/flutter/issues/16957. Based on the comments from Flutter team on it, it seems that adding a `gap` or `spacing` like parameter would be complicated.

@TheNavigateur Please check the underlying comments from https://github.com/flutter/flutter/issues/16957 and see if any of the solutions mentioned in it serves your purpose or not, specially https://github.com/flutter/flutter/issues/16957#issuecomment-558878770 and other solutions suggesting `wrap` widget.
