### ISSUE TITLE
BackdropFilter works with ClipRect but not with ClipRRect 

### ISSUE THREAD

**Issue by xster** [flutter/flutter#9874]
```dart
new ClipRRect(
  borderRadius: BorderRadius.zero, 
  child: new BackdropFilter(
    filter: new ImageFilter.blur(sigmaX: 10.0, sigmaY: 10.0),
    child: blah,
  ),
)
```

doesn't end up blurring things behind the ClipRRect whereas

```dart
new ClipRect(
  child: new BackdropFilter(
    filter: new ImageFilter.blur(sigmaX: 10.0, sigmaY: 10.0),
    child: blah,
  ),
)
```

works ok

**Comment by xster** [comment]
The only difference I see on the Dart side is canvas.save() vs canvas.saveLayer() between context.pushClipRect/pushClipRRect but just for laughs and giggles, changing save to saveLayer doesn't change it. 

It's probably something in the engine

**Comment by eseidelGoogle** [comment]
I wonder if this is related at all to https://github.com/flutter/flutter/issues/9792 ?

**Comment by xster** [comment]
Related issue #10284

**Comment by xster** [comment]
https://bugs.chromium.org/p/skia/issues/detail?id=6753

**Comment by wwwdata** [comment]
Also when using a custom `ClipPath` it kills off the `BackdropFilter`. Does anybody have any workarounds how to make a box with rounded borders and a Backdrop effect like blur?

**Comment by lukepighetti** [comment]
I am trying to use ClipPath with BackdropFilter and it is failing. Is this a known issue or am I doing something wrong?

**Comment by lukepighetti** [comment]
I'll have to check it out, thanks for the update!

**Comment by goderbauer** [comment]
Tentatively closing this based on @wwwdata's comment (the upstream skia issue is also marked as fixed). Please re-open it if you still see this problem.
