### ISSUE TITLE
Compile-time help with "RenderBox not laid out" exceptions etc.

### ISSUE THREAD

**Issue by TheNavigateur** [flutter/flutter#98744]
## Use case

When building layouts, I'd prefer compile-time help with "RenderBox not laid out" exceptions, etc.

## Proposal

I don't know if this is possible, but I'd like the IDE to help me when I've failed to set a height constraint for a list view inside a column, etc., instead of having the app fail to compile for which I had to search online for a solution.

**Comment by darshankawar** [comment]
@TheNavigateur 
There are linter rules you can set that will give you compile time warnings or errors which should indicate what's wrong in the code or implementation.
Also, if this is specific to IDE, then whichever IDE you are using, you'll need to raise this as an enhancement to their plugin.

With this, I am going ahead and closing this as not a framework related use case, but could be specific to IDE you are using and also linter you can use. If you disagree, write in comments and I'll reopen it.
