### ISSUE TITLE
use websocket  garbage collection(Unhandled exception:)or vm errors

### ISSUE THREAD

**Issue by jsonpeng** [flutter/flutter#9875]
## When I at the beginning of the application is started and a *websocket connection* and send the data for the first time the flutter  run can appear the following error console, it is strange that the next to repackage this problem will not appear again ##
Unhandled exception:
Exception: Error connecting to observatory: WebSocketChannelException: WebSocketChannelException: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:8100/ws
#0      throwToolExit (package:flutter_tools/src/base/common.dart:29)
#1      VM.invokeRpcRaw (package:flutter_tools/src/vmservice.dart:653)
<asynchronous suspension>
#2      VM._fetchDirect (package:flutter_tools/src/vmservice.dart:496)
<asynchronous suspension>
#3      ServiceObject.reload (package:flutter_tools/src/vmservice.dart:344)
<asynchronous suspension>
#4      VMService.getVM (package:flutter_tools/src/vmservice.dart:172)
#5      ResidentRunner.connectToServiceProtocol (package:flutter_tools/src/resident_runner.dart:218)
<asynchronous suspension>
#6      HotRunner.attach (package:flutter_tools/src/run_hot.dart:97)
<asynchronous suspension>
#7      HotRunner.run (package:flutter_tools/src/run_hot.dart:222)
<asynchronous suspension>
#8      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:281)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:151)
<asynchronous suspension>
#10     RunCommand.verifyThenRunCommand (package:flutter_tools/src/commands/run.dart:196)
<asynchronous suspension>
#11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:121)
#12     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:262)
<asynchronous suspension>
#14     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#15     Future.Future.sync (dart:async/future.dart:208)
#16     CommandRunner.run (package:args/command_runner.dart:109)
#17     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:157)
#18     run.<anonymous closure> (package:flutter_tools/executable.dart:140)
<asynchronous suspension>
#19     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#20     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#21     _rootRun (dart:async/zone.dart:1120)
#22     _CustomZone.run (dart:async/zone.dart:1001)
#23     runZoned (dart:async/zone.dart:1465)
#24     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#25     run (package:flutter_tools/executable.dart:113)
<asynchronous suspension>
#26     main (package:flutter_tools/executable.dart:66)
<asynchronous suspension>
#27     main (file:///Users/pengyun/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#28     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

**Comment by eseidelGoogle** [comment]
Some sort of hot-reload error?  @a-siva @tvolkert

**Comment by a-siva** [comment]
@jsonpeng can you provide us some instructions on how to reproduce this error.

**Comment by a-siva** [comment]
haven't received any instructions on how to reproduce the error, assuming not an issue anymore and closing the issue. Please feel free to reopen the issue if that is not the case and instructions for reproducing the bug is available.
