### ISSUE TITLE
Regression in `90th_percentile_picture_cache_memory` on iOS

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#98766]
See: https://flutter-flutter-perf.skia.org/e/?begin=1645128560&end=1645205659&keys=Xde8167531dd03e8f0687bbbab5fcc72a&num_commits=50&request_type=1&xbaroffset=27633

Seems like the mostly likely reason is https://github.com/flutter/engine/commit/d476e7a7308436e5cc87161b2d785a3565a7f56f. @gw280 is investigating.

**Comment by gw280** [comment]
This was fixed by https://github.com/flutter/engine/pull/31561

![Screen Shot 2022-02-19 at 12 32 50 PM](https://user-images.githubusercontent.com/1221057/154818089-e78f16b9-a964-40da-af10-480e7727bd1e.png)
