### ISSUE TITLE
Ability to retry a single build in presubmit

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#98776]
Sometimes when the scheduler fails to trigger all the builds only one or two may fail. Currently we can't retry a single build and we are forced to retry all the builds for a given commit wasting resources and time.

We need to implement functionality to retry all the failing or pending builds in a given commit. If we can expose this functionality through the GitHub UI it will be even better.

**Comment by keyonghan** [comment]
Changes have landed, and are validated to work.
