### ISSUE TITLE
Recreate Navigation Stack with modal not working when app cold starting from a dynamic link 

### ISSUE THREAD

**Issue by alexlipa91** [flutter/flutter#98790]
Hi, I see this weird behaviour when handling dynamic links. What I want to do is that when coming from a link containing matchId parameter I want to clean up the navigation stack, insert the `AvailableMatches` route, insert the `MatchDetails` page and finally show a modal. This is the code I use in the link handler
       
      FirebaseDynamicLinks.instance.onLink(
        onSuccess: (PendingDynamicLinkData dynamicLink) async {
            final Uri deepLink = dynamicLink?.link;
            if (deepLink != null) {
               handleLink(deepLink);
            }); 

      Future<void> handleLink(Uri deepLink) async {
          var context = navigatorKey.currentContext;
          var matchId = deepLink.queryParameters["match_id"];
       
          Navigator.of(context).pushNamedAndRemoveUntil(
             AvailableMatches.routeName,
            (Route<dynamic> route) => false
          );
          Navigator.of(context).pushNamed(MatchDetails.routeName,
             arguments: ScreenArguments(
                matchId, false)
          );
          await showModalBottomSheet(context: context, builder: (context) => Text("done"));
      }

If the app is already open this works fine. I see the pages going in the stack and the final modal. 

However if the app is starting from this link I have a problem. This is the `initState` in the first `StatefulWidget` of the application

          void initState() {
            super.initState();
            initDynamicLinks();
            loadData(context);
          }
          
          Future<void> loadData(BuildContext context) async {
              final PendingDynamicLinkData data = await FirebaseDynamicLinks.instance.getInitialLink();
              handleLink(data.link);
          }

In this case the `handeLink` method works until the latest modal. The pages are pushed correctly on the stack however the last modal doesn't show up.

I am adding prints and debug breakpoints but it seems that this line never gets executed. There is no crash or exception. It just gets ignored and nothing happens. 

I sense it might be something in the way I am using `context` but I am not sure

**Comment by darshankawar** [comment]
@alexlipa91 
Since this is related to firebase_dynamic_links which is a 3rd party plugin, you'll need to raise this in dedicated repo: https://github.com/FirebaseExtended/flutterfire/issues. or you can also ask the same on support platforms like StackOverflow because it may be related to the way dynamic links is set up / configured.
Closing from here.
