### ISSUE TITLE
[Flutter Camera 0.9.4+14] Build Warning of deprecated API

### ISSUE THREAD

**Issue by XeroDays** [flutter/flutter#98798]
### Flutter Camera : Build Warnings
I am using `flutter version 2.10` with the Camera version as mentioned `camera: ^0.9.4+14`

With command `flutter Run` I got issues as following

![image](https://user-images.githubusercontent.com/38852291/154801226-aa3f1c1c-167a-4c0f-86a5-bbef598779e4.png)

**Comment by danagbemava-nc** [comment]
Duplicate of #94999
