### ISSUE TITLE
Missing landscape layout of time pickers

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#988]
![screenshot_20151217-153210](https://cloud.githubusercontent.com/assets/5479/11885100/722fee56-a4d3-11e5-8356-b1125fe29017.png)

**Comment by eseidelGoogle** [comment]
Totally a feature.  @HansMuller :)

**Comment by abarth** [comment]
Yeah, I didn't implement the landscape version of the widget.  We totally need it.
