### ISSUE TITLE
Add an intial value

### ISSUE THREAD

**Issue by mouradkherouf** [flutter/flutter#98805]
I would be nice to add the availability to set an initial address as parameter.

**Comment by iapicca** [comment]
@mouradkherouf consider using [dart define](https://stackoverflow.com/questions/44250184/setting-environment-variables-in-flutter)

**Comment by maheshmnj** [comment]
Hi @mouradkherouf, Thanks for filing the issue. I am quite not sure what you are referring to as the initial address, Please update the issue description clearly explaining the issue and the solution you are proposing.

**Comment by mouradkherouf** [comment]
Thanks for your fast reply,

In fact I have partners accounts with the address of their restaurant.*, so when they want to update their account, I'd like to give them the possibility to change their address but, with your actual library, I didn't find a way to initialize the address field with the one that was saved in the database.

**Comment by maheshmnj** [comment]
Wow! that's very cool, But I am sorry I still don't understand what library are you referring to, You will need to be more specific with the issue, Also if its a proposal for a third party plugin as it sounds based on the description then you should be filing that in their dedicated repository.

**Comment by mouradkherouf** [comment]
Sorry, the library is : GooglePlaceAutoCompleteTextField

**Comment by maheshmnj** [comment]
Thanks for the update @mouradkherouf but there isn't any such plugin probably you are referring to [google_places_flutter](https://pub.dev/packages/google_places_flutter) which is a third-party plugin, Issues related to it must be filed in its dedicated repository. Closing as this is not really an issue with flutter.
