### ISSUE TITLE
Large regression in hot reload time

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#98802]
Due to https://github.com/flutter/flutter/commit/4add01ab68fa95adb67ed3ee91a7867146286347

https://flutter-flutter-perf.skia.org/e/?begin=1645176556&end=1645249764&keys=Xc864be5a237d97d53cd237ab0e2f5f8d&num_commits=50&request_type=1&xbaroffset=27645

**Comment by zanderso** [comment]
Regression is from < 1s hot reload to > 5s hot reload.

Revert is here https://github.com/flutter/flutter/pull/98803. This is P0 until the revert lands.

**Comment by zanderso** [comment]
Also here https://flutter-flutter-perf.skia.org/e/?begin=1645182560&end=1645253657&keys=X3b97b2bb7b9a25eed7e4b4c4e3d441d4&num_commits=50&request_type=1&xbaroffset=27647

**Comment by bkonyi** [comment]
Dropping priority to P3 as this isn't actively blocking anyone. I'll investigate the regression.

**Comment by bkonyi** [comment]
Relanded behind a flag in https://github.com/flutter/flutter/pull/100995.
