### ISSUE TITLE
Icons.key or similiars are not working well

### ISSUE THREAD

**Issue by EdmarCaixeta** [flutter/flutter#98816]
I'm running last version of Flutter (2.10) and testing my code on my Samsung Galaxy S20 FE, Google Chrome and Linux.

The following code is where I have my issue:
`const Icon(Icons.key),`
and even tried:
`const Icon(IconData(0xf0623, fontFamily: 'MaterialIcons')),`

Neither of them works well, instead of rendering the Key Icon it renders different emojis on the celphone and either Chrome or Linux renders nothing.

**Comment by danagbemava-nc** [comment]
Hi @EdmarCaixeta, kindly upgrade to flutter stable 2.10.2 and let me know if the icons are rendered properly. 

Thank you

**Comment by EdmarCaixeta** [comment]
Hello @danagbemava-nc, thanks for the support! After the update the icons worked well.
