### ISSUE TITLE
Import with generated codes does not play well if it is exported from another class

### ISSUE THREAD

**Issue by richard457** [flutter/flutter#98828]
let's say I have a file called models. dart with the following code:
```
export 'package:models/io/a.dart'
    if (dart.library.html) 'package:models/html/b.dart';
```

if the class A  has 
`` a.g.dart ``` in it, the generated code from A won't be imported in another where I am importing the file

if I do 
``` import 'models.dart' ```
unless I do ``` import 'a.dart' ``` directly.

**Comment by darshankawar** [comment]
@richard457 
This sounds to me like a dart-lang to be the correct repo for this, but before we could confirm this, can you provide a sample reproducible code along with actual vs expected behavior ?
