### ISSUE TITLE
Error: Unhandled Exception: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 2845 pos 18: '!navigator._debugLocked': is not true

### ISSUE THREAD

**Issue by mycar98765** [flutter/flutter#98820]
I am new in Flutter. I face a problem about Unhandled Exception: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 2845 pos 18: '!navigator._debugLocked': is not true.

This is my Debug Console:
```
E/flutter ( 5236): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 2845 pos 18: '!navigator._debugLocked': is not true.
package:flutter/…/widgets/navigator.dart:2845
E/flutter ( 5236): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
E/flutter ( 5236): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
E/flutter ( 5236): #2      _RouteEntry.handlePush.<anonymous closure>
package:flutter/…/widgets/navigator.dart:2845
E/flutter ( 5236): #3      TickerFuture.whenCompleteOrCancel.thunk
package:flutter/…/scheduler/ticker.dart:407
E/flutter ( 5236): #4      _rootRunUnary (dart:async/zone.dart:1434:47)
E/flutter ( 5236): #5      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter ( 5236): <asynchronous suspension>
E/flutter ( 5236): #6      TickerFuture.whenCompleteOrCancel.thunk
package:flutter/…/scheduler/ticker.dart:406
E/flutter ( 5236): <asynchronous suspension>
E/flutter ( 5236):
```
I would appreciate any help.

**Comment by maheshmnj** [comment]
Hi @mycar98765, Thanks for filing the issue. Please share output of `flutter doctor -v` and a minimal and complete reproducible code sample to investigate the issue further.  
Additionally, Please refer to this [SO answer](https://stackoverflow.com/a/55622474/8253662) and see if this helps solve your issue

**Comment by mycar98765** [comment]
[This answer](https://stackoverflow.com/questions/55618717/error-thrown-on-navigator-pop-until-debuglocked-is-not-true/55622474#55622474) didn't help me.

**Comment by maheshmnj** [comment]
Thanks for the update, In order to investigate further we would need a minimal and complete sample code.

Thanks

**Comment by mycar98765** [comment]
```
onPressed: () {
                      Navigator.pop(context);
                    },
```

**Comment by maheshmnj** [comment]
@mycar98765 The above piece of code wouldn't help us to find the cause of the issue. We would need a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example)  which we can directly copy and run and it should reproduce the same error as reported in the original post.

**Comment by mycar98765** [comment]
On my own, I finally found a solution.

**Comment by mycar98765** [comment]
On my own, I finally found a solution. I've been testing my widget to see what's causing the problem. Finally, I found it.

**Comment by slimpotatoboy** [comment]
what solution did you find? please share
