### ISSUE TITLE
Edge-To-Edge stops working after flutter run

### ISSUE THREAD

**Issue by har-nick** [flutter/flutter#98841]
**Expected results:**
The status bar and gesture bar do not have a background, and content is rendered behind it.
<details>
<summary>Expected result image</summary>

![image](https://user-images.githubusercontent.com/56137506/154868948-cb5c4b75-f542-4d5d-80bc-00cfbf4eabe1.png)

</details>

**Actual results:**
The status bar has a shadow, and the gesture bar is black.
<details>
<summary>Actual result image</summary>

![image](https://user-images.githubusercontent.com/56137506/154869111-7afd13e5-3dd1-4779-9924-a06b2b549a1a.png)

</details>
<details>
<summary>Full code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  SystemChrome.setEnabledSystemUIMode(SystemUiMode.edgeToEdge);
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Flutter Demo Home Page'),
      ),
    );
  }
}
```

</details>

No errors or exceptions were found.

The issue is "fixed" for either the status or gesture bars if I use SystemChrome to set their backgrounds transparent, like so:

```dart
void main() {
  WidgetsFlutterBinding.ensureInitialized();
  SystemChrome.setEnabledSystemUIMode(SystemUiMode.edgeToEdge);
  SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
      systemNavigationBarColor: Colors.transparent));
  runApp(const MyApp());
}
```

Setting it for a single UI element will only "fix" it for whatever element was set. The above code would show this on screen:

<details>
<summary>Status bar only</summary>

```dart
SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle(statusBarColor: Colors.transparent));
```

![image](https://user-images.githubusercontent.com/56137506/154870291-ad0ff186-ab70-4f78-8ff2-33410e16ef1c.png)

</details>

<details>
<summary>Gesture bar only</summary>

```dart
SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle(systemNavigationBarColor: Colors.transparent));
```

![image](https://user-images.githubusercontent.com/56137506/154870376-2a7bd286-14b7-4e67-a383-f29d89db9b08.png)

</details>

Removing the lines setting the background colours achieves the expected result.

**Comment by darshankawar** [comment]
@har-nick 
This seem to be happening because `SystemUiMode.edgeToEdge` is not enabled by default. Please see this similar open issue to make it default, for your reference: https://github.com/flutter/flutter/issues/86248

Also, the fix you provided, ie to have `systemNavigationBarColor: Colors.transparent` helps to make `SystemUiMode.edgeToEdge` to make it work. See this similar issue comment: https://github.com/flutter/flutter/issues/86248#issuecomment-879275168.

Based on above, I suggest you to follow-up in the linked issue for further updates.
Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.
