### ISSUE TITLE
[Feature] Add position property to SnackBar

### ISSUE THREAD

**Issue by joutvhu** [flutter/flutter#98848]
I need show SnackBar on top.

**Comment by danagbemava-nc** [comment]
Hi @joutvhu, according to the Material Design guidelines, the `Snackbar` should be placed at the bottom of the UI. See https://material.io/components/snackbars#placement for more information. 

Kindly consider using any of the toast packages in [pub.dev](https://pub.dev/packages?q=toast). 

Closing as this isn't in line with the Material Design specs.

Thank you
