### ISSUE TITLE
Need to support "frosted glass" effect in CSS. To use backdrop-filter: blur(20px) 

### ISSUE THREAD

**Issue by manh74** [flutter/flutter#98849]

**Comment by manh74** [comment]
Or anyone help solutions. Pls support me this.

**Comment by digit81** [comment]
@manh74 do you think about such solution: https://pub.dev/packages/glass_kit

**Comment by darshankawar** [comment]
@manh74 
I think your issue is same as https://github.com/flutter/flutter/issues/56603, so please follow-up in it for further updates.
Closing this as a duplicate.
