### ISSUE TITLE
I tried running my flutter app and it threw error

### ISSUE THREAD

**Issue by austinevitalis** [flutter/flutter#98852]
I ran my flutter and i got a red page error page and I have tried all the measure suggested in the log and it didnt go away. I had todowngrade flutter but it still didnt help. I will upload the screen and the github link to the app where I am working from. Thank you

https://github.com/austinevitalis/climaaa

**Comment by austinevitalis** [comment]
![WhatsApp Image 2022-02-17 at 06 57 35](https://user-images.githubusercontent.com/29200276/154903078-309c0fa3-6c14-45c3-94ee-44d8de068c35.jpeg)

**Comment by guchengxi1994** [comment]
i cloned your code but it worked without errors.
![image](https://user-images.githubusercontent.com/33513462/154912044-e49e6ef8-7bd2-4fa1-a8ca-a3f3d7e78ddf.png)
![image](https://user-images.githubusercontent.com/33513462/154912112-62a63396-15e1-48ca-9f69-f33fca101015.png)
### i think you may use a null string in this part.
![image](https://user-images.githubusercontent.com/33513462/154912238-e4bbc253-e7af-457c-8965-31bb60e19bc5.png)

**Comment by austinevitalis** [comment]
This is the error I keep getting

Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
C:\Users\AUSTINE\development\sdks\flutter\.pub-cache\hosted\pub.dartlang.org\geolocator_android-2.1.0\android\src\main\java\com\baseflow\geolocator\location\LocationMapper.java:29: error: cannot find symbol
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
                                                    ^
  symbol:   variable S
  location: class VERSION_CODES
C:\Users\AUSTINE\development\sdks\flutter\.pub-cache\hosted\pub.dartlang.org\geolocator_android-2.1.0\android\src\main\java\com\baseflow\geolocator\location\LocationMapper.java:30: error: cannot find symbol
      position.put("is_mocked", location.isMock());
                                        ^
  symbol:   method isMock()
  location: variable location of type Location
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':geolocator_android:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 17s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by darshankawar** [comment]
> 2.1.0\android\src\main\java\com\baseflow\geolocator\location\LocationMapper.java:29: error: cannot find symbol
> if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
> ^

This seem to be pointing to third party plugin, so please check that plugin's implementation or open issue in dedicated repo.

Also, the red screen error seems to be implementation issue rather than framework bug, so please ask the same on support channels like StackOverflow.
Closing from here.
