### ISSUE TITLE
Can not get the flutter 2.10.2 Release notes

### ISSUE THREAD

**Issue by haohongwei** [flutter/flutter#98858]
There is only 2.10.1 in https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel

**Comment by thomas-stockx** [comment]
Also, the wiki page references

"We intend to announce hotfixes to the [flutter-announce](https://groups.google.com/forum/#!forum/flutter-announce) group, and we recommend that you subscribe to that list if you publish an application using Flutter."

Both 2.10.1 and 2.10.2 are not (yet) announced in the flutter-announce group.

**Comment by darshankawar** [comment]
@haohongwei 
The https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel will soon get updated. Meantime you can check this link for your reference: https://github.com/flutter/flutter/releases/tag/2.10.2
I suggest you to keep an eye on hotfixes wiki for detailed information on the newest hotfix.
Closing from here.

**Comment by krispypen** [comment]
I think it's not really OK to not having a proper changelog when releasing something on your stable channel.

From what I understand the changelog is a combination of:
* https://github.com/flutter/engine/commit/a83ed0e5e3b9cd2b5e2f07ef31c72f43c55e93b7
* https://github.com/flutter/flutter/releases/tag/2.10.2 (but this only show a commit that is also reverted, so it's empty)

**Comment by fzyzcjy** [comment]
+1 Still not see changelog now :(

**Comment by darshankawar** [comment]
Could be due to the fact that there's a long weekend in the US (21 Feb, Monday) and all Flutter team would be not available. Once they are back to work, it'll hopefully be updated, so please have patience.

**Comment by fzyzcjy** [comment]
Sure. Did not realized it is long weekend before.

**Comment by krispypen** [comment]
https://groups.google.com/g/flutter-announce/c/GYHKJscFwOk/m/Gx19IeHKBwAJ 🎉
