### ISSUE TITLE
`Tooltip` doesn't dismiss when using `TooltipTriggerMode.tap`

### ISSUE THREAD

**Issue by mohsenpara** [flutter/flutter#98854]
Tooltip showDuration doesn't work with TooltipTriggerMode.tap 
When enable TooltipTriggerMode.tap , showDuration doesn't work and tooltip stay alive until another tab action!

**Comment by mohsenpara** [comment]
> flutter doctor -v

[✓] Flutter (Channel stable, 2.10.0, on macOS 11.6.3 20G415 darwin-x64, locale en-US)
    • Flutter version 2.10.0 at /Users/imohsen/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (3 weeks ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/imohsen/Library/Android/sdk
    • Platform android-31, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio Preview.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (5 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554                        • android-x64    • Android 9 (API 28)
      (emulator)
    • iPhone SE (2nd generation) (mobile)   • A2A6C505-1789-4D7E-B539-B3F1E0663CDE • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • iPhone 12 Pro Max (mobile)            • 09738AC7-A308-4257-BE89-78390B0C4ACD • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • iPhone 13 Pro Max (mobile)            • 75748311-7A3E-45C8-8BFA-303215706B0F • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)                          • chrome                               • web-javascript • Google Chrome
      92.0.4515.131
    ! Error: iMohsen is not connected. Xcode will continue when iMohsen is connected. (code -13)

[!] HTTP Host Availability
    ✗ HTTP host https://cloud.google.com/ is not reachable. Reason: Failed to connect to https://cloud.google.com/ in
      seconds

! Doctor found issues in 1 category.

**Comment by mohsenpara** [comment]
Widget build(BuildContext context) {
    return SizedBox(
      width: 80,
      height: 80,
      child: Tooltip(
        preferBelow: false,
        showDuration: Duration(seconds: 1),
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(20),
          border: Border.all(
            color: Color(0xff000000),
            width: 1,
          ),
          color: Colors.red,
        ),
        triggerMode: TooltipTriggerMode.tap,
        waitDuration: Duration(seconds: 0),
        textStyle: TextStyle(fontSize: 30),
        message: "all" +
            "\n " +
           "none",
        child: Container(
          margin: EdgeInsets.all(5),
          width: 80,
          height: 80,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(10),
            color: Colors.red,
            border: Border.all(
              color: Colors.black12,
              width: 1.0,
            ),
          ),
          alignment: Alignment.center,
          child: Text(
      "",
            style: TextStyle(fontSize: 25),
          ),
        ),
      ),
    );

**Comment by darshankawar** [comment]
@mohsenpara 
I tried your code sample on latest master and tapping on the sizedbox shows the tooltip, but not sure what exactly the issue is. Can you provide the actual vs expected behavior you are looking for after running below code sample ?

<details>
<summary> complete code sample  </summary>

```

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
          body: Center(
            child: SizedBox(
              width: 80,
              height: 80,
              child: Tooltip(
                preferBelow: false,
                showDuration: Duration(seconds: 1),
                decoration: BoxDecoration(
                  borderRadius: BorderRadius.circular(20),
                  border: Border.all(
                    color: Color(0xff000000),
                    width: 1,
                  ),
                  color: Colors.red,
                ),
                triggerMode: TooltipTriggerMode.tap,
                waitDuration: Duration(seconds: 0),
                textStyle: TextStyle(fontSize: 30),
                message: "all" +
                    "\n " +
                    "none",
                child: Container(
                  margin: EdgeInsets.all(5),
                  width: 80,
                  height: 80,
                  decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(10),
                    color: Colors.red,
                    border: Border.all(
                      color: Colors.black12,
                      width: 1.0,
                    ),
                  ),
                  alignment: Alignment.center,
                  child: Text(
                    "",
                    style: TextStyle(fontSize: 25),
                  ),
                ),
              ),
            ),
          )
      ),
    );
  }
}

```

</details>


https://user-images.githubusercontent.com/67046386/155068498-e66b87b5-0e1b-4842-9734-436315e94f95.mov



`Channel master, 2.11.0-0.0.pre.634`

**Comment by mohsenpara** [comment]
thanks for your answer
When clicking on the box, a new move must be applied to remove the tooltip from the screen

**Comment by darshankawar** [comment]
@mohsenpara 
Thanks for the update, but can you elaborate more when you says a new move must be applied to remove the tooltip ?

**Comment by mohsenpara** [comment]
> @mohsenpara
> Thanks for the update, but can you elaborate more when you says a new move must be applied to remove the tooltip ?

This is similar to the code I use in the program
Here I use two nested lists
And if you run it, you will see that it does not work properly

**Comment by mohsenpara** [comment]
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: TableBody(scrollController: ScrollController()),
    );
  }
}

class TableBody extends StatefulWidget {
  final ScrollController scrollController;

  TableBody({
    required this.scrollController,
  });

  @override
  _TableBodyState createState() => _TableBodyState();
}

class _TableBodyState extends State<TableBody> {
  // late LinkedScrollControllerGroup _controllers;
  late ScrollController _firstColumnController;
  late ScrollController _restColumnsController;

  @override
  void initState() {
    super.initState();
    // _controllers = LinkedScrollControllerGroup();
    // _firstColumnController = _controllers.addAndGet();
    // _restColumnsController = _controllers.addAndGet();
  }

  // @override
  // void dispose() {
  //   _firstColumnController.dispose();
  //   _restColumnsController.dispose();
  //   super.dispose();
  // }

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      child: SingleChildScrollView(
        // controller: widget.scrollController,
        scrollDirection: Axis.horizontal,
        //physics: ClampingScrollPhysics(),
        child: Padding(
          padding: const EdgeInsets.all(20.0),
          child: SizedBox(
            width: (10) * 80,
            child: ListView(
              // controller: _restColumnsController,
              physics: const AlwaysScrollableScrollPhysics(
                  // parent: BouncingScrollPhysics(),
                  ),
              children: List.generate(
                10,
                (y) {
                  return Padding(
                    padding: const EdgeInsets.all(8.0),
                    child: SizedBox(
                      child: Row(
                        children: List.generate(10, (x) {
                          return const Tooltip(
                              message: "ssss",
                              preferBelow: false,
                              showDuration: Duration(seconds: 1),
                              triggerMode: TooltipTriggerMode.tap,
                              waitDuration: Duration(seconds: 0),
                              textStyle: TextStyle(fontSize: 30),
                              child: Padding(
                                padding: EdgeInsets.all(8.0),
                                child: Text(
                                  "k",
                                  style: TextStyle(fontSize: 30),
                                ),
                              ));
                        }),
                      ),
                    ),
                  );
                },
              ),
            ),
          ),
        ),
      ),
    );
  }
}

**Comment by darshankawar** [comment]
Thanks for the details. I do see the same behavior as reported.

<details>
<summary> stable, master flutter doctor -v </summary>

```

[✓] Flutter (Channel stable, 2.10.2, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.10.2 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (2 days ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • iPhone 12 Pro Max (mobile)                     •
      A5473606-0213-4FD8-BA16-553433949729 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • iPad Pro (12.9-inch) (4th generation) (mobile) •
      AD9F1B85-B622-485E-97E8-E4AC866D5770 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)                                • macos
      • darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)                                   • chrome
      • web-javascript • Google Chrome 98.0.4758.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.


[✓] Flutter (Channel master, 2.11.0-0.0.pre.731, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 2.11.0-0.0.pre.731 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8f360c977a (5 hours ago), 2022-03-01 16:26:11 -0800
    • Engine revision a5718ab3c3
    • Dart version 2.17.0 (build 2.17.0-156.0.dev)
    • DevTools version 2.11.1

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • iPhone 12 Pro Max (mobile)                     •
      A5473606-0213-4FD8-BA16-553433949729 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • iPad Pro (12.9-inch) (4th generation) (mobile) •
      AD9F1B85-B622-485E-97E8-E4AC866D5770 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)                                • macos
      • darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)                                   • chrome
      • web-javascript • Google Chrome 98.0.4758.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.


```

</details>

**Comment by mohsenpara** [comment]
> 
thank you
Is this problem solvable?

**Comment by mohsenpara** [comment]
Can any one help me its very important thanks all

**Comment by bleroux** [comment]
@mohsenpara 
I will try to help you on this issue.
Using the first code sample (the one with the red square), for me, the tooltip disappears as expected after a 1 second delay. 
Here is a video where I waited for the tooltip to disappear after each tap (first tap is done at 0:03) :

https://user-images.githubusercontent.com/840911/168472757-bbb53a42-545b-46ad-aae3-a54a4e3cb9b7.mp4



The second code sample (the one with all the ‘k’ letters) seems to exhibit a real issue (multiple tooltips visible at the same time). But before going further, It would help if you confirm that, for the first sample, you see the same result that the one on my video.

**Comment by TahaTesser** [comment]
Looks like the issue is within a list view, Overlay entry doesn't dismiss when Tooltip is inside a list view.

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key, this.dark = false, this.useMaterial3 = true});

  final bool dark;
  final bool useMaterial3;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      themeMode: dark ? ThemeMode.dark : ThemeMode.light,
      theme: ThemeData(
        useMaterial3: useMaterial3,
        brightness: Brightness.light,
        colorSchemeSeed: const Color(0xff6750a4),
      ),
      darkTheme: ThemeData(
        useMaterial3: useMaterial3,
        brightness: Brightness.dark,
        colorSchemeSeed: const Color(0xff6750a4),
      ),
      home: const Example(),
    );
  }
}

class Example extends StatelessWidget {
  const Example({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Sample'),
      ),
      body: Column(
        mainAxisAlignment: MainAxisAlignment.spaceEvenly,
        children: <Widget>[
          Column(
            children: <Widget>  [
              const Text('Regaular Tooltip'),
              const SizedBox(height: 5),
              Container(
                color: Colors.green[100],
                child: const Tooltip(
                  message: 'Message',
                  preferBelow: false,
                  triggerMode: TooltipTriggerMode.tap,
                  child: Padding(
                    padding: EdgeInsets.all(8.0),
                    child: Text('Tap me - I will dismiss'),
                  ),
                ),
              ),
            ],
          ),
          Column(
            children: <Widget>[
              const Text(' Tooltip inside a ListView  '),
              const SizedBox(height: 5),
              Container(
                color: Colors.red[100],
                child: ListView(
                  shrinkWrap: true,
                  children: const <Widget>[
                    Tooltip(
                      message: 'Message',
                      preferBelow: false,
                      triggerMode: TooltipTriggerMode.tap,
                      child: Padding(
                        padding: EdgeInsets.all(8.0),
                        child: Text("Tap me - I Won't dismiss"),
                      ),
                    ),
                  ],
                ),
              ),
            ],
          )
        ],
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {},
        child: const Icon(Icons.add),
      ),
    );
  }
}

``` 
	
</details>

**Comment by bleroux** [comment]
Thanks @taha for this code sample.
After investigation, this issue can be narrowed down to gesture disambiguation.

<details>
<summary>Code sample with nested GestureDetector</summary>

```dart
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';

void main() {
  debugPrintGestureArenaDiagnostics = true;
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key, this.dark = false, this.useMaterial3 = true});

  final bool dark;
  final bool useMaterial3;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: true,
      themeMode: dark ? ThemeMode.dark : ThemeMode.light,
      theme: ThemeData(
        useMaterial3: useMaterial3,
        brightness: Brightness.light,
        colorSchemeSeed: const Color(0xff6750a4),
      ),
      darkTheme: ThemeData(
        useMaterial3: useMaterial3,
        brightness: Brightness.dark,
        colorSchemeSeed: const Color(0xff6750a4),
      ),
      home: const Example(),
    );
  }
}

class Example extends StatelessWidget {
  const Example({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Sample'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          children: <Widget>[
            Column(
              children: <Widget>[
                const Text('Regular Tooltip'),
                const SizedBox(height: 5),
                Container(
                  color: Colors.green[100],
                  child: const Tooltip(
                    message: 'Tooltip 1',
                    preferBelow: false,
                    triggerMode: TooltipTriggerMode.tap,
                    child: Padding(
                      padding: EdgeInsets.all(8.0),
                      child: Text('Tap me - I will dismiss'),
                    ),
                  ),
                ),
              ],
            ),
            Column(
              children: <Widget>[
                const Text(' Tooltip inside a GestureDetector'),
                const SizedBox(height: 5),
                Container(
                  color: Colors.red[100],
                  // Add a competing GestureDetector
                  child: GestureDetector(
                    onDoubleTap: () {},
                    child: const Tooltip(
                      message: 'Tooltip 2',
                      preferBelow: false,
                      triggerMode: TooltipTriggerMode.tap,
                      showDuration: Duration(milliseconds: 1000),
                      child: Padding(
                        padding: EdgeInsets.all(8.0),
                        child: Text("Tap me - I Won't dismiss"),
                      ),
                    ),
                  ),
                ),
              ],
            )
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {},
        child: const Icon(Icons.add),
      ),
    );
  }
}

```

</details>
