### ISSUE TITLE
Color filter layer does not support raster cache

### ISSUE THREAD

**Issue by wangying3426** [flutter/flutter#98866]
It seems that[ color filter layer ](https://github.com/flutter/engine/blob/main/flow/layers/color_filter_layer.cc#L38)still does not support raster cache, which may be affect performance.

**Comment by flar** [comment]
Is there an example of how and where this might be costing us some performance?

**Comment by wangying3426** [comment]
> Is there an example of how and where this might be costing us some performance?

We have some businesses use ColorFilter and BackdropFilter in a ListView item usually, something like https://github.com/flutter/flutter/pull/99542. If the item is complex, it sometimes drops frames while scrolling.
