### ISSUE TITLE
Flutter balance icon, showing a different image on BottomNavigationBar

### ISSUE THREAD

**Issue by Dany-Stark** [flutter/flutter#98869]
Hi!

I'm trying to use a material icon called "balance", but when rendered it shows another icon.

Flutter version 2.10.0 channel stable

import 'package:flutter/material.dart';

...

BottomNavigationBarItem(
                    icon: Icon(Icons.balance), label: 'Balance'),

expected 

![baseline_balance_black_24dp](https://user-images.githubusercontent.com/61211419/154972435-06b54c8d-fd6e-413a-b1f5-665d2403566e.png)

What I get...

![Screen Shot 2022-02-21 at 8 18 53](https://user-images.githubusercontent.com/61211419/154972670-22a667fd-93cd-47cd-aa71-ed2b2cdbb432.png)

**Comment by danagbemava-nc** [comment]
Kindly upgrade to `stable 2.10.2`. This has been fixed in that version. 

Closing as this has already been fixed. If you still experience it after the upgrade, kindly leave a comment below and I will reopen. 

Thank you
