### ISSUE TITLE
[tool_crash] SentinelException

### ISSUE THREAD

**Issue by MohaDevPro** [flutter/flutter#98860]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=emulator-5554 --start-paused --dart-define=flutter.inspector.structuredErrors=true --devtools-server-address=http://127.0.0.1:9100 lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SentinelException
```

```
```
[✓] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.18362.959], locale en-US)
    • Flutter version 2.0.4 at D:\Programs\flutter\flutter_windows_2.0.4-stable\flutter
    • Framework revision b1395592de (11 months ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:/Users/ASUS/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:/Users/ASUS/sdk
    • ANDROID_SDK_ROOT = C:\Users\ASUS\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.2.2
    • Flutter plugin version 43.0.2
    • Dart plugin version 192.8052

[✓] VS Code (version 1.61.1)
    • VS Code at C:\Users\ASUS\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 97.0.4692.99
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 98.0.1108.56

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: c5a4b4029c0798f37c4a39b479d7cb75daa7b05c
### Plugins
connectivity-3.0.6
connectivity_for_web-0.4.0
connectivity_macos-0.2.0
device_info-2.0.0
firebase_core-1.4.0
firebase_core_web-1.1.0
firebase_messaging-10.0.4
firebase_messaging_web-2.0.3
flutter_local_notifications-5.0.0+4
flutter_plugin_android_lifecycle-2.0.1
fluttertoast-8.0.7
geocoder-0.2.1
geolocator-7.4.0
geolocator_android-1.0.0
geolocator_apple-1.0.0
geolocator_web-2.0.6
google_api_headers-1.0.0
google_maps_flutter-2.0.3
image_cropper-1.4.1
image_picker-0.7.4
image_picker_for_web-2.0.0
location-2.5.4
package_info-2.0.0
path_provider-2.0.1
path_provider_linux-2.0.0
path_provider_macos-2.0.0
path_provider_windows-2.0.0
shared_preferences-2.0.6
shared_preferences_linux-2.0.0
shared_preferences_macos-2.0.0
shared_preferences_web-2.0.0
shared_preferences_windows-2.0.0
sqflite-2.0.0+3
url_launcher-6.0.3
url_launcher_linux-2.0.0
url_launcher_macos-2.0.0
url_launcher_web-2.0.0
url_launcher_windows-2.0.0

**Comment by darshankawar** [comment]
@MohaDevPro 
You are on older version of flutter. Please upgrade to latest and try again to see if you still get same exception or not.
Also, there's similar open issue in which you can refer for further updates: https://github.com/flutter/flutter/issues/78214
Closing as duplicate.
