### ISSUE TITLE
[Windows] `flutter build windows --release` should  generate a pdb file to address crash easily 

### ISSUE THREAD

**Issue by wc2411888** [flutter/flutter#98863]
There is no pdb file in the package file generated by my flutter build --release. How can I make the package published online have a pdb file so that we can solve the crash easily

**Comment by maheshmnj** [comment]
Hi @wc2411888, Thanks for filing the issue. Could you please explain what target platform are you building the app for? Also could you please share a resource about what PDB file you are referring to?

**Comment by maheshmnj** [comment]
Thanks for the update @wc2411888, This doesn't seem possible as of today and I couldn't find any resources for it too with regards to flutter.  I am labeling this issue as a proposal, for further insights from the team.

**Comment by muhleder** [comment]
In `windows\runner\CMakeLists.txt` add the line `target_link_options(${BINARY_NAME} PUBLIC /DEBUG:FULL)` and you should see a .pdb file next to your .exe file after build. There should also be a .pdb file for the engine, flutter_windows.dll.pdb file in flutter/bin/cache/artifacts/engine/windows-x64-release

**Comment by maheshmnj** [comment]
Thanks for the solution @muhleder,  @wc2411888  could you please confirm if the above helps generate the PDB file?

**Comment by wc2411888** [comment]
it works well，thanks！

**Comment by maheshmnj** [comment]
Provided your last response I feel it's safe to close the issue.

Closing as solved.
