### ISSUE TITLE
themeData is not Reflecting in the build

### ISSUE THREAD

**Issue by Voldemort373** [flutter/flutter#98872]
![image](https://user-images.githubusercontent.com/97844983/154987659-f5c60908-d583-4cdd-8dbc-c41f32e0441b.png)

**Comment by arnold-parge** [comment]
Use `ColorScheme`

```dart
ThemeData(
  colorScheme: ColorScheme(
    primary: const Color(0xffffffff), // Change to your color
    background: const Color(0xffffffff), // Change to your color
  ),
)
```

**Comment by maheshmnj** [comment]
duplicate of https://github.com/flutter/flutter/issues/89839

**Comment by darshankawar** [comment]
Use `colorScheme` to achieve the theming you require. You can read more about it here: https://api.flutter.dev/flutter/material/ColorScheme-class.html
Closing this as not an issue and this solution should help to achieve your case. If you disagree, write in comments and I'll reopen it.
