### ISSUE TITLE
pubspec.yaml packages version and pubspec.lock packages version are different 

### ISSUE THREAD

**Issue by sadaqatdev** [flutter/flutter#98877]
how can i use pubspec.yaml packages version also in pubspec.lock ,

**Comment by arnold-parge** [comment]
Take an example of the package `stream_mixin`.

If you use a package like this: `stream_mixin: ^3.0.4`, it will take the latest package equal to or above version `3.0.4`.
If you want to use the exact same version then use `stream_mixin: 3.0.4` (remove `^`).

**Comment by stuartmorgan** [comment]
Please see https://flutter.dev/community#community-grid for resources where you can get help with your project.

Closing as the issue tracker isn't intended for support questions.
