### ISSUE TITLE
SystemChrome.getPreferredOrientations

### ISSUE THREAD

**Issue by MehmetMcfly** [flutter/flutter#98875]
We already have the very useful SystemChrome.setPreferredOrientations() method, which probably all of us use. 

Recently I came across the issue of having one screen in an app that get's called from a lot of different pages and is the only one that can go landscape.

When disposing, I set the preferredOrientations back to just portraitUp, but I wanted to have a solution that is a little more flexible and just remembers the preferredOrientations before we changed it, so that I can just return it to the previous 'version' when disposing, rather than having it hardcoded.

I tried to write some native code to get the preferredOrientations, but I was unable to find out where they were stored on iOS and Android. 

Would a SystemChrome.getPreferredOrientations() method make sense/be possible/useful?

**Comment by darshankawar** [comment]
@MehmetMcfly 
I think your case is same as that of mentioned in below issues:

https://github.com/flutter/flutter/issues/95719
https://github.com/flutter/flutter/issues/74597

So please follow-up in them for further updates. Closing this in favor of above. If you disagree, write in comments and I'll reopen it.
