### ISSUE TITLE
Showing Error: Not found: 'dart:ui' in Flutter integration_test

### ISSUE THREAD

**Issue by asadbekdev** [flutter/flutter#98881]
How can  i solve this issue ?
I am running integration test with this

fvm flutter drive --driver=integration_test/test_driver/integration_driver.dart --target=integration_test/integration_test.dart --flavor dev 

![image](https://user-images.githubusercontent.com/67022917/155021086-6b8bd9b5-9302-4bef-be8c-68bc1ad316e6.png)

![image](https://user-images.githubusercontent.com/67022917/155021152-d0b9f551-65dc-4d75-b598-b1bf70a58cdd.png)

**Comment by asadbekdev** [comment]
![image](https://user-images.githubusercontent.com/67022917/155021495-708d5d3a-4db1-4348-a349-abda01f7b5c5.png)

**Comment by asadbekdev** [comment]
this is my integration test file

![image](https://user-images.githubusercontent.com/67022917/155022357-739a3051-c479-4356-80ed-d6ee0bab8d88.png)

**Comment by darshankawar** [comment]
@asadbekdev 
If your tests depends on `flutter` and not on `dart:ui`, you'll need to import `import 'package:flutter_test/flutter_test.dart';`, because `dart:ui` is not supported by integration_tests.

Closing as this is not an issue.

**Comment by asadbekdev** [comment]
Understandable Thanks!
