### ISSUE TITLE
Time picker fidelity (from gallery demo)

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#989]
(assumption: the OEM widget is correct, but that may not be the case)

OEM:

![screenshot_20151217-153128](https://cloud.githubusercontent.com/assets/5479/11885128/b698dc6a-a4d3-11e5-8b7e-93732fe930d2.png)

Flutter:

![screenshot_20151217-153336](https://cloud.githubusercontent.com/assets/5479/11885133/babc0fd8-a4d3-11e5-8a37-9355bb64f1b6.png)

Some differences I noticed:

- [x] flutter picker is larger
- [x] the selected number is black in the flutter version, white in the OEM version
- [x] AM / PM are bolder in OEM version
- [x] is the opacity the same for ":30" ? I know the background colors are different, but ":30" in the OEM version is more gray. Hard to tell...
- [x] "CANCEL" is farther away from "OK" in the Flutter version. Might be because the picker itself is larger in the Flutter one

**Comment by abarth** [comment]
Protip: If you use `- [ ]` for your bullets, they turn in checkboxes and the bug summary gets a progress indicator that shows how many of the checkboxes are checked.

**Comment by abarth** [comment]
The OEM version is a bit off spec.  I'm updating the Flutter version to better match the spec:

https://www.google.com/design/spec/components/pickers.html#pickers-time-pickers

Also, handling dark themes.

**Comment by abarth** [comment]
Fixed.
