### ISSUE TITLE
local_auth plugin: When I enable face ID in settings and when I use the authenticate function with the biometric option, I get the exception no biometric enrolled

### ISSUE THREAD

**Issue by hasinadevelop** [flutter/flutter#98907]

**Comment by darshankawar** [comment]
@hasinadevelop 
Can you provide `flutter doctor -v`, plugin version you are using and a small video of the behavior you are facing ?
Do you get the same behavior if you try the passcode instead of biometric ?

**Comment by floxydio** [comment]
are you using emulator? maybe just turn on Feature -> Face ID -> Enrolled 

if you're using real device just check if your phone support biometric or not using this function getAvailableBiometrics()

**Comment by hasinadevelop** [comment]
> @hasinadevelop Can you provide `flutter doctor -v`, plugin version you are using and a small video of the behavior you are facing ? Do you get the same behavior if you try the passcode instead of biometric ?

Thank you for your reply,
I am using version 1.1.10, below is the capture of my flutter doctor -v
![futterdoctor](https://user-images.githubusercontent.com/45894182/155092107-bb6c5c3f-23a7-4abc-9349-72cabc25beec.PNG)

Below is a screenshot of my authentication code
![code](https://user-images.githubusercontent.com/45894182/155092168-b0cd2aa2-290d-43b6-8604-f47054e24500.PNG)

Below is a video capture of the result: In parameter I recorded a face, then I put in a Toast the exception message

https://user-images.githubusercontent.com/45894182/155092257-9a3bbf9d-fae4-47a2-bc65-b63de80cd291.mp4

**Comment by hasinadevelop** [comment]
> are you using emulator? maybe just turn on Feature -> Face ID -> Enrolled
> 
> if you're using real device just check if your phone support biometric or not using this function getAvailableBiometrics()

I am using a real device with android 8. When I call getAvailableBiometrics function it returns only fingerprint, but local_auth said this function only return fingerprint with api less than 29

**Comment by darshankawar** [comment]
@hasinadevelop 
I think you are hitting https://github.com/flutter/flutter/issues/45775 wherein, I see you commented in it already. I suggest you to follow-up in it for further updates.
Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.
