### ISSUE TITLE
Custom class function property wrap try catch

### ISSUE THREAD

**Issue by yildirimbhdr** [flutter/flutter#98904]
I want create a catch management service. For this ı create CatchManagement class and  ı put function parameter in constructor but try catch in the class not trigger. 

login_page.dart
![asdasde](https://user-images.githubusercontent.com/69260315/155072756-ad4728e4-64c4-427a-a06b-4012872ed228.PNG)

user_model.dart
![rew](https://user-images.githubusercontent.com/69260315/155072813-60b5b37e-2eaa-4959-b169-54f93c7ec3f8.PNG)

catch_management.dart
![catchmanagement](https://user-images.githubusercontent.com/69260315/155072863-feb97d47-518a-48d8-a573-6c048eca5739.PNG)

**Comment by darshankawar** [comment]
@yildirimbhdr 
Your question is better suited for support channels like StackOverflow, so please ask the same there.
Closing from here as this is looks like code assistance question.
