### ISSUE TITLE
Project gets stuck on installing and running the app on physical iOS

### ISSUE THREAD

**Issue by matheus7mm** [flutter/flutter#98924]
## Steps to Reproduce

1. Execute `flutter run` on any project using my physical iPhone

**Expected results:** Install and launch the app.

**Actual results:** Get stuck on "installing and launching" on Visual Studio Code, and on "Installing to iPhone and Running Runner on iPhone" on Xcode. And the physical iPhone heats up.

<details>
<summary>Details</summary>

I am using MacBook Pro with macOS Monterey version 12.2.1 and Apple M1 chip.
The physical iPhone is iPhone 13 with iOS 15.3.1.

This problem doesn't happen with the iPhone simulators. I created a Technical Support Incident (TSI) to Apple, but they said my problem should be addressed by the support channel for Flutter.

When this problem happens, and it gets stuck in the stop I mentioned, when I go on Devices and Simulators, it says "iPhone is busy". I tried restarting the iPhone, but nothing seems to work... When I connect it to my MacBook, everything is fine, but then this "iPhone is busy" happens with it gets stuck in the process. 

```dart
```

</details>

<details>
  <summary>Logs</summary>

`flutter run --verbose`:

[flutter run verbose.txt](https://github.com/flutter/flutter/files/8117788/flutter.run.verbose.txt)

```
```

  `flutter analyze`:

[flutter analyze.txt](https://github.com/flutter/flutter/files/8117796/flutter.analyze.txt)

  
```
```

`flutter doctor -v`:

[✓] Flutter (Channel stable, 2.8.1, on macOS 12.2.1 21D62 darwin-arm, locale en-BR)
    • Flutter version 2.8.1 at /Users/matheus/development/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (10 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/matheus/development/tools/android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (3 available)
    • Matheus’s iPhone (mobile) • 00008110-001C44C00A46801E            • ios            • iOS 15.3.1 19D52
    • iPhone 13 (mobile)        • C270C73B-DAD0-428F-9A60-5DD1BE598FBE • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)              • chrome                               • web-javascript • Google Chrome 98.0.4758.102
    ! Error: Matheus’s iPhone is busy: Fetching debug symbols for Matheus’s iPhone. Xcode will continue when Matheus’s iPhone is finished. (code
      -10)

• No issues found!

```
```

</details>
<img width="1043" alt="Screen Shot 2022-02-19 at 22 20 39" src="https://user-images.githubusercontent.com/11657349/155159069-147cf072-de00-43ef-ab9f-e6721c9806a9.png">

<img width="905" alt="Screen Shot 2022-02-19 at 22 20 48" src="https://user-images.githubusercontent.com/11657349/155159150-3501c490-3db7-4c05-b38c-a4feddd8e12c.png">

**Comment by darshankawar** [comment]
> it says "iPhone is busy". I tried restarting the iPhone, but nothing seems to work... When I connect it to my MacBook, everything is fine, but then this "iPhone is busy" happens with it gets stuck in the process.

This is same as https://github.com/flutter/flutter/issues/66862, so you can follow-up in it for further updates.

For `getting stuck on installing and running`, the verbose log you provided doesn't seem to have the related logs, so can't really tell what could be causing this.
Please provide the relevant log that shows any connection timeout or when your app get stuck at `installing and running`, so we can analyze further.
