### ISSUE TITLE
i can't run fresh flutter app on android

### ISSUE THREAD

**Issue by nemixe** [flutter/flutter#98925]
## Disclaimer
i got this issue when i had android studio installed, i've been using android studio for a while before i got this issue. and  i'm trying to uninstalling android studio to save some of my storage and manually install android emulator, still facing the same issue.

## Steps to Reproduce

1. go to project folder
2. type `flutter create app_name` in this case im using name `tome`
3. type `cd tome`
4. type `flutter run`
5. error 

## Screenshot
<img width="1672" alt="Screen Shot 2022-02-22 at 22 38 23" src="https://user-images.githubusercontent.com/33045816/155169056-4048e56e-7261-40a7-bf37-2d69e65208b3.png">

## Logs

<details>
<summary>Logs</summary>

Error result :
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':app:packageDebug' (type 'PackageApplication').
> File '/Users/saidulumam/Documents/Projects/flutter/tome/android/app/~/Library/Android/Sdk/.android/debug.keystore' specified for property 'signingConfig.signingConfigData.storeFile' does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 32s
Running Gradle task 'assembleDebug'...                             33.9s
Exception: Gradle task assembleDebug failed with exit code 1
```

flutter doctor :
```
➜  tome flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.0, on macOS 12.2.1 21D62 darwin-arm, locale en-ID)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[!] Android Studio (not installed)
[✓] VS Code (version 1.64.2)
[✓] Connected device (1 available)
[✓] HTTP Host Availability

! Doctor found issues in 3 categories.
```

</details>

**Comment by nemixe** [comment]
it turns out the keystore dir is different with the one error told:
`/Users/saidulumam/Documents/Projects/flutter/tome/android/app/~/Library/Android/Sdk/.android/debug.keystore`

and the actual path is:

`/Users/saidulumam/Documents/Projects/flutter/tome/android/~/Library/Android/Sdk/.android/debug.keystore`

<img width="1792" alt="Screen Shot 2022-02-23 at 00 45 41" src="https://user-images.githubusercontent.com/33045816/155189070-f61f2fbc-8e2b-46e0-b1d0-ff15e4a3fb0b.png">

what should i do ?, should i remove the dir ?

**Comment by nemixe** [comment]
when i move it to the app folder, it creates the same folder

**Comment by darshankawar** [comment]
@nemixe 
Your question is better suited for support channels like Stackoverflow so please ask the same there.
Closing from here, as this doesn't seem to be a framework issue, but some mis configured keystore file, as the error is:

`.android/debug.keystore' specified for property 'signingConfig.signingConfigData.storeFile' does not exist.`
