### ISSUE TITLE
[webview_flutter] Expose property to bypass SSL

### ISSUE THREAD

**Issue by mdmota** [flutter/flutter#98931]
Every new version I have to copy the folder plugin and customize the android and ios delegate classes to bypass ssl.

It would be really nice if I had a property to do this work.

**Comment by danagbemava-nc** [comment]
Hi @mdmota, there's an open issue requesting the same in https://github.com/flutter/flutter/issues/36925.

Kindly follow up there for more information. 

Closing from here as duplicate. 

Thank you
