### ISSUE TITLE
flutter_web_plugins PathUrlStrategy ignores fragments

### ISSUE THREAD

**Issue by dsyrstad** [flutter/flutter#98933]
I have a Flutter web app using `setUrlStrategy(PathUrlStrategy())` to get normal-looking URLs.  I also have a [GoTrue/Supabase](https://github.com/supabase/gotrue) authentication server on the backend. GoTrue sometimes sends JWT access tokens in the fragment of the URL. For example, if I initiate a password reset, GoTrue eventually redirects back to my app with an access token, e.g.,

`http://localhost:35433/password-reset#access_token=...`

I'm using Navigator 2.0 and in my `RouteInformationParser.parseRouteInformation()` method, the `routeInformation.location` is missing the fragment (`#access_token=...`). As I mentioned, I'm using `flutter_web_plugins` with `PathUrlStrategy`.

## Steps to Reproduce

1. Clone this example repo: https://github.com/dsyrstad/flutter_path_url_strategy_bug 
2. Run `lib/main.dart` as a web app.
3. Change the URL in the browser address bar to: `http://localhost:<port>/book/2#access_token=xyzzy`

## Actual Result
The console displays: `parseRouteInformation: routeInformation.location=/book/2`. Note that the `#access_token` fragment has been lost.

## Expected Result
The fragment is part of `routeInformation.location` - i.e., `parseRouteInformation: routeInformation.location=/book/2#access_token=xyzzy` is logged in the console. By getting this information in the route parser, I can retrieve the supplied access token and proceed with resetting the user's password.

## Workaround

In the example, I have included `WebPathWithHashUrlStrategy` which is a proposed patch to `PathUrlStrategy`. In `main.dart`, comment-out `setUrlStrategy(PathUrlStrategy());` and uncomment `setUrlStrategy(WebPathWithHashUrlStrategy());` and reload the app. Load `http://localhost:<port>/book/2#access_token=xyzzy` again in the browser and note that the console displays `parseRouteInformation: routeInformation.location=/book/2#access_token=xyzzy`.

`WebPathWithHashUrlStrategy` simply changes the `PathUrlStrategy.getPath()` method to include the fragment (the "hash") in the path:

```dart
    final String path = _platformLocation.pathname +
        _platformLocation.search +
        _platformLocation.hash; // <- this is the change
```

Everything else works fine in Navigator 2.0 when using this, however the fragment must be captured during the parse phase. Somewhere in the guts of Nav 2.0, it changes the address bar and removes the fragment, so the fragment is lost downstream. 

## See also
- #80666 - now closed, seems like it was fixed on Android? 
- https://github.com/flutter/flutter/blob/master/packages/flutter_web_plugins/lib/src/navigation/url_strategy.dart#L164-L170 - the relevant Flutter code.

## Logs

<details>

```
[✓] Flutter (Channel stable, 2.10.2, on Ubuntu 21.10 5.13.0-28-generic, locale en_US.UTF-8)
    • Flutter version 2.10.2 at /home/dsyrstad/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (4 days ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/dsyrstad/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = /home/dsyrstad/Android/Sdk
    • Java binary at: /home/dsyrstad/AndroidStudio/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 13.0.0-2
    • cmake version 3.18.4
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 4.1)
    • Android Studio at /home/dsyrstad/AndroidStudio/android-studio
    • Flutter plugin version 57.0.1
    • Dart plugin version 201.9380
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[☠] IntelliJ IDEA Ultimate Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
  (... ignore...)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 21.10 5.13.0-28-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 98.0.4758.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

**Comment by darshankawar** [comment]
Thanks for the detailed report. Using the clone and running it with both renderers on latest stable and master, I do see the same behavior:

`parseRouteInformation: routeInformation.location=/book/2`

<img width="409" alt="Screenshot 2022-02-23 at 2 17 48 PM" src="https://user-images.githubusercontent.com/67046386/155286960-bd12f8bf-c8c8-4c0e-b8fa-bf9755f66a7e.png">

<details>
<summary> stable, master flutter doctor -v </summary>

```

[✓] Flutter (Channel stable, 2.10.2, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.10.2 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (2 days ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • iPhone 12 Pro Max (mobile)                     •
      A5473606-0213-4FD8-BA16-553433949729 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • iPad Pro (12.9-inch) (4th generation) (mobile) •
      AD9F1B85-B622-485E-97E8-E4AC866D5770 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)                                • macos
      • darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)                                   • chrome
      • web-javascript • Google Chrome 98.0.4758.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.


[✓] Flutter (Channel master, 2.11.0-0.0.pre.650, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.11.0-0.0.pre.650 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cddd5524d4 (3 hours ago), 2022-02-22 20:19:15 -0600
    • Engine revision ef9d407fed
    • Dart version 2.17.0 (build 2.17.0-137.0.dev)
    • DevTools version 2.11.0

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • iPhone 12 Pro Max (mobile)                     •
      A5473606-0213-4FD8-BA16-553433949729 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • iPad Pro (12.9-inch) (4th generation) (mobile) •
      AD9F1B85-B622-485E-97E8-E4AC866D5770 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)                                • macos
      • darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)                                   • chrome
      • web-javascript • Google Chrome 98.0.4758.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.


```

</details>

**Comment by yjbanov** [comment]
We currently do not plan to add new URL strategies into the core framework. However, we support custom strategies. Developers are encouraged to implement their own strategies and share them on pub.dev.

**Comment by dsyrstad** [comment]
@yjbanov This was not a request to add a new URL strategy - it was a request to fix a bug in the existing PathUrlStrategy.

**Comment by darshankawar** [comment]
@yjbanov Hi,
Based on above comment, should this be reopened ?

**Comment by darshankawar** [comment]
Reopening based on OP's feedback.

/cc @yjbanov for further insights based on OP's comment https://github.com/flutter/flutter/issues/98933#issuecomment-1064422487

**Comment by dsyrstad** [comment]
@yjbanov I disagree. This problem was fixed on Android and iOS to support deep linking with fragments: [#80666 ](https://github.com/flutter/flutter/issues/80666) and PR https://github.com/flutter/engine/pull/26185. Without fixing this bug, mobile handles deep linking with fragments, but web does not.

**Comment by dsyrstad** [comment]
@yjbanov No response? @darshankawar  You're just marking it as invalid when there is a clear inconsistency between the mobile and web platforms?
