### ISSUE TITLE
Framework's matchesGoldenFile should assert that file name has right structure

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#98943]
https://github.com/flutter/flutter/pull/98772 broke the tree because the file name provided to matchesGoldenFile was missing `.png`. We should assert that file names have the right structure - maybe even that they are unique at least for the given file?

incorrect:
```dart
matchesGoldenFile('slider_start_text_scale_1_width_0'),
```

correct:
```dart
matchesGoldenFile('slider_start_text_scale_1_width_0.png'),
```

**Comment by hterkelsen** [comment]
The fix was reverted here: https://github.com/flutter/flutter/pull/99075
