### ISSUE TITLE
It takes 20s for our build process to build nothing

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#9896]
```
$ flutter run
[...]
$ flutter run
[...]
Total time: 19.934 secs
[...]
```

It should not take 20s it build an app that hasn't changed.

**Comment by sethladd** [comment]
Same or similar to https://github.com/flutter/flutter/issues/7673 ?

**Comment by Hixie** [comment]
Same. I apparently really care about this issue. :-)

**Comment by sethladd** [comment]
I experienced the same problem, which is why I keep tabs on it :)
