### ISSUE TITLE
> I managed to make it work after commenting out the flavors in `app/build.gradle`

### ISSUE THREAD

**Issue by VroyCLe-Niranjan** [flutter/flutter#98969]
> I managed to make it work after commenting out the flavors in `app/build.gradle`
> 
> ```
>     // productFlavors {
>     //     debug {
>     //         dimension "default"
>     //         applicationIdSuffix ".debug"
>     //     }
>     //     staging {
>     //         dimension "default"
>     //         applicationIdSuffix ".staging"
>     //     }
>     //     prod {
>     //         dimension "default"
>     //     }
>     // }
> ```
> 
> The output was rightfully built in `build/app/outputs/apk/debug/app-debug.apk.`
> 
> Of course I'm not commiting these to source control. It's just until there isn't a fix.
> 
> Not a definitive solution, but at least I can work.

I have no flavours at all in my build.gradle.  This may be 'a' cause of this issue, but it is not 'the' cause.   We really need a fix on the all the critical stability issues for this platform.

_Originally posted by @ArtfulDodgerB92 in https://github.com/flutter/flutter/issues/44796#issuecomment-612299477_

**Comment by danagbemava-nc** [comment]
I'm going to assume this was opened accidentally and close this issue. 

If you have an actual issue to report, kindly file a new issue and provide the information requested in the template. If you are going to reference a closed issue, you should still provide the information requested in the template. 

Closing as this issue doesn't provide any information. 

Thank you
