### ISSUE TITLE
Android "cold" builds take around a minute for even basic apps

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#9897]
The basic_material_app__size build_time_millis benchmark now hovers between 50 and 70 seconds. That seems really excessive for a basic "Hello World" app.

**Comment by mit-mit** [comment]
Looks like we are closer to 35 seconds last few days, potentially due to the switch to gradle wrapper?

**Comment by asaarnak** [comment]
The gain could also be the upgrade to gradle 3.3 and new android gradle 2.3.3 plugin.

The new Android Gradle plugin should help performance futher:
https://developer.android.com/studio/preview/features/new-android-plugin.html#performance
"The main focus of this version is to address the build performance issues of Android projects with a large number of modules."

**Comment by Hixie** [comment]
Looks like this is down to about 20 seconds now. Closing.
