### ISSUE TITLE
[Android] Copy paste is not working when copying text from some other application

### ISSUE THREAD

**Issue by Mevasir** [flutter/flutter#98983]
## Steps to Reproduce

1, Create new Flutter Project
2. Copy text from Samsung Notes
3. Try paste it to text field in Flutter app

**Expected results:**
It should paste text to the text field.
It works in one of my older Flutter apps that built in 2020 and it also worked before in my other Flutter app, .
This also works in other apps that do not use Flutter.

**Actual results:**
Now it shows Paste button but it doesn't do anything.
Tested this also in new example app and also other computer where I have other Flutter app.

No issues found from flutter doctor.

Tested in Samsung Galaxy S8 (Android 9) and Galaxy S9.

**Comment by maheshmnj** [comment]
Hi @Mevasir, Thanks for filing the issue, Does this issue occur only when copying text from Samsung notes or in general from other apps too? Are you able to paste the copied text in non-samsung apps (e.g chrome)?
Please share the output of `flutter doctor -v`.

**Comment by Mevasir** [comment]
Only when I'm copying text from Samsung notes or Samsung email (I haven't tested other Samsung apps) to Flutter app. Chrome and gmail works fine.

Here's output of flutter doctor -v

```
[√] Flutter (Channel stable, 2.10.2, on Microsoft Windows [Version 10.0.19043.1526], locale fi-FI)
    • Flutter version 2.10.2 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (11 days ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Mevasir\AppData\Local\Android\sdk
    • Platform android-31, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30523.141
    • Windows 10 SDK version 10.0.17763.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3
    • Flutter plugin version 54.0.3
    • Dart plugin version 203.7759

[√] VS Code (version 1.64.2)
    • VS Code at C:\Users\Mevasir\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.17.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1526]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 98.0.4758.102
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 95.0.1020.30

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by maheshmnj** [comment]
Thanks for the update @Mevasir I suspect if Samsung restricts accessing clipBoard data captured from the Samsung app in 
other apps. 
Can you please try copying data from Samsung apps and try passing it to other apps (non-Samsung)? 

> Are you able to paste the copied text in non-samsung apps (e.g chrome)?

**Comment by Mevasir** [comment]
I tested copying data from Samsung notes and passing it to chrome, gmail, signal etc. and it works fine.
