### ISSUE TITLE
Email validation is allow accent

### ISSUE THREAD

**Issue by lucascorrea31** [flutter/flutter#98986]
I need to add RegExp to avoid this bug, like this:

```
if (!GetUtils.isEmail(value) ||
        RegExp(r'[!#<>?":`~;[\]\\|=+)(*&^%áàâãéèêíïóôõöúçñÁÀÂÃÉÈÍÏÓÔÕÖÚÇÑ]')
            .hasMatch(value)) {
throw error;
}
```

# Test should be return error, but pass as valid
```
      expect(
        Email.create('história@historia.com').left,
        isA<ValueTypeDomainError>(),
      );
```

Maybe this can be updated on this function isEmail(s);

**Comment by stuartmorgan** [comment]
Issues with third-party packages need to be reported to the developers of those packages, not the Flutter team.
