### ISSUE TITLE
flutter tool needs to be able to handle pub, curl, etc, failing with transient errors

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#9898]
We regularly see the flutter tool triggering `pub get`, `curl`, and other network requests that fail due to transient network problems (typically 500, 502, 503, but also DNS errors, network errors, etc).

We should make the tool display a message saying that there's been a network issue and then have it retry a bunch of times before giving up, whenever there's a network error.

**Comment by skybrian** [comment]
Also consider IDE users on a slow connection. We usually pop up a console window but not always.

It seems like there should be an option for progress and failure events to be machine-readable, so we can plug it into progress bars and error dialogs.

**Comment by Hixie** [comment]
See also https://github.com/flutter/flutter/issues/10764 which is specifically about our tests that use `pub`.

**Comment by Hixie** [comment]
Keywords that I sometimes use to search for this: pub flaky, download network error, retry...

**Comment by Hixie** [comment]
I sort of did this. Going to close in favour of more specific bugs if there's anything left to do.
