### ISSUE TITLE
Flutter imports are not case sensitive.

### ISSUE THREAD

**Issue by AbhishekDoshi26** [flutter/flutter#98993]
## Summary of Issue:
Recently encountered an issue which depicts that flutter's imports are not case sensitive. So for Flutter Engine:
`import 'package:test_project/screens/home.dart';` and `'package:test_project/Screens/home.dart';` are same which is totally incorrect. Now if the user imports as 2nd option, other services like firebase Hosting, Docker, GitHub actions, fail as they all are case sensitive and for them, this import will be undefined.

In one sentence, my folder name is `screen` and I imported it with `Screen` and still it works without any issues!

## Steps to Reproduce

1. Create a new project with main.dart as the basic file
2. Create another folder called screens and inside that create a file called home.dart
3. Import the file in main.dart and change the import to have it `Screen\home.dart` instead of `screen\home.dart`

**Expected results:** Dart Analyzer should throw an error for import not found as `Screen` and `screen` should be 2 different folders.

**Actual results:** It works! No errors, no warnings!

**Found on:** macOS 12.2.1, Flutter version 2.8.1 as well as 2.10.2, Dart version 2.15.1 as well as 2.16.1
<details>
<summary>Code sample</summary>

#### main.dart
```
import 'package:flutter/material.dart';
import 'package:test_project/Screens/home.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Material App',
      home: Home(),
    );
  }
}


```

#### home.dart
```
import 'package:flutter/material.dart';

class Home extends StatelessWidget {
  const Home({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}


```
</details>

<details>
  <summary>Logs</summary>

#### flutter run
```
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             12.5s
This app is linked to the debug service: ws://127.0.0.1:60085/QgzYCoQNVzo=/ws
Debug service listening on ws://127.0.0.1:60085/QgzYCoQNVzo=/ws

💪 Running with sound null safety 💪

🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".

An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:60085/QgzYCoQNVzo=
The Flutter DevTools debugger and profiler on Chrome is available at: http://127.0.0.1:9104?uri=http://127.0.0.1:60085/QgzYCoQNVzo=

```

#### flutter analyze

```
Analyzing test_project...                                               
No issues found! (ran in 1.5s)
```

#### flutter doctor -v

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.2.1 21D62 darwin-arm, locale en-GB)
    • Flutter version 2.8.1 at /Users/abhishekdoshi/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (10 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/abhishekdoshi/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 98.0.4758.102

• No issues found!
```

</details>

**Comment by timsneath** [comment]
I suspect this is working as intended. macOS has a case-insensitive file system (by default). Most Linux file systems are case sensitive. Dart Analyzer wouldn't prompt with an error on macOS, because the path you reference exists.

**Comment by craiglabenz** [comment]
To add to what @timsneath said, Dart aims to behave the same across all operating systems, so it had to pick one (case sensitive or insensitive) and go with it everywhere.

**Comment by AbhishekDoshi26** [comment]
> 

Agreed. So then how can we synchronise between pipelines and flutter?

**Comment by craiglabenz** [comment]
I think it is best to pretend that case-sensitivity will be enforced everywhere and always try to match cases on macOS, too. I admit that this does create a possible gotcha where you accidentally mis-type the casing somewhere and are in for a surprise when your code hiccups on Linux; but that is also how other systems behave when spanning multiple OS's.

**Comment by AbhishekDoshi26** [comment]
We should atleast have a lint rule which warns the users to not use upper case in imports at all.

have added the [issue](https://github.com/dart-lang/sdk/issues/48461#issuecomment-1049054805) in dart-sdk repo too.

**Comment by maheshmnj** [comment]
Hi @AbhishekDoshi26, Thanks for filing the issue. This is working as intended based on how the underlying OS treats the file systems.   However,  Effective Dart suggests using lower camelcase for libraries, packages, directories, and source files. 

To effectively deal with this issue, you could use the existing linter rule `library_names` and `file_name` which would warn if the naming convention does not comply with the dart style. Wouldn't this work for your use case?
You could read more about it in the [effective dart style guide](https://dart.dev/guides/language/effective-dart/style#do-name-libraries-and-source-files-using-lowercase_with_underscores)
