### ISSUE TITLE
FirebaseAuth startup crash in memechat

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#9899]
## Steps to Reproduce

Run the latest [memechat app](https://github.com/efortuna/memechat) on Android.

Crash in the logs:

AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.yourcompany.memechat/com.yourcompany.memechat.MainActivity}: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.yourcompany.memechat. Make sure to call FirebaseApp.initializeApp(Context) first.

This is looks like either a misconfiguration or a FirebaseAuth startup race condition. I'm investigating.

/cc @emshack @efortuna

**Comment by collinjackson** [comment]
Fixed in efortuna/memechat#14

**Comment by kroikie** [comment]
@collinjackson

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1011. Any further collaboration will be done there.
