### ISSUE TITLE
Avoid FLX file generation.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#9900]
FLX files were created for reasons that don't seem to be important anymore. However, having assets in a compressed archive within the application bundle (which itself is compressed when delivered via the stores anyway) adds overhead when accessed. In this trace attached below, to locate the asset in the compressed archive and copy it out takes about 4.5ms. We should consider not generating FLX files and packaging the assets directly in the application bundle.

![screen shot 2017-05-08 at 2 25 42 pm](https://cloud.githubusercontent.com/assets/44085/25826396/96be6fc8-33fb-11e7-9833-42fbc4f61e57.png)

**Comment by sethladd** [comment]
I wonder what kinds of wins we'll get on:

* build tool simplification
* build times
* improvements on using platform tools/patterns like APK splitting: https://developer.android.com/studio/build/configure-apk-splits.html

**Comment by sethladd** [comment]
head's up @mit-mit @devoncarew

**Comment by tvolkert** [comment]
Asset variants currently aren't wired up correctly inside Google because we hand-rolled our own FLX building, and it got stale (asset variant file layout has since been redone a few times).  Removing FLX would simplify things a lot on that front too.

**Comment by mit-mit** [comment]
@chinmaygarde would this also enable https://github.com/flutter/flutter/issues/11892 ?

**Comment by Hixie** [comment]
@szakarias is making great progress on this.
This is a top priority for the current milestone.

**Comment by szakarias** [comment]
The work for iOS and Android is done, will keep this open once all the FLX related code is removed.

**Comment by szakarias** [comment]
Closing this and tracking the final FLX cleanup in  #15338.
