### ISSUE TITLE
Example code for adding an image doesn't actually show the image

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#9901]
I just learnt how to add an image to my app from https://flutter.io/assets-and-images/.

After pasting the example code from the "Loading images" section into my app, the app didn't actually show an image (I think I now understand why that is). It might be more useful/satisfying to include code in the example that actually shows the image when copied to get people started quicker. I ended up using `new Image.asset('assets/sunset.jpg')` to verify that the image would actually load in my app.

**Comment by goderbauer** [comment]
This is what my `build` method looks like:

```dart
  @override
  Widget build(BuildContext context) {
    return  new Image.asset('assets/sunset2.jpg');
  }
```

**Comment by HansMuller** [comment]
Perhaps if the assets-and-images section pointed at a small working "sample app" in addition to providing code fragments, you'd have had less trouble (https://github.com/flutter/flutter/pull/9912).

**Comment by LarkAscending** [comment]
Talking w/ @goderbauer root cause is the parent of the Image widget needs to actually have a size in order to display the image. So the code snippet for the build() method needs to include a parent-with-size.

**Comment by Hixie** [comment]
The `Image` widget should size itself to the size of the image by default.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1826](https://github.com/flutter/website/issues/1826) via [**ZenHub**](https://www.zenhub.com/)
