### ISSUE TITLE
Bad state: Cannot add new events after calling close,  IOSDeviceLogReader.debuggerStream= > _BroadcastStreamController.add 

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#99021]
Flake during `new_gallery_ios__transition_perf`
```
[new_gallery_ios__transition_perf] [STDOUT] stdout: [        ] Application launched on the device. Waiting for observatory url.
[new_gallery_ios__transition_perf] [STDOUT] stderr: 
[new_gallery_ios__transition_perf] [STDOUT] stderr: Bad state: Cannot add new events after calling close
[new_gallery_ios__transition_perf] [STDOUT] stderr: #0      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:243:24)
[new_gallery_ios__transition_perf] [STDOUT] stderr: #1      IOSDeviceLogReader.debuggerStream=.<anonymous closure> (package:flutter_tools/src/ios/devices.dart:719:41)
[new_gallery_ios__transition_perf] [STDOUT] stderr: #2      _rootRunUnary (dart:async/zone.dart:1434:47)
[new_gallery_ios__transition_perf] [STDOUT] stderr: #3      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
[new_gallery_ios__transition_perf] [STDOUT] stderr: #4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
[new_gallery_ios__transition_perf] [STDOUT] stderr: #5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
...
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8821893964124656433/+/u/run_new_gallery_ios__transition_perf/test_stdout

Similar to stack at https://github.com/flutter/flutter/issues/16183#issuecomment-381556455

**Comment by jmagman** [comment]
Probably a regression from #98550?

**Comment by jmagman** [comment]
The only way I could see this happening is a narrow race where a new log line comes in, then the process exits before the log line is processed.

Exit, stdout controller cancelled, but is currently processing a log line:
https://github.com/flutter/flutter/blob/cef682363736079ab0eebbe4675d96ca46c78124/packages/flutter_tools/lib/src/ios/ios_deploy.dart#L398-L401
Stream controller closed:
https://github.com/flutter/flutter/blob/cef682363736079ab0eebbe4675d96ca46c78124/packages/flutter_tools/lib/src/ios/ios_deploy.dart#L404-L407
But inside the stdout controller the log line is finally added, even though the `stdout` listener block should be cancelled (and no more log lines, because the debugger has exited)
https://github.com/flutter/flutter/blob/cef682363736079ab0eebbe4675d96ca46c78124/packages/flutter_tools/lib/src/ios/ios_deploy.dart#L387

**Comment by christopherfujino** [comment]
should we `await stdoutSubscription.cancel()`?

**Comment by jmagman** [comment]
That's my thought, I already have a patch, now how to test...

**Comment by jmagman** [comment]
Hm, this still seems to be happening.  https://github.com/flutter/flutter/pull/99041 merged on Feb 24, but here's a test showing it from March 4
https://ci.chromium.org/p/flutter/builders/prod/Mac_ios%20animation_with_microtasks_perf_ios__timeline_summary/2016
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8820587852994788209/+/u/run_animation_with_microtasks_perf_ios__timeline_summary/test_stdout

**Comment by jmagman** [comment]
Causing a few tests to flake, raising priority.

**Comment by jmagman** [comment]
I'm OOO starting tomorrow, @christopherfujino is taking this over.

**Comment by Hixie** [comment]
Increasing priority to match that of blocked issues.
