### ISSUE TITLE
[Material 3] Update Dialogs to Material 3 design

### ISSUE THREAD

**Issue by darrenaustin** [flutter/flutter#99025]
![image](https://user-images.githubusercontent.com/19588/155408886-0b60c778-ae53-47bf-aad8-7eaff2c1771a.png)

As part of the migration to [Material Design 3](https://m3.material.io/), the `Dialog` and `AlertDialog` widgets need to be updated to the latest design spec:

https://m3.material.io/components/dialogs/overview

**Comment by TahaTesser** [comment]
Hey @darrenaustin 
Could this https://github.com/flutter/flutter/pull/98919 be considered for this?

**Comment by darrenaustin** [comment]
> Hey @darrenaustin Could this #98919 be considered for this?

Indeed it can. 😄 I just haven't had a chance to review it yet. Thx!
