### ISSUE TITLE
Update chips to support Material 3

### ISSUE THREAD

**Issue by darrenaustin** [flutter/flutter#99024]
![image](https://user-images.githubusercontent.com/19588/155408560-b77befef-6471-47f7-ab18-cba17dcbbd8a.png)

As part of the migration to [Material Design 3](https://m3.material.io/), the `Chip` widgets need to be updated to the latest design spec:

https://m3.material.io/components/chips/overview

**Comment by TahaTesser** [comment]
@darrenaustin @HansMuller 

I have some ideas and progress on these ideas in the works, please let me know if I can this

1. First of all, `chip.dart` is very long, and requires a lot of digging to make any changes. 
Keep `RawChip` and its code in `chip.dart` and move other independent chips into separate classes like material buttons.
2. Migrate `RawChip` to use new defaults, M2 and M3, each changes shape and text style, etc.
3. Add chips with new names in newly created classes such as `chip_suggestion.dart` and `chip_assist.dart.

**Comment by TahaTesser** [comment]
@guidezpl 
Do you have any thoughts?

**Comment by guidezpl** [comment]
I'm not super familiar with chips, though I know they are fairly complex and would benefit from re-engineered to get rid of bugs (e.g. filter chips change size when selected due to border disappearing).

**Comment by HansMuller** [comment]
If it's possible to get add the support for Material 3 without creating classes that should really be private within chip.dart, then breaking chip.dart into separate files sounds OK.

CC @darrenaustin

**Comment by TahaTesser** [comment]
> If it's possible to get add the support for Material 3 without creating classes that should really be private within chip.dart, then breaking chip.dart into separate files sounds OK.

My PR only moves  `ActionChip`, `ChoiceChip`, `FilterChip`, and `InputChip`  widgets to separate classes just like `TextButton`, `ElevatedButton`, etc.

I will file another PR to add support for Material 3 in `chip.dart` for `RawChip`. Which not only updates `RawChip` for Material 3 but also helps to migrate other existing chips and new chips `SuggestionChip` and `AssistChip` (these will be in separate class because of my refactor PR.

**Comment by TahaTesser** [comment]
Main reason I am doing this since migration code and `SuggestionChip` and `AssistChip`  will make already bloated `chip.dart` even more bloated cross 4k+ lines.

**Comment by HansMuller** [comment]
What about ElevatedButton? Or a TextButton configured with an opaque backgroundColor?

**Comment by cedvdb** [comment]
Sure, I can use a container or a material with border radii and colors as well.

My comment was aimed at the fact that this is, in material designs Figma file, a Chip component.

**Comment by TahaTesser** [comment]
> Migrate RawChip to use new defaults, M2 and M3, each theme changes shape, text style, etc.


Updating Chip to support Material 3 (WIP)


![Screenshot 2022-05-25 at 15 05 04](https://user-images.githubusercontent.com/48603081/170258000-f16e8345-3abd-4a8c-b4c6-bedb8c7defb4.png)

**Comment by darrenaustin** [comment]
Fixed with #99024
