### ISSUE TITLE
Analyzer failing on Excellent news! A package dependency has been removed! cli_util

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#99036]
Tree is closed on unrelated PR https://github.com/flutter/flutter/pull/98604
https://ci.chromium.org/p/flutter/builders/prod/Linux%20analyze/6101?

All analyzer checks are passing, but the output ends with:
```
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Excellent news! A package dependency has been removed!
  cli_util
To make sure we do not accidentally add this dependency back in the future,
please remove this packages from the allow-list in dev/bots/allowlist.dart.
Thanks!
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```
Guessing that "excellent news" is an unexpected output and is being interpreted as failing?

**Comment by jmagman** [comment]
I ran `flutter update-packages --force-upgrade` but all the `pubspec.lock`s still contain `cli_util`...

**Comment by jmagman** [comment]
This is coming from 
https://github.com/flutter/flutter/blob/87fe3fe03149fc14b70c4c3daf37e9a4b17d49fe/dev/bots/analyze.dart#L1569-L1571

https://github.com/flutter/flutter/blob/54a9d652828941dbebbe8de32cf667e89578b13d/packages/flutter_tools/lib/src/commands/update_packages.dart#L78-L80

So it's not about our package lock files, it's about the consumer-facing packages.
I see traffic from @devoncarew removing this dep like https://dart-review.googlesource.com/c/sdk/+/232423 so this looks expected.

**Comment by christopherfujino** [comment]
Thanks for fixing this @jmagman. The reason this test failed out of band, rather than on an update packages roll is https://github.com/flutter/flutter/issues/91757.

**Comment by devoncarew** [comment]
> I see traffic from @devoncarew removing this dep like https://dart-review.googlesource.com/c/sdk/+/232423 so this looks expected.

@jmagman - thanks for the fix in https://github.com/flutter/flutter/pull/99037! I didn't realize that reducing deps would break CIs.

**Comment by jmagman** [comment]
> I didn't realize that reducing deps would break CIs.

Neither did I, at least it was cheery "Excellent news!" 😄
