### ISSUE TITLE
Error: The method 'toDouble' was called on null.

### ISSUE THREAD

**Issue by mishadynin** [flutter/flutter#9903]
## Steps to Reproduce

Code to reproduce available upon request.

## Logs

[bug.txt](https://github.com/flutter/flutter/files/985003/bug.txt)

## Flutter Doctor

[doctor.txt](https://github.com/flutter/flutter/files/985006/doctor.txt)

**Comment by Hixie** [comment]
Fixed by https://github.com/flutter/flutter/pull/9905
