### ISSUE TITLE
[Impeller] Fix path rendering artifacts for disabled tests.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#99032]
These tests were newly added in https://github.com/flutter/impeller/pull/24. They are currently disabled.

**Comment by dnfield** [comment]
Calling `CubicPathSmoothenRecursive(approx, points, {234.592, 125.977},{207.708, 135.753},{192.381, 141.429},{222.206, 130.435}, 0)` results in non-sensical points.

**Comment by dnfield** [comment]
See https://fiddle.skia.org/c/f8a6756be77709a909cc2ca8553c5270 - it seems like impeller isn't handling MoveTo commands quite correctly for this case (if you comment out the moveTo and close (which inserts a moveTo in Skia) commands Skia starts to look like impeller).

**Comment by dnfield** [comment]
I think this is related to impeller not handling `MoveTo` quite correctly. I'm not sure how that could ever be expressed as a single polyline,without some sentinel value in the polyline to indicate a move. See for example this test:

```cpp
TEST_F(EntityTest, SimpleStrokeWithMove) {
  // Compare with https://fiddle.skia.org/c/a75d5da581da6b9683d846f7ad6911dc
  Path path =
      PathBuilder{}
          .MoveTo({10, 10})
          .LineTo({10, 210})
          .LineTo({210, 210})
          .LineTo({210, 10})
          .Close()
          .MoveTo({100, 100})
          .LineTo({50, 100})
          .LineTo({50, 150})
          .Close()
          .TakePath();

  Entity entity;
  entity.SetPath(path);
  auto contents = std::make_unique<SolidStrokeContents>();
  contents->SetColor(Color::Red());
  contents->SetStrokeSize(5.0);
  entity.SetContents(std::move(contents));
  ASSERT_TRUE(OpenPlaygroundHere(entity));
}
```

**Comment by dnfield** [comment]
(There seems to be some other issue with the stroke building up to its width as well instead of being consistently at 5.0)

**Comment by dnfield** [comment]
Paths will need to keep track of move components.

**Comment by dnfield** [comment]
From offline discussion: it seems reasonable to change `CreatePolyline` on path to be a `std::vector<PolylinePointStruct> where PolylinePointStruct has some more information about whether the point is intending to pick up the pen or not.

**Comment by bdero** [comment]
The stoke problems are a known issue and on the todo. It doesn't handle capping yet and we don't track stroke direction, so the vertices will often get mapped wrong. MoveTo is definitely new/unknown though.
