### ISSUE TITLE
Bot refusing to land PR due to mystery "changes requested"

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#99033]
https://github.com/flutter/plugins/pull/4448#issuecomment-1049281535 is a live example of an issue I've seen once before where the boy refuses to land a PR saying that I have requested changes on it, even though my current status is a simple approval.

Last time I tried re-approving, this time I tried finding every open conversation and marking it as resolved (which we should absolutely not require if they predate the last approval because it's a huge pain, but I thought I'd give it a try), and neither one makes a difference.

For now the only workaround I know of is to land manually. Is there an override mechanism here? If not, this is a blocker for enforcing bot submission.

I can leave this PR unlanded for a couple of days for investigation.

**Comment by godofredoc** [comment]
Is this working as expected? The bot will refuse to land a PR and will remove the label if the person requesting changes hasn't explicitly approved the PR

**Comment by stuartmorgan** [comment]
As you can see in the event log there, I have approved it. And I'm the person the bot is claiming requested changes. And as I said above the last time this happened I tried approving again just in case and it made no difference.

This would obviously be expected behavior if I hadn't approved it, but that's not what's happening.

**Comment by stuartmorgan** [comment]
@godofredoc Have you had a chance to analyze this yet? I'd like to land the PR soon.

**Comment by godofredoc** [comment]
No yet, but let me do it. It will take me a couple of hours.

**Comment by godofredoc** [comment]
From logs nothing seem wrong: 

```
Is pull request #4448 mergeable: MERGEABLE
Error
2022-02-25 08:11:25.605 PST
Validating name: plugins, branch: pull/4448, status: [{context: submit-queue, state: SUCCESS, targetUrl: }]
Error
2022-02-25 08:11:25.605 PST
Validating name: plugins, branch: pull/4448, checks: [{name: ci.yaml validation, status: COMPLETED, conclusion: SUCCESS, detailsUrl: https://flutter-dashboard.appspot.com}, {name: Windows win32-platform_tests master, status: COMPLETED, conclusion: SUCCESS, detailsUrl: https://ci.chromium.org/b/8821403099602602929}, {name: Windows win32-platform_tests stable, status: COMPLETED, conclusion: SUCCESS, detailsUrl: https://ci.chromium.org/b/8821403099602602913}, {name: Windows windows-build_all_plugins master, status: COMPLETED, conclusion: SUCCESS, detailsUrl: https://ci.chromium.org/b/8821403099602602897}, {name: Windows windows-build_all_plugins stable, status: COMPLETED, conclusion: SUCCESS, detailsUrl: https://ci.chromium.org/b/8821403099602602881}, {name: Windows uwp-platform_tests master, status: COMPLETED, conclusion: SUCCESS, detailsUrl: https://ci.chromium.org/b/8821403099602602865}, {name: Windows plugin_tools_tests, status: COMPLETED, conclusion: SUCCESS, detailsUrl: https://ci.chromium.org/b/8821403099985985521}]
```

**Comment by godofredoc** [comment]
I'll add more logging to the authors validation

**Comment by godofredoc** [comment]
This is the review data:

```
"reviews": {
                                    "nodes": [
                                        {
                                            "author": {
                                                "login": "cyanglaz"
                                            },
                                            "authorAssociation": "MEMBER",
                                            "state": "CHANGES_REQUESTED"
                                        },
                                        {
                                            "author": {
                                                "login": "cyanglaz"
                                            },
                                            "authorAssociation": "MEMBER",
                                            "state": "CHANGES_REQUESTED"
                                        },
                                        {
                                            "author": {
                                                "login": "stuartmorgan"
                                            },
                                            "authorAssociation": "MEMBER",
                                            "state": "CHANGES_REQUESTED"
                                        },
                                        {
                                            "author": {
                                                "login": "cyanglaz"
                                            },
                                            "authorAssociation": "MEMBER",
                                            "state": "CHANGES_REQUESTED"
                                        },
                                        {
                                            "author": {
                                                "login": "cyanglaz"
                                            },
                                            "authorAssociation": "MEMBER",
                                            "state": "APPROVED"
                                        },
                                        {
                                            "author": {
                                                "login": "stuartmorgan"
                                            },
                                            "authorAssociation": "MEMBER",
                                            "state": "CHANGES_REQUESTED"
                                        },
                                        {
                                            "author": {
                                                "login": "stuartmorgan"
                                            },
                                            "authorAssociation": "MEMBER",
                                            "state": "CHANGES_REQUESTED"
                                        },
                                        {
                                            "author": {
                                                "login": "stuartmorgan"
                                            },
                                            "authorAssociation": "MEMBER",
                                            "state": "CHANGES_REQUESTED"
                                        },
                                        {
                                            "author": {
                                                "login": "stuartmorgan"
                                            },
                                            "authorAssociation": "MEMBER",
                                            "state": "CHANGES_REQUESTED"
                                        },
                                        {
                                            "author": {
                                                "login": "stuartmorgan"
                                            },
                                            "authorAssociation": "MEMBER",
                                            "state": "APPROVED"
                                        }
                                    ]
                                }
                            },

```

**Comment by godofredoc** [comment]
There is an error in the logic here: https://github.com/flutter/cocoon/blob/main/app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart#L413

This is from the new logs `PR approved false, approvers: {cyanglaz}, change request authors: {stuartmorgan}`

**Comment by godofredoc** [comment]
OK, the issue is that graphql is returning only the first 5 code reviews and this specific PR has 10. @CaseyHillers what would be the impact of increasing this to 30?

**Comment by CaseyHillers** [comment]
The code reviews should be fine to increase. It's interesting to see that is the history of code reviews and not the current state. Maybe there's a different way we should pull that information in?

**Comment by stuartmorgan** [comment]
> [...] increasing this to 30?

Shouldn't we set it to something arbitrarily high (e.g., 1000)? Since the newest reviews are at the end, any case where we don't get the entire list we are essentially guaranteed to get the wrong behavior.

**Comment by godofredoc** [comment]
@CaseyHillers 
If we could rely on code review enforcement using the org configs maybe we could get the state as a single value but with the current configs is not possible.

@stuartmorgan
Most of the graphql APIs have a max limit of 100 values per page but we have been tweaking those values because are hitting the limits of graphql and there is an increasing number of timeouts when executing the queries.

**Comment by godofredoc** [comment]
Alternatively we can get the last 30 instead of the first 30

**Comment by godofredoc** [comment]
By the way we are pulling the approved and changes_requested ones `reviews(first: 30, states: [APPROVED, CHANGES_REQUESTED])`

**Comment by CaseyHillers** [comment]
> Shouldn't we set it to something arbitrarily high (e.g., 1000)? Since the newest reviews are at the end, any case where we don't get the entire list we are essentially guaranteed to get the wrong behavior.

GitHub's GraphQL API has a hard timeout of 10 seconds to process a request.

When the graph becomes large, there's more edges that have to be checked for possible nodes. Unfortunately, setting excessive values will increase the traversal time and likely hit a timeout. While plugins is really small, engine and the framework will likely hit issues. Generally, GraphQL nodes should be limited to 100
