### ISSUE TITLE
module_test_ios failing, "Could not find any supported simulator runtimes"

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#99039]
As of https://github.com/flutter/flutter/pull/98297 that test is running on Xcode 13a233 and should be grabbing `ios_runtime` simulator runtimes from cipd https://github.com/flutter/flutter/issues/91689

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8821388884257231665/+/u/run_module_test_ios/test_stdout
```
[module_test_ios] [STDOUT] stdout:         Underlying Errors:
[module_test_ios] [STDOUT] stdout:             Description: Could not find any supported simulator runtimes
```

`list simulators` shows no simulators:
```
== Runtimes ==
== Devices ==
```

In the `install Xcode` step it only shows installation from `flutter_internal/ios/xcode/mac` and `flutter_internal/ios/xcode/ios` but not [`ios_runtime`](https://chrome-infra-packages.appspot.com/p/flutter_internal/ios/xcode/ios_runtime/+/) 
```
[P22871 17:11:36.330 action_plan.go:174 I]     flutter_internal/ios/xcode/mac (8cf87f9a7d8b31aa99d303dcd9c0277dbc91198c -> UCaNcftiBhJwpRpc5DUfKSIw8COAV-Tys6P58EzPEykC)
[P22871 17:11:36.330 action_plan.go:174 I]     flutter_internal/ios/xcode/ios (41641f55a9654db87d73faf1d316fe71cf7df5d7 -> rWdxdSMwqPafHwtN9Uh77do6HVmD6iVatO_XNPbfHvEC)
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8821388884257231665/+/u/install_xcode/stdout

It's supposed to look like successful run https://ci.chromium.org/p/flutter/builders/prod/Mac_ios%20flutter_gallery_ios__start_up/3680
```
== Runtimes ==
iOS 15.0 (15.0 - 19A339) - com.apple.CoreSimulator.SimRuntime.iOS-15-0
```

Maybe the `mac_toolchain` running in staging isn't the one that knows how to handle default runtimes? https://flutter-review.googlesource.com/c/recipes/+/23980 & https://github.com/flutter/flutter/issues/94780

/cc @godofredoc @keyonghan

**Comment by keyonghan** [comment]
The `mac_toolchain` in staging does use the [latest version](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8821388884257231665/+/u/ensure_installed/json.output), same as prod ones:
```
"instance_id": "Lmnduk3ULUqIVoSwGka-yEiHkb_6pBo6RpJXIoXtS6IC", 
```
CIPD version list: https://chrome-infra-packages.appspot.com/p/infra/tools/mac_toolchain/mac-amd64/+/

**Comment by jmagman** [comment]
Here's an example of a led engine builder run that shows what this should look like when there's an Xcode cache miss:
```
Packages:
  flutter_internal/ios/xcode/ios_runtime:xbExNWHTJfpNf8vDNXhmLNx9sjfFvAl4ed74gTrXl3cC
[P92814 19:01:12.305 action_plan.go:160 I] In root:
[P92814 19:01:12.305 action_plan.go:166 I]   to install:
[P92814 19:01:12.305 action_plan.go:168 I]     flutter_internal/ios/xcode/ios_runtime:xbExNWHTJfpNf8vDNXhmLNx9sjfFvAl4ed74gTrXl3cC
[P92814 19:01:12.305 client.go:1655 I] Dry run, not actually doing anything.
[P92815 19:01:13.007 action_plan.go:160 I] In root:
[P92815 19:01:13.007 action_plan.go:166 I]   to install:
[P92815 19:01:13.007 action_plan.go:168 I]     flutter_internal/ios/xcode/ios_runtime:xbExNWHTJfpNf8vDNXhmLNx9sjfFvAl4ed74gTrXl3cC
[P92815 19:01:13.007 instancecache.go:187 I] Using instance cache at /opt/s/cipd_cache/cache/instances
[P92815 19:01:13.009 client.go:1594 I] [fetch] Resolving fetch URL for flutter_internal/ios/xcode/ios_runtime:xbExNWHTJfpNf8vDNXhmLNx9sjfFvAl4ed74gTrXl3cC
```

https://logs.chromium.org/logs/flutter/led/magder_google.com/34b0add45b8fe97daadbfb8f634b2426c6fdea1e39c03af96488ca5ff59eb6f2/+/u/install_xcode/stdout

**Comment by jmagman** [comment]
That one is using `L7ipPezGFZNueu6j99coF-PbUIE6l-bUXDK5mHNOOoQC` maybe they changed the behavior?

**Comment by jmagman** [comment]
And it passed as a try job from https://github.com/flutter/flutter/pull/99009 so what's up with staging? https://ci.chromium.org/p/flutter/builders/try/Mac%20module_test_ios/12059

**Comment by keyonghan** [comment]
This is strange.. Try and staging have exactly the same configs..

**Comment by jmagman** [comment]
Maybe we just need to be explicit that we want that runtime? https://github.com/flutter/flutter/pull/99093

**Comment by keyonghan** [comment]
One difference is the mac os version: staging bots are all with 12.0.1 whereas try bots are with 12.2. Will this cause the different behaviors?

**Comment by jmagman** [comment]
> staging bots are all with 12.0.1 whereas try bots are with 12.2 

I don't think that should matter, the mac_toolchain just isn't pulling in the default runtime.
https://g3doc.corp.google.com/company/teams/chrome/ios/docs/infra/xcode_upload.md?cl=head#upload-ios-runtimes

> iOS builders will use the default runtime from the Xcode used for building. iOS testers will dynamically download (or read from cache) the runtime it needs during task.

See also https://source.chromium.org/chromium/infra/infra/+/main:go/src/infra/cmd/mac_toolchain/README.md

**Comment by godofredoc** [comment]
> > staging bots are all with 12.0.1 whereas try bots are with 12.2
> 
> I don't think that should matter, the mac_toolchain just isn't pulling in the default runtime. https://g3doc.corp.google.com/company/teams/chrome/ios/docs/infra/xcode_upload.md?cl=head#upload-ios-runtimes
> 
> > iOS builders will use the default runtime from the Xcode used for building. iOS testers will dynamically download (or read from cache) the runtime it needs during task.
> 
> See also https://source.chromium.org/chromium/infra/infra/+/main:go/src/infra/cmd/mac_toolchain/README.md

This is because the devicelab builds use a different recipe module that does not have support for runtimes. We'll need to copy https://cs.opensource.google/flutter/recipes/+/main:recipe_modules/osx_sdk/api.py to https://cs.opensource.google/flutter/recipes/+/main:recipe_modules/devicelab_osx_sdk/api.py and fix the destination folder to `/opt/flutter/xcode/%s/XCode.app`

**Comment by jmagman** [comment]
> This is because the devicelab builds use a different recipe module that does not have support for runtimes.

But the recipe shouldn't need to handle downloading the default runtime, `mac_toolchain` does it.  We would only need the recipe change if we needed to add additional runtimes.  Which we shouldn't if it was behaving correctly and the default iOS 15 one was being installed...

**Comment by jmagman** [comment]
Like this:

> Here's an example of a led engine builder run that shows what this should look like when there's an Xcode cache miss:
> 
> ```
> Packages:
>   flutter_internal/ios/xcode/ios_runtime:xbExNWHTJfpNf8vDNXhmLNx9sjfFvAl4ed74gTrXl3cC
> [P92814 19:01:12.305 action_plan.go:160 I] In root:
> [P92814 19:01:12.305 action_plan.go:166 I]   to install:
> [P92814 19:01:12.305 action_plan.go:168 I]     flutter_internal/ios/xcode/ios_runtime:xbExNWHTJfpNf8vDNXhmLNx9sjfFvAl4ed74gTrXl3cC
> [P92814 19:01:12.305 client.go:1655 I] Dry run, not actually doing anything.
> [P92815 19:01:13.007 action_plan.go:160 I] In root:
> [P92815 19:01:13.007 action_plan.go:166 I]   to install:
> [P92815 19:01:13.007 action_plan.go:168 I]     flutter_internal/ios/xcode/ios_runtime:xbExNWHTJfpNf8vDNXhmLNx9sjfFvAl4ed74gTrXl3cC
> [P92815 19:01:13.007 instancecache.go:187 I] Using instance cache at /opt/s/cipd_cache/cache/instances
> [P92815 19:01:13.009 client.go:1594 I] [fetch] Resolving fetch URL for flutter_internal/ios/xcode/ios_runtime:xbExNWHTJfpNf8vDNXhmLNx9sjfFvAl4ed74gTrXl3cC
> ```
> 
> https://logs.chromium.org/logs/flutter/led/magder_google.com/34b0add45b8fe97daadbfb8f634b2426c6fdea1e39c03af96488ca5ff59eb6f2/+/u/install_xcode/stdout

**Comment by keyonghan** [comment]
Played around a bit with runtime via led:
By specifying the runtime_version:`ios-14-0` ('$flutter/osx_sdk={"sdk_version": "13a233", "runtime_versions": ["ios-14-0"] }'), it installed the correct runtime, and the runtime shows up in `list simulators`: https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/4c5ed369b54fe8780f4d6ee9c1db3df0003bd79654b54e114f68377547ab7555/+/build.proto

When using runtime_version: `ios-15-0` (`'$flutter/osx_sdk={"sdk_version": "13a233", "runtime_versions": ["ios-15-0"] }'`), it installed the runtime, but the runtime doesn't show up in `list simulators`: https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/bde43be1da39029643243b283b1284c04be99a9ebf2bc6b539f3d31c85b708f8/+/build.proto

Does this suggest something wrong this the `ios-15-0` version?

**Comment by keyonghan** [comment]
The test was enabled in `prod` moments ago, and is running well. So the issue happens only in staging...

**Comment by keyonghan** [comment]
Based on the observation the only difference is the mac bot version.. I requested an os upgrade in [crbug.com/1300948](https://bugs.chromium.org/p/chromium/issues/detail?id=1300948), just in case (we need to upgrade to 12.2 any way).

**Comment by godofredoc** [comment]
Bad caches of the xcode cipd package coming from tests while the package was created?

**Comment by CaseyHillers** [comment]
Duping this against https://github.com/flutter/flutter/issues/99429. Upgrading the bots is another way of doing a cache flush.

**Comment by jmagman** [comment]
This seems to be happening again https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20build_tests_2_4/18290/overview

**Comment by godofredoc** [comment]
Some updates here:

The current logic for managing runtimes is faulty:

* If the runtime folder inside xcode is  a symlink is not being deleted, instead it is deleting the destination folder from the cache leaving a symlink point to a non existent directory.

**Comment by keyonghan** [comment]
One data point: the runtime issue started happening on bot: [build842-m9](https://chromium-swarm.appspot.com/bot?id=build842-m9) after a failed build: https://luci-milo.appspot.com/ui/p/flutter/builders/try/Mac%20module_test/14975/overview on `Install gems` step (03/24).

**Comment by keyonghan** [comment]
@godofredoc is working on a fix:
https://flutter-review.googlesource.com/c/recipes/+/28680 landed
https://flutter-review.googlesource.com/c/recipes/+/28684 to be landed

**Comment by godofredoc** [comment]
https://flutter-review.googlesource.com/c/recipes/+/28684
