### ISSUE TITLE
Failed assertion: line 4234 pos 12: '_lifecycleState != _ElementLifecycle.defunct': is not true.

### ISSUE THREAD

**Issue by amalmohann** [flutter/flutter#99049]
I've encountered an error which says

`Failed assertion: line 4234 pos 12: '_lifecycleState != _ElementLifecycle.defunct': is not true.`

![image](https://user-images.githubusercontent.com/15846660/155462512-e318fab4-d059-41a5-8c9d-0f2eeeffb580.png)

I came across this issue when I tried to change the state in dispose() method.

> @override
      void dispose() {
        setState(() => _successErrorLoader = "");
        setState(() => _ackMessage = "");
     }
     
I want to do some state changes when an component is unmounted (removed from the screen). Please provide any alternative solution or a fix for this error.

**Comment by maheshmnj** [comment]
Hi @amalmohann, Thanks for filing the issue. You generally get this error if you try to call setState after `dispose`. To prevent this error you could put a check

```
if(mounted){
  setState((){});
}
```

In case you need further help please try asking questions on support forums like StackOverflow. Closing as this is neither a bug nor a feature request.
