### ISSUE TITLE
[web]SelectableText allows user to select multiple lines 

### ISSUE THREAD

**Issue by mafreud** [flutter/flutter#99047]
When I use it on the web, it highlights multiple lines. I would like to highlight only one place, what should I do?

## Steps to Reproduce
```dart
class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
          SelectableText('hi'),
          SelectableText('This is a test.'),
          SelectableText('Test sample message'),
          ],
        ),
      ),
    );
  }
}
```
<img width="626" alt="スクリーンショット 2022-02-24 13 22 50" src="https://user-images.githubusercontent.com/28733986/155457605-8464d96c-286b-44a4-b6df-a9de85445da3.png">

**Comment by maheshmnj** [comment]
Hi @mafreud, I am quite not sure I understood your question, In case you want to highlight only one string then wrap only that string in Selectable and rest in Text widget.

```dart
Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
          Text('hi'),
          SelectableText('Only this text can be selected.'),
          Text('Test sample message'),
          ],
        ),
      ),
```

Closing as this is neither a bug nor a feature request. In case you need further help with your code. Please try asking on StackOverflow with a proper sample code and you might get some help.
