### ISSUE TITLE
Cirrus presubmit customer_testing-Linux is taking >30 minutes, needs sharding?

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#99043]
Sometimes the long-pole of presubmission tests.  Not sure why the test is taking >30 minutes on Cirrus but 15-20 minutes in LUCI.
https://cirrus-ci.com/task/6127876452909056

https://ci.chromium.org/p/flutter/builders/try/Linux%20customer_testing/28770?
https://ci.chromium.org/p/flutter/builders/try/Linux%20customer_testing/28771?

**Comment by jmagman** [comment]
@Hixie may be interested in investigating 🙂

**Comment by Hixie** [comment]
Presumably the Luci bots are just better computers?

FWIW this is eminently shardable. There's a script that runs it, which could easily be extended to do the sharding.

**Comment by keyonghan** [comment]
Cirrus has been deprecated from our CI. Closing as obsolete.
