### ISSUE TITLE
[material][icons] pie_chart_outlined icon name changed

### ISSUE THREAD

**Issue by Lorenzohidalgo** [flutter/flutter#99059]
The latest update of Flutter v2.10.2 introduces a change in the name of the following icon:
- `Icons.pie_chart_outlined` no longer exists (https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Apie_chart%3A)
- `Icons.pie_chart_outline_outlined` seems to replace it (https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Apie_chart%3A)

I'm not sure if this is an intended change since the `pie_chart_outline` icon seems does not change/adapt to the rest of the styles.
If this is an intended change the ID `pie_chart_outlined` should continue working since it is the one referenced in the icon library.

**Comment by danagbemava-nc** [comment]
Hi @Lorenzohidalgo, 

> since the pie_chart_outline icon seems does not change/adapt to the rest of the styles.

I'm not sure I fully understand this. Can you provide a bit more detail as to what you mean?

**Comment by Lorenzohidalgo** [comment]
Hi @danagbemava-nc , the icon `pie_chart_outline` is the same for all of its versions (outlined, rounded, sharp) check out this [dart pad](https://dartpad.dev/?id=e6eb47c5350107cb0b0abcbd0c15f875) example.

**Comment by danagbemava-nc** [comment]
Hi @Lorenzohidalgo, it's the same on the material.io site. Take a look at the recording below.


https://user-images.githubusercontent.com/88313112/155934691-948794cb-1171-4baa-b568-31021a4f7aa5.mov

**Comment by Lorenzohidalgo** [comment]
Hi @danagbemava-nc, I'm aware of that, but the identifier for the pie chart outlined in flutter `pie_chart_outlined` does no longer exist.

What I meant by:
> If this is an intended change the ID pie_chart_outlined should continue working since it is the one referenced in the icon library.

Was that if like you are mentioning this is an intended change, then they should be treated as two different icons and the identifier `pie_chart_outlined` should continue working since it's the referenced id in the [font library](https://fonts.google.com/icons?selected=Material+Icons+Outlined:pie_chart:).

**Comment by danagbemava-nc** [comment]
Hi @Lorenzohidalgo, thanks for the clarification. 

/cc @guidezpl on whether or not this is an intended change

**Comment by guidezpl** [comment]
https://github.com/flutter/flutter/pull/96115 removes `Icons.pie_chart_outlined`, includes a dart fix for the correct name `Icons.pie_chart_outline`. The other "variants" of `pie_chart_outline` are a harmless artefact.

All variants can thus be accessed thusly:

```
      Icon(Icons.pie_chart),
      Icon(Icons.pie_chart_outline),
      Icon(Icons.pie_chart_rounded),
      Icon(Icons.pie_chart_sharp),
```

**Comment by Lorenzohidalgo** [comment]
@guidezpl, just to confirm, `Icons.pie_chart_outlined` won't be added back? The reference to `pie_chart_outlined` is still used in the [font library](https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Apie_chart%3A).

**Comment by guidezpl** [comment]
Correct, the next update to fonts.google.com will refresh all the Flutter identifiers
