### ISSUE TITLE
How could we know whether the application is using uses-material-design or not?

### ISSUE THREAD

**Issue by Tamilarasan-Paranthaman** [flutter/flutter#99053]
We need to draw the custom icon when the uses material design is set as false in the application. So, we set uses material design as false. But we still get the icon data in our source. how could we know whether application is using uses-material-design as false?

**Comment by maheshmnj** [comment]
Hi @Tamilarasan-Paranthaman, Thanks for filing the issue. Have you tried the solutions on this [StackOverflow thread](https://stackoverflow.com/questions/23613279/access-to-pubspec-yaml-attributes-version-from-dart-app) which allows you to read pubspec.yaml attributes?  

In my opinion if you want to perform some operation based on the value of `pubspec.yaml` considering pubspec cannot be manipulated in the run time. I think you should try passing arguments to your flutter app using [dart define](https://dartcode.org/docs/using-dart-define-in-flutter/)
