### ISSUE TITLE
dyld: Library not loaded: @rpath/App.framework/App

### ISSUE THREAD

**Issue by ChannelYu** [flutter/flutter#99051]
I'm trying to follow [Option B in this article](https://docs.flutter.dev/development/add-to-app/ios/project-setup) to add flutter to my app: 
 * run `cd some_path1`
 * run `flutter create --template module my_flutter_module`
 * run `cd my_flutter_module `
 * run `flutter build ios-framework --xcframework --no-universal --output=some_path2`(No need to change anything in my_flutter_module folder)
 * create an empty app using XCode, set app's minimum deployment target to iOS 11.0
 * embed Debug/App.xcframework & Debug/Flutter.xcframework to project

Then I tested the app on my real devices. It worked fine on iPhone12 Pro (iOS 15.2) and iPhone 11 (iOS 14.3).
**But it crashed on iPhone 6 Plus(iOS 12) & iPhone 6s(iOS 12)** 

Here is the crash snapshot:
<img width="973" alt="crash" src="https://user-images.githubusercontent.com/7424823/155475457-8fd0f43a-01e7-4473-af27-eb16fadc6128.png">

`flutter doctor -v`:
<img width="731" alt="doctor" src="https://user-images.githubusercontent.com/7424823/155475574-b53a88e9-07e0-4467-a891-4101dad58de3.png">

**By the way, if i embedded Release/App.xcframework & Release/Flutter.xcframework to project instead, it worked fine on all my devices.** 

I don't know why it's not working on iOS 12 if i use Debug/App.xcframework & Debug/Flutter.xcframework☹️

**Comment by danagbemava-nc** [comment]
Hi @ChannelYu, you appear to be on an older version of flutter. 

Can you upgrade to the latest version of `stable` to see whether or not you still experience this issue? If you do, please provide the updated `flutter doctor -v` and possibly a small sample repo we can use to reproduce this.

Thank you

**Comment by ChannelYu** [comment]
> Hi @ChannelYu, you appear to be on an older version of flutter.
> 
> Can you upgrade to the latest version of `stable` to see whether or not you still experience this issue? If you do, please provide the updated `flutter doctor -v` and possibly a small sample repo we can use to reproduce this.
> 
> Thank you

It works fine on my sample while I'm using 2.5.3 version. 

But in a real project I can't update flutter arbitrarily, it's not my call.

Although this problem doesn't bother me too much and I don't know much about compilation, I try to figure it out. Could you give me some help?

**Comment by danagbemava-nc** [comment]
> It works fine on my sample while I'm using 2.5.3 version.

Then the issue has likely been fixed

> Could you give me some help?

Unfortunately, this is not my domain of expertise so I cannot offer any help there. 

Given that the issue does not reproduce on a more recent version of flutter, I'm going to have to close this issue. 

If you run into this issue in a more recent version of flutter, don't hesitate to file a new issue. 

Thank you
