### ISSUE TITLE
The link address of the flutter web project page cannot be opened by accessing it alone

### ISSUE THREAD

**Issue by haoxuhong** [flutter/flutter#99055]
页面链接打不开我知道是#号的原因了，加上#号就能打开了，现在有个问题：

我自己项目中微信授权登录后跳转到首页因为首页链接有#号获取不到#号后面的参数。
我的想法是能不能首页使用去除#号，其它页面带#号，这种的怎么实现？

现在只能做到要么项目所有页面链接都带#号，要么都不带#号，如何实现某个页面不带#号，其它页面带#号呢？

_translated using Google translate_

The page link can't be opened. I know the reason for the # sign. It can be opened by adding the # sign. Now there is a problem:

In my own project, after WeChat authorized login, I jumped to the home page because the home page link has a #, and I cannot get the parameters behind the #.
My idea is whether the first page can be used to remove the ##, and other pages have the ##. How to achieve this?

Now it can only be done that either all page links of the project are marked with #, or none of them have #. How to realize that a certain page does not have a #, and other pages have a #?

**Comment by maheshmnj** [comment]
Hi @haoxuhong, Thanks for filing the issue. 

> How to realize that a certain page does not have a #, and other pages have a #?

Please ask support questions on community forums like StackOverflow. You might also get some help if you post with sufficient code and an explanation of what you have tried.

Closing as this is neither a bug nor a feature request. In case you disagree, feel free to write in the comments and we will reopen it.

Thank you.
