### ISSUE TITLE
[WINDOWS] .webp images not showing

### ISSUE THREAD

**Issue by DominicOrga** [flutter/flutter#99054]
On my app I'm displaying some `.webp` images using `Image.asset()`. Unfortunately, on Windows these images do not appear. 

In addition, after doing some tests I found that everything works fine when using `.png` assets.

**Expected results: Screen from web app** 

<img width="1497" alt="Screen Shot 2022-02-24 at 3 07 17 PM" src="https://user-images.githubusercontent.com/12520299/155477902-fa154d6b-2543-4c4d-ade6-c71b6b74efe4.png">

**Actual results: Screen from Windows app** 

<img width="1476" alt="Screen Shot 2022-02-24 at 2 58 24 PM" src="https://user-images.githubusercontent.com/12520299/155477941-a569f9eb-b331-4db2-a68e-135f1e392671.png">

**Comment by DominicOrga** [comment]
Here's the result of `flutter doctor -v`. Note that I am only building this app on a secondary Windows device and my objective is to generate a Windows build for the app.
<details>

```
[√] Flutter (Channel stable, 2.10.2, on Microsoft Windows [Version 10.0.19042.1466], locale en-PH)
    • Flutter version 2.10.2 at C:\Users\Raphael\Documents\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (5 days ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32210.238
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.64.2)
    • VS Code at C:\Users\Raphael\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.1466]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 95.0.4638.69
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 98.0.1108.56

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

<\details>

**Comment by maheshmnj** [comment]
Hi @DominicOrga, Thanks for filing the issue. Do you see any error logged to the console when the image fails to load? Have you tried loading other image assets to ensure this happens with a specific image or all images? 

Would it be possible for you to share a reproducible image to have a look?  

Thanks

**Comment by DominicOrga** [comment]
Hi @maheshmnj, after testing it today the .webp images are now appearing. Not sure what caused the issue last time which may be a technical glitch on my test device, but if it re-occurs I'll let you know. Thanks!
