### ISSUE TITLE
Example App - Shrine error

### ISSUE THREAD

**Issue by tombirmingham** [flutter/flutter#9906]
[analyze-1.txt](https://github.com/flutter/flutter/files/985134/analyze-1.txt)
## Steps to Reproduce

Ran flutter run for flutter_gallery.  Then selected Shrine and got error.

## Logs

See attached files.

## Flutter Doctor

C:\Users\Tom\GitHub\flutter\examples\flutter_gallery>flutter doctor
[√] Flutter (on Microsoft Windows [Version 10.0.14393], channel alpha)
    • Flutter at c:\Users\Tom\flutter
    • Framework revision ffa8483f3b (7 days ago), 2017-05-01 14:18:00 -0700
    • Engine revision da8ebf40bd
    • Tools Dart version 1.23.0-dev.11.11

[√] Host Executable Compatibility
    • Downloaded executables execute on host

[√] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at C:\Users\Tom\AppData\Local\Android\sdk
    • Platform android-25, build-tools 25.0.2
    • Java binary at: C:\Program Files\Android\Android Studio Preview\jre\bin\java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-736)

[√] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Android Studio (version 2.4)
    • Android Studio at C:\Program Files\Android\Android Studio Preview
    • Gradle version 3.4.1
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-736)

[√] Connected devices
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 7.1.1 (API 25) (emulator)
[issue-1.txt](https://github.com/flutter/flutter/files/985133/issue-1.txt)

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by jason-simmons** [comment]
The exception stack trace:

I/flutter ( 4129): The following assertion was thrown building ShrinePage(dirty; state: ShrinePageState#669912407()):
I/flutter ( 4129): type 'double' is not a subtype of type 'int' of 'elevation' where
I/flutter ( 4129):   double is from dart:core
I/flutter ( 4129):   int is from dart:core
I/flutter ( 4129):
I/flutter ( 4129): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 4129): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 4129): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 4129):   https://github.com/flutter/flutter/issues/new
I/flutter ( 4129):
I/flutter ( 4129): When the exception was thrown, this was the stack:
I/flutter ( 4129): #0      AppBar.AppBar (package:flutter/src/material/app_bar.dart:160)
I/flutter ( 4129): #1      ShrinePageState.build (file:///C:/Users/Tom/GitHub/flutter/examples/flutter_gallery/lib/demo/shrine/shrine_page.dart:93)
I/flutter ( 4129): #2      StatefulElement.build (package:flutter/src/widgets/framework.dart:3234)
I/flutter ( 4129): #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3144)

Try switching to the master branch.  The elevation parameter should consistently be a double now.

**Comment by tombirmingham** [comment]
Was on the master but now tried the alpha, and it works!

**Comment by tombirmingham** [comment]
Downloaded master right now from GitHub.  Same error occurs.

BTW - I shouldn't have Closed this Issue myself, that is for others.  I reopened it.

**Comment by tombirmingham** [comment]
Whoops, checked where I was launching Flutter and Flutter_gallery and it was both from the Alpha branch.  So all is OK.  Same goes for Issue #9910.  Can be Closed.
