### ISSUE TITLE
PlatformException(no_fragment_activity, local_auth plugin requires activity to be a FragmentActivity., null, null)

### ISSUE THREAD

**Issue by NIkos77-cloud** [flutter/flutter#99062]
PlatformException(no_fragment_activity, local_auth plugin requires activity to be a FragmentActivity., null, null)

## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by danagbemava-nc** [comment]
Your `MainActivity` class in your `MainActivity.java` or `MainActivity.kt` needs to extends `FlutterFragmentActivity`.

There's an already open issue in https://github.com/flutter/flutter/issues/81127 that seeks to address the documentation issue in the README of the package.

Kindly follow up there for more information. 

Closing as duplicate

**Comment by NIkos77-cloud** [comment]
Thank you so much for your help
I have fixed this issue
