### ISSUE TITLE
auto-submit bot landing changes with failures in packages and plugins 

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#99077]
There are two things to highlight:

* The cirrus status check was missing
* There was a cirrus failure

https://github.com/flutter/packages/pull/965

**Comment by godofredoc** [comment]
\cc @stuartmorgan

**Comment by fkorotkov** [comment]
> for a same commit, is it possible to return different builds belonging to different branches?

Yes, if you create a branch called `foo` in `flutter/flutter` and then create a PR out of it, then there will be two builds: one for `foo` branch and another for PR #N with "fake" branch name `pull/N`. Before order of builds returned from `searchBuilds` was undetermenistic but I just changed it to be in chronological order so the PR builds will be first.

**Comment by keyonghan** [comment]
Thanks @fkorotkov for the explanations.
So is it a safe assumption that the FIRST build based on latest commit of a PR will always reflect the true tests statuses of the PR (regardless of branches)?

**Comment by fkorotkov** [comment]
Yes. 👌
