### ISSUE TITLE
"unlock login keychain" task infra failed: The specified keychain is not a valid keychain file.

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#99076]
https://ci.chromium.org/p/flutter/builders/prod/Mac_ios%20large_image_changer_perf_ios/3694
```
security: SecKeychainUnlock login.keychain: The specified keychain is not a valid keychain file.
```

**Comment by godofredoc** [comment]
@keyonghan @yusuf-goog is this a newly provisioned machine?

**Comment by keyonghan** [comment]
No. It has been running all the time, and is now running with a success consistently (after this failure). Looking through the recent ~100 runs, only hit this issue once.

**Comment by godofredoc** [comment]
This may be a race condition with salt deleting and regenerating the keychain every time there are new changes in salt.

**Comment by CaseyHillers** [comment]
After monitoring this week, I haven't seen it repeat. I'm going to move this out of the ticket queue.

**Comment by godofredoc** [comment]
Closing as obsolete.
