### ISSUE TITLE
Mac test ignoring `os` field on prod task, ran on newer version of macOS

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#99087]
`Mac web_tool_tests` ran on a macOS 12 machine, even though `.ci.yaml` specifies Mac-10.15.
https://github.com/flutter/flutter/blob/37a1aaf8c11a2963f066427089d8dd3709a4a48d/.ci.yaml#L3077-L3078

https://ci.chromium.org/p/flutter/builders/prod/Mac%20web_tool_tests/5034

https://chromium-swarm.appspot.com/task?id=5946338c72923b10&o=true&w=true
Task dimensions shows:
```
          {
            "key": "os",
            "value": "Mac-12"
          },
```

Note it failed due to https://github.com/flutter/flutter/issues/98278 which seems to only reproduce on macOS 12, which is how I noticed this.

**Comment by jmagman** [comment]
@keyonghan

**Comment by jmagman** [comment]
More:
https://ci.chromium.org/p/flutter/builders/prod/Mac%20web_tool_tests/5026
https://ci.chromium.org/p/flutter/builders/prod/Mac%20web_tool_tests/5028
https://ci.chromium.org/p/flutter/builders/prod/Mac%20web_tool_tests/5030
https://ci.chromium.org/p/flutter/builders/prod/Mac%20web_tool_tests/5031

**Comment by keyonghan** [comment]
I am afraid this is expected. For post-submit builders, their configs will be auto-rolled after it's merged. Let me double check.

**Comment by jmagman** [comment]
How long does it usually take to auto-roll, that config change happened 21 hours ago https://github.com/flutter/flutter/pull/98297

**Comment by keyonghan** [comment]
The culprit is here: https://flutter.googlesource.com/infra/+/refs/heads/main/config/lib/ci_yaml/ci_yaml.star#315
It only reads the platform os value, ignoring target level os property.

**Comment by keyonghan** [comment]
https://flutter-review.googlesource.com/c/infra/+/27401 to fix.

**Comment by keyonghan** [comment]
New os version is picked up: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20web_tool_tests/5037/overview, but it seems still using new xcode version.. https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20web_tool_tests/5037/overview

**Comment by keyonghan** [comment]
@CaseyHillers IIRC, the properties will be merged among platform and target. Is the xcode version defined in target level expected to be auto rolled?

**Comment by CaseyHillers** [comment]
It looks like `def _properties(ci_yaml, target, default_properties = {}, repo = None, branch = None):` in the starlark needs to be updated

It should pull from the merged _properties instead of the platform

**Comment by keyonghan** [comment]
https://flutter-review.googlesource.com/c/infra/+/27420 to override with target level property.

**Comment by keyonghan** [comment]
Changes populated, and test is validated to run on expected test beds.
