### ISSUE TITLE
[go_router] how to redirect without pushing

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#99096]
copied from https://github.com/csells/go_router/issues/388

I'm trying to redirect to the previous page if query params are not provided but it pushes the previous screen on top of the current screen.
Route Stack: [ /, /chat_list ]
Pushing new route /chat without query param. The route stack should be as [ /, /chat_list ]
But route stack is [ /, /chat_list, /chat_list ]

```dart
GoRoute(
        path: '/chat_list',
        builder: (context, state) {
          return BlocProvider(
              create: (BuildContext context) => injector<ChatBloc>()
                ..add(GetChatEvent(user.id)),
              child: const ChatListPage());
        },
        routes: [
          GoRoute(
            path: 'chat',
            redirect: (state){
              if(state.queryParams.containsKey('chat_id')) {
                return null;
              } else {
                return '/chat_list';
              }
            },
            . . .
```

**Comment by johnpryan** [comment]
I can't reproduce this. Here's the sample I used:

```dart
```

**Comment by chunhtai** [comment]
Closed as not reproducible, feel free to reopen if you think otherwise

**Comment by johnpryan** [comment]
@II11II I think you originally filed this issue, can you take a look at my comment?
