### ISSUE TITLE
Using twoLevelSubList to build an expandable but non-scrollable list

### ISSUE THREAD

**Issue by vy0592** [flutter/flutter#9909]
We want to use twoLevelSublist inside non scrollable views like Listbody instead of twoLevelList. But it looks like the current implementation of twoLevelSublist requires its parent must be TwoLevelList. Is there any plans to make twoLevelSubList  a standalone widget so it can be used to build expandable but non-scrollable lists?

**Comment by eseidelGoogle** [comment]
We also have expansion panels, I'm not sure if that helps your use case or not:
https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/material/expansion_panels_demo.dart

**Comment by DaveShuckerow** [comment]
For some extra context, Vicky, myself, and @Hixie had a conversation yesterday:

> Vicky
> is there anyway to separate the scrollable and expand/collapse behavior in twoLevelList? Like having a expandable but not scrollable list?
> Ian
> hm, interesting question
> yup, looks like you can just use TwoLevelSublist directly
> TwoLevelList is just a ListView around the list of TwoLevelLists you pass in
> if you replace TwoLevelList with a ListBody it should just work
> around the list of TwoLevelSublists, that is
> 
...
Some implementation later revealed that TwoLevelSublist cannot be used in this fashion.

Being able to separate the scrolling behavior of TwoLevelList and the expandable list behavior of TwoLevelList would be valuable from a framework flexibility perspective.
