### ISSUE TITLE
[Impeller][Compiler] support more types in vertex stage inputs

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#99091]
Today, using a type like `float` or `int` results in a `Padding<4>` in the generated header.

**Comment by dnfield** [comment]
This is a little better after flutter/impeller#31, but still has some gaps

**Comment by chinmaygarde** [comment]
I took a look at what was missing and the the common types are already in there. If we are missing something specific we end up needing later, we can file a separate issue for that.
