### ISSUE TITLE
Roll of third_party/freetype2 repository

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#99094]
I'd like to do a roll of the version of FreeType on https://flutter.googlesource.com/third_party/freetype2/

I'm planning to base it on:
https://chromium.googlesource.com/chromium/src/third_party/freetype2/+/034e5dbf92ea3a7ea7c9322e47a3a50ff23f7b55

Can you import that commit into Flutter's mirror of FreeType?

**Comment by keyonghan** [comment]
Done: https://flutter.googlesource.com/third_party/freetype2/
