### ISSUE TITLE
[go_router] [Feature] allow push, pop, go operations in redirect callback

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#99108]
copied from https://github.com/csells/go_router/issues/369

Currently, api of go_route redirect is

...
redirect: (state){
      if(isSomething)
         return '/some_path';
      else if(isAnotherThing)
          return '/another_path';
      // No redirect
      return null;
         
    },
...
I suggest having such kind of API if it is possible:

...
redirect: (context,state){
      if(isSomething)
          context.go('/some_path');
      else if(isAnotherThing)
          context.pop();
      // No redirect
    },
...

**Comment by sam-parks-ogk** [comment]
I am relying on redirection to handle authentication routing and this would enable a page transitions when the redirection actually occurs instead of an abrupt route change. 

Is GoRouter implemented in this way for a reason? 

@chunhtai 
How are you handling these cases now?

**Comment by sam-parks-ogk** [comment]
One workaround I tried was to grab the `GoRouter` instance through `context` but using `MaterialApp.router` there wasn't a clean way to inject a top level widget to use the `GoRouter`

**Comment by chunhtai** [comment]
This can be achieve by this https://github.com/flutter/flutter/issues/99121 which I am currently working on. I will close this as a duplicate, feel free to reopen otherwise
