### ISSUE TITLE
[go_router] Support for flutter_riverpod  

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#99106]
copied from https://github.com/csells/go_router/issues/373

Here is the sample project i am working with on Flutter Riverpod and go_router. Every thing works good except just want to listen to logout state notifier
https://github.com/rddewan/flutter-note

**Comment by maks** [comment]
@rddewan the issue got moved here.

Having a look at your app code, I think I see what you want to do: with a `ChangeNotifier` you would just set it to your GoRouters `refreshListenable` property with an instance of your SignoutController.
**BUT** in your case that extends StateNotifier, which doesn't implement `Listenable` and [according to Remi can't do so](https://github.com/rrousselGit/state_notifier/issues/41#issuecomment-732971611).

I guess what is needed is some sort of adapter between a StateNotifier and the GoRouter wanting a Listenable. 

Maybe @rrousselGit would have an idea on how this could be done?

**Comment by maks** [comment]
Actually now that I think about it you could just create a wrapper ChangeNotifer that uses [`addListener`](https://pub.dev/documentation/state_notifier/latest/state_notifier/StateNotifier/addListener.html) on your SignoutController or alternatively wrap your controller in a stream, but it would be nice if go_router could support StateNotifier and hence Riverpod directly the way it does both for ChangeNotifer and Bloc (via streams).

**Comment by rddewan** [comment]
@maks  thank you for you info. I can try it out but yes it would be great if go_router can add this support for StateNotifier

**Comment by rrousselGit** [comment]
I've discussed this with Chris before his departure

The solution is supposed to be https://github.com/flutter/flutter/issues/99121 – specifically https://github.com/csells/go_router/issues/184#issuecomment-999870274

This removes the need for `refreshListenable`, therefore making go_router compatible with all approaches instead of being specific to Listenable.

**Comment by maks** [comment]
Thanks Remi, I should have known you would already be across this 👍🏻 
Given that #99121 exists I would suggest closing this issue in favour of that one.

**Comment by chunhtai** [comment]
closed as superseded by https://github.com/flutter/flutter/issues/99121
