### ISSUE TITLE
[go_router] Unique PageKey doesn't work

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#99103]
copied from https://github.com/csells/go_router/issues/382

Regarding the [documentation](https://gorouter.dev/nested-navigation) if Flutter identifies the same key it will update the url and keep the page (Widget). In the code below pageKey is a static const value set in both Containers. When navigating between those two routes (/home & /home/login) Flutter ignores it's the same widget and recreates it.
```dart
class ProjectXApp extends StatelessWidget {

  ProjectXApp({Key? key}) : super(key: key);

  static const pageKey = ValueKey("Home");

  final _router = GoRouter(
    routes: [
      GoRoute(
        path: '/',
        redirect: (_) => Routes.routeHome,
      ),
      GoRoute(
        path: '/home',
        builder: (context, state) {
          return Container(key: pageKey);
        }
      ),
      GoRoute(
          path: "/home/login",
          builder: (context, state) {
            return Container(key: pageKey);
          }
      )
    ],
  );

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
        routeInformationParser: _router.routeInformationParser,
        routerDelegate: _router.routerDelegate
    );
  }
}
```
Why is it happening? Is there a way to achieve this?

**Comment by danagbemava-nc** [comment]
Hi @martppa, the `go_router` issues have been transferred to the flutter repo. 
I need a little bit more information as to what it is you're trying to achieve. 

Perhaps some logs or a more detailed repro sample and some screen recordings that show what the actual issue is will help.

Thank you

**Comment by chunhtai** [comment]
The page key is meant to be used on [Page.key](https://api.flutter.dev/flutter/widgets/Page/key.html) in the [GoRoute.pageBuilder](https://pub.dev/documentation/go_router/latest/go_router/GoRoute/pageBuilder.html).
