### ISSUE TITLE
[go_router] Query parameters persist after redirection

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#99122]
copied from https://github.com/csells/go_router/issues/170

Given some logic in the router's redirect handler that redirects the app to a path with some query parameters in it (E.g.: /view-invoice?url=$invoiceUrl)... Once the user navigates back from that route (via back swipe gesture / back button), the state.queryParams object still holds the parameters from the view-invoice page, even though the user was taken to a new route with no parameters.

Example flow:

1. Navigate to /.
2. Navigate to /view-invoice?url=$invoiceUrl.
3. Navigate to /. <-- When printing the state.queryParams in the redirect handler, the object still holds the old values.

I'm not sure if this is by design or not, but if it is, there should at least be a way to clear the params manually. Maybe via an onBackNavigation handler?

**Comment by chunhtai** [comment]
This is WAI, this is the code I am using
<details>

```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

void main() => runApp(App());

class App extends StatelessWidget {
  App({Key? key}) : super(key: key);

  static final loginInfo = ValueNotifier<bool>(false);
  static const title = 'GoRouter Example: Redirection';

  // add the login info into the tree as app state that can change over time
  @override
  Widget build(BuildContext context) => MaterialApp.router(
    routeInformationParser: _router.routeInformationParser,
    routerDelegate: _router.routerDelegate,
    title: title,
    debugShowCheckedModeBanner: false,
  );

  late final _router = GoRouter(
    routes: [
      GoRoute(
        path: '/',
        builder: (context, state) => HomeScreen(state),
        routes: [
          GoRoute(
            path: 'a',
            builder: (context, state) => LoginScreen(state),
          )
        ],
      ),
    ],
  );
}

class LoginScreen extends StatelessWidget {
  const LoginScreen(this.state, {Key? key}) : super(key: key);
  final GoRouterState state;
  @override
  Widget build(BuildContext context) => Scaffold(
    appBar: AppBar(title: const Text(App.title)),
    body: Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Text('Login ${state.queryParams}'),
        ],
      ),
    ),
  );
}

class HomeScreen extends StatelessWidget {
  const HomeScreen(this.state, {Key? key}) : super(key: key);
  final GoRouterState state;
  @override
  Widget build(BuildContext context) {

    return Scaffold(
      appBar: AppBar(
        title: const Text(App.title),
      ),
      body: Text('home ${state.queryParams}'),
    );
  }
}
```

</details>

The query parameter should persist since the entire route stack is built with the query parameter. If you want to clear the query param, you can go context.goto() without the query parameters

**Comment by minhqdao** [comment]
As a workaround, programmatically using the browser back button clears the query parameters:

```dart
import 'package:flutter/foundation.dart';
import 'package:universal_html/html.dart';

...
onPressed: () => kIsWeb ? window.history.back : context.pop(),
...
```

**Comment by benPesso** [comment]
@minhqdao That won't work for native back navigation.

**Comment by minhqdao** [comment]
> @minhqdao That won't work for native back navigation.

What do you mean by "native back navigation"?

**Comment by benPesso** [comment]
> > @minhqdao That won't work for native back navigation.
> 
> What do you mean by "native back navigation"?

Android's back button. Android's and iOS' swipe back gesture.
