### ISSUE TITLE
[go_router] Add BuildContext to redirect

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#99121]
copied from https://github.com/csells/go_router/issues/184

https://github.com/csells/go_router/blob/master/lib/src/go_router_delegate.dart#L350

When we use the redirect we might want to check for dependencies injected in the widget tree using the context.

For instance, I have pages that are only accessible under certain user permissions. In Flutter web a user can simply type the url path to the page they want to see (navigate) but if the permission is not present the page should redirect.

I have the permissions up in the tree as the state of a bloc (using flutter bloc) and it would be great if I could receive the context in the redirect and simply find the bloc's state.

I believe this is possible, either passing the current navigator's state's context to the redirect callback or to the GoRouterState.

This should be broken into various stage:

- [x] 1. refactor go route match to be in the routeinformationparser https://github.com/flutter/packages/pull/1653
- [x] 2. change native API to pass the context to RouteInformationParser https://github.com/flutter/flutter/pull/102414
- [x] 3. pass the context to redirect.

**Comment by maks** [comment]
I've just been catching up with the discussion on this issue in the old repository in the context the I'm currently happily using GoRouter with `ChangeNotifier`'s for the moment but would like to switch to `StateNotifier` once its easily possible, though for me right now thats more about being able to use the `refreshListenable` property

Am I right that there was general consensus from @lulupointu and @letsar around this idea of making GoRouter a widget ](https://github.com/csells/go_router/issues/184#issuecomment-999870274)from @rrousselGit that Chris posted?

And if that's the case, @letsar could your PR take that approach? I'm sorry for all the questions, just trying to figure out where this is at after the move of GoRouter here to the Flutter repo...

**Comment by chunhtai** [comment]
Would like to know how people expect the behavior should be when the dependencies changes, for example, if the State you look up from the build context change, should the redirect be triggered again automatically?

**Comment by johnpryan** [comment]
I think our recommendation is that that they provide a [`refreshListenable`](https://pub.dev/documentation/go_router/latest/go_router/GoRouter/GoRouter.html) to the GoRouter constructor.

**Comment by chunhtai** [comment]
This is more of general question since the inherited look up from BuildContext will add a dependency between the context and the inherited widget, and this will cause rebuild when inherited widget change. I wonder whether people would expect the redirect to be triggered automatically as well.

**Comment by johnpryan** [comment]
It sounds like we could remove `refreshListenable` too, it's only used for re-processing the redirects.

**Comment by sam-parks** [comment]
@chunhtai 
I believe that adding the context to the redirect would still be beneficial for the reasons you mentioned, but looking through the documentation I found [Navigator Builder](https://gorouter.dev/navigator-builder). 

I was able to use this in combination with `flutter_bloc` to achieve the desired routing and transitions when certain states are met.  I'm not sure if this solves your exact issue, but it seems related.

**Comment by leoshusar** [comment]
My use case of `refreshListenable`.
I have an `AppState` service that uses `ChangeNotifier`, something like this:
```dart
class AppState extends ChangeNotifier {
  final SettingsService _settingsService;
  final PlaylistService _playlistService;

  AppState(this._settingsService, this._playlistService) {
    final streams = [
      _settingsService.isLoaded,
      _playlistService.isLoaded,
    ];
    _servicesReadySubscription = Rx
      .combineLatest<bool, bool>(streams, (s) => s.every((e) => e))
      .listen((e) {
        _isReady = e;
        notifyListeners();
      });
  }

  late final StreamSubscription<bool> _servicesReadySubscription;

  bool _isReady = false;
  bool get isReady => _isReady;
}
```

and I'm using it for redirecting to / from `LoadingRoute`.
Like this:
```dart
refreshListenable: _appState,
redirect: (state) {
  ...

  final loaded = _appState.isReady;
  final loading = state.subloc == _loadingRoute;
  final redirect = (loggingIn || loading) ? state.queryParams['r'] : state.location;

  if (!loaded) {
    return loading ? null : LoadingRoute(r: redirect).location;
  }

  ...
}
```

Once the `isReady` is `true`, it automatically redirects from `Loading` further on.

How would this behavior be achievable without `refreshListenable`?

**Comment by chunhtai** [comment]
fix merged into feature branch v5, please use https://github.com/flutter/flutter/issues/108044 to track v5 release progress
