### ISSUE TITLE
[go_router] Support multiple navigation stacks

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#99126]
copied from https://github.com/csells/go_router/issues/82

e.g. https://medium.com/coding-with-flutter/flutter-case-study-multiple-navigators-with-bottomnavigationbar-90eb6caa6dbf

**Comment by mark8044** [comment]
Its great that go_router got merged into flutter.  Had a feeling this was the `go`-to router due to its dead simple use.

But for it to be truly useful we need to get it to work with bottomNavigation.  Maybe it already does, but if not this has to be priority 1 if this package is still being worked on.  Please don't P4 this :) :)

**Comment by chunhtai** [comment]
We use thumbs up to prioritize the feature requests, but currently my top-most priority is to clean up the code and apply flutter lint. In the meantime, feel free to submit a pr if you may have idea to add this feature.

**Comment by tananga** [comment]
@chunhtai We need something like this https://youtu.be/9oH42_Axr3Q

**Comment by fullflash** [comment]
yes this is must feature for any router/navigation package.

**Comment by mark8044** [comment]
Please everyone give a thumbs up to the above posts.

It sounds like that's how they will gauge if they will do any work on this issue.  Im giddy to try using go_router and just waiting for this one issue to progress ...

**Comment by OppositeDragon** [comment]
Yes, please. 👍

**Comment by rahulrmishra** [comment]
Is there any update on this? If I am not able to use navigation with a persistent bottom bar and individual stacks for each tab, I might have to drop Go Router in my project.

**Comment by HarshilPatel18** [comment]
I agree with @rahulrmishra . @chunhtai  Can we have any update if this feature is being implemented or any timeline by when will it be implemented. This is a very common use case and needs urgent attention

**Comment by czaku** [comment]
Much needed for myself too...

**Comment by The-Redhat** [comment]
> Much needed for myself too...

Hey please add a thumbs up to the original issue instead of adding a comment. The flutter team works on issues based on the amount of thumbs up.

**Comment by mono0926** [comment]
It appears to be in the process of being addressed.

[GoRouter API improvements (PUBLICLY SHARED)](https://docs.google.com/document/u/0/d/1_mRXinbL_rb0mUt6DAFZ8kj0kh33ZjEMJuUq4PJgwj8/mobilebasic?resourcekey=0-sYbRzE9opneOFZ5F8J3gGw)

**Comment by mark8044** [comment]
@chunhtai @johnpryan If/when this is worked on, one thing to keep in mind is that so far with other implementations of multiple navigation stacks, we lose the ability to scroll-to-top in iOS when tapping on the status bar.  This is due to a problem with PrimaryScrollController being created above the indexed stack level.

If this issue can also be kept in mind while working on this issue would be ideal, since scroll-to-top on iOS is a critical part of making any app feel native.

**Comment by daanporon** [comment]
Does anybody know where the work for this is being tracked? We currently have this working with Navigator 1.0 without urls, but are looking into refactoring this to be more web-friendly. We would also be interested into supporting the development of this if possible.

**Comment by davidmartos96** [comment]
I believe the work is being done here https://github.com/flutter/uxr/pull/82

**Comment by mark8044** [comment]
> Hi @jhuckabee, you can now replace `go_router` with [`go_router_prototype`](https://pub.dev/packages/go_router_prototype) in your pubspec to try out the new API described in the design doc. The [UXR snippets](https://github.com/flutter/uxr/pull/82) might also be a helpful resource to compare to other designs. Feedback is very welcome at this stage!

I just tried it, but `NavigatorRoute` doesn't want to work, it looks like its part of prototype.  Im using the example in the design doc

```
import 'package:go_router_prototype/go_router_prototype.dart';

  final _router = GoRouter(
    routes: [
      ShellRoute(
        path: '/',
        defaultChildRoute: 'a',
        builder: (context, child) => AppScaffold(child: child),
        routes: [
          NavigatorRoute(
            path: 'a',
            builder: (context) => const NewsScreen(),
            routes: [
              StackedRoute(
                path: 'details',
                builder: (context) => const NewsScreen(),
              ),
            ],
          ),
          NavigatorRoute(
            path: 'b',
            builder: (context) => const Screen(
              title: 'Screen B',
              key: ValueKey('B'),
            ),
            routes: [
              StackedRoute(
                path: 'details',
                builder: (context) => const DetailsScreen(label: 'B'),
              ),
            ],
          ),
        ],
      ),
    ],
  );
```

It looks like in the example file the import is using `import 'package:tree_router/tree_router.dart';` ?

**Comment by mark8044** [comment]
Just an update, I've been using the Cupertino example and its working fairly slickly.  PreserveState will be a must however... :)

**Comment by johnpryan** [comment]
Hi @mark8044, thanks for the feedback, I was going to say NavigatorRoute was renamed to NestedStackRoute, but it sounds like you got it working. We're tracking preserveState here: https://github.com/flutter/flutter/issues/99124

**Comment by mark8044** [comment]
> Hi @mark8044, thanks for the feedback, I was going to say NavigatorRoute was renamed to NestedStackRoute, but it sounds like you got it working. We're tracking preserveState here: #99124

Yup your example app was perfect.  Once preserveState is working, I'm going to try putting this into production.  Have a million other questions, but I'll wait as I know you are working on it all 👍

**Comment by daanporon** [comment]
> Hi @jhuckabee, you can now replace `go_router` with [`go_router_prototype`](https://pub.dev/packages/go_router_prototype) in your pubspec to try out the new API described in the design doc. The [UXR snippets](https://github.com/flutter/uxr/pull/82) might also be a helpful resource to compare to other designs. Feedback is very welcome at this stage!

@johnpryan i also got it working, thanks for this. I will also be following up the preserveState work. 

One issue that i found and i don't know where to log it or if i'm missing something. But if your `ShellRoute` path has a path parameter, how can we use this in the `defaultRoute`? If the defaultRoute just points to the sub path, the path parameter goes missing. You also cannot use the full path because then you need to fill in a hard coded path parameter.

**Comment by ibrahim-mubarak** [comment]
One thing I've noticed in the prototype repo and the design docs is there's no more "extras" argument when navigating. Is this intended?

**Comment by johnpryan** [comment]
Here's a [gist](https://gist.github.com/johnpryan/8ee0b65666ac9ecb9406a3a78ffb2a9a) that attempts to use an IndexedStack for state preservation. It doesn't seem to preserve the state, but you might be able to get it working.

**Comment by mark8044** [comment]
> Here's a [gist](https://gist.github.com/johnpryan/8ee0b65666ac9ecb9406a3a78ffb2a9a) that attempts to use an IndexedStack for state preservation. It doesn't seem to preserve the state, but you might be able to get it working.

Do you foresee preserveState being something still a far off ways away?  I'm absolutely loving go_router_prototype using the Cupertino example you gave, just need preserveState before flicking the switch on this app 👍   Thank you man

**Comment by daanporon** [comment]
> Here's a [gist](https://gist.github.com/johnpryan/8ee0b65666ac9ecb9406a3a78ffb2a9a) that attempts to use an IndexedStack for state preservation. It doesn't seem to preserve the state, but you might be able to get it working.

Thank you! didn't even know that could work. I will try integrating it in my example.

**Comment by teneon** [comment]
Hi, @johnpryan i've been testing router prototype (bottom navigation material), it looks great so far. With the examples included i could figure out most things. We need preserveState asap and then we can further test it / use it. If possible please include and example for bottom navigation with andorid back button handling. I would like to see a behaviour which is similar to Google Youtube app or Google Drive app for android? Any ETA on the implementation for perserveState?

**Comment by subzero911** [comment]
"Nested navigation" secton in go_router documention is completely not what I wanted. It tells about TabBar navigation only, and how to make a web browser path change accordingly.
What I want is an inner navigator, replacing a part of screen (like a fragment of activity).
So I can create "a page inside of a page" with its own navigation stack and transitions (extremely useful for dashboards, where I have a menu on the left and a content page on the right)
`auto_route` has this feature for a long time, native Navigator also has this feature (https://docs.flutter.dev/cookbook/effects/nested-nav)

**Comment by johnpryan** [comment]
@subzero911 can you take a look at this [go_router_prototype example](https://github.com/johnpryan/go_router_prototype/blob/main/example/lib/stacked_nested_nav.dart) to confirm this is the API you need?

**Comment by tijanirf** [comment]
> @subzero911 can you take a look at this [go_router_prototype example](https://github.com/johnpryan/go_router_prototype/blob/main/example/lib/stacked_nested_nav.dart) to confirm this is the API you need?

Wow, can't wait for this feature to be released! Is there any "guesstimation" about the released date?

**Comment by johnpryan** [comment]
> Why can't I put a NestedStackRoute directly inside any GoRoute?

We could support this, but visually there's no difference. Most of the scenarios I've looked at display UI shell around the inner navigator. Can you explain more why you need this?

> Also, how am I supposed to show where exactly would I draw the inner navigator?

That is why you need `ShellRoute`.  If you want to display the inner navigator for a subsection of the screen, then there's probably a  UI shell you are building that will contain the Navigator.

> In auto_route, the AutoRouter() without parameters used as an outlet.

We could have designed it that way, but we decided to go with `ShellRoute` instead.

**Comment by subzero911** [comment]
One more question. Does it support the edge-case: nested in nested?

When I have a nested navigator, and on one of its page there's yet another inner navigator. 
![image](https://user-images.githubusercontent.com/12999702/181012300-334aae02-99f7-4639-b33e-cf2c5f85197b.png)

**Comment by johnpryan** [comment]
@subzero911 yes, see this demo: https://github.com/johnpryan/go_router_prototype/blob/main/example/lib/recursive_shell.dart

You can add a border to see how the nesting works:
<img width="1270" alt="Screen Shot 2022-07-26 at 8 45 00 AM" src="https://user-images.githubusercontent.com/1145719/181050869-6a849adc-9309-4fb1-a429-a76318eff206.png">

**Comment by dk5761** [comment]
@johnpryan, is there any ETA on the shell routes to be released in the stable?

**Comment by rhinck** [comment]
I recently discovered go_router and it seems really awesome. I appreciate all of the work the contributors have put towards making this package!

I don't know if the current stable version supports this or if it will be released with the updates proposed here, but I am essentially trying to figure out how to have a shared app bar (with dynamic title), shared bottom navigation bar, and an "outlet" where I can render the separate pages for each of the buttons as they're tapped in the bottom navigation bar.

When I say "outlet", I am referring to this concept in the React Router package: https://reactrouter.com/docs/en/v6/components/outlet. (I apologize for not knowing the proper nomenclature for this functionality in Flutter)

**Comment by johnpryan** [comment]
@rhinck yes this is the correct issue to follow for that scenario. You will be able to draw your UI "shell" with the app bar and bottom navigation bar using ShellRoute. See this example: https://github.com/johnpryan/go_router_prototype/blob/main/example/lib/bottom_nav.dart

**Comment by iEricKoh** [comment]
still wondering if there's any ETA, i've tried the [go_router_prototype](https://pub.dev/packages/go_router_prototype) package and everything works fine so far, every the param `extra` is missing in the package, didn't find a way to pass arguments between different routes.

**Comment by IlyaMax** [comment]
@johnpryan Do you support case of navigating with overriding transition animation. In beamer it is done with transitionDelegate parameter of beamTo/beamToNamed. And are you planning to add some variants of non-named navigation?

**Comment by ElteHupkes** [comment]
I played around with the go_router_prototype, and I think that API is pretty much what I would like to have. It has some issues that prevent me from using it right now, which is to be expected of a prototype, but otherwise the idea of having this differentiation between stacked routes, shell routes and navigator routes looks brilliant.

**Comment by johnpryan** [comment]
@ElteHupkes We made some changes since building the prototype, there is only `ShellRoute`, which always builds a navigator and doesn't contribute to the path. If you want the latest version you can check out this branch: https://github.com/flutter/packages/pull/2453

**Comment by michaelsoliman1** [comment]
I actually use go_router_prototype for a web app that's going to production soon 😅, it was the only solution for nested navigation. It has some limitations since it's just a prototype, but i did some workarounds to work with it. I can say it's pretty awesome and doing its job just fine 👍🏻

@johnpryan Waiting to use the official version!

**Comment by michaelsoliman1** [comment]
Just checked the [PR](https://github.com/flutter/packages/pull/2453) you mentioned, what will happen to go_router_prototype now? should I migrate to GoRouter and use ShellRoute?

**Comment by johnpryan** [comment]
@michaelsoliman1 yes, I would consider go_router_prototype deprecated.  Let us know if you have any issues migrating.

**Comment by subzero911** [comment]
Does it mean you got rid of these confusing StackedRoute and NestedStackRoute and finally left a ShellRoute only?

**Comment by johnpryan** [comment]
@subzero911 yes, there is only ShellRoute and GoRoute.

**Comment by subzero911** [comment]
I like this final variant.

**Comment by rlee1990** [comment]
@johnpryan any idea when this will be merged into the main package?

**Comment by ElteHupkes** [comment]
People, respectfully, and this goes for open source in general, asking for an ETA tends to only delay the ETA, because it's just another notification to deal with in somebody's inbox. If you look at the branch John Ryan linked to it seems there's active review and discussion going on, so it's coming!

**Comment by rlee1990** [comment]
> People, respectfully, and this goes for open source in general, asking for an ETA tends to only delay the ETA, because it's just another notification to deal with in somebody's inbox. If you look at the branch John Ryan linked to it seems there's active review and discussion going on, so it's coming!

The reason for me asking is because that package doesn't contain the other changes that are in the 5.0 branch for go router some of which I really do need. Also having a timetable helps other developers to know when they can complete a task or release an app.

**Comment by chunhtai** [comment]
Please use https://github.com/flutter/flutter/issues/108044 for discussion about v5 release.

**Comment by mark8044** [comment]
WOAH, it looks like we've made it?   Is there an example on how to do a Cupertino bottom navigation bar using this shiny new v5 release?
