### ISSUE TITLE
the bug of blockquote or the bug of unordered list

### ISSUE THREAD

**Issue by 2372281891** [flutter/flutter#99128]
In a specific mobile browser, such as via browser, the unordered lists in blockquote will overlap. It is unclear whether it is the bug of blockquote or the bug of unordered list

[click here](https://shenluncha.gitee.io/slc/web/)
Loading is slow, please wait patiently
** Please open the above web address through via browser **

Please click: 北京-- > 确认-- >查答案 -- > 北京-- > 第一题 in turn，
Then select the reference answer at the bottom

**Comment by danagbemava-nc** [comment]
Hi @2372281891, thanks for filing the issue. 

Please provide a complete minimal reproducible code sample as well as the output of `flutter doctor -v`. 

Thank you

**Comment by 2372281891** [comment]
# Please test my markdown content in via browser using the deployed flutterweb project

## code
```
Markdown(
                data: snapshot.data,
                styleSheetTheme: MarkdownStyleSheetBaseTheme.material, //主题
                styleSheet: MarkdownStyleSheet(
                    listBullet: TextStyle(
                      fontSize: 20, //列表符号大小
                    ),
                    textScaleFactor: Adapt.px(1.5),
                    blockquoteDecoration: BoxDecoration(
                      color: Colors.grey[200], //块注释背景颜色
                    ),
                    blockquote: TextStyle(color: Colors.grey[600] //块注释字体颜色
                        )),
              
```

## markdown content
```
## 参考答案：

>* 这句话指乡村硬件改造只能暂时改变村貌，但思想转变却能促进持续发展。
>* 一、“有形的”指改造硬件设施，包括：修建道路，进行拓宽硬化；改善住房条件；完善饮水、网络等生活设施。
>* 二、“无形的”指改变思想，包括：1.改变干部得过且过的思想。组织干部学习打字技能、党中央精神；锻炼年轻干部独立解决问题，提升工作主动性、积极性。2.改变村民轻视教育的思想。为大龄失学儿童提供义务教育，关爱鼓励孩子；开展普法教育，做通村民思想工作，让孩子憧憬未来、坚定信心。3.改变单一经济发展思路。建造集市，坚持宣传，成立合作社，吸引村民参与，动员商户入驻；创新品牌，建厂合作，扩大品牌影响力，加快标准化生产，开发生态产品，拓展市场。 

`应用商店搜索，查询国考+省考机构解析`


```

## flutter doctor
```
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.2, on Microsoft Windows [Version 10.0.17763.2565], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.64.2)
[√] Connected device (2 available)
[!] HTTP Host Availability
    X HTTP host https://maven.google.com/ is not reachable. Reason: An error occurred while checking the HTTP host:
      信号灯超时时间已到
```

**Comment by danagbemava-nc** [comment]
Hi @2372281891, what version of `flutter_markdown` are you experiencing this issue with?

**Comment by 2372281891** [comment]
0.6.9&nbsp; &nbsp;thanks



---Original---
From: "Daniel ***@***.***&gt;
Date: Mon, Feb 28, 2022 15:14 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [flutter/flutter] the bug of blockquote or the bug of unordered list (Issue #99128)




 
Hi @2372281891, what version of flutter_markdown are you experiencing this issue with?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 2372281891** [comment]
[image1](https://www.shenluncha.com/file/q1.jpg)
[image2](https://www.shenluncha.com/file/q2.jpg)

**Comment by danagbemava-nc** [comment]
Hi @2372281891, I cannot access the screenshots. So I'm not entirely sure what I should look out for. 
You can directly attach them to this thread. You do not need to create a hyperlink for them.

**Comment by 2372281891** [comment]
&nbsp; please&nbsp; test my code&nbsp; in the via&nbsp; browser&nbsp;&nbsp;



---Original---
From: "Daniel ***@***.***&gt;
Date: Tue, Mar 1, 2022 14:21 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [flutter/flutter] the bug of blockquote or the bug of unordered list (Issue #99128)




 
Hi @2372281891, I cannot access the screenshots. So I'm not entirely sure what I should look out for.
 You can directly attach them to this thread. You do not need to create a hyperlink for them.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by danagbemava-nc** [comment]
Hi @2372281891, is the text not being properly contained in the blockquote the bug you're referring to?

<img src="https://user-images.githubusercontent.com/88313112/156128900-b043a7e1-2a22-43dc-bc73-a2a649e2b2dc.jpeg" width="300" />
