### ISSUE TITLE
[go_router] Add go_router_builder

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#99127]
copied from https://github.com/csells/go_router/issues/66

This is an exploratory feature request to add a build_runner layer for generating type-safe wrappers around goNamed and pushNamed.

I'm imagining something like this:
```dart
@Generate(int fid)
GoRoute(
  name: 'family',
  path: '/family/:fid',
  pageBuilder: (context, state) {...},
)
```
Which would create something like this:

```dart
extension on GoRouter {
  void pushFamily(int fid) =>
    push(_lookupNamedRoute('family', {'fid': fid}));

  void goFamily(int fid) =>
    go(_lookupNamedRoute('family', {'fid': fid}));
}
```
Thoughts?

**Comment by johnpryan** [comment]
We need to re-submit https://github.com/csells/go_router/pull/216 to the flutter/packages repo.
