### ISSUE TITLE
windows-x64-embedder naming is not consistent

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#99137]
In linux the file does not end in .zip while in windows it does. Filename in windows is `windows-x64-embedder.zip` while the linux artifact is called `linux-x64-embedder`. Can we add `.zip` to the linux file name?

**Comment by godofredoc** [comment]
\cc @christopherfujino @zanderso @dnfield

**Comment by dnfield** [comment]
I think we'll have to update the tool to make that work right?  It's probably fine if the tool knows to check for either in the interim.

**Comment by christopherfujino** [comment]
Are these new? I don't these files in the tool code today: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/flutter_cache.dart#L857

**Comment by godofredoc** [comment]
Seems like with the explicit archiving steps we will be finding many of these issues.

**Comment by godofredoc** [comment]
If they don't exist in the tool I believe is safe to normalize the names to end with .zip. I'll send the PR

**Comment by christopherfujino** [comment]
> If they don't exist in the tool I believe is safe to normalize the names to end with .zip. I'll send the PR

SGTM
