### ISSUE TITLE
web app don't work because some resources like fonts and css are hard coded in main.dart.js

### ISSUE THREAD

**Issue by bajizhh** [flutter/flutter#99138]
Web app don't work without internet connection.

<img width="913" alt="image" src="https://user-images.githubusercontent.com/19441074/155665750-44547307-e8d1-4d71-9b00-a83fd3317b35.png">

**Comment by maheini** [comment]
Have a look to this issue and answer from Flutter devs:  #97579 and  #94264
->There is currently no support for offline usage, feature requests are already open: #60069.

If this solves your Issue, then close this issue as duplicated.
