### ISSUE TITLE
Flutter app screen getting cut with a white patch

### ISSUE THREAD

**Issue by yashwp** [flutter/flutter#99136]
We are facing a very weird issue with our Flutter Mobile app (Android version only). As displayed in the screenshot, the bottom part is getting cut, and the app loads only in the 3/4th part of the screen only.

This is coming in the released Playstore version only. In debug mode, this never happened on an emulator or real device. Also, this occurrence is very random and irrespective of the device model. If I close the app and re-run it works fine most of the time.

Flutter Version - 2.5.1

Here is the SS for the problem - 
<img width="291" alt="image" src="https://user-images.githubusercontent.com/13454790/155662419-250b86c7-6423-49f5-a744-570e662e6d69.png">

I have also opened a SO as well - https://stackoverflow.com/questions/71261566/flutter-app-screen-getting-cut-with-a-white-patch

**Comment by danagbemava-nc** [comment]
Hi @yashwp, can you upgrade to the latest version of `stable` and see if you still experience the issue? 

If you do, kindly provide the updated `flutter doctor -v` as well as a complete minimal reproducible code sample. 

Thank you
