### ISSUE TITLE
The flutter web project running on local host, it is very slow while running!

### ISSUE THREAD

**Issue by panli200** [flutter/flutter#99142]
## Details

**Target Platform: Big Sur**
**Target OS version/browser: Google Chrome**
**Devices: Macbook**

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@panli200 
When you open issues related to performance, please fill out the requested details in the template so that we'll have enough details to work with. 
Since you didn't provide any details, I am going ahead and closing this as non-actionable.
