### ISSUE TITLE
[shared_preferences]Removed the null checks that shouldn't be there.

### ISSUE THREAD

**Issue by talisk** [flutter/flutter#99145]
https://github.com/flutter/plugins/blob/main/packages/shared_preferences/shared_preferences/lib/shared_preferences.dart#L164-L165

``` dart
final Map<String, Object> fromSystem = await _store.getAll();
assert(fromSystem != null);
```

`fromSystem` isn't a nullable value. The assert should be removed

**Comment by stuartmorgan** [comment]
Flutter still supports mixed mode; assets are currently being left intentionally.
