### ISSUE TITLE
in_app_purchase how to handle incomplete purchase (ios)

### ISSUE THREAD

**Issue by faganchalabizada** [flutter/flutter#99148]
@mvanbeusekom 
I'm facing the same issue with the latest version of the plugin (in_app_purchase: ^1.0.6). 
I'm verifying the receipt by calling an API to my backend. I don't complete the transaction until I get the validation from the backend. Sometimes this API call fails because of connection issues. In this case, if the user tries to purchase the product again then he will see this error. How should I handle this? If I complete the transaction, then the backend will never know about the latest purchase.

_Originally posted by @varunkamanibosc in https://github.com/flutter/flutter/issues/60763#issuecomment-886047931_

We can get transaction list but there is not enough data for verify.
```
final transactions = await SKPaymentQueueWrapper().transactions();
      transactions.forEach((transaction) async {
         //is is impossible get payment details for verify purchase in server side. So we can't deliver product to user before finishing.
        //await SKPaymentQueueWrapper().finishTransaction(transaction); 
      });

```

**Comment by stuartmorgan** [comment]
1.0.6 is not the latest version of the plugin; the comment you have reposted here is outdated.

If you have an issue with the current version of the plugin, please file a new issue using the issue report template, providing all requested information.
