### ISSUE TITLE
[Web][Tool]: Flutter web debugging fails with `DevHandler: Stopped debug service` on Chrome enterprise

### ISSUE THREAD

**Issue by ddukesterman** [flutter/flutter#99157]
## Steps to Reproduce

1. Install Flutter tools to support web/chrome
2. Create new project, run `Flutter create .`
3. Run `flutter run -d chrome`
4. Notice that the application doesn't crash but just closes. Doesn't happen with `--release`

## Logs

<details>
<summary>Logs</summary>

```
[  +11 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+19921 ms] Waiting for connection from debug service on Chrome... (completed in
20.1s)
[   +1 ms] Synced 31.5MB.
[        ] <- accept
[        ] Caching compiled dill
[ +127 ms] Using Google Chrome 98.0.4758.109 

[+1697 ms] executing: sysctl hw.optional.arm64
[   +8 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[ +695 ms] [CHROME]:
[   +1 ms] [CHROME]:DevTools listening on
ws://127.0.0.1:54210/devtools/browser/cfe0bfd6-0704-4798-8d53-86dbd0ec1f76
[+1500 ms] DwdsInjector: Received request for entrypoint at
http://localhost:54191/main_module.bootstrap.js
[   +5 ms] MetadataProvider: Loading debug metadata...
[  +14 ms] MetadataProvider: Loaded debug metadata (sound null safety)
[   +7 ms] DwdsInjector: Injected debugging metadata for entrypoint at
http://localhost:54191/main_module.bootstrap.js
[+2604 ms] ChromeProxyService: Initializing expression compiler for
main_module.bootstrap.js with sound null safety: true
[ +103 ms] DevHandler: Debug service listening on
ws://127.0.0.1:54242/V_SLobRv6xU=/ws

[  +44 ms] This app is linked to the debug service:
ws://127.0.0.1:54242/V_SLobRv6xU=/ws
[  +16 ms] Debug service listening on ws://127.0.0.1:54242/V_SLobRv6xU=/ws
[        ] 💪 Running with sound null safety 💪
[   +4 ms] 🔥  To hot restart changes while running, press "r" or "R".
[        ] For a more detailed help message, press "h". To quit, press "q".
[   +1 ms] An Observatory debugger and profiler on Chrome is available at:
           http://127.0.0.1:54242/V_SLobRv6xU=
[+2020 ms] DevHandler: Stopped debug service on ws://127.0.0.1:44456

[ +900 ms] Application finished.
[   +4 ms] "flutter run" took 31,135ms.
[ +157 ms] ensureAnalyticsSent: 153ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0
```

</details>

**Comment by darshankawar** [comment]
@ddukesterman 
Can you provide your `flutter doctor -v` ? Do you see this behavior occuring everytime consistently ?
Also, you just create a new app using `flutter create .` and then run `flutter run -d chrome` ?

**Comment by ddukesterman** [comment]
@darshankawar  Here is the `flutter doctor -v` output
```
➜  testApp flutter doctor -v
[✓] Flutter (Channel stable, 2.10.2, on macOS 11.6.3 20G415 darwin-x64, locale en-US)
    • Flutter version 2.10.2 at /Users/tjd0019/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (10 days ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/tjd0019/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio Preview.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 98.0.4758.109

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

This occurs 100% of the time. It doesn't close when it opens when using `--release`. Is there some other logs I can fetch for you?

**Comment by darshankawar** [comment]
@ddukesterman 
Thanks for the update. From the log, it shows `DevHandler: Stopped debug service` indicating the devtools somehow is stopping abruptly.

Can you please provide `flutter run -d chrome --verbose` log ? It'll be huge so you can put that in a text file and share it here.

Also, in your original description, you said `Install Flutter tools to support web/chrome`. Are you doing anything explicitly before just creating an app and trying to run on web ?

**Comment by darshankawar** [comment]
From the log, it seems to stop the devHandler which is causing the app not to launch:

```
[+2206 ms] ChromeProxyService: Initializing expression compiler for main_module.bootstrap.js with sound null safety: true
[  +79 ms] DevHandler: Debug service listening on ws://127.0.0.1:55778/InB2O-qQ3EY=/ws

[  +21 ms] This app is linked to the debug service: ws://127.0.0.1:55778/InB2O-qQ3EY=/ws
[  +12 ms] Debug service listening on ws://127.0.0.1:55778/InB2O-qQ3EY=/ws
[        ] 💪 Running with sound null safety 💪
[   +4 ms] 🔥  To hot restart changes while running, press "r" or "R".
[        ] For a more detailed help message, press "h". To quit, press "q".
[        ] An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:55778/InB2O-qQ3EY=
[+2655 ms] DevHandler: Stopped debug service on ws://127.0.0.1:44456
```

I am unable to replicate this behavior on latest stable and on master, so will label it for further insights from the team.

There was a similarly reported issue which got closed due to inactivity: https://github.com/flutter/flutter/issues/78106

**Comment by ddukesterman** [comment]
@darshankawar It is very similar to [#78106](https://github.com/flutter/flutter/issues/78106). It works just fine on my Windows computer. Just like in the other issue that was reported.

**Comment by annagrin** [comment]
@ddukesterman I cannot repro this on my mac unfortunately. Did chrome start and then crashed, or did you now see it starting at all? To rule out chrome-related issues, could you please try upgrading chrome and then retrying?

**Comment by ddukesterman** [comment]
@annagrin Chrome will start up and display the sample app but just for a second or two and then just close. I have updated Chrome and it still does the same thing. This is my company's MacBook and it does the same with a co-worker's MacBook. I wonder if there is something between our system and Chrome that is preventing a debug connection.

**Comment by christopherfujino** [comment]
> @annagrin Chrome will start up and display the sample app but just for a second or two and then just close. I have updated Chrome and it still does the same thing. This is my company's MacBook and it does the same with a co-worker's MacBook. I wonder if there is something between our system and Chrome that is preventing a debug connection.

That's an interesting hypothesis I had not considered.

**Comment by ddukesterman** [comment]
@annagrin @christopherfujino 
I am not sure if this will make a difference but I am currently using the Intel based MacBook and will be able to try it on the MacBook M1 Pro next week. I can update you when I try it out.

**Comment by ddukesterman** [comment]
@annagrin @christopherfujino 
I just tried following these steps with a brand new computer. It is the M1 MacBook Pro and it does the same thing with debug build.

**Comment by ddukesterman** [comment]
Sorry for the delay. I am currently traveling and I will update this Friday.

**Comment by ddukesterman** [comment]
Sorry for the delay again.

@annagrin I was able to switch to master channel 

`Flutter is already up to date on channel master
Flutter 2.13.0-0.0.pre.379 • channel master •
https://github.com/flutter/flutter.git
Framework • revision bc0ec85717 (65 minutes ago) • 2022-04-04 17:27:18 -0700
Engine • revision e7e7ca1252
Tools • Dart 2.17.0 (build 2.17.0-266.0.dev) • DevTools 2.12.1`

Still the same results. What should we try next?

**Comment by ddukesterman** [comment]
Here is the stacktrace. 
[stack_trace.txt](https://github.com/flutter/flutter/files/8414218/stack_trace.txt)

Did you want me to place it in [#99935](https://github.com/flutter/flutter/issues/99935) as well?

**Comment by ddukesterman** [comment]
@annagrin Is there anything else we can try?

**Comment by annagrin** [comment]
I have a suspicion that Chrome remote debugger exits due to some error.

I filed an issue to add more information on the connection errors at: https://github.com/google/webkit_inspection_protocol.dart/issues/86

I don't have any sure workarounds at the moment as there is no repro to investigate and we can only add more information to debug the problem, so it will be slow, unfortunately.

**Ideas for debugging the problem**

If you are willing to debug the problem a bit yourself (to speed up the process), I have an idea on how we can look at the errors. Once the following PR (https://github.com/flutter/flutter/pull/103220) lands, you can try another way of connecting to chrome's remote debugger, via a web server and dart debug extension:

**Install Dart Debug Extension**

https://chrome.google.com/webstore/search/dart%20debug%20extension

**From VsCode**

Running the `web-server` device from VSCode 

- Open Preferences > User settings > Extensions > Dart > Flutter > Show Web Server Device > select “Always”
At the bottom right, select Web Server service
- Open the command palette, select Dart Capture Debugging Logs (this will add detailed logging to the Debug Console)
- Open the Run and Debug panel and run the Flutter application

This will start your application in paused mode. From there, you can select the Dart Debug Extension to connect the debugger and beginning debugging in VSCode.

If this scenario works, then you have a workaround! Otherwise, we can look at the the communication errors between chrome and the dart debugger:

**Collect errors**

If you encounter similar problems in this scenario, you can right-click the extension in another chrome window before you start debugging, click "manage extensions" , "background page", and then copy and paste what you see on the console and network tabs, and see if there are any errors in `$dwdsAuthentication` or `$debug` calls.


**For example**

<img width="1267" alt="image" src="https://user-images.githubusercontent.com/12737689/167523750-8b54fb69-db2e-454e-a3d3-84dcb049c904.png">

**Comment by ddukesterman** [comment]
Hi @annagrin @darshankawar 
Here is the latest debug build log using `flutter run -d chrome --verbose`

`[+1490 ms] ChromeProxyService: Initializing expression compiler for main_module.bootstrap.js with
sound null safety: true
[  +38 ms] DevHandler: Debug service listening on ws://127.0.0.1:59221/DUvRD4Ev3IU=/ws

[  +16 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 9, error: {code: -32601, message: Method not found, data: {jsonrpc:
           2.0, method: _setStreamIncludePrivateMembers, id: 9, params: {streamId: Stdout,
           includePrivateMembers: false}}}}
[   +1 ms] This app is linked to the debug service: ws://127.0.0.1:59221/DUvRD4Ev3IU=/ws
[   +2 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 10, error: {code: -32601, message: Method not found, data: {jsonrpc:
           2.0, method: _setStreamIncludePrivateMembers, id: 10, params: {streamId: Stderr,
           includePrivateMembers: false}}}}
[   +2 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 11, error: {code: -32601, message: Method not found, data: {jsonrpc:
           2.0, method: _setStreamIncludePrivateMembers, id: 11, params: {streamId: Isolate,
           includePrivateMembers: false}}}}
[   +6 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 12, error: {code: -32601, message: Method not found, data: {jsonrpc:
           2.0, method: _setStreamIncludePrivateMembers, id: 12, params: {streamId: Extension,
           includePrivateMembers: false}}}}
[   +5 ms] Debug service listening on ws://127.0.0.1:59221/DUvRD4Ev3IU=/ws
[        ] 💪 Running with sound null safety 💪
[   +1 ms] 🔥  To hot restart changes while running, press "r" or "R".
[        ] For a more detailed help message, press "h". To quit, press "q".
[        ] An Observatory debugger and profiler on Chrome is available at:
http://127.0.0.1:59221/DUvRD4Ev3IU=
[  +10 ms] Flutter Web Bootstrap: Auto
[+4203 ms] DevHandler: Stopped debug service on ws://127.0.0.1:44456`


I know it has been a while and there has been many updates to the SDK, It seems there is an error shown here ` VmService proxy responded with an error`.

**Comment by annagrin** [comment]
@ddukesterman unfortunately this is a known error but it does not interfere with the debugger (an API throws but the debugger continues normally. So the problem is still unknown at this point. Did you have any luck with the debug extension by any chance?

**Comment by ddukesterman** [comment]
> ...Did you have any luck with the debug extension by any chance?

@annagrin I am unable to have any luck with the debug extension. I see the same output as seen in the past. I wonder if the issue is similar to @rafall 's being a Chrome Enterprise version.

**Comment by JaapHaitsma** [comment]
Same problem here. Also running Chrome enterprise here

**Comment by JaapHaitsma** [comment]
OK I installed this chromium 
`brew install --cask eloston-chromium`
and then die
`export CHROME_EXECUTABLE="/Applications/Chromium.app/Contents/MacOS/Chromium"`

and with that it works fine. So it definitely is something with Chrome Enterprise

**Comment by alexandr-efimov** [comment]
Same issue is still actual with my mac. As described above, Chromium helps!

<img width="663" alt="image" src="https://user-images.githubusercontent.com/13253360/198730062-e2a1cfdc-577d-4cbc-b4af-d7c3490eb9cd.png">

doctor:
`oleksandryefymov@obil-oyefymov ebooks_app_test % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.6, on macOS 12.5.1 21G83 darwin-x64, locale en-GB)
[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.`

**Comment by adrienbusin** [comment]
Same issue for with Chrome Enterprise on Mac! 
Chromium fix the issue  🙂

**Comment by christopherfujino** [comment]
> Same issue for with Chrome Enterprise on Mac! Chromium fix the issue slightly_smiling_face

@annagrin could it be corporations are disabling some feature we rely on for debugging in enterprise chrome?

**Comment by christopherfujino** [comment]
cc @elliette

**Comment by christopherfujino** [comment]
I am going to lower the priority of this, as we have not been able to reproduce and it sounds like there exists workaround using open source chromium. Please feel free to share if you are able to provide reproduction steps.

**Comment by yjbanov** [comment]
Sounds like this one is no longer reproducible. Closing.
