### ISSUE TITLE
Separate beta from beta candidates

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#99163]
After dev was deprecated we have been maintaining two sets of branches in the beta configurations: the current beta and the next beta candidates. With the current configurations we can only use a version of recipes to build/test both. This is becoming problematic because beta candidates are closer to main while the current beta deviates from main.

To fix this issue we need to create configurations to trigger beta candidate builds using the main recipes configuration.

**Comment by godofredoc** [comment]
\cc @CaseyHillers @itsjustkevin

**Comment by CaseyHillers** [comment]
With the migration to the Cocoon scheduler, this should be fixed.

We now generate recipe bundles for every flutter/flutter branch, which is getting changes running on the correct recipe version. Additionally, properties are passed from the ci.yaml at that commit.
