### ISSUE TITLE
TAP failure finalizeCoverage is missing formatter parameter host_entrypoint.dart:507:9: Error: No named parameter with the name 'formatter'. 

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#99175]
`formatter` parameter removed in https://github.com/flutter/flutter/pull/98513
Used in g3 tool here: https://source.corp.google.com/piper///depot/google3/mobile/flutter/testing/flutter_test/host_entrypoint/lib/host_entrypoint.dart;l=507;ws=tap-prod-presubmit%2F173605486;cl=4?snapshot=4

This needs a g3fix or it won't build when it rolls.  Also it's making some PR `Google testing` FRoB runs fail cl/430863274

**Comment by jmagman** [comment]
cc @christopherfujino @bkonyi

**Comment by jmagman** [comment]
Wait looks like there was a g3fix cl/429313216 maybe I'm just confused by the FRoB UI since it's not in that tab, probably because it's post-submit?

**Comment by christopherfujino** [comment]
ok, per internal discussion, it sounds like this is WAI, Ben's PR did have a breaking change, but the g3fix was applied correctly.
