### ISSUE TITLE
When moved from staging -> prod (bringup = false) the first run shown in the dashboard uses the staging build number instead of the prod build number

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#99173]
`Mac module_test_ios` was marked flaky, and was running in staging with build numbers 629 ,630, [631](https://ci.chromium.org/p/flutter/builders/staging/Mac%20module_test_ios/631)...
<img width="267" alt="Screen Shot 2022-02-25 at 11 56 10 AM" src="https://user-images.githubusercontent.com/682784/155786270-4480791f-049a-4d85-8df6-6b47ee9002bd.png">

It was marked unflaky and moved back to prod in https://github.com/flutter/flutter/pull/99009.  The first time it ran in prod in the dashboard it correctly shows links to `prod` but incorrectly lists the n+1 staging build number, instead of the prod build number.

The first build listed is incorrectly [prod 632](https://ci.chromium.org/p/flutter/builders/prod/Mac%20module_test_ios/632), which is ancient (and happened to fail), and the next is correctly [prod 5245](https://ci.chromium.org/p/flutter/builders/prod/Mac%20module_test_ios/5245).
<img width="218" alt="Screen Shot 2022-02-25 at 11 58 42 AM" src="https://user-images.githubusercontent.com/682784/155786629-0551b4e3-97bd-4864-8cad-cf46b43528d5.png">

This made me start investigating why this test was "flaky" again when it really wasn't.

**Comment by CaseyHillers** [comment]
This will get fixed once we've finished our migration off the LUCI scheduler to Cocoon (tracked in https://github.com/flutter/flutter/issues/92300)

ETA is EOQ

**Comment by CaseyHillers** [comment]
Cocoon scheduler migration is complete, thanks @keyonghan !
