### ISSUE TITLE
[Impeller] Refactor path polyline creation

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#99177]
See https://github.com/flutter/impeller/pull/34

* Insert a 0, 0 move component at the beginning of every path.
* Overwrite the last move component for back-to-back MoveTos (never have multiple MoveTos in a row for the component stream).
* Never return the first point in the component CreatePolyline methods.
* For move components, append the destination point to the polyline.

**Comment by dnfield** [comment]
From some offline conversation between @chinmaygarde and I - this might help performance, but it's probably not critical for performance. That said, it does make the polylines easier to work with and make it less likely to make mistakes in algorithms that assume they won't encounter duplicated points.
