### ISSUE TITLE
Element subclasses can't clear `dirty` flag

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#99172]
Custom elements that are subclassing `Element` directly cannot clear the `dirty` [1] flag because the backing property `_dirty` is not accessible to them outside of the `framework.dart` file. To properly clear that flag in custom Elements, one must extend one of the provided subclasses of Element (e.g. ComponentElement), which do implement proper clearing logic.

We should either document that Element shouldn't be extended directly or provide API to properly deal with the `dirty` flag in subclasses.

[1] https://master-api.flutter.dev/flutter/widgets/Element/dirty.html

**Comment by alestiago** [comment]
@goderbauer has a decision been made here?

Are we leaning towards documentation or API change?

**Comment by goderbauer** [comment]
I fixed this recently in https://github.com/flutter/flutter/pull/109401, but apparently forgot to link it to this issue.
