### ISSUE TITLE
Scorecard security check failing on Impeller

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#99185]
The scorecard check started failing in impeller starting on one of my [commits](https://github.com/flutter/impeller/commit/319194d5fe7dbe6a86a4fada5e2ea88e1048231e) yesterday, but I'm not sure how to diagnose the problem. Is there a different dashboard that has more diagnostic/actionable output? I'm not seeing any here: https://github.com/flutter/impeller/runs/5327601854?check_suite_focus=true

(FYI @chinmaygarde and @dnfield -- in case you've been getting emails about the failures)

**Comment by dnfield** [comment]
Closing this since scorecard is disabled. I don't think we even need a bug to track this either since Impeller will be folded into the engine repo before very much longer anyway.
