### ISSUE TITLE
showTimePicker: Can't force 12-hour format for locales that default to a 24-hour format

### ISSUE THREAD

**Issue by touficbatache** [flutter/flutter#99184]
Issue #54839 has been closed for no reason, this is still an issue that needs to be fixed...

**Comment by touficbatache** [comment]
A good solution would be adding the `locale` parameter to `showTimePicker`, just as the `showDatePicker` has one.

**Comment by darshankawar** [comment]
@touficbatache 
Per [this](https://github.com/flutter/flutter/issues/54839#issuecomment-630942835) comment mentioned in the original issue you linked, the issue seem to be resolved and hence it was closed.



> A good solution would be adding the `locale` parameter to `showTimePicker`, just as the `showDatePicker` has one.

This sounds more like a proposal / feature request for `showTimePicker`. For that, could you please update your original description per feature request [template](https://github.com/flutter/flutter/issues/new?assignees=&labels=&template=3_feature_request.md&title=) from new issue ?
