### ISSUE TITLE
library.rb:275: [BUG] Bus Error at 0x00000001042fc000

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#99195]
## Steps to reproduce

1. On an M1 Mac...
1. Clone the repo at https://github.com/wmleler/thematrix
1. Enable macos for the project by running `flutter create --platforms=macos .`
1. Ensure that macos is enabled by running `flutter config --enable-macos-desktop`
1. Install Cocoapods from scratch using `sudo gem install cocoapods` (as instructed by https://guides.cocoapods.org/using/getting-started.html#installation, which is pointed to by `flutter doctor`)
1. Attempt to run the app using `flutter run -d macos`

## Expected behavior

You expect the app to run (it's out of date and has errors after running, but it still should be able to run).

## Actual behavior

You get an error building.  The main error is:

```
/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.3/lib/ffi/library.rb:275: [BUG] Bus Error at 0x00000001042fc000
```

Googling for that error will eventually lead you to https://github.com/CocoaPods/CocoaPods/issues/10723#issuecomment-864408657

So then, you run:

```
sudo arch -x86_64 gem install ffi
```

But when you run the app again, you still get the same error.

It turns out that you can get it working by applying the following patch to flutter_tools:

```diff
diff --git a/packages/flutter_tools/lib/src/macos/cocoapods.dart b/packages/flutter_tools/lib/src/macos/cocoapods.dart
index 8e7a08f62c..c0ce393d03 100644
--- a/packages/flutter_tools/lib/src/macos/cocoapods.dart
+++ b/packages/flutter_tools/lib/src/macos/cocoapods.dart
@@ -311,7 +311,7 @@ class CocoaPods {
   Future<void> _runPodInstall(XcodeBasedProject xcodeProject, BuildMode buildMode) async {
     final Status status = _logger.startProgress('Running pod install...');
     final ProcessResult result = await _processManager.run(
-      <String>['pod', 'install', '--verbose'],
+      <String>['arch', '-x86_64', 'pod', 'install', '--verbose'],
       workingDirectory: _fileSystem.path.dirname(xcodeProject.podfile.path),
       environment: <String, String>{
         // See https://github.com/flutter/flutter/issues/10873.
```

... but presumably we shouldn't be unconditionally running that.

**Comment by christopherfujino** [comment]
So, we're already detecting a similar error, and recommend a similar workaround: https://github.com/flutter/flutter/pull/94385

@tvolkert I wonder, does `arch -x86_64 sudo gem install ffi` work (with the sudo after the arch call)?

**Comment by eseidelGoogle** [comment]
I hit this today and followed instructions from https://stackoverflow.com/questions/69867593/flutter-run-crash-on-ios-error-running-pod-install

To do:
```
sudo arch -x86_64 gem install ffi

arch -x86_64 pod install
```
in the "ios" folder, and then `flutter build ios` worked just fine. :)

It also may be Google-mac specific?  I don't know if we have a different ruby than default on these machines (I know we used to have a non-standard python which sometimes caused problems).

**Comment by jmagman** [comment]
https://github.com/flutter/flutter/pull/101796 wasn't complete, I just hit this myself.
New PR @ https://github.com/flutter/flutter/pull/102327
