### ISSUE TITLE
flutter doctor isn't local-project-aware (was: flutter doctor says my android is good, but building says I need to accept license for 23 ?)

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#9920]
Just tried to build an app, but got this error:

```
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Error running gradle: Exit code 1 from: /Applications/Android Studio.app/Contents/gradle/gradle-3.2/bin/gradle app:properties
Launching lib/main.dart on Pixel in release mode...
Running 'gradle assembleRelease'...                       
Checking the license for package Android SDK Build-Tools 23.0.1 in /Users/sethladd/Library/Android/sdk/licenses
Warning: License for package Android SDK Build-Tools 23.0.1 not accepted.
Checking the license for package Android SDK Platform 23 in /Users/sethladd/Library/Android/sdk/licenses
Warning: License for package Android SDK Platform 23 not accepted.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > You have not accepted the license agreements of the following SDK components:
     [Android SDK Platform 23, Android SDK Build-Tools 23.0.1].
     Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
     Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html
   > Could not get unknown property 'compileDebugJavaWithJavac' for project ':app' of type org.gradle.api.Project.


```

However, flutter doctor says:

```
sethladd@sethladd-macbookpro ~/Code/posse_gallery (master) $ flutter doctor
[✓] Flutter (on Mac OS X 10.12.4 16E195, channel unknown)
    • Flutter at /Users/sethladd/Code/flutter
    • Framework revision 7c770e1e77 (4 days ago), 2017-05-05 11:41:45 -0700
    • Engine revision 0071651ecb
    • Tools Dart version 1.23.0-dev.11.11

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/sethladd/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[-] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    • ios-deploy 1.9.1
    ✗ CocoaPods installed but not initialized.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To initialize CocoaPods, run:
        pod setup
      once to finalize CocoaPods' installation.

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[-] IntelliJ IDEA Community Edition (version 2016.3.5)
    • Dart plugin version 163.13137
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/managing-plugins.html

[✓] Connected devices
```

Do we have confusion around which version of Android SDK we need ? 23 or 25?

If I really need 23 and I need the license accepted, can flutter doctor report this?

Thanks!

**Comment by sethladd** [comment]
cc @mit-mit is this from plugins?

**Comment by mit-mit** [comment]
No, unrelated to plugins.

This is another manifestation of https://github.com/flutter/flutter/issues/8438

**Comment by sethladd** [comment]
I'm confused. I was building apps last night.

I confirmed this is a problem with my specific app. My specific app requires Android 23 (not sure why).

So, we may want flutter doctor to be local-project-aware, as well.

**Comment by mit-mit** [comment]
I don't think it makes sense for doctor to be project specific. What does make sense is for doctor to check that Android licenses have been accepted. If they have, gradle will get the right version of build tools. The current error is that your project gradle file says it wants a version your system don't have, and it can't get it for you as you havn't accepted the license that allows it to download it.

**Comment by sethladd** [comment]
FWIW it would be fantastic if flutter_tool told me how to run "sdkmanager" and get the right thing. Or, better yet, give me a command-line to just copy and paste into my terminal.  `Fix this by running:  sdkmanager "platforms;android-23"`

**Comment by mit-mit** [comment]
Yes, that (giving you an error with a string you can paste into the terminal) is what is being fixed over in https://github.com/flutter/flutter/issues/8438.

**Comment by sethladd** [comment]
> check that Android licenses have been accepted

that's not sufficient. I had license accepted for Android 25, but not Android 23. That's why doctor says I was "good to go" but my specific project failed to build.

**Comment by sethladd** [comment]
Confirmed: the issue was, for whatever reason, posse_gallery requires that I had downloaded Android SDK 23. I had the license accepted for 25, but that was not sufficient.

To fix the problem, I ran `sdkmanager "platforms;android-23"` and then I could build.

> The current error is that your project gradle file says it wants a version your system don't have, 

That's correct.

> and it can't get it for you as you havn't accepted the license that allows it to download it.

Also correct. But I want to point out that accepting the license for 25 isn't sufficient for all other versions of the SDK.

**Comment by sethladd** [comment]
I think we can error out early, too. When a user runs "flutter build ..." or "flutter run ..." we can look at which versions of Android are required, check if they are downloaded and licenses accepted. If not, we can error out early and say "you'll need to download version XX , do so by running ..."

**Comment by lukef** [comment]
The Posse Gallery needs build tools 23.0.x for the CI APK generation (see flutter/posse_gallery#27) but the flutter tools don't request installation of the specific version of the android tools. This will be a constant battle as its super common to update your tools from time to time as they are updated and it's highly likely that you will at some point become out of sync with the project.

It would be handy to have the option to automatically install the missing version like Android Studio does.

**Comment by yjbanov** [comment]
The reason I downgraded Posse Gallery to 23 was to make APKs build on Travis. Travis [claims to accept all licenses](https://docs.travis-ci.com/user/languages/android/#Dealing-with-Licenses), but it didn't for 25. I need to find another way to get the build going on 25. [Here's the corresponding issue](https://github.com/flutter/posse_gallery/issues/27).

**Comment by mit-mit** [comment]
I think maybe you can accept the license on your desktop, and then copy the generated license file to travis?

**Comment by mit-mit** [comment]
I'm going to close this bug, as everything is either working correctly, or covered as part of https://github.com/flutter/flutter/issues/8438.

First, not that this is not about which Android SDK you have installed. It's about the separate component called 'Android SDK Build-Tools'. This is a separate install from the actual SDK.

Also note that an app declares which build tools it needs in the file `android/app/build.gradle` in the second line shown here:

```
android {
    compileSdkVersion 25
    buildToolsVersion '25.0.3'
...
```

Let's test the two cases: 

### License has been accepted

To check that the build-tools license has been accepted, check that you have an `~/Library/Android/sdk/licenses/android-sdk-license` file.

Not, let's delete all installed build tools except the latest `23.0.3`:

```
$ ls -l ~/Library/Android/sdk/build-tools/
drwxr-xr-x  23 mit  eng   782 May 10 13:57 23.0.0
drwxr-xr-x  30 mit  eng  1020 May 10 13:56 25.0.2
drwxr-xr-x  30 mit  eng  1020 May 10 13:55 25.0.3
$ rm -rf ~/Library/Android/sdk/build-tools/23.0.0
$ rm -rf ~/Library/Android/sdk/build-tools/23.0.2
```

Next, let's build `examples/hello_world` -- in a up-to-date flutter checkout this needs 23.0.3, so it should build with no issues:

```
mit-macbookpro2:hello_world mit$ flutter build apk
Running 'gradle assembleRelease'...                   3.2s
Built build/app/outputs/apk/app-release.apk (6.8MB).
```

Next, edit `android/app/build.gradle` to require 25.0.0:
```
android {
    compileSdkVersion 25
    buildToolsVersion '25.0.0'
...
```

and build:
```
mit-macbookpro2:hello_world mit$ flutter build apk
Running 'gradle assembleRelease'...
Checking the license for package Android SDK Build-Tools 25 in /Users/mit/Library/Android/sdk/licenses
License for package Android SDK Build-Tools 25 accepted.
Preparing "Install Android SDK Build-Tools 25".
"Install Android SDK Build-Tools 25" ready.
Finishing "Install Android SDK Build-Tools 25"
Installing Android SDK Build-Tools 25 in /Users/mit/Library/Android/sdk/build-tools/25.0.0
"Install Android SDK Build-Tools 25" complete.
Built build/app/outputs/apk/app-release.apk (6.8MB).
```

Works as expected!

Let's try the same, but just with build-tools 23.0.0:

```
mit-macbookpro2:hello_world mit$ flutter build apk
Running 'gradle assembleRelease'...
Checking the license for package Android SDK Build-Tools 23 in /Users/mit/Library/Android/sdk/licenses
License for package Android SDK Build-Tools 23 accepted.
Preparing "Install Android SDK Build-Tools 23".
"Install Android SDK Build-Tools 23" ready.
Finishing "Install Android SDK Build-Tools 23"
Installing Android SDK Build-Tools 23 in /Users/mit/Library/Android/sdk/build-tools/23.0.0
"Install Android SDK Build-Tools 23" complete.
Built build/app/outputs/apk/app-release.apk (6.8MB).
mit-macbookpro2:hello_world mit$
```

Works as expected!

### License has not been accepted

This is really the critical case, because as mentioned in https://github.com/flutter/flutter/issues/8438#issuecomment-299842450, on a clean machine with Android Studio installed and the Android Studio Setup Wizard completed (which installs SDK + build tools, etc.) the license is *not* marked accepted.

First, make sure the license file is deleted:
```
rm ~/Library/Android/sdk/licenses/android-sdk-license
```

Then delete the `23.0.0.` build tools we just made `hello_world` depend on:
```
rm -rf ~/Library/Android/sdk/build-tools/23.0.0/
```

Then build:
```
mit-macbookpro2:hello_world mit$ flutter build apk
Running 'gradle assembleRelease'...
Checking the license for package Android SDK Build-Tools 23 in /Users/mit/Library/Android/sdk/licenses
Warning: License for package Android SDK Build-Tools 23 not accepted.

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/mit/tmp/flutter/examples/hello_world/android/build.gradle' line: 20

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Failed to notify project evaluation listener.
      > You have not accepted the license agreements of the following SDK components:
        [Android SDK Build-Tools 23].
        Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
        Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html
      > Could not get unknown property 'compileDebugJavaWithJavac' for project ':app' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Gradle build failed: 1
```

OK, so this fails with a bad error. This is exactly what bug https://github.com/flutter/flutter/issues/8438#issuecomment-300316761 is tracking resolving! You can +1 one there if you agree!

Finally, note that we can now easily recover from this with the new doctor command:
```
mit-macbookpro2:hello_world mit$ flutter doctor --android-licenses
1 of 6 SDK package license not accepted.
Review license that has not been accepted (y/N)? y

1/1: License android-sdk-license:
---------------------------------------
...
---------------------------------------
Accept? (y/N): y
All SDK package licenses accepted
done
mit-macbookpro2:hello_world mit$ flutter build apk
Running 'gradle assembleRelease'...
Checking the license for package Android SDK Build-Tools 23 in /Users/mit/Library/Android/sdk/licenses
License for package Android SDK Build-Tools 23 accepted.
Preparing "Install Android SDK Build-Tools 23".
"Install Android SDK Build-Tools 23" ready.
Finishing "Install Android SDK Build-Tools 23"
Installing Android SDK Build-Tools 23 in /Users/mit/Library/Android/sdk/build-tools/23.0.0
"Install Android SDK Build-Tools 23" complete.
Built build/app/outputs/apk/app-release.apk (6.8MB).
mit-macbookpro2:hello_world mit$
```
