### ISSUE TITLE
Flutter web doesn't support unicode characters(𝐀𝐁𝐂𝐃𝐄𝐅𝐆𝐇𝐈𝐉𝐊𝐋𝐌𝐍) on a textfield   

### ISSUE THREAD

**Issue by DevAmma237** [flutter/flutter#99209]
Bad UTF-8 encoding found while decoding string

**Comment by darshankawar** [comment]
@DevAmma237 
It does seem to be a case of directly copy pasting into a textfield which renders it as gibberish. Try above solution and see if it helps to resolve your issue.
