### ISSUE TITLE
DraggableScrollableSheet Documentation example not working

### ISSUE THREAD

**Issue by stevenspiel** [flutter/flutter#99215]
The [documentation](https://github.com/flutter/flutter/blob/38455c515f1adf349dc5f74ef8278d85969e58e9/packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart#L232-L260) for `DraggableScrollableSheet` doesn't behave as described. Specifically, it says:

> This is a sample widget which shows a ListView that has 25 ListTiles. It starts out as taking up half the body of the Scaffold, and can be dragged up to the full height of the scaffold or down to 25% of the height of the scaffold. Upon reaching full height, the list contents will be scrolled up or down, until they reach the top of the list again and the user drags the sheet back down.

## Steps to Reproduce

Open [this dartpad example](https://dartpad.dev/?id=9e4e2769b99596a592adb9e032d7e7d9)

**Expected results:** 

I expected the sheet to be "draggable up to the full height of the scaffold"

**Actual results:** 

There was no drag ability.

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        appBar: AppBar(
          title: const Text('DraggableScrollableSheet'),
        ),
        body: SizedBox.expand(
          child: DraggableScrollableSheet(
            builder: (BuildContext context, ScrollController scrollController) {
              return Container(
                color: Colors.blue[100],
                child: ListView.builder(
                  controller: scrollController,
                  itemCount: 25,
                  itemBuilder: (BuildContext context, int index) {
                    return ListTile(title: Text('Item $index'));
                  },
                ),
              );
            },
          ),
        ),
      ),
    );
  }
}
```

https://user-images.githubusercontent.com/1630091/155860634-ee456891-dd90-40b1-91a6-ce533b013a41.mov

**Comment by danagbemava-nc** [comment]
Hi @stevenspiel, thanks for pointing this out. 

The sample does work when you run it on mobile, but it doesn't on desktop platforms. This is likely due to https://docs.flutter.dev/release/breaking-changes/default-scroll-behavior-drag. 

You should be able to get it working as expected using the sample below. 

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';

class MyCustomScrollBehavior extends MaterialScrollBehavior {
  // Override behavior methods and getters like dragDevices
  @override
  Set<PointerDeviceKind> get dragDevices => {
        PointerDeviceKind.touch,
        PointerDeviceKind.mouse,
        // etc.
      };
}

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      scrollBehavior: MyCustomScrollBehavior(),
      home: Scaffold(
        appBar: AppBar(
          title: const Text('DraggableScrollableSheet'),
        ),
        body: SizedBox.expand(
          child: DraggableScrollableSheet(
            builder: (BuildContext context, ScrollController scrollController) {
              return Container(
                color: Colors.blue[100],
                child: ListView.builder(
                  controller: scrollController,
                  itemCount: 25,
                  itemBuilder: (BuildContext context, int index) {
                    return ListTile(title: Text('Item $index'));
                  },
                ),
              );
            },
          ),
        ),
      ),
    );
  }
}
```
</details>

Can you confirm if the sample works for you?
