### ISSUE TITLE
deep-link not working.....navigation is reset on refresh

### ISSUE THREAD

**Issue by Parables** [flutter/flutter#99214]
════════ Exception caught by Flutter framework ═════════════════════════════════
The following message was thrown:
Could not navigate to initial route.
The requested route name was: "/categories/fruits"
There was no corresponding route in the app, and therefore the initial route specified will be ignored and "/" will be used instead.

════════════════════════════════════════════════════════════════════════════════

When the app is launched and I try to either refresh the page or open the same link in another tab, the app reloads and navigates back to the initial route '/'

#99124

#99098

**Comment by Parables** [comment]
#99124

**Comment by darshankawar** [comment]
@Parables 
Is it related to `go_router` package ? 
Can you elaborate properly with `flutter doctor -v`, a [minimal code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with steps to replicate ?
