### ISSUE TITLE
Flutter readOnly TextField not getting Focus on tab key press

### ISSUE THREAD

**Issue by abdulrehmananwar** [flutter/flutter#99224]
i have two textfield widgets in list. secound textfield widget is readonly. i am using it on windows . when i press tab key focus not goes into readonly textfield. if i trun off readonly then it work quite fine.

**Comment by darshankawar** [comment]
@abdulrehmananwar 
What flutter version are you on ? Although I didn't verify on Windows yet, but on macOS desktop, the focus using tab key on read-only textfield works properly. I verified this on latest stable (2.10.2).

**Comment by abdulrehmananwar** [comment]
issue resolved after turn on focused border .thanks
