### ISSUE TITLE
[Image_picker] Add desktop support

### ISSUE THREAD

**Issue by prggTheProgrammer** [flutter/flutter#99236]
## Use case
I have an app that uses the [image_picker](https://pub.dev/packages/image_picker) plugin and I wanted to add windows to my flutter project, but I can't use the image_picker on the windwos app.

## Proposal
So my proposal is to add desktop support to the image_picker plugin. The ImageSource.camera would just use the camera of the pc (if it has any) and ImageSource.gallery would just ask for a image file.

**Comment by cdprete** [comment]
> ## Use case
> I have an app that uses the [image_picker](https://pub.dev/packages/image_picker) plugin and I wanted to add windows to my flutter project, but I can't use the image_picker on the windwos app.
> 
> ## Proposal
> So my proposal is to add desktop support to the image_picker plugin. The ImageSource.camera would just use the camera of the pc (if it has any) and ImageSource.gallery would just ask for a image file.

Even though this doesn't want to close the proposal you made (I think it's good actually), I had once the same "issue" and I ended up using https://pub.dev/packages/file_picker instead.

**Comment by darshankawar** [comment]
Closing this as duplicate of https://github.com/flutter/flutter/issues/92108
