### ISSUE TITLE
[Web][Windows][Html]: Hovering over drawer icon shows a horizontal scrollbar 

### ISSUE THREAD

**Issue by Cellaryllis** [flutter/flutter#99230]
## Steps to Reproduce
1. ~~Execute `flutter run` on the code sample~~ Execute `flutter run --web-renderer html` on the code sample
2. Hover over the dashboard button on the left top
3. See that the emoji receives a horizontal scrollbar

**Expected results:** 
Do not see the horizontal scrollbar

**Actual results:** 
the emoji receives a horizontal scrollbar

```dart
Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(
          "⚔️",
        ),
      ),
      drawer: Drawer(),
      body: Center(),
    );
  }
```

```
Analyzing crashtest...                                                  
No issues found! (ran in 2.8s)
```

```
[√] Flutter (Channel stable, 2.10.2, on Microsoft Windows [Version 10.0.22000.493], locale en-US)
    • Flutter version 2.10.2 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (8 days ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Amaryllis\AppData\Local\Android\Sdk
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Amaryllis\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31112.23
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.64.2)
    • VS Code at C:\Users\Amaryllis\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.34.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.493]

    • Chrome (web)      • chrome  • web-javascript • Google Chrome 98.0.4758.102
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 98.0.1108.56

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
![chrome_vPlnTUW9P7](https://user-images.githubusercontent.com/95936504/155880552-eb64c05e-f224-439a-9a53-cbb58db7714a.png)
![chrome_PJWZrwmd9a](https://user-images.githubusercontent.com/95936504/155880553-7584006b-142c-4147-8b0b-5e1ccf919cd6.png)

[flutter_horizontal_scroll_web_issue.txt](https://github.com/flutter/flutter/files/8148552/flutter_horizontal_scroll_web_issue.txt)

**Comment by theshivamlko** [comment]
Use Unicodes or SVG or Images of this icon. Don't directly use Copy Paste these icons in code.

**Comment by Cellaryllis** [comment]
This is just a code example, in the actual app the title of the appbar on some pages can be named by the user, who can use emojis.

**Comment by darshankawar** [comment]
@Cellaryllis 
Tried the code sample using latest stable (2.10.2) using html rendering, but didn't see the behavior you reported:

<img width="640" alt="Screenshot 2022-02-28 at 3 46 56 PM" src="https://user-images.githubusercontent.com/67046386/155965882-f89280af-ad88-4f89-a16b-8e5460b072c2.png">

Does it occur evertyime you hover ? Can you try the same on another browser (e.g firefox) and check if it still persists ?

**Comment by Cellaryllis** [comment]
Apologies, the execute command should be "flutter run --web-renderer html", I had forgotten to append the web renderer to the steps to reproduce after writing web in the title. When running with this command, I can reproduce it in both Chrome and Edge. It's 100% repro rate for us.

**Comment by darshankawar** [comment]
Thanks for the update. This behavior seems to be specific to windows + web, as I am able to replicate this on that setup, but not on macOS + web.

1. On windows, running above code sample with html rendering and hovering over the drawer shows the scrollbar:

![1](https://user-images.githubusercontent.com/67046386/156118710-b6ae3ad4-41fb-4a25-b071-1b379ff3217f.png)

2. Running the same using canvaskit doesn't show the same behavior:

![2](https://user-images.githubusercontent.com/67046386/156118779-c07a3fea-5c4c-4a20-9b1a-5cb3a3ba33ba.png)


Another thing I noticed while running the same code on mac  + web is that, the distance between drawer and appbar icon is different as compared to on windows + web:


<details>
<summary> stable, master flutter doctor </summary>

```

[√] Flutter (Channel stable, 2.10.2, on Microsoft Windows [Version 10.0.19042.1526], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.2)
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.62.3)
[√] Connected device (3 available)
[√] HTTP Host Availability

• No issues found!

[√] Flutter (Channel master, 2.11.0-0.0.pre.542, on Microsoft Windows [Version 10.0.19042.1526], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.2)
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.62.3)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!


```

</details>

**Comment by yjbanov** [comment]
The issue is the `overflow` property we set on the `<p>` tag. We should fix this. It has been reported by other customers too.

**Comment by shalehaha** [comment]
Any update on this ticket?

We are seeing the similar problems on both MacOS and Windows with Chrome.

![Screen Shot 2022-04-26 at 4 22 33 PM](https://user-images.githubusercontent.com/2831856/165402458-d49e9544-f6db-412c-b699-816454d9907d.png)
![Screen Shot 2022-04-26 at 4 22 49 PM](https://user-images.githubusercontent.com/2831856/165402491-33c6423c-5837-40c0-a064-bd3f854e7527.png)

**Comment by yjbanov** [comment]
I can't find the change that did this, but I just checked and we no longer set `overflow` on the paragraph elements. This should no longer be an issue.
