### ISSUE TITLE
Missing kernel_blob.bin file in Release folder when build Flutter code into frameworks

### ISSUE THREAD

**Issue by hoangatuan** [flutter/flutter#99237]
I want to create a Flutter module, then I will embed it to native iOS project. I'm following Option B in this [document](https://docs.flutter.dev/development/add-to-app/ios/project-setup) of Flutter to create a module.   

As in the document, I executed this command: `flutter build ios-framework --output=some/path/MyApp/Flutter/` to generate Flutter code into frameworks.    
But when I imported App.xcframework and Flutter.xcframework (from same folder Debug/Profile/Release), I got this error:   
**_Failed to find snapshot: .../App.framework/flutter-assets/kernel_blob.bin_**.    

After researching, I followed this [document](https://docs.flutter.dev/development/ios-project-migration) of Flutter, I updated Thin Binary script and add Other Linker Flags.    
But when I build Flutter's code into frameworks, only App.xcframework in Debug folder have kernel_blob.bin file.    

This is my flutter config:    
[✓] Flutter (Channel stable, 2.10.2, on macOS 12.1 21C52 darwin-x64, locale en-VN)      
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)      
    ✗ cmdline-tools component is missing      
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`      
      See https://developer.android.com/studio/command-line for more details.      
    ✗ Android license status unknown.      
      Run `flutter doctor --android-licenses` to accept the SDK licenses.      
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.      
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)      
[✓] Chrome - develop for the web      
[✓] Android Studio (version 4.2)      
[✓] VS Code (version 1.64.2)      
[✓] Connected device (1 available)      
[✓] HTTP Host Availability       

I've posted a question with images in StackOverflow at this [link](https://stackoverflow.com/questions/71278489/missing-kernel-blob-bin-file-in-release-folder-when-build-flutter-code-into-fram).

How to make App.xcframework in Release folder have kernel_blob.bin file? Thank in advance for your help.

**Comment by darshankawar** [comment]
Labeling it for further insights from the team on `How to make App.xcframework in Release folder have kernel_blob.bin file?`

/cc @jmagman

**Comment by jmagman** [comment]
Release versions of your App.framework don't have `kernel_blob.bin`, I can't tell what's looking for it.

1. Can you give us the full exported Xcode logging output?
2. Please attach your host app `project.pbxproj` if you can share it.
