### ISSUE TITLE
useWideViewPort: is missing in 3.0.1 release

### ISSUE THREAD

**Issue by PawanFyers** [flutter/flutter#99238]
Some webpages are not properly displayed without default Zoom -in, or without useWidePort.
Some webpages needed to be stretched/zoomed on purpose when the webpage is launched.

Please provide feature for the same.

**Comment by danagbemava-nc** [comment]
Hi @danagbemava-nc, what package/plugin are you requesting this feature for?

Can you also provide a detailed description of the issue? As it is now, I'm not sure what exactly you're requesting or why it should be added. 

Thank you
