### ISSUE TITLE
Frame build time regression in flutter_gallery_ios__transition_perf

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#99249]
SkiaPerf is reporting regressions in average and 90th %-ile framebuild times in this benchmark:

https://flutter-flutter-perf.skia.org/e/?begin=1642956908&end=1645923376&keys=X92ead8c5190b5e262a415353fe431d08&requestType=0&xbaroffset=27665

The regression is reported on the Engine roll https://github.com/flutter/flutter/pull/98940, however there is no data for the previous two framework commits:

https://github.com/flutter/flutter/pull/98542 and https://github.com/flutter/flutter/pull/93439, however they don't look too suspicious to me.

It looks like the worst frame time has actually doubled, which is why the average is going up a lot more than the 90th %-ile:

https://flutter-flutter-perf.skia.org/e/?begin=1642789126&end=1645923376&queries=test%3Dflutter_gallery_ios__transition_perf&requestType=0

The Engine roll has mainly Dart and Skia rolls. I'm going to speculate that this is also related to recent SkParagraph changes and cc @jason-simmons.

**Comment by zanderso** [comment]
The warmup version also regressed https://flutter-flutter-perf.skia.org/e/?begin=1645546762&end=1645602561&keys=Xcdef096590ecc6afeb803ae4e6a43c0a&num_commits=50&request_type=1&xbaroffset=27666

**Comment by jason-simmons** [comment]
Bisected this to https://github.com/flutter/engine/commit/df562b8e2b7eb90b16876d4c50d7480c9294eb93

**Comment by jason-simmons** [comment]
Created a revert PR.

Based on the discussion in https://github.com/flutter/engine/pull/30664 it looks like the desired effect can be achieved by calling `FlutterViewController setViewOpaque:NO`

@chinmaygarde @cyanglaz @dnfield

**Comment by dnfield** [comment]
Agree on revert. This is too much of a penalty

**Comment by chinmaygarde** [comment]
The revert has landed. Closing.
