### ISSUE TITLE
SEO Support

### ISSUE THREAD

**Issue by dan1229** [flutter/flutter#99240]
## Proposal

I just want to know what the progress is on SEO support in Flutter - specifically with 1. crawler support and 2. meta tag support:

1. crawlers still struggle to actually render my website past the #. I understand this is an issue with all SPA/JS based apps however considering Flutter 2.0 Navigation (and the fact that this is a Google Framework) I feel we should have some better support for this? Maybe we could support native prerendering on build (like NextJS) or similar to help make the sites more crawlable.

2. meta tags need a way to be updated dynamically to support keywords and all that fun stuff

While there are a handful of plugins that help with this - like [SEO renderer](https://pub.dev/packages/seo_renderer) - I do think native support for this would be a great way to increase the popularity of the platform, especially when compared to other SPA frameworks.

Mostly just interested in if this (SEO in general) is even on the timeline for Flutter. Is this of interest at all or just not an issue the Flutter team views as a Flutter problem.

Thank you in advance!

**Comment by danagbemava-nc** [comment]
Hi @dan1229, SEO is important to the team but there are some prerequisites. See https://github.com/flutter/flutter/issues/46789#issuecomment-1007835929. 

Feel free to share your contribution in #46789. 

Closing from here as duplicate. 

Thank you
