### ISSUE TITLE
'Flutter\Flutter.h' file not found #import <Flutter\Flutter.h> - iOS

### ISSUE THREAD

**Issue by PINHOf** [flutter/flutter#99241]
## Steps to Reproduce
Executing "flutter run" or "Product > Build" in XCode, returns the following results:

1. `'Flutter/Flutter.h' file not found`
2. `Failed to emit precompiled header '/Users/john/Library/Developer/Xcode/DerivedData/Runner-fvlyqlqeqwwztgdauzjjwaczyrit/Build/Intermediates.noindex/PrecompiledHeaders/Runner-Bridging-Header-swift_1HF3Z1H43D0VW-clang_1Y2DOLIIMB8UK.pch' for bridging header '/Users/john/Documents/sample-app/ios/Runner/Runner-Bridging-Header.h'`

Bellow is the logs of the command "flutter run --verbose"
<details>
<summary>Logs</summary>
john@DESKTOP-20CT sample-app % flutter run
Launching lib/main.dart on iPhone 13 in debug mode...
Updating project for Xcode compatibility.
Upgrading Runner.xcscheme
Running Xcode build...                                                  
Xcode build done.                                           70.9s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/q1/xr_cpqc945z58gbnfhdzv0q40000gp/T/flutter_tools.usd3L6/flutt
    	er_ios_build_temp_dirGThIC8/temporary_xcresult_bundle

    /Users/john/Documents/sample-app/ios/Pods/DKPhotoGallery/DKPhotoGallery/D
    KPhotoGalleryContentVC.swift:39:52: warning: using 'class' keyword to define
    a class-constrained protocol is deprecated; use 'AnyObject' instead
    internal protocol DKPhotoGalleryContentDataSource: class {
                                                       ^~~~~
                                                       AnyObject
    /Users/john/Documents/sample-app/ios/Pods/DKPhotoGallery/DKPhotoGallery/D
    KPhotoGalleryContentVC.swift:55:50: warning: using 'class' keyword to define
    a class-constrained protocol is deprecated; use 'AnyObject' instead
    internal protocol DKPhotoGalleryContentDelegate: class {
                                                     ^~~~~
                                                     AnyObject
    /Users/john/Documents/sample-app/ios/Pods/DKPhotoGallery/DKPhotoGallery/D
    KPhotoGalleryContentVC.swift:107:14: warning:
    'automaticallyAdjustsScrollViewInsets' was deprecated in iOS 11.0: Use
    UIScrollView's contentInsetAdjustmentBehavior instead
            self.automaticallyAdjustsScrollViewInsets = false
                 ^
    /Users/john/Documents/sample-app/ios/Pods/DKPhotoGallery/DKPhotoGallery/D
    KPhotoGalleryContentVC.swift:39:52: warning: using 'class' keyword to define
    a class-constrained protocol is deprecated; use 'AnyObject' instead
    internal protocol DKPhotoGalleryContentDataSource: class {
                                                       ^~~~~
                                                       AnyObject
    /Users/john/Documents/sample-app/ios/Pods/DKPhotoGallery/DKPhotoGallery/D
    KPhotoGalleryContentVC.swift:55:50: warning: using 'class' keyword to define
    a class-constrained protocol is deprecated; use 'AnyObject' instead
    internal protocol DKPhotoGalleryContentDelegate: class {
                                                     ^~~~~
                                                     AnyObject
    /Users/john/Documents/sample-app/ios/Pods/DKPhotoGallery/DKPhotoGallery/D
    KPhotoGalleryContentVC.swift:107:14: warning:
    'automaticallyAdjustsScrollViewInsets' was deprecated in iOS 11.0: Use
    UIScrollView's contentInsetAdjustmentBehavior instead
            self.automaticallyAdjustsScrollViewInsets = false
                 ^
    /Users/john/Documents/sample-app/ios/Pods/GoogleUtilities/GoogleUtilities
    /Logger/GULLogger.m:130:20: warning: this old-style function definition is
    not preceded by a prototype [-Wstrict-prototypes]
    void GULResetLogger() {
                       ^
    /Users/john/Documents/sample-app/ios/Pods/GoogleUtilities/GoogleUtilities
    /Logger/GULLogger.m:135:29: warning: this old-style function definition is
    not preceded by a prototype [-Wstrict-prototypes]
    aslclient getGULLoggerClient() {
                                ^
    /Users/john/Documents/sample-app/ios/Pods/GoogleUtilities/GoogleUtilities
    /Logger/GULLogger.m:139:35: warning: this old-style function definition is
    not preceded by a prototype [-Wstrict-prototypes]
    dispatch_queue_t getGULClientQueue() {
                                      ^
    /Users/john/Documents/sample-app/ios/Pods/GoogleUtilities/GoogleUtilities
    /Logger/GULLogger.m:143:27: warning: this old-style function definition is
    not preceded by a prototype [-Wstrict-prototypes]
    BOOL getGULLoggerDebugMode() {
                              ^
    4 warnings generated.
    /Users/john/Documents/sample-app/ios/Pods/GoogleUtilities/GoogleUtilities
    /Logger/GULLogger.m:130:20: warning: this old-style function definition is
    not preceded by a prototype [-Wstrict-prototypes]
    void GULResetLogger() {
                       ^
    /Users/john/Documents/sample-app/ios/Pods/GoogleUtilities/GoogleUtilities
    /Logger/GULLogger.m:135:29: warning: this old-style function definition is
    not preceded by a prototype [-Wstrict-prototypes]
    aslclient getGULLoggerClient() {
                                ^
    /Users/john/Documents/sample-app/ios/Pods/GoogleUtilities/GoogleUtilities
    /Logger/GULLogger.m:139:35: warning: this old-style function definition is
    not preceded by a prototype [-Wstrict-prototypes]
    dispatch_queue_t getGULClientQueue() {
                                      ^
    /Users/john/Documents/sample-app/ios/Pods/GoogleUtilities/GoogleUtilities
    /Logger/GULLogger.m:143:27: warning: this old-style function definition is
    not preceded by a prototype [-Wstrict-prototypes]
    BOOL getGULLoggerDebugMode() {
                              ^
    4 warnings generated.
    /Users/john/Documents/sample-app/ios/Pods/FirebaseCore/FirebaseCore/Sourc
    es/FIRLogger.m:61:28: warning: this old-style function definition is not
    preceded by a prototype [-Wstrict-prototypes]
    void FIRLoggerInitializeASL() {
                               ^
    /Users/john/Documents/sample-app/ios/Pods/FirebaseCore/FirebaseCore/Sourc
    es/FIRLogger.m:104:20: warning: this old-style function definition is not
    preceded by a prototype [-Wstrict-prototypes]
    void FIRResetLogger() {
                       ^
    2 warnings generated.
    /Users/john/Documents/sample-app/ios/Pods/FirebaseCore/FirebaseCore/Sourc
    es/FIRLogger.m:61:28: warning: this old-style function definition is not
    preceded by a prototype [-Wstrict-prototypes]
    void FIRLoggerInitializeASL() {
                               ^
    /Users/john/Documents/sample-app/ios/Pods/FirebaseCore/FirebaseCore/Sourc
    es/FIRLogger.m:104:20: warning: this old-style function definition is not
    preceded by a prototype [-Wstrict-prototypes]
    void FIRResetLogger() {
                       ^
    2 warnings generated.
    /Users/john/Documents/sample-app/ios/Pods/FirebaseInstanceID/Firebase/Ins
    tanceID/FIRInstanceIDVersionUtilities.m:33:45: warning: this old-style
    function definition is not preceded by a prototype [-Wstrict-prototypes]
    void FIRInstanceIDParseCurrentLibraryVersion() {
                                                ^
    1 warning generated.
    /Users/john/Documents/sample-app/ios/Pods/FirebaseInstanceID/Firebase/Ins
    tanceID/FIRInstanceID.m:154:8: warning: 'FIRInstanceID' is deprecated:
    FIRInstanceID is deprecated, please use FIRInstallations for installation
    identifier handling and use FIRMessaging for FCM registration token
    handling. [-Wdeprecated-declarations]
    static FIRInstanceID *gInstanceID;
           ^
    In file included from
    /Users/john/Documents/sample-app/ios/Pods/FirebaseInstanceID/Firebase/Ins
    tanceID/FIRInstanceID.m:17:
    /Users/john/Documents/sample-app/ios/Pods/FirebaseInstanceID/Firebase/Ins
    tanceID/Public/FIRInstanceID.h:190:1: note: 'FIRInstanceID' has been
    explicitly marked deprecated here
    __deprecated_msg("FIRInstanceID is deprecated, please use FIRInstallations
    for installation "
    ^
    In module 'Foundation' imported from
    /Users/john/Documents/sample-app/ios/Pods/FirebaseInstanceID/Firebase/Ins
    tanceID/Public/FIRInstanceID.h:17:
    In module 'CoreFoundation' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator15.2.sdk/System/Library/Frameworks/Foundatio
    n.framework/Headers/Foundation.h:6:
    In module 'Darwin' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator15.2.sdk/System/Library/Frameworks/CoreFound
    ation.framework/Headers/CoreFoundation.h:16:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator15.2.sdk/usr/include/sys/cdefs.h:208:48:
    note: expanded from macro '__deprecated_msg'
            #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                          ^
    1 warning generated.
    /Users/john/Documents/sample-app/ios/Pods/FirebaseInstanceID/Firebase/Ins
    tanceID/FIRInstanceIDVersionUtilities.m:33:45: warning: this old-style
    function definition is not preceded by a prototype [-Wstrict-prototypes]
    void FIRInstanceIDParseCurrentLibraryVersion() {
                                                ^
    1 warning generated.
    /Users/john/Documents/sample-app/ios/Pods/FirebaseInstanceID/Firebase/Ins
    tanceID/FIRInstanceID.m:154:8: warning: 'FIRInstanceID' is deprecated:
    FIRInstanceID is deprecated, please use FIRInstallations for installation
    identifier handling and use FIRMessaging for FCM registration token
    handling. [-Wdeprecated-declarations]
    static FIRInstanceID *gInstanceID;
           ^
    In file included from
    /Users/john/Documents/sample-app/ios/Pods/FirebaseInstanceID/Firebase/Ins
    tanceID/FIRInstanceID.m:17:
    /Users/john/Documents/sample-app/ios/Pods/FirebaseInstanceID/Firebase/Ins
    tanceID/Public/FIRInstanceID.h:190:1: note: 'FIRInstanceID' has been
    explicitly marked deprecated here
    __deprecated_msg("FIRInstanceID is deprecated, please use FIRInstallations
    for installation "
    ^
    In module 'Foundation' imported from
    /Users/john/Documents/sample-app/ios/Pods/FirebaseInstanceID/Firebase/Ins
    tanceID/Public/FIRInstanceID.h:17:
    In module 'CoreFoundation' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator15.2.sdk/System/Library/Frameworks/Foundatio
    n.framework/Headers/Foundation.h:6:
    In module 'Darwin' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator15.2.sdk/System/Library/Frameworks/CoreFound
    ation.framework/Headers/CoreFoundation.h:16:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator15.2.sdk/usr/include/sys/cdefs.h:208:48:
    note: expanded from macro '__deprecated_msg'
            #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                          ^
    1 warning generated.
    /Users/john/Documents/sample-app/ios/Pods/FirebaseMessaging/FirebaseMessa
    ging/Sources/FIRMessagingTopicOperation.m:29:42: warning: this old-style
    function definition is not preceded by a prototype [-Wstrict-prototypes]
    NSString *FIRMessagingSubscriptionsServer() {
                                             ^
    1 warning generated.
    /Users/john/Documents/sample-app/ios/Pods/FirebaseMessaging/FirebaseMessa
    ging/Sources/FIRMessagingTopicOperation.m:29:42: warning: this old-style
    function definition is not preceded by a prototype [-Wstrict-prototypes]
    NSString *FIRMessagingSubscriptionsServer() {
                                             ^
    1 warning generated.
    /Users/john/Documents/sample-app/ios/Pods/DKImagePickerController/Sources
    /DKImagePickerController/View/DKAssetGroupDetailVC.swift:344:14: warning:
    'frameInterval' was deprecated in iOS 10.0: preferredFramesPerSecond
            link.frameInterval = 1
                 ^
    /Users/john/Documents/sample-app/ios/Pods/DKImagePickerController/Sources
    /DKImagePickerController/View/DKAssetGroupDetailVC.swift:344:14: warning:
    'frameInterval' was deprecated in iOS 10.0: preferredFramesPerSecond
            link.frameInterval = 1
                 ^
    /Users/john/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/file_picke
    r-2.1.4/ios/Classes/FilePickerPlugin.m:221:68: warning: implicit conversion
    from enumeration type 'enum UIImagePickerControllerImageURLExportPreset' to
    different enumeration type 'enum DKImageExportPresent' [-Wenum-conversion]
            exportConfiguration.imageExportPreset = allowCompression ?
            UIImagePickerControllerImageURLExportPresetCompatible :
            UIImagePickerControllerImageURLExportPresetCurrent;
                                                  ~
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                  ~~~~~~~~~~~~~~~~~~~~~~~
    /Users/john/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/file_picke
    r-2.1.4/ios/Classes/FilePickerPlugin.m:221:124: warning: implicit conversion
    from enumeration type 'enum UIImagePickerControllerImageURLExportPreset' to
    different enumeration type 'enum DKImageExportPresent' [-Wenum-conversion]
            exportConfiguration.imageExportPreset = allowCompression ?
            UIImagePickerControllerImageURLExportPresetCompatible :
            UIImagePickerControllerImageURLExportPresetCurrent;
                                                  ~
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                  ~~~~~~~~~~~~~~~~~~~~
    /Users/john/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/file_picke
    r-2.1.4/ios/Classes/FilePickerPlugin.m:294:1: warning: implementing
    deprecated method [-Wdeprecated-implementations]
    - (void)documentPicker:(UIDocumentPickerViewController *)controller
    didPickDocumentAtURL:(NSURL *)url{
    ^
    In module 'UIKit' imported from
    /Users/john/Documents/sample-app/ios/Pods/Target Support
    Files/file_picker/file_picker-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator15.2.sdk/System/Library/Frameworks/UIKit.fra
    mework/Headers/UIDocumentPickerViewController.h:27:1: note: method
    'documentPicker:didPickDocumentAtURL:' declared here
    - (void)documentPicker:(UIDocumentPickerViewController *)controller
    didPickDocumentAtURL:(NSURL *)url
    API_DEPRECATED_WITH_REPLACEMENT("documentPicker:didPickDocumentsAtURLs:",
    ios(8.0, 11.0));
    ^
    3 warnings generated.
    /Users/john/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/file_picke
    r-2.1.4/ios/Classes/FilePickerPlugin.m:221:68: warning: implicit conversion
    from enumeration type 'enum UIImagePickerControllerImageURLExportPreset' to
    different enumeration type 'enum DKImageExportPresent' [-Wenum-conversion]
            exportConfiguration.imageExportPreset = allowCompression ?
            UIImagePickerControllerImageURLExportPresetCompatible :
            UIImagePickerControllerImageURLExportPresetCurrent;
                                                  ~
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                  ~~~~~~~~~~~~~~~~~~~~~~~
    /Users/john/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/file_picke
    r-2.1.4/ios/Classes/FilePickerPlugin.m:221:124: warning: implicit conversion
    from enumeration type 'enum UIImagePickerControllerImageURLExportPreset' to
    different enumeration type 'enum DKImageExportPresent' [-Wenum-conversion]
            exportConfiguration.imageExportPreset = allowCompression ?
            UIImagePickerControllerImageURLExportPresetCompatible :
            UIImagePickerControllerImageURLExportPresetCurrent;
                                                  ~
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                  ~~~~~~~~~~~~~~~~~~~~
    /Users/john/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/file_picke
    r-2.1.4/ios/Classes/FilePickerPlugin.m:294:1: warning: implementing
    deprecated method [-Wdeprecated-implementations]
    - (void)documentPicker:(UIDocumentPickerViewController *)controller
    didPickDocumentAtURL:(NSURL *)url{
    ^
    In module 'UIKit' imported from
    /Users/john/Documents/sample-app/ios/Pods/Target Support
    Files/file_picker/file_picker-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator15.2.sdk/System/Library/Frameworks/UIKit.fra
    mework/Headers/UIDocumentPickerViewController.h:27:1: note: method
    'documentPicker:didPickDocumentAtURL:' declared here
    - (void)documentPicker:(UIDocumentPickerViewController *)controller
    didPickDocumentAtURL:(NSURL *)url
    API_DEPRECATED_WITH_REPLACEMENT("documentPicker:didPickDocumentsAtURLs:",
    ios(8.0, 11.0));
    ^
    3 warnings generated.
    /Users/john/Documents/sample-app/ios/Runner/Runner-Bridging-Header.h:1:9:
    note: in file included from
    /Users/john/Documents/sample-app/ios/Runner/Runner-Bridging-Header.h:1:
    #import "GeneratedPluginRegistrant.h"
            ^
    /Users/john/Documents/sample-app/ios/Runner/GeneratedPluginRegistrant.h:1
    0:9: error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^
    1 error generated.
    <unknown>:0: error: failed to emit precompiled header
    '/Users/john/Library/Developer/Xcode/DerivedData/Runner-fvlyqlqeqwwztgdauzj
    jwaczyrit/Build/Intermediates.noindex/PrecompiledHeaders/Runner-Bridging-Hea
    der-swift_3AF8PW1L0EUT0-clang_1Y2DOLIIMB8UK.pch' for bridging header
    '/Users/john/Documents/sample-app/ios/Runner/Runner-Bridging-Header.h'
    /Users/john/Documents/sample-app/ios/Runner/Runner-Bridging-Header.h:1:9:
    note: in file included from
    /Users/john/Documents/sample-app/ios/Runner/Runner-Bridging-Header.h:1:
    #import "GeneratedPluginRegistrant.h"
            ^
    2 errors generated.
    error: generate-pch command failed with exit code 1 (use -v to see
    invocation)
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order

    Result bundle written to path:
    	/var/folders/q1/xr_cpqc945z58gbnfhdzv0q40000gp/T/flutter_tools.usd3L6/flutt
    	er_ios_build_temp_dirGThIC8/temporary_xcresult_bundle


Error (Xcode): 'Flutter/Flutter.h' file not found
/Users/john/Documents/sample-app/ios/Runner/GeneratedPluginRegistrant.h:9:8


Error (Xcode): failed to emit precompiled header
'/Users/john/Library/Developer/Xcode/DerivedData/Runner-fvlyqlqeqwwztgdauzjjwac
zyrit/Build/Intermediates.noindex/PrecompiledHeaders/Runner-Bridging-Header-swif
t_3AF8PW1L0EUT0-clang_1Y2DOLIIMB8UK.pch' for bridging header
'/Users/john/Documents/sample-app/ios/Runner/Runner-Bridging-Header.h'


Could not build the application for the simulator.
Error launching application on iPhone 13.
</details>

**Flutter doctor -v:**
```
[✓] Flutter (Channel stable, 2.10.2, on macOS 12.2.1 21D62 darwin-x64, locale en-GB)
    • Flutter version 2.10.2 at /Users/john/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (9 days ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/john/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /usr/bin/java
    ✗ Could not determine java version

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google
    Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed
      instructions).

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • iPhone 13 (mobile) • B4FC31BD-940B-4B89-88C6-5AE341552104 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

**What have I done**:
Pretty much everything I could find by googling this error, like all the solutions in this links:

1. https://fluttercorner.com/error-flutter-flutter-h-file-not-found-when-flutter-run-on-ios/
2. https://www.kindacode.com/article/flutter-fatal-error-flutter-flutter-h-file-not-found/

This error only happens in iOS/macOS machine, it works great in my Windows/Android machine.

And yes, I have seen similiar issues such as https://github.com/flutter/flutter/issues/70895 and tried the solutions.

**Comment by PINHOf** [comment]
**Solved**.

Two problems:
1. Flutter versio -, since this is a project with at least 1 year, in my Windows machine I'm using Flutter 2.0.4 and in macOS I did a new Flutter installation which brings the newest Flutter version 2.10x
2. Some of my dependencies are now old and must be updated. Applying `any` to the dependencies fixed the problems too

**Comment by GHO5TMEDO** [comment]
> **Solved**.
> 
> Two problems:
> 
> 1. Flutter version - since this is an old project, in my Windows machine I'm using Flutter 2.0.4 and in macOS I did a new Flutter installation which brings the newest Flutter version 2.10x. The solution was to downgrade the macOS version into 2.0.4
> 2. Some of my dependencies are now old and must be updated. Applying `any` to the dependencies fixed the problems too

Not working for me on Mac m1.
