### ISSUE TITLE
Throws an error while building an apk using GitHub Action.

### ISSUE THREAD

**Issue by Prajun2010** [flutter/flutter#99259]
After adding the location package to the project, the GitHub action throws an error and couldn't build the apk. 
To know what went wrong, I've tried checking to build the apk on my pc but it builds perfectly. 
I really couldn't figure out where the issue is from. 
So could you please help me with this?

![Screenshot 2022-02-28 121738](https://user-images.githubusercontent.com/42827734/155935454-5fbdd528-c64b-40cb-a52b-a672ca69a0fa.jpg)

**Comment by darshankawar** [comment]
@Prajun2010 
The error seems to be pointing to the location plugin as you mentioned which is 3rd party, so I suggest you to raise this in dedicated repo: https://github.com/Lyokone/flutterlocation/issues as the error is pointing to one of it's class.

**Comment by darshankawar** [comment]
@Prajun2010 
The error `FlutterLocationService is not abstract and does not implement abstract member public abstract fun` seems to indicate it is related to Kotlin version which may not be compatible. You can search for similar issues on StackOverflow to get more details.
