### ISSUE TITLE
Better management of Android Build Tools versions

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#9925]
As discussed in https://github.com/flutter/flutter/pull/9878 and https://github.com/flutter/plugins/pull/27 and as suggested by @Hixie , it can be cumbersome to have Android build tools pinned at an exact version at the project level, as upgrading to a new versions requires edits in many places. We should investigate if this can be improved.

**Comment by iapicca** [comment]
Hi @mit-mit  is this issestill relevant?

**Comment by blasten** [comment]
This is no longer relevant.
