### ISSUE TITLE
Cannot build for ios simulator

### ISSUE THREAD

**Issue by turbomanson** [flutter/flutter#99260]
Exact the same issue here. 
No matter what I try, it's either the "fatal error: 'Flutter/Flutter.h' file not found" error, or "...The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.5.99. "

Android works totally fine though

_Originally posted by @hschk in https://github.com/flutter/flutter/issues/88860#issuecomment-922244487_

**Comment by turbomanson** [comment]
Flutter doctor:

[✓] Flutter (Channel stable, 2.10.2, on macOS 11.6 20G165 darwin-x64, locale en-US)
    • Flutter version 2.10.2 at /Users/tmanson/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (9 days ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tmanson/Library/Android/sdk
    • Platform android-31, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (4 available)
    • AOSP on IA Emulator (mobile) • emulator-5556                        • android-x86    • Android 9 (API 28) (emulator)
    • iPhone 13 (mobile)           • 208883E2-9CC7-4FB5-ACD2-79623A484037 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)              • macos                                • darwin-x64     • macOS 11.6 20G165 darwin-x64
    • Chrome (web)                 • chrome                               • web-javascript • Google Chrome 98.0.4758.109

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by turbomanson** [comment]
Podfile
`# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
`

**Comment by turbomanson** [comment]
pubspec.yaml

name: prototype
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ^2.2.0

dependencies:
  provider: ^5.0.0
  # Calendar Widget
  table_calendar: ^3.0.0
  # Collections library
  quiver: ^3.0.1
  # Add the dependency for the Firebase Core Flutter SDK
  firebase_core: ^1.2.0
  # Add the dependencies for the Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  firebase_auth: ^1.2.0
  cloud_firestore: ^2.2.0
  firebase_storage: ^8.0.0
  flutter_datetime_picker: ^1.5.1
  datetime_picker_formfield: ^2.0.0
  intl: ^0.17.0-nullsafety.2
  material_design_icons_flutter: ^5.0.5955-rc.1
  #sliding_switch: ^0.0.3
  webview_flutter: ^2.0.8
  flutter_pdfview: ^1.2.1
  simple_gesture_detector: ^0.2.0
  fl_chart: ^0.36.1
  path_provider: ^2.0.1
  flutter_spinkit: ^5.0.0
  flutter_calendar_carousel: ^2.0.1
  flame: 1.0.0-rc9
  firebase_messaging: ^10.0.0
  overlay_support: ^1.2.1
  flutter_local_notifications: ^6.0.0
  device_info: ^2.0.0
  flutter_native_timezone: ^1.0.10
  http: ^0.13.0
  rxdart: ^0.26.0-nullsafety.1
  shared_preferences: ^2.0.1
  background_fetch: ^1.0.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.0
  build_runner: ^2.0.6
  flutter_quill: ^3.9.3
  grouped_list: ^4.2.0
  charts_flutter: ^0.12.0
  url_launcher: ^6.0.20
  video_player: ^2.2.18

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/day_header.png

**Comment by turbomanson** [comment]
`name: prototype
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ^2.2.0

dependencies:
  provider: ^5.0.0
  # Calendar Widget
  table_calendar: ^3.0.0
  # Collections library
  quiver: ^3.0.1
  # Add the dependency for the Firebase Core Flutter SDK
  firebase_core: ^1.2.0
  # Add the dependencies for the Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  firebase_auth: ^1.2.0
  cloud_firestore: ^2.2.0
  firebase_storage: ^8.0.0
  flutter_datetime_picker: ^1.5.1
  datetime_picker_formfield: ^2.0.0
  intl: ^0.17.0-nullsafety.2
  material_design_icons_flutter: ^5.0.5955-rc.1
  #sliding_switch: ^0.0.3
  webview_flutter: ^2.0.8
  flutter_pdfview: ^1.2.1
  simple_gesture_detector: ^0.2.0
  fl_chart: ^0.36.1
  path_provider: ^2.0.1
  flutter_spinkit: ^5.0.0
  flutter_calendar_carousel: ^2.0.1
  flame: 1.0.0-rc9
  firebase_messaging: ^10.0.0
  overlay_support: ^1.2.1
  flutter_local_notifications: ^6.0.0
  device_info: ^2.0.0
  flutter_native_timezone: ^1.0.10
  http: ^0.13.0
  rxdart: ^0.26.0-nullsafety.1
  shared_preferences: ^2.0.1
  background_fetch: ^1.0.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.0
  build_runner: ^2.0.6
  flutter_quill: ^3.9.3
  grouped_list: ^4.2.0
  charts_flutter: ^0.12.0
  url_launcher: ^6.0.20
  video_player: ^2.2.18

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/day_header.png`

**Comment by turbomanson** [comment]
Can't find any way to resolve this.  Just lots of expired issues.

**Comment by darshankawar** [comment]
@turbomanson 
Can you provide `flutter run -v` and put the entire log in a text file and share it here ?
Also, provide your `Runner.xcodeproj/project.pbxproj`.

**Comment by YOUDevelop** [comment]
![Screen Shot 2022-02-28 at 20 34 41](https://user-images.githubusercontent.com/85257353/156076744-011c1a38-1adf-4d2a-a88c-b25f37199c1a.png)

Same error here. Cannot build.
