### ISSUE TITLE
Restrict the maximum count of images the user can pick

### ISSUE THREAD

**Issue by FIREIDEAS** [flutter/flutter#99271]
## Proposal
can you add this feature
Restrict the maximum count of images the user can pick, so the user can't pick more the number allowed to.

**Comment by maheshmnj** [comment]
Hi @FIREIDEAS, Thanks for filing the issue. Is this issue proposal regarding limiting the images picked  via image picker? If so  please read this comment https://github.com/flutter/flutter/issues/85772#issuecomment-887614127

**Comment by FIREIDEAS** [comment]
in the comment you mentioned that this feature works only on IOS, so is it hard to implement it on android?
there is a package called multi_image_picker https://pub.dev/packages/multi_image_picker2/example
that implemented it but without image quality, so is there any way to add this feature?

**Comment by maheshmnj** [comment]
>  so is there any way to add this feature?

Not that I am aware of, But you could look for other existing third-party plugins which support this feature on Android.

 Closing as per the linked comment in the above response.

**Comment by FIREIDEAS** [comment]
I have a suggestion to implement it, what if we take the number of max images number from user and select images until we reach this number then show scaffold message?
