### ISSUE TITLE
Error from source code. 

### ISSUE THREAD

**Issue by oeng-hok-leng** [flutter/flutter#99272]
I got this error after I update the flutter.

: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
../…/snackbar/snackbar.dart:452
- 'SchedulerBinding' is from 'package:flutter[/src/scheduler/binding.dart]()' ('.[./../../../../Development/flutter/packages/flutter/lib/src/scheduler/binding.dart]()').
package:flutter/…/scheduler/binding.dart:1

    SchedulerBinding.instance!.addPostFrameCallback(
                     ^
: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
../…/src/router_report.dart:53
- 'WidgetsBinding' is from 'package:flutter[/src/widgets/binding.dart]()' ('.[./../../../../Development/flutter/packages/flutter/lib/src/widgets/binding.dart]()').
package:flutter/…/widgets/binding.dart:1

**Comment by maheshmnj** [comment]
Hi @oeng-hok-leng, Thanks for filing the issue. Please share the output of `flutter run -v` in a text file along with the output of `flutter doctor -v` to investigate the issue further.

Thanks

**Comment by oeng-hok-leng** [comment]
I got this for the red color text after I run `flutter run -v ` 
[  +37 ms] ../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/get-4.6.1/lib/get_navigation/src/snackbar/snackbar.dart:452:22: Warning:
Operand of
           null-aware operation '!' has type 'SchedulerBinding' which excludes null.
[   +2 ms]  - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart'
            ('../../../../../Development/flutter/packages/flutter/lib/src/scheduler/binding.dart').
[        ]     SchedulerBinding.instance!.addPostFrameCallback(
[        ]                      ^
[        ] ../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/get-4.6.1/lib/get_navigation/src/router_report.dart:53:22: Warning: Operand
of
           null-aware operation '!' has type 'WidgetsBinding' which excludes null.
[   +1 ms]  - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart'
('../../../../../Development/flutter/packages/flutter/lib/src/widgets/binding.dart').
[        ]       WidgetsBinding.instance!.addPostFrameCallback((_) {
[        ]                      ^
[        ] ../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/get-4.6.1/lib/get_state_manager/src/simple/get_controllers.dart:90:20:
Warning:
           Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
[        ]  - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart'
('../../../../../Development/flutter/packages/flutter/lib/src/widgets/binding.dart').
[        ]     WidgetsBinding.instance!.addObserver(this);
[        ]                    ^
[        ] ../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/get-4.6.1/lib/get_state_manager/src/simple/get_controllers.dart:96:20:
Warning:
           Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
[        ]  - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart'
('../../../../../Development/flutter/packages/flutter/lib/src/widgets/binding.dart').
[   +1 ms]     WidgetsBinding.instance!.removeObserver(this);
[        ]                    ^
[   +1 ms] ../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/get-4.6.1/lib/get_state_manager/src/rx_flutter/rx_notifier.dart:130:22:
Warning:
           Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
[        ]  - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart'
            ('../../../../../Development/flutter/packages/flutter/lib/src/scheduler/binding.dart').
[        ]     SchedulerBinding.instance?.addPostFrameCallback((_) => onReady());
[        ]                      ^
[        ] ../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/get-4.6.1/lib/get_state_manager/src/rx_flutter/rx_disposable.dart:20:22:
Warning:
           Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
[   +5 ms]  - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart'
            ('../../../../../Development/flutter/packages/flutter/lib/src/scheduler/binding.dart').
[        ]     SchedulerBinding.instance?.addPostFrameCallback((_) => onReady());
[        ]                      ^
[        ] ../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/get-4.6.1/lib/get_navigation/src/extension_navigation.dart:357:24: Warning:
Operand of
           null-aware operation '!' has type 'SchedulerBinding' which excludes null.
[        ]  - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart'
            ('../../../../../Development/flutter/packages/flutter/lib/src/scheduler/binding.dart').
[        ]       SchedulerBinding.instance!.addPostFrameCallback((_) {
[        ]                        ^
[        ] ../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/get-4.6.1/lib/get_navigation/src/extension_navigation.dart:468:24: Warning:
Operand of
           null-aware operation '!' has type 'SchedulerBinding' which excludes null.
[        ]  - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart'
            ('../../../../../Development/flutter/packages/flutter/lib/src/scheduler/binding.dart').
[   +9 ms]       SchedulerBinding.instance!.addPostFrameCallback((_) {
[   +1 ms]                        ^

**Comment by oeng-hok-leng** [comment]
This is the result from `flutter doctor -v`
![Screen Shot 2022-02-28 at 8 53 56 PM](https://user-images.githubusercontent.com/68270693/155994964-9f19ff3a-7f6b-408b-bff4-302b410ac06d.png)

**Comment by maheshmnj** [comment]
@oeng-hok-leng, The logs you shared are basically warnings from a third-party package [get](https://pub.dev/packages/get) those shouldn't stop you from running the application. In case you want those warnings to be fixed and not show up in logs then that request must be made in the get Repository as that issue is related to that package and not with flutter.

Closing as this is an issue with the third-party plugin. In case you disagree feel free to write in the comments and we will reopen it.

PS: Please avoid sharing image snippets of code or logs as they don't help us in copying the information for search.

**Comment by oeng-hok-leng** [comment]
Yes, if I want to fix this warning, how can I do ?

**Comment by oeng-hok-leng** [comment]
> @oeng-hok-leng, The logs you shared are basically warnings from a third-party package [get](https://pub.dev/packages/get) those shouldn't stop you from running the application. In case you want those warnings to be fixed and not show up in logs then that request must be made in the get Repository as that issue is related to that package and not with flutter.
> 
> Closing as this is an issue with the third-party plugin. In case you disagree feel free to write in the comments and we will reopen it.
> 
> PS: Please avoid sharing image snippets of code or logs as they don't help us in copying the information for search.

thank you sir..

**Comment by maheshmnj** [comment]
> Yes, if I want to fix this warning, how can I do ?

Those warnings are basically from the get plugin, The fixes needs to be made in the plugin. The maintainer of the get package might have more info on how to fix this please report this in the get repository.

**Comment by ctrysbita** [comment]
It seems that #89451 is a breaking change on master, which breaks a wide range of plugins.

**Comment by maheshmnj** [comment]
@Hixie Are these warnings due to https://github.com/flutter/flutter/pull/89451 ?  I can see them on the master channel.

**Comment by Hixie** [comment]
Yes, running `dart fix --apply` should fix that.
