### ISSUE TITLE
Enabling arm64 packaging builder before next stable

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#99282]
Only beta and master builds are generating the arm artifacts and we protected the builders to not run on stable just in case we need another hotfix.

The builder will need to be enabled in stable before the next release to stable.

**Comment by godofredoc** [comment]
\cc @itsjustkevin @christopherfujino

**Comment by christopherfujino** [comment]
oh, is the engine change to build the arm dart sdk not in stable?

**Comment by godofredoc** [comment]
> oh, is the engine change to build the arm dart sdk not in stable?

That's correct, those changes are not yet in stable.

**Comment by christopherfujino** [comment]
Ahh, ok, sounds good to me.

**Comment by godofredoc** [comment]
This is now complete!
