### ISSUE TITLE
Selection indicator lags when being dragged around in large text

### ISSUE THREAD

**Issue by KevinTheGray** [flutter/flutter#9928]
The indicator on a TextField behaves very oddly on TextFields in Android and possibly iOS.  There are two problems 
~~1.) If you select a position in a TextField and it is within a scrollable container, the indicator will scroll with the container, and not stick to the TextField as expected.~~ see #3861.
2.) If you enter a lot of text into the TextField, select a position, then drag the indicator around back and forth, it will begin to slow down a lot and the behavior of the app can become erratic as the indicator finds its final position.

## Steps to Reproduce
Build the flutter gallery app, run it, and open the Text fields demo.  Do the above actions and notice the behavior.

I can reproduce this issue 100% of the time on a Nexus 5x.  I have attached a video of the issue below.

[device-2017-05-09-145708.mp4.zip](https://github.com/flutter/flutter/files/987750/device-2017-05-09-145708.mp4.zip)

**Comment by eseidelGoogle** [comment]
1) is https://github.com/flutter/flutter/issues/3861
However I think we can use this bug to track 2).

**Comment by Hixie** [comment]
#2 looks like we're leaking something that we walk each time you move the selection handle.

**Comment by Hixie** [comment]
@jason-simmons This might be a good one for your mystery-piercing skills.

**Comment by eseidelGoogle** [comment]
@jason-simmons mentioned at triage that he believes this may be related to or incomplete Android IME implementation.

**Comment by KevinTheGray** [comment]
It's working a lot better for me, but if you have a large block of text, the indicator will still lag as you drag it around very rapidly.  It's an edge case for sure, since you need to actively be trying to cause it to happen.  Try this in the text fields demo, enter a ton of text in "Life Story", and just start dragging it all over the text.  After a bit, it starts to lag and needs to catch up.

**Comment by eseidelGoogle** [comment]
@lukef / @KevinTheGray would you consider the remaining case a blocker still?  Happy to investigate more, just seeking to better understand the prioritization.

**Comment by eseidelGoogle** [comment]
@brianosman did you mean to close this?  Were there additional changes just now?

**Comment by eseidelGoogle** [comment]
I suspect this wasn't meant to be closed, but instead of fighting github, I've filed a new issue:
https://github.com/flutter/flutter/issues/10854
