### ISSUE TITLE
Allow adding shortcut keys to push buttons in a screen-reader friendly way

### ISSUE THREAD

**Issue by Keithcat1** [flutter/flutter#99295]
## Use case

I have a bunch of buttons (FloatingActionButton) and want to quickly and conveniently give them shortcut keys. The Shortcuts widget seems able to sort of do this, but it conseptually ties the shortcut to the window and not the button that does the same action. Also, most if not all popular screen readers support announcing a buttons shortcut key when you move over that button and I'd like to take advantage of that.
## Proposal

Add a parameter to the FloatingActionButton constructor which allows setting a hotkey which, when pressed, will activate the button. The button should also indicate its hotkey to screen readers for example, "open file button alt + O" is what such a button looks like for me. I don't know how to do that though. I happen to be a screen-reader user myself so I might be able to test it.

**Comment by cedvdb** [comment]
I'm not a screen-reader user but should there be a default shortcut for a TAB ?

**Comment by maheshmnj** [comment]
Hi @Keithcat1, Thanks for filing the issue. I believe your use case can be achieved with Focus widget when the particular widget is currently in focus.  For instance, take a look at the below code sample which prints to console on pressing (ctrl+a) only when the fab button is in focus.

<details>
<summary>flutter doctor -v</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  MyApp({Key? key}) : super(key: key);

  final FocusNode focus = FocusNode();
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: Scaffold(
        floatingActionButton: CallbackShortcuts(
          focus: focus,
          bindings: {
            LogicalKeySet(LogicalKeyboardKey.control, LogicalKeyboardKey.keyA):
                () {
              print(' do something ');
            },
          },
          child: FloatingActionButton(
            child: Icon(Icons.add),
            onPressed: () {},
          ),
        ),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              ElevatedButton(
                child: Text("Shift Focus to Fab"),
                onPressed: () {
                  focus.requestFocus();
                },
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class CallbackShortcuts extends StatelessWidget {
  const CallbackShortcuts(
      {Key? key,
      required this.bindings,
      required this.child,
      required this.focus})
      : super(key: key);

  final Map<ShortcutActivator, VoidCallback> bindings;
  final Widget child;
  final FocusNode focus;

  @override
  Widget build(BuildContext context) {
    return Focus(
      focusNode: focus,
      onKey: (FocusNode node, RawKeyEvent event) {
        KeyEventResult result = KeyEventResult.ignored;
        // Activates all key bindings that match, returns handled if any handle it.
        for (final ShortcutActivator activator in bindings.keys) {
          if (activator.accepts(event, RawKeyboard.instance)) {
            bindings[activator]!.call();
            result = KeyEventResult.handled;
          }
        }
        return result;
      },
      child: child,
    );
  }
}

```
</details>

**Comment by Keithcat1** [comment]
I think I was misunderstood somehow. I have no problem activating a FloatingActionButton just by pressing the space bar while focusing on it. What I want is the ability to add an extra shortcut key which invokes the FAB it's attached to when I press it. I'd like to be able to set this shortcut key via the FloatingActionButton constructor. Also, screen readers have special support for announcing when a button has an additional shortcut key that can be used.

**Comment by maheshmnj** [comment]
@Keithcat1 I think I understood your proposal that you want to have a shortcut key to trigger the Fab Button by having a parameter in the FAB constructor. But as per my above response, this can be achieved using Focus Widget. You could wrap focus around any widget (not just fab) and have any custom shortcut to activate the widget.

> Also, screen readers have special support for announcing when a button has an additional shortcut key that can be used.

And regarding the screen Readers announcing the shortcut key you could wrap the Semantics widget inside Focus to have screen readers read the shortcut.
