### ISSUE TITLE
Update service null ptr crash

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#993]
Reported in the wild: https://gist.github.com/stevenroose/5cbaad5dee58b63bac59

If @stevenroose has the ability to get the tombstone from the crash and post it here (along with what flutter --version says) that would be helpful.

Typically they're in `/data/tombstones/tombstones`, and can be grabbed by `adb pull`

**Comment by stevenroose** [comment]
```
$ flutter --version
Flutter
Repository: https://github.com/flutter/flutter.git
Branch: alpha
Revision: 9487197502b5fcbe14a6b2de91ed51b95f5297d5 (6 days ago)
```

```
$ adb pull /data/tombstones/tombstones
remote object '/data/tombstones/tombstones' does not exist
```
I use a Nexus 6...

**Comment by eseidelGoogle** [comment]
@mpcomplete if you're still around, I think @stevenroose needs a way to turn off the updater to prevent crashing.

**Comment by eseidelGoogle** [comment]
Since android is not providing steven logs, one way to debug would be to use a debug build of the flutter engine.

https://github.com/flutter/engine/blob/master/CONTRIBUTING.md has instructions on building your own engine.  Once you have an engine built, you could use it by passing --debug to the flutter tool.

It's definitely not the easiest process (part of why we have the flutter tool, etc.).  We have Nexus 6 devices and will definitely fix this when more of us are back in the office.  Unclear if this will get fixed before January unfortunately.

You may also just try updating your flutter sdk in the meanwhile.  Not sure if you're using the `alpha` branch or `master`.  `alpha` should be more stable.

**Comment by stevenroose** [comment]
> Not sure if you're using the alpha branch or master. alpha should be more stable.
:)

I'm on master, will try alpha, thanks.

**Comment by stevenroose** [comment]
I currently just update with `flutter upgrade`, how can I switch branches? Just go over to `/opt/flutter`, do `git checkout` and run `flutter upgrade` again?

**Comment by stevenroose** [comment]
I'm on master again and its fixed now!

**Comment by eseidel** [comment]
Today I learned we have a flutter upgrade command:
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/upgrade.dart

It looks like it's useful for when you have flutter installed somewhere on your disk and run the flutter command from elsewhere.  We should probably make it also print out `flutter version` after completion.

Glad it's fixed.  I can close this when I'm back on my work account or someone else can before then.  @mpcomplete

**Comment by stevenroose** [comment]
The flutter upgrade pulls the git repo, so when you are on alpha, you dont
get the changes made in master :)

**Comment by abarth** [comment]
It pulls whatever branch you have set as upstream in the flutter git repo.  If you set the upstream to master, it should pull master.
