### ISSUE TITLE
[autosubmit] Checks are being falsely reported as failing

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#99306]
Example: https://github.com/flutter/packages/pull/979

**Comment by keyonghan** [comment]
Cocoon is using the first cirrus build to check the PR tests statues: https://github.com/flutter/cocoon/blob/main/app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart#L369, which has correct test results. However, the logic seems using the second build.

Based on cirrus GraphQL explorer: 
```
{
  searchBuilds(repositoryOwner: "flutter", repositoryName: "packages", SHA: "6643f49c2c18f3d2ead18a9d9dc450bc1c331d3b") {
    id
    branch
    latestGroupTasks {
      id
      name
      status
    }
  }
}
``` 
It does return the correct ordered results (the correct ones come the first).

@fkorotkov Could you please help take a look. Is there any package version we need to pin to maintain the order?

**Comment by fkorotkov** [comment]
I just checked the follwing query in the [API explorer](https://cirrus-ci.com/explorer):

```graphql
query {
  searchBuilds(repositoryOwner: "flutter", repositoryName: "packages", SHA: "6643f49c2c18f3d2ead18a9d9dc450bc1c331d3b") {
    id
    branch
    changeTimestamp
    buildCreatedTimestamp
  }
}
```

And the builds are always sorted by `buildCreatedTimestamp` as expected after my recent change. Where do you see it's reporting incorrectly?

**Comment by keyonghan** [comment]
We are relying on the first searchBuild results: https://github.com/flutter/cocoon/blob/main/app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart#L369 to check the tests.

However, for the above PR/commit sha, it throws tests alert: https://github.com/flutter/packages/pull/979#issuecomment-1054861089, which seems a match with the second searchBuild results.

I created https://github.com/flutter/cocoon/pull/1631 to log the searchBuild id to get a better idea.

**Comment by keyonghan** [comment]
It seems we get the correct `id` from the first `searchBuild`, but the incorrect test results from the second `searchBuild`..
```
First cirrus searchBuild id for flutter/packages, sha: d4dd40dfaab3bc214bafe2f149101e1d5e70174f: 4532390054854656
```
However the checks were based on statuses from the second build.

**Comment by keyonghan** [comment]
Thanks @fkorotkov , the cirrus API does return the correct results.

PR https://github.com/flutter/cocoon/pull/1632 fixed the issue by returning the first build results directly
Example: https://github.com/flutter/packages/pull/964 was submitted correctly based on the correct tests.

Closing.
