### ISSUE TITLE
Android Studio old project flutter debugger does not display sidebar, other new projects have

### ISSUE THREAD

**Issue by yimao009** [flutter/flutter#99314]
Existing flutter projects, the flutter inspector tool is not displayed when opened, and the new flutter project has these debugging tools, which is very distressing。

new flutter project pic:
[new flutter project pic:](https://github.com/yimao009/pic/blob/main/has%20tools.png?raw=true)
---
my existing flutter project pic:
[new flutter project pic:](https://github.com/yimao009/pic/blob/main/no%20tools.png?raw=true)

how to fix??

**Comment by yimao009** [comment]
➜ flutter doctor -v
[✓] Flutter (Channel stable, 2.2.2, on macOS 12.1 21C52 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 2.2.2 at /Users/guoruize/flutter
    • Framework revision d79295af24 (9 months ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at /Users/guoruize/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.2, Build version 13C90
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (3 available)
    • iPhone (mobile)        • 165c26309fb78e6d20c89c3a4a25258cec4371af • ios
      • iOS 11.0.3
    • iPhone 13 Pro (mobile) • 2E7C4374-18E3-4457-B67E-C29A5D27FC98     • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)           • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.109

• No issues found!

**Comment by yimao009** [comment]
Android Studio Bumblebee | 2021.1.1 Patch 2
Build #AI-211.7628.21.2111.8193401, built on February 17, 2022
Runtime version: 11.0.11+0-b60-7590822 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.1
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 12
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: Dart (211.7798), com.localizely.flutter-intl (1.17.1-2020.3), org.jetbrains.kotlin (211-1.6.10-release-923-AS7442.40), io.flutter (64.1.2)

**Comment by yimao009** [comment]
Chinese NB！！！！

**Comment by maheshmnj** [comment]
Hi @yimao009, Thanks for filing the issue. Please note that in your second picture you have not opened the flutter project but some other directory. you get access to flutter tools if you open flutter project  in android studio (containing pubspec.yaml) in the root.

Closing as this is not really a bug with flutter. In case you feel that this is a bug you should file the issue in [flutter intellij](https://github.com/flutter/flutter-intellij) repository.
