### ISSUE TITLE
Execution failed for task ':app:compileFlutterBuildRelease'.

### ISSUE THREAD

**Issue by amani27** [flutter/flutter#99325]
```
Script '/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1102

What went wrong: Execution failed for task ':app:compileFlutterBuildRelease'. Process 'command '/flutter/bin/flutter'' finished with non-zero exit value 1
```

But flutter pub get, flutter run is working. I've tried doing flutter clean, checked all pubspec.yaml dependencies, updated android build.gradle minimum version to satisfy dependency requirements.

Project environment: sdk: ">=2.16.1 <3.0.0" Flutter version: 2.10.2(stable channel)

Has anyone faced anything such? If so what could be some possible solutions to this issue?

**Comment by danagbemava-nc** [comment]
Hi @amani27, please provide the following. 

- the output of `flutter build apk -v`. The output is likely to be huge so kindly put it into a .txt file and attach it here
- your `pubspec.yaml`/`pubspec.lock`
- your `android/build.gradle` and `android/app/build.gradle`

Thank you

**Comment by amani27** [comment]
> Hi @amani27, please provide the following.
> 
> * the output of `flutter build apk -v`. The output is likely to be huge so kindly put it into a .txt file and attach it here
> * your `pubspec.yaml`/`pubspec.lock`
> * your `android/build.gradle` and `android/app/build.gradle`
> 
> Thank you

Output of `flutter build apk --release` - https://pastebin.pl/view/4539cc24
Output of `flutter build apk -v` - https://pastebin.pl/view/4ba383a9
`pubspec.yaml` - https://pastebin.pl/view/2ef02565
`pubspec.lock` - https://pastebin.pl/view/abfe03ef
`android/build.gradle` - https://pastebin.pl/view/4ca89581
`android/app/build.gradle` - https://pastebin.pl/view/a9bc5c8b
Though later noticed it's not just Android release build issue, iOS ipa build also fails with similar log.

**Comment by danagbemava-nc** [comment]
Hi @amani27, can you please provide your `flutter doctor -v` as well?

Thank you

**Comment by amani27** [comment]
> Hi @amani27, can you please provide your `flutter doctor -v` as well?
> 
> Thank you

https://pastebin.pl/view/f387e471

**Comment by danagbemava-nc** [comment]
Hi @amani27, do you have this issue with the default `flutter create` app as well ?

**Comment by amani27** [comment]
> Hi @amani27, do you have this issue with the default `flutter create` app as well ?

No, create is fine. Never mind I found the issue. The actual issue was with Riverpod usage. As after upgrading to riverpod 1 context.read doesn't work. earlier we could obtain context using global navigation keys. We were trying to obtain Ref from Dart class, which caused the errors. Using ProviderContainer instead solved the issue.
