### ISSUE TITLE
[Integration_test][Web]:  Proposal to add a way to disable `chrome is being controlled by automated software` which appears in top as info panel.

### ISSUE THREAD

**Issue by rajeshpatil95** [flutter/flutter#99320]
I am developing some intregration tests for my flutter-web application wherein I wanted to disable the top header info bar "chrome is being controlled by automated software"?
Tried looking into official docs (Dart, Flutter) ...but didn't find any relevant match?
![Screenshot (322)](https://user-images.githubusercontent.com/41562370/156116276-6d15fa72-763f-4ad3-b963-ec5c9a19c607.png)

**Comment by yjbanov** [comment]
If there was an automated way to remove that banner it would defeat the purpose of that banner, so I don't think we can do anything about it. This might be a good feature request for Chromium, if there's a meaningful way to remove it.
