### ISSUE TITLE
Missing a single list of every widget in catalog

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#9932]
We have a nice new catalog of widgets, but we're missing a single page of everything. We'd like to eventually have a single list of everything for those people that want to see everything all at once.

**Comment by sethladd** [comment]
cc @FaisalAbid

**Comment by FaisalAbid** [comment]
Cool, will do it tonight or tomorrow!

**Comment by sethladd** [comment]
Thanks! Please also remove the .csv file while you're in there.

**Comment by sethladd** [comment]
I think we did this. But, I don't see it on https://flutter.io/widgets/

@FaisalAbid did I miss something?

**Comment by FaisalAbid** [comment]
Yea that's weird.. the staging url from the PR has what it should be. Maybe
it's being cached somehow?

https://flutter-io-deploy-three.firebaseapp.com/widgets

**Comment by sethladd** [comment]
Found the issue. Our 404 checker failed: External link https://docs.flutter.io/flutter/material/Icon-class.html failed: 404 No error

**Comment by sethladd** [comment]
Fixed! :)
