### ISSUE TITLE
Live streaming not working in IOS but works in andriod.

### ISSUE THREAD

**Issue by inn-sharmila-varatharajan** [flutter/flutter#99335]
building an livestreaming in webview works in android , Safari ios, but same not working in IOS Flutter App. 
using RMTP Getting error Can't open connection tcp:// 

Tried using an default IP : getting below error
PlatformException(VideoError, Failed to load video: Operation Stopped, null, null)

If any suggestions let me know. what are the ways and types of stream will work in both flutter Android and ios in webview.

**Comment by maheshmnj** [comment]
Hi @inn-sharmila-varatharajan, Thanks for filing the issue. Please note that the issue tracker is  to track the bugs in the flutter framework. How-to questions are best suited for communities like StackOverflow. You might get some help if you ask the question there with enough details, code sample, and the error that you are getting.

Closing as this is neither a bug nor a feature request. In case you disagree feel free to write in the comments and we will reopen it. 

Thank you.
