### ISSUE TITLE
Unable to deploy the Flutter sample in iOS - simulator with Google signIn package.

### ISSUE THREAD

**Issue by Indumathi1195R** [flutter/flutter#99334]
I was used the google sign in package for loading the google calendar events to Flutter calendar. Now we are facing the following issue while deploying the sample.

**Steps to reproduce:**

1.	Run the sample from here 
[flutter_appcal.zip](https://github.com/flutter/flutter/files/8161638/flutter_appcal.zip)

2.	Below deployment issue occurred with this package.
3.  
![Screenshot 2022-02-23 at 5 51 11 PM](https://user-images.githubusercontent.com/54974849/156170696-1c11805d-c7ef-4a9f-aa4a-2aa3c9280550.png)

**Expected result:**
      It must show the google calendar events from the created account while deploying the sample.

**Comment by darshankawar** [comment]
@Indumathi1195R 
Can you provide `flutter doctor -v`, `flutter run -v` in a text file that shows the error ?
