### ISSUE TITLE
Application crash on  HUAWEI JNY-LX1

### ISSUE THREAD

**Issue by hussenIbrahim** [flutter/flutter#99339]
`Fatal Exception: java.lang.IndexOutOfBoundsException: getChars (6 ... 5) has end before start
       at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1326)
       at android.text.SpannableStringBuilder.getChars(SpannableStringBuilder.java:1213)
       at android.text.TextUtils.getChars(TextUtils.java:154)
       at android.text.TextUtils.substring(TextUtils.java:345)
       at android.view.inputmethod.BaseInputConnection.getTextBeforeCursor(BaseInputConnection.java:505)
       at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:264)
       at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:89)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:219)
       at android.app.ActivityThread.main(ActivityThread.java:8349)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)`

Brand:HUAWEI
Model:JNY-LX1
Version:Android 10
flutter version 2.10.1

**Comment by darshankawar** [comment]
@hussenIbrahim 
Can you provide `flutter doctor -v`, a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and steps to replicate that throws this exception ?

**Comment by hussenIbrahim** [comment]
> @hussenIbrahim Can you provide `flutter doctor -v`, a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and steps to replicate that throws this exception ?

` Flutter (Channel stable, 2.10.2, on Microsoft Windows [Version 10.0.22000.493], locale en-GB)
    • Flutter version 2.10.2 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (12 days ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
    • Android SDK at C:\Users\Hussen\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.0.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31321.278
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.64.2)
    • VS Code at C:\Users\Hussen\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.34.0

[√] Connected device (4 available)
    • SM M115F (mobile) • R9JN40LXMSJ • android-arm    • Android 11 (API 30)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.22000.493]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 98.0.4758.102
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 98.0.1108.62`

**Comment by darshankawar** [comment]
> a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and steps to replicate that throws this exception ?

@hussenIbrahim Please provide this too.

**Comment by hussenIbrahim** [comment]
sorry for late reply
this exception comes from firebase Crashlytics.
i have no idea how and where this exception is occurs

**Comment by darshankawar** [comment]
@hussenIbrahim 
From the crash log you shared, it seems to be related or similar to this old issue : https://github.com/flutter/flutter/issues/33642. Can you try the reproduction steps and code mentioned in it and see if you are able to replicate it locally on same huawei device ?

**Comment by hussenIbrahim** [comment]
i tried on another Huawei device , but I couldn't reproduce this crash.

**Comment by darshankawar** [comment]
Without a proper replication code and steps, we won't be able to make this issue actionable. If you see a pattern or exact steps to replicate, provide the same so that we can address it properly.
