### ISSUE TITLE
Way to Handle / differentiate between  mouse/touch area dynamically

### ISSUE THREAD

**Issue by Dvergar** [flutter/flutter#99345]
### What we want :

Being able to dynamically adapt the tap/mouse area depending on pointer kind.

Issue being that whenever we get `PointerDeviceKind` - inside a `onX` callback - the widget tree is already built.

We want to handle cases where people could alternate between mouse and touch events (ie. touchscreen laptops).
_We could cache the pointer kind but we'll always have a one-frame delay._

### Our workaround :

Checking `userAgent` and `userAgentData` to identity touch-devices.

What would be a proper flutter way to handle this ?

**Expected results:** 
Set an interaction area of size x depending on `PointerDeviceKind` (mouse or touch).

**Actual results:** 
We can only handle one of the two cases but not both dynamically.

https://dartpad.dartlang.org/?id=8694ee176cbffeecbd0a214df56c1840
<details>

<summary>Code sample</summary>

```dart
// Objective : Handling handles for both mouse & touch events
// What we want is two scenarios :
// - Clicking..
//      - on the handle should trigger an event
//      - on the purple image should return "purple"
//      - on the tapzone shouldn't absorb the event
//          - returns "purple" or nothing if hovering image or not
// - Tapping..
//      - on the tapzone/handle should trigger an event
//      - on the purple image should return "purple"

//// OUR IMPLEMENTATION
Canvas(
title: "Branch implementation",
children: [
    // HANDLE
    Positioned.fromRect(
        rect: _handleRect, // 16px
        child: const DecoratedBox(
        decoration: BoxDecoration(color: Colors.blue),
        )),

    // FILTER AREA
    Positioned.fromRect(
    rect: _tapRect, // 48px
    child: GestureDetector(
        onTapDown: (details) {
        // IF TOUCH WE HANDLE THE EVENT
        if (details.kind == PointerDeviceKind.touch) {
            print("orange");
            // IF MOUSE
        } else if (details.kind == PointerDeviceKind.mouse) {
            var localHandleRect = Rect.fromCenter(
                center: const Offset(_tapSize / 2, _tapSize / 2),
                width: _handleSize,
                height: _handleSize);
            // WE HANDLE EVENT ONLY IF IT SATISFIES HITTEST
            if (localHandleRect.contains(details.localPosition)) {
            print("green");
            }
        }
        },
        child: DecoratedBox(
            decoration: BoxDecoration(
                color: Colors.orange.withOpacity(0.5))),
    ),
    ),
],
),
```

</details>

<details>
  <summary>Logs</summary>

```
No issues found! (ran in 1.3s)
```

```
[√] VS Code (version 1.64.2)
    • VS Code at C:\Users\_____\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.34.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 98.0.4758.102
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 98.0.1108.56

! Doctor found issues in 2 categories.
```

</details>

**Comment by goderbauer** [comment]
This sounds like a question that's better suited for one of our community channels on https://flutter.dev/community (e.g. StackOverflow).

/cc @Piinks who may have some advice here.

**Comment by Piinks** [comment]
There are probably a number of ways to do this, but off the top of my head I can think of 2:

- GestureRecognizer (and its subclasses) can filter for different input types, so you could have one gesture recognizer for one inout type, and one gesture recognizer for another input type

- Check out how we handle scrollbar gestures. It is possible to have a gesture detector make different decisions based on the input type, for example, we add invisible padding to the scrollbar thumb when someone is using touch inout, making it easier to grab onto it. A mouse is more precise, so we do not apply that extra padding in that case.
 https://github.com/flutter/flutter/blob/4919b749680ebe29cab5ec8ce7de6ff8a33dd70d/packages/flutter/lib/src/widgets/scrollbar.dart#L2040
