### ISSUE TITLE
CP request: #96486 into stable

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#99349]
## Description

Due to #92598, `LayerLink.leader` was removed / made private. This, however, proved to be used in a number of packages.

> [...] proved to be pretty popular (see https://github.com/flutter/flutter/pull/96451).

## Cherrypick request

Therefore, I would like to request #96486 to be cherry-picked into stable as it:

> Reintroduces LayerLink.leader, that was removed in https://github.com/flutter/flutter/pull/92598

### Impact

This would e.g. allow making a new and improved version of `flutter_portal` (see https://github.com/rrousselGit/flutter_portal/pull/44) compile again. This worked previously but was broken by #92598 landing on stable (due to missing tests in `flutter/tests`).

**Comment by christopherfujino** [comment]
added the label for consideration by the release team

**Comment by goderbauer** [comment]
> (due to missing tests in flutter/tests).

Have these tests been added now to avoid this in the future?

**Comment by creativecreatorormaybenot** [comment]
@goderbauer that's a good point - I created https://github.com/flutter/tests/pull/126.

**Comment by fzyzcjy** [comment]
Hi, how is it going on?

**Comment by creativecreatorormaybenot** [comment]
Hi @goderbauer - I am curious towards the status on this request.

From what I can tell, P6 basically means that an issue will not be tackled by the team. Also, cherrypick requests inherently require to be dealt with short term.

Combining these two points makes me come to the conclusion that P6 does not have an effect here / it should rather be the CP denied label.

In that case, does cherry-picking this have any unintended side effects? The problem here is that the only way we can make our code work again is copy the whole framework code related to `LayerLink`s and make the one change to make the member public. It would really help a lot to have this picked into `stable` to not have to wait 3 months.

**Comment by HansMuller** [comment]
@creativecreatorormaybenot - cherry-picking https://github.com/flutter/flutter/pull/96486 was a good suggestion. Unfortunately we're going to have a turn this one down because, this far into the 2.10 stable release, we're not accepting hot fixes for issues that don't have broad impact and are not hyper-critical. The fix will land in the next beta and stable releases of course.

**Comment by creativecreatorormaybenot** [comment]
I wonder if I was late here or the response. Regardless of that and considering that it is too late now, I am going to close this issue.
