### ISSUE TITLE
ffi debug and release

### ISSUE THREAD

**Issue by butterflyXX** [flutter/flutter#99373]
ffi is ok in debug ,but it`s not work in release:
flutter: Invalid argument(s): Failed to lookup symbol 'add_test': dlsym(RTLD_DEFAULT, add_test): symbol not found

**Comment by dcharkes** [comment]
It should work. Can you provide steps to reproduce? Did you use `flutter create --template plugin_ffi`?

**Comment by darshankawar** [comment]
@butterflyXX 
Please provide `flutter doctor -v`, [minimal code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with steps to replicate as requested above.

**Comment by butterflyXX** [comment]
> 

I add the files to /iOS/Runner/Classes , on iOS,debug is ok, bug release failed

flutter: Invalid argument(s): Failed to lookup symbol 'add_test': dlsym(RTLD_DEFAULT, add_test): symbol not found
![image](https://user-images.githubusercontent.com/24794442/156722465-5b3a68ec-ace3-4ea2-a581-8ca7f34ef44c.png)

**Comment by butterflyXX** [comment]
@dcharkes

**Comment by butterflyXX** [comment]
I think Xcode need to set something in release

**Comment by dcharkes** [comment]
@butterflyXX did you use the `flutter create --template plugin_ffi`?

`sum` from the template should work:

* https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/plugin_ffi/src.tmpl/projectName.c.tmpl
* https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/plugin_ffi/ios.tmpl/Classes/projectName.c.tmpl

Please try to run with this template and see if `sum` has the same problem as `add_test`.
