### ISSUE TITLE
Linux ci_yaml flutter roller failed on git push

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#99370]
Tree closed
https://ci.chromium.org/p/flutter/builders/prod/Linux%20ci_yaml%20flutter%20roller/1753

`git push` failed.

**Comment by jmagman** [comment]
@CaseyHillers on call

**Comment by mdebbar** [comment]
@CaseyHillers Jenn and I approved the PR but it's failing `Mac web_tool_tests`. I re-ran it 🤞 

Any idea why the original PR didn't close the tree immediately? Is it because it wasn't picked up by cocoon until later?

**Comment by mdebbar** [comment]
Tree is green now!

**Comment by CaseyHillers** [comment]
Infra is migrating builds from the LUCI scheduler to the Cocoon scheduler (context in go/cocoon-scheduler).

The issue happened to be that the retry logic doesn't work with the Cocoon scheduler. Cocoon successfully retries the builds (409 indicated retries were successful), however, it failed to add the PubSub topic for updating it.

 I have https://github.com/flutter/cocoon/pull/1610 to implement it. I'll hold off the schedule migrations until that PR lands.

**Comment by CaseyHillers** [comment]
Closing as this seemed to be a race condition (and cocoon auto-retries would have reopened the tree).

Core work is being tracked in https://github.com/flutter/cocoon/pull/1610
