### ISSUE TITLE
flutter web html render mode. Textformfield inputs digit "1" cause cursor error position

### ISSUE THREAD

**Issue by wangsujin2015** [flutter/flutter#99394]
flutter web html render mode. Textformfield inputs digit "1" cause cursor error position
![37DD4671-1F9D-4F69-A68A-5A98FE97D24E](https://user-images.githubusercontent.com/13251360/156371181-a127bb7d-0fb1-4430-89be-15a52c927051.gif)

**Comment by danagbemava-nc** [comment]
Hi @wangsujin2015,

Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Thank you
