### ISSUE TITLE
flutter run is failing in MAC M1 chipset

### ISSUE THREAD

**Issue by kristijorgji** [flutter/flutter#99396]
Hi all I migrated from old mac with intel cpu to new one with M1 and since then facing hell cannot develop at all.
My flutter and machine specs:

```
Flutter 2.2.2 • channel unknown • unknown source
Framework • revision d79295af24 (9 months ago) • 2021-06-11 08:56:01 -0700
Engine • revision 91c9fc8fe0
Tools • Dart 2.13.3
```

```
 arch
arm64

```
<img width="265" alt="Screenshot 2022-03-02 at 14 44 59" src="https://user-images.githubusercontent.com/15630854/156373359-66bd2c20-c8ab-47bf-9f4c-4bc1bf0b6669.png">

I tried `flutter clean` deleting podspec, and actually pod install works fine but then flutter run fails with error as below:

```
Error output from Xcode build:
↳
    objc[38132]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libamsupport.dylib (0x1ea20f130) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1061d42c8). One of the two will be used. Which one is undefined.
    objc[38132]: Class AMSupportURLSession is implemented in both /usr/lib/libamsupport.dylib (0x1ea20f180) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1061d4318). One of the two will be used. Which one is undefined.
    --- xcodebuild: WARNING: Using the first of multiple matching destinations:
```

**Comment by danagbemava-nc** [comment]
Hi @kristijorgji, it looks like you're on an older version of flutter. Can you upgrade to the latest version of `stable`(2.10.2) and see if you still experience this issue? 

If you do, please provide the full logs of `flutter run -v` as well as the updated `flutter doctor -v`. The output of `flutter run -v` is likely to be huge so kindly put it into a .txt file and attach it here. 

FWIW:    
```
objc[38132]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libamsupport.dylib (0x1ea20f130) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1061d42c8). One of the two will be used. Which one is undefined.
```
is just a message from xcode and is unlikely to be the cause of your issue.

**Comment by yassinsameh** [comment]
Facing the same issue On Flutter 2.10.2 Stable channel on a previously working project.

**Comment by danagbemava-nc** [comment]
@yassinsameh, kindly file a new issue and provide the following

- `pubspec.yaml`/`pubspec.lock`
- `Podfile`/`Podfile.lock`
- `project.pbxproj`
- The full logs of `flutter run -v` (output may be huge so put it into a.txt file and attach it)
- And your `flutter doctor -v`
