### ISSUE TITLE
safari brower on Iphone, can not hide softkeybord when tapping "done" key

### ISSUE THREAD

**Issue by wangsujin2015** [flutter/flutter#99395]
safari brower on Iphone, can not hide softkeybord when tapping "done" key

**Comment by danagbemava-nc** [comment]
Hi @wangsujin2015,

Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Thank you
