### ISSUE TITLE
Migrate `ListTile` disabled icon color to Material 3

### ISSUE THREAD

**Issue by TheCarpetMerchant** [flutter/flutter#99400]
## Use case
Trailing IconButtons in ListTiles.

## Proposal
`ListTileThemeData` doesn't inherit its `iconColor` from `iconTheme`. Took me a few minutes to figure out. It would make sense that if no `iconColor` is provided to `ThemeData.listTileTheme`, the `iconColor` should default to the one in `iconTheme` instead of the default Materiel grey color.

Would you consider changing this behaviour ?

Short reproduction code :
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        iconTheme: IconThemeData(color: Colors.red),
      ),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Column(
          children: const [
            ListTile(
              leading: Icon(Icons.add_rounded),
            ),
            Icon(Icons.add_rounded),
          ]
        ),
      ),
    );
  }
}
```

**Comment by maheshmnj** [comment]
Hi @TheCarpetMerchant, Thanks for filing the issue. Widgets within the ListTile use ListTileTheme as mentioned in the docs

> To override the appearance of specific components, provide a component theme parameter like [sliderTheme], [toggleButtonsTheme], or [bottomNavigationBarTheme].

So you will need to add listTileTheme in ThemeData

```dart
theme: ThemeData(
        iconTheme: const IconThemeData(color: Colors.red),
        listTileTheme: ListTileThemeData(iconColor: Colors.red),
      ),
```

**Comment by TheCarpetMerchant** [comment]
Yes, I disagree. It works as intended of course, but I think that if no `ListTileThemeData.iconColor` is provided, Flutter should default to `IconThemeData.color` instead of a set value.

**Comment by maheshmnj** [comment]
Reopening based on the above response

**Comment by maheshmnj** [comment]
> if no ListTileThemeData.iconColor is provided, Flutter should default to IconThemeData.color

Thanks for the update @TheCarpetMerchant, that looks like a valid proposal to me.

Presently when we add an icon theme to MaterialApp
```dart
MaterialApp(
      theme: ThemeData(
        iconTheme: IconThemeData(color: Colors.red),
      ),
```

This does not apply to all the icons in the app, for instance, if we have Icons in ListTile or AppBar the `iconsTheme` does not get applied to these icons and the only way to change the theme of these icons is to specify their parent's theme via `AppBarTheme` and `ListTileTheme`.

This is a proposal to use iconsTheme as the default theme for the icons used in the entire widget tree.

**Comment by mtc-jed** [comment]
In addition to this : `ListTileThemeData` doesn't have a `splashColor` property, which would be appropriate.

**Comment by TahaTesser** [comment]
`ListTile` doesn't inherit icon color only in when Brightness is light.
This is intended, for backward compatibility.

https://github.com/flutter/flutter/blob/c394ba83ace5fbaced93ebdbaaf35a8b44fa891c/packages/flutter/lib/src/material/list_tile.dart#L1104-L1111

if `_iconColor` doesn't return color (which it doesn't in dark theme), iconTheme's icon color is inherited 

This was added in https://github.com/flutter/flutter/pull/77004

cc: @HansMuller

**Comment by mtc-jed** [comment]
Ah, this makes sense. An option to override this behaviour in `ListTileThemeData` would be nice in case this particular backwards compatibility needs to be kept.

**Comment by HansMuller** [comment]
@TahaTesser, @darrenaustin - undoing the backwards compatibility hack noted in https://github.com/flutter/flutter/issues/99400#issuecomment-1074899259 might be acceptable for `useMaterial: true` apps. The transition to M3 will introduce many small color changes; seems OK to include this one too.
