### ISSUE TITLE
Process Java is not automatically terminated after flutter build apk finishes and work is completed 

### ISSUE THREAD

**Issue by Pr47h4m** [flutter/flutter#99415]
Hello 
I'm unable to figure out if its general behaviour please take a look at details and screenshot

## Steps to Reproduce

After terminating / quitting flutter apk from debug (or after building flutter apk) Process java is not getting terminated automatically and it is using 1.5-2GB of RAM 

I have seen this issue in my Linux (ubuntu) PC too and it has 8GB ram so i have to always run `pkill java` after `flutter build apk` finishes

**Expected results:** 

**Actual results:** 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/56750378/156401176-4decfdf4-7073-4939-87e3-e9f0fea05e24.png">

<details>
  <summary>Logs</summary>

```
flutter doctor -v
```

[✓] Flutter (Channel stable, 2.10.2, on macOS 12.2.1 21D62 darwin-arm, locale en-IN)
    • Flutter version 2.10.2 at /Users/pr47h4m/SDKs/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (12 days ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/pr47h4m/SDKs/android
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (1 available)
    • vivo 1820 (mobile) • M7O789USNVS8ORKF • android-arm64 • Android 8.1.0 (API 27)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

</details>

**Comment by darshankawar** [comment]
@Pr47h4m 
This may not be specific to Flutter. Please check [this](https://stackoverflow.com/a/32300657) link / solution as to why the process keeps running. Hope it helps to answer your question.
Closing from here.
