### ISSUE TITLE
Linux Fuchsia SDK roll failing on a (infra?) test failure

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#99428]
Starting with the roll here https://github.com/flutter/engine/pull/31758

Linux Fuchsia FEMU tests are failing https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Fuchsia%20FEMU/12452/overview

I'm not sure if this is an infra issue or a test failure.

@chaselatta @arbreng

**Comment by akbiggs** [comment]
Spoke with Fuchsia infra team members - we need to update the path here, it's pointing at an out-of-date CIPD location and not pulling in changes to aemu as a result. https://flutter.googlesource.com/recipes/+/refs/heads/main/recipe_modules/vdl/api.py#56

**Comment by zanderso** [comment]
It looks like the roll is now successful. Thanks!
