### ISSUE TITLE
[IOS Flavors] Xcode Archive app fails with Module 'XXX' not found

### ISSUE THREAD

**Issue by milanobrenovic** [flutter/flutter#99438]
## Steps to Reproduce

1. Add 3 different flutter flavors (dev, stg, prod)
2. Try to Archive the app for iOS via Xcode, Product -> Archive OR Product -> Build

**Expected results:** 
Successfully archive and deploy the app to App Store.

**Actual results:** 
`Module 'XXX' not found`

Basically I believe I am having the same issue as here: https://github.com/flutter/flutter/issues/60843

Except I have tried what people suggested there and it didn't work. So im opening this thread again. It seems that flutter cant recognize the production build so it can't deploy it to the App Store. Everything works fine and the app can be ran normally via flutter for both iOS and Android. Even `--release` works fine. But deploying Only to iOS App Store gives this error.

The error `Module 'contacts_service' not found`, or `Module 'firebase_core' not found` happens for all packages. It just doesnt recognize it. I tried removing flutter flavors, leaving only the production flavor, and then it worked fine, the build and archive were successful, so this is definitely a problem with flutter flavors.

How do I resolve this while keeping my 3 flavors?

**Comment by maheshmnj** [comment]
Hi @milanobrenovic, Thanks for filing the issue. Please ensure that when opening your app in xcode you are opening `Runner.xcworkspace` and not `Runner.xcodeproj` https://docs.flutter.dev/deployment/ios#create-a-build-archive.
Also, does the app build and run when running from xcode?

Please share your output of `flutter doctor -v`.

**Comment by milanobrenovic** [comment]
> Hi @milanobrenovic, Thanks for filing the issue. Please ensure that when opening your app in xcode you are opening `Runner.xcworkspace` and not `Runner.xcodeproj` https://docs.flutter.dev/deployment/ios#create-a-build-archive. Also, does the app build and run when running from xcode?
> 
> Please share your output of `flutter doctor -v`.

Hi, Yes I can confirm that I am opening `Runner.xcworkspace` 100%.

The app does not build nor run when running from xcode.

In the same project, I have already tried removing flavors and leaving only the production flavor. Then the build succeeded as well as archive, and the app even got deployed on the app store. Now when i reverted back to flavors i get that error.

Here is the log of `flutter doctor -v`

```
[✓] Flutter (Channel stable, 2.10.2, on macOS 12.2.1 21D62 darwin-x64, locale en-RS)
    • Flutter version 2.10.2 at /Users/user/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (12 days ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.4746.57

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (3 available)
    • Blacksky (mobile)          • 00008101-001228442608001E            • ios            • iOS 15.3.1 19D52
    • iPhone 13 Pro Max (mobile) • ABFB26F0-3D3B-469B-8C8A-C4BF22F0DA44 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 98.0.4758.109
    ! Error: Blacksky is busy: Preparing the watch for development via Blacksky. Xcode will continue when Blacksky is finished. (code -10)

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

**Comment by maheshmnj** [comment]
Thanks for the update could you please share a minimal sample project for us to have a look?

**Comment by milanobrenovic** [comment]
> Thanks for the update could you please share a minimal sample project for us to have a look?

I don't have the sample project specifically for flavors, however you can make one from scratch following this less than 10 minute tutorial: https://www.youtube.com/watch?v=Vhm1Cv2uPko

That is the tutorial that I followed. The flavors work, compiling and building on Android and iOS from flutter works, debug and release mode work, publishing to Android Play Store works, the only thing that doesn't work is building from xcode and archiving iOS to App Store.

**Comment by maheshmnj** [comment]
Thanks for the update @milanobrenovic, It looks to me that this issue is due to the third party dependency (contacts_service) as can be seen from your screenshot. I tried this [flavors_example app](https://github.com/flutter/flutter/files/8196224/flavors_example.zip)  and I was able to build the archive successfully.


<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.10.3 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (20 hours ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • 192.168.1.5:5555 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos            • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 99.0.4844.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by yy1300326388** [comment]
https://github.com/flutter/flutter/issues/43986
