### ISSUE TITLE
Flutter ci yaml roller stops rolling

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#99439]
I landed https://github.com/flutter/flutter/pull/99353 hours ago, and is expecting the changes populated by now. But they are not.

Then checked the ci yaml roller, and seems it stoped rolling after: https://github.com/flutter/flutter/pull/99375
![Screen Shot 2022-03-02 at 3 16 46 PM](https://user-images.githubusercontent.com/54558023/156466088-907fc7e4-908d-40f7-bf31-4bb452a787cd.png)

/cc @CaseyHillers

**Comment by CaseyHillers** [comment]
I'll send a manual roll now to kick it again

**Comment by CaseyHillers** [comment]
Fix in https://flutter-review.googlesource.com/c/infra/+/27601

**Comment by CaseyHillers** [comment]
Closing as remaining work is being tracked in https://github.com/flutter/flutter/issues/99370
