### ISSUE TITLE
Issue from website page 发布Android版APP

### ISSUE THREAD

**Issue by hvhz186** [flutter/flutter#99447]
From URL: https://www.flutterchina.club/android-release-build.md
请问一下，提交到google play的时候要求提供用户名和密码输入框的id，但是flutter的view好像没有id这个属性，这个要怎么解决？

**Comment by danagbemava-nc** [comment]
Hi @hvhz186, the flutter china website is community-maintained. 
Kindly report this to them over https://github.com/flutterchina/website/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc. 

Closing as the website is not maintained by the flutter team. 

Thank you
