### ISSUE TITLE
[google sign in]  idtoken is returned null

### ISSUE THREAD

**Issue by napierya** [flutter/flutter#99451]
![image](https://user-images.githubusercontent.com/38169718/156492886-e1fd9eef-10a7-494f-914c-32fd6c809620.png)![image](https://user-images.githubusercontent.com/38169718/156492886-e1fd9eef-10a7-494f-914c-32fd6c809620.png)
![image](https://user-images.githubusercontent.com/38169718/156492939-ea7121bf-033d-47a5-8627-fdfd7a9b2fc0.png)
![image](https://user-images.githubusercontent.com/38169718/156492959-a28d8724-f11d-4c56-8499-f1391edae1c9.png)
I use google for login can't get idtoken only accesstoken is getting. I can't find the reason for this

**Comment by maheshmnj** [comment]
Hi @napierya, Thanks for filing the issue. What platform are you compiling for? please ensure you have correctly configured the plugin and followed all the steps for the target platform as per the docs https://pub.dev/packages/google_sign_in
