### ISSUE TITLE
[Windows] Upgrading to 2.10 app crashed with Chinese input method, hold down CapsLock and other keys and type frequently

### ISSUE THREAD

**Issue by wc2411888** [flutter/flutter#99465]
When I use the Chinese input method, hold down CapsLock and other keys and type frequently, the program will cras
h，![1](https://user-images.githubusercontent.com/11803121/156520204-26c92009-4626-42f4-8775-2346033f8490.jpg)

**Comment by wc2411888** [comment]
<img width="744" alt="企业微信截图_16462954366716" src="https://user-images.githubusercontent.com/11803121/156525080-f6427798-f3b2-432f-9582-f7e515ca16cf.png">

**Comment by maheshmnj** [comment]
Hi @wc2411888, Thanks for filing the issue. Is this regarding a windows app crash?   Please share errors/logs when the app crashes. To investigate this issue further you need to provide us with a reproducible code sample and the exact steps to reproduce the issue.

PS: Please avoid sharing screenshots of logs and code snippets, instead share them in a textual form.

**Comment by wc2411888** [comment]
More detailed crash informatio
<img width="959" alt="企业微信截图_16463778253354" src="https://user-images.githubusercontent.com/11803121/156716879-ad7bff4b-2278-434f-80e0-ca7495a64393.png">
<img width="960" alt="企业微信截图_1646377705541" src="https://user-images.githubusercontent.com/11803121/156716890-5205e84a-6c75-4182-b652-20aa635328b3.png">
<img width="960" alt="企业微信截图_16463775935329" src="https://user-images.githubusercontent.com/11803121/156716892-ee15c5a6-c093-4537-ba6b-d92319c93b28.png">
n

**Comment by maheshmnj** [comment]
@wc2411888 Please share textual logs of crash reorts and avoid sharing image snippets and screenshots. It would be great if you can break down the reproducible steps indicating which keys crashes the app. I tried holding capslock (on) key and pressed random keys with chinese input, But I don't see app crashing


https://user-images.githubusercontent.com/31410839/156749468-7639c432-9624-4181-b31d-00c531f6a128.mp4

<details>
<summary>flutter doctor -v (windows)</summary>

```
[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.19044.1526], locale en-US)
    • Flutter version 2.10.3 at C:\flutter_sdk\stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (14 hours ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\mahesh\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.64.2)
    • VS Code at C:\Users\mahesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.36.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1526]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 98.0.4758.102
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 98.0.1108.56

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>
