### ISSUE TITLE
iOS Archive -> Lexical or Preprocessor Issue Group  'FlutterPluginRegistrant/GeneratedPluginRegistrant.h' file not found

### ISSUE THREAD

**Issue by NkGins** [flutter/flutter#99474]
## Steps to Reproduce

The flutter run and flutter build iOS is correct 

<img width="471" alt="image" src="https://user-images.githubusercontent.com/43539205/156541732-593aaf93-b3f9-444b-b720-aaf9573109e9.png">

but when I archive ,the error has occurred

<img width="1075" alt="image" src="https://user-images.githubusercontent.com/43539205/156541202-14c6da5f-514a-4ae1-b78f-94883a5d3f3e.png">

## Logs

<details>
<summary>Logs</summary>

```
```

<img width="571" alt="image" src="https://user-images.githubusercontent.com/43539205/156542789-86af17a3-56b2-4743-89fd-0f3694956b8a.png">

```

</details>

**Comment by maheshmnj** [comment]
Hi @NkGins, Thanks for filing the issue. Is this issue with a newly created flutter app too? 
Please ensure that you are opening `ios/Runner.xcworkspace` also You seem to be on older version of flutter and Unfortunately we cannot provide support to old versions. I would recommend you to please update flutter to latest stable by running `flutter upgrade`.
