### ISSUE TITLE
[Pigeon] Pigeon <-> Flutter communication with HostApi

### ISSUE THREAD

**Issue by kndl22** [flutter/flutter#99481]
I have the following Pigeon structure

```
import 'package:pigeon/pigeon.dart';

class MyData {
  MyData(this.var1, this.var2);

  final String var1;
  final String var2;
} 

@HostApi()
abstract class MyApi {
  MyData  getMyData();
}
```
I wonder how this structure could be applied into Flutter application as-well. Does Pigeon support Plugin -> Flutter App type-safe communication like it does with native applications?

**Comment by darshankawar** [comment]
@kndl22 
Please check if [this](https://github.com/flutter/flutter/issues/60758) proposal is same as your case.

**Comment by kndl22** [comment]
hi @darshankawar,
The mentioned proposal seems to be unrelated in my case.

I'll try to be more specific:
Is it possible to have the plugin to communicate with a Flutter applications (that depends on this plugin) using Pigeon?

Following the structure I mentioned, here's how I call the host api:
```
hostApi.getMyData(
    MyData(
        var1: '123',
        var2: '456',
    ),
);
```

I try to implement Pigeon at my example flutter application that uses the plugin, and I wonder how to achieve this

**Comment by darshankawar** [comment]
Thanks for the update, will leave it open and label for insights from the team.

/cc @gaaclarke

**Comment by gaaclarke** [comment]
I think what you are looking for is `@FlutterApi()`.  That is for communicating from the host side to the flutter side.  Every looks the same in Pigeon, you just use `@FlutterApi()` instead of `@HostApi()`.

**Comment by kndl22** [comment]
Thanks @gaaclarke! I'm writing a Flutter package which will be implemented by a Flutter module and then will the exported to Android and iOS (by add-to-app practice). So far Pigeon works perfectly with this practice.

My question is how (or if) a Flutter project can communicate with Flutter plugin using Pigeon?

**Comment by stuartmorgan** [comment]
@kndl22 Please give a specific, detailed example of what you are trying to do, including example code for how you would do what you are describing without Pigeon.

"Fluter project" and "flutter plugin" are very vague terms in the context of Pigeon, given that its purpose is communication between specific different parts of those things, so it's very hard to understand what your question is.

**Comment by kndl22** [comment]
@stuartmorgan I'm developing a mobile SDK that'll be delivered to iOS, Android & Flutter applications. 
To achieve that i followed Flutter's add-to-app practice -> building a Flutter module, export AAR & xcframework artifacts and implement on the native side.

I used pigeon for type-safe communication with the native hosts and so far everything works well.

Now, I have a customer who works with Flutter and I want to able to deliver my SDK. Currently I supports Android & iOS applications and I wonder how I can deliver the same SDK to a Flutter user. 

I wrapped my Flutter module with Flutter plugin and moved all the UI to the plugin, so basically the module depends on the plugin and I'm using it as a "bridge" for exporting the necessary artifacts for the native applications.

My Flutter customer is accessing the plugin via private repository, but the issue is that when I'm using Pigeon's HostApi functions at my SDK, there're no generated files for Flutter that I can deliver like I do for Android & iOS applications.

I might be wrong with my assumptions here but my question is what would be considered as best-practice for me, as a SDK developer, to support Flutter projects while using Pigeon.

**Comment by stuartmorgan** [comment]
I'm still not clear on what you are describing. You keep using the word "Flutter" in vague ways that make it hard to understand what you mean by it (e.g., you say that there are "no generated files for Flutter"; all files generated by Pigeon are by definition for Flutter). You've also described the relationship between your module and your plugin in contradictory ways within the same sentence. At this point I'm not even clear what languages the two endpoints you are dealing with are. (I suspect that some of the time when you say "Flutter" you actually mean "Dart", but I'm not sure.)

Again, please provide *example code* (not high-level descriptions) of how you would accomplish your goal without Pigeon, using method channels directly, so that we can understand what the Pigeon equivalent would be.
