### ISSUE TITLE
Flutter Chewie Player opening fullscreen but the video is taking only quarter of space

### ISSUE THREAD

**Issue by Sowmo0509** [flutter/flutter#99492]
Hey there, I am working on a project where I have to implement fullscreen player in Flutter using **Chewie**, I have enabled `allowFullScreen: true, fullScreenByDefault: true, showControls: true,` the controls taking all the size of my screen but the video is somewhat quarter in size at the topRight position. I don't understand what's wrong.

**Comment by stuartmorgan** [comment]
Please file issues with third-party packages with the developers of the package. `chewie` is not developed by the Flutter team.
