### ISSUE TITLE
Deprecate SingletonFlutterWindow

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#99500]
The ultimate goal is to remove `SingletonFlutterWindow` from the code base and replace it with just a regular `FlutterWindow` to prepare apps/packages for a multi-window world and migrate existing apps to use the `PlatformDispatcher` API directly. Single-windowed apps (just like multi-windowed apps) would interact with a plain `FlutterWindow` and the `PlatformDispatcher` instead of a `SingletonFlutterWindow`, which combines both APIs in one.

The existence of the `SingletonFlutterWindow` is confusing because it allows a developer to access window-agnostic functionality via the `window` property and may lead to the incorrect assumption that there is only one window.

Suggestions:
* Put a deprecation notice on all methods of `SingletonFlutterWindow` that forward to the `platformDispatcher` informing people that they should use the `PlatformDispatcher` directly, e.g. via `WidgetsBinding.instance.platformDispatcher` or `PlatformDispatcher.instance` or `FlutterView.platformDispatcher`.
* Put a deprecation notice on `SingletonFlutterWindow` and advise people to use `FlutterView` instead. Since `SingletonFlutterWindow` can't be instantiated, this will only prevent developers from using the type in code (see example below) and it will teach people that window-agnostic API's shouldn't be accessed from the `window` property.
```dart
// Deprecation notice on the next line that `SingletonFlutterWindow` should be replaced
// with `PlatformDispatcher` (if the functionality is window-agnostic) or `FlutterView` (if window-based).
// In the latter case, `FlutterView.platformDispatcher` can be used for API from `SingletonFlutterWindow`
// that's not directly available on `FlutterView`.
void fooMethod(SingletonFlutterWindow window) {
  // ...
}
```

**Comment by gspencergoog** [comment]
Yes, it was a band-aid to keep from breaking changes until we had real multi-window support.  Ideally, we eventually deprecate and remove the `window` singleton, and `SingletonFlutterWindow` along with it.

**Comment by goderbauer** [comment]
This is done now: https://github.com/flutter/flutter/issues/116929
