### ISSUE TITLE
Flutter app not opening on Xcode(macOS) although working in Windows for android 

### ISSUE THREAD

**Issue by kavyabhargava** [flutter/flutter#99506]
My flutter app is not working for macOS development , at first it was showing that Xcode 12.4 does not support the current flutter version so i reduced the version and all the packages version to required but now its still not running, now it does not gives any error but automatically loses connection to device before built gets completed.

The default flutter app runs perfectly.

Flutter doctor :

[✓] Flutter (Channel unknown, 2.0.0, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-IN)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed
      instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] Connected device (2 available)

I can not use upgraded flutter version as my mac does not support the Xcode 12.5+

**Comment by maheshmnj** [comment]
Hi @kavyabhargava, Thanks for filing the issue. You seem to be using an old version of flutter. Unfortunately, we do not provide support to old versions. I would suggest you to please upgrade to latest `stable 2.10.3` and see if that fixes the issue. If the issue persists after the upgrade please share the updated output of `flutter doctor -v` and the complete logs of `flutter run -v` in a text file.

Additionally, if you cannot upgrade then you may try to find the cause of the issue by looking at the logs by running 
`flutter run -v`

**Comment by kavyabhargava** [comment]
Flutter run -v gave a really huge result should I paste it here??
