### ISSUE TITLE
How to make the fields in `TimelineSummary` being collected by skia

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#99516]
I added some new fields in `TimelineSummary` in this PR: https://github.com/flutter/flutter/pull/95699
Including: '30hz_frame_percentage',  '60hz_frame_percentage', '90hz_frame_percentage',  '120hz_frame_percentage', 'illegal_refresh_rate_frame_count'. 

These fields are not shown in the skia perf tool: https://flutter-flutter-perf.skia.org/e/

I have run the local tests and confirmed that the timeline summary file was generated and it contains the new key-values.

Is there anything that I'm missing for these new fields to be collected by Skia?

CC @keyonghan 

@dnfield @flar I heard you two might know how to do it :) 

This is blocking https://github.com/flutter/flutter/issues/95700

**Comment by dnfield** [comment]
I haven't lookeda t it in a while, but I think your PR should have done this if the values were getting reported. You should try grabbing a timeline summary from a LUCI run of your benchmark and make sure the values are there as expected.

**Comment by cyanglaz** [comment]
> I haven't lookeda t it in a while, but I think your PR should have done this if the values were getting reported. You should try grabbing a timeline summary from a LUCI run of your benchmark and make sure the values are there as expected.

Thank you for the response! Where do I find the "timeline summary from a LUCI run of your benchmark"? There is no particular benchmark that I added, everything I added is in the PR. I was hoping some magic happens and these fields are included in the exciting benchmarks.

**Comment by flar** [comment]
It looks like they are being tracked:

https://flutter-flutter-perf.skia.org/e/?queries=sub_result%3D120hz_frame_percentage

**Comment by flar** [comment]
The next step would get them listed on our alerts page so that a gardner gets notified when their results trend. @zanderso

**Comment by zanderso** [comment]
We really need to re-organize the alerts, but in the meantime, I'd suggest adding these to `Time-based alerts` at https://flutter-flutter-perf.skia.org/a/

**Comment by cyanglaz** [comment]
> illegal_refresh_rate_frame_count

Added the new fields to `Time-based alerts`.
