### ISSUE TITLE
[in_app_purchase][ios] InAppPurchase.instance.restorePurchases() does not bring purchased but not consumed products in ios [consumables]

### ISSUE THREAD

**Issue by utkudenis** [flutter/flutter#99512]
Hi,

For my purchase service I cannot get purchased but not consumed products in IOS. 
I need it to solve problems in IOS store payments. If connection closed or app crashed but money taken from user I need to check and do related backend credit uploads. 

I don't have any problem in android side but ios not working :( 

Method is : InAppPurchase.instance.restorePurchases() 

after call it if it is android it returns purchased but not consumed products in InAppPurchase.instance.purchaseStream.listen method with purchasedetaillist 

However, ios not working. And if there is a not consumed consumable in user account, also package give error and give info about you should consume it before. 

I solved the issue with this code snippet
 
```
 // checks ios not consumed purchased consumables
    if (Platform.isIOS) {
      if (checkIosPendings) {
        var paymentWrapper = SKPaymentQueueWrapper();
        var transactions = await paymentWrapper.transactions();
        // ignore: avoid_function_literals_in_foreach_calls
        transactions.forEach((transaction) async {
          final uniqId = "${DateTime.now()}${globalUserProvider.user.id}";
          await paymentWrapper.finishTransaction(transaction).then((value) async => {
                if (transaction.transactionState.name == "purchased") {await processIosPendings(transaction.payment.productIdentifier, uniqId)}
              });
        });
        checkIosPendings = false;
      }
    }
  }
```

But I cannot get purchaseDetails.verificationData.serverVerificationData from transaction variable :( 
We are using it to check purchase is succesfull or not in the backend side by sending request to ios store 

```
Flutter version 2.10.2
package version 3.0.0 
there is any error or problem in flutter doctor 
[√] Flutter (Channel stable, 2.10.2, on Microsoft Windows [Version 10.0.19044.1526], locale tr-TR)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.5)
[√] Android Studio (version 2021.1)
[!] Android Studio (version 4.1)
    X Unable to determine bundled Java version.
[√] VS Code (version 1.64.2)
[√] Connected device (3 available)
[√] HTTP Host Availability
```

**Comment by darshankawar** [comment]
> But I cannot get purchaseDetails.verificationData.serverVerificationData from transaction variable :(
> We are using it to check purchase is succesfull or not in the backend side by sending request to ios store

For this scenario, are you looking to get a token after completing or restoring purchases ?
Because, if I am not wrong, you'll need some kind of token to send to back-end after in-app purchase is complete.

If I understand correctly, after a non consumable purchase is used, you don't receive anything from the purchase stream after the initial stream ?

**Comment by utkudenis** [comment]
Hi @darshankawar 
we are getting token from both ios and android for every succesfull consumable (product) before consume it. If you have a time ı can show it to you or record a video

**Comment by darshankawar** [comment]
@utkudenis 
I think your issue title is a bit misleading wherein it says: `InAppPurchase.instance.restorePurchases() does not bring purchased but not consumed products in ios [consumables]`

Probably you wanted to say: `InAppPurchase.instance.restorePurchases()  bring purchased but not consumed products in ios [consumables]`  Is it a correct interpretation ?

Also, on Android: `InAppPurchase.instance.restorePurchases()` returns purchased but not consumed products in `InAppPurchase.instance.purchaseStream.listen` method with `purchaseDetailsList`

But on iOS: the same is not working. Is this a correct interpretation ?



> And if there is a not consumed consumable in user account, also package give error and give info about you should consume it before.

Can you provide the detailed error log you get for this ?

**Comment by utkudenis** [comment]
> @utkudenis I think your issue title is a bit misleading wherein it says: `InAppPurchase.instance.restorePurchases() does not bring purchased but not consumed products in ios [consumables]`
> 
> Probably you wanted to say: `InAppPurchase.instance.restorePurchases() bring purchased but not consumed products in ios [consumables]` Is it a correct interpretation ?
> Actually, title is right :) I call InAppPurchase.instance.restorePurchases() in ios and nothing coming to listen method 
( although there is a purchased but not consumed consumable in ios) so I need to use my code snippet :( 
> Also, on Android: `InAppPurchase.instance.restorePurchases()` returns purchased but not consumed products in `InAppPurchase.instance.purchaseStream.listen` method with `purchaseDetailsList`
> yes, Android works perfectly in the same scenario
> But on iOS: the same is not working. Is this a correct interpretation ? 
> Yes
> > And if there is a not consumed consumable in user account, also package give error and give info about you should consume it before.
> 
> Can you provide the detailed error log you get for this ?
I will share screen shot as soon as possible
