### ISSUE TITLE
google_sign_in build failure

### ISSUE THREAD

**Issue by gibsonsyd** [flutter/flutter#9951]
## Steps to Reproduce

Run: 'Flutter run' in the google_sign_in example app.

## Logs

exampe/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:11: error: cannot find symbol
    GoogleSignInPlugin.registerWith(registry.registrarFor("io.flutter.plugins.googlesignin.GoogleSignInPlugin"));
                      ^
  symbol:   method registerWith(Registrar)
  location: class GoogleSignInPlugin
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

## Flutter Doctor

[✓] Flutter (on Mac OS X 10.12.4 16E195, channel alpha)
    • Flutter at /Apps/Flutter
    • Framework revision 9f1d5ba50e (8 hours ago), 2017-05-09 17:06:52 -0700
    • Engine revision cbbf956fcb
    • Tools Dart version 1.23.0-dev.11.11

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/pietertheron/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[-] iOS toolchain - develop for iOS devices
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Once installed, run 'sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer'.
    ✗ ideviceinstaller not available; this is used to discover connected iOS devices.
      To install, run:
        brew update
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew update
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew update
        brew install cocoapods
        pod setup

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1.2)
    • Dart plugin version 171.4424
    • Flutter plugin version 13.1

[✓] Connected devices
    • SM G920F • 06157df6ac48212c • android-arm • Android 6.0.1 (API 23)

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by eseidelGoogle** [comment]
There was one last change to plugin registration which might be related?
https://groups.google.com/forum/#!topic/flutter-dev/zba1Ynf2OKM

**Comment by gibsonsyd** [comment]
That was the issue for me.
