### ISSUE TITLE
LUCI bots are generating inconsistent licenses_third_party signatures 

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#99526]
The prod engine LUCI builder has failed the licenses check in the Linux Unopt build for 3 of the past 7 commits.  The failures all involve a mismatch in the licenses_third_party signature.

This failure occurred even though these commits passed the licenses check on the try bots.  Some of these commits did not change the dependencies used to generate licenses_third_party and therefore should not have altered the licenses_third_party signature.

The licenses script generates the signature by crawling and hashing a subset of the files in the src/third_party tree.  A mismatch could happen if some of the LUCI bot filesystems contain files covered by the crawl that are missing or out of sync on other bots.

**Comment by godofredoc** [comment]
Retrying with led to see if it is consistent:

https://chromium-swarm.appspot.com/task?id=596b633c1f5b8810

**Comment by CaseyHillers** [comment]
List of failures in https://ci.chromium.org/p/flutter/builders/prod/Linux%20Unopt

**Comment by CaseyHillers** [comment]
Is this check pulling the licenses from pub cache @jason-simmons ?

**Comment by zanderso** [comment]
The license check runs before anything could be fetched from pub into the tree.

**Comment by jason-simmons** [comment]
Is there a way to inspect the filesystem on a bot where the check succeeded and a bot where it failed?  Would the state still be preserved if the checks ran several hours ago?

Another option would be pushing a patch to the license script that logs each file path found in the crawl along with a hash of the file.

**Comment by godofredoc** [comment]
Even though the default for clobber is True we are explicitly passing clobber=false. This is one builder on the same bot passing clobber=true: https://chromium-swarm.appspot.com/task?id=596b76269ea03e10

**Comment by godofredoc** [comment]
Passing clobber=true didn't help https://chromium-swarm.appspot.com/task?id=596b76269ea03e10

**Comment by godofredoc** [comment]
This is a retry deleting the git cache: https://chromium-swarm.appspot.com/task?id=596b86111f645d10

**Comment by godofredoc** [comment]
That last one worked. We need two different CLs:

* https://flutter-review.googlesource.com/c/recipes/+/27640
* https://github.com/flutter/engine/pull/31817

**Comment by zanderso** [comment]
This is continuing to happen https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Unopt/3927/overview

**Comment by godofredoc** [comment]
I would recommend to check the script or the auto-roller. All the caches are now being cleaned before running `Linux unopt`

**Comment by godofredoc** [comment]
The problem was caused by a dependency using a branch rather than a tag. The third party dependencies are now pinned to a commit and this problem should not happen again.
