### ISSUE TITLE
Dart roll failing on pthread_setname_np compilation error

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#99534]
Starting with the roll here https://github.com/flutter/engine/pull/31818

The Dart roll to the Engine is failing on the compilation error:
```
../../third_party/dart/runtime/bin/platform_macos.cc:256:3: error: use of undeclared identifier 'pthread_setname_np'
  pthread_setname_np(name);
  ^
1 error generated.
```

 See build https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20Unopt/9726/overview

Looks like it was introduced in https://dart.googlesource.com/sdk.git/+/bd8ed80309714c00e306a270844e912d81cfe19b cc @rmacnak-google

**Comment by zanderso** [comment]
cc @a-siva

**Comment by aam** [comment]
https://dart.googlesource.com/sdk/+/574bc8e59c1abd08fb1759513104e44a3debb005 with revert of culprit landed
