### ISSUE TITLE
Flutter plugins don't work on windows - GeneratedPluginRegistrant

### ISSUE THREAD

**Issue by DrasiusMajere** [flutter/flutter#9953]
## Steps to Reproduce
After upgrade flutter, now pathprovider is a plugin. I try to use it but get the below error. I think something is wrong with registration of plugins.  The GeneratedPluginRegistrant  file  is generated automatically. 
This is the output on a new project. Although in my old project fails too. Furthermore in my old app show an additional issue in the settings.gradle file that is not updated.

## Logs

PS C:\PROGRAMACION\FLUTTER\mysterion> flutter run
Running 'flutter packages get' in mysterion...        1.2s
Launching lib/main.dart on SM A510F in debug mode...
Running 'gradle assembleDebug'...
C:\PROGRAMACION\FLUTTER\mysterion\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:11: error: cannot find symbol
    PathProviderPlugin.registerWith(registry.registrarFor("io.flutter.plugins.path_provider.PathProviderPlugin"));
                      ^
  symbol:   method registerWith(Registrar)
  location: class PathProviderPlugin
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Gradle build failed: 1

## Flutter Doctor

PS C:\PROGRAMACION\FLUTTER\mysterion> flutter doctor
[√] Flutter (on Microsoft Windows [VersiÃ³n 10.0.15063], channel master)
    • Flutter at C:\flutter
    • Framework revision 9b56c1c58c (3 hours ago), 2017-05-10 09:41:55 +0200
    • Engine revision cbbf956fcb
    • Tools Dart version 1.23.0-dev.11.11

[√] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at C:\Users\Drasius\AppData\Local\Android\sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[-] IntelliJ IDEA Community Edition (version 14)
    • Dart plugin version 141.1586
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/managing-plugins.html

[-] WebStorm (version 2016.1)
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/managing-plugins.html

[√] Connected devices
    • SM A510F • 3300886347c56327 • android-arm • Android 6.0.1 (API 23)

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by mit-mit** [comment]
I'm really sorry, but this plugin is currently broken. @szakarias is working on fixing it, and a new version will be published shortly!

**Comment by DrasiusMajere** [comment]
I test sharedpreferences plugin and the same error

**Comment by mit-mit** [comment]
Yes, all plugins need to be updated after this breaking change:
https://groups.google.com/forum/#!topic/flutter-dev/zba1Ynf2OKM

Also, we are working on adding test automation in travis to prevent breaks like this going undetected.

Sorry about the breaks once again, these were the last planned breaking changes to plugins.

**Comment by DrasiusMajere** [comment]
thank you, sorry not needed it's normal in development. I like working with flutter and dart techs. keep going like this
