### ISSUE TITLE
Windows released app close automatically. 

### ISSUE THREAD

**Issue by mjafartp** [flutter/flutter#99539]
## Steps to Reproduce

1. flutter build --release windows
2. open build windows app
3. crash after routing to a new page (or even doing something on the application)

Windows Error report

```
Faulting application name: xxx.exe, version: 7.83.0.0, time stamp: 0x6221b5ca
Faulting module name: ucrtbase.dll, version: 10.0.19041.789, time stamp: 0x2bd748bf
Exception code: 0xc0000409
Fault offset: 0x000000000007286e
Faulting process id: 0x4328
Faulting application start time: 0x01d82f9482220926
Faulting application path: C:\Apps\xxx\build\windows\runner\Release\xxx.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report Id: 92b1ee33-f73a-434a-95fe-9a7ae9b6b901
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by mjafartp** [comment]
Sometimes the error is

Faulting application name: xxx.exe, version: 7.83.0.0, time stamp: 0x6221d591
Faulting module name: flutter_windows.dll, version: 0.0.0.0, time stamp: 0x621d4c74
Exception code: 0xc0000005
Fault offset: 0x00000000009f2b07
Faulting process id: 0x285c
Faulting application start time: 0x01d82fa6c0bdbb98
Faulting application path: C:\Apps\xxx\build\windows\runner\Release\xxx.exe
Faulting module path: C:\Apps\xxx\build\windows\runner\Release\flutter_windows.dll
Report Id: 440b59ce-c801-4269-be6e-aafe4a9843cc
Faulting package full name: 
Faulting package-relative application ID:

**Comment by darshankawar** [comment]
@mjafartp 
Can you provide `flutter doctor -v`, your windows machine details ? Are you using Win 7 or 10 ?

**Comment by mjafartp** [comment]
We are using windows 10 

flutter doctor -v
[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.19044.1526], locale en-IN)
    • Flutter version 2.10.3 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (2 days ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\xxx\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31129.286
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.64.2)
    • VS Code at C:\Users\xxx\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.34.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1526]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 99.0.4844.51
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 98.0.1108.62

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by FusoraTech** [comment]
Update your VS Studio CE to VS CE 2022 (and with it, the C runtimes of your machine), reboot and try again.

https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=Community&channel=Release&version=VS2022&source=VSLandingPage&cid=2030&passive=false

**Comment by darshankawar** [comment]
@mjafartp 
Try above and see if it helps.

**Comment by mjafartp** [comment]
We identified this issue because of `ReorderableListView`, This works well on Android / iOS and Linux but it gives errors on Windows.

**Comment by darshankawar** [comment]
@mjafartp 
Thanks for further details. Can you provide us a complete minimal reproducible code sample that includes `ReorderableListView` which shows this error ?

**Comment by moescs** [comment]
Please reopen. We're having the same issue. It crashes intermittently with different error codes in the windows event log. Click on the "+" button to add a tab. It generally fails the first time you click "+" after launch or it won't fail no matter how many tabs you add. I had to remove the windows directory because it made the zip file too large for githubs limitations.
[crash_repro.zip](https://github.com/flutter/flutter/files/8366025/crash_repro.zip)
.
