### ISSUE TITLE
Flutter Plugin with xcframework only works with device not in ios simulator (depending on Flutter version)

### ISSUE THREAD

**Issue by raegtime** [flutter/flutter#99541]
[](https://i.stack.imgur.com/I9f5k.png)I have created a flutter plugin. By running the example app in Flutter I get this error:

Error: Swift Compiler Error (Xcode): No such module 'AusweisApp2'
 

podspec file:

```
Pod::Spec.new do |s|       
  s.source           = { :path => '.' }
  s.source_files = 'Classes/**/*'
  s.dependency 'Flutter'
  s.platform = :ios, '11.0'
  s.vendored_frameworks = 'Frameworks/AusweisApp2.xcframework'
  s.xcconfig = { 'OTHER_LDFLAGS' => '-framework AusweisApp2' }

  # Flutter.framework does not contain a i386 slice.
  s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES', 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'i386' }
  s.swift_version = '5.0'
end
```
The App works on device but not on ios simulators. You can download the xcframework here https://github.com/Governikus/AusweisApp2-SDK-iOS

 
In Flutter 2.2.1 it works
In Flutter 2.5.3 it works not
in Flutter 2.8.0 it works
in Flutter 2.8.1 it works not
in Flutter 2.10.3 it works not

**Comment by darshankawar** [comment]
@raegtime 
`'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'i386'` , can you also try to add `arm64` to it and see if it helps ?

**Comment by raegtime** [comment]
works fine! THX!!! ... but why does it work in different flutter versions without adding `arm64`

**Comment by darshankawar** [comment]
@raegtime 
Good to know it worked. I am not sure about earlier versions, but there are some plugins (e.g google_sign_in) and Google Maps SDK that don't support arm64 simulators and hence that arm arch need to be excluded like we did above. It may be similar to the one related to your case.

You may look at this issue for further reference: https://github.com/flutter/flutter/issues/85713
Closing from here as the original issue you reported is resolved.

**Comment by ammarhemani** [comment]
> @raegtime `'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'i386'` , can you also try to add `arm64` to it and see if it helps ?

I have been trying to find a fix for the last 4 hours, and finally landed on excluding the architecture, however was having some trouble. This comment just made my day, thank you, kind sir

For anyone else, the way to add arm64 to it is like this: 
`  s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES', 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'i386 arm64' }`
