### ISSUE TITLE
image_picker plugin does not build for Android

### ISSUE THREAD

**Issue by nalin** [flutter/flutter#9956]
## Steps to Reproduce

1.  cloned the image_picker plugin repository.
2. ran `flutter packages get`
3. ran `flutter run` with android emulator running
4. received build error below

## Logs

nalinmittal-macbookpro:example nalinmittal$ flutter run -d emulator-5554
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Running 'gradle assembleDebug'...                         
/Users/nalinmittal/code/flutterCam/image_picker/example/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:11: error: cannot find symbol
    ImagePickerPlugin.registerWith(registry.registrarFor("io.flutter.plugins.imagepicker.ImagePickerPlugin"));
                     ^
  symbol:   method registerWith(Registrar)
  location: class ImagePickerPlugin
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Gradle build failed: 1

## Flutter Analyze

nalinmittal-macbookpro:example nalinmittal$ flutter analyze
Analyzing /Users/nalinmittal/code/flutterCam/image_picker/example...
     hint • Unused import at lib/main.dart:3:8 • unused_import
     hint • Unused import at lib/main.dart:5:8 • unused_import
2 issues found.
(Ran in 4.4s)

## Flutter Doctor

nalinmittal-macbookpro:example nalinmittal$ flutter doctor
[✓] Flutter (on Mac OS X 10.12.4 16E195, channel master)
    • Flutter at /Users/nalinmittal/code/flutter
    • Framework revision 0b2fb13269 (16 hours ago), 2017-05-09 17:56:49 -0700
    • Engine revision cbbf956fcb
    • Tools Dart version 1.23.0-dev.11.11

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/nalinmittal/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1.2)
    • Dart plugin version 171.4424
    • Flutter plugin version 13.1

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 7.1.1 (API 25) (emulator)
    • iPhone 7                  • 0923BEF5-F988-4C08-B0A9-9871620BC171 • ios         • iOS 10.2 (simulator)

**Comment by eseidelGoogle** [comment]
@collinjackson or @mravn-google would know.

**Comment by goderbauer** [comment]
I am working on updating this plugin to the new plugin API. PR will be out soon. Stay tuned.
