### ISSUE TITLE
[go_router] Widget unintendedly recreates on Android back button pressed

### ISSUE THREAD

**Issue by hosikiti** [flutter/flutter#99577]
## Steps to Reproduce

I have the following page structure.

HomePage -> Modal 1 -> Modal 2

When you are in Modal 2 and go back with Android back button, Modal 2 closes. That is fine. But Modal 1 and Modal 2 rebuild unintendedly.

Following console logs shows this issue.

```
// show homepage
I[/flutter]() (23826): build homepage

// tap 'Open Modal 1' button
I[/flutter]() (23826): build modal 1

// tap 'Open Modal 2' button
I[/flutter]() (23826): build modal 2

// press Android back button
I[/flutter]() (23826): build modal 1
I[/flutter]() (23826): build modal 2
```

## Sample Project to Reproduce

https://github.com/hosikiti/go-router-backbutton-issue

## What I have confirmed

I confirmed that this issue does not happen when you press the close button at the left top corner. Also, without GoRouter the issue does not occur either.

**Comment by darshankawar** [comment]
Thanks for the report. Using the repo and running it on Android device does show me the same behavior as reported:

```
// show homepage
I[/flutter]() (35483): build homepage

// tap 'Open Modal 1' button
I[/flutter]() (35483): build modal 1

// tap 'Open Modal 2' button
I[/flutter]() (35483): build modal 2

// press Android back button
I[/flutter]() (35483): build modal 1
I[/flutter]() (35483): build modal 2
```

<details>
<summary> stable, master flutter doctor -v </summary>

```

[✓] Flutter (Channel stable, 2.10.3, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 2.10.3 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (11 hours ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.


[✓] Flutter (Channel master, 2.11.0-0.0.pre.795, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 2.11.0-0.0.pre.795 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78039ea4f3 (2 hours ago), 2022-03-06 21:51:15 -0500
    • Engine revision 1875f0ad3f
    • Dart version 2.17.0 (build 2.17.0-181.0.dev)
    • DevTools version 2.11.1

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.


```

</details>

**Comment by BelongsH** [comment]
I also found this problem

I'm jumping to an A page and passing parameters. Then, switch to page B from page A. A page  are refreshed.(I thinks page A Should not refresh) When I go from page B to page A. The page of A also refreshes.

Is it designed that way?

**Comment by abdullah432** [comment]
I'm facing same issue

**Comment by medz** [comment]
I feel sorry that it hasn't been repaired yet.

**Comment by yairsts** [comment]
I'm facing the same issue

**Comment by iqram0014** [comment]
I had similar issue. My whole navigation stack was getting rebuild after each navigation. I solved it by keeping track of user navigation. I created one List of routes/urls. initialized list with one element as initial url. whenever we go to new screen add the url to router list. For going back to previous screen, use WillPoPScope and inside this we need to delete the last element and then navigate to previous screen from last element of List. Example code snippet given below:

Initializing list:
List routesTrack = ['/SplashScreen'];

While pushing to next screen:
routesTrack.add('/FirstScreen');
context.go('/SecondScreen');

going back to previous screen( natural go back by sliding screen or by back button in navigation whatever):
WillPopScope(
      onWillPop: () async {
        routesTrack.removeLast();
        context.go(routesTrack.last);
        return false;
      },
      child: child:
      );

**Comment by vishalpatel1327** [comment]
That's the critical bug. to prevent it add lots of unnecessary conditions. That's totally ridiculous.  ;(

**Comment by JohnnyRainbow81** [comment]
Same issue here. Produces ugly side effects especially on pages with init()-triggered animations :/

**Comment by chunhtai** [comment]
We don't guarantee how often the build is called. So it is always a good idea to not do any heavy loading or side effect when calling build. This is true across entire flutter framework. These logic should be in a statefulwidget. I don't have plan to change the current behavior.

**Comment by medz** [comment]
> We don't guarantee how often the build is called. This is true across entire flutter framework. It is always a good idea to not do any heavy loading or side effect when calling build. These logic should be in a statefulwidget. I don't have plan to change the current behavior.

Your understanding of routing is wrong! Could it be that if I click the back button in Chrome, will the currently browsed page reload the page?

I suggest you learn more about routing in depth, and refer to Vue-router, React Router, etc. It is impossible for us to make every page or widget into a "state preservation" component, and it is unreasonable for the gorouter to roll back the page refresh itself.

If this is the official theory to make routing, then why isn't this logic in Flutter navigation?

Your remarks are obviously the "thinking" of a dictator. As an official, you should not make such remarks as "I will not make changes", but should actually discuss this issue to collect community opinions.

**Comment by vishalpatel1327** [comment]
I am also with the @medz  .
the way of rebuilding the previous widget/parent widget is totally useless even not fit for some complicated app logic.

@chunhtai  you guys have to rethink why lots of people are facing the same issue.?

**Comment by chunhtai** [comment]
GoRouter is using decorative routing behind the scene. Every time an operation happens, the navigator is given a modified page list to update. The navigator doesn't know whether the modified list is a result of push/go/pop, it just grab the new list and update its history.

We could doing some hack to allow navigator to treat a certain kind of update differently, but we will soon want to add more and more cases like this to navigator and make it really hard to maintain. This is essentially the same issue we are facing when we first developing navigator API.

**Comment by evferrer87** [comment]
Actually I was observing this same weird behavior and asking what was wrong in my app, when I click on the back button the current page I want to close re-build again, until  I found this issue thread.

When we execute the pop I think there should be new logic to avoid that behavior and fix it by next releases.
Also it should be included someway in the docs.

Thanks to this great community.
Regards
