### ISSUE TITLE
No way to know whether it is doing a debug or release build in Flutter Windows

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/flutter#99595]
Hi thanks for the wonderful framework! 

I have some Python scripts which should run when building the Flutter Windows app. It looks like:

```
find_package( PythonInterp 3 REQUIRED )
add_custom_target(
 myscript ALL
 COMMAND ${PYTHON_EXECUTABLE} somefile.py
)
add_dependencies(${PLUGIN_NAME} myscript)
```

However, in my script, I need to know whether it is doing a debug or a release build. But I cannot find out an approach to do this.

I have tried to print every cmake variable, and nothing indicates it is a debug or release. I have also tried to print out all environment variables in the python script, but again nothing interesting. 

Thanks for any suggestions!

## Steps to Reproduce

run any flutter windows app.

**Expected results:** 
in scripts at compile time, can know whether debug or release

**Actual results:** 
cannot know

<details>
<summary>Code sample</summary>

```dart
n/a
```

</details>

<details>
  <summary>Logs</summary>

```
n/a
```

```
```

```
[✓] Flutter (Channel stable, 2.10.3, on macOS 11.6.4 20G417 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.10.3 at /Users/tom/fvm/versions/2.10.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (3 天前), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
other parts also ok
```

</details>

**Comment by stuartmorgan** [comment]
There is nothing special about the CMake builds used in the Flutter template; determining the build type is done [in the usual way](https://cmake.org/cmake/help/latest/manual/cmake-buildsystem.7.html#build-configurations).

Closing as there's no Flutter issue here (and the assertion that there's no way to get this information is not correct). In the future, a resource like StackOverflow would be the place to ask questions about how to use CMake in general.

**Comment by fzyzcjy** [comment]
Thank you! I did not realized this and originally thought Flutter will pass some flags around.
