### ISSUE TITLE
Feature: WebView support for all desktop platforms (Windows/MacOS/Linux)

### ISSUE THREAD

**Issue by Eerey** [flutter/flutter#99597]
Currently, more and more customers demand for a WebView inside our desktop flutter app.
It boosts productivity, sometimes websites are quickly scanned within an application, just for a few seconds, without opening another window (and closing it)

Currently, [WebView for Flutter](https://pub.dev/packages/webview_flutter) is a very popular plugin for mobile platforms, but **this does not work for e.g. Windows**.
I know that there are other plugins such as [flutter-webview-windows](https://github.com/jnschulze/flutter-webview-windows), but it is only working for windows and we want to offer our application to Mac and Linux users aswell.

Are there any official plans to support WebView on desktop platforms?
I'm asking because the "View/report issues" of [WebView for Flutter](https://pub.dev/packages/webview_flutter) is tied to the flutter-repository.

**Comment by danagbemava-nc** [comment]
Kindly see the following issues

- https://github.com/flutter/flutter/issues/41725
- https://github.com/flutter/flutter/issues/37597
- https://github.com/flutter/flutter/issues/41726

Closing from here as duplicate. 

Thank you
