### ISSUE TITLE
IntelliJ IDEA Community Edition (the doctor check crashed)

### ISSUE THREAD

**Issue by Jacobkyalo** [flutter/flutter#99599]
Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
   FormatException: Unexpected extension byte (at offset 5)

**Comment by Jacobkyalo** [comment]
I need help on error when I run flutter doctor in windows PowerShell

**Comment by tomgeraghty3** [comment]
I also have this problem but for IntelliJ Ultimate:

```
[☠] IntelliJ IDEA Ultimate Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about
      this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
```

**Comment by JoseCarlosSkar** [comment]
One way to "fix" it that worked on my machine was to update the version of gradle and dart.

I downloaded the latest 'complete' version and added /bin from the extracted folder to the system environment variables.
![image](https://user-images.githubusercontent.com/64156428/156901049-9f82abd2-e66a-4abd-9da4-c6d3a867c64c.png)

Then in the configuration files... 
- andriod/gradle/wrapper/gradle-wrapper.properties
I updated the distributionUrl to https\://services.gradle.org/distributions/gradle-7.4-all.zip

- andriod/build.gradle
ext.kotlin_version to '1.6.10'
And I also updated 'com.android.tools.build:gradle:x.x.x' to com.android.tools.build:gradle:7.0.4

$ flutter clean

I hope I have helped in some way.

**Comment by darshankawar** [comment]
@JoseCarlosSkar and everyone facing this issue, please note below:

This was fixed as part of https://github.com/flutter/flutter/issues/94060 and the fix is available on latest master. This will be rolled into stable in upcoming version. See this issue comment for your reference: https://github.com/flutter/flutter/issues/94060#issuecomment-1018801980

Closing this as duplicate.
