### ISSUE TITLE
[local_auth] application crashes with "Invalid package identifier when getting bag for resource number 0x000005f7"

### ISSUE THREAD

**Issue by halfaHalfawy** [flutter/flutter#99598]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by halfaHalfawy** [comment]
i followed all steps of insalling local_auth  "android integration", i used android 8.1

**Comment by danagbemava-nc** [comment]
Hi @halfaHalfawy, please provide a complete minimal reproducible code sample that we can use to verify this as well as the output of `flutter doctor -v`, the version of `local_auth` you're using and steps to reproduce. 

In the future, when filing an issue, please provide the information requested in the template. 

Thank you
