### ISSUE TITLE
[Skia] Direct draw into buffer using GPU for further usages

### ISSUE THREAD

**Issue by ryuujo1573** [flutter/flutter#99593]
I was trying to draw Flutter widgets directly into the video, via a buffer object.

It shows that Flutter has an implementation: **`Scene`** , where lies a native method `_toImage` linked to `Scene_toImage`,
and it offers access to **Image Bytes**, which can be used to furnish the video.

However, it causes quite some pressure on CPU seemingly, and I was wondering how to use `Skia` ability to draw flutter things into some `FrameBuffer` or sth like that.

I am a quite newbee and non-english speaker here, so I would appreciate for excusing my poor understanding of the workflows.

## Use case

Creating one video-stream composing APP, providing OBS-like functions.
* Video composing with YUV(A)/ARGB inputs
* Live video source filtering, e.g. Gauss blur etc. *(SkSL might be needed)*
* Switching final composition from various sources.
* ...

Now I ran into the problem that I can't use flutter widgets as in-video visual components.

What I can do now is as following code:
```dart
try {
  var render = repaintKey.currentContext!.findRenderObject()
      as RenderRepaintBoundary;
  double dpr = window.devicePixelRatio;

  var byteData = await render
      .toImage(pixelRatio: dpr)
      .then((image) => image.toByteData(format: ImageByteFormat.png));

  var tempDir = await getTemporaryDirectory();
  var fileName = '${tempDir.path}/frame_${index++}';

  var bytes = byteData!.buffer.asUint8List();

  var file = File(fileName);
  if (!file.existsSync()) {
    file.createSync();
  }
  await file.writeAsBytes(bytes);

} catch (e) {
  ...
}

```
I can get single frame of this.

I have no idea of implementing continuous outputting and generating the ARGB or YUVA data as a stream source.

## Proposal

Expose an API or access to Skia, which could be this way:
(naive design)
```dart
RenderRepaintBoundary render = ... ;

// redirect/multicast the output
var bufferObject = render.createBuffer();

var foo = StreamSource(...);
foo.bindBuffer(bufferObject);

```

Thank you for your time.

**Comment by ryuujo1573** [comment]
I've found some questions on StackOverflow maybe relevant to the issue:
[Video Editor in Flutter using dart [closed]](https://stackoverflow.com/questions/54018792/video-editor-in-flutter-using-dart)
[Flutter how to save(re-encode) text overlay on video](https://stackoverflow.com/questions/51852673/flutter-how-to-savere-encode-text-overlay-on-video)
and also mine:
<img width="480" alt="image" src="https://user-images.githubusercontent.com/16525512/156877409-e095637a-99e6-4397-aa15-d9ec68441b9e.png">
, which turned out to be the issue here.
and thanks.

**Comment by ryuujo1573** [comment]
Hi, this feature request is mainly about `flutter/engine`.
I started to know about Flutter's low-level workflows, whose understanding is out of my capabilities now.
I found this picture:
![image](https://user-images.githubusercontent.com/16525512/156915533-e251c144-eeb2-4f0f-8c91-c7fe25650e02.png)
might be some sort of starting point, and seemingly I need to write native code around *compositing* stage.
`rasterizer.cc` -> `gpu_surface_gl.cc` -> `android_surface_gl.cc` might be the steps I should intervene.

Could you please give some hints on this? The feature might not be added in the coming future, but if I the noob (😵‍💫 ) make it to mess up with these codes... hmmm

Any thanks, Zhang

**Comment by chinmaygarde** [comment]
If you want to record a stream of Flutter frames directly to a video, I suggest authoring [a custom Flutter Embedder](https://github.com/flutter/flutter/wiki/Custom-Flutter-Engine-Embedders) where you have control of the notion of the "onscreen" framebuffer that Flutter renders to.

As you have already discovered, capturing a single image from within a Flutter application is possible but prohibitively slow. Also, there isn't anything Skia specific about the implementation of this feature.

The use-case is fairly niche and since there is already a way to do this using custom embedders, I am closing this as a wont-fix.

**Comment by ryuujo1573** [comment]
Thank you. I'll try.
