### ISSUE TITLE
> Could not resolve junit:junit:4.12.          > Could not parse POM https://repo.maven.apache.org/maven2/junit/junit/4.12/junit-4.12.pom

### ISSUE THREAD

**Issue by ofceab** [flutter/flutter#99613]
## Steps to Reproduce

I'm using the flutter 2.10.0 for building my application.

I have the following as dependencies
`dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^1.0.3
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  mockito: ^5.1.0
  http: ^0.13.4
  dartz: ^0.10.1
  get_it: ^7.2.0
  validators: ^3.0.0
  url_launcher: ^6.0.20
  data_connection_checker_tv: ^0.3.5-nullsafety

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  hive_generator: ^1.1.2
  build_runner: ^2.1.7`

 I'm running on windows 11

3. **To get the result I got**
 To get the error I got just try to build the final apk using : flutter build apk --split-per-abi

**Actual results:**
`Building with sound null safety 

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':path_provider_android:debugUnitTestRuntimeClasspath'.
   > Could not resolve junit:junit:4.12.
     Required by:
         project :path_provider_android
      > Could not resolve junit:junit:4.12.
         > Could not parse POM https://repo.maven.apache.org/maven2/junit/junit/4.12/junit-4.12.pom
            > Resetting to invalid mark
      > Could not resolve junit:junit:4.12.
         > Could not parse POM https://repo.maven.apache.org/maven2/junit/junit/4.12/junit-4.12.pom
            > Resetting to invalid mark
      > Could not resolve junit:junit:4.12.
         > Could not parse POM https://repo.maven.apache.org/maven2/junit/junit/4.12/junit-4.12.pom
            > Resetting to invalid mark

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 4s
Running Gradle task 'assembleRelease'...                           66,0s
Gradle task assembleRelease failed with exit code 1`

As the project was an open source project here is the code link
[https://github.com/SiProgramming/trace_in_mobile_app.git](https://github.com/SiProgramming/trace_in_mobile_app.git)

**Comment by darshankawar** [comment]
@ofceab 
I cloned the repo and ran the said command which built the apk properly for me without any issues:
```

C:\Users\Win\Downloads\trace_in_mobile_app-main\trace_in_mobile_app-main>flutter build apk --split-per-abi
Running "flutter pub get" in trace_in_mobile_app-main...           12.7s

 Building with sound null safety

Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Note: D:\FlutterSDK\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_android-2.0.12\android\src\main\java\io\flutter\plugins\pathprovider\PathProviderPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
WARNING: [Processor] Library 'C:\Users\Win\.gradle\caches\modules-2\files-2.1\org.robolectric\shadows-framework\4.3\150103d5732c432906f6130b734e7452855dd67b\shadows-framework-4.3.jar' contains references to both AndroidX and old support library. This seems like the library is partially migrated. Jetifier will try to rewrite the library anyway.
 Example of androidX reference: 'androidx/test/runner/lifecycle/Stage'
 Example of support library reference: 'android/support/annotation/NonNull'
Running Gradle task 'assembleRelease'...                          300.0s
√  Built build\app\outputs\flutter-apk\app-armeabi-v7a-release.apk (6.8MB).

C:\Users\Win\Downloads\trace_in_mobile_app-main\trace_in_mobile_app-main>
```

I am latest stable (2.10.3).

Looking at the error log, it seems to indicate you might be on older version of gradle and it may not have anything to do with Flutter, so closing this as not an issue. You may ask about the same on support channels like stackoverflow.
