### ISSUE TITLE
[WebView]Android app crashes after long idle time

### ISSUE THREAD

**Issue by FiShelly** [flutter/flutter#99614]
## Steps to Reproduce

1. Use webview_flutter（same in flutter_inappwebview） in app。（the target url use websocket and live stream(m3u8), other type url not test）
2. wait a long time (maybe dozens of minutes or  couple of hours)
3. and app will crash in android ( ios not test).
4. device: HUAWEI Mate 40 pro(Harmony os)、XIAOMI、HUAWEI MATE 30 Pro(Anroid 10)

<details>
<summary>Code sample</summary>

```dart
WebView(
              gestureNavigationEnabled: true,
              userAgent: Platform.isIOS
                  ? Constant.APP_WEBVIEW_IOS_USERAGEN
                  : Constant.APP_WEBVIEW_ANDROID_USERAGEN,
              onWebResourceError: (error) {
                print(error);
              },
              onWebViewCreated: (controller) {
                webViewController = controller;
                if (widget.onWebViewCreated != null) {
                  widget.onWebViewCreated!(controller);
                  _controller.complete(webViewController);
                }
              },
              javascriptChannels: <JavascriptChannel>[
                _javascriptChannel(context),
              ].toSet(),
              navigationDelegate: (NavigationRequest request) {
                return NavigationDecision.navigate;
              },
              initialUrl: url,
              javascriptMode: JavascriptMode.unrestricted,
              onPageFinished: (finish) {
                if (widget.onWebviewCallback != null) {
                  widget.onWebviewCallback!({'type': 'loadStop'});
                }
              },
              onPageStarted: (v) {
                if (widget.onWebviewCallback != null) {
                  widget.onWebviewCallback!({'type': 'loadStart'});
                }
              },
              allowsInlineMediaPlayback: true,)
```

</details>

<details>
  <summary>Logs</summary>

[bug4.log](https://github.com/flutter/flutter/files/8191727/bug4.log)  (use webview_flutter)
[bug3.log](https://github.com/flutter/flutter/files/8191732/bug3.log)  (use flutter_inappwebview)

 

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on Mac OS X 10.14.6 18G95
    darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK
    version 31.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    ✗ Flutter requires a minimum Xcode version of 12.0.1.
      Download the latest version or update via the Mac App Store.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.65.0)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

</details>

https://user-images.githubusercontent.com/16427792/156904475-ce0b7645-3aaf-478f-a062-22512e0f43ec.mp4

**Comment by ryuujo1573** [comment]
This is the wrong place to ask a question like this.
Try **StackOverflow**.

--------

看着你好像在做软创的项目，这种问题建议尽可能多查文档：
https://github.com/flutter/plugins/tree/main/packages/webview_flutter/webview_flutter
或者去plugins的repo下面去提问。
https://github.com/flutter/plugins/issues

建议自行close。

**Comment by maheshmnj** [comment]
Hi @FiShelly, Thanks for filing the issue. Does the app crash in any specific mode (debug/profile/release) or all modes? Are there any crash logs that you can share with us to have a look? 
Please share the target URL in order to investigate the issue further.  

Additionally, Please try upgrading to latest `stable 2.10.3` and see if this helps resolve the issue.

**Comment by FiShelly** [comment]
> [bug4.log](https://github.com/flutter/flutter/files/8191727/bug4.log) (use webview_flutter)
> [bug3.log](https://github.com/flutter/flutter/files/8191732/bug3.log) (use flutter_inappwebview)

@maheshmnj 

thank you comment, and the app crash in debug \ release ,and profile not test, so i do not know.

i have exported this log, I'm not sure if this log can help you.

yes, i am testing in stable 2.10.3 now (  I've been running for a few hours without a crash in stable 2.10.3.) , but you know it's a random crash, so i do not know it is solve.

**Comment by maheshmnj** [comment]
Thanks for the logs @FiShelly, Provided that you are no longer experiencing the crash on stable 2.10, I feel it's safe to close the issue. I do understand that it's an intermittent crash, So Please free to file a new issue or comment down on this issue  if you reproduce the crash again using the latest version of flutter (at the time of reporting) and we will reopen it.
