### ISSUE TITLE
FlutterPluginRegistrar should expose FlutterViewController

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#9961]
I am updating the image_picker plugin to the newest plugin API and there doesn't see, to be a way anymore to access the FlutterViewController: https://github.com/flutter/image_picker/commit/733d3317646e928c781809fe2648c4ba89f7f53e#diff-5899d28b4e39af8fd863d004b30d690eR20

Can a getter be added to FlutterPluginRegistrar?

**Comment by mravn-google** [comment]
I'm not sure there will always be just one `FlutterViewController` in any Flutter-based app. Maybe expose the `UIWindow` property from `FlutterAppDelegate` via the plugin registrar. That way, plugins can access view controllers during registration in the same way that `FlutterAppDelegate` currently does, e.g.:

```
UIViewController* viewController = registrar.window.rootViewController;
```

**Comment by cbracken** [comment]
> I'm not sure there will always be just one FlutterViewController in any Flutter-based app.

Agreed we should avoid that assumption. 

> Maybe expose the UIWindow property from FlutterAppDelegate via the plugin registrar.

It's theoretically possible to have multiple `FlutterViewController`s in the responder chain for a given `UIWindow`, so you'd probably want to assume that when you go to find the one you want.

**Comment by mravn-google** [comment]
We just want to `presentViewController:` on "the" `UIViewController`.

If `[UIApplication sharedApplication].keyWindow.rootViewController is a reliable source of a `UIViewController` for such use, we should let plugins use that instead, and close this PR.

cc @szakarias

**Comment by mravn-google** [comment]
Closed per comment above.

**Comment by collinjackson** [comment]
I'm reopening this bug because this change is causing crashes when signing in on iOS. 

`[UIApplication sharedApplication].keyWindow.rootViewController` is nil at the time it is read.

`(UIViewController *)registrar.messenger` works fine.

**Comment by collinjackson** [comment]
In case anyone runs into the crash, here are the logs for it. The problem seems to be that keyWindow isn't set up yet. I'm running the firebase_auth sample app which uses google_sign_in.

```
Jun 13 16:49:50 jackson-macbookpro Runner[25579]: *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'uiDelegate must either be a |UIViewController| or implement the |signIn:presentViewController:| and |signIn:dismissViewController:| methods from |GIDSignInUIDelegate|.'
	*** First throw call stack:
	(
		0   CoreFoundation                      0x000000010406cb0b __exceptionPreprocess + 171
		1   libobjc.A.dylib                     0x00000001084e4141 objc_exception_throw + 48
		2   CoreFoundation                      0x00000001040d5625 +[NSException raise:format:] + 197
		3   Runner                              0x0000000103a654e4 -[GIDSignIn signInWithOptions:] + 88
		4   Runner                              0x0000000103a61f50 -[GIDSignIn signIn] + 64
		5   Runner                              0x00000001039a38ff -[GoogleSignInPlugin handleMethodCall:result:] + 1295
		6   Flutter                             0x000000010489e6b8 __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 118
		7   Flutter                             0x00000001048ab6b8 _ZN5shell21PlatformMessageRouter21HandlePlatformMessageEN3ftl6RefPtrIN5blink15PlatformMessageEEE + 166
		8   Flutter                             0x00000001048aec0b _ZN5shell15PlatformViewIOS21HandlePlatformMessageEN3ftl6RefPtrIN5blink15PlatformMessageEEE + 35
		9   Flutter                             0x00000001048cf099 _ZNSt3__110__function6__funcIZN5shell6Engine21HandlePlatformMessageEN3ftl6RefPtrIN5blink15PlatformMessageEEEE3$_1NS_9allocatorIS9_EEFvvEEclEv + 59
		10  Flutter                             0x00000001048b5d37 _ZN3fml15MessageLoopImpl15RunExpiredTasksEv + 1007
		11  Flutter                             0x00000001048b8454 _ZN3fml17MessageLoopDarwin11OnTimerFireEP16__CFRunLoopTimerPS0_ + 26
		12  CoreFoundation                      0x0000000104000454 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
		13  CoreFoundation                      0x00000001040000e3 __CFRunLoopDoTimer + 1011
		14  CoreFoundation                      0x0000000103fffcaa __CFRunLoopDoTimers + 266
		15  CoreFoundation                      0x0000000103ff79ec __CFRunLoopRun + 1916
		16  CoreFoundation                      0x0000000103ff7016 CFRunLoopRunSpecific + 406
		17  GraphicsServices                    0x000000010a830a24 GSEventRunModal + 62
		18  UIKit                               0x00000001067490d4 UIApplicationMain + 159
		19  Runner                              0x000000010394cadf main + 111
		20  libdyld.dylib                       0x00000001091fa65d start + 1
	)
```

**Comment by mravn-google** [comment]
`[UIApplication sharedApplication].delegate.window.rootViewController` may be more obvious than casting the `messenger`.

**Comment by collinjackson** [comment]
@mravn-google yep, that's what I ended up doing. Thanks for the suggestion!

**Comment by AppleEducate** [comment]
`[UIApplication sharedApplication].delegate.window.rootViewController`
How do we do this in swift?

**Comment by AndreHaueisen** [comment]
In swift code

```
let viewController = UIApplication.shared.delegate!.window!!.rootViewController!
```
