### ISSUE TITLE
[Video Player] crash Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: Source error, null, null)

### ISSUE THREAD

**Issue by ayezarniaung** [flutter/flutter#99615]
#99615 

## Proposal

Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: Source error, null, null)

**Comment by maheshmnj** [comment]
Hi @ayezarniaung, Thanks for filing the issue. Please share minimal and complete sample code along with the complete output of `flutter run -v`.

Thanks

**Comment by ayezarniaung** [comment]
Solved!
