### ISSUE TITLE
HandshakeException: Connection terminated during handshake

### ISSUE THREAD

**Issue by yxlolxy** [flutter/flutter#99628]
it occurs when i run flutter doctor
## Steps to Reproduce
1. flutter --version
```
Flutter 2.10.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7e9793dee1 (4 days ago) • 2022-03-02 11:23:12 -0600
Engine • revision bd539267b4
Tools • Dart 2.16.1 • DevTools 2.9.2
```

2. flutter doctor -v
```
Flutter assets will be downloaded from https://storage.flutter-io.c. Make sure you trust this
source!
[✓] Flutter (Channel stable, 2.10.3, on Linux Mint 20.1 5.4.0-58-generic, locale zh_CN.UTF-8)
    • Flutter version 2.10.3 at /usr/soft/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (4 days ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.c

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /home/host/Android/Sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /usr/soft/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /usr/soft/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.63.2)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 97.0.4692.71

[☠] HTTP Host Availability (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful,
      please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ HandshakeException: Connection terminated during handshake
    • 

! Doctor found issues in 1 category.
```
is there other solutions except vpn?

**Comment by darshankawar** [comment]
@yxlolxy 
You seem to be accessing from China. Can you try to access it using a different network or provider and see if it helps?
The error seems to indicate a network related behavior.

**Comment by yxlolxy** [comment]
> @yxlolxy You seem to be accessing from China. Can you try to access it using a different network or provider and see if it helps? The error seems to indicate a network related behavior.

thanks a lot, I will try it in spare time

**Comment by guojunlong** [comment]
> > @yxlolxy You seem to be accessing from China. Can you try to access it using a different network or provider and see if it helps? The error seems to indicate a network related behavior.
> 
> thanks a lot, I did it with v2ray client at home. and i will try it again in spare time


Can you tell me exactly how you solved it? I have the same problem.

**Comment by yxlolxy** [comment]
It has been solved!
The reason is wrong environment variables. The value of FLUTTER_STORAGE_BASE_URL  is "https://storage.flutter-io.cn" and i lost the chracter "n" at the end, then i removed ${flutter_home}/bin/cache and executed "flutter doctor" again, and got the reuslt as follows:
`[!] HTTP Host Availability
    ✗ HTTP host https://maven.google.com/ is not reachable. Reason: An error
      occurred while checking the HTTP host: Operation timed out`
I tried the way descriped in [How is HTTP Host Availability in flutter 2.10?](https://stackoverflow.com/questions/71063780/how-is-http-host-availability-in-flutter-2-10), everything is OKAY  at last

**Comment by darshankawar** [comment]
Closing this as resolved.
