### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by rusahang** [flutter/flutter#99621]
`Facing this issue while running on android`

1. FAILURE: Build failed with an exception.

* What went wrong:
Could not open settings generic class cache for settings file '/Volumes/Macintosh Data/flutter_app/android/settings.gradle' (/Users/mymac/.gradle/caches/6.7/scripts/f0emg6u6oecmxqzgk5g9nn4ui).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 61

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
Exception: Gradle task assembleDebug failed with exit code 1

`2. My environment`
[✓] Flutter (Channel stable, 2.10.3, on Mac OS X 10.15.7 19H1715 darwin-x64,
    locale en-US)
    • Flutter version 2.10.3 at /Users/mymac/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (4 days ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at /Users/mymac/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at:
      /Library/Java/JavaVirtualMachines/jdk1.8.0_321.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_321-b07)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] Connected device (3 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 11
      (API 30) (emulator)
    • macOS (desktop)            • macos         • darwin-x64     • Mac OS X
      10.15.7 19H1715 darwin-x64
    • Chrome (web)               • chrome        • web-javascript • Google
      Chrome 99.0.4844.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by ryuujo1573** [comment]
> exception in phase 'semantic analysis' in source unit 'BuildScript' Unsupported class file major version 61
This is where and why exception occurred, for `61` appears strange.
Please check your build scripts.

**Comment by rusahang** [comment]
`it's occurred here`
`/flutter_app/android/settings.gradle' (/Users/mymac/.gradle/caches/6.7/scripts/f0emg6u6oecmxqzgk5g9nn4ui).`

java 17.0.2 2022-01-18 LTS
Java(TM) SE Runtime Environment (build 17.0.2+8-LTS-86)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.2+8-LTS-86, mixed mode, sharing)
limbu@Rusahangs-iMac ~ % gradle --version

------------------------------------------------------------
Gradle 7.4
------------------------------------------------------------

Build time:   2022-02-08 09:58:38 UTC
Revision:     f0d9291c04b90b59445041eaa75b2ee744162586

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.2 (Homebrew 17.0.2+0)
OS:           Mac OS X 10.15.7 x86_64`

**Comment by ryuujo1573** [comment]
What exactly lies there in `/flutter_app/android/settings.gradle`?
btw, you should quote using \` only if they're some codes or formulae stuffs.

**Comment by rusahang** [comment]
This is fresh code created from android studio. nothing error in` /settings.gradle.`

`include ':app'`
`def localPropertiesFile = new File(rootProject.projectDir, "local.properties")`
`def properties = new Properties()`
`assert localPropertiesFile.exists()`
`localPropertiesFile.withReader("UTF-8") { reader -> properties.load(reader) }
`
`def flutterSdkPath = properties.getProperty("flutter.sdk")`
`assert flutterSdkPath != null, "flutter.sdk not set in local.properties"`
`apply from: "$flutterSdkPath/packages/flutter_tools/gradle/app_plugin_loader.gradle"`

**Comment by ryuujo1573** [comment]
? 
Show me `settings.gradle` pls.

btw, learn to use ```

**Comment by rusahang** [comment]
[settings.gradle](https://github.com/flutter/flutter/issues/99621#issuecomment-1060115404)

**Comment by darshankawar** [comment]
@rusahang 
The error `BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 61` seems to be coming from gradle which doesn't seem to be compatible with jdk version you are using. Try to downgrade your jdk version to a version less than what you are using and see if it helps.

See this similar issue for your reference: https://stackoverflow.com/questions/66893535/why-my-flutter-app-dont-run-bug-exception-in-phase-semantic-analysis-in-sou

Closing from here, as this isn't a Flutter issue. If you disagree, write in comments and I'll reopen it.
