### ISSUE TITLE
TikTok icons from material don't work.

### ISSUE THREAD

**Issue by maykhid** [flutter/flutter#99637]
I am currently using Flutter version 2.10.0. I am unable to use any of the TikTok icons available e.g Icons.tiktok_outlined, Icons.tiktok etc. It's just blank and not visible.  I've done flutter clean, uninstalled the app, but still doesn't work. How do I resolve this?

**Comment by aquib1011** [comment]
For correct syntax use of the icon please refer to [this](https://api.flutter.dev/flutter/material/Icons/tiktok_outlined-constant.html).
`static const IconData tiktok_outlined = IconData(0xf0680, fontFamily: 'MaterialIcons');`

**Comment by danagbemava-nc** [comment]
Hi @maykhid, kindly upgrade to stable 2.10.3 and let me know whether or not this is still an issue for you. 

The icon renders as expected for me no 2.10.3. See screenshot below

<img src="https://user-images.githubusercontent.com/88313112/157004019-4c0b3cf6-0ba9-4088-b1ae-8434f69b3c40.png" width="300" />

**Comment by maykhid** [comment]
Thanks guys it works now.
