### ISSUE TITLE
Use of FadeTransitions causes slowdowns in the warm welcome screen.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#9964]
The FadeTransitions being used on the images on the welcome screen cause render target switches that cause slowdowns on older devices. To avoid such slowdowns, one of the follow workaround must be applied:

* Most of the images don't have their own view hierarchies, the fade can be applied directly in the fragment shader via a blend mode. This is the same workaround as the one applied by Hans on https://github.com/flutter/flutter/issues/9219.
* We can rely on Skia to analyze the picture and decide that since the image does not have a hierarchy, the opacity can be applied in the fragment shader instead of setting up a render target switch. I have followed up with the Skia team regarding this and this optimization is currently not in place. The estimate seemed to be that this could be implemented sometime later in 2017. I will follow up with actual tickets and stuff.
* The engine unrolls the picture and performs the analysis described above performs the optimization by rewriting the picture. Seems hacky but we could do it if given no other options.
* The welcome screen does seem to have some images that do contain hierarchies, so options 2 and 3 described above won't help. The suggestion there is to simply get rid of the fade transition.

![flutter_01](https://cloud.githubusercontent.com/assets/44085/25917746/fd4d4a1a-357d-11e7-9994-577d6b0780cb.png)

**Comment by eseidelGoogle** [comment]
FYI @lukef

**Comment by Hixie** [comment]
If this used Opacity (I'm guessing it did), then maybe the recent fixes resolved this. Might be worth checking again.

**Comment by jonahwilliams** [comment]
Given how old this issue is I'm going to guess its long since out of date
