### ISSUE TITLE
running app on win7 is not support?

### ISSUE THREAD

**Issue by baneyue** [flutter/flutter#99650]
how can i do?

![企业微信截图_16466158525378](https://user-images.githubusercontent.com/1902581/156954092-76356956-17a2-4551-85c7-d727b4a67e2f.png)

![企业微信截图_16466172269746](https://user-images.githubusercontent.com/1902581/156954137-27b0e344-f27c-41d2-85c4-318aa5a64964.png)

![50e4c47458928633605b77afce638038](https://user-images.githubusercontent.com/1902581/156954370-7c68e33b-93c5-482e-97ba-8084e70f140f.jpg)

**Comment by stuartmorgan** [comment]
Flutter itself does not statically reference that method. You'll need to contact the author of whatever plugin you are using that calls it unconditionally to request Windows 7 support.

**Comment by baneyue** [comment]
![image](https://user-images.githubusercontent.com/1902581/156975972-b5144d27-4907-4041-ab68-33865b4de0d7.png)
 @stuartmorgan   thks

**Comment by stuartmorgan** [comment]
That's a dynamic lookup, not a static reference, so shouldn't cause the error you are seeing. I would suggest checking any other Windows plugins you are using.
