### ISSUE TITLE
Flutter web release not working with dhttpd package

### ISSUE THREAD

**Issue by MuhmdHsn313** [flutter/flutter#99668]
Hello There

I completed the development of a flutter app and started build this app with `flutter build web`, after that I try run by `dhttpd` using `dart pub global run dhttpd --path build/web/` or `flutter pub global run dhttpd --path build/web/`, when I open chrome and paste link, the app not working, and throwing 304 status code in cmd, and throw an errors in console.

When entering website
![Screenshot 2022-03-07 121241](https://user-images.githubusercontent.com/33749659/157001750-64c22858-05cd-4f21-b544-29408473ffb1.png)

Console of browser
![Screenshot 2022-03-07 121303](https://user-images.githubusercontent.com/33749659/157001980-676fbe23-ed9a-4418-989d-65c3ee6c1ad2.png)

Thanks...

**Comment by exaby73** [comment]
Hey. Could you include an example repo here?

**Comment by maheshmnj** [comment]
Hi @MuhmdHsn313, Thanks for filing the issue [dhttpd](https://pub.dev/packages/dhttpd) is a third party (not developed by flutter team) plugin. So issues regarding such plugins must be filed in their respective repository.

dhttpd repository: https://github.com/kevmoo/dhttpd

Closing as this is not an issue with flutter, in case you disagree feel free to write in the comments and we will reopen it.

Thank you.
