### ISSUE TITLE
how add a static function in extension

### ISSUE THREAD

**Issue by butterflyXX** [flutter/flutter#99667]
how add a static function in extension:
For example,
`
extension Test on String {
  static test() {

  }
}
`
I canot use the function 'test' : String.test is not be supported

**Comment by MerdanDev** [comment]
> I canot use the function 'test' : String.test is not be supported

For your case I suggest you to use getter, for example:
```dart
extension L12n on String {
  String get trs {
    String? result = AppLocalizations(null).translate(this);
    result ??= AppLocalizations.templocalizedStrings[this];
    return result ?? this;
  }
}

// and use case

print('some_key_for_translate'.trs);
```

**Comment by danagbemava-nc** [comment]
Hi @butterflyXX, the flutter issue tracker is for reporting issues or feature requests with flutter. 

Kindly visit any of the communities in  https://flutter.dev/community#community-grid for asking these types of questions. 

Closing as this is neither a bug report nor a feature request.

**Comment by butterflyXX** [comment]
@MerdanDev I wish call the function with the class of String , For example:
`String.test()` , Is not `"string Instance".test()`
