### ISSUE TITLE
[go_router] Support return data from a screen with pop()

### ISSUE THREAD

**Issue by dangngocduc** [flutter/flutter#99663]
## Use case

With Navigator, we can push to new screen and await result.
```
    final result = await Navigator.push(
      context,
      // Create the SelectionScreen in the next step.
      MaterialPageRoute(builder: (context) => const SelectionScreen()),
    );
   
```
Currently _go_router_ is support _push_, _go_ but it return void.  
```
  /// Navigate to a URI location w/ optional query parameters, e.g.
  /// `/family/f2/person/p1?color=blue`
  void go(String location, {Object? extra}) =>
      routerDelegate.go(location, extra: extra);
```

```
  /// Push a URI location onto the page stack w/ optional query parameters, e.g.
  /// `/family/f2/person/p1?color=blue`
  void push(String location, {Object? extra}) =>
      routerDelegate.push(location, extra: extra);
```

Expected Behaviour: push, go support return a Future<T> and user can call pop with a result.

This is sample for this feature:

https://docs.flutter.dev/cookbook/navigation/returning-data

**Comment by MrOnyszko** [comment]
Hi there!

I strongly subscribe to this idea. In my opinion, it is a desirable use case. I tried to figure it out how it could be done in [this commit ](https://github.com/MrOnyszko/packages/commit/2d345a710afdcbbbd708b78676715b3ed6b1a009)

The other similar use case is to support deep pop with result data. For example, we can navigate from Screen A to Screen B to Screen C, and we want to pop to Screen A with the result.

**Comment by rodgav** [comment]
> Hi there!
> 
> I strongly subscribe to this idea. In my opinion, it is a desirable use case. I tried to figure it out how it could be done in [this commit ](https://github.com/MrOnyszko/packages/commit/2d345a710afdcbbbd708b78676715b3ed6b1a009)
> 
> The other similar use case is to support deep pop with result data. For example, we can navigate from Screen A to Screen B to Screen C, and we want to pop to Screen A with the result.
cool, how can i use this?

**Comment by chenenyu** [comment]
👍

**Comment by ssyzh** [comment]
> Hi there!
> 
> I strongly subscribe to this idea. In my opinion, it is a desirable use case. I tried to figure it out how it could be done in [this commit ](https://github.com/MrOnyszko/packages/commit/2d345a710afdcbbbd708b78676715b3ed6b1a009)
> 
> The other similar use case is to support deep pop with result data. For example, we can navigate from Screen A to Screen B to Screen C, and we want to pop to Screen A with the result.

so cool, I need it!!!!

**Comment by m7mdra** [comment]
incase anyone...

you can add it with following

```yaml
  go_router:
    git:
      url: git@github.com:MrOnyszko/packages.git
      ref: pop_with_result
      path: packages/go_router
```

**Comment by m7mdra** [comment]
According to documentation its ok use gorouter in combination with navigator apis, it will only affect browsers... other platforms are ok i guess.

> You can feel free to use GoRouter and Navigator together like this. However, one thing that using Navigator.push in this way will not do is update the browser's address bar. If you want that, you'll need to use GoRouter.go or GoRouter.push.

 
[soure](https://gorouter.dev/user-input#navigator-style)

**Comment by tomassasovsky** [comment]
@MrOnyszko that's awesome! Have you opened a PR yet?

**Comment by NazarenoCavazzon** [comment]
I opened a PR for this.
https://github.com/flutter/packages/pull/2416

**Comment by giallon** [comment]
Awesome 😎

**Comment by magnocasmor** [comment]
Any updates?

**Comment by booooohdan** [comment]
I'll wait for this feature. Thanks 🙏

**Comment by NazarenoCavazzon** [comment]
> I'll wait for this feature. Thanks 🙏

I made a package until implementation. They're still defining architecture, so no expectations for near updates.

https://pub.dev/packages/go_router_flow

**Comment by hm-tamim** [comment]
Any update on this?

**Comment by jari-kuipers** [comment]
I'd also like to express my interest in this. Right now we're using `Navigator.push()` for those pages that need it but we'd love to make the full switch to go_router.

**Comment by NazarenoCavazzon** [comment]
@jari-kuipers if you want to make the switch to go_router and be able to return values on pop you can use the fork of go_router I made with the feature implemented, it's called go_router_flow, we're currently using it in production in my company and it's updated to the last version of go_router

**Comment by Katekko** [comment]
> go_router_flow

Using this for now, thanks for the fork

**Comment by abdulrojakdev** [comment]
Any update on this?

**Comment by daksh-gargas** [comment]
IDK why the dev didn't add this provision in the first place.
Shame!

**Comment by kamami** [comment]
Any news?

**Comment by jari-kuipers** [comment]
@kamami Look at the linked, closed MR. We have to wait on #99112 for this feature to be reconsidered.

**Comment by Katekko** [comment]
If you are using the base routes only from go_router, you can use the normal Navigator from flutter. It's not necessary use the the pop from go_router, you can use Navigator.of(context).pop(true) from flutter

**Comment by Brandon-Wolff** [comment]
A workaround I've used for this is to pass a `VoidCallback` into the `extra` parameter, and then call that function from the second screen when you `pop()`

**Comment by NazarenoCavazzon** [comment]
Nasty

**Comment by 8thgencore** [comment]
@NazarenoCavazzon When to add the latest changes from go_router to go_router_flow?

**Comment by omar-hanafy** [comment]
Any updates 🥲

**Comment by chunhtai** [comment]
I already add way to pass result to pop when i refactor pop. I think what is missing is the push does not return the future.

**Comment by ceokin** [comment]
will there be a new version with this last PR solving this issue?

**Comment by NazarenoCavazzon** [comment]
@ceokin https://github.com/flutter/packages/pull/3368

**Comment by martppa** [comment]
@booooohdan PR checks are failing. I am using go_router_flow in the meantime.

**Comment by leonidlist** [comment]
Same here, using go_router_flow until go_router has that

**Comment by tsquillario** [comment]
What's the status on this? Is GoRouter still under development?

**Comment by tiendunghk** [comment]
waiting

**Comment by bahadirarslan** [comment]
I am using 6.2.0 and if I am not wrong I can return value with pop method.
Here is the source of pop

```dart
 /// Pop the top-most route off the current screen.
  ///
  /// If the top-most route is a pop up or dialog, this method pops it instead
  /// of any GoRoute under it.
  void pop<T extends Object?>([T? result]) {
    assert(() {
      log.info('popping $location');
      return true;
    }());
    _routerDelegate.pop<T>(result);
  }
```

**Comment by martppa** [comment]
> I am using 6.2.0 and if I am not wrong I can return value with pop method. Here is the source of pop
> 
> ```dart
>  /// Pop the top-most route off the current screen.
>   ///
>   /// If the top-most route is a pop up or dialog, this method pops it instead
>   /// of any GoRoute under it.
>   void pop<T extends Object?>([T? result]) {
>     assert(() {
>       log.info('popping $location');
>       return true;
>     }());
>     _routerDelegate.pop<T>(result);
>   }
> ```

Yes, thats correct, but you still cannot await for result when using goRouter `push` method.
