### ISSUE TITLE
Error while building Flutter APK for android-arm only

### ISSUE THREAD

**Issue by OutdatedGuy** [flutter/flutter#99674]
I got into this problem since last month. 
- I can build APK for android-arm64, android-x86 or all of them combined.
- It can even create an android-arm apk with the command `flutter build apk --split-per-abi`
- But it cannot build apk specifically for android-arm alone.

## Thing I have tried
- I tried changing gradle versions to 6.7-all, 7.3.1-bin and 7.2-bin
- I tried removing flutter folder and reinstalling it all

## Steps to Reproduce

1. Execute `flutter build apk --target-platform android-arm --analyze-size` 

**Expected results:** 
APK built for android-arm architecture

**Actual results:** 
```

 Building with sound null safety 

Dart snapshot generator failed with exit code -2147483645


FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1102

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.      

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 54s
Running Gradle task 'assembleRelease'...                          295.9s
Gradle task assembleRelease failed with exit code 1
```

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

The verbose output is exceeding github issue max character limit.
Link to the verbose output file is [here](https://drive.google.com/file/d/12SDGa6ILZsVS3zTZmJxA-vUnmLW5sV_e/view?usp=sharing)
```
```

```
Analyzing auxpert_app...                                                
No issues found! (ran in 14.1s)
```

```
[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.22000.527], locale en-IN)
    • Flutter version 2.10.3 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (5 days ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\Dell\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.0.32126.317
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.65.0)
    • VS Code at C:\Users\Dell\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.36.0

[√] Connected device (4 available)
    • COR AL00 (mobile) • RFS3Y18827024871 • android-arm64  • Android 9 (API 28)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.22000.527]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 98.0.4758.102
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 99.0.1150.30

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

[verbose_output.txt](https://github.com/flutter/flutter/files/8197780/verbose_output.txt)

**Comment by danagbemava-nc** [comment]
Hi @OutdatedGuy, do you have this issue with the counter app? 

If you do, please provide the complete output of `flutter build apk --target-platform android-arm --analyze-size -v`. The output is likely to be huge, so kindly put it into a .txt file and attach it here. 

If it doesn't reproduce with the counter app, kindly provide your `pubspec.yaml`, `android/build.gradle`, `android/app/build.gradle` as well as the verbose logs of `flutter build apk --target-platform android-arm --analyze-size -v`

Thank you

**Comment by OutdatedGuy** [comment]
Yo @danagbemava-nc , YES I have this issue with the counter app too.

Here is the output for the command you gave: [counter_app_build_verbose.txt](https://github.com/flutter/flutter/files/8198382/counter_app_build_verbose.txt)

More to add:
- There was no issue a month ago
- It likely started after I downloaded the stable windows flutter version(i.e. 2.10.0)

**Comment by danagbemava-nc** [comment]
There's a similar issue reported in #97764. 

Kindly follow up there for updates. 

Closing from here as duplicate. 

Thank you
