### ISSUE TITLE
[flutter_lints] No lint rule for a GestureDetector without handlers

### ISSUE THREAD

**Issue by navaronbracke** [flutter/flutter#99686]
## Use case

Given the following Widget
```
GestureDetector(child: const SizedBox(width: 100, height: 100))
```
there is no analysis warning about the GestureDetector not doing anything.

## Proposal

Add a new lint rule for a `GestureDetector` without any onXXX properties set.
Similar to the lint for a redundant `Container`.

**Comment by maheshmnj** [comment]
Hi @navaronbracke, Thanks for filing the issue that looks like a valid feature request.  
Wrapping a GestureDetector around any widget without any parameters should show a linter warning.

e.g  
```dart
GestureDetector(
     child: Container(child: SizedBox()),
 ),
```

**Comment by goderbauer** [comment]
Looks like this is a request for a new lint rule. Can you please file this request over in the linter repository (https://github.com/dart-lang/linter)? Once it exists, we can consider whether it should be added to the recommended set.
