### ISSUE TITLE
In App Purchases not working on API level under 28 with Error: The item you requested is not available for purchase.

### ISSUE THREAD

**Issue by cuzyoucant** [flutter/flutter#99684]
## Steps to Reproduce

1. Setup Google Play Console for you App and Subscription/Non-consumable and release on Closed Testing.
2. Init PurchaseStream with `final Stream purchaseUpdated = InAppPurchase.instance.purchaseStream;
    log("IAP sream opend");
    _appStoreSubscription = purchaseUpdated.listen((purchaseDetailsList) {};`
3. Query GooglePlatProductDetails with `final ProductDetailsResponse response =
        await InAppPurchase.instance.queryProductDetails(_kIds);`
4. Try to purchase the aboved queried GooglePlatProductDetails. 

**Expected results:** 
Expect to get GooglePlayPurchaseDetails object in purchaseUpdated stream.

**Actual results:** 
Error: The item you requested is not available for purchase.

The only relevant info the plugin is printing is this:
`W[/ProxyBillingActivity]()( 5038): Activity finished with resultCode 0 and billing's responseCode: 4
W[/BillingHelper]()( 5038): Couldn't find purchase lists, trying to find single data.
W[/BillingHelper]()( 5038): Received a bad purchase data.
W[/BillingHelper]()( 5038): Couldn't find single purchase data as well.`

## Extra Info
I tested it with API levels 25,26,28,30,32 with real and emulated devices.
Works like expected on evey API level 28+.

Tested with in_app_purchase: ^3.0.1 and ^3.0.0.

Relevant build.gradle settings:
`        minSdkVersion 21
        targetSdkVersion 31`

I am quite confident my Google Play Console settings are correct because it worked right away with higher API levels.

If anyone has any infos/tipps on how i could get this to work, or why it doesnt work would be very much appreciated.

**Comment by darshankawar** [comment]
@cuzyoucant 
Please check [this](https://github.com/flutter/flutter/issues/35741) similar issue and underlying comments which has solutions and see if it helps in your case.

**Comment by cuzyoucant** [comment]
@darshankawar
I already saw that issue and sadly it is not related.

**Comment by darshankawar** [comment]
Thank for the update. There doesn't seem to be any changes related to IAP plugin to work above and below API 28, so ideally it should work.
Can you take a look at [this](https://medium.com/swlh/some-things-we-learned-while-implementing-in-app-purchase-in-android-9e70c22addf0) article and see if it helps ?

**Comment by cuzyoucant** [comment]
I took at a look a the article and it didn't directly help, but it gave me an idea.
The devices it wasn't working on where old phones from my coworker where i added my Google Play Account which is entered as a licence tester.

The thing was his account still was the original Google Play Account which wasn't a Licence Tester.
After i removed his accounts from the device it worked!

Thank you very much for your help!
