### ISSUE TITLE
Rendering flutter into texture using Metal

### ISSUE THREAD

**Issue by dubik** [flutter/flutter#99685]
## Steps to Reproduce

1. I have an app that has rendering loop and I want to embed flutter
2. I don't want Flutter to use its thread, so I replaced it with my task queue (same queue for rendering and platform tasks)
3. I call basically 2 functions: `FlutterEngineInitialize` and `FlutterEngineRunInitialized`
4. I modified OpenGL app, and it seems to work the way I want
5. However with Metal app, it doesn't render anything. I can see that Flutter calls back my task queue, and schedules some tasks, but never asks for a texture and never calls present. Any idea what Flutter engine needs in order to start requesting texture and rendering into it? May be some input events. There are no errors returned.

**Comment by darshankawar** [comment]
@dubik 
Can you provide `flutter doctor -v`, a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with actual vs expected results ?

Thanks.

**Comment by dubik** [comment]
while I was working on a standalone project, I noticed that Flutter may need `FlutterEngineSendWindowMetricsEvent` to create surface, and indeed, after I called that function, it started calling `get_next_drawable`.  It still complains `Could not create the SkSurface from the metal texture.` but I think I can progress now. Thanks.
