### ISSUE TITLE
[ci.yaml] Clobber caches when changing dependencies

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#99694]
I attempted to write a devicelab benchmark which needs to build windows applications. I've found that it will easily pass on presubmit but continually fails on postsubmit. Are we missing some tags/depenendencies here?

Attempted Fix: https://github.com/flutter/flutter/pull/99602
Original PR: https://github.com/flutter/flutter/pull/99564

**Comment by CaseyHillers** [comment]
As a temporary fix: Add `clobber: "true`` to the targets properties.

The test likely hit a warm cache and used old dependencies. I'll use this to track an automated way of passing `clobber: true` when dependencies are changed

**Comment by keyonghan** [comment]
This may not be a problem anymore with cache versioning based on dependencies.

**Comment by CaseyHillers** [comment]
This is still an issue, we'd need something like CreateBuild RPC instead of ScheduleBuild to override the swarming caches from the scheduler (crbug.com/1114804)

**Comment by godofredoc** [comment]
Pub dependencies are not cached anymore. Closing as completed.
