### ISSUE TITLE
Cannot initialize TextFormField with initialValue (property marked final)

### ISSUE THREAD

**Issue by gibsonsyd** [flutter/flutter#9969]
When creating a new TextFormField there is no way to specify the initial value in the constructor. 

How are we supposed to set the initial value of a textFormField in a Form?

[See FormField.initialValue](https://docs.flutter.io/flutter/widgets/FormField/initialValue.html)

**Comment by eseidelGoogle** [comment]
The value is maintained by the TextEditingController.  TextFields (like some other widgets, like Animation) have a Stateful component, for maintaining presentation state (like what text is entered but not committed, where the cursor is, etc.)  TextEditingController is that state object.

TextEditingController can be created with an initial value, there is even a helper contructor for that case:
https://docs.flutter.io/flutter/widgets/TextEditingController/TextEditingController.fromValue.html

When you move from having the FormField auto-create its own TextEditingController to creating one yourself, you need to make sure to hold the TextEditingController off of some object which has an appropriate lifetime for that text state.  Typically this is a parent StatefulWidget's State, but it can even be higher up or static depending on what behavior you want to have when navigating away from that scene of widgets and back again, etc.

**Comment by gibsonsyd** [comment]
Thanks, I was not aware of this.

**Comment by mishubham** [comment]
can we place our database value in initialvalue in textformfield in flutter

**Comment by CubeRoshan** [comment]
@mishubham did you find any solution?

**Comment by fahjan** [comment]
```
final TextEditingController _textFieldController = TextEditingController();
  @override
  void initState() {
    _textFieldController.text = "4444";
    super.initState();
  }
```

**Comment by errorsolve** [comment]
[Take a look on How to Supply an Initial value to TextField Widget in Flutter?
](https://fluttercorner.com/how-to-supply-an-initial-value-to-textfield-widget-in-flutter/)
