### ISSUE TITLE
[macOS] Unable to type text into native textView with IME after destroying Flutter window.

### ISSUE THREAD

**Issue by GetToSet** [flutter/flutter#99695]
## Steps to Reproduce

1. Construct an app with a `NSWindow` containing a `FlutterViewController` which has `releasedWhenClosed` set to `YES` and another contains native `NSTextView`.
2. Close the flutter window.
3. Switch back to the native window, typing with an IME(e.g Chinese input method)

https://user-images.githubusercontent.com/8158163/157072209-7d3a4a18-3571-4d27-a50e-7bab7ac27ea8.mov

**Expected results:**
Characters typed into the native textView.

**Actual results:** 
Unable to type. IME window resides on the lower left corner of the screen.

<details>
<summary>Code sample</summary>

```swift
import AppKit
import FlutterMacOS

class MainFlutterWindow: NSWindow {
    
    override func awakeFromNib() {
        let flutterViewController = FlutterViewController.init()
        let windowFrame = self.frame
        self.contentViewController = flutterViewController
        self.setFrame(windowFrame, display: true)
        self.isReleasedWhenClosed = true

        RegisterGeneratedPlugins(registry: flutterViewController)

        super.awakeFromNib()
    }
    
}
```
</details>

**Comment by HansMuller** [comment]
CC @cbracken @weiyu
