### ISSUE TITLE
Allow iOS simulator runtimes to be set from .ci.yaml

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#99698]
It's now possible to run different tests with different iOS runtimes https://github.com/flutter/flutter/issues/91689.  Expose this as a settable property in `.ci.yaml`.
This is needed before the engine builders can migrate to Xcode 13. https://github.com/flutter/flutter/issues/94078

**Comment by yusuf-goog** [comment]
https://flutter-review.googlesource.com/c/infra/+/27742  adds getting "runtime_versions" property value from ci.yaml into osx_sdk property in recipes.

**Comment by jmagman** [comment]
So I tried this in https://github.com/flutter/engine/pull/31915 and it doesn't seem to be pulling in both runtimes.
.ci.yaml:
```
      runtime_versions: >-
        [
          "ios-13",
          "ios-15"
        ]
```

But I don't see the expected `install xcode runtime ios-13-0`, `Removing stale iOS 13.0.simruntime`, `Moving ios-13-0 to final dest` steps (see led run https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/magder_google.com/15ce71ff15e962e13bb340538339f307495e846c6eba7ec007621015430e011f/+/build.proto for example).

And the `list simulators` step only shows iOS 15:
```
== Runtimes ==
iOS 15.0 (15.0 - 19A339) - com.apple.CoreSimulator.SimRuntime.iOS-15-0
== Devices ==
-- iOS 15.0 --
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8820208992595983441/+/u/list_simulators/stdout

**Comment by yusuf-goog** [comment]
https://github.com/flutter/cocoon/pull/1652 adds the functionality for presubmit.

**Comment by yusuf-goog** [comment]
Builds are now picking up the properties as expected.
