### ISSUE TITLE
Engine doesn't always resume after the app has been paused

### ISSUE THREAD

**Issue by vlidholt** [flutter/flutter#997]
This often happens in the game. To reproduce:

Start the game, pause it by hitting the home button, resume it by navigating back into the app. Screen often remains black when returning to the game or sometimes the ui is frozen.

**Comment by Hixie** [comment]
I noticed that Engine::OnAppLifecycleStateChanged doesn't call ScheduleFrame(), which is suspicious, but when viktor tried putting an ensureVisualUpdate() call in the corresponding dart code (which I think should be equivalent), it didn't help the problem.

**Comment by sethladd** [comment]
Confirmed this behavior with a toy app at home. Ran `flutter apk`, then `adb install build/app.apk`. The app runs, but if it backgrounds, and I try to bring it back, I just got a black screen.

**Comment by eseidelGoogle** [comment]
I've seen this in other apps I've built.  This is clearly a show-stopper.

**Comment by eseidelGoogle** [comment]
@abarth is gonna look.

**Comment by sethladd** [comment]
Thanks!
