### ISSUE TITLE
flutter/plugins unable to run Firebase Test Lab tests

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#99703]
The flutter/plugin tree is currently closed because trying to re-run a post-submit flake is giving the following error on FTL tests:

```
ERROR: Unable to execute "gcloud auth activate-service-account --key-file=/root/gcloud-service-key.json". Stderr:
Unable to activate gcloud account.
```

I'm seeing the same on presubmit tests on PRs.

Presumably a key expired or changed, and the plugins repository was not updated.

**Comment by CaseyHillers** [comment]
Related to https://github.com/flutter/flutter/issues/99283

Our oncall docs did not make it clear this needed to be updated. Let me take a look and update the keys for this

**Comment by CaseyHillers** [comment]
@stuartmorgan I pinged you with an internal doc we need to follow. I lack admin access to the plugins repo

**Comment by stuartmorgan** [comment]
I'm not an admin for the plugins repository either.
