### ISSUE TITLE
Do not require the Xcode version to be appended to `osx_sdk` cache name in .ci.yaml

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#99702]
To work around https://github.com/flutter/flutter/issues/99429, the `osx_sdk` cache was renamed to `osx_sdk_13a233`.  However that means there are two spots to update the Xcode version which need to stay in sync.  Can the different `osx_sdk` cache names instead be enforced on the recipe side? Or if the Xcode version and `osx_sdk` now need to stay in sync, can they be combined?

**Comment by CaseyHillers** [comment]
As an FYI, I'm drafting a one pager to have the ci.yaml logic generate the caches based on the passed dependencies.

I'll update this issue once that's complete (ETA end of today)

**Comment by CaseyHillers** [comment]
I wrote go/automatic-swarming-caches to address this. It's open to RFC internally before sending the few CLs to enable it.

**Comment by godofredoc** [comment]
@CaseyHillers is this complete?
