### ISSUE TITLE
Log links do not work for LUCI windows bots

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#99713]
e.g. on https://ci.chromium.org/ui/p/flutter/builders/staging/Windows%20windows_home_scroll_perf__timeline_summary/43/overview, clicking any of the log links leads to an error page. It looks like it's trying to mix Windows and Unix style path separators...?

@CaseyHillers @keyonghan @godofredoc fyi

**Comment by CaseyHillers** [comment]
To clarify, it's literally `log links` section. Example link:

https://storage.googleapis.com/flutter_logs/flutter/a491a81f78739dc1c801529b98239adc6a2dd361/windows_home_scroll_perf__timeline_summary/4fe0ab0d-5c2c-4ceb-9caf-644c68ca1756/C:%5Cb%5Cs%5Cw%5Cir%5Cx%5Cw%5Crecipe_cleanup%5Cflutter_logs_dir%5Cflutter_driver_commands_0.log

**Comment by keyonghan** [comment]
Fix is in: https://flutter-review.googlesource.com/c/recipes/+/31960
