### ISSUE TITLE
Painting sample is janky due to slow resolution of images used in the scene graph.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#9972]
The painting sample in the Posse gallery is janky but the performance overlays indicate that neither the rasterizer not the engine is particularly busy (see attached screenshot). The scene contains extremely large images that must be read, decompressed and uploaded to the GPU. Now, the async image decode and texture upload is in effect. But since the frame needs the images to be ready, there is a stall while waiting on those the GPU uploads to finish (and the DecodeImage future to be resolved). For extremely large images, the application ought to show placeholder or spinners till the images are ready.

In the attached traces, I have marked a particularly expensive frame on the engine. That is caused by the `unzLocateFile` in the FLX. I am working on removing that so the frame producer should not be stalled.

![flutter_04](https://cloud.githubusercontent.com/assets/44085/25921474/65e43294-358a-11e7-9bd9-d95b1282b88d.png)

![screen shot 2017-05-10 at 1 03 21 pm](https://cloud.githubusercontent.com/assets/44085/25921487/717998d8-358a-11e7-9e98-9d78beec1771.png)

**Comment by sethladd** [comment]
Thanks!

@lukef can you confirm that the app is using correctly-sized assets? Maybe the asset is simply too big for our needs.

**Comment by lukef** [comment]
They are too big. We're reducing and will retest.

**Comment by sethladd** [comment]
Great, thanks!

**Comment by eseidelGoogle** [comment]
@chinmaygarde is there more action to take now that we've made the images small?

**Comment by eseidelGoogle** [comment]
Maybe there is a bug about how the Framework should have warned the user?

**Comment by eseidelGoogle** [comment]
@Hixie do you believe we can close this?  Or should we keep this open (and maybe remove customer:posse) for some related work?

**Comment by Hixie** [comment]
I think it's fine to close. I'm not sure how the framework would know if it's a bad case or a good case.
