### ISSUE TITLE
Is there an app or system where flutter team can work together ?

### ISSUE THREAD

**Issue by misterdiallo** [flutter/flutter#99733]
I'm looking for an online solution where my team and I,  can upload, edit, build and test our flutter projects all together at the same time. We don't want only versioning, like GitHub.
Is there any existing solution ?

**Comment by darshankawar** [comment]
@misterdiallo 
This repo isn't the correct place to ask this question. Please use flutter [community](https://flutter.dev/community) link that has different platforms to ask such questions.
Closing from here.
