### ISSUE TITLE
[tool_crash] StateError: Bad state: No element while running `flutter debug-adapter`

### ISSUE THREAD

**Issue by Mouftakir99** [flutter/flutter#99734]
Command
```
flutter debug-adapter
```

Steps to Reproduce
1. ...
2. ...
3. ...

Logs
StateError: Bad state: No element
```
%230      ListMixin.firstWhere (dart:collection/list.dart:167:5)
%231      PacketTransformer._parseHeaders (package:dds/src/dap/protocol_stream_transformers.dart:94:17)
%232      PacketTransformer.bind.<anonymous closure>.<anonymous closure> (package:dds/src/dap/protocol_stream_transformers.dart:40:25)
%233      _rootRunUnary (dart:async/zone.dart:1434:47)
%234      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
%235      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
%236      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
%237      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
%238      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
%239      _ExpandStream._handleData (dart:async/stream_pipe.dart:233:14)
%2310     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
%2311     _rootRunUnary (dart:async/zone.dart:1434:47)
%2312     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
%2313     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
%2314     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
%2315     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
%2316     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
%2317     _StreamController._add (dart:async/stream_controller.dart:648:7)
%2318     _StreamController.add (dart:async/stream_controller.dart:596:5)
%2319     _Socket._onData (dart:io-patch/socket_patch.dart:2314:41)
%2320     _rootRunUnary (dart:async/zone.dart:1442:13)
%2321     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
%2322     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
%2323     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
%2324     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
```
```
[✓] Flutter (Channel stable, 2.10.3, on Microsoft Windows [version 10.0.19044.1526], locale fr-CA)
    • Flutter version 2.10.3 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (5 days ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✗] Android toolchain - develop for Android devices
    • Android SDK at C:\Users\HP Probook\AppData\Local\Android\sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools
```

**Comment by darshankawar** [comment]
Labeling it based on the crash log.

/cc @christopherfujino

**Comment by christopherfujino** [comment]
cc @DanTup

**Comment by DanTup** [comment]
@Mouftakir99 can you describe how you encountered this? Did you trigger this from an editor, or are you running the command manually? If you're running it manually, can you describe what you were trying to do?

The command is intended to be used by tools that must communicate using the [debug adapter protocol](https://microsoft.github.io/debug-adapter-protocol/). It shouldn't fail in this way if you send it input that doesn't conform to the spec, though the fix for that will likely be to emit a clear error message. I'm not sure if that will solve your issue without understanding how you triggered this.

**Comment by Mouftakir99** [comment]
Thank u for responding my message i resolve the problem    Envoyé à partir de Courrier pour Windows De : Danny TuppenyEnvoyé le :8 mars 2022 19:26À : flutter/flutterCc : Mouftakir Aiman; MentionObjet :Re: [flutter/flutter] [tool_crash] StateError: Bad state: No element while running `flutter debug-adapter` (Issue ***@***.*** can you describe how you encountered this? Did you trigger this from an editor, or are you running the command manually? If you're running it manually, can you describe what you were trying to do?The command is intended to be used by tools that must communicate using the debug adapter protocol. It shouldn't fail in this way if you send it input that doesn't conform to the spec, though the fix for that will likely be to emit a clear error message. I'm not sure if that will solve your issue without understanding how you triggered this.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
