### ISSUE TITLE
Autocomplete does not dismiss overlay on selection

### ISSUE THREAD

**Issue by StraussPorcupine** [flutter/flutter#99749]
The bug happens when you use autocomplete, and the user fills in the same value as  what is recommended and the user clicks on the recommended value, if it is the same as the filled value, it will not dismiss the overlay.

## Steps to Reproduce

This bug is on any Autocomplete widget
Even on the Api.flutter.dev
1. Go to https://api.flutter.dev/flutter/material/Autocomplete-class.html
2. Run the first example.
3. in the input field type in 'aardvark'
4. click on the recommended answer that is the same

**Expected results:** 
The expected result is the overlay to dismiss.

**Actual results:** 
Overlay stays, and nothing happens, the material splash happens, but it does not close the overlay.

**Comment by maheshmnj** [comment]
Hi @StraussPorcupine, Thanks for filing the issue. I am able to reproduce the issue on stable and the master channel. Basically, this issue occurs if the AutoCompleteField contains exactly one of the options in the list then the options cannot be submitted.


<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const AutocompleteExampleApp());

class AutocompleteExampleApp extends StatelessWidget {
  const AutocompleteExampleApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Autocomplete Basic'),
        ),
        body: const Center(
          child: AutocompleteBasicExample(),
        ),
      ),
    );
  }
}

class AutocompleteBasicExample extends StatelessWidget {
  const AutocompleteBasicExample({Key? key}) : super(key: key);

  static const List<String> _kOptions = <String>[
    'aardvark',
    'bobcat',
    'chameleon',
  ];

  @override
  Widget build(BuildContext context) {
    return Autocomplete<String>(
      optionsBuilder: (TextEditingValue textEditingValue) {
        if (textEditingValue.text == '') {
          return const Iterable<String>.empty();
        }
        return _kOptions.where((String option) {
          return option.contains(textEditingValue.text.toLowerCase());
        });
      },
      onSelected: (String selection) {
        debugPrint('You just selected $selection');
      },
    );
  }
}

```
</details>
