### ISSUE TITLE
Showing import error while add localisation in flutter

### ISSUE THREAD

**Issue by Harsh1052** [flutter/flutter#99741]
## Steps to Reproduce

1. I Implemented Localisation in app
2. Run flutter clean && flutter pub get
3. add localisation strings in app.

My l10n.yaml file:

```
 arb-dir: lib/l10n
 template-arb-file: intl_en.arb
 output-localization-file: app_localizations.dart
```

## Logs

<details>
<summary>analysis</summary>

```
lib/main.dart:88:20: Warning: Operand of null-aware operation '!' has type 'AppLocalizations' which excludes null.
 - 'AppLocalizations' is from 'package:flutter_gen/gen_l10n/app_localizations.dart' ('.dart_tool/flutter_gen/gen_l10n/app_localizations.dart').
                  .of(context)!.appName),
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @Harsh1052, please provide the output of `flutter doctor -v` as well as your `main.dart`. 

Thank you

**Comment by Harsh1052** [comment]
<summary>
Flutter (Channel stable, 2.10.2, on macOS 11.6.2 20G314 darwin-x64, locale en-GB)
    • Flutter version 2.10.2 at /Users/mac/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (2 weeks ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode copy.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] Connected device (2 available)
    • RMX3241 (mobile) • HYBAE6IFQG5TYHJZ • android-arm64  • Android 11 (API 30)
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 99.0.4844.51
    ! Error: iPhone (2) is not connected. Xcode will continue when iPhone (2) is connected. (code -13)
    ! Error: Tag iPhone 8 is not connected. Xcode will continue when Tag iPhone 8 is connected. (code -13)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
</summary>

main.dart

```
import 'package:fluro/fluro.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:mohit_wellness/bloc/localization/locale_cubit.dart';
import 'package:mohit_wellness/routes/application.dart';
import 'package:mohit_wellness/routes/routes.dart';
import 'package:mohit_wellness/screens/auth_screen/auth_option_screen.dart';
import 'package:mohit_wellness/screens/on_boarding_screens/introductory_screen.dart';
import 'package:mohit_wellness/theme/theme.dart';
import 'package:responsive_framework/responsive_wrapper.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';
import 'l10n/l10n.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  State createState() {
    return _MyAppState();
  }

}

class _MyAppState extends State<MyApp> {
  _MyAppState() {
    final router = FluroRouter();
    Routes.configureRoutes(router);
    Application.router = router;
  }

  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (_) => LocaleCubit(),
      child: BlocBuilder<LocaleCubit, LocaleState>(
        builder: (context, state) {
          return MaterialApp(
            title: 'Mohit Wellness',
            theme: ThemesData.setTheme(),
            builder: (context, widget) =>
                ResponsiveWrapper.builder(
                  widget,
                  maxWidth: 1200,
                  minWidth: 390,
                  defaultScale: true,
                  breakpoints: [
                    const ResponsiveBreakpoint.resize(480, name: MOBILE),
                    const ResponsiveBreakpoint.autoScale(800, name: TABLET),
                    const ResponsiveBreakpoint.resize(1000, name: DESKTOP),
                  ],
                ),
            localizationsDelegates: const [
              AppLocalizations.delegate,
              GlobalMaterialLocalizations.delegate,
              GlobalWidgetsLocalizations.delegate,
              GlobalCupertinoLocalizations.delegate,
            ],
            locale: state.locale,
            supportedLocales: L10n.all,
            debugShowCheckedModeBanner: false,
            home:const AuthOptionScreen(),
          );
        },
      ),
    );
  }
}

class Screen extends StatelessWidget {
  const Screen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
appBar: AppBar(
  title: Text("Dummy Text"),
),
        body: Center(
      child: BlocBuilder<LocaleCubit, LocaleState>(
        builder: (context, state) {
          return Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Text(AppLocalizations
                  .of(context)!.appName),
              ElevatedButton(onPressed: () {
                context.read<LocaleCubit>().setLocale(const Locale('gu'));
                Navigator.of(context).push(MaterialPageRoute(builder: (context)=>IntroductionScreen()));
              }, child: Text("Changes language"))
            ],
          );
        },
      ),
    ));
  }
}


```

**Comment by Harsh1052** [comment]
intl_en.arb 
```
{
  "@@locale": "en",
  "appName": "Mohit Wellness",
  "skip": "Skip",
  "login": "Login",
  "next": "Next",
  "signup": "Sign Up",
  "loginAsGuest": "Login As Guest",
  "doNotHaveAccount": "Don’t have account?",
  "alreadyHaveAccount": "Already have account?",
  "signIn": "Sign In",
  "signUpTo": "Sign Up to",
  "fullName": "Full Name",
  "mobileNo": "Mobile No.",
  "email": "Email",
  "emailAddress": "Email Address",
  "dateOfBirth": "Date of Birth",
  "dateFormat": "DD/MM/YYYY",
  "address": "Address",
  "verificationFor": "Verification for",
  "yourAccount": "Your Account",
  "weHaveSentAOTPCodeToYourMobileNumber": "We have sent a OTP code to your mobile number",
  "welcomeTo": "Welcome to",
  "trackYourHealthWithUs": "Track your Health with Us",
  "verify": "Verify",
  "doNotReceiveOTP": "Don’t Receive OTP?",
  "resendOTP": "Resend OTP"
}
```

**Comment by Harsh1052** [comment]
I need to close and reopen my project to import file properly.

**Comment by danagbemava-nc** [comment]
@Harsh1052, what IDE are you experiencing this issue with?

**Comment by Harsh1052** [comment]
Android Studio ( Bubblebee ) and visual code (1.65.1) in both

**Comment by danagbemava-nc** [comment]
Hi @Harsh1052, can you send a screenshot of the import error?

**Comment by Harsh1052** [comment]
Sorry for delay
Error screen shot:
![image](https://user-images.githubusercontent.com/72139154/158101892-22d42466-89b0-41e5-9d33-992cf1cdc3e1.png)

**Comment by danagbemava-nc** [comment]
Hi @Harsh1052, can you try following the localization guide in https://docs.flutter.dev/development/accessibility-and-localization/internationalization and instead of using 
`template-arb-file: intl_en.arb` use `template-arb-file: app_en.arb`? 

I want to know if that makes any difference for you

**Comment by Harsh1052** [comment]
Still facing issues after run flutter pub get command
![image](https://user-images.githubusercontent.com/72139154/159421873-98d33397-4ca0-411f-b5ec-527a1aa0604b.png)

**Comment by danagbemava-nc** [comment]
Hmm, can you try running `flutter gen-l10n` to see if it helps?

**Comment by Harsh1052** [comment]
run `flutter gen-l10n` not working still showing import error.

**Comment by danagbemava-nc** [comment]
Hi @Harsh1052, kindly also share the rest of your `.arb` files.
