### ISSUE TITLE
open and Work on multiple Windows same time

### ISSUE THREAD

**Issue by abdulrehmananwar** [flutter/flutter#99754]
i want to open multiple windows just like chrome and windows form application. where we can open multiple windows from same application at the same time we can minimize or maximize these tabs.

**Comment by maheshmnj** [comment]
Hi @abdulrehmananwar, Thanks for filing the issue. I believe you are referring to opening Multiple Desktop windows of a flutter app? if so that is already being tracked here  https://github.com/flutter/flutter/issues/30701
