### ISSUE TITLE
Built IOS app for App Store, blocked by apple only for apple silicon iPad Pro. 

### ISSUE THREAD

**Issue by jbardu** [flutter/flutter#99750]
## Steps to Reproduce

1. Build an app and submit to App Store, and it is not compatible with iPad Pro m1

**Expected results:**

It should be compatible with any iPhone or iPad with latest IOS ?

**Actual results:** 

App Store and test flight gives message that the application is not compatible with device, but only for owners of iPad Pro current gen M1 based chip.

<details>
<summary>Code sample</summary>

I cannot create a minimal version reproducible as this requires submission
to App Store, approval and hardware. It works in the iPad Pro m1 sim.

```dart
```

</details>

<details>
  <summary>Logs</summary>

There is no error message in flutter.

```
```

```
Analyzing flutter_application_1...                                      

   info • The value of the local variable 'appName' isn't used • lib/map_page.dart:301:12 • unused_local_variable
   info • The value of the local variable 'packageName' isn't used • lib/map_page.dart:302:12 • unused_local_variable
   info • The value of the local variable 's' isn't used • lib/scope_widget.dart:415:14 • unused_local_variable
   info • The value of the local variable 's' isn't used • lib/scope_widget.dart:453:14 • unused_local_variable
   info • Avoid empty statements • lib/settings_page.dart:225:5 • empty_statements
   info • Prefer const with constant constructors • lib/settings_page.dart:262:23 • prefer_const_constructors
   info • The value of the field '_animation' isn't used • lib/skyview_page.dart:827:27 • unused_field
   info • Dead code • lib/skyview_page.dart:866:16 • dead_code
   info • The value of the local variable 'x1' isn't used • lib/skyview_page.dart:949:12 • unused_local_variable
   info • The value of the local variable 'x2' isn't used • lib/skyview_page.dart:951:12 • unused_local_variable
   info • Prefer const with constant constructors • lib/skyview_page.dart:955:19 • prefer_const_constructors
   info • Unused import: 'matrix.dart' • lib/splashscreen.dart:5:8 • unused_import
   info • Private field could be final • lib/splashscreen.dart:46:8 • prefer_final_fields
   info • Private field could be final • lib/splashscreen.dart:47:8 • prefer_final_fields
   info • The declaration '_decreaseDuration' isn't referenced • lib/splashscreen.dart:279:8 • unused_element
   info • The declaration '_increaseDuration' isn't referenced • lib/splashscreen.dart:287:8 • unused_element
   info • Avoid single cascade in expression statements • lib/splashscreen.dart:296:5 •
          avoid_single_cascade_in_expression_statements
   info • The value of the local variable 'lightPaint' isn't used • lib/splashscreen.dart:355:11 •
          unused_local_variable
   info • The value of the local variable 'darkPaint' isn't used • lib/splashscreen.dart:356:11 • unused_local_variable
   info • The value of the local variable 'xx' isn't used • lib/splashscreen.dart:370:11 • unused_local_variable
   info • The value of the local variable 'yy' isn't used • lib/splashscreen.dart:371:11 • unused_local_variable
   info • The declaration '_drawMiddleBeam' isn't referenced • lib/splashscreen.dart:468:8 • unused_element
   info • The declaration '_flipMiddleBeamWhenInTheMiddle' isn't referenced • lib/splashscreen.dart:511:8 •
          unused_element
   info • The declaration '_rotateMiddleBeamAroundAxis' isn't referenced • lib/splashscreen.dart:520:8 • unused_element
   info • The declaration '_drawTopBeam' isn't referenced • lib/splashscreen.dart:526:8 • unused_element
   info • The declaration '_drawBottomDarkBeam' isn't referenced • lib/splashscreen.dart:554:8 • unused_element
   info • The declaration '_getTriangleGradient' isn't referenced • lib/splashscreen.dart:584:15 • unused_element

27 issues found. (ran in 3.4s)
```

```
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.2.1 21D62 darwin-arm, locale en-AU)
    • Flutter version 2.10.3 at /Users/justin/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (6 days ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/justin/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Users/justin/Downloads/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/justin/Downloads/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 99.0.4844.51
    ! Error: Jiphone is not connected. Xcode will continue when Jiphone is connected. (code -13)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

![IMG_0557](https://user-images.githubusercontent.com/1498560/157218667-b6c2f8ce-6064-4b8b-9e0e-cf6160b712d2.JPG)

There are a lot of things I could attach or include from Xcode
need guidance on what is helpful to see to diagnose the issue.

There were no settings inside App Store connect that can exclude one specific iPad variant, iPad Pro m1, from distribution, or are there? 

thanks.

**Comment by maheshmnj** [comment]
Hi @jbardu, Thanks for filing the issue. Labeling this issue for further investigation from the team.

cc: @jmagman

**Comment by jmagman** [comment]
I know in Discord you said it worked on an iPad Pro 5th generation.  Were you able to install the app locally on a physical M1 iPad Pro?

**Comment by jbardu** [comment]
I have no way to do that as I don't have access to one. The user I know with one, that can try things, takes 3 days to turnaround a request - like please try this TestFlight.

If he gives me his device identifier I can build him one, and he can try to install it outside TestFlight or App Store?

**Comment by jmagman** [comment]
@cyanglaz I think you have the new iPad Pro, can you validate that a newly `flutter create`d app can run and launch on it?

**Comment by jmagman** [comment]
@jbardu is it the one already shipped to the App Store? https://apps.apple.com/us/app/satellitemap-space/id1598264303
On my 3rd gen iPad Pro I also see it's `Not compatible with this device`

**Comment by jbardu** [comment]
Here is what Xcode thinks info.plist has been set from default. Device capabilities etc etc. I have not tried extending the build to OSX/M1 .. that I *could* check. Maybe. 

<img width="728" alt="Screen Shot 2022-03-09 at 11 28 14 am" src="https://user-images.githubusercontent.com/1498560/157349162-931c3b52-bdc4-49b5-8ec3-fa96b490199e.png">

@jmagman well that one was built in December but yes. I'd only had two reports of iPad Pro incompatibility so ASSumed it was only for M1 chip because that's what they noted to me.

I'll dust off an old iPad - that I do have - connect physically and see how I go.

**Comment by jbardu** [comment]
Oh I guess the answer is right there staring at me.
No GPS support in ANY wifi only iPad.. Which is described as required.
It isn't actually required for some functionality. So I can remove that.

Would be SO helpful if TestFlight  / App Store gave the reason for the block. Like: "This app requires GPS which your device does not have".

**Comment by jmagman** [comment]
<img width="842" alt="Screen Shot 2022-03-08 at 4 39 54 PM" src="https://user-images.githubusercontent.com/682784/157350166-e1dc2108-93eb-4771-bca2-598dcd8e3bd6.png">

Yeah, I agree the App Store UI was very unhelpful too, it didn't mention it was because of GPS.

Going to close this since you would have had this issue without Flutter, and we can't really do anything about the unhelpful TestFlight/App Store UI.
