### ISSUE TITLE
[web] main.dart.js critical issue

### ISSUE THREAD

**Issue by harsh-savvient** [flutter/flutter#99758]
We have developed website using the flutter. It contains video player. When i am loading page then it's getting stuck and displaying following error in loop:

NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

Please help me to fix the issue.

**Comment by danagbemava-nc** [comment]
Hi @harsh-savvient, thanks for reporting this. 

Please provide a complete minimal reproducible code sample as well as steps to reproduce so that we may verify this issue. 

Please also provide the output of `flutter doctor -v` and any other logs that may be relevant. 

Thank you
