### ISSUE TITLE
Mockito mock generation throws missing library exception flutter/plugins/webview_flutter

### ISSUE THREAD

**Issue by m-skolnick** [flutter/flutter#99766]
I am attempting to prepare a PR into plugins/webview_flutter. Mock generation is not working, so I am unable to add tests for my changes.

## Steps to Reproduce

1. clone [flutter/plugins ](https://github.com/flutter/plugins.git)
2. cd packages/webview_flutter/webview_flutter_android 
3. flutter pub get 
4. flutter pub run build_runner build --delete-conflicting-outputs --verbose 

**Expected results:** Mocks should generate successfully

**Actual results:** Error is thrown and mockito generator loops endlessly

<details>
  <summary>

    > flutter pub run build_runner build --delete-conflicting-outputs --verbose
    [ +112 ms] executing: sysctl hw.optional.arm64
    [  +24 ms] Exit code 1 from: sysctl hw.optional.arm64
    [        ] sysctl: unknown oid 'hw.optional.arm64'
    [   +7 ms] executing: [/Users/micaiah.skolnick/fvm/versions/stable/] git -c log.showSignature=false log -n 1 --pretty=format:%H
    [  +21 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
    [        ] 097d3313d8e2c7f901932d63e537c1acefb87800
    [        ] executing: [/Users/micaiah.skolnick/fvm/versions/stable/] git tag --points-at 097d3313d8e2c7f901932d63e537c1acefb87800
    [ +129 ms] Exit code 0 from: git tag --points-at 097d3313d8e2c7f901932d63e537c1acefb87800
    [        ] 2.10.2
    [   +9 ms] executing: [/Users/micaiah.skolnick/fvm/versions/stable/] git rev-parse --abbrev-ref --symbolic @{u}
    [  +19 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
    [        ] origin/stable
    [        ] executing: [/Users/micaiah.skolnick/fvm/versions/stable/] git ls-remote --get-url origin
    [  +16 ms] Exit code 0 from: git ls-remote --get-url origin
    [        ] https://github.com/flutter/flutter.git
    [ +120 ms] executing: [/Users/micaiah.skolnick/fvm/versions/stable/] git rev-parse --abbrev-ref HEAD
    [  +20 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
    [        ] stable
    [   +8 ms] executing: sw_vers -productName
    [  +18 ms] Exit code 0 from: sw_vers -productName
    [        ] macOS
    [        ] executing: sw_vers -productVersion
    [  +23 ms] Exit code 0 from: sw_vers -productVersion
    [   +1 ms] 12.0.1
    [        ] executing: sw_vers -buildVersion
    [  +20 ms] Exit code 0 from: sw_vers -buildVersion
    [        ] 21A559
    [  +77 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
    [   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
    [  +62 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
    [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
    [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
    [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
    [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
    [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
    [  +94 ms] executing: /Users/micaiah.skolnick/fvm/versions/stable/bin/cache/dart-sdk/bin/dart __deprecated_pub run build_runner build --delete-conflicting-outputs --verbose
    [INFO] Entrypoint:Generating build script...
    [INFO] Entrypoint:Generating build script completed, took 570ms
    
    [WARNING] Bootstrap:
    Invalidated precompiled build script due to missing asset graph.
    [INFO] Bootstrap:Precompiling build script......
    [INFO] Bootstrap:Precompiling build script... completed, took 1.2s
    
    [INFO] BuildDefinition:Initializing inputs
    [INFO] BuildDefinition:Building new asset graph...
    [INFO] BuildDefinition:Building new asset graph completed, took 759ms
    
    [INFO] BuildDefinition:Checking for unexpected pre-existing outputs....
    [INFO] BuildDefinition:Checking for unexpected pre-existing outputs. completed, took 1ms
    
    [INFO] Build:Running build...
    [INFO] Heartbeat:1.0s elapsed, 0/16 actions completed.
    [INFO] Heartbeat:2.1s elapsed, 1/17 actions completed.
    [INFO] Heartbeat:3.2s elapsed, 1/17 actions completed.
    [INFO] Heartbeat:4.2s elapsed, 1/17 actions completed.
    [INFO] Heartbeat:5.3s elapsed, 3/19 actions completed.
    [INFO] Heartbeat:7.1s elapsed, 3/19 actions completed.
    [INFO] Heartbeat:8.5s elapsed, 4/19 actions completed.
    [SEVERE] mockito:mockBuilder on test/instance_manager_test.dart:
    
    Invalid argument(s): Missing library: package:webview_flutter_android/src/android_webview.pigeon.dart
    Available libraries: [dart:typed_data, dart:convert, dart:math, dart:core, dart:_internal, dart:collection, dart:async, dart:isolate, dart:developer, dart:ffi, dart:_js_embedded_names, dart:_js_names, dart:_recipe_syntax, dart:_rti, dart:_foreign_helper, dart:_js_helper, dart:_interceptors, dart:_native_typed_data, dart:web_gl, dart:js_util, dart:_metadata, dart:html_common, dart:indexed_db, dart:svg, dart:web_audio, dart:html, dart:io, dart:_http, dart:js, dart:_js, dart:mirrors, dart:nativewrappers, dart:cli, dart:_late_helper, dart:_dart2js_runtime_metrics, dart:_js_primitives, dart:_async_await_error_codes, dart:_js_annotations, dart:_spirv, dart:ui]
    #0      LinkedElementFactory.createLibraryElementForReading (package:analyzer/src/summary2/linked_element_factory.dart:74:7)
    #1      LinkedElementFactory.elementOfReference (package:analyzer/src/summary2/linked_element_factory.dart:128:14)
    #2      LinkedElementFactory.libraryOfUri (package:analyzer/src/summary2/linked_element_factory.dart:177:12)
    #3      ElementBuilder._selectLibrary (package:analyzer/src/summary2/element_builder.dart:1018:37)
    #4      ElementBuilder.visitImportDirective (package:analyzer/src/summary2/element_builder.dart:598:31)
    #5      ImportDirectiveImpl.accept (package:analyzer/src/dart/ast/ast.dart:5953:50)
    #6      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7758:20)
    #7      ElementBuilder.buildLibraryElementChildren (package:analyzer/src/summary2/element_builder.dart:60:21)
    #8      LibraryBuilder.buildElements (package:analyzer/src/summary2/library_builder.dart:109:24)
    #9      Linker._computeLibraryScopes (package:analyzer/src/summary2/link.dart:109:15)
    #10     Linker._buildOutlines (package:analyzer/src/summary2/link.dart:88:5)
    #11     Linker.link (package:analyzer/src/summary2/link.dart:74:5)
    #12     link (package:analyzer/src/summary2/link.dart:33:10)
    #13     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:176:30)
    #14     LibraryContext.load2.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:206:7)
    #15     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
    #16     LibraryContext.load2 (package:analyzer/src/dart/analysis/library_context.dart:204:12)
    #17     AnalysisDriver._computeUnitElement.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1574:22)
    #18     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
    #19     AnalysisDriver._computeUnitElement (package:analyzer/src/dart/analysis/driver.dart:1572:20)
    #20     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1126:35)
    #21     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2140:24)
    <asynchronous suspension>
    
    
    package:analyzer/src/dart/analysis/library_context.dart 267:5     LibraryContext._throwLibraryCycleLinkException
    package:analyzer/src/dart/analysis/library_context.dart 181:11    LibraryContext.load2.loadBundle
    package:analyzer/src/dart/analysis/library_context.dart 206:7     LibraryContext.load2.<fn>
    package:analyzer/src/dart/analysis/performance_logger.dart 32:15  PerformanceLog.run
    package:analyzer/src/dart/analysis/library_context.dart 204:12    LibraryContext.load2
    package:analyzer/src/dart/analysis/driver.dart 1574:22            AnalysisDriver._computeUnitElement.<fn>
    package:analyzer/src/dart/analysis/performance_logger.dart 32:15  PerformanceLog.run
    package:analyzer/src/dart/analysis/driver.dart 1572:20            AnalysisDriver._computeUnitElement
    package:analyzer/src/dart/analysis/driver.dart 1126:35            AnalysisDriver.performWork
    package:analyzer/src/dart/analysis/driver.dart 2140:24            AnalysisDriverScheduler._run
    
    [INFO] Heartbeat:12.1s elapsed, 5/19 actions completed.
    [INFO] Heartbeat:13.1s elapsed, 5/19 actions completed.
    [INFO] Heartbeat:14.2s elapsed, 5/19 actions completed.
    [INFO] Heartbeat:15.3s elapsed, 5/19 actions completed.
    [INFO] Heartbeat:16.4s elapsed, 5/19 actions completed.
    [INFO] Heartbeat:17.4s elapsed, 5/19 actions completed.
    [INFO] Heartbeat:18.4s elapsed, 5/19 actions completed.
    [INFO] Heartbeat:19.5s elapsed, 5/19 actions completed.
    [INFO] Heartbeat:20.6s elapsed, 5/19 actions completed.
    [INFO] Heartbeat:21.7s elapsed, 5/19 actions completed.
    [INFO] Heartbeat:22.7s elapsed, 5/19 actions completed.
    [INFO] Heartbeat:23.8s elapsed, 5/19 actions completed.
    [INFO] Heartbeat:24.9s elapsed, 5/19 actions completed.
    ^C</summary>

```
> flutter analyze
Running "flutter pub get" in webview_flutter_android...          1,622ms
Analyzing webview_flutter_android...                            
No issues found! (ran in 6.3s)
```

```
> flutter doctor -v
[✓] Flutter (Channel stable, 2.10.2, on macOS 12.2.1 21D62 darwin-x64, locale en-US)
    • Flutter version 2.10.2 at /Users/micaiah.skolnick/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (3 weeks ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/micaiah.skolnick/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/micaiah.skolnick/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.65.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • SAMSUNG SM G930A (mobile) • b7a04742 • android-arm64  • Android 7.0 (API 24)
    • Chrome (web)              • chrome   • web-javascript • Google Chrome 99.0.4844.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report. Using steps to replicate and running on both latest versions, I do see the same error in the console while running the said command:

<details>
<summary> error log snippet </summary>

```

Invalid argument(s): Missing library: package:webview_flutter_android/src/android_webview.pigeon.dart
Available libraries: [dart:typed_data, dart:convert, dart:math, dart:core, dart:_internal, dart:collection, dart:async, dart:isolate, dart:developer, dart:ffi, dart:_js_embedded_names, dart:_js_names, dart:_recipe_syntax, dart:_rti, dart:_foreign_helper, dart:_js_helper, dart:_interceptors, dart:_native_typed_data, dart:web_gl, dart:js_util, dart:_metadata, dart:html_common, dart:indexed_db, dart:svg, dart:web_audio, dart:html, dart:io, dart:_http, dart:js, dart:_js, dart:mirrors, dart:nativewrappers, dart:cli, dart:_late_helper, dart:_dart2js_runtime_metrics, dart:_js_primitives, dart:_async_await_error_codes, dart:_js_annotations, dart:_spirv, dart:ui]
#0      LinkedElementFactory.createLibraryElementForReading (package:analyzer/src/summary2/linked_element_factory.dart:74:7)
#1      LinkedElementFactory.elementOfReference (package:analyzer/src/summary2/linked_element_factory.dart:128:14)
#2      LinkedElementFactory.libraryOfUri (package:analyzer/src/summary2/linked_element_factory.dart:177:12)
#3      ElementBuilder._selectLibrary (package:analyzer/src/summary2/element_builder.dart:1018:37)
#4      ElementBuilder.visitImportDirective (package:analyzer/src/summary2/element_builder.dart:598:31)
#5      ImportDirectiveImpl.accept (package:analyzer/src/dart/ast/ast.dart:5953:50)
#6      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7758:20)
#7      ElementBuilder.buildLibraryElementChildren (package:analyzer/src/summary2/element_builder.dart:60:21)
#8      LibraryBuilder.buildElements (package:analyzer/src/summary2/library_builder.dart:109:24)
#9      Linker._computeLibraryScopes (package:analyzer/src/summary2/link.dart:109:15)
#10     Linker._buildOutlines (package:analyzer/src/summary2/link.dart:88:5)
#11     Linker.link (package:analyzer/src/summary2/link.dart:74:5)
#12     link (package:analyzer/src/summary2/link.dart:33:10)
#13     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:176:30)
#14     SetMixin.forEach (dart:collection/set.dart:142:30)
#15     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:113:32)
#16     LibraryContext.load2.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:206:7)
#17     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#18     LibraryContext.load2 (package:analyzer/src/dart/analysis/library_context.dart:204:12)
#19     AnalysisDriver._computeUnitElement.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1574:22)
#20     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#21     AnalysisDriver._computeUnitElement (package:analyzer/src/dart/analysis/driver.dart:1572:20)
#22     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1126:35)
#23     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2140:24)
<asynchronous suspension>


package:analyzer/src/dart/analysis/library_context.dart 267:5     LibraryContext._throwLibraryCycleLinkException
package:analyzer/src/dart/analysis/library_context.dart 181:11    LibraryContext.load2.loadBundle
dart:collection                                                   SetMixin.forEach
package:analyzer/src/dart/analysis/library_context.dart 113:32    LibraryContext.load2.loadBundle
package:analyzer/src/dart/analysis/library_context.dart 206:7     LibraryContext.load2.<fn>
package:analyzer/src/dart/analysis/performance_logger.dart 32:15  PerformanceLog.run
package:analyzer/src/dart/analysis/library_context.dart 204:12    LibraryContext.load2
package:analyzer/src/dart/analysis/driver.dart 1574:22            AnalysisDriver._computeUnitElement.<fn>
package:analyzer/src/dart/analysis/performance_logger.dart 32:15  PerformanceLog.run
package:analyzer/src/dart/analysis/driver.dart 1572:20            AnalysisDriver._computeUnitElement
package:analyzer/src/dart/analysis/driver.dart 1126:35            AnalysisDriver.performWork
package:analyzer/src/dart/analysis/driver.dart 2140:24            AnalysisDriverScheduler._run

```
</details>

<details>
<summary> stable, master flutter doctor -v </summary>

```

[✓] Flutter (Channel stable, 2.10.3, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 2.10.3 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (11 hours ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.


[✓] Flutter (Channel master, 2.11.0-0.0.pre.831, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 2.11.0-0.0.pre.831 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3172065fba (3 hours ago), 2022-03-08 19:35:20 -0600
    • Engine revision 5c760759fe
    • Dart version 2.17.0 (build 2.17.0-182.0.dev)
    • DevTools version 2.11.1

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.


```

</details>

**Comment by stuartmorgan** [comment]
Assigning to @bparrishMines per discussion.
