### ISSUE TITLE
Linux tool_integration_tests_1_4 flakes on `gradle_non_android_plugin_test`

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#99767]
(part of https://github.com/flutter/flutter/issues/97036)

1 gradle_non_android_plugin_test.dart flake ([3454](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20tool_integration_tests_1_4/3454/overview))

```
12:19 +63 -1: test/integration.shard/gradle_non_android_plugin_test.dart: Flutter app that depends on a non-Android plugin can still build for Android [E]                                             
  Expected: a file system entity that exists
    Actual: LocalFile:<LocalFile: '/b/s/w/ir/x/t/flutter_flutter_plugin_test.ESHTVW/ios_only/example/build/app/outputs/apk/release/app-release.apk'>
     Which: does not exist
  
  package:test_api                                                 expect
  test/integration.shard/gradle_non_android_plugin_test.dart 92:5  main.<fn>
  dart:async                                                       runZoned
  test/src/common.dart 197:14                                      testWithoutContext.<fn>
  test/src/common.dart 196:18                                      testWithoutContext.<fn>
  test/src/common.dart 166:18                                      test.<fn>
  test/src/common.dart 161:5     
```

**Comment by christopherfujino** [comment]
Here we're not even checking the exit code of the `flutter build` command: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/integration.shard/gradle_non_android_plugin_test.dart#LL71C1-L80C1

We should do an expectation something like:

`expect(result.exitCode, 0, reason: 'stdout: ${result.stdout}\nstderr: ${result.stderr}');`

**Comment by christopherfujino** [comment]
I think it would make sense to write a helper function in https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/integration.shard/test_utils.dart

**Comment by eliasyishak** [comment]
> I think it would make sense to write a helper function in https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/integration.shard/test_utils.dart

Captured in issue:
- https://github.com/flutter/flutter/issues/127135

**Comment by eliasyishak** [comment]
Closing this issue to let the new process result matcher help debug future flakes if still occuring
