### ISSUE TITLE
Flutter tool unable to update on Windows

### ISSUE THREAD

**Issue by alibix** [flutter/flutter#9976]
## Steps to Reproduce

I installed git and flutter onto my windows 10 computer. I followed the tutorial and entered the command:

flutter doctor

Then it looks like it tries to update the flutter tool but it fails every time and then tries to update again in an infinite loop of updating and failing.

## Flutter Doctor
PS C:\WINDOWS\system32> flutter doctor
Updating flutter tool...
%1 is not a valid Win32 application.

  Command: C:\Users\[username]\flutter\bin\cache\dart-sdk\lib\_internal\pub\asset\7zip\7za.exe e data.tar.gz
Unhandled exception:
Could not import "package:flutter_tools/executable.dart" from "file:///C:/Users/[username]/flutter/packages/flut
ter_tools/bin/flutter_tools.dart": Packages file 'file:///C:/Users/[username]/flutter/packages/flutter_tools/.pa
ckages' not found.
null
Updating flutter tool...
%1 is not a valid Win32 application.

  Command: C:\Users\[username]\flutter\bin\cache\dart-sdk\lib\_internal\pub\asset\7zip\7za.exe e data.tar.gz
Unhandled exception:
Could not import "package:flutter_tools/executable.dart" from "file:///C:/Users/[username]/flutter/packages/flut
ter_tools/bin/flutter_tools.dart": Packages file 'file:///C:/Users/[username]/flutter/packages/flutter_tools/.pa
ckages' not found.
null
Updating flutter tool...
%1 is not a valid Win32 application.

This just keeps going on forever. What am I doing wrong?

**Comment by eseidelGoogle** [comment]
@goderbauer would know.

**Comment by goderbauer** [comment]
Can you delete the `cache` directory under `flutter/bin` and try the `flutter doctor` command again? I am suspecting that the dart-sdk in the `cache` directory got corrupted. Deleting `cache` will re-download it.

**Comment by alibix** [comment]
@goderbauer the same issue arises

**Comment by goderbauer** [comment]
That's unfortunate. In that case, we need more logging. Can you replace your version of `flutter/bin/flutter.bat` with this: https://github.com/goderbauer/flutter/blob/578c6196e327d434189834d77cc5ec59f49d92a2/bin/flutter.bat

Then delete `cache` in `flutter/bin` and run `flutter doctor` again. What does it say now?

Also, can you execute the following two commands in your PowerShell window and tell me what they return? Thanks

```ps
[Environment]::Is64BitProcess
[environment]::Is64BitOperatingSystem
```

**Comment by alibix** [comment]
@goderbauer it now says this:

Checking Dart SDK version...
Downloading Dart SDK 1.23.0-dev.11.11...
Unzipping Dart SDK...
Updating flutter tool...
%1 is not a valid Win32 application.

  Command: C:\Users\[username]\flutter\bin\cache\dart-sdk\lib\_internal\pub\asset\7zip\7za.exe e data.tar.gz
Error: Unable to 'pub upgrade' flutter tool. Retrying...

Waiting for 0 seconds, press CTRL+C to quit ...
%1 is not a valid Win32 application.

  Command: C:\Users\[username]\flutter\bin\cache\dart-sdk\lib\_internal\pub\asset\7zip\7za.exe e data.tar.gz
Error: Unable to 'pub upgrade' flutter tool. Retrying...

Waiting for 0 seconds, press CTRL+C to quit ...
%1 is not a valid Win32 application.

  Command: C:\Users\[username]\flutter\bin\cache\dart-sdk\lib\_internal\pub\asset\7zip\7za.exe e data.tar.gz
Error: Unable to 'pub upgrade' flutter tool. Retrying...

and goes on an on like before.

When I use those two commands in the power shell window it gives me:

True
True

**Comment by goderbauer** [comment]
Looks like it is a problem with pub. Just to verify, where are you running `flutter doctor`? In PowerShell? Or somewhere else?

**Comment by goderbauer** [comment]
Are you sure that there is not a slash between `lib` and `_internal` in the error message?

What happens if you execute the command `C:\Users\[username]\flutter\bin\cache\dart-sdk\lib\_internal\pub\asset\7zip\7za.exe` directly?

**Comment by Hixie** [comment]
I added backticks to the previous message which shows that there is a backslash before the `_`.

**Comment by alibix** [comment]
What do you mean by executing the command directly? I'm using PowerShell. I tried going to that path and running 7za.exe directly - nothing happens except a window flashing open for a second and closing again.

I tried putting that directory into the Powershell and it asked me for a program to open it with

**Comment by goderbauer** [comment]
I'm suspecting that `7za.exe` within the dart SDK somehow got corrupted. If you send me the hash of that file I can compare it with mine to verify. You can get that value by executing the following in PoweShell 4 (or newer):

`Get-Filehash -path C:\Users\[username]\flutter\bin\cache\dart-sdk\lib\_internal\pub\asset\7zip\7za.exe -algorithm SHA512 | fl`

**Comment by jerrytk** [comment]
I am experiencing the same problem.  
Running `7za.exe` directly says:
```
7za.exe : The term '7za.exe' is not recognized as the name of a cmdlet, function, script file, or operable progra
m. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ 7za.exe
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (7za.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException


Suggestion [3,General]: The command 7za.exe was not found, but does exist in the current location. Windows PowerShell does not load commands from the current location by default. If you trust this command, instead type: ".\7za.exe". See "get-help about_Command_Precedence" for more details.
```

Hash:
```
Algorithm : SHA512
Hash      : 6BC519A7368EE6BD8C8F69F2D634DD18799B4CA31FBC284D2580BA625F3A88B6A52D2BC17BEA0E75E63CA11C10356C47EE00C
            2C500294ABCB5141424FC5DC71C
Path      : C:\devel\flutter\bin\cache\dart-sdk\lib\_internal\pub\asset\7zip\7za.exe
```

**Comment by jerrytk** [comment]
OK, so in my case the problem was caused by restrictive firewall which denied outgoing connection for `pub upgrade`. This command just silently failed without complaining about being unable to download anything. After adding firewall rule everything works fine.

**Comment by goderbauer** [comment]
@alibix Do you have a firewall that might be restricting pub's access to the internet as @jerrytk?

**Comment by alibix** [comment]
@goderbauer 

I think I found the issue. My flutter folder had a path with spaces in it. The [username] in the paths I typed here had space in it as it was a full name. Cloning flutter into a different path with no spaces made it work:

`Checking Dart SDK version...
Downloading Dart SDK 1.23.0-dev.11.11...
Unzipping Dart SDK...
Updating flutter tool...

  ╔════════════════════════════════════════════════════════════════════════════╗
  ║                 Welcome to Flutter! - https://flutter.io                   ║
  ║                                                                            ║
  ║ The Flutter tool anonymously reports feature usage statistics and crash    ║
  ║ reports to Google in order to help Google contribute improvements to       ║
  ║ Flutter over time.                                                         ║
  ║                                                                            ║
  ║ Read about data we send with crash reports:                                ║
  ║ https://github.com/flutter/flutter/wiki/Flutter-CLI-crash-reporting        ║
  ║                                                                            ║
  ║ See Google's privacy policy:                                               ║
  ║ https://www.google.com/intl/en/policies/privacy/                           ║
  ║                                                                            ║
  ║ Use "flutter config --no-analytics" to disable analytics and crash         ║
  ║ reporting.                                                                 ║
  ╚════════════════════════════════════════════════════════════════════════════╝

Downloading Material fonts...                         1.7s
Downloading package sky_engine...                     2.6s
Downloading windows-x64 tools...                      1.5s
Downloading android-arm-profile/windows-x64 tools...  1.8s
Downloading android-arm-release/windows-x64 tools...  2.4s
Downloading android-x86 tools...                      3.0s
Downloading android-x64 tools...                      5.9s
Downloading android-arm tools...                      1.6s
Downloading android-arm-profile tools...              4.0s
Downloading android-arm-release tools...              1.6s
[√] Flutter (on Microsoft Windows [Version 10.0.15063], channel alpha)
    • Flutter at C:\flutter
    • Framework revision dc4ca8db83 (19 hours ago), 2017-05-11 15:33:29 -0700
    • Engine revision f99d3ef108
    • Tools Dart version 1.23.0-dev.11.11

[√] Android toolchain - develop for Android devices (Android SDK 25.0.1)
    • Android SDK at C:\Users\[username]\AppData\Local\Android\sdk
    • Platform android-25, build-tools 25.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)


Oops; flutter has exited unexpectedly.
Crash report written to C:\Users\[username]\flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.`

**Comment by alibix** [comment]
The same problem might be arising now again with this crash log:

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

ProcessException: ProcessException: %1 is not a valid Win32 application.

  Command: C:\Users\[username]\AppData\Local\Android\sdk\platform-tools\adb.EXE devices -l

```
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:447)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:595)
#2      Process.runSync (dart:io-patch/process_patch.dart:64)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:85)
#4      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:286)
#5      runSync (package:flutter_tools/src/base/process.dart:261)
#6      getAdbDevices (package:flutter_tools/src/android/android_device.dart:527)
#7      AndroidDevices.pollingGetDevices (package:flutter_tools/src/android/android_device.dart:40)
#8      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:132)
#9      DeviceManager.getAllConnectedDevices.<anonymous closure> (package:flutter_tools/src/device.dart:88)
#10     ExpandIterator.moveNext (dart:_internal/iterable.dart:480)
#11     _IterablePendingEvents.handleNext (dart:async/stream_impl.dart:528)
#12     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:654)
#13     _rootRun (dart:async/zone.dart:1120)
#14     _CustomZone.run (dart:async/zone.dart:1001)
#15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:928)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#18     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)
```

## flutter doctor

```
encountered exception: ProcessException: %1 is not a valid Win32 application.

  Command: C:\Users\[username]\AppData\Local\Android\sdk\platform-tools\adb.EXE devices -l

#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:447)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:595)
#2      Process.runSync (dart:io-patch/process_patch.dart:64)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:85)
#4      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:286)
#5      runSync (package:flutter_tools/src/base/process.dart:261)
#6      getAdbDevices (package:flutter_tools/src/android/android_device.dart:527)
#7      AndroidDevices.pollingGetDevices (package:flutter_tools/src/android/android_device.dart:40)
#8      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:132)
#9      DeviceManager.getAllConnectedDevices.<anonymous closure> (package:flutter_tools/src/device.dart:88)
#10     ExpandIterator.moveNext (dart:_internal/iterable.dart:480)
#11     _IterablePendingEvents.handleNext (dart:async/stream_impl.dart:528)
#12     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:654)
#13     _rootRun (dart:async/zone.dart:1120)
#14     _CustomZone.run (dart:async/zone.dart:1001)
#15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:928)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#18     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:375)
#19     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:394)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by goderbauer** [comment]
I can't reproduce this even when I add spaces to my username. To you have any other special characters in your name?

If your username in the path really is the issue, you could install the Android SDK to a custom location outside your [username] folder and set the ANDROID_HOME environment variable to point to it.

**Comment by alibix** [comment]
I also did try adding an exception to the firewall for dart.exe so that might also have been it.

I don't have special characters in the username - and this was the hash you were asking for by the way:

Algorithm : SHA512
Hash      : 6BC519A7368EE6BD8C8F69F2D634DD18799B4CA31FBC284D2580BA625F3A88B6A52D2BC17BEA0E75E63CA11C10356C47EE00C2C5002
            94ABCB5141424FC5DC71C
Path      : C:\flutter\bin\cache\dart-sdk\lib\_internal\pub\asset\7zip\7za.exe

**Comment by alibix** [comment]
Also found this:

https://support.microsoft.com/en-in/help/812486/event-id-7000-and-1-is-not-a-valid-win32-application-error-message-when-you-start-a-service

I think it has to be spaces in the file directory. I'm not sure what else it could be

**Comment by alibix** [comment]
Okay - I've moved the SDK. Everything works now.

**Comment by RahulSDeshpande** [comment]
@alibix What is the final solution you have implemented ??

**Comment by 09abhishek** [comment]
@alibix Could you please tell where did you moved the folder and what did you do in order to solve the error!

**Comment by alibix** [comment]
@RahulSDeshpande @09abhishek 
I moved the flutter files to a directory with no spaces in the name - I did the same with the Android SDK

**Comment by goderbauer** [comment]
Looks like the problem is a space in the Android SDK path. I have filed https://github.com/flutter/flutter/issues/12698 for that.

**Comment by cbracken** [comment]
Update: the Flutter SDK, Android SDK, and project directories now all support paths that include spaces in them. (#6577 and #12698 are the related bugs)

**Comment by FogelAO** [comment]
> Update: Flutter now supports spaces in the paths of any/all of the Flutter SDK, the Android SDK, and project directories. (#6577 and #12698 are the related bugs)

@cbracken, 
What about other paths, like Git paths?

**Comment by zoechi** [comment]
@FogelAO if you run into issues related to spaces in paths, please create a new issue (if none exists yet) This one is long closed.

**Comment by FogelAO** [comment]
@zoechi I just want to know when this issues will be fixed. Is it really so hard to fix space in path?
https://github.com/flutter/flutter/issues/18938
https://github.com/flutter/flutter/issues/19359

**Comment by zoechi** [comment]
@FogelAO Ensure you upvoted to raise priority. 
Pull requests are welcome as well of course.

**Comment by eseidelGoogle** [comment]
I thought we fixed this?  Maybe that was @cbracken on mac.  @gspencergoog or @goderbauer might know.

**Comment by FogelAO** [comment]
I guess it is still relevant, because these https://github.com/flutter/flutter/issues/19359, https://github.com/flutter/flutter/issues/18938 issues are still open. And I had to replace all paths to folder without spaces in it's name to avoid errors connected with this issue (of course this is not a solution).

**Comment by gspencergoog** [comment]
This particular bug is definitely fixed (our CI system builds every build using directories with spaces in the names of all of the dependencies). There may still be a related bug having to do with Windows user names with spaces in them, but it's not event clear that is the root cause, based on the comments in those bugs referenced above.

**Comment by FogelAO** [comment]
What about Git in your builds? If it builds with spaces successfully then it is my local problem.

**Comment by cbracken** [comment]
We definitely run all CI with spaces in the SDK path. Since we build the gallery example (which is nested under the SDK), we're also covering the case where the user Flutter project directory contains a space.

Other issues I can imagine that AFAIK we *don't* test for in our CI, but probably should:
1. Space in Android SDK path
2. Space in Xcode path
3. Space in path of command-line tools such as ideviceinstaller, git, etc.

@FogelAO would you mind filing a new issue with details of your particular failure, including the output of `flutter doctor` and a run of whichever command is failing for you with the `--verbose` flag. If you could CC me and @gspencer, and reference this issue in that one, that would be very much appreciated.

**Comment by FogelAO** [comment]
@cbracken , I had [one](https://github.com/flutter/flutter/issues/24232) but it is a duplicate of https://github.com/flutter/flutter/issues/19359 
I hope there are enough information that would be helpful in those issues, because I have moved my Git and Android folders, so now I can enjoy Flutter without these problems. But I can move it back if it will help you to fix it.

**Comment by cbracken** [comment]
@FogelAO Thanks for confirming - this is useful info. I've copied the previous comment over there. Sounds like we need some additional patching and regression tests to handle cases of tools installed at paths with spaces -- as well as potentially other issues.

**Comment by personaluser01** [comment]
This version of D:\src\flutter\bin\cache\dart-sdk\bin\dart.exe is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need a x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher.

**Comment by personaluser01** [comment]
Not support flutter
