### ISSUE TITLE
[video_player] Formatting issue with uncommon aspect ratios.

### ISSUE THREAD

**Issue by TomVeniat** [flutter/flutter#99760]
Hi there,

I face an issue when using the video_player plugin with videos having uncommon aspect ratios.
For example, the video texture will vertically overflow its container when the video has a fairly small aspect ratio:

<img src="https://user-images.githubusercontent.com/5921144/157253774-81ba188b-009d-4540-b75b-ab5a2d46ae96.png" width="300" />

The red block on the right is a container having the aspect ration given by the `VideoPlayerController`, while the actual video on the left is displayed incorrectly. 

It can be reproduced on the latest version using the example project in [this fork](https://github.com/TomVeniat/plugins).

<details><summary>Video to reproduce</summary>

https://user-images.githubusercontent.com/5921144/157257830-342e66cd-05e2-4e11-8ee8-50bbaf919007.mp4

</details>

<details><summary>flutter doctor -v</summary>
<pre>
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.22000.527], locale en-US)
    • Flutter version 2.8.1 at C:\tools\flutter_windows_2.2.3-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 months ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Tom\AppData\Local\Android\sdk
    • Platform android-31, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code, 64-bit edition (version 1.64.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Pixel 5 (mobile) • 08131FDD4003UU • android-arm64  • Android 12 (API 31)
    • Chrome (web)     • chrome         • web-javascript • Google Chrome 98.0.4758.102
    • Edge (web)       • edge           • web-javascript • Microsoft Edge 99.0.1150.30

• No issues found!
</pre>
</details>

This problem doesn't happen on iOS. I only see it on Android, at least on Pixel and Honor phones.
Let me know if you need anything else to diagnostic this issue.

**Comment by darshankawar** [comment]
@TomVeniat 
Thanks for the detailed report. It seems that the issue is video doesn't fit into the parent widget and goes out of the container, that leads me to this similar / related issue: https://github.com/flutter/flutter/issues/51250. Can you check this and see if it's same as your case ?

**Comment by darshankawar** [comment]
Thanks For the feedback @TomVeniat.
The stretch at the bottom is the same as you mentioned: https://github.com/flutter/flutter/issues/64233 in which you can follow-up for the fix.

As for the issue you reported, it seems to me that the video doesn't fit into the container goes out of the bounds, which seems to be similar to https://github.com/flutter/flutter/issues/51250. Would like to know how your issue is different than 51250 and if the behavior you reported can be followed up in the original issue.
