### ISSUE TITLE
Allow to remove suggestion from Autocomplete options list

### ISSUE THREAD

**Issue by binoypatel** [flutter/flutter#99784]
My application provides a way to store autocomplete options as user search. This list is dynamic and easily grows and user would like to remove unused suggestion from the list. At present, there is no way to rebuild the Overlay list which is a show stopper

To address this issue, I would like to have a remove option as given below screenshot:
![image](https://user-images.githubusercontent.com/4742252/157334019-424e47ea-7b5f-47e0-9af7-59efe983f901.png)

As seen in the above screenshot, user should be able to click on the clear button on the right and that option should be removed from the suggestion list.

**Comment by maheshmnj** [comment]
Hi @binoypatel, This should be possible with the current implementation of AutoComplete, Please take a look at the below code sample.

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const AutocompleteExampleApp());

class AutocompleteExampleApp extends StatelessWidget {
  const AutocompleteExampleApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Autocomplete Basic'),
        ),
        body: const Center(
          child: AutocompleteBasicExample(),
        ),
      ),
    );
  }
}

class AutocompleteBasicExample extends StatefulWidget {
  const AutocompleteBasicExample({Key? key}) : super(key: key);

  @override
  State<AutocompleteBasicExample> createState() => _AutocompleteBasicExampleState();
}

class _AutocompleteBasicExampleState extends State<AutocompleteBasicExample> {
    List<String> _kOptions = <String>[
    'aardvark',
    'bobcat',
    'chameleon',
  ];
  @override
  Widget build(BuildContext context) {
    return Autocomplete<String>(
      optionsViewBuilder: (BuildContext _,AutocompleteOnSelected<String> onSelected,Iterable<String> iterable){
        return  Material(
          child: ListView.builder(
            padding: EdgeInsets.zero,
            itemCount: iterable.length,
            itemBuilder: (context,index){
                final String text = iterable.elementAt(index);
            return ListTile(
              trailing: IconButton(onPressed: (){
                  setState(() {
                 _kOptions.remove(text);
                  });
                  print(_kOptions);
              }, icon: const Icon(Icons.close)),
            title: Text(text),
          );
          })
        );
      },
      optionsBuilder: (TextEditingValue textEditingValue) {
        if (textEditingValue.text == '') {
          return const Iterable<String>.empty();
        }
        return _kOptions.where((String option) {
          return option.contains(textEditingValue.text.toLowerCase());
        });
      },
      onSelected: (String selection) {
        debugPrint('You just selected $selection');
      },
    );
  }
}

```
</details>
 
Closing as this can be achieved as per the above code sample. In case you disagree feel free to write in the comments and we will reopen it.

Thank you.

**Comment by binoypatel** [comment]
Hi Mahesh

Thanks for the quick update and sample code, yes this solved my issue. I managed to do the same using bloc.

But it would be nice to achieve this without having to create our own optionsViewBuilder as it does so many magic things inside (for example, highlighting the item etc.), just by passing some callback and boolean parameter to show the delete option and executing the callback.

Kind regards,
Binoy
