### ISSUE TITLE
[skip test] Font issue with the navigation_rail_test on Linux Web tests.

### ISSUE THREAD

**Issue by darrenaustin** [flutter/flutter#99786]
With #99171 we are starting to see an issue with 6 tests that are only failing on 'Linux web_tests_2' with off by one errors: 

```
00:38 +61: test/material/navigation_rail_test.dart: Destination spacing is correct - [labelType]=selected, [textScaleFactor]=1.0 (default)                                                             
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: Offset:<Offset(33.0, 76.0)>
  Actual: Offset:<Offset(33.0, 75.0)>
```

It passes locally on a macbook or a cloudtop Linux box with either html or canvaskit renderer, so I am not sure what is causing this. My guess is that it might be a font size difference on that specific VM. It is apparently running `Chromium 84.0.4147.0` where my cloudtop is running `Google Chrome 98.0.4758.102`.

Skipping these tests on web for now until we can figure this out.

**Comment by darrenaustin** [comment]
Comment from @yjbanov in chat:

> This test seems to be running the HTML renderer. If the test doesn't use Ahem, it is subject to whatever system font the browser ends up falling back on. Chrome on Linux tends to be consistent, but once in a while we see different results (e.g. we discovered some time ago that the HHH bot ends up picking up a different font).
>
> For this reason, using Ahem in tests is strongly encouraged.

So perhaps forcing the use of the Ahem font for these tests will fix this and we can remove the skip.

**Comment by LongCatIsLooong** [comment]
This is no longer reproducible. I believe the HTML renderer always uses one of the test fonts:

https://github.com/flutter/engine/blob/db3d28d4755953f645df677a08d272af5b1954b7/lib/web_ui/lib/src/engine/text/paragraph.dart#L468-L475

Unskipping in https://github.com/flutter/flutter/pull/122945 and closing.
