### ISSUE TITLE
Cocoon auto retried one failed engine build twice

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#99790]
Windows UWP Engine failed on 5c760759fecafa7ae63f7d536d4de9454a59471f, [4644](https://ci.chromium.org/p/flutter/builders/prod/Windows%20UWP%20Engine/4644)

Two builds were retried: [4645](https://ci.chromium.org/p/flutter/builders/prod/Windows%20UWP%20Engine/4645), [4646](https://ci.chromium.org/p/flutter/builders/prod/Windows%20UWP%20Engine/4646)

Based on build tags, both were auto triggered by cocoon:
```
trigger_type: retry
triggered_by: cocoon
user_agent: luci-scheduler
```

<img width="1598" alt="Screen Shot 2022-03-08 at 4 40 31 PM" src="https://user-images.githubusercontent.com/54558023/157350670-10e7fb42-f8db-4828-b21b-c59b3f8d0756.png">

**Comment by CaseyHillers** [comment]
Duping this with https://github.com/flutter/flutter/issues/98674
