### ISSUE TITLE
Convert String To Code.

### ISSUE THREAD

**Issue by ncr9108** [flutter/flutter#99803]
I am Developing One Story Application In Which I am using Carousal For Story Scenes. In Which All Scenes are Dynamic.

     So Is there any Feature Something In Which String Convert To Widget or Code. So I get String From Server Which I cant Convert To Code Or Widget. 
     
     Dynamic Widget Library Not Working For Me As My All Image And Position are Responsive with using Responsive Sizer Library, And Dynamic Widget Not Support Third Party Library.

**Comment by maheshmnj** [comment]
Hi @ncr9108,  I believe you are trying to do a dynamic rendering of widgets based on the response from the backend? If so this is currently not possible with flutter, However there might be some community solutions, You might want to ask such discussion-related questions on our community forums at https://flutter.dev/community.

Closing as this is neither a bug nor a feature request. In case you disagree feel free to write in the comments and we will reopen it.

Thank you.
