### ISSUE TITLE
Not receiving past purchases in_app_purchase

### ISSUE THREAD

**Issue by dovahkiin98** [flutter/flutter#99813]
I'm using the latest version of [in_app_purchase](https://pub.dev/packages/in_app_purchase) [3.0.1], but the documentations don't mention anything about receiving past purchases.

In my testing, I made a purchase and completed it, but when I restart the app, the stream doesn't get called. I can't buy the item again because it says I already own that item, even though that item is refunded.

If I use the `restorePurchases` function, the payment is `purchased` and complete. Same if I manually use `queryPastPurchases` from `InAppPurchaseAndroidPlatformAddition`.

Am I missing something? Or is there an issue with the plugin?

**Comment by darshankawar** [comment]
@dovahkiin98 
According to the plugin's changelog:

`The InAppPurchaseConnection.queryPastPurchases method has been removed. Instead, you should use InAppPurchase.restorePurchases. This method emits each restored purchase on the InAppPurchase.purchaseStream, the PurchaseDetails object will be marked with a status of PurchaseStatus.restored;`

So you should use `InAppPurchase.restorePurchases` to receive past purchases. 
Also check [this](https://stackoverflow.com/questions/69125209/flutter-get-past-purchases-on-android?rq=1) SO link and see if it helps.

**Comment by dovahkiin98** [comment]
Isn't `restorePurchases` supposed to be used when the user is on another device? Or in another instance of the app? (New Installation)? Other documents say that this method is for the user to trigger, not automatically on each application run. The example itself doesn't use that method at all

**Comment by darshankawar** [comment]
Calling `restorePurchases()` sends the purchases to the purchaseStream which you can listen. The example does contain usage of it as below:

https://github.com/flutter/plugins/blob/20e231b0529cbe94e2f372cc53020512873d9c66/packages/in_app_purchase/in_app_purchase/example/lib/main.dart#L367

**Comment by dovahkiin98** [comment]
Yes but it's a separate button, the user has to manually trigger it.

But what if the user just closed the app and relaunched it? They'll have to go click that button again just to reapply the purchases?

**Comment by darshankawar** [comment]
Check [this](https://blog.codemagic.io/understanding-in-app-purchase-apis-in-flutter/) blog, specially `Restoring purchases` , its functioning and how you can use it to deal with past purchases and see if it helps.

**Comment by dovahkiin98** [comment]
> If the user has purchased products in the past, developers can allow users to restore previously purchased products by calling `InAppPurchase.instance.restorePurchases`

This is what confuses me. It says "allow users", meaning it's an action by the user, not the application itself. No example makes the call automatically, and the `codelabs` doesn't even mention it.

**Comment by darshankawar** [comment]
Can you take a chance and try to run the plugin [example](https://github.com/flutter/plugins/tree/main/packages/in_app_purchase/in_app_purchase/example) which makes use of the `restorePurchases()` method and see if it relatable with your use case and see if it's implementation could help to answer your question ?

**Comment by dovahkiin98** [comment]
In the example, the `restorePurchases()` is a separate button, doesn't that mean the user has to manually restore their purchases every time the app launches?

**Comment by darshankawar** [comment]
@dovahkiin98 
Are you looking for a way to get old purchases and to check if the user has already bought the product and `restorePurchases()` doesn't help to get old purchases ?

**Comment by dovahkiin98** [comment]
`restorePurchases()` works, but that's not an automatic function, the user is supposed to trigger it

**Comment by darshankawar** [comment]
@dovahkiin98 
The plugin added that function instead of `queryPastPurchases()` so that's probably the best method for you to use and implement your use case.
