### ISSUE TITLE
Oops; flutter has exited unexpectedly: "FormatException: Missing extension byte (at offset 28)".

### ISSUE THREAD

**Issue by Charlipi** [flutter/flutter#99823]
flutter build ios --release 

Oops; flutter has exited unexpectedly: "FormatException: Missing extension byte (at offset 28)".
A crash report has been written to /private/var/jenkins/workspace/p-amway-superapp-flutter-ios_dev/flutter_01.log.
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+FormatException%3A+Missing+extension+byte+%28at+offset+28%29

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!

**Comment by myryq** [comment]
I had a similar problem but for a Linux build. Unfortunately, I don't remember the reason...

try to run app in release mode `flutter run --release` and check logs

**Comment by Charlipi** [comment]
<img width="404" alt="微信图片_20220309213007" src="https://user-images.githubusercontent.com/42059089/157451487-f3c414bd-9af1-43e7-9b44-62de155516e0.png">

<img width="486" alt="微信图片_20220309213002" src="https://user-images.githubusercontent.com/42059089/157451481-eef82019-5a7b-4a2b-a63b-df14c363eb47.png">
![Uploading 微信图片_20220309213007.png…]()
those picture is error log

**Comment by danagbemava-nc** [comment]
Hi @Charlipi, kindly attach the `flutter_01.log` file here. Screenshots are not searchable. 

Please also provide the following information. 

- your `pubspec.yaml` & pubspec.lock
- the output of `flutter doctor -v`

Thank you
