### ISSUE TITLE
Turkish characters 'ş' , 'ı' and 'ğ' cannot be entered in the TextField

### ISSUE THREAD

**Issue by gulsenkeskin** [flutter/flutter#99826]
I can't enter 'ş' , 'ı' and 'ğ' in TextField.  Even the onChanged event doesn't work when I want to enter these letters.

**Comment by maheshmnj** [comment]
Hi @gulsenkeskin, Thanks for filing the issue. Could you please share your output of `flutter doctor -v` and the target platform this issue reproduces on?  and Please also clarify the keyboard language that needs to be used and the key that needs to be pressed to trigger those characters.
