### ISSUE TITLE
Calling Dart_InitializeApiDL in the C++ plugin from flutter

### ISSUE THREAD

**Issue by rogurotus** [flutter/flutter#99825]
I tried to call Dart_InitializeApiDL in the c++ plugin by sending NativeAPI.initializeApiDLData using platform channel. But I got a segfault.

**Comment by maheshmnj** [comment]
Hi @rogurotus, Thanks for filing the issue. Please share the output of `flutter doctor -v`, The complete error logs, minimal and complete sample code along with the steps to reproduce the issue in order to investigate this issue further.
