### ISSUE TITLE
Audit use of Font Awesome on website

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#9983]
Not sure how this is being used, but it's a chunk of CSS we download on every page.

**Comment by LarkAscending** [comment]
One way it's being used is the much-loved icon that denotes external links. FTR I'm not suggesting we remove that, just saying it's one known use case.

**Comment by sethladd** [comment]
We removed that "external link" icon :)

**Comment by Sfshaza** [comment]
@chalin, have we removed font awesome from the new site? I can't remember.

**Comment by chalin** [comment]
We are using it now for GitHub icons. We'll likely be reintroducing the external link icon. We'll likely be adding a few more FA icons ("build" comes to mind -- like what we have in the www footer).

**Comment by Sfshaza** [comment]
OK, thx. I'm going to close this.
