### ISSUE TITLE
Flavor Asset Tree shaking

### ISSUE THREAD

**Issue by bretmh** [flutter/flutter#99839]
## Details

**This may be a feature request. As I have not found a solution for this yet.**

1. Create 2 flavors with 5 assets.
2. Build your flavors, they both have 5 assets.
3. I'm expecting there to be a way to define what assets are available to each flavor.

**Target Platform:** All
**Target OS version/browser:** All
**Devices:** All

**Comment by bretmh** [comment]
This is similar https://github.com/flutter/flutter/issues/21682

**Comment by darshankawar** [comment]
As you linked the original issue already, I suggest you to follow-up in it for further updates.
Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.
