### ISSUE TITLE
[go_router]If there is more than one route to match, use the first match

### ISSUE THREAD

**Issue by torikatsupg** [flutter/flutter#99833]
## Use case
If there is more than one route to match, use the first match.

The following was implemented using go_router.
```dart
  final _router = GoRouter(
    routes: [
      GoRoute(
        path: '/home',
        builder: (_, __) => const HomePage(),
        routes: [
          GoRoute(
            path: 'create',
            builder: (_, __) => const CreatePage(),
          ),
          GoRoute(
            path: ':id',
            builder: (_, __) => const DetailPage(),
          ),
      ),
    ],
    urlPathStrategy: UrlPathStrategy.path,
  );
```

I expected the following behavior.
```
/home/create -> CreatePage
/home/xxxx   -> DetailPage ("xxxx" is some string, but exclude "create")
```

But I opened `/home/create`, go_router displayed following error.
```
Exception: too many routes for location: /home/create
/home => create
/home => :id
```
go_router uses path_to_regexp internally.
Therefore, perhaps specifying a regular expression could solve this problem. However, we felt that this would not be concise and would be a hassle for the developer.

## Proposal
This can be accomplished by removing `go_router_delegate.dart l442-l463`.
```
441
442    if (matchStacks.length > 1) {
443      final sb = StringBuffer()
444        ..writeln('too many routes for location: $location');
445
446      for (final stack in matchStacks) {
447        sb.writeln('\t${stack.map((m) => m.route.path).join(' => ')}');
448      }
449
450      throw Exception(sb.toString());
451    }
452
453    if (kDebugMode) {
454      assert(matchStacks.length == 1);
455      final match = matchStacks.first.last;
456      final loc1 = _addQueryParams(match.subloc, match.queryParams);
457      final uri2 = Uri.parse(location);
458      final loc2 = _addQueryParams(uri2.path, uri2.queryParameters);
459
460      // NOTE: match the lower case, since subloc is canonicalized to match the
461      // path case whereas the location can be any case
462      assert(loc1.toLowerCase() == loc2.toLowerCase(), '$loc1 != $loc2');
463    }
442
```

**Comment by nank1ro** [comment]
Really need this, would love if you do this.
Please take a look at next js dynamic links documentation: https://nextjs.org/docs/routing/dynamic-routes#caveats
They say:
> Predefined routes take precedence over dynamic routes, and dynamic routes over catch all routes. 

I completely agree with this behavior.

**Comment by rossheat** [comment]
I wholeheartedly agree with the above sentiments.  

Right now, the following such URLs are not possible: 

twitter.com/[username]
instagram.com/[username] 
etc.

**Comment by RaduGrama** [comment]
Agree with the proposed behavior, most common routers pick the first found route, allowing the developer to prioritize.

**Comment by torikatsupg** [comment]
Thank you for your comments!

From these comments, I think it is a useful suggestion for many developers.

How can I raise the label from p5?

**Comment by jamov** [comment]
Agreed. 

Would this change also enable using catch-all route as last option as a top level route? 

For paths loaded runtime from e.g. REST API?
Something like:

- /known-route-1 --> home()
- /known-route-2 --> otherPage()
- /:catch-all --> doesRuntimePathExist(catchedPath) ? webPage() : errorPage()

**Comment by rhc** [comment]
Same here. Coming from a Web background, the ability to distinguish /projects/new and /projects/:id is crucial

**Comment by GauravCalidig** [comment]
Same here, I guess its just a matter of commenting code

**Comment by GauravCalidig** [comment]
Created a dummy repo [here](https://github.com/GauravCalidig/go_router) if anyone wants this and can't wait for package update.

**Comment by amerblackbird** [comment]
Its crucial feature
