### ISSUE TITLE
deprecated salt state has some lingering artifacts: mount.sh

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#99844]
I think this state was deprecated. The script file was removed, but the state still seems to be referenced.

@godofredoc can you confirm this is ok to remove?

----------
          ID: /opt/flutter/provision/mount.sh
    Function: file.managed
      Result: False
     Comment: Source file salt://flutter/mount.sh not found in saltenv 'base'
     Started: 09:44:02.088902
    Duration: 21.173 ms
     Changes:

**Comment by godofredoc** [comment]
That is correct, there is actually a PR open to fix that issue.

**Comment by yusuf-goog** [comment]
Assigning to @godofredoc to close once the PR lands.

**Comment by yusuf-goog** [comment]
Fixed by https://turquoise-internal-review.googlesource.com/c/infra/salt/+/491781
