### ISSUE TITLE
First frame janks after UI has been idle for a few seconds, when laptop is on low battery 

### ISSUE THREAD

**Issue by alexvoina** [flutter/flutter#99846]
When my laptop is disconnected from power plug and is running on medium to low battery my app has a serious performance issue. 

If I leave the app alone for a few seconds (~5-10) and then I scroll a ListView or do some other interaction, the first frame takes a ridiculous amount of time (~600ms) and then subsequent frames are under (16ms = UI + Raster).

I can see on the profiler that the function that is causing the jank is FlutterCompositorCreateBackingStore() which takes somewhere around 680ms to complete. 

I've managed to reproduce this issue on 2 devices, both MacBook Pro (15-inch, 2018), on two different OS versions (Big Sur & Monterrey)

[✓] Flutter (Channel unknown, 2.10.0-0.3.pre, on macOS 12.2.1 21D62 darwin-x64, locale en-GB)
    • Flutter version 2.10.0-0.3.pre 
    • Upstream repository unknown
    • Framework revision fdd0af78bb (6 weeks ago), 2022-01-25 22:01:33 -0600
    • Engine revision 5ac30ef0c7
    • Dart version 2.16.0 (build 2.16.0-134.5.beta)
    • DevTools version 2.9.2

Any pointers or ideas of why this is happening? I've tried to look deep into the flutter code but it is hard for me to understand exactly what's happening in FlutterCompositorCreateBackingStore() and how my laptop running on low battery can affect that.

**Comment by SpencerC** [comment]
Do you have low power graphics mode enabled?
https://www.macworld.com/article/348837/macos-monterey-low-power-mode-system-preferences-how-to-enable.html

**Comment by darshankawar** [comment]
@alexvoina 
Are you seeing the jank on iOS device or desktop platform ?
I see that you are on `Channel unknown, 2.10.0-0.3.pre`, which could be master or beta. Can you upgrade to latest version and try again to see if the behavior still persists ?

If so, can you provide a complete minimal reproducible code sample along with a short video or gif that shows the first frame jank ?

Also check above mentioned link if it helps.

**Comment by alexvoina** [comment]
thanks @darshankawar @SpencerC for the quick replies 

@darshankawar it's on desktop

I found what the problem is and I really don't know how this slipped (sorry to waste your time).

<img width="671" alt="Screenshot 2022-03-10 at 11 45 58" src="https://user-images.githubusercontent.com/32097135/157635551-9d2888c9-ac10-4a46-9fd0-56c3fe385b46.png">

This issue is happening when the "Automatic graphics switching" option is enabled (which is enabled by default). From my point of view, I can do my best to inform users how to avoid this problem (my guess is that Apple should do that too). 

Here's a screenshot from the profiler. 

<img width="695" alt="Screenshot 2022-03-10 at 11 27 04" src="https://user-images.githubusercontent.com/32097135/157637080-7138ce8b-e0ab-4bfb-9fdd-0f9c6a79df1a.png">
 
Do you still want me to test this on latest and provide minimal repro code, given the circumstances? You just have to let an app go out of focus (either switch tabs, or let it 'sleep' for a few seconds), and then go back and scroll a ListView...

**Comment by darshankawar** [comment]
Thanks for the update @alexvoina. You can try to set `NSSupportsAutomaticGraphicsSwitching` to YES in `macos/Runner/Info.plist` and see if it helps to improve the performance or not.

**Comment by alexvoina** [comment]
Ha! I actually googled to see if I can access these settings programatically, but didn't find anything. It seems like NSSupportsAutomaticGraphicsSwitching should do the job! Thanks, I'll let you know if that solves the problem 👍

**Comment by alexvoina** [comment]
@darshankawar setting NSSupportsAutomaticGraphicsSwitching to YES in macos/Runner/Info.plist doesn't help solving the problem

here's Apple explanation of this

A: Starting with OS X 10.7, you may choose to run your OpenGL application on the integrated GPU on the dual-GPU MacBook Pros shipped Early 2011 and after.

By default, once your application creates an OpenGL context (by either calling OpenGL directly or an API that relies on OpenGL such as Core Animation, Core Image, etc), the MacBook Pro automatically switches to the higher-end discrete GPU for performance concerns and won't switch back until the application quits. On OS X 10.6 and earlier, you are not allowed to choose to run on the integrated GPU instead. Starting with OS X 10.7, you may utilize the integrated GPU on the MacBook Pros if you want to, for example, to save battery life.

On OS X 10.7 and later, there is a new attribute called NSSupportsAutomaticGraphicsSwitching. To allow your OpenGL application to utilize the integrated GPU, you must add in the Info.plist of your application this key with a Boolean value of true

https://developer.apple.com/library/archive/qa/qa1734/_index.html#//apple_ref/doc/uid/DTS40010791

My understanding is that this will only allow my app to jump back to use the integrated GPU... Ideally, I want my app to use the discrete (high-performance GPU) all the time. It also might be fine running on the integrated GPU all the time too, even though that would be a big underuse of the device's resources... What I definitely don't want, is to have the app switching between the 2, causing this jank so frequently. It really destroys the user experience.

I've tried setting NSSupportsAutomaticGraphicsSwitching to NO, but that doesn't help either... The only thing that works is to disable Automatic Graphics Switching as shown in the picture from my previous comment.

`once your application creates an OpenGL context (by either calling OpenGL directly or an API that relies on OpenGL such as Core Animation, Core Image, etc), the MacBook Pro automatically switches to the higher-end discrete GPU for performance concerns and won't switch back until the application quits`

It feels like flutter has modified something to force the MacBook Pro to switch back every time the app goes idle (~5 secs), instead of letting it run on the discrete GPU until the app quits.

**Comment by darshankawar** [comment]
@alexvoina 
Thanks for further updates on this. I am assuming you are still on the version you reported this behavior on. Probably a good idea to upgrade to latest and see if updating the version has made any difference / impact on the performance or not.

**Comment by alexvoina** [comment]
no difference

**Comment by darshankawar** [comment]
> My understanding is that this will only allow my app to jump back to use the integrated GPU... Ideally, I want my app to use the discrete (high-performance GPU) all the time.

See this similar open issue https://github.com/flutter/flutter/issues/47822
