### ISSUE TITLE
Removing assets doesn't remove from build folders

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#9985]
We've seen that if you remove assets from resolution dependent folders (3.0x, etc) but keep the 1x ones then the higher resolution images will not be removed from the build folder and will end up in the final APK/IPA.

**Comment by Hixie** [comment]
In case anyone is running into this, a work around is probably to run `flutter build clean`.

**Comment by Hixie** [comment]
Is this iOS or Android or both?

**Comment by lukef** [comment]
I'll confirm if it is both. I know for sure it is on Android.

**Comment by jonahwilliams** [comment]
Fixed via https://github.com/flutter/flutter/pull/39654
