### ISSUE TITLE
[autosubmit] Upstream checkRun to include conclusion property

### ISSUE THREAD

**Issue by KristinBi** [flutter/flutter#99850]
Upstream checkRun class in github package to include conclusion property.

**Comment by keyonghan** [comment]
Some context: we are switching to use github Rest API to get checkruns, which is missing the conclusion property in existing  model: https://github.com/SpinlockLabs/github.dart/blob/master/lib/src/common/model/checks.dart#L88.

The conclusion is necessary to determine the check runs results, and further determine the commit/PR overall result.

**Comment by KristinBi** [comment]
Finished this in https://github.com/SpinlockLabs/github.dart/pull/298.
