### ISSUE TITLE
[cocoon] Create request handler returns latest green commits

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#99869]
The goal is someone can make an HTTP request to `/api/public/get-green-commits?repo=$repo`, and receive a list of the commit shas that had green runs.

A green commit is used to help the release tooling find commits Flutter infrastructure has validated. The rules are:
1. A commit had all its tests run (at least those that are not in bringup)
2. All those blocking tasks were green

This is similar to `/api/public/get-status`, with the added logic above.

**Comment by XilaiZhang** [comment]
done
