### ISSUE TITLE
Specify Visual Studio (Not VS code)

### ISSUE THREAD

**Issue by vonroga** [flutter/flutter#99872]
It might be good to point out that Visual Studio is required, but specifically mention that you're referring to something OTHER than VS Code. As a new developer, I didn't know there was even a difference, because I've never had any reason to use or even know that Visual Studio was a different thing than VS Code.

**Comment by stuartmorgan** [comment]
> 3\. Run into issue, with no instructions on how to solve the problem.

We don't know how to solve the problem; that is a status reported by Visual Studio itself using its own bundled installation status querying tool (`vswhere`). If you are having issues with installing it you'll need to contact Microsoft, who makes it.

> I can assure you that VS Code is "fully installed". I've been using it for months - VS Code works great.

The error that `flutter doctor` is reporting is with Visual Studio, which is completely different from VS Code. (Feedback about the potentially confusing naming there would need to be directed to Microsoft, the vendor for both products.)

**Comment by stuartmorgan** [comment]
It looks like you completely rewrote this this at the same time I closed it. Responding to your updated version:

> It might be good to point out that Visual Studio is required

We do, in both our instructions and in `flutter doctor`. I'm not sure what else you would want to see here.

> but specifically mention that you're referring to something OTHER than VS Code.

We do:
- In a callout box [in our installation instructions](https://docs.flutter.dev/desktop#additional-windows-requirements), as well as by linking directly to the product page.
- In `doctor`, where we provide the full name of the product, the version, and in verbose mode the path.

On the second, from your provided output:
```
[!] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.10)
[...]
[√] VS Code (version 1.65.1)
```

Note the different names and versions, and different paths in the verbose output:

```
• Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
• Visual Studio Build Tools 2019 version 16.11.32126.315
[...]
[√] VS Code (version 1.65.1)
• VS Code at C:\Users\ryanr\AppData\Local\Programs\Microsoft VS Code
```

> As a new developer, I didn't know there was even a difference, because I've never had any reason to use or even know that Visual Studio was a different thing than VS Code.

You have it installed, so it seems like at you've had some occasion to use it, and at some point knew that it was different. If you hadn't already had it installed, `doctor` would have pointed you to https://visualstudio.microsoft.com/downloads/ which would have been quite clear.
