### ISSUE TITLE
Icons should have a simpler/faster path than the ParagraphBuilder machinery

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#99879]
On a low end Android device, this is the before and after of replacing the `Icon` widget with a `SizedBox`:

Before: 

```
  "average_frame_build_time_millis": 3.238827970297031,
  "90th_percentile_frame_build_time_millis": 4.886,
  "99th_percentile_frame_build_time_millis": 32.002,
  "worst_frame_build_time_millis": 77.743,
  "missed_frame_build_budget_count": 21,
  "average_frame_rasterizer_time_millis": 11.093690594059396,
  "90th_percentile_frame_rasterizer_time_millis": 16.367,
  "99th_percentile_frame_rasterizer_time_millis": 48.283,
  "worst_frame_rasterizer_time_millis": 112.337,
  "missed_frame_rasterizer_budget_count": 91,
  "frame_count": 808,
  "frame_rasterizer_count": 808,
  "new_gen_gc_count": 84,
  "old_gen_gc_count": 24,
```

after:

```
  "average_frame_build_time_millis": 3.1781577017114913,
  "90th_percentile_frame_build_time_millis": 4.676,
  "99th_percentile_frame_build_time_millis": 30.592,
  "worst_frame_build_time_millis": 82.322,
  "missed_frame_build_budget_count": 24,
  "average_frame_rasterizer_time_millis": 10.882724390243894,
  "90th_percentile_frame_rasterizer_time_millis": 16.594,
  "99th_percentile_frame_rasterizer_time_millis": 46.564,
  "worst_frame_rasterizer_time_millis": 121.437,
  "missed_frame_rasterizer_budget_count": 99,
  "frame_count": 818,
  "frame_rasterizer_count": 820,
  "new_gen_gc_count": 68,
  "old_gen_gc_count": 22,
```

I did not run multiple tests to try to rule out noise, but this seems like something where we may be able to squeeze out some more room. That said, Gallery is a pretty icon-heavy app and it's not clear how many of our customers actually have that.

For icons in particular, we would want some kind of API that lets you draw a specific glyph from a known font. We know all of this at compile time for the icon fonts used in the application. Today we just put the codepoints in and rely on SkParagraph/Shaper/harfbuzz to help us out, but those are pretty heavy tools for just drawing a single grapheme. We also have to create new paragraph builder instances with associated styles that we really only need a few bits of information from to do this.

**Comment by dnfield** [comment]
https://github.com/flutter/flutter/issues/96617 would fix this

**Comment by olof-dev** [comment]
It looks like this is related to https://github.com/flutter/flutter/issues/58478, which wants to be able to efficiently paint single glyphs.

**Comment by dnfield** [comment]
FWIW, I don't think drawString or drawSimpleText are the righ tAPI - we'd want to expose something that draws glyphs because otherwise it will be way too easy to misuse this API and end up not drawing what you think you're drawing.

**Comment by olof-dev** [comment]
For my purposes, just having `canvas.drawGlyph` in the API sounds good, whether it calls SkCanvas's drawString under the hood or does something else.
