### ISSUE TITLE
[autosubmit] Implement the logic to validate check run statuses

### ISSUE THREAD

**Issue by KristinBi** [flutter/flutter#99873]
Currently since we haven't upstreamed checkRun to include conclusion and haven't distinguished the check runs from cirrus to flutter-dashboard, we cannot add the logic to validate check run statuses. Need to do this after finish the previous two TODOs.

**Comment by keyonghan** [comment]
@KristinBi You may want to add some refs to other issues/PRs so people know the whole picture of this bug.
