### ISSUE TITLE
Repeat flag for flakey tests

### ISSUE THREAD

**Issue by SpencerC** [flutter/flutter#99875]
## Use case
We have a flakey test that fails a very small percentage of the time. We'd like to have the test automatically repeat to reproduce the problem. I've done this in C++ with [`--gtest_repeat`](https://github.com/google/googletest/blob/main/docs/advanced.md#repeating-the-tests). It would be great if flutter had something similar.

## Proposal

```shell
flutter test  --repeat 100 --plain-name "some test" test/unit/thing_test.dart
```

**Comment by darshankawar** [comment]
I think having a `--retry` parameter as mentioned in [this](https://github.com/flutter/flutter/issues/81098) issue is same as above proposal, hence I am closing this in favor of https://github.com/flutter/flutter/issues/81098, so please follow-up in linked issue for further updates.

If anybody disagrees, please write in comments and I'll reopen it.
