### ISSUE TITLE
Flutter AutoComplete populate future list from API and restrict to choose only exist value

### ISSUE THREAD

**Issue by abdulrehmananwar** [flutter/flutter#99889]
i am using AutoComplete i want to call  future list and if i input wrong value which not exist on leave focus i want to validate it also.
below is piece of code butt i want to call list from future and restrict on leave focus if input value not exist.
one more thing i want to show progress indicator while loading data

```

  static const List<User> _userOptions = <User>[
    User(name: 'Alice', email: 'alice@example.com'),
    User(name: 'Bob', email: 'bob@example.com'),
    User(name: 'Charlie', email: 'charlie123@gmail.com'),
  ];

  static String _displayStringForOption(User option) => option.name;

  @override
  Widget build(BuildContext context) {
    return Autocomplete<User>(
      displayStringForOption: _displayStringForOption,
      optionsBuilder: (TextEditingValue textEditingValue) {
        if (textEditingValue.text == '') {
          return const Iterable<User>.empty();
        }
        return
          _userOptions.where((User option) {
          return option
              .toString()
              .contains(textEditingValue.text.toLowerCase());
        });
      },
      onSelected: (User selection) {
        debugPrint('You just selected ${_displayStringForOption(selection)}');
      },
    );
  }
}


@immutable
class User {
  const User({
    required this.email,
    required this.name,
  });

  final String email;
  final String name;

  @override
  String toString() {
    return '$name, $email';
  }

  @override
  bool operator ==(Object other) {
    if (other.runtimeType != runtimeType) {
      return false;
    }
    return other is User && other.name == name && other.email == email;
  }

  @override
  int get hashCode => hashValues(email, name);
}

```

**Comment by darshankawar** [comment]
@abdulrehmananwar 
From your issue description, you are looking for:

- call future list and if i input wrong value which not exist on leave focus i want to validate
- show progress indicator while loading data

I believe for such solutions, support channels like StackOverflow is the correct platform, so please ask the same there as you can find solutions for both.
Also, checkout this video and see if it helps https://www.youtube.com/watch?v=gDryje6oPrk
You can also search for community packages that uses AutoComplete feature which offers both the points you are looking for.

Closing from here, as the solution you are looking for in AutoComplete can be found on support channels or in community third party plugins.
If you disagree, write in comments and I'll reopen.
