### ISSUE TITLE
[Material] ThemeData should use InkSparkle for splashFactory when useMaterial3 is true

### ISSUE THREAD

**Issue by clocksmith** [flutter/flutter#99886]
InkSparkle should only be used as the splashFactory in ThemeData when useMaterial3 is true, the platform is Android, and the compilation mode is not web, i.e. kIsWeb is false.

**Comment by LasseRosenow** [comment]
I already asked this in the pr, but it was ignored, so maybe its better to ask questions in the dedicated issues:

I'm curious: is the sparkle effect not part of material design, or why is it only applied on Android?
