### ISSUE TITLE
webview_flutter can't scroll anymore after long pressed on Android Device

### ISSUE THREAD

**Issue by daydreary** [flutter/flutter#99897]
Steps to Reproduce
1. Open url , wait until it loads complete
2. Scrolling down a little
3. Long pressed any text. Keep pressing at least 5 seconds.(Long enough, don't release finger when the pop menu shows)
4. Pointer up, and try to scroll the page.It is not working.

I will upload a video or gif to show this problem

![8A59936FD089DED30BC095C24C15A9D2](https://user-images.githubusercontent.com/8489471/157639306-55544220-1c4b-4b26-9b72-2abf3b1e9868.gif)

I tried set a gestureRecognizers but it is still not working.
gestureRecognizers: <Factory<OneSequenceGestureRecognizer>>{ Factory(() => EagerGestureRecognizer()), }

device os is Android 9
`webview_flutter` is `2.0.4`

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.1 21C52 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 2.5.3 at /Users/caoxun/Applications/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (5 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/caoxun/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.2, Build version 13C90
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Connected device (2 available)
    • MIX 2 (mobile) • ed1066f1 • android-arm64  • Android 9 (API 28)
    • Chrome (web)   • chrome   • web-javascript • Google Chrome 99.0.4844.51
```
</details>

**Comment by daydreary** [comment]
![8A59936FD089DED30BC095C24C15A9D2](https://user-images.githubusercontent.com/8489471/157638264-66354bed-f04b-40e8-8204-e8f97bd606ee.gif)

**Comment by danagbemava-nc** [comment]
Hi @daydreary, you appear to be using older versions of both `flutter` and `webview_flutter`. 

Kindly upgrade to the latest versions of both to see whether or not you still experience this issue. 

If you do, please provide the updated `flutter doctor -v` as well as a complete minimal reproducible code sample.

Thank you

**Comment by daydreary** [comment]
> Hi @daydreary, you appear to be using older versions of both `flutter` and `webview_flutter`.
> 
> Kindly upgrade to the latest versions of both to see whether or not you still experience this issue.
> 
> If you do, please provide the updated `flutter doctor -v` as well as a complete minimal reproducible code sample.
> 
> Thank you

Hi @danagbemava-nc , thanks for your reply
I update the flutter to 2.10.3 stable and the webview_flutter to 3.0.1
I write a simple demo to test the function and It does work.
I think something goes wrong with my APP. 
I will try to find out what settings cause this problem.

Thank you
