### ISSUE TITLE
[Android]Custom Kotlin plugin Registrar cannot be converted to PluginRegistry

### ISSUE THREAD

**Issue by barangungor** [flutter/flutter#99899]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. I'm trying to create my custom plugin for Flutter on Kotlin. I see this error when i run my app.
3. Even though I follow the migration steps, I also get the v2 migration error 

> The plugin `beacon_scanner_plugin` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.  

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
//GeneratedPluginRegistrant.java
package io.flutter.plugins;
import androidx.annotation.Keep;
import androidx.annotation.NonNull;
import io.flutter.Log;
import io.flutter.embedding.engine.FlutterEngine;
import io.flutter.embedding.engine.plugins.shim.ShimPluginRegistry;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
  private static final String TAG = "GeneratedPluginRegistrant";
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    ShimPluginRegistry shimPluginRegistry = new ShimPluginRegistry(flutterEngine);
    try {
      com.baran.beacon_scanner.beacon_scanner_plugin.BeaconScannerPlugin.registerWith(shimPluginRegistry.registrarFor("com.baran.beacon_scanner.beacon_scanner_plugin.BeaconScannerPlugin"));
    } catch(Exception e) {
      Log.e(TAG, "Error registering plugin beacon_scanner_plugin, com.baran.beacon_scanner.beacon_scanner_plugin.BeaconScannerPlugin", e);
    }
  }
}


//Manifest.xml
    <application>
        <activity android:name=".BeaconScannerPlugin"></activity>
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>


//BeaconScannerPlugin.kt
class BeaconScannerPlugin: FlutterActivity(){
  private val channel="beacon_scanner_plugin"
  fun registerWith(registry: PluginRegistry) {
    GeneratedPluginRegister.registerGeneratedPlugins(FlutterEngine(this))
  }


  override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
    super.configureFlutterEngine(flutterEngine)
    GeneratedPluginRegister.registerGeneratedPlugins(flutterEngine)
   }
}
```

</details>

<details>
  <summary>Logs</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.2, on Microsoft Windows [Version 10.0.19044.1586], locale tr-TR)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.65.1)
[√] Connected device (4 available)
[√] HTTP Host Availability
```

</details>

**Comment by maheshmnj** [comment]
Hi @barangungor, Thanks for filing the issue. Please share a minimal sample project for us to have a look, in order to better address the issue.

**Comment by maheshmnj** [comment]
Hi @barangungor, Thanks for filing the issue. Please share a minimal sample project for us to have a look, in order to better address the issue.

**Comment by barangungor** [comment]
All the codes of my project are available in the codeSample section. It resolved after create new project. Thanks for answers 🙌

**Comment by canitez** [comment]
> All the codes of my project are available in the codeSample section. It resolved after create new project. Thanks for answers 🙌

how exactly did you solve the problem ?

**Comment by barangungor** [comment]
> how exactly did you solve the problem ?
@canitez only i created a new project and transfer my codes step by step
