### ISSUE TITLE
[video_player] Video is not displaying on the iOS device

### ISSUE THREAD

**Issue by yura2000** [flutter/flutter#99894]
Hey! I'm having an issue with the video_player package. It's not displaying some videos on the real iOS device (transparent). Some videos work fine. Audio works for this video. Tried debug and release modes. No errors in the console. An interesting thing is that this video works fine on the iOS simulator. 

<img src="https://user-images.githubusercontent.com/11773084/157613438-5bf47eb5-878c-49c2-9cf1-8f6bc3341885.jpg" width="300" />

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.2.1 21D62 darwin-arm, locale en-UA)
    • Flutter version 2.8.1 at /Users/user/fvm/versions/2.8.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 months ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/user/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.65.0)
    • VS Code at /Users/user/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • iPhone 13 (mobile) • C9EF6C91-DC8F-41CE-9766-559A26257589 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 99.0.4844.51
```
</details>

**Comment by danagbemava-nc** [comment]
Hi @yura2000, please provide a complete minimal reproducible code sample as well as a sample video/video link you're experiencing this issue with. 

Thank you

**Comment by yura2000** [comment]
Hi @danagbemava-nc. I found that iPhone doesn't support this video. Looks like the issue in a video codec or something like that.

**Comment by yura2000** [comment]
Also tried through different apps. Through Slack works and Telegram not.

**Comment by danagbemava-nc** [comment]
>  I found that iPhone doesn't support this video. Looks like the issue in a video codec or something like that.

Hi, @yura2000, if the particular video is not "supported" on iPhones, I'm not sure there's anything that the `video_player` plugin can do about that. 

Can you tell me how you made this discovery?

**Comment by yura2000** [comment]
@danagbemava-nc This video works ok on other devices: macBook, Android... But the weird thing is that it works in Slack app on my iPhone

**Comment by danagbemava-nc** [comment]
Can you share a link to the video?
