### ISSUE TITLE
How to add engine tests on iOS platform.

### ISSUE THREAD

**Issue by wangying3426** [flutter/flutter#99891]
I add some tests in  `FlutterViewControllerTest `, but didn't work. Here are the steps:

1. add some tests in `FlutterViewControllerTest `.
<img width="1222" alt="Screen Shot 2022-03-10 at 2 09 18 PM" src="https://user-images.githubusercontent.com/4476512/157600159-b17947d6-2b39-42f3-8dcf-2ed9832c9e90.png">

2. `ninja -C out/hot_debug_unopt && ninja -C out/ios_debug_sim_unopt ` or `autoninja -C out/hot_debug_unopt && autoninja -C out/ios_debug_sim_unopt`
3. `python flutter/testing/run_tests.py --type=objc`, the results do not include the new test case.

It's seems that FlutterViewControllerTest  even didn't recompile. so, how to add a new tests in the test file on iOS platform? Thanks.

**Comment by ColdPaleLight** [comment]
@wangying3426 
I guess you could replace
```
ninja -C out/hot_debug_unopt && ninja -C out/ios_debug_sim_unopt
```
to
```
ninja -C out/hot_debug_unopt && ninja -C out/ios_debug_sim_unopt && ninja -C out/ios_debug_sim_unopt ios_test_flutter 
```

**Comment by wangying3426** [comment]
> 

@ColdPaleLight Good, it's works.
