### ISSUE TITLE
Navigator needs a variant of push that clears the history (or allows history rewrite)

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#9989]
There are a lot of potential uses cases where you will want to push a widget/screen onto the Navigator and seamlessly clear (or modify) the Navigator history. A good example of this is an welcome or sign up/in flow. If you don't clear the history it can expose the user to situations where they could go back (i.e. Android hardware back button) to those screens leaving the application in an unpredictable state.

@abarth suggested adding a `pushAndRemoveUntil` function to the navigator. It could also be a flag on `push(Named)`.

**Comment by abarth** [comment]
@Hixie the tricky bit is waiting until it is safe to call removeRouteBelow

**Comment by sethladd** [comment]
Did @FaisalAbid mention something similar?
