### ISSUE TITLE
Flutter websites not searchable with Strg+F

### ISSUE THREAD

**Issue by Wissperwind** [flutter/flutter#99895]
Hi,
I really like web development with flutter. But the team I like to establish flutter as framework in says, "We can not use flutter, Strg+F does not work in the Browser".
Is there anything we can do about this?

**Comment by Wissperwind** [comment]
So, firefox for example finds something in selectable text and marks it. But if I scroll the marked sections do not dissappear th the end of the ListView. They overlay other content. Thats nothing we can ship.

**Comment by maheshmnj** [comment]
Hi @Wissperwind, Thanks for filing the issue. If I am understanding it right you are referring to `cmd/ctrl + f`  which allows you to search text through the website is that correct? If so this issue is being tracked here https://github.com/flutter/flutter/issues/53585
