### ISSUE TITLE
TextFormField tooltip error

### ISSUE THREAD

**Issue by Hiteshc29** [flutter/flutter#99901]
![tooltip error](https://user-images.githubusercontent.com/23652725/157651217-7082ffcb-c31f-4488-b17f-a17b6fb99a75.png)

There is no property that can invoke suffix icon with tooltip error in the textformfield widget. 

I'll be really glad to have this feature in TextFormField widget. 

Thank you.

**Comment by maheshmnj** [comment]
Hi @Hiteshc29, Thanks for filing the issue. You should be able to achieve that using the Tooltip widget.   Please take a look at this StackOverflow answer https://stackoverflow.com/questions/56644714/customising-flutter-tooltip.

Closing as this can be achieved with the existing widget and such custom implementations shouldn't be part of the framework.
