### ISSUE TITLE
[card] widget not showing shadow on top

### ISSUE THREAD

**Issue by jinfagang** [flutter/flutter#99907]
I don't know if it is normal, but Card widget does not showing shadow on top:

<img width="392" alt="image" src="https://user-images.githubusercontent.com/21303438/157678938-3866816c-1078-4007-b58d-7a78c4738216.png">

You can clearly see the top shadow not showing. I don't know if this is intended, but I found some where Card actually have shadow on top:

<img width="656" alt="image" src="https://user-images.githubusercontent.com/21303438/157679091-8de344dc-d3db-4ed9-9658-7b3ab87b622a.png">

Part of my layout:

```
Card(
                      margin: EdgeInsets.all(10),
                        elevation: 4,
                        shadowColor: Colors.grey.withAlpha(20),
                        // margin: EdgeInsets.all(0),
                        color: Theme.of(context).scaffoldBackgroundColor,
                        shape: RoundedRectangleBorder(borderRadius: radius),
                       
                        child: InkWell(
                            borderRadius: radius,
                            customBorder: RoundedRectangleBorder(
                              borderRadius: radius,
                            ),
                            onTap: () {
                              _navToDetail(context, taskBloc, tasks);
                            },
                            // onTapDown: onTapDown,
                            child: Padding(
                              padding: EdgeInsets.symmetric(
                                  vertical: 0.0, horizontal: 4.0),
                              child: Row(
```

**I don't want Container here, since it doesn't have a ripple effect when click**

**Comment by darshankawar** [comment]
@jinfagang 
Looking at the use case, I think you can raise this on support channels like StackOverflow where you can find existing solutions on how to get shadow on top. Usually the shadow is based on the elevation we provide and it naturally is found to be at the bottom. 
Closing for now from here. If you disagree or think this is a genuine issue in the framework, write in comments and I'll reopen it.

**Comment by jinfagang** [comment]
thanks. I found my solution, but not gonna post here.... anybody else need this feature
 please figure out yourself.
