### ISSUE TITLE
Stable Focus widget after return back to previous screen

### ISSUE THREAD

**Issue by abdulrehmananwar** [flutter/flutter#99903]
i have two screen first screen contain two textfields and on leave focus i Navigator to secound screen. after returning back to the 1st screen i want to see the focus in last textfield which not working
below is my code
   
```dart
Focus(
        canRequestFocus: false,
        onFocusChange: (focused) async{
          if (!focused) {
            if (tec.text!= "" && tec.text != "test")
            {
              FocusScope.of(context).previousFocus();
              Navigator.push(
                context,
                MaterialPageRoute(builder: (context) =>  search_list()),
              );
            }
          }

        },
        child:
        TextField(
          controller: tec,
          autofocus: true,)
    );
```
when i press back button of secound screen then i want tec focused.

## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

</details>

<details>
  <summary>Logs</summary>

</details>

**Comment by maheshmnj** [comment]
Hi @abdulrehmananwar, Thanks for filing the issue. Please note that the issue tracker is not to get support with your code but to track bugs in the framework. I would suggest you please ask support questions on community forums like StackOverflow or Reddit.

Closing as this is neither a bug nor a feature request, in case you disagree feel free to write in the comments and we will reopen it.

Thank you.

**Comment by abdulrehmananwar** [comment]
> Closed

please share a piece of code. cause its not working . when i close child screen why no one widget focused??? 
if there is  any event (on parent screen)  occur when i close child window there i cant set focus please let me know?
