### ISSUE TITLE
[video_player] Caption (subtitles) Issues

### ISSUE THREAD

**Issue by venushiphop** [flutter/flutter#99902]
I receive the subtitle file(SRT) and the video playback url and serve the video by streaming.
However, if the conversation is fast, there is a delay between the time the subtitle disappears and the time that the new view appears, so the sync does not match well.

Then please check and reply, please.

```dart
Future<ClosedCaptionFile> _loadCaptions(String subtitleUrl) async {
    // srt file
    final Uri subTitleUri = Uri.parse(subtitleUrl);
    final response = await http.get(subTitleUri);
    late String fileContents;
    if (response.statusCode == 200) {
      final decodeData = utf8.decode(response.bodyBytes);
      fileContents = decodeData.toString();
    }
    return SubRipCaptionFile(fileContents);
}

final controller = VideoPlayerController.network(_playUrl,
        closedCaptionFile: _loadCaptions(subtitleUrl)
```

**Comment by maheshmnj** [comment]
Hi @venushiphop, Thanks for filing the issue. Could you please share a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example)  with a sample video source to investigate the issue further.
Please also share the output of `flutter doctor -v`,  Also, Is the captions delayed on a specific target platform or on all video_player plugin supported platforms?
