### ISSUE TITLE
add video recording format in camera plugin (for support recorded video in web browser)

### ISSUE THREAD

**Issue by ravidewanga** [flutter/flutter#99912]

**Comment by darshankawar** [comment]
@ravidewanga 
Can you elaborate your use case by giving an example along with detailed proposal ?
Are you requesting to add a specific recording format for the plugin that can be played in browser ?

**Comment by ravi160691** [comment]
any other option to play recorded video in browser window

**Comment by ravidewanga** [comment]
> @ravidewanga Can you elaborate your use case by giving an example along with detailed proposal ? Are you requesting to add a specific recording format for the plugin that can be played in browser ?

Yes, this plugin recorded video not play chrome and Firefox browser its showing black screen and only audio was play.
Any one have any other option to play recorded video in browser.

**Comment by darshankawar** [comment]
@ravidewanga 
If I understand correctly, you recorded a video on mobile using `video_player` plugin and trying to play that recorded video on web in chrome browser, which isn't showing the video but only audio.

Try [this](https://github.com/flutter/flutter/issues/58527#issuecomment-940169009) solution and see if it helps.

**Comment by ravidewanga** [comment]
I'm recoding video in low resolution but rhis recorded video not supported
in browser window. Only supporting medium or high resolution. Bur i have
need to record small size of recorded video and and upload in service and
use in html.

**Comment by darshankawar** [comment]
@ravidewanga 
Can you provide code sample you are using to record video in low resolution  along with `flutter doctor -v` ?
