### ISSUE TITLE
Flutter Doctor reports no Android Studio unless it's in "Applications"

### ISSUE THREAD

**Issue by brendan-fahy** [flutter/flutter#9991]
## Steps to Reproduce
1. Have Android Studio installed somewhere other than `Applications` or `$HOME/Applications`
2. Run `flutter doctor` 

**Expected behaviour**: Android Studio installation found
**Actual behaviour**: Android Studio installation not found

I realise this is kind of a silly case, but I thought I'd mention it anyway. Due to reasons that aren't worth getting into here, I have my Android Studio installation in a non-standard location. In my case, it's in `$ANDROID_HOME`. `flutter doctor` then reports that I don't have Android Studio installed. 
By the looks of it, it's because of where https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_studio.dart is looking for it. 

**Workaround (or maybe just the fix)**:  move/install an instance of Android Studio to the standard location (`Applications`). Flutter doctor reports a success once I do this.

A potential other fix could be providing a way to tell flutter (or doctor) where to look for the Android Studio installation. 

## Logs

N/A

## Flutter Doctor
```
[✗] Android Studio (not installed)
    • Android Studio not found. Download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
```

**Comment by iNoles** [comment]
You could use flutter config --android-studio-dir=<Point to your unstandard Android Studio Location>

**Comment by brendan-fahy** [comment]
Ah, this looks exactly like it does exactly what I'm looking for. Thank you!

**Comment by chen8888** [comment]
> You could use flutter config --android-studio-dir

very thanks!  This problem has bothered me for a long time.

**Comment by yoavapi** [comment]
my solution was to rename the app to Android Studio (was renamed to build code in one of the updates)

![image](https://user-images.githubusercontent.com/1726989/60767724-2ff30280-a0c4-11e9-8225-b400e6e3762e.png)

**Comment by FLYINGKRIPTO** [comment]
> You could use flutter config --android-studio-dir=

This saved my life

**Comment by austenstrine** [comment]
Two very important notes:

If you set the path without the .app extension, it will not work, and won't give you a hint:

[!] Android Studio
    • Android Studio at /Volumes/External_SSD/Users/admin/Applications/Android Studio/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ Android Studio not found at /Volumes/External_SSD/Users/admin/Applications/Android Studio/Contents
    • Try updating or re-installing Android Studio.

If you set the path wrong (due to a typo or something like that, as in below where I forgot the s at the end of Applications), it will not work, and won't give you a hint:

[!] Android Studio
    • Android Studio at /Volumes/External_SSD/Users/admin/Application/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ Android Studio not found at /Volumes/External_SSD/Users/admin/Application/Android Studio.app/Contents
    • Try updating or re-installing Android Studio.


Flutter team: it might be worth it to add warnings for when the given path does not end in .app, and for when the given path does not exist.

**Comment by Yumore** [comment]
flutter config --android-studio-dir="/Applications/AndroidStudio.app/Contents"
flutter doctor -v

this two commands is my solution
