### ISSUE TITLE
No CMAKE_CXX_COMPILER could be found

### ISSUE THREAD

**Issue by geedeee** [flutter/flutter#99939]
Trying to build the simplest of apps (HelloWorld) for the windows platform. Project created using 'flutter create myapp'

Steps to reproduce in a windows environment (Version 20H2 - Build 10.0.19042.1586)

1) run a cmd shell
2) cd /d s:\path\to\source\code\directory\myapp
3) flutter run -d windows

Output below:-

```
Launching lib\main.dart on Windows in debug mode...
CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_CXX_COMPILER could be found.

Building Windows application...
Exception: Unable to generate build files

```

Running 'flutter run -d chrome' and 'flutter run -d edge' work fine.
I can also run the app in the android emulator without any problems.

See below for detailed build and flutter doctor -v

<details>
<summary> flutter run --verbose -d windows </summary>

```


[  +81 ms] executing: [C:\Users\Admin\development\sdks\flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[ +578 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] 7e9793dee1b85a243edd0e06cb1658e98b077561
[        ] executing: [C:\Users\Admin\development\sdks\flutter/] git tag --points-at
7e9793dee1b85a243edd0e06cb1658e98b077561
[  +54 ms] Exit code 0 from: git tag --points-at 7e9793dee1b85a243edd0e06cb1658e98b077561
[        ] 2.10.3
[   +8 ms] executing: [C:\Users\Admin\development\sdks\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +45 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\Users\Admin\development\sdks\flutter/] git ls-remote --get-url origin
[  +44 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +125 ms] executing: [C:\Users\Admin\development\sdks\flutter/] git rev-parse --abbrev-ref HEAD
[  +43 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +89 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +81 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +7 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +155 ms] Skipping pub get: version match.
[  +82 ms] Generating
S:\Dev\SourceCode\Flutter\first_app\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +114 ms] Initializing file store
[  +17 ms] Skipping target: gen_localizations
[   +9 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have
updated contents: S:\Dev\SourceCode\Flutter\first_app\.dart_tool\package_config_subset}
[  +34 ms] gen_dart_plugin_registrant: Complete
[   +3 ms] Skipping target: _composite
[   +3 ms] complete
[   +9 ms] Launching lib\main.dart on Windows in debug mode...
[   +6 ms] C:\Users\Admin\development\sdks\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\Users\Admin\development\sdks\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\Users\Admin\development\sdks\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental
--target=flutter --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
C:\Users\Admin\AppData\Local\Temp\flutter_tools.9b18bbe6\flutter_tool.66c8c796\app.dill --packages
S:\Dev\SourceCode\Flutter\first_app\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false
--enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill
build\c075001b96339384a97db4862b8ab8db.cache.dill.track.dill --enable-experiment=alternative-invalidation-strategy
[  +34 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products *
-utf8 -latest -version 16 -requires Microsoft.VisualStudio.Workload.NativeDesktop
Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[  +43 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products
* -utf8 -latest -version 16 -requires Microsoft.VisualStudio.Workload.NativeDesktop
Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[   +2 ms] [
             {
               "instanceId": "3b3ab3aa",
               "installDate": "2022-02-28T00:46:58Z",
               "installationName": "VisualStudio/17.1.1+32228.430",
               "installationPath": "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community",
               "installationVersion": "17.1.32228.430",
               "productId": "Microsoft.VisualStudio.Product.Community",
               "productPath": "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\IDE\\devenv.exe",
               "state": 4294967295,
               "isComplete": true,
               "isLaunchable": true,
               "isPrerelease": false,
               "isRebootRequired": false,
               "displayName": "Visual Studio Community 2022",
               "description": "Powerful IDE, free for students, open-source contributors, and individuals",
               "channelId": "VisualStudio.17.Release",
               "channelUri": "https://aka.ms/vs/17/release/channel",
               "enginePath": "C:\\Program Files (x86)\\Microsoft Visual
               Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
               "installChannelUri": "H:\\_Development\\Visual Studio 2022\\ChannelManifest.json",
               "installedChannelUri": "https://aka.ms/vs/17/release/channel",
               "layoutPath": "H:\\_Development\\Visual Studio 2022",
               "releaseNotes": "https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-notes-v17.1#17.1.1",
               "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=661288",
               "updateDate": "2022-03-10T23:25:53.8565786Z",
               "catalog": {
                 "buildBranch": "d17.1",
                 "buildVersion": "17.1.32228.430",
                 "id": "VisualStudio/17.1.1+32228.430",
                 "localBuild": "build-lab",
                 "manifestName": "VisualStudio",
                 "manifestType": "installer",
                 "productDisplayVersion": "17.1.1",
                 "productLine": "Dev17",
                 "productLineVersion": "2022",
                 "productMilestone": "RTW",
                 "productMilestoneIsPreRelease": "False",
                 "productName": "Visual Studio",
                 "productPatchVersion": "1",
                 "productPreReleaseMilestoneSuffix": "1.0",
                 "productSemanticVersion": "17.1.1+32228.430",
                 "requiredEngineVersion": "3.1.2196.8931"
               },
               "properties": {
                 "campaignId": "",
                 "channelManifestId": "VisualStudio.17.Release/17.1.1+32228.430",
                 "nickname": "",
                 "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\setup.exe"
               }
             }
           ]
[   +4 ms] Building Windows application...
[  +29 ms] <- compile package:first_app/main.dart
[   +3 ms] executing: C:\Program Files\Microsoft Visual
Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe -S
S:\Dev\SourceCode\Flutter\first_app\windows -B build\windows -G Visual Studio 17 2022
[  +62 ms] -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
[+5030 ms] -- The CXX compiler identification is unknown
[  +86 ms] CMake Error at CMakeLists.txt:2 (project):
[   +3 ms]   No CMAKE_CXX_COMPILER could be found.
[   +2 ms] -- Configuring incomplete, errors occurred!
[        ] See also "S:/Dev/SourceCode/Flutter/first_app/build/windows/CMakeFiles/CMakeOutput.log".
[        ] See also "S:/Dev/SourceCode/Flutter/first_app/build/windows/CMakeFiles/CMakeError.log".
[  +34 ms] Building Windows application... (completed in 5.2s)
[+4816 ms] Exception: Unable to generate build files
[   +3 ms] "flutter run" took 10,748ms.
[  +10 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:687:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1161:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>


[ +140 ms] ensureAnalyticsSent: 136ms
[   +3 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1

================================

```

</details>

<details>
<summary> flutter doctor -v </summary>

```

flutter doctor -v
[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.19042.1586], locale en-AU)
    • Flutter version 2.10.3 at C:\Users\Admin\development\sdks\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (8 days ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\Admin\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android_Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32228.430
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android_Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.65.2)
    • VS Code at C:\Users\Admin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.36.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.1586]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 99.0.4844.51
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 99.0.1150.36

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

================================

```

</details>

**Comment by darshankawar** [comment]
@geedeee 
Can you provide `myapp/build/windows/CMakeFiles/CMakeOutput.log` ?

**Comment by geedeee** [comment]
Thanks!
I have provided both CMakeOutput.log and CMakeError.log as CMakeOutput.log is sparse in information.
[CMakeError.log](https://github.com/flutter/flutter/files/8236757/CMakeError.log)
[CMakeOutput.log](https://github.com/flutter/flutter/files/8236758/CMakeOutput.log)

**Comment by geedeee** [comment]
Ok, maybe traced some of the problem due to a bug with the Windows SDK installer under Visual Studio 2022.
(See here https://developercommunity2.visualstudio.com/t/Incorrect-UCRT-path-in-UniversalCRT_Incl/1454565 )

1) Run the visual studio installer and uninstall ALL "Windows SDK" packages.
2) Go into Windows Settings and choose Apps & Features and uninstall ALL "Windows SDK" packages from here too.
3) Ran a registry cleanup.
4) Run the visual studio installer and modify your installation to re-install "Windows 10 SDK 10.0.19041.0" AND "Windows 10 SDK 10.0.22000.0"
5) Test Visual Studio by creating both a "Console App" and a "Windows Desktop App" - Both should build and run successfully.

Now however, I have a different problem.
When I run 'flutter run -d windows' I get the below output.

flutter_wrapper_app.lib(core_implementations.obj) : error LNK2001: unresolved external symbol __imp__invalid_parameter [S:\Dev\SourceCode\Flutter\first_app\build\windows\runner\first_app.vcxproj]
flutter_window.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter [S:\Dev\SourceCode\Flutter\first_app\build\windows\runner\first_app.vcxproj]
main.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter [S:\Dev\SourceCode\Flutter\first_app\build\windows\runner\first_app.vcxproj]
utils.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter [S:\Dev\SourceCode\Flutter\first_app\build\windows\runner\first_app.vcxproj]
flutter_wrapper_app.lib(flutter_engine.obj) : error LNK2001: unresolved external symbol __imp__invalid_parameter [S:\Dev\SourceCode\Flutter\first_app\build\windows\runner\first_app.vcxproj]
flutter_wrapper_app.lib(core_implementations.obj) : error LNK2001: unresolved external symbol __imp__CrtDbgReport [S:\Dev\SourceCode\Flutter\first_app\build\windows\runner\first_app.vcxproj]
flutter_window.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReport [S:\Dev\SourceCode\Flutter\first_app\build\windows\runner\first_app.vcxproj]
main.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReport [S:\Dev\SourceCode\Flutter\first_app\build\windows\runner\first_app.vcxproj]
utils.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReport [S:\Dev\SourceCode\Flutter\first_app\build\windows\runner\first_app.vcxproj]
flutter_wrapper_app.lib(flutter_engine.obj) : error LNK2001: unresolved external symbol __imp__CrtDbgReport [S:\Dev\SourceCode\Flutter\first_app\build\windows\runner\first_app.vcxproj]
S:\Dev\SourceCode\Flutter\first_app\build\windows\runner\Debug\first_app.exe : fatal error LNK1120: 2 unresolved externals [S:\Dev\SourceCode\Flutter\first_app\build\windows\runner\first_app.vcxproj]
Building Windows application...
Exception: Build process failed.


=========================

Here are CMakeError.log & CMakeOutput.log

[CMakeError.log](https://github.com/flutter/flutter/files/8237148/CMakeError.log)
[CMakeOutput.log](https://github.com/flutter/flutter/files/8237149/CMakeOutput.log)

**Comment by geedeee** [comment]
I thought that maybe "Windows 10 SDK 10.0.22000.0" (Windows 11 SDK) was the problem so I went ahead and uninstalled that.
However, it made no difference at all and still gives the same errors.

**Comment by geedeee** [comment]
Ok, got a little bit further.

1) Open the "first_app" SOLUTION file in Visual Studio.
2) Apply the below 'step 3 ' instructions to the projects "ALL_BUILD", "first_app", "flutter_wrapper_app"
3) Right click on the above 'step 2' projects in the solution explorer and select 'properties'
4) Under 'Configuration Properties' select 'Advanced'
5) On the right, set "Use Debug Libraries" to "Yes" (Previously they are all set to "No")
6) Click "Apply" button, then "OK" button.
7) From Build menu, select "Rebuild Solution"

Code now compiles correctly but FAILS in the "INSTALL" project.
See further down for failure details.

The "first_app.exe" file can be found under "first_app\build\windows\runner\Debug"
The "flutter_windows.dll" file can be found under "first_app\windows\flutter\ephemeral"
I copied the "flutter_windows.dll" file to where the "first_app.exe" is located.
Run the "first_app.exe" and a window very briefly pops up and then disappears.
So, don't really know what to do next. It does seem that CMake is not configuring the solutions project files correctly.
Don't know why the program runs then disappears.


I should not need to run with Admin privileges.  cmake_install.cmake should not be trying to write to anything under "C:/Program Files (x86)"


------ Rebuild All started: Project: INSTALL, Configuration: Debug x64 ------
7>-- Install configuration: "Debug"
7>CMake Error at cmake_install.cmake:55 (file):
7>  file cannot create directory: C:/Program Files (x86)/first_app.  Maybe need
7>  administrative privileges.
7>
7>
7>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(157,5): error MSB3073: The command "setlocal
7>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(157,5): error MSB3073: "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -DBUILD_TYPE=Debug -P cmake_install.cmake
7>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(157,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
7>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(157,5): error MSB3073: :cmEnd
7>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(157,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
7>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(157,5): error MSB3073: :cmErrorLevel
7>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(157,5): error MSB3073: exit /b %1
7>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(157,5): error MSB3073: :cmDone
7>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(157,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd
7>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(157,5): error MSB3073: :VCEnd" exited with code 1.
7>Done building project "INSTALL.vcxproj" -- FAILED.
========== Rebuild All: 6 succeeded, 1 failed, 0 skipped ==========

**Comment by geedeee** [comment]
Ok, so now I am really confused.

From a cmd prompt inside the "first_app" directory I did the following.

1) flutter clean
2) flutter build windows
3) This successfully produces "first_app.exe" and "flutter_windows.dll" in "first_app\build\windows\runner\Release" directory.
4) Double click on "first_app.exe" and program runs successfully.

So I decide to try building and running a Debug build.

1) flutter clean
2) flutter run -d windows
3) This successfully produces "first_app.exe" and "flutter_windows.dll" in "first_app\build\windows\runner\Debug" directory.
4) Double click on "first_app.exe" and program runs successfully.

Was it running a clean on the project that fixed things?

**Comment by geedeee** [comment]
So, I think the initial problem was that I had visual studio 2019 installed, along with some Windows SDKs.
When I uninstalled Visual Studio 2019 it did not completely remove all the Windows SDKs. I then installed Visual Studio 2022 with it's default more recent Windows SDK.
However, due to a bug in the Windows SDK installer, the macros $(VC_IncludePath) , $(UniveralCRT_IncludePath) and $(WindowsSDK_IncludePath) have an incorrect path. Instead of using "C:\Program Files (x86)\path\to\windows\sdk\..." they use "C:\Program Files\path\to\windows\sdk\..."
The installation of a newer Windows SDK does not correctly update the macros. This is why you need to completely remove ALL Windows SDKs and re-install the Windows SDK of your choice.
Perhaps this affected the contents of the CMake files when they were initially created.
Regenerating the CMake and project files using 'flutter clean' and then building/running the project fixed the further problems.

Doing the following now works straight out of the box.

1) flutter create second_app
2) flutter run -d windows
3) app runs successfully

then 

1) flutter build windows
2) cd "build\windows\runner\Release"
3) run "second_app.exe"
4) app runs successfully

Hopefully this may help someone in the future.

**Comment by darshankawar** [comment]
Thanks for these updated and glad that you were able to identify the root-cause and fix the issue.
Closing this as resolved.

**Comment by geedeee** [comment]
So, I think the initial problem was that I had visual studio 2019 installed, along with some Windows SDKs.
When I uninstalled Visual Studio 2019 it did not completely remove all the Windows SDKs. I then installed Visual Studio 2022 with it's default more recent Windows SDK.
However, due to a bug in the Windows SDK installer, the macros $(VC_IncludePath) , $(UniveralCRT_IncludePath) and $(WindowsSDK_IncludePath) have an incorrect path. Instead of using "C:\Program Files (x86)\path\to\windows\sdk\..." they use "C:\Program Files\path\to\windows\sdk\..."
The installation of a newer Windows SDK does not correctly update the macros. This is why you need to completely remove ALL Windows SDKs and re-install the Windows SDK of your choice.
Perhaps this affected the contents of the CMake files when they were initially created.
Regenerating the CMake and project files using 'flutter clean' and then building/running the project fixed the further problems.

Doing the following now works straight out of the box.

1) flutter create second_app
2) flutter run -d windows
3) app runs successfully

then 

1) flutter build windows
2) cd "build\windows\runner\Release"
3) run "second_app.exe"
4) app runs successfully

Hopefully this may help someone in the future.
