### ISSUE TITLE
[dashboard] Make it easy to swap repos

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#99938]
We should move the repo dropdown from the settings dialog into the `AppBar` directly.

This will make it easier for developers to swap between repos instead of needing to open a new tab

![image](https://user-images.githubusercontent.com/2148558/157774968-8aa6d564-12e5-4db2-9b18-c39a584c7319.png)

**Comment by CaseyHillers** [comment]
Does this SG to you @jonahwilliams ?

**Comment by jonahwilliams** [comment]
Sounds great!

**Comment by CaseyHillers** [comment]
Change has rolled out. @jonahwilliams feel free to reopen if there's anything missing / could be made easier to access.
