### ISSUE TITLE
An ios pwa question

### ISSUE THREAD

**Issue by pandagit123** [flutter/flutter#99930]
https://user-images.githubusercontent.com/100551147/157749135-a7bc2f3f-6196-4303-8be6-c1e58cd47d97.mp4

This is a new project, and no change any code, but on ios pwa, you can swipe right through the sliding gesture...

Is this normal?

**Comment by TahaTesser** [comment]
This is a known issue https://github.com/flutter/flutter/issues/55913
Reproduction https://github.com/flutter/flutter/issues/55913#issuecomment-933332262
