### ISSUE TITLE
"The project ‘Runner’ is damaged and cannot be opened due to a parse error" 

### ISSUE THREAD

**Issue by Dan1ell** [flutter/flutter#99932]
Since [https://github.com/flutter/flutter/issues/41987#issue-502730712](https://github.com/flutter/flutter/issues/41987#issue-502730712) is closed, I just wanted to report that this just happened to me also.

I ran flutter clean,
invalidated caches,
I ran flutter pub get,
then I ran flutter upgrade and restarted the laptop. 
Then I upgraded the android studio flutter plugin and restarted the laptop.
Then I tried to open the ios project in xcode to see if there were any issues in there but the error came up:

> Unable to get Xcode project information:
>  objc[1332]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libamsupport.dylib (0x1e1ebb130) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x103ec02c8). One of the two will be used. Which one is undefined.
> objc[1332]: Class AMSupportURLSession is implemented in both /usr/lib/libamsupport.dylib (0x1e1ebb180) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x103ec0318). One of the two will be used. Which one is undefined.
> 2022-03-10 18:23:54.883 xcodebuild[1332:11974] Error Domain=NSCocoaErrorDomain Code=3840 "Unable to parse empty data." UserInfo={NSDebugDescription=Unable to parse empty data.}
> xcodebuild: error: Unable to read project 'Runner.xcodeproj'.
> 	Reason: The project ‘Runner’ is damaged and cannot be opened due to a parse error. Examine the project file for invalid edits or unresolved source control conflicts.
> 

The project.pbxproj file was completely empty. I had to restore it from git.

Strike all that. 

Just checked the git log again. The project.pbxproj file was already empty on my last commit. Right before starting those actions. I had been running the app on the android emulator with no issues up that point. I recall seeing the file in the changes list just after trying to run the app in the ios simulator. A run that failed with an error about installing pods. I figured the file must have been changed due to the failed run somehow and committed my work without realizing I was committing an empty project.pbxproj file. Only then did I begin the cleaning and upgrade process.

**Comment by darshankawar** [comment]
@Dan1ell 
What command are you running that gives you this error ? Can you attach `-v` to it and provide the entire verbose log ? The log will be huge so you can put that in a text file and share it here.
Also provide your `flutter doctor -v` to know on which version are you seeing this.

**Comment by Dan1ell** [comment]
I just selected the ios simulator and ran the app from within android studio with run main dart. That caused the pod install error en then the project.pbxproj file showed up in the commit list as altered. 
I selected the avd next, and ran it from within android studio and got 'The project is damaged and cannot be opened due to a parse error'. I eventually found the project.pbxproj file was empty. 

After restoring project.pbxproj from git I'm no longer getting any errors. But I don't know what exactly caused that file to become empty in the first place. Since I'm not getting the error anymore do you still want full flutter run -v logs?

I didn't run flutter doctor right after the error but it did run automatically after the upgrade and no issues were found. I was upgrading from 2.10.1 to 2.10.3. This is my flutter doctor now.

[✓] Flutter (Channel stable, 2.10.3, on macOS 12.0.1 21A559 darwin-arm, locale en-US)
    • Flutter version 2.10.3 at /Users/strijdhaftig/Code/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (11 days ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/strijdhaftig/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.65.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 12 (API 32) (emulator)
    • iPhone 13 (mobile)          • FFF677E4-9CDA-475F-8C79-041A0409EE10 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 99.0.4844.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by darshankawar** [comment]
@Dan1ell 
Thanks for the update. We have not seen this type of error before or consistently so it will be a bit hard to tell as why that error could have triggered, but looking at the error, it could have been related to any merge conflicts while merging branches using git and specially with pbxproj file, in it could have some conflict markers and it may not have anything to do with Flutter itself.
Since you restored the file and not getting error anymore, I'll go ahead and close it as resolved. If you see same error again or know the pattern that causes it, write in comments and I'll reopen it.
