### ISSUE TITLE
Consider adding a stencil buffer for Skia to use on OpenGL backend

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#99934]
On Android, we set the `EGL_STENCIL_SIZE` to 0. On Windows, we set it to 8.

However, we tell skia to avoid stencil buffers. This was added in https://github.com/flutter/engine/pull/4362.

We should stop telling Skia to avoid stencil buffers and make sure android provides one as well. That should avoid the performance overlay regression, and allow Skia to perform better on Android and Windows.

I suspect this could also help https://github.com/flutter/flutter/issues/97334

@chinmaygarde @jonahwilliams @brianosman  fyi

**Comment by chinmaygarde** [comment]
Agreed. We should always configure the default onscreen framebuffer to have a stencil buffer and ask Skia to make use of it. The only regression would be the additional full-screen 8-bit buffer. Skia may already be using glInvalidateFramebuffer with glDiscardFrembufferEXT to give hints to the driver about the use of these buffers.

**Comment by dnfield** [comment]
Verified locally that the performance overlay still renders on an Android device with this configuration.
