### ISSUE TITLE
flutter create --plugin should ask for value of com.yourcompany

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#9994]
`flutter create --plugin` uses the placeholder `com.yourcompany` in many, many, many places. It's a huge pain to change it to the correct value everywhere without missing a spot. It would be nice if `flutter create --plugin` would (optionally) ask for the actual value you want to use and use that to populate the template. 

/cc @mravn-google @mit-mit

**Comment by eseidelGoogle** [comment]
Related to https://github.com/flutter/flutter/issues/9797?

**Comment by goderbauer** [comment]
What makes matters even worse: if you attempt to use android studio to rename the packages it will mess up the entire package structure.

**Comment by mit-mit** [comment]
I think we should do this for both --plugin and regular template.

**Comment by mravn-google** [comment]
```
flutter create          --org com.foo.bar hello
flutter create --plugin --org com.foo.bar hello
```
resulting in Java package = iOS bundle ID = `com.foo.bar.hello`
