### ISSUE TITLE
Moving a test to staging breaks links

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#99948]
After a test moves to staging, the links to the logs from cocoon will 404.

<img width="375" alt="Screen Shot 2022-03-10 at 6 12 25 PM" src="https://user-images.githubusercontent.com/6343103/157788954-231dca80-5e48-4790-bfb0-2a1d4c3616f4.png">

The circled link will no longer go to logs showing the failures, which makes investigation more difficult.

@CaseyHillers

**Comment by zanderso** [comment]
That is, if you click the exclamation point, and then click "View Logs" it will 404.

**Comment by CaseyHillers** [comment]
CL in https://flutter-review.googlesource.com/c/infra/+/28141

**Comment by CaseyHillers** [comment]
CL has landed and this is fixed.

As a side effect, we can start running staging runs overnight from the Cocoon side to verify infra changes.
