### ISSUE TITLE
Focus on remain stable after retrun back from child widget to  parent widget

### ISSUE THREAD

**Issue by abdulrehmananwar** [flutter/flutter#99943]
i am using text widget on parent window and on tap i navigate to child window . when child window close i want to see the focus in the same textfield of parent window.

**Comment by maheshmnj** [comment]
This issue was originally filed here https://github.com/flutter/flutter/issues/99903 and has been closed for the reasons specified https://github.com/flutter/flutter/issues/99903#issuecomment-1064058567

**Comment by darshankawar** [comment]
@abdulrehmananwar 
Looking at the description you provided, it may already have an existing solution for which you can ask on support channels like StackOverflow, so I am closing for now from here. Take a look at this documentation and see if it helps : https://docs.flutter.dev/cookbook/forms/focus

**Comment by abdulrehmananwar** [comment]
please share a piece of code. cause its not working . when i close child screen why no one widget focused??? 
if there is  any event (on parent screen)  occur when i close child window there i cant set focus please let me know?

**Comment by maheshmnj** [comment]
@abdulrehmananwar, You have autofocus enabled in TextField, It is expected that the Textfield should gain the focus when it comes into view. But as per the current implementation, On popping the route widgets with `AutoFocus: true` do not gain focus. This issue is begin tracked here https://github.com/flutter/flutter/issues/48464

However, the linked issue is about regaining focus without opening a keyboard, changing scroll position. I tried to achieve that with the help of the below code sample but it opens up the keyboard. 

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      navigatorObservers: [routeObserver],
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final FocusNode focusNode = FocusNode();

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    focusNode.addListener(() {
      if (!focusNode.hasFocus) {
        push(SecondScreen(
          onPop: () {
            focusNode.requestFocus();
          },
        ));
      }
    });
  }

  void push(Widget child) {
    Navigator.push(context, MaterialPageRoute(builder: (context) => child));
  }

  @override
  void dispose() {
    focusNode.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () => FocusScope.of(context).unfocus(),
      child: Scaffold(
          body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            TextField(
              autofocus: true,
              focusNode: focusNode,
            )
          ],
        ),
      )),
    );
  }
}

final RouteObserver<ModalRoute<void>> routeObserver =
    RouteObserver<ModalRoute<void>>();

class SecondScreen extends StatefulWidget {
  final Function? onPop;

  const SecondScreen({Key? key, this.onPop}) : super(key: key);

  @override
  State<SecondScreen> createState() => _SecondScreenState();
}

class _SecondScreenState extends State<SecondScreen> with RouteAware {
  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    routeObserver.subscribe(this, ModalRoute.of(context)!);
  }

  @override
  void dispose() {
    routeObserver.unsubscribe(this);
    super.dispose();
  }

  @override
  void didPop() {
    widget.onPop!();
    super.didPop();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: const Center(
        child: Text('Second Screen'),
      ),
    );
  }
}

```
</details>

**Comment by abdulrehmananwar** [comment]
this is perfect for single textfield. butt i have multiple textfields using List<TextEditingController> on parent form. how to manage them with focused node. on each text field on parent form i want the same function

**Comment by abdulrehmananwar** [comment]
do i need to create a List<FocusNode>  for my multiple textfields?? 
as i have created List<TextEditingController>.
if yes please let me know thanks
