### ISSUE TITLE
Mac dart_plugin_registry_test is super flaky

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#99940]
The `Mac dart_plugin_registry_test` has been flaky 7 times today:
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20dart_plugin_registry_test/4171/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20dart_plugin_registry_test/4170/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20dart_plugin_registry_test/4167/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20dart_plugin_registry_test/4164/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20dart_plugin_registry_test/4163/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20dart_plugin_registry_test/4157/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20dart_plugin_registry_test/4156/overview

It timed out when resolving dependencies:
```
[dart_plugin_registry_test] [STDOUT] stdout: [        ] Xcode 13.0
[dart_plugin_registry_test] [STDOUT] stdout:            Build version 13A233
[dart_plugin_registry_test] [STDOUT] stdout: [ +101 ms] Running "flutter pub get" in app...
[dart_plugin_registry_test] [STDOUT] stdout: [   +5 ms] executing: [/opt/s/w/ir/x/t/flutter_devicelab_dart_plugin_test.4d7EAz/app/] /opt/s/w/ir/x/w/recipe_cleanup/tmp9d30io9p/flutter sdk/bin/cache/dart-sdk/bin/dart __deprecated_pub --verbose get --no-precompile
[dart_plugin_registry_test] [STDOUT] stdout: [  +92 ms] MSG : Resolving dependencies...```
```

**Comment by stuartmorgan** [comment]
Were there network issues on the bot? Dependency resolution generally isn't flaky.

**Comment by christopherfujino** [comment]
This has been blocking https://github.com/flutter/flutter/pull/98928 from landing.

**Comment by blasten** [comment]
The latest 25 runs are green. https://ci.chromium.org/p/flutter/builders/staging/Mac%20dart_plugin_registry_test?limit=25

closing this for now.
