### ISSUE TITLE
[Proposal] Disable linting for generated_plugin_registrant.dart

### ISSUE THREAD

**Issue by 18601673727** [flutter/flutter#99952]
Transfered issue from https://github.com/dart-lang/sdk/issues/48520

**Comment by maheshmnj** [comment]
Hi @18601673727,  Thanks for filing the issue I can reproduce it generated files are included in lint warnings so the linter complains about double quotes, A temporary solution is to exclude such generated files as mentioned here https://github.com/dart-lang/sdk/issues/48520#issuecomment-1061096153 

This issue tracks a proposal to exclude generated files from linter reports by default as mentioned here https://github.com/dart-lang/sdk/issues/48520#issuecomment-1061096273   

cc: @christopherfujino

**Comment by stuartmorgan** [comment]
This is unrelated to `flutter_lints`, it's a request to have the tool add `// ignore_for_file: type=lint` to `generated_plugin_registrant.dart`.

**Comment by ditman** [comment]
(Forgot to sneak a fix for this with the new web initialization code; however I'll tackle this next week)

**Comment by ditman** [comment]
In the latest `master`, the `generated_plugin_registrant.dart` file contains the `//ignore` rule suggested above.

It has also been moved *outside* of an app's working copy, so it should never be picked up by dart analysis either.
