### ISSUE TITLE
[web]: Embed flutter web into the iframe，inertia disappears After sliding

### ISSUE THREAD

**Issue by JINMUSENG** [flutter/flutter#99953]
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.1 21C52 darwin-x64, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] Connected device (1 available)

![image](https://user-images.githubusercontent.com/18130832/157801725-8a047df3-0ce9-49b2-b52d-53a73cd7efb0.png)
![image](https://user-images.githubusercontent.com/18130832/157801823-c7603713-2066-49f3-a745-cc1d976d8928.png)

Does anyone can answer? thanks

**Comment by JINMUSENG** [comment]
https://user-images.githubusercontent.com/18130832/157829110-a27b2df5-f80d-4093-a1a1-afdf58020101.mp4

**Comment by darshankawar** [comment]
@JINMUSENG 
Can you upgrade to latest stable (2.10.3) and try again to see if behavior still persists ?
If so, can you provide a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) ?
