### ISSUE TITLE
The following assertion was thrown building UiKitView(dependencies: [Directionality], state: _UiKitViewState#2b400):

### ISSUE THREAD

**Issue by walkerwg** [flutter/flutter#99950]
The following assertion was thrown building UiKitView(dependencies: [Directionality], state: _UiKitViewState#2b400):
There were multiple gesture recognizer factories for the same type, there must only be a single gesture recognizer factory for each gesture recognizer type.
'package:flutter/src/rendering/platform_view.dart':
Failed assertion: line 292 pos 5: '_factoriesTypeSet(gestureRecognizers).length == gestureRecognizers.length'

**Comment by danagbemava-nc** [comment]
Hi @walkerwg,

Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Thank you
