### ISSUE TITLE
[Fonts] Icon request: whatsapp

### ISSUE THREAD

**Issue by santosh9798** [flutter/flutter#99956]

**Comment by danagbemava-nc** [comment]
The whatsapp icon is already available on the latest version of stable(2.10.3). If you're not on the latest stable, I would advise that you upgrade. Closing as the icon is already available. Thank you

<img src="https://user-images.githubusercontent.com/88313112/157832848-9e12bfe0-caf6-4e8d-9ca2-802998913c1f.png"  width="300"/>
