### ISSUE TITLE
firebase_database should have an example app

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#9995]
The `firebase_database` plugin currently doesn't have an example app to verify functionality. Would be cool to add one.

/cc @collinjackson

**Comment by collinjackson** [comment]
Assigning to me, thanks!

**Comment by HansMuller** [comment]
A sample app that helped explain how to use the data (which would also be tested) might be a good idea: https://github.com/flutter/flutter/pull/9912

**Comment by kroikie** [comment]
@goderbauer

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1010. Any further collaboration will be done there.
