### ISSUE TITLE
Merge bot never landed a pull request

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#99965]
It seems like the bot stuck in landing the https://github.com/flutter/flutter/pull/95757.

The https://github.com/flutter/flutter/labels/waiting%20for%20tree%20to%20go%20green label was applied 20 days ago, and since then, the bot didn't say anything, until there appeared a merge conflict, after which it said it couldn't land it.

cc @godofredoc

**Comment by godofredoc** [comment]
This is a known issue where GraphQL is not scaling to our needs. We are working on a new version of the bot and it will be ready by mid April.

**Comment by godofredoc** [comment]
\cc @keyonghan @CaseyHillers

**Comment by CaseyHillers** [comment]
Duplicate of https://github.com/flutter/flutter/issues/96836#issuecomment-1029251155
