### ISSUE TITLE
get expand child height

### ISSUE THREAD

**Issue by dikeboy** [flutter/flutter#99962]
` CustomPaint(painter: new SignaturePainter(pWidth,pHeight,model.posX,model.posY)),`

MyCustomPaint is a child of expand, how can't i get the current height of expand

**Comment by dikeboy** [comment]
1

**Comment by dikeboy** [comment]
1

**Comment by maheshmnj** [comment]
Hi @dikeboy, Thanks for filing the issue. You could get the dimensions of any widget post rendering with the help of a key.
Please see this StackOverflow thread https://stackoverflow.com/questions/49307677/how-to-get-height-of-a-widget

Closing as this is neither a bug nor a feature request.
