### ISSUE TITLE
Flutter web scroll problem inside iframe

### ISSUE THREAD

**Issue by gh-arman** [flutter/flutter#99964]
I have a flutter application which I deployed on a server. On a webpage, I embedded the flutter application Inside an Iframe.

**Problem**
When I scroll the page, After reaching the iframe, I cannot scroll any more. It seems Flutter application consumes scroll events and do not pass the events to the web page.
And I need user interaction with the iframe as well. I have multiple widget like carousel, Poll slide, Horizontal scrolling and vertical scrolling inside the iframe.
I have implemented one of my widget with jquery (not flutter) and it worked perfectly.
I researched more than 2 months about this issue, I found the work around for desktop :
s.addEventListener.apply(s,["wheel",q,r])
If I remove this line from main.dart.js, The scroll behavior fixes in desktop browsers But I still have problem in mobile browsers such as Safari.

Thank you in advance.

**Comment by maheshmnj** [comment]
see https://github.com/flutter/flutter/issues/86021#issuecomment-887912902

**Comment by danagbemava-nc** [comment]
Hi @gh-arman, does the comment in https://github.com/flutter/flutter/issues/86021#issuecomment-887912902 provide some more information?

**Comment by gh-arman** [comment]
Thank you for your reply.
I have checked that comment before, But It did not solve my issue.
As he said, It is browser limitation, So I will try the work around again, if I couldn't solve the problem I will open another issue.
