### ISSUE TITLE
Upgrade to Flutter 2.10.3 stable, webview page will cause page blinking when disposed on Android Device

### ISSUE THREAD

**Issue by daydreary** [flutter/flutter#99961]
## Steps to Reproduce
1.Open a page which can jump to a WebView page, load a url.
2.In the WebView page, jump to the 3rd page.
3.Click back twice fast.
***
You can see the demostration gif below. When I back to the initial page, something was blinking, that was the 3rd page.
## gif
![5E3F616D54ACF3FD73B047124C04D8EF](https://user-images.githubusercontent.com/8489471/157832546-9fe1c903-be49-442c-8655-fd9a40223430.gif)
***

The reproduce  chance is not 100%,  but at least 50% or even more.

webview_flutter is latest version 3.0.1
flutter version is latest stable channel verion 2.10.3

And the most important thing is, before i upgraded flutter, everything was fine. My flutter version was 2.5.3 before.
Android Device Only

***
<details>
<summary>flutter doctor -v</summary>
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.1 21C52 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 2.10.3 at /Users/caoxun/Applications/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (9 days ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/caoxun/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Connected device (2 available)
    • MIX 2 (mobile) • ed1066f1 • android-arm64  • Android 9 (API 28)
    • Chrome (web)   • chrome   • web-javascript • Google Chrome 99.0.4844.51
</details>
***

I wrote a demo project, it can also reproduce this problem. Apk file has uploaded.
demo link : https://github.com/daydreary/flutter_demo
<details>
<summary>main page's coding</summary>
import 'package:flutter/material.dart';
import 'package:webview_test/web_page.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'Click Button to jump to WebView',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: jump,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }

  void jump() {
    Navigator.push(context,
        MaterialPageRoute(builder: (context) => const WebPage()));
  }
}

</details>

<details>
<summary>webview page's coding</summary>
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';
import 'package:webview_test/test_page.dart';

class WebPage extends StatefulWidget {
  const WebPage({Key? key}) : super(key: key);

  @override
  _WebPageState createState() => _WebPageState();
}

class _WebPageState extends State<WebPage> {

  final String url = "https://h5-ol.sns.sohu.com/hy-moyukik-h5/topic/detail/1502089429110525977";

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Webview Test"),
      ),
      body: WebView(
        onWebViewCreated: (controller) async {
          controller.loadUrl(url);
        },
        javascriptMode: JavascriptMode.unrestricted,
        // initialUrl: url,
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: jump,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }

  void jump() {
    Navigator.push(context,
        MaterialPageRoute(builder: (context) => const TestPage()));
  }
}

</details>

<details>
<summary>3rd page's coding</summary>
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

class TestPage extends StatefulWidget {
  const TestPage({Key? key}) : super(key: key);

  @override
  _TestPageState createState() => _TestPageState();
}

class _TestPageState extends State<TestPage> {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text("Webview Test"),),
      body: Container(
        color: Colors.redAccent,
        child: Center(
          child: Text("Hello World", style: TextStyle(fontSize: 30, fontWeight: FontWeight.bold, color: Colors.white),),
        ),
      )
    );
  }
}

</details>

how to use this demo:
1. Run it on an Android Device.
2. Click the floatingActionButton twice. 
3. Click back twice fast
4. Maybe you can see the problem happened.
5. If step 4 not happened, try it again.

**Comment by darshankawar** [comment]
@daydreary 
There's similar open [issue](https://github.com/flutter/flutter/issues/95545) describing your case, so please follow-up in it for further updates.
Closing this as a duplicate.
