### ISSUE TITLE
[Windows] Left arrow/Right arrow keys detected when mousing left/right in touch pad of RawKeyboardListener

### ISSUE THREAD

**Issue by dillibabu1802** [flutter/flutter#99960]
I am upgrading my plugin to provide Windows support. We have used RawKeyboardListener to deduct left and right arrow keys. But, while moving the hands in touch pad, left and right arrow are deducted which doesn't occur in Flutter web and macos.

## Steps to Reproduce

**Expected results:** As well, flutter web and macos - arrow left and right key should not be deducted.

https://user-images.githubusercontent.com/93312410/157830970-714c9d44-2570-4551-bbf7-9b3b0ead8bea.mp4

**Actual results:** Left and right arrow logical key are deducted. 

https://user-images.githubusercontent.com/93312410/157830947-acd03eeb-9caa-4bf6-b8cd-d24d58ad703d.mp4

<details>
<summary>

```dart
class _MyHomePageState extends State<MyHomePage> {
  /// focus node of pdf page view.
  FocusNode focusNode = FocusNode();
  String action = 'No key detected';
  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: RawKeyboardListener(
      focusNode: focusNode,
    onKey: (RawKeyEvent event) {
        setState(() {
          action = event.logicalKey.toString();
        });
    },
        child: Center(
          // Center is a layout widget. It takes a single child and positions it
          // in the middle of the parent.
          child: Container(
            width: 500,
            height: 500,
            color: Colors.blue,
            child: Text("Move in touch pad, detected key in rawkeyboardlistener " + action.toString()),
            )
          ),
        )
    );
  }
}
```
</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.19042.1526], locale en-US)
    • Flutter version 2.10.3 at C:\f\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (9 days ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\DilliBabuN\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Professional 2022 17.0.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Professional
    • Visual Studio Professional 2022 version 17.0.32014.148
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code, 64-bit edition (version 1.64.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.34.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.1526]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 99.0.4844.51
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 99.0.1150.36

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
```

```
```

```
```

</details>

<!--
      Consider also attaching screenshots and/or videos to better
      illustrate the issue.

      You can upload them directly on GitHub.
      Beware that video file size is limited to 10MB.
--

>

**Comment by dillibabu1802** [comment]
Hi @maheshmnj 

Can you look into this ?

**Comment by dillibabu1802** [comment]
is this related to https://github.com/flutter/engine/pull/31594 ?

**Comment by maheshmnj** [comment]
Hi @dillibabu1802, Thanks for filing the issue.

> We have used RawKeyboardListener to deduct left and right arrow keys. But, while moving the hands in touchpad, left and right arrows are deducted which doesn't occur in Flutter web and macOS.

If I am understanding it right you were able to trigger right/left arrow keys using the trackpad, is that correct? if so I did try tapping and tried out few gestures on the track pad with your code sample but the arrow key click events were not detected.

https://user-images.githubusercontent.com/31410839/157858828-3b4f5217-5bd8-4375-87f8-d757aec85321.mp4


Please share your output of `flutter doctor -v` and the exact steps to reproduce the issue.

<details>
<summary>flutter doctor -v (windows)</summary>

```
[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.19044.1526], locale en-US)
    • Flutter version 2.10.3 at C:\flutter_sdk\stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (14 hours ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\mahesh\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.64.2)
    • VS Code at C:\Users\mahesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.36.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1526]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 98.0.4758.102
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 98.0.1108.56

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by dillibabu1802** [comment]
Hi @maheshmnj ,

No. In web, it is working properly. Issue is in Windows, please move the trackpad in windows target. Like this.

https://user-images.githubusercontent.com/93312410/157860655-b44f5aac-1631-41d1-b8be-8acbdabafd92.mp4

Actually, I am trying to capture the pointer move gesture in Listener. Listener's  pointer gesture weren't working in Windows and found it - https://github.com/flutter/engine/pull/31594 

Regards,
Dilli babu.

logs:

[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.19042.1526], locale en-US)
• Flutter version 2.10.3 at C:\f\flutter
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision https://github.com/flutter/flutter/commit/7e9793dee1b85a243edd0e06cb1658e98b077561 (9 days ago), 2022-03-02 11:23:12 -0600
• Engine revision bd539267b4
• Dart version 2.16.1
• DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
• Android SDK at C:\Users\DilliBabuN\AppData\Local\Android\sdk
X cmdline-tools component is missing
Run path/to/sdkmanager --install "cmdline-tools;latest"
See https://developer.android.com/studio/command-line for more details.
X Android license status unknown.
Run flutter doctor --android-licenses to accept the SDK licenses.
See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
• Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Professional 2022 17.0.4)
• Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Professional
• Visual Studio Professional 2022 version 17.0.32014.148
• Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.2)
• Android Studio at C:\Program Files\Android\Android Studio
• Flutter plugin can be installed from:
https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
https://plugins.jetbrains.com/plugin/6351-dart
• Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code, 64-bit edition (version 1.64.0)
• VS Code at C:\Program Files\Microsoft VS Code
• Flutter extension version 3.34.0

[√] Connected device (3 available)
• Windows (desktop) • windows • windows-x64 • Microsoft Windows [Version 10.0.19042.1526]
• Chrome (web) • chrome • web-javascript • Google Chrome 99.0.4844.51
• Edge (web) • edge • web-javascript • Microsoft Edge 99.0.1150.36

[√] HTTP Host Availability
• All required HTTP hosts are available

! Doctor found issues in 1 category.

**Comment by dillibabu1802** [comment]
Please try two finger swipe in touch pad

**Comment by maheshmnj** [comment]
I did verify on windows desktop too, with two-finger horizontal and vertical swipe. But I don't see any key events triggering. Does this happen only on Windows Desktop?

**Comment by dillibabu1802** [comment]
Hi @maheshmnj 

It occurs only on Windows Desktop.

**Comment by maheshmnj** [comment]
Thanks for the info @dillibabu1802, Even my colleague was not able to reproduce the issue. I wonder if this is reproducible with other native apps too?
Could you please try the following

1. create a new flutter app
2. add a textfield in column
3. run the windows Desktop app
4. enter some text e.g "hello"
5. move cursor in center manually
6. perform gesture on trackpad and see if the cursor position changes
7. if the cursor moves in step 6 then run a native windows app and check if step 6 is reproducible

**Comment by moffatman** [comment]
I didn't try it, but I assume the issue is due to trackpad driver (probably Synaptics). On new trackpads this shouldn't happen but older laptops will send arrow key events when swiping left and right on trackpad.
