### ISSUE TITLE
[iOS][add2app] profile and release builds not working

### ISSUE THREAD

**Issue by ljmatan** [flutter/flutter#99967]
Testing on an actual device, everything works fine with debug builds, while with the profile and release builds I'm getting the below logs and an empty view controller.

[Logs.txt](https://github.com/flutter/flutter/files/8231128/Logs.txt)

Had a similar issue the other day but that was fixed via `flutter upgrade`. Possibly related? https://github.com/flutter/flutter/issues/91841

Flutter doctor: 

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 2.11.0-0.0.pre.869, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.65.1)
[✓] Connected device (4 available)
    ! Device 52007e785ffc85c7 is not authorized.
      You might need to check your device for an authorization dialog.
[✓] HTTP Host Availability

• No issues found!
```

**Comment by danagbemava-nc** [comment]
Hi @ljmatan, please provide a complete minimal reproducible code sample so that we may verify this. 

Thank you

**Comment by ljmatan** [comment]
Thanks, that actually helped me troubleshoot the issue - I had an expanded widget where I wasn't supposed to. 

Why it works in debug? Who knows.
