### ISSUE TITLE
☂️  Missing Material Icons

### ISSUE THREAD

**Issue by Ilgarmississippi** [flutter/flutter#99973]
This issue tracks missing Material icons.

If you were linked here from the Google Fonts website, please check a few things:

* Is the icon actually available on the stable channel? https://api.flutter.dev/flutter/material/Icons-class.html
* Is the icon actually available on the master channel? https://master-api.flutter.dev/flutter/material/Icons-class.html
   * it should be available in the next stable release
* The icon might be added in an open PR or recently merged PR
* Are you in fact looking at Material Symbols? For more, follow https://github.com/flutter/flutter/issues/102560
   ![image](https://user-images.githubusercontent.com/6655696/193220600-4b5dee58-44f0-4fc2-97c7-770329e1513d.png)

If no to all of the above, please leave a comment with the icon name

**Comment by guidezpl** [comment]
@danagbemava-nc I'll be updating fonts.google.com to point to this issue instead, to avoid churn with issue creation. In the meantime, please continue to close and point to this issue. I also have a pending PR https://github.com/flutter/flutter/pull/100885

**Comment by danagbemava-nc** [comment]
- signal_wifi_1_bar
- signal_wifi_2_bar
- signal_wifi_3_bar

**Comment by guidezpl** [comment]
signal_wifi_1_bar, signal_wifi_1_bar, and signal_wifi_1_bar are not available on fonts.google.com/icons. However, the "network wifi" icons are

**Comment by cgutierr-zgz** [comment]
`download` and `file_download` are out of date

`file_download_outlined` is the only one up to date

**Comment by guidezpl** [comment]
I think you might be looking at Material Symbols rather than Material Icons. See https://github.com/flutter/flutter/issues/102560 for more on that.

**Comment by m-paunovic-vegait** [comment]
`ray-start-vertex-end` seems to be missing, with `commit` being a close-but-not-quite substitute.

**Comment by solshuffle** [comment]
`contact_emergency` icon is missing

**Comment by guidezpl** [comment]
> Is the icon actually available on the master channel? https://master-api.flutter.dev/flutter/material/Icons-class.html
> it should be available in the next stable release

https://master-api.flutter.dev/flutter/material/Icons/contact_emergency-constant.html

**Comment by tmpfs** [comment]
Please can we add `settings_account_box`, `database` and `table`.

If I may ask how does this process work, do icons need to be added individually or is this something that could be automated by running a script that syncs Flutter with the current set of Material Icons?

**Comment by nagringapp** [comment]
Missing Icon: Voting Chip

**Comment by nagringapp** [comment]
Hi Team, do we need to add all the missing icons? 
Material has just launched an update on Material 3, and I didn't notice much updates on the icons - aligned with the Material Icons.
