### ISSUE TITLE
[flutter_localizations] can we update flutter_localizations to use path: 1.8.1 (the newest version)

### ISSUE THREAD

**Issue by mariopepe** [flutter/flutter#99985]
This is the error I get while depending on both the newest version of path and flutter_localizations

```
Because [YOUR_PROJECT] depends on flutter_localizations from sdk which depends on path 1.8.0, path 1.8.0 is required.
So, because [YOUR_PROJECT] depends on path ^1.8.1, version solving failed.
pub get failed (1; So, because [YOUR_PROJECT] depends on path ^1.8.1, version solving failed.)
```

Thanks!

**Comment by mgesmundo** [comment]
Do you tried to override the dependency in your pubspec.yaml file?

dependency_overrides:
  path: ^1.8.1

**Comment by stuartmorgan** [comment]
This has [already been done](https://github.com/flutter/flutter/blob/master/packages/flutter_localizations/pubspec.yaml#L18).

In general, it's not necessary to file issues like this; dependencies are updated pretty regularly.
