### ISSUE TITLE
Android Studio, iOS won't compile due to Android Embedding v2

### ISSUE THREAD

**Issue by Polemics** [flutter/flutter#99989]
Apologies, I searched all over but couldn't find a way to work around / fix this.

<img width="1645" alt="Screen Shot 2022-03-11 at 11 35 22 AM" src="https://user-images.githubusercontent.com/9342912/157930993-cb9967d7-d70d-4ed1-9c85-8c992b7d619e.png">

I only work the iOS side of this project so I'm not concerned with Android v2 embedding unless it is mandatory for iOS (flutter) to work.  A solution that mutes this works.  

I did try to migrate this using the steps provided at https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects, however these instructions are for MainActivity.java.  The Android files I have are Kotlin based.  I don't have a MainActivity.java file at all.

Thanks for the help! I'm easily 8 hours down the drain.

**Comment by darshankawar** [comment]
@Polemics 
Can you provide `flutter doctor -v`. I have seen a similar issue reported for iOS but can't seem to find it but it seemed to have been fixed already but I'll wait for your `flutter version` on which you are seeing this.

**Comment by johnwargo** [comment]
I'm having the same issue (except that I am using my Android project). I have the same conditions, no MainActivity.java and everything in my project looks like its setup for embedding v2.

my `AndroidManifest.xml` even says its embedding v2:

```xml
<meta-data
            android:name="flutterEmbedding"
            android:value="2" />
```

Here's my flutter doctor output:

```
[✓] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.19044.1586], locale en-US)
    • Flutter version 2.10.3 at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (3 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\john\AppData\Local\Android\Sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = C:\Users\john\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32228.430
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[✓] VS Code, 64-bit edition (version 1.65.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1586]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 99.0.4844.74
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 99.0.1150.39

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by Polemics** [comment]
Hello all, sorry I didn't see the original ask for Flutter doctor -v until Johnwargo's post here.  Anyway My problem is solved.  I ended up doing the Android conversion as specified here https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects.  Migrating the Android side...fixed the iOS side.  The process wasn't too bad.
