### ISSUE TITLE
`flutter test` yielding wrong async behavior

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#9998]
## Steps to Reproduce

* Create a test to match https://gist.github.com/tvolkert/48ef8cde13fcf50511a390abe613836d
* Run the test via `dart -c bug_test.dart`
* Run the test via `flutter_tester --non-interactive bug_test.dart`

## Expected behavior

Both methods of invoking the script should print out `1, 2, 3, 4` (in order)

## Actual behavior

When run via `flutter_tester`, it prints out `1, 2, 4, 3`

**Comment by tvolkert** [comment]
@Hixie

**Comment by Hixie** [comment]
Does it still reproduce if you replace the `Future.delayed` with a `new Timer` and the `Future.value` with ` scheduleMicrotask`?

**Comment by tvolkert** [comment]
### Reduced test case:

```
import 'dart:async';

Future<Null> main() async {
  print(1);
  await new Future.delayed(Duration.ZERO);

  scheduleMicrotask(() {
    print(3);
  });

  print(2);
  await new Future.delayed(Duration.ZERO);

  print(4);
}
```

### Output in standalone embedder

```
$ dart -c test/bug_test.dart 
1
2
3
4
```

### Output in flutter_tester

```
$ flutter_tester --non-interactive test/bug_test.dart 
1
2
4
3
```

**Comment by tvolkert** [comment]
@jason-simmons

**Comment by tvolkert** [comment]
`4` should never be allowed to print before `3`, because according to the docs on `Future.delayed()`, "If the duration is 0 or less, it completes no sooner than in the next event-loop iteration" -- which is specifically after the microtask queue has cleared.

**Comment by tvolkert** [comment]
Two other interesting bits here that may or may not aid in the investigation:

### Still happens if we don't use scheduleMicortask()

The following still exhibits the disparity in output between the CLI and `flutter_tester`:

```
Future<Null> main() async {
  print(1);
  await new Future.delayed(Duration.ZERO);

  new Future<Null>.value().then((_) {
    print(3);
  });

  print(2);
  await new Future.delayed(Duration.ZERO);

  print(4);
}
```

### Is fixed if we remove the first await

If we comment out the first await (as we do below), then both Dart embedders correctly print the numbers in order!

```
Future<Null> main() async {
  print(1);
  //await new Future.delayed(Duration.ZERO);

  scheduleMicrotask(() {
    print(3);
  });

  print(2);
  await new Future.delayed(Duration.ZERO);

  print(4);
}
```

**Comment by jason-simmons** [comment]
One thing I noticed is that Tonic's DartMessageHandler::OnHandleMessage is calling Dart_HandleMessages, which processes all pending messages for the isolate.  This means that multiple messages might be handled without any drain of the microtask queue between messages.

I was able to get flutter_tester to output the numbers in order for the original test program by changing the Dart_HandleMessages() to a Dart_HandleMessage() call that processes a single message.

@a-siva and the Dart team: what are the expectations for how embedders should schedule message handling versus microtask execution?

**Comment by a-siva** [comment]
Chatted offline with Jason, looks like we need to call the microTask queue handler callback if one is registered after processing each message.

**Comment by tvolkert** [comment]
@jason-simmons it sounds like we have the right answer as to how to solve this based on the last comment from @a-siva - can you take a look?

Alternatively, @rmacnak-google are you game to take a look?

**Comment by tvolkert** [comment]
@rmacnak-google ftr, can you point to the Tonic change that fixed this?

**Comment by tvolkert** [comment]
https://fuchsia-review.googlesource.com/c/topaz/+/83861

**Comment by cbracken** [comment]
Added a test in #13073 to ensure this doesn't regress.
