### ISSUE TITLE
[Fonts] Icon request: shopping_cart_checkout

### ISSUE THREAD

**Issue by karimhassoub** [flutter/flutter#99991]

**Comment by danagbemava-nc** [comment]
The `shopping_cart_checkout` icon is already available in the latest version of flutter (stable 2.10.3). The fonts site just hasn't been updated yet. 

Closing as the icon already exists.

<img src="https://user-images.githubusercontent.com/88313112/158125873-0aa517fa-5d9d-4a6c-87ae-0260910cc407.png" width="300"/>
