### ISSUE TITLE
[Windows] Reference Flutter library instead of generating code for Windows platform

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/flutter#99999]
## Use case

Hi thanks for the library! Currently, the `windows` target includes a lot of generated files, such as:

* flutter/generated_plugins.cmake
* flutter/generated_plugin_registrant.h
* flutter/generated_plugin_registrant.cc
* flutter/CMakeLists.txt
* runner/utils.h
* runner/utils.cpp
* runner/win32_window.h
* runner/win32_window.cpp

Seems that they are all fixed and is usually not modified by Flutter programmers. Especially, the `generated_plugins` has comments saying "do not modify by hand", and the `utils` may be moved into some flutter header files.

Therefore, IMHO we can move much of those code into the Flutter framework, instead of duplicating them in each of the Flutter apps.

By doing so, not only are we more DRY, but it is also easier to upgrade Flutter logic related to those generated code in the future.

## Proposal

See above

**Comment by maheshmnj** [comment]
Hi @fzyzcjy, Thanks for filing the issue. Leaving this issue open for further insights from the team.

**Comment by fzyzcjy** [comment]
@maheshmnj Looking forward to further insights :)

**Comment by christopherfujino** [comment]
These files are a part of the application. Even if they are "usually not modified by Flutter programmers" (which I am not sure is true), users need the ability to. For example, if a user wants to link a C++ source file they have authored, they would need to edit their CMakeLists.txt file.

In addition, while users are not intended to manually hand-edited by users, it IS edited by the Flutter tooling and is application specific.

In addition, they need to be version controlled with the application. Otherwise, if these files were read from the Flutter SDK, using a different version of the Flutter SDK may lead to build failures.

**Comment by christopherfujino** [comment]
Thank you for contributing; however I am closing this proposal as something we will not be able to implement.

**Comment by fzyzcjy** [comment]
@christopherfujino Hi thanks for the reply! I am talking about making it DRY, instead of completely remove those files. As a simple example, `utils` may be (partially) moved into some flutter files. The user can still freely modify/add/delete anything since they can just write down their own code.

**Comment by christopherfujino** [comment]
> @christopherfujino Hi thanks for the reply! I am talking about making it DRY, instead of completely remove those files. As a simple example, `utils` may be (partially) moved into some flutter files. The user can still freely modify/add/delete anything since they can just write down their own code.

How would you partially move it? Using patch and diff? Would Flutter builds then need to apply those patches before building? There are some workflows that involve building apps without the Flutter tool; how would those native build systems know how to apply the patches?

**Comment by fzyzcjy** [comment]
Firstly, without considering compatibility with current 2.10, it may not be hard: The most naive method, as an example, may be just remove `utils.h` and `utils.cc`, and move them into `flutter/flutter.h` (I know that is not good, just an example). Then as long as users can include `flutter.h` (they should - otherwise program cannot compile), the utils are there.

Similarly, CMakeLists.txt can include other CMakeLists.txt as well. Just use the way how we include Flutter's CMAkeLists.txt is enough.
