### ISSUE TITLE
The application's Info.plist does not contain a valid CFBundleVersion.

### ISSUE THREAD

**Issue by ahmedsaheed** [flutter/flutter#99995]
Hello there, 

This is my first time opening an issue because I've exhausted all the available solutions without any improvement.
i have been through all step from [here](https://github.com/flutter/flutter/issues/40623) without any luck

So, I just added stripe to my application, after several successful tests my application stopped installing. Below is the error printed to console.

`Launching lib[/main.dart]() on iPhone 13 in debug mode...
lib/main.dart:1
Xcode build done.                                           43.3s
Unable to install [/Users/ahmedsaheed/Desktop/Desktop/sdg_app2/sdg_app2/build/ios/iphonesimulator/Runner.app]() on 2799BD3F-275C-4DC2-A158-74381D86EBC4. This is sometimes caused by a malformed plist file:
ProcessException: Process exited abnormally:
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The application's Info.plist does not contain a valid CFBundleVersion.
Ensure your bundle contains a valid CFBundleVersion.
  Command: xcrun simctl install 2799BD3F-275C-4DC2-A158-74381D86EBC4 [/Users/ahmedsaheed/Desktop/Desktop/sdg_app2/sdg_app2/build/ios/iphonesimulator/Runner.app]()
Error launching application on iPhone 13.
Exited (sigterm)`

This is my info.plist
![Screenshot 2022-03-12 at 00 51 45](https://user-images.githubusercontent.com/87912847/157996529-cadbf802-f91c-4cec-9647-aa891ae9be3e.png)

I have tried using `flutter create -i swift ` to get a new plist. But without any success.

Please can anyone help me out? Thank you.

**Comment by maendamedia** [comment]
Did you fixed this? And if yes, how? I do have the same issue :(

**Comment by ahmedsaheed** [comment]
I fixed it,
First, I deleted my whole IOS folder (you could just keep it somewhere outside root for reference purposes), 
then on root, I ran `flutter create .` which creates any missing file. 
After that I got a new IOS folder, I manually added some details that were in my previous info.plist to this new info.plist that was autogenerated. And that sorted it out.
